#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_AddPersonalTrustDBPages;
void *ptr_AddPersonalTrustDBPages = NULL;
extern void *ptr_CatalogCompactHashDatabase;
void *ptr_CatalogCompactHashDatabase = NULL;
extern void *ptr_CryptCATAdminAcquireContext;
void *ptr_CryptCATAdminAcquireContext = NULL;
extern void *ptr_CryptCATAdminAcquireContext2;
void *ptr_CryptCATAdminAcquireContext2 = NULL;
extern void *ptr_CryptCATAdminAddCatalog;
void *ptr_CryptCATAdminAddCatalog = NULL;
extern void *ptr_CryptCATAdminCalcHashFromFileHandle;
void *ptr_CryptCATAdminCalcHashFromFileHandle = NULL;
extern void *ptr_CryptCATAdminCalcHashFromFileHandle2;
void *ptr_CryptCATAdminCalcHashFromFileHandle2 = NULL;
extern void *ptr_CryptCATAdminEnumCatalogFromHash;
void *ptr_CryptCATAdminEnumCatalogFromHash = NULL;
extern void *ptr_CryptCATAdminPauseServiceForBackup;
void *ptr_CryptCATAdminPauseServiceForBackup = NULL;
extern void *ptr_CryptCATAdminReleaseCatalogContext;
void *ptr_CryptCATAdminReleaseCatalogContext = NULL;
extern void *ptr_CryptCATAdminReleaseContext;
void *ptr_CryptCATAdminReleaseContext = NULL;
extern void *ptr_CryptCATAdminRemoveCatalog;
void *ptr_CryptCATAdminRemoveCatalog = NULL;
extern void *ptr_CryptCATAdminResolveCatalogPath;
void *ptr_CryptCATAdminResolveCatalogPath = NULL;
extern void *ptr_CryptCATAllocSortedMemberInfo;
void *ptr_CryptCATAllocSortedMemberInfo = NULL;
extern void *ptr_CryptCATCDFClose;
void *ptr_CryptCATCDFClose = NULL;
extern void *ptr_CryptCATCDFEnumAttributes;
void *ptr_CryptCATCDFEnumAttributes = NULL;
extern void *ptr_CryptCATCDFEnumAttributesWithCDFTag;
void *ptr_CryptCATCDFEnumAttributesWithCDFTag = NULL;
extern void *ptr_CryptCATCDFEnumCatAttributes;
void *ptr_CryptCATCDFEnumCatAttributes = NULL;
extern void *ptr_CryptCATCDFEnumMembers;
void *ptr_CryptCATCDFEnumMembers = NULL;
extern void *ptr_CryptCATCDFEnumMembersByCDFTag;
void *ptr_CryptCATCDFEnumMembersByCDFTag = NULL;
extern void *ptr_CryptCATCDFEnumMembersByCDFTagEx;
void *ptr_CryptCATCDFEnumMembersByCDFTagEx = NULL;
extern void *ptr_CryptCATCDFOpen;
void *ptr_CryptCATCDFOpen = NULL;
extern void *ptr_CryptCATCatalogInfoFromContext;
void *ptr_CryptCATCatalogInfoFromContext = NULL;
extern void *ptr_CryptCATClose;
void *ptr_CryptCATClose = NULL;
extern void *ptr_CryptCATEnumerateAttr;
void *ptr_CryptCATEnumerateAttr = NULL;
extern void *ptr_CryptCATEnumerateCatAttr;
void *ptr_CryptCATEnumerateCatAttr = NULL;
extern void *ptr_CryptCATEnumerateMember;
void *ptr_CryptCATEnumerateMember = NULL;
extern void *ptr_CryptCATFreeSortedMemberInfo;
void *ptr_CryptCATFreeSortedMemberInfo = NULL;
extern void *ptr_CryptCATGetAttrInfo;
void *ptr_CryptCATGetAttrInfo = NULL;
extern void *ptr_CryptCATGetCatAttrInfo;
void *ptr_CryptCATGetCatAttrInfo = NULL;
extern void *ptr_CryptCATGetMemberInfo;
void *ptr_CryptCATGetMemberInfo = NULL;
extern void *ptr_CryptCATHandleFromStore;
void *ptr_CryptCATHandleFromStore = NULL;
extern void *ptr_CryptCATOpen;
void *ptr_CryptCATOpen = NULL;
extern void *ptr_CryptCATPersistStore;
void *ptr_CryptCATPersistStore = NULL;
extern void *ptr_CryptCATPutAttrInfo;
void *ptr_CryptCATPutAttrInfo = NULL;
extern void *ptr_CryptCATPutCatAttrInfo;
void *ptr_CryptCATPutCatAttrInfo = NULL;
extern void *ptr_CryptCATPutMemberInfo;
void *ptr_CryptCATPutMemberInfo = NULL;
extern void *ptr_CryptCATStoreFromHandle;
void *ptr_CryptCATStoreFromHandle = NULL;
extern void *ptr_CryptCATVerifyMember;
void *ptr_CryptCATVerifyMember = NULL;
extern void *ptr_CryptSIPCreateIndirectData;
void *ptr_CryptSIPCreateIndirectData = NULL;
extern void *ptr_CryptSIPGetInfo;
void *ptr_CryptSIPGetInfo = NULL;
extern void *ptr_CryptSIPGetRegWorkingFlags;
void *ptr_CryptSIPGetRegWorkingFlags = NULL;
extern void *ptr_CryptSIPGetSignedDataMsg;
void *ptr_CryptSIPGetSignedDataMsg = NULL;
extern void *ptr_CryptSIPPutSignedDataMsg;
void *ptr_CryptSIPPutSignedDataMsg = NULL;
extern void *ptr_CryptSIPRemoveSignedDataMsg;
void *ptr_CryptSIPRemoveSignedDataMsg = NULL;
extern void *ptr_CryptSIPVerifyIndirectData;
void *ptr_CryptSIPVerifyIndirectData = NULL;
extern void *ptr_DllRegisterServer;
void *ptr_DllRegisterServer = NULL;
extern void *ptr_DllUnregisterServer;
void *ptr_DllUnregisterServer = NULL;
extern void *ptr_DriverCleanupPolicy;
void *ptr_DriverCleanupPolicy = NULL;
extern void *ptr_DriverFinalPolicy;
void *ptr_DriverFinalPolicy = NULL;
extern void *ptr_DriverInitializePolicy;
void *ptr_DriverInitializePolicy = NULL;
extern void *ptr_FindCertsByIssuer;
void *ptr_FindCertsByIssuer = NULL;
extern void *ptr_GenericChainCertificateTrust;
void *ptr_GenericChainCertificateTrust = NULL;
extern void *ptr_GenericChainFinalProv;
void *ptr_GenericChainFinalProv = NULL;
extern void *ptr_HTTPSCertificateTrust;
void *ptr_HTTPSCertificateTrust = NULL;
extern void *ptr_HTTPSFinalProv;
void *ptr_HTTPSFinalProv = NULL;
extern void *ptr_IsCatalogFile;
void *ptr_IsCatalogFile = NULL;
extern void *ptr_MsCatConstructHashTag;
void *ptr_MsCatConstructHashTag = NULL;
extern void *ptr_MsCatFreeHashTag;
void *ptr_MsCatFreeHashTag = NULL;
extern void *ptr_OfficeCleanupPolicy;
void *ptr_OfficeCleanupPolicy = NULL;
extern void *ptr_OfficeInitializePolicy;
void *ptr_OfficeInitializePolicy = NULL;
extern void *ptr_OpenPersonalTrustDBDialog;
void *ptr_OpenPersonalTrustDBDialog = NULL;
extern void *ptr_OpenPersonalTrustDBDialogEx;
void *ptr_OpenPersonalTrustDBDialogEx = NULL;
extern void *ptr_SoftpubAuthenticode;
void *ptr_SoftpubAuthenticode = NULL;
extern void *ptr_SoftpubCheckCert;
void *ptr_SoftpubCheckCert = NULL;
extern void *ptr_SoftpubCleanup;
void *ptr_SoftpubCleanup = NULL;
extern void *ptr_SoftpubDefCertInit;
void *ptr_SoftpubDefCertInit = NULL;
extern void *ptr_SoftpubDllRegisterServer;
void *ptr_SoftpubDllRegisterServer = NULL;
extern void *ptr_SoftpubDllUnregisterServer;
void *ptr_SoftpubDllUnregisterServer = NULL;
extern void *ptr_SoftpubDumpStructure;
void *ptr_SoftpubDumpStructure = NULL;
extern void *ptr_SoftpubFreeDefUsageCallData;
void *ptr_SoftpubFreeDefUsageCallData = NULL;
extern void *ptr_SoftpubInitialize;
void *ptr_SoftpubInitialize = NULL;
extern void *ptr_SoftpubLoadDefUsageCallData;
void *ptr_SoftpubLoadDefUsageCallData = NULL;
extern void *ptr_SoftpubLoadMessage;
void *ptr_SoftpubLoadMessage = NULL;
extern void *ptr_SoftpubLoadSignature;
void *ptr_SoftpubLoadSignature = NULL;
extern void *ptr_TrustDecode;
void *ptr_TrustDecode = NULL;
extern void *ptr_TrustFindIssuerCertificate;
void *ptr_TrustFindIssuerCertificate = NULL;
extern void *ptr_TrustFreeDecode;
void *ptr_TrustFreeDecode = NULL;
extern void *ptr_TrustIsCertificateSelfSigned;
void *ptr_TrustIsCertificateSelfSigned = NULL;
extern void *ptr_TrustOpenStores;
void *ptr_TrustOpenStores = NULL;
extern void *ptr_WTHelperCertCheckValidSignature;
void *ptr_WTHelperCertCheckValidSignature = NULL;
extern void *ptr_WTHelperCertFindIssuerCertificate;
void *ptr_WTHelperCertFindIssuerCertificate = NULL;
extern void *ptr_WTHelperCertIsSelfSigned;
void *ptr_WTHelperCertIsSelfSigned = NULL;
extern void *ptr_WTHelperCheckCertUsage;
void *ptr_WTHelperCheckCertUsage = NULL;
extern void *ptr_WTHelperGetAgencyInfo;
void *ptr_WTHelperGetAgencyInfo = NULL;
extern void *ptr_WTHelperGetFileHandle;
void *ptr_WTHelperGetFileHandle = NULL;
extern void *ptr_WTHelperGetFileHash;
void *ptr_WTHelperGetFileHash = NULL;
extern void *ptr_WTHelperGetFileName;
void *ptr_WTHelperGetFileName = NULL;
extern void *ptr_WTHelperGetKnownUsages;
void *ptr_WTHelperGetKnownUsages = NULL;
extern void *ptr_WTHelperGetProvCertFromChain;
void *ptr_WTHelperGetProvCertFromChain = NULL;
extern void *ptr_WTHelperGetProvPrivateDataFromChain;
void *ptr_WTHelperGetProvPrivateDataFromChain = NULL;
extern void *ptr_WTHelperGetProvSignerFromChain;
void *ptr_WTHelperGetProvSignerFromChain = NULL;
extern void *ptr_WTHelperIsInRootStore;
void *ptr_WTHelperIsInRootStore = NULL;
extern void *ptr_WTHelperOpenKnownStores;
void *ptr_WTHelperOpenKnownStores = NULL;
extern void *ptr_WTHelperProvDataFromStateData;
void *ptr_WTHelperProvDataFromStateData = NULL;
extern void *ptr_WVTAsn1CatMemberInfo2Decode;
void *ptr_WVTAsn1CatMemberInfo2Decode = NULL;
extern void *ptr_WVTAsn1CatMemberInfo2Encode;
void *ptr_WVTAsn1CatMemberInfo2Encode = NULL;
extern void *ptr_WVTAsn1CatMemberInfoDecode;
void *ptr_WVTAsn1CatMemberInfoDecode = NULL;
extern void *ptr_WVTAsn1CatMemberInfoEncode;
void *ptr_WVTAsn1CatMemberInfoEncode = NULL;
extern void *ptr_WVTAsn1CatNameValueDecode;
void *ptr_WVTAsn1CatNameValueDecode = NULL;
extern void *ptr_WVTAsn1CatNameValueEncode;
void *ptr_WVTAsn1CatNameValueEncode = NULL;
extern void *ptr_WVTAsn1SpcFinancialCriteriaInfoDecode;
void *ptr_WVTAsn1SpcFinancialCriteriaInfoDecode = NULL;
extern void *ptr_WVTAsn1SpcFinancialCriteriaInfoEncode;
void *ptr_WVTAsn1SpcFinancialCriteriaInfoEncode = NULL;
extern void *ptr_WVTAsn1SpcIndirectDataContentDecode;
void *ptr_WVTAsn1SpcIndirectDataContentDecode = NULL;
extern void *ptr_WVTAsn1SpcIndirectDataContentEncode;
void *ptr_WVTAsn1SpcIndirectDataContentEncode = NULL;
extern void *ptr_WVTAsn1SpcLinkDecode;
void *ptr_WVTAsn1SpcLinkDecode = NULL;
extern void *ptr_WVTAsn1SpcLinkEncode;
void *ptr_WVTAsn1SpcLinkEncode = NULL;
extern void *ptr_WVTAsn1SpcMinimalCriteriaInfoDecode;
void *ptr_WVTAsn1SpcMinimalCriteriaInfoDecode = NULL;
extern void *ptr_WVTAsn1SpcMinimalCriteriaInfoEncode;
void *ptr_WVTAsn1SpcMinimalCriteriaInfoEncode = NULL;
extern void *ptr_WVTAsn1SpcPeImageDataDecode;
void *ptr_WVTAsn1SpcPeImageDataDecode = NULL;
extern void *ptr_WVTAsn1SpcPeImageDataEncode;
void *ptr_WVTAsn1SpcPeImageDataEncode = NULL;
extern void *ptr_WVTAsn1SpcSigInfoDecode;
void *ptr_WVTAsn1SpcSigInfoDecode = NULL;
extern void *ptr_WVTAsn1SpcSigInfoEncode;
void *ptr_WVTAsn1SpcSigInfoEncode = NULL;
extern void *ptr_WVTAsn1SpcSpAgencyInfoDecode;
void *ptr_WVTAsn1SpcSpAgencyInfoDecode = NULL;
extern void *ptr_WVTAsn1SpcSpAgencyInfoEncode;
void *ptr_WVTAsn1SpcSpAgencyInfoEncode = NULL;
extern void *ptr_WVTAsn1SpcSpOpusInfoDecode;
void *ptr_WVTAsn1SpcSpOpusInfoDecode = NULL;
extern void *ptr_WVTAsn1SpcSpOpusInfoEncode;
void *ptr_WVTAsn1SpcSpOpusInfoEncode = NULL;
extern void *ptr_WVTAsn1SpcStatementTypeDecode;
void *ptr_WVTAsn1SpcStatementTypeDecode = NULL;
extern void *ptr_WVTAsn1SpcStatementTypeEncode;
void *ptr_WVTAsn1SpcStatementTypeEncode = NULL;
extern void *ptr_WinVerifyTrust;
void *ptr_WinVerifyTrust = NULL;
extern void *ptr_WinVerifyTrustEx;
void *ptr_WinVerifyTrustEx = NULL;
extern void *ptr_WintrustAddActionID;
void *ptr_WintrustAddActionID = NULL;
extern void *ptr_WintrustAddDefaultForUsage;
void *ptr_WintrustAddDefaultForUsage = NULL;
extern void *ptr_WintrustCertificateTrust;
void *ptr_WintrustCertificateTrust = NULL;
extern void *ptr_WintrustGetDefaultForUsage;
void *ptr_WintrustGetDefaultForUsage = NULL;
extern void *ptr_WintrustGetRegPolicyFlags;
void *ptr_WintrustGetRegPolicyFlags = NULL;
extern void *ptr_WintrustLoadFunctionPointers;
void *ptr_WintrustLoadFunctionPointers = NULL;
extern void *ptr_WintrustRemoveActionID;
void *ptr_WintrustRemoveActionID = NULL;
extern void *ptr_WintrustSetDefaultIncludePEPageHashes;
void *ptr_WintrustSetDefaultIncludePEPageHashes = NULL;
extern void *ptr_WintrustSetRegPolicyFlags;
void *ptr_WintrustSetRegPolicyFlags = NULL;
extern void *ptr_mscat32DllRegisterServer;
void *ptr_mscat32DllRegisterServer = NULL;
extern void *ptr_mscat32DllUnregisterServer;
void *ptr_mscat32DllUnregisterServer = NULL;
extern void *ptr_mssip32DllRegisterServer;
void *ptr_mssip32DllRegisterServer = NULL;
extern void *ptr_mssip32DllUnregisterServer;
void *ptr_mssip32DllUnregisterServer = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\wintrust.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_AddPersonalTrustDBPages = (__vartype(ptr_AddPersonalTrustDBPages))GetProcAddress(hModule, "AddPersonalTrustDBPages");
   ptr_CatalogCompactHashDatabase = (__vartype(ptr_CatalogCompactHashDatabase))GetProcAddress(hModule, "CatalogCompactHashDatabase");
   ptr_CryptCATAdminAcquireContext = (__vartype(ptr_CryptCATAdminAcquireContext))GetProcAddress(hModule, "CryptCATAdminAcquireContext");
   ptr_CryptCATAdminAcquireContext2 = (__vartype(ptr_CryptCATAdminAcquireContext2))GetProcAddress(hModule, "CryptCATAdminAcquireContext2");
   ptr_CryptCATAdminAddCatalog = (__vartype(ptr_CryptCATAdminAddCatalog))GetProcAddress(hModule, "CryptCATAdminAddCatalog");
   ptr_CryptCATAdminCalcHashFromFileHandle = (__vartype(ptr_CryptCATAdminCalcHashFromFileHandle))GetProcAddress(hModule, "CryptCATAdminCalcHashFromFileHandle");
   ptr_CryptCATAdminCalcHashFromFileHandle2 = (__vartype(ptr_CryptCATAdminCalcHashFromFileHandle2))GetProcAddress(hModule, "CryptCATAdminCalcHashFromFileHandle2");
   ptr_CryptCATAdminEnumCatalogFromHash = (__vartype(ptr_CryptCATAdminEnumCatalogFromHash))GetProcAddress(hModule, "CryptCATAdminEnumCatalogFromHash");
   ptr_CryptCATAdminPauseServiceForBackup = (__vartype(ptr_CryptCATAdminPauseServiceForBackup))GetProcAddress(hModule, "CryptCATAdminPauseServiceForBackup");
   ptr_CryptCATAdminReleaseCatalogContext = (__vartype(ptr_CryptCATAdminReleaseCatalogContext))GetProcAddress(hModule, "CryptCATAdminReleaseCatalogContext");
   ptr_CryptCATAdminReleaseContext = (__vartype(ptr_CryptCATAdminReleaseContext))GetProcAddress(hModule, "CryptCATAdminReleaseContext");
   ptr_CryptCATAdminRemoveCatalog = (__vartype(ptr_CryptCATAdminRemoveCatalog))GetProcAddress(hModule, "CryptCATAdminRemoveCatalog");
   ptr_CryptCATAdminResolveCatalogPath = (__vartype(ptr_CryptCATAdminResolveCatalogPath))GetProcAddress(hModule, "CryptCATAdminResolveCatalogPath");
   ptr_CryptCATAllocSortedMemberInfo = (__vartype(ptr_CryptCATAllocSortedMemberInfo))GetProcAddress(hModule, "CryptCATAllocSortedMemberInfo");
   ptr_CryptCATCDFClose = (__vartype(ptr_CryptCATCDFClose))GetProcAddress(hModule, "CryptCATCDFClose");
   ptr_CryptCATCDFEnumAttributes = (__vartype(ptr_CryptCATCDFEnumAttributes))GetProcAddress(hModule, "CryptCATCDFEnumAttributes");
   ptr_CryptCATCDFEnumAttributesWithCDFTag = (__vartype(ptr_CryptCATCDFEnumAttributesWithCDFTag))GetProcAddress(hModule, "CryptCATCDFEnumAttributesWithCDFTag");
   ptr_CryptCATCDFEnumCatAttributes = (__vartype(ptr_CryptCATCDFEnumCatAttributes))GetProcAddress(hModule, "CryptCATCDFEnumCatAttributes");
   ptr_CryptCATCDFEnumMembers = (__vartype(ptr_CryptCATCDFEnumMembers))GetProcAddress(hModule, "CryptCATCDFEnumMembers");
   ptr_CryptCATCDFEnumMembersByCDFTag = (__vartype(ptr_CryptCATCDFEnumMembersByCDFTag))GetProcAddress(hModule, "CryptCATCDFEnumMembersByCDFTag");
   ptr_CryptCATCDFEnumMembersByCDFTagEx = (__vartype(ptr_CryptCATCDFEnumMembersByCDFTagEx))GetProcAddress(hModule, "CryptCATCDFEnumMembersByCDFTagEx");
   ptr_CryptCATCDFOpen = (__vartype(ptr_CryptCATCDFOpen))GetProcAddress(hModule, "CryptCATCDFOpen");
   ptr_CryptCATCatalogInfoFromContext = (__vartype(ptr_CryptCATCatalogInfoFromContext))GetProcAddress(hModule, "CryptCATCatalogInfoFromContext");
   ptr_CryptCATClose = (__vartype(ptr_CryptCATClose))GetProcAddress(hModule, "CryptCATClose");
   ptr_CryptCATEnumerateAttr = (__vartype(ptr_CryptCATEnumerateAttr))GetProcAddress(hModule, "CryptCATEnumerateAttr");
   ptr_CryptCATEnumerateCatAttr = (__vartype(ptr_CryptCATEnumerateCatAttr))GetProcAddress(hModule, "CryptCATEnumerateCatAttr");
   ptr_CryptCATEnumerateMember = (__vartype(ptr_CryptCATEnumerateMember))GetProcAddress(hModule, "CryptCATEnumerateMember");
   ptr_CryptCATFreeSortedMemberInfo = (__vartype(ptr_CryptCATFreeSortedMemberInfo))GetProcAddress(hModule, "CryptCATFreeSortedMemberInfo");
   ptr_CryptCATGetAttrInfo = (__vartype(ptr_CryptCATGetAttrInfo))GetProcAddress(hModule, "CryptCATGetAttrInfo");
   ptr_CryptCATGetCatAttrInfo = (__vartype(ptr_CryptCATGetCatAttrInfo))GetProcAddress(hModule, "CryptCATGetCatAttrInfo");
   ptr_CryptCATGetMemberInfo = (__vartype(ptr_CryptCATGetMemberInfo))GetProcAddress(hModule, "CryptCATGetMemberInfo");
   ptr_CryptCATHandleFromStore = (__vartype(ptr_CryptCATHandleFromStore))GetProcAddress(hModule, "CryptCATHandleFromStore");
   ptr_CryptCATOpen = (__vartype(ptr_CryptCATOpen))GetProcAddress(hModule, "CryptCATOpen");
   ptr_CryptCATPersistStore = (__vartype(ptr_CryptCATPersistStore))GetProcAddress(hModule, "CryptCATPersistStore");
   ptr_CryptCATPutAttrInfo = (__vartype(ptr_CryptCATPutAttrInfo))GetProcAddress(hModule, "CryptCATPutAttrInfo");
   ptr_CryptCATPutCatAttrInfo = (__vartype(ptr_CryptCATPutCatAttrInfo))GetProcAddress(hModule, "CryptCATPutCatAttrInfo");
   ptr_CryptCATPutMemberInfo = (__vartype(ptr_CryptCATPutMemberInfo))GetProcAddress(hModule, "CryptCATPutMemberInfo");
   ptr_CryptCATStoreFromHandle = (__vartype(ptr_CryptCATStoreFromHandle))GetProcAddress(hModule, "CryptCATStoreFromHandle");
   ptr_CryptCATVerifyMember = (__vartype(ptr_CryptCATVerifyMember))GetProcAddress(hModule, "CryptCATVerifyMember");
   ptr_CryptSIPCreateIndirectData = (__vartype(ptr_CryptSIPCreateIndirectData))GetProcAddress(hModule, "CryptSIPCreateIndirectData");
   ptr_CryptSIPGetInfo = (__vartype(ptr_CryptSIPGetInfo))GetProcAddress(hModule, "CryptSIPGetInfo");
   ptr_CryptSIPGetRegWorkingFlags = (__vartype(ptr_CryptSIPGetRegWorkingFlags))GetProcAddress(hModule, "CryptSIPGetRegWorkingFlags");
   ptr_CryptSIPGetSignedDataMsg = (__vartype(ptr_CryptSIPGetSignedDataMsg))GetProcAddress(hModule, "CryptSIPGetSignedDataMsg");
   ptr_CryptSIPPutSignedDataMsg = (__vartype(ptr_CryptSIPPutSignedDataMsg))GetProcAddress(hModule, "CryptSIPPutSignedDataMsg");
   ptr_CryptSIPRemoveSignedDataMsg = (__vartype(ptr_CryptSIPRemoveSignedDataMsg))GetProcAddress(hModule, "CryptSIPRemoveSignedDataMsg");
   ptr_CryptSIPVerifyIndirectData = (__vartype(ptr_CryptSIPVerifyIndirectData))GetProcAddress(hModule, "CryptSIPVerifyIndirectData");
   ptr_DllRegisterServer = (__vartype(ptr_DllRegisterServer))GetProcAddress(hModule, "DllRegisterServer");
   ptr_DllUnregisterServer = (__vartype(ptr_DllUnregisterServer))GetProcAddress(hModule, "DllUnregisterServer");
   ptr_DriverCleanupPolicy = (__vartype(ptr_DriverCleanupPolicy))GetProcAddress(hModule, "DriverCleanupPolicy");
   ptr_DriverFinalPolicy = (__vartype(ptr_DriverFinalPolicy))GetProcAddress(hModule, "DriverFinalPolicy");
   ptr_DriverInitializePolicy = (__vartype(ptr_DriverInitializePolicy))GetProcAddress(hModule, "DriverInitializePolicy");
   ptr_FindCertsByIssuer = (__vartype(ptr_FindCertsByIssuer))GetProcAddress(hModule, "FindCertsByIssuer");
   ptr_GenericChainCertificateTrust = (__vartype(ptr_GenericChainCertificateTrust))GetProcAddress(hModule, "GenericChainCertificateTrust");
   ptr_GenericChainFinalProv = (__vartype(ptr_GenericChainFinalProv))GetProcAddress(hModule, "GenericChainFinalProv");
   ptr_HTTPSCertificateTrust = (__vartype(ptr_HTTPSCertificateTrust))GetProcAddress(hModule, "HTTPSCertificateTrust");
   ptr_HTTPSFinalProv = (__vartype(ptr_HTTPSFinalProv))GetProcAddress(hModule, "HTTPSFinalProv");
   ptr_IsCatalogFile = (__vartype(ptr_IsCatalogFile))GetProcAddress(hModule, "IsCatalogFile");
   ptr_MsCatConstructHashTag = (__vartype(ptr_MsCatConstructHashTag))GetProcAddress(hModule, "MsCatConstructHashTag");
   ptr_MsCatFreeHashTag = (__vartype(ptr_MsCatFreeHashTag))GetProcAddress(hModule, "MsCatFreeHashTag");
   ptr_OfficeCleanupPolicy = (__vartype(ptr_OfficeCleanupPolicy))GetProcAddress(hModule, "OfficeCleanupPolicy");
   ptr_OfficeInitializePolicy = (__vartype(ptr_OfficeInitializePolicy))GetProcAddress(hModule, "OfficeInitializePolicy");
   ptr_OpenPersonalTrustDBDialog = (__vartype(ptr_OpenPersonalTrustDBDialog))GetProcAddress(hModule, "OpenPersonalTrustDBDialog");
   ptr_OpenPersonalTrustDBDialogEx = (__vartype(ptr_OpenPersonalTrustDBDialogEx))GetProcAddress(hModule, "OpenPersonalTrustDBDialogEx");
   ptr_SoftpubAuthenticode = (__vartype(ptr_SoftpubAuthenticode))GetProcAddress(hModule, "SoftpubAuthenticode");
   ptr_SoftpubCheckCert = (__vartype(ptr_SoftpubCheckCert))GetProcAddress(hModule, "SoftpubCheckCert");
   ptr_SoftpubCleanup = (__vartype(ptr_SoftpubCleanup))GetProcAddress(hModule, "SoftpubCleanup");
   ptr_SoftpubDefCertInit = (__vartype(ptr_SoftpubDefCertInit))GetProcAddress(hModule, "SoftpubDefCertInit");
   ptr_SoftpubDllRegisterServer = (__vartype(ptr_SoftpubDllRegisterServer))GetProcAddress(hModule, "SoftpubDllRegisterServer");
   ptr_SoftpubDllUnregisterServer = (__vartype(ptr_SoftpubDllUnregisterServer))GetProcAddress(hModule, "SoftpubDllUnregisterServer");
   ptr_SoftpubDumpStructure = (__vartype(ptr_SoftpubDumpStructure))GetProcAddress(hModule, "SoftpubDumpStructure");
   ptr_SoftpubFreeDefUsageCallData = (__vartype(ptr_SoftpubFreeDefUsageCallData))GetProcAddress(hModule, "SoftpubFreeDefUsageCallData");
   ptr_SoftpubInitialize = (__vartype(ptr_SoftpubInitialize))GetProcAddress(hModule, "SoftpubInitialize");
   ptr_SoftpubLoadDefUsageCallData = (__vartype(ptr_SoftpubLoadDefUsageCallData))GetProcAddress(hModule, "SoftpubLoadDefUsageCallData");
   ptr_SoftpubLoadMessage = (__vartype(ptr_SoftpubLoadMessage))GetProcAddress(hModule, "SoftpubLoadMessage");
   ptr_SoftpubLoadSignature = (__vartype(ptr_SoftpubLoadSignature))GetProcAddress(hModule, "SoftpubLoadSignature");
   ptr_TrustDecode = (__vartype(ptr_TrustDecode))GetProcAddress(hModule, "TrustDecode");
   ptr_TrustFindIssuerCertificate = (__vartype(ptr_TrustFindIssuerCertificate))GetProcAddress(hModule, "TrustFindIssuerCertificate");
   ptr_TrustFreeDecode = (__vartype(ptr_TrustFreeDecode))GetProcAddress(hModule, "TrustFreeDecode");
   ptr_TrustIsCertificateSelfSigned = (__vartype(ptr_TrustIsCertificateSelfSigned))GetProcAddress(hModule, "TrustIsCertificateSelfSigned");
   ptr_TrustOpenStores = (__vartype(ptr_TrustOpenStores))GetProcAddress(hModule, "TrustOpenStores");
   ptr_WTHelperCertCheckValidSignature = (__vartype(ptr_WTHelperCertCheckValidSignature))GetProcAddress(hModule, "WTHelperCertCheckValidSignature");
   ptr_WTHelperCertFindIssuerCertificate = (__vartype(ptr_WTHelperCertFindIssuerCertificate))GetProcAddress(hModule, "WTHelperCertFindIssuerCertificate");
   ptr_WTHelperCertIsSelfSigned = (__vartype(ptr_WTHelperCertIsSelfSigned))GetProcAddress(hModule, "WTHelperCertIsSelfSigned");
   ptr_WTHelperCheckCertUsage = (__vartype(ptr_WTHelperCheckCertUsage))GetProcAddress(hModule, "WTHelperCheckCertUsage");
   ptr_WTHelperGetAgencyInfo = (__vartype(ptr_WTHelperGetAgencyInfo))GetProcAddress(hModule, "WTHelperGetAgencyInfo");
   ptr_WTHelperGetFileHandle = (__vartype(ptr_WTHelperGetFileHandle))GetProcAddress(hModule, "WTHelperGetFileHandle");
   ptr_WTHelperGetFileHash = (__vartype(ptr_WTHelperGetFileHash))GetProcAddress(hModule, "WTHelperGetFileHash");
   ptr_WTHelperGetFileName = (__vartype(ptr_WTHelperGetFileName))GetProcAddress(hModule, "WTHelperGetFileName");
   ptr_WTHelperGetKnownUsages = (__vartype(ptr_WTHelperGetKnownUsages))GetProcAddress(hModule, "WTHelperGetKnownUsages");
   ptr_WTHelperGetProvCertFromChain = (__vartype(ptr_WTHelperGetProvCertFromChain))GetProcAddress(hModule, "WTHelperGetProvCertFromChain");
   ptr_WTHelperGetProvPrivateDataFromChain = (__vartype(ptr_WTHelperGetProvPrivateDataFromChain))GetProcAddress(hModule, "WTHelperGetProvPrivateDataFromChain");
   ptr_WTHelperGetProvSignerFromChain = (__vartype(ptr_WTHelperGetProvSignerFromChain))GetProcAddress(hModule, "WTHelperGetProvSignerFromChain");
   ptr_WTHelperIsInRootStore = (__vartype(ptr_WTHelperIsInRootStore))GetProcAddress(hModule, "WTHelperIsInRootStore");
   ptr_WTHelperOpenKnownStores = (__vartype(ptr_WTHelperOpenKnownStores))GetProcAddress(hModule, "WTHelperOpenKnownStores");
   ptr_WTHelperProvDataFromStateData = (__vartype(ptr_WTHelperProvDataFromStateData))GetProcAddress(hModule, "WTHelperProvDataFromStateData");
   ptr_WVTAsn1CatMemberInfo2Decode = (__vartype(ptr_WVTAsn1CatMemberInfo2Decode))GetProcAddress(hModule, "WVTAsn1CatMemberInfo2Decode");
   ptr_WVTAsn1CatMemberInfo2Encode = (__vartype(ptr_WVTAsn1CatMemberInfo2Encode))GetProcAddress(hModule, "WVTAsn1CatMemberInfo2Encode");
   ptr_WVTAsn1CatMemberInfoDecode = (__vartype(ptr_WVTAsn1CatMemberInfoDecode))GetProcAddress(hModule, "WVTAsn1CatMemberInfoDecode");
   ptr_WVTAsn1CatMemberInfoEncode = (__vartype(ptr_WVTAsn1CatMemberInfoEncode))GetProcAddress(hModule, "WVTAsn1CatMemberInfoEncode");
   ptr_WVTAsn1CatNameValueDecode = (__vartype(ptr_WVTAsn1CatNameValueDecode))GetProcAddress(hModule, "WVTAsn1CatNameValueDecode");
   ptr_WVTAsn1CatNameValueEncode = (__vartype(ptr_WVTAsn1CatNameValueEncode))GetProcAddress(hModule, "WVTAsn1CatNameValueEncode");
   ptr_WVTAsn1SpcFinancialCriteriaInfoDecode = (__vartype(ptr_WVTAsn1SpcFinancialCriteriaInfoDecode))GetProcAddress(hModule, "WVTAsn1SpcFinancialCriteriaInfoDecode");
   ptr_WVTAsn1SpcFinancialCriteriaInfoEncode = (__vartype(ptr_WVTAsn1SpcFinancialCriteriaInfoEncode))GetProcAddress(hModule, "WVTAsn1SpcFinancialCriteriaInfoEncode");
   ptr_WVTAsn1SpcIndirectDataContentDecode = (__vartype(ptr_WVTAsn1SpcIndirectDataContentDecode))GetProcAddress(hModule, "WVTAsn1SpcIndirectDataContentDecode");
   ptr_WVTAsn1SpcIndirectDataContentEncode = (__vartype(ptr_WVTAsn1SpcIndirectDataContentEncode))GetProcAddress(hModule, "WVTAsn1SpcIndirectDataContentEncode");
   ptr_WVTAsn1SpcLinkDecode = (__vartype(ptr_WVTAsn1SpcLinkDecode))GetProcAddress(hModule, "WVTAsn1SpcLinkDecode");
   ptr_WVTAsn1SpcLinkEncode = (__vartype(ptr_WVTAsn1SpcLinkEncode))GetProcAddress(hModule, "WVTAsn1SpcLinkEncode");
   ptr_WVTAsn1SpcMinimalCriteriaInfoDecode = (__vartype(ptr_WVTAsn1SpcMinimalCriteriaInfoDecode))GetProcAddress(hModule, "WVTAsn1SpcMinimalCriteriaInfoDecode");
   ptr_WVTAsn1SpcMinimalCriteriaInfoEncode = (__vartype(ptr_WVTAsn1SpcMinimalCriteriaInfoEncode))GetProcAddress(hModule, "WVTAsn1SpcMinimalCriteriaInfoEncode");
   ptr_WVTAsn1SpcPeImageDataDecode = (__vartype(ptr_WVTAsn1SpcPeImageDataDecode))GetProcAddress(hModule, "WVTAsn1SpcPeImageDataDecode");
   ptr_WVTAsn1SpcPeImageDataEncode = (__vartype(ptr_WVTAsn1SpcPeImageDataEncode))GetProcAddress(hModule, "WVTAsn1SpcPeImageDataEncode");
   ptr_WVTAsn1SpcSigInfoDecode = (__vartype(ptr_WVTAsn1SpcSigInfoDecode))GetProcAddress(hModule, "WVTAsn1SpcSigInfoDecode");
   ptr_WVTAsn1SpcSigInfoEncode = (__vartype(ptr_WVTAsn1SpcSigInfoEncode))GetProcAddress(hModule, "WVTAsn1SpcSigInfoEncode");
   ptr_WVTAsn1SpcSpAgencyInfoDecode = (__vartype(ptr_WVTAsn1SpcSpAgencyInfoDecode))GetProcAddress(hModule, "WVTAsn1SpcSpAgencyInfoDecode");
   ptr_WVTAsn1SpcSpAgencyInfoEncode = (__vartype(ptr_WVTAsn1SpcSpAgencyInfoEncode))GetProcAddress(hModule, "WVTAsn1SpcSpAgencyInfoEncode");
   ptr_WVTAsn1SpcSpOpusInfoDecode = (__vartype(ptr_WVTAsn1SpcSpOpusInfoDecode))GetProcAddress(hModule, "WVTAsn1SpcSpOpusInfoDecode");
   ptr_WVTAsn1SpcSpOpusInfoEncode = (__vartype(ptr_WVTAsn1SpcSpOpusInfoEncode))GetProcAddress(hModule, "WVTAsn1SpcSpOpusInfoEncode");
   ptr_WVTAsn1SpcStatementTypeDecode = (__vartype(ptr_WVTAsn1SpcStatementTypeDecode))GetProcAddress(hModule, "WVTAsn1SpcStatementTypeDecode");
   ptr_WVTAsn1SpcStatementTypeEncode = (__vartype(ptr_WVTAsn1SpcStatementTypeEncode))GetProcAddress(hModule, "WVTAsn1SpcStatementTypeEncode");
   ptr_WinVerifyTrust = (__vartype(ptr_WinVerifyTrust))GetProcAddress(hModule, "WinVerifyTrust");
   ptr_WinVerifyTrustEx = (__vartype(ptr_WinVerifyTrustEx))GetProcAddress(hModule, "WinVerifyTrustEx");
   ptr_WintrustAddActionID = (__vartype(ptr_WintrustAddActionID))GetProcAddress(hModule, "WintrustAddActionID");
   ptr_WintrustAddDefaultForUsage = (__vartype(ptr_WintrustAddDefaultForUsage))GetProcAddress(hModule, "WintrustAddDefaultForUsage");
   ptr_WintrustCertificateTrust = (__vartype(ptr_WintrustCertificateTrust))GetProcAddress(hModule, "WintrustCertificateTrust");
   ptr_WintrustGetDefaultForUsage = (__vartype(ptr_WintrustGetDefaultForUsage))GetProcAddress(hModule, "WintrustGetDefaultForUsage");
   ptr_WintrustGetRegPolicyFlags = (__vartype(ptr_WintrustGetRegPolicyFlags))GetProcAddress(hModule, "WintrustGetRegPolicyFlags");
   ptr_WintrustLoadFunctionPointers = (__vartype(ptr_WintrustLoadFunctionPointers))GetProcAddress(hModule, "WintrustLoadFunctionPointers");
   ptr_WintrustRemoveActionID = (__vartype(ptr_WintrustRemoveActionID))GetProcAddress(hModule, "WintrustRemoveActionID");
   ptr_WintrustSetDefaultIncludePEPageHashes = (__vartype(ptr_WintrustSetDefaultIncludePEPageHashes))GetProcAddress(hModule, "WintrustSetDefaultIncludePEPageHashes");
   ptr_WintrustSetRegPolicyFlags = (__vartype(ptr_WintrustSetRegPolicyFlags))GetProcAddress(hModule, "WintrustSetRegPolicyFlags");
   ptr_mscat32DllRegisterServer = (__vartype(ptr_mscat32DllRegisterServer))GetProcAddress(hModule, "mscat32DllRegisterServer");
   ptr_mscat32DllUnregisterServer = (__vartype(ptr_mscat32DllUnregisterServer))GetProcAddress(hModule, "mscat32DllUnregisterServer");
   ptr_mssip32DllRegisterServer = (__vartype(ptr_mssip32DllRegisterServer))GetProcAddress(hModule, "mssip32DllRegisterServer");
   ptr_mssip32DllUnregisterServer = (__vartype(ptr_mssip32DllUnregisterServer))GetProcAddress(hModule, "mssip32DllUnregisterServer");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

