#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_CM_Apply_PowerScheme;
void *ptr_CM_Apply_PowerScheme = NULL;
extern void *ptr_CM_Delete_PowerScheme;
void *ptr_CM_Delete_PowerScheme = NULL;
extern void *ptr_CM_Duplicate_PowerScheme;
void *ptr_CM_Duplicate_PowerScheme = NULL;
extern void *ptr_CM_Import_PowerScheme;
void *ptr_CM_Import_PowerScheme = NULL;
extern void *ptr_CM_RestoreAll_DefaultPowerSchemes;
void *ptr_CM_RestoreAll_DefaultPowerSchemes = NULL;
extern void *ptr_CM_Restore_DefaultPowerScheme;
void *ptr_CM_Restore_DefaultPowerScheme = NULL;
extern void *ptr_CM_Set_ActiveScheme;
void *ptr_CM_Set_ActiveScheme = NULL;
extern void *ptr_CM_Write_UserPowerKey;
void *ptr_CM_Write_UserPowerKey = NULL;
extern void *ptr_DoesUserHavePrivilege;
void *ptr_DoesUserHavePrivilege = NULL;
extern void *ptr_DriverStoreAddDriverPackageA;
void *ptr_DriverStoreAddDriverPackageA = NULL;
extern void *ptr_DriverStoreAddDriverPackageW;
void *ptr_DriverStoreAddDriverPackageW = NULL;
extern void *ptr_DriverStoreDeleteDriverPackageA;
void *ptr_DriverStoreDeleteDriverPackageA = NULL;
extern void *ptr_DriverStoreDeleteDriverPackageW;
void *ptr_DriverStoreDeleteDriverPackageW = NULL;
extern void *ptr_DriverStoreEnumDriverPackageA;
void *ptr_DriverStoreEnumDriverPackageA = NULL;
extern void *ptr_DriverStoreEnumDriverPackageW;
void *ptr_DriverStoreEnumDriverPackageW = NULL;
extern void *ptr_DriverStoreFindDriverPackageA;
void *ptr_DriverStoreFindDriverPackageA = NULL;
extern void *ptr_DriverStoreFindDriverPackageW;
void *ptr_DriverStoreFindDriverPackageW = NULL;
extern void *ptr_ExtensionPropSheetPageProc;
void *ptr_ExtensionPropSheetPageProc = NULL;
extern void *ptr_InstallCatalog;
void *ptr_InstallCatalog = NULL;
extern void *ptr_InstallHinfSection;
void *ptr_InstallHinfSection = NULL;
extern void *ptr_InstallHinfSectionA;
void *ptr_InstallHinfSectionA = NULL;
extern void *ptr_InstallHinfSectionW;
void *ptr_InstallHinfSectionW = NULL;
extern void *ptr_IsUserAdmin;
void *ptr_IsUserAdmin = NULL;
extern void *ptr_MyFree;
void *ptr_MyFree = NULL;
extern void *ptr_MyMalloc;
void *ptr_MyMalloc = NULL;
extern void *ptr_MyRealloc;
void *ptr_MyRealloc = NULL;
extern void *ptr_PnpEnumDrpFile;
void *ptr_PnpEnumDrpFile = NULL;
extern void *ptr_PnpIsFileAclIntact;
void *ptr_PnpIsFileAclIntact = NULL;
extern void *ptr_PnpIsFileContentIntact;
void *ptr_PnpIsFileContentIntact = NULL;
extern void *ptr_PnpIsFilePnpDriver;
void *ptr_PnpIsFilePnpDriver = NULL;
extern void *ptr_PnpRepairWindowsProtectedDriver;
void *ptr_PnpRepairWindowsProtectedDriver = NULL;
extern void *ptr_SetupAddInstallSectionToDiskSpaceListA;
void *ptr_SetupAddInstallSectionToDiskSpaceListA = NULL;
extern void *ptr_SetupAddInstallSectionToDiskSpaceListW;
void *ptr_SetupAddInstallSectionToDiskSpaceListW = NULL;
extern void *ptr_SetupAddSectionToDiskSpaceListA;
void *ptr_SetupAddSectionToDiskSpaceListA = NULL;
extern void *ptr_SetupAddSectionToDiskSpaceListW;
void *ptr_SetupAddSectionToDiskSpaceListW = NULL;
extern void *ptr_SetupAddToDiskSpaceListA;
void *ptr_SetupAddToDiskSpaceListA = NULL;
extern void *ptr_SetupAddToDiskSpaceListW;
void *ptr_SetupAddToDiskSpaceListW = NULL;
extern void *ptr_SetupAddToSourceListA;
void *ptr_SetupAddToSourceListA = NULL;
extern void *ptr_SetupAddToSourceListW;
void *ptr_SetupAddToSourceListW = NULL;
extern void *ptr_SetupAdjustDiskSpaceListA;
void *ptr_SetupAdjustDiskSpaceListA = NULL;
extern void *ptr_SetupAdjustDiskSpaceListW;
void *ptr_SetupAdjustDiskSpaceListW = NULL;
extern void *ptr_SetupBackupErrorA;
void *ptr_SetupBackupErrorA = NULL;
extern void *ptr_SetupBackupErrorW;
void *ptr_SetupBackupErrorW = NULL;
extern void *ptr_SetupCancelTemporarySourceList;
void *ptr_SetupCancelTemporarySourceList = NULL;
extern void *ptr_SetupCloseFileQueue;
void *ptr_SetupCloseFileQueue = NULL;
extern void *ptr_SetupCloseInfFile;
void *ptr_SetupCloseInfFile = NULL;
extern void *ptr_SetupCloseLog;
void *ptr_SetupCloseLog = NULL;
extern void *ptr_SetupCommitFileQueue;
void *ptr_SetupCommitFileQueue = NULL;
extern void *ptr_SetupCommitFileQueueA;
void *ptr_SetupCommitFileQueueA = NULL;
extern void *ptr_SetupCommitFileQueueW;
void *ptr_SetupCommitFileQueueW = NULL;
extern void *ptr_SetupConfigureWmiFromInfSectionA;
void *ptr_SetupConfigureWmiFromInfSectionA = NULL;
extern void *ptr_SetupConfigureWmiFromInfSectionW;
void *ptr_SetupConfigureWmiFromInfSectionW = NULL;
extern void *ptr_SetupCopyErrorA;
void *ptr_SetupCopyErrorA = NULL;
extern void *ptr_SetupCopyErrorW;
void *ptr_SetupCopyErrorW = NULL;
extern void *ptr_SetupCopyOEMInfA;
void *ptr_SetupCopyOEMInfA = NULL;
extern void *ptr_SetupCopyOEMInfW;
void *ptr_SetupCopyOEMInfW = NULL;
extern void *ptr_SetupCreateDiskSpaceListA;
void *ptr_SetupCreateDiskSpaceListA = NULL;
extern void *ptr_SetupCreateDiskSpaceListW;
void *ptr_SetupCreateDiskSpaceListW = NULL;
extern void *ptr_SetupDecompressOrCopyFileA;
void *ptr_SetupDecompressOrCopyFileA = NULL;
extern void *ptr_SetupDecompressOrCopyFileW;
void *ptr_SetupDecompressOrCopyFileW = NULL;
extern void *ptr_SetupDefaultQueueCallback;
void *ptr_SetupDefaultQueueCallback = NULL;
extern void *ptr_SetupDefaultQueueCallbackA;
void *ptr_SetupDefaultQueueCallbackA = NULL;
extern void *ptr_SetupDefaultQueueCallbackW;
void *ptr_SetupDefaultQueueCallbackW = NULL;
extern void *ptr_SetupDeleteErrorA;
void *ptr_SetupDeleteErrorA = NULL;
extern void *ptr_SetupDeleteErrorW;
void *ptr_SetupDeleteErrorW = NULL;
extern void *ptr_SetupDestroyDiskSpaceList;
void *ptr_SetupDestroyDiskSpaceList = NULL;
extern void *ptr_SetupDiApplyPowerScheme;
void *ptr_SetupDiApplyPowerScheme = NULL;
extern void *ptr_SetupDiAskForOEMDisk;
void *ptr_SetupDiAskForOEMDisk = NULL;
extern void *ptr_SetupDiBuildClassInfoList;
void *ptr_SetupDiBuildClassInfoList = NULL;
extern void *ptr_SetupDiBuildClassInfoListExA;
void *ptr_SetupDiBuildClassInfoListExA = NULL;
extern void *ptr_SetupDiBuildClassInfoListExW;
void *ptr_SetupDiBuildClassInfoListExW = NULL;
extern void *ptr_SetupDiBuildDriverInfoList;
void *ptr_SetupDiBuildDriverInfoList = NULL;
extern void *ptr_SetupDiCallClassInstaller;
void *ptr_SetupDiCallClassInstaller = NULL;
extern void *ptr_SetupDiCancelDriverInfoSearch;
void *ptr_SetupDiCancelDriverInfoSearch = NULL;
extern void *ptr_SetupDiChangeState;
void *ptr_SetupDiChangeState = NULL;
extern void *ptr_SetupDiClassGuidsFromNameA;
void *ptr_SetupDiClassGuidsFromNameA = NULL;
extern void *ptr_SetupDiClassGuidsFromNameExA;
void *ptr_SetupDiClassGuidsFromNameExA = NULL;
extern void *ptr_SetupDiClassGuidsFromNameExW;
void *ptr_SetupDiClassGuidsFromNameExW = NULL;
extern void *ptr_SetupDiClassGuidsFromNameW;
void *ptr_SetupDiClassGuidsFromNameW = NULL;
extern void *ptr_SetupDiClassNameFromGuidA;
void *ptr_SetupDiClassNameFromGuidA = NULL;
extern void *ptr_SetupDiClassNameFromGuidExA;
void *ptr_SetupDiClassNameFromGuidExA = NULL;
extern void *ptr_SetupDiClassNameFromGuidExW;
void *ptr_SetupDiClassNameFromGuidExW = NULL;
extern void *ptr_SetupDiClassNameFromGuidW;
void *ptr_SetupDiClassNameFromGuidW = NULL;
extern void *ptr_SetupDiCreateDevRegKeyA;
void *ptr_SetupDiCreateDevRegKeyA = NULL;
extern void *ptr_SetupDiCreateDevRegKeyW;
void *ptr_SetupDiCreateDevRegKeyW = NULL;
extern void *ptr_SetupDiCreateDeviceInfoA;
void *ptr_SetupDiCreateDeviceInfoA = NULL;
extern void *ptr_SetupDiCreateDeviceInfoList;
void *ptr_SetupDiCreateDeviceInfoList = NULL;
extern void *ptr_SetupDiCreateDeviceInfoListExA;
void *ptr_SetupDiCreateDeviceInfoListExA = NULL;
extern void *ptr_SetupDiCreateDeviceInfoListExW;
void *ptr_SetupDiCreateDeviceInfoListExW = NULL;
extern void *ptr_SetupDiCreateDeviceInfoW;
void *ptr_SetupDiCreateDeviceInfoW = NULL;
extern void *ptr_SetupDiCreateDeviceInterfaceA;
void *ptr_SetupDiCreateDeviceInterfaceA = NULL;
extern void *ptr_SetupDiCreateDeviceInterfaceRegKeyA;
void *ptr_SetupDiCreateDeviceInterfaceRegKeyA = NULL;
extern void *ptr_SetupDiCreateDeviceInterfaceRegKeyW;
void *ptr_SetupDiCreateDeviceInterfaceRegKeyW = NULL;
extern void *ptr_SetupDiCreateDeviceInterfaceW;
void *ptr_SetupDiCreateDeviceInterfaceW = NULL;
extern void *ptr_SetupDiDeleteDevRegKey;
void *ptr_SetupDiDeleteDevRegKey = NULL;
extern void *ptr_SetupDiDeleteDeviceInfo;
void *ptr_SetupDiDeleteDeviceInfo = NULL;
extern void *ptr_SetupDiDeleteDeviceInterfaceData;
void *ptr_SetupDiDeleteDeviceInterfaceData = NULL;
extern void *ptr_SetupDiDeleteDeviceInterfaceRegKey;
void *ptr_SetupDiDeleteDeviceInterfaceRegKey = NULL;
extern void *ptr_SetupDiDestroyClassImageList;
void *ptr_SetupDiDestroyClassImageList = NULL;
extern void *ptr_SetupDiDestroyDeviceInfoList;
void *ptr_SetupDiDestroyDeviceInfoList = NULL;
extern void *ptr_SetupDiDestroyDriverInfoList;
void *ptr_SetupDiDestroyDriverInfoList = NULL;
extern void *ptr_SetupDiDrawMiniIcon;
void *ptr_SetupDiDrawMiniIcon = NULL;
extern void *ptr_SetupDiEnumDeviceInfo;
void *ptr_SetupDiEnumDeviceInfo = NULL;
extern void *ptr_SetupDiEnumDeviceInterfaces;
void *ptr_SetupDiEnumDeviceInterfaces = NULL;
extern void *ptr_SetupDiEnumDriverInfoA;
void *ptr_SetupDiEnumDriverInfoA = NULL;
extern void *ptr_SetupDiEnumDriverInfoW;
void *ptr_SetupDiEnumDriverInfoW = NULL;
extern void *ptr_SetupDiGetActualModelsSectionA;
void *ptr_SetupDiGetActualModelsSectionA = NULL;
extern void *ptr_SetupDiGetActualModelsSectionW;
void *ptr_SetupDiGetActualModelsSectionW = NULL;
extern void *ptr_SetupDiGetActualSectionToInstallA;
void *ptr_SetupDiGetActualSectionToInstallA = NULL;
extern void *ptr_SetupDiGetActualSectionToInstallExA;
void *ptr_SetupDiGetActualSectionToInstallExA = NULL;
extern void *ptr_SetupDiGetActualSectionToInstallExW;
void *ptr_SetupDiGetActualSectionToInstallExW = NULL;
extern void *ptr_SetupDiGetActualSectionToInstallW;
void *ptr_SetupDiGetActualSectionToInstallW = NULL;
extern void *ptr_SetupDiGetClassBitmapIndex;
void *ptr_SetupDiGetClassBitmapIndex = NULL;
extern void *ptr_SetupDiGetClassDescriptionA;
void *ptr_SetupDiGetClassDescriptionA = NULL;
extern void *ptr_SetupDiGetClassDescriptionExA;
void *ptr_SetupDiGetClassDescriptionExA = NULL;
extern void *ptr_SetupDiGetClassDescriptionExW;
void *ptr_SetupDiGetClassDescriptionExW = NULL;
extern void *ptr_SetupDiGetClassDescriptionW;
void *ptr_SetupDiGetClassDescriptionW = NULL;
extern void *ptr_SetupDiGetClassDevPropertySheetsA;
void *ptr_SetupDiGetClassDevPropertySheetsA = NULL;
extern void *ptr_SetupDiGetClassDevPropertySheetsW;
void *ptr_SetupDiGetClassDevPropertySheetsW = NULL;
extern void *ptr_SetupDiGetClassDevsA;
void *ptr_SetupDiGetClassDevsA = NULL;
extern void *ptr_SetupDiGetClassDevsExA;
void *ptr_SetupDiGetClassDevsExA = NULL;
extern void *ptr_SetupDiGetClassDevsExW;
void *ptr_SetupDiGetClassDevsExW = NULL;
extern void *ptr_SetupDiGetClassDevsW;
void *ptr_SetupDiGetClassDevsW = NULL;
extern void *ptr_SetupDiGetClassImageIndex;
void *ptr_SetupDiGetClassImageIndex = NULL;
extern void *ptr_SetupDiGetClassImageList;
void *ptr_SetupDiGetClassImageList = NULL;
extern void *ptr_SetupDiGetClassImageListExA;
void *ptr_SetupDiGetClassImageListExA = NULL;
extern void *ptr_SetupDiGetClassImageListExW;
void *ptr_SetupDiGetClassImageListExW = NULL;
extern void *ptr_SetupDiGetClassInstallParamsA;
void *ptr_SetupDiGetClassInstallParamsA = NULL;
extern void *ptr_SetupDiGetClassInstallParamsW;
void *ptr_SetupDiGetClassInstallParamsW = NULL;
extern void *ptr_SetupDiGetClassPropertyExW;
void *ptr_SetupDiGetClassPropertyExW = NULL;
extern void *ptr_SetupDiGetClassPropertyKeys;
void *ptr_SetupDiGetClassPropertyKeys = NULL;
extern void *ptr_SetupDiGetClassPropertyKeysExW;
void *ptr_SetupDiGetClassPropertyKeysExW = NULL;
extern void *ptr_SetupDiGetClassPropertyW;
void *ptr_SetupDiGetClassPropertyW = NULL;
extern void *ptr_SetupDiGetClassRegistryPropertyA;
void *ptr_SetupDiGetClassRegistryPropertyA = NULL;
extern void *ptr_SetupDiGetClassRegistryPropertyW;
void *ptr_SetupDiGetClassRegistryPropertyW = NULL;
extern void *ptr_SetupDiGetCustomDevicePropertyA;
void *ptr_SetupDiGetCustomDevicePropertyA = NULL;
extern void *ptr_SetupDiGetCustomDevicePropertyW;
void *ptr_SetupDiGetCustomDevicePropertyW = NULL;
extern void *ptr_SetupDiGetDeviceInfoListClass;
void *ptr_SetupDiGetDeviceInfoListClass = NULL;
extern void *ptr_SetupDiGetDeviceInfoListDetailA;
void *ptr_SetupDiGetDeviceInfoListDetailA = NULL;
extern void *ptr_SetupDiGetDeviceInfoListDetailW;
void *ptr_SetupDiGetDeviceInfoListDetailW = NULL;
extern void *ptr_SetupDiGetDeviceInstallParamsA;
void *ptr_SetupDiGetDeviceInstallParamsA = NULL;
extern void *ptr_SetupDiGetDeviceInstallParamsW;
void *ptr_SetupDiGetDeviceInstallParamsW = NULL;
extern void *ptr_SetupDiGetDeviceInstanceIdA;
void *ptr_SetupDiGetDeviceInstanceIdA = NULL;
extern void *ptr_SetupDiGetDeviceInstanceIdW;
void *ptr_SetupDiGetDeviceInstanceIdW = NULL;
extern void *ptr_SetupDiGetDeviceInterfaceAlias;
void *ptr_SetupDiGetDeviceInterfaceAlias = NULL;
extern void *ptr_SetupDiGetDeviceInterfaceDetailA;
void *ptr_SetupDiGetDeviceInterfaceDetailA = NULL;
extern void *ptr_SetupDiGetDeviceInterfaceDetailW;
void *ptr_SetupDiGetDeviceInterfaceDetailW = NULL;
extern void *ptr_SetupDiGetDeviceInterfacePropertyKeys;
void *ptr_SetupDiGetDeviceInterfacePropertyKeys = NULL;
extern void *ptr_SetupDiGetDeviceInterfacePropertyW;
void *ptr_SetupDiGetDeviceInterfacePropertyW = NULL;
extern void *ptr_SetupDiGetDevicePropertyKeys;
void *ptr_SetupDiGetDevicePropertyKeys = NULL;
extern void *ptr_SetupDiGetDevicePropertyW;
void *ptr_SetupDiGetDevicePropertyW = NULL;
extern void *ptr_SetupDiGetDeviceRegistryPropertyA;
void *ptr_SetupDiGetDeviceRegistryPropertyA = NULL;
extern void *ptr_SetupDiGetDeviceRegistryPropertyW;
void *ptr_SetupDiGetDeviceRegistryPropertyW = NULL;
extern void *ptr_SetupDiGetDriverInfoDetailA;
void *ptr_SetupDiGetDriverInfoDetailA = NULL;
extern void *ptr_SetupDiGetDriverInfoDetailW;
void *ptr_SetupDiGetDriverInfoDetailW = NULL;
extern void *ptr_SetupDiGetDriverInstallParamsA;
void *ptr_SetupDiGetDriverInstallParamsA = NULL;
extern void *ptr_SetupDiGetDriverInstallParamsW;
void *ptr_SetupDiGetDriverInstallParamsW = NULL;
extern void *ptr_SetupDiGetHwProfileFriendlyNameA;
void *ptr_SetupDiGetHwProfileFriendlyNameA = NULL;
extern void *ptr_SetupDiGetHwProfileFriendlyNameExA;
void *ptr_SetupDiGetHwProfileFriendlyNameExA = NULL;
extern void *ptr_SetupDiGetHwProfileFriendlyNameExW;
void *ptr_SetupDiGetHwProfileFriendlyNameExW = NULL;
extern void *ptr_SetupDiGetHwProfileFriendlyNameW;
void *ptr_SetupDiGetHwProfileFriendlyNameW = NULL;
extern void *ptr_SetupDiGetHwProfileList;
void *ptr_SetupDiGetHwProfileList = NULL;
extern void *ptr_SetupDiGetHwProfileListExA;
void *ptr_SetupDiGetHwProfileListExA = NULL;
extern void *ptr_SetupDiGetHwProfileListExW;
void *ptr_SetupDiGetHwProfileListExW = NULL;
extern void *ptr_SetupDiGetINFClassA;
void *ptr_SetupDiGetINFClassA = NULL;
extern void *ptr_SetupDiGetINFClassW;
void *ptr_SetupDiGetINFClassW = NULL;
extern void *ptr_SetupDiGetSelectedDevice;
void *ptr_SetupDiGetSelectedDevice = NULL;
extern void *ptr_SetupDiGetSelectedDriverA;
void *ptr_SetupDiGetSelectedDriverA = NULL;
extern void *ptr_SetupDiGetSelectedDriverW;
void *ptr_SetupDiGetSelectedDriverW = NULL;
extern void *ptr_SetupDiGetWizardPage;
void *ptr_SetupDiGetWizardPage = NULL;
extern void *ptr_SetupDiInstallClassA;
void *ptr_SetupDiInstallClassA = NULL;
extern void *ptr_SetupDiInstallClassExA;
void *ptr_SetupDiInstallClassExA = NULL;
extern void *ptr_SetupDiInstallClassExW;
void *ptr_SetupDiInstallClassExW = NULL;
extern void *ptr_SetupDiInstallClassW;
void *ptr_SetupDiInstallClassW = NULL;
extern void *ptr_SetupDiInstallDevice;
void *ptr_SetupDiInstallDevice = NULL;
extern void *ptr_SetupDiInstallDeviceInterfaces;
void *ptr_SetupDiInstallDeviceInterfaces = NULL;
extern void *ptr_SetupDiInstallDriverFiles;
void *ptr_SetupDiInstallDriverFiles = NULL;
extern void *ptr_SetupDiLoadClassIcon;
void *ptr_SetupDiLoadClassIcon = NULL;
extern void *ptr_SetupDiLoadDeviceIcon;
void *ptr_SetupDiLoadDeviceIcon = NULL;
extern void *ptr_SetupDiMoveDuplicateDevice;
void *ptr_SetupDiMoveDuplicateDevice = NULL;
extern void *ptr_SetupDiOpenClassRegKey;
void *ptr_SetupDiOpenClassRegKey = NULL;
extern void *ptr_SetupDiOpenClassRegKeyExA;
void *ptr_SetupDiOpenClassRegKeyExA = NULL;
extern void *ptr_SetupDiOpenClassRegKeyExW;
void *ptr_SetupDiOpenClassRegKeyExW = NULL;
extern void *ptr_SetupDiOpenDevRegKey;
void *ptr_SetupDiOpenDevRegKey = NULL;
extern void *ptr_SetupDiOpenDeviceInfoA;
void *ptr_SetupDiOpenDeviceInfoA = NULL;
extern void *ptr_SetupDiOpenDeviceInfoW;
void *ptr_SetupDiOpenDeviceInfoW = NULL;
extern void *ptr_SetupDiOpenDeviceInterfaceA;
void *ptr_SetupDiOpenDeviceInterfaceA = NULL;
extern void *ptr_SetupDiOpenDeviceInterfaceRegKey;
void *ptr_SetupDiOpenDeviceInterfaceRegKey = NULL;
extern void *ptr_SetupDiOpenDeviceInterfaceW;
void *ptr_SetupDiOpenDeviceInterfaceW = NULL;
extern void *ptr_SetupDiRegisterCoDeviceInstallers;
void *ptr_SetupDiRegisterCoDeviceInstallers = NULL;
extern void *ptr_SetupDiRegisterDeviceInfo;
void *ptr_SetupDiRegisterDeviceInfo = NULL;
extern void *ptr_SetupDiRemoveDevice;
void *ptr_SetupDiRemoveDevice = NULL;
extern void *ptr_SetupDiRemoveDeviceInterface;
void *ptr_SetupDiRemoveDeviceInterface = NULL;
extern void *ptr_SetupDiReportAdditionalSoftwareRequested;
void *ptr_SetupDiReportAdditionalSoftwareRequested = NULL;
extern void *ptr_SetupDiReportDeviceInstallError;
void *ptr_SetupDiReportDeviceInstallError = NULL;
extern void *ptr_SetupDiReportDriverNotFoundError;
void *ptr_SetupDiReportDriverNotFoundError = NULL;
extern void *ptr_SetupDiReportDriverPackageImportationError;
void *ptr_SetupDiReportDriverPackageImportationError = NULL;
extern void *ptr_SetupDiReportGenericDriverInstalled;
void *ptr_SetupDiReportGenericDriverInstalled = NULL;
extern void *ptr_SetupDiReportPnPDeviceProblem;
void *ptr_SetupDiReportPnPDeviceProblem = NULL;
extern void *ptr_SetupDiRestartDevices;
void *ptr_SetupDiRestartDevices = NULL;
extern void *ptr_SetupDiSelectBestCompatDrv;
void *ptr_SetupDiSelectBestCompatDrv = NULL;
extern void *ptr_SetupDiSelectDevice;
void *ptr_SetupDiSelectDevice = NULL;
extern void *ptr_SetupDiSelectOEMDrv;
void *ptr_SetupDiSelectOEMDrv = NULL;
extern void *ptr_SetupDiSetClassInstallParamsA;
void *ptr_SetupDiSetClassInstallParamsA = NULL;
extern void *ptr_SetupDiSetClassInstallParamsW;
void *ptr_SetupDiSetClassInstallParamsW = NULL;
extern void *ptr_SetupDiSetClassPropertyExW;
void *ptr_SetupDiSetClassPropertyExW = NULL;
extern void *ptr_SetupDiSetClassPropertyW;
void *ptr_SetupDiSetClassPropertyW = NULL;
extern void *ptr_SetupDiSetClassRegistryPropertyA;
void *ptr_SetupDiSetClassRegistryPropertyA = NULL;
extern void *ptr_SetupDiSetClassRegistryPropertyW;
void *ptr_SetupDiSetClassRegistryPropertyW = NULL;
extern void *ptr_SetupDiSetDeviceInstallParamsA;
void *ptr_SetupDiSetDeviceInstallParamsA = NULL;
extern void *ptr_SetupDiSetDeviceInstallParamsW;
void *ptr_SetupDiSetDeviceInstallParamsW = NULL;
extern void *ptr_SetupDiSetDeviceInterfaceDefault;
void *ptr_SetupDiSetDeviceInterfaceDefault = NULL;
extern void *ptr_SetupDiSetDeviceInterfacePropertyW;
void *ptr_SetupDiSetDeviceInterfacePropertyW = NULL;
extern void *ptr_SetupDiSetDevicePropertyW;
void *ptr_SetupDiSetDevicePropertyW = NULL;
extern void *ptr_SetupDiSetDeviceRegistryPropertyA;
void *ptr_SetupDiSetDeviceRegistryPropertyA = NULL;
extern void *ptr_SetupDiSetDeviceRegistryPropertyW;
void *ptr_SetupDiSetDeviceRegistryPropertyW = NULL;
extern void *ptr_SetupDiSetDriverInstallParamsA;
void *ptr_SetupDiSetDriverInstallParamsA = NULL;
extern void *ptr_SetupDiSetDriverInstallParamsW;
void *ptr_SetupDiSetDriverInstallParamsW = NULL;
extern void *ptr_SetupDiSetSelectedDevice;
void *ptr_SetupDiSetSelectedDevice = NULL;
extern void *ptr_SetupDiSetSelectedDriverA;
void *ptr_SetupDiSetSelectedDriverA = NULL;
extern void *ptr_SetupDiSetSelectedDriverW;
void *ptr_SetupDiSetSelectedDriverW = NULL;
extern void *ptr_SetupDiUnremoveDevice;
void *ptr_SetupDiUnremoveDevice = NULL;
extern void *ptr_SetupDuplicateDiskSpaceListA;
void *ptr_SetupDuplicateDiskSpaceListA = NULL;
extern void *ptr_SetupDuplicateDiskSpaceListW;
void *ptr_SetupDuplicateDiskSpaceListW = NULL;
extern void *ptr_SetupEnumInfSectionsA;
void *ptr_SetupEnumInfSectionsA = NULL;
extern void *ptr_SetupEnumInfSectionsW;
void *ptr_SetupEnumInfSectionsW = NULL;
extern void *ptr_SetupEnumPublishedInfA;
void *ptr_SetupEnumPublishedInfA = NULL;
extern void *ptr_SetupEnumPublishedInfW;
void *ptr_SetupEnumPublishedInfW = NULL;
extern void *ptr_SetupFindFirstLineA;
void *ptr_SetupFindFirstLineA = NULL;
extern void *ptr_SetupFindFirstLineW;
void *ptr_SetupFindFirstLineW = NULL;
extern void *ptr_SetupFindNextLine;
void *ptr_SetupFindNextLine = NULL;
extern void *ptr_SetupFindNextMatchLineA;
void *ptr_SetupFindNextMatchLineA = NULL;
extern void *ptr_SetupFindNextMatchLineW;
void *ptr_SetupFindNextMatchLineW = NULL;
extern void *ptr_SetupFreeSourceListA;
void *ptr_SetupFreeSourceListA = NULL;
extern void *ptr_SetupFreeSourceListW;
void *ptr_SetupFreeSourceListW = NULL;
extern void *ptr_SetupGetBackupInformationA;
void *ptr_SetupGetBackupInformationA = NULL;
extern void *ptr_SetupGetBackupInformationW;
void *ptr_SetupGetBackupInformationW = NULL;
extern void *ptr_SetupGetBinaryField;
void *ptr_SetupGetBinaryField = NULL;
extern void *ptr_SetupGetFieldCount;
void *ptr_SetupGetFieldCount = NULL;
extern void *ptr_SetupGetFileCompressionInfoA;
void *ptr_SetupGetFileCompressionInfoA = NULL;
extern void *ptr_SetupGetFileCompressionInfoExA;
void *ptr_SetupGetFileCompressionInfoExA = NULL;
extern void *ptr_SetupGetFileCompressionInfoExW;
void *ptr_SetupGetFileCompressionInfoExW = NULL;
extern void *ptr_SetupGetFileCompressionInfoW;
void *ptr_SetupGetFileCompressionInfoW = NULL;
extern void *ptr_SetupGetFileQueueCount;
void *ptr_SetupGetFileQueueCount = NULL;
extern void *ptr_SetupGetFileQueueFlags;
void *ptr_SetupGetFileQueueFlags = NULL;
extern void *ptr_SetupGetInfDriverStoreLocationA;
void *ptr_SetupGetInfDriverStoreLocationA = NULL;
extern void *ptr_SetupGetInfDriverStoreLocationW;
void *ptr_SetupGetInfDriverStoreLocationW = NULL;
extern void *ptr_SetupGetInfFileListA;
void *ptr_SetupGetInfFileListA = NULL;
extern void *ptr_SetupGetInfFileListW;
void *ptr_SetupGetInfFileListW = NULL;
extern void *ptr_SetupGetInfInformationA;
void *ptr_SetupGetInfInformationA = NULL;
extern void *ptr_SetupGetInfInformationW;
void *ptr_SetupGetInfInformationW = NULL;
extern void *ptr_SetupGetInfPublishedNameA;
void *ptr_SetupGetInfPublishedNameA = NULL;
extern void *ptr_SetupGetInfPublishedNameW;
void *ptr_SetupGetInfPublishedNameW = NULL;
extern void *ptr_SetupGetInfSections;
void *ptr_SetupGetInfSections = NULL;
extern void *ptr_SetupGetIntField;
void *ptr_SetupGetIntField = NULL;
extern void *ptr_SetupGetLineByIndexA;
void *ptr_SetupGetLineByIndexA = NULL;
extern void *ptr_SetupGetLineByIndexW;
void *ptr_SetupGetLineByIndexW = NULL;
extern void *ptr_SetupGetLineCountA;
void *ptr_SetupGetLineCountA = NULL;
extern void *ptr_SetupGetLineCountW;
void *ptr_SetupGetLineCountW = NULL;
extern void *ptr_SetupGetLineTextA;
void *ptr_SetupGetLineTextA = NULL;
extern void *ptr_SetupGetLineTextW;
void *ptr_SetupGetLineTextW = NULL;
extern void *ptr_SetupGetMultiSzFieldA;
void *ptr_SetupGetMultiSzFieldA = NULL;
extern void *ptr_SetupGetMultiSzFieldW;
void *ptr_SetupGetMultiSzFieldW = NULL;
extern void *ptr_SetupGetNonInteractiveMode;
void *ptr_SetupGetNonInteractiveMode = NULL;
extern void *ptr_SetupGetSourceFileLocationA;
void *ptr_SetupGetSourceFileLocationA = NULL;
extern void *ptr_SetupGetSourceFileLocationW;
void *ptr_SetupGetSourceFileLocationW = NULL;
extern void *ptr_SetupGetSourceFileSizeA;
void *ptr_SetupGetSourceFileSizeA = NULL;
extern void *ptr_SetupGetSourceFileSizeW;
void *ptr_SetupGetSourceFileSizeW = NULL;
extern void *ptr_SetupGetSourceInfoA;
void *ptr_SetupGetSourceInfoA = NULL;
extern void *ptr_SetupGetSourceInfoW;
void *ptr_SetupGetSourceInfoW = NULL;
extern void *ptr_SetupGetStringFieldA;
void *ptr_SetupGetStringFieldA = NULL;
extern void *ptr_SetupGetStringFieldW;
void *ptr_SetupGetStringFieldW = NULL;
extern void *ptr_SetupGetTargetPathA;
void *ptr_SetupGetTargetPathA = NULL;
extern void *ptr_SetupGetTargetPathW;
void *ptr_SetupGetTargetPathW = NULL;
extern void *ptr_SetupInitDefaultQueueCallback;
void *ptr_SetupInitDefaultQueueCallback = NULL;
extern void *ptr_SetupInitDefaultQueueCallbackEx;
void *ptr_SetupInitDefaultQueueCallbackEx = NULL;
extern void *ptr_SetupInitializeFileLogA;
void *ptr_SetupInitializeFileLogA = NULL;
extern void *ptr_SetupInitializeFileLogW;
void *ptr_SetupInitializeFileLogW = NULL;
extern void *ptr_SetupInstallFileA;
void *ptr_SetupInstallFileA = NULL;
extern void *ptr_SetupInstallFileExA;
void *ptr_SetupInstallFileExA = NULL;
extern void *ptr_SetupInstallFileExW;
void *ptr_SetupInstallFileExW = NULL;
extern void *ptr_SetupInstallFileW;
void *ptr_SetupInstallFileW = NULL;
extern void *ptr_SetupInstallFilesFromInfSectionA;
void *ptr_SetupInstallFilesFromInfSectionA = NULL;
extern void *ptr_SetupInstallFilesFromInfSectionW;
void *ptr_SetupInstallFilesFromInfSectionW = NULL;
extern void *ptr_SetupInstallFromInfSectionA;
void *ptr_SetupInstallFromInfSectionA = NULL;
extern void *ptr_SetupInstallFromInfSectionW;
void *ptr_SetupInstallFromInfSectionW = NULL;
extern void *ptr_SetupInstallLogCloseEventGroup;
void *ptr_SetupInstallLogCloseEventGroup = NULL;
extern void *ptr_SetupInstallLogCreateEventGroup;
void *ptr_SetupInstallLogCreateEventGroup = NULL;
extern void *ptr_SetupInstallServicesFromInfSectionA;
void *ptr_SetupInstallServicesFromInfSectionA = NULL;
extern void *ptr_SetupInstallServicesFromInfSectionExA;
void *ptr_SetupInstallServicesFromInfSectionExA = NULL;
extern void *ptr_SetupInstallServicesFromInfSectionExW;
void *ptr_SetupInstallServicesFromInfSectionExW = NULL;
extern void *ptr_SetupInstallServicesFromInfSectionW;
void *ptr_SetupInstallServicesFromInfSectionW = NULL;
extern void *ptr_SetupIterateCabinetA;
void *ptr_SetupIterateCabinetA = NULL;
extern void *ptr_SetupIterateCabinetW;
void *ptr_SetupIterateCabinetW = NULL;
extern void *ptr_SetupLogErrorA;
void *ptr_SetupLogErrorA = NULL;
extern void *ptr_SetupLogErrorW;
void *ptr_SetupLogErrorW = NULL;
extern void *ptr_SetupLogFileA;
void *ptr_SetupLogFileA = NULL;
extern void *ptr_SetupLogFileW;
void *ptr_SetupLogFileW = NULL;
extern void *ptr_SetupOpenAppendInfFileA;
void *ptr_SetupOpenAppendInfFileA = NULL;
extern void *ptr_SetupOpenAppendInfFileW;
void *ptr_SetupOpenAppendInfFileW = NULL;
extern void *ptr_SetupOpenFileQueue;
void *ptr_SetupOpenFileQueue = NULL;
extern void *ptr_SetupOpenInfFileA;
void *ptr_SetupOpenInfFileA = NULL;
extern void *ptr_SetupOpenInfFileW;
void *ptr_SetupOpenInfFileW = NULL;
extern void *ptr_SetupOpenLog;
void *ptr_SetupOpenLog = NULL;
extern void *ptr_SetupOpenMasterInf;
void *ptr_SetupOpenMasterInf = NULL;
extern void *ptr_SetupPrepareQueueForRestoreA;
void *ptr_SetupPrepareQueueForRestoreA = NULL;
extern void *ptr_SetupPrepareQueueForRestoreW;
void *ptr_SetupPrepareQueueForRestoreW = NULL;
extern void *ptr_SetupPromptForDiskA;
void *ptr_SetupPromptForDiskA = NULL;
extern void *ptr_SetupPromptForDiskW;
void *ptr_SetupPromptForDiskW = NULL;
extern void *ptr_SetupPromptReboot;
void *ptr_SetupPromptReboot = NULL;
extern void *ptr_SetupQueryDrivesInDiskSpaceListA;
void *ptr_SetupQueryDrivesInDiskSpaceListA = NULL;
extern void *ptr_SetupQueryDrivesInDiskSpaceListW;
void *ptr_SetupQueryDrivesInDiskSpaceListW = NULL;
extern void *ptr_SetupQueryFileLogA;
void *ptr_SetupQueryFileLogA = NULL;
extern void *ptr_SetupQueryFileLogW;
void *ptr_SetupQueryFileLogW = NULL;
extern void *ptr_SetupQueryInfFileInformationA;
void *ptr_SetupQueryInfFileInformationA = NULL;
extern void *ptr_SetupQueryInfFileInformationW;
void *ptr_SetupQueryInfFileInformationW = NULL;
extern void *ptr_SetupQueryInfOriginalFileInformationA;
void *ptr_SetupQueryInfOriginalFileInformationA = NULL;
extern void *ptr_SetupQueryInfOriginalFileInformationW;
void *ptr_SetupQueryInfOriginalFileInformationW = NULL;
extern void *ptr_SetupQueryInfVersionInformationA;
void *ptr_SetupQueryInfVersionInformationA = NULL;
extern void *ptr_SetupQueryInfVersionInformationW;
void *ptr_SetupQueryInfVersionInformationW = NULL;
extern void *ptr_SetupQuerySourceListA;
void *ptr_SetupQuerySourceListA = NULL;
extern void *ptr_SetupQuerySourceListW;
void *ptr_SetupQuerySourceListW = NULL;
extern void *ptr_SetupQuerySpaceRequiredOnDriveA;
void *ptr_SetupQuerySpaceRequiredOnDriveA = NULL;
extern void *ptr_SetupQuerySpaceRequiredOnDriveW;
void *ptr_SetupQuerySpaceRequiredOnDriveW = NULL;
extern void *ptr_SetupQueueCopyA;
void *ptr_SetupQueueCopyA = NULL;
extern void *ptr_SetupQueueCopyIndirectA;
void *ptr_SetupQueueCopyIndirectA = NULL;
extern void *ptr_SetupQueueCopyIndirectW;
void *ptr_SetupQueueCopyIndirectW = NULL;
extern void *ptr_SetupQueueCopySectionA;
void *ptr_SetupQueueCopySectionA = NULL;
extern void *ptr_SetupQueueCopySectionW;
void *ptr_SetupQueueCopySectionW = NULL;
extern void *ptr_SetupQueueCopyW;
void *ptr_SetupQueueCopyW = NULL;
extern void *ptr_SetupQueueDefaultCopyA;
void *ptr_SetupQueueDefaultCopyA = NULL;
extern void *ptr_SetupQueueDefaultCopyW;
void *ptr_SetupQueueDefaultCopyW = NULL;
extern void *ptr_SetupQueueDeleteA;
void *ptr_SetupQueueDeleteA = NULL;
extern void *ptr_SetupQueueDeleteSectionA;
void *ptr_SetupQueueDeleteSectionA = NULL;
extern void *ptr_SetupQueueDeleteSectionW;
void *ptr_SetupQueueDeleteSectionW = NULL;
extern void *ptr_SetupQueueDeleteW;
void *ptr_SetupQueueDeleteW = NULL;
extern void *ptr_SetupQueueRenameA;
void *ptr_SetupQueueRenameA = NULL;
extern void *ptr_SetupQueueRenameSectionA;
void *ptr_SetupQueueRenameSectionA = NULL;
extern void *ptr_SetupQueueRenameSectionW;
void *ptr_SetupQueueRenameSectionW = NULL;
extern void *ptr_SetupQueueRenameW;
void *ptr_SetupQueueRenameW = NULL;
extern void *ptr_SetupRemoveFileLogEntryA;
void *ptr_SetupRemoveFileLogEntryA = NULL;
extern void *ptr_SetupRemoveFileLogEntryW;
void *ptr_SetupRemoveFileLogEntryW = NULL;
extern void *ptr_SetupRemoveFromDiskSpaceListA;
void *ptr_SetupRemoveFromDiskSpaceListA = NULL;
extern void *ptr_SetupRemoveFromDiskSpaceListW;
void *ptr_SetupRemoveFromDiskSpaceListW = NULL;
extern void *ptr_SetupRemoveFromSourceListA;
void *ptr_SetupRemoveFromSourceListA = NULL;
extern void *ptr_SetupRemoveFromSourceListW;
void *ptr_SetupRemoveFromSourceListW = NULL;
extern void *ptr_SetupRemoveInstallSectionFromDiskSpaceListA;
void *ptr_SetupRemoveInstallSectionFromDiskSpaceListA = NULL;
extern void *ptr_SetupRemoveInstallSectionFromDiskSpaceListW;
void *ptr_SetupRemoveInstallSectionFromDiskSpaceListW = NULL;
extern void *ptr_SetupRemoveSectionFromDiskSpaceListA;
void *ptr_SetupRemoveSectionFromDiskSpaceListA = NULL;
extern void *ptr_SetupRemoveSectionFromDiskSpaceListW;
void *ptr_SetupRemoveSectionFromDiskSpaceListW = NULL;
extern void *ptr_SetupRenameErrorA;
void *ptr_SetupRenameErrorA = NULL;
extern void *ptr_SetupRenameErrorW;
void *ptr_SetupRenameErrorW = NULL;
extern void *ptr_SetupScanFileQueue;
void *ptr_SetupScanFileQueue = NULL;
extern void *ptr_SetupScanFileQueueA;
void *ptr_SetupScanFileQueueA = NULL;
extern void *ptr_SetupScanFileQueueW;
void *ptr_SetupScanFileQueueW = NULL;
extern void *ptr_SetupSetDirectoryIdA;
void *ptr_SetupSetDirectoryIdA = NULL;
extern void *ptr_SetupSetDirectoryIdExA;
void *ptr_SetupSetDirectoryIdExA = NULL;
extern void *ptr_SetupSetDirectoryIdExW;
void *ptr_SetupSetDirectoryIdExW = NULL;
extern void *ptr_SetupSetDirectoryIdW;
void *ptr_SetupSetDirectoryIdW = NULL;
extern void *ptr_SetupSetFileQueueAlternatePlatformA;
void *ptr_SetupSetFileQueueAlternatePlatformA = NULL;
extern void *ptr_SetupSetFileQueueAlternatePlatformW;
void *ptr_SetupSetFileQueueAlternatePlatformW = NULL;
extern void *ptr_SetupSetFileQueueFlags;
void *ptr_SetupSetFileQueueFlags = NULL;
extern void *ptr_SetupSetNonInteractiveMode;
void *ptr_SetupSetNonInteractiveMode = NULL;
extern void *ptr_SetupSetPlatformPathOverrideA;
void *ptr_SetupSetPlatformPathOverrideA = NULL;
extern void *ptr_SetupSetPlatformPathOverrideW;
void *ptr_SetupSetPlatformPathOverrideW = NULL;
extern void *ptr_SetupSetSourceListA;
void *ptr_SetupSetSourceListA = NULL;
extern void *ptr_SetupSetSourceListW;
void *ptr_SetupSetSourceListW = NULL;
extern void *ptr_SetupTermDefaultQueueCallback;
void *ptr_SetupTermDefaultQueueCallback = NULL;
extern void *ptr_SetupTerminateFileLog;
void *ptr_SetupTerminateFileLog = NULL;
extern void *ptr_SetupUninstallNewlyCopiedInfs;
void *ptr_SetupUninstallNewlyCopiedInfs = NULL;
extern void *ptr_SetupUninstallOEMInfA;
void *ptr_SetupUninstallOEMInfA = NULL;
extern void *ptr_SetupUninstallOEMInfW;
void *ptr_SetupUninstallOEMInfW = NULL;
extern void *ptr_SetupVerifyInfFileA;
void *ptr_SetupVerifyInfFileA = NULL;
extern void *ptr_SetupVerifyInfFileW;
void *ptr_SetupVerifyInfFileW = NULL;
extern void *ptr_SetupWriteTextLogInfLine;
void *ptr_SetupWriteTextLogInfLine = NULL;
extern void *ptr_UnicodeToMultiByte;
void *ptr_UnicodeToMultiByte = NULL;
extern void *ptr_VerifyCatalogFile;
void *ptr_VerifyCatalogFile = NULL;
extern void *ptr_pGetDriverPackageHash;
void *ptr_pGetDriverPackageHash = NULL;
extern void *ptr_pSetupAccessRunOnceNodeList;
void *ptr_pSetupAccessRunOnceNodeList = NULL;
extern void *ptr_pSetupAddMiniIconToList;
void *ptr_pSetupAddMiniIconToList = NULL;
extern void *ptr_pSetupAddTagToGroupOrderListEntry;
void *ptr_pSetupAddTagToGroupOrderListEntry = NULL;
extern void *ptr_pSetupAppendPath;
void *ptr_pSetupAppendPath = NULL;
extern void *ptr_pSetupCaptureAndConvertAnsiArg;
void *ptr_pSetupCaptureAndConvertAnsiArg = NULL;
extern void *ptr_pSetupCenterWindowRelativeToParent;
void *ptr_pSetupCenterWindowRelativeToParent = NULL;
extern void *ptr_pSetupConcatenatePaths;
void *ptr_pSetupConcatenatePaths = NULL;
extern void *ptr_pSetupDestroyRunOnceNodeList;
void *ptr_pSetupDestroyRunOnceNodeList = NULL;
extern void *ptr_pSetupDiBuildInfoDataFromStrongName;
void *ptr_pSetupDiBuildInfoDataFromStrongName = NULL;
extern void *ptr_pSetupDiCrimsonLogDeviceInstall;
void *ptr_pSetupDiCrimsonLogDeviceInstall = NULL;
extern void *ptr_pSetupDiGetStrongNameForDriverNode;
void *ptr_pSetupDiGetStrongNameForDriverNode = NULL;
extern void *ptr_pSetupDiInvalidateHelperModules;
void *ptr_pSetupDiInvalidateHelperModules = NULL;
extern void *ptr_pSetupDoLastKnownGoodBackup;
void *ptr_pSetupDoLastKnownGoodBackup = NULL;
extern void *ptr_pSetupDoesUserHavePrivilege;
void *ptr_pSetupDoesUserHavePrivilege = NULL;
extern void *ptr_pSetupDuplicateString;
void *ptr_pSetupDuplicateString = NULL;
extern void *ptr_pSetupEnablePrivilege;
void *ptr_pSetupEnablePrivilege = NULL;
extern void *ptr_pSetupFree;
void *ptr_pSetupFree = NULL;
extern void *ptr_pSetupGetCurrentDriverSigningPolicy;
void *ptr_pSetupGetCurrentDriverSigningPolicy = NULL;
extern void *ptr_pSetupGetDriverDate;
void *ptr_pSetupGetDriverDate = NULL;
extern void *ptr_pSetupGetDriverVersion;
void *ptr_pSetupGetDriverVersion = NULL;
extern void *ptr_pSetupGetField;
void *ptr_pSetupGetField = NULL;
extern void *ptr_pSetupGetFileTitle;
void *ptr_pSetupGetFileTitle = NULL;
extern void *ptr_pSetupGetGlobalFlags;
void *ptr_pSetupGetGlobalFlags = NULL;
extern void *ptr_pSetupGetIndirectStringsFromDriverInfo;
void *ptr_pSetupGetIndirectStringsFromDriverInfo = NULL;
extern void *ptr_pSetupGetInfSections;
void *ptr_pSetupGetInfSections = NULL;
extern void *ptr_pSetupGetQueueFlags;
void *ptr_pSetupGetQueueFlags = NULL;
extern void *ptr_pSetupGetRealSystemTime;
void *ptr_pSetupGetRealSystemTime = NULL;
extern void *ptr_pSetupGuidFromString;
void *ptr_pSetupGuidFromString = NULL;
extern void *ptr_pSetupHandleFailedVerification;
void *ptr_pSetupHandleFailedVerification = NULL;
extern void *ptr_pSetupInfGetDigitalSignatureInfo;
void *ptr_pSetupInfGetDigitalSignatureInfo = NULL;
extern void *ptr_pSetupInfIsInbox;
void *ptr_pSetupInfIsInbox = NULL;
extern void *ptr_pSetupInfSetDigitalSignatureInfo;
void *ptr_pSetupInfSetDigitalSignatureInfo = NULL;
extern void *ptr_pSetupInstallCatalog;
void *ptr_pSetupInstallCatalog = NULL;
extern void *ptr_pSetupIsBiDiLocalizedSystemEx;
void *ptr_pSetupIsBiDiLocalizedSystemEx = NULL;
extern void *ptr_pSetupIsGuidNull;
void *ptr_pSetupIsGuidNull = NULL;
extern void *ptr_pSetupIsLocalSystem;
void *ptr_pSetupIsLocalSystem = NULL;
extern void *ptr_pSetupIsUserAdmin;
void *ptr_pSetupIsUserAdmin = NULL;
extern void *ptr_pSetupIsUserTrustedInstaller;
void *ptr_pSetupIsUserTrustedInstaller = NULL;
extern void *ptr_pSetupLoadIndirectString;
void *ptr_pSetupLoadIndirectString = NULL;
extern void *ptr_pSetupMakeSurePathExists;
void *ptr_pSetupMakeSurePathExists = NULL;
extern void *ptr_pSetupMalloc;
void *ptr_pSetupMalloc = NULL;
extern void *ptr_pSetupModifyGlobalFlags;
void *ptr_pSetupModifyGlobalFlags = NULL;
extern void *ptr_pSetupMultiByteToUnicode;
void *ptr_pSetupMultiByteToUnicode = NULL;
extern void *ptr_pSetupOpenAndMapFileForRead;
void *ptr_pSetupOpenAndMapFileForRead = NULL;
extern void *ptr_pSetupOutOfMemory;
void *ptr_pSetupOutOfMemory = NULL;
extern void *ptr_pSetupQueryMultiSzValueToArray;
void *ptr_pSetupQueryMultiSzValueToArray = NULL;
extern void *ptr_pSetupRealloc;
void *ptr_pSetupRealloc = NULL;
extern void *ptr_pSetupRegistryDelnode;
void *ptr_pSetupRegistryDelnode = NULL;
extern void *ptr_pSetupRetrieveServiceConfig;
void *ptr_pSetupRetrieveServiceConfig = NULL;
extern void *ptr_pSetupSetArrayToMultiSzValue;
void *ptr_pSetupSetArrayToMultiSzValue = NULL;
extern void *ptr_pSetupSetDriverPackageRestorePoint;
void *ptr_pSetupSetDriverPackageRestorePoint = NULL;
extern void *ptr_pSetupSetGlobalFlags;
void *ptr_pSetupSetGlobalFlags = NULL;
extern void *ptr_pSetupSetQueueFlags;
void *ptr_pSetupSetQueueFlags = NULL;
extern void *ptr_pSetupShouldDeviceBeExcluded;
void *ptr_pSetupShouldDeviceBeExcluded = NULL;
extern void *ptr_pSetupStringFromGuid;
void *ptr_pSetupStringFromGuid = NULL;
extern void *ptr_pSetupStringTableAddString;
void *ptr_pSetupStringTableAddString = NULL;
extern void *ptr_pSetupStringTableAddStringEx;
void *ptr_pSetupStringTableAddStringEx = NULL;
extern void *ptr_pSetupStringTableDestroy;
void *ptr_pSetupStringTableDestroy = NULL;
extern void *ptr_pSetupStringTableDuplicate;
void *ptr_pSetupStringTableDuplicate = NULL;
extern void *ptr_pSetupStringTableEnum;
void *ptr_pSetupStringTableEnum = NULL;
extern void *ptr_pSetupStringTableGetExtraData;
void *ptr_pSetupStringTableGetExtraData = NULL;
extern void *ptr_pSetupStringTableInitialize;
void *ptr_pSetupStringTableInitialize = NULL;
extern void *ptr_pSetupStringTableInitializeEx;
void *ptr_pSetupStringTableInitializeEx = NULL;
extern void *ptr_pSetupStringTableLookUpString;
void *ptr_pSetupStringTableLookUpString = NULL;
extern void *ptr_pSetupStringTableLookUpStringEx;
void *ptr_pSetupStringTableLookUpStringEx = NULL;
extern void *ptr_pSetupStringTableSetExtraData;
void *ptr_pSetupStringTableSetExtraData = NULL;
extern void *ptr_pSetupStringTableStringFromId;
void *ptr_pSetupStringTableStringFromId = NULL;
extern void *ptr_pSetupStringTableStringFromIdEx;
void *ptr_pSetupStringTableStringFromIdEx = NULL;
extern void *ptr_pSetupUnicodeToMultiByte;
void *ptr_pSetupUnicodeToMultiByte = NULL;
extern void *ptr_pSetupUnmapAndCloseFile;
void *ptr_pSetupUnmapAndCloseFile = NULL;
extern void *ptr_pSetupValidateDriverPackage;
void *ptr_pSetupValidateDriverPackage = NULL;
extern void *ptr_pSetupVerifyCatalogFile;
void *ptr_pSetupVerifyCatalogFile = NULL;
extern void *ptr_pSetupVerifyQueuedCatalogs;
void *ptr_pSetupVerifyQueuedCatalogs = NULL;
extern void *ptr_pSetupWriteLogEntry;
void *ptr_pSetupWriteLogEntry = NULL;
extern void *ptr_pSetupWriteLogError;
void *ptr_pSetupWriteLogError = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\setupapi.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_CM_Apply_PowerScheme = (__vartype(ptr_CM_Apply_PowerScheme))GetProcAddress(hModule, "CM_Apply_PowerScheme");
   ptr_CM_Delete_PowerScheme = (__vartype(ptr_CM_Delete_PowerScheme))GetProcAddress(hModule, "CM_Delete_PowerScheme");
   ptr_CM_Duplicate_PowerScheme = (__vartype(ptr_CM_Duplicate_PowerScheme))GetProcAddress(hModule, "CM_Duplicate_PowerScheme");
   ptr_CM_Import_PowerScheme = (__vartype(ptr_CM_Import_PowerScheme))GetProcAddress(hModule, "CM_Import_PowerScheme");
   ptr_CM_RestoreAll_DefaultPowerSchemes = (__vartype(ptr_CM_RestoreAll_DefaultPowerSchemes))GetProcAddress(hModule, "CM_RestoreAll_DefaultPowerSchemes");
   ptr_CM_Restore_DefaultPowerScheme = (__vartype(ptr_CM_Restore_DefaultPowerScheme))GetProcAddress(hModule, "CM_Restore_DefaultPowerScheme");
   ptr_CM_Set_ActiveScheme = (__vartype(ptr_CM_Set_ActiveScheme))GetProcAddress(hModule, "CM_Set_ActiveScheme");
   ptr_CM_Write_UserPowerKey = (__vartype(ptr_CM_Write_UserPowerKey))GetProcAddress(hModule, "CM_Write_UserPowerKey");
   ptr_DoesUserHavePrivilege = (__vartype(ptr_DoesUserHavePrivilege))GetProcAddress(hModule, "DoesUserHavePrivilege");
   ptr_DriverStoreAddDriverPackageA = (__vartype(ptr_DriverStoreAddDriverPackageA))GetProcAddress(hModule, "DriverStoreAddDriverPackageA");
   ptr_DriverStoreAddDriverPackageW = (__vartype(ptr_DriverStoreAddDriverPackageW))GetProcAddress(hModule, "DriverStoreAddDriverPackageW");
   ptr_DriverStoreDeleteDriverPackageA = (__vartype(ptr_DriverStoreDeleteDriverPackageA))GetProcAddress(hModule, "DriverStoreDeleteDriverPackageA");
   ptr_DriverStoreDeleteDriverPackageW = (__vartype(ptr_DriverStoreDeleteDriverPackageW))GetProcAddress(hModule, "DriverStoreDeleteDriverPackageW");
   ptr_DriverStoreEnumDriverPackageA = (__vartype(ptr_DriverStoreEnumDriverPackageA))GetProcAddress(hModule, "DriverStoreEnumDriverPackageA");
   ptr_DriverStoreEnumDriverPackageW = (__vartype(ptr_DriverStoreEnumDriverPackageW))GetProcAddress(hModule, "DriverStoreEnumDriverPackageW");
   ptr_DriverStoreFindDriverPackageA = (__vartype(ptr_DriverStoreFindDriverPackageA))GetProcAddress(hModule, "DriverStoreFindDriverPackageA");
   ptr_DriverStoreFindDriverPackageW = (__vartype(ptr_DriverStoreFindDriverPackageW))GetProcAddress(hModule, "DriverStoreFindDriverPackageW");
   ptr_ExtensionPropSheetPageProc = (__vartype(ptr_ExtensionPropSheetPageProc))GetProcAddress(hModule, "ExtensionPropSheetPageProc");
   ptr_InstallCatalog = (__vartype(ptr_InstallCatalog))GetProcAddress(hModule, "InstallCatalog");
   ptr_InstallHinfSection = (__vartype(ptr_InstallHinfSection))GetProcAddress(hModule, "InstallHinfSection");
   ptr_InstallHinfSectionA = (__vartype(ptr_InstallHinfSectionA))GetProcAddress(hModule, "InstallHinfSectionA");
   ptr_InstallHinfSectionW = (__vartype(ptr_InstallHinfSectionW))GetProcAddress(hModule, "InstallHinfSectionW");
   ptr_IsUserAdmin = (__vartype(ptr_IsUserAdmin))GetProcAddress(hModule, "IsUserAdmin");
   ptr_MyFree = (__vartype(ptr_MyFree))GetProcAddress(hModule, "MyFree");
   ptr_MyMalloc = (__vartype(ptr_MyMalloc))GetProcAddress(hModule, "MyMalloc");
   ptr_MyRealloc = (__vartype(ptr_MyRealloc))GetProcAddress(hModule, "MyRealloc");
   ptr_PnpEnumDrpFile = (__vartype(ptr_PnpEnumDrpFile))GetProcAddress(hModule, "PnpEnumDrpFile");
   ptr_PnpIsFileAclIntact = (__vartype(ptr_PnpIsFileAclIntact))GetProcAddress(hModule, "PnpIsFileAclIntact");
   ptr_PnpIsFileContentIntact = (__vartype(ptr_PnpIsFileContentIntact))GetProcAddress(hModule, "PnpIsFileContentIntact");
   ptr_PnpIsFilePnpDriver = (__vartype(ptr_PnpIsFilePnpDriver))GetProcAddress(hModule, "PnpIsFilePnpDriver");
   ptr_PnpRepairWindowsProtectedDriver = (__vartype(ptr_PnpRepairWindowsProtectedDriver))GetProcAddress(hModule, "PnpRepairWindowsProtectedDriver");
   ptr_SetupAddInstallSectionToDiskSpaceListA = (__vartype(ptr_SetupAddInstallSectionToDiskSpaceListA))GetProcAddress(hModule, "SetupAddInstallSectionToDiskSpaceListA");
   ptr_SetupAddInstallSectionToDiskSpaceListW = (__vartype(ptr_SetupAddInstallSectionToDiskSpaceListW))GetProcAddress(hModule, "SetupAddInstallSectionToDiskSpaceListW");
   ptr_SetupAddSectionToDiskSpaceListA = (__vartype(ptr_SetupAddSectionToDiskSpaceListA))GetProcAddress(hModule, "SetupAddSectionToDiskSpaceListA");
   ptr_SetupAddSectionToDiskSpaceListW = (__vartype(ptr_SetupAddSectionToDiskSpaceListW))GetProcAddress(hModule, "SetupAddSectionToDiskSpaceListW");
   ptr_SetupAddToDiskSpaceListA = (__vartype(ptr_SetupAddToDiskSpaceListA))GetProcAddress(hModule, "SetupAddToDiskSpaceListA");
   ptr_SetupAddToDiskSpaceListW = (__vartype(ptr_SetupAddToDiskSpaceListW))GetProcAddress(hModule, "SetupAddToDiskSpaceListW");
   ptr_SetupAddToSourceListA = (__vartype(ptr_SetupAddToSourceListA))GetProcAddress(hModule, "SetupAddToSourceListA");
   ptr_SetupAddToSourceListW = (__vartype(ptr_SetupAddToSourceListW))GetProcAddress(hModule, "SetupAddToSourceListW");
   ptr_SetupAdjustDiskSpaceListA = (__vartype(ptr_SetupAdjustDiskSpaceListA))GetProcAddress(hModule, "SetupAdjustDiskSpaceListA");
   ptr_SetupAdjustDiskSpaceListW = (__vartype(ptr_SetupAdjustDiskSpaceListW))GetProcAddress(hModule, "SetupAdjustDiskSpaceListW");
   ptr_SetupBackupErrorA = (__vartype(ptr_SetupBackupErrorA))GetProcAddress(hModule, "SetupBackupErrorA");
   ptr_SetupBackupErrorW = (__vartype(ptr_SetupBackupErrorW))GetProcAddress(hModule, "SetupBackupErrorW");
   ptr_SetupCancelTemporarySourceList = (__vartype(ptr_SetupCancelTemporarySourceList))GetProcAddress(hModule, "SetupCancelTemporarySourceList");
   ptr_SetupCloseFileQueue = (__vartype(ptr_SetupCloseFileQueue))GetProcAddress(hModule, "SetupCloseFileQueue");
   ptr_SetupCloseInfFile = (__vartype(ptr_SetupCloseInfFile))GetProcAddress(hModule, "SetupCloseInfFile");
   ptr_SetupCloseLog = (__vartype(ptr_SetupCloseLog))GetProcAddress(hModule, "SetupCloseLog");
   ptr_SetupCommitFileQueue = (__vartype(ptr_SetupCommitFileQueue))GetProcAddress(hModule, "SetupCommitFileQueue");
   ptr_SetupCommitFileQueueA = (__vartype(ptr_SetupCommitFileQueueA))GetProcAddress(hModule, "SetupCommitFileQueueA");
   ptr_SetupCommitFileQueueW = (__vartype(ptr_SetupCommitFileQueueW))GetProcAddress(hModule, "SetupCommitFileQueueW");
   ptr_SetupConfigureWmiFromInfSectionA = (__vartype(ptr_SetupConfigureWmiFromInfSectionA))GetProcAddress(hModule, "SetupConfigureWmiFromInfSectionA");
   ptr_SetupConfigureWmiFromInfSectionW = (__vartype(ptr_SetupConfigureWmiFromInfSectionW))GetProcAddress(hModule, "SetupConfigureWmiFromInfSectionW");
   ptr_SetupCopyErrorA = (__vartype(ptr_SetupCopyErrorA))GetProcAddress(hModule, "SetupCopyErrorA");
   ptr_SetupCopyErrorW = (__vartype(ptr_SetupCopyErrorW))GetProcAddress(hModule, "SetupCopyErrorW");
   ptr_SetupCopyOEMInfA = (__vartype(ptr_SetupCopyOEMInfA))GetProcAddress(hModule, "SetupCopyOEMInfA");
   ptr_SetupCopyOEMInfW = (__vartype(ptr_SetupCopyOEMInfW))GetProcAddress(hModule, "SetupCopyOEMInfW");
   ptr_SetupCreateDiskSpaceListA = (__vartype(ptr_SetupCreateDiskSpaceListA))GetProcAddress(hModule, "SetupCreateDiskSpaceListA");
   ptr_SetupCreateDiskSpaceListW = (__vartype(ptr_SetupCreateDiskSpaceListW))GetProcAddress(hModule, "SetupCreateDiskSpaceListW");
   ptr_SetupDecompressOrCopyFileA = (__vartype(ptr_SetupDecompressOrCopyFileA))GetProcAddress(hModule, "SetupDecompressOrCopyFileA");
   ptr_SetupDecompressOrCopyFileW = (__vartype(ptr_SetupDecompressOrCopyFileW))GetProcAddress(hModule, "SetupDecompressOrCopyFileW");
   ptr_SetupDefaultQueueCallback = (__vartype(ptr_SetupDefaultQueueCallback))GetProcAddress(hModule, "SetupDefaultQueueCallback");
   ptr_SetupDefaultQueueCallbackA = (__vartype(ptr_SetupDefaultQueueCallbackA))GetProcAddress(hModule, "SetupDefaultQueueCallbackA");
   ptr_SetupDefaultQueueCallbackW = (__vartype(ptr_SetupDefaultQueueCallbackW))GetProcAddress(hModule, "SetupDefaultQueueCallbackW");
   ptr_SetupDeleteErrorA = (__vartype(ptr_SetupDeleteErrorA))GetProcAddress(hModule, "SetupDeleteErrorA");
   ptr_SetupDeleteErrorW = (__vartype(ptr_SetupDeleteErrorW))GetProcAddress(hModule, "SetupDeleteErrorW");
   ptr_SetupDestroyDiskSpaceList = (__vartype(ptr_SetupDestroyDiskSpaceList))GetProcAddress(hModule, "SetupDestroyDiskSpaceList");
   ptr_SetupDiApplyPowerScheme = (__vartype(ptr_SetupDiApplyPowerScheme))GetProcAddress(hModule, "SetupDiApplyPowerScheme");
   ptr_SetupDiAskForOEMDisk = (__vartype(ptr_SetupDiAskForOEMDisk))GetProcAddress(hModule, "SetupDiAskForOEMDisk");
   ptr_SetupDiBuildClassInfoList = (__vartype(ptr_SetupDiBuildClassInfoList))GetProcAddress(hModule, "SetupDiBuildClassInfoList");
   ptr_SetupDiBuildClassInfoListExA = (__vartype(ptr_SetupDiBuildClassInfoListExA))GetProcAddress(hModule, "SetupDiBuildClassInfoListExA");
   ptr_SetupDiBuildClassInfoListExW = (__vartype(ptr_SetupDiBuildClassInfoListExW))GetProcAddress(hModule, "SetupDiBuildClassInfoListExW");
   ptr_SetupDiBuildDriverInfoList = (__vartype(ptr_SetupDiBuildDriverInfoList))GetProcAddress(hModule, "SetupDiBuildDriverInfoList");
   ptr_SetupDiCallClassInstaller = (__vartype(ptr_SetupDiCallClassInstaller))GetProcAddress(hModule, "SetupDiCallClassInstaller");
   ptr_SetupDiCancelDriverInfoSearch = (__vartype(ptr_SetupDiCancelDriverInfoSearch))GetProcAddress(hModule, "SetupDiCancelDriverInfoSearch");
   ptr_SetupDiChangeState = (__vartype(ptr_SetupDiChangeState))GetProcAddress(hModule, "SetupDiChangeState");
   ptr_SetupDiClassGuidsFromNameA = (__vartype(ptr_SetupDiClassGuidsFromNameA))GetProcAddress(hModule, "SetupDiClassGuidsFromNameA");
   ptr_SetupDiClassGuidsFromNameExA = (__vartype(ptr_SetupDiClassGuidsFromNameExA))GetProcAddress(hModule, "SetupDiClassGuidsFromNameExA");
   ptr_SetupDiClassGuidsFromNameExW = (__vartype(ptr_SetupDiClassGuidsFromNameExW))GetProcAddress(hModule, "SetupDiClassGuidsFromNameExW");
   ptr_SetupDiClassGuidsFromNameW = (__vartype(ptr_SetupDiClassGuidsFromNameW))GetProcAddress(hModule, "SetupDiClassGuidsFromNameW");
   ptr_SetupDiClassNameFromGuidA = (__vartype(ptr_SetupDiClassNameFromGuidA))GetProcAddress(hModule, "SetupDiClassNameFromGuidA");
   ptr_SetupDiClassNameFromGuidExA = (__vartype(ptr_SetupDiClassNameFromGuidExA))GetProcAddress(hModule, "SetupDiClassNameFromGuidExA");
   ptr_SetupDiClassNameFromGuidExW = (__vartype(ptr_SetupDiClassNameFromGuidExW))GetProcAddress(hModule, "SetupDiClassNameFromGuidExW");
   ptr_SetupDiClassNameFromGuidW = (__vartype(ptr_SetupDiClassNameFromGuidW))GetProcAddress(hModule, "SetupDiClassNameFromGuidW");
   ptr_SetupDiCreateDevRegKeyA = (__vartype(ptr_SetupDiCreateDevRegKeyA))GetProcAddress(hModule, "SetupDiCreateDevRegKeyA");
   ptr_SetupDiCreateDevRegKeyW = (__vartype(ptr_SetupDiCreateDevRegKeyW))GetProcAddress(hModule, "SetupDiCreateDevRegKeyW");
   ptr_SetupDiCreateDeviceInfoA = (__vartype(ptr_SetupDiCreateDeviceInfoA))GetProcAddress(hModule, "SetupDiCreateDeviceInfoA");
   ptr_SetupDiCreateDeviceInfoList = (__vartype(ptr_SetupDiCreateDeviceInfoList))GetProcAddress(hModule, "SetupDiCreateDeviceInfoList");
   ptr_SetupDiCreateDeviceInfoListExA = (__vartype(ptr_SetupDiCreateDeviceInfoListExA))GetProcAddress(hModule, "SetupDiCreateDeviceInfoListExA");
   ptr_SetupDiCreateDeviceInfoListExW = (__vartype(ptr_SetupDiCreateDeviceInfoListExW))GetProcAddress(hModule, "SetupDiCreateDeviceInfoListExW");
   ptr_SetupDiCreateDeviceInfoW = (__vartype(ptr_SetupDiCreateDeviceInfoW))GetProcAddress(hModule, "SetupDiCreateDeviceInfoW");
   ptr_SetupDiCreateDeviceInterfaceA = (__vartype(ptr_SetupDiCreateDeviceInterfaceA))GetProcAddress(hModule, "SetupDiCreateDeviceInterfaceA");
   ptr_SetupDiCreateDeviceInterfaceRegKeyA = (__vartype(ptr_SetupDiCreateDeviceInterfaceRegKeyA))GetProcAddress(hModule, "SetupDiCreateDeviceInterfaceRegKeyA");
   ptr_SetupDiCreateDeviceInterfaceRegKeyW = (__vartype(ptr_SetupDiCreateDeviceInterfaceRegKeyW))GetProcAddress(hModule, "SetupDiCreateDeviceInterfaceRegKeyW");
   ptr_SetupDiCreateDeviceInterfaceW = (__vartype(ptr_SetupDiCreateDeviceInterfaceW))GetProcAddress(hModule, "SetupDiCreateDeviceInterfaceW");
   ptr_SetupDiDeleteDevRegKey = (__vartype(ptr_SetupDiDeleteDevRegKey))GetProcAddress(hModule, "SetupDiDeleteDevRegKey");
   ptr_SetupDiDeleteDeviceInfo = (__vartype(ptr_SetupDiDeleteDeviceInfo))GetProcAddress(hModule, "SetupDiDeleteDeviceInfo");
   ptr_SetupDiDeleteDeviceInterfaceData = (__vartype(ptr_SetupDiDeleteDeviceInterfaceData))GetProcAddress(hModule, "SetupDiDeleteDeviceInterfaceData");
   ptr_SetupDiDeleteDeviceInterfaceRegKey = (__vartype(ptr_SetupDiDeleteDeviceInterfaceRegKey))GetProcAddress(hModule, "SetupDiDeleteDeviceInterfaceRegKey");
   ptr_SetupDiDestroyClassImageList = (__vartype(ptr_SetupDiDestroyClassImageList))GetProcAddress(hModule, "SetupDiDestroyClassImageList");
   ptr_SetupDiDestroyDeviceInfoList = (__vartype(ptr_SetupDiDestroyDeviceInfoList))GetProcAddress(hModule, "SetupDiDestroyDeviceInfoList");
   ptr_SetupDiDestroyDriverInfoList = (__vartype(ptr_SetupDiDestroyDriverInfoList))GetProcAddress(hModule, "SetupDiDestroyDriverInfoList");
   ptr_SetupDiDrawMiniIcon = (__vartype(ptr_SetupDiDrawMiniIcon))GetProcAddress(hModule, "SetupDiDrawMiniIcon");
   ptr_SetupDiEnumDeviceInfo = (__vartype(ptr_SetupDiEnumDeviceInfo))GetProcAddress(hModule, "SetupDiEnumDeviceInfo");
   ptr_SetupDiEnumDeviceInterfaces = (__vartype(ptr_SetupDiEnumDeviceInterfaces))GetProcAddress(hModule, "SetupDiEnumDeviceInterfaces");
   ptr_SetupDiEnumDriverInfoA = (__vartype(ptr_SetupDiEnumDriverInfoA))GetProcAddress(hModule, "SetupDiEnumDriverInfoA");
   ptr_SetupDiEnumDriverInfoW = (__vartype(ptr_SetupDiEnumDriverInfoW))GetProcAddress(hModule, "SetupDiEnumDriverInfoW");
   ptr_SetupDiGetActualModelsSectionA = (__vartype(ptr_SetupDiGetActualModelsSectionA))GetProcAddress(hModule, "SetupDiGetActualModelsSectionA");
   ptr_SetupDiGetActualModelsSectionW = (__vartype(ptr_SetupDiGetActualModelsSectionW))GetProcAddress(hModule, "SetupDiGetActualModelsSectionW");
   ptr_SetupDiGetActualSectionToInstallA = (__vartype(ptr_SetupDiGetActualSectionToInstallA))GetProcAddress(hModule, "SetupDiGetActualSectionToInstallA");
   ptr_SetupDiGetActualSectionToInstallExA = (__vartype(ptr_SetupDiGetActualSectionToInstallExA))GetProcAddress(hModule, "SetupDiGetActualSectionToInstallExA");
   ptr_SetupDiGetActualSectionToInstallExW = (__vartype(ptr_SetupDiGetActualSectionToInstallExW))GetProcAddress(hModule, "SetupDiGetActualSectionToInstallExW");
   ptr_SetupDiGetActualSectionToInstallW = (__vartype(ptr_SetupDiGetActualSectionToInstallW))GetProcAddress(hModule, "SetupDiGetActualSectionToInstallW");
   ptr_SetupDiGetClassBitmapIndex = (__vartype(ptr_SetupDiGetClassBitmapIndex))GetProcAddress(hModule, "SetupDiGetClassBitmapIndex");
   ptr_SetupDiGetClassDescriptionA = (__vartype(ptr_SetupDiGetClassDescriptionA))GetProcAddress(hModule, "SetupDiGetClassDescriptionA");
   ptr_SetupDiGetClassDescriptionExA = (__vartype(ptr_SetupDiGetClassDescriptionExA))GetProcAddress(hModule, "SetupDiGetClassDescriptionExA");
   ptr_SetupDiGetClassDescriptionExW = (__vartype(ptr_SetupDiGetClassDescriptionExW))GetProcAddress(hModule, "SetupDiGetClassDescriptionExW");
   ptr_SetupDiGetClassDescriptionW = (__vartype(ptr_SetupDiGetClassDescriptionW))GetProcAddress(hModule, "SetupDiGetClassDescriptionW");
   ptr_SetupDiGetClassDevPropertySheetsA = (__vartype(ptr_SetupDiGetClassDevPropertySheetsA))GetProcAddress(hModule, "SetupDiGetClassDevPropertySheetsA");
   ptr_SetupDiGetClassDevPropertySheetsW = (__vartype(ptr_SetupDiGetClassDevPropertySheetsW))GetProcAddress(hModule, "SetupDiGetClassDevPropertySheetsW");
   ptr_SetupDiGetClassDevsA = (__vartype(ptr_SetupDiGetClassDevsA))GetProcAddress(hModule, "SetupDiGetClassDevsA");
   ptr_SetupDiGetClassDevsExA = (__vartype(ptr_SetupDiGetClassDevsExA))GetProcAddress(hModule, "SetupDiGetClassDevsExA");
   ptr_SetupDiGetClassDevsExW = (__vartype(ptr_SetupDiGetClassDevsExW))GetProcAddress(hModule, "SetupDiGetClassDevsExW");
   ptr_SetupDiGetClassDevsW = (__vartype(ptr_SetupDiGetClassDevsW))GetProcAddress(hModule, "SetupDiGetClassDevsW");
   ptr_SetupDiGetClassImageIndex = (__vartype(ptr_SetupDiGetClassImageIndex))GetProcAddress(hModule, "SetupDiGetClassImageIndex");
   ptr_SetupDiGetClassImageList = (__vartype(ptr_SetupDiGetClassImageList))GetProcAddress(hModule, "SetupDiGetClassImageList");
   ptr_SetupDiGetClassImageListExA = (__vartype(ptr_SetupDiGetClassImageListExA))GetProcAddress(hModule, "SetupDiGetClassImageListExA");
   ptr_SetupDiGetClassImageListExW = (__vartype(ptr_SetupDiGetClassImageListExW))GetProcAddress(hModule, "SetupDiGetClassImageListExW");
   ptr_SetupDiGetClassInstallParamsA = (__vartype(ptr_SetupDiGetClassInstallParamsA))GetProcAddress(hModule, "SetupDiGetClassInstallParamsA");
   ptr_SetupDiGetClassInstallParamsW = (__vartype(ptr_SetupDiGetClassInstallParamsW))GetProcAddress(hModule, "SetupDiGetClassInstallParamsW");
   ptr_SetupDiGetClassPropertyExW = (__vartype(ptr_SetupDiGetClassPropertyExW))GetProcAddress(hModule, "SetupDiGetClassPropertyExW");
   ptr_SetupDiGetClassPropertyKeys = (__vartype(ptr_SetupDiGetClassPropertyKeys))GetProcAddress(hModule, "SetupDiGetClassPropertyKeys");
   ptr_SetupDiGetClassPropertyKeysExW = (__vartype(ptr_SetupDiGetClassPropertyKeysExW))GetProcAddress(hModule, "SetupDiGetClassPropertyKeysExW");
   ptr_SetupDiGetClassPropertyW = (__vartype(ptr_SetupDiGetClassPropertyW))GetProcAddress(hModule, "SetupDiGetClassPropertyW");
   ptr_SetupDiGetClassRegistryPropertyA = (__vartype(ptr_SetupDiGetClassRegistryPropertyA))GetProcAddress(hModule, "SetupDiGetClassRegistryPropertyA");
   ptr_SetupDiGetClassRegistryPropertyW = (__vartype(ptr_SetupDiGetClassRegistryPropertyW))GetProcAddress(hModule, "SetupDiGetClassRegistryPropertyW");
   ptr_SetupDiGetCustomDevicePropertyA = (__vartype(ptr_SetupDiGetCustomDevicePropertyA))GetProcAddress(hModule, "SetupDiGetCustomDevicePropertyA");
   ptr_SetupDiGetCustomDevicePropertyW = (__vartype(ptr_SetupDiGetCustomDevicePropertyW))GetProcAddress(hModule, "SetupDiGetCustomDevicePropertyW");
   ptr_SetupDiGetDeviceInfoListClass = (__vartype(ptr_SetupDiGetDeviceInfoListClass))GetProcAddress(hModule, "SetupDiGetDeviceInfoListClass");
   ptr_SetupDiGetDeviceInfoListDetailA = (__vartype(ptr_SetupDiGetDeviceInfoListDetailA))GetProcAddress(hModule, "SetupDiGetDeviceInfoListDetailA");
   ptr_SetupDiGetDeviceInfoListDetailW = (__vartype(ptr_SetupDiGetDeviceInfoListDetailW))GetProcAddress(hModule, "SetupDiGetDeviceInfoListDetailW");
   ptr_SetupDiGetDeviceInstallParamsA = (__vartype(ptr_SetupDiGetDeviceInstallParamsA))GetProcAddress(hModule, "SetupDiGetDeviceInstallParamsA");
   ptr_SetupDiGetDeviceInstallParamsW = (__vartype(ptr_SetupDiGetDeviceInstallParamsW))GetProcAddress(hModule, "SetupDiGetDeviceInstallParamsW");
   ptr_SetupDiGetDeviceInstanceIdA = (__vartype(ptr_SetupDiGetDeviceInstanceIdA))GetProcAddress(hModule, "SetupDiGetDeviceInstanceIdA");
   ptr_SetupDiGetDeviceInstanceIdW = (__vartype(ptr_SetupDiGetDeviceInstanceIdW))GetProcAddress(hModule, "SetupDiGetDeviceInstanceIdW");
   ptr_SetupDiGetDeviceInterfaceAlias = (__vartype(ptr_SetupDiGetDeviceInterfaceAlias))GetProcAddress(hModule, "SetupDiGetDeviceInterfaceAlias");
   ptr_SetupDiGetDeviceInterfaceDetailA = (__vartype(ptr_SetupDiGetDeviceInterfaceDetailA))GetProcAddress(hModule, "SetupDiGetDeviceInterfaceDetailA");
   ptr_SetupDiGetDeviceInterfaceDetailW = (__vartype(ptr_SetupDiGetDeviceInterfaceDetailW))GetProcAddress(hModule, "SetupDiGetDeviceInterfaceDetailW");
   ptr_SetupDiGetDeviceInterfacePropertyKeys = (__vartype(ptr_SetupDiGetDeviceInterfacePropertyKeys))GetProcAddress(hModule, "SetupDiGetDeviceInterfacePropertyKeys");
   ptr_SetupDiGetDeviceInterfacePropertyW = (__vartype(ptr_SetupDiGetDeviceInterfacePropertyW))GetProcAddress(hModule, "SetupDiGetDeviceInterfacePropertyW");
   ptr_SetupDiGetDevicePropertyKeys = (__vartype(ptr_SetupDiGetDevicePropertyKeys))GetProcAddress(hModule, "SetupDiGetDevicePropertyKeys");
   ptr_SetupDiGetDevicePropertyW = (__vartype(ptr_SetupDiGetDevicePropertyW))GetProcAddress(hModule, "SetupDiGetDevicePropertyW");
   ptr_SetupDiGetDeviceRegistryPropertyA = (__vartype(ptr_SetupDiGetDeviceRegistryPropertyA))GetProcAddress(hModule, "SetupDiGetDeviceRegistryPropertyA");
   ptr_SetupDiGetDeviceRegistryPropertyW = (__vartype(ptr_SetupDiGetDeviceRegistryPropertyW))GetProcAddress(hModule, "SetupDiGetDeviceRegistryPropertyW");
   ptr_SetupDiGetDriverInfoDetailA = (__vartype(ptr_SetupDiGetDriverInfoDetailA))GetProcAddress(hModule, "SetupDiGetDriverInfoDetailA");
   ptr_SetupDiGetDriverInfoDetailW = (__vartype(ptr_SetupDiGetDriverInfoDetailW))GetProcAddress(hModule, "SetupDiGetDriverInfoDetailW");
   ptr_SetupDiGetDriverInstallParamsA = (__vartype(ptr_SetupDiGetDriverInstallParamsA))GetProcAddress(hModule, "SetupDiGetDriverInstallParamsA");
   ptr_SetupDiGetDriverInstallParamsW = (__vartype(ptr_SetupDiGetDriverInstallParamsW))GetProcAddress(hModule, "SetupDiGetDriverInstallParamsW");
   ptr_SetupDiGetHwProfileFriendlyNameA = (__vartype(ptr_SetupDiGetHwProfileFriendlyNameA))GetProcAddress(hModule, "SetupDiGetHwProfileFriendlyNameA");
   ptr_SetupDiGetHwProfileFriendlyNameExA = (__vartype(ptr_SetupDiGetHwProfileFriendlyNameExA))GetProcAddress(hModule, "SetupDiGetHwProfileFriendlyNameExA");
   ptr_SetupDiGetHwProfileFriendlyNameExW = (__vartype(ptr_SetupDiGetHwProfileFriendlyNameExW))GetProcAddress(hModule, "SetupDiGetHwProfileFriendlyNameExW");
   ptr_SetupDiGetHwProfileFriendlyNameW = (__vartype(ptr_SetupDiGetHwProfileFriendlyNameW))GetProcAddress(hModule, "SetupDiGetHwProfileFriendlyNameW");
   ptr_SetupDiGetHwProfileList = (__vartype(ptr_SetupDiGetHwProfileList))GetProcAddress(hModule, "SetupDiGetHwProfileList");
   ptr_SetupDiGetHwProfileListExA = (__vartype(ptr_SetupDiGetHwProfileListExA))GetProcAddress(hModule, "SetupDiGetHwProfileListExA");
   ptr_SetupDiGetHwProfileListExW = (__vartype(ptr_SetupDiGetHwProfileListExW))GetProcAddress(hModule, "SetupDiGetHwProfileListExW");
   ptr_SetupDiGetINFClassA = (__vartype(ptr_SetupDiGetINFClassA))GetProcAddress(hModule, "SetupDiGetINFClassA");
   ptr_SetupDiGetINFClassW = (__vartype(ptr_SetupDiGetINFClassW))GetProcAddress(hModule, "SetupDiGetINFClassW");
   ptr_SetupDiGetSelectedDevice = (__vartype(ptr_SetupDiGetSelectedDevice))GetProcAddress(hModule, "SetupDiGetSelectedDevice");
   ptr_SetupDiGetSelectedDriverA = (__vartype(ptr_SetupDiGetSelectedDriverA))GetProcAddress(hModule, "SetupDiGetSelectedDriverA");
   ptr_SetupDiGetSelectedDriverW = (__vartype(ptr_SetupDiGetSelectedDriverW))GetProcAddress(hModule, "SetupDiGetSelectedDriverW");
   ptr_SetupDiGetWizardPage = (__vartype(ptr_SetupDiGetWizardPage))GetProcAddress(hModule, "SetupDiGetWizardPage");
   ptr_SetupDiInstallClassA = (__vartype(ptr_SetupDiInstallClassA))GetProcAddress(hModule, "SetupDiInstallClassA");
   ptr_SetupDiInstallClassExA = (__vartype(ptr_SetupDiInstallClassExA))GetProcAddress(hModule, "SetupDiInstallClassExA");
   ptr_SetupDiInstallClassExW = (__vartype(ptr_SetupDiInstallClassExW))GetProcAddress(hModule, "SetupDiInstallClassExW");
   ptr_SetupDiInstallClassW = (__vartype(ptr_SetupDiInstallClassW))GetProcAddress(hModule, "SetupDiInstallClassW");
   ptr_SetupDiInstallDevice = (__vartype(ptr_SetupDiInstallDevice))GetProcAddress(hModule, "SetupDiInstallDevice");
   ptr_SetupDiInstallDeviceInterfaces = (__vartype(ptr_SetupDiInstallDeviceInterfaces))GetProcAddress(hModule, "SetupDiInstallDeviceInterfaces");
   ptr_SetupDiInstallDriverFiles = (__vartype(ptr_SetupDiInstallDriverFiles))GetProcAddress(hModule, "SetupDiInstallDriverFiles");
   ptr_SetupDiLoadClassIcon = (__vartype(ptr_SetupDiLoadClassIcon))GetProcAddress(hModule, "SetupDiLoadClassIcon");
   ptr_SetupDiLoadDeviceIcon = (__vartype(ptr_SetupDiLoadDeviceIcon))GetProcAddress(hModule, "SetupDiLoadDeviceIcon");
   ptr_SetupDiMoveDuplicateDevice = (__vartype(ptr_SetupDiMoveDuplicateDevice))GetProcAddress(hModule, "SetupDiMoveDuplicateDevice");
   ptr_SetupDiOpenClassRegKey = (__vartype(ptr_SetupDiOpenClassRegKey))GetProcAddress(hModule, "SetupDiOpenClassRegKey");
   ptr_SetupDiOpenClassRegKeyExA = (__vartype(ptr_SetupDiOpenClassRegKeyExA))GetProcAddress(hModule, "SetupDiOpenClassRegKeyExA");
   ptr_SetupDiOpenClassRegKeyExW = (__vartype(ptr_SetupDiOpenClassRegKeyExW))GetProcAddress(hModule, "SetupDiOpenClassRegKeyExW");
   ptr_SetupDiOpenDevRegKey = (__vartype(ptr_SetupDiOpenDevRegKey))GetProcAddress(hModule, "SetupDiOpenDevRegKey");
   ptr_SetupDiOpenDeviceInfoA = (__vartype(ptr_SetupDiOpenDeviceInfoA))GetProcAddress(hModule, "SetupDiOpenDeviceInfoA");
   ptr_SetupDiOpenDeviceInfoW = (__vartype(ptr_SetupDiOpenDeviceInfoW))GetProcAddress(hModule, "SetupDiOpenDeviceInfoW");
   ptr_SetupDiOpenDeviceInterfaceA = (__vartype(ptr_SetupDiOpenDeviceInterfaceA))GetProcAddress(hModule, "SetupDiOpenDeviceInterfaceA");
   ptr_SetupDiOpenDeviceInterfaceRegKey = (__vartype(ptr_SetupDiOpenDeviceInterfaceRegKey))GetProcAddress(hModule, "SetupDiOpenDeviceInterfaceRegKey");
   ptr_SetupDiOpenDeviceInterfaceW = (__vartype(ptr_SetupDiOpenDeviceInterfaceW))GetProcAddress(hModule, "SetupDiOpenDeviceInterfaceW");
   ptr_SetupDiRegisterCoDeviceInstallers = (__vartype(ptr_SetupDiRegisterCoDeviceInstallers))GetProcAddress(hModule, "SetupDiRegisterCoDeviceInstallers");
   ptr_SetupDiRegisterDeviceInfo = (__vartype(ptr_SetupDiRegisterDeviceInfo))GetProcAddress(hModule, "SetupDiRegisterDeviceInfo");
   ptr_SetupDiRemoveDevice = (__vartype(ptr_SetupDiRemoveDevice))GetProcAddress(hModule, "SetupDiRemoveDevice");
   ptr_SetupDiRemoveDeviceInterface = (__vartype(ptr_SetupDiRemoveDeviceInterface))GetProcAddress(hModule, "SetupDiRemoveDeviceInterface");
   ptr_SetupDiReportAdditionalSoftwareRequested = (__vartype(ptr_SetupDiReportAdditionalSoftwareRequested))GetProcAddress(hModule, "SetupDiReportAdditionalSoftwareRequested");
   ptr_SetupDiReportDeviceInstallError = (__vartype(ptr_SetupDiReportDeviceInstallError))GetProcAddress(hModule, "SetupDiReportDeviceInstallError");
   ptr_SetupDiReportDriverNotFoundError = (__vartype(ptr_SetupDiReportDriverNotFoundError))GetProcAddress(hModule, "SetupDiReportDriverNotFoundError");
   ptr_SetupDiReportDriverPackageImportationError = (__vartype(ptr_SetupDiReportDriverPackageImportationError))GetProcAddress(hModule, "SetupDiReportDriverPackageImportationError");
   ptr_SetupDiReportGenericDriverInstalled = (__vartype(ptr_SetupDiReportGenericDriverInstalled))GetProcAddress(hModule, "SetupDiReportGenericDriverInstalled");
   ptr_SetupDiReportPnPDeviceProblem = (__vartype(ptr_SetupDiReportPnPDeviceProblem))GetProcAddress(hModule, "SetupDiReportPnPDeviceProblem");
   ptr_SetupDiRestartDevices = (__vartype(ptr_SetupDiRestartDevices))GetProcAddress(hModule, "SetupDiRestartDevices");
   ptr_SetupDiSelectBestCompatDrv = (__vartype(ptr_SetupDiSelectBestCompatDrv))GetProcAddress(hModule, "SetupDiSelectBestCompatDrv");
   ptr_SetupDiSelectDevice = (__vartype(ptr_SetupDiSelectDevice))GetProcAddress(hModule, "SetupDiSelectDevice");
   ptr_SetupDiSelectOEMDrv = (__vartype(ptr_SetupDiSelectOEMDrv))GetProcAddress(hModule, "SetupDiSelectOEMDrv");
   ptr_SetupDiSetClassInstallParamsA = (__vartype(ptr_SetupDiSetClassInstallParamsA))GetProcAddress(hModule, "SetupDiSetClassInstallParamsA");
   ptr_SetupDiSetClassInstallParamsW = (__vartype(ptr_SetupDiSetClassInstallParamsW))GetProcAddress(hModule, "SetupDiSetClassInstallParamsW");
   ptr_SetupDiSetClassPropertyExW = (__vartype(ptr_SetupDiSetClassPropertyExW))GetProcAddress(hModule, "SetupDiSetClassPropertyExW");
   ptr_SetupDiSetClassPropertyW = (__vartype(ptr_SetupDiSetClassPropertyW))GetProcAddress(hModule, "SetupDiSetClassPropertyW");
   ptr_SetupDiSetClassRegistryPropertyA = (__vartype(ptr_SetupDiSetClassRegistryPropertyA))GetProcAddress(hModule, "SetupDiSetClassRegistryPropertyA");
   ptr_SetupDiSetClassRegistryPropertyW = (__vartype(ptr_SetupDiSetClassRegistryPropertyW))GetProcAddress(hModule, "SetupDiSetClassRegistryPropertyW");
   ptr_SetupDiSetDeviceInstallParamsA = (__vartype(ptr_SetupDiSetDeviceInstallParamsA))GetProcAddress(hModule, "SetupDiSetDeviceInstallParamsA");
   ptr_SetupDiSetDeviceInstallParamsW = (__vartype(ptr_SetupDiSetDeviceInstallParamsW))GetProcAddress(hModule, "SetupDiSetDeviceInstallParamsW");
   ptr_SetupDiSetDeviceInterfaceDefault = (__vartype(ptr_SetupDiSetDeviceInterfaceDefault))GetProcAddress(hModule, "SetupDiSetDeviceInterfaceDefault");
   ptr_SetupDiSetDeviceInterfacePropertyW = (__vartype(ptr_SetupDiSetDeviceInterfacePropertyW))GetProcAddress(hModule, "SetupDiSetDeviceInterfacePropertyW");
   ptr_SetupDiSetDevicePropertyW = (__vartype(ptr_SetupDiSetDevicePropertyW))GetProcAddress(hModule, "SetupDiSetDevicePropertyW");
   ptr_SetupDiSetDeviceRegistryPropertyA = (__vartype(ptr_SetupDiSetDeviceRegistryPropertyA))GetProcAddress(hModule, "SetupDiSetDeviceRegistryPropertyA");
   ptr_SetupDiSetDeviceRegistryPropertyW = (__vartype(ptr_SetupDiSetDeviceRegistryPropertyW))GetProcAddress(hModule, "SetupDiSetDeviceRegistryPropertyW");
   ptr_SetupDiSetDriverInstallParamsA = (__vartype(ptr_SetupDiSetDriverInstallParamsA))GetProcAddress(hModule, "SetupDiSetDriverInstallParamsA");
   ptr_SetupDiSetDriverInstallParamsW = (__vartype(ptr_SetupDiSetDriverInstallParamsW))GetProcAddress(hModule, "SetupDiSetDriverInstallParamsW");
   ptr_SetupDiSetSelectedDevice = (__vartype(ptr_SetupDiSetSelectedDevice))GetProcAddress(hModule, "SetupDiSetSelectedDevice");
   ptr_SetupDiSetSelectedDriverA = (__vartype(ptr_SetupDiSetSelectedDriverA))GetProcAddress(hModule, "SetupDiSetSelectedDriverA");
   ptr_SetupDiSetSelectedDriverW = (__vartype(ptr_SetupDiSetSelectedDriverW))GetProcAddress(hModule, "SetupDiSetSelectedDriverW");
   ptr_SetupDiUnremoveDevice = (__vartype(ptr_SetupDiUnremoveDevice))GetProcAddress(hModule, "SetupDiUnremoveDevice");
   ptr_SetupDuplicateDiskSpaceListA = (__vartype(ptr_SetupDuplicateDiskSpaceListA))GetProcAddress(hModule, "SetupDuplicateDiskSpaceListA");
   ptr_SetupDuplicateDiskSpaceListW = (__vartype(ptr_SetupDuplicateDiskSpaceListW))GetProcAddress(hModule, "SetupDuplicateDiskSpaceListW");
   ptr_SetupEnumInfSectionsA = (__vartype(ptr_SetupEnumInfSectionsA))GetProcAddress(hModule, "SetupEnumInfSectionsA");
   ptr_SetupEnumInfSectionsW = (__vartype(ptr_SetupEnumInfSectionsW))GetProcAddress(hModule, "SetupEnumInfSectionsW");
   ptr_SetupEnumPublishedInfA = (__vartype(ptr_SetupEnumPublishedInfA))GetProcAddress(hModule, "SetupEnumPublishedInfA");
   ptr_SetupEnumPublishedInfW = (__vartype(ptr_SetupEnumPublishedInfW))GetProcAddress(hModule, "SetupEnumPublishedInfW");
   ptr_SetupFindFirstLineA = (__vartype(ptr_SetupFindFirstLineA))GetProcAddress(hModule, "SetupFindFirstLineA");
   ptr_SetupFindFirstLineW = (__vartype(ptr_SetupFindFirstLineW))GetProcAddress(hModule, "SetupFindFirstLineW");
   ptr_SetupFindNextLine = (__vartype(ptr_SetupFindNextLine))GetProcAddress(hModule, "SetupFindNextLine");
   ptr_SetupFindNextMatchLineA = (__vartype(ptr_SetupFindNextMatchLineA))GetProcAddress(hModule, "SetupFindNextMatchLineA");
   ptr_SetupFindNextMatchLineW = (__vartype(ptr_SetupFindNextMatchLineW))GetProcAddress(hModule, "SetupFindNextMatchLineW");
   ptr_SetupFreeSourceListA = (__vartype(ptr_SetupFreeSourceListA))GetProcAddress(hModule, "SetupFreeSourceListA");
   ptr_SetupFreeSourceListW = (__vartype(ptr_SetupFreeSourceListW))GetProcAddress(hModule, "SetupFreeSourceListW");
   ptr_SetupGetBackupInformationA = (__vartype(ptr_SetupGetBackupInformationA))GetProcAddress(hModule, "SetupGetBackupInformationA");
   ptr_SetupGetBackupInformationW = (__vartype(ptr_SetupGetBackupInformationW))GetProcAddress(hModule, "SetupGetBackupInformationW");
   ptr_SetupGetBinaryField = (__vartype(ptr_SetupGetBinaryField))GetProcAddress(hModule, "SetupGetBinaryField");
   ptr_SetupGetFieldCount = (__vartype(ptr_SetupGetFieldCount))GetProcAddress(hModule, "SetupGetFieldCount");
   ptr_SetupGetFileCompressionInfoA = (__vartype(ptr_SetupGetFileCompressionInfoA))GetProcAddress(hModule, "SetupGetFileCompressionInfoA");
   ptr_SetupGetFileCompressionInfoExA = (__vartype(ptr_SetupGetFileCompressionInfoExA))GetProcAddress(hModule, "SetupGetFileCompressionInfoExA");
   ptr_SetupGetFileCompressionInfoExW = (__vartype(ptr_SetupGetFileCompressionInfoExW))GetProcAddress(hModule, "SetupGetFileCompressionInfoExW");
   ptr_SetupGetFileCompressionInfoW = (__vartype(ptr_SetupGetFileCompressionInfoW))GetProcAddress(hModule, "SetupGetFileCompressionInfoW");
   ptr_SetupGetFileQueueCount = (__vartype(ptr_SetupGetFileQueueCount))GetProcAddress(hModule, "SetupGetFileQueueCount");
   ptr_SetupGetFileQueueFlags = (__vartype(ptr_SetupGetFileQueueFlags))GetProcAddress(hModule, "SetupGetFileQueueFlags");
   ptr_SetupGetInfDriverStoreLocationA = (__vartype(ptr_SetupGetInfDriverStoreLocationA))GetProcAddress(hModule, "SetupGetInfDriverStoreLocationA");
   ptr_SetupGetInfDriverStoreLocationW = (__vartype(ptr_SetupGetInfDriverStoreLocationW))GetProcAddress(hModule, "SetupGetInfDriverStoreLocationW");
   ptr_SetupGetInfFileListA = (__vartype(ptr_SetupGetInfFileListA))GetProcAddress(hModule, "SetupGetInfFileListA");
   ptr_SetupGetInfFileListW = (__vartype(ptr_SetupGetInfFileListW))GetProcAddress(hModule, "SetupGetInfFileListW");
   ptr_SetupGetInfInformationA = (__vartype(ptr_SetupGetInfInformationA))GetProcAddress(hModule, "SetupGetInfInformationA");
   ptr_SetupGetInfInformationW = (__vartype(ptr_SetupGetInfInformationW))GetProcAddress(hModule, "SetupGetInfInformationW");
   ptr_SetupGetInfPublishedNameA = (__vartype(ptr_SetupGetInfPublishedNameA))GetProcAddress(hModule, "SetupGetInfPublishedNameA");
   ptr_SetupGetInfPublishedNameW = (__vartype(ptr_SetupGetInfPublishedNameW))GetProcAddress(hModule, "SetupGetInfPublishedNameW");
   ptr_SetupGetInfSections = (__vartype(ptr_SetupGetInfSections))GetProcAddress(hModule, "SetupGetInfSections");
   ptr_SetupGetIntField = (__vartype(ptr_SetupGetIntField))GetProcAddress(hModule, "SetupGetIntField");
   ptr_SetupGetLineByIndexA = (__vartype(ptr_SetupGetLineByIndexA))GetProcAddress(hModule, "SetupGetLineByIndexA");
   ptr_SetupGetLineByIndexW = (__vartype(ptr_SetupGetLineByIndexW))GetProcAddress(hModule, "SetupGetLineByIndexW");
   ptr_SetupGetLineCountA = (__vartype(ptr_SetupGetLineCountA))GetProcAddress(hModule, "SetupGetLineCountA");
   ptr_SetupGetLineCountW = (__vartype(ptr_SetupGetLineCountW))GetProcAddress(hModule, "SetupGetLineCountW");
   ptr_SetupGetLineTextA = (__vartype(ptr_SetupGetLineTextA))GetProcAddress(hModule, "SetupGetLineTextA");
   ptr_SetupGetLineTextW = (__vartype(ptr_SetupGetLineTextW))GetProcAddress(hModule, "SetupGetLineTextW");
   ptr_SetupGetMultiSzFieldA = (__vartype(ptr_SetupGetMultiSzFieldA))GetProcAddress(hModule, "SetupGetMultiSzFieldA");
   ptr_SetupGetMultiSzFieldW = (__vartype(ptr_SetupGetMultiSzFieldW))GetProcAddress(hModule, "SetupGetMultiSzFieldW");
   ptr_SetupGetNonInteractiveMode = (__vartype(ptr_SetupGetNonInteractiveMode))GetProcAddress(hModule, "SetupGetNonInteractiveMode");
   ptr_SetupGetSourceFileLocationA = (__vartype(ptr_SetupGetSourceFileLocationA))GetProcAddress(hModule, "SetupGetSourceFileLocationA");
   ptr_SetupGetSourceFileLocationW = (__vartype(ptr_SetupGetSourceFileLocationW))GetProcAddress(hModule, "SetupGetSourceFileLocationW");
   ptr_SetupGetSourceFileSizeA = (__vartype(ptr_SetupGetSourceFileSizeA))GetProcAddress(hModule, "SetupGetSourceFileSizeA");
   ptr_SetupGetSourceFileSizeW = (__vartype(ptr_SetupGetSourceFileSizeW))GetProcAddress(hModule, "SetupGetSourceFileSizeW");
   ptr_SetupGetSourceInfoA = (__vartype(ptr_SetupGetSourceInfoA))GetProcAddress(hModule, "SetupGetSourceInfoA");
   ptr_SetupGetSourceInfoW = (__vartype(ptr_SetupGetSourceInfoW))GetProcAddress(hModule, "SetupGetSourceInfoW");
   ptr_SetupGetStringFieldA = (__vartype(ptr_SetupGetStringFieldA))GetProcAddress(hModule, "SetupGetStringFieldA");
   ptr_SetupGetStringFieldW = (__vartype(ptr_SetupGetStringFieldW))GetProcAddress(hModule, "SetupGetStringFieldW");
   ptr_SetupGetTargetPathA = (__vartype(ptr_SetupGetTargetPathA))GetProcAddress(hModule, "SetupGetTargetPathA");
   ptr_SetupGetTargetPathW = (__vartype(ptr_SetupGetTargetPathW))GetProcAddress(hModule, "SetupGetTargetPathW");
   ptr_SetupInitDefaultQueueCallback = (__vartype(ptr_SetupInitDefaultQueueCallback))GetProcAddress(hModule, "SetupInitDefaultQueueCallback");
   ptr_SetupInitDefaultQueueCallbackEx = (__vartype(ptr_SetupInitDefaultQueueCallbackEx))GetProcAddress(hModule, "SetupInitDefaultQueueCallbackEx");
   ptr_SetupInitializeFileLogA = (__vartype(ptr_SetupInitializeFileLogA))GetProcAddress(hModule, "SetupInitializeFileLogA");
   ptr_SetupInitializeFileLogW = (__vartype(ptr_SetupInitializeFileLogW))GetProcAddress(hModule, "SetupInitializeFileLogW");
   ptr_SetupInstallFileA = (__vartype(ptr_SetupInstallFileA))GetProcAddress(hModule, "SetupInstallFileA");
   ptr_SetupInstallFileExA = (__vartype(ptr_SetupInstallFileExA))GetProcAddress(hModule, "SetupInstallFileExA");
   ptr_SetupInstallFileExW = (__vartype(ptr_SetupInstallFileExW))GetProcAddress(hModule, "SetupInstallFileExW");
   ptr_SetupInstallFileW = (__vartype(ptr_SetupInstallFileW))GetProcAddress(hModule, "SetupInstallFileW");
   ptr_SetupInstallFilesFromInfSectionA = (__vartype(ptr_SetupInstallFilesFromInfSectionA))GetProcAddress(hModule, "SetupInstallFilesFromInfSectionA");
   ptr_SetupInstallFilesFromInfSectionW = (__vartype(ptr_SetupInstallFilesFromInfSectionW))GetProcAddress(hModule, "SetupInstallFilesFromInfSectionW");
   ptr_SetupInstallFromInfSectionA = (__vartype(ptr_SetupInstallFromInfSectionA))GetProcAddress(hModule, "SetupInstallFromInfSectionA");
   ptr_SetupInstallFromInfSectionW = (__vartype(ptr_SetupInstallFromInfSectionW))GetProcAddress(hModule, "SetupInstallFromInfSectionW");
   ptr_SetupInstallLogCloseEventGroup = (__vartype(ptr_SetupInstallLogCloseEventGroup))GetProcAddress(hModule, "SetupInstallLogCloseEventGroup");
   ptr_SetupInstallLogCreateEventGroup = (__vartype(ptr_SetupInstallLogCreateEventGroup))GetProcAddress(hModule, "SetupInstallLogCreateEventGroup");
   ptr_SetupInstallServicesFromInfSectionA = (__vartype(ptr_SetupInstallServicesFromInfSectionA))GetProcAddress(hModule, "SetupInstallServicesFromInfSectionA");
   ptr_SetupInstallServicesFromInfSectionExA = (__vartype(ptr_SetupInstallServicesFromInfSectionExA))GetProcAddress(hModule, "SetupInstallServicesFromInfSectionExA");
   ptr_SetupInstallServicesFromInfSectionExW = (__vartype(ptr_SetupInstallServicesFromInfSectionExW))GetProcAddress(hModule, "SetupInstallServicesFromInfSectionExW");
   ptr_SetupInstallServicesFromInfSectionW = (__vartype(ptr_SetupInstallServicesFromInfSectionW))GetProcAddress(hModule, "SetupInstallServicesFromInfSectionW");
   ptr_SetupIterateCabinetA = (__vartype(ptr_SetupIterateCabinetA))GetProcAddress(hModule, "SetupIterateCabinetA");
   ptr_SetupIterateCabinetW = (__vartype(ptr_SetupIterateCabinetW))GetProcAddress(hModule, "SetupIterateCabinetW");
   ptr_SetupLogErrorA = (__vartype(ptr_SetupLogErrorA))GetProcAddress(hModule, "SetupLogErrorA");
   ptr_SetupLogErrorW = (__vartype(ptr_SetupLogErrorW))GetProcAddress(hModule, "SetupLogErrorW");
   ptr_SetupLogFileA = (__vartype(ptr_SetupLogFileA))GetProcAddress(hModule, "SetupLogFileA");
   ptr_SetupLogFileW = (__vartype(ptr_SetupLogFileW))GetProcAddress(hModule, "SetupLogFileW");
   ptr_SetupOpenAppendInfFileA = (__vartype(ptr_SetupOpenAppendInfFileA))GetProcAddress(hModule, "SetupOpenAppendInfFileA");
   ptr_SetupOpenAppendInfFileW = (__vartype(ptr_SetupOpenAppendInfFileW))GetProcAddress(hModule, "SetupOpenAppendInfFileW");
   ptr_SetupOpenFileQueue = (__vartype(ptr_SetupOpenFileQueue))GetProcAddress(hModule, "SetupOpenFileQueue");
   ptr_SetupOpenInfFileA = (__vartype(ptr_SetupOpenInfFileA))GetProcAddress(hModule, "SetupOpenInfFileA");
   ptr_SetupOpenInfFileW = (__vartype(ptr_SetupOpenInfFileW))GetProcAddress(hModule, "SetupOpenInfFileW");
   ptr_SetupOpenLog = (__vartype(ptr_SetupOpenLog))GetProcAddress(hModule, "SetupOpenLog");
   ptr_SetupOpenMasterInf = (__vartype(ptr_SetupOpenMasterInf))GetProcAddress(hModule, "SetupOpenMasterInf");
   ptr_SetupPrepareQueueForRestoreA = (__vartype(ptr_SetupPrepareQueueForRestoreA))GetProcAddress(hModule, "SetupPrepareQueueForRestoreA");
   ptr_SetupPrepareQueueForRestoreW = (__vartype(ptr_SetupPrepareQueueForRestoreW))GetProcAddress(hModule, "SetupPrepareQueueForRestoreW");
   ptr_SetupPromptForDiskA = (__vartype(ptr_SetupPromptForDiskA))GetProcAddress(hModule, "SetupPromptForDiskA");
   ptr_SetupPromptForDiskW = (__vartype(ptr_SetupPromptForDiskW))GetProcAddress(hModule, "SetupPromptForDiskW");
   ptr_SetupPromptReboot = (__vartype(ptr_SetupPromptReboot))GetProcAddress(hModule, "SetupPromptReboot");
   ptr_SetupQueryDrivesInDiskSpaceListA = (__vartype(ptr_SetupQueryDrivesInDiskSpaceListA))GetProcAddress(hModule, "SetupQueryDrivesInDiskSpaceListA");
   ptr_SetupQueryDrivesInDiskSpaceListW = (__vartype(ptr_SetupQueryDrivesInDiskSpaceListW))GetProcAddress(hModule, "SetupQueryDrivesInDiskSpaceListW");
   ptr_SetupQueryFileLogA = (__vartype(ptr_SetupQueryFileLogA))GetProcAddress(hModule, "SetupQueryFileLogA");
   ptr_SetupQueryFileLogW = (__vartype(ptr_SetupQueryFileLogW))GetProcAddress(hModule, "SetupQueryFileLogW");
   ptr_SetupQueryInfFileInformationA = (__vartype(ptr_SetupQueryInfFileInformationA))GetProcAddress(hModule, "SetupQueryInfFileInformationA");
   ptr_SetupQueryInfFileInformationW = (__vartype(ptr_SetupQueryInfFileInformationW))GetProcAddress(hModule, "SetupQueryInfFileInformationW");
   ptr_SetupQueryInfOriginalFileInformationA = (__vartype(ptr_SetupQueryInfOriginalFileInformationA))GetProcAddress(hModule, "SetupQueryInfOriginalFileInformationA");
   ptr_SetupQueryInfOriginalFileInformationW = (__vartype(ptr_SetupQueryInfOriginalFileInformationW))GetProcAddress(hModule, "SetupQueryInfOriginalFileInformationW");
   ptr_SetupQueryInfVersionInformationA = (__vartype(ptr_SetupQueryInfVersionInformationA))GetProcAddress(hModule, "SetupQueryInfVersionInformationA");
   ptr_SetupQueryInfVersionInformationW = (__vartype(ptr_SetupQueryInfVersionInformationW))GetProcAddress(hModule, "SetupQueryInfVersionInformationW");
   ptr_SetupQuerySourceListA = (__vartype(ptr_SetupQuerySourceListA))GetProcAddress(hModule, "SetupQuerySourceListA");
   ptr_SetupQuerySourceListW = (__vartype(ptr_SetupQuerySourceListW))GetProcAddress(hModule, "SetupQuerySourceListW");
   ptr_SetupQuerySpaceRequiredOnDriveA = (__vartype(ptr_SetupQuerySpaceRequiredOnDriveA))GetProcAddress(hModule, "SetupQuerySpaceRequiredOnDriveA");
   ptr_SetupQuerySpaceRequiredOnDriveW = (__vartype(ptr_SetupQuerySpaceRequiredOnDriveW))GetProcAddress(hModule, "SetupQuerySpaceRequiredOnDriveW");
   ptr_SetupQueueCopyA = (__vartype(ptr_SetupQueueCopyA))GetProcAddress(hModule, "SetupQueueCopyA");
   ptr_SetupQueueCopyIndirectA = (__vartype(ptr_SetupQueueCopyIndirectA))GetProcAddress(hModule, "SetupQueueCopyIndirectA");
   ptr_SetupQueueCopyIndirectW = (__vartype(ptr_SetupQueueCopyIndirectW))GetProcAddress(hModule, "SetupQueueCopyIndirectW");
   ptr_SetupQueueCopySectionA = (__vartype(ptr_SetupQueueCopySectionA))GetProcAddress(hModule, "SetupQueueCopySectionA");
   ptr_SetupQueueCopySectionW = (__vartype(ptr_SetupQueueCopySectionW))GetProcAddress(hModule, "SetupQueueCopySectionW");
   ptr_SetupQueueCopyW = (__vartype(ptr_SetupQueueCopyW))GetProcAddress(hModule, "SetupQueueCopyW");
   ptr_SetupQueueDefaultCopyA = (__vartype(ptr_SetupQueueDefaultCopyA))GetProcAddress(hModule, "SetupQueueDefaultCopyA");
   ptr_SetupQueueDefaultCopyW = (__vartype(ptr_SetupQueueDefaultCopyW))GetProcAddress(hModule, "SetupQueueDefaultCopyW");
   ptr_SetupQueueDeleteA = (__vartype(ptr_SetupQueueDeleteA))GetProcAddress(hModule, "SetupQueueDeleteA");
   ptr_SetupQueueDeleteSectionA = (__vartype(ptr_SetupQueueDeleteSectionA))GetProcAddress(hModule, "SetupQueueDeleteSectionA");
   ptr_SetupQueueDeleteSectionW = (__vartype(ptr_SetupQueueDeleteSectionW))GetProcAddress(hModule, "SetupQueueDeleteSectionW");
   ptr_SetupQueueDeleteW = (__vartype(ptr_SetupQueueDeleteW))GetProcAddress(hModule, "SetupQueueDeleteW");
   ptr_SetupQueueRenameA = (__vartype(ptr_SetupQueueRenameA))GetProcAddress(hModule, "SetupQueueRenameA");
   ptr_SetupQueueRenameSectionA = (__vartype(ptr_SetupQueueRenameSectionA))GetProcAddress(hModule, "SetupQueueRenameSectionA");
   ptr_SetupQueueRenameSectionW = (__vartype(ptr_SetupQueueRenameSectionW))GetProcAddress(hModule, "SetupQueueRenameSectionW");
   ptr_SetupQueueRenameW = (__vartype(ptr_SetupQueueRenameW))GetProcAddress(hModule, "SetupQueueRenameW");
   ptr_SetupRemoveFileLogEntryA = (__vartype(ptr_SetupRemoveFileLogEntryA))GetProcAddress(hModule, "SetupRemoveFileLogEntryA");
   ptr_SetupRemoveFileLogEntryW = (__vartype(ptr_SetupRemoveFileLogEntryW))GetProcAddress(hModule, "SetupRemoveFileLogEntryW");
   ptr_SetupRemoveFromDiskSpaceListA = (__vartype(ptr_SetupRemoveFromDiskSpaceListA))GetProcAddress(hModule, "SetupRemoveFromDiskSpaceListA");
   ptr_SetupRemoveFromDiskSpaceListW = (__vartype(ptr_SetupRemoveFromDiskSpaceListW))GetProcAddress(hModule, "SetupRemoveFromDiskSpaceListW");
   ptr_SetupRemoveFromSourceListA = (__vartype(ptr_SetupRemoveFromSourceListA))GetProcAddress(hModule, "SetupRemoveFromSourceListA");
   ptr_SetupRemoveFromSourceListW = (__vartype(ptr_SetupRemoveFromSourceListW))GetProcAddress(hModule, "SetupRemoveFromSourceListW");
   ptr_SetupRemoveInstallSectionFromDiskSpaceListA = (__vartype(ptr_SetupRemoveInstallSectionFromDiskSpaceListA))GetProcAddress(hModule, "SetupRemoveInstallSectionFromDiskSpaceListA");
   ptr_SetupRemoveInstallSectionFromDiskSpaceListW = (__vartype(ptr_SetupRemoveInstallSectionFromDiskSpaceListW))GetProcAddress(hModule, "SetupRemoveInstallSectionFromDiskSpaceListW");
   ptr_SetupRemoveSectionFromDiskSpaceListA = (__vartype(ptr_SetupRemoveSectionFromDiskSpaceListA))GetProcAddress(hModule, "SetupRemoveSectionFromDiskSpaceListA");
   ptr_SetupRemoveSectionFromDiskSpaceListW = (__vartype(ptr_SetupRemoveSectionFromDiskSpaceListW))GetProcAddress(hModule, "SetupRemoveSectionFromDiskSpaceListW");
   ptr_SetupRenameErrorA = (__vartype(ptr_SetupRenameErrorA))GetProcAddress(hModule, "SetupRenameErrorA");
   ptr_SetupRenameErrorW = (__vartype(ptr_SetupRenameErrorW))GetProcAddress(hModule, "SetupRenameErrorW");
   ptr_SetupScanFileQueue = (__vartype(ptr_SetupScanFileQueue))GetProcAddress(hModule, "SetupScanFileQueue");
   ptr_SetupScanFileQueueA = (__vartype(ptr_SetupScanFileQueueA))GetProcAddress(hModule, "SetupScanFileQueueA");
   ptr_SetupScanFileQueueW = (__vartype(ptr_SetupScanFileQueueW))GetProcAddress(hModule, "SetupScanFileQueueW");
   ptr_SetupSetDirectoryIdA = (__vartype(ptr_SetupSetDirectoryIdA))GetProcAddress(hModule, "SetupSetDirectoryIdA");
   ptr_SetupSetDirectoryIdExA = (__vartype(ptr_SetupSetDirectoryIdExA))GetProcAddress(hModule, "SetupSetDirectoryIdExA");
   ptr_SetupSetDirectoryIdExW = (__vartype(ptr_SetupSetDirectoryIdExW))GetProcAddress(hModule, "SetupSetDirectoryIdExW");
   ptr_SetupSetDirectoryIdW = (__vartype(ptr_SetupSetDirectoryIdW))GetProcAddress(hModule, "SetupSetDirectoryIdW");
   ptr_SetupSetFileQueueAlternatePlatformA = (__vartype(ptr_SetupSetFileQueueAlternatePlatformA))GetProcAddress(hModule, "SetupSetFileQueueAlternatePlatformA");
   ptr_SetupSetFileQueueAlternatePlatformW = (__vartype(ptr_SetupSetFileQueueAlternatePlatformW))GetProcAddress(hModule, "SetupSetFileQueueAlternatePlatformW");
   ptr_SetupSetFileQueueFlags = (__vartype(ptr_SetupSetFileQueueFlags))GetProcAddress(hModule, "SetupSetFileQueueFlags");
   ptr_SetupSetNonInteractiveMode = (__vartype(ptr_SetupSetNonInteractiveMode))GetProcAddress(hModule, "SetupSetNonInteractiveMode");
   ptr_SetupSetPlatformPathOverrideA = (__vartype(ptr_SetupSetPlatformPathOverrideA))GetProcAddress(hModule, "SetupSetPlatformPathOverrideA");
   ptr_SetupSetPlatformPathOverrideW = (__vartype(ptr_SetupSetPlatformPathOverrideW))GetProcAddress(hModule, "SetupSetPlatformPathOverrideW");
   ptr_SetupSetSourceListA = (__vartype(ptr_SetupSetSourceListA))GetProcAddress(hModule, "SetupSetSourceListA");
   ptr_SetupSetSourceListW = (__vartype(ptr_SetupSetSourceListW))GetProcAddress(hModule, "SetupSetSourceListW");
   ptr_SetupTermDefaultQueueCallback = (__vartype(ptr_SetupTermDefaultQueueCallback))GetProcAddress(hModule, "SetupTermDefaultQueueCallback");
   ptr_SetupTerminateFileLog = (__vartype(ptr_SetupTerminateFileLog))GetProcAddress(hModule, "SetupTerminateFileLog");
   ptr_SetupUninstallNewlyCopiedInfs = (__vartype(ptr_SetupUninstallNewlyCopiedInfs))GetProcAddress(hModule, "SetupUninstallNewlyCopiedInfs");
   ptr_SetupUninstallOEMInfA = (__vartype(ptr_SetupUninstallOEMInfA))GetProcAddress(hModule, "SetupUninstallOEMInfA");
   ptr_SetupUninstallOEMInfW = (__vartype(ptr_SetupUninstallOEMInfW))GetProcAddress(hModule, "SetupUninstallOEMInfW");
   ptr_SetupVerifyInfFileA = (__vartype(ptr_SetupVerifyInfFileA))GetProcAddress(hModule, "SetupVerifyInfFileA");
   ptr_SetupVerifyInfFileW = (__vartype(ptr_SetupVerifyInfFileW))GetProcAddress(hModule, "SetupVerifyInfFileW");
   ptr_SetupWriteTextLogInfLine = (__vartype(ptr_SetupWriteTextLogInfLine))GetProcAddress(hModule, "SetupWriteTextLogInfLine");
   ptr_UnicodeToMultiByte = (__vartype(ptr_UnicodeToMultiByte))GetProcAddress(hModule, "UnicodeToMultiByte");
   ptr_VerifyCatalogFile = (__vartype(ptr_VerifyCatalogFile))GetProcAddress(hModule, "VerifyCatalogFile");
   ptr_pGetDriverPackageHash = (__vartype(ptr_pGetDriverPackageHash))GetProcAddress(hModule, "pGetDriverPackageHash");
   ptr_pSetupAccessRunOnceNodeList = (__vartype(ptr_pSetupAccessRunOnceNodeList))GetProcAddress(hModule, "pSetupAccessRunOnceNodeList");
   ptr_pSetupAddMiniIconToList = (__vartype(ptr_pSetupAddMiniIconToList))GetProcAddress(hModule, "pSetupAddMiniIconToList");
   ptr_pSetupAddTagToGroupOrderListEntry = (__vartype(ptr_pSetupAddTagToGroupOrderListEntry))GetProcAddress(hModule, "pSetupAddTagToGroupOrderListEntry");
   ptr_pSetupAppendPath = (__vartype(ptr_pSetupAppendPath))GetProcAddress(hModule, "pSetupAppendPath");
   ptr_pSetupCaptureAndConvertAnsiArg = (__vartype(ptr_pSetupCaptureAndConvertAnsiArg))GetProcAddress(hModule, "pSetupCaptureAndConvertAnsiArg");
   ptr_pSetupCenterWindowRelativeToParent = (__vartype(ptr_pSetupCenterWindowRelativeToParent))GetProcAddress(hModule, "pSetupCenterWindowRelativeToParent");
   ptr_pSetupConcatenatePaths = (__vartype(ptr_pSetupConcatenatePaths))GetProcAddress(hModule, "pSetupConcatenatePaths");
   ptr_pSetupDestroyRunOnceNodeList = (__vartype(ptr_pSetupDestroyRunOnceNodeList))GetProcAddress(hModule, "pSetupDestroyRunOnceNodeList");
   ptr_pSetupDiBuildInfoDataFromStrongName = (__vartype(ptr_pSetupDiBuildInfoDataFromStrongName))GetProcAddress(hModule, "pSetupDiBuildInfoDataFromStrongName");
   ptr_pSetupDiCrimsonLogDeviceInstall = (__vartype(ptr_pSetupDiCrimsonLogDeviceInstall))GetProcAddress(hModule, "pSetupDiCrimsonLogDeviceInstall");
   ptr_pSetupDiGetStrongNameForDriverNode = (__vartype(ptr_pSetupDiGetStrongNameForDriverNode))GetProcAddress(hModule, "pSetupDiGetStrongNameForDriverNode");
   ptr_pSetupDiInvalidateHelperModules = (__vartype(ptr_pSetupDiInvalidateHelperModules))GetProcAddress(hModule, "pSetupDiInvalidateHelperModules");
   ptr_pSetupDoLastKnownGoodBackup = (__vartype(ptr_pSetupDoLastKnownGoodBackup))GetProcAddress(hModule, "pSetupDoLastKnownGoodBackup");
   ptr_pSetupDoesUserHavePrivilege = (__vartype(ptr_pSetupDoesUserHavePrivilege))GetProcAddress(hModule, "pSetupDoesUserHavePrivilege");
   ptr_pSetupDuplicateString = (__vartype(ptr_pSetupDuplicateString))GetProcAddress(hModule, "pSetupDuplicateString");
   ptr_pSetupEnablePrivilege = (__vartype(ptr_pSetupEnablePrivilege))GetProcAddress(hModule, "pSetupEnablePrivilege");
   ptr_pSetupFree = (__vartype(ptr_pSetupFree))GetProcAddress(hModule, "pSetupFree");
   ptr_pSetupGetCurrentDriverSigningPolicy = (__vartype(ptr_pSetupGetCurrentDriverSigningPolicy))GetProcAddress(hModule, "pSetupGetCurrentDriverSigningPolicy");
   ptr_pSetupGetDriverDate = (__vartype(ptr_pSetupGetDriverDate))GetProcAddress(hModule, "pSetupGetDriverDate");
   ptr_pSetupGetDriverVersion = (__vartype(ptr_pSetupGetDriverVersion))GetProcAddress(hModule, "pSetupGetDriverVersion");
   ptr_pSetupGetField = (__vartype(ptr_pSetupGetField))GetProcAddress(hModule, "pSetupGetField");
   ptr_pSetupGetFileTitle = (__vartype(ptr_pSetupGetFileTitle))GetProcAddress(hModule, "pSetupGetFileTitle");
   ptr_pSetupGetGlobalFlags = (__vartype(ptr_pSetupGetGlobalFlags))GetProcAddress(hModule, "pSetupGetGlobalFlags");
   ptr_pSetupGetIndirectStringsFromDriverInfo = (__vartype(ptr_pSetupGetIndirectStringsFromDriverInfo))GetProcAddress(hModule, "pSetupGetIndirectStringsFromDriverInfo");
   ptr_pSetupGetInfSections = (__vartype(ptr_pSetupGetInfSections))GetProcAddress(hModule, "pSetupGetInfSections");
   ptr_pSetupGetQueueFlags = (__vartype(ptr_pSetupGetQueueFlags))GetProcAddress(hModule, "pSetupGetQueueFlags");
   ptr_pSetupGetRealSystemTime = (__vartype(ptr_pSetupGetRealSystemTime))GetProcAddress(hModule, "pSetupGetRealSystemTime");
   ptr_pSetupGuidFromString = (__vartype(ptr_pSetupGuidFromString))GetProcAddress(hModule, "pSetupGuidFromString");
   ptr_pSetupHandleFailedVerification = (__vartype(ptr_pSetupHandleFailedVerification))GetProcAddress(hModule, "pSetupHandleFailedVerification");
   ptr_pSetupInfGetDigitalSignatureInfo = (__vartype(ptr_pSetupInfGetDigitalSignatureInfo))GetProcAddress(hModule, "pSetupInfGetDigitalSignatureInfo");
   ptr_pSetupInfIsInbox = (__vartype(ptr_pSetupInfIsInbox))GetProcAddress(hModule, "pSetupInfIsInbox");
   ptr_pSetupInfSetDigitalSignatureInfo = (__vartype(ptr_pSetupInfSetDigitalSignatureInfo))GetProcAddress(hModule, "pSetupInfSetDigitalSignatureInfo");
   ptr_pSetupInstallCatalog = (__vartype(ptr_pSetupInstallCatalog))GetProcAddress(hModule, "pSetupInstallCatalog");
   ptr_pSetupIsBiDiLocalizedSystemEx = (__vartype(ptr_pSetupIsBiDiLocalizedSystemEx))GetProcAddress(hModule, "pSetupIsBiDiLocalizedSystemEx");
   ptr_pSetupIsGuidNull = (__vartype(ptr_pSetupIsGuidNull))GetProcAddress(hModule, "pSetupIsGuidNull");
   ptr_pSetupIsLocalSystem = (__vartype(ptr_pSetupIsLocalSystem))GetProcAddress(hModule, "pSetupIsLocalSystem");
   ptr_pSetupIsUserAdmin = (__vartype(ptr_pSetupIsUserAdmin))GetProcAddress(hModule, "pSetupIsUserAdmin");
   ptr_pSetupIsUserTrustedInstaller = (__vartype(ptr_pSetupIsUserTrustedInstaller))GetProcAddress(hModule, "pSetupIsUserTrustedInstaller");
   ptr_pSetupLoadIndirectString = (__vartype(ptr_pSetupLoadIndirectString))GetProcAddress(hModule, "pSetupLoadIndirectString");
   ptr_pSetupMakeSurePathExists = (__vartype(ptr_pSetupMakeSurePathExists))GetProcAddress(hModule, "pSetupMakeSurePathExists");
   ptr_pSetupMalloc = (__vartype(ptr_pSetupMalloc))GetProcAddress(hModule, "pSetupMalloc");
   ptr_pSetupModifyGlobalFlags = (__vartype(ptr_pSetupModifyGlobalFlags))GetProcAddress(hModule, "pSetupModifyGlobalFlags");
   ptr_pSetupMultiByteToUnicode = (__vartype(ptr_pSetupMultiByteToUnicode))GetProcAddress(hModule, "pSetupMultiByteToUnicode");
   ptr_pSetupOpenAndMapFileForRead = (__vartype(ptr_pSetupOpenAndMapFileForRead))GetProcAddress(hModule, "pSetupOpenAndMapFileForRead");
   ptr_pSetupOutOfMemory = (__vartype(ptr_pSetupOutOfMemory))GetProcAddress(hModule, "pSetupOutOfMemory");
   ptr_pSetupQueryMultiSzValueToArray = (__vartype(ptr_pSetupQueryMultiSzValueToArray))GetProcAddress(hModule, "pSetupQueryMultiSzValueToArray");
   ptr_pSetupRealloc = (__vartype(ptr_pSetupRealloc))GetProcAddress(hModule, "pSetupRealloc");
   ptr_pSetupRegistryDelnode = (__vartype(ptr_pSetupRegistryDelnode))GetProcAddress(hModule, "pSetupRegistryDelnode");
   ptr_pSetupRetrieveServiceConfig = (__vartype(ptr_pSetupRetrieveServiceConfig))GetProcAddress(hModule, "pSetupRetrieveServiceConfig");
   ptr_pSetupSetArrayToMultiSzValue = (__vartype(ptr_pSetupSetArrayToMultiSzValue))GetProcAddress(hModule, "pSetupSetArrayToMultiSzValue");
   ptr_pSetupSetDriverPackageRestorePoint = (__vartype(ptr_pSetupSetDriverPackageRestorePoint))GetProcAddress(hModule, "pSetupSetDriverPackageRestorePoint");
   ptr_pSetupSetGlobalFlags = (__vartype(ptr_pSetupSetGlobalFlags))GetProcAddress(hModule, "pSetupSetGlobalFlags");
   ptr_pSetupSetQueueFlags = (__vartype(ptr_pSetupSetQueueFlags))GetProcAddress(hModule, "pSetupSetQueueFlags");
   ptr_pSetupShouldDeviceBeExcluded = (__vartype(ptr_pSetupShouldDeviceBeExcluded))GetProcAddress(hModule, "pSetupShouldDeviceBeExcluded");
   ptr_pSetupStringFromGuid = (__vartype(ptr_pSetupStringFromGuid))GetProcAddress(hModule, "pSetupStringFromGuid");
   ptr_pSetupStringTableAddString = (__vartype(ptr_pSetupStringTableAddString))GetProcAddress(hModule, "pSetupStringTableAddString");
   ptr_pSetupStringTableAddStringEx = (__vartype(ptr_pSetupStringTableAddStringEx))GetProcAddress(hModule, "pSetupStringTableAddStringEx");
   ptr_pSetupStringTableDestroy = (__vartype(ptr_pSetupStringTableDestroy))GetProcAddress(hModule, "pSetupStringTableDestroy");
   ptr_pSetupStringTableDuplicate = (__vartype(ptr_pSetupStringTableDuplicate))GetProcAddress(hModule, "pSetupStringTableDuplicate");
   ptr_pSetupStringTableEnum = (__vartype(ptr_pSetupStringTableEnum))GetProcAddress(hModule, "pSetupStringTableEnum");
   ptr_pSetupStringTableGetExtraData = (__vartype(ptr_pSetupStringTableGetExtraData))GetProcAddress(hModule, "pSetupStringTableGetExtraData");
   ptr_pSetupStringTableInitialize = (__vartype(ptr_pSetupStringTableInitialize))GetProcAddress(hModule, "pSetupStringTableInitialize");
   ptr_pSetupStringTableInitializeEx = (__vartype(ptr_pSetupStringTableInitializeEx))GetProcAddress(hModule, "pSetupStringTableInitializeEx");
   ptr_pSetupStringTableLookUpString = (__vartype(ptr_pSetupStringTableLookUpString))GetProcAddress(hModule, "pSetupStringTableLookUpString");
   ptr_pSetupStringTableLookUpStringEx = (__vartype(ptr_pSetupStringTableLookUpStringEx))GetProcAddress(hModule, "pSetupStringTableLookUpStringEx");
   ptr_pSetupStringTableSetExtraData = (__vartype(ptr_pSetupStringTableSetExtraData))GetProcAddress(hModule, "pSetupStringTableSetExtraData");
   ptr_pSetupStringTableStringFromId = (__vartype(ptr_pSetupStringTableStringFromId))GetProcAddress(hModule, "pSetupStringTableStringFromId");
   ptr_pSetupStringTableStringFromIdEx = (__vartype(ptr_pSetupStringTableStringFromIdEx))GetProcAddress(hModule, "pSetupStringTableStringFromIdEx");
   ptr_pSetupUnicodeToMultiByte = (__vartype(ptr_pSetupUnicodeToMultiByte))GetProcAddress(hModule, "pSetupUnicodeToMultiByte");
   ptr_pSetupUnmapAndCloseFile = (__vartype(ptr_pSetupUnmapAndCloseFile))GetProcAddress(hModule, "pSetupUnmapAndCloseFile");
   ptr_pSetupValidateDriverPackage = (__vartype(ptr_pSetupValidateDriverPackage))GetProcAddress(hModule, "pSetupValidateDriverPackage");
   ptr_pSetupVerifyCatalogFile = (__vartype(ptr_pSetupVerifyCatalogFile))GetProcAddress(hModule, "pSetupVerifyCatalogFile");
   ptr_pSetupVerifyQueuedCatalogs = (__vartype(ptr_pSetupVerifyQueuedCatalogs))GetProcAddress(hModule, "pSetupVerifyQueuedCatalogs");
   ptr_pSetupWriteLogEntry = (__vartype(ptr_pSetupWriteLogEntry))GetProcAddress(hModule, "pSetupWriteLogEntry");
   ptr_pSetupWriteLogError = (__vartype(ptr_pSetupWriteLogError))GetProcAddress(hModule, "pSetupWriteLogError");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

