#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_CompareFileTime;
void *ptr_CompareFileTime = NULL;
extern void *ptr_CreateDirectoryA;
void *ptr_CreateDirectoryA = NULL;
extern void *ptr_CreateDirectoryW;
void *ptr_CreateDirectoryW = NULL;
extern void *ptr_CreateFileA;
void *ptr_CreateFileA = NULL;
extern void *ptr_CreateFileW;
void *ptr_CreateFileW = NULL;
extern void *ptr_DefineDosDeviceW;
void *ptr_DefineDosDeviceW = NULL;
extern void *ptr_DeleteFileA;
void *ptr_DeleteFileA = NULL;
extern void *ptr_DeleteFileW;
void *ptr_DeleteFileW = NULL;
extern void *ptr_DeleteVolumeMountPointW;
void *ptr_DeleteVolumeMountPointW = NULL;
extern void *ptr_FileTimeToLocalFileTime;
void *ptr_FileTimeToLocalFileTime = NULL;
extern void *ptr_FileTimeToSystemTime;
void *ptr_FileTimeToSystemTime = NULL;
extern void *ptr_FindClose;
void *ptr_FindClose = NULL;
extern void *ptr_FindCloseChangeNotification;
void *ptr_FindCloseChangeNotification = NULL;
extern void *ptr_FindFirstChangeNotificationA;
void *ptr_FindFirstChangeNotificationA = NULL;
extern void *ptr_FindFirstChangeNotificationW;
void *ptr_FindFirstChangeNotificationW = NULL;
extern void *ptr_FindFirstFileA;
void *ptr_FindFirstFileA = NULL;
extern void *ptr_FindFirstFileExA;
void *ptr_FindFirstFileExA = NULL;
extern void *ptr_FindFirstFileExW;
void *ptr_FindFirstFileExW = NULL;
extern void *ptr_FindFirstFileW;
void *ptr_FindFirstFileW = NULL;
extern void *ptr_FindFirstVolumeW;
void *ptr_FindFirstVolumeW = NULL;
extern void *ptr_FindNextChangeNotification;
void *ptr_FindNextChangeNotification = NULL;
extern void *ptr_FindNextFileA;
void *ptr_FindNextFileA = NULL;
extern void *ptr_FindNextFileW;
void *ptr_FindNextFileW = NULL;
extern void *ptr_FindNextVolumeW;
void *ptr_FindNextVolumeW = NULL;
extern void *ptr_FindVolumeClose;
void *ptr_FindVolumeClose = NULL;
extern void *ptr_FlushFileBuffers;
void *ptr_FlushFileBuffers = NULL;
extern void *ptr_GetDiskFreeSpaceA;
void *ptr_GetDiskFreeSpaceA = NULL;
extern void *ptr_GetDiskFreeSpaceExA;
void *ptr_GetDiskFreeSpaceExA = NULL;
extern void *ptr_GetDiskFreeSpaceExW;
void *ptr_GetDiskFreeSpaceExW = NULL;
extern void *ptr_GetDiskFreeSpaceW;
void *ptr_GetDiskFreeSpaceW = NULL;
extern void *ptr_GetDriveTypeA;
void *ptr_GetDriveTypeA = NULL;
extern void *ptr_GetDriveTypeW;
void *ptr_GetDriveTypeW = NULL;
extern void *ptr_GetFileAttributesA;
void *ptr_GetFileAttributesA = NULL;
extern void *ptr_GetFileAttributesExA;
void *ptr_GetFileAttributesExA = NULL;
extern void *ptr_GetFileAttributesExW;
void *ptr_GetFileAttributesExW = NULL;
extern void *ptr_GetFileAttributesW;
void *ptr_GetFileAttributesW = NULL;
extern void *ptr_GetFileInformationByHandle;
void *ptr_GetFileInformationByHandle = NULL;
extern void *ptr_GetFileSize;
void *ptr_GetFileSize = NULL;
extern void *ptr_GetFileSizeEx;
void *ptr_GetFileSizeEx = NULL;
extern void *ptr_GetFileTime;
void *ptr_GetFileTime = NULL;
extern void *ptr_GetFileType;
void *ptr_GetFileType = NULL;
extern void *ptr_GetFinalPathNameByHandleA;
void *ptr_GetFinalPathNameByHandleA = NULL;
extern void *ptr_GetFinalPathNameByHandleW;
void *ptr_GetFinalPathNameByHandleW = NULL;
extern void *ptr_GetFullPathNameA;
void *ptr_GetFullPathNameA = NULL;
extern void *ptr_GetFullPathNameW;
void *ptr_GetFullPathNameW = NULL;
extern void *ptr_GetLogicalDriveStringsW;
void *ptr_GetLogicalDriveStringsW = NULL;
extern void *ptr_GetLogicalDrives;
void *ptr_GetLogicalDrives = NULL;
extern void *ptr_GetLongPathNameA;
void *ptr_GetLongPathNameA = NULL;
extern void *ptr_GetLongPathNameW;
void *ptr_GetLongPathNameW = NULL;
extern void *ptr_GetShortPathNameW;
void *ptr_GetShortPathNameW = NULL;
extern void *ptr_GetTempFileNameW;
void *ptr_GetTempFileNameW = NULL;
extern void *ptr_GetVolumeInformationByHandleW;
void *ptr_GetVolumeInformationByHandleW = NULL;
extern void *ptr_GetVolumeInformationW;
void *ptr_GetVolumeInformationW = NULL;
extern void *ptr_GetVolumePathNameW;
void *ptr_GetVolumePathNameW = NULL;
extern void *ptr_LocalFileTimeToFileTime;
void *ptr_LocalFileTimeToFileTime = NULL;
extern void *ptr_LockFile;
void *ptr_LockFile = NULL;
extern void *ptr_LockFileEx;
void *ptr_LockFileEx = NULL;
extern void *ptr_QueryDosDeviceW;
void *ptr_QueryDosDeviceW = NULL;
extern void *ptr_ReadFile;
void *ptr_ReadFile = NULL;
extern void *ptr_ReadFileEx;
void *ptr_ReadFileEx = NULL;
extern void *ptr_ReadFileScatter;
void *ptr_ReadFileScatter = NULL;
extern void *ptr_RemoveDirectoryA;
void *ptr_RemoveDirectoryA = NULL;
extern void *ptr_RemoveDirectoryW;
void *ptr_RemoveDirectoryW = NULL;
extern void *ptr_SetEndOfFile;
void *ptr_SetEndOfFile = NULL;
extern void *ptr_SetFileAttributesA;
void *ptr_SetFileAttributesA = NULL;
extern void *ptr_SetFileAttributesW;
void *ptr_SetFileAttributesW = NULL;
extern void *ptr_SetFileInformationByHandle;
void *ptr_SetFileInformationByHandle = NULL;
extern void *ptr_SetFilePointer;
void *ptr_SetFilePointer = NULL;
extern void *ptr_SetFilePointerEx;
void *ptr_SetFilePointerEx = NULL;
extern void *ptr_SetFileTime;
void *ptr_SetFileTime = NULL;
extern void *ptr_SetFileValidData;
void *ptr_SetFileValidData = NULL;
extern void *ptr_UnlockFile;
void *ptr_UnlockFile = NULL;
extern void *ptr_UnlockFileEx;
void *ptr_UnlockFileEx = NULL;
extern void *ptr_WriteFile;
void *ptr_WriteFile = NULL;
extern void *ptr_WriteFileEx;
void *ptr_WriteFileEx = NULL;
extern void *ptr_WriteFileGather;
void *ptr_WriteFileGather = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\api-ms-win-core-file-l1-1-0.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_CompareFileTime = (__vartype(ptr_CompareFileTime))GetProcAddress(hModule, "CompareFileTime");
   ptr_CreateDirectoryA = (__vartype(ptr_CreateDirectoryA))GetProcAddress(hModule, "CreateDirectoryA");
   ptr_CreateDirectoryW = (__vartype(ptr_CreateDirectoryW))GetProcAddress(hModule, "CreateDirectoryW");
   ptr_CreateFileA = (__vartype(ptr_CreateFileA))GetProcAddress(hModule, "CreateFileA");
   ptr_CreateFileW = (__vartype(ptr_CreateFileW))GetProcAddress(hModule, "CreateFileW");
   ptr_DefineDosDeviceW = (__vartype(ptr_DefineDosDeviceW))GetProcAddress(hModule, "DefineDosDeviceW");
   ptr_DeleteFileA = (__vartype(ptr_DeleteFileA))GetProcAddress(hModule, "DeleteFileA");
   ptr_DeleteFileW = (__vartype(ptr_DeleteFileW))GetProcAddress(hModule, "DeleteFileW");
   ptr_DeleteVolumeMountPointW = (__vartype(ptr_DeleteVolumeMountPointW))GetProcAddress(hModule, "DeleteVolumeMountPointW");
   ptr_FileTimeToLocalFileTime = (__vartype(ptr_FileTimeToLocalFileTime))GetProcAddress(hModule, "FileTimeToLocalFileTime");
   ptr_FileTimeToSystemTime = (__vartype(ptr_FileTimeToSystemTime))GetProcAddress(hModule, "FileTimeToSystemTime");
   ptr_FindClose = (__vartype(ptr_FindClose))GetProcAddress(hModule, "FindClose");
   ptr_FindCloseChangeNotification = (__vartype(ptr_FindCloseChangeNotification))GetProcAddress(hModule, "FindCloseChangeNotification");
   ptr_FindFirstChangeNotificationA = (__vartype(ptr_FindFirstChangeNotificationA))GetProcAddress(hModule, "FindFirstChangeNotificationA");
   ptr_FindFirstChangeNotificationW = (__vartype(ptr_FindFirstChangeNotificationW))GetProcAddress(hModule, "FindFirstChangeNotificationW");
   ptr_FindFirstFileA = (__vartype(ptr_FindFirstFileA))GetProcAddress(hModule, "FindFirstFileA");
   ptr_FindFirstFileExA = (__vartype(ptr_FindFirstFileExA))GetProcAddress(hModule, "FindFirstFileExA");
   ptr_FindFirstFileExW = (__vartype(ptr_FindFirstFileExW))GetProcAddress(hModule, "FindFirstFileExW");
   ptr_FindFirstFileW = (__vartype(ptr_FindFirstFileW))GetProcAddress(hModule, "FindFirstFileW");
   ptr_FindFirstVolumeW = (__vartype(ptr_FindFirstVolumeW))GetProcAddress(hModule, "FindFirstVolumeW");
   ptr_FindNextChangeNotification = (__vartype(ptr_FindNextChangeNotification))GetProcAddress(hModule, "FindNextChangeNotification");
   ptr_FindNextFileA = (__vartype(ptr_FindNextFileA))GetProcAddress(hModule, "FindNextFileA");
   ptr_FindNextFileW = (__vartype(ptr_FindNextFileW))GetProcAddress(hModule, "FindNextFileW");
   ptr_FindNextVolumeW = (__vartype(ptr_FindNextVolumeW))GetProcAddress(hModule, "FindNextVolumeW");
   ptr_FindVolumeClose = (__vartype(ptr_FindVolumeClose))GetProcAddress(hModule, "FindVolumeClose");
   ptr_FlushFileBuffers = (__vartype(ptr_FlushFileBuffers))GetProcAddress(hModule, "FlushFileBuffers");
   ptr_GetDiskFreeSpaceA = (__vartype(ptr_GetDiskFreeSpaceA))GetProcAddress(hModule, "GetDiskFreeSpaceA");
   ptr_GetDiskFreeSpaceExA = (__vartype(ptr_GetDiskFreeSpaceExA))GetProcAddress(hModule, "GetDiskFreeSpaceExA");
   ptr_GetDiskFreeSpaceExW = (__vartype(ptr_GetDiskFreeSpaceExW))GetProcAddress(hModule, "GetDiskFreeSpaceExW");
   ptr_GetDiskFreeSpaceW = (__vartype(ptr_GetDiskFreeSpaceW))GetProcAddress(hModule, "GetDiskFreeSpaceW");
   ptr_GetDriveTypeA = (__vartype(ptr_GetDriveTypeA))GetProcAddress(hModule, "GetDriveTypeA");
   ptr_GetDriveTypeW = (__vartype(ptr_GetDriveTypeW))GetProcAddress(hModule, "GetDriveTypeW");
   ptr_GetFileAttributesA = (__vartype(ptr_GetFileAttributesA))GetProcAddress(hModule, "GetFileAttributesA");
   ptr_GetFileAttributesExA = (__vartype(ptr_GetFileAttributesExA))GetProcAddress(hModule, "GetFileAttributesExA");
   ptr_GetFileAttributesExW = (__vartype(ptr_GetFileAttributesExW))GetProcAddress(hModule, "GetFileAttributesExW");
   ptr_GetFileAttributesW = (__vartype(ptr_GetFileAttributesW))GetProcAddress(hModule, "GetFileAttributesW");
   ptr_GetFileInformationByHandle = (__vartype(ptr_GetFileInformationByHandle))GetProcAddress(hModule, "GetFileInformationByHandle");
   ptr_GetFileSize = (__vartype(ptr_GetFileSize))GetProcAddress(hModule, "GetFileSize");
   ptr_GetFileSizeEx = (__vartype(ptr_GetFileSizeEx))GetProcAddress(hModule, "GetFileSizeEx");
   ptr_GetFileTime = (__vartype(ptr_GetFileTime))GetProcAddress(hModule, "GetFileTime");
   ptr_GetFileType = (__vartype(ptr_GetFileType))GetProcAddress(hModule, "GetFileType");
   ptr_GetFinalPathNameByHandleA = (__vartype(ptr_GetFinalPathNameByHandleA))GetProcAddress(hModule, "GetFinalPathNameByHandleA");
   ptr_GetFinalPathNameByHandleW = (__vartype(ptr_GetFinalPathNameByHandleW))GetProcAddress(hModule, "GetFinalPathNameByHandleW");
   ptr_GetFullPathNameA = (__vartype(ptr_GetFullPathNameA))GetProcAddress(hModule, "GetFullPathNameA");
   ptr_GetFullPathNameW = (__vartype(ptr_GetFullPathNameW))GetProcAddress(hModule, "GetFullPathNameW");
   ptr_GetLogicalDriveStringsW = (__vartype(ptr_GetLogicalDriveStringsW))GetProcAddress(hModule, "GetLogicalDriveStringsW");
   ptr_GetLogicalDrives = (__vartype(ptr_GetLogicalDrives))GetProcAddress(hModule, "GetLogicalDrives");
   ptr_GetLongPathNameA = (__vartype(ptr_GetLongPathNameA))GetProcAddress(hModule, "GetLongPathNameA");
   ptr_GetLongPathNameW = (__vartype(ptr_GetLongPathNameW))GetProcAddress(hModule, "GetLongPathNameW");
   ptr_GetShortPathNameW = (__vartype(ptr_GetShortPathNameW))GetProcAddress(hModule, "GetShortPathNameW");
   ptr_GetTempFileNameW = (__vartype(ptr_GetTempFileNameW))GetProcAddress(hModule, "GetTempFileNameW");
   ptr_GetVolumeInformationByHandleW = (__vartype(ptr_GetVolumeInformationByHandleW))GetProcAddress(hModule, "GetVolumeInformationByHandleW");
   ptr_GetVolumeInformationW = (__vartype(ptr_GetVolumeInformationW))GetProcAddress(hModule, "GetVolumeInformationW");
   ptr_GetVolumePathNameW = (__vartype(ptr_GetVolumePathNameW))GetProcAddress(hModule, "GetVolumePathNameW");
   ptr_LocalFileTimeToFileTime = (__vartype(ptr_LocalFileTimeToFileTime))GetProcAddress(hModule, "LocalFileTimeToFileTime");
   ptr_LockFile = (__vartype(ptr_LockFile))GetProcAddress(hModule, "LockFile");
   ptr_LockFileEx = (__vartype(ptr_LockFileEx))GetProcAddress(hModule, "LockFileEx");
   ptr_QueryDosDeviceW = (__vartype(ptr_QueryDosDeviceW))GetProcAddress(hModule, "QueryDosDeviceW");
   ptr_ReadFile = (__vartype(ptr_ReadFile))GetProcAddress(hModule, "ReadFile");
   ptr_ReadFileEx = (__vartype(ptr_ReadFileEx))GetProcAddress(hModule, "ReadFileEx");
   ptr_ReadFileScatter = (__vartype(ptr_ReadFileScatter))GetProcAddress(hModule, "ReadFileScatter");
   ptr_RemoveDirectoryA = (__vartype(ptr_RemoveDirectoryA))GetProcAddress(hModule, "RemoveDirectoryA");
   ptr_RemoveDirectoryW = (__vartype(ptr_RemoveDirectoryW))GetProcAddress(hModule, "RemoveDirectoryW");
   ptr_SetEndOfFile = (__vartype(ptr_SetEndOfFile))GetProcAddress(hModule, "SetEndOfFile");
   ptr_SetFileAttributesA = (__vartype(ptr_SetFileAttributesA))GetProcAddress(hModule, "SetFileAttributesA");
   ptr_SetFileAttributesW = (__vartype(ptr_SetFileAttributesW))GetProcAddress(hModule, "SetFileAttributesW");
   ptr_SetFileInformationByHandle = (__vartype(ptr_SetFileInformationByHandle))GetProcAddress(hModule, "SetFileInformationByHandle");
   ptr_SetFilePointer = (__vartype(ptr_SetFilePointer))GetProcAddress(hModule, "SetFilePointer");
   ptr_SetFilePointerEx = (__vartype(ptr_SetFilePointerEx))GetProcAddress(hModule, "SetFilePointerEx");
   ptr_SetFileTime = (__vartype(ptr_SetFileTime))GetProcAddress(hModule, "SetFileTime");
   ptr_SetFileValidData = (__vartype(ptr_SetFileValidData))GetProcAddress(hModule, "SetFileValidData");
   ptr_UnlockFile = (__vartype(ptr_UnlockFile))GetProcAddress(hModule, "UnlockFile");
   ptr_UnlockFileEx = (__vartype(ptr_UnlockFileEx))GetProcAddress(hModule, "UnlockFileEx");
   ptr_WriteFile = (__vartype(ptr_WriteFile))GetProcAddress(hModule, "WriteFile");
   ptr_WriteFileEx = (__vartype(ptr_WriteFileEx))GetProcAddress(hModule, "WriteFileEx");
   ptr_WriteFileGather = (__vartype(ptr_WriteFileGather))GetProcAddress(hModule, "WriteFileGather");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

