#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_DsAddSidHistoryA;
void *ptr_DsAddSidHistoryA = NULL;
extern void *ptr_DsAddSidHistoryW;
void *ptr_DsAddSidHistoryW = NULL;
extern void *ptr_DsBindA;
void *ptr_DsBindA = NULL;
extern void *ptr_DsBindByInstanceA;
void *ptr_DsBindByInstanceA = NULL;
extern void *ptr_DsBindByInstanceW;
void *ptr_DsBindByInstanceW = NULL;
extern void *ptr_DsBindToISTGA;
void *ptr_DsBindToISTGA = NULL;
extern void *ptr_DsBindToISTGW;
void *ptr_DsBindToISTGW = NULL;
extern void *ptr_DsBindW;
void *ptr_DsBindW = NULL;
extern void *ptr_DsBindWithCredA;
void *ptr_DsBindWithCredA = NULL;
extern void *ptr_DsBindWithCredW;
void *ptr_DsBindWithCredW = NULL;
extern void *ptr_DsBindWithSpnA;
void *ptr_DsBindWithSpnA = NULL;
extern void *ptr_DsBindWithSpnExA;
void *ptr_DsBindWithSpnExA = NULL;
extern void *ptr_DsBindWithSpnExW;
void *ptr_DsBindWithSpnExW = NULL;
extern void *ptr_DsBindWithSpnW;
void *ptr_DsBindWithSpnW = NULL;
extern void *ptr_DsBindingSetTimeout;
void *ptr_DsBindingSetTimeout = NULL;
extern void *ptr_DsClientMakeSpnForTargetServerA;
void *ptr_DsClientMakeSpnForTargetServerA = NULL;
extern void *ptr_DsClientMakeSpnForTargetServerW;
void *ptr_DsClientMakeSpnForTargetServerW = NULL;
extern void *ptr_DsCrackNamesA;
void *ptr_DsCrackNamesA = NULL;
extern void *ptr_DsCrackNamesW;
void *ptr_DsCrackNamesW = NULL;
extern void *ptr_DsCrackSpn2A;
void *ptr_DsCrackSpn2A = NULL;
extern void *ptr_DsCrackSpn2W;
void *ptr_DsCrackSpn2W = NULL;
extern void *ptr_DsCrackSpn3W;
void *ptr_DsCrackSpn3W = NULL;
extern void *ptr_DsCrackSpn4W;
void *ptr_DsCrackSpn4W = NULL;
extern void *ptr_DsCrackSpnA;
void *ptr_DsCrackSpnA = NULL;
extern void *ptr_DsCrackSpnW;
void *ptr_DsCrackSpnW = NULL;
extern void *ptr_DsCrackUnquotedMangledRdnA;
void *ptr_DsCrackUnquotedMangledRdnA = NULL;
extern void *ptr_DsCrackUnquotedMangledRdnW;
void *ptr_DsCrackUnquotedMangledRdnW = NULL;
extern void *ptr_DsFinishDemotionW;
void *ptr_DsFinishDemotionW = NULL;
extern void *ptr_DsFreeDomainControllerInfoA;
void *ptr_DsFreeDomainControllerInfoA = NULL;
extern void *ptr_DsFreeDomainControllerInfoW;
void *ptr_DsFreeDomainControllerInfoW = NULL;
extern void *ptr_DsFreeNameResultA;
void *ptr_DsFreeNameResultA = NULL;
extern void *ptr_DsFreeNameResultW;
void *ptr_DsFreeNameResultW = NULL;
extern void *ptr_DsFreePasswordCredentials;
void *ptr_DsFreePasswordCredentials = NULL;
extern void *ptr_DsFreeSchemaGuidMapA;
void *ptr_DsFreeSchemaGuidMapA = NULL;
extern void *ptr_DsFreeSchemaGuidMapW;
void *ptr_DsFreeSchemaGuidMapW = NULL;
extern void *ptr_DsFreeSpnArrayA;
void *ptr_DsFreeSpnArrayA = NULL;
extern void *ptr_DsFreeSpnArrayW;
void *ptr_DsFreeSpnArrayW = NULL;
extern void *ptr_DsGetBindAddrW;
void *ptr_DsGetBindAddrW = NULL;
extern void *ptr_DsGetBindAnnotW;
void *ptr_DsGetBindAnnotW = NULL;
extern void *ptr_DsGetBindInstGuid;
void *ptr_DsGetBindInstGuid = NULL;
extern void *ptr_DsGetDomainControllerInfoA;
void *ptr_DsGetDomainControllerInfoA = NULL;
extern void *ptr_DsGetDomainControllerInfoW;
void *ptr_DsGetDomainControllerInfoW = NULL;
extern void *ptr_DsGetRdnW;
void *ptr_DsGetRdnW = NULL;
extern void *ptr_DsGetSpnA;
void *ptr_DsGetSpnA = NULL;
extern void *ptr_DsGetSpnW;
void *ptr_DsGetSpnW = NULL;
extern void *ptr_DsInheritSecurityIdentityA;
void *ptr_DsInheritSecurityIdentityA = NULL;
extern void *ptr_DsInheritSecurityIdentityW;
void *ptr_DsInheritSecurityIdentityW = NULL;
extern void *ptr_DsInitDemotionW;
void *ptr_DsInitDemotionW = NULL;
extern void *ptr_DsIsMangledDnA;
void *ptr_DsIsMangledDnA = NULL;
extern void *ptr_DsIsMangledDnW;
void *ptr_DsIsMangledDnW = NULL;
extern void *ptr_DsIsMangledRdnValueA;
void *ptr_DsIsMangledRdnValueA = NULL;
extern void *ptr_DsIsMangledRdnValueW;
void *ptr_DsIsMangledRdnValueW = NULL;
extern void *ptr_DsListDomainsInSiteA;
void *ptr_DsListDomainsInSiteA = NULL;
extern void *ptr_DsListDomainsInSiteW;
void *ptr_DsListDomainsInSiteW = NULL;
extern void *ptr_DsListInfoForServerA;
void *ptr_DsListInfoForServerA = NULL;
extern void *ptr_DsListInfoForServerW;
void *ptr_DsListInfoForServerW = NULL;
extern void *ptr_DsListRolesA;
void *ptr_DsListRolesA = NULL;
extern void *ptr_DsListRolesW;
void *ptr_DsListRolesW = NULL;
extern void *ptr_DsListServersForDomainInSiteA;
void *ptr_DsListServersForDomainInSiteA = NULL;
extern void *ptr_DsListServersForDomainInSiteW;
void *ptr_DsListServersForDomainInSiteW = NULL;
extern void *ptr_DsListServersInSiteA;
void *ptr_DsListServersInSiteA = NULL;
extern void *ptr_DsListServersInSiteW;
void *ptr_DsListServersInSiteW = NULL;
extern void *ptr_DsListSitesA;
void *ptr_DsListSitesA = NULL;
extern void *ptr_DsListSitesW;
void *ptr_DsListSitesW = NULL;
extern void *ptr_DsLogEntry;
void *ptr_DsLogEntry = NULL;
extern void *ptr_DsMakePasswordCredentialsA;
void *ptr_DsMakePasswordCredentialsA = NULL;
extern void *ptr_DsMakePasswordCredentialsW;
void *ptr_DsMakePasswordCredentialsW = NULL;
extern void *ptr_DsMakeSpnA;
void *ptr_DsMakeSpnA = NULL;
extern void *ptr_DsMakeSpnW;
void *ptr_DsMakeSpnW = NULL;
extern void *ptr_DsMapSchemaGuidsA;
void *ptr_DsMapSchemaGuidsA = NULL;
extern void *ptr_DsMapSchemaGuidsW;
void *ptr_DsMapSchemaGuidsW = NULL;
extern void *ptr_DsQuerySitesByCostA;
void *ptr_DsQuerySitesByCostA = NULL;
extern void *ptr_DsQuerySitesByCostW;
void *ptr_DsQuerySitesByCostW = NULL;
extern void *ptr_DsQuerySitesFree;
void *ptr_DsQuerySitesFree = NULL;
extern void *ptr_DsQuoteRdnValueA;
void *ptr_DsQuoteRdnValueA = NULL;
extern void *ptr_DsQuoteRdnValueW;
void *ptr_DsQuoteRdnValueW = NULL;
extern void *ptr_DsRemoveDsDomainA;
void *ptr_DsRemoveDsDomainA = NULL;
extern void *ptr_DsRemoveDsDomainW;
void *ptr_DsRemoveDsDomainW = NULL;
extern void *ptr_DsRemoveDsServerA;
void *ptr_DsRemoveDsServerA = NULL;
extern void *ptr_DsRemoveDsServerW;
void *ptr_DsRemoveDsServerW = NULL;
extern void *ptr_DsReplicaAddA;
void *ptr_DsReplicaAddA = NULL;
extern void *ptr_DsReplicaAddW;
void *ptr_DsReplicaAddW = NULL;
extern void *ptr_DsReplicaConsistencyCheck;
void *ptr_DsReplicaConsistencyCheck = NULL;
extern void *ptr_DsReplicaDelA;
void *ptr_DsReplicaDelA = NULL;
extern void *ptr_DsReplicaDelW;
void *ptr_DsReplicaDelW = NULL;
extern void *ptr_DsReplicaDemotionW;
void *ptr_DsReplicaDemotionW = NULL;
extern void *ptr_DsReplicaFreeInfo;
void *ptr_DsReplicaFreeInfo = NULL;
extern void *ptr_DsReplicaGetInfo2W;
void *ptr_DsReplicaGetInfo2W = NULL;
extern void *ptr_DsReplicaGetInfoW;
void *ptr_DsReplicaGetInfoW = NULL;
extern void *ptr_DsReplicaModifyA;
void *ptr_DsReplicaModifyA = NULL;
extern void *ptr_DsReplicaModifyW;
void *ptr_DsReplicaModifyW = NULL;
extern void *ptr_DsReplicaSyncA;
void *ptr_DsReplicaSyncA = NULL;
extern void *ptr_DsReplicaSyncAllA;
void *ptr_DsReplicaSyncAllA = NULL;
extern void *ptr_DsReplicaSyncAllW;
void *ptr_DsReplicaSyncAllW = NULL;
extern void *ptr_DsReplicaSyncW;
void *ptr_DsReplicaSyncW = NULL;
extern void *ptr_DsReplicaUpdateRefsA;
void *ptr_DsReplicaUpdateRefsA = NULL;
extern void *ptr_DsReplicaUpdateRefsW;
void *ptr_DsReplicaUpdateRefsW = NULL;
extern void *ptr_DsReplicaVerifyObjectsA;
void *ptr_DsReplicaVerifyObjectsA = NULL;
extern void *ptr_DsReplicaVerifyObjectsW;
void *ptr_DsReplicaVerifyObjectsW = NULL;
extern void *ptr_DsServerRegisterSpnA;
void *ptr_DsServerRegisterSpnA = NULL;
extern void *ptr_DsServerRegisterSpnW;
void *ptr_DsServerRegisterSpnW = NULL;
extern void *ptr_DsUnBindA;
void *ptr_DsUnBindA = NULL;
extern void *ptr_DsUnBindW;
void *ptr_DsUnBindW = NULL;
extern void *ptr_DsUnquoteRdnValueA;
void *ptr_DsUnquoteRdnValueA = NULL;
extern void *ptr_DsUnquoteRdnValueW;
void *ptr_DsUnquoteRdnValueW = NULL;
extern void *ptr_DsWriteAccountSpnA;
void *ptr_DsWriteAccountSpnA = NULL;
extern void *ptr_DsWriteAccountSpnW;
void *ptr_DsWriteAccountSpnW = NULL;
extern void *ptr_DsaopBind;
void *ptr_DsaopBind = NULL;
extern void *ptr_DsaopBindWithCred;
void *ptr_DsaopBindWithCred = NULL;
extern void *ptr_DsaopBindWithSpn;
void *ptr_DsaopBindWithSpn = NULL;
extern void *ptr_DsaopExecuteScript;
void *ptr_DsaopExecuteScript = NULL;
extern void *ptr_DsaopPrepareScript;
void *ptr_DsaopPrepareScript = NULL;
extern void *ptr_DsaopUnBind;
void *ptr_DsaopUnBind = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\ntdsapi.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_DsAddSidHistoryA = (__vartype(ptr_DsAddSidHistoryA))GetProcAddress(hModule, "DsAddSidHistoryA");
   ptr_DsAddSidHistoryW = (__vartype(ptr_DsAddSidHistoryW))GetProcAddress(hModule, "DsAddSidHistoryW");
   ptr_DsBindA = (__vartype(ptr_DsBindA))GetProcAddress(hModule, "DsBindA");
   ptr_DsBindByInstanceA = (__vartype(ptr_DsBindByInstanceA))GetProcAddress(hModule, "DsBindByInstanceA");
   ptr_DsBindByInstanceW = (__vartype(ptr_DsBindByInstanceW))GetProcAddress(hModule, "DsBindByInstanceW");
   ptr_DsBindToISTGA = (__vartype(ptr_DsBindToISTGA))GetProcAddress(hModule, "DsBindToISTGA");
   ptr_DsBindToISTGW = (__vartype(ptr_DsBindToISTGW))GetProcAddress(hModule, "DsBindToISTGW");
   ptr_DsBindW = (__vartype(ptr_DsBindW))GetProcAddress(hModule, "DsBindW");
   ptr_DsBindWithCredA = (__vartype(ptr_DsBindWithCredA))GetProcAddress(hModule, "DsBindWithCredA");
   ptr_DsBindWithCredW = (__vartype(ptr_DsBindWithCredW))GetProcAddress(hModule, "DsBindWithCredW");
   ptr_DsBindWithSpnA = (__vartype(ptr_DsBindWithSpnA))GetProcAddress(hModule, "DsBindWithSpnA");
   ptr_DsBindWithSpnExA = (__vartype(ptr_DsBindWithSpnExA))GetProcAddress(hModule, "DsBindWithSpnExA");
   ptr_DsBindWithSpnExW = (__vartype(ptr_DsBindWithSpnExW))GetProcAddress(hModule, "DsBindWithSpnExW");
   ptr_DsBindWithSpnW = (__vartype(ptr_DsBindWithSpnW))GetProcAddress(hModule, "DsBindWithSpnW");
   ptr_DsBindingSetTimeout = (__vartype(ptr_DsBindingSetTimeout))GetProcAddress(hModule, "DsBindingSetTimeout");
   ptr_DsClientMakeSpnForTargetServerA = (__vartype(ptr_DsClientMakeSpnForTargetServerA))GetProcAddress(hModule, "DsClientMakeSpnForTargetServerA");
   ptr_DsClientMakeSpnForTargetServerW = (__vartype(ptr_DsClientMakeSpnForTargetServerW))GetProcAddress(hModule, "DsClientMakeSpnForTargetServerW");
   ptr_DsCrackNamesA = (__vartype(ptr_DsCrackNamesA))GetProcAddress(hModule, "DsCrackNamesA");
   ptr_DsCrackNamesW = (__vartype(ptr_DsCrackNamesW))GetProcAddress(hModule, "DsCrackNamesW");
   ptr_DsCrackSpn2A = (__vartype(ptr_DsCrackSpn2A))GetProcAddress(hModule, "DsCrackSpn2A");
   ptr_DsCrackSpn2W = (__vartype(ptr_DsCrackSpn2W))GetProcAddress(hModule, "DsCrackSpn2W");
   ptr_DsCrackSpn3W = (__vartype(ptr_DsCrackSpn3W))GetProcAddress(hModule, "DsCrackSpn3W");
   ptr_DsCrackSpn4W = (__vartype(ptr_DsCrackSpn4W))GetProcAddress(hModule, "DsCrackSpn4W");
   ptr_DsCrackSpnA = (__vartype(ptr_DsCrackSpnA))GetProcAddress(hModule, "DsCrackSpnA");
   ptr_DsCrackSpnW = (__vartype(ptr_DsCrackSpnW))GetProcAddress(hModule, "DsCrackSpnW");
   ptr_DsCrackUnquotedMangledRdnA = (__vartype(ptr_DsCrackUnquotedMangledRdnA))GetProcAddress(hModule, "DsCrackUnquotedMangledRdnA");
   ptr_DsCrackUnquotedMangledRdnW = (__vartype(ptr_DsCrackUnquotedMangledRdnW))GetProcAddress(hModule, "DsCrackUnquotedMangledRdnW");
   ptr_DsFinishDemotionW = (__vartype(ptr_DsFinishDemotionW))GetProcAddress(hModule, "DsFinishDemotionW");
   ptr_DsFreeDomainControllerInfoA = (__vartype(ptr_DsFreeDomainControllerInfoA))GetProcAddress(hModule, "DsFreeDomainControllerInfoA");
   ptr_DsFreeDomainControllerInfoW = (__vartype(ptr_DsFreeDomainControllerInfoW))GetProcAddress(hModule, "DsFreeDomainControllerInfoW");
   ptr_DsFreeNameResultA = (__vartype(ptr_DsFreeNameResultA))GetProcAddress(hModule, "DsFreeNameResultA");
   ptr_DsFreeNameResultW = (__vartype(ptr_DsFreeNameResultW))GetProcAddress(hModule, "DsFreeNameResultW");
   ptr_DsFreePasswordCredentials = (__vartype(ptr_DsFreePasswordCredentials))GetProcAddress(hModule, "DsFreePasswordCredentials");
   ptr_DsFreeSchemaGuidMapA = (__vartype(ptr_DsFreeSchemaGuidMapA))GetProcAddress(hModule, "DsFreeSchemaGuidMapA");
   ptr_DsFreeSchemaGuidMapW = (__vartype(ptr_DsFreeSchemaGuidMapW))GetProcAddress(hModule, "DsFreeSchemaGuidMapW");
   ptr_DsFreeSpnArrayA = (__vartype(ptr_DsFreeSpnArrayA))GetProcAddress(hModule, "DsFreeSpnArrayA");
   ptr_DsFreeSpnArrayW = (__vartype(ptr_DsFreeSpnArrayW))GetProcAddress(hModule, "DsFreeSpnArrayW");
   ptr_DsGetBindAddrW = (__vartype(ptr_DsGetBindAddrW))GetProcAddress(hModule, "DsGetBindAddrW");
   ptr_DsGetBindAnnotW = (__vartype(ptr_DsGetBindAnnotW))GetProcAddress(hModule, "DsGetBindAnnotW");
   ptr_DsGetBindInstGuid = (__vartype(ptr_DsGetBindInstGuid))GetProcAddress(hModule, "DsGetBindInstGuid");
   ptr_DsGetDomainControllerInfoA = (__vartype(ptr_DsGetDomainControllerInfoA))GetProcAddress(hModule, "DsGetDomainControllerInfoA");
   ptr_DsGetDomainControllerInfoW = (__vartype(ptr_DsGetDomainControllerInfoW))GetProcAddress(hModule, "DsGetDomainControllerInfoW");
   ptr_DsGetRdnW = (__vartype(ptr_DsGetRdnW))GetProcAddress(hModule, "DsGetRdnW");
   ptr_DsGetSpnA = (__vartype(ptr_DsGetSpnA))GetProcAddress(hModule, "DsGetSpnA");
   ptr_DsGetSpnW = (__vartype(ptr_DsGetSpnW))GetProcAddress(hModule, "DsGetSpnW");
   ptr_DsInheritSecurityIdentityA = (__vartype(ptr_DsInheritSecurityIdentityA))GetProcAddress(hModule, "DsInheritSecurityIdentityA");
   ptr_DsInheritSecurityIdentityW = (__vartype(ptr_DsInheritSecurityIdentityW))GetProcAddress(hModule, "DsInheritSecurityIdentityW");
   ptr_DsInitDemotionW = (__vartype(ptr_DsInitDemotionW))GetProcAddress(hModule, "DsInitDemotionW");
   ptr_DsIsMangledDnA = (__vartype(ptr_DsIsMangledDnA))GetProcAddress(hModule, "DsIsMangledDnA");
   ptr_DsIsMangledDnW = (__vartype(ptr_DsIsMangledDnW))GetProcAddress(hModule, "DsIsMangledDnW");
   ptr_DsIsMangledRdnValueA = (__vartype(ptr_DsIsMangledRdnValueA))GetProcAddress(hModule, "DsIsMangledRdnValueA");
   ptr_DsIsMangledRdnValueW = (__vartype(ptr_DsIsMangledRdnValueW))GetProcAddress(hModule, "DsIsMangledRdnValueW");
   ptr_DsListDomainsInSiteA = (__vartype(ptr_DsListDomainsInSiteA))GetProcAddress(hModule, "DsListDomainsInSiteA");
   ptr_DsListDomainsInSiteW = (__vartype(ptr_DsListDomainsInSiteW))GetProcAddress(hModule, "DsListDomainsInSiteW");
   ptr_DsListInfoForServerA = (__vartype(ptr_DsListInfoForServerA))GetProcAddress(hModule, "DsListInfoForServerA");
   ptr_DsListInfoForServerW = (__vartype(ptr_DsListInfoForServerW))GetProcAddress(hModule, "DsListInfoForServerW");
   ptr_DsListRolesA = (__vartype(ptr_DsListRolesA))GetProcAddress(hModule, "DsListRolesA");
   ptr_DsListRolesW = (__vartype(ptr_DsListRolesW))GetProcAddress(hModule, "DsListRolesW");
   ptr_DsListServersForDomainInSiteA = (__vartype(ptr_DsListServersForDomainInSiteA))GetProcAddress(hModule, "DsListServersForDomainInSiteA");
   ptr_DsListServersForDomainInSiteW = (__vartype(ptr_DsListServersForDomainInSiteW))GetProcAddress(hModule, "DsListServersForDomainInSiteW");
   ptr_DsListServersInSiteA = (__vartype(ptr_DsListServersInSiteA))GetProcAddress(hModule, "DsListServersInSiteA");
   ptr_DsListServersInSiteW = (__vartype(ptr_DsListServersInSiteW))GetProcAddress(hModule, "DsListServersInSiteW");
   ptr_DsListSitesA = (__vartype(ptr_DsListSitesA))GetProcAddress(hModule, "DsListSitesA");
   ptr_DsListSitesW = (__vartype(ptr_DsListSitesW))GetProcAddress(hModule, "DsListSitesW");
   ptr_DsLogEntry = (__vartype(ptr_DsLogEntry))GetProcAddress(hModule, "DsLogEntry");
   ptr_DsMakePasswordCredentialsA = (__vartype(ptr_DsMakePasswordCredentialsA))GetProcAddress(hModule, "DsMakePasswordCredentialsA");
   ptr_DsMakePasswordCredentialsW = (__vartype(ptr_DsMakePasswordCredentialsW))GetProcAddress(hModule, "DsMakePasswordCredentialsW");
   ptr_DsMakeSpnA = (__vartype(ptr_DsMakeSpnA))GetProcAddress(hModule, "DsMakeSpnA");
   ptr_DsMakeSpnW = (__vartype(ptr_DsMakeSpnW))GetProcAddress(hModule, "DsMakeSpnW");
   ptr_DsMapSchemaGuidsA = (__vartype(ptr_DsMapSchemaGuidsA))GetProcAddress(hModule, "DsMapSchemaGuidsA");
   ptr_DsMapSchemaGuidsW = (__vartype(ptr_DsMapSchemaGuidsW))GetProcAddress(hModule, "DsMapSchemaGuidsW");
   ptr_DsQuerySitesByCostA = (__vartype(ptr_DsQuerySitesByCostA))GetProcAddress(hModule, "DsQuerySitesByCostA");
   ptr_DsQuerySitesByCostW = (__vartype(ptr_DsQuerySitesByCostW))GetProcAddress(hModule, "DsQuerySitesByCostW");
   ptr_DsQuerySitesFree = (__vartype(ptr_DsQuerySitesFree))GetProcAddress(hModule, "DsQuerySitesFree");
   ptr_DsQuoteRdnValueA = (__vartype(ptr_DsQuoteRdnValueA))GetProcAddress(hModule, "DsQuoteRdnValueA");
   ptr_DsQuoteRdnValueW = (__vartype(ptr_DsQuoteRdnValueW))GetProcAddress(hModule, "DsQuoteRdnValueW");
   ptr_DsRemoveDsDomainA = (__vartype(ptr_DsRemoveDsDomainA))GetProcAddress(hModule, "DsRemoveDsDomainA");
   ptr_DsRemoveDsDomainW = (__vartype(ptr_DsRemoveDsDomainW))GetProcAddress(hModule, "DsRemoveDsDomainW");
   ptr_DsRemoveDsServerA = (__vartype(ptr_DsRemoveDsServerA))GetProcAddress(hModule, "DsRemoveDsServerA");
   ptr_DsRemoveDsServerW = (__vartype(ptr_DsRemoveDsServerW))GetProcAddress(hModule, "DsRemoveDsServerW");
   ptr_DsReplicaAddA = (__vartype(ptr_DsReplicaAddA))GetProcAddress(hModule, "DsReplicaAddA");
   ptr_DsReplicaAddW = (__vartype(ptr_DsReplicaAddW))GetProcAddress(hModule, "DsReplicaAddW");
   ptr_DsReplicaConsistencyCheck = (__vartype(ptr_DsReplicaConsistencyCheck))GetProcAddress(hModule, "DsReplicaConsistencyCheck");
   ptr_DsReplicaDelA = (__vartype(ptr_DsReplicaDelA))GetProcAddress(hModule, "DsReplicaDelA");
   ptr_DsReplicaDelW = (__vartype(ptr_DsReplicaDelW))GetProcAddress(hModule, "DsReplicaDelW");
   ptr_DsReplicaDemotionW = (__vartype(ptr_DsReplicaDemotionW))GetProcAddress(hModule, "DsReplicaDemotionW");
   ptr_DsReplicaFreeInfo = (__vartype(ptr_DsReplicaFreeInfo))GetProcAddress(hModule, "DsReplicaFreeInfo");
   ptr_DsReplicaGetInfo2W = (__vartype(ptr_DsReplicaGetInfo2W))GetProcAddress(hModule, "DsReplicaGetInfo2W");
   ptr_DsReplicaGetInfoW = (__vartype(ptr_DsReplicaGetInfoW))GetProcAddress(hModule, "DsReplicaGetInfoW");
   ptr_DsReplicaModifyA = (__vartype(ptr_DsReplicaModifyA))GetProcAddress(hModule, "DsReplicaModifyA");
   ptr_DsReplicaModifyW = (__vartype(ptr_DsReplicaModifyW))GetProcAddress(hModule, "DsReplicaModifyW");
   ptr_DsReplicaSyncA = (__vartype(ptr_DsReplicaSyncA))GetProcAddress(hModule, "DsReplicaSyncA");
   ptr_DsReplicaSyncAllA = (__vartype(ptr_DsReplicaSyncAllA))GetProcAddress(hModule, "DsReplicaSyncAllA");
   ptr_DsReplicaSyncAllW = (__vartype(ptr_DsReplicaSyncAllW))GetProcAddress(hModule, "DsReplicaSyncAllW");
   ptr_DsReplicaSyncW = (__vartype(ptr_DsReplicaSyncW))GetProcAddress(hModule, "DsReplicaSyncW");
   ptr_DsReplicaUpdateRefsA = (__vartype(ptr_DsReplicaUpdateRefsA))GetProcAddress(hModule, "DsReplicaUpdateRefsA");
   ptr_DsReplicaUpdateRefsW = (__vartype(ptr_DsReplicaUpdateRefsW))GetProcAddress(hModule, "DsReplicaUpdateRefsW");
   ptr_DsReplicaVerifyObjectsA = (__vartype(ptr_DsReplicaVerifyObjectsA))GetProcAddress(hModule, "DsReplicaVerifyObjectsA");
   ptr_DsReplicaVerifyObjectsW = (__vartype(ptr_DsReplicaVerifyObjectsW))GetProcAddress(hModule, "DsReplicaVerifyObjectsW");
   ptr_DsServerRegisterSpnA = (__vartype(ptr_DsServerRegisterSpnA))GetProcAddress(hModule, "DsServerRegisterSpnA");
   ptr_DsServerRegisterSpnW = (__vartype(ptr_DsServerRegisterSpnW))GetProcAddress(hModule, "DsServerRegisterSpnW");
   ptr_DsUnBindA = (__vartype(ptr_DsUnBindA))GetProcAddress(hModule, "DsUnBindA");
   ptr_DsUnBindW = (__vartype(ptr_DsUnBindW))GetProcAddress(hModule, "DsUnBindW");
   ptr_DsUnquoteRdnValueA = (__vartype(ptr_DsUnquoteRdnValueA))GetProcAddress(hModule, "DsUnquoteRdnValueA");
   ptr_DsUnquoteRdnValueW = (__vartype(ptr_DsUnquoteRdnValueW))GetProcAddress(hModule, "DsUnquoteRdnValueW");
   ptr_DsWriteAccountSpnA = (__vartype(ptr_DsWriteAccountSpnA))GetProcAddress(hModule, "DsWriteAccountSpnA");
   ptr_DsWriteAccountSpnW = (__vartype(ptr_DsWriteAccountSpnW))GetProcAddress(hModule, "DsWriteAccountSpnW");
   ptr_DsaopBind = (__vartype(ptr_DsaopBind))GetProcAddress(hModule, "DsaopBind");
   ptr_DsaopBindWithCred = (__vartype(ptr_DsaopBindWithCred))GetProcAddress(hModule, "DsaopBindWithCred");
   ptr_DsaopBindWithSpn = (__vartype(ptr_DsaopBindWithSpn))GetProcAddress(hModule, "DsaopBindWithSpn");
   ptr_DsaopExecuteScript = (__vartype(ptr_DsaopExecuteScript))GetProcAddress(hModule, "DsaopExecuteScript");
   ptr_DsaopPrepareScript = (__vartype(ptr_DsaopPrepareScript))GetProcAddress(hModule, "DsaopPrepareScript");
   ptr_DsaopUnBind = (__vartype(ptr_DsaopUnBind))GetProcAddress(hModule, "DsaopUnBind");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

