#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_DllCanUnloadNow;
void *ptr_DllCanUnloadNow = NULL;
extern void *ptr_DllGetClassObject;
void *ptr_DllGetClassObject = NULL;
extern void *ptr_DllGetVersion;
void *ptr_DllGetVersion = NULL;
extern void *ptr_DllRegisterServer;
void *ptr_DllRegisterServer = NULL;
extern void *ptr_DllUnregisterServer;
void *ptr_DllUnregisterServer = NULL;
extern void *ptr_Migrate10CachedPackagesA;
void *ptr_Migrate10CachedPackagesA = NULL;
extern void *ptr_Migrate10CachedPackagesW;
void *ptr_Migrate10CachedPackagesW = NULL;
extern void *ptr_MsiAdvertiseProductA;
void *ptr_MsiAdvertiseProductA = NULL;
extern void *ptr_MsiAdvertiseProductExA;
void *ptr_MsiAdvertiseProductExA = NULL;
extern void *ptr_MsiAdvertiseProductExW;
void *ptr_MsiAdvertiseProductExW = NULL;
extern void *ptr_MsiAdvertiseProductW;
void *ptr_MsiAdvertiseProductW = NULL;
extern void *ptr_MsiAdvertiseScriptA;
void *ptr_MsiAdvertiseScriptA = NULL;
extern void *ptr_MsiAdvertiseScriptW;
void *ptr_MsiAdvertiseScriptW = NULL;
extern void *ptr_MsiApplyMultiplePatchesA;
void *ptr_MsiApplyMultiplePatchesA = NULL;
extern void *ptr_MsiApplyMultiplePatchesW;
void *ptr_MsiApplyMultiplePatchesW = NULL;
extern void *ptr_MsiApplyPatchA;
void *ptr_MsiApplyPatchA = NULL;
extern void *ptr_MsiApplyPatchW;
void *ptr_MsiApplyPatchW = NULL;
extern void *ptr_MsiBeginTransactionA;
void *ptr_MsiBeginTransactionA = NULL;
extern void *ptr_MsiBeginTransactionW;
void *ptr_MsiBeginTransactionW = NULL;
extern void *ptr_MsiCloseAllHandles;
void *ptr_MsiCloseAllHandles = NULL;
extern void *ptr_MsiCloseHandle;
void *ptr_MsiCloseHandle = NULL;
extern void *ptr_MsiCollectUserInfoA;
void *ptr_MsiCollectUserInfoA = NULL;
extern void *ptr_MsiCollectUserInfoW;
void *ptr_MsiCollectUserInfoW = NULL;
extern void *ptr_MsiConfigureFeatureA;
void *ptr_MsiConfigureFeatureA = NULL;
extern void *ptr_MsiConfigureFeatureFromDescriptorA;
void *ptr_MsiConfigureFeatureFromDescriptorA = NULL;
extern void *ptr_MsiConfigureFeatureFromDescriptorW;
void *ptr_MsiConfigureFeatureFromDescriptorW = NULL;
extern void *ptr_MsiConfigureFeatureW;
void *ptr_MsiConfigureFeatureW = NULL;
extern void *ptr_MsiConfigureProductA;
void *ptr_MsiConfigureProductA = NULL;
extern void *ptr_MsiConfigureProductExA;
void *ptr_MsiConfigureProductExA = NULL;
extern void *ptr_MsiConfigureProductExW;
void *ptr_MsiConfigureProductExW = NULL;
extern void *ptr_MsiConfigureProductW;
void *ptr_MsiConfigureProductW = NULL;
extern void *ptr_MsiCreateAndVerifyInstallerDirectory;
void *ptr_MsiCreateAndVerifyInstallerDirectory = NULL;
extern void *ptr_MsiCreateRecord;
void *ptr_MsiCreateRecord = NULL;
extern void *ptr_MsiCreateTransformSummaryInfoA;
void *ptr_MsiCreateTransformSummaryInfoA = NULL;
extern void *ptr_MsiCreateTransformSummaryInfoW;
void *ptr_MsiCreateTransformSummaryInfoW = NULL;
extern void *ptr_MsiDatabaseApplyTransformA;
void *ptr_MsiDatabaseApplyTransformA = NULL;
extern void *ptr_MsiDatabaseApplyTransformW;
void *ptr_MsiDatabaseApplyTransformW = NULL;
extern void *ptr_MsiDatabaseCommit;
void *ptr_MsiDatabaseCommit = NULL;
extern void *ptr_MsiDatabaseExportA;
void *ptr_MsiDatabaseExportA = NULL;
extern void *ptr_MsiDatabaseExportW;
void *ptr_MsiDatabaseExportW = NULL;
extern void *ptr_MsiDatabaseGenerateTransformA;
void *ptr_MsiDatabaseGenerateTransformA = NULL;
extern void *ptr_MsiDatabaseGenerateTransformW;
void *ptr_MsiDatabaseGenerateTransformW = NULL;
extern void *ptr_MsiDatabaseGetPrimaryKeysA;
void *ptr_MsiDatabaseGetPrimaryKeysA = NULL;
extern void *ptr_MsiDatabaseGetPrimaryKeysW;
void *ptr_MsiDatabaseGetPrimaryKeysW = NULL;
extern void *ptr_MsiDatabaseImportA;
void *ptr_MsiDatabaseImportA = NULL;
extern void *ptr_MsiDatabaseImportW;
void *ptr_MsiDatabaseImportW = NULL;
extern void *ptr_MsiDatabaseIsTablePersistentA;
void *ptr_MsiDatabaseIsTablePersistentA = NULL;
extern void *ptr_MsiDatabaseIsTablePersistentW;
void *ptr_MsiDatabaseIsTablePersistentW = NULL;
extern void *ptr_MsiDatabaseMergeA;
void *ptr_MsiDatabaseMergeA = NULL;
extern void *ptr_MsiDatabaseMergeW;
void *ptr_MsiDatabaseMergeW = NULL;
extern void *ptr_MsiDatabaseOpenViewA;
void *ptr_MsiDatabaseOpenViewA = NULL;
extern void *ptr_MsiDatabaseOpenViewW;
void *ptr_MsiDatabaseOpenViewW = NULL;
extern void *ptr_MsiDecomposeDescriptorA;
void *ptr_MsiDecomposeDescriptorA = NULL;
extern void *ptr_MsiDecomposeDescriptorW;
void *ptr_MsiDecomposeDescriptorW = NULL;
extern void *ptr_MsiDeleteUserDataA;
void *ptr_MsiDeleteUserDataA = NULL;
extern void *ptr_MsiDeleteUserDataW;
void *ptr_MsiDeleteUserDataW = NULL;
extern void *ptr_MsiDetermineApplicablePatchesA;
void *ptr_MsiDetermineApplicablePatchesA = NULL;
extern void *ptr_MsiDetermineApplicablePatchesW;
void *ptr_MsiDetermineApplicablePatchesW = NULL;
extern void *ptr_MsiDeterminePatchSequenceA;
void *ptr_MsiDeterminePatchSequenceA = NULL;
extern void *ptr_MsiDeterminePatchSequenceW;
void *ptr_MsiDeterminePatchSequenceW = NULL;
extern void *ptr_MsiDoActionA;
void *ptr_MsiDoActionA = NULL;
extern void *ptr_MsiDoActionW;
void *ptr_MsiDoActionW = NULL;
extern void *ptr_MsiEnableLogA;
void *ptr_MsiEnableLogA = NULL;
extern void *ptr_MsiEnableLogW;
void *ptr_MsiEnableLogW = NULL;
extern void *ptr_MsiEnableUIPreview;
void *ptr_MsiEnableUIPreview = NULL;
extern void *ptr_MsiEndTransaction;
void *ptr_MsiEndTransaction = NULL;
extern void *ptr_MsiEnumClientsA;
void *ptr_MsiEnumClientsA = NULL;
extern void *ptr_MsiEnumClientsExA;
void *ptr_MsiEnumClientsExA = NULL;
extern void *ptr_MsiEnumClientsExW;
void *ptr_MsiEnumClientsExW = NULL;
extern void *ptr_MsiEnumClientsW;
void *ptr_MsiEnumClientsW = NULL;
extern void *ptr_MsiEnumComponentCostsA;
void *ptr_MsiEnumComponentCostsA = NULL;
extern void *ptr_MsiEnumComponentCostsW;
void *ptr_MsiEnumComponentCostsW = NULL;
extern void *ptr_MsiEnumComponentQualifiersA;
void *ptr_MsiEnumComponentQualifiersA = NULL;
extern void *ptr_MsiEnumComponentQualifiersW;
void *ptr_MsiEnumComponentQualifiersW = NULL;
extern void *ptr_MsiEnumComponentsA;
void *ptr_MsiEnumComponentsA = NULL;
extern void *ptr_MsiEnumComponentsExA;
void *ptr_MsiEnumComponentsExA = NULL;
extern void *ptr_MsiEnumComponentsExW;
void *ptr_MsiEnumComponentsExW = NULL;
extern void *ptr_MsiEnumComponentsW;
void *ptr_MsiEnumComponentsW = NULL;
extern void *ptr_MsiEnumFeaturesA;
void *ptr_MsiEnumFeaturesA = NULL;
extern void *ptr_MsiEnumFeaturesW;
void *ptr_MsiEnumFeaturesW = NULL;
extern void *ptr_MsiEnumPatchesA;
void *ptr_MsiEnumPatchesA = NULL;
extern void *ptr_MsiEnumPatchesExA;
void *ptr_MsiEnumPatchesExA = NULL;
extern void *ptr_MsiEnumPatchesExW;
void *ptr_MsiEnumPatchesExW = NULL;
extern void *ptr_MsiEnumPatchesW;
void *ptr_MsiEnumPatchesW = NULL;
extern void *ptr_MsiEnumProductsA;
void *ptr_MsiEnumProductsA = NULL;
extern void *ptr_MsiEnumProductsExA;
void *ptr_MsiEnumProductsExA = NULL;
extern void *ptr_MsiEnumProductsExW;
void *ptr_MsiEnumProductsExW = NULL;
extern void *ptr_MsiEnumProductsW;
void *ptr_MsiEnumProductsW = NULL;
extern void *ptr_MsiEnumRelatedProductsA;
void *ptr_MsiEnumRelatedProductsA = NULL;
extern void *ptr_MsiEnumRelatedProductsW;
void *ptr_MsiEnumRelatedProductsW = NULL;
extern void *ptr_MsiEvaluateConditionA;
void *ptr_MsiEvaluateConditionA = NULL;
extern void *ptr_MsiEvaluateConditionW;
void *ptr_MsiEvaluateConditionW = NULL;
extern void *ptr_MsiExtractPatchXMLDataA;
void *ptr_MsiExtractPatchXMLDataA = NULL;
extern void *ptr_MsiExtractPatchXMLDataW;
void *ptr_MsiExtractPatchXMLDataW = NULL;
extern void *ptr_MsiFormatRecordA;
void *ptr_MsiFormatRecordA = NULL;
extern void *ptr_MsiFormatRecordW;
void *ptr_MsiFormatRecordW = NULL;
extern void *ptr_MsiGetActiveDatabase;
void *ptr_MsiGetActiveDatabase = NULL;
extern void *ptr_MsiGetComponentPathA;
void *ptr_MsiGetComponentPathA = NULL;
extern void *ptr_MsiGetComponentPathExA;
void *ptr_MsiGetComponentPathExA = NULL;
extern void *ptr_MsiGetComponentPathExW;
void *ptr_MsiGetComponentPathExW = NULL;
extern void *ptr_MsiGetComponentPathW;
void *ptr_MsiGetComponentPathW = NULL;
extern void *ptr_MsiGetComponentStateA;
void *ptr_MsiGetComponentStateA = NULL;
extern void *ptr_MsiGetComponentStateW;
void *ptr_MsiGetComponentStateW = NULL;
extern void *ptr_MsiGetDatabaseState;
void *ptr_MsiGetDatabaseState = NULL;
extern void *ptr_MsiGetFeatureCostA;
void *ptr_MsiGetFeatureCostA = NULL;
extern void *ptr_MsiGetFeatureCostW;
void *ptr_MsiGetFeatureCostW = NULL;
extern void *ptr_MsiGetFeatureInfoA;
void *ptr_MsiGetFeatureInfoA = NULL;
extern void *ptr_MsiGetFeatureInfoW;
void *ptr_MsiGetFeatureInfoW = NULL;
extern void *ptr_MsiGetFeatureStateA;
void *ptr_MsiGetFeatureStateA = NULL;
extern void *ptr_MsiGetFeatureStateW;
void *ptr_MsiGetFeatureStateW = NULL;
extern void *ptr_MsiGetFeatureUsageA;
void *ptr_MsiGetFeatureUsageA = NULL;
extern void *ptr_MsiGetFeatureUsageW;
void *ptr_MsiGetFeatureUsageW = NULL;
extern void *ptr_MsiGetFeatureValidStatesA;
void *ptr_MsiGetFeatureValidStatesA = NULL;
extern void *ptr_MsiGetFeatureValidStatesW;
void *ptr_MsiGetFeatureValidStatesW = NULL;
extern void *ptr_MsiGetFileHashA;
void *ptr_MsiGetFileHashA = NULL;
extern void *ptr_MsiGetFileHashW;
void *ptr_MsiGetFileHashW = NULL;
extern void *ptr_MsiGetFileSignatureInformationA;
void *ptr_MsiGetFileSignatureInformationA = NULL;
extern void *ptr_MsiGetFileSignatureInformationW;
void *ptr_MsiGetFileSignatureInformationW = NULL;
extern void *ptr_MsiGetFileVersionA;
void *ptr_MsiGetFileVersionA = NULL;
extern void *ptr_MsiGetFileVersionW;
void *ptr_MsiGetFileVersionW = NULL;
extern void *ptr_MsiGetLanguage;
void *ptr_MsiGetLanguage = NULL;
extern void *ptr_MsiGetLastErrorRecord;
void *ptr_MsiGetLastErrorRecord = NULL;
extern void *ptr_MsiGetMode;
void *ptr_MsiGetMode = NULL;
extern void *ptr_MsiGetPatchFileListA;
void *ptr_MsiGetPatchFileListA = NULL;
extern void *ptr_MsiGetPatchFileListW;
void *ptr_MsiGetPatchFileListW = NULL;
extern void *ptr_MsiGetPatchInfoA;
void *ptr_MsiGetPatchInfoA = NULL;
extern void *ptr_MsiGetPatchInfoExA;
void *ptr_MsiGetPatchInfoExA = NULL;
extern void *ptr_MsiGetPatchInfoExW;
void *ptr_MsiGetPatchInfoExW = NULL;
extern void *ptr_MsiGetPatchInfoW;
void *ptr_MsiGetPatchInfoW = NULL;
extern void *ptr_MsiGetProductCodeA;
void *ptr_MsiGetProductCodeA = NULL;
extern void *ptr_MsiGetProductCodeFromPackageCodeA;
void *ptr_MsiGetProductCodeFromPackageCodeA = NULL;
extern void *ptr_MsiGetProductCodeFromPackageCodeW;
void *ptr_MsiGetProductCodeFromPackageCodeW = NULL;
extern void *ptr_MsiGetProductCodeW;
void *ptr_MsiGetProductCodeW = NULL;
extern void *ptr_MsiGetProductInfoA;
void *ptr_MsiGetProductInfoA = NULL;
extern void *ptr_MsiGetProductInfoExA;
void *ptr_MsiGetProductInfoExA = NULL;
extern void *ptr_MsiGetProductInfoExW;
void *ptr_MsiGetProductInfoExW = NULL;
extern void *ptr_MsiGetProductInfoFromScriptA;
void *ptr_MsiGetProductInfoFromScriptA = NULL;
extern void *ptr_MsiGetProductInfoFromScriptW;
void *ptr_MsiGetProductInfoFromScriptW = NULL;
extern void *ptr_MsiGetProductInfoW;
void *ptr_MsiGetProductInfoW = NULL;
extern void *ptr_MsiGetProductPropertyA;
void *ptr_MsiGetProductPropertyA = NULL;
extern void *ptr_MsiGetProductPropertyW;
void *ptr_MsiGetProductPropertyW = NULL;
extern void *ptr_MsiGetPropertyA;
void *ptr_MsiGetPropertyA = NULL;
extern void *ptr_MsiGetPropertyW;
void *ptr_MsiGetPropertyW = NULL;
extern void *ptr_MsiGetShortcutTargetA;
void *ptr_MsiGetShortcutTargetA = NULL;
extern void *ptr_MsiGetShortcutTargetW;
void *ptr_MsiGetShortcutTargetW = NULL;
extern void *ptr_MsiGetSourcePathA;
void *ptr_MsiGetSourcePathA = NULL;
extern void *ptr_MsiGetSourcePathW;
void *ptr_MsiGetSourcePathW = NULL;
extern void *ptr_MsiGetSummaryInformationA;
void *ptr_MsiGetSummaryInformationA = NULL;
extern void *ptr_MsiGetSummaryInformationW;
void *ptr_MsiGetSummaryInformationW = NULL;
extern void *ptr_MsiGetTargetPathA;
void *ptr_MsiGetTargetPathA = NULL;
extern void *ptr_MsiGetTargetPathW;
void *ptr_MsiGetTargetPathW = NULL;
extern void *ptr_MsiGetUserInfoA;
void *ptr_MsiGetUserInfoA = NULL;
extern void *ptr_MsiGetUserInfoW;
void *ptr_MsiGetUserInfoW = NULL;
extern void *ptr_MsiInstallMissingComponentA;
void *ptr_MsiInstallMissingComponentA = NULL;
extern void *ptr_MsiInstallMissingComponentW;
void *ptr_MsiInstallMissingComponentW = NULL;
extern void *ptr_MsiInstallMissingFileA;
void *ptr_MsiInstallMissingFileA = NULL;
extern void *ptr_MsiInstallMissingFileW;
void *ptr_MsiInstallMissingFileW = NULL;
extern void *ptr_MsiInstallProductA;
void *ptr_MsiInstallProductA = NULL;
extern void *ptr_MsiInstallProductW;
void *ptr_MsiInstallProductW = NULL;
extern void *ptr_MsiInvalidateFeatureCache;
void *ptr_MsiInvalidateFeatureCache = NULL;
extern void *ptr_MsiIsProductElevatedA;
void *ptr_MsiIsProductElevatedA = NULL;
extern void *ptr_MsiIsProductElevatedW;
void *ptr_MsiIsProductElevatedW = NULL;
extern void *ptr_MsiJoinTransaction;
void *ptr_MsiJoinTransaction = NULL;
extern void *ptr_MsiLoadStringA;
void *ptr_MsiLoadStringA = NULL;
extern void *ptr_MsiLoadStringW;
void *ptr_MsiLoadStringW = NULL;
extern void *ptr_MsiLocateComponentA;
void *ptr_MsiLocateComponentA = NULL;
extern void *ptr_MsiLocateComponentW;
void *ptr_MsiLocateComponentW = NULL;
extern void *ptr_MsiMessageBoxA;
void *ptr_MsiMessageBoxA = NULL;
extern void *ptr_MsiMessageBoxExA;
void *ptr_MsiMessageBoxExA = NULL;
extern void *ptr_MsiMessageBoxExW;
void *ptr_MsiMessageBoxExW = NULL;
extern void *ptr_MsiMessageBoxW;
void *ptr_MsiMessageBoxW = NULL;
extern void *ptr_MsiNotifySidChangeA;
void *ptr_MsiNotifySidChangeA = NULL;
extern void *ptr_MsiNotifySidChangeW;
void *ptr_MsiNotifySidChangeW = NULL;
extern void *ptr_MsiOpenDatabaseA;
void *ptr_MsiOpenDatabaseA = NULL;
extern void *ptr_MsiOpenDatabaseW;
void *ptr_MsiOpenDatabaseW = NULL;
extern void *ptr_MsiOpenPackageA;
void *ptr_MsiOpenPackageA = NULL;
extern void *ptr_MsiOpenPackageExA;
void *ptr_MsiOpenPackageExA = NULL;
extern void *ptr_MsiOpenPackageExW;
void *ptr_MsiOpenPackageExW = NULL;
extern void *ptr_MsiOpenPackageW;
void *ptr_MsiOpenPackageW = NULL;
extern void *ptr_MsiOpenProductA;
void *ptr_MsiOpenProductA = NULL;
extern void *ptr_MsiOpenProductW;
void *ptr_MsiOpenProductW = NULL;
extern void *ptr_MsiPreviewBillboardA;
void *ptr_MsiPreviewBillboardA = NULL;
extern void *ptr_MsiPreviewBillboardW;
void *ptr_MsiPreviewBillboardW = NULL;
extern void *ptr_MsiPreviewDialogA;
void *ptr_MsiPreviewDialogA = NULL;
extern void *ptr_MsiPreviewDialogW;
void *ptr_MsiPreviewDialogW = NULL;
extern void *ptr_MsiProcessAdvertiseScriptA;
void *ptr_MsiProcessAdvertiseScriptA = NULL;
extern void *ptr_MsiProcessAdvertiseScriptW;
void *ptr_MsiProcessAdvertiseScriptW = NULL;
extern void *ptr_MsiProcessMessage;
void *ptr_MsiProcessMessage = NULL;
extern void *ptr_MsiProvideAssemblyA;
void *ptr_MsiProvideAssemblyA = NULL;
extern void *ptr_MsiProvideAssemblyW;
void *ptr_MsiProvideAssemblyW = NULL;
extern void *ptr_MsiProvideComponentA;
void *ptr_MsiProvideComponentA = NULL;
extern void *ptr_MsiProvideComponentFromDescriptorA;
void *ptr_MsiProvideComponentFromDescriptorA = NULL;
extern void *ptr_MsiProvideComponentFromDescriptorW;
void *ptr_MsiProvideComponentFromDescriptorW = NULL;
extern void *ptr_MsiProvideComponentW;
void *ptr_MsiProvideComponentW = NULL;
extern void *ptr_MsiProvideQualifiedComponentA;
void *ptr_MsiProvideQualifiedComponentA = NULL;
extern void *ptr_MsiProvideQualifiedComponentExA;
void *ptr_MsiProvideQualifiedComponentExA = NULL;
extern void *ptr_MsiProvideQualifiedComponentExW;
void *ptr_MsiProvideQualifiedComponentExW = NULL;
extern void *ptr_MsiProvideQualifiedComponentW;
void *ptr_MsiProvideQualifiedComponentW = NULL;
extern void *ptr_MsiQueryComponentStateA;
void *ptr_MsiQueryComponentStateA = NULL;
extern void *ptr_MsiQueryComponentStateW;
void *ptr_MsiQueryComponentStateW = NULL;
extern void *ptr_MsiQueryFeatureStateA;
void *ptr_MsiQueryFeatureStateA = NULL;
extern void *ptr_MsiQueryFeatureStateExA;
void *ptr_MsiQueryFeatureStateExA = NULL;
extern void *ptr_MsiQueryFeatureStateExW;
void *ptr_MsiQueryFeatureStateExW = NULL;
extern void *ptr_MsiQueryFeatureStateFromDescriptorA;
void *ptr_MsiQueryFeatureStateFromDescriptorA = NULL;
extern void *ptr_MsiQueryFeatureStateFromDescriptorW;
void *ptr_MsiQueryFeatureStateFromDescriptorW = NULL;
extern void *ptr_MsiQueryFeatureStateW;
void *ptr_MsiQueryFeatureStateW = NULL;
extern void *ptr_MsiQueryProductStateA;
void *ptr_MsiQueryProductStateA = NULL;
extern void *ptr_MsiQueryProductStateW;
void *ptr_MsiQueryProductStateW = NULL;
extern void *ptr_MsiRecordClearData;
void *ptr_MsiRecordClearData = NULL;
extern void *ptr_MsiRecordDataSize;
void *ptr_MsiRecordDataSize = NULL;
extern void *ptr_MsiRecordGetFieldCount;
void *ptr_MsiRecordGetFieldCount = NULL;
extern void *ptr_MsiRecordGetInteger;
void *ptr_MsiRecordGetInteger = NULL;
extern void *ptr_MsiRecordGetStringA;
void *ptr_MsiRecordGetStringA = NULL;
extern void *ptr_MsiRecordGetStringW;
void *ptr_MsiRecordGetStringW = NULL;
extern void *ptr_MsiRecordIsNull;
void *ptr_MsiRecordIsNull = NULL;
extern void *ptr_MsiRecordReadStream;
void *ptr_MsiRecordReadStream = NULL;
extern void *ptr_MsiRecordSetInteger;
void *ptr_MsiRecordSetInteger = NULL;
extern void *ptr_MsiRecordSetStreamA;
void *ptr_MsiRecordSetStreamA = NULL;
extern void *ptr_MsiRecordSetStreamW;
void *ptr_MsiRecordSetStreamW = NULL;
extern void *ptr_MsiRecordSetStringA;
void *ptr_MsiRecordSetStringA = NULL;
extern void *ptr_MsiRecordSetStringW;
void *ptr_MsiRecordSetStringW = NULL;
extern void *ptr_MsiReinstallFeatureA;
void *ptr_MsiReinstallFeatureA = NULL;
extern void *ptr_MsiReinstallFeatureFromDescriptorA;
void *ptr_MsiReinstallFeatureFromDescriptorA = NULL;
extern void *ptr_MsiReinstallFeatureFromDescriptorW;
void *ptr_MsiReinstallFeatureFromDescriptorW = NULL;
extern void *ptr_MsiReinstallFeatureW;
void *ptr_MsiReinstallFeatureW = NULL;
extern void *ptr_MsiReinstallProductA;
void *ptr_MsiReinstallProductA = NULL;
extern void *ptr_MsiReinstallProductW;
void *ptr_MsiReinstallProductW = NULL;
extern void *ptr_MsiRemovePatchesA;
void *ptr_MsiRemovePatchesA = NULL;
extern void *ptr_MsiRemovePatchesW;
void *ptr_MsiRemovePatchesW = NULL;
extern void *ptr_MsiSequenceA;
void *ptr_MsiSequenceA = NULL;
extern void *ptr_MsiSequenceW;
void *ptr_MsiSequenceW = NULL;
extern void *ptr_MsiSetComponentStateA;
void *ptr_MsiSetComponentStateA = NULL;
extern void *ptr_MsiSetComponentStateW;
void *ptr_MsiSetComponentStateW = NULL;
extern void *ptr_MsiSetExternalUIA;
void *ptr_MsiSetExternalUIA = NULL;
extern void *ptr_MsiSetExternalUIRecord;
void *ptr_MsiSetExternalUIRecord = NULL;
extern void *ptr_MsiSetExternalUIW;
void *ptr_MsiSetExternalUIW = NULL;
extern void *ptr_MsiSetFeatureAttributesA;
void *ptr_MsiSetFeatureAttributesA = NULL;
extern void *ptr_MsiSetFeatureAttributesW;
void *ptr_MsiSetFeatureAttributesW = NULL;
extern void *ptr_MsiSetFeatureStateA;
void *ptr_MsiSetFeatureStateA = NULL;
extern void *ptr_MsiSetFeatureStateW;
void *ptr_MsiSetFeatureStateW = NULL;
extern void *ptr_MsiSetInstallLevel;
void *ptr_MsiSetInstallLevel = NULL;
extern void *ptr_MsiSetInternalUI;
void *ptr_MsiSetInternalUI = NULL;
extern void *ptr_MsiSetMode;
void *ptr_MsiSetMode = NULL;
extern void *ptr_MsiSetOfflineContextW;
void *ptr_MsiSetOfflineContextW = NULL;
extern void *ptr_MsiSetPropertyA;
void *ptr_MsiSetPropertyA = NULL;
extern void *ptr_MsiSetPropertyW;
void *ptr_MsiSetPropertyW = NULL;
extern void *ptr_MsiSetTargetPathA;
void *ptr_MsiSetTargetPathA = NULL;
extern void *ptr_MsiSetTargetPathW;
void *ptr_MsiSetTargetPathW = NULL;
extern void *ptr_MsiSourceListAddMediaDiskA;
void *ptr_MsiSourceListAddMediaDiskA = NULL;
extern void *ptr_MsiSourceListAddMediaDiskW;
void *ptr_MsiSourceListAddMediaDiskW = NULL;
extern void *ptr_MsiSourceListAddSourceA;
void *ptr_MsiSourceListAddSourceA = NULL;
extern void *ptr_MsiSourceListAddSourceExA;
void *ptr_MsiSourceListAddSourceExA = NULL;
extern void *ptr_MsiSourceListAddSourceExW;
void *ptr_MsiSourceListAddSourceExW = NULL;
extern void *ptr_MsiSourceListAddSourceW;
void *ptr_MsiSourceListAddSourceW = NULL;
extern void *ptr_MsiSourceListClearAllA;
void *ptr_MsiSourceListClearAllA = NULL;
extern void *ptr_MsiSourceListClearAllExA;
void *ptr_MsiSourceListClearAllExA = NULL;
extern void *ptr_MsiSourceListClearAllExW;
void *ptr_MsiSourceListClearAllExW = NULL;
extern void *ptr_MsiSourceListClearAllW;
void *ptr_MsiSourceListClearAllW = NULL;
extern void *ptr_MsiSourceListClearMediaDiskA;
void *ptr_MsiSourceListClearMediaDiskA = NULL;
extern void *ptr_MsiSourceListClearMediaDiskW;
void *ptr_MsiSourceListClearMediaDiskW = NULL;
extern void *ptr_MsiSourceListClearSourceA;
void *ptr_MsiSourceListClearSourceA = NULL;
extern void *ptr_MsiSourceListClearSourceW;
void *ptr_MsiSourceListClearSourceW = NULL;
extern void *ptr_MsiSourceListEnumMediaDisksA;
void *ptr_MsiSourceListEnumMediaDisksA = NULL;
extern void *ptr_MsiSourceListEnumMediaDisksW;
void *ptr_MsiSourceListEnumMediaDisksW = NULL;
extern void *ptr_MsiSourceListEnumSourcesA;
void *ptr_MsiSourceListEnumSourcesA = NULL;
extern void *ptr_MsiSourceListEnumSourcesW;
void *ptr_MsiSourceListEnumSourcesW = NULL;
extern void *ptr_MsiSourceListForceResolutionA;
void *ptr_MsiSourceListForceResolutionA = NULL;
extern void *ptr_MsiSourceListForceResolutionExA;
void *ptr_MsiSourceListForceResolutionExA = NULL;
extern void *ptr_MsiSourceListForceResolutionExW;
void *ptr_MsiSourceListForceResolutionExW = NULL;
extern void *ptr_MsiSourceListForceResolutionW;
void *ptr_MsiSourceListForceResolutionW = NULL;
extern void *ptr_MsiSourceListGetInfoA;
void *ptr_MsiSourceListGetInfoA = NULL;
extern void *ptr_MsiSourceListGetInfoW;
void *ptr_MsiSourceListGetInfoW = NULL;
extern void *ptr_MsiSourceListSetInfoA;
void *ptr_MsiSourceListSetInfoA = NULL;
extern void *ptr_MsiSourceListSetInfoW;
void *ptr_MsiSourceListSetInfoW = NULL;
extern void *ptr_MsiSummaryInfoGetPropertyA;
void *ptr_MsiSummaryInfoGetPropertyA = NULL;
extern void *ptr_MsiSummaryInfoGetPropertyCount;
void *ptr_MsiSummaryInfoGetPropertyCount = NULL;
extern void *ptr_MsiSummaryInfoGetPropertyW;
void *ptr_MsiSummaryInfoGetPropertyW = NULL;
extern void *ptr_MsiSummaryInfoPersist;
void *ptr_MsiSummaryInfoPersist = NULL;
extern void *ptr_MsiSummaryInfoSetPropertyA;
void *ptr_MsiSummaryInfoSetPropertyA = NULL;
extern void *ptr_MsiSummaryInfoSetPropertyW;
void *ptr_MsiSummaryInfoSetPropertyW = NULL;
extern void *ptr_MsiUseFeatureA;
void *ptr_MsiUseFeatureA = NULL;
extern void *ptr_MsiUseFeatureExA;
void *ptr_MsiUseFeatureExA = NULL;
extern void *ptr_MsiUseFeatureExW;
void *ptr_MsiUseFeatureExW = NULL;
extern void *ptr_MsiUseFeatureW;
void *ptr_MsiUseFeatureW = NULL;
extern void *ptr_MsiVerifyDiskSpace;
void *ptr_MsiVerifyDiskSpace = NULL;
extern void *ptr_MsiVerifyPackageA;
void *ptr_MsiVerifyPackageA = NULL;
extern void *ptr_MsiVerifyPackageW;
void *ptr_MsiVerifyPackageW = NULL;
extern void *ptr_MsiViewClose;
void *ptr_MsiViewClose = NULL;
extern void *ptr_MsiViewExecute;
void *ptr_MsiViewExecute = NULL;
extern void *ptr_MsiViewFetch;
void *ptr_MsiViewFetch = NULL;
extern void *ptr_MsiViewGetColumnInfo;
void *ptr_MsiViewGetColumnInfo = NULL;
extern void *ptr_MsiViewGetErrorA;
void *ptr_MsiViewGetErrorA = NULL;
extern void *ptr_MsiViewGetErrorW;
void *ptr_MsiViewGetErrorW = NULL;
extern void *ptr_MsiViewModify;
void *ptr_MsiViewModify = NULL;
extern void *ptr_QueryInstanceCount;
void *ptr_QueryInstanceCount = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\msi.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_DllCanUnloadNow = (__vartype(ptr_DllCanUnloadNow))GetProcAddress(hModule, "DllCanUnloadNow");
   ptr_DllGetClassObject = (__vartype(ptr_DllGetClassObject))GetProcAddress(hModule, "DllGetClassObject");
   ptr_DllGetVersion = (__vartype(ptr_DllGetVersion))GetProcAddress(hModule, "DllGetVersion");
   ptr_DllRegisterServer = (__vartype(ptr_DllRegisterServer))GetProcAddress(hModule, "DllRegisterServer");
   ptr_DllUnregisterServer = (__vartype(ptr_DllUnregisterServer))GetProcAddress(hModule, "DllUnregisterServer");
   ptr_Migrate10CachedPackagesA = (__vartype(ptr_Migrate10CachedPackagesA))GetProcAddress(hModule, "Migrate10CachedPackagesA");
   ptr_Migrate10CachedPackagesW = (__vartype(ptr_Migrate10CachedPackagesW))GetProcAddress(hModule, "Migrate10CachedPackagesW");
   ptr_MsiAdvertiseProductA = (__vartype(ptr_MsiAdvertiseProductA))GetProcAddress(hModule, "MsiAdvertiseProductA");
   ptr_MsiAdvertiseProductExA = (__vartype(ptr_MsiAdvertiseProductExA))GetProcAddress(hModule, "MsiAdvertiseProductExA");
   ptr_MsiAdvertiseProductExW = (__vartype(ptr_MsiAdvertiseProductExW))GetProcAddress(hModule, "MsiAdvertiseProductExW");
   ptr_MsiAdvertiseProductW = (__vartype(ptr_MsiAdvertiseProductW))GetProcAddress(hModule, "MsiAdvertiseProductW");
   ptr_MsiAdvertiseScriptA = (__vartype(ptr_MsiAdvertiseScriptA))GetProcAddress(hModule, "MsiAdvertiseScriptA");
   ptr_MsiAdvertiseScriptW = (__vartype(ptr_MsiAdvertiseScriptW))GetProcAddress(hModule, "MsiAdvertiseScriptW");
   ptr_MsiApplyMultiplePatchesA = (__vartype(ptr_MsiApplyMultiplePatchesA))GetProcAddress(hModule, "MsiApplyMultiplePatchesA");
   ptr_MsiApplyMultiplePatchesW = (__vartype(ptr_MsiApplyMultiplePatchesW))GetProcAddress(hModule, "MsiApplyMultiplePatchesW");
   ptr_MsiApplyPatchA = (__vartype(ptr_MsiApplyPatchA))GetProcAddress(hModule, "MsiApplyPatchA");
   ptr_MsiApplyPatchW = (__vartype(ptr_MsiApplyPatchW))GetProcAddress(hModule, "MsiApplyPatchW");
   ptr_MsiBeginTransactionA = (__vartype(ptr_MsiBeginTransactionA))GetProcAddress(hModule, "MsiBeginTransactionA");
   ptr_MsiBeginTransactionW = (__vartype(ptr_MsiBeginTransactionW))GetProcAddress(hModule, "MsiBeginTransactionW");
   ptr_MsiCloseAllHandles = (__vartype(ptr_MsiCloseAllHandles))GetProcAddress(hModule, "MsiCloseAllHandles");
   ptr_MsiCloseHandle = (__vartype(ptr_MsiCloseHandle))GetProcAddress(hModule, "MsiCloseHandle");
   ptr_MsiCollectUserInfoA = (__vartype(ptr_MsiCollectUserInfoA))GetProcAddress(hModule, "MsiCollectUserInfoA");
   ptr_MsiCollectUserInfoW = (__vartype(ptr_MsiCollectUserInfoW))GetProcAddress(hModule, "MsiCollectUserInfoW");
   ptr_MsiConfigureFeatureA = (__vartype(ptr_MsiConfigureFeatureA))GetProcAddress(hModule, "MsiConfigureFeatureA");
   ptr_MsiConfigureFeatureFromDescriptorA = (__vartype(ptr_MsiConfigureFeatureFromDescriptorA))GetProcAddress(hModule, "MsiConfigureFeatureFromDescriptorA");
   ptr_MsiConfigureFeatureFromDescriptorW = (__vartype(ptr_MsiConfigureFeatureFromDescriptorW))GetProcAddress(hModule, "MsiConfigureFeatureFromDescriptorW");
   ptr_MsiConfigureFeatureW = (__vartype(ptr_MsiConfigureFeatureW))GetProcAddress(hModule, "MsiConfigureFeatureW");
   ptr_MsiConfigureProductA = (__vartype(ptr_MsiConfigureProductA))GetProcAddress(hModule, "MsiConfigureProductA");
   ptr_MsiConfigureProductExA = (__vartype(ptr_MsiConfigureProductExA))GetProcAddress(hModule, "MsiConfigureProductExA");
   ptr_MsiConfigureProductExW = (__vartype(ptr_MsiConfigureProductExW))GetProcAddress(hModule, "MsiConfigureProductExW");
   ptr_MsiConfigureProductW = (__vartype(ptr_MsiConfigureProductW))GetProcAddress(hModule, "MsiConfigureProductW");
   ptr_MsiCreateAndVerifyInstallerDirectory = (__vartype(ptr_MsiCreateAndVerifyInstallerDirectory))GetProcAddress(hModule, "MsiCreateAndVerifyInstallerDirectory");
   ptr_MsiCreateRecord = (__vartype(ptr_MsiCreateRecord))GetProcAddress(hModule, "MsiCreateRecord");
   ptr_MsiCreateTransformSummaryInfoA = (__vartype(ptr_MsiCreateTransformSummaryInfoA))GetProcAddress(hModule, "MsiCreateTransformSummaryInfoA");
   ptr_MsiCreateTransformSummaryInfoW = (__vartype(ptr_MsiCreateTransformSummaryInfoW))GetProcAddress(hModule, "MsiCreateTransformSummaryInfoW");
   ptr_MsiDatabaseApplyTransformA = (__vartype(ptr_MsiDatabaseApplyTransformA))GetProcAddress(hModule, "MsiDatabaseApplyTransformA");
   ptr_MsiDatabaseApplyTransformW = (__vartype(ptr_MsiDatabaseApplyTransformW))GetProcAddress(hModule, "MsiDatabaseApplyTransformW");
   ptr_MsiDatabaseCommit = (__vartype(ptr_MsiDatabaseCommit))GetProcAddress(hModule, "MsiDatabaseCommit");
   ptr_MsiDatabaseExportA = (__vartype(ptr_MsiDatabaseExportA))GetProcAddress(hModule, "MsiDatabaseExportA");
   ptr_MsiDatabaseExportW = (__vartype(ptr_MsiDatabaseExportW))GetProcAddress(hModule, "MsiDatabaseExportW");
   ptr_MsiDatabaseGenerateTransformA = (__vartype(ptr_MsiDatabaseGenerateTransformA))GetProcAddress(hModule, "MsiDatabaseGenerateTransformA");
   ptr_MsiDatabaseGenerateTransformW = (__vartype(ptr_MsiDatabaseGenerateTransformW))GetProcAddress(hModule, "MsiDatabaseGenerateTransformW");
   ptr_MsiDatabaseGetPrimaryKeysA = (__vartype(ptr_MsiDatabaseGetPrimaryKeysA))GetProcAddress(hModule, "MsiDatabaseGetPrimaryKeysA");
   ptr_MsiDatabaseGetPrimaryKeysW = (__vartype(ptr_MsiDatabaseGetPrimaryKeysW))GetProcAddress(hModule, "MsiDatabaseGetPrimaryKeysW");
   ptr_MsiDatabaseImportA = (__vartype(ptr_MsiDatabaseImportA))GetProcAddress(hModule, "MsiDatabaseImportA");
   ptr_MsiDatabaseImportW = (__vartype(ptr_MsiDatabaseImportW))GetProcAddress(hModule, "MsiDatabaseImportW");
   ptr_MsiDatabaseIsTablePersistentA = (__vartype(ptr_MsiDatabaseIsTablePersistentA))GetProcAddress(hModule, "MsiDatabaseIsTablePersistentA");
   ptr_MsiDatabaseIsTablePersistentW = (__vartype(ptr_MsiDatabaseIsTablePersistentW))GetProcAddress(hModule, "MsiDatabaseIsTablePersistentW");
   ptr_MsiDatabaseMergeA = (__vartype(ptr_MsiDatabaseMergeA))GetProcAddress(hModule, "MsiDatabaseMergeA");
   ptr_MsiDatabaseMergeW = (__vartype(ptr_MsiDatabaseMergeW))GetProcAddress(hModule, "MsiDatabaseMergeW");
   ptr_MsiDatabaseOpenViewA = (__vartype(ptr_MsiDatabaseOpenViewA))GetProcAddress(hModule, "MsiDatabaseOpenViewA");
   ptr_MsiDatabaseOpenViewW = (__vartype(ptr_MsiDatabaseOpenViewW))GetProcAddress(hModule, "MsiDatabaseOpenViewW");
   ptr_MsiDecomposeDescriptorA = (__vartype(ptr_MsiDecomposeDescriptorA))GetProcAddress(hModule, "MsiDecomposeDescriptorA");
   ptr_MsiDecomposeDescriptorW = (__vartype(ptr_MsiDecomposeDescriptorW))GetProcAddress(hModule, "MsiDecomposeDescriptorW");
   ptr_MsiDeleteUserDataA = (__vartype(ptr_MsiDeleteUserDataA))GetProcAddress(hModule, "MsiDeleteUserDataA");
   ptr_MsiDeleteUserDataW = (__vartype(ptr_MsiDeleteUserDataW))GetProcAddress(hModule, "MsiDeleteUserDataW");
   ptr_MsiDetermineApplicablePatchesA = (__vartype(ptr_MsiDetermineApplicablePatchesA))GetProcAddress(hModule, "MsiDetermineApplicablePatchesA");
   ptr_MsiDetermineApplicablePatchesW = (__vartype(ptr_MsiDetermineApplicablePatchesW))GetProcAddress(hModule, "MsiDetermineApplicablePatchesW");
   ptr_MsiDeterminePatchSequenceA = (__vartype(ptr_MsiDeterminePatchSequenceA))GetProcAddress(hModule, "MsiDeterminePatchSequenceA");
   ptr_MsiDeterminePatchSequenceW = (__vartype(ptr_MsiDeterminePatchSequenceW))GetProcAddress(hModule, "MsiDeterminePatchSequenceW");
   ptr_MsiDoActionA = (__vartype(ptr_MsiDoActionA))GetProcAddress(hModule, "MsiDoActionA");
   ptr_MsiDoActionW = (__vartype(ptr_MsiDoActionW))GetProcAddress(hModule, "MsiDoActionW");
   ptr_MsiEnableLogA = (__vartype(ptr_MsiEnableLogA))GetProcAddress(hModule, "MsiEnableLogA");
   ptr_MsiEnableLogW = (__vartype(ptr_MsiEnableLogW))GetProcAddress(hModule, "MsiEnableLogW");
   ptr_MsiEnableUIPreview = (__vartype(ptr_MsiEnableUIPreview))GetProcAddress(hModule, "MsiEnableUIPreview");
   ptr_MsiEndTransaction = (__vartype(ptr_MsiEndTransaction))GetProcAddress(hModule, "MsiEndTransaction");
   ptr_MsiEnumClientsA = (__vartype(ptr_MsiEnumClientsA))GetProcAddress(hModule, "MsiEnumClientsA");
   ptr_MsiEnumClientsExA = (__vartype(ptr_MsiEnumClientsExA))GetProcAddress(hModule, "MsiEnumClientsExA");
   ptr_MsiEnumClientsExW = (__vartype(ptr_MsiEnumClientsExW))GetProcAddress(hModule, "MsiEnumClientsExW");
   ptr_MsiEnumClientsW = (__vartype(ptr_MsiEnumClientsW))GetProcAddress(hModule, "MsiEnumClientsW");
   ptr_MsiEnumComponentCostsA = (__vartype(ptr_MsiEnumComponentCostsA))GetProcAddress(hModule, "MsiEnumComponentCostsA");
   ptr_MsiEnumComponentCostsW = (__vartype(ptr_MsiEnumComponentCostsW))GetProcAddress(hModule, "MsiEnumComponentCostsW");
   ptr_MsiEnumComponentQualifiersA = (__vartype(ptr_MsiEnumComponentQualifiersA))GetProcAddress(hModule, "MsiEnumComponentQualifiersA");
   ptr_MsiEnumComponentQualifiersW = (__vartype(ptr_MsiEnumComponentQualifiersW))GetProcAddress(hModule, "MsiEnumComponentQualifiersW");
   ptr_MsiEnumComponentsA = (__vartype(ptr_MsiEnumComponentsA))GetProcAddress(hModule, "MsiEnumComponentsA");
   ptr_MsiEnumComponentsExA = (__vartype(ptr_MsiEnumComponentsExA))GetProcAddress(hModule, "MsiEnumComponentsExA");
   ptr_MsiEnumComponentsExW = (__vartype(ptr_MsiEnumComponentsExW))GetProcAddress(hModule, "MsiEnumComponentsExW");
   ptr_MsiEnumComponentsW = (__vartype(ptr_MsiEnumComponentsW))GetProcAddress(hModule, "MsiEnumComponentsW");
   ptr_MsiEnumFeaturesA = (__vartype(ptr_MsiEnumFeaturesA))GetProcAddress(hModule, "MsiEnumFeaturesA");
   ptr_MsiEnumFeaturesW = (__vartype(ptr_MsiEnumFeaturesW))GetProcAddress(hModule, "MsiEnumFeaturesW");
   ptr_MsiEnumPatchesA = (__vartype(ptr_MsiEnumPatchesA))GetProcAddress(hModule, "MsiEnumPatchesA");
   ptr_MsiEnumPatchesExA = (__vartype(ptr_MsiEnumPatchesExA))GetProcAddress(hModule, "MsiEnumPatchesExA");
   ptr_MsiEnumPatchesExW = (__vartype(ptr_MsiEnumPatchesExW))GetProcAddress(hModule, "MsiEnumPatchesExW");
   ptr_MsiEnumPatchesW = (__vartype(ptr_MsiEnumPatchesW))GetProcAddress(hModule, "MsiEnumPatchesW");
   ptr_MsiEnumProductsA = (__vartype(ptr_MsiEnumProductsA))GetProcAddress(hModule, "MsiEnumProductsA");
   ptr_MsiEnumProductsExA = (__vartype(ptr_MsiEnumProductsExA))GetProcAddress(hModule, "MsiEnumProductsExA");
   ptr_MsiEnumProductsExW = (__vartype(ptr_MsiEnumProductsExW))GetProcAddress(hModule, "MsiEnumProductsExW");
   ptr_MsiEnumProductsW = (__vartype(ptr_MsiEnumProductsW))GetProcAddress(hModule, "MsiEnumProductsW");
   ptr_MsiEnumRelatedProductsA = (__vartype(ptr_MsiEnumRelatedProductsA))GetProcAddress(hModule, "MsiEnumRelatedProductsA");
   ptr_MsiEnumRelatedProductsW = (__vartype(ptr_MsiEnumRelatedProductsW))GetProcAddress(hModule, "MsiEnumRelatedProductsW");
   ptr_MsiEvaluateConditionA = (__vartype(ptr_MsiEvaluateConditionA))GetProcAddress(hModule, "MsiEvaluateConditionA");
   ptr_MsiEvaluateConditionW = (__vartype(ptr_MsiEvaluateConditionW))GetProcAddress(hModule, "MsiEvaluateConditionW");
   ptr_MsiExtractPatchXMLDataA = (__vartype(ptr_MsiExtractPatchXMLDataA))GetProcAddress(hModule, "MsiExtractPatchXMLDataA");
   ptr_MsiExtractPatchXMLDataW = (__vartype(ptr_MsiExtractPatchXMLDataW))GetProcAddress(hModule, "MsiExtractPatchXMLDataW");
   ptr_MsiFormatRecordA = (__vartype(ptr_MsiFormatRecordA))GetProcAddress(hModule, "MsiFormatRecordA");
   ptr_MsiFormatRecordW = (__vartype(ptr_MsiFormatRecordW))GetProcAddress(hModule, "MsiFormatRecordW");
   ptr_MsiGetActiveDatabase = (__vartype(ptr_MsiGetActiveDatabase))GetProcAddress(hModule, "MsiGetActiveDatabase");
   ptr_MsiGetComponentPathA = (__vartype(ptr_MsiGetComponentPathA))GetProcAddress(hModule, "MsiGetComponentPathA");
   ptr_MsiGetComponentPathExA = (__vartype(ptr_MsiGetComponentPathExA))GetProcAddress(hModule, "MsiGetComponentPathExA");
   ptr_MsiGetComponentPathExW = (__vartype(ptr_MsiGetComponentPathExW))GetProcAddress(hModule, "MsiGetComponentPathExW");
   ptr_MsiGetComponentPathW = (__vartype(ptr_MsiGetComponentPathW))GetProcAddress(hModule, "MsiGetComponentPathW");
   ptr_MsiGetComponentStateA = (__vartype(ptr_MsiGetComponentStateA))GetProcAddress(hModule, "MsiGetComponentStateA");
   ptr_MsiGetComponentStateW = (__vartype(ptr_MsiGetComponentStateW))GetProcAddress(hModule, "MsiGetComponentStateW");
   ptr_MsiGetDatabaseState = (__vartype(ptr_MsiGetDatabaseState))GetProcAddress(hModule, "MsiGetDatabaseState");
   ptr_MsiGetFeatureCostA = (__vartype(ptr_MsiGetFeatureCostA))GetProcAddress(hModule, "MsiGetFeatureCostA");
   ptr_MsiGetFeatureCostW = (__vartype(ptr_MsiGetFeatureCostW))GetProcAddress(hModule, "MsiGetFeatureCostW");
   ptr_MsiGetFeatureInfoA = (__vartype(ptr_MsiGetFeatureInfoA))GetProcAddress(hModule, "MsiGetFeatureInfoA");
   ptr_MsiGetFeatureInfoW = (__vartype(ptr_MsiGetFeatureInfoW))GetProcAddress(hModule, "MsiGetFeatureInfoW");
   ptr_MsiGetFeatureStateA = (__vartype(ptr_MsiGetFeatureStateA))GetProcAddress(hModule, "MsiGetFeatureStateA");
   ptr_MsiGetFeatureStateW = (__vartype(ptr_MsiGetFeatureStateW))GetProcAddress(hModule, "MsiGetFeatureStateW");
   ptr_MsiGetFeatureUsageA = (__vartype(ptr_MsiGetFeatureUsageA))GetProcAddress(hModule, "MsiGetFeatureUsageA");
   ptr_MsiGetFeatureUsageW = (__vartype(ptr_MsiGetFeatureUsageW))GetProcAddress(hModule, "MsiGetFeatureUsageW");
   ptr_MsiGetFeatureValidStatesA = (__vartype(ptr_MsiGetFeatureValidStatesA))GetProcAddress(hModule, "MsiGetFeatureValidStatesA");
   ptr_MsiGetFeatureValidStatesW = (__vartype(ptr_MsiGetFeatureValidStatesW))GetProcAddress(hModule, "MsiGetFeatureValidStatesW");
   ptr_MsiGetFileHashA = (__vartype(ptr_MsiGetFileHashA))GetProcAddress(hModule, "MsiGetFileHashA");
   ptr_MsiGetFileHashW = (__vartype(ptr_MsiGetFileHashW))GetProcAddress(hModule, "MsiGetFileHashW");
   ptr_MsiGetFileSignatureInformationA = (__vartype(ptr_MsiGetFileSignatureInformationA))GetProcAddress(hModule, "MsiGetFileSignatureInformationA");
   ptr_MsiGetFileSignatureInformationW = (__vartype(ptr_MsiGetFileSignatureInformationW))GetProcAddress(hModule, "MsiGetFileSignatureInformationW");
   ptr_MsiGetFileVersionA = (__vartype(ptr_MsiGetFileVersionA))GetProcAddress(hModule, "MsiGetFileVersionA");
   ptr_MsiGetFileVersionW = (__vartype(ptr_MsiGetFileVersionW))GetProcAddress(hModule, "MsiGetFileVersionW");
   ptr_MsiGetLanguage = (__vartype(ptr_MsiGetLanguage))GetProcAddress(hModule, "MsiGetLanguage");
   ptr_MsiGetLastErrorRecord = (__vartype(ptr_MsiGetLastErrorRecord))GetProcAddress(hModule, "MsiGetLastErrorRecord");
   ptr_MsiGetMode = (__vartype(ptr_MsiGetMode))GetProcAddress(hModule, "MsiGetMode");
   ptr_MsiGetPatchFileListA = (__vartype(ptr_MsiGetPatchFileListA))GetProcAddress(hModule, "MsiGetPatchFileListA");
   ptr_MsiGetPatchFileListW = (__vartype(ptr_MsiGetPatchFileListW))GetProcAddress(hModule, "MsiGetPatchFileListW");
   ptr_MsiGetPatchInfoA = (__vartype(ptr_MsiGetPatchInfoA))GetProcAddress(hModule, "MsiGetPatchInfoA");
   ptr_MsiGetPatchInfoExA = (__vartype(ptr_MsiGetPatchInfoExA))GetProcAddress(hModule, "MsiGetPatchInfoExA");
   ptr_MsiGetPatchInfoExW = (__vartype(ptr_MsiGetPatchInfoExW))GetProcAddress(hModule, "MsiGetPatchInfoExW");
   ptr_MsiGetPatchInfoW = (__vartype(ptr_MsiGetPatchInfoW))GetProcAddress(hModule, "MsiGetPatchInfoW");
   ptr_MsiGetProductCodeA = (__vartype(ptr_MsiGetProductCodeA))GetProcAddress(hModule, "MsiGetProductCodeA");
   ptr_MsiGetProductCodeFromPackageCodeA = (__vartype(ptr_MsiGetProductCodeFromPackageCodeA))GetProcAddress(hModule, "MsiGetProductCodeFromPackageCodeA");
   ptr_MsiGetProductCodeFromPackageCodeW = (__vartype(ptr_MsiGetProductCodeFromPackageCodeW))GetProcAddress(hModule, "MsiGetProductCodeFromPackageCodeW");
   ptr_MsiGetProductCodeW = (__vartype(ptr_MsiGetProductCodeW))GetProcAddress(hModule, "MsiGetProductCodeW");
   ptr_MsiGetProductInfoA = (__vartype(ptr_MsiGetProductInfoA))GetProcAddress(hModule, "MsiGetProductInfoA");
   ptr_MsiGetProductInfoExA = (__vartype(ptr_MsiGetProductInfoExA))GetProcAddress(hModule, "MsiGetProductInfoExA");
   ptr_MsiGetProductInfoExW = (__vartype(ptr_MsiGetProductInfoExW))GetProcAddress(hModule, "MsiGetProductInfoExW");
   ptr_MsiGetProductInfoFromScriptA = (__vartype(ptr_MsiGetProductInfoFromScriptA))GetProcAddress(hModule, "MsiGetProductInfoFromScriptA");
   ptr_MsiGetProductInfoFromScriptW = (__vartype(ptr_MsiGetProductInfoFromScriptW))GetProcAddress(hModule, "MsiGetProductInfoFromScriptW");
   ptr_MsiGetProductInfoW = (__vartype(ptr_MsiGetProductInfoW))GetProcAddress(hModule, "MsiGetProductInfoW");
   ptr_MsiGetProductPropertyA = (__vartype(ptr_MsiGetProductPropertyA))GetProcAddress(hModule, "MsiGetProductPropertyA");
   ptr_MsiGetProductPropertyW = (__vartype(ptr_MsiGetProductPropertyW))GetProcAddress(hModule, "MsiGetProductPropertyW");
   ptr_MsiGetPropertyA = (__vartype(ptr_MsiGetPropertyA))GetProcAddress(hModule, "MsiGetPropertyA");
   ptr_MsiGetPropertyW = (__vartype(ptr_MsiGetPropertyW))GetProcAddress(hModule, "MsiGetPropertyW");
   ptr_MsiGetShortcutTargetA = (__vartype(ptr_MsiGetShortcutTargetA))GetProcAddress(hModule, "MsiGetShortcutTargetA");
   ptr_MsiGetShortcutTargetW = (__vartype(ptr_MsiGetShortcutTargetW))GetProcAddress(hModule, "MsiGetShortcutTargetW");
   ptr_MsiGetSourcePathA = (__vartype(ptr_MsiGetSourcePathA))GetProcAddress(hModule, "MsiGetSourcePathA");
   ptr_MsiGetSourcePathW = (__vartype(ptr_MsiGetSourcePathW))GetProcAddress(hModule, "MsiGetSourcePathW");
   ptr_MsiGetSummaryInformationA = (__vartype(ptr_MsiGetSummaryInformationA))GetProcAddress(hModule, "MsiGetSummaryInformationA");
   ptr_MsiGetSummaryInformationW = (__vartype(ptr_MsiGetSummaryInformationW))GetProcAddress(hModule, "MsiGetSummaryInformationW");
   ptr_MsiGetTargetPathA = (__vartype(ptr_MsiGetTargetPathA))GetProcAddress(hModule, "MsiGetTargetPathA");
   ptr_MsiGetTargetPathW = (__vartype(ptr_MsiGetTargetPathW))GetProcAddress(hModule, "MsiGetTargetPathW");
   ptr_MsiGetUserInfoA = (__vartype(ptr_MsiGetUserInfoA))GetProcAddress(hModule, "MsiGetUserInfoA");
   ptr_MsiGetUserInfoW = (__vartype(ptr_MsiGetUserInfoW))GetProcAddress(hModule, "MsiGetUserInfoW");
   ptr_MsiInstallMissingComponentA = (__vartype(ptr_MsiInstallMissingComponentA))GetProcAddress(hModule, "MsiInstallMissingComponentA");
   ptr_MsiInstallMissingComponentW = (__vartype(ptr_MsiInstallMissingComponentW))GetProcAddress(hModule, "MsiInstallMissingComponentW");
   ptr_MsiInstallMissingFileA = (__vartype(ptr_MsiInstallMissingFileA))GetProcAddress(hModule, "MsiInstallMissingFileA");
   ptr_MsiInstallMissingFileW = (__vartype(ptr_MsiInstallMissingFileW))GetProcAddress(hModule, "MsiInstallMissingFileW");
   ptr_MsiInstallProductA = (__vartype(ptr_MsiInstallProductA))GetProcAddress(hModule, "MsiInstallProductA");
   ptr_MsiInstallProductW = (__vartype(ptr_MsiInstallProductW))GetProcAddress(hModule, "MsiInstallProductW");
   ptr_MsiInvalidateFeatureCache = (__vartype(ptr_MsiInvalidateFeatureCache))GetProcAddress(hModule, "MsiInvalidateFeatureCache");
   ptr_MsiIsProductElevatedA = (__vartype(ptr_MsiIsProductElevatedA))GetProcAddress(hModule, "MsiIsProductElevatedA");
   ptr_MsiIsProductElevatedW = (__vartype(ptr_MsiIsProductElevatedW))GetProcAddress(hModule, "MsiIsProductElevatedW");
   ptr_MsiJoinTransaction = (__vartype(ptr_MsiJoinTransaction))GetProcAddress(hModule, "MsiJoinTransaction");
   ptr_MsiLoadStringA = (__vartype(ptr_MsiLoadStringA))GetProcAddress(hModule, "MsiLoadStringA");
   ptr_MsiLoadStringW = (__vartype(ptr_MsiLoadStringW))GetProcAddress(hModule, "MsiLoadStringW");
   ptr_MsiLocateComponentA = (__vartype(ptr_MsiLocateComponentA))GetProcAddress(hModule, "MsiLocateComponentA");
   ptr_MsiLocateComponentW = (__vartype(ptr_MsiLocateComponentW))GetProcAddress(hModule, "MsiLocateComponentW");
   ptr_MsiMessageBoxA = (__vartype(ptr_MsiMessageBoxA))GetProcAddress(hModule, "MsiMessageBoxA");
   ptr_MsiMessageBoxExA = (__vartype(ptr_MsiMessageBoxExA))GetProcAddress(hModule, "MsiMessageBoxExA");
   ptr_MsiMessageBoxExW = (__vartype(ptr_MsiMessageBoxExW))GetProcAddress(hModule, "MsiMessageBoxExW");
   ptr_MsiMessageBoxW = (__vartype(ptr_MsiMessageBoxW))GetProcAddress(hModule, "MsiMessageBoxW");
   ptr_MsiNotifySidChangeA = (__vartype(ptr_MsiNotifySidChangeA))GetProcAddress(hModule, "MsiNotifySidChangeA");
   ptr_MsiNotifySidChangeW = (__vartype(ptr_MsiNotifySidChangeW))GetProcAddress(hModule, "MsiNotifySidChangeW");
   ptr_MsiOpenDatabaseA = (__vartype(ptr_MsiOpenDatabaseA))GetProcAddress(hModule, "MsiOpenDatabaseA");
   ptr_MsiOpenDatabaseW = (__vartype(ptr_MsiOpenDatabaseW))GetProcAddress(hModule, "MsiOpenDatabaseW");
   ptr_MsiOpenPackageA = (__vartype(ptr_MsiOpenPackageA))GetProcAddress(hModule, "MsiOpenPackageA");
   ptr_MsiOpenPackageExA = (__vartype(ptr_MsiOpenPackageExA))GetProcAddress(hModule, "MsiOpenPackageExA");
   ptr_MsiOpenPackageExW = (__vartype(ptr_MsiOpenPackageExW))GetProcAddress(hModule, "MsiOpenPackageExW");
   ptr_MsiOpenPackageW = (__vartype(ptr_MsiOpenPackageW))GetProcAddress(hModule, "MsiOpenPackageW");
   ptr_MsiOpenProductA = (__vartype(ptr_MsiOpenProductA))GetProcAddress(hModule, "MsiOpenProductA");
   ptr_MsiOpenProductW = (__vartype(ptr_MsiOpenProductW))GetProcAddress(hModule, "MsiOpenProductW");
   ptr_MsiPreviewBillboardA = (__vartype(ptr_MsiPreviewBillboardA))GetProcAddress(hModule, "MsiPreviewBillboardA");
   ptr_MsiPreviewBillboardW = (__vartype(ptr_MsiPreviewBillboardW))GetProcAddress(hModule, "MsiPreviewBillboardW");
   ptr_MsiPreviewDialogA = (__vartype(ptr_MsiPreviewDialogA))GetProcAddress(hModule, "MsiPreviewDialogA");
   ptr_MsiPreviewDialogW = (__vartype(ptr_MsiPreviewDialogW))GetProcAddress(hModule, "MsiPreviewDialogW");
   ptr_MsiProcessAdvertiseScriptA = (__vartype(ptr_MsiProcessAdvertiseScriptA))GetProcAddress(hModule, "MsiProcessAdvertiseScriptA");
   ptr_MsiProcessAdvertiseScriptW = (__vartype(ptr_MsiProcessAdvertiseScriptW))GetProcAddress(hModule, "MsiProcessAdvertiseScriptW");
   ptr_MsiProcessMessage = (__vartype(ptr_MsiProcessMessage))GetProcAddress(hModule, "MsiProcessMessage");
   ptr_MsiProvideAssemblyA = (__vartype(ptr_MsiProvideAssemblyA))GetProcAddress(hModule, "MsiProvideAssemblyA");
   ptr_MsiProvideAssemblyW = (__vartype(ptr_MsiProvideAssemblyW))GetProcAddress(hModule, "MsiProvideAssemblyW");
   ptr_MsiProvideComponentA = (__vartype(ptr_MsiProvideComponentA))GetProcAddress(hModule, "MsiProvideComponentA");
   ptr_MsiProvideComponentFromDescriptorA = (__vartype(ptr_MsiProvideComponentFromDescriptorA))GetProcAddress(hModule, "MsiProvideComponentFromDescriptorA");
   ptr_MsiProvideComponentFromDescriptorW = (__vartype(ptr_MsiProvideComponentFromDescriptorW))GetProcAddress(hModule, "MsiProvideComponentFromDescriptorW");
   ptr_MsiProvideComponentW = (__vartype(ptr_MsiProvideComponentW))GetProcAddress(hModule, "MsiProvideComponentW");
   ptr_MsiProvideQualifiedComponentA = (__vartype(ptr_MsiProvideQualifiedComponentA))GetProcAddress(hModule, "MsiProvideQualifiedComponentA");
   ptr_MsiProvideQualifiedComponentExA = (__vartype(ptr_MsiProvideQualifiedComponentExA))GetProcAddress(hModule, "MsiProvideQualifiedComponentExA");
   ptr_MsiProvideQualifiedComponentExW = (__vartype(ptr_MsiProvideQualifiedComponentExW))GetProcAddress(hModule, "MsiProvideQualifiedComponentExW");
   ptr_MsiProvideQualifiedComponentW = (__vartype(ptr_MsiProvideQualifiedComponentW))GetProcAddress(hModule, "MsiProvideQualifiedComponentW");
   ptr_MsiQueryComponentStateA = (__vartype(ptr_MsiQueryComponentStateA))GetProcAddress(hModule, "MsiQueryComponentStateA");
   ptr_MsiQueryComponentStateW = (__vartype(ptr_MsiQueryComponentStateW))GetProcAddress(hModule, "MsiQueryComponentStateW");
   ptr_MsiQueryFeatureStateA = (__vartype(ptr_MsiQueryFeatureStateA))GetProcAddress(hModule, "MsiQueryFeatureStateA");
   ptr_MsiQueryFeatureStateExA = (__vartype(ptr_MsiQueryFeatureStateExA))GetProcAddress(hModule, "MsiQueryFeatureStateExA");
   ptr_MsiQueryFeatureStateExW = (__vartype(ptr_MsiQueryFeatureStateExW))GetProcAddress(hModule, "MsiQueryFeatureStateExW");
   ptr_MsiQueryFeatureStateFromDescriptorA = (__vartype(ptr_MsiQueryFeatureStateFromDescriptorA))GetProcAddress(hModule, "MsiQueryFeatureStateFromDescriptorA");
   ptr_MsiQueryFeatureStateFromDescriptorW = (__vartype(ptr_MsiQueryFeatureStateFromDescriptorW))GetProcAddress(hModule, "MsiQueryFeatureStateFromDescriptorW");
   ptr_MsiQueryFeatureStateW = (__vartype(ptr_MsiQueryFeatureStateW))GetProcAddress(hModule, "MsiQueryFeatureStateW");
   ptr_MsiQueryProductStateA = (__vartype(ptr_MsiQueryProductStateA))GetProcAddress(hModule, "MsiQueryProductStateA");
   ptr_MsiQueryProductStateW = (__vartype(ptr_MsiQueryProductStateW))GetProcAddress(hModule, "MsiQueryProductStateW");
   ptr_MsiRecordClearData = (__vartype(ptr_MsiRecordClearData))GetProcAddress(hModule, "MsiRecordClearData");
   ptr_MsiRecordDataSize = (__vartype(ptr_MsiRecordDataSize))GetProcAddress(hModule, "MsiRecordDataSize");
   ptr_MsiRecordGetFieldCount = (__vartype(ptr_MsiRecordGetFieldCount))GetProcAddress(hModule, "MsiRecordGetFieldCount");
   ptr_MsiRecordGetInteger = (__vartype(ptr_MsiRecordGetInteger))GetProcAddress(hModule, "MsiRecordGetInteger");
   ptr_MsiRecordGetStringA = (__vartype(ptr_MsiRecordGetStringA))GetProcAddress(hModule, "MsiRecordGetStringA");
   ptr_MsiRecordGetStringW = (__vartype(ptr_MsiRecordGetStringW))GetProcAddress(hModule, "MsiRecordGetStringW");
   ptr_MsiRecordIsNull = (__vartype(ptr_MsiRecordIsNull))GetProcAddress(hModule, "MsiRecordIsNull");
   ptr_MsiRecordReadStream = (__vartype(ptr_MsiRecordReadStream))GetProcAddress(hModule, "MsiRecordReadStream");
   ptr_MsiRecordSetInteger = (__vartype(ptr_MsiRecordSetInteger))GetProcAddress(hModule, "MsiRecordSetInteger");
   ptr_MsiRecordSetStreamA = (__vartype(ptr_MsiRecordSetStreamA))GetProcAddress(hModule, "MsiRecordSetStreamA");
   ptr_MsiRecordSetStreamW = (__vartype(ptr_MsiRecordSetStreamW))GetProcAddress(hModule, "MsiRecordSetStreamW");
   ptr_MsiRecordSetStringA = (__vartype(ptr_MsiRecordSetStringA))GetProcAddress(hModule, "MsiRecordSetStringA");
   ptr_MsiRecordSetStringW = (__vartype(ptr_MsiRecordSetStringW))GetProcAddress(hModule, "MsiRecordSetStringW");
   ptr_MsiReinstallFeatureA = (__vartype(ptr_MsiReinstallFeatureA))GetProcAddress(hModule, "MsiReinstallFeatureA");
   ptr_MsiReinstallFeatureFromDescriptorA = (__vartype(ptr_MsiReinstallFeatureFromDescriptorA))GetProcAddress(hModule, "MsiReinstallFeatureFromDescriptorA");
   ptr_MsiReinstallFeatureFromDescriptorW = (__vartype(ptr_MsiReinstallFeatureFromDescriptorW))GetProcAddress(hModule, "MsiReinstallFeatureFromDescriptorW");
   ptr_MsiReinstallFeatureW = (__vartype(ptr_MsiReinstallFeatureW))GetProcAddress(hModule, "MsiReinstallFeatureW");
   ptr_MsiReinstallProductA = (__vartype(ptr_MsiReinstallProductA))GetProcAddress(hModule, "MsiReinstallProductA");
   ptr_MsiReinstallProductW = (__vartype(ptr_MsiReinstallProductW))GetProcAddress(hModule, "MsiReinstallProductW");
   ptr_MsiRemovePatchesA = (__vartype(ptr_MsiRemovePatchesA))GetProcAddress(hModule, "MsiRemovePatchesA");
   ptr_MsiRemovePatchesW = (__vartype(ptr_MsiRemovePatchesW))GetProcAddress(hModule, "MsiRemovePatchesW");
   ptr_MsiSequenceA = (__vartype(ptr_MsiSequenceA))GetProcAddress(hModule, "MsiSequenceA");
   ptr_MsiSequenceW = (__vartype(ptr_MsiSequenceW))GetProcAddress(hModule, "MsiSequenceW");
   ptr_MsiSetComponentStateA = (__vartype(ptr_MsiSetComponentStateA))GetProcAddress(hModule, "MsiSetComponentStateA");
   ptr_MsiSetComponentStateW = (__vartype(ptr_MsiSetComponentStateW))GetProcAddress(hModule, "MsiSetComponentStateW");
   ptr_MsiSetExternalUIA = (__vartype(ptr_MsiSetExternalUIA))GetProcAddress(hModule, "MsiSetExternalUIA");
   ptr_MsiSetExternalUIRecord = (__vartype(ptr_MsiSetExternalUIRecord))GetProcAddress(hModule, "MsiSetExternalUIRecord");
   ptr_MsiSetExternalUIW = (__vartype(ptr_MsiSetExternalUIW))GetProcAddress(hModule, "MsiSetExternalUIW");
   ptr_MsiSetFeatureAttributesA = (__vartype(ptr_MsiSetFeatureAttributesA))GetProcAddress(hModule, "MsiSetFeatureAttributesA");
   ptr_MsiSetFeatureAttributesW = (__vartype(ptr_MsiSetFeatureAttributesW))GetProcAddress(hModule, "MsiSetFeatureAttributesW");
   ptr_MsiSetFeatureStateA = (__vartype(ptr_MsiSetFeatureStateA))GetProcAddress(hModule, "MsiSetFeatureStateA");
   ptr_MsiSetFeatureStateW = (__vartype(ptr_MsiSetFeatureStateW))GetProcAddress(hModule, "MsiSetFeatureStateW");
   ptr_MsiSetInstallLevel = (__vartype(ptr_MsiSetInstallLevel))GetProcAddress(hModule, "MsiSetInstallLevel");
   ptr_MsiSetInternalUI = (__vartype(ptr_MsiSetInternalUI))GetProcAddress(hModule, "MsiSetInternalUI");
   ptr_MsiSetMode = (__vartype(ptr_MsiSetMode))GetProcAddress(hModule, "MsiSetMode");
   ptr_MsiSetOfflineContextW = (__vartype(ptr_MsiSetOfflineContextW))GetProcAddress(hModule, "MsiSetOfflineContextW");
   ptr_MsiSetPropertyA = (__vartype(ptr_MsiSetPropertyA))GetProcAddress(hModule, "MsiSetPropertyA");
   ptr_MsiSetPropertyW = (__vartype(ptr_MsiSetPropertyW))GetProcAddress(hModule, "MsiSetPropertyW");
   ptr_MsiSetTargetPathA = (__vartype(ptr_MsiSetTargetPathA))GetProcAddress(hModule, "MsiSetTargetPathA");
   ptr_MsiSetTargetPathW = (__vartype(ptr_MsiSetTargetPathW))GetProcAddress(hModule, "MsiSetTargetPathW");
   ptr_MsiSourceListAddMediaDiskA = (__vartype(ptr_MsiSourceListAddMediaDiskA))GetProcAddress(hModule, "MsiSourceListAddMediaDiskA");
   ptr_MsiSourceListAddMediaDiskW = (__vartype(ptr_MsiSourceListAddMediaDiskW))GetProcAddress(hModule, "MsiSourceListAddMediaDiskW");
   ptr_MsiSourceListAddSourceA = (__vartype(ptr_MsiSourceListAddSourceA))GetProcAddress(hModule, "MsiSourceListAddSourceA");
   ptr_MsiSourceListAddSourceExA = (__vartype(ptr_MsiSourceListAddSourceExA))GetProcAddress(hModule, "MsiSourceListAddSourceExA");
   ptr_MsiSourceListAddSourceExW = (__vartype(ptr_MsiSourceListAddSourceExW))GetProcAddress(hModule, "MsiSourceListAddSourceExW");
   ptr_MsiSourceListAddSourceW = (__vartype(ptr_MsiSourceListAddSourceW))GetProcAddress(hModule, "MsiSourceListAddSourceW");
   ptr_MsiSourceListClearAllA = (__vartype(ptr_MsiSourceListClearAllA))GetProcAddress(hModule, "MsiSourceListClearAllA");
   ptr_MsiSourceListClearAllExA = (__vartype(ptr_MsiSourceListClearAllExA))GetProcAddress(hModule, "MsiSourceListClearAllExA");
   ptr_MsiSourceListClearAllExW = (__vartype(ptr_MsiSourceListClearAllExW))GetProcAddress(hModule, "MsiSourceListClearAllExW");
   ptr_MsiSourceListClearAllW = (__vartype(ptr_MsiSourceListClearAllW))GetProcAddress(hModule, "MsiSourceListClearAllW");
   ptr_MsiSourceListClearMediaDiskA = (__vartype(ptr_MsiSourceListClearMediaDiskA))GetProcAddress(hModule, "MsiSourceListClearMediaDiskA");
   ptr_MsiSourceListClearMediaDiskW = (__vartype(ptr_MsiSourceListClearMediaDiskW))GetProcAddress(hModule, "MsiSourceListClearMediaDiskW");
   ptr_MsiSourceListClearSourceA = (__vartype(ptr_MsiSourceListClearSourceA))GetProcAddress(hModule, "MsiSourceListClearSourceA");
   ptr_MsiSourceListClearSourceW = (__vartype(ptr_MsiSourceListClearSourceW))GetProcAddress(hModule, "MsiSourceListClearSourceW");
   ptr_MsiSourceListEnumMediaDisksA = (__vartype(ptr_MsiSourceListEnumMediaDisksA))GetProcAddress(hModule, "MsiSourceListEnumMediaDisksA");
   ptr_MsiSourceListEnumMediaDisksW = (__vartype(ptr_MsiSourceListEnumMediaDisksW))GetProcAddress(hModule, "MsiSourceListEnumMediaDisksW");
   ptr_MsiSourceListEnumSourcesA = (__vartype(ptr_MsiSourceListEnumSourcesA))GetProcAddress(hModule, "MsiSourceListEnumSourcesA");
   ptr_MsiSourceListEnumSourcesW = (__vartype(ptr_MsiSourceListEnumSourcesW))GetProcAddress(hModule, "MsiSourceListEnumSourcesW");
   ptr_MsiSourceListForceResolutionA = (__vartype(ptr_MsiSourceListForceResolutionA))GetProcAddress(hModule, "MsiSourceListForceResolutionA");
   ptr_MsiSourceListForceResolutionExA = (__vartype(ptr_MsiSourceListForceResolutionExA))GetProcAddress(hModule, "MsiSourceListForceResolutionExA");
   ptr_MsiSourceListForceResolutionExW = (__vartype(ptr_MsiSourceListForceResolutionExW))GetProcAddress(hModule, "MsiSourceListForceResolutionExW");
   ptr_MsiSourceListForceResolutionW = (__vartype(ptr_MsiSourceListForceResolutionW))GetProcAddress(hModule, "MsiSourceListForceResolutionW");
   ptr_MsiSourceListGetInfoA = (__vartype(ptr_MsiSourceListGetInfoA))GetProcAddress(hModule, "MsiSourceListGetInfoA");
   ptr_MsiSourceListGetInfoW = (__vartype(ptr_MsiSourceListGetInfoW))GetProcAddress(hModule, "MsiSourceListGetInfoW");
   ptr_MsiSourceListSetInfoA = (__vartype(ptr_MsiSourceListSetInfoA))GetProcAddress(hModule, "MsiSourceListSetInfoA");
   ptr_MsiSourceListSetInfoW = (__vartype(ptr_MsiSourceListSetInfoW))GetProcAddress(hModule, "MsiSourceListSetInfoW");
   ptr_MsiSummaryInfoGetPropertyA = (__vartype(ptr_MsiSummaryInfoGetPropertyA))GetProcAddress(hModule, "MsiSummaryInfoGetPropertyA");
   ptr_MsiSummaryInfoGetPropertyCount = (__vartype(ptr_MsiSummaryInfoGetPropertyCount))GetProcAddress(hModule, "MsiSummaryInfoGetPropertyCount");
   ptr_MsiSummaryInfoGetPropertyW = (__vartype(ptr_MsiSummaryInfoGetPropertyW))GetProcAddress(hModule, "MsiSummaryInfoGetPropertyW");
   ptr_MsiSummaryInfoPersist = (__vartype(ptr_MsiSummaryInfoPersist))GetProcAddress(hModule, "MsiSummaryInfoPersist");
   ptr_MsiSummaryInfoSetPropertyA = (__vartype(ptr_MsiSummaryInfoSetPropertyA))GetProcAddress(hModule, "MsiSummaryInfoSetPropertyA");
   ptr_MsiSummaryInfoSetPropertyW = (__vartype(ptr_MsiSummaryInfoSetPropertyW))GetProcAddress(hModule, "MsiSummaryInfoSetPropertyW");
   ptr_MsiUseFeatureA = (__vartype(ptr_MsiUseFeatureA))GetProcAddress(hModule, "MsiUseFeatureA");
   ptr_MsiUseFeatureExA = (__vartype(ptr_MsiUseFeatureExA))GetProcAddress(hModule, "MsiUseFeatureExA");
   ptr_MsiUseFeatureExW = (__vartype(ptr_MsiUseFeatureExW))GetProcAddress(hModule, "MsiUseFeatureExW");
   ptr_MsiUseFeatureW = (__vartype(ptr_MsiUseFeatureW))GetProcAddress(hModule, "MsiUseFeatureW");
   ptr_MsiVerifyDiskSpace = (__vartype(ptr_MsiVerifyDiskSpace))GetProcAddress(hModule, "MsiVerifyDiskSpace");
   ptr_MsiVerifyPackageA = (__vartype(ptr_MsiVerifyPackageA))GetProcAddress(hModule, "MsiVerifyPackageA");
   ptr_MsiVerifyPackageW = (__vartype(ptr_MsiVerifyPackageW))GetProcAddress(hModule, "MsiVerifyPackageW");
   ptr_MsiViewClose = (__vartype(ptr_MsiViewClose))GetProcAddress(hModule, "MsiViewClose");
   ptr_MsiViewExecute = (__vartype(ptr_MsiViewExecute))GetProcAddress(hModule, "MsiViewExecute");
   ptr_MsiViewFetch = (__vartype(ptr_MsiViewFetch))GetProcAddress(hModule, "MsiViewFetch");
   ptr_MsiViewGetColumnInfo = (__vartype(ptr_MsiViewGetColumnInfo))GetProcAddress(hModule, "MsiViewGetColumnInfo");
   ptr_MsiViewGetErrorA = (__vartype(ptr_MsiViewGetErrorA))GetProcAddress(hModule, "MsiViewGetErrorA");
   ptr_MsiViewGetErrorW = (__vartype(ptr_MsiViewGetErrorW))GetProcAddress(hModule, "MsiViewGetErrorW");
   ptr_MsiViewModify = (__vartype(ptr_MsiViewModify))GetProcAddress(hModule, "MsiViewModify");
   ptr_QueryInstanceCount = (__vartype(ptr_QueryInstanceCount))GetProcAddress(hModule, "QueryInstanceCount");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

