#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_AllowPermLayer;
void *ptr_AllowPermLayer = NULL;
extern void *ptr_ApphelpCheckExe;
void *ptr_ApphelpCheckExe = NULL;
extern void *ptr_ApphelpCheckIME;
void *ptr_ApphelpCheckIME = NULL;
extern void *ptr_ApphelpCheckInstallShieldPackage;
void *ptr_ApphelpCheckInstallShieldPackage = NULL;
extern void *ptr_ApphelpCheckModule;
void *ptr_ApphelpCheckModule = NULL;
extern void *ptr_ApphelpCheckMsiPackage;
void *ptr_ApphelpCheckMsiPackage = NULL;
extern void *ptr_ApphelpCheckRunApp;
void *ptr_ApphelpCheckRunApp = NULL;
extern void *ptr_ApphelpCheckRunAppEx;
void *ptr_ApphelpCheckRunAppEx = NULL;
extern void *ptr_ApphelpCheckShellObject;
void *ptr_ApphelpCheckShellObject = NULL;
extern void *ptr_ApphelpCreateAppcompatData;
void *ptr_ApphelpCreateAppcompatData = NULL;
extern void *ptr_ApphelpFixMsiPackage;
void *ptr_ApphelpFixMsiPackage = NULL;
extern void *ptr_ApphelpFixMsiPackageExe;
void *ptr_ApphelpFixMsiPackageExe = NULL;
extern void *ptr_ApphelpFreeFileAttributes;
void *ptr_ApphelpFreeFileAttributes = NULL;
extern void *ptr_ApphelpGetFileAttributes;
void *ptr_ApphelpGetFileAttributes = NULL;
extern void *ptr_ApphelpGetMsiProperties;
void *ptr_ApphelpGetMsiProperties = NULL;
extern void *ptr_ApphelpGetNTVDMInfo;
void *ptr_ApphelpGetNTVDMInfo = NULL;
extern void *ptr_ApphelpGetShimDebugLevel;
void *ptr_ApphelpGetShimDebugLevel = NULL;
extern void *ptr_ApphelpParseModuleData;
void *ptr_ApphelpParseModuleData = NULL;
extern void *ptr_ApphelpQueryModuleData;
void *ptr_ApphelpQueryModuleData = NULL;
extern void *ptr_ApphelpQueryModuleDataEx;
void *ptr_ApphelpQueryModuleDataEx = NULL;
extern void *ptr_ApphelpShowDialog;
void *ptr_ApphelpShowDialog = NULL;
extern void *ptr_ApphelpUpdateCacheEntry;
void *ptr_ApphelpUpdateCacheEntry = NULL;
extern void *ptr_GetPermLayers;
void *ptr_GetPermLayers = NULL;
extern void *ptr_SE_DllLoaded;
void *ptr_SE_DllLoaded = NULL;
extern void *ptr_SE_DllUnloaded;
void *ptr_SE_DllUnloaded = NULL;
extern void *ptr_SE_DynamicShim;
void *ptr_SE_DynamicShim = NULL;
extern void *ptr_SE_GetHookAPIs;
void *ptr_SE_GetHookAPIs = NULL;
extern void *ptr_SE_GetMaxShimCount;
void *ptr_SE_GetMaxShimCount = NULL;
extern void *ptr_SE_GetProcAddressIgnoreIncExc;
void *ptr_SE_GetProcAddressIgnoreIncExc = NULL;
extern void *ptr_SE_GetProcAddressLoad;
void *ptr_SE_GetProcAddressLoad = NULL;
extern void *ptr_SE_GetShimCount;
void *ptr_SE_GetShimCount = NULL;
extern void *ptr_SE_InstallAfterInit;
void *ptr_SE_InstallAfterInit = NULL;
extern void *ptr_SE_InstallBeforeInit;
void *ptr_SE_InstallBeforeInit = NULL;
extern void *ptr_SE_IsShimDll;
void *ptr_SE_IsShimDll = NULL;
extern void *ptr_SE_LdrEntryRemoved;
void *ptr_SE_LdrEntryRemoved = NULL;
extern void *ptr_SE_ProcessDying;
void *ptr_SE_ProcessDying = NULL;
extern void *ptr_SdbAddLayerTagRefToQuery;
void *ptr_SdbAddLayerTagRefToQuery = NULL;
extern void *ptr_SdbApphelpNotify;
void *ptr_SdbApphelpNotify = NULL;
extern void *ptr_SdbApphelpNotifyEx;
void *ptr_SdbApphelpNotifyEx = NULL;
extern void *ptr_SdbApphelpNotifyEx2;
void *ptr_SdbApphelpNotifyEx2 = NULL;
extern void *ptr_SdbBeginWriteListTag;
void *ptr_SdbBeginWriteListTag = NULL;
extern void *ptr_SdbBuildCompatEnvVariables;
void *ptr_SdbBuildCompatEnvVariables = NULL;
extern void *ptr_SdbCloseApphelpInformation;
void *ptr_SdbCloseApphelpInformation = NULL;
extern void *ptr_SdbCloseDatabase;
void *ptr_SdbCloseDatabase = NULL;
extern void *ptr_SdbCloseDatabaseWrite;
void *ptr_SdbCloseDatabaseWrite = NULL;
extern void *ptr_SdbCloseLocalDatabase;
void *ptr_SdbCloseLocalDatabase = NULL;
extern void *ptr_SdbCommitIndexes;
void *ptr_SdbCommitIndexes = NULL;
extern void *ptr_SdbCreateDatabase;
void *ptr_SdbCreateDatabase = NULL;
extern void *ptr_SdbCreateHelpCenterURL;
void *ptr_SdbCreateHelpCenterURL = NULL;
extern void *ptr_SdbCreateMsiTransformFile;
void *ptr_SdbCreateMsiTransformFile = NULL;
extern void *ptr_SdbDeclareIndex;
void *ptr_SdbDeclareIndex = NULL;
extern void *ptr_SdbDeletePermLayerKeys;
void *ptr_SdbDeletePermLayerKeys = NULL;
extern void *ptr_SdbDumpSearchPathPartCaches;
void *ptr_SdbDumpSearchPathPartCaches = NULL;
extern void *ptr_SdbEndWriteListTag;
void *ptr_SdbEndWriteListTag = NULL;
extern void *ptr_SdbEnumMsiTransforms;
void *ptr_SdbEnumMsiTransforms = NULL;
extern void *ptr_SdbEscapeApphelpURL;
void *ptr_SdbEscapeApphelpURL = NULL;
extern void *ptr_SdbFindCustomActionForPackage;
void *ptr_SdbFindCustomActionForPackage = NULL;
extern void *ptr_SdbFindFirstDWORDIndexedTag;
void *ptr_SdbFindFirstDWORDIndexedTag = NULL;
extern void *ptr_SdbFindFirstGUIDIndexedTag;
void *ptr_SdbFindFirstGUIDIndexedTag = NULL;
extern void *ptr_SdbFindFirstMsiPackage;
void *ptr_SdbFindFirstMsiPackage = NULL;
extern void *ptr_SdbFindFirstMsiPackage_Str;
void *ptr_SdbFindFirstMsiPackage_Str = NULL;
extern void *ptr_SdbFindFirstNamedTag;
void *ptr_SdbFindFirstNamedTag = NULL;
extern void *ptr_SdbFindFirstStringIndexedTag;
void *ptr_SdbFindFirstStringIndexedTag = NULL;
extern void *ptr_SdbFindFirstTag;
void *ptr_SdbFindFirstTag = NULL;
extern void *ptr_SdbFindFirstTagRef;
void *ptr_SdbFindFirstTagRef = NULL;
extern void *ptr_SdbFindMsiPackageByID;
void *ptr_SdbFindMsiPackageByID = NULL;
extern void *ptr_SdbFindNextDWORDIndexedTag;
void *ptr_SdbFindNextDWORDIndexedTag = NULL;
extern void *ptr_SdbFindNextGUIDIndexedTag;
void *ptr_SdbFindNextGUIDIndexedTag = NULL;
extern void *ptr_SdbFindNextMsiPackage;
void *ptr_SdbFindNextMsiPackage = NULL;
extern void *ptr_SdbFindNextStringIndexedTag;
void *ptr_SdbFindNextStringIndexedTag = NULL;
extern void *ptr_SdbFindNextTag;
void *ptr_SdbFindNextTag = NULL;
extern void *ptr_SdbFindNextTagRef;
void *ptr_SdbFindNextTagRef = NULL;
extern void *ptr_SdbFormatAttribute;
void *ptr_SdbFormatAttribute = NULL;
extern void *ptr_SdbFreeDatabaseInformation;
void *ptr_SdbFreeDatabaseInformation = NULL;
extern void *ptr_SdbFreeFileAttributes;
void *ptr_SdbFreeFileAttributes = NULL;
extern void *ptr_SdbFreeFileInfo;
void *ptr_SdbFreeFileInfo = NULL;
extern void *ptr_SdbFreeFlagInfo;
void *ptr_SdbFreeFlagInfo = NULL;
extern void *ptr_SdbGUIDFromString;
void *ptr_SdbGUIDFromString = NULL;
extern void *ptr_SdbGUIDToString;
void *ptr_SdbGUIDToString = NULL;
extern void *ptr_SdbGetAppCompatDataSize;
void *ptr_SdbGetAppCompatDataSize = NULL;
extern void *ptr_SdbGetAppPatchDir;
void *ptr_SdbGetAppPatchDir = NULL;
extern void *ptr_SdbGetBinaryTagData;
void *ptr_SdbGetBinaryTagData = NULL;
extern void *ptr_SdbGetDatabaseGUID;
void *ptr_SdbGetDatabaseGUID = NULL;
extern void *ptr_SdbGetDatabaseID;
void *ptr_SdbGetDatabaseID = NULL;
extern void *ptr_SdbGetDatabaseInformation;
void *ptr_SdbGetDatabaseInformation = NULL;
extern void *ptr_SdbGetDatabaseInformationByName;
void *ptr_SdbGetDatabaseInformationByName = NULL;
extern void *ptr_SdbGetDatabaseMatch;
void *ptr_SdbGetDatabaseMatch = NULL;
extern void *ptr_SdbGetDatabaseVersion;
void *ptr_SdbGetDatabaseVersion = NULL;
extern void *ptr_SdbGetDllPath;
void *ptr_SdbGetDllPath = NULL;
extern void *ptr_SdbGetEntryFlags;
void *ptr_SdbGetEntryFlags = NULL;
extern void *ptr_SdbGetFileAttributes;
void *ptr_SdbGetFileAttributes = NULL;
extern void *ptr_SdbGetFileImageType;
void *ptr_SdbGetFileImageType = NULL;
extern void *ptr_SdbGetFileImageTypeEx;
void *ptr_SdbGetFileImageTypeEx = NULL;
extern void *ptr_SdbGetFileInfo;
void *ptr_SdbGetFileInfo = NULL;
extern void *ptr_SdbGetFirstChild;
void *ptr_SdbGetFirstChild = NULL;
extern void *ptr_SdbGetImageType;
void *ptr_SdbGetImageType = NULL;
extern void *ptr_SdbGetIndex;
void *ptr_SdbGetIndex = NULL;
extern void *ptr_SdbGetItemFromItemRef;
void *ptr_SdbGetItemFromItemRef = NULL;
extern void *ptr_SdbGetLayerName;
void *ptr_SdbGetLayerName = NULL;
extern void *ptr_SdbGetLayerTagRef;
void *ptr_SdbGetLayerTagRef = NULL;
extern void *ptr_SdbGetLocalPDB;
void *ptr_SdbGetLocalPDB = NULL;
extern void *ptr_SdbGetMatchingExe;
void *ptr_SdbGetMatchingExe = NULL;
extern void *ptr_SdbGetMsiPackageInformation;
void *ptr_SdbGetMsiPackageInformation = NULL;
extern void *ptr_SdbGetNamedLayer;
void *ptr_SdbGetNamedLayer = NULL;
extern void *ptr_SdbGetNextChild;
void *ptr_SdbGetNextChild = NULL;
extern void *ptr_SdbGetNthUserSdb;
void *ptr_SdbGetNthUserSdb = NULL;
extern void *ptr_SdbGetPDBFromGUID;
void *ptr_SdbGetPDBFromGUID = NULL;
extern void *ptr_SdbGetPermLayerKeys;
void *ptr_SdbGetPermLayerKeys = NULL;
extern void *ptr_SdbGetShowDebugInfoOption;
void *ptr_SdbGetShowDebugInfoOption = NULL;
extern void *ptr_SdbGetShowDebugInfoOptionValue;
void *ptr_SdbGetShowDebugInfoOptionValue = NULL;
extern void *ptr_SdbGetStandardDatabaseGUID;
void *ptr_SdbGetStandardDatabaseGUID = NULL;
extern void *ptr_SdbGetStringTagPtr;
void *ptr_SdbGetStringTagPtr = NULL;
extern void *ptr_SdbGetTagDataSize;
void *ptr_SdbGetTagDataSize = NULL;
extern void *ptr_SdbGetTagFromTagID;
void *ptr_SdbGetTagFromTagID = NULL;
extern void *ptr_SdbGrabMatchingInfo;
void *ptr_SdbGrabMatchingInfo = NULL;
extern void *ptr_SdbGrabMatchingInfoEx;
void *ptr_SdbGrabMatchingInfoEx = NULL;
extern void *ptr_SdbInitDatabase;
void *ptr_SdbInitDatabase = NULL;
extern void *ptr_SdbInitDatabaseEx;
void *ptr_SdbInitDatabaseEx = NULL;
extern void *ptr_SdbIsNullGUID;
void *ptr_SdbIsNullGUID = NULL;
extern void *ptr_SdbIsStandardDatabase;
void *ptr_SdbIsStandardDatabase = NULL;
extern void *ptr_SdbIsTagrefFromLocalDB;
void *ptr_SdbIsTagrefFromLocalDB = NULL;
extern void *ptr_SdbIsTagrefFromMainDB;
void *ptr_SdbIsTagrefFromMainDB = NULL;
extern void *ptr_SdbLoadString;
void *ptr_SdbLoadString = NULL;
extern void *ptr_SdbMakeIndexKeyFromString;
void *ptr_SdbMakeIndexKeyFromString = NULL;
extern void *ptr_SdbOpenApphelpDetailsDatabase;
void *ptr_SdbOpenApphelpDetailsDatabase = NULL;
extern void *ptr_SdbOpenApphelpDetailsDatabaseSP;
void *ptr_SdbOpenApphelpDetailsDatabaseSP = NULL;
extern void *ptr_SdbOpenApphelpInformation;
void *ptr_SdbOpenApphelpInformation = NULL;
extern void *ptr_SdbOpenApphelpInformationByID;
void *ptr_SdbOpenApphelpInformationByID = NULL;
extern void *ptr_SdbOpenApphelpResourceFile;
void *ptr_SdbOpenApphelpResourceFile = NULL;
extern void *ptr_SdbOpenDatabase;
void *ptr_SdbOpenDatabase = NULL;
extern void *ptr_SdbOpenDbFromGuid;
void *ptr_SdbOpenDbFromGuid = NULL;
extern void *ptr_SdbOpenLocalDatabase;
void *ptr_SdbOpenLocalDatabase = NULL;
extern void *ptr_SdbPackAppCompatData;
void *ptr_SdbPackAppCompatData = NULL;
extern void *ptr_SdbQueryApphelpInformation;
void *ptr_SdbQueryApphelpInformation = NULL;
extern void *ptr_SdbQueryBlockUpgrade;
void *ptr_SdbQueryBlockUpgrade = NULL;
extern void *ptr_SdbQueryContext;
void *ptr_SdbQueryContext = NULL;
extern void *ptr_SdbQueryData;
void *ptr_SdbQueryData = NULL;
extern void *ptr_SdbQueryDataEx;
void *ptr_SdbQueryDataEx = NULL;
extern void *ptr_SdbQueryDataExTagID;
void *ptr_SdbQueryDataExTagID = NULL;
extern void *ptr_SdbQueryFlagInfo;
void *ptr_SdbQueryFlagInfo = NULL;
extern void *ptr_SdbQueryFlagMask;
void *ptr_SdbQueryFlagMask = NULL;
extern void *ptr_SdbQueryName;
void *ptr_SdbQueryName = NULL;
extern void *ptr_SdbQueryReinstallUpgrade;
void *ptr_SdbQueryReinstallUpgrade = NULL;
extern void *ptr_SdbReadApphelpData;
void *ptr_SdbReadApphelpData = NULL;
extern void *ptr_SdbReadApphelpDetailsData;
void *ptr_SdbReadApphelpDetailsData = NULL;
extern void *ptr_SdbReadBYTETag;
void *ptr_SdbReadBYTETag = NULL;
extern void *ptr_SdbReadBYTETagRef;
void *ptr_SdbReadBYTETagRef = NULL;
extern void *ptr_SdbReadBinaryTag;
void *ptr_SdbReadBinaryTag = NULL;
extern void *ptr_SdbReadDWORDTag;
void *ptr_SdbReadDWORDTag = NULL;
extern void *ptr_SdbReadDWORDTagRef;
void *ptr_SdbReadDWORDTagRef = NULL;
extern void *ptr_SdbReadEntryInformation;
void *ptr_SdbReadEntryInformation = NULL;
extern void *ptr_SdbReadMsiTransformInfo;
void *ptr_SdbReadMsiTransformInfo = NULL;
extern void *ptr_SdbReadPatchBits;
void *ptr_SdbReadPatchBits = NULL;
extern void *ptr_SdbReadQWORDTag;
void *ptr_SdbReadQWORDTag = NULL;
extern void *ptr_SdbReadQWORDTagRef;
void *ptr_SdbReadQWORDTagRef = NULL;
extern void *ptr_SdbReadStringTag;
void *ptr_SdbReadStringTag = NULL;
extern void *ptr_SdbReadStringTagRef;
void *ptr_SdbReadStringTagRef = NULL;
extern void *ptr_SdbReadWORDTag;
void *ptr_SdbReadWORDTag = NULL;
extern void *ptr_SdbReadWORDTagRef;
void *ptr_SdbReadWORDTagRef = NULL;
extern void *ptr_SdbRegisterDatabase;
void *ptr_SdbRegisterDatabase = NULL;
extern void *ptr_SdbRegisterDatabaseEx;
void *ptr_SdbRegisterDatabaseEx = NULL;
extern void *ptr_SdbReleaseDatabase;
void *ptr_SdbReleaseDatabase = NULL;
extern void *ptr_SdbReleaseMatchingExe;
void *ptr_SdbReleaseMatchingExe = NULL;
extern void *ptr_SdbResolveDatabase;
void *ptr_SdbResolveDatabase = NULL;
extern void *ptr_SdbSetApphelpDebugParameters;
void *ptr_SdbSetApphelpDebugParameters = NULL;
extern void *ptr_SdbSetEntryFlags;
void *ptr_SdbSetEntryFlags = NULL;
extern void *ptr_SdbSetImageType;
void *ptr_SdbSetImageType = NULL;
extern void *ptr_SdbSetPermLayerKeys;
void *ptr_SdbSetPermLayerKeys = NULL;
extern void *ptr_SdbShowApphelpDialog;
void *ptr_SdbShowApphelpDialog = NULL;
extern void *ptr_SdbShowApphelpFromQuery;
void *ptr_SdbShowApphelpFromQuery = NULL;
extern void *ptr_SdbStartIndexing;
void *ptr_SdbStartIndexing = NULL;
extern void *ptr_SdbStopIndexing;
void *ptr_SdbStopIndexing = NULL;
extern void *ptr_SdbStringDuplicate;
void *ptr_SdbStringDuplicate = NULL;
extern void *ptr_SdbStringReplace;
void *ptr_SdbStringReplace = NULL;
extern void *ptr_SdbStringReplaceArray;
void *ptr_SdbStringReplaceArray = NULL;
extern void *ptr_SdbTagIDToTagRef;
void *ptr_SdbTagIDToTagRef = NULL;
extern void *ptr_SdbTagRefToTagID;
void *ptr_SdbTagRefToTagID = NULL;
extern void *ptr_SdbTagToString;
void *ptr_SdbTagToString = NULL;
extern void *ptr_SdbUnpackAppCompatData;
void *ptr_SdbUnpackAppCompatData = NULL;
extern void *ptr_SdbUnregisterDatabase;
void *ptr_SdbUnregisterDatabase = NULL;
extern void *ptr_SdbWriteBYTETag;
void *ptr_SdbWriteBYTETag = NULL;
extern void *ptr_SdbWriteBinaryTag;
void *ptr_SdbWriteBinaryTag = NULL;
extern void *ptr_SdbWriteBinaryTagFromFile;
void *ptr_SdbWriteBinaryTagFromFile = NULL;
extern void *ptr_SdbWriteDWORDTag;
void *ptr_SdbWriteDWORDTag = NULL;
extern void *ptr_SdbWriteNULLTag;
void *ptr_SdbWriteNULLTag = NULL;
extern void *ptr_SdbWriteQWORDTag;
void *ptr_SdbWriteQWORDTag = NULL;
extern void *ptr_SdbWriteStringRefTag;
void *ptr_SdbWriteStringRefTag = NULL;
extern void *ptr_SdbWriteStringTag;
void *ptr_SdbWriteStringTag = NULL;
extern void *ptr_SdbWriteStringTagDirect;
void *ptr_SdbWriteStringTagDirect = NULL;
extern void *ptr_SdbWriteWORDTag;
void *ptr_SdbWriteWORDTag = NULL;
extern void *ptr_SetPermLayerState;
void *ptr_SetPermLayerState = NULL;
extern void *ptr_SetPermLayers;
void *ptr_SetPermLayers = NULL;
extern void *ptr_ShimDbgPrint;
void *ptr_ShimDbgPrint = NULL;
extern void *ptr_ShimDumpCache;
void *ptr_ShimDumpCache = NULL;
extern void *ptr_ShimFlushCache;
void *ptr_ShimFlushCache = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\apphelp.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_AllowPermLayer = (__vartype(ptr_AllowPermLayer))GetProcAddress(hModule, "AllowPermLayer");
   ptr_ApphelpCheckExe = (__vartype(ptr_ApphelpCheckExe))GetProcAddress(hModule, "ApphelpCheckExe");
   ptr_ApphelpCheckIME = (__vartype(ptr_ApphelpCheckIME))GetProcAddress(hModule, "ApphelpCheckIME");
   ptr_ApphelpCheckInstallShieldPackage = (__vartype(ptr_ApphelpCheckInstallShieldPackage))GetProcAddress(hModule, "ApphelpCheckInstallShieldPackage");
   ptr_ApphelpCheckModule = (__vartype(ptr_ApphelpCheckModule))GetProcAddress(hModule, "ApphelpCheckModule");
   ptr_ApphelpCheckMsiPackage = (__vartype(ptr_ApphelpCheckMsiPackage))GetProcAddress(hModule, "ApphelpCheckMsiPackage");
   ptr_ApphelpCheckRunApp = (__vartype(ptr_ApphelpCheckRunApp))GetProcAddress(hModule, "ApphelpCheckRunApp");
   ptr_ApphelpCheckRunAppEx = (__vartype(ptr_ApphelpCheckRunAppEx))GetProcAddress(hModule, "ApphelpCheckRunAppEx");
   ptr_ApphelpCheckShellObject = (__vartype(ptr_ApphelpCheckShellObject))GetProcAddress(hModule, "ApphelpCheckShellObject");
   ptr_ApphelpCreateAppcompatData = (__vartype(ptr_ApphelpCreateAppcompatData))GetProcAddress(hModule, "ApphelpCreateAppcompatData");
   ptr_ApphelpFixMsiPackage = (__vartype(ptr_ApphelpFixMsiPackage))GetProcAddress(hModule, "ApphelpFixMsiPackage");
   ptr_ApphelpFixMsiPackageExe = (__vartype(ptr_ApphelpFixMsiPackageExe))GetProcAddress(hModule, "ApphelpFixMsiPackageExe");
   ptr_ApphelpFreeFileAttributes = (__vartype(ptr_ApphelpFreeFileAttributes))GetProcAddress(hModule, "ApphelpFreeFileAttributes");
   ptr_ApphelpGetFileAttributes = (__vartype(ptr_ApphelpGetFileAttributes))GetProcAddress(hModule, "ApphelpGetFileAttributes");
   ptr_ApphelpGetMsiProperties = (__vartype(ptr_ApphelpGetMsiProperties))GetProcAddress(hModule, "ApphelpGetMsiProperties");
   ptr_ApphelpGetNTVDMInfo = (__vartype(ptr_ApphelpGetNTVDMInfo))GetProcAddress(hModule, "ApphelpGetNTVDMInfo");
   ptr_ApphelpGetShimDebugLevel = (__vartype(ptr_ApphelpGetShimDebugLevel))GetProcAddress(hModule, "ApphelpGetShimDebugLevel");
   ptr_ApphelpParseModuleData = (__vartype(ptr_ApphelpParseModuleData))GetProcAddress(hModule, "ApphelpParseModuleData");
   ptr_ApphelpQueryModuleData = (__vartype(ptr_ApphelpQueryModuleData))GetProcAddress(hModule, "ApphelpQueryModuleData");
   ptr_ApphelpQueryModuleDataEx = (__vartype(ptr_ApphelpQueryModuleDataEx))GetProcAddress(hModule, "ApphelpQueryModuleDataEx");
   ptr_ApphelpShowDialog = (__vartype(ptr_ApphelpShowDialog))GetProcAddress(hModule, "ApphelpShowDialog");
   ptr_ApphelpUpdateCacheEntry = (__vartype(ptr_ApphelpUpdateCacheEntry))GetProcAddress(hModule, "ApphelpUpdateCacheEntry");
   ptr_GetPermLayers = (__vartype(ptr_GetPermLayers))GetProcAddress(hModule, "GetPermLayers");
   ptr_SE_DllLoaded = (__vartype(ptr_SE_DllLoaded))GetProcAddress(hModule, "SE_DllLoaded");
   ptr_SE_DllUnloaded = (__vartype(ptr_SE_DllUnloaded))GetProcAddress(hModule, "SE_DllUnloaded");
   ptr_SE_DynamicShim = (__vartype(ptr_SE_DynamicShim))GetProcAddress(hModule, "SE_DynamicShim");
   ptr_SE_GetHookAPIs = (__vartype(ptr_SE_GetHookAPIs))GetProcAddress(hModule, "SE_GetHookAPIs");
   ptr_SE_GetMaxShimCount = (__vartype(ptr_SE_GetMaxShimCount))GetProcAddress(hModule, "SE_GetMaxShimCount");
   ptr_SE_GetProcAddressIgnoreIncExc = (__vartype(ptr_SE_GetProcAddressIgnoreIncExc))GetProcAddress(hModule, "SE_GetProcAddressIgnoreIncExc");
   ptr_SE_GetProcAddressLoad = (__vartype(ptr_SE_GetProcAddressLoad))GetProcAddress(hModule, "SE_GetProcAddressLoad");
   ptr_SE_GetShimCount = (__vartype(ptr_SE_GetShimCount))GetProcAddress(hModule, "SE_GetShimCount");
   ptr_SE_InstallAfterInit = (__vartype(ptr_SE_InstallAfterInit))GetProcAddress(hModule, "SE_InstallAfterInit");
   ptr_SE_InstallBeforeInit = (__vartype(ptr_SE_InstallBeforeInit))GetProcAddress(hModule, "SE_InstallBeforeInit");
   ptr_SE_IsShimDll = (__vartype(ptr_SE_IsShimDll))GetProcAddress(hModule, "SE_IsShimDll");
   ptr_SE_LdrEntryRemoved = (__vartype(ptr_SE_LdrEntryRemoved))GetProcAddress(hModule, "SE_LdrEntryRemoved");
   ptr_SE_ProcessDying = (__vartype(ptr_SE_ProcessDying))GetProcAddress(hModule, "SE_ProcessDying");
   ptr_SdbAddLayerTagRefToQuery = (__vartype(ptr_SdbAddLayerTagRefToQuery))GetProcAddress(hModule, "SdbAddLayerTagRefToQuery");
   ptr_SdbApphelpNotify = (__vartype(ptr_SdbApphelpNotify))GetProcAddress(hModule, "SdbApphelpNotify");
   ptr_SdbApphelpNotifyEx = (__vartype(ptr_SdbApphelpNotifyEx))GetProcAddress(hModule, "SdbApphelpNotifyEx");
   ptr_SdbApphelpNotifyEx2 = (__vartype(ptr_SdbApphelpNotifyEx2))GetProcAddress(hModule, "SdbApphelpNotifyEx2");
   ptr_SdbBeginWriteListTag = (__vartype(ptr_SdbBeginWriteListTag))GetProcAddress(hModule, "SdbBeginWriteListTag");
   ptr_SdbBuildCompatEnvVariables = (__vartype(ptr_SdbBuildCompatEnvVariables))GetProcAddress(hModule, "SdbBuildCompatEnvVariables");
   ptr_SdbCloseApphelpInformation = (__vartype(ptr_SdbCloseApphelpInformation))GetProcAddress(hModule, "SdbCloseApphelpInformation");
   ptr_SdbCloseDatabase = (__vartype(ptr_SdbCloseDatabase))GetProcAddress(hModule, "SdbCloseDatabase");
   ptr_SdbCloseDatabaseWrite = (__vartype(ptr_SdbCloseDatabaseWrite))GetProcAddress(hModule, "SdbCloseDatabaseWrite");
   ptr_SdbCloseLocalDatabase = (__vartype(ptr_SdbCloseLocalDatabase))GetProcAddress(hModule, "SdbCloseLocalDatabase");
   ptr_SdbCommitIndexes = (__vartype(ptr_SdbCommitIndexes))GetProcAddress(hModule, "SdbCommitIndexes");
   ptr_SdbCreateDatabase = (__vartype(ptr_SdbCreateDatabase))GetProcAddress(hModule, "SdbCreateDatabase");
   ptr_SdbCreateHelpCenterURL = (__vartype(ptr_SdbCreateHelpCenterURL))GetProcAddress(hModule, "SdbCreateHelpCenterURL");
   ptr_SdbCreateMsiTransformFile = (__vartype(ptr_SdbCreateMsiTransformFile))GetProcAddress(hModule, "SdbCreateMsiTransformFile");
   ptr_SdbDeclareIndex = (__vartype(ptr_SdbDeclareIndex))GetProcAddress(hModule, "SdbDeclareIndex");
   ptr_SdbDeletePermLayerKeys = (__vartype(ptr_SdbDeletePermLayerKeys))GetProcAddress(hModule, "SdbDeletePermLayerKeys");
   ptr_SdbDumpSearchPathPartCaches = (__vartype(ptr_SdbDumpSearchPathPartCaches))GetProcAddress(hModule, "SdbDumpSearchPathPartCaches");
   ptr_SdbEndWriteListTag = (__vartype(ptr_SdbEndWriteListTag))GetProcAddress(hModule, "SdbEndWriteListTag");
   ptr_SdbEnumMsiTransforms = (__vartype(ptr_SdbEnumMsiTransforms))GetProcAddress(hModule, "SdbEnumMsiTransforms");
   ptr_SdbEscapeApphelpURL = (__vartype(ptr_SdbEscapeApphelpURL))GetProcAddress(hModule, "SdbEscapeApphelpURL");
   ptr_SdbFindCustomActionForPackage = (__vartype(ptr_SdbFindCustomActionForPackage))GetProcAddress(hModule, "SdbFindCustomActionForPackage");
   ptr_SdbFindFirstDWORDIndexedTag = (__vartype(ptr_SdbFindFirstDWORDIndexedTag))GetProcAddress(hModule, "SdbFindFirstDWORDIndexedTag");
   ptr_SdbFindFirstGUIDIndexedTag = (__vartype(ptr_SdbFindFirstGUIDIndexedTag))GetProcAddress(hModule, "SdbFindFirstGUIDIndexedTag");
   ptr_SdbFindFirstMsiPackage = (__vartype(ptr_SdbFindFirstMsiPackage))GetProcAddress(hModule, "SdbFindFirstMsiPackage");
   ptr_SdbFindFirstMsiPackage_Str = (__vartype(ptr_SdbFindFirstMsiPackage_Str))GetProcAddress(hModule, "SdbFindFirstMsiPackage_Str");
   ptr_SdbFindFirstNamedTag = (__vartype(ptr_SdbFindFirstNamedTag))GetProcAddress(hModule, "SdbFindFirstNamedTag");
   ptr_SdbFindFirstStringIndexedTag = (__vartype(ptr_SdbFindFirstStringIndexedTag))GetProcAddress(hModule, "SdbFindFirstStringIndexedTag");
   ptr_SdbFindFirstTag = (__vartype(ptr_SdbFindFirstTag))GetProcAddress(hModule, "SdbFindFirstTag");
   ptr_SdbFindFirstTagRef = (__vartype(ptr_SdbFindFirstTagRef))GetProcAddress(hModule, "SdbFindFirstTagRef");
   ptr_SdbFindMsiPackageByID = (__vartype(ptr_SdbFindMsiPackageByID))GetProcAddress(hModule, "SdbFindMsiPackageByID");
   ptr_SdbFindNextDWORDIndexedTag = (__vartype(ptr_SdbFindNextDWORDIndexedTag))GetProcAddress(hModule, "SdbFindNextDWORDIndexedTag");
   ptr_SdbFindNextGUIDIndexedTag = (__vartype(ptr_SdbFindNextGUIDIndexedTag))GetProcAddress(hModule, "SdbFindNextGUIDIndexedTag");
   ptr_SdbFindNextMsiPackage = (__vartype(ptr_SdbFindNextMsiPackage))GetProcAddress(hModule, "SdbFindNextMsiPackage");
   ptr_SdbFindNextStringIndexedTag = (__vartype(ptr_SdbFindNextStringIndexedTag))GetProcAddress(hModule, "SdbFindNextStringIndexedTag");
   ptr_SdbFindNextTag = (__vartype(ptr_SdbFindNextTag))GetProcAddress(hModule, "SdbFindNextTag");
   ptr_SdbFindNextTagRef = (__vartype(ptr_SdbFindNextTagRef))GetProcAddress(hModule, "SdbFindNextTagRef");
   ptr_SdbFormatAttribute = (__vartype(ptr_SdbFormatAttribute))GetProcAddress(hModule, "SdbFormatAttribute");
   ptr_SdbFreeDatabaseInformation = (__vartype(ptr_SdbFreeDatabaseInformation))GetProcAddress(hModule, "SdbFreeDatabaseInformation");
   ptr_SdbFreeFileAttributes = (__vartype(ptr_SdbFreeFileAttributes))GetProcAddress(hModule, "SdbFreeFileAttributes");
   ptr_SdbFreeFileInfo = (__vartype(ptr_SdbFreeFileInfo))GetProcAddress(hModule, "SdbFreeFileInfo");
   ptr_SdbFreeFlagInfo = (__vartype(ptr_SdbFreeFlagInfo))GetProcAddress(hModule, "SdbFreeFlagInfo");
   ptr_SdbGUIDFromString = (__vartype(ptr_SdbGUIDFromString))GetProcAddress(hModule, "SdbGUIDFromString");
   ptr_SdbGUIDToString = (__vartype(ptr_SdbGUIDToString))GetProcAddress(hModule, "SdbGUIDToString");
   ptr_SdbGetAppCompatDataSize = (__vartype(ptr_SdbGetAppCompatDataSize))GetProcAddress(hModule, "SdbGetAppCompatDataSize");
   ptr_SdbGetAppPatchDir = (__vartype(ptr_SdbGetAppPatchDir))GetProcAddress(hModule, "SdbGetAppPatchDir");
   ptr_SdbGetBinaryTagData = (__vartype(ptr_SdbGetBinaryTagData))GetProcAddress(hModule, "SdbGetBinaryTagData");
   ptr_SdbGetDatabaseGUID = (__vartype(ptr_SdbGetDatabaseGUID))GetProcAddress(hModule, "SdbGetDatabaseGUID");
   ptr_SdbGetDatabaseID = (__vartype(ptr_SdbGetDatabaseID))GetProcAddress(hModule, "SdbGetDatabaseID");
   ptr_SdbGetDatabaseInformation = (__vartype(ptr_SdbGetDatabaseInformation))GetProcAddress(hModule, "SdbGetDatabaseInformation");
   ptr_SdbGetDatabaseInformationByName = (__vartype(ptr_SdbGetDatabaseInformationByName))GetProcAddress(hModule, "SdbGetDatabaseInformationByName");
   ptr_SdbGetDatabaseMatch = (__vartype(ptr_SdbGetDatabaseMatch))GetProcAddress(hModule, "SdbGetDatabaseMatch");
   ptr_SdbGetDatabaseVersion = (__vartype(ptr_SdbGetDatabaseVersion))GetProcAddress(hModule, "SdbGetDatabaseVersion");
   ptr_SdbGetDllPath = (__vartype(ptr_SdbGetDllPath))GetProcAddress(hModule, "SdbGetDllPath");
   ptr_SdbGetEntryFlags = (__vartype(ptr_SdbGetEntryFlags))GetProcAddress(hModule, "SdbGetEntryFlags");
   ptr_SdbGetFileAttributes = (__vartype(ptr_SdbGetFileAttributes))GetProcAddress(hModule, "SdbGetFileAttributes");
   ptr_SdbGetFileImageType = (__vartype(ptr_SdbGetFileImageType))GetProcAddress(hModule, "SdbGetFileImageType");
   ptr_SdbGetFileImageTypeEx = (__vartype(ptr_SdbGetFileImageTypeEx))GetProcAddress(hModule, "SdbGetFileImageTypeEx");
   ptr_SdbGetFileInfo = (__vartype(ptr_SdbGetFileInfo))GetProcAddress(hModule, "SdbGetFileInfo");
   ptr_SdbGetFirstChild = (__vartype(ptr_SdbGetFirstChild))GetProcAddress(hModule, "SdbGetFirstChild");
   ptr_SdbGetImageType = (__vartype(ptr_SdbGetImageType))GetProcAddress(hModule, "SdbGetImageType");
   ptr_SdbGetIndex = (__vartype(ptr_SdbGetIndex))GetProcAddress(hModule, "SdbGetIndex");
   ptr_SdbGetItemFromItemRef = (__vartype(ptr_SdbGetItemFromItemRef))GetProcAddress(hModule, "SdbGetItemFromItemRef");
   ptr_SdbGetLayerName = (__vartype(ptr_SdbGetLayerName))GetProcAddress(hModule, "SdbGetLayerName");
   ptr_SdbGetLayerTagRef = (__vartype(ptr_SdbGetLayerTagRef))GetProcAddress(hModule, "SdbGetLayerTagRef");
   ptr_SdbGetLocalPDB = (__vartype(ptr_SdbGetLocalPDB))GetProcAddress(hModule, "SdbGetLocalPDB");
   ptr_SdbGetMatchingExe = (__vartype(ptr_SdbGetMatchingExe))GetProcAddress(hModule, "SdbGetMatchingExe");
   ptr_SdbGetMsiPackageInformation = (__vartype(ptr_SdbGetMsiPackageInformation))GetProcAddress(hModule, "SdbGetMsiPackageInformation");
   ptr_SdbGetNamedLayer = (__vartype(ptr_SdbGetNamedLayer))GetProcAddress(hModule, "SdbGetNamedLayer");
   ptr_SdbGetNextChild = (__vartype(ptr_SdbGetNextChild))GetProcAddress(hModule, "SdbGetNextChild");
   ptr_SdbGetNthUserSdb = (__vartype(ptr_SdbGetNthUserSdb))GetProcAddress(hModule, "SdbGetNthUserSdb");
   ptr_SdbGetPDBFromGUID = (__vartype(ptr_SdbGetPDBFromGUID))GetProcAddress(hModule, "SdbGetPDBFromGUID");
   ptr_SdbGetPermLayerKeys = (__vartype(ptr_SdbGetPermLayerKeys))GetProcAddress(hModule, "SdbGetPermLayerKeys");
   ptr_SdbGetShowDebugInfoOption = (__vartype(ptr_SdbGetShowDebugInfoOption))GetProcAddress(hModule, "SdbGetShowDebugInfoOption");
   ptr_SdbGetShowDebugInfoOptionValue = (__vartype(ptr_SdbGetShowDebugInfoOptionValue))GetProcAddress(hModule, "SdbGetShowDebugInfoOptionValue");
   ptr_SdbGetStandardDatabaseGUID = (__vartype(ptr_SdbGetStandardDatabaseGUID))GetProcAddress(hModule, "SdbGetStandardDatabaseGUID");
   ptr_SdbGetStringTagPtr = (__vartype(ptr_SdbGetStringTagPtr))GetProcAddress(hModule, "SdbGetStringTagPtr");
   ptr_SdbGetTagDataSize = (__vartype(ptr_SdbGetTagDataSize))GetProcAddress(hModule, "SdbGetTagDataSize");
   ptr_SdbGetTagFromTagID = (__vartype(ptr_SdbGetTagFromTagID))GetProcAddress(hModule, "SdbGetTagFromTagID");
   ptr_SdbGrabMatchingInfo = (__vartype(ptr_SdbGrabMatchingInfo))GetProcAddress(hModule, "SdbGrabMatchingInfo");
   ptr_SdbGrabMatchingInfoEx = (__vartype(ptr_SdbGrabMatchingInfoEx))GetProcAddress(hModule, "SdbGrabMatchingInfoEx");
   ptr_SdbInitDatabase = (__vartype(ptr_SdbInitDatabase))GetProcAddress(hModule, "SdbInitDatabase");
   ptr_SdbInitDatabaseEx = (__vartype(ptr_SdbInitDatabaseEx))GetProcAddress(hModule, "SdbInitDatabaseEx");
   ptr_SdbIsNullGUID = (__vartype(ptr_SdbIsNullGUID))GetProcAddress(hModule, "SdbIsNullGUID");
   ptr_SdbIsStandardDatabase = (__vartype(ptr_SdbIsStandardDatabase))GetProcAddress(hModule, "SdbIsStandardDatabase");
   ptr_SdbIsTagrefFromLocalDB = (__vartype(ptr_SdbIsTagrefFromLocalDB))GetProcAddress(hModule, "SdbIsTagrefFromLocalDB");
   ptr_SdbIsTagrefFromMainDB = (__vartype(ptr_SdbIsTagrefFromMainDB))GetProcAddress(hModule, "SdbIsTagrefFromMainDB");
   ptr_SdbLoadString = (__vartype(ptr_SdbLoadString))GetProcAddress(hModule, "SdbLoadString");
   ptr_SdbMakeIndexKeyFromString = (__vartype(ptr_SdbMakeIndexKeyFromString))GetProcAddress(hModule, "SdbMakeIndexKeyFromString");
   ptr_SdbOpenApphelpDetailsDatabase = (__vartype(ptr_SdbOpenApphelpDetailsDatabase))GetProcAddress(hModule, "SdbOpenApphelpDetailsDatabase");
   ptr_SdbOpenApphelpDetailsDatabaseSP = (__vartype(ptr_SdbOpenApphelpDetailsDatabaseSP))GetProcAddress(hModule, "SdbOpenApphelpDetailsDatabaseSP");
   ptr_SdbOpenApphelpInformation = (__vartype(ptr_SdbOpenApphelpInformation))GetProcAddress(hModule, "SdbOpenApphelpInformation");
   ptr_SdbOpenApphelpInformationByID = (__vartype(ptr_SdbOpenApphelpInformationByID))GetProcAddress(hModule, "SdbOpenApphelpInformationByID");
   ptr_SdbOpenApphelpResourceFile = (__vartype(ptr_SdbOpenApphelpResourceFile))GetProcAddress(hModule, "SdbOpenApphelpResourceFile");
   ptr_SdbOpenDatabase = (__vartype(ptr_SdbOpenDatabase))GetProcAddress(hModule, "SdbOpenDatabase");
   ptr_SdbOpenDbFromGuid = (__vartype(ptr_SdbOpenDbFromGuid))GetProcAddress(hModule, "SdbOpenDbFromGuid");
   ptr_SdbOpenLocalDatabase = (__vartype(ptr_SdbOpenLocalDatabase))GetProcAddress(hModule, "SdbOpenLocalDatabase");
   ptr_SdbPackAppCompatData = (__vartype(ptr_SdbPackAppCompatData))GetProcAddress(hModule, "SdbPackAppCompatData");
   ptr_SdbQueryApphelpInformation = (__vartype(ptr_SdbQueryApphelpInformation))GetProcAddress(hModule, "SdbQueryApphelpInformation");
   ptr_SdbQueryBlockUpgrade = (__vartype(ptr_SdbQueryBlockUpgrade))GetProcAddress(hModule, "SdbQueryBlockUpgrade");
   ptr_SdbQueryContext = (__vartype(ptr_SdbQueryContext))GetProcAddress(hModule, "SdbQueryContext");
   ptr_SdbQueryData = (__vartype(ptr_SdbQueryData))GetProcAddress(hModule, "SdbQueryData");
   ptr_SdbQueryDataEx = (__vartype(ptr_SdbQueryDataEx))GetProcAddress(hModule, "SdbQueryDataEx");
   ptr_SdbQueryDataExTagID = (__vartype(ptr_SdbQueryDataExTagID))GetProcAddress(hModule, "SdbQueryDataExTagID");
   ptr_SdbQueryFlagInfo = (__vartype(ptr_SdbQueryFlagInfo))GetProcAddress(hModule, "SdbQueryFlagInfo");
   ptr_SdbQueryFlagMask = (__vartype(ptr_SdbQueryFlagMask))GetProcAddress(hModule, "SdbQueryFlagMask");
   ptr_SdbQueryName = (__vartype(ptr_SdbQueryName))GetProcAddress(hModule, "SdbQueryName");
   ptr_SdbQueryReinstallUpgrade = (__vartype(ptr_SdbQueryReinstallUpgrade))GetProcAddress(hModule, "SdbQueryReinstallUpgrade");
   ptr_SdbReadApphelpData = (__vartype(ptr_SdbReadApphelpData))GetProcAddress(hModule, "SdbReadApphelpData");
   ptr_SdbReadApphelpDetailsData = (__vartype(ptr_SdbReadApphelpDetailsData))GetProcAddress(hModule, "SdbReadApphelpDetailsData");
   ptr_SdbReadBYTETag = (__vartype(ptr_SdbReadBYTETag))GetProcAddress(hModule, "SdbReadBYTETag");
   ptr_SdbReadBYTETagRef = (__vartype(ptr_SdbReadBYTETagRef))GetProcAddress(hModule, "SdbReadBYTETagRef");
   ptr_SdbReadBinaryTag = (__vartype(ptr_SdbReadBinaryTag))GetProcAddress(hModule, "SdbReadBinaryTag");
   ptr_SdbReadDWORDTag = (__vartype(ptr_SdbReadDWORDTag))GetProcAddress(hModule, "SdbReadDWORDTag");
   ptr_SdbReadDWORDTagRef = (__vartype(ptr_SdbReadDWORDTagRef))GetProcAddress(hModule, "SdbReadDWORDTagRef");
   ptr_SdbReadEntryInformation = (__vartype(ptr_SdbReadEntryInformation))GetProcAddress(hModule, "SdbReadEntryInformation");
   ptr_SdbReadMsiTransformInfo = (__vartype(ptr_SdbReadMsiTransformInfo))GetProcAddress(hModule, "SdbReadMsiTransformInfo");
   ptr_SdbReadPatchBits = (__vartype(ptr_SdbReadPatchBits))GetProcAddress(hModule, "SdbReadPatchBits");
   ptr_SdbReadQWORDTag = (__vartype(ptr_SdbReadQWORDTag))GetProcAddress(hModule, "SdbReadQWORDTag");
   ptr_SdbReadQWORDTagRef = (__vartype(ptr_SdbReadQWORDTagRef))GetProcAddress(hModule, "SdbReadQWORDTagRef");
   ptr_SdbReadStringTag = (__vartype(ptr_SdbReadStringTag))GetProcAddress(hModule, "SdbReadStringTag");
   ptr_SdbReadStringTagRef = (__vartype(ptr_SdbReadStringTagRef))GetProcAddress(hModule, "SdbReadStringTagRef");
   ptr_SdbReadWORDTag = (__vartype(ptr_SdbReadWORDTag))GetProcAddress(hModule, "SdbReadWORDTag");
   ptr_SdbReadWORDTagRef = (__vartype(ptr_SdbReadWORDTagRef))GetProcAddress(hModule, "SdbReadWORDTagRef");
   ptr_SdbRegisterDatabase = (__vartype(ptr_SdbRegisterDatabase))GetProcAddress(hModule, "SdbRegisterDatabase");
   ptr_SdbRegisterDatabaseEx = (__vartype(ptr_SdbRegisterDatabaseEx))GetProcAddress(hModule, "SdbRegisterDatabaseEx");
   ptr_SdbReleaseDatabase = (__vartype(ptr_SdbReleaseDatabase))GetProcAddress(hModule, "SdbReleaseDatabase");
   ptr_SdbReleaseMatchingExe = (__vartype(ptr_SdbReleaseMatchingExe))GetProcAddress(hModule, "SdbReleaseMatchingExe");
   ptr_SdbResolveDatabase = (__vartype(ptr_SdbResolveDatabase))GetProcAddress(hModule, "SdbResolveDatabase");
   ptr_SdbSetApphelpDebugParameters = (__vartype(ptr_SdbSetApphelpDebugParameters))GetProcAddress(hModule, "SdbSetApphelpDebugParameters");
   ptr_SdbSetEntryFlags = (__vartype(ptr_SdbSetEntryFlags))GetProcAddress(hModule, "SdbSetEntryFlags");
   ptr_SdbSetImageType = (__vartype(ptr_SdbSetImageType))GetProcAddress(hModule, "SdbSetImageType");
   ptr_SdbSetPermLayerKeys = (__vartype(ptr_SdbSetPermLayerKeys))GetProcAddress(hModule, "SdbSetPermLayerKeys");
   ptr_SdbShowApphelpDialog = (__vartype(ptr_SdbShowApphelpDialog))GetProcAddress(hModule, "SdbShowApphelpDialog");
   ptr_SdbShowApphelpFromQuery = (__vartype(ptr_SdbShowApphelpFromQuery))GetProcAddress(hModule, "SdbShowApphelpFromQuery");
   ptr_SdbStartIndexing = (__vartype(ptr_SdbStartIndexing))GetProcAddress(hModule, "SdbStartIndexing");
   ptr_SdbStopIndexing = (__vartype(ptr_SdbStopIndexing))GetProcAddress(hModule, "SdbStopIndexing");
   ptr_SdbStringDuplicate = (__vartype(ptr_SdbStringDuplicate))GetProcAddress(hModule, "SdbStringDuplicate");
   ptr_SdbStringReplace = (__vartype(ptr_SdbStringReplace))GetProcAddress(hModule, "SdbStringReplace");
   ptr_SdbStringReplaceArray = (__vartype(ptr_SdbStringReplaceArray))GetProcAddress(hModule, "SdbStringReplaceArray");
   ptr_SdbTagIDToTagRef = (__vartype(ptr_SdbTagIDToTagRef))GetProcAddress(hModule, "SdbTagIDToTagRef");
   ptr_SdbTagRefToTagID = (__vartype(ptr_SdbTagRefToTagID))GetProcAddress(hModule, "SdbTagRefToTagID");
   ptr_SdbTagToString = (__vartype(ptr_SdbTagToString))GetProcAddress(hModule, "SdbTagToString");
   ptr_SdbUnpackAppCompatData = (__vartype(ptr_SdbUnpackAppCompatData))GetProcAddress(hModule, "SdbUnpackAppCompatData");
   ptr_SdbUnregisterDatabase = (__vartype(ptr_SdbUnregisterDatabase))GetProcAddress(hModule, "SdbUnregisterDatabase");
   ptr_SdbWriteBYTETag = (__vartype(ptr_SdbWriteBYTETag))GetProcAddress(hModule, "SdbWriteBYTETag");
   ptr_SdbWriteBinaryTag = (__vartype(ptr_SdbWriteBinaryTag))GetProcAddress(hModule, "SdbWriteBinaryTag");
   ptr_SdbWriteBinaryTagFromFile = (__vartype(ptr_SdbWriteBinaryTagFromFile))GetProcAddress(hModule, "SdbWriteBinaryTagFromFile");
   ptr_SdbWriteDWORDTag = (__vartype(ptr_SdbWriteDWORDTag))GetProcAddress(hModule, "SdbWriteDWORDTag");
   ptr_SdbWriteNULLTag = (__vartype(ptr_SdbWriteNULLTag))GetProcAddress(hModule, "SdbWriteNULLTag");
   ptr_SdbWriteQWORDTag = (__vartype(ptr_SdbWriteQWORDTag))GetProcAddress(hModule, "SdbWriteQWORDTag");
   ptr_SdbWriteStringRefTag = (__vartype(ptr_SdbWriteStringRefTag))GetProcAddress(hModule, "SdbWriteStringRefTag");
   ptr_SdbWriteStringTag = (__vartype(ptr_SdbWriteStringTag))GetProcAddress(hModule, "SdbWriteStringTag");
   ptr_SdbWriteStringTagDirect = (__vartype(ptr_SdbWriteStringTagDirect))GetProcAddress(hModule, "SdbWriteStringTagDirect");
   ptr_SdbWriteWORDTag = (__vartype(ptr_SdbWriteWORDTag))GetProcAddress(hModule, "SdbWriteWORDTag");
   ptr_SetPermLayerState = (__vartype(ptr_SetPermLayerState))GetProcAddress(hModule, "SetPermLayerState");
   ptr_SetPermLayers = (__vartype(ptr_SetPermLayers))GetProcAddress(hModule, "SetPermLayers");
   ptr_ShimDbgPrint = (__vartype(ptr_ShimDbgPrint))GetProcAddress(hModule, "ShimDbgPrint");
   ptr_ShimDumpCache = (__vartype(ptr_ShimDumpCache))GetProcAddress(hModule, "ShimDumpCache");
   ptr_ShimFlushCache = (__vartype(ptr_ShimFlushCache))GetProcAddress(hModule, "ShimFlushCache");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

