#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_GlmfBeginGlsBlock;
void *ptr_GlmfBeginGlsBlock = NULL;
extern void *ptr_GlmfCloseMetaFile;
void *ptr_GlmfCloseMetaFile = NULL;
extern void *ptr_GlmfEndGlsBlock;
void *ptr_GlmfEndGlsBlock = NULL;
extern void *ptr_GlmfEndPlayback;
void *ptr_GlmfEndPlayback = NULL;
extern void *ptr_GlmfInitPlayback;
void *ptr_GlmfInitPlayback = NULL;
extern void *ptr_GlmfPlayGlsRecord;
void *ptr_GlmfPlayGlsRecord = NULL;
extern void *ptr_glAccum;
void *ptr_glAccum = NULL;
extern void *ptr_glAlphaFunc;
void *ptr_glAlphaFunc = NULL;
extern void *ptr_glAreTexturesResident;
void *ptr_glAreTexturesResident = NULL;
extern void *ptr_glArrayElement;
void *ptr_glArrayElement = NULL;
extern void *ptr_glBegin;
void *ptr_glBegin = NULL;
extern void *ptr_glBindTexture;
void *ptr_glBindTexture = NULL;
extern void *ptr_glBitmap;
void *ptr_glBitmap = NULL;
extern void *ptr_glBlendFunc;
void *ptr_glBlendFunc = NULL;
extern void *ptr_glCallList;
void *ptr_glCallList = NULL;
extern void *ptr_glCallLists;
void *ptr_glCallLists = NULL;
extern void *ptr_glClear;
void *ptr_glClear = NULL;
extern void *ptr_glClearAccum;
void *ptr_glClearAccum = NULL;
extern void *ptr_glClearColor;
void *ptr_glClearColor = NULL;
extern void *ptr_glClearDepth;
void *ptr_glClearDepth = NULL;
extern void *ptr_glClearIndex;
void *ptr_glClearIndex = NULL;
extern void *ptr_glClearStencil;
void *ptr_glClearStencil = NULL;
extern void *ptr_glClipPlane;
void *ptr_glClipPlane = NULL;
extern void *ptr_glColor3b;
void *ptr_glColor3b = NULL;
extern void *ptr_glColor3bv;
void *ptr_glColor3bv = NULL;
extern void *ptr_glColor3d;
void *ptr_glColor3d = NULL;
extern void *ptr_glColor3dv;
void *ptr_glColor3dv = NULL;
extern void *ptr_glColor3f;
void *ptr_glColor3f = NULL;
extern void *ptr_glColor3fv;
void *ptr_glColor3fv = NULL;
extern void *ptr_glColor3i;
void *ptr_glColor3i = NULL;
extern void *ptr_glColor3iv;
void *ptr_glColor3iv = NULL;
extern void *ptr_glColor3s;
void *ptr_glColor3s = NULL;
extern void *ptr_glColor3sv;
void *ptr_glColor3sv = NULL;
extern void *ptr_glColor3ub;
void *ptr_glColor3ub = NULL;
extern void *ptr_glColor3ubv;
void *ptr_glColor3ubv = NULL;
extern void *ptr_glColor3ui;
void *ptr_glColor3ui = NULL;
extern void *ptr_glColor3uiv;
void *ptr_glColor3uiv = NULL;
extern void *ptr_glColor3us;
void *ptr_glColor3us = NULL;
extern void *ptr_glColor3usv;
void *ptr_glColor3usv = NULL;
extern void *ptr_glColor4b;
void *ptr_glColor4b = NULL;
extern void *ptr_glColor4bv;
void *ptr_glColor4bv = NULL;
extern void *ptr_glColor4d;
void *ptr_glColor4d = NULL;
extern void *ptr_glColor4dv;
void *ptr_glColor4dv = NULL;
extern void *ptr_glColor4f;
void *ptr_glColor4f = NULL;
extern void *ptr_glColor4fv;
void *ptr_glColor4fv = NULL;
extern void *ptr_glColor4i;
void *ptr_glColor4i = NULL;
extern void *ptr_glColor4iv;
void *ptr_glColor4iv = NULL;
extern void *ptr_glColor4s;
void *ptr_glColor4s = NULL;
extern void *ptr_glColor4sv;
void *ptr_glColor4sv = NULL;
extern void *ptr_glColor4ub;
void *ptr_glColor4ub = NULL;
extern void *ptr_glColor4ubv;
void *ptr_glColor4ubv = NULL;
extern void *ptr_glColor4ui;
void *ptr_glColor4ui = NULL;
extern void *ptr_glColor4uiv;
void *ptr_glColor4uiv = NULL;
extern void *ptr_glColor4us;
void *ptr_glColor4us = NULL;
extern void *ptr_glColor4usv;
void *ptr_glColor4usv = NULL;
extern void *ptr_glColorMask;
void *ptr_glColorMask = NULL;
extern void *ptr_glColorMaterial;
void *ptr_glColorMaterial = NULL;
extern void *ptr_glColorPointer;
void *ptr_glColorPointer = NULL;
extern void *ptr_glCopyPixels;
void *ptr_glCopyPixels = NULL;
extern void *ptr_glCopyTexImage1D;
void *ptr_glCopyTexImage1D = NULL;
extern void *ptr_glCopyTexImage2D;
void *ptr_glCopyTexImage2D = NULL;
extern void *ptr_glCopyTexSubImage1D;
void *ptr_glCopyTexSubImage1D = NULL;
extern void *ptr_glCopyTexSubImage2D;
void *ptr_glCopyTexSubImage2D = NULL;
extern void *ptr_glCullFace;
void *ptr_glCullFace = NULL;
extern void *ptr_glDebugEntry;
void *ptr_glDebugEntry = NULL;
extern void *ptr_glDeleteLists;
void *ptr_glDeleteLists = NULL;
extern void *ptr_glDeleteTextures;
void *ptr_glDeleteTextures = NULL;
extern void *ptr_glDepthFunc;
void *ptr_glDepthFunc = NULL;
extern void *ptr_glDepthMask;
void *ptr_glDepthMask = NULL;
extern void *ptr_glDepthRange;
void *ptr_glDepthRange = NULL;
extern void *ptr_glDisable;
void *ptr_glDisable = NULL;
extern void *ptr_glDisableClientState;
void *ptr_glDisableClientState = NULL;
extern void *ptr_glDrawArrays;
void *ptr_glDrawArrays = NULL;
extern void *ptr_glDrawBuffer;
void *ptr_glDrawBuffer = NULL;
extern void *ptr_glDrawElements;
void *ptr_glDrawElements = NULL;
extern void *ptr_glDrawPixels;
void *ptr_glDrawPixels = NULL;
extern void *ptr_glEdgeFlag;
void *ptr_glEdgeFlag = NULL;
extern void *ptr_glEdgeFlagPointer;
void *ptr_glEdgeFlagPointer = NULL;
extern void *ptr_glEdgeFlagv;
void *ptr_glEdgeFlagv = NULL;
extern void *ptr_glEnable;
void *ptr_glEnable = NULL;
extern void *ptr_glEnableClientState;
void *ptr_glEnableClientState = NULL;
extern void *ptr_glEnd;
void *ptr_glEnd = NULL;
extern void *ptr_glEndList;
void *ptr_glEndList = NULL;
extern void *ptr_glEvalCoord1d;
void *ptr_glEvalCoord1d = NULL;
extern void *ptr_glEvalCoord1dv;
void *ptr_glEvalCoord1dv = NULL;
extern void *ptr_glEvalCoord1f;
void *ptr_glEvalCoord1f = NULL;
extern void *ptr_glEvalCoord1fv;
void *ptr_glEvalCoord1fv = NULL;
extern void *ptr_glEvalCoord2d;
void *ptr_glEvalCoord2d = NULL;
extern void *ptr_glEvalCoord2dv;
void *ptr_glEvalCoord2dv = NULL;
extern void *ptr_glEvalCoord2f;
void *ptr_glEvalCoord2f = NULL;
extern void *ptr_glEvalCoord2fv;
void *ptr_glEvalCoord2fv = NULL;
extern void *ptr_glEvalMesh1;
void *ptr_glEvalMesh1 = NULL;
extern void *ptr_glEvalMesh2;
void *ptr_glEvalMesh2 = NULL;
extern void *ptr_glEvalPoint1;
void *ptr_glEvalPoint1 = NULL;
extern void *ptr_glEvalPoint2;
void *ptr_glEvalPoint2 = NULL;
extern void *ptr_glFeedbackBuffer;
void *ptr_glFeedbackBuffer = NULL;
extern void *ptr_glFinish;
void *ptr_glFinish = NULL;
extern void *ptr_glFlush;
void *ptr_glFlush = NULL;
extern void *ptr_glFogf;
void *ptr_glFogf = NULL;
extern void *ptr_glFogfv;
void *ptr_glFogfv = NULL;
extern void *ptr_glFogi;
void *ptr_glFogi = NULL;
extern void *ptr_glFogiv;
void *ptr_glFogiv = NULL;
extern void *ptr_glFrontFace;
void *ptr_glFrontFace = NULL;
extern void *ptr_glFrustum;
void *ptr_glFrustum = NULL;
extern void *ptr_glGenLists;
void *ptr_glGenLists = NULL;
extern void *ptr_glGenTextures;
void *ptr_glGenTextures = NULL;
extern void *ptr_glGetBooleanv;
void *ptr_glGetBooleanv = NULL;
extern void *ptr_glGetClipPlane;
void *ptr_glGetClipPlane = NULL;
extern void *ptr_glGetDoublev;
void *ptr_glGetDoublev = NULL;
extern void *ptr_glGetError;
void *ptr_glGetError = NULL;
extern void *ptr_glGetFloatv;
void *ptr_glGetFloatv = NULL;
extern void *ptr_glGetIntegerv;
void *ptr_glGetIntegerv = NULL;
extern void *ptr_glGetLightfv;
void *ptr_glGetLightfv = NULL;
extern void *ptr_glGetLightiv;
void *ptr_glGetLightiv = NULL;
extern void *ptr_glGetMapdv;
void *ptr_glGetMapdv = NULL;
extern void *ptr_glGetMapfv;
void *ptr_glGetMapfv = NULL;
extern void *ptr_glGetMapiv;
void *ptr_glGetMapiv = NULL;
extern void *ptr_glGetMaterialfv;
void *ptr_glGetMaterialfv = NULL;
extern void *ptr_glGetMaterialiv;
void *ptr_glGetMaterialiv = NULL;
extern void *ptr_glGetPixelMapfv;
void *ptr_glGetPixelMapfv = NULL;
extern void *ptr_glGetPixelMapuiv;
void *ptr_glGetPixelMapuiv = NULL;
extern void *ptr_glGetPixelMapusv;
void *ptr_glGetPixelMapusv = NULL;
extern void *ptr_glGetPointerv;
void *ptr_glGetPointerv = NULL;
extern void *ptr_glGetPolygonStipple;
void *ptr_glGetPolygonStipple = NULL;
extern void *ptr_glGetString;
void *ptr_glGetString = NULL;
extern void *ptr_glGetTexEnvfv;
void *ptr_glGetTexEnvfv = NULL;
extern void *ptr_glGetTexEnviv;
void *ptr_glGetTexEnviv = NULL;
extern void *ptr_glGetTexGendv;
void *ptr_glGetTexGendv = NULL;
extern void *ptr_glGetTexGenfv;
void *ptr_glGetTexGenfv = NULL;
extern void *ptr_glGetTexGeniv;
void *ptr_glGetTexGeniv = NULL;
extern void *ptr_glGetTexImage;
void *ptr_glGetTexImage = NULL;
extern void *ptr_glGetTexLevelParameterfv;
void *ptr_glGetTexLevelParameterfv = NULL;
extern void *ptr_glGetTexLevelParameteriv;
void *ptr_glGetTexLevelParameteriv = NULL;
extern void *ptr_glGetTexParameterfv;
void *ptr_glGetTexParameterfv = NULL;
extern void *ptr_glGetTexParameteriv;
void *ptr_glGetTexParameteriv = NULL;
extern void *ptr_glHint;
void *ptr_glHint = NULL;
extern void *ptr_glIndexMask;
void *ptr_glIndexMask = NULL;
extern void *ptr_glIndexPointer;
void *ptr_glIndexPointer = NULL;
extern void *ptr_glIndexd;
void *ptr_glIndexd = NULL;
extern void *ptr_glIndexdv;
void *ptr_glIndexdv = NULL;
extern void *ptr_glIndexf;
void *ptr_glIndexf = NULL;
extern void *ptr_glIndexfv;
void *ptr_glIndexfv = NULL;
extern void *ptr_glIndexi;
void *ptr_glIndexi = NULL;
extern void *ptr_glIndexiv;
void *ptr_glIndexiv = NULL;
extern void *ptr_glIndexs;
void *ptr_glIndexs = NULL;
extern void *ptr_glIndexsv;
void *ptr_glIndexsv = NULL;
extern void *ptr_glIndexub;
void *ptr_glIndexub = NULL;
extern void *ptr_glIndexubv;
void *ptr_glIndexubv = NULL;
extern void *ptr_glInitNames;
void *ptr_glInitNames = NULL;
extern void *ptr_glInterleavedArrays;
void *ptr_glInterleavedArrays = NULL;
extern void *ptr_glIsEnabled;
void *ptr_glIsEnabled = NULL;
extern void *ptr_glIsList;
void *ptr_glIsList = NULL;
extern void *ptr_glIsTexture;
void *ptr_glIsTexture = NULL;
extern void *ptr_glLightModelf;
void *ptr_glLightModelf = NULL;
extern void *ptr_glLightModelfv;
void *ptr_glLightModelfv = NULL;
extern void *ptr_glLightModeli;
void *ptr_glLightModeli = NULL;
extern void *ptr_glLightModeliv;
void *ptr_glLightModeliv = NULL;
extern void *ptr_glLightf;
void *ptr_glLightf = NULL;
extern void *ptr_glLightfv;
void *ptr_glLightfv = NULL;
extern void *ptr_glLighti;
void *ptr_glLighti = NULL;
extern void *ptr_glLightiv;
void *ptr_glLightiv = NULL;
extern void *ptr_glLineStipple;
void *ptr_glLineStipple = NULL;
extern void *ptr_glLineWidth;
void *ptr_glLineWidth = NULL;
extern void *ptr_glListBase;
void *ptr_glListBase = NULL;
extern void *ptr_glLoadIdentity;
void *ptr_glLoadIdentity = NULL;
extern void *ptr_glLoadMatrixd;
void *ptr_glLoadMatrixd = NULL;
extern void *ptr_glLoadMatrixf;
void *ptr_glLoadMatrixf = NULL;
extern void *ptr_glLoadName;
void *ptr_glLoadName = NULL;
extern void *ptr_glLogicOp;
void *ptr_glLogicOp = NULL;
extern void *ptr_glMap1d;
void *ptr_glMap1d = NULL;
extern void *ptr_glMap1f;
void *ptr_glMap1f = NULL;
extern void *ptr_glMap2d;
void *ptr_glMap2d = NULL;
extern void *ptr_glMap2f;
void *ptr_glMap2f = NULL;
extern void *ptr_glMapGrid1d;
void *ptr_glMapGrid1d = NULL;
extern void *ptr_glMapGrid1f;
void *ptr_glMapGrid1f = NULL;
extern void *ptr_glMapGrid2d;
void *ptr_glMapGrid2d = NULL;
extern void *ptr_glMapGrid2f;
void *ptr_glMapGrid2f = NULL;
extern void *ptr_glMaterialf;
void *ptr_glMaterialf = NULL;
extern void *ptr_glMaterialfv;
void *ptr_glMaterialfv = NULL;
extern void *ptr_glMateriali;
void *ptr_glMateriali = NULL;
extern void *ptr_glMaterialiv;
void *ptr_glMaterialiv = NULL;
extern void *ptr_glMatrixMode;
void *ptr_glMatrixMode = NULL;
extern void *ptr_glMultMatrixd;
void *ptr_glMultMatrixd = NULL;
extern void *ptr_glMultMatrixf;
void *ptr_glMultMatrixf = NULL;
extern void *ptr_glNewList;
void *ptr_glNewList = NULL;
extern void *ptr_glNormal3b;
void *ptr_glNormal3b = NULL;
extern void *ptr_glNormal3bv;
void *ptr_glNormal3bv = NULL;
extern void *ptr_glNormal3d;
void *ptr_glNormal3d = NULL;
extern void *ptr_glNormal3dv;
void *ptr_glNormal3dv = NULL;
extern void *ptr_glNormal3f;
void *ptr_glNormal3f = NULL;
extern void *ptr_glNormal3fv;
void *ptr_glNormal3fv = NULL;
extern void *ptr_glNormal3i;
void *ptr_glNormal3i = NULL;
extern void *ptr_glNormal3iv;
void *ptr_glNormal3iv = NULL;
extern void *ptr_glNormal3s;
void *ptr_glNormal3s = NULL;
extern void *ptr_glNormal3sv;
void *ptr_glNormal3sv = NULL;
extern void *ptr_glNormalPointer;
void *ptr_glNormalPointer = NULL;
extern void *ptr_glOrtho;
void *ptr_glOrtho = NULL;
extern void *ptr_glPassThrough;
void *ptr_glPassThrough = NULL;
extern void *ptr_glPixelMapfv;
void *ptr_glPixelMapfv = NULL;
extern void *ptr_glPixelMapuiv;
void *ptr_glPixelMapuiv = NULL;
extern void *ptr_glPixelMapusv;
void *ptr_glPixelMapusv = NULL;
extern void *ptr_glPixelStoref;
void *ptr_glPixelStoref = NULL;
extern void *ptr_glPixelStorei;
void *ptr_glPixelStorei = NULL;
extern void *ptr_glPixelTransferf;
void *ptr_glPixelTransferf = NULL;
extern void *ptr_glPixelTransferi;
void *ptr_glPixelTransferi = NULL;
extern void *ptr_glPixelZoom;
void *ptr_glPixelZoom = NULL;
extern void *ptr_glPointSize;
void *ptr_glPointSize = NULL;
extern void *ptr_glPolygonMode;
void *ptr_glPolygonMode = NULL;
extern void *ptr_glPolygonOffset;
void *ptr_glPolygonOffset = NULL;
extern void *ptr_glPolygonStipple;
void *ptr_glPolygonStipple = NULL;
extern void *ptr_glPopAttrib;
void *ptr_glPopAttrib = NULL;
extern void *ptr_glPopClientAttrib;
void *ptr_glPopClientAttrib = NULL;
extern void *ptr_glPopMatrix;
void *ptr_glPopMatrix = NULL;
extern void *ptr_glPopName;
void *ptr_glPopName = NULL;
extern void *ptr_glPrioritizeTextures;
void *ptr_glPrioritizeTextures = NULL;
extern void *ptr_glPushAttrib;
void *ptr_glPushAttrib = NULL;
extern void *ptr_glPushClientAttrib;
void *ptr_glPushClientAttrib = NULL;
extern void *ptr_glPushMatrix;
void *ptr_glPushMatrix = NULL;
extern void *ptr_glPushName;
void *ptr_glPushName = NULL;
extern void *ptr_glRasterPos2d;
void *ptr_glRasterPos2d = NULL;
extern void *ptr_glRasterPos2dv;
void *ptr_glRasterPos2dv = NULL;
extern void *ptr_glRasterPos2f;
void *ptr_glRasterPos2f = NULL;
extern void *ptr_glRasterPos2fv;
void *ptr_glRasterPos2fv = NULL;
extern void *ptr_glRasterPos2i;
void *ptr_glRasterPos2i = NULL;
extern void *ptr_glRasterPos2iv;
void *ptr_glRasterPos2iv = NULL;
extern void *ptr_glRasterPos2s;
void *ptr_glRasterPos2s = NULL;
extern void *ptr_glRasterPos2sv;
void *ptr_glRasterPos2sv = NULL;
extern void *ptr_glRasterPos3d;
void *ptr_glRasterPos3d = NULL;
extern void *ptr_glRasterPos3dv;
void *ptr_glRasterPos3dv = NULL;
extern void *ptr_glRasterPos3f;
void *ptr_glRasterPos3f = NULL;
extern void *ptr_glRasterPos3fv;
void *ptr_glRasterPos3fv = NULL;
extern void *ptr_glRasterPos3i;
void *ptr_glRasterPos3i = NULL;
extern void *ptr_glRasterPos3iv;
void *ptr_glRasterPos3iv = NULL;
extern void *ptr_glRasterPos3s;
void *ptr_glRasterPos3s = NULL;
extern void *ptr_glRasterPos3sv;
void *ptr_glRasterPos3sv = NULL;
extern void *ptr_glRasterPos4d;
void *ptr_glRasterPos4d = NULL;
extern void *ptr_glRasterPos4dv;
void *ptr_glRasterPos4dv = NULL;
extern void *ptr_glRasterPos4f;
void *ptr_glRasterPos4f = NULL;
extern void *ptr_glRasterPos4fv;
void *ptr_glRasterPos4fv = NULL;
extern void *ptr_glRasterPos4i;
void *ptr_glRasterPos4i = NULL;
extern void *ptr_glRasterPos4iv;
void *ptr_glRasterPos4iv = NULL;
extern void *ptr_glRasterPos4s;
void *ptr_glRasterPos4s = NULL;
extern void *ptr_glRasterPos4sv;
void *ptr_glRasterPos4sv = NULL;
extern void *ptr_glReadBuffer;
void *ptr_glReadBuffer = NULL;
extern void *ptr_glReadPixels;
void *ptr_glReadPixels = NULL;
extern void *ptr_glRectd;
void *ptr_glRectd = NULL;
extern void *ptr_glRectdv;
void *ptr_glRectdv = NULL;
extern void *ptr_glRectf;
void *ptr_glRectf = NULL;
extern void *ptr_glRectfv;
void *ptr_glRectfv = NULL;
extern void *ptr_glRecti;
void *ptr_glRecti = NULL;
extern void *ptr_glRectiv;
void *ptr_glRectiv = NULL;
extern void *ptr_glRects;
void *ptr_glRects = NULL;
extern void *ptr_glRectsv;
void *ptr_glRectsv = NULL;
extern void *ptr_glRenderMode;
void *ptr_glRenderMode = NULL;
extern void *ptr_glRotated;
void *ptr_glRotated = NULL;
extern void *ptr_glRotatef;
void *ptr_glRotatef = NULL;
extern void *ptr_glScaled;
void *ptr_glScaled = NULL;
extern void *ptr_glScalef;
void *ptr_glScalef = NULL;
extern void *ptr_glScissor;
void *ptr_glScissor = NULL;
extern void *ptr_glSelectBuffer;
void *ptr_glSelectBuffer = NULL;
extern void *ptr_glShadeModel;
void *ptr_glShadeModel = NULL;
extern void *ptr_glStencilFunc;
void *ptr_glStencilFunc = NULL;
extern void *ptr_glStencilMask;
void *ptr_glStencilMask = NULL;
extern void *ptr_glStencilOp;
void *ptr_glStencilOp = NULL;
extern void *ptr_glTexCoord1d;
void *ptr_glTexCoord1d = NULL;
extern void *ptr_glTexCoord1dv;
void *ptr_glTexCoord1dv = NULL;
extern void *ptr_glTexCoord1f;
void *ptr_glTexCoord1f = NULL;
extern void *ptr_glTexCoord1fv;
void *ptr_glTexCoord1fv = NULL;
extern void *ptr_glTexCoord1i;
void *ptr_glTexCoord1i = NULL;
extern void *ptr_glTexCoord1iv;
void *ptr_glTexCoord1iv = NULL;
extern void *ptr_glTexCoord1s;
void *ptr_glTexCoord1s = NULL;
extern void *ptr_glTexCoord1sv;
void *ptr_glTexCoord1sv = NULL;
extern void *ptr_glTexCoord2d;
void *ptr_glTexCoord2d = NULL;
extern void *ptr_glTexCoord2dv;
void *ptr_glTexCoord2dv = NULL;
extern void *ptr_glTexCoord2f;
void *ptr_glTexCoord2f = NULL;
extern void *ptr_glTexCoord2fv;
void *ptr_glTexCoord2fv = NULL;
extern void *ptr_glTexCoord2i;
void *ptr_glTexCoord2i = NULL;
extern void *ptr_glTexCoord2iv;
void *ptr_glTexCoord2iv = NULL;
extern void *ptr_glTexCoord2s;
void *ptr_glTexCoord2s = NULL;
extern void *ptr_glTexCoord2sv;
void *ptr_glTexCoord2sv = NULL;
extern void *ptr_glTexCoord3d;
void *ptr_glTexCoord3d = NULL;
extern void *ptr_glTexCoord3dv;
void *ptr_glTexCoord3dv = NULL;
extern void *ptr_glTexCoord3f;
void *ptr_glTexCoord3f = NULL;
extern void *ptr_glTexCoord3fv;
void *ptr_glTexCoord3fv = NULL;
extern void *ptr_glTexCoord3i;
void *ptr_glTexCoord3i = NULL;
extern void *ptr_glTexCoord3iv;
void *ptr_glTexCoord3iv = NULL;
extern void *ptr_glTexCoord3s;
void *ptr_glTexCoord3s = NULL;
extern void *ptr_glTexCoord3sv;
void *ptr_glTexCoord3sv = NULL;
extern void *ptr_glTexCoord4d;
void *ptr_glTexCoord4d = NULL;
extern void *ptr_glTexCoord4dv;
void *ptr_glTexCoord4dv = NULL;
extern void *ptr_glTexCoord4f;
void *ptr_glTexCoord4f = NULL;
extern void *ptr_glTexCoord4fv;
void *ptr_glTexCoord4fv = NULL;
extern void *ptr_glTexCoord4i;
void *ptr_glTexCoord4i = NULL;
extern void *ptr_glTexCoord4iv;
void *ptr_glTexCoord4iv = NULL;
extern void *ptr_glTexCoord4s;
void *ptr_glTexCoord4s = NULL;
extern void *ptr_glTexCoord4sv;
void *ptr_glTexCoord4sv = NULL;
extern void *ptr_glTexCoordPointer;
void *ptr_glTexCoordPointer = NULL;
extern void *ptr_glTexEnvf;
void *ptr_glTexEnvf = NULL;
extern void *ptr_glTexEnvfv;
void *ptr_glTexEnvfv = NULL;
extern void *ptr_glTexEnvi;
void *ptr_glTexEnvi = NULL;
extern void *ptr_glTexEnviv;
void *ptr_glTexEnviv = NULL;
extern void *ptr_glTexGend;
void *ptr_glTexGend = NULL;
extern void *ptr_glTexGendv;
void *ptr_glTexGendv = NULL;
extern void *ptr_glTexGenf;
void *ptr_glTexGenf = NULL;
extern void *ptr_glTexGenfv;
void *ptr_glTexGenfv = NULL;
extern void *ptr_glTexGeni;
void *ptr_glTexGeni = NULL;
extern void *ptr_glTexGeniv;
void *ptr_glTexGeniv = NULL;
extern void *ptr_glTexImage1D;
void *ptr_glTexImage1D = NULL;
extern void *ptr_glTexImage2D;
void *ptr_glTexImage2D = NULL;
extern void *ptr_glTexParameterf;
void *ptr_glTexParameterf = NULL;
extern void *ptr_glTexParameterfv;
void *ptr_glTexParameterfv = NULL;
extern void *ptr_glTexParameteri;
void *ptr_glTexParameteri = NULL;
extern void *ptr_glTexParameteriv;
void *ptr_glTexParameteriv = NULL;
extern void *ptr_glTexSubImage1D;
void *ptr_glTexSubImage1D = NULL;
extern void *ptr_glTexSubImage2D;
void *ptr_glTexSubImage2D = NULL;
extern void *ptr_glTranslated;
void *ptr_glTranslated = NULL;
extern void *ptr_glTranslatef;
void *ptr_glTranslatef = NULL;
extern void *ptr_glVertex2d;
void *ptr_glVertex2d = NULL;
extern void *ptr_glVertex2dv;
void *ptr_glVertex2dv = NULL;
extern void *ptr_glVertex2f;
void *ptr_glVertex2f = NULL;
extern void *ptr_glVertex2fv;
void *ptr_glVertex2fv = NULL;
extern void *ptr_glVertex2i;
void *ptr_glVertex2i = NULL;
extern void *ptr_glVertex2iv;
void *ptr_glVertex2iv = NULL;
extern void *ptr_glVertex2s;
void *ptr_glVertex2s = NULL;
extern void *ptr_glVertex2sv;
void *ptr_glVertex2sv = NULL;
extern void *ptr_glVertex3d;
void *ptr_glVertex3d = NULL;
extern void *ptr_glVertex3dv;
void *ptr_glVertex3dv = NULL;
extern void *ptr_glVertex3f;
void *ptr_glVertex3f = NULL;
extern void *ptr_glVertex3fv;
void *ptr_glVertex3fv = NULL;
extern void *ptr_glVertex3i;
void *ptr_glVertex3i = NULL;
extern void *ptr_glVertex3iv;
void *ptr_glVertex3iv = NULL;
extern void *ptr_glVertex3s;
void *ptr_glVertex3s = NULL;
extern void *ptr_glVertex3sv;
void *ptr_glVertex3sv = NULL;
extern void *ptr_glVertex4d;
void *ptr_glVertex4d = NULL;
extern void *ptr_glVertex4dv;
void *ptr_glVertex4dv = NULL;
extern void *ptr_glVertex4f;
void *ptr_glVertex4f = NULL;
extern void *ptr_glVertex4fv;
void *ptr_glVertex4fv = NULL;
extern void *ptr_glVertex4i;
void *ptr_glVertex4i = NULL;
extern void *ptr_glVertex4iv;
void *ptr_glVertex4iv = NULL;
extern void *ptr_glVertex4s;
void *ptr_glVertex4s = NULL;
extern void *ptr_glVertex4sv;
void *ptr_glVertex4sv = NULL;
extern void *ptr_glVertexPointer;
void *ptr_glVertexPointer = NULL;
extern void *ptr_glViewport;
void *ptr_glViewport = NULL;
extern void *ptr_wglChoosePixelFormat;
void *ptr_wglChoosePixelFormat = NULL;
extern void *ptr_wglCopyContext;
void *ptr_wglCopyContext = NULL;
extern void *ptr_wglCreateContext;
void *ptr_wglCreateContext = NULL;
extern void *ptr_wglCreateLayerContext;
void *ptr_wglCreateLayerContext = NULL;
extern void *ptr_wglDeleteContext;
void *ptr_wglDeleteContext = NULL;
extern void *ptr_wglDescribeLayerPlane;
void *ptr_wglDescribeLayerPlane = NULL;
extern void *ptr_wglDescribePixelFormat;
void *ptr_wglDescribePixelFormat = NULL;
extern void *ptr_wglGetCurrentContext;
void *ptr_wglGetCurrentContext = NULL;
extern void *ptr_wglGetCurrentDC;
void *ptr_wglGetCurrentDC = NULL;
extern void *ptr_wglGetDefaultProcAddress;
void *ptr_wglGetDefaultProcAddress = NULL;
extern void *ptr_wglGetLayerPaletteEntries;
void *ptr_wglGetLayerPaletteEntries = NULL;
extern void *ptr_wglGetPixelFormat;
void *ptr_wglGetPixelFormat = NULL;
extern void *ptr_wglGetProcAddress;
void *ptr_wglGetProcAddress = NULL;
extern void *ptr_wglMakeCurrent;
void *ptr_wglMakeCurrent = NULL;
extern void *ptr_wglRealizeLayerPalette;
void *ptr_wglRealizeLayerPalette = NULL;
extern void *ptr_wglSetLayerPaletteEntries;
void *ptr_wglSetLayerPaletteEntries = NULL;
extern void *ptr_wglSetPixelFormat;
void *ptr_wglSetPixelFormat = NULL;
extern void *ptr_wglShareLists;
void *ptr_wglShareLists = NULL;
extern void *ptr_wglSwapBuffers;
void *ptr_wglSwapBuffers = NULL;
extern void *ptr_wglSwapLayerBuffers;
void *ptr_wglSwapLayerBuffers = NULL;
extern void *ptr_wglSwapMultipleBuffers;
void *ptr_wglSwapMultipleBuffers = NULL;
extern void *ptr_wglUseFontBitmapsA;
void *ptr_wglUseFontBitmapsA = NULL;
extern void *ptr_wglUseFontBitmapsW;
void *ptr_wglUseFontBitmapsW = NULL;
extern void *ptr_wglUseFontOutlinesA;
void *ptr_wglUseFontOutlinesA = NULL;
extern void *ptr_wglUseFontOutlinesW;
void *ptr_wglUseFontOutlinesW = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\opengl32.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_GlmfBeginGlsBlock = (__vartype(ptr_GlmfBeginGlsBlock))GetProcAddress(hModule, "GlmfBeginGlsBlock");
   ptr_GlmfCloseMetaFile = (__vartype(ptr_GlmfCloseMetaFile))GetProcAddress(hModule, "GlmfCloseMetaFile");
   ptr_GlmfEndGlsBlock = (__vartype(ptr_GlmfEndGlsBlock))GetProcAddress(hModule, "GlmfEndGlsBlock");
   ptr_GlmfEndPlayback = (__vartype(ptr_GlmfEndPlayback))GetProcAddress(hModule, "GlmfEndPlayback");
   ptr_GlmfInitPlayback = (__vartype(ptr_GlmfInitPlayback))GetProcAddress(hModule, "GlmfInitPlayback");
   ptr_GlmfPlayGlsRecord = (__vartype(ptr_GlmfPlayGlsRecord))GetProcAddress(hModule, "GlmfPlayGlsRecord");
   ptr_glAccum = (__vartype(ptr_glAccum))GetProcAddress(hModule, "glAccum");
   ptr_glAlphaFunc = (__vartype(ptr_glAlphaFunc))GetProcAddress(hModule, "glAlphaFunc");
   ptr_glAreTexturesResident = (__vartype(ptr_glAreTexturesResident))GetProcAddress(hModule, "glAreTexturesResident");
   ptr_glArrayElement = (__vartype(ptr_glArrayElement))GetProcAddress(hModule, "glArrayElement");
   ptr_glBegin = (__vartype(ptr_glBegin))GetProcAddress(hModule, "glBegin");
   ptr_glBindTexture = (__vartype(ptr_glBindTexture))GetProcAddress(hModule, "glBindTexture");
   ptr_glBitmap = (__vartype(ptr_glBitmap))GetProcAddress(hModule, "glBitmap");
   ptr_glBlendFunc = (__vartype(ptr_glBlendFunc))GetProcAddress(hModule, "glBlendFunc");
   ptr_glCallList = (__vartype(ptr_glCallList))GetProcAddress(hModule, "glCallList");
   ptr_glCallLists = (__vartype(ptr_glCallLists))GetProcAddress(hModule, "glCallLists");
   ptr_glClear = (__vartype(ptr_glClear))GetProcAddress(hModule, "glClear");
   ptr_glClearAccum = (__vartype(ptr_glClearAccum))GetProcAddress(hModule, "glClearAccum");
   ptr_glClearColor = (__vartype(ptr_glClearColor))GetProcAddress(hModule, "glClearColor");
   ptr_glClearDepth = (__vartype(ptr_glClearDepth))GetProcAddress(hModule, "glClearDepth");
   ptr_glClearIndex = (__vartype(ptr_glClearIndex))GetProcAddress(hModule, "glClearIndex");
   ptr_glClearStencil = (__vartype(ptr_glClearStencil))GetProcAddress(hModule, "glClearStencil");
   ptr_glClipPlane = (__vartype(ptr_glClipPlane))GetProcAddress(hModule, "glClipPlane");
   ptr_glColor3b = (__vartype(ptr_glColor3b))GetProcAddress(hModule, "glColor3b");
   ptr_glColor3bv = (__vartype(ptr_glColor3bv))GetProcAddress(hModule, "glColor3bv");
   ptr_glColor3d = (__vartype(ptr_glColor3d))GetProcAddress(hModule, "glColor3d");
   ptr_glColor3dv = (__vartype(ptr_glColor3dv))GetProcAddress(hModule, "glColor3dv");
   ptr_glColor3f = (__vartype(ptr_glColor3f))GetProcAddress(hModule, "glColor3f");
   ptr_glColor3fv = (__vartype(ptr_glColor3fv))GetProcAddress(hModule, "glColor3fv");
   ptr_glColor3i = (__vartype(ptr_glColor3i))GetProcAddress(hModule, "glColor3i");
   ptr_glColor3iv = (__vartype(ptr_glColor3iv))GetProcAddress(hModule, "glColor3iv");
   ptr_glColor3s = (__vartype(ptr_glColor3s))GetProcAddress(hModule, "glColor3s");
   ptr_glColor3sv = (__vartype(ptr_glColor3sv))GetProcAddress(hModule, "glColor3sv");
   ptr_glColor3ub = (__vartype(ptr_glColor3ub))GetProcAddress(hModule, "glColor3ub");
   ptr_glColor3ubv = (__vartype(ptr_glColor3ubv))GetProcAddress(hModule, "glColor3ubv");
   ptr_glColor3ui = (__vartype(ptr_glColor3ui))GetProcAddress(hModule, "glColor3ui");
   ptr_glColor3uiv = (__vartype(ptr_glColor3uiv))GetProcAddress(hModule, "glColor3uiv");
   ptr_glColor3us = (__vartype(ptr_glColor3us))GetProcAddress(hModule, "glColor3us");
   ptr_glColor3usv = (__vartype(ptr_glColor3usv))GetProcAddress(hModule, "glColor3usv");
   ptr_glColor4b = (__vartype(ptr_glColor4b))GetProcAddress(hModule, "glColor4b");
   ptr_glColor4bv = (__vartype(ptr_glColor4bv))GetProcAddress(hModule, "glColor4bv");
   ptr_glColor4d = (__vartype(ptr_glColor4d))GetProcAddress(hModule, "glColor4d");
   ptr_glColor4dv = (__vartype(ptr_glColor4dv))GetProcAddress(hModule, "glColor4dv");
   ptr_glColor4f = (__vartype(ptr_glColor4f))GetProcAddress(hModule, "glColor4f");
   ptr_glColor4fv = (__vartype(ptr_glColor4fv))GetProcAddress(hModule, "glColor4fv");
   ptr_glColor4i = (__vartype(ptr_glColor4i))GetProcAddress(hModule, "glColor4i");
   ptr_glColor4iv = (__vartype(ptr_glColor4iv))GetProcAddress(hModule, "glColor4iv");
   ptr_glColor4s = (__vartype(ptr_glColor4s))GetProcAddress(hModule, "glColor4s");
   ptr_glColor4sv = (__vartype(ptr_glColor4sv))GetProcAddress(hModule, "glColor4sv");
   ptr_glColor4ub = (__vartype(ptr_glColor4ub))GetProcAddress(hModule, "glColor4ub");
   ptr_glColor4ubv = (__vartype(ptr_glColor4ubv))GetProcAddress(hModule, "glColor4ubv");
   ptr_glColor4ui = (__vartype(ptr_glColor4ui))GetProcAddress(hModule, "glColor4ui");
   ptr_glColor4uiv = (__vartype(ptr_glColor4uiv))GetProcAddress(hModule, "glColor4uiv");
   ptr_glColor4us = (__vartype(ptr_glColor4us))GetProcAddress(hModule, "glColor4us");
   ptr_glColor4usv = (__vartype(ptr_glColor4usv))GetProcAddress(hModule, "glColor4usv");
   ptr_glColorMask = (__vartype(ptr_glColorMask))GetProcAddress(hModule, "glColorMask");
   ptr_glColorMaterial = (__vartype(ptr_glColorMaterial))GetProcAddress(hModule, "glColorMaterial");
   ptr_glColorPointer = (__vartype(ptr_glColorPointer))GetProcAddress(hModule, "glColorPointer");
   ptr_glCopyPixels = (__vartype(ptr_glCopyPixels))GetProcAddress(hModule, "glCopyPixels");
   ptr_glCopyTexImage1D = (__vartype(ptr_glCopyTexImage1D))GetProcAddress(hModule, "glCopyTexImage1D");
   ptr_glCopyTexImage2D = (__vartype(ptr_glCopyTexImage2D))GetProcAddress(hModule, "glCopyTexImage2D");
   ptr_glCopyTexSubImage1D = (__vartype(ptr_glCopyTexSubImage1D))GetProcAddress(hModule, "glCopyTexSubImage1D");
   ptr_glCopyTexSubImage2D = (__vartype(ptr_glCopyTexSubImage2D))GetProcAddress(hModule, "glCopyTexSubImage2D");
   ptr_glCullFace = (__vartype(ptr_glCullFace))GetProcAddress(hModule, "glCullFace");
   ptr_glDebugEntry = (__vartype(ptr_glDebugEntry))GetProcAddress(hModule, "glDebugEntry");
   ptr_glDeleteLists = (__vartype(ptr_glDeleteLists))GetProcAddress(hModule, "glDeleteLists");
   ptr_glDeleteTextures = (__vartype(ptr_glDeleteTextures))GetProcAddress(hModule, "glDeleteTextures");
   ptr_glDepthFunc = (__vartype(ptr_glDepthFunc))GetProcAddress(hModule, "glDepthFunc");
   ptr_glDepthMask = (__vartype(ptr_glDepthMask))GetProcAddress(hModule, "glDepthMask");
   ptr_glDepthRange = (__vartype(ptr_glDepthRange))GetProcAddress(hModule, "glDepthRange");
   ptr_glDisable = (__vartype(ptr_glDisable))GetProcAddress(hModule, "glDisable");
   ptr_glDisableClientState = (__vartype(ptr_glDisableClientState))GetProcAddress(hModule, "glDisableClientState");
   ptr_glDrawArrays = (__vartype(ptr_glDrawArrays))GetProcAddress(hModule, "glDrawArrays");
   ptr_glDrawBuffer = (__vartype(ptr_glDrawBuffer))GetProcAddress(hModule, "glDrawBuffer");
   ptr_glDrawElements = (__vartype(ptr_glDrawElements))GetProcAddress(hModule, "glDrawElements");
   ptr_glDrawPixels = (__vartype(ptr_glDrawPixels))GetProcAddress(hModule, "glDrawPixels");
   ptr_glEdgeFlag = (__vartype(ptr_glEdgeFlag))GetProcAddress(hModule, "glEdgeFlag");
   ptr_glEdgeFlagPointer = (__vartype(ptr_glEdgeFlagPointer))GetProcAddress(hModule, "glEdgeFlagPointer");
   ptr_glEdgeFlagv = (__vartype(ptr_glEdgeFlagv))GetProcAddress(hModule, "glEdgeFlagv");
   ptr_glEnable = (__vartype(ptr_glEnable))GetProcAddress(hModule, "glEnable");
   ptr_glEnableClientState = (__vartype(ptr_glEnableClientState))GetProcAddress(hModule, "glEnableClientState");
   ptr_glEnd = (__vartype(ptr_glEnd))GetProcAddress(hModule, "glEnd");
   ptr_glEndList = (__vartype(ptr_glEndList))GetProcAddress(hModule, "glEndList");
   ptr_glEvalCoord1d = (__vartype(ptr_glEvalCoord1d))GetProcAddress(hModule, "glEvalCoord1d");
   ptr_glEvalCoord1dv = (__vartype(ptr_glEvalCoord1dv))GetProcAddress(hModule, "glEvalCoord1dv");
   ptr_glEvalCoord1f = (__vartype(ptr_glEvalCoord1f))GetProcAddress(hModule, "glEvalCoord1f");
   ptr_glEvalCoord1fv = (__vartype(ptr_glEvalCoord1fv))GetProcAddress(hModule, "glEvalCoord1fv");
   ptr_glEvalCoord2d = (__vartype(ptr_glEvalCoord2d))GetProcAddress(hModule, "glEvalCoord2d");
   ptr_glEvalCoord2dv = (__vartype(ptr_glEvalCoord2dv))GetProcAddress(hModule, "glEvalCoord2dv");
   ptr_glEvalCoord2f = (__vartype(ptr_glEvalCoord2f))GetProcAddress(hModule, "glEvalCoord2f");
   ptr_glEvalCoord2fv = (__vartype(ptr_glEvalCoord2fv))GetProcAddress(hModule, "glEvalCoord2fv");
   ptr_glEvalMesh1 = (__vartype(ptr_glEvalMesh1))GetProcAddress(hModule, "glEvalMesh1");
   ptr_glEvalMesh2 = (__vartype(ptr_glEvalMesh2))GetProcAddress(hModule, "glEvalMesh2");
   ptr_glEvalPoint1 = (__vartype(ptr_glEvalPoint1))GetProcAddress(hModule, "glEvalPoint1");
   ptr_glEvalPoint2 = (__vartype(ptr_glEvalPoint2))GetProcAddress(hModule, "glEvalPoint2");
   ptr_glFeedbackBuffer = (__vartype(ptr_glFeedbackBuffer))GetProcAddress(hModule, "glFeedbackBuffer");
   ptr_glFinish = (__vartype(ptr_glFinish))GetProcAddress(hModule, "glFinish");
   ptr_glFlush = (__vartype(ptr_glFlush))GetProcAddress(hModule, "glFlush");
   ptr_glFogf = (__vartype(ptr_glFogf))GetProcAddress(hModule, "glFogf");
   ptr_glFogfv = (__vartype(ptr_glFogfv))GetProcAddress(hModule, "glFogfv");
   ptr_glFogi = (__vartype(ptr_glFogi))GetProcAddress(hModule, "glFogi");
   ptr_glFogiv = (__vartype(ptr_glFogiv))GetProcAddress(hModule, "glFogiv");
   ptr_glFrontFace = (__vartype(ptr_glFrontFace))GetProcAddress(hModule, "glFrontFace");
   ptr_glFrustum = (__vartype(ptr_glFrustum))GetProcAddress(hModule, "glFrustum");
   ptr_glGenLists = (__vartype(ptr_glGenLists))GetProcAddress(hModule, "glGenLists");
   ptr_glGenTextures = (__vartype(ptr_glGenTextures))GetProcAddress(hModule, "glGenTextures");
   ptr_glGetBooleanv = (__vartype(ptr_glGetBooleanv))GetProcAddress(hModule, "glGetBooleanv");
   ptr_glGetClipPlane = (__vartype(ptr_glGetClipPlane))GetProcAddress(hModule, "glGetClipPlane");
   ptr_glGetDoublev = (__vartype(ptr_glGetDoublev))GetProcAddress(hModule, "glGetDoublev");
   ptr_glGetError = (__vartype(ptr_glGetError))GetProcAddress(hModule, "glGetError");
   ptr_glGetFloatv = (__vartype(ptr_glGetFloatv))GetProcAddress(hModule, "glGetFloatv");
   ptr_glGetIntegerv = (__vartype(ptr_glGetIntegerv))GetProcAddress(hModule, "glGetIntegerv");
   ptr_glGetLightfv = (__vartype(ptr_glGetLightfv))GetProcAddress(hModule, "glGetLightfv");
   ptr_glGetLightiv = (__vartype(ptr_glGetLightiv))GetProcAddress(hModule, "glGetLightiv");
   ptr_glGetMapdv = (__vartype(ptr_glGetMapdv))GetProcAddress(hModule, "glGetMapdv");
   ptr_glGetMapfv = (__vartype(ptr_glGetMapfv))GetProcAddress(hModule, "glGetMapfv");
   ptr_glGetMapiv = (__vartype(ptr_glGetMapiv))GetProcAddress(hModule, "glGetMapiv");
   ptr_glGetMaterialfv = (__vartype(ptr_glGetMaterialfv))GetProcAddress(hModule, "glGetMaterialfv");
   ptr_glGetMaterialiv = (__vartype(ptr_glGetMaterialiv))GetProcAddress(hModule, "glGetMaterialiv");
   ptr_glGetPixelMapfv = (__vartype(ptr_glGetPixelMapfv))GetProcAddress(hModule, "glGetPixelMapfv");
   ptr_glGetPixelMapuiv = (__vartype(ptr_glGetPixelMapuiv))GetProcAddress(hModule, "glGetPixelMapuiv");
   ptr_glGetPixelMapusv = (__vartype(ptr_glGetPixelMapusv))GetProcAddress(hModule, "glGetPixelMapusv");
   ptr_glGetPointerv = (__vartype(ptr_glGetPointerv))GetProcAddress(hModule, "glGetPointerv");
   ptr_glGetPolygonStipple = (__vartype(ptr_glGetPolygonStipple))GetProcAddress(hModule, "glGetPolygonStipple");
   ptr_glGetString = (__vartype(ptr_glGetString))GetProcAddress(hModule, "glGetString");
   ptr_glGetTexEnvfv = (__vartype(ptr_glGetTexEnvfv))GetProcAddress(hModule, "glGetTexEnvfv");
   ptr_glGetTexEnviv = (__vartype(ptr_glGetTexEnviv))GetProcAddress(hModule, "glGetTexEnviv");
   ptr_glGetTexGendv = (__vartype(ptr_glGetTexGendv))GetProcAddress(hModule, "glGetTexGendv");
   ptr_glGetTexGenfv = (__vartype(ptr_glGetTexGenfv))GetProcAddress(hModule, "glGetTexGenfv");
   ptr_glGetTexGeniv = (__vartype(ptr_glGetTexGeniv))GetProcAddress(hModule, "glGetTexGeniv");
   ptr_glGetTexImage = (__vartype(ptr_glGetTexImage))GetProcAddress(hModule, "glGetTexImage");
   ptr_glGetTexLevelParameterfv = (__vartype(ptr_glGetTexLevelParameterfv))GetProcAddress(hModule, "glGetTexLevelParameterfv");
   ptr_glGetTexLevelParameteriv = (__vartype(ptr_glGetTexLevelParameteriv))GetProcAddress(hModule, "glGetTexLevelParameteriv");
   ptr_glGetTexParameterfv = (__vartype(ptr_glGetTexParameterfv))GetProcAddress(hModule, "glGetTexParameterfv");
   ptr_glGetTexParameteriv = (__vartype(ptr_glGetTexParameteriv))GetProcAddress(hModule, "glGetTexParameteriv");
   ptr_glHint = (__vartype(ptr_glHint))GetProcAddress(hModule, "glHint");
   ptr_glIndexMask = (__vartype(ptr_glIndexMask))GetProcAddress(hModule, "glIndexMask");
   ptr_glIndexPointer = (__vartype(ptr_glIndexPointer))GetProcAddress(hModule, "glIndexPointer");
   ptr_glIndexd = (__vartype(ptr_glIndexd))GetProcAddress(hModule, "glIndexd");
   ptr_glIndexdv = (__vartype(ptr_glIndexdv))GetProcAddress(hModule, "glIndexdv");
   ptr_glIndexf = (__vartype(ptr_glIndexf))GetProcAddress(hModule, "glIndexf");
   ptr_glIndexfv = (__vartype(ptr_glIndexfv))GetProcAddress(hModule, "glIndexfv");
   ptr_glIndexi = (__vartype(ptr_glIndexi))GetProcAddress(hModule, "glIndexi");
   ptr_glIndexiv = (__vartype(ptr_glIndexiv))GetProcAddress(hModule, "glIndexiv");
   ptr_glIndexs = (__vartype(ptr_glIndexs))GetProcAddress(hModule, "glIndexs");
   ptr_glIndexsv = (__vartype(ptr_glIndexsv))GetProcAddress(hModule, "glIndexsv");
   ptr_glIndexub = (__vartype(ptr_glIndexub))GetProcAddress(hModule, "glIndexub");
   ptr_glIndexubv = (__vartype(ptr_glIndexubv))GetProcAddress(hModule, "glIndexubv");
   ptr_glInitNames = (__vartype(ptr_glInitNames))GetProcAddress(hModule, "glInitNames");
   ptr_glInterleavedArrays = (__vartype(ptr_glInterleavedArrays))GetProcAddress(hModule, "glInterleavedArrays");
   ptr_glIsEnabled = (__vartype(ptr_glIsEnabled))GetProcAddress(hModule, "glIsEnabled");
   ptr_glIsList = (__vartype(ptr_glIsList))GetProcAddress(hModule, "glIsList");
   ptr_glIsTexture = (__vartype(ptr_glIsTexture))GetProcAddress(hModule, "glIsTexture");
   ptr_glLightModelf = (__vartype(ptr_glLightModelf))GetProcAddress(hModule, "glLightModelf");
   ptr_glLightModelfv = (__vartype(ptr_glLightModelfv))GetProcAddress(hModule, "glLightModelfv");
   ptr_glLightModeli = (__vartype(ptr_glLightModeli))GetProcAddress(hModule, "glLightModeli");
   ptr_glLightModeliv = (__vartype(ptr_glLightModeliv))GetProcAddress(hModule, "glLightModeliv");
   ptr_glLightf = (__vartype(ptr_glLightf))GetProcAddress(hModule, "glLightf");
   ptr_glLightfv = (__vartype(ptr_glLightfv))GetProcAddress(hModule, "glLightfv");
   ptr_glLighti = (__vartype(ptr_glLighti))GetProcAddress(hModule, "glLighti");
   ptr_glLightiv = (__vartype(ptr_glLightiv))GetProcAddress(hModule, "glLightiv");
   ptr_glLineStipple = (__vartype(ptr_glLineStipple))GetProcAddress(hModule, "glLineStipple");
   ptr_glLineWidth = (__vartype(ptr_glLineWidth))GetProcAddress(hModule, "glLineWidth");
   ptr_glListBase = (__vartype(ptr_glListBase))GetProcAddress(hModule, "glListBase");
   ptr_glLoadIdentity = (__vartype(ptr_glLoadIdentity))GetProcAddress(hModule, "glLoadIdentity");
   ptr_glLoadMatrixd = (__vartype(ptr_glLoadMatrixd))GetProcAddress(hModule, "glLoadMatrixd");
   ptr_glLoadMatrixf = (__vartype(ptr_glLoadMatrixf))GetProcAddress(hModule, "glLoadMatrixf");
   ptr_glLoadName = (__vartype(ptr_glLoadName))GetProcAddress(hModule, "glLoadName");
   ptr_glLogicOp = (__vartype(ptr_glLogicOp))GetProcAddress(hModule, "glLogicOp");
   ptr_glMap1d = (__vartype(ptr_glMap1d))GetProcAddress(hModule, "glMap1d");
   ptr_glMap1f = (__vartype(ptr_glMap1f))GetProcAddress(hModule, "glMap1f");
   ptr_glMap2d = (__vartype(ptr_glMap2d))GetProcAddress(hModule, "glMap2d");
   ptr_glMap2f = (__vartype(ptr_glMap2f))GetProcAddress(hModule, "glMap2f");
   ptr_glMapGrid1d = (__vartype(ptr_glMapGrid1d))GetProcAddress(hModule, "glMapGrid1d");
   ptr_glMapGrid1f = (__vartype(ptr_glMapGrid1f))GetProcAddress(hModule, "glMapGrid1f");
   ptr_glMapGrid2d = (__vartype(ptr_glMapGrid2d))GetProcAddress(hModule, "glMapGrid2d");
   ptr_glMapGrid2f = (__vartype(ptr_glMapGrid2f))GetProcAddress(hModule, "glMapGrid2f");
   ptr_glMaterialf = (__vartype(ptr_glMaterialf))GetProcAddress(hModule, "glMaterialf");
   ptr_glMaterialfv = (__vartype(ptr_glMaterialfv))GetProcAddress(hModule, "glMaterialfv");
   ptr_glMateriali = (__vartype(ptr_glMateriali))GetProcAddress(hModule, "glMateriali");
   ptr_glMaterialiv = (__vartype(ptr_glMaterialiv))GetProcAddress(hModule, "glMaterialiv");
   ptr_glMatrixMode = (__vartype(ptr_glMatrixMode))GetProcAddress(hModule, "glMatrixMode");
   ptr_glMultMatrixd = (__vartype(ptr_glMultMatrixd))GetProcAddress(hModule, "glMultMatrixd");
   ptr_glMultMatrixf = (__vartype(ptr_glMultMatrixf))GetProcAddress(hModule, "glMultMatrixf");
   ptr_glNewList = (__vartype(ptr_glNewList))GetProcAddress(hModule, "glNewList");
   ptr_glNormal3b = (__vartype(ptr_glNormal3b))GetProcAddress(hModule, "glNormal3b");
   ptr_glNormal3bv = (__vartype(ptr_glNormal3bv))GetProcAddress(hModule, "glNormal3bv");
   ptr_glNormal3d = (__vartype(ptr_glNormal3d))GetProcAddress(hModule, "glNormal3d");
   ptr_glNormal3dv = (__vartype(ptr_glNormal3dv))GetProcAddress(hModule, "glNormal3dv");
   ptr_glNormal3f = (__vartype(ptr_glNormal3f))GetProcAddress(hModule, "glNormal3f");
   ptr_glNormal3fv = (__vartype(ptr_glNormal3fv))GetProcAddress(hModule, "glNormal3fv");
   ptr_glNormal3i = (__vartype(ptr_glNormal3i))GetProcAddress(hModule, "glNormal3i");
   ptr_glNormal3iv = (__vartype(ptr_glNormal3iv))GetProcAddress(hModule, "glNormal3iv");
   ptr_glNormal3s = (__vartype(ptr_glNormal3s))GetProcAddress(hModule, "glNormal3s");
   ptr_glNormal3sv = (__vartype(ptr_glNormal3sv))GetProcAddress(hModule, "glNormal3sv");
   ptr_glNormalPointer = (__vartype(ptr_glNormalPointer))GetProcAddress(hModule, "glNormalPointer");
   ptr_glOrtho = (__vartype(ptr_glOrtho))GetProcAddress(hModule, "glOrtho");
   ptr_glPassThrough = (__vartype(ptr_glPassThrough))GetProcAddress(hModule, "glPassThrough");
   ptr_glPixelMapfv = (__vartype(ptr_glPixelMapfv))GetProcAddress(hModule, "glPixelMapfv");
   ptr_glPixelMapuiv = (__vartype(ptr_glPixelMapuiv))GetProcAddress(hModule, "glPixelMapuiv");
   ptr_glPixelMapusv = (__vartype(ptr_glPixelMapusv))GetProcAddress(hModule, "glPixelMapusv");
   ptr_glPixelStoref = (__vartype(ptr_glPixelStoref))GetProcAddress(hModule, "glPixelStoref");
   ptr_glPixelStorei = (__vartype(ptr_glPixelStorei))GetProcAddress(hModule, "glPixelStorei");
   ptr_glPixelTransferf = (__vartype(ptr_glPixelTransferf))GetProcAddress(hModule, "glPixelTransferf");
   ptr_glPixelTransferi = (__vartype(ptr_glPixelTransferi))GetProcAddress(hModule, "glPixelTransferi");
   ptr_glPixelZoom = (__vartype(ptr_glPixelZoom))GetProcAddress(hModule, "glPixelZoom");
   ptr_glPointSize = (__vartype(ptr_glPointSize))GetProcAddress(hModule, "glPointSize");
   ptr_glPolygonMode = (__vartype(ptr_glPolygonMode))GetProcAddress(hModule, "glPolygonMode");
   ptr_glPolygonOffset = (__vartype(ptr_glPolygonOffset))GetProcAddress(hModule, "glPolygonOffset");
   ptr_glPolygonStipple = (__vartype(ptr_glPolygonStipple))GetProcAddress(hModule, "glPolygonStipple");
   ptr_glPopAttrib = (__vartype(ptr_glPopAttrib))GetProcAddress(hModule, "glPopAttrib");
   ptr_glPopClientAttrib = (__vartype(ptr_glPopClientAttrib))GetProcAddress(hModule, "glPopClientAttrib");
   ptr_glPopMatrix = (__vartype(ptr_glPopMatrix))GetProcAddress(hModule, "glPopMatrix");
   ptr_glPopName = (__vartype(ptr_glPopName))GetProcAddress(hModule, "glPopName");
   ptr_glPrioritizeTextures = (__vartype(ptr_glPrioritizeTextures))GetProcAddress(hModule, "glPrioritizeTextures");
   ptr_glPushAttrib = (__vartype(ptr_glPushAttrib))GetProcAddress(hModule, "glPushAttrib");
   ptr_glPushClientAttrib = (__vartype(ptr_glPushClientAttrib))GetProcAddress(hModule, "glPushClientAttrib");
   ptr_glPushMatrix = (__vartype(ptr_glPushMatrix))GetProcAddress(hModule, "glPushMatrix");
   ptr_glPushName = (__vartype(ptr_glPushName))GetProcAddress(hModule, "glPushName");
   ptr_glRasterPos2d = (__vartype(ptr_glRasterPos2d))GetProcAddress(hModule, "glRasterPos2d");
   ptr_glRasterPos2dv = (__vartype(ptr_glRasterPos2dv))GetProcAddress(hModule, "glRasterPos2dv");
   ptr_glRasterPos2f = (__vartype(ptr_glRasterPos2f))GetProcAddress(hModule, "glRasterPos2f");
   ptr_glRasterPos2fv = (__vartype(ptr_glRasterPos2fv))GetProcAddress(hModule, "glRasterPos2fv");
   ptr_glRasterPos2i = (__vartype(ptr_glRasterPos2i))GetProcAddress(hModule, "glRasterPos2i");
   ptr_glRasterPos2iv = (__vartype(ptr_glRasterPos2iv))GetProcAddress(hModule, "glRasterPos2iv");
   ptr_glRasterPos2s = (__vartype(ptr_glRasterPos2s))GetProcAddress(hModule, "glRasterPos2s");
   ptr_glRasterPos2sv = (__vartype(ptr_glRasterPos2sv))GetProcAddress(hModule, "glRasterPos2sv");
   ptr_glRasterPos3d = (__vartype(ptr_glRasterPos3d))GetProcAddress(hModule, "glRasterPos3d");
   ptr_glRasterPos3dv = (__vartype(ptr_glRasterPos3dv))GetProcAddress(hModule, "glRasterPos3dv");
   ptr_glRasterPos3f = (__vartype(ptr_glRasterPos3f))GetProcAddress(hModule, "glRasterPos3f");
   ptr_glRasterPos3fv = (__vartype(ptr_glRasterPos3fv))GetProcAddress(hModule, "glRasterPos3fv");
   ptr_glRasterPos3i = (__vartype(ptr_glRasterPos3i))GetProcAddress(hModule, "glRasterPos3i");
   ptr_glRasterPos3iv = (__vartype(ptr_glRasterPos3iv))GetProcAddress(hModule, "glRasterPos3iv");
   ptr_glRasterPos3s = (__vartype(ptr_glRasterPos3s))GetProcAddress(hModule, "glRasterPos3s");
   ptr_glRasterPos3sv = (__vartype(ptr_glRasterPos3sv))GetProcAddress(hModule, "glRasterPos3sv");
   ptr_glRasterPos4d = (__vartype(ptr_glRasterPos4d))GetProcAddress(hModule, "glRasterPos4d");
   ptr_glRasterPos4dv = (__vartype(ptr_glRasterPos4dv))GetProcAddress(hModule, "glRasterPos4dv");
   ptr_glRasterPos4f = (__vartype(ptr_glRasterPos4f))GetProcAddress(hModule, "glRasterPos4f");
   ptr_glRasterPos4fv = (__vartype(ptr_glRasterPos4fv))GetProcAddress(hModule, "glRasterPos4fv");
   ptr_glRasterPos4i = (__vartype(ptr_glRasterPos4i))GetProcAddress(hModule, "glRasterPos4i");
   ptr_glRasterPos4iv = (__vartype(ptr_glRasterPos4iv))GetProcAddress(hModule, "glRasterPos4iv");
   ptr_glRasterPos4s = (__vartype(ptr_glRasterPos4s))GetProcAddress(hModule, "glRasterPos4s");
   ptr_glRasterPos4sv = (__vartype(ptr_glRasterPos4sv))GetProcAddress(hModule, "glRasterPos4sv");
   ptr_glReadBuffer = (__vartype(ptr_glReadBuffer))GetProcAddress(hModule, "glReadBuffer");
   ptr_glReadPixels = (__vartype(ptr_glReadPixels))GetProcAddress(hModule, "glReadPixels");
   ptr_glRectd = (__vartype(ptr_glRectd))GetProcAddress(hModule, "glRectd");
   ptr_glRectdv = (__vartype(ptr_glRectdv))GetProcAddress(hModule, "glRectdv");
   ptr_glRectf = (__vartype(ptr_glRectf))GetProcAddress(hModule, "glRectf");
   ptr_glRectfv = (__vartype(ptr_glRectfv))GetProcAddress(hModule, "glRectfv");
   ptr_glRecti = (__vartype(ptr_glRecti))GetProcAddress(hModule, "glRecti");
   ptr_glRectiv = (__vartype(ptr_glRectiv))GetProcAddress(hModule, "glRectiv");
   ptr_glRects = (__vartype(ptr_glRects))GetProcAddress(hModule, "glRects");
   ptr_glRectsv = (__vartype(ptr_glRectsv))GetProcAddress(hModule, "glRectsv");
   ptr_glRenderMode = (__vartype(ptr_glRenderMode))GetProcAddress(hModule, "glRenderMode");
   ptr_glRotated = (__vartype(ptr_glRotated))GetProcAddress(hModule, "glRotated");
   ptr_glRotatef = (__vartype(ptr_glRotatef))GetProcAddress(hModule, "glRotatef");
   ptr_glScaled = (__vartype(ptr_glScaled))GetProcAddress(hModule, "glScaled");
   ptr_glScalef = (__vartype(ptr_glScalef))GetProcAddress(hModule, "glScalef");
   ptr_glScissor = (__vartype(ptr_glScissor))GetProcAddress(hModule, "glScissor");
   ptr_glSelectBuffer = (__vartype(ptr_glSelectBuffer))GetProcAddress(hModule, "glSelectBuffer");
   ptr_glShadeModel = (__vartype(ptr_glShadeModel))GetProcAddress(hModule, "glShadeModel");
   ptr_glStencilFunc = (__vartype(ptr_glStencilFunc))GetProcAddress(hModule, "glStencilFunc");
   ptr_glStencilMask = (__vartype(ptr_glStencilMask))GetProcAddress(hModule, "glStencilMask");
   ptr_glStencilOp = (__vartype(ptr_glStencilOp))GetProcAddress(hModule, "glStencilOp");
   ptr_glTexCoord1d = (__vartype(ptr_glTexCoord1d))GetProcAddress(hModule, "glTexCoord1d");
   ptr_glTexCoord1dv = (__vartype(ptr_glTexCoord1dv))GetProcAddress(hModule, "glTexCoord1dv");
   ptr_glTexCoord1f = (__vartype(ptr_glTexCoord1f))GetProcAddress(hModule, "glTexCoord1f");
   ptr_glTexCoord1fv = (__vartype(ptr_glTexCoord1fv))GetProcAddress(hModule, "glTexCoord1fv");
   ptr_glTexCoord1i = (__vartype(ptr_glTexCoord1i))GetProcAddress(hModule, "glTexCoord1i");
   ptr_glTexCoord1iv = (__vartype(ptr_glTexCoord1iv))GetProcAddress(hModule, "glTexCoord1iv");
   ptr_glTexCoord1s = (__vartype(ptr_glTexCoord1s))GetProcAddress(hModule, "glTexCoord1s");
   ptr_glTexCoord1sv = (__vartype(ptr_glTexCoord1sv))GetProcAddress(hModule, "glTexCoord1sv");
   ptr_glTexCoord2d = (__vartype(ptr_glTexCoord2d))GetProcAddress(hModule, "glTexCoord2d");
   ptr_glTexCoord2dv = (__vartype(ptr_glTexCoord2dv))GetProcAddress(hModule, "glTexCoord2dv");
   ptr_glTexCoord2f = (__vartype(ptr_glTexCoord2f))GetProcAddress(hModule, "glTexCoord2f");
   ptr_glTexCoord2fv = (__vartype(ptr_glTexCoord2fv))GetProcAddress(hModule, "glTexCoord2fv");
   ptr_glTexCoord2i = (__vartype(ptr_glTexCoord2i))GetProcAddress(hModule, "glTexCoord2i");
   ptr_glTexCoord2iv = (__vartype(ptr_glTexCoord2iv))GetProcAddress(hModule, "glTexCoord2iv");
   ptr_glTexCoord2s = (__vartype(ptr_glTexCoord2s))GetProcAddress(hModule, "glTexCoord2s");
   ptr_glTexCoord2sv = (__vartype(ptr_glTexCoord2sv))GetProcAddress(hModule, "glTexCoord2sv");
   ptr_glTexCoord3d = (__vartype(ptr_glTexCoord3d))GetProcAddress(hModule, "glTexCoord3d");
   ptr_glTexCoord3dv = (__vartype(ptr_glTexCoord3dv))GetProcAddress(hModule, "glTexCoord3dv");
   ptr_glTexCoord3f = (__vartype(ptr_glTexCoord3f))GetProcAddress(hModule, "glTexCoord3f");
   ptr_glTexCoord3fv = (__vartype(ptr_glTexCoord3fv))GetProcAddress(hModule, "glTexCoord3fv");
   ptr_glTexCoord3i = (__vartype(ptr_glTexCoord3i))GetProcAddress(hModule, "glTexCoord3i");
   ptr_glTexCoord3iv = (__vartype(ptr_glTexCoord3iv))GetProcAddress(hModule, "glTexCoord3iv");
   ptr_glTexCoord3s = (__vartype(ptr_glTexCoord3s))GetProcAddress(hModule, "glTexCoord3s");
   ptr_glTexCoord3sv = (__vartype(ptr_glTexCoord3sv))GetProcAddress(hModule, "glTexCoord3sv");
   ptr_glTexCoord4d = (__vartype(ptr_glTexCoord4d))GetProcAddress(hModule, "glTexCoord4d");
   ptr_glTexCoord4dv = (__vartype(ptr_glTexCoord4dv))GetProcAddress(hModule, "glTexCoord4dv");
   ptr_glTexCoord4f = (__vartype(ptr_glTexCoord4f))GetProcAddress(hModule, "glTexCoord4f");
   ptr_glTexCoord4fv = (__vartype(ptr_glTexCoord4fv))GetProcAddress(hModule, "glTexCoord4fv");
   ptr_glTexCoord4i = (__vartype(ptr_glTexCoord4i))GetProcAddress(hModule, "glTexCoord4i");
   ptr_glTexCoord4iv = (__vartype(ptr_glTexCoord4iv))GetProcAddress(hModule, "glTexCoord4iv");
   ptr_glTexCoord4s = (__vartype(ptr_glTexCoord4s))GetProcAddress(hModule, "glTexCoord4s");
   ptr_glTexCoord4sv = (__vartype(ptr_glTexCoord4sv))GetProcAddress(hModule, "glTexCoord4sv");
   ptr_glTexCoordPointer = (__vartype(ptr_glTexCoordPointer))GetProcAddress(hModule, "glTexCoordPointer");
   ptr_glTexEnvf = (__vartype(ptr_glTexEnvf))GetProcAddress(hModule, "glTexEnvf");
   ptr_glTexEnvfv = (__vartype(ptr_glTexEnvfv))GetProcAddress(hModule, "glTexEnvfv");
   ptr_glTexEnvi = (__vartype(ptr_glTexEnvi))GetProcAddress(hModule, "glTexEnvi");
   ptr_glTexEnviv = (__vartype(ptr_glTexEnviv))GetProcAddress(hModule, "glTexEnviv");
   ptr_glTexGend = (__vartype(ptr_glTexGend))GetProcAddress(hModule, "glTexGend");
   ptr_glTexGendv = (__vartype(ptr_glTexGendv))GetProcAddress(hModule, "glTexGendv");
   ptr_glTexGenf = (__vartype(ptr_glTexGenf))GetProcAddress(hModule, "glTexGenf");
   ptr_glTexGenfv = (__vartype(ptr_glTexGenfv))GetProcAddress(hModule, "glTexGenfv");
   ptr_glTexGeni = (__vartype(ptr_glTexGeni))GetProcAddress(hModule, "glTexGeni");
   ptr_glTexGeniv = (__vartype(ptr_glTexGeniv))GetProcAddress(hModule, "glTexGeniv");
   ptr_glTexImage1D = (__vartype(ptr_glTexImage1D))GetProcAddress(hModule, "glTexImage1D");
   ptr_glTexImage2D = (__vartype(ptr_glTexImage2D))GetProcAddress(hModule, "glTexImage2D");
   ptr_glTexParameterf = (__vartype(ptr_glTexParameterf))GetProcAddress(hModule, "glTexParameterf");
   ptr_glTexParameterfv = (__vartype(ptr_glTexParameterfv))GetProcAddress(hModule, "glTexParameterfv");
   ptr_glTexParameteri = (__vartype(ptr_glTexParameteri))GetProcAddress(hModule, "glTexParameteri");
   ptr_glTexParameteriv = (__vartype(ptr_glTexParameteriv))GetProcAddress(hModule, "glTexParameteriv");
   ptr_glTexSubImage1D = (__vartype(ptr_glTexSubImage1D))GetProcAddress(hModule, "glTexSubImage1D");
   ptr_glTexSubImage2D = (__vartype(ptr_glTexSubImage2D))GetProcAddress(hModule, "glTexSubImage2D");
   ptr_glTranslated = (__vartype(ptr_glTranslated))GetProcAddress(hModule, "glTranslated");
   ptr_glTranslatef = (__vartype(ptr_glTranslatef))GetProcAddress(hModule, "glTranslatef");
   ptr_glVertex2d = (__vartype(ptr_glVertex2d))GetProcAddress(hModule, "glVertex2d");
   ptr_glVertex2dv = (__vartype(ptr_glVertex2dv))GetProcAddress(hModule, "glVertex2dv");
   ptr_glVertex2f = (__vartype(ptr_glVertex2f))GetProcAddress(hModule, "glVertex2f");
   ptr_glVertex2fv = (__vartype(ptr_glVertex2fv))GetProcAddress(hModule, "glVertex2fv");
   ptr_glVertex2i = (__vartype(ptr_glVertex2i))GetProcAddress(hModule, "glVertex2i");
   ptr_glVertex2iv = (__vartype(ptr_glVertex2iv))GetProcAddress(hModule, "glVertex2iv");
   ptr_glVertex2s = (__vartype(ptr_glVertex2s))GetProcAddress(hModule, "glVertex2s");
   ptr_glVertex2sv = (__vartype(ptr_glVertex2sv))GetProcAddress(hModule, "glVertex2sv");
   ptr_glVertex3d = (__vartype(ptr_glVertex3d))GetProcAddress(hModule, "glVertex3d");
   ptr_glVertex3dv = (__vartype(ptr_glVertex3dv))GetProcAddress(hModule, "glVertex3dv");
   ptr_glVertex3f = (__vartype(ptr_glVertex3f))GetProcAddress(hModule, "glVertex3f");
   ptr_glVertex3fv = (__vartype(ptr_glVertex3fv))GetProcAddress(hModule, "glVertex3fv");
   ptr_glVertex3i = (__vartype(ptr_glVertex3i))GetProcAddress(hModule, "glVertex3i");
   ptr_glVertex3iv = (__vartype(ptr_glVertex3iv))GetProcAddress(hModule, "glVertex3iv");
   ptr_glVertex3s = (__vartype(ptr_glVertex3s))GetProcAddress(hModule, "glVertex3s");
   ptr_glVertex3sv = (__vartype(ptr_glVertex3sv))GetProcAddress(hModule, "glVertex3sv");
   ptr_glVertex4d = (__vartype(ptr_glVertex4d))GetProcAddress(hModule, "glVertex4d");
   ptr_glVertex4dv = (__vartype(ptr_glVertex4dv))GetProcAddress(hModule, "glVertex4dv");
   ptr_glVertex4f = (__vartype(ptr_glVertex4f))GetProcAddress(hModule, "glVertex4f");
   ptr_glVertex4fv = (__vartype(ptr_glVertex4fv))GetProcAddress(hModule, "glVertex4fv");
   ptr_glVertex4i = (__vartype(ptr_glVertex4i))GetProcAddress(hModule, "glVertex4i");
   ptr_glVertex4iv = (__vartype(ptr_glVertex4iv))GetProcAddress(hModule, "glVertex4iv");
   ptr_glVertex4s = (__vartype(ptr_glVertex4s))GetProcAddress(hModule, "glVertex4s");
   ptr_glVertex4sv = (__vartype(ptr_glVertex4sv))GetProcAddress(hModule, "glVertex4sv");
   ptr_glVertexPointer = (__vartype(ptr_glVertexPointer))GetProcAddress(hModule, "glVertexPointer");
   ptr_glViewport = (__vartype(ptr_glViewport))GetProcAddress(hModule, "glViewport");
   ptr_wglChoosePixelFormat = (__vartype(ptr_wglChoosePixelFormat))GetProcAddress(hModule, "wglChoosePixelFormat");
   ptr_wglCopyContext = (__vartype(ptr_wglCopyContext))GetProcAddress(hModule, "wglCopyContext");
   ptr_wglCreateContext = (__vartype(ptr_wglCreateContext))GetProcAddress(hModule, "wglCreateContext");
   ptr_wglCreateLayerContext = (__vartype(ptr_wglCreateLayerContext))GetProcAddress(hModule, "wglCreateLayerContext");
   ptr_wglDeleteContext = (__vartype(ptr_wglDeleteContext))GetProcAddress(hModule, "wglDeleteContext");
   ptr_wglDescribeLayerPlane = (__vartype(ptr_wglDescribeLayerPlane))GetProcAddress(hModule, "wglDescribeLayerPlane");
   ptr_wglDescribePixelFormat = (__vartype(ptr_wglDescribePixelFormat))GetProcAddress(hModule, "wglDescribePixelFormat");
   ptr_wglGetCurrentContext = (__vartype(ptr_wglGetCurrentContext))GetProcAddress(hModule, "wglGetCurrentContext");
   ptr_wglGetCurrentDC = (__vartype(ptr_wglGetCurrentDC))GetProcAddress(hModule, "wglGetCurrentDC");
   ptr_wglGetDefaultProcAddress = (__vartype(ptr_wglGetDefaultProcAddress))GetProcAddress(hModule, "wglGetDefaultProcAddress");
   ptr_wglGetLayerPaletteEntries = (__vartype(ptr_wglGetLayerPaletteEntries))GetProcAddress(hModule, "wglGetLayerPaletteEntries");
   ptr_wglGetPixelFormat = (__vartype(ptr_wglGetPixelFormat))GetProcAddress(hModule, "wglGetPixelFormat");
   ptr_wglGetProcAddress = (__vartype(ptr_wglGetProcAddress))GetProcAddress(hModule, "wglGetProcAddress");
   ptr_wglMakeCurrent = (__vartype(ptr_wglMakeCurrent))GetProcAddress(hModule, "wglMakeCurrent");
   ptr_wglRealizeLayerPalette = (__vartype(ptr_wglRealizeLayerPalette))GetProcAddress(hModule, "wglRealizeLayerPalette");
   ptr_wglSetLayerPaletteEntries = (__vartype(ptr_wglSetLayerPaletteEntries))GetProcAddress(hModule, "wglSetLayerPaletteEntries");
   ptr_wglSetPixelFormat = (__vartype(ptr_wglSetPixelFormat))GetProcAddress(hModule, "wglSetPixelFormat");
   ptr_wglShareLists = (__vartype(ptr_wglShareLists))GetProcAddress(hModule, "wglShareLists");
   ptr_wglSwapBuffers = (__vartype(ptr_wglSwapBuffers))GetProcAddress(hModule, "wglSwapBuffers");
   ptr_wglSwapLayerBuffers = (__vartype(ptr_wglSwapLayerBuffers))GetProcAddress(hModule, "wglSwapLayerBuffers");
   ptr_wglSwapMultipleBuffers = (__vartype(ptr_wglSwapMultipleBuffers))GetProcAddress(hModule, "wglSwapMultipleBuffers");
   ptr_wglUseFontBitmapsA = (__vartype(ptr_wglUseFontBitmapsA))GetProcAddress(hModule, "wglUseFontBitmapsA");
   ptr_wglUseFontBitmapsW = (__vartype(ptr_wglUseFontBitmapsW))GetProcAddress(hModule, "wglUseFontBitmapsW");
   ptr_wglUseFontOutlinesA = (__vartype(ptr_wglUseFontOutlinesA))GetProcAddress(hModule, "wglUseFontOutlinesA");
   ptr_wglUseFontOutlinesW = (__vartype(ptr_wglUseFontOutlinesW))GetProcAddress(hModule, "wglUseFontOutlinesW");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

