#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_PdhAdd009CounterA;
void *ptr_PdhAdd009CounterA = NULL;
extern void *ptr_PdhAdd009CounterW;
void *ptr_PdhAdd009CounterW = NULL;
extern void *ptr_PdhAddCounterA;
void *ptr_PdhAddCounterA = NULL;
extern void *ptr_PdhAddCounterW;
void *ptr_PdhAddCounterW = NULL;
extern void *ptr_PdhAddEnglishCounterA;
void *ptr_PdhAddEnglishCounterA = NULL;
extern void *ptr_PdhAddEnglishCounterW;
void *ptr_PdhAddEnglishCounterW = NULL;
extern void *ptr_PdhAddRelogCounter;
void *ptr_PdhAddRelogCounter = NULL;
extern void *ptr_PdhBindInputDataSourceA;
void *ptr_PdhBindInputDataSourceA = NULL;
extern void *ptr_PdhBindInputDataSourceW;
void *ptr_PdhBindInputDataSourceW = NULL;
extern void *ptr_PdhBrowseCountersA;
void *ptr_PdhBrowseCountersA = NULL;
extern void *ptr_PdhBrowseCountersHA;
void *ptr_PdhBrowseCountersHA = NULL;
extern void *ptr_PdhBrowseCountersHW;
void *ptr_PdhBrowseCountersHW = NULL;
extern void *ptr_PdhBrowseCountersW;
void *ptr_PdhBrowseCountersW = NULL;
extern void *ptr_PdhCalculateCounterFromRawValue;
void *ptr_PdhCalculateCounterFromRawValue = NULL;
extern void *ptr_PdhCloseLog;
void *ptr_PdhCloseLog = NULL;
extern void *ptr_PdhCloseQuery;
void *ptr_PdhCloseQuery = NULL;
extern void *ptr_PdhCollectQueryData;
void *ptr_PdhCollectQueryData = NULL;
extern void *ptr_PdhCollectQueryDataEx;
void *ptr_PdhCollectQueryDataEx = NULL;
extern void *ptr_PdhCollectQueryDataWithTime;
void *ptr_PdhCollectQueryDataWithTime = NULL;
extern void *ptr_PdhComputeCounterStatistics;
void *ptr_PdhComputeCounterStatistics = NULL;
extern void *ptr_PdhConnectMachineA;
void *ptr_PdhConnectMachineA = NULL;
extern void *ptr_PdhConnectMachineW;
void *ptr_PdhConnectMachineW = NULL;
extern void *ptr_PdhCreateSQLTablesA;
void *ptr_PdhCreateSQLTablesA = NULL;
extern void *ptr_PdhCreateSQLTablesW;
void *ptr_PdhCreateSQLTablesW = NULL;
extern void *ptr_PdhEnumLogSetNamesA;
void *ptr_PdhEnumLogSetNamesA = NULL;
extern void *ptr_PdhEnumLogSetNamesW;
void *ptr_PdhEnumLogSetNamesW = NULL;
extern void *ptr_PdhEnumMachinesA;
void *ptr_PdhEnumMachinesA = NULL;
extern void *ptr_PdhEnumMachinesHA;
void *ptr_PdhEnumMachinesHA = NULL;
extern void *ptr_PdhEnumMachinesHW;
void *ptr_PdhEnumMachinesHW = NULL;
extern void *ptr_PdhEnumMachinesW;
void *ptr_PdhEnumMachinesW = NULL;
extern void *ptr_PdhEnumObjectItemsA;
void *ptr_PdhEnumObjectItemsA = NULL;
extern void *ptr_PdhEnumObjectItemsHA;
void *ptr_PdhEnumObjectItemsHA = NULL;
extern void *ptr_PdhEnumObjectItemsHW;
void *ptr_PdhEnumObjectItemsHW = NULL;
extern void *ptr_PdhEnumObjectItemsW;
void *ptr_PdhEnumObjectItemsW = NULL;
extern void *ptr_PdhEnumObjectsA;
void *ptr_PdhEnumObjectsA = NULL;
extern void *ptr_PdhEnumObjectsHA;
void *ptr_PdhEnumObjectsHA = NULL;
extern void *ptr_PdhEnumObjectsHW;
void *ptr_PdhEnumObjectsHW = NULL;
extern void *ptr_PdhEnumObjectsW;
void *ptr_PdhEnumObjectsW = NULL;
extern void *ptr_PdhExpandCounterPathA;
void *ptr_PdhExpandCounterPathA = NULL;
extern void *ptr_PdhExpandCounterPathW;
void *ptr_PdhExpandCounterPathW = NULL;
extern void *ptr_PdhExpandWildCardPathA;
void *ptr_PdhExpandWildCardPathA = NULL;
extern void *ptr_PdhExpandWildCardPathHA;
void *ptr_PdhExpandWildCardPathHA = NULL;
extern void *ptr_PdhExpandWildCardPathHW;
void *ptr_PdhExpandWildCardPathHW = NULL;
extern void *ptr_PdhExpandWildCardPathW;
void *ptr_PdhExpandWildCardPathW = NULL;
extern void *ptr_PdhFormatFromRawValue;
void *ptr_PdhFormatFromRawValue = NULL;
extern void *ptr_PdhGetCounterInfoA;
void *ptr_PdhGetCounterInfoA = NULL;
extern void *ptr_PdhGetCounterInfoW;
void *ptr_PdhGetCounterInfoW = NULL;
extern void *ptr_PdhGetCounterTimeBase;
void *ptr_PdhGetCounterTimeBase = NULL;
extern void *ptr_PdhGetDataSourceTimeRangeA;
void *ptr_PdhGetDataSourceTimeRangeA = NULL;
extern void *ptr_PdhGetDataSourceTimeRangeH;
void *ptr_PdhGetDataSourceTimeRangeH = NULL;
extern void *ptr_PdhGetDataSourceTimeRangeW;
void *ptr_PdhGetDataSourceTimeRangeW = NULL;
extern void *ptr_PdhGetDefaultPerfCounterA;
void *ptr_PdhGetDefaultPerfCounterA = NULL;
extern void *ptr_PdhGetDefaultPerfCounterHA;
void *ptr_PdhGetDefaultPerfCounterHA = NULL;
extern void *ptr_PdhGetDefaultPerfCounterHW;
void *ptr_PdhGetDefaultPerfCounterHW = NULL;
extern void *ptr_PdhGetDefaultPerfCounterW;
void *ptr_PdhGetDefaultPerfCounterW = NULL;
extern void *ptr_PdhGetDefaultPerfObjectA;
void *ptr_PdhGetDefaultPerfObjectA = NULL;
extern void *ptr_PdhGetDefaultPerfObjectHA;
void *ptr_PdhGetDefaultPerfObjectHA = NULL;
extern void *ptr_PdhGetDefaultPerfObjectHW;
void *ptr_PdhGetDefaultPerfObjectHW = NULL;
extern void *ptr_PdhGetDefaultPerfObjectW;
void *ptr_PdhGetDefaultPerfObjectW = NULL;
extern void *ptr_PdhGetDllVersion;
void *ptr_PdhGetDllVersion = NULL;
extern void *ptr_PdhGetExplainText;
void *ptr_PdhGetExplainText = NULL;
extern void *ptr_PdhGetFormattedCounterArrayA;
void *ptr_PdhGetFormattedCounterArrayA = NULL;
extern void *ptr_PdhGetFormattedCounterArrayW;
void *ptr_PdhGetFormattedCounterArrayW = NULL;
extern void *ptr_PdhGetFormattedCounterValue;
void *ptr_PdhGetFormattedCounterValue = NULL;
extern void *ptr_PdhGetLogFileSize;
void *ptr_PdhGetLogFileSize = NULL;
extern void *ptr_PdhGetLogFileTypeA;
void *ptr_PdhGetLogFileTypeA = NULL;
extern void *ptr_PdhGetLogFileTypeW;
void *ptr_PdhGetLogFileTypeW = NULL;
extern void *ptr_PdhGetLogSetGUID;
void *ptr_PdhGetLogSetGUID = NULL;
extern void *ptr_PdhGetRawCounterArrayA;
void *ptr_PdhGetRawCounterArrayA = NULL;
extern void *ptr_PdhGetRawCounterArrayW;
void *ptr_PdhGetRawCounterArrayW = NULL;
extern void *ptr_PdhGetRawCounterValue;
void *ptr_PdhGetRawCounterValue = NULL;
extern void *ptr_PdhIsRealTimeQuery;
void *ptr_PdhIsRealTimeQuery = NULL;
extern void *ptr_PdhListLogFileHeaderA;
void *ptr_PdhListLogFileHeaderA = NULL;
extern void *ptr_PdhListLogFileHeaderW;
void *ptr_PdhListLogFileHeaderW = NULL;
extern void *ptr_PdhLookupPerfIndexByNameA;
void *ptr_PdhLookupPerfIndexByNameA = NULL;
extern void *ptr_PdhLookupPerfIndexByNameW;
void *ptr_PdhLookupPerfIndexByNameW = NULL;
extern void *ptr_PdhLookupPerfNameByIndexA;
void *ptr_PdhLookupPerfNameByIndexA = NULL;
extern void *ptr_PdhLookupPerfNameByIndexW;
void *ptr_PdhLookupPerfNameByIndexW = NULL;
extern void *ptr_PdhMakeCounterPathA;
void *ptr_PdhMakeCounterPathA = NULL;
extern void *ptr_PdhMakeCounterPathW;
void *ptr_PdhMakeCounterPathW = NULL;
extern void *ptr_PdhOpenLogA;
void *ptr_PdhOpenLogA = NULL;
extern void *ptr_PdhOpenLogW;
void *ptr_PdhOpenLogW = NULL;
extern void *ptr_PdhOpenQuery;
void *ptr_PdhOpenQuery = NULL;
extern void *ptr_PdhOpenQueryA;
void *ptr_PdhOpenQueryA = NULL;
extern void *ptr_PdhOpenQueryH;
void *ptr_PdhOpenQueryH = NULL;
extern void *ptr_PdhOpenQueryW;
void *ptr_PdhOpenQueryW = NULL;
extern void *ptr_PdhParseCounterPathA;
void *ptr_PdhParseCounterPathA = NULL;
extern void *ptr_PdhParseCounterPathW;
void *ptr_PdhParseCounterPathW = NULL;
extern void *ptr_PdhParseInstanceNameA;
void *ptr_PdhParseInstanceNameA = NULL;
extern void *ptr_PdhParseInstanceNameW;
void *ptr_PdhParseInstanceNameW = NULL;
extern void *ptr_PdhReadRawLogRecord;
void *ptr_PdhReadRawLogRecord = NULL;
extern void *ptr_PdhRelogA;
void *ptr_PdhRelogA = NULL;
extern void *ptr_PdhRelogW;
void *ptr_PdhRelogW = NULL;
extern void *ptr_PdhRemoveCounter;
void *ptr_PdhRemoveCounter = NULL;
extern void *ptr_PdhResetRelogCounterValues;
void *ptr_PdhResetRelogCounterValues = NULL;
extern void *ptr_PdhSelectDataSourceA;
void *ptr_PdhSelectDataSourceA = NULL;
extern void *ptr_PdhSelectDataSourceW;
void *ptr_PdhSelectDataSourceW = NULL;
extern void *ptr_PdhSetCounterScaleFactor;
void *ptr_PdhSetCounterScaleFactor = NULL;
extern void *ptr_PdhSetCounterValue;
void *ptr_PdhSetCounterValue = NULL;
extern void *ptr_PdhSetDefaultRealTimeDataSource;
void *ptr_PdhSetDefaultRealTimeDataSource = NULL;
extern void *ptr_PdhSetLogSetRunID;
void *ptr_PdhSetLogSetRunID = NULL;
extern void *ptr_PdhSetQueryTimeRange;
void *ptr_PdhSetQueryTimeRange = NULL;
extern void *ptr_PdhTranslate009CounterA;
void *ptr_PdhTranslate009CounterA = NULL;
extern void *ptr_PdhTranslate009CounterW;
void *ptr_PdhTranslate009CounterW = NULL;
extern void *ptr_PdhTranslateLocaleCounterA;
void *ptr_PdhTranslateLocaleCounterA = NULL;
extern void *ptr_PdhTranslateLocaleCounterW;
void *ptr_PdhTranslateLocaleCounterW = NULL;
extern void *ptr_PdhUpdateLogA;
void *ptr_PdhUpdateLogA = NULL;
extern void *ptr_PdhUpdateLogFileCatalog;
void *ptr_PdhUpdateLogFileCatalog = NULL;
extern void *ptr_PdhUpdateLogW;
void *ptr_PdhUpdateLogW = NULL;
extern void *ptr_PdhValidatePathA;
void *ptr_PdhValidatePathA = NULL;
extern void *ptr_PdhValidatePathExA;
void *ptr_PdhValidatePathExA = NULL;
extern void *ptr_PdhValidatePathExW;
void *ptr_PdhValidatePathExW = NULL;
extern void *ptr_PdhValidatePathW;
void *ptr_PdhValidatePathW = NULL;
extern void *ptr_PdhVbAddCounter;
void *ptr_PdhVbAddCounter = NULL;
extern void *ptr_PdhVbCreateCounterPathList;
void *ptr_PdhVbCreateCounterPathList = NULL;
extern void *ptr_PdhVbGetCounterPathElements;
void *ptr_PdhVbGetCounterPathElements = NULL;
extern void *ptr_PdhVbGetCounterPathFromList;
void *ptr_PdhVbGetCounterPathFromList = NULL;
extern void *ptr_PdhVbGetDoubleCounterValue;
void *ptr_PdhVbGetDoubleCounterValue = NULL;
extern void *ptr_PdhVbGetLogFileSize;
void *ptr_PdhVbGetLogFileSize = NULL;
extern void *ptr_PdhVbGetOneCounterPath;
void *ptr_PdhVbGetOneCounterPath = NULL;
extern void *ptr_PdhVbIsGoodStatus;
void *ptr_PdhVbIsGoodStatus = NULL;
extern void *ptr_PdhVbOpenLog;
void *ptr_PdhVbOpenLog = NULL;
extern void *ptr_PdhVbOpenQuery;
void *ptr_PdhVbOpenQuery = NULL;
extern void *ptr_PdhVbUpdateLog;
void *ptr_PdhVbUpdateLog = NULL;
extern void *ptr_PdhVerifySQLDBA;
void *ptr_PdhVerifySQLDBA = NULL;
extern void *ptr_PdhVerifySQLDBW;
void *ptr_PdhVerifySQLDBW = NULL;
extern void *ptr_PdhWriteRelogSample;
void *ptr_PdhWriteRelogSample = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\pdh.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_PdhAdd009CounterA = (__vartype(ptr_PdhAdd009CounterA))GetProcAddress(hModule, "PdhAdd009CounterA");
   ptr_PdhAdd009CounterW = (__vartype(ptr_PdhAdd009CounterW))GetProcAddress(hModule, "PdhAdd009CounterW");
   ptr_PdhAddCounterA = (__vartype(ptr_PdhAddCounterA))GetProcAddress(hModule, "PdhAddCounterA");
   ptr_PdhAddCounterW = (__vartype(ptr_PdhAddCounterW))GetProcAddress(hModule, "PdhAddCounterW");
   ptr_PdhAddEnglishCounterA = (__vartype(ptr_PdhAddEnglishCounterA))GetProcAddress(hModule, "PdhAddEnglishCounterA");
   ptr_PdhAddEnglishCounterW = (__vartype(ptr_PdhAddEnglishCounterW))GetProcAddress(hModule, "PdhAddEnglishCounterW");
   ptr_PdhAddRelogCounter = (__vartype(ptr_PdhAddRelogCounter))GetProcAddress(hModule, "PdhAddRelogCounter");
   ptr_PdhBindInputDataSourceA = (__vartype(ptr_PdhBindInputDataSourceA))GetProcAddress(hModule, "PdhBindInputDataSourceA");
   ptr_PdhBindInputDataSourceW = (__vartype(ptr_PdhBindInputDataSourceW))GetProcAddress(hModule, "PdhBindInputDataSourceW");
   ptr_PdhBrowseCountersA = (__vartype(ptr_PdhBrowseCountersA))GetProcAddress(hModule, "PdhBrowseCountersA");
   ptr_PdhBrowseCountersHA = (__vartype(ptr_PdhBrowseCountersHA))GetProcAddress(hModule, "PdhBrowseCountersHA");
   ptr_PdhBrowseCountersHW = (__vartype(ptr_PdhBrowseCountersHW))GetProcAddress(hModule, "PdhBrowseCountersHW");
   ptr_PdhBrowseCountersW = (__vartype(ptr_PdhBrowseCountersW))GetProcAddress(hModule, "PdhBrowseCountersW");
   ptr_PdhCalculateCounterFromRawValue = (__vartype(ptr_PdhCalculateCounterFromRawValue))GetProcAddress(hModule, "PdhCalculateCounterFromRawValue");
   ptr_PdhCloseLog = (__vartype(ptr_PdhCloseLog))GetProcAddress(hModule, "PdhCloseLog");
   ptr_PdhCloseQuery = (__vartype(ptr_PdhCloseQuery))GetProcAddress(hModule, "PdhCloseQuery");
   ptr_PdhCollectQueryData = (__vartype(ptr_PdhCollectQueryData))GetProcAddress(hModule, "PdhCollectQueryData");
   ptr_PdhCollectQueryDataEx = (__vartype(ptr_PdhCollectQueryDataEx))GetProcAddress(hModule, "PdhCollectQueryDataEx");
   ptr_PdhCollectQueryDataWithTime = (__vartype(ptr_PdhCollectQueryDataWithTime))GetProcAddress(hModule, "PdhCollectQueryDataWithTime");
   ptr_PdhComputeCounterStatistics = (__vartype(ptr_PdhComputeCounterStatistics))GetProcAddress(hModule, "PdhComputeCounterStatistics");
   ptr_PdhConnectMachineA = (__vartype(ptr_PdhConnectMachineA))GetProcAddress(hModule, "PdhConnectMachineA");
   ptr_PdhConnectMachineW = (__vartype(ptr_PdhConnectMachineW))GetProcAddress(hModule, "PdhConnectMachineW");
   ptr_PdhCreateSQLTablesA = (__vartype(ptr_PdhCreateSQLTablesA))GetProcAddress(hModule, "PdhCreateSQLTablesA");
   ptr_PdhCreateSQLTablesW = (__vartype(ptr_PdhCreateSQLTablesW))GetProcAddress(hModule, "PdhCreateSQLTablesW");
   ptr_PdhEnumLogSetNamesA = (__vartype(ptr_PdhEnumLogSetNamesA))GetProcAddress(hModule, "PdhEnumLogSetNamesA");
   ptr_PdhEnumLogSetNamesW = (__vartype(ptr_PdhEnumLogSetNamesW))GetProcAddress(hModule, "PdhEnumLogSetNamesW");
   ptr_PdhEnumMachinesA = (__vartype(ptr_PdhEnumMachinesA))GetProcAddress(hModule, "PdhEnumMachinesA");
   ptr_PdhEnumMachinesHA = (__vartype(ptr_PdhEnumMachinesHA))GetProcAddress(hModule, "PdhEnumMachinesHA");
   ptr_PdhEnumMachinesHW = (__vartype(ptr_PdhEnumMachinesHW))GetProcAddress(hModule, "PdhEnumMachinesHW");
   ptr_PdhEnumMachinesW = (__vartype(ptr_PdhEnumMachinesW))GetProcAddress(hModule, "PdhEnumMachinesW");
   ptr_PdhEnumObjectItemsA = (__vartype(ptr_PdhEnumObjectItemsA))GetProcAddress(hModule, "PdhEnumObjectItemsA");
   ptr_PdhEnumObjectItemsHA = (__vartype(ptr_PdhEnumObjectItemsHA))GetProcAddress(hModule, "PdhEnumObjectItemsHA");
   ptr_PdhEnumObjectItemsHW = (__vartype(ptr_PdhEnumObjectItemsHW))GetProcAddress(hModule, "PdhEnumObjectItemsHW");
   ptr_PdhEnumObjectItemsW = (__vartype(ptr_PdhEnumObjectItemsW))GetProcAddress(hModule, "PdhEnumObjectItemsW");
   ptr_PdhEnumObjectsA = (__vartype(ptr_PdhEnumObjectsA))GetProcAddress(hModule, "PdhEnumObjectsA");
   ptr_PdhEnumObjectsHA = (__vartype(ptr_PdhEnumObjectsHA))GetProcAddress(hModule, "PdhEnumObjectsHA");
   ptr_PdhEnumObjectsHW = (__vartype(ptr_PdhEnumObjectsHW))GetProcAddress(hModule, "PdhEnumObjectsHW");
   ptr_PdhEnumObjectsW = (__vartype(ptr_PdhEnumObjectsW))GetProcAddress(hModule, "PdhEnumObjectsW");
   ptr_PdhExpandCounterPathA = (__vartype(ptr_PdhExpandCounterPathA))GetProcAddress(hModule, "PdhExpandCounterPathA");
   ptr_PdhExpandCounterPathW = (__vartype(ptr_PdhExpandCounterPathW))GetProcAddress(hModule, "PdhExpandCounterPathW");
   ptr_PdhExpandWildCardPathA = (__vartype(ptr_PdhExpandWildCardPathA))GetProcAddress(hModule, "PdhExpandWildCardPathA");
   ptr_PdhExpandWildCardPathHA = (__vartype(ptr_PdhExpandWildCardPathHA))GetProcAddress(hModule, "PdhExpandWildCardPathHA");
   ptr_PdhExpandWildCardPathHW = (__vartype(ptr_PdhExpandWildCardPathHW))GetProcAddress(hModule, "PdhExpandWildCardPathHW");
   ptr_PdhExpandWildCardPathW = (__vartype(ptr_PdhExpandWildCardPathW))GetProcAddress(hModule, "PdhExpandWildCardPathW");
   ptr_PdhFormatFromRawValue = (__vartype(ptr_PdhFormatFromRawValue))GetProcAddress(hModule, "PdhFormatFromRawValue");
   ptr_PdhGetCounterInfoA = (__vartype(ptr_PdhGetCounterInfoA))GetProcAddress(hModule, "PdhGetCounterInfoA");
   ptr_PdhGetCounterInfoW = (__vartype(ptr_PdhGetCounterInfoW))GetProcAddress(hModule, "PdhGetCounterInfoW");
   ptr_PdhGetCounterTimeBase = (__vartype(ptr_PdhGetCounterTimeBase))GetProcAddress(hModule, "PdhGetCounterTimeBase");
   ptr_PdhGetDataSourceTimeRangeA = (__vartype(ptr_PdhGetDataSourceTimeRangeA))GetProcAddress(hModule, "PdhGetDataSourceTimeRangeA");
   ptr_PdhGetDataSourceTimeRangeH = (__vartype(ptr_PdhGetDataSourceTimeRangeH))GetProcAddress(hModule, "PdhGetDataSourceTimeRangeH");
   ptr_PdhGetDataSourceTimeRangeW = (__vartype(ptr_PdhGetDataSourceTimeRangeW))GetProcAddress(hModule, "PdhGetDataSourceTimeRangeW");
   ptr_PdhGetDefaultPerfCounterA = (__vartype(ptr_PdhGetDefaultPerfCounterA))GetProcAddress(hModule, "PdhGetDefaultPerfCounterA");
   ptr_PdhGetDefaultPerfCounterHA = (__vartype(ptr_PdhGetDefaultPerfCounterHA))GetProcAddress(hModule, "PdhGetDefaultPerfCounterHA");
   ptr_PdhGetDefaultPerfCounterHW = (__vartype(ptr_PdhGetDefaultPerfCounterHW))GetProcAddress(hModule, "PdhGetDefaultPerfCounterHW");
   ptr_PdhGetDefaultPerfCounterW = (__vartype(ptr_PdhGetDefaultPerfCounterW))GetProcAddress(hModule, "PdhGetDefaultPerfCounterW");
   ptr_PdhGetDefaultPerfObjectA = (__vartype(ptr_PdhGetDefaultPerfObjectA))GetProcAddress(hModule, "PdhGetDefaultPerfObjectA");
   ptr_PdhGetDefaultPerfObjectHA = (__vartype(ptr_PdhGetDefaultPerfObjectHA))GetProcAddress(hModule, "PdhGetDefaultPerfObjectHA");
   ptr_PdhGetDefaultPerfObjectHW = (__vartype(ptr_PdhGetDefaultPerfObjectHW))GetProcAddress(hModule, "PdhGetDefaultPerfObjectHW");
   ptr_PdhGetDefaultPerfObjectW = (__vartype(ptr_PdhGetDefaultPerfObjectW))GetProcAddress(hModule, "PdhGetDefaultPerfObjectW");
   ptr_PdhGetDllVersion = (__vartype(ptr_PdhGetDllVersion))GetProcAddress(hModule, "PdhGetDllVersion");
   ptr_PdhGetExplainText = (__vartype(ptr_PdhGetExplainText))GetProcAddress(hModule, "PdhGetExplainText");
   ptr_PdhGetFormattedCounterArrayA = (__vartype(ptr_PdhGetFormattedCounterArrayA))GetProcAddress(hModule, "PdhGetFormattedCounterArrayA");
   ptr_PdhGetFormattedCounterArrayW = (__vartype(ptr_PdhGetFormattedCounterArrayW))GetProcAddress(hModule, "PdhGetFormattedCounterArrayW");
   ptr_PdhGetFormattedCounterValue = (__vartype(ptr_PdhGetFormattedCounterValue))GetProcAddress(hModule, "PdhGetFormattedCounterValue");
   ptr_PdhGetLogFileSize = (__vartype(ptr_PdhGetLogFileSize))GetProcAddress(hModule, "PdhGetLogFileSize");
   ptr_PdhGetLogFileTypeA = (__vartype(ptr_PdhGetLogFileTypeA))GetProcAddress(hModule, "PdhGetLogFileTypeA");
   ptr_PdhGetLogFileTypeW = (__vartype(ptr_PdhGetLogFileTypeW))GetProcAddress(hModule, "PdhGetLogFileTypeW");
   ptr_PdhGetLogSetGUID = (__vartype(ptr_PdhGetLogSetGUID))GetProcAddress(hModule, "PdhGetLogSetGUID");
   ptr_PdhGetRawCounterArrayA = (__vartype(ptr_PdhGetRawCounterArrayA))GetProcAddress(hModule, "PdhGetRawCounterArrayA");
   ptr_PdhGetRawCounterArrayW = (__vartype(ptr_PdhGetRawCounterArrayW))GetProcAddress(hModule, "PdhGetRawCounterArrayW");
   ptr_PdhGetRawCounterValue = (__vartype(ptr_PdhGetRawCounterValue))GetProcAddress(hModule, "PdhGetRawCounterValue");
   ptr_PdhIsRealTimeQuery = (__vartype(ptr_PdhIsRealTimeQuery))GetProcAddress(hModule, "PdhIsRealTimeQuery");
   ptr_PdhListLogFileHeaderA = (__vartype(ptr_PdhListLogFileHeaderA))GetProcAddress(hModule, "PdhListLogFileHeaderA");
   ptr_PdhListLogFileHeaderW = (__vartype(ptr_PdhListLogFileHeaderW))GetProcAddress(hModule, "PdhListLogFileHeaderW");
   ptr_PdhLookupPerfIndexByNameA = (__vartype(ptr_PdhLookupPerfIndexByNameA))GetProcAddress(hModule, "PdhLookupPerfIndexByNameA");
   ptr_PdhLookupPerfIndexByNameW = (__vartype(ptr_PdhLookupPerfIndexByNameW))GetProcAddress(hModule, "PdhLookupPerfIndexByNameW");
   ptr_PdhLookupPerfNameByIndexA = (__vartype(ptr_PdhLookupPerfNameByIndexA))GetProcAddress(hModule, "PdhLookupPerfNameByIndexA");
   ptr_PdhLookupPerfNameByIndexW = (__vartype(ptr_PdhLookupPerfNameByIndexW))GetProcAddress(hModule, "PdhLookupPerfNameByIndexW");
   ptr_PdhMakeCounterPathA = (__vartype(ptr_PdhMakeCounterPathA))GetProcAddress(hModule, "PdhMakeCounterPathA");
   ptr_PdhMakeCounterPathW = (__vartype(ptr_PdhMakeCounterPathW))GetProcAddress(hModule, "PdhMakeCounterPathW");
   ptr_PdhOpenLogA = (__vartype(ptr_PdhOpenLogA))GetProcAddress(hModule, "PdhOpenLogA");
   ptr_PdhOpenLogW = (__vartype(ptr_PdhOpenLogW))GetProcAddress(hModule, "PdhOpenLogW");
   ptr_PdhOpenQuery = (__vartype(ptr_PdhOpenQuery))GetProcAddress(hModule, "PdhOpenQuery");
   ptr_PdhOpenQueryA = (__vartype(ptr_PdhOpenQueryA))GetProcAddress(hModule, "PdhOpenQueryA");
   ptr_PdhOpenQueryH = (__vartype(ptr_PdhOpenQueryH))GetProcAddress(hModule, "PdhOpenQueryH");
   ptr_PdhOpenQueryW = (__vartype(ptr_PdhOpenQueryW))GetProcAddress(hModule, "PdhOpenQueryW");
   ptr_PdhParseCounterPathA = (__vartype(ptr_PdhParseCounterPathA))GetProcAddress(hModule, "PdhParseCounterPathA");
   ptr_PdhParseCounterPathW = (__vartype(ptr_PdhParseCounterPathW))GetProcAddress(hModule, "PdhParseCounterPathW");
   ptr_PdhParseInstanceNameA = (__vartype(ptr_PdhParseInstanceNameA))GetProcAddress(hModule, "PdhParseInstanceNameA");
   ptr_PdhParseInstanceNameW = (__vartype(ptr_PdhParseInstanceNameW))GetProcAddress(hModule, "PdhParseInstanceNameW");
   ptr_PdhReadRawLogRecord = (__vartype(ptr_PdhReadRawLogRecord))GetProcAddress(hModule, "PdhReadRawLogRecord");
   ptr_PdhRelogA = (__vartype(ptr_PdhRelogA))GetProcAddress(hModule, "PdhRelogA");
   ptr_PdhRelogW = (__vartype(ptr_PdhRelogW))GetProcAddress(hModule, "PdhRelogW");
   ptr_PdhRemoveCounter = (__vartype(ptr_PdhRemoveCounter))GetProcAddress(hModule, "PdhRemoveCounter");
   ptr_PdhResetRelogCounterValues = (__vartype(ptr_PdhResetRelogCounterValues))GetProcAddress(hModule, "PdhResetRelogCounterValues");
   ptr_PdhSelectDataSourceA = (__vartype(ptr_PdhSelectDataSourceA))GetProcAddress(hModule, "PdhSelectDataSourceA");
   ptr_PdhSelectDataSourceW = (__vartype(ptr_PdhSelectDataSourceW))GetProcAddress(hModule, "PdhSelectDataSourceW");
   ptr_PdhSetCounterScaleFactor = (__vartype(ptr_PdhSetCounterScaleFactor))GetProcAddress(hModule, "PdhSetCounterScaleFactor");
   ptr_PdhSetCounterValue = (__vartype(ptr_PdhSetCounterValue))GetProcAddress(hModule, "PdhSetCounterValue");
   ptr_PdhSetDefaultRealTimeDataSource = (__vartype(ptr_PdhSetDefaultRealTimeDataSource))GetProcAddress(hModule, "PdhSetDefaultRealTimeDataSource");
   ptr_PdhSetLogSetRunID = (__vartype(ptr_PdhSetLogSetRunID))GetProcAddress(hModule, "PdhSetLogSetRunID");
   ptr_PdhSetQueryTimeRange = (__vartype(ptr_PdhSetQueryTimeRange))GetProcAddress(hModule, "PdhSetQueryTimeRange");
   ptr_PdhTranslate009CounterA = (__vartype(ptr_PdhTranslate009CounterA))GetProcAddress(hModule, "PdhTranslate009CounterA");
   ptr_PdhTranslate009CounterW = (__vartype(ptr_PdhTranslate009CounterW))GetProcAddress(hModule, "PdhTranslate009CounterW");
   ptr_PdhTranslateLocaleCounterA = (__vartype(ptr_PdhTranslateLocaleCounterA))GetProcAddress(hModule, "PdhTranslateLocaleCounterA");
   ptr_PdhTranslateLocaleCounterW = (__vartype(ptr_PdhTranslateLocaleCounterW))GetProcAddress(hModule, "PdhTranslateLocaleCounterW");
   ptr_PdhUpdateLogA = (__vartype(ptr_PdhUpdateLogA))GetProcAddress(hModule, "PdhUpdateLogA");
   ptr_PdhUpdateLogFileCatalog = (__vartype(ptr_PdhUpdateLogFileCatalog))GetProcAddress(hModule, "PdhUpdateLogFileCatalog");
   ptr_PdhUpdateLogW = (__vartype(ptr_PdhUpdateLogW))GetProcAddress(hModule, "PdhUpdateLogW");
   ptr_PdhValidatePathA = (__vartype(ptr_PdhValidatePathA))GetProcAddress(hModule, "PdhValidatePathA");
   ptr_PdhValidatePathExA = (__vartype(ptr_PdhValidatePathExA))GetProcAddress(hModule, "PdhValidatePathExA");
   ptr_PdhValidatePathExW = (__vartype(ptr_PdhValidatePathExW))GetProcAddress(hModule, "PdhValidatePathExW");
   ptr_PdhValidatePathW = (__vartype(ptr_PdhValidatePathW))GetProcAddress(hModule, "PdhValidatePathW");
   ptr_PdhVbAddCounter = (__vartype(ptr_PdhVbAddCounter))GetProcAddress(hModule, "PdhVbAddCounter");
   ptr_PdhVbCreateCounterPathList = (__vartype(ptr_PdhVbCreateCounterPathList))GetProcAddress(hModule, "PdhVbCreateCounterPathList");
   ptr_PdhVbGetCounterPathElements = (__vartype(ptr_PdhVbGetCounterPathElements))GetProcAddress(hModule, "PdhVbGetCounterPathElements");
   ptr_PdhVbGetCounterPathFromList = (__vartype(ptr_PdhVbGetCounterPathFromList))GetProcAddress(hModule, "PdhVbGetCounterPathFromList");
   ptr_PdhVbGetDoubleCounterValue = (__vartype(ptr_PdhVbGetDoubleCounterValue))GetProcAddress(hModule, "PdhVbGetDoubleCounterValue");
   ptr_PdhVbGetLogFileSize = (__vartype(ptr_PdhVbGetLogFileSize))GetProcAddress(hModule, "PdhVbGetLogFileSize");
   ptr_PdhVbGetOneCounterPath = (__vartype(ptr_PdhVbGetOneCounterPath))GetProcAddress(hModule, "PdhVbGetOneCounterPath");
   ptr_PdhVbIsGoodStatus = (__vartype(ptr_PdhVbIsGoodStatus))GetProcAddress(hModule, "PdhVbIsGoodStatus");
   ptr_PdhVbOpenLog = (__vartype(ptr_PdhVbOpenLog))GetProcAddress(hModule, "PdhVbOpenLog");
   ptr_PdhVbOpenQuery = (__vartype(ptr_PdhVbOpenQuery))GetProcAddress(hModule, "PdhVbOpenQuery");
   ptr_PdhVbUpdateLog = (__vartype(ptr_PdhVbUpdateLog))GetProcAddress(hModule, "PdhVbUpdateLog");
   ptr_PdhVerifySQLDBA = (__vartype(ptr_PdhVerifySQLDBA))GetProcAddress(hModule, "PdhVerifySQLDBA");
   ptr_PdhVerifySQLDBW = (__vartype(ptr_PdhVerifySQLDBW))GetProcAddress(hModule, "PdhVerifySQLDBW");
   ptr_PdhWriteRelogSample = (__vartype(ptr_PdhWriteRelogSample))GetProcAddress(hModule, "PdhWriteRelogSample");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

