#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr___glsParser_create;
void *ptr___glsParser_create = NULL;
extern void *ptr___glsParser_print;
void *ptr___glsParser_print = NULL;
extern void *ptr___glsString_appendChar;
void *ptr___glsString_appendChar = NULL;
extern void *ptr___glsString_assign;
void *ptr___glsString_assign = NULL;
extern void *ptr___glsString_init;
void *ptr___glsString_init = NULL;
extern void *ptr_glsAbortCall;
void *ptr_glsAbortCall = NULL;
extern void *ptr_glsAppRef;
void *ptr_glsAppRef = NULL;
extern void *ptr_glsBeginCapture;
void *ptr_glsBeginCapture = NULL;
extern void *ptr_glsBeginGLS;
void *ptr_glsBeginGLS = NULL;
extern void *ptr_glsBeginObj;
void *ptr_glsBeginObj = NULL;
extern void *ptr_glsBinary;
void *ptr_glsBinary = NULL;
extern void *ptr_glsBlock;
void *ptr_glsBlock = NULL;
extern void *ptr_glsCallArray;
void *ptr_glsCallArray = NULL;
extern void *ptr_glsCallArrayInContext;
void *ptr_glsCallArrayInContext = NULL;
extern void *ptr_glsCallStream;
void *ptr_glsCallStream = NULL;
extern void *ptr_glsCaptureFlags;
void *ptr_glsCaptureFlags = NULL;
extern void *ptr_glsCaptureFunc;
void *ptr_glsCaptureFunc = NULL;
extern void *ptr_glsChannel;
void *ptr_glsChannel = NULL;
extern void *ptr_glsCharubz;
void *ptr_glsCharubz = NULL;
extern void *ptr_glsCommandAPI;
void *ptr_glsCommandAPI = NULL;
extern void *ptr_glsCommandFunc;
void *ptr_glsCommandFunc = NULL;
extern void *ptr_glsCommandString;
void *ptr_glsCommandString = NULL;
extern void *ptr_glsComment;
void *ptr_glsComment = NULL;
extern void *ptr_glsContext;
void *ptr_glsContext = NULL;
extern void *ptr_glsCopyStream;
void *ptr_glsCopyStream = NULL;
extern void *ptr_glsDataPointer;
void *ptr_glsDataPointer = NULL;
extern void *ptr_glsDeleteContext;
void *ptr_glsDeleteContext = NULL;
extern void *ptr_glsDeleteReadPrefix;
void *ptr_glsDeleteReadPrefix = NULL;
extern void *ptr_glsDeleteStream;
void *ptr_glsDeleteStream = NULL;
extern void *ptr_glsDisplayMapfv;
void *ptr_glsDisplayMapfv = NULL;
extern void *ptr_glsEndCapture;
void *ptr_glsEndCapture = NULL;
extern void *ptr_glsEndGLS;
void *ptr_glsEndGLS = NULL;
extern void *ptr_glsEndObj;
void *ptr_glsEndObj = NULL;
extern void *ptr_glsEnumString;
void *ptr_glsEnumString = NULL;
extern void *ptr_glsError;
void *ptr_glsError = NULL;
extern void *ptr_glsFlush;
void *ptr_glsFlush = NULL;
extern void *ptr_glsGLRC;
void *ptr_glsGLRC = NULL;
extern void *ptr_glsGLRCLayer;
void *ptr_glsGLRCLayer = NULL;
extern void *ptr_glsGenContext;
void *ptr_glsGenContext = NULL;
extern void *ptr_glsGetAllContexts;
void *ptr_glsGetAllContexts = NULL;
extern void *ptr_glsGetCaptureDispatchTable;
void *ptr_glsGetCaptureDispatchTable = NULL;
extern void *ptr_glsGetCaptureExecTable;
void *ptr_glsGetCaptureExecTable = NULL;
extern void *ptr_glsGetCaptureFlags;
void *ptr_glsGetCaptureFlags = NULL;
extern void *ptr_glsGetCommandAlignment;
void *ptr_glsGetCommandAlignment = NULL;
extern void *ptr_glsGetCommandAttrib;
void *ptr_glsGetCommandAttrib = NULL;
extern void *ptr_glsGetCommandFunc;
void *ptr_glsGetCommandFunc = NULL;
extern void *ptr_glsGetConsti;
void *ptr_glsGetConsti = NULL;
extern void *ptr_glsGetConstiv;
void *ptr_glsGetConstiv = NULL;
extern void *ptr_glsGetConstubz;
void *ptr_glsGetConstubz = NULL;
extern void *ptr_glsGetContextFunc;
void *ptr_glsGetContextFunc = NULL;
extern void *ptr_glsGetContextListl;
void *ptr_glsGetContextListl = NULL;
extern void *ptr_glsGetContextListubz;
void *ptr_glsGetContextListubz = NULL;
extern void *ptr_glsGetContextPointer;
void *ptr_glsGetContextPointer = NULL;
extern void *ptr_glsGetContexti;
void *ptr_glsGetContexti = NULL;
extern void *ptr_glsGetContextubz;
void *ptr_glsGetContextubz = NULL;
extern void *ptr_glsGetCurrentContext;
void *ptr_glsGetCurrentContext = NULL;
extern void *ptr_glsGetCurrentTime;
void *ptr_glsGetCurrentTime = NULL;
extern void *ptr_glsGetError;
void *ptr_glsGetError = NULL;
extern void *ptr_glsGetGLRCi;
void *ptr_glsGetGLRCi = NULL;
extern void *ptr_glsGetHeaderf;
void *ptr_glsGetHeaderf = NULL;
extern void *ptr_glsGetHeaderfv;
void *ptr_glsGetHeaderfv = NULL;
extern void *ptr_glsGetHeaderi;
void *ptr_glsGetHeaderi = NULL;
extern void *ptr_glsGetHeaderiv;
void *ptr_glsGetHeaderiv = NULL;
extern void *ptr_glsGetHeaderubz;
void *ptr_glsGetHeaderubz = NULL;
extern void *ptr_glsGetLayerf;
void *ptr_glsGetLayerf = NULL;
extern void *ptr_glsGetLayeri;
void *ptr_glsGetLayeri = NULL;
extern void *ptr_glsGetOpcodeCount;
void *ptr_glsGetOpcodeCount = NULL;
extern void *ptr_glsGetOpcodes;
void *ptr_glsGetOpcodes = NULL;
extern void *ptr_glsGetStreamAttrib;
void *ptr_glsGetStreamAttrib = NULL;
extern void *ptr_glsGetStreamCRC32;
void *ptr_glsGetStreamCRC32 = NULL;
extern void *ptr_glsGetStreamReadName;
void *ptr_glsGetStreamReadName = NULL;
extern void *ptr_glsGetStreamSize;
void *ptr_glsGetStreamSize = NULL;
extern void *ptr_glsGetStreamType;
void *ptr_glsGetStreamType = NULL;
extern void *ptr_glsHeaderGLRCi;
void *ptr_glsHeaderGLRCi = NULL;
extern void *ptr_glsHeaderLayerf;
void *ptr_glsHeaderLayerf = NULL;
extern void *ptr_glsHeaderLayeri;
void *ptr_glsHeaderLayeri = NULL;
extern void *ptr_glsHeaderf;
void *ptr_glsHeaderf = NULL;
extern void *ptr_glsHeaderfv;
void *ptr_glsHeaderfv = NULL;
extern void *ptr_glsHeaderi;
void *ptr_glsHeaderi = NULL;
extern void *ptr_glsHeaderiv;
void *ptr_glsHeaderiv = NULL;
extern void *ptr_glsHeaderubz;
void *ptr_glsHeaderubz = NULL;
extern void *ptr_glsIsContext;
void *ptr_glsIsContext = NULL;
extern void *ptr_glsIsContextStream;
void *ptr_glsIsContextStream = NULL;
extern void *ptr_glsIsExtensionSupported;
void *ptr_glsIsExtensionSupported = NULL;
extern void *ptr_glsIsUTF8String;
void *ptr_glsIsUTF8String = NULL;
extern void *ptr_glsLong;
void *ptr_glsLong = NULL;
extern void *ptr_glsLongHigh;
void *ptr_glsLongHigh = NULL;
extern void *ptr_glsLongLow;
void *ptr_glsLongLow = NULL;
extern void *ptr_glsNullCommandFunc;
void *ptr_glsNullCommandFunc = NULL;
extern void *ptr_glsNumb;
void *ptr_glsNumb = NULL;
extern void *ptr_glsNumbv;
void *ptr_glsNumbv = NULL;
extern void *ptr_glsNumd;
void *ptr_glsNumd = NULL;
extern void *ptr_glsNumdv;
void *ptr_glsNumdv = NULL;
extern void *ptr_glsNumf;
void *ptr_glsNumf = NULL;
extern void *ptr_glsNumfv;
void *ptr_glsNumfv = NULL;
extern void *ptr_glsNumi;
void *ptr_glsNumi = NULL;
extern void *ptr_glsNumiv;
void *ptr_glsNumiv = NULL;
extern void *ptr_glsNuml;
void *ptr_glsNuml = NULL;
extern void *ptr_glsNumlv;
void *ptr_glsNumlv = NULL;
extern void *ptr_glsNums;
void *ptr_glsNums = NULL;
extern void *ptr_glsNumsv;
void *ptr_glsNumsv = NULL;
extern void *ptr_glsNumub;
void *ptr_glsNumub = NULL;
extern void *ptr_glsNumubv;
void *ptr_glsNumubv = NULL;
extern void *ptr_glsNumui;
void *ptr_glsNumui = NULL;
extern void *ptr_glsNumuiv;
void *ptr_glsNumuiv = NULL;
extern void *ptr_glsNumul;
void *ptr_glsNumul = NULL;
extern void *ptr_glsNumulv;
void *ptr_glsNumulv = NULL;
extern void *ptr_glsNumus;
void *ptr_glsNumus = NULL;
extern void *ptr_glsNumusv;
void *ptr_glsNumusv = NULL;
extern void *ptr_glsPad;
void *ptr_glsPad = NULL;
extern void *ptr_glsPixelSetup;
void *ptr_glsPixelSetup = NULL;
extern void *ptr_glsPixelSetupGen;
void *ptr_glsPixelSetupGen = NULL;
extern void *ptr_glsReadFunc;
void *ptr_glsReadFunc = NULL;
extern void *ptr_glsReadPrefix;
void *ptr_glsReadPrefix = NULL;
extern void *ptr_glsRequireExtension;
void *ptr_glsRequireExtension = NULL;
extern void *ptr_glsSwapBuffers;
void *ptr_glsSwapBuffers = NULL;
extern void *ptr_glsUCS1toUTF8z;
void *ptr_glsUCS1toUTF8z = NULL;
extern void *ptr_glsUCS2toUTF8z;
void *ptr_glsUCS2toUTF8z = NULL;
extern void *ptr_glsUCS4toUTF8;
void *ptr_glsUCS4toUTF8 = NULL;
extern void *ptr_glsUCS4toUTF8z;
void *ptr_glsUCS4toUTF8z = NULL;
extern void *ptr_glsUCStoUTF8z;
void *ptr_glsUCStoUTF8z = NULL;
extern void *ptr_glsULong;
void *ptr_glsULong = NULL;
extern void *ptr_glsULongHigh;
void *ptr_glsULongHigh = NULL;
extern void *ptr_glsULongLow;
void *ptr_glsULongLow = NULL;
extern void *ptr_glsUTF8toUCS1z;
void *ptr_glsUTF8toUCS1z = NULL;
extern void *ptr_glsUTF8toUCS2z;
void *ptr_glsUTF8toUCS2z = NULL;
extern void *ptr_glsUTF8toUCS4;
void *ptr_glsUTF8toUCS4 = NULL;
extern void *ptr_glsUTF8toUCS4z;
void *ptr_glsUTF8toUCS4z = NULL;
extern void *ptr_glsUTF8toUCSz;
void *ptr_glsUTF8toUCSz = NULL;
extern void *ptr_glsUnreadFunc;
void *ptr_glsUnreadFunc = NULL;
extern void *ptr_glsUnsupportedCommand;
void *ptr_glsUnsupportedCommand = NULL;
extern void *ptr_glsUpdateCaptureExecTable;
void *ptr_glsUpdateCaptureExecTable = NULL;
extern void *ptr_glsWriteFunc;
void *ptr_glsWriteFunc = NULL;
extern void *ptr_glsWritePrefix;
void *ptr_glsWritePrefix = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\glmf32.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr___glsParser_create = (__vartype(ptr___glsParser_create))GetProcAddress(hModule, "__glsParser_create");
   ptr___glsParser_print = (__vartype(ptr___glsParser_print))GetProcAddress(hModule, "__glsParser_print");
   ptr___glsString_appendChar = (__vartype(ptr___glsString_appendChar))GetProcAddress(hModule, "__glsString_appendChar");
   ptr___glsString_assign = (__vartype(ptr___glsString_assign))GetProcAddress(hModule, "__glsString_assign");
   ptr___glsString_init = (__vartype(ptr___glsString_init))GetProcAddress(hModule, "__glsString_init");
   ptr_glsAbortCall = (__vartype(ptr_glsAbortCall))GetProcAddress(hModule, "glsAbortCall");
   ptr_glsAppRef = (__vartype(ptr_glsAppRef))GetProcAddress(hModule, "glsAppRef");
   ptr_glsBeginCapture = (__vartype(ptr_glsBeginCapture))GetProcAddress(hModule, "glsBeginCapture");
   ptr_glsBeginGLS = (__vartype(ptr_glsBeginGLS))GetProcAddress(hModule, "glsBeginGLS");
   ptr_glsBeginObj = (__vartype(ptr_glsBeginObj))GetProcAddress(hModule, "glsBeginObj");
   ptr_glsBinary = (__vartype(ptr_glsBinary))GetProcAddress(hModule, "glsBinary");
   ptr_glsBlock = (__vartype(ptr_glsBlock))GetProcAddress(hModule, "glsBlock");
   ptr_glsCallArray = (__vartype(ptr_glsCallArray))GetProcAddress(hModule, "glsCallArray");
   ptr_glsCallArrayInContext = (__vartype(ptr_glsCallArrayInContext))GetProcAddress(hModule, "glsCallArrayInContext");
   ptr_glsCallStream = (__vartype(ptr_glsCallStream))GetProcAddress(hModule, "glsCallStream");
   ptr_glsCaptureFlags = (__vartype(ptr_glsCaptureFlags))GetProcAddress(hModule, "glsCaptureFlags");
   ptr_glsCaptureFunc = (__vartype(ptr_glsCaptureFunc))GetProcAddress(hModule, "glsCaptureFunc");
   ptr_glsChannel = (__vartype(ptr_glsChannel))GetProcAddress(hModule, "glsChannel");
   ptr_glsCharubz = (__vartype(ptr_glsCharubz))GetProcAddress(hModule, "glsCharubz");
   ptr_glsCommandAPI = (__vartype(ptr_glsCommandAPI))GetProcAddress(hModule, "glsCommandAPI");
   ptr_glsCommandFunc = (__vartype(ptr_glsCommandFunc))GetProcAddress(hModule, "glsCommandFunc");
   ptr_glsCommandString = (__vartype(ptr_glsCommandString))GetProcAddress(hModule, "glsCommandString");
   ptr_glsComment = (__vartype(ptr_glsComment))GetProcAddress(hModule, "glsComment");
   ptr_glsContext = (__vartype(ptr_glsContext))GetProcAddress(hModule, "glsContext");
   ptr_glsCopyStream = (__vartype(ptr_glsCopyStream))GetProcAddress(hModule, "glsCopyStream");
   ptr_glsDataPointer = (__vartype(ptr_glsDataPointer))GetProcAddress(hModule, "glsDataPointer");
   ptr_glsDeleteContext = (__vartype(ptr_glsDeleteContext))GetProcAddress(hModule, "glsDeleteContext");
   ptr_glsDeleteReadPrefix = (__vartype(ptr_glsDeleteReadPrefix))GetProcAddress(hModule, "glsDeleteReadPrefix");
   ptr_glsDeleteStream = (__vartype(ptr_glsDeleteStream))GetProcAddress(hModule, "glsDeleteStream");
   ptr_glsDisplayMapfv = (__vartype(ptr_glsDisplayMapfv))GetProcAddress(hModule, "glsDisplayMapfv");
   ptr_glsEndCapture = (__vartype(ptr_glsEndCapture))GetProcAddress(hModule, "glsEndCapture");
   ptr_glsEndGLS = (__vartype(ptr_glsEndGLS))GetProcAddress(hModule, "glsEndGLS");
   ptr_glsEndObj = (__vartype(ptr_glsEndObj))GetProcAddress(hModule, "glsEndObj");
   ptr_glsEnumString = (__vartype(ptr_glsEnumString))GetProcAddress(hModule, "glsEnumString");
   ptr_glsError = (__vartype(ptr_glsError))GetProcAddress(hModule, "glsError");
   ptr_glsFlush = (__vartype(ptr_glsFlush))GetProcAddress(hModule, "glsFlush");
   ptr_glsGLRC = (__vartype(ptr_glsGLRC))GetProcAddress(hModule, "glsGLRC");
   ptr_glsGLRCLayer = (__vartype(ptr_glsGLRCLayer))GetProcAddress(hModule, "glsGLRCLayer");
   ptr_glsGenContext = (__vartype(ptr_glsGenContext))GetProcAddress(hModule, "glsGenContext");
   ptr_glsGetAllContexts = (__vartype(ptr_glsGetAllContexts))GetProcAddress(hModule, "glsGetAllContexts");
   ptr_glsGetCaptureDispatchTable = (__vartype(ptr_glsGetCaptureDispatchTable))GetProcAddress(hModule, "glsGetCaptureDispatchTable");
   ptr_glsGetCaptureExecTable = (__vartype(ptr_glsGetCaptureExecTable))GetProcAddress(hModule, "glsGetCaptureExecTable");
   ptr_glsGetCaptureFlags = (__vartype(ptr_glsGetCaptureFlags))GetProcAddress(hModule, "glsGetCaptureFlags");
   ptr_glsGetCommandAlignment = (__vartype(ptr_glsGetCommandAlignment))GetProcAddress(hModule, "glsGetCommandAlignment");
   ptr_glsGetCommandAttrib = (__vartype(ptr_glsGetCommandAttrib))GetProcAddress(hModule, "glsGetCommandAttrib");
   ptr_glsGetCommandFunc = (__vartype(ptr_glsGetCommandFunc))GetProcAddress(hModule, "glsGetCommandFunc");
   ptr_glsGetConsti = (__vartype(ptr_glsGetConsti))GetProcAddress(hModule, "glsGetConsti");
   ptr_glsGetConstiv = (__vartype(ptr_glsGetConstiv))GetProcAddress(hModule, "glsGetConstiv");
   ptr_glsGetConstubz = (__vartype(ptr_glsGetConstubz))GetProcAddress(hModule, "glsGetConstubz");
   ptr_glsGetContextFunc = (__vartype(ptr_glsGetContextFunc))GetProcAddress(hModule, "glsGetContextFunc");
   ptr_glsGetContextListl = (__vartype(ptr_glsGetContextListl))GetProcAddress(hModule, "glsGetContextListl");
   ptr_glsGetContextListubz = (__vartype(ptr_glsGetContextListubz))GetProcAddress(hModule, "glsGetContextListubz");
   ptr_glsGetContextPointer = (__vartype(ptr_glsGetContextPointer))GetProcAddress(hModule, "glsGetContextPointer");
   ptr_glsGetContexti = (__vartype(ptr_glsGetContexti))GetProcAddress(hModule, "glsGetContexti");
   ptr_glsGetContextubz = (__vartype(ptr_glsGetContextubz))GetProcAddress(hModule, "glsGetContextubz");
   ptr_glsGetCurrentContext = (__vartype(ptr_glsGetCurrentContext))GetProcAddress(hModule, "glsGetCurrentContext");
   ptr_glsGetCurrentTime = (__vartype(ptr_glsGetCurrentTime))GetProcAddress(hModule, "glsGetCurrentTime");
   ptr_glsGetError = (__vartype(ptr_glsGetError))GetProcAddress(hModule, "glsGetError");
   ptr_glsGetGLRCi = (__vartype(ptr_glsGetGLRCi))GetProcAddress(hModule, "glsGetGLRCi");
   ptr_glsGetHeaderf = (__vartype(ptr_glsGetHeaderf))GetProcAddress(hModule, "glsGetHeaderf");
   ptr_glsGetHeaderfv = (__vartype(ptr_glsGetHeaderfv))GetProcAddress(hModule, "glsGetHeaderfv");
   ptr_glsGetHeaderi = (__vartype(ptr_glsGetHeaderi))GetProcAddress(hModule, "glsGetHeaderi");
   ptr_glsGetHeaderiv = (__vartype(ptr_glsGetHeaderiv))GetProcAddress(hModule, "glsGetHeaderiv");
   ptr_glsGetHeaderubz = (__vartype(ptr_glsGetHeaderubz))GetProcAddress(hModule, "glsGetHeaderubz");
   ptr_glsGetLayerf = (__vartype(ptr_glsGetLayerf))GetProcAddress(hModule, "glsGetLayerf");
   ptr_glsGetLayeri = (__vartype(ptr_glsGetLayeri))GetProcAddress(hModule, "glsGetLayeri");
   ptr_glsGetOpcodeCount = (__vartype(ptr_glsGetOpcodeCount))GetProcAddress(hModule, "glsGetOpcodeCount");
   ptr_glsGetOpcodes = (__vartype(ptr_glsGetOpcodes))GetProcAddress(hModule, "glsGetOpcodes");
   ptr_glsGetStreamAttrib = (__vartype(ptr_glsGetStreamAttrib))GetProcAddress(hModule, "glsGetStreamAttrib");
   ptr_glsGetStreamCRC32 = (__vartype(ptr_glsGetStreamCRC32))GetProcAddress(hModule, "glsGetStreamCRC32");
   ptr_glsGetStreamReadName = (__vartype(ptr_glsGetStreamReadName))GetProcAddress(hModule, "glsGetStreamReadName");
   ptr_glsGetStreamSize = (__vartype(ptr_glsGetStreamSize))GetProcAddress(hModule, "glsGetStreamSize");
   ptr_glsGetStreamType = (__vartype(ptr_glsGetStreamType))GetProcAddress(hModule, "glsGetStreamType");
   ptr_glsHeaderGLRCi = (__vartype(ptr_glsHeaderGLRCi))GetProcAddress(hModule, "glsHeaderGLRCi");
   ptr_glsHeaderLayerf = (__vartype(ptr_glsHeaderLayerf))GetProcAddress(hModule, "glsHeaderLayerf");
   ptr_glsHeaderLayeri = (__vartype(ptr_glsHeaderLayeri))GetProcAddress(hModule, "glsHeaderLayeri");
   ptr_glsHeaderf = (__vartype(ptr_glsHeaderf))GetProcAddress(hModule, "glsHeaderf");
   ptr_glsHeaderfv = (__vartype(ptr_glsHeaderfv))GetProcAddress(hModule, "glsHeaderfv");
   ptr_glsHeaderi = (__vartype(ptr_glsHeaderi))GetProcAddress(hModule, "glsHeaderi");
   ptr_glsHeaderiv = (__vartype(ptr_glsHeaderiv))GetProcAddress(hModule, "glsHeaderiv");
   ptr_glsHeaderubz = (__vartype(ptr_glsHeaderubz))GetProcAddress(hModule, "glsHeaderubz");
   ptr_glsIsContext = (__vartype(ptr_glsIsContext))GetProcAddress(hModule, "glsIsContext");
   ptr_glsIsContextStream = (__vartype(ptr_glsIsContextStream))GetProcAddress(hModule, "glsIsContextStream");
   ptr_glsIsExtensionSupported = (__vartype(ptr_glsIsExtensionSupported))GetProcAddress(hModule, "glsIsExtensionSupported");
   ptr_glsIsUTF8String = (__vartype(ptr_glsIsUTF8String))GetProcAddress(hModule, "glsIsUTF8String");
   ptr_glsLong = (__vartype(ptr_glsLong))GetProcAddress(hModule, "glsLong");
   ptr_glsLongHigh = (__vartype(ptr_glsLongHigh))GetProcAddress(hModule, "glsLongHigh");
   ptr_glsLongLow = (__vartype(ptr_glsLongLow))GetProcAddress(hModule, "glsLongLow");
   ptr_glsNullCommandFunc = (__vartype(ptr_glsNullCommandFunc))GetProcAddress(hModule, "glsNullCommandFunc");
   ptr_glsNumb = (__vartype(ptr_glsNumb))GetProcAddress(hModule, "glsNumb");
   ptr_glsNumbv = (__vartype(ptr_glsNumbv))GetProcAddress(hModule, "glsNumbv");
   ptr_glsNumd = (__vartype(ptr_glsNumd))GetProcAddress(hModule, "glsNumd");
   ptr_glsNumdv = (__vartype(ptr_glsNumdv))GetProcAddress(hModule, "glsNumdv");
   ptr_glsNumf = (__vartype(ptr_glsNumf))GetProcAddress(hModule, "glsNumf");
   ptr_glsNumfv = (__vartype(ptr_glsNumfv))GetProcAddress(hModule, "glsNumfv");
   ptr_glsNumi = (__vartype(ptr_glsNumi))GetProcAddress(hModule, "glsNumi");
   ptr_glsNumiv = (__vartype(ptr_glsNumiv))GetProcAddress(hModule, "glsNumiv");
   ptr_glsNuml = (__vartype(ptr_glsNuml))GetProcAddress(hModule, "glsNuml");
   ptr_glsNumlv = (__vartype(ptr_glsNumlv))GetProcAddress(hModule, "glsNumlv");
   ptr_glsNums = (__vartype(ptr_glsNums))GetProcAddress(hModule, "glsNums");
   ptr_glsNumsv = (__vartype(ptr_glsNumsv))GetProcAddress(hModule, "glsNumsv");
   ptr_glsNumub = (__vartype(ptr_glsNumub))GetProcAddress(hModule, "glsNumub");
   ptr_glsNumubv = (__vartype(ptr_glsNumubv))GetProcAddress(hModule, "glsNumubv");
   ptr_glsNumui = (__vartype(ptr_glsNumui))GetProcAddress(hModule, "glsNumui");
   ptr_glsNumuiv = (__vartype(ptr_glsNumuiv))GetProcAddress(hModule, "glsNumuiv");
   ptr_glsNumul = (__vartype(ptr_glsNumul))GetProcAddress(hModule, "glsNumul");
   ptr_glsNumulv = (__vartype(ptr_glsNumulv))GetProcAddress(hModule, "glsNumulv");
   ptr_glsNumus = (__vartype(ptr_glsNumus))GetProcAddress(hModule, "glsNumus");
   ptr_glsNumusv = (__vartype(ptr_glsNumusv))GetProcAddress(hModule, "glsNumusv");
   ptr_glsPad = (__vartype(ptr_glsPad))GetProcAddress(hModule, "glsPad");
   ptr_glsPixelSetup = (__vartype(ptr_glsPixelSetup))GetProcAddress(hModule, "glsPixelSetup");
   ptr_glsPixelSetupGen = (__vartype(ptr_glsPixelSetupGen))GetProcAddress(hModule, "glsPixelSetupGen");
   ptr_glsReadFunc = (__vartype(ptr_glsReadFunc))GetProcAddress(hModule, "glsReadFunc");
   ptr_glsReadPrefix = (__vartype(ptr_glsReadPrefix))GetProcAddress(hModule, "glsReadPrefix");
   ptr_glsRequireExtension = (__vartype(ptr_glsRequireExtension))GetProcAddress(hModule, "glsRequireExtension");
   ptr_glsSwapBuffers = (__vartype(ptr_glsSwapBuffers))GetProcAddress(hModule, "glsSwapBuffers");
   ptr_glsUCS1toUTF8z = (__vartype(ptr_glsUCS1toUTF8z))GetProcAddress(hModule, "glsUCS1toUTF8z");
   ptr_glsUCS2toUTF8z = (__vartype(ptr_glsUCS2toUTF8z))GetProcAddress(hModule, "glsUCS2toUTF8z");
   ptr_glsUCS4toUTF8 = (__vartype(ptr_glsUCS4toUTF8))GetProcAddress(hModule, "glsUCS4toUTF8");
   ptr_glsUCS4toUTF8z = (__vartype(ptr_glsUCS4toUTF8z))GetProcAddress(hModule, "glsUCS4toUTF8z");
   ptr_glsUCStoUTF8z = (__vartype(ptr_glsUCStoUTF8z))GetProcAddress(hModule, "glsUCStoUTF8z");
   ptr_glsULong = (__vartype(ptr_glsULong))GetProcAddress(hModule, "glsULong");
   ptr_glsULongHigh = (__vartype(ptr_glsULongHigh))GetProcAddress(hModule, "glsULongHigh");
   ptr_glsULongLow = (__vartype(ptr_glsULongLow))GetProcAddress(hModule, "glsULongLow");
   ptr_glsUTF8toUCS1z = (__vartype(ptr_glsUTF8toUCS1z))GetProcAddress(hModule, "glsUTF8toUCS1z");
   ptr_glsUTF8toUCS2z = (__vartype(ptr_glsUTF8toUCS2z))GetProcAddress(hModule, "glsUTF8toUCS2z");
   ptr_glsUTF8toUCS4 = (__vartype(ptr_glsUTF8toUCS4))GetProcAddress(hModule, "glsUTF8toUCS4");
   ptr_glsUTF8toUCS4z = (__vartype(ptr_glsUTF8toUCS4z))GetProcAddress(hModule, "glsUTF8toUCS4z");
   ptr_glsUTF8toUCSz = (__vartype(ptr_glsUTF8toUCSz))GetProcAddress(hModule, "glsUTF8toUCSz");
   ptr_glsUnreadFunc = (__vartype(ptr_glsUnreadFunc))GetProcAddress(hModule, "glsUnreadFunc");
   ptr_glsUnsupportedCommand = (__vartype(ptr_glsUnsupportedCommand))GetProcAddress(hModule, "glsUnsupportedCommand");
   ptr_glsUpdateCaptureExecTable = (__vartype(ptr_glsUpdateCaptureExecTable))GetProcAddress(hModule, "glsUpdateCaptureExecTable");
   ptr_glsWriteFunc = (__vartype(ptr_glsWriteFunc))GetProcAddress(hModule, "glsWriteFunc");
   ptr_glsWritePrefix = (__vartype(ptr_glsWritePrefix))GetProcAddress(hModule, "glsWritePrefix");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

