#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_DDMFreePhonebookContext;
void *ptr_DDMFreePhonebookContext = NULL;
extern void *ptr_DDMGetPhonebookInfo;
void *ptr_DDMGetPhonebookInfo = NULL;
extern void *ptr_DwCloneEntry;
void *ptr_DwCloneEntry = NULL;
extern void *ptr_DwEnumEntryDetails;
void *ptr_DwEnumEntryDetails = NULL;
extern void *ptr_DwRasUninitialize;
void *ptr_DwRasUninitialize = NULL;
extern void *ptr_RasAutoDialSharedConnection;
void *ptr_RasAutoDialSharedConnection = NULL;
extern void *ptr_RasAutodialAddressToNetwork;
void *ptr_RasAutodialAddressToNetwork = NULL;
extern void *ptr_RasAutodialEntryToNetwork;
void *ptr_RasAutodialEntryToNetwork = NULL;
extern void *ptr_RasClearConnectionStatistics;
void *ptr_RasClearConnectionStatistics = NULL;
extern void *ptr_RasClearLinkStatistics;
void *ptr_RasClearLinkStatistics = NULL;
extern void *ptr_RasConnectionNotificationA;
void *ptr_RasConnectionNotificationA = NULL;
extern void *ptr_RasConnectionNotificationW;
void *ptr_RasConnectionNotificationW = NULL;
extern void *ptr_RasCreatePhonebookEntryA;
void *ptr_RasCreatePhonebookEntryA = NULL;
extern void *ptr_RasCreatePhonebookEntryW;
void *ptr_RasCreatePhonebookEntryW = NULL;
extern void *ptr_RasDeleteEntryA;
void *ptr_RasDeleteEntryA = NULL;
extern void *ptr_RasDeleteEntryW;
void *ptr_RasDeleteEntryW = NULL;
extern void *ptr_RasDeleteSubEntryA;
void *ptr_RasDeleteSubEntryA = NULL;
extern void *ptr_RasDeleteSubEntryW;
void *ptr_RasDeleteSubEntryW = NULL;
extern void *ptr_RasDialA;
void *ptr_RasDialA = NULL;
extern void *ptr_RasDialW;
void *ptr_RasDialW = NULL;
extern void *ptr_RasEditPhonebookEntryA;
void *ptr_RasEditPhonebookEntryA = NULL;
extern void *ptr_RasEditPhonebookEntryW;
void *ptr_RasEditPhonebookEntryW = NULL;
extern void *ptr_RasEnumAutodialAddressesA;
void *ptr_RasEnumAutodialAddressesA = NULL;
extern void *ptr_RasEnumAutodialAddressesW;
void *ptr_RasEnumAutodialAddressesW = NULL;
extern void *ptr_RasEnumConnectionsA;
void *ptr_RasEnumConnectionsA = NULL;
extern void *ptr_RasEnumConnectionsW;
void *ptr_RasEnumConnectionsW = NULL;
extern void *ptr_RasEnumDevicesA;
void *ptr_RasEnumDevicesA = NULL;
extern void *ptr_RasEnumDevicesW;
void *ptr_RasEnumDevicesW = NULL;
extern void *ptr_RasEnumEntriesA;
void *ptr_RasEnumEntriesA = NULL;
extern void *ptr_RasEnumEntriesW;
void *ptr_RasEnumEntriesW = NULL;
extern void *ptr_RasFreeEapUserIdentityA;
void *ptr_RasFreeEapUserIdentityA = NULL;
extern void *ptr_RasFreeEapUserIdentityW;
void *ptr_RasFreeEapUserIdentityW = NULL;
extern void *ptr_RasGetAutodialAddressA;
void *ptr_RasGetAutodialAddressA = NULL;
extern void *ptr_RasGetAutodialAddressW;
void *ptr_RasGetAutodialAddressW = NULL;
extern void *ptr_RasGetAutodialEnableA;
void *ptr_RasGetAutodialEnableA = NULL;
extern void *ptr_RasGetAutodialEnableW;
void *ptr_RasGetAutodialEnableW = NULL;
extern void *ptr_RasGetAutodialParamA;
void *ptr_RasGetAutodialParamA = NULL;
extern void *ptr_RasGetAutodialParamW;
void *ptr_RasGetAutodialParamW = NULL;
extern void *ptr_RasGetConnectStatusA;
void *ptr_RasGetConnectStatusA = NULL;
extern void *ptr_RasGetConnectStatusW;
void *ptr_RasGetConnectStatusW = NULL;
extern void *ptr_RasGetConnectionStatistics;
void *ptr_RasGetConnectionStatistics = NULL;
extern void *ptr_RasGetCountryInfoA;
void *ptr_RasGetCountryInfoA = NULL;
extern void *ptr_RasGetCountryInfoW;
void *ptr_RasGetCountryInfoW = NULL;
extern void *ptr_RasGetCredentialsA;
void *ptr_RasGetCredentialsA = NULL;
extern void *ptr_RasGetCredentialsW;
void *ptr_RasGetCredentialsW = NULL;
extern void *ptr_RasGetCustomAuthDataA;
void *ptr_RasGetCustomAuthDataA = NULL;
extern void *ptr_RasGetCustomAuthDataW;
void *ptr_RasGetCustomAuthDataW = NULL;
extern void *ptr_RasGetEapUserDataA;
void *ptr_RasGetEapUserDataA = NULL;
extern void *ptr_RasGetEapUserDataW;
void *ptr_RasGetEapUserDataW = NULL;
extern void *ptr_RasGetEapUserIdentityA;
void *ptr_RasGetEapUserIdentityA = NULL;
extern void *ptr_RasGetEapUserIdentityW;
void *ptr_RasGetEapUserIdentityW = NULL;
extern void *ptr_RasGetEntryDialParamsA;
void *ptr_RasGetEntryDialParamsA = NULL;
extern void *ptr_RasGetEntryDialParamsW;
void *ptr_RasGetEntryDialParamsW = NULL;
extern void *ptr_RasGetEntryHrasconnW;
void *ptr_RasGetEntryHrasconnW = NULL;
extern void *ptr_RasGetEntryPropertiesA;
void *ptr_RasGetEntryPropertiesA = NULL;
extern void *ptr_RasGetEntryPropertiesW;
void *ptr_RasGetEntryPropertiesW = NULL;
extern void *ptr_RasGetErrorStringA;
void *ptr_RasGetErrorStringA = NULL;
extern void *ptr_RasGetErrorStringW;
void *ptr_RasGetErrorStringW = NULL;
extern void *ptr_RasGetHport;
void *ptr_RasGetHport = NULL;
extern void *ptr_RasGetLinkStatistics;
void *ptr_RasGetLinkStatistics = NULL;
extern void *ptr_RasGetNapStatus;
void *ptr_RasGetNapStatus = NULL;
extern void *ptr_RasGetProjectionInfoA;
void *ptr_RasGetProjectionInfoA = NULL;
extern void *ptr_RasGetProjectionInfoEx;
void *ptr_RasGetProjectionInfoEx = NULL;
extern void *ptr_RasGetProjectionInfoW;
void *ptr_RasGetProjectionInfoW = NULL;
extern void *ptr_RasGetSubEntryHandleA;
void *ptr_RasGetSubEntryHandleA = NULL;
extern void *ptr_RasGetSubEntryHandleW;
void *ptr_RasGetSubEntryHandleW = NULL;
extern void *ptr_RasGetSubEntryPropertiesA;
void *ptr_RasGetSubEntryPropertiesA = NULL;
extern void *ptr_RasGetSubEntryPropertiesW;
void *ptr_RasGetSubEntryPropertiesW = NULL;
extern void *ptr_RasHangUpA;
void *ptr_RasHangUpA = NULL;
extern void *ptr_RasHangUpW;
void *ptr_RasHangUpW = NULL;
extern void *ptr_RasInvokeEapUI;
void *ptr_RasInvokeEapUI = NULL;
extern void *ptr_RasIsPublicPhonebook;
void *ptr_RasIsPublicPhonebook = NULL;
extern void *ptr_RasIsSharedConnection;
void *ptr_RasIsSharedConnection = NULL;
extern void *ptr_RasQueryRedialOnLinkFailure;
void *ptr_RasQueryRedialOnLinkFailure = NULL;
extern void *ptr_RasQuerySharedAutoDial;
void *ptr_RasQuerySharedAutoDial = NULL;
extern void *ptr_RasQuerySharedConnection;
void *ptr_RasQuerySharedConnection = NULL;
extern void *ptr_RasRenameEntryA;
void *ptr_RasRenameEntryA = NULL;
extern void *ptr_RasRenameEntryW;
void *ptr_RasRenameEntryW = NULL;
extern void *ptr_RasScriptGetIpAddress;
void *ptr_RasScriptGetIpAddress = NULL;
extern void *ptr_RasScriptInit;
void *ptr_RasScriptInit = NULL;
extern void *ptr_RasScriptReceive;
void *ptr_RasScriptReceive = NULL;
extern void *ptr_RasScriptSend;
void *ptr_RasScriptSend = NULL;
extern void *ptr_RasScriptTerm;
void *ptr_RasScriptTerm = NULL;
extern void *ptr_RasSetAutodialAddressA;
void *ptr_RasSetAutodialAddressA = NULL;
extern void *ptr_RasSetAutodialAddressW;
void *ptr_RasSetAutodialAddressW = NULL;
extern void *ptr_RasSetAutodialEnableA;
void *ptr_RasSetAutodialEnableA = NULL;
extern void *ptr_RasSetAutodialEnableW;
void *ptr_RasSetAutodialEnableW = NULL;
extern void *ptr_RasSetAutodialParamA;
void *ptr_RasSetAutodialParamA = NULL;
extern void *ptr_RasSetAutodialParamW;
void *ptr_RasSetAutodialParamW = NULL;
extern void *ptr_RasSetCredentialsA;
void *ptr_RasSetCredentialsA = NULL;
extern void *ptr_RasSetCredentialsW;
void *ptr_RasSetCredentialsW = NULL;
extern void *ptr_RasSetCustomAuthDataA;
void *ptr_RasSetCustomAuthDataA = NULL;
extern void *ptr_RasSetCustomAuthDataW;
void *ptr_RasSetCustomAuthDataW = NULL;
extern void *ptr_RasSetEapUserDataA;
void *ptr_RasSetEapUserDataA = NULL;
extern void *ptr_RasSetEapUserDataW;
void *ptr_RasSetEapUserDataW = NULL;
extern void *ptr_RasSetEntryDialParamsA;
void *ptr_RasSetEntryDialParamsA = NULL;
extern void *ptr_RasSetEntryDialParamsW;
void *ptr_RasSetEntryDialParamsW = NULL;
extern void *ptr_RasSetEntryPropertiesA;
void *ptr_RasSetEntryPropertiesA = NULL;
extern void *ptr_RasSetEntryPropertiesW;
void *ptr_RasSetEntryPropertiesW = NULL;
extern void *ptr_RasSetOldPassword;
void *ptr_RasSetOldPassword = NULL;
extern void *ptr_RasSetSharedAutoDial;
void *ptr_RasSetSharedAutoDial = NULL;
extern void *ptr_RasSetSubEntryPropertiesA;
void *ptr_RasSetSubEntryPropertiesA = NULL;
extern void *ptr_RasSetSubEntryPropertiesW;
void *ptr_RasSetSubEntryPropertiesW = NULL;
extern void *ptr_RasUpdateConnection;
void *ptr_RasUpdateConnection = NULL;
extern void *ptr_RasValidateEntryNameA;
void *ptr_RasValidateEntryNameA = NULL;
extern void *ptr_RasValidateEntryNameW;
void *ptr_RasValidateEntryNameW = NULL;
extern void *ptr_RasWriteSharedPbkOptions;
void *ptr_RasWriteSharedPbkOptions = NULL;
extern void *ptr_UnInitializeRAS;
void *ptr_UnInitializeRAS = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\rasapi32.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_DDMFreePhonebookContext = (__vartype(ptr_DDMFreePhonebookContext))GetProcAddress(hModule, "DDMFreePhonebookContext");
   ptr_DDMGetPhonebookInfo = (__vartype(ptr_DDMGetPhonebookInfo))GetProcAddress(hModule, "DDMGetPhonebookInfo");
   ptr_DwCloneEntry = (__vartype(ptr_DwCloneEntry))GetProcAddress(hModule, "DwCloneEntry");
   ptr_DwEnumEntryDetails = (__vartype(ptr_DwEnumEntryDetails))GetProcAddress(hModule, "DwEnumEntryDetails");
   ptr_DwRasUninitialize = (__vartype(ptr_DwRasUninitialize))GetProcAddress(hModule, "DwRasUninitialize");
   ptr_RasAutoDialSharedConnection = (__vartype(ptr_RasAutoDialSharedConnection))GetProcAddress(hModule, "RasAutoDialSharedConnection");
   ptr_RasAutodialAddressToNetwork = (__vartype(ptr_RasAutodialAddressToNetwork))GetProcAddress(hModule, "RasAutodialAddressToNetwork");
   ptr_RasAutodialEntryToNetwork = (__vartype(ptr_RasAutodialEntryToNetwork))GetProcAddress(hModule, "RasAutodialEntryToNetwork");
   ptr_RasClearConnectionStatistics = (__vartype(ptr_RasClearConnectionStatistics))GetProcAddress(hModule, "RasClearConnectionStatistics");
   ptr_RasClearLinkStatistics = (__vartype(ptr_RasClearLinkStatistics))GetProcAddress(hModule, "RasClearLinkStatistics");
   ptr_RasConnectionNotificationA = (__vartype(ptr_RasConnectionNotificationA))GetProcAddress(hModule, "RasConnectionNotificationA");
   ptr_RasConnectionNotificationW = (__vartype(ptr_RasConnectionNotificationW))GetProcAddress(hModule, "RasConnectionNotificationW");
   ptr_RasCreatePhonebookEntryA = (__vartype(ptr_RasCreatePhonebookEntryA))GetProcAddress(hModule, "RasCreatePhonebookEntryA");
   ptr_RasCreatePhonebookEntryW = (__vartype(ptr_RasCreatePhonebookEntryW))GetProcAddress(hModule, "RasCreatePhonebookEntryW");
   ptr_RasDeleteEntryA = (__vartype(ptr_RasDeleteEntryA))GetProcAddress(hModule, "RasDeleteEntryA");
   ptr_RasDeleteEntryW = (__vartype(ptr_RasDeleteEntryW))GetProcAddress(hModule, "RasDeleteEntryW");
   ptr_RasDeleteSubEntryA = (__vartype(ptr_RasDeleteSubEntryA))GetProcAddress(hModule, "RasDeleteSubEntryA");
   ptr_RasDeleteSubEntryW = (__vartype(ptr_RasDeleteSubEntryW))GetProcAddress(hModule, "RasDeleteSubEntryW");
   ptr_RasDialA = (__vartype(ptr_RasDialA))GetProcAddress(hModule, "RasDialA");
   ptr_RasDialW = (__vartype(ptr_RasDialW))GetProcAddress(hModule, "RasDialW");
   ptr_RasEditPhonebookEntryA = (__vartype(ptr_RasEditPhonebookEntryA))GetProcAddress(hModule, "RasEditPhonebookEntryA");
   ptr_RasEditPhonebookEntryW = (__vartype(ptr_RasEditPhonebookEntryW))GetProcAddress(hModule, "RasEditPhonebookEntryW");
   ptr_RasEnumAutodialAddressesA = (__vartype(ptr_RasEnumAutodialAddressesA))GetProcAddress(hModule, "RasEnumAutodialAddressesA");
   ptr_RasEnumAutodialAddressesW = (__vartype(ptr_RasEnumAutodialAddressesW))GetProcAddress(hModule, "RasEnumAutodialAddressesW");
   ptr_RasEnumConnectionsA = (__vartype(ptr_RasEnumConnectionsA))GetProcAddress(hModule, "RasEnumConnectionsA");
   ptr_RasEnumConnectionsW = (__vartype(ptr_RasEnumConnectionsW))GetProcAddress(hModule, "RasEnumConnectionsW");
   ptr_RasEnumDevicesA = (__vartype(ptr_RasEnumDevicesA))GetProcAddress(hModule, "RasEnumDevicesA");
   ptr_RasEnumDevicesW = (__vartype(ptr_RasEnumDevicesW))GetProcAddress(hModule, "RasEnumDevicesW");
   ptr_RasEnumEntriesA = (__vartype(ptr_RasEnumEntriesA))GetProcAddress(hModule, "RasEnumEntriesA");
   ptr_RasEnumEntriesW = (__vartype(ptr_RasEnumEntriesW))GetProcAddress(hModule, "RasEnumEntriesW");
   ptr_RasFreeEapUserIdentityA = (__vartype(ptr_RasFreeEapUserIdentityA))GetProcAddress(hModule, "RasFreeEapUserIdentityA");
   ptr_RasFreeEapUserIdentityW = (__vartype(ptr_RasFreeEapUserIdentityW))GetProcAddress(hModule, "RasFreeEapUserIdentityW");
   ptr_RasGetAutodialAddressA = (__vartype(ptr_RasGetAutodialAddressA))GetProcAddress(hModule, "RasGetAutodialAddressA");
   ptr_RasGetAutodialAddressW = (__vartype(ptr_RasGetAutodialAddressW))GetProcAddress(hModule, "RasGetAutodialAddressW");
   ptr_RasGetAutodialEnableA = (__vartype(ptr_RasGetAutodialEnableA))GetProcAddress(hModule, "RasGetAutodialEnableA");
   ptr_RasGetAutodialEnableW = (__vartype(ptr_RasGetAutodialEnableW))GetProcAddress(hModule, "RasGetAutodialEnableW");
   ptr_RasGetAutodialParamA = (__vartype(ptr_RasGetAutodialParamA))GetProcAddress(hModule, "RasGetAutodialParamA");
   ptr_RasGetAutodialParamW = (__vartype(ptr_RasGetAutodialParamW))GetProcAddress(hModule, "RasGetAutodialParamW");
   ptr_RasGetConnectStatusA = (__vartype(ptr_RasGetConnectStatusA))GetProcAddress(hModule, "RasGetConnectStatusA");
   ptr_RasGetConnectStatusW = (__vartype(ptr_RasGetConnectStatusW))GetProcAddress(hModule, "RasGetConnectStatusW");
   ptr_RasGetConnectionStatistics = (__vartype(ptr_RasGetConnectionStatistics))GetProcAddress(hModule, "RasGetConnectionStatistics");
   ptr_RasGetCountryInfoA = (__vartype(ptr_RasGetCountryInfoA))GetProcAddress(hModule, "RasGetCountryInfoA");
   ptr_RasGetCountryInfoW = (__vartype(ptr_RasGetCountryInfoW))GetProcAddress(hModule, "RasGetCountryInfoW");
   ptr_RasGetCredentialsA = (__vartype(ptr_RasGetCredentialsA))GetProcAddress(hModule, "RasGetCredentialsA");
   ptr_RasGetCredentialsW = (__vartype(ptr_RasGetCredentialsW))GetProcAddress(hModule, "RasGetCredentialsW");
   ptr_RasGetCustomAuthDataA = (__vartype(ptr_RasGetCustomAuthDataA))GetProcAddress(hModule, "RasGetCustomAuthDataA");
   ptr_RasGetCustomAuthDataW = (__vartype(ptr_RasGetCustomAuthDataW))GetProcAddress(hModule, "RasGetCustomAuthDataW");
   ptr_RasGetEapUserDataA = (__vartype(ptr_RasGetEapUserDataA))GetProcAddress(hModule, "RasGetEapUserDataA");
   ptr_RasGetEapUserDataW = (__vartype(ptr_RasGetEapUserDataW))GetProcAddress(hModule, "RasGetEapUserDataW");
   ptr_RasGetEapUserIdentityA = (__vartype(ptr_RasGetEapUserIdentityA))GetProcAddress(hModule, "RasGetEapUserIdentityA");
   ptr_RasGetEapUserIdentityW = (__vartype(ptr_RasGetEapUserIdentityW))GetProcAddress(hModule, "RasGetEapUserIdentityW");
   ptr_RasGetEntryDialParamsA = (__vartype(ptr_RasGetEntryDialParamsA))GetProcAddress(hModule, "RasGetEntryDialParamsA");
   ptr_RasGetEntryDialParamsW = (__vartype(ptr_RasGetEntryDialParamsW))GetProcAddress(hModule, "RasGetEntryDialParamsW");
   ptr_RasGetEntryHrasconnW = (__vartype(ptr_RasGetEntryHrasconnW))GetProcAddress(hModule, "RasGetEntryHrasconnW");
   ptr_RasGetEntryPropertiesA = (__vartype(ptr_RasGetEntryPropertiesA))GetProcAddress(hModule, "RasGetEntryPropertiesA");
   ptr_RasGetEntryPropertiesW = (__vartype(ptr_RasGetEntryPropertiesW))GetProcAddress(hModule, "RasGetEntryPropertiesW");
   ptr_RasGetErrorStringA = (__vartype(ptr_RasGetErrorStringA))GetProcAddress(hModule, "RasGetErrorStringA");
   ptr_RasGetErrorStringW = (__vartype(ptr_RasGetErrorStringW))GetProcAddress(hModule, "RasGetErrorStringW");
   ptr_RasGetHport = (__vartype(ptr_RasGetHport))GetProcAddress(hModule, "RasGetHport");
   ptr_RasGetLinkStatistics = (__vartype(ptr_RasGetLinkStatistics))GetProcAddress(hModule, "RasGetLinkStatistics");
   ptr_RasGetNapStatus = (__vartype(ptr_RasGetNapStatus))GetProcAddress(hModule, "RasGetNapStatus");
   ptr_RasGetProjectionInfoA = (__vartype(ptr_RasGetProjectionInfoA))GetProcAddress(hModule, "RasGetProjectionInfoA");
   ptr_RasGetProjectionInfoEx = (__vartype(ptr_RasGetProjectionInfoEx))GetProcAddress(hModule, "RasGetProjectionInfoEx");
   ptr_RasGetProjectionInfoW = (__vartype(ptr_RasGetProjectionInfoW))GetProcAddress(hModule, "RasGetProjectionInfoW");
   ptr_RasGetSubEntryHandleA = (__vartype(ptr_RasGetSubEntryHandleA))GetProcAddress(hModule, "RasGetSubEntryHandleA");
   ptr_RasGetSubEntryHandleW = (__vartype(ptr_RasGetSubEntryHandleW))GetProcAddress(hModule, "RasGetSubEntryHandleW");
   ptr_RasGetSubEntryPropertiesA = (__vartype(ptr_RasGetSubEntryPropertiesA))GetProcAddress(hModule, "RasGetSubEntryPropertiesA");
   ptr_RasGetSubEntryPropertiesW = (__vartype(ptr_RasGetSubEntryPropertiesW))GetProcAddress(hModule, "RasGetSubEntryPropertiesW");
   ptr_RasHangUpA = (__vartype(ptr_RasHangUpA))GetProcAddress(hModule, "RasHangUpA");
   ptr_RasHangUpW = (__vartype(ptr_RasHangUpW))GetProcAddress(hModule, "RasHangUpW");
   ptr_RasInvokeEapUI = (__vartype(ptr_RasInvokeEapUI))GetProcAddress(hModule, "RasInvokeEapUI");
   ptr_RasIsPublicPhonebook = (__vartype(ptr_RasIsPublicPhonebook))GetProcAddress(hModule, "RasIsPublicPhonebook");
   ptr_RasIsSharedConnection = (__vartype(ptr_RasIsSharedConnection))GetProcAddress(hModule, "RasIsSharedConnection");
   ptr_RasQueryRedialOnLinkFailure = (__vartype(ptr_RasQueryRedialOnLinkFailure))GetProcAddress(hModule, "RasQueryRedialOnLinkFailure");
   ptr_RasQuerySharedAutoDial = (__vartype(ptr_RasQuerySharedAutoDial))GetProcAddress(hModule, "RasQuerySharedAutoDial");
   ptr_RasQuerySharedConnection = (__vartype(ptr_RasQuerySharedConnection))GetProcAddress(hModule, "RasQuerySharedConnection");
   ptr_RasRenameEntryA = (__vartype(ptr_RasRenameEntryA))GetProcAddress(hModule, "RasRenameEntryA");
   ptr_RasRenameEntryW = (__vartype(ptr_RasRenameEntryW))GetProcAddress(hModule, "RasRenameEntryW");
   ptr_RasScriptGetIpAddress = (__vartype(ptr_RasScriptGetIpAddress))GetProcAddress(hModule, "RasScriptGetIpAddress");
   ptr_RasScriptInit = (__vartype(ptr_RasScriptInit))GetProcAddress(hModule, "RasScriptInit");
   ptr_RasScriptReceive = (__vartype(ptr_RasScriptReceive))GetProcAddress(hModule, "RasScriptReceive");
   ptr_RasScriptSend = (__vartype(ptr_RasScriptSend))GetProcAddress(hModule, "RasScriptSend");
   ptr_RasScriptTerm = (__vartype(ptr_RasScriptTerm))GetProcAddress(hModule, "RasScriptTerm");
   ptr_RasSetAutodialAddressA = (__vartype(ptr_RasSetAutodialAddressA))GetProcAddress(hModule, "RasSetAutodialAddressA");
   ptr_RasSetAutodialAddressW = (__vartype(ptr_RasSetAutodialAddressW))GetProcAddress(hModule, "RasSetAutodialAddressW");
   ptr_RasSetAutodialEnableA = (__vartype(ptr_RasSetAutodialEnableA))GetProcAddress(hModule, "RasSetAutodialEnableA");
   ptr_RasSetAutodialEnableW = (__vartype(ptr_RasSetAutodialEnableW))GetProcAddress(hModule, "RasSetAutodialEnableW");
   ptr_RasSetAutodialParamA = (__vartype(ptr_RasSetAutodialParamA))GetProcAddress(hModule, "RasSetAutodialParamA");
   ptr_RasSetAutodialParamW = (__vartype(ptr_RasSetAutodialParamW))GetProcAddress(hModule, "RasSetAutodialParamW");
   ptr_RasSetCredentialsA = (__vartype(ptr_RasSetCredentialsA))GetProcAddress(hModule, "RasSetCredentialsA");
   ptr_RasSetCredentialsW = (__vartype(ptr_RasSetCredentialsW))GetProcAddress(hModule, "RasSetCredentialsW");
   ptr_RasSetCustomAuthDataA = (__vartype(ptr_RasSetCustomAuthDataA))GetProcAddress(hModule, "RasSetCustomAuthDataA");
   ptr_RasSetCustomAuthDataW = (__vartype(ptr_RasSetCustomAuthDataW))GetProcAddress(hModule, "RasSetCustomAuthDataW");
   ptr_RasSetEapUserDataA = (__vartype(ptr_RasSetEapUserDataA))GetProcAddress(hModule, "RasSetEapUserDataA");
   ptr_RasSetEapUserDataW = (__vartype(ptr_RasSetEapUserDataW))GetProcAddress(hModule, "RasSetEapUserDataW");
   ptr_RasSetEntryDialParamsA = (__vartype(ptr_RasSetEntryDialParamsA))GetProcAddress(hModule, "RasSetEntryDialParamsA");
   ptr_RasSetEntryDialParamsW = (__vartype(ptr_RasSetEntryDialParamsW))GetProcAddress(hModule, "RasSetEntryDialParamsW");
   ptr_RasSetEntryPropertiesA = (__vartype(ptr_RasSetEntryPropertiesA))GetProcAddress(hModule, "RasSetEntryPropertiesA");
   ptr_RasSetEntryPropertiesW = (__vartype(ptr_RasSetEntryPropertiesW))GetProcAddress(hModule, "RasSetEntryPropertiesW");
   ptr_RasSetOldPassword = (__vartype(ptr_RasSetOldPassword))GetProcAddress(hModule, "RasSetOldPassword");
   ptr_RasSetSharedAutoDial = (__vartype(ptr_RasSetSharedAutoDial))GetProcAddress(hModule, "RasSetSharedAutoDial");
   ptr_RasSetSubEntryPropertiesA = (__vartype(ptr_RasSetSubEntryPropertiesA))GetProcAddress(hModule, "RasSetSubEntryPropertiesA");
   ptr_RasSetSubEntryPropertiesW = (__vartype(ptr_RasSetSubEntryPropertiesW))GetProcAddress(hModule, "RasSetSubEntryPropertiesW");
   ptr_RasUpdateConnection = (__vartype(ptr_RasUpdateConnection))GetProcAddress(hModule, "RasUpdateConnection");
   ptr_RasValidateEntryNameA = (__vartype(ptr_RasValidateEntryNameA))GetProcAddress(hModule, "RasValidateEntryNameA");
   ptr_RasValidateEntryNameW = (__vartype(ptr_RasValidateEntryNameW))GetProcAddress(hModule, "RasValidateEntryNameW");
   ptr_RasWriteSharedPbkOptions = (__vartype(ptr_RasWriteSharedPbkOptions))GetProcAddress(hModule, "RasWriteSharedPbkOptions");
   ptr_UnInitializeRAS = (__vartype(ptr_UnInitializeRAS))GetProcAddress(hModule, "UnInitializeRAS");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

