#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_ConstructPartialMsgIfA;
void *ptr_ConstructPartialMsgIfA = NULL;
extern void *ptr_ConstructPartialMsgIfW;
void *ptr_ConstructPartialMsgIfW = NULL;
extern void *ptr_ConstructPartialMsgVA;
void *ptr_ConstructPartialMsgVA = NULL;
extern void *ptr_ConstructPartialMsgVW;
void *ptr_ConstructPartialMsgVW = NULL;
extern void *ptr_CurrentIP;
void *ptr_CurrentIP = NULL;
extern void *ptr_EndMajorTask;
void *ptr_EndMajorTask = NULL;
extern void *ptr_EndMinorTask;
void *ptr_EndMinorTask = NULL;
extern void *ptr_GetMajorTask;
void *ptr_GetMajorTask = NULL;
extern void *ptr_GetMajorTaskA;
void *ptr_GetMajorTaskA = NULL;
extern void *ptr_GetMinorTask;
void *ptr_GetMinorTask = NULL;
extern void *ptr_GetMinorTaskA;
void *ptr_GetMinorTaskA = NULL;
extern void *ptr_StartMajorTask;
void *ptr_StartMajorTask = NULL;
extern void *ptr_StartMinorTask;
void *ptr_StartMinorTask = NULL;
extern void *ptr_WdsAbortBlackboardItemEnum;
void *ptr_WdsAbortBlackboardItemEnum = NULL;
extern void *ptr_WdsAddModule;
void *ptr_WdsAddModule = NULL;
extern void *ptr_WdsAddUsmtLogStack;
void *ptr_WdsAddUsmtLogStack = NULL;
extern void *ptr_WdsAllocCollection;
void *ptr_WdsAllocCollection = NULL;
extern void *ptr_WdsCollectionAddValue;
void *ptr_WdsCollectionAddValue = NULL;
extern void *ptr_WdsCollectionGetValue;
void *ptr_WdsCollectionGetValue = NULL;
extern void *ptr_WdsCopyBlackboardItems;
void *ptr_WdsCopyBlackboardItems = NULL;
extern void *ptr_WdsCopyBlackboardItemsEx;
void *ptr_WdsCopyBlackboardItemsEx = NULL;
extern void *ptr_WdsCreateBlackboard;
void *ptr_WdsCreateBlackboard = NULL;
extern void *ptr_WdsDeleteBlackboardValue;
void *ptr_WdsDeleteBlackboardValue = NULL;
extern void *ptr_WdsDeleteEvent;
void *ptr_WdsDeleteEvent = NULL;
extern void *ptr_WdsDestroyBlackboard;
void *ptr_WdsDestroyBlackboard = NULL;
extern void *ptr_WdsDuplicateData;
void *ptr_WdsDuplicateData = NULL;
extern void *ptr_WdsEnableDiagnosticMode;
void *ptr_WdsEnableDiagnosticMode = NULL;
extern void *ptr_WdsEnableExit;
void *ptr_WdsEnableExit = NULL;
extern void *ptr_WdsEnableExitEx;
void *ptr_WdsEnableExitEx = NULL;
extern void *ptr_WdsEnumFirstBlackboardItem;
void *ptr_WdsEnumFirstBlackboardItem = NULL;
extern void *ptr_WdsEnumFirstCollectionValue;
void *ptr_WdsEnumFirstCollectionValue = NULL;
extern void *ptr_WdsEnumNextBlackboardItem;
void *ptr_WdsEnumNextBlackboardItem = NULL;
extern void *ptr_WdsEnumNextCollectionValue;
void *ptr_WdsEnumNextCollectionValue = NULL;
extern void *ptr_WdsExecuteWorkQueue;
void *ptr_WdsExecuteWorkQueue = NULL;
extern void *ptr_WdsExecuteWorkQueue2;
void *ptr_WdsExecuteWorkQueue2 = NULL;
extern void *ptr_WdsExecuteWorkQueueEx;
void *ptr_WdsExecuteWorkQueueEx = NULL;
extern void *ptr_WdsExitImmediately;
void *ptr_WdsExitImmediately = NULL;
extern void *ptr_WdsExitImmediatelyEx;
void *ptr_WdsExitImmediatelyEx = NULL;
extern void *ptr_WdsFreeCollection;
void *ptr_WdsFreeCollection = NULL;
extern void *ptr_WdsFreeData;
void *ptr_WdsFreeData = NULL;
extern void *ptr_WdsGenericSetupLogInit;
void *ptr_WdsGenericSetupLogInit = NULL;
extern void *ptr_WdsGetAssertFlags;
void *ptr_WdsGetAssertFlags = NULL;
extern void *ptr_WdsGetBlackboardBinaryData;
void *ptr_WdsGetBlackboardBinaryData = NULL;
extern void *ptr_WdsGetBlackboardStringA;
void *ptr_WdsGetBlackboardStringA = NULL;
extern void *ptr_WdsGetBlackboardStringW;
void *ptr_WdsGetBlackboardStringW = NULL;
extern void *ptr_WdsGetBlackboardUintPtr;
void *ptr_WdsGetBlackboardUintPtr = NULL;
extern void *ptr_WdsGetBlackboardValue;
void *ptr_WdsGetBlackboardValue = NULL;
extern void *ptr_WdsGetCurrentExecutionGroup;
void *ptr_WdsGetCurrentExecutionGroup = NULL;
extern void *ptr_WdsGetPointer;
void *ptr_WdsGetPointer = NULL;
extern void *ptr_WdsGetSetupLog;
void *ptr_WdsGetSetupLog = NULL;
extern void *ptr_WdsGetTempDir;
void *ptr_WdsGetTempDir = NULL;
extern void *ptr_WdsInitialize;
void *ptr_WdsInitialize = NULL;
extern void *ptr_WdsInitializeCallbackArray;
void *ptr_WdsInitializeCallbackArray = NULL;
extern void *ptr_WdsInitializeDataBinary;
void *ptr_WdsInitializeDataBinary = NULL;
extern void *ptr_WdsInitializeDataStringA;
void *ptr_WdsInitializeDataStringA = NULL;
extern void *ptr_WdsInitializeDataStringW;
void *ptr_WdsInitializeDataStringW = NULL;
extern void *ptr_WdsInitializeDataUInt32;
void *ptr_WdsInitializeDataUInt32 = NULL;
extern void *ptr_WdsInitializeDataUInt64;
void *ptr_WdsInitializeDataUInt64 = NULL;
extern void *ptr_WdsIsDiagnosticModeEnabled;
void *ptr_WdsIsDiagnosticModeEnabled = NULL;
extern void *ptr_WdsIterateOfflineQueue;
void *ptr_WdsIterateOfflineQueue = NULL;
extern void *ptr_WdsIterateQueue;
void *ptr_WdsIterateQueue = NULL;
extern void *ptr_WdsLockBlackboardValue;
void *ptr_WdsLockBlackboardValue = NULL;
extern void *ptr_WdsLockExecutionGroup;
void *ptr_WdsLockExecutionGroup = NULL;
extern void *ptr_WdsLogCreate;
void *ptr_WdsLogCreate = NULL;
extern void *ptr_WdsLogDestroy;
void *ptr_WdsLogDestroy = NULL;
extern void *ptr_WdsLogRegStockProviders;
void *ptr_WdsLogRegStockProviders = NULL;
extern void *ptr_WdsLogRegisterProvider;
void *ptr_WdsLogRegisterProvider = NULL;
extern void *ptr_WdsLogStructuredException;
void *ptr_WdsLogStructuredException = NULL;
extern void *ptr_WdsLogUnRegStockProviders;
void *ptr_WdsLogUnRegStockProviders = NULL;
extern void *ptr_WdsLogUnRegisterProvider;
void *ptr_WdsLogUnRegisterProvider = NULL;
extern void *ptr_WdsPackCollection;
void *ptr_WdsPackCollection = NULL;
extern void *ptr_WdsPublish;
void *ptr_WdsPublish = NULL;
extern void *ptr_WdsPublishEx;
void *ptr_WdsPublishEx = NULL;
extern void *ptr_WdsPublishImmediateAsync;
void *ptr_WdsPublishImmediateAsync = NULL;
extern void *ptr_WdsPublishImmediateEx;
void *ptr_WdsPublishImmediateEx = NULL;
extern void *ptr_WdsPublishOffline;
void *ptr_WdsPublishOffline = NULL;
extern void *ptr_WdsSeqAlloc;
void *ptr_WdsSeqAlloc = NULL;
extern void *ptr_WdsSeqFree;
void *ptr_WdsSeqFree = NULL;
extern void *ptr_WdsSetAssertFlags;
void *ptr_WdsSetAssertFlags = NULL;
extern void *ptr_WdsSetBlackboardValue;
void *ptr_WdsSetBlackboardValue = NULL;
extern void *ptr_WdsSetNextExecutionGroup;
void *ptr_WdsSetNextExecutionGroup = NULL;
extern void *ptr_WdsSetUILanguage;
void *ptr_WdsSetUILanguage = NULL;
extern void *ptr_WdsSetupLogDestroy;
void *ptr_WdsSetupLogDestroy = NULL;
extern void *ptr_WdsSetupLogInit;
void *ptr_WdsSetupLogInit = NULL;
extern void *ptr_WdsSetupLogMessageA;
void *ptr_WdsSetupLogMessageA = NULL;
extern void *ptr_WdsSetupLogMessageW;
void *ptr_WdsSetupLogMessageW = NULL;
extern void *ptr_WdsSubscribeEx;
void *ptr_WdsSubscribeEx = NULL;
extern void *ptr_WdsTerminate;
void *ptr_WdsTerminate = NULL;
extern void *ptr_WdsUnlockExecutionGroup;
void *ptr_WdsUnlockExecutionGroup = NULL;
extern void *ptr_WdsUnpackCollection;
void *ptr_WdsUnpackCollection = NULL;
extern void *ptr_WdsUnsubscribe;
void *ptr_WdsUnsubscribe = NULL;
extern void *ptr_WdsUnsubscribeEx;
void *ptr_WdsUnsubscribeEx = NULL;
extern void *ptr_WdsValidBlackboard;
void *ptr_WdsValidBlackboard = NULL;
extern void *ptr_g_Kernel32;
void *ptr_g_Kernel32 = NULL;
extern void *ptr_g_bEnableDiagnosticMode;
void *ptr_g_bEnableDiagnosticMode = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\wdscore.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_ConstructPartialMsgIfA = (__vartype(ptr_ConstructPartialMsgIfA))GetProcAddress(hModule, "ConstructPartialMsgIfA");
   ptr_ConstructPartialMsgIfW = (__vartype(ptr_ConstructPartialMsgIfW))GetProcAddress(hModule, "ConstructPartialMsgIfW");
   ptr_ConstructPartialMsgVA = (__vartype(ptr_ConstructPartialMsgVA))GetProcAddress(hModule, "ConstructPartialMsgVA");
   ptr_ConstructPartialMsgVW = (__vartype(ptr_ConstructPartialMsgVW))GetProcAddress(hModule, "ConstructPartialMsgVW");
   ptr_CurrentIP = (__vartype(ptr_CurrentIP))GetProcAddress(hModule, "CurrentIP");
   ptr_EndMajorTask = (__vartype(ptr_EndMajorTask))GetProcAddress(hModule, "EndMajorTask");
   ptr_EndMinorTask = (__vartype(ptr_EndMinorTask))GetProcAddress(hModule, "EndMinorTask");
   ptr_GetMajorTask = (__vartype(ptr_GetMajorTask))GetProcAddress(hModule, "GetMajorTask");
   ptr_GetMajorTaskA = (__vartype(ptr_GetMajorTaskA))GetProcAddress(hModule, "GetMajorTaskA");
   ptr_GetMinorTask = (__vartype(ptr_GetMinorTask))GetProcAddress(hModule, "GetMinorTask");
   ptr_GetMinorTaskA = (__vartype(ptr_GetMinorTaskA))GetProcAddress(hModule, "GetMinorTaskA");
   ptr_StartMajorTask = (__vartype(ptr_StartMajorTask))GetProcAddress(hModule, "StartMajorTask");
   ptr_StartMinorTask = (__vartype(ptr_StartMinorTask))GetProcAddress(hModule, "StartMinorTask");
   ptr_WdsAbortBlackboardItemEnum = (__vartype(ptr_WdsAbortBlackboardItemEnum))GetProcAddress(hModule, "WdsAbortBlackboardItemEnum");
   ptr_WdsAddModule = (__vartype(ptr_WdsAddModule))GetProcAddress(hModule, "WdsAddModule");
   ptr_WdsAddUsmtLogStack = (__vartype(ptr_WdsAddUsmtLogStack))GetProcAddress(hModule, "WdsAddUsmtLogStack");
   ptr_WdsAllocCollection = (__vartype(ptr_WdsAllocCollection))GetProcAddress(hModule, "WdsAllocCollection");
   ptr_WdsCollectionAddValue = (__vartype(ptr_WdsCollectionAddValue))GetProcAddress(hModule, "WdsCollectionAddValue");
   ptr_WdsCollectionGetValue = (__vartype(ptr_WdsCollectionGetValue))GetProcAddress(hModule, "WdsCollectionGetValue");
   ptr_WdsCopyBlackboardItems = (__vartype(ptr_WdsCopyBlackboardItems))GetProcAddress(hModule, "WdsCopyBlackboardItems");
   ptr_WdsCopyBlackboardItemsEx = (__vartype(ptr_WdsCopyBlackboardItemsEx))GetProcAddress(hModule, "WdsCopyBlackboardItemsEx");
   ptr_WdsCreateBlackboard = (__vartype(ptr_WdsCreateBlackboard))GetProcAddress(hModule, "WdsCreateBlackboard");
   ptr_WdsDeleteBlackboardValue = (__vartype(ptr_WdsDeleteBlackboardValue))GetProcAddress(hModule, "WdsDeleteBlackboardValue");
   ptr_WdsDeleteEvent = (__vartype(ptr_WdsDeleteEvent))GetProcAddress(hModule, "WdsDeleteEvent");
   ptr_WdsDestroyBlackboard = (__vartype(ptr_WdsDestroyBlackboard))GetProcAddress(hModule, "WdsDestroyBlackboard");
   ptr_WdsDuplicateData = (__vartype(ptr_WdsDuplicateData))GetProcAddress(hModule, "WdsDuplicateData");
   ptr_WdsEnableDiagnosticMode = (__vartype(ptr_WdsEnableDiagnosticMode))GetProcAddress(hModule, "WdsEnableDiagnosticMode");
   ptr_WdsEnableExit = (__vartype(ptr_WdsEnableExit))GetProcAddress(hModule, "WdsEnableExit");
   ptr_WdsEnableExitEx = (__vartype(ptr_WdsEnableExitEx))GetProcAddress(hModule, "WdsEnableExitEx");
   ptr_WdsEnumFirstBlackboardItem = (__vartype(ptr_WdsEnumFirstBlackboardItem))GetProcAddress(hModule, "WdsEnumFirstBlackboardItem");
   ptr_WdsEnumFirstCollectionValue = (__vartype(ptr_WdsEnumFirstCollectionValue))GetProcAddress(hModule, "WdsEnumFirstCollectionValue");
   ptr_WdsEnumNextBlackboardItem = (__vartype(ptr_WdsEnumNextBlackboardItem))GetProcAddress(hModule, "WdsEnumNextBlackboardItem");
   ptr_WdsEnumNextCollectionValue = (__vartype(ptr_WdsEnumNextCollectionValue))GetProcAddress(hModule, "WdsEnumNextCollectionValue");
   ptr_WdsExecuteWorkQueue = (__vartype(ptr_WdsExecuteWorkQueue))GetProcAddress(hModule, "WdsExecuteWorkQueue");
   ptr_WdsExecuteWorkQueue2 = (__vartype(ptr_WdsExecuteWorkQueue2))GetProcAddress(hModule, "WdsExecuteWorkQueue2");
   ptr_WdsExecuteWorkQueueEx = (__vartype(ptr_WdsExecuteWorkQueueEx))GetProcAddress(hModule, "WdsExecuteWorkQueueEx");
   ptr_WdsExitImmediately = (__vartype(ptr_WdsExitImmediately))GetProcAddress(hModule, "WdsExitImmediately");
   ptr_WdsExitImmediatelyEx = (__vartype(ptr_WdsExitImmediatelyEx))GetProcAddress(hModule, "WdsExitImmediatelyEx");
   ptr_WdsFreeCollection = (__vartype(ptr_WdsFreeCollection))GetProcAddress(hModule, "WdsFreeCollection");
   ptr_WdsFreeData = (__vartype(ptr_WdsFreeData))GetProcAddress(hModule, "WdsFreeData");
   ptr_WdsGenericSetupLogInit = (__vartype(ptr_WdsGenericSetupLogInit))GetProcAddress(hModule, "WdsGenericSetupLogInit");
   ptr_WdsGetAssertFlags = (__vartype(ptr_WdsGetAssertFlags))GetProcAddress(hModule, "WdsGetAssertFlags");
   ptr_WdsGetBlackboardBinaryData = (__vartype(ptr_WdsGetBlackboardBinaryData))GetProcAddress(hModule, "WdsGetBlackboardBinaryData");
   ptr_WdsGetBlackboardStringA = (__vartype(ptr_WdsGetBlackboardStringA))GetProcAddress(hModule, "WdsGetBlackboardStringA");
   ptr_WdsGetBlackboardStringW = (__vartype(ptr_WdsGetBlackboardStringW))GetProcAddress(hModule, "WdsGetBlackboardStringW");
   ptr_WdsGetBlackboardUintPtr = (__vartype(ptr_WdsGetBlackboardUintPtr))GetProcAddress(hModule, "WdsGetBlackboardUintPtr");
   ptr_WdsGetBlackboardValue = (__vartype(ptr_WdsGetBlackboardValue))GetProcAddress(hModule, "WdsGetBlackboardValue");
   ptr_WdsGetCurrentExecutionGroup = (__vartype(ptr_WdsGetCurrentExecutionGroup))GetProcAddress(hModule, "WdsGetCurrentExecutionGroup");
   ptr_WdsGetPointer = (__vartype(ptr_WdsGetPointer))GetProcAddress(hModule, "WdsGetPointer");
   ptr_WdsGetSetupLog = (__vartype(ptr_WdsGetSetupLog))GetProcAddress(hModule, "WdsGetSetupLog");
   ptr_WdsGetTempDir = (__vartype(ptr_WdsGetTempDir))GetProcAddress(hModule, "WdsGetTempDir");
   ptr_WdsInitialize = (__vartype(ptr_WdsInitialize))GetProcAddress(hModule, "WdsInitialize");
   ptr_WdsInitializeCallbackArray = (__vartype(ptr_WdsInitializeCallbackArray))GetProcAddress(hModule, "WdsInitializeCallbackArray");
   ptr_WdsInitializeDataBinary = (__vartype(ptr_WdsInitializeDataBinary))GetProcAddress(hModule, "WdsInitializeDataBinary");
   ptr_WdsInitializeDataStringA = (__vartype(ptr_WdsInitializeDataStringA))GetProcAddress(hModule, "WdsInitializeDataStringA");
   ptr_WdsInitializeDataStringW = (__vartype(ptr_WdsInitializeDataStringW))GetProcAddress(hModule, "WdsInitializeDataStringW");
   ptr_WdsInitializeDataUInt32 = (__vartype(ptr_WdsInitializeDataUInt32))GetProcAddress(hModule, "WdsInitializeDataUInt32");
   ptr_WdsInitializeDataUInt64 = (__vartype(ptr_WdsInitializeDataUInt64))GetProcAddress(hModule, "WdsInitializeDataUInt64");
   ptr_WdsIsDiagnosticModeEnabled = (__vartype(ptr_WdsIsDiagnosticModeEnabled))GetProcAddress(hModule, "WdsIsDiagnosticModeEnabled");
   ptr_WdsIterateOfflineQueue = (__vartype(ptr_WdsIterateOfflineQueue))GetProcAddress(hModule, "WdsIterateOfflineQueue");
   ptr_WdsIterateQueue = (__vartype(ptr_WdsIterateQueue))GetProcAddress(hModule, "WdsIterateQueue");
   ptr_WdsLockBlackboardValue = (__vartype(ptr_WdsLockBlackboardValue))GetProcAddress(hModule, "WdsLockBlackboardValue");
   ptr_WdsLockExecutionGroup = (__vartype(ptr_WdsLockExecutionGroup))GetProcAddress(hModule, "WdsLockExecutionGroup");
   ptr_WdsLogCreate = (__vartype(ptr_WdsLogCreate))GetProcAddress(hModule, "WdsLogCreate");
   ptr_WdsLogDestroy = (__vartype(ptr_WdsLogDestroy))GetProcAddress(hModule, "WdsLogDestroy");
   ptr_WdsLogRegStockProviders = (__vartype(ptr_WdsLogRegStockProviders))GetProcAddress(hModule, "WdsLogRegStockProviders");
   ptr_WdsLogRegisterProvider = (__vartype(ptr_WdsLogRegisterProvider))GetProcAddress(hModule, "WdsLogRegisterProvider");
   ptr_WdsLogStructuredException = (__vartype(ptr_WdsLogStructuredException))GetProcAddress(hModule, "WdsLogStructuredException");
   ptr_WdsLogUnRegStockProviders = (__vartype(ptr_WdsLogUnRegStockProviders))GetProcAddress(hModule, "WdsLogUnRegStockProviders");
   ptr_WdsLogUnRegisterProvider = (__vartype(ptr_WdsLogUnRegisterProvider))GetProcAddress(hModule, "WdsLogUnRegisterProvider");
   ptr_WdsPackCollection = (__vartype(ptr_WdsPackCollection))GetProcAddress(hModule, "WdsPackCollection");
   ptr_WdsPublish = (__vartype(ptr_WdsPublish))GetProcAddress(hModule, "WdsPublish");
   ptr_WdsPublishEx = (__vartype(ptr_WdsPublishEx))GetProcAddress(hModule, "WdsPublishEx");
   ptr_WdsPublishImmediateAsync = (__vartype(ptr_WdsPublishImmediateAsync))GetProcAddress(hModule, "WdsPublishImmediateAsync");
   ptr_WdsPublishImmediateEx = (__vartype(ptr_WdsPublishImmediateEx))GetProcAddress(hModule, "WdsPublishImmediateEx");
   ptr_WdsPublishOffline = (__vartype(ptr_WdsPublishOffline))GetProcAddress(hModule, "WdsPublishOffline");
   ptr_WdsSeqAlloc = (__vartype(ptr_WdsSeqAlloc))GetProcAddress(hModule, "WdsSeqAlloc");
   ptr_WdsSeqFree = (__vartype(ptr_WdsSeqFree))GetProcAddress(hModule, "WdsSeqFree");
   ptr_WdsSetAssertFlags = (__vartype(ptr_WdsSetAssertFlags))GetProcAddress(hModule, "WdsSetAssertFlags");
   ptr_WdsSetBlackboardValue = (__vartype(ptr_WdsSetBlackboardValue))GetProcAddress(hModule, "WdsSetBlackboardValue");
   ptr_WdsSetNextExecutionGroup = (__vartype(ptr_WdsSetNextExecutionGroup))GetProcAddress(hModule, "WdsSetNextExecutionGroup");
   ptr_WdsSetUILanguage = (__vartype(ptr_WdsSetUILanguage))GetProcAddress(hModule, "WdsSetUILanguage");
   ptr_WdsSetupLogDestroy = (__vartype(ptr_WdsSetupLogDestroy))GetProcAddress(hModule, "WdsSetupLogDestroy");
   ptr_WdsSetupLogInit = (__vartype(ptr_WdsSetupLogInit))GetProcAddress(hModule, "WdsSetupLogInit");
   ptr_WdsSetupLogMessageA = (__vartype(ptr_WdsSetupLogMessageA))GetProcAddress(hModule, "WdsSetupLogMessageA");
   ptr_WdsSetupLogMessageW = (__vartype(ptr_WdsSetupLogMessageW))GetProcAddress(hModule, "WdsSetupLogMessageW");
   ptr_WdsSubscribeEx = (__vartype(ptr_WdsSubscribeEx))GetProcAddress(hModule, "WdsSubscribeEx");
   ptr_WdsTerminate = (__vartype(ptr_WdsTerminate))GetProcAddress(hModule, "WdsTerminate");
   ptr_WdsUnlockExecutionGroup = (__vartype(ptr_WdsUnlockExecutionGroup))GetProcAddress(hModule, "WdsUnlockExecutionGroup");
   ptr_WdsUnpackCollection = (__vartype(ptr_WdsUnpackCollection))GetProcAddress(hModule, "WdsUnpackCollection");
   ptr_WdsUnsubscribe = (__vartype(ptr_WdsUnsubscribe))GetProcAddress(hModule, "WdsUnsubscribe");
   ptr_WdsUnsubscribeEx = (__vartype(ptr_WdsUnsubscribeEx))GetProcAddress(hModule, "WdsUnsubscribeEx");
   ptr_WdsValidBlackboard = (__vartype(ptr_WdsValidBlackboard))GetProcAddress(hModule, "WdsValidBlackboard");
   ptr_g_Kernel32 = (__vartype(ptr_g_Kernel32))GetProcAddress(hModule, "g_Kernel32");
   ptr_g_bEnableDiagnosticMode = (__vartype(ptr_g_bEnableDiagnosticMode))GetProcAddress(hModule, "g_bEnableDiagnosticMode");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

