#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_CreateCommunityTransport;
void *ptr_CreateCommunityTransport = NULL;
extern void *ptr_CreateIMAPTransport;
void *ptr_CreateIMAPTransport = NULL;
extern void *ptr_CreateIMAPTransport2;
void *ptr_CreateIMAPTransport2 = NULL;
extern void *ptr_CreateNNTPTransport;
void *ptr_CreateNNTPTransport = NULL;
extern void *ptr_CreatePOP3Transport;
void *ptr_CreatePOP3Transport = NULL;
extern void *ptr_CreateRASTransport;
void *ptr_CreateRASTransport = NULL;
extern void *ptr_CreateRangeList;
void *ptr_CreateRangeList = NULL;
extern void *ptr_CreateSMTPTransport;
void *ptr_CreateSMTPTransport = NULL;
extern void *ptr_DllCanUnloadNow;
void *ptr_DllCanUnloadNow = NULL;
extern void *ptr_DllGetClassObject;
void *ptr_DllGetClassObject = NULL;
extern void *ptr_EssContentHintDecodeEx;
void *ptr_EssContentHintDecodeEx = NULL;
extern void *ptr_EssContentHintEncodeEx;
void *ptr_EssContentHintEncodeEx = NULL;
extern void *ptr_EssKeyExchPreferenceDecodeEx;
void *ptr_EssKeyExchPreferenceDecodeEx = NULL;
extern void *ptr_EssKeyExchPreferenceEncodeEx;
void *ptr_EssKeyExchPreferenceEncodeEx = NULL;
extern void *ptr_EssMLHistoryDecodeEx;
void *ptr_EssMLHistoryDecodeEx = NULL;
extern void *ptr_EssMLHistoryEncodeEx;
void *ptr_EssMLHistoryEncodeEx = NULL;
extern void *ptr_EssReceiptDecodeEx;
void *ptr_EssReceiptDecodeEx = NULL;
extern void *ptr_EssReceiptEncodeEx;
void *ptr_EssReceiptEncodeEx = NULL;
extern void *ptr_EssReceiptRequestDecodeEx;
void *ptr_EssReceiptRequestDecodeEx = NULL;
extern void *ptr_EssReceiptRequestEncodeEx;
void *ptr_EssReceiptRequestEncodeEx = NULL;
extern void *ptr_EssSecurityLabelDecodeEx;
void *ptr_EssSecurityLabelDecodeEx = NULL;
extern void *ptr_EssSecurityLabelEncodeEx;
void *ptr_EssSecurityLabelEncodeEx = NULL;
extern void *ptr_EssSignCertificateDecodeEx;
void *ptr_EssSignCertificateDecodeEx = NULL;
extern void *ptr_EssSignCertificateEncodeEx;
void *ptr_EssSignCertificateEncodeEx = NULL;
extern void *ptr_GetDllMajorVersion;
void *ptr_GetDllMajorVersion = NULL;
extern void *ptr_HrAthGetFileName;
void *ptr_HrAthGetFileName = NULL;
extern void *ptr_HrAthGetFileNameW;
void *ptr_HrAthGetFileNameW = NULL;
extern void *ptr_HrAttachDataFromBodyPart;
void *ptr_HrAttachDataFromBodyPart = NULL;
extern void *ptr_HrAttachDataFromFile;
void *ptr_HrAttachDataFromFile = NULL;
extern void *ptr_HrCreateDisplayNameWithSizeForFile;
void *ptr_HrCreateDisplayNameWithSizeForFile = NULL;
extern void *ptr_HrDoAttachmentVerb;
void *ptr_HrDoAttachmentVerb = NULL;
extern void *ptr_HrFreeAttachData;
void *ptr_HrFreeAttachData = NULL;
extern void *ptr_HrGetAttachIcon;
void *ptr_HrGetAttachIcon = NULL;
extern void *ptr_HrGetAttachIconByFile;
void *ptr_HrGetAttachIconByFile = NULL;
extern void *ptr_HrGetDisplayNameWithSizeForFile;
void *ptr_HrGetDisplayNameWithSizeForFile = NULL;
extern void *ptr_HrGetLastOpenFileDirectory;
void *ptr_HrGetLastOpenFileDirectory = NULL;
extern void *ptr_HrGetLastOpenFileDirectoryW;
void *ptr_HrGetLastOpenFileDirectoryW = NULL;
extern void *ptr_HrSaveAttachToFile;
void *ptr_HrSaveAttachToFile = NULL;
extern void *ptr_HrSaveAttachmentAs;
void *ptr_HrSaveAttachmentAs = NULL;
extern void *ptr_MimeEditCreateMimeDocument;
void *ptr_MimeEditCreateMimeDocument = NULL;
extern void *ptr_MimeEditDocumentFromStream;
void *ptr_MimeEditDocumentFromStream = NULL;
extern void *ptr_MimeEditGetBackgroundImageUrl;
void *ptr_MimeEditGetBackgroundImageUrl = NULL;
extern void *ptr_MimeEditIsSafeToRun;
void *ptr_MimeEditIsSafeToRun = NULL;
extern void *ptr_MimeEditViewSource;
void *ptr_MimeEditViewSource = NULL;
extern void *ptr_MimeGetAddressFormatW;
void *ptr_MimeGetAddressFormatW = NULL;
extern void *ptr_MimeOleAlgNameFromSMimeCap;
void *ptr_MimeOleAlgNameFromSMimeCap = NULL;
extern void *ptr_MimeOleAlgStrengthFromSMimeCap;
void *ptr_MimeOleAlgStrengthFromSMimeCap = NULL;
extern void *ptr_MimeOleClearDirtyTree;
void *ptr_MimeOleClearDirtyTree = NULL;
extern void *ptr_MimeOleConvertEnrichedToHTML;
void *ptr_MimeOleConvertEnrichedToHTML = NULL;
extern void *ptr_MimeOleCreateBody;
void *ptr_MimeOleCreateBody = NULL;
extern void *ptr_MimeOleCreateByteStream;
void *ptr_MimeOleCreateByteStream = NULL;
extern void *ptr_MimeOleCreateHashTable;
void *ptr_MimeOleCreateHashTable = NULL;
extern void *ptr_MimeOleCreateHeaderTable;
void *ptr_MimeOleCreateHeaderTable = NULL;
extern void *ptr_MimeOleCreateMessage;
void *ptr_MimeOleCreateMessage = NULL;
extern void *ptr_MimeOleCreateMessageParts;
void *ptr_MimeOleCreateMessageParts = NULL;
extern void *ptr_MimeOleCreatePropertySet;
void *ptr_MimeOleCreatePropertySet = NULL;
extern void *ptr_MimeOleCreateSecurity;
void *ptr_MimeOleCreateSecurity = NULL;
extern void *ptr_MimeOleCreateVirtualStream;
void *ptr_MimeOleCreateVirtualStream = NULL;
extern void *ptr_MimeOleDecodeHeader;
void *ptr_MimeOleDecodeHeader = NULL;
extern void *ptr_MimeOleEncodeHeader;
void *ptr_MimeOleEncodeHeader = NULL;
extern void *ptr_MimeOleFileTimeToInetDate;
void *ptr_MimeOleFileTimeToInetDate = NULL;
extern void *ptr_MimeOleFindCharset;
void *ptr_MimeOleFindCharset = NULL;
extern void *ptr_MimeOleGenerateCID;
void *ptr_MimeOleGenerateCID = NULL;
extern void *ptr_MimeOleGenerateFileName;
void *ptr_MimeOleGenerateFileName = NULL;
extern void *ptr_MimeOleGenerateMID;
void *ptr_MimeOleGenerateMID = NULL;
extern void *ptr_MimeOleGetAllocator;
void *ptr_MimeOleGetAllocator = NULL;
extern void *ptr_MimeOleGetBodyPropA;
void *ptr_MimeOleGetBodyPropA = NULL;
extern void *ptr_MimeOleGetBodyPropW;
void *ptr_MimeOleGetBodyPropW = NULL;
extern void *ptr_MimeOleGetCertsFromThumbprints;
void *ptr_MimeOleGetCertsFromThumbprints = NULL;
extern void *ptr_MimeOleGetCharsetInfo;
void *ptr_MimeOleGetCharsetInfo = NULL;
extern void *ptr_MimeOleGetCodePageCharset;
void *ptr_MimeOleGetCodePageCharset = NULL;
extern void *ptr_MimeOleGetCodePageInfo;
void *ptr_MimeOleGetCodePageInfo = NULL;
extern void *ptr_MimeOleGetContentTypeExt;
void *ptr_MimeOleGetContentTypeExt = NULL;
extern void *ptr_MimeOleGetDefaultCharset;
void *ptr_MimeOleGetDefaultCharset = NULL;
extern void *ptr_MimeOleGetExtContentType;
void *ptr_MimeOleGetExtContentType = NULL;
extern void *ptr_MimeOleGetFileExtension;
void *ptr_MimeOleGetFileExtension = NULL;
extern void *ptr_MimeOleGetFileInfo;
void *ptr_MimeOleGetFileInfo = NULL;
extern void *ptr_MimeOleGetFileInfoW;
void *ptr_MimeOleGetFileInfoW = NULL;
extern void *ptr_MimeOleGetInternat;
void *ptr_MimeOleGetInternat = NULL;
extern void *ptr_MimeOleGetPropA;
void *ptr_MimeOleGetPropA = NULL;
extern void *ptr_MimeOleGetPropW;
void *ptr_MimeOleGetPropW = NULL;
extern void *ptr_MimeOleGetPropertySchema;
void *ptr_MimeOleGetPropertySchema = NULL;
extern void *ptr_MimeOleGetRelatedSection;
void *ptr_MimeOleGetRelatedSection = NULL;
extern void *ptr_MimeOleInetDateToFileTime;
void *ptr_MimeOleInetDateToFileTime = NULL;
extern void *ptr_MimeOleObjectFromMoniker;
void *ptr_MimeOleObjectFromMoniker = NULL;
extern void *ptr_MimeOleOpenFileStream;
void *ptr_MimeOleOpenFileStream = NULL;
extern void *ptr_MimeOleParseMhtmlUrl;
void *ptr_MimeOleParseMhtmlUrl = NULL;
extern void *ptr_MimeOleParseRfc822Address;
void *ptr_MimeOleParseRfc822Address = NULL;
extern void *ptr_MimeOleParseRfc822AddressW;
void *ptr_MimeOleParseRfc822AddressW = NULL;
extern void *ptr_MimeOleSMimeCapAddCert;
void *ptr_MimeOleSMimeCapAddCert = NULL;
extern void *ptr_MimeOleSMimeCapAddSMimeCap;
void *ptr_MimeOleSMimeCapAddSMimeCap = NULL;
extern void *ptr_MimeOleSMimeCapGetEncAlg;
void *ptr_MimeOleSMimeCapGetEncAlg = NULL;
extern void *ptr_MimeOleSMimeCapGetHashAlg;
void *ptr_MimeOleSMimeCapGetHashAlg = NULL;
extern void *ptr_MimeOleSMimeCapInit;
void *ptr_MimeOleSMimeCapInit = NULL;
extern void *ptr_MimeOleSMimeCapRelease;
void *ptr_MimeOleSMimeCapRelease = NULL;
extern void *ptr_MimeOleSMimeCapsFromDlg;
void *ptr_MimeOleSMimeCapsFromDlg = NULL;
extern void *ptr_MimeOleSMimeCapsFull;
void *ptr_MimeOleSMimeCapsFull = NULL;
extern void *ptr_MimeOleSMimeCapsToDlg;
void *ptr_MimeOleSMimeCapsToDlg = NULL;
extern void *ptr_MimeOleSetBodyPropA;
void *ptr_MimeOleSetBodyPropA = NULL;
extern void *ptr_MimeOleSetBodyPropW;
void *ptr_MimeOleSetBodyPropW = NULL;
extern void *ptr_MimeOleSetCompatMode;
void *ptr_MimeOleSetCompatMode = NULL;
extern void *ptr_MimeOleSetDefaultCharset;
void *ptr_MimeOleSetDefaultCharset = NULL;
extern void *ptr_MimeOleSetPropA;
void *ptr_MimeOleSetPropA = NULL;
extern void *ptr_MimeOleSetPropW;
void *ptr_MimeOleSetPropW = NULL;
extern void *ptr_MimeOleStripHeaders;
void *ptr_MimeOleStripHeaders = NULL;
extern void *ptr_MimeOleUnEscapeStringInPlace;
void *ptr_MimeOleUnEscapeStringInPlace = NULL;
extern void *ptr_MimeOleUnEscapeStringInPlaceW;
void *ptr_MimeOleUnEscapeStringInPlaceW = NULL;
extern void *ptr_RichMimeEdit_CreateInstance;
void *ptr_RichMimeEdit_CreateInstance = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\inetcomm.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_CreateCommunityTransport = (__vartype(ptr_CreateCommunityTransport))GetProcAddress(hModule, "CreateCommunityTransport");
   ptr_CreateIMAPTransport = (__vartype(ptr_CreateIMAPTransport))GetProcAddress(hModule, "CreateIMAPTransport");
   ptr_CreateIMAPTransport2 = (__vartype(ptr_CreateIMAPTransport2))GetProcAddress(hModule, "CreateIMAPTransport2");
   ptr_CreateNNTPTransport = (__vartype(ptr_CreateNNTPTransport))GetProcAddress(hModule, "CreateNNTPTransport");
   ptr_CreatePOP3Transport = (__vartype(ptr_CreatePOP3Transport))GetProcAddress(hModule, "CreatePOP3Transport");
   ptr_CreateRASTransport = (__vartype(ptr_CreateRASTransport))GetProcAddress(hModule, "CreateRASTransport");
   ptr_CreateRangeList = (__vartype(ptr_CreateRangeList))GetProcAddress(hModule, "CreateRangeList");
   ptr_CreateSMTPTransport = (__vartype(ptr_CreateSMTPTransport))GetProcAddress(hModule, "CreateSMTPTransport");
   ptr_DllCanUnloadNow = (__vartype(ptr_DllCanUnloadNow))GetProcAddress(hModule, "DllCanUnloadNow");
   ptr_DllGetClassObject = (__vartype(ptr_DllGetClassObject))GetProcAddress(hModule, "DllGetClassObject");
   ptr_EssContentHintDecodeEx = (__vartype(ptr_EssContentHintDecodeEx))GetProcAddress(hModule, "EssContentHintDecodeEx");
   ptr_EssContentHintEncodeEx = (__vartype(ptr_EssContentHintEncodeEx))GetProcAddress(hModule, "EssContentHintEncodeEx");
   ptr_EssKeyExchPreferenceDecodeEx = (__vartype(ptr_EssKeyExchPreferenceDecodeEx))GetProcAddress(hModule, "EssKeyExchPreferenceDecodeEx");
   ptr_EssKeyExchPreferenceEncodeEx = (__vartype(ptr_EssKeyExchPreferenceEncodeEx))GetProcAddress(hModule, "EssKeyExchPreferenceEncodeEx");
   ptr_EssMLHistoryDecodeEx = (__vartype(ptr_EssMLHistoryDecodeEx))GetProcAddress(hModule, "EssMLHistoryDecodeEx");
   ptr_EssMLHistoryEncodeEx = (__vartype(ptr_EssMLHistoryEncodeEx))GetProcAddress(hModule, "EssMLHistoryEncodeEx");
   ptr_EssReceiptDecodeEx = (__vartype(ptr_EssReceiptDecodeEx))GetProcAddress(hModule, "EssReceiptDecodeEx");
   ptr_EssReceiptEncodeEx = (__vartype(ptr_EssReceiptEncodeEx))GetProcAddress(hModule, "EssReceiptEncodeEx");
   ptr_EssReceiptRequestDecodeEx = (__vartype(ptr_EssReceiptRequestDecodeEx))GetProcAddress(hModule, "EssReceiptRequestDecodeEx");
   ptr_EssReceiptRequestEncodeEx = (__vartype(ptr_EssReceiptRequestEncodeEx))GetProcAddress(hModule, "EssReceiptRequestEncodeEx");
   ptr_EssSecurityLabelDecodeEx = (__vartype(ptr_EssSecurityLabelDecodeEx))GetProcAddress(hModule, "EssSecurityLabelDecodeEx");
   ptr_EssSecurityLabelEncodeEx = (__vartype(ptr_EssSecurityLabelEncodeEx))GetProcAddress(hModule, "EssSecurityLabelEncodeEx");
   ptr_EssSignCertificateDecodeEx = (__vartype(ptr_EssSignCertificateDecodeEx))GetProcAddress(hModule, "EssSignCertificateDecodeEx");
   ptr_EssSignCertificateEncodeEx = (__vartype(ptr_EssSignCertificateEncodeEx))GetProcAddress(hModule, "EssSignCertificateEncodeEx");
   ptr_GetDllMajorVersion = (__vartype(ptr_GetDllMajorVersion))GetProcAddress(hModule, "GetDllMajorVersion");
   ptr_HrAthGetFileName = (__vartype(ptr_HrAthGetFileName))GetProcAddress(hModule, "HrAthGetFileName");
   ptr_HrAthGetFileNameW = (__vartype(ptr_HrAthGetFileNameW))GetProcAddress(hModule, "HrAthGetFileNameW");
   ptr_HrAttachDataFromBodyPart = (__vartype(ptr_HrAttachDataFromBodyPart))GetProcAddress(hModule, "HrAttachDataFromBodyPart");
   ptr_HrAttachDataFromFile = (__vartype(ptr_HrAttachDataFromFile))GetProcAddress(hModule, "HrAttachDataFromFile");
   ptr_HrCreateDisplayNameWithSizeForFile = (__vartype(ptr_HrCreateDisplayNameWithSizeForFile))GetProcAddress(hModule, "HrCreateDisplayNameWithSizeForFile");
   ptr_HrDoAttachmentVerb = (__vartype(ptr_HrDoAttachmentVerb))GetProcAddress(hModule, "HrDoAttachmentVerb");
   ptr_HrFreeAttachData = (__vartype(ptr_HrFreeAttachData))GetProcAddress(hModule, "HrFreeAttachData");
   ptr_HrGetAttachIcon = (__vartype(ptr_HrGetAttachIcon))GetProcAddress(hModule, "HrGetAttachIcon");
   ptr_HrGetAttachIconByFile = (__vartype(ptr_HrGetAttachIconByFile))GetProcAddress(hModule, "HrGetAttachIconByFile");
   ptr_HrGetDisplayNameWithSizeForFile = (__vartype(ptr_HrGetDisplayNameWithSizeForFile))GetProcAddress(hModule, "HrGetDisplayNameWithSizeForFile");
   ptr_HrGetLastOpenFileDirectory = (__vartype(ptr_HrGetLastOpenFileDirectory))GetProcAddress(hModule, "HrGetLastOpenFileDirectory");
   ptr_HrGetLastOpenFileDirectoryW = (__vartype(ptr_HrGetLastOpenFileDirectoryW))GetProcAddress(hModule, "HrGetLastOpenFileDirectoryW");
   ptr_HrSaveAttachToFile = (__vartype(ptr_HrSaveAttachToFile))GetProcAddress(hModule, "HrSaveAttachToFile");
   ptr_HrSaveAttachmentAs = (__vartype(ptr_HrSaveAttachmentAs))GetProcAddress(hModule, "HrSaveAttachmentAs");
   ptr_MimeEditCreateMimeDocument = (__vartype(ptr_MimeEditCreateMimeDocument))GetProcAddress(hModule, "MimeEditCreateMimeDocument");
   ptr_MimeEditDocumentFromStream = (__vartype(ptr_MimeEditDocumentFromStream))GetProcAddress(hModule, "MimeEditDocumentFromStream");
   ptr_MimeEditGetBackgroundImageUrl = (__vartype(ptr_MimeEditGetBackgroundImageUrl))GetProcAddress(hModule, "MimeEditGetBackgroundImageUrl");
   ptr_MimeEditIsSafeToRun = (__vartype(ptr_MimeEditIsSafeToRun))GetProcAddress(hModule, "MimeEditIsSafeToRun");
   ptr_MimeEditViewSource = (__vartype(ptr_MimeEditViewSource))GetProcAddress(hModule, "MimeEditViewSource");
   ptr_MimeGetAddressFormatW = (__vartype(ptr_MimeGetAddressFormatW))GetProcAddress(hModule, "MimeGetAddressFormatW");
   ptr_MimeOleAlgNameFromSMimeCap = (__vartype(ptr_MimeOleAlgNameFromSMimeCap))GetProcAddress(hModule, "MimeOleAlgNameFromSMimeCap");
   ptr_MimeOleAlgStrengthFromSMimeCap = (__vartype(ptr_MimeOleAlgStrengthFromSMimeCap))GetProcAddress(hModule, "MimeOleAlgStrengthFromSMimeCap");
   ptr_MimeOleClearDirtyTree = (__vartype(ptr_MimeOleClearDirtyTree))GetProcAddress(hModule, "MimeOleClearDirtyTree");
   ptr_MimeOleConvertEnrichedToHTML = (__vartype(ptr_MimeOleConvertEnrichedToHTML))GetProcAddress(hModule, "MimeOleConvertEnrichedToHTML");
   ptr_MimeOleCreateBody = (__vartype(ptr_MimeOleCreateBody))GetProcAddress(hModule, "MimeOleCreateBody");
   ptr_MimeOleCreateByteStream = (__vartype(ptr_MimeOleCreateByteStream))GetProcAddress(hModule, "MimeOleCreateByteStream");
   ptr_MimeOleCreateHashTable = (__vartype(ptr_MimeOleCreateHashTable))GetProcAddress(hModule, "MimeOleCreateHashTable");
   ptr_MimeOleCreateHeaderTable = (__vartype(ptr_MimeOleCreateHeaderTable))GetProcAddress(hModule, "MimeOleCreateHeaderTable");
   ptr_MimeOleCreateMessage = (__vartype(ptr_MimeOleCreateMessage))GetProcAddress(hModule, "MimeOleCreateMessage");
   ptr_MimeOleCreateMessageParts = (__vartype(ptr_MimeOleCreateMessageParts))GetProcAddress(hModule, "MimeOleCreateMessageParts");
   ptr_MimeOleCreatePropertySet = (__vartype(ptr_MimeOleCreatePropertySet))GetProcAddress(hModule, "MimeOleCreatePropertySet");
   ptr_MimeOleCreateSecurity = (__vartype(ptr_MimeOleCreateSecurity))GetProcAddress(hModule, "MimeOleCreateSecurity");
   ptr_MimeOleCreateVirtualStream = (__vartype(ptr_MimeOleCreateVirtualStream))GetProcAddress(hModule, "MimeOleCreateVirtualStream");
   ptr_MimeOleDecodeHeader = (__vartype(ptr_MimeOleDecodeHeader))GetProcAddress(hModule, "MimeOleDecodeHeader");
   ptr_MimeOleEncodeHeader = (__vartype(ptr_MimeOleEncodeHeader))GetProcAddress(hModule, "MimeOleEncodeHeader");
   ptr_MimeOleFileTimeToInetDate = (__vartype(ptr_MimeOleFileTimeToInetDate))GetProcAddress(hModule, "MimeOleFileTimeToInetDate");
   ptr_MimeOleFindCharset = (__vartype(ptr_MimeOleFindCharset))GetProcAddress(hModule, "MimeOleFindCharset");
   ptr_MimeOleGenerateCID = (__vartype(ptr_MimeOleGenerateCID))GetProcAddress(hModule, "MimeOleGenerateCID");
   ptr_MimeOleGenerateFileName = (__vartype(ptr_MimeOleGenerateFileName))GetProcAddress(hModule, "MimeOleGenerateFileName");
   ptr_MimeOleGenerateMID = (__vartype(ptr_MimeOleGenerateMID))GetProcAddress(hModule, "MimeOleGenerateMID");
   ptr_MimeOleGetAllocator = (__vartype(ptr_MimeOleGetAllocator))GetProcAddress(hModule, "MimeOleGetAllocator");
   ptr_MimeOleGetBodyPropA = (__vartype(ptr_MimeOleGetBodyPropA))GetProcAddress(hModule, "MimeOleGetBodyPropA");
   ptr_MimeOleGetBodyPropW = (__vartype(ptr_MimeOleGetBodyPropW))GetProcAddress(hModule, "MimeOleGetBodyPropW");
   ptr_MimeOleGetCertsFromThumbprints = (__vartype(ptr_MimeOleGetCertsFromThumbprints))GetProcAddress(hModule, "MimeOleGetCertsFromThumbprints");
   ptr_MimeOleGetCharsetInfo = (__vartype(ptr_MimeOleGetCharsetInfo))GetProcAddress(hModule, "MimeOleGetCharsetInfo");
   ptr_MimeOleGetCodePageCharset = (__vartype(ptr_MimeOleGetCodePageCharset))GetProcAddress(hModule, "MimeOleGetCodePageCharset");
   ptr_MimeOleGetCodePageInfo = (__vartype(ptr_MimeOleGetCodePageInfo))GetProcAddress(hModule, "MimeOleGetCodePageInfo");
   ptr_MimeOleGetContentTypeExt = (__vartype(ptr_MimeOleGetContentTypeExt))GetProcAddress(hModule, "MimeOleGetContentTypeExt");
   ptr_MimeOleGetDefaultCharset = (__vartype(ptr_MimeOleGetDefaultCharset))GetProcAddress(hModule, "MimeOleGetDefaultCharset");
   ptr_MimeOleGetExtContentType = (__vartype(ptr_MimeOleGetExtContentType))GetProcAddress(hModule, "MimeOleGetExtContentType");
   ptr_MimeOleGetFileExtension = (__vartype(ptr_MimeOleGetFileExtension))GetProcAddress(hModule, "MimeOleGetFileExtension");
   ptr_MimeOleGetFileInfo = (__vartype(ptr_MimeOleGetFileInfo))GetProcAddress(hModule, "MimeOleGetFileInfo");
   ptr_MimeOleGetFileInfoW = (__vartype(ptr_MimeOleGetFileInfoW))GetProcAddress(hModule, "MimeOleGetFileInfoW");
   ptr_MimeOleGetInternat = (__vartype(ptr_MimeOleGetInternat))GetProcAddress(hModule, "MimeOleGetInternat");
   ptr_MimeOleGetPropA = (__vartype(ptr_MimeOleGetPropA))GetProcAddress(hModule, "MimeOleGetPropA");
   ptr_MimeOleGetPropW = (__vartype(ptr_MimeOleGetPropW))GetProcAddress(hModule, "MimeOleGetPropW");
   ptr_MimeOleGetPropertySchema = (__vartype(ptr_MimeOleGetPropertySchema))GetProcAddress(hModule, "MimeOleGetPropertySchema");
   ptr_MimeOleGetRelatedSection = (__vartype(ptr_MimeOleGetRelatedSection))GetProcAddress(hModule, "MimeOleGetRelatedSection");
   ptr_MimeOleInetDateToFileTime = (__vartype(ptr_MimeOleInetDateToFileTime))GetProcAddress(hModule, "MimeOleInetDateToFileTime");
   ptr_MimeOleObjectFromMoniker = (__vartype(ptr_MimeOleObjectFromMoniker))GetProcAddress(hModule, "MimeOleObjectFromMoniker");
   ptr_MimeOleOpenFileStream = (__vartype(ptr_MimeOleOpenFileStream))GetProcAddress(hModule, "MimeOleOpenFileStream");
   ptr_MimeOleParseMhtmlUrl = (__vartype(ptr_MimeOleParseMhtmlUrl))GetProcAddress(hModule, "MimeOleParseMhtmlUrl");
   ptr_MimeOleParseRfc822Address = (__vartype(ptr_MimeOleParseRfc822Address))GetProcAddress(hModule, "MimeOleParseRfc822Address");
   ptr_MimeOleParseRfc822AddressW = (__vartype(ptr_MimeOleParseRfc822AddressW))GetProcAddress(hModule, "MimeOleParseRfc822AddressW");
   ptr_MimeOleSMimeCapAddCert = (__vartype(ptr_MimeOleSMimeCapAddCert))GetProcAddress(hModule, "MimeOleSMimeCapAddCert");
   ptr_MimeOleSMimeCapAddSMimeCap = (__vartype(ptr_MimeOleSMimeCapAddSMimeCap))GetProcAddress(hModule, "MimeOleSMimeCapAddSMimeCap");
   ptr_MimeOleSMimeCapGetEncAlg = (__vartype(ptr_MimeOleSMimeCapGetEncAlg))GetProcAddress(hModule, "MimeOleSMimeCapGetEncAlg");
   ptr_MimeOleSMimeCapGetHashAlg = (__vartype(ptr_MimeOleSMimeCapGetHashAlg))GetProcAddress(hModule, "MimeOleSMimeCapGetHashAlg");
   ptr_MimeOleSMimeCapInit = (__vartype(ptr_MimeOleSMimeCapInit))GetProcAddress(hModule, "MimeOleSMimeCapInit");
   ptr_MimeOleSMimeCapRelease = (__vartype(ptr_MimeOleSMimeCapRelease))GetProcAddress(hModule, "MimeOleSMimeCapRelease");
   ptr_MimeOleSMimeCapsFromDlg = (__vartype(ptr_MimeOleSMimeCapsFromDlg))GetProcAddress(hModule, "MimeOleSMimeCapsFromDlg");
   ptr_MimeOleSMimeCapsFull = (__vartype(ptr_MimeOleSMimeCapsFull))GetProcAddress(hModule, "MimeOleSMimeCapsFull");
   ptr_MimeOleSMimeCapsToDlg = (__vartype(ptr_MimeOleSMimeCapsToDlg))GetProcAddress(hModule, "MimeOleSMimeCapsToDlg");
   ptr_MimeOleSetBodyPropA = (__vartype(ptr_MimeOleSetBodyPropA))GetProcAddress(hModule, "MimeOleSetBodyPropA");
   ptr_MimeOleSetBodyPropW = (__vartype(ptr_MimeOleSetBodyPropW))GetProcAddress(hModule, "MimeOleSetBodyPropW");
   ptr_MimeOleSetCompatMode = (__vartype(ptr_MimeOleSetCompatMode))GetProcAddress(hModule, "MimeOleSetCompatMode");
   ptr_MimeOleSetDefaultCharset = (__vartype(ptr_MimeOleSetDefaultCharset))GetProcAddress(hModule, "MimeOleSetDefaultCharset");
   ptr_MimeOleSetPropA = (__vartype(ptr_MimeOleSetPropA))GetProcAddress(hModule, "MimeOleSetPropA");
   ptr_MimeOleSetPropW = (__vartype(ptr_MimeOleSetPropW))GetProcAddress(hModule, "MimeOleSetPropW");
   ptr_MimeOleStripHeaders = (__vartype(ptr_MimeOleStripHeaders))GetProcAddress(hModule, "MimeOleStripHeaders");
   ptr_MimeOleUnEscapeStringInPlace = (__vartype(ptr_MimeOleUnEscapeStringInPlace))GetProcAddress(hModule, "MimeOleUnEscapeStringInPlace");
   ptr_MimeOleUnEscapeStringInPlaceW = (__vartype(ptr_MimeOleUnEscapeStringInPlaceW))GetProcAddress(hModule, "MimeOleUnEscapeStringInPlaceW");
   ptr_RichMimeEdit_CreateInstance = (__vartype(ptr_RichMimeEdit_CreateInstance))GetProcAddress(hModule, "RichMimeEdit_CreateInstance");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

