#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_DllCanUnloadNow;
void *ptr_DllCanUnloadNow = NULL;
extern void *ptr_DllGetClassObject;
void *ptr_DllGetClassObject = NULL;
extern void *ptr_DllRegisterServer;
void *ptr_DllRegisterServer = NULL;
extern void *ptr_DllUnregisterServer;
void *ptr_DllUnregisterServer = NULL;
extern void *ptr_DockPattern_SetDockPosition;
void *ptr_DockPattern_SetDockPosition = NULL;
extern void *ptr_ExpandCollapsePattern_Collapse;
void *ptr_ExpandCollapsePattern_Collapse = NULL;
extern void *ptr_ExpandCollapsePattern_Expand;
void *ptr_ExpandCollapsePattern_Expand = NULL;
extern void *ptr_GridPattern_GetItem;
void *ptr_GridPattern_GetItem = NULL;
extern void *ptr_InvokePattern_Invoke;
void *ptr_InvokePattern_Invoke = NULL;
extern void *ptr_ItemContainerPattern_FindItemByProperty;
void *ptr_ItemContainerPattern_FindItemByProperty = NULL;
extern void *ptr_LegacyIAccessiblePattern_DoDefaultAction;
void *ptr_LegacyIAccessiblePattern_DoDefaultAction = NULL;
extern void *ptr_LegacyIAccessiblePattern_GetIAccessible;
void *ptr_LegacyIAccessiblePattern_GetIAccessible = NULL;
extern void *ptr_LegacyIAccessiblePattern_Select;
void *ptr_LegacyIAccessiblePattern_Select = NULL;
extern void *ptr_LegacyIAccessiblePattern_SetValue;
void *ptr_LegacyIAccessiblePattern_SetValue = NULL;
extern void *ptr_MultipleViewPattern_GetViewName;
void *ptr_MultipleViewPattern_GetViewName = NULL;
extern void *ptr_MultipleViewPattern_SetCurrentView;
void *ptr_MultipleViewPattern_SetCurrentView = NULL;
extern void *ptr_RangeValuePattern_SetValue;
void *ptr_RangeValuePattern_SetValue = NULL;
extern void *ptr_ScrollItemPattern_ScrollIntoView;
void *ptr_ScrollItemPattern_ScrollIntoView = NULL;
extern void *ptr_ScrollPattern_Scroll;
void *ptr_ScrollPattern_Scroll = NULL;
extern void *ptr_ScrollPattern_SetScrollPercent;
void *ptr_ScrollPattern_SetScrollPercent = NULL;
extern void *ptr_SelectionItemPattern_AddToSelection;
void *ptr_SelectionItemPattern_AddToSelection = NULL;
extern void *ptr_SelectionItemPattern_RemoveFromSelection;
void *ptr_SelectionItemPattern_RemoveFromSelection = NULL;
extern void *ptr_SelectionItemPattern_Select;
void *ptr_SelectionItemPattern_Select = NULL;
extern void *ptr_SynchronizedInputPattern_Cancel;
void *ptr_SynchronizedInputPattern_Cancel = NULL;
extern void *ptr_SynchronizedInputPattern_StartListening;
void *ptr_SynchronizedInputPattern_StartListening = NULL;
extern void *ptr_TextPattern_GetSelection;
void *ptr_TextPattern_GetSelection = NULL;
extern void *ptr_TextPattern_GetVisibleRanges;
void *ptr_TextPattern_GetVisibleRanges = NULL;
extern void *ptr_TextPattern_RangeFromChild;
void *ptr_TextPattern_RangeFromChild = NULL;
extern void *ptr_TextPattern_RangeFromPoint;
void *ptr_TextPattern_RangeFromPoint = NULL;
extern void *ptr_TextPattern_get_DocumentRange;
void *ptr_TextPattern_get_DocumentRange = NULL;
extern void *ptr_TextPattern_get_SupportedTextSelection;
void *ptr_TextPattern_get_SupportedTextSelection = NULL;
extern void *ptr_TextRange_AddToSelection;
void *ptr_TextRange_AddToSelection = NULL;
extern void *ptr_TextRange_Clone;
void *ptr_TextRange_Clone = NULL;
extern void *ptr_TextRange_Compare;
void *ptr_TextRange_Compare = NULL;
extern void *ptr_TextRange_CompareEndpoints;
void *ptr_TextRange_CompareEndpoints = NULL;
extern void *ptr_TextRange_ExpandToEnclosingUnit;
void *ptr_TextRange_ExpandToEnclosingUnit = NULL;
extern void *ptr_TextRange_FindAttribute;
void *ptr_TextRange_FindAttribute = NULL;
extern void *ptr_TextRange_FindText;
void *ptr_TextRange_FindText = NULL;
extern void *ptr_TextRange_GetAttributeValue;
void *ptr_TextRange_GetAttributeValue = NULL;
extern void *ptr_TextRange_GetBoundingRectangles;
void *ptr_TextRange_GetBoundingRectangles = NULL;
extern void *ptr_TextRange_GetChildren;
void *ptr_TextRange_GetChildren = NULL;
extern void *ptr_TextRange_GetEnclosingElement;
void *ptr_TextRange_GetEnclosingElement = NULL;
extern void *ptr_TextRange_GetText;
void *ptr_TextRange_GetText = NULL;
extern void *ptr_TextRange_Move;
void *ptr_TextRange_Move = NULL;
extern void *ptr_TextRange_MoveEndpointByRange;
void *ptr_TextRange_MoveEndpointByRange = NULL;
extern void *ptr_TextRange_MoveEndpointByUnit;
void *ptr_TextRange_MoveEndpointByUnit = NULL;
extern void *ptr_TextRange_RemoveFromSelection;
void *ptr_TextRange_RemoveFromSelection = NULL;
extern void *ptr_TextRange_ScrollIntoView;
void *ptr_TextRange_ScrollIntoView = NULL;
extern void *ptr_TextRange_Select;
void *ptr_TextRange_Select = NULL;
extern void *ptr_TogglePattern_Toggle;
void *ptr_TogglePattern_Toggle = NULL;
extern void *ptr_TransformPattern_Move;
void *ptr_TransformPattern_Move = NULL;
extern void *ptr_TransformPattern_Resize;
void *ptr_TransformPattern_Resize = NULL;
extern void *ptr_TransformPattern_Rotate;
void *ptr_TransformPattern_Rotate = NULL;
extern void *ptr_UiaAddEvent;
void *ptr_UiaAddEvent = NULL;
extern void *ptr_UiaClientsAreListening;
void *ptr_UiaClientsAreListening = NULL;
extern void *ptr_UiaEventAddWindow;
void *ptr_UiaEventAddWindow = NULL;
extern void *ptr_UiaEventRemoveWindow;
void *ptr_UiaEventRemoveWindow = NULL;
extern void *ptr_UiaFind;
void *ptr_UiaFind = NULL;
extern void *ptr_UiaGetErrorDescription;
void *ptr_UiaGetErrorDescription = NULL;
extern void *ptr_UiaGetPatternProvider;
void *ptr_UiaGetPatternProvider = NULL;
extern void *ptr_UiaGetPropertyValue;
void *ptr_UiaGetPropertyValue = NULL;
extern void *ptr_UiaGetReservedMixedAttributeValue;
void *ptr_UiaGetReservedMixedAttributeValue = NULL;
extern void *ptr_UiaGetReservedNotSupportedValue;
void *ptr_UiaGetReservedNotSupportedValue = NULL;
extern void *ptr_UiaGetRootNode;
void *ptr_UiaGetRootNode = NULL;
extern void *ptr_UiaGetRuntimeId;
void *ptr_UiaGetRuntimeId = NULL;
extern void *ptr_UiaGetUpdatedCache;
void *ptr_UiaGetUpdatedCache = NULL;
extern void *ptr_UiaHPatternObjectFromVariant;
void *ptr_UiaHPatternObjectFromVariant = NULL;
extern void *ptr_UiaHTextRangeFromVariant;
void *ptr_UiaHTextRangeFromVariant = NULL;
extern void *ptr_UiaHUiaNodeFromVariant;
void *ptr_UiaHUiaNodeFromVariant = NULL;
extern void *ptr_UiaHasServerSideProvider;
void *ptr_UiaHasServerSideProvider = NULL;
extern void *ptr_UiaHostProviderFromHwnd;
void *ptr_UiaHostProviderFromHwnd = NULL;
extern void *ptr_UiaLookupId;
void *ptr_UiaLookupId = NULL;
extern void *ptr_UiaNavigate;
void *ptr_UiaNavigate = NULL;
extern void *ptr_UiaNodeFromFocus;
void *ptr_UiaNodeFromFocus = NULL;
extern void *ptr_UiaNodeFromHandle;
void *ptr_UiaNodeFromHandle = NULL;
extern void *ptr_UiaNodeFromPoint;
void *ptr_UiaNodeFromPoint = NULL;
extern void *ptr_UiaNodeFromProvider;
void *ptr_UiaNodeFromProvider = NULL;
extern void *ptr_UiaNodeRelease;
void *ptr_UiaNodeRelease = NULL;
extern void *ptr_UiaPatternRelease;
void *ptr_UiaPatternRelease = NULL;
extern void *ptr_UiaRaiseAsyncContentLoadedEvent;
void *ptr_UiaRaiseAsyncContentLoadedEvent = NULL;
extern void *ptr_UiaRaiseAutomationEvent;
void *ptr_UiaRaiseAutomationEvent = NULL;
extern void *ptr_UiaRaiseAutomationPropertyChangedEvent;
void *ptr_UiaRaiseAutomationPropertyChangedEvent = NULL;
extern void *ptr_UiaRaiseStructureChangedEvent;
void *ptr_UiaRaiseStructureChangedEvent = NULL;
extern void *ptr_UiaRegisterProviderCallback;
void *ptr_UiaRegisterProviderCallback = NULL;
extern void *ptr_UiaRemoveEvent;
void *ptr_UiaRemoveEvent = NULL;
extern void *ptr_UiaReturnRawElementProvider;
void *ptr_UiaReturnRawElementProvider = NULL;
extern void *ptr_UiaSetFocus;
void *ptr_UiaSetFocus = NULL;
extern void *ptr_UiaTextRangeRelease;
void *ptr_UiaTextRangeRelease = NULL;
extern void *ptr_ValuePattern_SetValue;
void *ptr_ValuePattern_SetValue = NULL;
extern void *ptr_VirtualizedItemPattern_Realize;
void *ptr_VirtualizedItemPattern_Realize = NULL;
extern void *ptr_WindowPattern_Close;
void *ptr_WindowPattern_Close = NULL;
extern void *ptr_WindowPattern_SetWindowVisualState;
void *ptr_WindowPattern_SetWindowVisualState = NULL;
extern void *ptr_WindowPattern_WaitForInputIdle;
void *ptr_WindowPattern_WaitForInputIdle = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\UIAutomationCore.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_DllCanUnloadNow = (__vartype(ptr_DllCanUnloadNow))GetProcAddress(hModule, "DllCanUnloadNow");
   ptr_DllGetClassObject = (__vartype(ptr_DllGetClassObject))GetProcAddress(hModule, "DllGetClassObject");
   ptr_DllRegisterServer = (__vartype(ptr_DllRegisterServer))GetProcAddress(hModule, "DllRegisterServer");
   ptr_DllUnregisterServer = (__vartype(ptr_DllUnregisterServer))GetProcAddress(hModule, "DllUnregisterServer");
   ptr_DockPattern_SetDockPosition = (__vartype(ptr_DockPattern_SetDockPosition))GetProcAddress(hModule, "DockPattern_SetDockPosition");
   ptr_ExpandCollapsePattern_Collapse = (__vartype(ptr_ExpandCollapsePattern_Collapse))GetProcAddress(hModule, "ExpandCollapsePattern_Collapse");
   ptr_ExpandCollapsePattern_Expand = (__vartype(ptr_ExpandCollapsePattern_Expand))GetProcAddress(hModule, "ExpandCollapsePattern_Expand");
   ptr_GridPattern_GetItem = (__vartype(ptr_GridPattern_GetItem))GetProcAddress(hModule, "GridPattern_GetItem");
   ptr_InvokePattern_Invoke = (__vartype(ptr_InvokePattern_Invoke))GetProcAddress(hModule, "InvokePattern_Invoke");
   ptr_ItemContainerPattern_FindItemByProperty = (__vartype(ptr_ItemContainerPattern_FindItemByProperty))GetProcAddress(hModule, "ItemContainerPattern_FindItemByProperty");
   ptr_LegacyIAccessiblePattern_DoDefaultAction = (__vartype(ptr_LegacyIAccessiblePattern_DoDefaultAction))GetProcAddress(hModule, "LegacyIAccessiblePattern_DoDefaultAction");
   ptr_LegacyIAccessiblePattern_GetIAccessible = (__vartype(ptr_LegacyIAccessiblePattern_GetIAccessible))GetProcAddress(hModule, "LegacyIAccessiblePattern_GetIAccessible");
   ptr_LegacyIAccessiblePattern_Select = (__vartype(ptr_LegacyIAccessiblePattern_Select))GetProcAddress(hModule, "LegacyIAccessiblePattern_Select");
   ptr_LegacyIAccessiblePattern_SetValue = (__vartype(ptr_LegacyIAccessiblePattern_SetValue))GetProcAddress(hModule, "LegacyIAccessiblePattern_SetValue");
   ptr_MultipleViewPattern_GetViewName = (__vartype(ptr_MultipleViewPattern_GetViewName))GetProcAddress(hModule, "MultipleViewPattern_GetViewName");
   ptr_MultipleViewPattern_SetCurrentView = (__vartype(ptr_MultipleViewPattern_SetCurrentView))GetProcAddress(hModule, "MultipleViewPattern_SetCurrentView");
   ptr_RangeValuePattern_SetValue = (__vartype(ptr_RangeValuePattern_SetValue))GetProcAddress(hModule, "RangeValuePattern_SetValue");
   ptr_ScrollItemPattern_ScrollIntoView = (__vartype(ptr_ScrollItemPattern_ScrollIntoView))GetProcAddress(hModule, "ScrollItemPattern_ScrollIntoView");
   ptr_ScrollPattern_Scroll = (__vartype(ptr_ScrollPattern_Scroll))GetProcAddress(hModule, "ScrollPattern_Scroll");
   ptr_ScrollPattern_SetScrollPercent = (__vartype(ptr_ScrollPattern_SetScrollPercent))GetProcAddress(hModule, "ScrollPattern_SetScrollPercent");
   ptr_SelectionItemPattern_AddToSelection = (__vartype(ptr_SelectionItemPattern_AddToSelection))GetProcAddress(hModule, "SelectionItemPattern_AddToSelection");
   ptr_SelectionItemPattern_RemoveFromSelection = (__vartype(ptr_SelectionItemPattern_RemoveFromSelection))GetProcAddress(hModule, "SelectionItemPattern_RemoveFromSelection");
   ptr_SelectionItemPattern_Select = (__vartype(ptr_SelectionItemPattern_Select))GetProcAddress(hModule, "SelectionItemPattern_Select");
   ptr_SynchronizedInputPattern_Cancel = (__vartype(ptr_SynchronizedInputPattern_Cancel))GetProcAddress(hModule, "SynchronizedInputPattern_Cancel");
   ptr_SynchronizedInputPattern_StartListening = (__vartype(ptr_SynchronizedInputPattern_StartListening))GetProcAddress(hModule, "SynchronizedInputPattern_StartListening");
   ptr_TextPattern_GetSelection = (__vartype(ptr_TextPattern_GetSelection))GetProcAddress(hModule, "TextPattern_GetSelection");
   ptr_TextPattern_GetVisibleRanges = (__vartype(ptr_TextPattern_GetVisibleRanges))GetProcAddress(hModule, "TextPattern_GetVisibleRanges");
   ptr_TextPattern_RangeFromChild = (__vartype(ptr_TextPattern_RangeFromChild))GetProcAddress(hModule, "TextPattern_RangeFromChild");
   ptr_TextPattern_RangeFromPoint = (__vartype(ptr_TextPattern_RangeFromPoint))GetProcAddress(hModule, "TextPattern_RangeFromPoint");
   ptr_TextPattern_get_DocumentRange = (__vartype(ptr_TextPattern_get_DocumentRange))GetProcAddress(hModule, "TextPattern_get_DocumentRange");
   ptr_TextPattern_get_SupportedTextSelection = (__vartype(ptr_TextPattern_get_SupportedTextSelection))GetProcAddress(hModule, "TextPattern_get_SupportedTextSelection");
   ptr_TextRange_AddToSelection = (__vartype(ptr_TextRange_AddToSelection))GetProcAddress(hModule, "TextRange_AddToSelection");
   ptr_TextRange_Clone = (__vartype(ptr_TextRange_Clone))GetProcAddress(hModule, "TextRange_Clone");
   ptr_TextRange_Compare = (__vartype(ptr_TextRange_Compare))GetProcAddress(hModule, "TextRange_Compare");
   ptr_TextRange_CompareEndpoints = (__vartype(ptr_TextRange_CompareEndpoints))GetProcAddress(hModule, "TextRange_CompareEndpoints");
   ptr_TextRange_ExpandToEnclosingUnit = (__vartype(ptr_TextRange_ExpandToEnclosingUnit))GetProcAddress(hModule, "TextRange_ExpandToEnclosingUnit");
   ptr_TextRange_FindAttribute = (__vartype(ptr_TextRange_FindAttribute))GetProcAddress(hModule, "TextRange_FindAttribute");
   ptr_TextRange_FindText = (__vartype(ptr_TextRange_FindText))GetProcAddress(hModule, "TextRange_FindText");
   ptr_TextRange_GetAttributeValue = (__vartype(ptr_TextRange_GetAttributeValue))GetProcAddress(hModule, "TextRange_GetAttributeValue");
   ptr_TextRange_GetBoundingRectangles = (__vartype(ptr_TextRange_GetBoundingRectangles))GetProcAddress(hModule, "TextRange_GetBoundingRectangles");
   ptr_TextRange_GetChildren = (__vartype(ptr_TextRange_GetChildren))GetProcAddress(hModule, "TextRange_GetChildren");
   ptr_TextRange_GetEnclosingElement = (__vartype(ptr_TextRange_GetEnclosingElement))GetProcAddress(hModule, "TextRange_GetEnclosingElement");
   ptr_TextRange_GetText = (__vartype(ptr_TextRange_GetText))GetProcAddress(hModule, "TextRange_GetText");
   ptr_TextRange_Move = (__vartype(ptr_TextRange_Move))GetProcAddress(hModule, "TextRange_Move");
   ptr_TextRange_MoveEndpointByRange = (__vartype(ptr_TextRange_MoveEndpointByRange))GetProcAddress(hModule, "TextRange_MoveEndpointByRange");
   ptr_TextRange_MoveEndpointByUnit = (__vartype(ptr_TextRange_MoveEndpointByUnit))GetProcAddress(hModule, "TextRange_MoveEndpointByUnit");
   ptr_TextRange_RemoveFromSelection = (__vartype(ptr_TextRange_RemoveFromSelection))GetProcAddress(hModule, "TextRange_RemoveFromSelection");
   ptr_TextRange_ScrollIntoView = (__vartype(ptr_TextRange_ScrollIntoView))GetProcAddress(hModule, "TextRange_ScrollIntoView");
   ptr_TextRange_Select = (__vartype(ptr_TextRange_Select))GetProcAddress(hModule, "TextRange_Select");
   ptr_TogglePattern_Toggle = (__vartype(ptr_TogglePattern_Toggle))GetProcAddress(hModule, "TogglePattern_Toggle");
   ptr_TransformPattern_Move = (__vartype(ptr_TransformPattern_Move))GetProcAddress(hModule, "TransformPattern_Move");
   ptr_TransformPattern_Resize = (__vartype(ptr_TransformPattern_Resize))GetProcAddress(hModule, "TransformPattern_Resize");
   ptr_TransformPattern_Rotate = (__vartype(ptr_TransformPattern_Rotate))GetProcAddress(hModule, "TransformPattern_Rotate");
   ptr_UiaAddEvent = (__vartype(ptr_UiaAddEvent))GetProcAddress(hModule, "UiaAddEvent");
   ptr_UiaClientsAreListening = (__vartype(ptr_UiaClientsAreListening))GetProcAddress(hModule, "UiaClientsAreListening");
   ptr_UiaEventAddWindow = (__vartype(ptr_UiaEventAddWindow))GetProcAddress(hModule, "UiaEventAddWindow");
   ptr_UiaEventRemoveWindow = (__vartype(ptr_UiaEventRemoveWindow))GetProcAddress(hModule, "UiaEventRemoveWindow");
   ptr_UiaFind = (__vartype(ptr_UiaFind))GetProcAddress(hModule, "UiaFind");
   ptr_UiaGetErrorDescription = (__vartype(ptr_UiaGetErrorDescription))GetProcAddress(hModule, "UiaGetErrorDescription");
   ptr_UiaGetPatternProvider = (__vartype(ptr_UiaGetPatternProvider))GetProcAddress(hModule, "UiaGetPatternProvider");
   ptr_UiaGetPropertyValue = (__vartype(ptr_UiaGetPropertyValue))GetProcAddress(hModule, "UiaGetPropertyValue");
   ptr_UiaGetReservedMixedAttributeValue = (__vartype(ptr_UiaGetReservedMixedAttributeValue))GetProcAddress(hModule, "UiaGetReservedMixedAttributeValue");
   ptr_UiaGetReservedNotSupportedValue = (__vartype(ptr_UiaGetReservedNotSupportedValue))GetProcAddress(hModule, "UiaGetReservedNotSupportedValue");
   ptr_UiaGetRootNode = (__vartype(ptr_UiaGetRootNode))GetProcAddress(hModule, "UiaGetRootNode");
   ptr_UiaGetRuntimeId = (__vartype(ptr_UiaGetRuntimeId))GetProcAddress(hModule, "UiaGetRuntimeId");
   ptr_UiaGetUpdatedCache = (__vartype(ptr_UiaGetUpdatedCache))GetProcAddress(hModule, "UiaGetUpdatedCache");
   ptr_UiaHPatternObjectFromVariant = (__vartype(ptr_UiaHPatternObjectFromVariant))GetProcAddress(hModule, "UiaHPatternObjectFromVariant");
   ptr_UiaHTextRangeFromVariant = (__vartype(ptr_UiaHTextRangeFromVariant))GetProcAddress(hModule, "UiaHTextRangeFromVariant");
   ptr_UiaHUiaNodeFromVariant = (__vartype(ptr_UiaHUiaNodeFromVariant))GetProcAddress(hModule, "UiaHUiaNodeFromVariant");
   ptr_UiaHasServerSideProvider = (__vartype(ptr_UiaHasServerSideProvider))GetProcAddress(hModule, "UiaHasServerSideProvider");
   ptr_UiaHostProviderFromHwnd = (__vartype(ptr_UiaHostProviderFromHwnd))GetProcAddress(hModule, "UiaHostProviderFromHwnd");
   ptr_UiaLookupId = (__vartype(ptr_UiaLookupId))GetProcAddress(hModule, "UiaLookupId");
   ptr_UiaNavigate = (__vartype(ptr_UiaNavigate))GetProcAddress(hModule, "UiaNavigate");
   ptr_UiaNodeFromFocus = (__vartype(ptr_UiaNodeFromFocus))GetProcAddress(hModule, "UiaNodeFromFocus");
   ptr_UiaNodeFromHandle = (__vartype(ptr_UiaNodeFromHandle))GetProcAddress(hModule, "UiaNodeFromHandle");
   ptr_UiaNodeFromPoint = (__vartype(ptr_UiaNodeFromPoint))GetProcAddress(hModule, "UiaNodeFromPoint");
   ptr_UiaNodeFromProvider = (__vartype(ptr_UiaNodeFromProvider))GetProcAddress(hModule, "UiaNodeFromProvider");
   ptr_UiaNodeRelease = (__vartype(ptr_UiaNodeRelease))GetProcAddress(hModule, "UiaNodeRelease");
   ptr_UiaPatternRelease = (__vartype(ptr_UiaPatternRelease))GetProcAddress(hModule, "UiaPatternRelease");
   ptr_UiaRaiseAsyncContentLoadedEvent = (__vartype(ptr_UiaRaiseAsyncContentLoadedEvent))GetProcAddress(hModule, "UiaRaiseAsyncContentLoadedEvent");
   ptr_UiaRaiseAutomationEvent = (__vartype(ptr_UiaRaiseAutomationEvent))GetProcAddress(hModule, "UiaRaiseAutomationEvent");
   ptr_UiaRaiseAutomationPropertyChangedEvent = (__vartype(ptr_UiaRaiseAutomationPropertyChangedEvent))GetProcAddress(hModule, "UiaRaiseAutomationPropertyChangedEvent");
   ptr_UiaRaiseStructureChangedEvent = (__vartype(ptr_UiaRaiseStructureChangedEvent))GetProcAddress(hModule, "UiaRaiseStructureChangedEvent");
   ptr_UiaRegisterProviderCallback = (__vartype(ptr_UiaRegisterProviderCallback))GetProcAddress(hModule, "UiaRegisterProviderCallback");
   ptr_UiaRemoveEvent = (__vartype(ptr_UiaRemoveEvent))GetProcAddress(hModule, "UiaRemoveEvent");
   ptr_UiaReturnRawElementProvider = (__vartype(ptr_UiaReturnRawElementProvider))GetProcAddress(hModule, "UiaReturnRawElementProvider");
   ptr_UiaSetFocus = (__vartype(ptr_UiaSetFocus))GetProcAddress(hModule, "UiaSetFocus");
   ptr_UiaTextRangeRelease = (__vartype(ptr_UiaTextRangeRelease))GetProcAddress(hModule, "UiaTextRangeRelease");
   ptr_ValuePattern_SetValue = (__vartype(ptr_ValuePattern_SetValue))GetProcAddress(hModule, "ValuePattern_SetValue");
   ptr_VirtualizedItemPattern_Realize = (__vartype(ptr_VirtualizedItemPattern_Realize))GetProcAddress(hModule, "VirtualizedItemPattern_Realize");
   ptr_WindowPattern_Close = (__vartype(ptr_WindowPattern_Close))GetProcAddress(hModule, "WindowPattern_Close");
   ptr_WindowPattern_SetWindowVisualState = (__vartype(ptr_WindowPattern_SetWindowVisualState))GetProcAddress(hModule, "WindowPattern_SetWindowVisualState");
   ptr_WindowPattern_WaitForInputIdle = (__vartype(ptr_WindowPattern_WaitForInputIdle))GetProcAddress(hModule, "WindowPattern_WaitForInputIdle");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

