#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_LogonIdFromWinStationNameA;
void *ptr_LogonIdFromWinStationNameA = NULL;
extern void *ptr_LogonIdFromWinStationNameW;
void *ptr_LogonIdFromWinStationNameW = NULL;
extern void *ptr_RemoteAssistancePrepareSystemRestore;
void *ptr_RemoteAssistancePrepareSystemRestore = NULL;
extern void *ptr_ServerGetInternetConnectorStatus;
void *ptr_ServerGetInternetConnectorStatus = NULL;
extern void *ptr_ServerLicensingClose;
void *ptr_ServerLicensingClose = NULL;
extern void *ptr_ServerLicensingDeactivateCurrentPolicy;
void *ptr_ServerLicensingDeactivateCurrentPolicy = NULL;
extern void *ptr_ServerLicensingFreePolicyInformation;
void *ptr_ServerLicensingFreePolicyInformation = NULL;
extern void *ptr_ServerLicensingGetAvailablePolicyIds;
void *ptr_ServerLicensingGetAvailablePolicyIds = NULL;
extern void *ptr_ServerLicensingGetPolicy;
void *ptr_ServerLicensingGetPolicy = NULL;
extern void *ptr_ServerLicensingGetPolicyInformationA;
void *ptr_ServerLicensingGetPolicyInformationA = NULL;
extern void *ptr_ServerLicensingGetPolicyInformationW;
void *ptr_ServerLicensingGetPolicyInformationW = NULL;
extern void *ptr_ServerLicensingLoadPolicy;
void *ptr_ServerLicensingLoadPolicy = NULL;
extern void *ptr_ServerLicensingOpenA;
void *ptr_ServerLicensingOpenA = NULL;
extern void *ptr_ServerLicensingOpenW;
void *ptr_ServerLicensingOpenW = NULL;
extern void *ptr_ServerLicensingSetPolicy;
void *ptr_ServerLicensingSetPolicy = NULL;
extern void *ptr_ServerLicensingUnloadPolicy;
void *ptr_ServerLicensingUnloadPolicy = NULL;
extern void *ptr_ServerQueryInetConnectorInformationA;
void *ptr_ServerQueryInetConnectorInformationA = NULL;
extern void *ptr_ServerQueryInetConnectorInformationW;
void *ptr_ServerQueryInetConnectorInformationW = NULL;
extern void *ptr_ServerSetInternetConnectorStatus;
void *ptr_ServerSetInternetConnectorStatus = NULL;
extern void *ptr_WinStationActivateLicense;
void *ptr_WinStationActivateLicense = NULL;
extern void *ptr_WinStationAutoReconnect;
void *ptr_WinStationAutoReconnect = NULL;
extern void *ptr_WinStationBroadcastSystemMessage;
void *ptr_WinStationBroadcastSystemMessage = NULL;
extern void *ptr_WinStationCheckAccess;
void *ptr_WinStationCheckAccess = NULL;
extern void *ptr_WinStationCheckLoopBack;
void *ptr_WinStationCheckLoopBack = NULL;
extern void *ptr_WinStationCloseServer;
void *ptr_WinStationCloseServer = NULL;
extern void *ptr_WinStationConnectA;
void *ptr_WinStationConnectA = NULL;
extern void *ptr_WinStationConnectCallback;
void *ptr_WinStationConnectCallback = NULL;
extern void *ptr_WinStationConnectEx;
void *ptr_WinStationConnectEx = NULL;
extern void *ptr_WinStationConnectW;
void *ptr_WinStationConnectW = NULL;
extern void *ptr_WinStationDisconnect;
void *ptr_WinStationDisconnect = NULL;
extern void *ptr_WinStationEnumerateA;
void *ptr_WinStationEnumerateA = NULL;
extern void *ptr_WinStationEnumerateExW;
void *ptr_WinStationEnumerateExW = NULL;
extern void *ptr_WinStationEnumerateLicenses;
void *ptr_WinStationEnumerateLicenses = NULL;
extern void *ptr_WinStationEnumerateProcesses;
void *ptr_WinStationEnumerateProcesses = NULL;
extern void *ptr_WinStationEnumerateW;
void *ptr_WinStationEnumerateW = NULL;
extern void *ptr_WinStationEnumerate_IndexedA;
void *ptr_WinStationEnumerate_IndexedA = NULL;
extern void *ptr_WinStationEnumerate_IndexedW;
void *ptr_WinStationEnumerate_IndexedW = NULL;
extern void *ptr_WinStationFreeConsoleNotification;
void *ptr_WinStationFreeConsoleNotification = NULL;
extern void *ptr_WinStationFreeGAPMemory;
void *ptr_WinStationFreeGAPMemory = NULL;
extern void *ptr_WinStationFreeMemory;
void *ptr_WinStationFreeMemory = NULL;
extern void *ptr_WinStationFreePropertyValue;
void *ptr_WinStationFreePropertyValue = NULL;
extern void *ptr_WinStationFreeUserCertificates;
void *ptr_WinStationFreeUserCertificates = NULL;
extern void *ptr_WinStationFreeUserCredentials;
void *ptr_WinStationFreeUserCredentials = NULL;
extern void *ptr_WinStationGenerateLicense;
void *ptr_WinStationGenerateLicense = NULL;
extern void *ptr_WinStationGetAllProcesses;
void *ptr_WinStationGetAllProcesses = NULL;
extern void *ptr_WinStationGetAllSessionsW;
void *ptr_WinStationGetAllSessionsW = NULL;
extern void *ptr_WinStationGetConnectionProperty;
void *ptr_WinStationGetConnectionProperty = NULL;
extern void *ptr_WinStationGetDeviceId;
void *ptr_WinStationGetDeviceId = NULL;
extern void *ptr_WinStationGetInitialApplication;
void *ptr_WinStationGetInitialApplication = NULL;
extern void *ptr_WinStationGetLanAdapterNameA;
void *ptr_WinStationGetLanAdapterNameA = NULL;
extern void *ptr_WinStationGetLanAdapterNameW;
void *ptr_WinStationGetLanAdapterNameW = NULL;
extern void *ptr_WinStationGetLoggedOnCount;
void *ptr_WinStationGetLoggedOnCount = NULL;
extern void *ptr_WinStationGetMachinePolicy;
void *ptr_WinStationGetMachinePolicy = NULL;
extern void *ptr_WinStationGetProcessSid;
void *ptr_WinStationGetProcessSid = NULL;
extern void *ptr_WinStationGetRestrictedLogonInfo;
void *ptr_WinStationGetRestrictedLogonInfo = NULL;
extern void *ptr_WinStationGetSessionIds;
void *ptr_WinStationGetSessionIds = NULL;
extern void *ptr_WinStationGetTermSrvCountersValue;
void *ptr_WinStationGetTermSrvCountersValue = NULL;
extern void *ptr_WinStationGetUserCertificates;
void *ptr_WinStationGetUserCertificates = NULL;
extern void *ptr_WinStationGetUserCredentials;
void *ptr_WinStationGetUserCredentials = NULL;
extern void *ptr_WinStationGetUserProfile;
void *ptr_WinStationGetUserProfile = NULL;
extern void *ptr_WinStationInstallLicense;
void *ptr_WinStationInstallLicense = NULL;
extern void *ptr_WinStationIsHelpAssistantSession;
void *ptr_WinStationIsHelpAssistantSession = NULL;
extern void *ptr_WinStationIsSessionPermitted;
void *ptr_WinStationIsSessionPermitted = NULL;
extern void *ptr_WinStationIsSessionRemoteable;
void *ptr_WinStationIsSessionRemoteable = NULL;
extern void *ptr_WinStationNameFromLogonIdA;
void *ptr_WinStationNameFromLogonIdA = NULL;
extern void *ptr_WinStationNameFromLogonIdW;
void *ptr_WinStationNameFromLogonIdW = NULL;
extern void *ptr_WinStationNegotiateSession;
void *ptr_WinStationNegotiateSession = NULL;
extern void *ptr_WinStationNtsdDebug;
void *ptr_WinStationNtsdDebug = NULL;
extern void *ptr_WinStationOpenServerA;
void *ptr_WinStationOpenServerA = NULL;
extern void *ptr_WinStationOpenServerExA;
void *ptr_WinStationOpenServerExA = NULL;
extern void *ptr_WinStationOpenServerExW;
void *ptr_WinStationOpenServerExW = NULL;
extern void *ptr_WinStationOpenServerW;
void *ptr_WinStationOpenServerW = NULL;
extern void *ptr_WinStationQueryAllowConcurrentConnections;
void *ptr_WinStationQueryAllowConcurrentConnections = NULL;
extern void *ptr_WinStationQueryEnforcementCore;
void *ptr_WinStationQueryEnforcementCore = NULL;
extern void *ptr_WinStationQueryInformationA;
void *ptr_WinStationQueryInformationA = NULL;
extern void *ptr_WinStationQueryInformationW;
void *ptr_WinStationQueryInformationW = NULL;
extern void *ptr_WinStationQueryLicense;
void *ptr_WinStationQueryLicense = NULL;
extern void *ptr_WinStationQueryLogonCredentialsW;
void *ptr_WinStationQueryLogonCredentialsW = NULL;
extern void *ptr_WinStationQuerySessionVirtualIP;
void *ptr_WinStationQuerySessionVirtualIP = NULL;
extern void *ptr_WinStationQueryUpdateRequired;
void *ptr_WinStationQueryUpdateRequired = NULL;
extern void *ptr_WinStationRedirectErrorMessage;
void *ptr_WinStationRedirectErrorMessage = NULL;
extern void *ptr_WinStationRedirectLogonBeginPainting;
void *ptr_WinStationRedirectLogonBeginPainting = NULL;
extern void *ptr_WinStationRedirectLogonError;
void *ptr_WinStationRedirectLogonError = NULL;
extern void *ptr_WinStationRedirectLogonMessage;
void *ptr_WinStationRedirectLogonMessage = NULL;
extern void *ptr_WinStationRedirectLogonStatus;
void *ptr_WinStationRedirectLogonStatus = NULL;
extern void *ptr_WinStationRegisterConsoleNotification;
void *ptr_WinStationRegisterConsoleNotification = NULL;
extern void *ptr_WinStationRegisterConsoleNotificationEx;
void *ptr_WinStationRegisterConsoleNotificationEx = NULL;
extern void *ptr_WinStationRegisterNotificationEvent;
void *ptr_WinStationRegisterNotificationEvent = NULL;
extern void *ptr_WinStationRemoveLicense;
void *ptr_WinStationRemoveLicense = NULL;
extern void *ptr_WinStationRenameA;
void *ptr_WinStationRenameA = NULL;
extern void *ptr_WinStationRenameW;
void *ptr_WinStationRenameW = NULL;
extern void *ptr_WinStationReportUIResult;
void *ptr_WinStationReportUIResult = NULL;
extern void *ptr_WinStationReset;
void *ptr_WinStationReset = NULL;
extern void *ptr_WinStationRevertFromServicesSession;
void *ptr_WinStationRevertFromServicesSession = NULL;
extern void *ptr_WinStationSendMessageA;
void *ptr_WinStationSendMessageA = NULL;
extern void *ptr_WinStationSendMessageW;
void *ptr_WinStationSendMessageW = NULL;
extern void *ptr_WinStationSendWindowMessage;
void *ptr_WinStationSendWindowMessage = NULL;
extern void *ptr_WinStationServerPing;
void *ptr_WinStationServerPing = NULL;
extern void *ptr_WinStationSetAutologonPassword;
void *ptr_WinStationSetAutologonPassword = NULL;
extern void *ptr_WinStationSetInformationA;
void *ptr_WinStationSetInformationA = NULL;
extern void *ptr_WinStationSetInformationW;
void *ptr_WinStationSetInformationW = NULL;
extern void *ptr_WinStationSetPoolCount;
void *ptr_WinStationSetPoolCount = NULL;
extern void *ptr_WinStationShadow;
void *ptr_WinStationShadow = NULL;
extern void *ptr_WinStationShadowStop;
void *ptr_WinStationShadowStop = NULL;
extern void *ptr_WinStationShutdownSystem;
void *ptr_WinStationShutdownSystem = NULL;
extern void *ptr_WinStationSwitchToServicesSession;
void *ptr_WinStationSwitchToServicesSession = NULL;
extern void *ptr_WinStationSystemShutdownStarted;
void *ptr_WinStationSystemShutdownStarted = NULL;
extern void *ptr_WinStationSystemShutdownWait;
void *ptr_WinStationSystemShutdownWait = NULL;
extern void *ptr_WinStationTerminateProcess;
void *ptr_WinStationTerminateProcess = NULL;
extern void *ptr_WinStationUnRegisterConsoleNotification;
void *ptr_WinStationUnRegisterConsoleNotification = NULL;
extern void *ptr_WinStationUnRegisterNotificationEvent;
void *ptr_WinStationUnRegisterNotificationEvent = NULL;
extern void *ptr_WinStationUserLoginAccessCheck;
void *ptr_WinStationUserLoginAccessCheck = NULL;
extern void *ptr_WinStationVerify;
void *ptr_WinStationVerify = NULL;
extern void *ptr_WinStationVirtualOpen;
void *ptr_WinStationVirtualOpen = NULL;
extern void *ptr_WinStationVirtualOpenEx;
void *ptr_WinStationVirtualOpenEx = NULL;
extern void *ptr_WinStationWaitSystemEvent;
void *ptr_WinStationWaitSystemEvent = NULL;
extern void *ptr__NWLogonQueryAdmin;
void *ptr__NWLogonQueryAdmin = NULL;
extern void *ptr__NWLogonSetAdmin;
void *ptr__NWLogonSetAdmin = NULL;
extern void *ptr__WinStationAnnoyancePopup;
void *ptr__WinStationAnnoyancePopup = NULL;
extern void *ptr__WinStationBeepOpen;
void *ptr__WinStationBeepOpen = NULL;
extern void *ptr__WinStationBreakPoint;
void *ptr__WinStationBreakPoint = NULL;
extern void *ptr__WinStationCallback;
void *ptr__WinStationCallback = NULL;
extern void *ptr__WinStationCheckForApplicationName;
void *ptr__WinStationCheckForApplicationName = NULL;
extern void *ptr__WinStationFUSCanRemoteUserDisconnect;
void *ptr__WinStationFUSCanRemoteUserDisconnect = NULL;
extern void *ptr__WinStationGetApplicationInfo;
void *ptr__WinStationGetApplicationInfo = NULL;
extern void *ptr__WinStationNotifyDisconnectPipe;
void *ptr__WinStationNotifyDisconnectPipe = NULL;
extern void *ptr__WinStationNotifyLogoff;
void *ptr__WinStationNotifyLogoff = NULL;
extern void *ptr__WinStationNotifyLogon;
void *ptr__WinStationNotifyLogon = NULL;
extern void *ptr__WinStationNotifyNewSession;
void *ptr__WinStationNotifyNewSession = NULL;
extern void *ptr__WinStationOpenSessionDirectory;
void *ptr__WinStationOpenSessionDirectory = NULL;
extern void *ptr__WinStationReInitializeSecurity;
void *ptr__WinStationReInitializeSecurity = NULL;
extern void *ptr__WinStationReadRegistry;
void *ptr__WinStationReadRegistry = NULL;
extern void *ptr__WinStationSessionInitialized;
void *ptr__WinStationSessionInitialized = NULL;
extern void *ptr__WinStationShadowTarget;
void *ptr__WinStationShadowTarget = NULL;
extern void *ptr__WinStationShadowTarget2;
void *ptr__WinStationShadowTarget2 = NULL;
extern void *ptr__WinStationShadowTargetSetup;
void *ptr__WinStationShadowTargetSetup = NULL;
extern void *ptr__WinStationUpdateClientCachedCredentials;
void *ptr__WinStationUpdateClientCachedCredentials = NULL;
extern void *ptr__WinStationUpdateSettings;
void *ptr__WinStationUpdateSettings = NULL;
extern void *ptr__WinStationUpdateUserConfig;
void *ptr__WinStationUpdateUserConfig = NULL;
extern void *ptr__WinStationWaitForConnect;
void *ptr__WinStationWaitForConnect = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\winsta.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_LogonIdFromWinStationNameA = (__vartype(ptr_LogonIdFromWinStationNameA))GetProcAddress(hModule, "LogonIdFromWinStationNameA");
   ptr_LogonIdFromWinStationNameW = (__vartype(ptr_LogonIdFromWinStationNameW))GetProcAddress(hModule, "LogonIdFromWinStationNameW");
   ptr_RemoteAssistancePrepareSystemRestore = (__vartype(ptr_RemoteAssistancePrepareSystemRestore))GetProcAddress(hModule, "RemoteAssistancePrepareSystemRestore");
   ptr_ServerGetInternetConnectorStatus = (__vartype(ptr_ServerGetInternetConnectorStatus))GetProcAddress(hModule, "ServerGetInternetConnectorStatus");
   ptr_ServerLicensingClose = (__vartype(ptr_ServerLicensingClose))GetProcAddress(hModule, "ServerLicensingClose");
   ptr_ServerLicensingDeactivateCurrentPolicy = (__vartype(ptr_ServerLicensingDeactivateCurrentPolicy))GetProcAddress(hModule, "ServerLicensingDeactivateCurrentPolicy");
   ptr_ServerLicensingFreePolicyInformation = (__vartype(ptr_ServerLicensingFreePolicyInformation))GetProcAddress(hModule, "ServerLicensingFreePolicyInformation");
   ptr_ServerLicensingGetAvailablePolicyIds = (__vartype(ptr_ServerLicensingGetAvailablePolicyIds))GetProcAddress(hModule, "ServerLicensingGetAvailablePolicyIds");
   ptr_ServerLicensingGetPolicy = (__vartype(ptr_ServerLicensingGetPolicy))GetProcAddress(hModule, "ServerLicensingGetPolicy");
   ptr_ServerLicensingGetPolicyInformationA = (__vartype(ptr_ServerLicensingGetPolicyInformationA))GetProcAddress(hModule, "ServerLicensingGetPolicyInformationA");
   ptr_ServerLicensingGetPolicyInformationW = (__vartype(ptr_ServerLicensingGetPolicyInformationW))GetProcAddress(hModule, "ServerLicensingGetPolicyInformationW");
   ptr_ServerLicensingLoadPolicy = (__vartype(ptr_ServerLicensingLoadPolicy))GetProcAddress(hModule, "ServerLicensingLoadPolicy");
   ptr_ServerLicensingOpenA = (__vartype(ptr_ServerLicensingOpenA))GetProcAddress(hModule, "ServerLicensingOpenA");
   ptr_ServerLicensingOpenW = (__vartype(ptr_ServerLicensingOpenW))GetProcAddress(hModule, "ServerLicensingOpenW");
   ptr_ServerLicensingSetPolicy = (__vartype(ptr_ServerLicensingSetPolicy))GetProcAddress(hModule, "ServerLicensingSetPolicy");
   ptr_ServerLicensingUnloadPolicy = (__vartype(ptr_ServerLicensingUnloadPolicy))GetProcAddress(hModule, "ServerLicensingUnloadPolicy");
   ptr_ServerQueryInetConnectorInformationA = (__vartype(ptr_ServerQueryInetConnectorInformationA))GetProcAddress(hModule, "ServerQueryInetConnectorInformationA");
   ptr_ServerQueryInetConnectorInformationW = (__vartype(ptr_ServerQueryInetConnectorInformationW))GetProcAddress(hModule, "ServerQueryInetConnectorInformationW");
   ptr_ServerSetInternetConnectorStatus = (__vartype(ptr_ServerSetInternetConnectorStatus))GetProcAddress(hModule, "ServerSetInternetConnectorStatus");
   ptr_WinStationActivateLicense = (__vartype(ptr_WinStationActivateLicense))GetProcAddress(hModule, "WinStationActivateLicense");
   ptr_WinStationAutoReconnect = (__vartype(ptr_WinStationAutoReconnect))GetProcAddress(hModule, "WinStationAutoReconnect");
   ptr_WinStationBroadcastSystemMessage = (__vartype(ptr_WinStationBroadcastSystemMessage))GetProcAddress(hModule, "WinStationBroadcastSystemMessage");
   ptr_WinStationCheckAccess = (__vartype(ptr_WinStationCheckAccess))GetProcAddress(hModule, "WinStationCheckAccess");
   ptr_WinStationCheckLoopBack = (__vartype(ptr_WinStationCheckLoopBack))GetProcAddress(hModule, "WinStationCheckLoopBack");
   ptr_WinStationCloseServer = (__vartype(ptr_WinStationCloseServer))GetProcAddress(hModule, "WinStationCloseServer");
   ptr_WinStationConnectA = (__vartype(ptr_WinStationConnectA))GetProcAddress(hModule, "WinStationConnectA");
   ptr_WinStationConnectCallback = (__vartype(ptr_WinStationConnectCallback))GetProcAddress(hModule, "WinStationConnectCallback");
   ptr_WinStationConnectEx = (__vartype(ptr_WinStationConnectEx))GetProcAddress(hModule, "WinStationConnectEx");
   ptr_WinStationConnectW = (__vartype(ptr_WinStationConnectW))GetProcAddress(hModule, "WinStationConnectW");
   ptr_WinStationDisconnect = (__vartype(ptr_WinStationDisconnect))GetProcAddress(hModule, "WinStationDisconnect");
   ptr_WinStationEnumerateA = (__vartype(ptr_WinStationEnumerateA))GetProcAddress(hModule, "WinStationEnumerateA");
   ptr_WinStationEnumerateExW = (__vartype(ptr_WinStationEnumerateExW))GetProcAddress(hModule, "WinStationEnumerateExW");
   ptr_WinStationEnumerateLicenses = (__vartype(ptr_WinStationEnumerateLicenses))GetProcAddress(hModule, "WinStationEnumerateLicenses");
   ptr_WinStationEnumerateProcesses = (__vartype(ptr_WinStationEnumerateProcesses))GetProcAddress(hModule, "WinStationEnumerateProcesses");
   ptr_WinStationEnumerateW = (__vartype(ptr_WinStationEnumerateW))GetProcAddress(hModule, "WinStationEnumerateW");
   ptr_WinStationEnumerate_IndexedA = (__vartype(ptr_WinStationEnumerate_IndexedA))GetProcAddress(hModule, "WinStationEnumerate_IndexedA");
   ptr_WinStationEnumerate_IndexedW = (__vartype(ptr_WinStationEnumerate_IndexedW))GetProcAddress(hModule, "WinStationEnumerate_IndexedW");
   ptr_WinStationFreeConsoleNotification = (__vartype(ptr_WinStationFreeConsoleNotification))GetProcAddress(hModule, "WinStationFreeConsoleNotification");
   ptr_WinStationFreeGAPMemory = (__vartype(ptr_WinStationFreeGAPMemory))GetProcAddress(hModule, "WinStationFreeGAPMemory");
   ptr_WinStationFreeMemory = (__vartype(ptr_WinStationFreeMemory))GetProcAddress(hModule, "WinStationFreeMemory");
   ptr_WinStationFreePropertyValue = (__vartype(ptr_WinStationFreePropertyValue))GetProcAddress(hModule, "WinStationFreePropertyValue");
   ptr_WinStationFreeUserCertificates = (__vartype(ptr_WinStationFreeUserCertificates))GetProcAddress(hModule, "WinStationFreeUserCertificates");
   ptr_WinStationFreeUserCredentials = (__vartype(ptr_WinStationFreeUserCredentials))GetProcAddress(hModule, "WinStationFreeUserCredentials");
   ptr_WinStationGenerateLicense = (__vartype(ptr_WinStationGenerateLicense))GetProcAddress(hModule, "WinStationGenerateLicense");
   ptr_WinStationGetAllProcesses = (__vartype(ptr_WinStationGetAllProcesses))GetProcAddress(hModule, "WinStationGetAllProcesses");
   ptr_WinStationGetAllSessionsW = (__vartype(ptr_WinStationGetAllSessionsW))GetProcAddress(hModule, "WinStationGetAllSessionsW");
   ptr_WinStationGetConnectionProperty = (__vartype(ptr_WinStationGetConnectionProperty))GetProcAddress(hModule, "WinStationGetConnectionProperty");
   ptr_WinStationGetDeviceId = (__vartype(ptr_WinStationGetDeviceId))GetProcAddress(hModule, "WinStationGetDeviceId");
   ptr_WinStationGetInitialApplication = (__vartype(ptr_WinStationGetInitialApplication))GetProcAddress(hModule, "WinStationGetInitialApplication");
   ptr_WinStationGetLanAdapterNameA = (__vartype(ptr_WinStationGetLanAdapterNameA))GetProcAddress(hModule, "WinStationGetLanAdapterNameA");
   ptr_WinStationGetLanAdapterNameW = (__vartype(ptr_WinStationGetLanAdapterNameW))GetProcAddress(hModule, "WinStationGetLanAdapterNameW");
   ptr_WinStationGetLoggedOnCount = (__vartype(ptr_WinStationGetLoggedOnCount))GetProcAddress(hModule, "WinStationGetLoggedOnCount");
   ptr_WinStationGetMachinePolicy = (__vartype(ptr_WinStationGetMachinePolicy))GetProcAddress(hModule, "WinStationGetMachinePolicy");
   ptr_WinStationGetProcessSid = (__vartype(ptr_WinStationGetProcessSid))GetProcAddress(hModule, "WinStationGetProcessSid");
   ptr_WinStationGetRestrictedLogonInfo = (__vartype(ptr_WinStationGetRestrictedLogonInfo))GetProcAddress(hModule, "WinStationGetRestrictedLogonInfo");
   ptr_WinStationGetSessionIds = (__vartype(ptr_WinStationGetSessionIds))GetProcAddress(hModule, "WinStationGetSessionIds");
   ptr_WinStationGetTermSrvCountersValue = (__vartype(ptr_WinStationGetTermSrvCountersValue))GetProcAddress(hModule, "WinStationGetTermSrvCountersValue");
   ptr_WinStationGetUserCertificates = (__vartype(ptr_WinStationGetUserCertificates))GetProcAddress(hModule, "WinStationGetUserCertificates");
   ptr_WinStationGetUserCredentials = (__vartype(ptr_WinStationGetUserCredentials))GetProcAddress(hModule, "WinStationGetUserCredentials");
   ptr_WinStationGetUserProfile = (__vartype(ptr_WinStationGetUserProfile))GetProcAddress(hModule, "WinStationGetUserProfile");
   ptr_WinStationInstallLicense = (__vartype(ptr_WinStationInstallLicense))GetProcAddress(hModule, "WinStationInstallLicense");
   ptr_WinStationIsHelpAssistantSession = (__vartype(ptr_WinStationIsHelpAssistantSession))GetProcAddress(hModule, "WinStationIsHelpAssistantSession");
   ptr_WinStationIsSessionPermitted = (__vartype(ptr_WinStationIsSessionPermitted))GetProcAddress(hModule, "WinStationIsSessionPermitted");
   ptr_WinStationIsSessionRemoteable = (__vartype(ptr_WinStationIsSessionRemoteable))GetProcAddress(hModule, "WinStationIsSessionRemoteable");
   ptr_WinStationNameFromLogonIdA = (__vartype(ptr_WinStationNameFromLogonIdA))GetProcAddress(hModule, "WinStationNameFromLogonIdA");
   ptr_WinStationNameFromLogonIdW = (__vartype(ptr_WinStationNameFromLogonIdW))GetProcAddress(hModule, "WinStationNameFromLogonIdW");
   ptr_WinStationNegotiateSession = (__vartype(ptr_WinStationNegotiateSession))GetProcAddress(hModule, "WinStationNegotiateSession");
   ptr_WinStationNtsdDebug = (__vartype(ptr_WinStationNtsdDebug))GetProcAddress(hModule, "WinStationNtsdDebug");
   ptr_WinStationOpenServerA = (__vartype(ptr_WinStationOpenServerA))GetProcAddress(hModule, "WinStationOpenServerA");
   ptr_WinStationOpenServerExA = (__vartype(ptr_WinStationOpenServerExA))GetProcAddress(hModule, "WinStationOpenServerExA");
   ptr_WinStationOpenServerExW = (__vartype(ptr_WinStationOpenServerExW))GetProcAddress(hModule, "WinStationOpenServerExW");
   ptr_WinStationOpenServerW = (__vartype(ptr_WinStationOpenServerW))GetProcAddress(hModule, "WinStationOpenServerW");
   ptr_WinStationQueryAllowConcurrentConnections = (__vartype(ptr_WinStationQueryAllowConcurrentConnections))GetProcAddress(hModule, "WinStationQueryAllowConcurrentConnections");
   ptr_WinStationQueryEnforcementCore = (__vartype(ptr_WinStationQueryEnforcementCore))GetProcAddress(hModule, "WinStationQueryEnforcementCore");
   ptr_WinStationQueryInformationA = (__vartype(ptr_WinStationQueryInformationA))GetProcAddress(hModule, "WinStationQueryInformationA");
   ptr_WinStationQueryInformationW = (__vartype(ptr_WinStationQueryInformationW))GetProcAddress(hModule, "WinStationQueryInformationW");
   ptr_WinStationQueryLicense = (__vartype(ptr_WinStationQueryLicense))GetProcAddress(hModule, "WinStationQueryLicense");
   ptr_WinStationQueryLogonCredentialsW = (__vartype(ptr_WinStationQueryLogonCredentialsW))GetProcAddress(hModule, "WinStationQueryLogonCredentialsW");
   ptr_WinStationQuerySessionVirtualIP = (__vartype(ptr_WinStationQuerySessionVirtualIP))GetProcAddress(hModule, "WinStationQuerySessionVirtualIP");
   ptr_WinStationQueryUpdateRequired = (__vartype(ptr_WinStationQueryUpdateRequired))GetProcAddress(hModule, "WinStationQueryUpdateRequired");
   ptr_WinStationRedirectErrorMessage = (__vartype(ptr_WinStationRedirectErrorMessage))GetProcAddress(hModule, "WinStationRedirectErrorMessage");
   ptr_WinStationRedirectLogonBeginPainting = (__vartype(ptr_WinStationRedirectLogonBeginPainting))GetProcAddress(hModule, "WinStationRedirectLogonBeginPainting");
   ptr_WinStationRedirectLogonError = (__vartype(ptr_WinStationRedirectLogonError))GetProcAddress(hModule, "WinStationRedirectLogonError");
   ptr_WinStationRedirectLogonMessage = (__vartype(ptr_WinStationRedirectLogonMessage))GetProcAddress(hModule, "WinStationRedirectLogonMessage");
   ptr_WinStationRedirectLogonStatus = (__vartype(ptr_WinStationRedirectLogonStatus))GetProcAddress(hModule, "WinStationRedirectLogonStatus");
   ptr_WinStationRegisterConsoleNotification = (__vartype(ptr_WinStationRegisterConsoleNotification))GetProcAddress(hModule, "WinStationRegisterConsoleNotification");
   ptr_WinStationRegisterConsoleNotificationEx = (__vartype(ptr_WinStationRegisterConsoleNotificationEx))GetProcAddress(hModule, "WinStationRegisterConsoleNotificationEx");
   ptr_WinStationRegisterNotificationEvent = (__vartype(ptr_WinStationRegisterNotificationEvent))GetProcAddress(hModule, "WinStationRegisterNotificationEvent");
   ptr_WinStationRemoveLicense = (__vartype(ptr_WinStationRemoveLicense))GetProcAddress(hModule, "WinStationRemoveLicense");
   ptr_WinStationRenameA = (__vartype(ptr_WinStationRenameA))GetProcAddress(hModule, "WinStationRenameA");
   ptr_WinStationRenameW = (__vartype(ptr_WinStationRenameW))GetProcAddress(hModule, "WinStationRenameW");
   ptr_WinStationReportUIResult = (__vartype(ptr_WinStationReportUIResult))GetProcAddress(hModule, "WinStationReportUIResult");
   ptr_WinStationReset = (__vartype(ptr_WinStationReset))GetProcAddress(hModule, "WinStationReset");
   ptr_WinStationRevertFromServicesSession = (__vartype(ptr_WinStationRevertFromServicesSession))GetProcAddress(hModule, "WinStationRevertFromServicesSession");
   ptr_WinStationSendMessageA = (__vartype(ptr_WinStationSendMessageA))GetProcAddress(hModule, "WinStationSendMessageA");
   ptr_WinStationSendMessageW = (__vartype(ptr_WinStationSendMessageW))GetProcAddress(hModule, "WinStationSendMessageW");
   ptr_WinStationSendWindowMessage = (__vartype(ptr_WinStationSendWindowMessage))GetProcAddress(hModule, "WinStationSendWindowMessage");
   ptr_WinStationServerPing = (__vartype(ptr_WinStationServerPing))GetProcAddress(hModule, "WinStationServerPing");
   ptr_WinStationSetAutologonPassword = (__vartype(ptr_WinStationSetAutologonPassword))GetProcAddress(hModule, "WinStationSetAutologonPassword");
   ptr_WinStationSetInformationA = (__vartype(ptr_WinStationSetInformationA))GetProcAddress(hModule, "WinStationSetInformationA");
   ptr_WinStationSetInformationW = (__vartype(ptr_WinStationSetInformationW))GetProcAddress(hModule, "WinStationSetInformationW");
   ptr_WinStationSetPoolCount = (__vartype(ptr_WinStationSetPoolCount))GetProcAddress(hModule, "WinStationSetPoolCount");
   ptr_WinStationShadow = (__vartype(ptr_WinStationShadow))GetProcAddress(hModule, "WinStationShadow");
   ptr_WinStationShadowStop = (__vartype(ptr_WinStationShadowStop))GetProcAddress(hModule, "WinStationShadowStop");
   ptr_WinStationShutdownSystem = (__vartype(ptr_WinStationShutdownSystem))GetProcAddress(hModule, "WinStationShutdownSystem");
   ptr_WinStationSwitchToServicesSession = (__vartype(ptr_WinStationSwitchToServicesSession))GetProcAddress(hModule, "WinStationSwitchToServicesSession");
   ptr_WinStationSystemShutdownStarted = (__vartype(ptr_WinStationSystemShutdownStarted))GetProcAddress(hModule, "WinStationSystemShutdownStarted");
   ptr_WinStationSystemShutdownWait = (__vartype(ptr_WinStationSystemShutdownWait))GetProcAddress(hModule, "WinStationSystemShutdownWait");
   ptr_WinStationTerminateProcess = (__vartype(ptr_WinStationTerminateProcess))GetProcAddress(hModule, "WinStationTerminateProcess");
   ptr_WinStationUnRegisterConsoleNotification = (__vartype(ptr_WinStationUnRegisterConsoleNotification))GetProcAddress(hModule, "WinStationUnRegisterConsoleNotification");
   ptr_WinStationUnRegisterNotificationEvent = (__vartype(ptr_WinStationUnRegisterNotificationEvent))GetProcAddress(hModule, "WinStationUnRegisterNotificationEvent");
   ptr_WinStationUserLoginAccessCheck = (__vartype(ptr_WinStationUserLoginAccessCheck))GetProcAddress(hModule, "WinStationUserLoginAccessCheck");
   ptr_WinStationVerify = (__vartype(ptr_WinStationVerify))GetProcAddress(hModule, "WinStationVerify");
   ptr_WinStationVirtualOpen = (__vartype(ptr_WinStationVirtualOpen))GetProcAddress(hModule, "WinStationVirtualOpen");
   ptr_WinStationVirtualOpenEx = (__vartype(ptr_WinStationVirtualOpenEx))GetProcAddress(hModule, "WinStationVirtualOpenEx");
   ptr_WinStationWaitSystemEvent = (__vartype(ptr_WinStationWaitSystemEvent))GetProcAddress(hModule, "WinStationWaitSystemEvent");
   ptr__NWLogonQueryAdmin = (__vartype(ptr__NWLogonQueryAdmin))GetProcAddress(hModule, "_NWLogonQueryAdmin");
   ptr__NWLogonSetAdmin = (__vartype(ptr__NWLogonSetAdmin))GetProcAddress(hModule, "_NWLogonSetAdmin");
   ptr__WinStationAnnoyancePopup = (__vartype(ptr__WinStationAnnoyancePopup))GetProcAddress(hModule, "_WinStationAnnoyancePopup");
   ptr__WinStationBeepOpen = (__vartype(ptr__WinStationBeepOpen))GetProcAddress(hModule, "_WinStationBeepOpen");
   ptr__WinStationBreakPoint = (__vartype(ptr__WinStationBreakPoint))GetProcAddress(hModule, "_WinStationBreakPoint");
   ptr__WinStationCallback = (__vartype(ptr__WinStationCallback))GetProcAddress(hModule, "_WinStationCallback");
   ptr__WinStationCheckForApplicationName = (__vartype(ptr__WinStationCheckForApplicationName))GetProcAddress(hModule, "_WinStationCheckForApplicationName");
   ptr__WinStationFUSCanRemoteUserDisconnect = (__vartype(ptr__WinStationFUSCanRemoteUserDisconnect))GetProcAddress(hModule, "_WinStationFUSCanRemoteUserDisconnect");
   ptr__WinStationGetApplicationInfo = (__vartype(ptr__WinStationGetApplicationInfo))GetProcAddress(hModule, "_WinStationGetApplicationInfo");
   ptr__WinStationNotifyDisconnectPipe = (__vartype(ptr__WinStationNotifyDisconnectPipe))GetProcAddress(hModule, "_WinStationNotifyDisconnectPipe");
   ptr__WinStationNotifyLogoff = (__vartype(ptr__WinStationNotifyLogoff))GetProcAddress(hModule, "_WinStationNotifyLogoff");
   ptr__WinStationNotifyLogon = (__vartype(ptr__WinStationNotifyLogon))GetProcAddress(hModule, "_WinStationNotifyLogon");
   ptr__WinStationNotifyNewSession = (__vartype(ptr__WinStationNotifyNewSession))GetProcAddress(hModule, "_WinStationNotifyNewSession");
   ptr__WinStationOpenSessionDirectory = (__vartype(ptr__WinStationOpenSessionDirectory))GetProcAddress(hModule, "_WinStationOpenSessionDirectory");
   ptr__WinStationReInitializeSecurity = (__vartype(ptr__WinStationReInitializeSecurity))GetProcAddress(hModule, "_WinStationReInitializeSecurity");
   ptr__WinStationReadRegistry = (__vartype(ptr__WinStationReadRegistry))GetProcAddress(hModule, "_WinStationReadRegistry");
   ptr__WinStationSessionInitialized = (__vartype(ptr__WinStationSessionInitialized))GetProcAddress(hModule, "_WinStationSessionInitialized");
   ptr__WinStationShadowTarget = (__vartype(ptr__WinStationShadowTarget))GetProcAddress(hModule, "_WinStationShadowTarget");
   ptr__WinStationShadowTarget2 = (__vartype(ptr__WinStationShadowTarget2))GetProcAddress(hModule, "_WinStationShadowTarget2");
   ptr__WinStationShadowTargetSetup = (__vartype(ptr__WinStationShadowTargetSetup))GetProcAddress(hModule, "_WinStationShadowTargetSetup");
   ptr__WinStationUpdateClientCachedCredentials = (__vartype(ptr__WinStationUpdateClientCachedCredentials))GetProcAddress(hModule, "_WinStationUpdateClientCachedCredentials");
   ptr__WinStationUpdateSettings = (__vartype(ptr__WinStationUpdateSettings))GetProcAddress(hModule, "_WinStationUpdateSettings");
   ptr__WinStationUpdateUserConfig = (__vartype(ptr__WinStationUpdateUserConfig))GetProcAddress(hModule, "_WinStationUpdateUserConfig");
   ptr__WinStationWaitForConnect = (__vartype(ptr__WinStationWaitForConnect))GetProcAddress(hModule, "_WinStationWaitForConnect");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

