#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_DebugExtensionInitialize;
void *ptr_DebugExtensionInitialize = NULL;
extern void *ptr_DebugExtensionNotify;
void *ptr_DebugExtensionNotify = NULL;
extern void *ptr_DebugExtensionUninitialize;
void *ptr_DebugExtensionUninitialize = NULL;
extern void *ptr_JetAddColumn;
void *ptr_JetAddColumn = NULL;
extern void *ptr_JetAddColumnA;
void *ptr_JetAddColumnA = NULL;
extern void *ptr_JetAddColumnW;
void *ptr_JetAddColumnW = NULL;
extern void *ptr_JetAttachDatabase;
void *ptr_JetAttachDatabase = NULL;
extern void *ptr_JetAttachDatabase2;
void *ptr_JetAttachDatabase2 = NULL;
extern void *ptr_JetAttachDatabase2A;
void *ptr_JetAttachDatabase2A = NULL;
extern void *ptr_JetAttachDatabase2W;
void *ptr_JetAttachDatabase2W = NULL;
extern void *ptr_JetAttachDatabaseA;
void *ptr_JetAttachDatabaseA = NULL;
extern void *ptr_JetAttachDatabaseW;
void *ptr_JetAttachDatabaseW = NULL;
extern void *ptr_JetAttachDatabaseWithStreaming;
void *ptr_JetAttachDatabaseWithStreaming = NULL;
extern void *ptr_JetAttachDatabaseWithStreamingA;
void *ptr_JetAttachDatabaseWithStreamingA = NULL;
extern void *ptr_JetAttachDatabaseWithStreamingW;
void *ptr_JetAttachDatabaseWithStreamingW = NULL;
extern void *ptr_JetBackup;
void *ptr_JetBackup = NULL;
extern void *ptr_JetBackupA;
void *ptr_JetBackupA = NULL;
extern void *ptr_JetBackupInstance;
void *ptr_JetBackupInstance = NULL;
extern void *ptr_JetBackupInstanceA;
void *ptr_JetBackupInstanceA = NULL;
extern void *ptr_JetBackupInstanceW;
void *ptr_JetBackupInstanceW = NULL;
extern void *ptr_JetBackupW;
void *ptr_JetBackupW = NULL;
extern void *ptr_JetBeginDatabaseIncrementalReseed;
void *ptr_JetBeginDatabaseIncrementalReseed = NULL;
extern void *ptr_JetBeginDatabaseIncrementalReseedA;
void *ptr_JetBeginDatabaseIncrementalReseedA = NULL;
extern void *ptr_JetBeginDatabaseIncrementalReseedW;
void *ptr_JetBeginDatabaseIncrementalReseedW = NULL;
extern void *ptr_JetBeginExternalBackup;
void *ptr_JetBeginExternalBackup = NULL;
extern void *ptr_JetBeginExternalBackupInstance;
void *ptr_JetBeginExternalBackupInstance = NULL;
extern void *ptr_JetBeginSession;
void *ptr_JetBeginSession = NULL;
extern void *ptr_JetBeginSessionA;
void *ptr_JetBeginSessionA = NULL;
extern void *ptr_JetBeginSessionW;
void *ptr_JetBeginSessionW = NULL;
extern void *ptr_JetBeginSurrogateBackup;
void *ptr_JetBeginSurrogateBackup = NULL;
extern void *ptr_JetBeginTransaction;
void *ptr_JetBeginTransaction = NULL;
extern void *ptr_JetBeginTransaction2;
void *ptr_JetBeginTransaction2 = NULL;
extern void *ptr_JetCloseDatabase;
void *ptr_JetCloseDatabase = NULL;
extern void *ptr_JetCloseFile;
void *ptr_JetCloseFile = NULL;
extern void *ptr_JetCloseFileInstance;
void *ptr_JetCloseFileInstance = NULL;
extern void *ptr_JetCloseTable;
void *ptr_JetCloseTable = NULL;
extern void *ptr_JetCommitTransaction;
void *ptr_JetCommitTransaction = NULL;
extern void *ptr_JetCompact;
void *ptr_JetCompact = NULL;
extern void *ptr_JetCompactA;
void *ptr_JetCompactA = NULL;
extern void *ptr_JetCompactW;
void *ptr_JetCompactW = NULL;
extern void *ptr_JetComputeStats;
void *ptr_JetComputeStats = NULL;
extern void *ptr_JetConfigureProcessForCrashDump;
void *ptr_JetConfigureProcessForCrashDump = NULL;
extern void *ptr_JetConvertDDL;
void *ptr_JetConvertDDL = NULL;
extern void *ptr_JetConvertDDLA;
void *ptr_JetConvertDDLA = NULL;
extern void *ptr_JetConvertDDLW;
void *ptr_JetConvertDDLW = NULL;
extern void *ptr_JetCreateDatabase;
void *ptr_JetCreateDatabase = NULL;
extern void *ptr_JetCreateDatabase2;
void *ptr_JetCreateDatabase2 = NULL;
extern void *ptr_JetCreateDatabase2A;
void *ptr_JetCreateDatabase2A = NULL;
extern void *ptr_JetCreateDatabase2W;
void *ptr_JetCreateDatabase2W = NULL;
extern void *ptr_JetCreateDatabaseA;
void *ptr_JetCreateDatabaseA = NULL;
extern void *ptr_JetCreateDatabaseW;
void *ptr_JetCreateDatabaseW = NULL;
extern void *ptr_JetCreateDatabaseWithStreaming;
void *ptr_JetCreateDatabaseWithStreaming = NULL;
extern void *ptr_JetCreateDatabaseWithStreamingA;
void *ptr_JetCreateDatabaseWithStreamingA = NULL;
extern void *ptr_JetCreateDatabaseWithStreamingW;
void *ptr_JetCreateDatabaseWithStreamingW = NULL;
extern void *ptr_JetCreateIndex;
void *ptr_JetCreateIndex = NULL;
extern void *ptr_JetCreateIndex2;
void *ptr_JetCreateIndex2 = NULL;
extern void *ptr_JetCreateIndex2A;
void *ptr_JetCreateIndex2A = NULL;
extern void *ptr_JetCreateIndex2W;
void *ptr_JetCreateIndex2W = NULL;
extern void *ptr_JetCreateIndex3A;
void *ptr_JetCreateIndex3A = NULL;
extern void *ptr_JetCreateIndex3W;
void *ptr_JetCreateIndex3W = NULL;
extern void *ptr_JetCreateIndexA;
void *ptr_JetCreateIndexA = NULL;
extern void *ptr_JetCreateIndexW;
void *ptr_JetCreateIndexW = NULL;
extern void *ptr_JetCreateInstance;
void *ptr_JetCreateInstance = NULL;
extern void *ptr_JetCreateInstance2;
void *ptr_JetCreateInstance2 = NULL;
extern void *ptr_JetCreateInstance2A;
void *ptr_JetCreateInstance2A = NULL;
extern void *ptr_JetCreateInstance2W;
void *ptr_JetCreateInstance2W = NULL;
extern void *ptr_JetCreateInstanceA;
void *ptr_JetCreateInstanceA = NULL;
extern void *ptr_JetCreateInstanceW;
void *ptr_JetCreateInstanceW = NULL;
extern void *ptr_JetCreateTable;
void *ptr_JetCreateTable = NULL;
extern void *ptr_JetCreateTableA;
void *ptr_JetCreateTableA = NULL;
extern void *ptr_JetCreateTableColumnIndex;
void *ptr_JetCreateTableColumnIndex = NULL;
extern void *ptr_JetCreateTableColumnIndex2;
void *ptr_JetCreateTableColumnIndex2 = NULL;
extern void *ptr_JetCreateTableColumnIndex2A;
void *ptr_JetCreateTableColumnIndex2A = NULL;
extern void *ptr_JetCreateTableColumnIndex2W;
void *ptr_JetCreateTableColumnIndex2W = NULL;
extern void *ptr_JetCreateTableColumnIndex3A;
void *ptr_JetCreateTableColumnIndex3A = NULL;
extern void *ptr_JetCreateTableColumnIndex3W;
void *ptr_JetCreateTableColumnIndex3W = NULL;
extern void *ptr_JetCreateTableColumnIndexA;
void *ptr_JetCreateTableColumnIndexA = NULL;
extern void *ptr_JetCreateTableColumnIndexW;
void *ptr_JetCreateTableColumnIndexW = NULL;
extern void *ptr_JetCreateTableW;
void *ptr_JetCreateTableW = NULL;
extern void *ptr_JetDBUtilities;
void *ptr_JetDBUtilities = NULL;
extern void *ptr_JetDBUtilitiesA;
void *ptr_JetDBUtilitiesA = NULL;
extern void *ptr_JetDBUtilitiesW;
void *ptr_JetDBUtilitiesW = NULL;
extern void *ptr_JetDatabaseScan;
void *ptr_JetDatabaseScan = NULL;
extern void *ptr_JetDefragment;
void *ptr_JetDefragment = NULL;
extern void *ptr_JetDefragment2;
void *ptr_JetDefragment2 = NULL;
extern void *ptr_JetDefragment2A;
void *ptr_JetDefragment2A = NULL;
extern void *ptr_JetDefragment2W;
void *ptr_JetDefragment2W = NULL;
extern void *ptr_JetDefragment3;
void *ptr_JetDefragment3 = NULL;
extern void *ptr_JetDefragment3A;
void *ptr_JetDefragment3A = NULL;
extern void *ptr_JetDefragment3W;
void *ptr_JetDefragment3W = NULL;
extern void *ptr_JetDefragmentA;
void *ptr_JetDefragmentA = NULL;
extern void *ptr_JetDefragmentW;
void *ptr_JetDefragmentW = NULL;
extern void *ptr_JetDelete;
void *ptr_JetDelete = NULL;
extern void *ptr_JetDeleteColumn;
void *ptr_JetDeleteColumn = NULL;
extern void *ptr_JetDeleteColumn2;
void *ptr_JetDeleteColumn2 = NULL;
extern void *ptr_JetDeleteColumn2A;
void *ptr_JetDeleteColumn2A = NULL;
extern void *ptr_JetDeleteColumn2W;
void *ptr_JetDeleteColumn2W = NULL;
extern void *ptr_JetDeleteColumnA;
void *ptr_JetDeleteColumnA = NULL;
extern void *ptr_JetDeleteColumnW;
void *ptr_JetDeleteColumnW = NULL;
extern void *ptr_JetDeleteIndex;
void *ptr_JetDeleteIndex = NULL;
extern void *ptr_JetDeleteIndexA;
void *ptr_JetDeleteIndexA = NULL;
extern void *ptr_JetDeleteIndexW;
void *ptr_JetDeleteIndexW = NULL;
extern void *ptr_JetDeleteTable;
void *ptr_JetDeleteTable = NULL;
extern void *ptr_JetDeleteTableA;
void *ptr_JetDeleteTableA = NULL;
extern void *ptr_JetDeleteTableW;
void *ptr_JetDeleteTableW = NULL;
extern void *ptr_JetDetachDatabase;
void *ptr_JetDetachDatabase = NULL;
extern void *ptr_JetDetachDatabase2;
void *ptr_JetDetachDatabase2 = NULL;
extern void *ptr_JetDetachDatabase2A;
void *ptr_JetDetachDatabase2A = NULL;
extern void *ptr_JetDetachDatabase2W;
void *ptr_JetDetachDatabase2W = NULL;
extern void *ptr_JetDetachDatabaseA;
void *ptr_JetDetachDatabaseA = NULL;
extern void *ptr_JetDetachDatabaseW;
void *ptr_JetDetachDatabaseW = NULL;
extern void *ptr_JetDupCursor;
void *ptr_JetDupCursor = NULL;
extern void *ptr_JetDupSession;
void *ptr_JetDupSession = NULL;
extern void *ptr_JetEnableFaultInjection;
void *ptr_JetEnableFaultInjection = NULL;
extern void *ptr_JetEnableMultiInstance;
void *ptr_JetEnableMultiInstance = NULL;
extern void *ptr_JetEnableMultiInstanceA;
void *ptr_JetEnableMultiInstanceA = NULL;
extern void *ptr_JetEnableMultiInstanceW;
void *ptr_JetEnableMultiInstanceW = NULL;
extern void *ptr_JetEndDatabaseIncrementalReseed;
void *ptr_JetEndDatabaseIncrementalReseed = NULL;
extern void *ptr_JetEndDatabaseIncrementalReseedA;
void *ptr_JetEndDatabaseIncrementalReseedA = NULL;
extern void *ptr_JetEndDatabaseIncrementalReseedW;
void *ptr_JetEndDatabaseIncrementalReseedW = NULL;
extern void *ptr_JetEndExternalBackup;
void *ptr_JetEndExternalBackup = NULL;
extern void *ptr_JetEndExternalBackupInstance;
void *ptr_JetEndExternalBackupInstance = NULL;
extern void *ptr_JetEndExternalBackupInstance2;
void *ptr_JetEndExternalBackupInstance2 = NULL;
extern void *ptr_JetEndSession;
void *ptr_JetEndSession = NULL;
extern void *ptr_JetEndSurrogateBackup;
void *ptr_JetEndSurrogateBackup = NULL;
extern void *ptr_JetEnumerateColumns;
void *ptr_JetEnumerateColumns = NULL;
extern void *ptr_JetEscrowUpdate;
void *ptr_JetEscrowUpdate = NULL;
extern void *ptr_JetExternalRestore;
void *ptr_JetExternalRestore = NULL;
extern void *ptr_JetExternalRestore2;
void *ptr_JetExternalRestore2 = NULL;
extern void *ptr_JetExternalRestore2A;
void *ptr_JetExternalRestore2A = NULL;
extern void *ptr_JetExternalRestore2W;
void *ptr_JetExternalRestore2W = NULL;
extern void *ptr_JetExternalRestoreA;
void *ptr_JetExternalRestoreA = NULL;
extern void *ptr_JetExternalRestoreW;
void *ptr_JetExternalRestoreW = NULL;
extern void *ptr_JetFreeBuffer;
void *ptr_JetFreeBuffer = NULL;
extern void *ptr_JetGetAttachInfo;
void *ptr_JetGetAttachInfo = NULL;
extern void *ptr_JetGetAttachInfoA;
void *ptr_JetGetAttachInfoA = NULL;
extern void *ptr_JetGetAttachInfoInstance;
void *ptr_JetGetAttachInfoInstance = NULL;
extern void *ptr_JetGetAttachInfoInstanceA;
void *ptr_JetGetAttachInfoInstanceA = NULL;
extern void *ptr_JetGetAttachInfoInstanceW;
void *ptr_JetGetAttachInfoInstanceW = NULL;
extern void *ptr_JetGetAttachInfoW;
void *ptr_JetGetAttachInfoW = NULL;
extern void *ptr_JetGetBookmark;
void *ptr_JetGetBookmark = NULL;
extern void *ptr_JetGetColumnInfo;
void *ptr_JetGetColumnInfo = NULL;
extern void *ptr_JetGetColumnInfoA;
void *ptr_JetGetColumnInfoA = NULL;
extern void *ptr_JetGetColumnInfoW;
void *ptr_JetGetColumnInfoW = NULL;
extern void *ptr_JetGetCounter;
void *ptr_JetGetCounter = NULL;
extern void *ptr_JetGetCurrentIndex;
void *ptr_JetGetCurrentIndex = NULL;
extern void *ptr_JetGetCurrentIndexA;
void *ptr_JetGetCurrentIndexA = NULL;
extern void *ptr_JetGetCurrentIndexW;
void *ptr_JetGetCurrentIndexW = NULL;
extern void *ptr_JetGetCursorInfo;
void *ptr_JetGetCursorInfo = NULL;
extern void *ptr_JetGetDatabaseFileInfo;
void *ptr_JetGetDatabaseFileInfo = NULL;
extern void *ptr_JetGetDatabaseFileInfoA;
void *ptr_JetGetDatabaseFileInfoA = NULL;
extern void *ptr_JetGetDatabaseFileInfoW;
void *ptr_JetGetDatabaseFileInfoW = NULL;
extern void *ptr_JetGetDatabaseInfo;
void *ptr_JetGetDatabaseInfo = NULL;
extern void *ptr_JetGetDatabaseInfoA;
void *ptr_JetGetDatabaseInfoA = NULL;
extern void *ptr_JetGetDatabaseInfoW;
void *ptr_JetGetDatabaseInfoW = NULL;
extern void *ptr_JetGetDatabasePages;
void *ptr_JetGetDatabasePages = NULL;
extern void *ptr_JetGetIndexInfo;
void *ptr_JetGetIndexInfo = NULL;
extern void *ptr_JetGetIndexInfoA;
void *ptr_JetGetIndexInfoA = NULL;
extern void *ptr_JetGetIndexInfoW;
void *ptr_JetGetIndexInfoW = NULL;
extern void *ptr_JetGetInstanceInfo;
void *ptr_JetGetInstanceInfo = NULL;
extern void *ptr_JetGetInstanceInfoA;
void *ptr_JetGetInstanceInfoA = NULL;
extern void *ptr_JetGetInstanceInfoW;
void *ptr_JetGetInstanceInfoW = NULL;
extern void *ptr_JetGetInstanceMiscInfo;
void *ptr_JetGetInstanceMiscInfo = NULL;
extern void *ptr_JetGetLS;
void *ptr_JetGetLS = NULL;
extern void *ptr_JetGetLock;
void *ptr_JetGetLock = NULL;
extern void *ptr_JetGetLogFileInfo;
void *ptr_JetGetLogFileInfo = NULL;
extern void *ptr_JetGetLogFileInfoA;
void *ptr_JetGetLogFileInfoA = NULL;
extern void *ptr_JetGetLogFileInfoW;
void *ptr_JetGetLogFileInfoW = NULL;
extern void *ptr_JetGetLogInfo;
void *ptr_JetGetLogInfo = NULL;
extern void *ptr_JetGetLogInfoA;
void *ptr_JetGetLogInfoA = NULL;
extern void *ptr_JetGetLogInfoInstance;
void *ptr_JetGetLogInfoInstance = NULL;
extern void *ptr_JetGetLogInfoInstance2;
void *ptr_JetGetLogInfoInstance2 = NULL;
extern void *ptr_JetGetLogInfoInstance2A;
void *ptr_JetGetLogInfoInstance2A = NULL;
extern void *ptr_JetGetLogInfoInstance2W;
void *ptr_JetGetLogInfoInstance2W = NULL;
extern void *ptr_JetGetLogInfoInstanceA;
void *ptr_JetGetLogInfoInstanceA = NULL;
extern void *ptr_JetGetLogInfoInstanceW;
void *ptr_JetGetLogInfoInstanceW = NULL;
extern void *ptr_JetGetLogInfoW;
void *ptr_JetGetLogInfoW = NULL;
extern void *ptr_JetGetMaxDatabaseSize;
void *ptr_JetGetMaxDatabaseSize = NULL;
extern void *ptr_JetGetObjectInfo;
void *ptr_JetGetObjectInfo = NULL;
extern void *ptr_JetGetObjectInfoA;
void *ptr_JetGetObjectInfoA = NULL;
extern void *ptr_JetGetObjectInfoW;
void *ptr_JetGetObjectInfoW = NULL;
extern void *ptr_JetGetPageInfo;
void *ptr_JetGetPageInfo = NULL;
extern void *ptr_JetGetPageInfo2;
void *ptr_JetGetPageInfo2 = NULL;
extern void *ptr_JetGetRecordPosition;
void *ptr_JetGetRecordPosition = NULL;
extern void *ptr_JetGetRecordSize;
void *ptr_JetGetRecordSize = NULL;
extern void *ptr_JetGetRecordSize2;
void *ptr_JetGetRecordSize2 = NULL;
extern void *ptr_JetGetResourceParam;
void *ptr_JetGetResourceParam = NULL;
extern void *ptr_JetGetSecondaryIndexBookmark;
void *ptr_JetGetSecondaryIndexBookmark = NULL;
extern void *ptr_JetGetSessionInfo;
void *ptr_JetGetSessionInfo = NULL;
extern void *ptr_JetGetSystemParameter;
void *ptr_JetGetSystemParameter = NULL;
extern void *ptr_JetGetSystemParameterA;
void *ptr_JetGetSystemParameterA = NULL;
extern void *ptr_JetGetSystemParameterW;
void *ptr_JetGetSystemParameterW = NULL;
extern void *ptr_JetGetTableColumnInfo;
void *ptr_JetGetTableColumnInfo = NULL;
extern void *ptr_JetGetTableColumnInfoA;
void *ptr_JetGetTableColumnInfoA = NULL;
extern void *ptr_JetGetTableColumnInfoW;
void *ptr_JetGetTableColumnInfoW = NULL;
extern void *ptr_JetGetTableIndexInfo;
void *ptr_JetGetTableIndexInfo = NULL;
extern void *ptr_JetGetTableIndexInfoA;
void *ptr_JetGetTableIndexInfoA = NULL;
extern void *ptr_JetGetTableIndexInfoW;
void *ptr_JetGetTableIndexInfoW = NULL;
extern void *ptr_JetGetTableInfo;
void *ptr_JetGetTableInfo = NULL;
extern void *ptr_JetGetTableInfoA;
void *ptr_JetGetTableInfoA = NULL;
extern void *ptr_JetGetTableInfoW;
void *ptr_JetGetTableInfoW = NULL;
extern void *ptr_JetGetThreadStats;
void *ptr_JetGetThreadStats = NULL;
extern void *ptr_JetGetTruncateLogInfoInstance;
void *ptr_JetGetTruncateLogInfoInstance = NULL;
extern void *ptr_JetGetTruncateLogInfoInstanceA;
void *ptr_JetGetTruncateLogInfoInstanceA = NULL;
extern void *ptr_JetGetTruncateLogInfoInstanceW;
void *ptr_JetGetTruncateLogInfoInstanceW = NULL;
extern void *ptr_JetGetVersion;
void *ptr_JetGetVersion = NULL;
extern void *ptr_JetGotoBookmark;
void *ptr_JetGotoBookmark = NULL;
extern void *ptr_JetGotoPosition;
void *ptr_JetGotoPosition = NULL;
extern void *ptr_JetGotoSecondaryIndexBookmark;
void *ptr_JetGotoSecondaryIndexBookmark = NULL;
extern void *ptr_JetGrowDatabase;
void *ptr_JetGrowDatabase = NULL;
extern void *ptr_JetIdle;
void *ptr_JetIdle = NULL;
extern void *ptr_JetIndexRecordCount;
void *ptr_JetIndexRecordCount = NULL;
extern void *ptr_JetInit;
void *ptr_JetInit = NULL;
extern void *ptr_JetInit2;
void *ptr_JetInit2 = NULL;
extern void *ptr_JetInit3;
void *ptr_JetInit3 = NULL;
extern void *ptr_JetInit3A;
void *ptr_JetInit3A = NULL;
extern void *ptr_JetInit3W;
void *ptr_JetInit3W = NULL;
extern void *ptr_JetIntersectIndexes;
void *ptr_JetIntersectIndexes = NULL;
extern void *ptr_JetMakeKey;
void *ptr_JetMakeKey = NULL;
extern void *ptr_JetMove;
void *ptr_JetMove = NULL;
extern void *ptr_JetOSSnapshotAbort;
void *ptr_JetOSSnapshotAbort = NULL;
extern void *ptr_JetOSSnapshotEnd;
void *ptr_JetOSSnapshotEnd = NULL;
extern void *ptr_JetOSSnapshotFreeze;
void *ptr_JetOSSnapshotFreeze = NULL;
extern void *ptr_JetOSSnapshotFreezeA;
void *ptr_JetOSSnapshotFreezeA = NULL;
extern void *ptr_JetOSSnapshotFreezeW;
void *ptr_JetOSSnapshotFreezeW = NULL;
extern void *ptr_JetOSSnapshotGetFreezeInfo;
void *ptr_JetOSSnapshotGetFreezeInfo = NULL;
extern void *ptr_JetOSSnapshotGetFreezeInfoA;
void *ptr_JetOSSnapshotGetFreezeInfoA = NULL;
extern void *ptr_JetOSSnapshotGetFreezeInfoW;
void *ptr_JetOSSnapshotGetFreezeInfoW = NULL;
extern void *ptr_JetOSSnapshotPrepare;
void *ptr_JetOSSnapshotPrepare = NULL;
extern void *ptr_JetOSSnapshotPrepareInstance;
void *ptr_JetOSSnapshotPrepareInstance = NULL;
extern void *ptr_JetOSSnapshotThaw;
void *ptr_JetOSSnapshotThaw = NULL;
extern void *ptr_JetOSSnapshotTruncateLog;
void *ptr_JetOSSnapshotTruncateLog = NULL;
extern void *ptr_JetOSSnapshotTruncateLogInstance;
void *ptr_JetOSSnapshotTruncateLogInstance = NULL;
extern void *ptr_JetOpenDatabase;
void *ptr_JetOpenDatabase = NULL;
extern void *ptr_JetOpenDatabaseA;
void *ptr_JetOpenDatabaseA = NULL;
extern void *ptr_JetOpenDatabaseW;
void *ptr_JetOpenDatabaseW = NULL;
extern void *ptr_JetOpenFile;
void *ptr_JetOpenFile = NULL;
extern void *ptr_JetOpenFileA;
void *ptr_JetOpenFileA = NULL;
extern void *ptr_JetOpenFileInstance;
void *ptr_JetOpenFileInstance = NULL;
extern void *ptr_JetOpenFileInstanceA;
void *ptr_JetOpenFileInstanceA = NULL;
extern void *ptr_JetOpenFileInstanceW;
void *ptr_JetOpenFileInstanceW = NULL;
extern void *ptr_JetOpenFileSectionInstance;
void *ptr_JetOpenFileSectionInstance = NULL;
extern void *ptr_JetOpenFileSectionInstanceA;
void *ptr_JetOpenFileSectionInstanceA = NULL;
extern void *ptr_JetOpenFileSectionInstanceW;
void *ptr_JetOpenFileSectionInstanceW = NULL;
extern void *ptr_JetOpenFileW;
void *ptr_JetOpenFileW = NULL;
extern void *ptr_JetOpenTable;
void *ptr_JetOpenTable = NULL;
extern void *ptr_JetOpenTableA;
void *ptr_JetOpenTableA = NULL;
extern void *ptr_JetOpenTableW;
void *ptr_JetOpenTableW = NULL;
extern void *ptr_JetOpenTempTable;
void *ptr_JetOpenTempTable = NULL;
extern void *ptr_JetOpenTempTable2;
void *ptr_JetOpenTempTable2 = NULL;
extern void *ptr_JetOpenTempTable3;
void *ptr_JetOpenTempTable3 = NULL;
extern void *ptr_JetOpenTemporaryTable;
void *ptr_JetOpenTemporaryTable = NULL;
extern void *ptr_JetPatchDatabasePages;
void *ptr_JetPatchDatabasePages = NULL;
extern void *ptr_JetPatchDatabasePagesA;
void *ptr_JetPatchDatabasePagesA = NULL;
extern void *ptr_JetPatchDatabasePagesW;
void *ptr_JetPatchDatabasePagesW = NULL;
extern void *ptr_JetPrepareToCommitTransaction;
void *ptr_JetPrepareToCommitTransaction = NULL;
extern void *ptr_JetPrepareUpdate;
void *ptr_JetPrepareUpdate = NULL;
extern void *ptr_JetPrereadKeys;
void *ptr_JetPrereadKeys = NULL;
extern void *ptr_JetReadFile;
void *ptr_JetReadFile = NULL;
extern void *ptr_JetReadFileInstance;
void *ptr_JetReadFileInstance = NULL;
extern void *ptr_JetRegisterCallback;
void *ptr_JetRegisterCallback = NULL;
extern void *ptr_JetRemoveLogfileA;
void *ptr_JetRemoveLogfileA = NULL;
extern void *ptr_JetRemoveLogfileW;
void *ptr_JetRemoveLogfileW = NULL;
extern void *ptr_JetRenameColumn;
void *ptr_JetRenameColumn = NULL;
extern void *ptr_JetRenameColumnA;
void *ptr_JetRenameColumnA = NULL;
extern void *ptr_JetRenameColumnW;
void *ptr_JetRenameColumnW = NULL;
extern void *ptr_JetRenameTable;
void *ptr_JetRenameTable = NULL;
extern void *ptr_JetRenameTableA;
void *ptr_JetRenameTableA = NULL;
extern void *ptr_JetRenameTableW;
void *ptr_JetRenameTableW = NULL;
extern void *ptr_JetResetCounter;
void *ptr_JetResetCounter = NULL;
extern void *ptr_JetResetSessionContext;
void *ptr_JetResetSessionContext = NULL;
extern void *ptr_JetResetTableSequential;
void *ptr_JetResetTableSequential = NULL;
extern void *ptr_JetRestore;
void *ptr_JetRestore = NULL;
extern void *ptr_JetRestore2;
void *ptr_JetRestore2 = NULL;
extern void *ptr_JetRestore2A;
void *ptr_JetRestore2A = NULL;
extern void *ptr_JetRestore2W;
void *ptr_JetRestore2W = NULL;
extern void *ptr_JetRestoreA;
void *ptr_JetRestoreA = NULL;
extern void *ptr_JetRestoreInstance;
void *ptr_JetRestoreInstance = NULL;
extern void *ptr_JetRestoreInstanceA;
void *ptr_JetRestoreInstanceA = NULL;
extern void *ptr_JetRestoreInstanceW;
void *ptr_JetRestoreInstanceW = NULL;
extern void *ptr_JetRestoreW;
void *ptr_JetRestoreW = NULL;
extern void *ptr_JetRetrieveColumn;
void *ptr_JetRetrieveColumn = NULL;
extern void *ptr_JetRetrieveColumns;
void *ptr_JetRetrieveColumns = NULL;
extern void *ptr_JetRetrieveKey;
void *ptr_JetRetrieveKey = NULL;
extern void *ptr_JetRetrieveTaggedColumnList;
void *ptr_JetRetrieveTaggedColumnList = NULL;
extern void *ptr_JetRollback;
void *ptr_JetRollback = NULL;
extern void *ptr_JetSeek;
void *ptr_JetSeek = NULL;
extern void *ptr_JetSetColumn;
void *ptr_JetSetColumn = NULL;
extern void *ptr_JetSetColumnDefaultValue;
void *ptr_JetSetColumnDefaultValue = NULL;
extern void *ptr_JetSetColumnDefaultValueA;
void *ptr_JetSetColumnDefaultValueA = NULL;
extern void *ptr_JetSetColumnDefaultValueW;
void *ptr_JetSetColumnDefaultValueW = NULL;
extern void *ptr_JetSetColumns;
void *ptr_JetSetColumns = NULL;
extern void *ptr_JetSetCurrentIndex;
void *ptr_JetSetCurrentIndex = NULL;
extern void *ptr_JetSetCurrentIndex2;
void *ptr_JetSetCurrentIndex2 = NULL;
extern void *ptr_JetSetCurrentIndex2A;
void *ptr_JetSetCurrentIndex2A = NULL;
extern void *ptr_JetSetCurrentIndex2W;
void *ptr_JetSetCurrentIndex2W = NULL;
extern void *ptr_JetSetCurrentIndex3;
void *ptr_JetSetCurrentIndex3 = NULL;
extern void *ptr_JetSetCurrentIndex3A;
void *ptr_JetSetCurrentIndex3A = NULL;
extern void *ptr_JetSetCurrentIndex3W;
void *ptr_JetSetCurrentIndex3W = NULL;
extern void *ptr_JetSetCurrentIndex4;
void *ptr_JetSetCurrentIndex4 = NULL;
extern void *ptr_JetSetCurrentIndex4A;
void *ptr_JetSetCurrentIndex4A = NULL;
extern void *ptr_JetSetCurrentIndex4W;
void *ptr_JetSetCurrentIndex4W = NULL;
extern void *ptr_JetSetCurrentIndexA;
void *ptr_JetSetCurrentIndexA = NULL;
extern void *ptr_JetSetCurrentIndexW;
void *ptr_JetSetCurrentIndexW = NULL;
extern void *ptr_JetSetDatabaseSize;
void *ptr_JetSetDatabaseSize = NULL;
extern void *ptr_JetSetDatabaseSizeA;
void *ptr_JetSetDatabaseSizeA = NULL;
extern void *ptr_JetSetDatabaseSizeW;
void *ptr_JetSetDatabaseSizeW = NULL;
extern void *ptr_JetSetIndexRange;
void *ptr_JetSetIndexRange = NULL;
extern void *ptr_JetSetLS;
void *ptr_JetSetLS = NULL;
extern void *ptr_JetSetMaxDatabaseSize;
void *ptr_JetSetMaxDatabaseSize = NULL;
extern void *ptr_JetSetResourceParam;
void *ptr_JetSetResourceParam = NULL;
extern void *ptr_JetSetSessionContext;
void *ptr_JetSetSessionContext = NULL;
extern void *ptr_JetSetSystemParameter;
void *ptr_JetSetSystemParameter = NULL;
extern void *ptr_JetSetSystemParameterA;
void *ptr_JetSetSystemParameterA = NULL;
extern void *ptr_JetSetSystemParameterW;
void *ptr_JetSetSystemParameterW = NULL;
extern void *ptr_JetSetTableSequential;
void *ptr_JetSetTableSequential = NULL;
extern void *ptr_JetSnapshotStart;
void *ptr_JetSnapshotStart = NULL;
extern void *ptr_JetSnapshotStartA;
void *ptr_JetSnapshotStartA = NULL;
extern void *ptr_JetSnapshotStartW;
void *ptr_JetSnapshotStartW = NULL;
extern void *ptr_JetSnapshotStop;
void *ptr_JetSnapshotStop = NULL;
extern void *ptr_JetStopBackup;
void *ptr_JetStopBackup = NULL;
extern void *ptr_JetStopBackupInstance;
void *ptr_JetStopBackupInstance = NULL;
extern void *ptr_JetStopService;
void *ptr_JetStopService = NULL;
extern void *ptr_JetStopServiceInstance;
void *ptr_JetStopServiceInstance = NULL;
extern void *ptr_JetTerm;
void *ptr_JetTerm = NULL;
extern void *ptr_JetTerm2;
void *ptr_JetTerm2 = NULL;
extern void *ptr_JetTest;
void *ptr_JetTest = NULL;
extern void *ptr_JetTracing;
void *ptr_JetTracing = NULL;
extern void *ptr_JetTruncateLog;
void *ptr_JetTruncateLog = NULL;
extern void *ptr_JetTruncateLogInstance;
void *ptr_JetTruncateLogInstance = NULL;
extern void *ptr_JetUnregisterCallback;
void *ptr_JetUnregisterCallback = NULL;
extern void *ptr_JetUpdate;
void *ptr_JetUpdate = NULL;
extern void *ptr_JetUpdate2;
void *ptr_JetUpdate2 = NULL;
extern void *ptr_JetUpgradeDatabase;
void *ptr_JetUpgradeDatabase = NULL;
extern void *ptr_JetUpgradeDatabaseA;
void *ptr_JetUpgradeDatabaseA = NULL;
extern void *ptr_JetUpgradeDatabaseW;
void *ptr_JetUpgradeDatabaseW = NULL;
extern void *ptr_ese;
void *ptr_ese = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\esent.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_DebugExtensionInitialize = (__vartype(ptr_DebugExtensionInitialize))GetProcAddress(hModule, "DebugExtensionInitialize");
   ptr_DebugExtensionNotify = (__vartype(ptr_DebugExtensionNotify))GetProcAddress(hModule, "DebugExtensionNotify");
   ptr_DebugExtensionUninitialize = (__vartype(ptr_DebugExtensionUninitialize))GetProcAddress(hModule, "DebugExtensionUninitialize");
   ptr_JetAddColumn = (__vartype(ptr_JetAddColumn))GetProcAddress(hModule, "JetAddColumn");
   ptr_JetAddColumnA = (__vartype(ptr_JetAddColumnA))GetProcAddress(hModule, "JetAddColumnA");
   ptr_JetAddColumnW = (__vartype(ptr_JetAddColumnW))GetProcAddress(hModule, "JetAddColumnW");
   ptr_JetAttachDatabase = (__vartype(ptr_JetAttachDatabase))GetProcAddress(hModule, "JetAttachDatabase");
   ptr_JetAttachDatabase2 = (__vartype(ptr_JetAttachDatabase2))GetProcAddress(hModule, "JetAttachDatabase2");
   ptr_JetAttachDatabase2A = (__vartype(ptr_JetAttachDatabase2A))GetProcAddress(hModule, "JetAttachDatabase2A");
   ptr_JetAttachDatabase2W = (__vartype(ptr_JetAttachDatabase2W))GetProcAddress(hModule, "JetAttachDatabase2W");
   ptr_JetAttachDatabaseA = (__vartype(ptr_JetAttachDatabaseA))GetProcAddress(hModule, "JetAttachDatabaseA");
   ptr_JetAttachDatabaseW = (__vartype(ptr_JetAttachDatabaseW))GetProcAddress(hModule, "JetAttachDatabaseW");
   ptr_JetAttachDatabaseWithStreaming = (__vartype(ptr_JetAttachDatabaseWithStreaming))GetProcAddress(hModule, "JetAttachDatabaseWithStreaming");
   ptr_JetAttachDatabaseWithStreamingA = (__vartype(ptr_JetAttachDatabaseWithStreamingA))GetProcAddress(hModule, "JetAttachDatabaseWithStreamingA");
   ptr_JetAttachDatabaseWithStreamingW = (__vartype(ptr_JetAttachDatabaseWithStreamingW))GetProcAddress(hModule, "JetAttachDatabaseWithStreamingW");
   ptr_JetBackup = (__vartype(ptr_JetBackup))GetProcAddress(hModule, "JetBackup");
   ptr_JetBackupA = (__vartype(ptr_JetBackupA))GetProcAddress(hModule, "JetBackupA");
   ptr_JetBackupInstance = (__vartype(ptr_JetBackupInstance))GetProcAddress(hModule, "JetBackupInstance");
   ptr_JetBackupInstanceA = (__vartype(ptr_JetBackupInstanceA))GetProcAddress(hModule, "JetBackupInstanceA");
   ptr_JetBackupInstanceW = (__vartype(ptr_JetBackupInstanceW))GetProcAddress(hModule, "JetBackupInstanceW");
   ptr_JetBackupW = (__vartype(ptr_JetBackupW))GetProcAddress(hModule, "JetBackupW");
   ptr_JetBeginDatabaseIncrementalReseed = (__vartype(ptr_JetBeginDatabaseIncrementalReseed))GetProcAddress(hModule, "JetBeginDatabaseIncrementalReseed");
   ptr_JetBeginDatabaseIncrementalReseedA = (__vartype(ptr_JetBeginDatabaseIncrementalReseedA))GetProcAddress(hModule, "JetBeginDatabaseIncrementalReseedA");
   ptr_JetBeginDatabaseIncrementalReseedW = (__vartype(ptr_JetBeginDatabaseIncrementalReseedW))GetProcAddress(hModule, "JetBeginDatabaseIncrementalReseedW");
   ptr_JetBeginExternalBackup = (__vartype(ptr_JetBeginExternalBackup))GetProcAddress(hModule, "JetBeginExternalBackup");
   ptr_JetBeginExternalBackupInstance = (__vartype(ptr_JetBeginExternalBackupInstance))GetProcAddress(hModule, "JetBeginExternalBackupInstance");
   ptr_JetBeginSession = (__vartype(ptr_JetBeginSession))GetProcAddress(hModule, "JetBeginSession");
   ptr_JetBeginSessionA = (__vartype(ptr_JetBeginSessionA))GetProcAddress(hModule, "JetBeginSessionA");
   ptr_JetBeginSessionW = (__vartype(ptr_JetBeginSessionW))GetProcAddress(hModule, "JetBeginSessionW");
   ptr_JetBeginSurrogateBackup = (__vartype(ptr_JetBeginSurrogateBackup))GetProcAddress(hModule, "JetBeginSurrogateBackup");
   ptr_JetBeginTransaction = (__vartype(ptr_JetBeginTransaction))GetProcAddress(hModule, "JetBeginTransaction");
   ptr_JetBeginTransaction2 = (__vartype(ptr_JetBeginTransaction2))GetProcAddress(hModule, "JetBeginTransaction2");
   ptr_JetCloseDatabase = (__vartype(ptr_JetCloseDatabase))GetProcAddress(hModule, "JetCloseDatabase");
   ptr_JetCloseFile = (__vartype(ptr_JetCloseFile))GetProcAddress(hModule, "JetCloseFile");
   ptr_JetCloseFileInstance = (__vartype(ptr_JetCloseFileInstance))GetProcAddress(hModule, "JetCloseFileInstance");
   ptr_JetCloseTable = (__vartype(ptr_JetCloseTable))GetProcAddress(hModule, "JetCloseTable");
   ptr_JetCommitTransaction = (__vartype(ptr_JetCommitTransaction))GetProcAddress(hModule, "JetCommitTransaction");
   ptr_JetCompact = (__vartype(ptr_JetCompact))GetProcAddress(hModule, "JetCompact");
   ptr_JetCompactA = (__vartype(ptr_JetCompactA))GetProcAddress(hModule, "JetCompactA");
   ptr_JetCompactW = (__vartype(ptr_JetCompactW))GetProcAddress(hModule, "JetCompactW");
   ptr_JetComputeStats = (__vartype(ptr_JetComputeStats))GetProcAddress(hModule, "JetComputeStats");
   ptr_JetConfigureProcessForCrashDump = (__vartype(ptr_JetConfigureProcessForCrashDump))GetProcAddress(hModule, "JetConfigureProcessForCrashDump");
   ptr_JetConvertDDL = (__vartype(ptr_JetConvertDDL))GetProcAddress(hModule, "JetConvertDDL");
   ptr_JetConvertDDLA = (__vartype(ptr_JetConvertDDLA))GetProcAddress(hModule, "JetConvertDDLA");
   ptr_JetConvertDDLW = (__vartype(ptr_JetConvertDDLW))GetProcAddress(hModule, "JetConvertDDLW");
   ptr_JetCreateDatabase = (__vartype(ptr_JetCreateDatabase))GetProcAddress(hModule, "JetCreateDatabase");
   ptr_JetCreateDatabase2 = (__vartype(ptr_JetCreateDatabase2))GetProcAddress(hModule, "JetCreateDatabase2");
   ptr_JetCreateDatabase2A = (__vartype(ptr_JetCreateDatabase2A))GetProcAddress(hModule, "JetCreateDatabase2A");
   ptr_JetCreateDatabase2W = (__vartype(ptr_JetCreateDatabase2W))GetProcAddress(hModule, "JetCreateDatabase2W");
   ptr_JetCreateDatabaseA = (__vartype(ptr_JetCreateDatabaseA))GetProcAddress(hModule, "JetCreateDatabaseA");
   ptr_JetCreateDatabaseW = (__vartype(ptr_JetCreateDatabaseW))GetProcAddress(hModule, "JetCreateDatabaseW");
   ptr_JetCreateDatabaseWithStreaming = (__vartype(ptr_JetCreateDatabaseWithStreaming))GetProcAddress(hModule, "JetCreateDatabaseWithStreaming");
   ptr_JetCreateDatabaseWithStreamingA = (__vartype(ptr_JetCreateDatabaseWithStreamingA))GetProcAddress(hModule, "JetCreateDatabaseWithStreamingA");
   ptr_JetCreateDatabaseWithStreamingW = (__vartype(ptr_JetCreateDatabaseWithStreamingW))GetProcAddress(hModule, "JetCreateDatabaseWithStreamingW");
   ptr_JetCreateIndex = (__vartype(ptr_JetCreateIndex))GetProcAddress(hModule, "JetCreateIndex");
   ptr_JetCreateIndex2 = (__vartype(ptr_JetCreateIndex2))GetProcAddress(hModule, "JetCreateIndex2");
   ptr_JetCreateIndex2A = (__vartype(ptr_JetCreateIndex2A))GetProcAddress(hModule, "JetCreateIndex2A");
   ptr_JetCreateIndex2W = (__vartype(ptr_JetCreateIndex2W))GetProcAddress(hModule, "JetCreateIndex2W");
   ptr_JetCreateIndex3A = (__vartype(ptr_JetCreateIndex3A))GetProcAddress(hModule, "JetCreateIndex3A");
   ptr_JetCreateIndex3W = (__vartype(ptr_JetCreateIndex3W))GetProcAddress(hModule, "JetCreateIndex3W");
   ptr_JetCreateIndexA = (__vartype(ptr_JetCreateIndexA))GetProcAddress(hModule, "JetCreateIndexA");
   ptr_JetCreateIndexW = (__vartype(ptr_JetCreateIndexW))GetProcAddress(hModule, "JetCreateIndexW");
   ptr_JetCreateInstance = (__vartype(ptr_JetCreateInstance))GetProcAddress(hModule, "JetCreateInstance");
   ptr_JetCreateInstance2 = (__vartype(ptr_JetCreateInstance2))GetProcAddress(hModule, "JetCreateInstance2");
   ptr_JetCreateInstance2A = (__vartype(ptr_JetCreateInstance2A))GetProcAddress(hModule, "JetCreateInstance2A");
   ptr_JetCreateInstance2W = (__vartype(ptr_JetCreateInstance2W))GetProcAddress(hModule, "JetCreateInstance2W");
   ptr_JetCreateInstanceA = (__vartype(ptr_JetCreateInstanceA))GetProcAddress(hModule, "JetCreateInstanceA");
   ptr_JetCreateInstanceW = (__vartype(ptr_JetCreateInstanceW))GetProcAddress(hModule, "JetCreateInstanceW");
   ptr_JetCreateTable = (__vartype(ptr_JetCreateTable))GetProcAddress(hModule, "JetCreateTable");
   ptr_JetCreateTableA = (__vartype(ptr_JetCreateTableA))GetProcAddress(hModule, "JetCreateTableA");
   ptr_JetCreateTableColumnIndex = (__vartype(ptr_JetCreateTableColumnIndex))GetProcAddress(hModule, "JetCreateTableColumnIndex");
   ptr_JetCreateTableColumnIndex2 = (__vartype(ptr_JetCreateTableColumnIndex2))GetProcAddress(hModule, "JetCreateTableColumnIndex2");
   ptr_JetCreateTableColumnIndex2A = (__vartype(ptr_JetCreateTableColumnIndex2A))GetProcAddress(hModule, "JetCreateTableColumnIndex2A");
   ptr_JetCreateTableColumnIndex2W = (__vartype(ptr_JetCreateTableColumnIndex2W))GetProcAddress(hModule, "JetCreateTableColumnIndex2W");
   ptr_JetCreateTableColumnIndex3A = (__vartype(ptr_JetCreateTableColumnIndex3A))GetProcAddress(hModule, "JetCreateTableColumnIndex3A");
   ptr_JetCreateTableColumnIndex3W = (__vartype(ptr_JetCreateTableColumnIndex3W))GetProcAddress(hModule, "JetCreateTableColumnIndex3W");
   ptr_JetCreateTableColumnIndexA = (__vartype(ptr_JetCreateTableColumnIndexA))GetProcAddress(hModule, "JetCreateTableColumnIndexA");
   ptr_JetCreateTableColumnIndexW = (__vartype(ptr_JetCreateTableColumnIndexW))GetProcAddress(hModule, "JetCreateTableColumnIndexW");
   ptr_JetCreateTableW = (__vartype(ptr_JetCreateTableW))GetProcAddress(hModule, "JetCreateTableW");
   ptr_JetDBUtilities = (__vartype(ptr_JetDBUtilities))GetProcAddress(hModule, "JetDBUtilities");
   ptr_JetDBUtilitiesA = (__vartype(ptr_JetDBUtilitiesA))GetProcAddress(hModule, "JetDBUtilitiesA");
   ptr_JetDBUtilitiesW = (__vartype(ptr_JetDBUtilitiesW))GetProcAddress(hModule, "JetDBUtilitiesW");
   ptr_JetDatabaseScan = (__vartype(ptr_JetDatabaseScan))GetProcAddress(hModule, "JetDatabaseScan");
   ptr_JetDefragment = (__vartype(ptr_JetDefragment))GetProcAddress(hModule, "JetDefragment");
   ptr_JetDefragment2 = (__vartype(ptr_JetDefragment2))GetProcAddress(hModule, "JetDefragment2");
   ptr_JetDefragment2A = (__vartype(ptr_JetDefragment2A))GetProcAddress(hModule, "JetDefragment2A");
   ptr_JetDefragment2W = (__vartype(ptr_JetDefragment2W))GetProcAddress(hModule, "JetDefragment2W");
   ptr_JetDefragment3 = (__vartype(ptr_JetDefragment3))GetProcAddress(hModule, "JetDefragment3");
   ptr_JetDefragment3A = (__vartype(ptr_JetDefragment3A))GetProcAddress(hModule, "JetDefragment3A");
   ptr_JetDefragment3W = (__vartype(ptr_JetDefragment3W))GetProcAddress(hModule, "JetDefragment3W");
   ptr_JetDefragmentA = (__vartype(ptr_JetDefragmentA))GetProcAddress(hModule, "JetDefragmentA");
   ptr_JetDefragmentW = (__vartype(ptr_JetDefragmentW))GetProcAddress(hModule, "JetDefragmentW");
   ptr_JetDelete = (__vartype(ptr_JetDelete))GetProcAddress(hModule, "JetDelete");
   ptr_JetDeleteColumn = (__vartype(ptr_JetDeleteColumn))GetProcAddress(hModule, "JetDeleteColumn");
   ptr_JetDeleteColumn2 = (__vartype(ptr_JetDeleteColumn2))GetProcAddress(hModule, "JetDeleteColumn2");
   ptr_JetDeleteColumn2A = (__vartype(ptr_JetDeleteColumn2A))GetProcAddress(hModule, "JetDeleteColumn2A");
   ptr_JetDeleteColumn2W = (__vartype(ptr_JetDeleteColumn2W))GetProcAddress(hModule, "JetDeleteColumn2W");
   ptr_JetDeleteColumnA = (__vartype(ptr_JetDeleteColumnA))GetProcAddress(hModule, "JetDeleteColumnA");
   ptr_JetDeleteColumnW = (__vartype(ptr_JetDeleteColumnW))GetProcAddress(hModule, "JetDeleteColumnW");
   ptr_JetDeleteIndex = (__vartype(ptr_JetDeleteIndex))GetProcAddress(hModule, "JetDeleteIndex");
   ptr_JetDeleteIndexA = (__vartype(ptr_JetDeleteIndexA))GetProcAddress(hModule, "JetDeleteIndexA");
   ptr_JetDeleteIndexW = (__vartype(ptr_JetDeleteIndexW))GetProcAddress(hModule, "JetDeleteIndexW");
   ptr_JetDeleteTable = (__vartype(ptr_JetDeleteTable))GetProcAddress(hModule, "JetDeleteTable");
   ptr_JetDeleteTableA = (__vartype(ptr_JetDeleteTableA))GetProcAddress(hModule, "JetDeleteTableA");
   ptr_JetDeleteTableW = (__vartype(ptr_JetDeleteTableW))GetProcAddress(hModule, "JetDeleteTableW");
   ptr_JetDetachDatabase = (__vartype(ptr_JetDetachDatabase))GetProcAddress(hModule, "JetDetachDatabase");
   ptr_JetDetachDatabase2 = (__vartype(ptr_JetDetachDatabase2))GetProcAddress(hModule, "JetDetachDatabase2");
   ptr_JetDetachDatabase2A = (__vartype(ptr_JetDetachDatabase2A))GetProcAddress(hModule, "JetDetachDatabase2A");
   ptr_JetDetachDatabase2W = (__vartype(ptr_JetDetachDatabase2W))GetProcAddress(hModule, "JetDetachDatabase2W");
   ptr_JetDetachDatabaseA = (__vartype(ptr_JetDetachDatabaseA))GetProcAddress(hModule, "JetDetachDatabaseA");
   ptr_JetDetachDatabaseW = (__vartype(ptr_JetDetachDatabaseW))GetProcAddress(hModule, "JetDetachDatabaseW");
   ptr_JetDupCursor = (__vartype(ptr_JetDupCursor))GetProcAddress(hModule, "JetDupCursor");
   ptr_JetDupSession = (__vartype(ptr_JetDupSession))GetProcAddress(hModule, "JetDupSession");
   ptr_JetEnableFaultInjection = (__vartype(ptr_JetEnableFaultInjection))GetProcAddress(hModule, "JetEnableFaultInjection");
   ptr_JetEnableMultiInstance = (__vartype(ptr_JetEnableMultiInstance))GetProcAddress(hModule, "JetEnableMultiInstance");
   ptr_JetEnableMultiInstanceA = (__vartype(ptr_JetEnableMultiInstanceA))GetProcAddress(hModule, "JetEnableMultiInstanceA");
   ptr_JetEnableMultiInstanceW = (__vartype(ptr_JetEnableMultiInstanceW))GetProcAddress(hModule, "JetEnableMultiInstanceW");
   ptr_JetEndDatabaseIncrementalReseed = (__vartype(ptr_JetEndDatabaseIncrementalReseed))GetProcAddress(hModule, "JetEndDatabaseIncrementalReseed");
   ptr_JetEndDatabaseIncrementalReseedA = (__vartype(ptr_JetEndDatabaseIncrementalReseedA))GetProcAddress(hModule, "JetEndDatabaseIncrementalReseedA");
   ptr_JetEndDatabaseIncrementalReseedW = (__vartype(ptr_JetEndDatabaseIncrementalReseedW))GetProcAddress(hModule, "JetEndDatabaseIncrementalReseedW");
   ptr_JetEndExternalBackup = (__vartype(ptr_JetEndExternalBackup))GetProcAddress(hModule, "JetEndExternalBackup");
   ptr_JetEndExternalBackupInstance = (__vartype(ptr_JetEndExternalBackupInstance))GetProcAddress(hModule, "JetEndExternalBackupInstance");
   ptr_JetEndExternalBackupInstance2 = (__vartype(ptr_JetEndExternalBackupInstance2))GetProcAddress(hModule, "JetEndExternalBackupInstance2");
   ptr_JetEndSession = (__vartype(ptr_JetEndSession))GetProcAddress(hModule, "JetEndSession");
   ptr_JetEndSurrogateBackup = (__vartype(ptr_JetEndSurrogateBackup))GetProcAddress(hModule, "JetEndSurrogateBackup");
   ptr_JetEnumerateColumns = (__vartype(ptr_JetEnumerateColumns))GetProcAddress(hModule, "JetEnumerateColumns");
   ptr_JetEscrowUpdate = (__vartype(ptr_JetEscrowUpdate))GetProcAddress(hModule, "JetEscrowUpdate");
   ptr_JetExternalRestore = (__vartype(ptr_JetExternalRestore))GetProcAddress(hModule, "JetExternalRestore");
   ptr_JetExternalRestore2 = (__vartype(ptr_JetExternalRestore2))GetProcAddress(hModule, "JetExternalRestore2");
   ptr_JetExternalRestore2A = (__vartype(ptr_JetExternalRestore2A))GetProcAddress(hModule, "JetExternalRestore2A");
   ptr_JetExternalRestore2W = (__vartype(ptr_JetExternalRestore2W))GetProcAddress(hModule, "JetExternalRestore2W");
   ptr_JetExternalRestoreA = (__vartype(ptr_JetExternalRestoreA))GetProcAddress(hModule, "JetExternalRestoreA");
   ptr_JetExternalRestoreW = (__vartype(ptr_JetExternalRestoreW))GetProcAddress(hModule, "JetExternalRestoreW");
   ptr_JetFreeBuffer = (__vartype(ptr_JetFreeBuffer))GetProcAddress(hModule, "JetFreeBuffer");
   ptr_JetGetAttachInfo = (__vartype(ptr_JetGetAttachInfo))GetProcAddress(hModule, "JetGetAttachInfo");
   ptr_JetGetAttachInfoA = (__vartype(ptr_JetGetAttachInfoA))GetProcAddress(hModule, "JetGetAttachInfoA");
   ptr_JetGetAttachInfoInstance = (__vartype(ptr_JetGetAttachInfoInstance))GetProcAddress(hModule, "JetGetAttachInfoInstance");
   ptr_JetGetAttachInfoInstanceA = (__vartype(ptr_JetGetAttachInfoInstanceA))GetProcAddress(hModule, "JetGetAttachInfoInstanceA");
   ptr_JetGetAttachInfoInstanceW = (__vartype(ptr_JetGetAttachInfoInstanceW))GetProcAddress(hModule, "JetGetAttachInfoInstanceW");
   ptr_JetGetAttachInfoW = (__vartype(ptr_JetGetAttachInfoW))GetProcAddress(hModule, "JetGetAttachInfoW");
   ptr_JetGetBookmark = (__vartype(ptr_JetGetBookmark))GetProcAddress(hModule, "JetGetBookmark");
   ptr_JetGetColumnInfo = (__vartype(ptr_JetGetColumnInfo))GetProcAddress(hModule, "JetGetColumnInfo");
   ptr_JetGetColumnInfoA = (__vartype(ptr_JetGetColumnInfoA))GetProcAddress(hModule, "JetGetColumnInfoA");
   ptr_JetGetColumnInfoW = (__vartype(ptr_JetGetColumnInfoW))GetProcAddress(hModule, "JetGetColumnInfoW");
   ptr_JetGetCounter = (__vartype(ptr_JetGetCounter))GetProcAddress(hModule, "JetGetCounter");
   ptr_JetGetCurrentIndex = (__vartype(ptr_JetGetCurrentIndex))GetProcAddress(hModule, "JetGetCurrentIndex");
   ptr_JetGetCurrentIndexA = (__vartype(ptr_JetGetCurrentIndexA))GetProcAddress(hModule, "JetGetCurrentIndexA");
   ptr_JetGetCurrentIndexW = (__vartype(ptr_JetGetCurrentIndexW))GetProcAddress(hModule, "JetGetCurrentIndexW");
   ptr_JetGetCursorInfo = (__vartype(ptr_JetGetCursorInfo))GetProcAddress(hModule, "JetGetCursorInfo");
   ptr_JetGetDatabaseFileInfo = (__vartype(ptr_JetGetDatabaseFileInfo))GetProcAddress(hModule, "JetGetDatabaseFileInfo");
   ptr_JetGetDatabaseFileInfoA = (__vartype(ptr_JetGetDatabaseFileInfoA))GetProcAddress(hModule, "JetGetDatabaseFileInfoA");
   ptr_JetGetDatabaseFileInfoW = (__vartype(ptr_JetGetDatabaseFileInfoW))GetProcAddress(hModule, "JetGetDatabaseFileInfoW");
   ptr_JetGetDatabaseInfo = (__vartype(ptr_JetGetDatabaseInfo))GetProcAddress(hModule, "JetGetDatabaseInfo");
   ptr_JetGetDatabaseInfoA = (__vartype(ptr_JetGetDatabaseInfoA))GetProcAddress(hModule, "JetGetDatabaseInfoA");
   ptr_JetGetDatabaseInfoW = (__vartype(ptr_JetGetDatabaseInfoW))GetProcAddress(hModule, "JetGetDatabaseInfoW");
   ptr_JetGetDatabasePages = (__vartype(ptr_JetGetDatabasePages))GetProcAddress(hModule, "JetGetDatabasePages");
   ptr_JetGetIndexInfo = (__vartype(ptr_JetGetIndexInfo))GetProcAddress(hModule, "JetGetIndexInfo");
   ptr_JetGetIndexInfoA = (__vartype(ptr_JetGetIndexInfoA))GetProcAddress(hModule, "JetGetIndexInfoA");
   ptr_JetGetIndexInfoW = (__vartype(ptr_JetGetIndexInfoW))GetProcAddress(hModule, "JetGetIndexInfoW");
   ptr_JetGetInstanceInfo = (__vartype(ptr_JetGetInstanceInfo))GetProcAddress(hModule, "JetGetInstanceInfo");
   ptr_JetGetInstanceInfoA = (__vartype(ptr_JetGetInstanceInfoA))GetProcAddress(hModule, "JetGetInstanceInfoA");
   ptr_JetGetInstanceInfoW = (__vartype(ptr_JetGetInstanceInfoW))GetProcAddress(hModule, "JetGetInstanceInfoW");
   ptr_JetGetInstanceMiscInfo = (__vartype(ptr_JetGetInstanceMiscInfo))GetProcAddress(hModule, "JetGetInstanceMiscInfo");
   ptr_JetGetLS = (__vartype(ptr_JetGetLS))GetProcAddress(hModule, "JetGetLS");
   ptr_JetGetLock = (__vartype(ptr_JetGetLock))GetProcAddress(hModule, "JetGetLock");
   ptr_JetGetLogFileInfo = (__vartype(ptr_JetGetLogFileInfo))GetProcAddress(hModule, "JetGetLogFileInfo");
   ptr_JetGetLogFileInfoA = (__vartype(ptr_JetGetLogFileInfoA))GetProcAddress(hModule, "JetGetLogFileInfoA");
   ptr_JetGetLogFileInfoW = (__vartype(ptr_JetGetLogFileInfoW))GetProcAddress(hModule, "JetGetLogFileInfoW");
   ptr_JetGetLogInfo = (__vartype(ptr_JetGetLogInfo))GetProcAddress(hModule, "JetGetLogInfo");
   ptr_JetGetLogInfoA = (__vartype(ptr_JetGetLogInfoA))GetProcAddress(hModule, "JetGetLogInfoA");
   ptr_JetGetLogInfoInstance = (__vartype(ptr_JetGetLogInfoInstance))GetProcAddress(hModule, "JetGetLogInfoInstance");
   ptr_JetGetLogInfoInstance2 = (__vartype(ptr_JetGetLogInfoInstance2))GetProcAddress(hModule, "JetGetLogInfoInstance2");
   ptr_JetGetLogInfoInstance2A = (__vartype(ptr_JetGetLogInfoInstance2A))GetProcAddress(hModule, "JetGetLogInfoInstance2A");
   ptr_JetGetLogInfoInstance2W = (__vartype(ptr_JetGetLogInfoInstance2W))GetProcAddress(hModule, "JetGetLogInfoInstance2W");
   ptr_JetGetLogInfoInstanceA = (__vartype(ptr_JetGetLogInfoInstanceA))GetProcAddress(hModule, "JetGetLogInfoInstanceA");
   ptr_JetGetLogInfoInstanceW = (__vartype(ptr_JetGetLogInfoInstanceW))GetProcAddress(hModule, "JetGetLogInfoInstanceW");
   ptr_JetGetLogInfoW = (__vartype(ptr_JetGetLogInfoW))GetProcAddress(hModule, "JetGetLogInfoW");
   ptr_JetGetMaxDatabaseSize = (__vartype(ptr_JetGetMaxDatabaseSize))GetProcAddress(hModule, "JetGetMaxDatabaseSize");
   ptr_JetGetObjectInfo = (__vartype(ptr_JetGetObjectInfo))GetProcAddress(hModule, "JetGetObjectInfo");
   ptr_JetGetObjectInfoA = (__vartype(ptr_JetGetObjectInfoA))GetProcAddress(hModule, "JetGetObjectInfoA");
   ptr_JetGetObjectInfoW = (__vartype(ptr_JetGetObjectInfoW))GetProcAddress(hModule, "JetGetObjectInfoW");
   ptr_JetGetPageInfo = (__vartype(ptr_JetGetPageInfo))GetProcAddress(hModule, "JetGetPageInfo");
   ptr_JetGetPageInfo2 = (__vartype(ptr_JetGetPageInfo2))GetProcAddress(hModule, "JetGetPageInfo2");
   ptr_JetGetRecordPosition = (__vartype(ptr_JetGetRecordPosition))GetProcAddress(hModule, "JetGetRecordPosition");
   ptr_JetGetRecordSize = (__vartype(ptr_JetGetRecordSize))GetProcAddress(hModule, "JetGetRecordSize");
   ptr_JetGetRecordSize2 = (__vartype(ptr_JetGetRecordSize2))GetProcAddress(hModule, "JetGetRecordSize2");
   ptr_JetGetResourceParam = (__vartype(ptr_JetGetResourceParam))GetProcAddress(hModule, "JetGetResourceParam");
   ptr_JetGetSecondaryIndexBookmark = (__vartype(ptr_JetGetSecondaryIndexBookmark))GetProcAddress(hModule, "JetGetSecondaryIndexBookmark");
   ptr_JetGetSessionInfo = (__vartype(ptr_JetGetSessionInfo))GetProcAddress(hModule, "JetGetSessionInfo");
   ptr_JetGetSystemParameter = (__vartype(ptr_JetGetSystemParameter))GetProcAddress(hModule, "JetGetSystemParameter");
   ptr_JetGetSystemParameterA = (__vartype(ptr_JetGetSystemParameterA))GetProcAddress(hModule, "JetGetSystemParameterA");
   ptr_JetGetSystemParameterW = (__vartype(ptr_JetGetSystemParameterW))GetProcAddress(hModule, "JetGetSystemParameterW");
   ptr_JetGetTableColumnInfo = (__vartype(ptr_JetGetTableColumnInfo))GetProcAddress(hModule, "JetGetTableColumnInfo");
   ptr_JetGetTableColumnInfoA = (__vartype(ptr_JetGetTableColumnInfoA))GetProcAddress(hModule, "JetGetTableColumnInfoA");
   ptr_JetGetTableColumnInfoW = (__vartype(ptr_JetGetTableColumnInfoW))GetProcAddress(hModule, "JetGetTableColumnInfoW");
   ptr_JetGetTableIndexInfo = (__vartype(ptr_JetGetTableIndexInfo))GetProcAddress(hModule, "JetGetTableIndexInfo");
   ptr_JetGetTableIndexInfoA = (__vartype(ptr_JetGetTableIndexInfoA))GetProcAddress(hModule, "JetGetTableIndexInfoA");
   ptr_JetGetTableIndexInfoW = (__vartype(ptr_JetGetTableIndexInfoW))GetProcAddress(hModule, "JetGetTableIndexInfoW");
   ptr_JetGetTableInfo = (__vartype(ptr_JetGetTableInfo))GetProcAddress(hModule, "JetGetTableInfo");
   ptr_JetGetTableInfoA = (__vartype(ptr_JetGetTableInfoA))GetProcAddress(hModule, "JetGetTableInfoA");
   ptr_JetGetTableInfoW = (__vartype(ptr_JetGetTableInfoW))GetProcAddress(hModule, "JetGetTableInfoW");
   ptr_JetGetThreadStats = (__vartype(ptr_JetGetThreadStats))GetProcAddress(hModule, "JetGetThreadStats");
   ptr_JetGetTruncateLogInfoInstance = (__vartype(ptr_JetGetTruncateLogInfoInstance))GetProcAddress(hModule, "JetGetTruncateLogInfoInstance");
   ptr_JetGetTruncateLogInfoInstanceA = (__vartype(ptr_JetGetTruncateLogInfoInstanceA))GetProcAddress(hModule, "JetGetTruncateLogInfoInstanceA");
   ptr_JetGetTruncateLogInfoInstanceW = (__vartype(ptr_JetGetTruncateLogInfoInstanceW))GetProcAddress(hModule, "JetGetTruncateLogInfoInstanceW");
   ptr_JetGetVersion = (__vartype(ptr_JetGetVersion))GetProcAddress(hModule, "JetGetVersion");
   ptr_JetGotoBookmark = (__vartype(ptr_JetGotoBookmark))GetProcAddress(hModule, "JetGotoBookmark");
   ptr_JetGotoPosition = (__vartype(ptr_JetGotoPosition))GetProcAddress(hModule, "JetGotoPosition");
   ptr_JetGotoSecondaryIndexBookmark = (__vartype(ptr_JetGotoSecondaryIndexBookmark))GetProcAddress(hModule, "JetGotoSecondaryIndexBookmark");
   ptr_JetGrowDatabase = (__vartype(ptr_JetGrowDatabase))GetProcAddress(hModule, "JetGrowDatabase");
   ptr_JetIdle = (__vartype(ptr_JetIdle))GetProcAddress(hModule, "JetIdle");
   ptr_JetIndexRecordCount = (__vartype(ptr_JetIndexRecordCount))GetProcAddress(hModule, "JetIndexRecordCount");
   ptr_JetInit = (__vartype(ptr_JetInit))GetProcAddress(hModule, "JetInit");
   ptr_JetInit2 = (__vartype(ptr_JetInit2))GetProcAddress(hModule, "JetInit2");
   ptr_JetInit3 = (__vartype(ptr_JetInit3))GetProcAddress(hModule, "JetInit3");
   ptr_JetInit3A = (__vartype(ptr_JetInit3A))GetProcAddress(hModule, "JetInit3A");
   ptr_JetInit3W = (__vartype(ptr_JetInit3W))GetProcAddress(hModule, "JetInit3W");
   ptr_JetIntersectIndexes = (__vartype(ptr_JetIntersectIndexes))GetProcAddress(hModule, "JetIntersectIndexes");
   ptr_JetMakeKey = (__vartype(ptr_JetMakeKey))GetProcAddress(hModule, "JetMakeKey");
   ptr_JetMove = (__vartype(ptr_JetMove))GetProcAddress(hModule, "JetMove");
   ptr_JetOSSnapshotAbort = (__vartype(ptr_JetOSSnapshotAbort))GetProcAddress(hModule, "JetOSSnapshotAbort");
   ptr_JetOSSnapshotEnd = (__vartype(ptr_JetOSSnapshotEnd))GetProcAddress(hModule, "JetOSSnapshotEnd");
   ptr_JetOSSnapshotFreeze = (__vartype(ptr_JetOSSnapshotFreeze))GetProcAddress(hModule, "JetOSSnapshotFreeze");
   ptr_JetOSSnapshotFreezeA = (__vartype(ptr_JetOSSnapshotFreezeA))GetProcAddress(hModule, "JetOSSnapshotFreezeA");
   ptr_JetOSSnapshotFreezeW = (__vartype(ptr_JetOSSnapshotFreezeW))GetProcAddress(hModule, "JetOSSnapshotFreezeW");
   ptr_JetOSSnapshotGetFreezeInfo = (__vartype(ptr_JetOSSnapshotGetFreezeInfo))GetProcAddress(hModule, "JetOSSnapshotGetFreezeInfo");
   ptr_JetOSSnapshotGetFreezeInfoA = (__vartype(ptr_JetOSSnapshotGetFreezeInfoA))GetProcAddress(hModule, "JetOSSnapshotGetFreezeInfoA");
   ptr_JetOSSnapshotGetFreezeInfoW = (__vartype(ptr_JetOSSnapshotGetFreezeInfoW))GetProcAddress(hModule, "JetOSSnapshotGetFreezeInfoW");
   ptr_JetOSSnapshotPrepare = (__vartype(ptr_JetOSSnapshotPrepare))GetProcAddress(hModule, "JetOSSnapshotPrepare");
   ptr_JetOSSnapshotPrepareInstance = (__vartype(ptr_JetOSSnapshotPrepareInstance))GetProcAddress(hModule, "JetOSSnapshotPrepareInstance");
   ptr_JetOSSnapshotThaw = (__vartype(ptr_JetOSSnapshotThaw))GetProcAddress(hModule, "JetOSSnapshotThaw");
   ptr_JetOSSnapshotTruncateLog = (__vartype(ptr_JetOSSnapshotTruncateLog))GetProcAddress(hModule, "JetOSSnapshotTruncateLog");
   ptr_JetOSSnapshotTruncateLogInstance = (__vartype(ptr_JetOSSnapshotTruncateLogInstance))GetProcAddress(hModule, "JetOSSnapshotTruncateLogInstance");
   ptr_JetOpenDatabase = (__vartype(ptr_JetOpenDatabase))GetProcAddress(hModule, "JetOpenDatabase");
   ptr_JetOpenDatabaseA = (__vartype(ptr_JetOpenDatabaseA))GetProcAddress(hModule, "JetOpenDatabaseA");
   ptr_JetOpenDatabaseW = (__vartype(ptr_JetOpenDatabaseW))GetProcAddress(hModule, "JetOpenDatabaseW");
   ptr_JetOpenFile = (__vartype(ptr_JetOpenFile))GetProcAddress(hModule, "JetOpenFile");
   ptr_JetOpenFileA = (__vartype(ptr_JetOpenFileA))GetProcAddress(hModule, "JetOpenFileA");
   ptr_JetOpenFileInstance = (__vartype(ptr_JetOpenFileInstance))GetProcAddress(hModule, "JetOpenFileInstance");
   ptr_JetOpenFileInstanceA = (__vartype(ptr_JetOpenFileInstanceA))GetProcAddress(hModule, "JetOpenFileInstanceA");
   ptr_JetOpenFileInstanceW = (__vartype(ptr_JetOpenFileInstanceW))GetProcAddress(hModule, "JetOpenFileInstanceW");
   ptr_JetOpenFileSectionInstance = (__vartype(ptr_JetOpenFileSectionInstance))GetProcAddress(hModule, "JetOpenFileSectionInstance");
   ptr_JetOpenFileSectionInstanceA = (__vartype(ptr_JetOpenFileSectionInstanceA))GetProcAddress(hModule, "JetOpenFileSectionInstanceA");
   ptr_JetOpenFileSectionInstanceW = (__vartype(ptr_JetOpenFileSectionInstanceW))GetProcAddress(hModule, "JetOpenFileSectionInstanceW");
   ptr_JetOpenFileW = (__vartype(ptr_JetOpenFileW))GetProcAddress(hModule, "JetOpenFileW");
   ptr_JetOpenTable = (__vartype(ptr_JetOpenTable))GetProcAddress(hModule, "JetOpenTable");
   ptr_JetOpenTableA = (__vartype(ptr_JetOpenTableA))GetProcAddress(hModule, "JetOpenTableA");
   ptr_JetOpenTableW = (__vartype(ptr_JetOpenTableW))GetProcAddress(hModule, "JetOpenTableW");
   ptr_JetOpenTempTable = (__vartype(ptr_JetOpenTempTable))GetProcAddress(hModule, "JetOpenTempTable");
   ptr_JetOpenTempTable2 = (__vartype(ptr_JetOpenTempTable2))GetProcAddress(hModule, "JetOpenTempTable2");
   ptr_JetOpenTempTable3 = (__vartype(ptr_JetOpenTempTable3))GetProcAddress(hModule, "JetOpenTempTable3");
   ptr_JetOpenTemporaryTable = (__vartype(ptr_JetOpenTemporaryTable))GetProcAddress(hModule, "JetOpenTemporaryTable");
   ptr_JetPatchDatabasePages = (__vartype(ptr_JetPatchDatabasePages))GetProcAddress(hModule, "JetPatchDatabasePages");
   ptr_JetPatchDatabasePagesA = (__vartype(ptr_JetPatchDatabasePagesA))GetProcAddress(hModule, "JetPatchDatabasePagesA");
   ptr_JetPatchDatabasePagesW = (__vartype(ptr_JetPatchDatabasePagesW))GetProcAddress(hModule, "JetPatchDatabasePagesW");
   ptr_JetPrepareToCommitTransaction = (__vartype(ptr_JetPrepareToCommitTransaction))GetProcAddress(hModule, "JetPrepareToCommitTransaction");
   ptr_JetPrepareUpdate = (__vartype(ptr_JetPrepareUpdate))GetProcAddress(hModule, "JetPrepareUpdate");
   ptr_JetPrereadKeys = (__vartype(ptr_JetPrereadKeys))GetProcAddress(hModule, "JetPrereadKeys");
   ptr_JetReadFile = (__vartype(ptr_JetReadFile))GetProcAddress(hModule, "JetReadFile");
   ptr_JetReadFileInstance = (__vartype(ptr_JetReadFileInstance))GetProcAddress(hModule, "JetReadFileInstance");
   ptr_JetRegisterCallback = (__vartype(ptr_JetRegisterCallback))GetProcAddress(hModule, "JetRegisterCallback");
   ptr_JetRemoveLogfileA = (__vartype(ptr_JetRemoveLogfileA))GetProcAddress(hModule, "JetRemoveLogfileA");
   ptr_JetRemoveLogfileW = (__vartype(ptr_JetRemoveLogfileW))GetProcAddress(hModule, "JetRemoveLogfileW");
   ptr_JetRenameColumn = (__vartype(ptr_JetRenameColumn))GetProcAddress(hModule, "JetRenameColumn");
   ptr_JetRenameColumnA = (__vartype(ptr_JetRenameColumnA))GetProcAddress(hModule, "JetRenameColumnA");
   ptr_JetRenameColumnW = (__vartype(ptr_JetRenameColumnW))GetProcAddress(hModule, "JetRenameColumnW");
   ptr_JetRenameTable = (__vartype(ptr_JetRenameTable))GetProcAddress(hModule, "JetRenameTable");
   ptr_JetRenameTableA = (__vartype(ptr_JetRenameTableA))GetProcAddress(hModule, "JetRenameTableA");
   ptr_JetRenameTableW = (__vartype(ptr_JetRenameTableW))GetProcAddress(hModule, "JetRenameTableW");
   ptr_JetResetCounter = (__vartype(ptr_JetResetCounter))GetProcAddress(hModule, "JetResetCounter");
   ptr_JetResetSessionContext = (__vartype(ptr_JetResetSessionContext))GetProcAddress(hModule, "JetResetSessionContext");
   ptr_JetResetTableSequential = (__vartype(ptr_JetResetTableSequential))GetProcAddress(hModule, "JetResetTableSequential");
   ptr_JetRestore = (__vartype(ptr_JetRestore))GetProcAddress(hModule, "JetRestore");
   ptr_JetRestore2 = (__vartype(ptr_JetRestore2))GetProcAddress(hModule, "JetRestore2");
   ptr_JetRestore2A = (__vartype(ptr_JetRestore2A))GetProcAddress(hModule, "JetRestore2A");
   ptr_JetRestore2W = (__vartype(ptr_JetRestore2W))GetProcAddress(hModule, "JetRestore2W");
   ptr_JetRestoreA = (__vartype(ptr_JetRestoreA))GetProcAddress(hModule, "JetRestoreA");
   ptr_JetRestoreInstance = (__vartype(ptr_JetRestoreInstance))GetProcAddress(hModule, "JetRestoreInstance");
   ptr_JetRestoreInstanceA = (__vartype(ptr_JetRestoreInstanceA))GetProcAddress(hModule, "JetRestoreInstanceA");
   ptr_JetRestoreInstanceW = (__vartype(ptr_JetRestoreInstanceW))GetProcAddress(hModule, "JetRestoreInstanceW");
   ptr_JetRestoreW = (__vartype(ptr_JetRestoreW))GetProcAddress(hModule, "JetRestoreW");
   ptr_JetRetrieveColumn = (__vartype(ptr_JetRetrieveColumn))GetProcAddress(hModule, "JetRetrieveColumn");
   ptr_JetRetrieveColumns = (__vartype(ptr_JetRetrieveColumns))GetProcAddress(hModule, "JetRetrieveColumns");
   ptr_JetRetrieveKey = (__vartype(ptr_JetRetrieveKey))GetProcAddress(hModule, "JetRetrieveKey");
   ptr_JetRetrieveTaggedColumnList = (__vartype(ptr_JetRetrieveTaggedColumnList))GetProcAddress(hModule, "JetRetrieveTaggedColumnList");
   ptr_JetRollback = (__vartype(ptr_JetRollback))GetProcAddress(hModule, "JetRollback");
   ptr_JetSeek = (__vartype(ptr_JetSeek))GetProcAddress(hModule, "JetSeek");
   ptr_JetSetColumn = (__vartype(ptr_JetSetColumn))GetProcAddress(hModule, "JetSetColumn");
   ptr_JetSetColumnDefaultValue = (__vartype(ptr_JetSetColumnDefaultValue))GetProcAddress(hModule, "JetSetColumnDefaultValue");
   ptr_JetSetColumnDefaultValueA = (__vartype(ptr_JetSetColumnDefaultValueA))GetProcAddress(hModule, "JetSetColumnDefaultValueA");
   ptr_JetSetColumnDefaultValueW = (__vartype(ptr_JetSetColumnDefaultValueW))GetProcAddress(hModule, "JetSetColumnDefaultValueW");
   ptr_JetSetColumns = (__vartype(ptr_JetSetColumns))GetProcAddress(hModule, "JetSetColumns");
   ptr_JetSetCurrentIndex = (__vartype(ptr_JetSetCurrentIndex))GetProcAddress(hModule, "JetSetCurrentIndex");
   ptr_JetSetCurrentIndex2 = (__vartype(ptr_JetSetCurrentIndex2))GetProcAddress(hModule, "JetSetCurrentIndex2");
   ptr_JetSetCurrentIndex2A = (__vartype(ptr_JetSetCurrentIndex2A))GetProcAddress(hModule, "JetSetCurrentIndex2A");
   ptr_JetSetCurrentIndex2W = (__vartype(ptr_JetSetCurrentIndex2W))GetProcAddress(hModule, "JetSetCurrentIndex2W");
   ptr_JetSetCurrentIndex3 = (__vartype(ptr_JetSetCurrentIndex3))GetProcAddress(hModule, "JetSetCurrentIndex3");
   ptr_JetSetCurrentIndex3A = (__vartype(ptr_JetSetCurrentIndex3A))GetProcAddress(hModule, "JetSetCurrentIndex3A");
   ptr_JetSetCurrentIndex3W = (__vartype(ptr_JetSetCurrentIndex3W))GetProcAddress(hModule, "JetSetCurrentIndex3W");
   ptr_JetSetCurrentIndex4 = (__vartype(ptr_JetSetCurrentIndex4))GetProcAddress(hModule, "JetSetCurrentIndex4");
   ptr_JetSetCurrentIndex4A = (__vartype(ptr_JetSetCurrentIndex4A))GetProcAddress(hModule, "JetSetCurrentIndex4A");
   ptr_JetSetCurrentIndex4W = (__vartype(ptr_JetSetCurrentIndex4W))GetProcAddress(hModule, "JetSetCurrentIndex4W");
   ptr_JetSetCurrentIndexA = (__vartype(ptr_JetSetCurrentIndexA))GetProcAddress(hModule, "JetSetCurrentIndexA");
   ptr_JetSetCurrentIndexW = (__vartype(ptr_JetSetCurrentIndexW))GetProcAddress(hModule, "JetSetCurrentIndexW");
   ptr_JetSetDatabaseSize = (__vartype(ptr_JetSetDatabaseSize))GetProcAddress(hModule, "JetSetDatabaseSize");
   ptr_JetSetDatabaseSizeA = (__vartype(ptr_JetSetDatabaseSizeA))GetProcAddress(hModule, "JetSetDatabaseSizeA");
   ptr_JetSetDatabaseSizeW = (__vartype(ptr_JetSetDatabaseSizeW))GetProcAddress(hModule, "JetSetDatabaseSizeW");
   ptr_JetSetIndexRange = (__vartype(ptr_JetSetIndexRange))GetProcAddress(hModule, "JetSetIndexRange");
   ptr_JetSetLS = (__vartype(ptr_JetSetLS))GetProcAddress(hModule, "JetSetLS");
   ptr_JetSetMaxDatabaseSize = (__vartype(ptr_JetSetMaxDatabaseSize))GetProcAddress(hModule, "JetSetMaxDatabaseSize");
   ptr_JetSetResourceParam = (__vartype(ptr_JetSetResourceParam))GetProcAddress(hModule, "JetSetResourceParam");
   ptr_JetSetSessionContext = (__vartype(ptr_JetSetSessionContext))GetProcAddress(hModule, "JetSetSessionContext");
   ptr_JetSetSystemParameter = (__vartype(ptr_JetSetSystemParameter))GetProcAddress(hModule, "JetSetSystemParameter");
   ptr_JetSetSystemParameterA = (__vartype(ptr_JetSetSystemParameterA))GetProcAddress(hModule, "JetSetSystemParameterA");
   ptr_JetSetSystemParameterW = (__vartype(ptr_JetSetSystemParameterW))GetProcAddress(hModule, "JetSetSystemParameterW");
   ptr_JetSetTableSequential = (__vartype(ptr_JetSetTableSequential))GetProcAddress(hModule, "JetSetTableSequential");
   ptr_JetSnapshotStart = (__vartype(ptr_JetSnapshotStart))GetProcAddress(hModule, "JetSnapshotStart");
   ptr_JetSnapshotStartA = (__vartype(ptr_JetSnapshotStartA))GetProcAddress(hModule, "JetSnapshotStartA");
   ptr_JetSnapshotStartW = (__vartype(ptr_JetSnapshotStartW))GetProcAddress(hModule, "JetSnapshotStartW");
   ptr_JetSnapshotStop = (__vartype(ptr_JetSnapshotStop))GetProcAddress(hModule, "JetSnapshotStop");
   ptr_JetStopBackup = (__vartype(ptr_JetStopBackup))GetProcAddress(hModule, "JetStopBackup");
   ptr_JetStopBackupInstance = (__vartype(ptr_JetStopBackupInstance))GetProcAddress(hModule, "JetStopBackupInstance");
   ptr_JetStopService = (__vartype(ptr_JetStopService))GetProcAddress(hModule, "JetStopService");
   ptr_JetStopServiceInstance = (__vartype(ptr_JetStopServiceInstance))GetProcAddress(hModule, "JetStopServiceInstance");
   ptr_JetTerm = (__vartype(ptr_JetTerm))GetProcAddress(hModule, "JetTerm");
   ptr_JetTerm2 = (__vartype(ptr_JetTerm2))GetProcAddress(hModule, "JetTerm2");
   ptr_JetTest = (__vartype(ptr_JetTest))GetProcAddress(hModule, "JetTest");
   ptr_JetTracing = (__vartype(ptr_JetTracing))GetProcAddress(hModule, "JetTracing");
   ptr_JetTruncateLog = (__vartype(ptr_JetTruncateLog))GetProcAddress(hModule, "JetTruncateLog");
   ptr_JetTruncateLogInstance = (__vartype(ptr_JetTruncateLogInstance))GetProcAddress(hModule, "JetTruncateLogInstance");
   ptr_JetUnregisterCallback = (__vartype(ptr_JetUnregisterCallback))GetProcAddress(hModule, "JetUnregisterCallback");
   ptr_JetUpdate = (__vartype(ptr_JetUpdate))GetProcAddress(hModule, "JetUpdate");
   ptr_JetUpdate2 = (__vartype(ptr_JetUpdate2))GetProcAddress(hModule, "JetUpdate2");
   ptr_JetUpgradeDatabase = (__vartype(ptr_JetUpgradeDatabase))GetProcAddress(hModule, "JetUpgradeDatabase");
   ptr_JetUpgradeDatabaseA = (__vartype(ptr_JetUpgradeDatabaseA))GetProcAddress(hModule, "JetUpgradeDatabaseA");
   ptr_JetUpgradeDatabaseW = (__vartype(ptr_JetUpgradeDatabaseW))GetProcAddress(hModule, "JetUpgradeDatabaseW");
   ptr_ese = (__vartype(ptr_ese))GetProcAddress(hModule, "ese");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

