#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_ClearPropVariantArray;
void *ptr_ClearPropVariantArray = NULL;
extern void *ptr_ClearVariantArray;
void *ptr_ClearVariantArray = NULL;
extern void *ptr_DllCanUnloadNow;
void *ptr_DllCanUnloadNow = NULL;
extern void *ptr_DllGetClassObject;
void *ptr_DllGetClassObject = NULL;
extern void *ptr_DllRegisterServer;
void *ptr_DllRegisterServer = NULL;
extern void *ptr_DllUnregisterServer;
void *ptr_DllUnregisterServer = NULL;
extern void *ptr_GetProxyDllInfo;
void *ptr_GetProxyDllInfo = NULL;
extern void *ptr_InitPropVariantFromBooleanVector;
void *ptr_InitPropVariantFromBooleanVector = NULL;
extern void *ptr_InitPropVariantFromBuffer;
void *ptr_InitPropVariantFromBuffer = NULL;
extern void *ptr_InitPropVariantFromCLSID;
void *ptr_InitPropVariantFromCLSID = NULL;
extern void *ptr_InitPropVariantFromDoubleVector;
void *ptr_InitPropVariantFromDoubleVector = NULL;
extern void *ptr_InitPropVariantFromFileTime;
void *ptr_InitPropVariantFromFileTime = NULL;
extern void *ptr_InitPropVariantFromFileTimeVector;
void *ptr_InitPropVariantFromFileTimeVector = NULL;
extern void *ptr_InitPropVariantFromGUIDAsString;
void *ptr_InitPropVariantFromGUIDAsString = NULL;
extern void *ptr_InitPropVariantFromInt16Vector;
void *ptr_InitPropVariantFromInt16Vector = NULL;
extern void *ptr_InitPropVariantFromInt32Vector;
void *ptr_InitPropVariantFromInt32Vector = NULL;
extern void *ptr_InitPropVariantFromInt64Vector;
void *ptr_InitPropVariantFromInt64Vector = NULL;
extern void *ptr_InitPropVariantFromPropVariantVectorElem;
void *ptr_InitPropVariantFromPropVariantVectorElem = NULL;
extern void *ptr_InitPropVariantFromResource;
void *ptr_InitPropVariantFromResource = NULL;
extern void *ptr_InitPropVariantFromStrRet;
void *ptr_InitPropVariantFromStrRet = NULL;
extern void *ptr_InitPropVariantFromStringAsVector;
void *ptr_InitPropVariantFromStringAsVector = NULL;
extern void *ptr_InitPropVariantFromStringVector;
void *ptr_InitPropVariantFromStringVector = NULL;
extern void *ptr_InitPropVariantFromUInt16Vector;
void *ptr_InitPropVariantFromUInt16Vector = NULL;
extern void *ptr_InitPropVariantFromUInt32Vector;
void *ptr_InitPropVariantFromUInt32Vector = NULL;
extern void *ptr_InitPropVariantFromUInt64Vector;
void *ptr_InitPropVariantFromUInt64Vector = NULL;
extern void *ptr_InitPropVariantVectorFromPropVariant;
void *ptr_InitPropVariantVectorFromPropVariant = NULL;
extern void *ptr_InitVariantFromBooleanArray;
void *ptr_InitVariantFromBooleanArray = NULL;
extern void *ptr_InitVariantFromBuffer;
void *ptr_InitVariantFromBuffer = NULL;
extern void *ptr_InitVariantFromDoubleArray;
void *ptr_InitVariantFromDoubleArray = NULL;
extern void *ptr_InitVariantFromFileTime;
void *ptr_InitVariantFromFileTime = NULL;
extern void *ptr_InitVariantFromFileTimeArray;
void *ptr_InitVariantFromFileTimeArray = NULL;
extern void *ptr_InitVariantFromGUIDAsString;
void *ptr_InitVariantFromGUIDAsString = NULL;
extern void *ptr_InitVariantFromInt16Array;
void *ptr_InitVariantFromInt16Array = NULL;
extern void *ptr_InitVariantFromInt32Array;
void *ptr_InitVariantFromInt32Array = NULL;
extern void *ptr_InitVariantFromInt64Array;
void *ptr_InitVariantFromInt64Array = NULL;
extern void *ptr_InitVariantFromResource;
void *ptr_InitVariantFromResource = NULL;
extern void *ptr_InitVariantFromStrRet;
void *ptr_InitVariantFromStrRet = NULL;
extern void *ptr_InitVariantFromStringArray;
void *ptr_InitVariantFromStringArray = NULL;
extern void *ptr_InitVariantFromUInt16Array;
void *ptr_InitVariantFromUInt16Array = NULL;
extern void *ptr_InitVariantFromUInt32Array;
void *ptr_InitVariantFromUInt32Array = NULL;
extern void *ptr_InitVariantFromUInt64Array;
void *ptr_InitVariantFromUInt64Array = NULL;
extern void *ptr_InitVariantFromVariantArrayElem;
void *ptr_InitVariantFromVariantArrayElem = NULL;
extern void *ptr_PSCoerceToCanonicalValue;
void *ptr_PSCoerceToCanonicalValue = NULL;
extern void *ptr_PSCreateAdapterFromPropertyStore;
void *ptr_PSCreateAdapterFromPropertyStore = NULL;
extern void *ptr_PSCreateDelayedMultiplexPropertyStore;
void *ptr_PSCreateDelayedMultiplexPropertyStore = NULL;
extern void *ptr_PSCreateMemoryPropertyStore;
void *ptr_PSCreateMemoryPropertyStore = NULL;
extern void *ptr_PSCreateMultiplexPropertyStore;
void *ptr_PSCreateMultiplexPropertyStore = NULL;
extern void *ptr_PSCreatePropertyChangeArray;
void *ptr_PSCreatePropertyChangeArray = NULL;
extern void *ptr_PSCreatePropertyStoreFromObject;
void *ptr_PSCreatePropertyStoreFromObject = NULL;
extern void *ptr_PSCreatePropertyStoreFromPropertySetStorage;
void *ptr_PSCreatePropertyStoreFromPropertySetStorage = NULL;
extern void *ptr_PSCreateSimplePropertyChange;
void *ptr_PSCreateSimplePropertyChange = NULL;
extern void *ptr_PSEnumeratePropertyDescriptions;
void *ptr_PSEnumeratePropertyDescriptions = NULL;
extern void *ptr_PSFormatForDisplay;
void *ptr_PSFormatForDisplay = NULL;
extern void *ptr_PSFormatForDisplayAlloc;
void *ptr_PSFormatForDisplayAlloc = NULL;
extern void *ptr_PSFormatPropertyValue;
void *ptr_PSFormatPropertyValue = NULL;
extern void *ptr_PSGetImageReferenceForValue;
void *ptr_PSGetImageReferenceForValue = NULL;
extern void *ptr_PSGetItemPropertyHandler;
void *ptr_PSGetItemPropertyHandler = NULL;
extern void *ptr_PSGetItemPropertyHandlerWithCreateObject;
void *ptr_PSGetItemPropertyHandlerWithCreateObject = NULL;
extern void *ptr_PSGetNameFromPropertyKey;
void *ptr_PSGetNameFromPropertyKey = NULL;
extern void *ptr_PSGetNamedPropertyFromPropertyStorage;
void *ptr_PSGetNamedPropertyFromPropertyStorage = NULL;
extern void *ptr_PSGetPropertyDescription;
void *ptr_PSGetPropertyDescription = NULL;
extern void *ptr_PSGetPropertyDescriptionByName;
void *ptr_PSGetPropertyDescriptionByName = NULL;
extern void *ptr_PSGetPropertyDescriptionListFromString;
void *ptr_PSGetPropertyDescriptionListFromString = NULL;
extern void *ptr_PSGetPropertyFromPropertyStorage;
void *ptr_PSGetPropertyFromPropertyStorage = NULL;
extern void *ptr_PSGetPropertyKeyFromName;
void *ptr_PSGetPropertyKeyFromName = NULL;
extern void *ptr_PSGetPropertySystem;
void *ptr_PSGetPropertySystem = NULL;
extern void *ptr_PSGetPropertyValue;
void *ptr_PSGetPropertyValue = NULL;
extern void *ptr_PSLookupPropertyHandlerCLSID;
void *ptr_PSLookupPropertyHandlerCLSID = NULL;
extern void *ptr_PSPropertyBag_Delete;
void *ptr_PSPropertyBag_Delete = NULL;
extern void *ptr_PSPropertyBag_ReadBOOL;
void *ptr_PSPropertyBag_ReadBOOL = NULL;
extern void *ptr_PSPropertyBag_ReadBSTR;
void *ptr_PSPropertyBag_ReadBSTR = NULL;
extern void *ptr_PSPropertyBag_ReadDWORD;
void *ptr_PSPropertyBag_ReadDWORD = NULL;
extern void *ptr_PSPropertyBag_ReadGUID;
void *ptr_PSPropertyBag_ReadGUID = NULL;
extern void *ptr_PSPropertyBag_ReadInt;
void *ptr_PSPropertyBag_ReadInt = NULL;
extern void *ptr_PSPropertyBag_ReadLONG;
void *ptr_PSPropertyBag_ReadLONG = NULL;
extern void *ptr_PSPropertyBag_ReadPOINTL;
void *ptr_PSPropertyBag_ReadPOINTL = NULL;
extern void *ptr_PSPropertyBag_ReadPOINTS;
void *ptr_PSPropertyBag_ReadPOINTS = NULL;
extern void *ptr_PSPropertyBag_ReadPropertyKey;
void *ptr_PSPropertyBag_ReadPropertyKey = NULL;
extern void *ptr_PSPropertyBag_ReadRECTL;
void *ptr_PSPropertyBag_ReadRECTL = NULL;
extern void *ptr_PSPropertyBag_ReadSHORT;
void *ptr_PSPropertyBag_ReadSHORT = NULL;
extern void *ptr_PSPropertyBag_ReadStr;
void *ptr_PSPropertyBag_ReadStr = NULL;
extern void *ptr_PSPropertyBag_ReadStrAlloc;
void *ptr_PSPropertyBag_ReadStrAlloc = NULL;
extern void *ptr_PSPropertyBag_ReadStream;
void *ptr_PSPropertyBag_ReadStream = NULL;
extern void *ptr_PSPropertyBag_ReadType;
void *ptr_PSPropertyBag_ReadType = NULL;
extern void *ptr_PSPropertyBag_ReadULONGLONG;
void *ptr_PSPropertyBag_ReadULONGLONG = NULL;
extern void *ptr_PSPropertyBag_ReadUnknown;
void *ptr_PSPropertyBag_ReadUnknown = NULL;
extern void *ptr_PSPropertyBag_WriteBOOL;
void *ptr_PSPropertyBag_WriteBOOL = NULL;
extern void *ptr_PSPropertyBag_WriteBSTR;
void *ptr_PSPropertyBag_WriteBSTR = NULL;
extern void *ptr_PSPropertyBag_WriteDWORD;
void *ptr_PSPropertyBag_WriteDWORD = NULL;
extern void *ptr_PSPropertyBag_WriteGUID;
void *ptr_PSPropertyBag_WriteGUID = NULL;
extern void *ptr_PSPropertyBag_WriteInt;
void *ptr_PSPropertyBag_WriteInt = NULL;
extern void *ptr_PSPropertyBag_WriteLONG;
void *ptr_PSPropertyBag_WriteLONG = NULL;
extern void *ptr_PSPropertyBag_WritePOINTL;
void *ptr_PSPropertyBag_WritePOINTL = NULL;
extern void *ptr_PSPropertyBag_WritePOINTS;
void *ptr_PSPropertyBag_WritePOINTS = NULL;
extern void *ptr_PSPropertyBag_WritePropertyKey;
void *ptr_PSPropertyBag_WritePropertyKey = NULL;
extern void *ptr_PSPropertyBag_WriteRECTL;
void *ptr_PSPropertyBag_WriteRECTL = NULL;
extern void *ptr_PSPropertyBag_WriteSHORT;
void *ptr_PSPropertyBag_WriteSHORT = NULL;
extern void *ptr_PSPropertyBag_WriteStr;
void *ptr_PSPropertyBag_WriteStr = NULL;
extern void *ptr_PSPropertyBag_WriteStream;
void *ptr_PSPropertyBag_WriteStream = NULL;
extern void *ptr_PSPropertyBag_WriteULONGLONG;
void *ptr_PSPropertyBag_WriteULONGLONG = NULL;
extern void *ptr_PSPropertyBag_WriteUnknown;
void *ptr_PSPropertyBag_WriteUnknown = NULL;
extern void *ptr_PSPropertyKeyFromString;
void *ptr_PSPropertyKeyFromString = NULL;
extern void *ptr_PSRefreshPropertySchema;
void *ptr_PSRefreshPropertySchema = NULL;
extern void *ptr_PSRegisterPropertySchema;
void *ptr_PSRegisterPropertySchema = NULL;
extern void *ptr_PSSetPropertyValue;
void *ptr_PSSetPropertyValue = NULL;
extern void *ptr_PSStringFromPropertyKey;
void *ptr_PSStringFromPropertyKey = NULL;
extern void *ptr_PSUnregisterPropertySchema;
void *ptr_PSUnregisterPropertySchema = NULL;
extern void *ptr_PropVariantChangeType;
void *ptr_PropVariantChangeType = NULL;
extern void *ptr_PropVariantCompareEx;
void *ptr_PropVariantCompareEx = NULL;
extern void *ptr_PropVariantGetBooleanElem;
void *ptr_PropVariantGetBooleanElem = NULL;
extern void *ptr_PropVariantGetDoubleElem;
void *ptr_PropVariantGetDoubleElem = NULL;
extern void *ptr_PropVariantGetElementCount;
void *ptr_PropVariantGetElementCount = NULL;
extern void *ptr_PropVariantGetFileTimeElem;
void *ptr_PropVariantGetFileTimeElem = NULL;
extern void *ptr_PropVariantGetInt16Elem;
void *ptr_PropVariantGetInt16Elem = NULL;
extern void *ptr_PropVariantGetInt32Elem;
void *ptr_PropVariantGetInt32Elem = NULL;
extern void *ptr_PropVariantGetInt64Elem;
void *ptr_PropVariantGetInt64Elem = NULL;
extern void *ptr_PropVariantGetStringElem;
void *ptr_PropVariantGetStringElem = NULL;
extern void *ptr_PropVariantGetUInt16Elem;
void *ptr_PropVariantGetUInt16Elem = NULL;
extern void *ptr_PropVariantGetUInt32Elem;
void *ptr_PropVariantGetUInt32Elem = NULL;
extern void *ptr_PropVariantGetUInt64Elem;
void *ptr_PropVariantGetUInt64Elem = NULL;
extern void *ptr_PropVariantToBSTR;
void *ptr_PropVariantToBSTR = NULL;
extern void *ptr_PropVariantToBoolean;
void *ptr_PropVariantToBoolean = NULL;
extern void *ptr_PropVariantToBooleanVector;
void *ptr_PropVariantToBooleanVector = NULL;
extern void *ptr_PropVariantToBooleanVectorAlloc;
void *ptr_PropVariantToBooleanVectorAlloc = NULL;
extern void *ptr_PropVariantToBooleanWithDefault;
void *ptr_PropVariantToBooleanWithDefault = NULL;
extern void *ptr_PropVariantToBuffer;
void *ptr_PropVariantToBuffer = NULL;
extern void *ptr_PropVariantToDouble;
void *ptr_PropVariantToDouble = NULL;
extern void *ptr_PropVariantToDoubleVector;
void *ptr_PropVariantToDoubleVector = NULL;
extern void *ptr_PropVariantToDoubleVectorAlloc;
void *ptr_PropVariantToDoubleVectorAlloc = NULL;
extern void *ptr_PropVariantToDoubleWithDefault;
void *ptr_PropVariantToDoubleWithDefault = NULL;
extern void *ptr_PropVariantToFileTime;
void *ptr_PropVariantToFileTime = NULL;
extern void *ptr_PropVariantToFileTimeVector;
void *ptr_PropVariantToFileTimeVector = NULL;
extern void *ptr_PropVariantToFileTimeVectorAlloc;
void *ptr_PropVariantToFileTimeVectorAlloc = NULL;
extern void *ptr_PropVariantToGUID;
void *ptr_PropVariantToGUID = NULL;
extern void *ptr_PropVariantToInt16;
void *ptr_PropVariantToInt16 = NULL;
extern void *ptr_PropVariantToInt16Vector;
void *ptr_PropVariantToInt16Vector = NULL;
extern void *ptr_PropVariantToInt16VectorAlloc;
void *ptr_PropVariantToInt16VectorAlloc = NULL;
extern void *ptr_PropVariantToInt16WithDefault;
void *ptr_PropVariantToInt16WithDefault = NULL;
extern void *ptr_PropVariantToInt32;
void *ptr_PropVariantToInt32 = NULL;
extern void *ptr_PropVariantToInt32Vector;
void *ptr_PropVariantToInt32Vector = NULL;
extern void *ptr_PropVariantToInt32VectorAlloc;
void *ptr_PropVariantToInt32VectorAlloc = NULL;
extern void *ptr_PropVariantToInt32WithDefault;
void *ptr_PropVariantToInt32WithDefault = NULL;
extern void *ptr_PropVariantToInt64;
void *ptr_PropVariantToInt64 = NULL;
extern void *ptr_PropVariantToInt64Vector;
void *ptr_PropVariantToInt64Vector = NULL;
extern void *ptr_PropVariantToInt64VectorAlloc;
void *ptr_PropVariantToInt64VectorAlloc = NULL;
extern void *ptr_PropVariantToInt64WithDefault;
void *ptr_PropVariantToInt64WithDefault = NULL;
extern void *ptr_PropVariantToStrRet;
void *ptr_PropVariantToStrRet = NULL;
extern void *ptr_PropVariantToString;
void *ptr_PropVariantToString = NULL;
extern void *ptr_PropVariantToStringAlloc;
void *ptr_PropVariantToStringAlloc = NULL;
extern void *ptr_PropVariantToStringVector;
void *ptr_PropVariantToStringVector = NULL;
extern void *ptr_PropVariantToStringVectorAlloc;
void *ptr_PropVariantToStringVectorAlloc = NULL;
extern void *ptr_PropVariantToStringWithDefault;
void *ptr_PropVariantToStringWithDefault = NULL;
extern void *ptr_PropVariantToUInt16;
void *ptr_PropVariantToUInt16 = NULL;
extern void *ptr_PropVariantToUInt16Vector;
void *ptr_PropVariantToUInt16Vector = NULL;
extern void *ptr_PropVariantToUInt16VectorAlloc;
void *ptr_PropVariantToUInt16VectorAlloc = NULL;
extern void *ptr_PropVariantToUInt16WithDefault;
void *ptr_PropVariantToUInt16WithDefault = NULL;
extern void *ptr_PropVariantToUInt32;
void *ptr_PropVariantToUInt32 = NULL;
extern void *ptr_PropVariantToUInt32Vector;
void *ptr_PropVariantToUInt32Vector = NULL;
extern void *ptr_PropVariantToUInt32VectorAlloc;
void *ptr_PropVariantToUInt32VectorAlloc = NULL;
extern void *ptr_PropVariantToUInt32WithDefault;
void *ptr_PropVariantToUInt32WithDefault = NULL;
extern void *ptr_PropVariantToUInt64;
void *ptr_PropVariantToUInt64 = NULL;
extern void *ptr_PropVariantToUInt64Vector;
void *ptr_PropVariantToUInt64Vector = NULL;
extern void *ptr_PropVariantToUInt64VectorAlloc;
void *ptr_PropVariantToUInt64VectorAlloc = NULL;
extern void *ptr_PropVariantToUInt64WithDefault;
void *ptr_PropVariantToUInt64WithDefault = NULL;
extern void *ptr_PropVariantToVariant;
void *ptr_PropVariantToVariant = NULL;
extern void *ptr_StgDeserializePropVariant;
void *ptr_StgDeserializePropVariant = NULL;
extern void *ptr_StgSerializePropVariant;
void *ptr_StgSerializePropVariant = NULL;
extern void *ptr_VariantCompare;
void *ptr_VariantCompare = NULL;
extern void *ptr_VariantGetBooleanElem;
void *ptr_VariantGetBooleanElem = NULL;
extern void *ptr_VariantGetDoubleElem;
void *ptr_VariantGetDoubleElem = NULL;
extern void *ptr_VariantGetElementCount;
void *ptr_VariantGetElementCount = NULL;
extern void *ptr_VariantGetInt16Elem;
void *ptr_VariantGetInt16Elem = NULL;
extern void *ptr_VariantGetInt32Elem;
void *ptr_VariantGetInt32Elem = NULL;
extern void *ptr_VariantGetInt64Elem;
void *ptr_VariantGetInt64Elem = NULL;
extern void *ptr_VariantGetStringElem;
void *ptr_VariantGetStringElem = NULL;
extern void *ptr_VariantGetUInt16Elem;
void *ptr_VariantGetUInt16Elem = NULL;
extern void *ptr_VariantGetUInt32Elem;
void *ptr_VariantGetUInt32Elem = NULL;
extern void *ptr_VariantGetUInt64Elem;
void *ptr_VariantGetUInt64Elem = NULL;
extern void *ptr_VariantToBoolean;
void *ptr_VariantToBoolean = NULL;
extern void *ptr_VariantToBooleanArray;
void *ptr_VariantToBooleanArray = NULL;
extern void *ptr_VariantToBooleanArrayAlloc;
void *ptr_VariantToBooleanArrayAlloc = NULL;
extern void *ptr_VariantToBooleanWithDefault;
void *ptr_VariantToBooleanWithDefault = NULL;
extern void *ptr_VariantToBuffer;
void *ptr_VariantToBuffer = NULL;
extern void *ptr_VariantToDosDateTime;
void *ptr_VariantToDosDateTime = NULL;
extern void *ptr_VariantToDouble;
void *ptr_VariantToDouble = NULL;
extern void *ptr_VariantToDoubleArray;
void *ptr_VariantToDoubleArray = NULL;
extern void *ptr_VariantToDoubleArrayAlloc;
void *ptr_VariantToDoubleArrayAlloc = NULL;
extern void *ptr_VariantToDoubleWithDefault;
void *ptr_VariantToDoubleWithDefault = NULL;
extern void *ptr_VariantToFileTime;
void *ptr_VariantToFileTime = NULL;
extern void *ptr_VariantToGUID;
void *ptr_VariantToGUID = NULL;
extern void *ptr_VariantToInt16;
void *ptr_VariantToInt16 = NULL;
extern void *ptr_VariantToInt16Array;
void *ptr_VariantToInt16Array = NULL;
extern void *ptr_VariantToInt16ArrayAlloc;
void *ptr_VariantToInt16ArrayAlloc = NULL;
extern void *ptr_VariantToInt16WithDefault;
void *ptr_VariantToInt16WithDefault = NULL;
extern void *ptr_VariantToInt32;
void *ptr_VariantToInt32 = NULL;
extern void *ptr_VariantToInt32Array;
void *ptr_VariantToInt32Array = NULL;
extern void *ptr_VariantToInt32ArrayAlloc;
void *ptr_VariantToInt32ArrayAlloc = NULL;
extern void *ptr_VariantToInt32WithDefault;
void *ptr_VariantToInt32WithDefault = NULL;
extern void *ptr_VariantToInt64;
void *ptr_VariantToInt64 = NULL;
extern void *ptr_VariantToInt64Array;
void *ptr_VariantToInt64Array = NULL;
extern void *ptr_VariantToInt64ArrayAlloc;
void *ptr_VariantToInt64ArrayAlloc = NULL;
extern void *ptr_VariantToInt64WithDefault;
void *ptr_VariantToInt64WithDefault = NULL;
extern void *ptr_VariantToPropVariant;
void *ptr_VariantToPropVariant = NULL;
extern void *ptr_VariantToStrRet;
void *ptr_VariantToStrRet = NULL;
extern void *ptr_VariantToString;
void *ptr_VariantToString = NULL;
extern void *ptr_VariantToStringAlloc;
void *ptr_VariantToStringAlloc = NULL;
extern void *ptr_VariantToStringArray;
void *ptr_VariantToStringArray = NULL;
extern void *ptr_VariantToStringArrayAlloc;
void *ptr_VariantToStringArrayAlloc = NULL;
extern void *ptr_VariantToStringWithDefault;
void *ptr_VariantToStringWithDefault = NULL;
extern void *ptr_VariantToUInt16;
void *ptr_VariantToUInt16 = NULL;
extern void *ptr_VariantToUInt16Array;
void *ptr_VariantToUInt16Array = NULL;
extern void *ptr_VariantToUInt16ArrayAlloc;
void *ptr_VariantToUInt16ArrayAlloc = NULL;
extern void *ptr_VariantToUInt16WithDefault;
void *ptr_VariantToUInt16WithDefault = NULL;
extern void *ptr_VariantToUInt32;
void *ptr_VariantToUInt32 = NULL;
extern void *ptr_VariantToUInt32Array;
void *ptr_VariantToUInt32Array = NULL;
extern void *ptr_VariantToUInt32ArrayAlloc;
void *ptr_VariantToUInt32ArrayAlloc = NULL;
extern void *ptr_VariantToUInt32WithDefault;
void *ptr_VariantToUInt32WithDefault = NULL;
extern void *ptr_VariantToUInt64;
void *ptr_VariantToUInt64 = NULL;
extern void *ptr_VariantToUInt64Array;
void *ptr_VariantToUInt64Array = NULL;
extern void *ptr_VariantToUInt64ArrayAlloc;
void *ptr_VariantToUInt64ArrayAlloc = NULL;
extern void *ptr_VariantToUInt64WithDefault;
void *ptr_VariantToUInt64WithDefault = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\propsys.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_ClearPropVariantArray = (__vartype(ptr_ClearPropVariantArray))GetProcAddress(hModule, "ClearPropVariantArray");
   ptr_ClearVariantArray = (__vartype(ptr_ClearVariantArray))GetProcAddress(hModule, "ClearVariantArray");
   ptr_DllCanUnloadNow = (__vartype(ptr_DllCanUnloadNow))GetProcAddress(hModule, "DllCanUnloadNow");
   ptr_DllGetClassObject = (__vartype(ptr_DllGetClassObject))GetProcAddress(hModule, "DllGetClassObject");
   ptr_DllRegisterServer = (__vartype(ptr_DllRegisterServer))GetProcAddress(hModule, "DllRegisterServer");
   ptr_DllUnregisterServer = (__vartype(ptr_DllUnregisterServer))GetProcAddress(hModule, "DllUnregisterServer");
   ptr_GetProxyDllInfo = (__vartype(ptr_GetProxyDllInfo))GetProcAddress(hModule, "GetProxyDllInfo");
   ptr_InitPropVariantFromBooleanVector = (__vartype(ptr_InitPropVariantFromBooleanVector))GetProcAddress(hModule, "InitPropVariantFromBooleanVector");
   ptr_InitPropVariantFromBuffer = (__vartype(ptr_InitPropVariantFromBuffer))GetProcAddress(hModule, "InitPropVariantFromBuffer");
   ptr_InitPropVariantFromCLSID = (__vartype(ptr_InitPropVariantFromCLSID))GetProcAddress(hModule, "InitPropVariantFromCLSID");
   ptr_InitPropVariantFromDoubleVector = (__vartype(ptr_InitPropVariantFromDoubleVector))GetProcAddress(hModule, "InitPropVariantFromDoubleVector");
   ptr_InitPropVariantFromFileTime = (__vartype(ptr_InitPropVariantFromFileTime))GetProcAddress(hModule, "InitPropVariantFromFileTime");
   ptr_InitPropVariantFromFileTimeVector = (__vartype(ptr_InitPropVariantFromFileTimeVector))GetProcAddress(hModule, "InitPropVariantFromFileTimeVector");
   ptr_InitPropVariantFromGUIDAsString = (__vartype(ptr_InitPropVariantFromGUIDAsString))GetProcAddress(hModule, "InitPropVariantFromGUIDAsString");
   ptr_InitPropVariantFromInt16Vector = (__vartype(ptr_InitPropVariantFromInt16Vector))GetProcAddress(hModule, "InitPropVariantFromInt16Vector");
   ptr_InitPropVariantFromInt32Vector = (__vartype(ptr_InitPropVariantFromInt32Vector))GetProcAddress(hModule, "InitPropVariantFromInt32Vector");
   ptr_InitPropVariantFromInt64Vector = (__vartype(ptr_InitPropVariantFromInt64Vector))GetProcAddress(hModule, "InitPropVariantFromInt64Vector");
   ptr_InitPropVariantFromPropVariantVectorElem = (__vartype(ptr_InitPropVariantFromPropVariantVectorElem))GetProcAddress(hModule, "InitPropVariantFromPropVariantVectorElem");
   ptr_InitPropVariantFromResource = (__vartype(ptr_InitPropVariantFromResource))GetProcAddress(hModule, "InitPropVariantFromResource");
   ptr_InitPropVariantFromStrRet = (__vartype(ptr_InitPropVariantFromStrRet))GetProcAddress(hModule, "InitPropVariantFromStrRet");
   ptr_InitPropVariantFromStringAsVector = (__vartype(ptr_InitPropVariantFromStringAsVector))GetProcAddress(hModule, "InitPropVariantFromStringAsVector");
   ptr_InitPropVariantFromStringVector = (__vartype(ptr_InitPropVariantFromStringVector))GetProcAddress(hModule, "InitPropVariantFromStringVector");
   ptr_InitPropVariantFromUInt16Vector = (__vartype(ptr_InitPropVariantFromUInt16Vector))GetProcAddress(hModule, "InitPropVariantFromUInt16Vector");
   ptr_InitPropVariantFromUInt32Vector = (__vartype(ptr_InitPropVariantFromUInt32Vector))GetProcAddress(hModule, "InitPropVariantFromUInt32Vector");
   ptr_InitPropVariantFromUInt64Vector = (__vartype(ptr_InitPropVariantFromUInt64Vector))GetProcAddress(hModule, "InitPropVariantFromUInt64Vector");
   ptr_InitPropVariantVectorFromPropVariant = (__vartype(ptr_InitPropVariantVectorFromPropVariant))GetProcAddress(hModule, "InitPropVariantVectorFromPropVariant");
   ptr_InitVariantFromBooleanArray = (__vartype(ptr_InitVariantFromBooleanArray))GetProcAddress(hModule, "InitVariantFromBooleanArray");
   ptr_InitVariantFromBuffer = (__vartype(ptr_InitVariantFromBuffer))GetProcAddress(hModule, "InitVariantFromBuffer");
   ptr_InitVariantFromDoubleArray = (__vartype(ptr_InitVariantFromDoubleArray))GetProcAddress(hModule, "InitVariantFromDoubleArray");
   ptr_InitVariantFromFileTime = (__vartype(ptr_InitVariantFromFileTime))GetProcAddress(hModule, "InitVariantFromFileTime");
   ptr_InitVariantFromFileTimeArray = (__vartype(ptr_InitVariantFromFileTimeArray))GetProcAddress(hModule, "InitVariantFromFileTimeArray");
   ptr_InitVariantFromGUIDAsString = (__vartype(ptr_InitVariantFromGUIDAsString))GetProcAddress(hModule, "InitVariantFromGUIDAsString");
   ptr_InitVariantFromInt16Array = (__vartype(ptr_InitVariantFromInt16Array))GetProcAddress(hModule, "InitVariantFromInt16Array");
   ptr_InitVariantFromInt32Array = (__vartype(ptr_InitVariantFromInt32Array))GetProcAddress(hModule, "InitVariantFromInt32Array");
   ptr_InitVariantFromInt64Array = (__vartype(ptr_InitVariantFromInt64Array))GetProcAddress(hModule, "InitVariantFromInt64Array");
   ptr_InitVariantFromResource = (__vartype(ptr_InitVariantFromResource))GetProcAddress(hModule, "InitVariantFromResource");
   ptr_InitVariantFromStrRet = (__vartype(ptr_InitVariantFromStrRet))GetProcAddress(hModule, "InitVariantFromStrRet");
   ptr_InitVariantFromStringArray = (__vartype(ptr_InitVariantFromStringArray))GetProcAddress(hModule, "InitVariantFromStringArray");
   ptr_InitVariantFromUInt16Array = (__vartype(ptr_InitVariantFromUInt16Array))GetProcAddress(hModule, "InitVariantFromUInt16Array");
   ptr_InitVariantFromUInt32Array = (__vartype(ptr_InitVariantFromUInt32Array))GetProcAddress(hModule, "InitVariantFromUInt32Array");
   ptr_InitVariantFromUInt64Array = (__vartype(ptr_InitVariantFromUInt64Array))GetProcAddress(hModule, "InitVariantFromUInt64Array");
   ptr_InitVariantFromVariantArrayElem = (__vartype(ptr_InitVariantFromVariantArrayElem))GetProcAddress(hModule, "InitVariantFromVariantArrayElem");
   ptr_PSCoerceToCanonicalValue = (__vartype(ptr_PSCoerceToCanonicalValue))GetProcAddress(hModule, "PSCoerceToCanonicalValue");
   ptr_PSCreateAdapterFromPropertyStore = (__vartype(ptr_PSCreateAdapterFromPropertyStore))GetProcAddress(hModule, "PSCreateAdapterFromPropertyStore");
   ptr_PSCreateDelayedMultiplexPropertyStore = (__vartype(ptr_PSCreateDelayedMultiplexPropertyStore))GetProcAddress(hModule, "PSCreateDelayedMultiplexPropertyStore");
   ptr_PSCreateMemoryPropertyStore = (__vartype(ptr_PSCreateMemoryPropertyStore))GetProcAddress(hModule, "PSCreateMemoryPropertyStore");
   ptr_PSCreateMultiplexPropertyStore = (__vartype(ptr_PSCreateMultiplexPropertyStore))GetProcAddress(hModule, "PSCreateMultiplexPropertyStore");
   ptr_PSCreatePropertyChangeArray = (__vartype(ptr_PSCreatePropertyChangeArray))GetProcAddress(hModule, "PSCreatePropertyChangeArray");
   ptr_PSCreatePropertyStoreFromObject = (__vartype(ptr_PSCreatePropertyStoreFromObject))GetProcAddress(hModule, "PSCreatePropertyStoreFromObject");
   ptr_PSCreatePropertyStoreFromPropertySetStorage = (__vartype(ptr_PSCreatePropertyStoreFromPropertySetStorage))GetProcAddress(hModule, "PSCreatePropertyStoreFromPropertySetStorage");
   ptr_PSCreateSimplePropertyChange = (__vartype(ptr_PSCreateSimplePropertyChange))GetProcAddress(hModule, "PSCreateSimplePropertyChange");
   ptr_PSEnumeratePropertyDescriptions = (__vartype(ptr_PSEnumeratePropertyDescriptions))GetProcAddress(hModule, "PSEnumeratePropertyDescriptions");
   ptr_PSFormatForDisplay = (__vartype(ptr_PSFormatForDisplay))GetProcAddress(hModule, "PSFormatForDisplay");
   ptr_PSFormatForDisplayAlloc = (__vartype(ptr_PSFormatForDisplayAlloc))GetProcAddress(hModule, "PSFormatForDisplayAlloc");
   ptr_PSFormatPropertyValue = (__vartype(ptr_PSFormatPropertyValue))GetProcAddress(hModule, "PSFormatPropertyValue");
   ptr_PSGetImageReferenceForValue = (__vartype(ptr_PSGetImageReferenceForValue))GetProcAddress(hModule, "PSGetImageReferenceForValue");
   ptr_PSGetItemPropertyHandler = (__vartype(ptr_PSGetItemPropertyHandler))GetProcAddress(hModule, "PSGetItemPropertyHandler");
   ptr_PSGetItemPropertyHandlerWithCreateObject = (__vartype(ptr_PSGetItemPropertyHandlerWithCreateObject))GetProcAddress(hModule, "PSGetItemPropertyHandlerWithCreateObject");
   ptr_PSGetNameFromPropertyKey = (__vartype(ptr_PSGetNameFromPropertyKey))GetProcAddress(hModule, "PSGetNameFromPropertyKey");
   ptr_PSGetNamedPropertyFromPropertyStorage = (__vartype(ptr_PSGetNamedPropertyFromPropertyStorage))GetProcAddress(hModule, "PSGetNamedPropertyFromPropertyStorage");
   ptr_PSGetPropertyDescription = (__vartype(ptr_PSGetPropertyDescription))GetProcAddress(hModule, "PSGetPropertyDescription");
   ptr_PSGetPropertyDescriptionByName = (__vartype(ptr_PSGetPropertyDescriptionByName))GetProcAddress(hModule, "PSGetPropertyDescriptionByName");
   ptr_PSGetPropertyDescriptionListFromString = (__vartype(ptr_PSGetPropertyDescriptionListFromString))GetProcAddress(hModule, "PSGetPropertyDescriptionListFromString");
   ptr_PSGetPropertyFromPropertyStorage = (__vartype(ptr_PSGetPropertyFromPropertyStorage))GetProcAddress(hModule, "PSGetPropertyFromPropertyStorage");
   ptr_PSGetPropertyKeyFromName = (__vartype(ptr_PSGetPropertyKeyFromName))GetProcAddress(hModule, "PSGetPropertyKeyFromName");
   ptr_PSGetPropertySystem = (__vartype(ptr_PSGetPropertySystem))GetProcAddress(hModule, "PSGetPropertySystem");
   ptr_PSGetPropertyValue = (__vartype(ptr_PSGetPropertyValue))GetProcAddress(hModule, "PSGetPropertyValue");
   ptr_PSLookupPropertyHandlerCLSID = (__vartype(ptr_PSLookupPropertyHandlerCLSID))GetProcAddress(hModule, "PSLookupPropertyHandlerCLSID");
   ptr_PSPropertyBag_Delete = (__vartype(ptr_PSPropertyBag_Delete))GetProcAddress(hModule, "PSPropertyBag_Delete");
   ptr_PSPropertyBag_ReadBOOL = (__vartype(ptr_PSPropertyBag_ReadBOOL))GetProcAddress(hModule, "PSPropertyBag_ReadBOOL");
   ptr_PSPropertyBag_ReadBSTR = (__vartype(ptr_PSPropertyBag_ReadBSTR))GetProcAddress(hModule, "PSPropertyBag_ReadBSTR");
   ptr_PSPropertyBag_ReadDWORD = (__vartype(ptr_PSPropertyBag_ReadDWORD))GetProcAddress(hModule, "PSPropertyBag_ReadDWORD");
   ptr_PSPropertyBag_ReadGUID = (__vartype(ptr_PSPropertyBag_ReadGUID))GetProcAddress(hModule, "PSPropertyBag_ReadGUID");
   ptr_PSPropertyBag_ReadInt = (__vartype(ptr_PSPropertyBag_ReadInt))GetProcAddress(hModule, "PSPropertyBag_ReadInt");
   ptr_PSPropertyBag_ReadLONG = (__vartype(ptr_PSPropertyBag_ReadLONG))GetProcAddress(hModule, "PSPropertyBag_ReadLONG");
   ptr_PSPropertyBag_ReadPOINTL = (__vartype(ptr_PSPropertyBag_ReadPOINTL))GetProcAddress(hModule, "PSPropertyBag_ReadPOINTL");
   ptr_PSPropertyBag_ReadPOINTS = (__vartype(ptr_PSPropertyBag_ReadPOINTS))GetProcAddress(hModule, "PSPropertyBag_ReadPOINTS");
   ptr_PSPropertyBag_ReadPropertyKey = (__vartype(ptr_PSPropertyBag_ReadPropertyKey))GetProcAddress(hModule, "PSPropertyBag_ReadPropertyKey");
   ptr_PSPropertyBag_ReadRECTL = (__vartype(ptr_PSPropertyBag_ReadRECTL))GetProcAddress(hModule, "PSPropertyBag_ReadRECTL");
   ptr_PSPropertyBag_ReadSHORT = (__vartype(ptr_PSPropertyBag_ReadSHORT))GetProcAddress(hModule, "PSPropertyBag_ReadSHORT");
   ptr_PSPropertyBag_ReadStr = (__vartype(ptr_PSPropertyBag_ReadStr))GetProcAddress(hModule, "PSPropertyBag_ReadStr");
   ptr_PSPropertyBag_ReadStrAlloc = (__vartype(ptr_PSPropertyBag_ReadStrAlloc))GetProcAddress(hModule, "PSPropertyBag_ReadStrAlloc");
   ptr_PSPropertyBag_ReadStream = (__vartype(ptr_PSPropertyBag_ReadStream))GetProcAddress(hModule, "PSPropertyBag_ReadStream");
   ptr_PSPropertyBag_ReadType = (__vartype(ptr_PSPropertyBag_ReadType))GetProcAddress(hModule, "PSPropertyBag_ReadType");
   ptr_PSPropertyBag_ReadULONGLONG = (__vartype(ptr_PSPropertyBag_ReadULONGLONG))GetProcAddress(hModule, "PSPropertyBag_ReadULONGLONG");
   ptr_PSPropertyBag_ReadUnknown = (__vartype(ptr_PSPropertyBag_ReadUnknown))GetProcAddress(hModule, "PSPropertyBag_ReadUnknown");
   ptr_PSPropertyBag_WriteBOOL = (__vartype(ptr_PSPropertyBag_WriteBOOL))GetProcAddress(hModule, "PSPropertyBag_WriteBOOL");
   ptr_PSPropertyBag_WriteBSTR = (__vartype(ptr_PSPropertyBag_WriteBSTR))GetProcAddress(hModule, "PSPropertyBag_WriteBSTR");
   ptr_PSPropertyBag_WriteDWORD = (__vartype(ptr_PSPropertyBag_WriteDWORD))GetProcAddress(hModule, "PSPropertyBag_WriteDWORD");
   ptr_PSPropertyBag_WriteGUID = (__vartype(ptr_PSPropertyBag_WriteGUID))GetProcAddress(hModule, "PSPropertyBag_WriteGUID");
   ptr_PSPropertyBag_WriteInt = (__vartype(ptr_PSPropertyBag_WriteInt))GetProcAddress(hModule, "PSPropertyBag_WriteInt");
   ptr_PSPropertyBag_WriteLONG = (__vartype(ptr_PSPropertyBag_WriteLONG))GetProcAddress(hModule, "PSPropertyBag_WriteLONG");
   ptr_PSPropertyBag_WritePOINTL = (__vartype(ptr_PSPropertyBag_WritePOINTL))GetProcAddress(hModule, "PSPropertyBag_WritePOINTL");
   ptr_PSPropertyBag_WritePOINTS = (__vartype(ptr_PSPropertyBag_WritePOINTS))GetProcAddress(hModule, "PSPropertyBag_WritePOINTS");
   ptr_PSPropertyBag_WritePropertyKey = (__vartype(ptr_PSPropertyBag_WritePropertyKey))GetProcAddress(hModule, "PSPropertyBag_WritePropertyKey");
   ptr_PSPropertyBag_WriteRECTL = (__vartype(ptr_PSPropertyBag_WriteRECTL))GetProcAddress(hModule, "PSPropertyBag_WriteRECTL");
   ptr_PSPropertyBag_WriteSHORT = (__vartype(ptr_PSPropertyBag_WriteSHORT))GetProcAddress(hModule, "PSPropertyBag_WriteSHORT");
   ptr_PSPropertyBag_WriteStr = (__vartype(ptr_PSPropertyBag_WriteStr))GetProcAddress(hModule, "PSPropertyBag_WriteStr");
   ptr_PSPropertyBag_WriteStream = (__vartype(ptr_PSPropertyBag_WriteStream))GetProcAddress(hModule, "PSPropertyBag_WriteStream");
   ptr_PSPropertyBag_WriteULONGLONG = (__vartype(ptr_PSPropertyBag_WriteULONGLONG))GetProcAddress(hModule, "PSPropertyBag_WriteULONGLONG");
   ptr_PSPropertyBag_WriteUnknown = (__vartype(ptr_PSPropertyBag_WriteUnknown))GetProcAddress(hModule, "PSPropertyBag_WriteUnknown");
   ptr_PSPropertyKeyFromString = (__vartype(ptr_PSPropertyKeyFromString))GetProcAddress(hModule, "PSPropertyKeyFromString");
   ptr_PSRefreshPropertySchema = (__vartype(ptr_PSRefreshPropertySchema))GetProcAddress(hModule, "PSRefreshPropertySchema");
   ptr_PSRegisterPropertySchema = (__vartype(ptr_PSRegisterPropertySchema))GetProcAddress(hModule, "PSRegisterPropertySchema");
   ptr_PSSetPropertyValue = (__vartype(ptr_PSSetPropertyValue))GetProcAddress(hModule, "PSSetPropertyValue");
   ptr_PSStringFromPropertyKey = (__vartype(ptr_PSStringFromPropertyKey))GetProcAddress(hModule, "PSStringFromPropertyKey");
   ptr_PSUnregisterPropertySchema = (__vartype(ptr_PSUnregisterPropertySchema))GetProcAddress(hModule, "PSUnregisterPropertySchema");
   ptr_PropVariantChangeType = (__vartype(ptr_PropVariantChangeType))GetProcAddress(hModule, "PropVariantChangeType");
   ptr_PropVariantCompareEx = (__vartype(ptr_PropVariantCompareEx))GetProcAddress(hModule, "PropVariantCompareEx");
   ptr_PropVariantGetBooleanElem = (__vartype(ptr_PropVariantGetBooleanElem))GetProcAddress(hModule, "PropVariantGetBooleanElem");
   ptr_PropVariantGetDoubleElem = (__vartype(ptr_PropVariantGetDoubleElem))GetProcAddress(hModule, "PropVariantGetDoubleElem");
   ptr_PropVariantGetElementCount = (__vartype(ptr_PropVariantGetElementCount))GetProcAddress(hModule, "PropVariantGetElementCount");
   ptr_PropVariantGetFileTimeElem = (__vartype(ptr_PropVariantGetFileTimeElem))GetProcAddress(hModule, "PropVariantGetFileTimeElem");
   ptr_PropVariantGetInt16Elem = (__vartype(ptr_PropVariantGetInt16Elem))GetProcAddress(hModule, "PropVariantGetInt16Elem");
   ptr_PropVariantGetInt32Elem = (__vartype(ptr_PropVariantGetInt32Elem))GetProcAddress(hModule, "PropVariantGetInt32Elem");
   ptr_PropVariantGetInt64Elem = (__vartype(ptr_PropVariantGetInt64Elem))GetProcAddress(hModule, "PropVariantGetInt64Elem");
   ptr_PropVariantGetStringElem = (__vartype(ptr_PropVariantGetStringElem))GetProcAddress(hModule, "PropVariantGetStringElem");
   ptr_PropVariantGetUInt16Elem = (__vartype(ptr_PropVariantGetUInt16Elem))GetProcAddress(hModule, "PropVariantGetUInt16Elem");
   ptr_PropVariantGetUInt32Elem = (__vartype(ptr_PropVariantGetUInt32Elem))GetProcAddress(hModule, "PropVariantGetUInt32Elem");
   ptr_PropVariantGetUInt64Elem = (__vartype(ptr_PropVariantGetUInt64Elem))GetProcAddress(hModule, "PropVariantGetUInt64Elem");
   ptr_PropVariantToBSTR = (__vartype(ptr_PropVariantToBSTR))GetProcAddress(hModule, "PropVariantToBSTR");
   ptr_PropVariantToBoolean = (__vartype(ptr_PropVariantToBoolean))GetProcAddress(hModule, "PropVariantToBoolean");
   ptr_PropVariantToBooleanVector = (__vartype(ptr_PropVariantToBooleanVector))GetProcAddress(hModule, "PropVariantToBooleanVector");
   ptr_PropVariantToBooleanVectorAlloc = (__vartype(ptr_PropVariantToBooleanVectorAlloc))GetProcAddress(hModule, "PropVariantToBooleanVectorAlloc");
   ptr_PropVariantToBooleanWithDefault = (__vartype(ptr_PropVariantToBooleanWithDefault))GetProcAddress(hModule, "PropVariantToBooleanWithDefault");
   ptr_PropVariantToBuffer = (__vartype(ptr_PropVariantToBuffer))GetProcAddress(hModule, "PropVariantToBuffer");
   ptr_PropVariantToDouble = (__vartype(ptr_PropVariantToDouble))GetProcAddress(hModule, "PropVariantToDouble");
   ptr_PropVariantToDoubleVector = (__vartype(ptr_PropVariantToDoubleVector))GetProcAddress(hModule, "PropVariantToDoubleVector");
   ptr_PropVariantToDoubleVectorAlloc = (__vartype(ptr_PropVariantToDoubleVectorAlloc))GetProcAddress(hModule, "PropVariantToDoubleVectorAlloc");
   ptr_PropVariantToDoubleWithDefault = (__vartype(ptr_PropVariantToDoubleWithDefault))GetProcAddress(hModule, "PropVariantToDoubleWithDefault");
   ptr_PropVariantToFileTime = (__vartype(ptr_PropVariantToFileTime))GetProcAddress(hModule, "PropVariantToFileTime");
   ptr_PropVariantToFileTimeVector = (__vartype(ptr_PropVariantToFileTimeVector))GetProcAddress(hModule, "PropVariantToFileTimeVector");
   ptr_PropVariantToFileTimeVectorAlloc = (__vartype(ptr_PropVariantToFileTimeVectorAlloc))GetProcAddress(hModule, "PropVariantToFileTimeVectorAlloc");
   ptr_PropVariantToGUID = (__vartype(ptr_PropVariantToGUID))GetProcAddress(hModule, "PropVariantToGUID");
   ptr_PropVariantToInt16 = (__vartype(ptr_PropVariantToInt16))GetProcAddress(hModule, "PropVariantToInt16");
   ptr_PropVariantToInt16Vector = (__vartype(ptr_PropVariantToInt16Vector))GetProcAddress(hModule, "PropVariantToInt16Vector");
   ptr_PropVariantToInt16VectorAlloc = (__vartype(ptr_PropVariantToInt16VectorAlloc))GetProcAddress(hModule, "PropVariantToInt16VectorAlloc");
   ptr_PropVariantToInt16WithDefault = (__vartype(ptr_PropVariantToInt16WithDefault))GetProcAddress(hModule, "PropVariantToInt16WithDefault");
   ptr_PropVariantToInt32 = (__vartype(ptr_PropVariantToInt32))GetProcAddress(hModule, "PropVariantToInt32");
   ptr_PropVariantToInt32Vector = (__vartype(ptr_PropVariantToInt32Vector))GetProcAddress(hModule, "PropVariantToInt32Vector");
   ptr_PropVariantToInt32VectorAlloc = (__vartype(ptr_PropVariantToInt32VectorAlloc))GetProcAddress(hModule, "PropVariantToInt32VectorAlloc");
   ptr_PropVariantToInt32WithDefault = (__vartype(ptr_PropVariantToInt32WithDefault))GetProcAddress(hModule, "PropVariantToInt32WithDefault");
   ptr_PropVariantToInt64 = (__vartype(ptr_PropVariantToInt64))GetProcAddress(hModule, "PropVariantToInt64");
   ptr_PropVariantToInt64Vector = (__vartype(ptr_PropVariantToInt64Vector))GetProcAddress(hModule, "PropVariantToInt64Vector");
   ptr_PropVariantToInt64VectorAlloc = (__vartype(ptr_PropVariantToInt64VectorAlloc))GetProcAddress(hModule, "PropVariantToInt64VectorAlloc");
   ptr_PropVariantToInt64WithDefault = (__vartype(ptr_PropVariantToInt64WithDefault))GetProcAddress(hModule, "PropVariantToInt64WithDefault");
   ptr_PropVariantToStrRet = (__vartype(ptr_PropVariantToStrRet))GetProcAddress(hModule, "PropVariantToStrRet");
   ptr_PropVariantToString = (__vartype(ptr_PropVariantToString))GetProcAddress(hModule, "PropVariantToString");
   ptr_PropVariantToStringAlloc = (__vartype(ptr_PropVariantToStringAlloc))GetProcAddress(hModule, "PropVariantToStringAlloc");
   ptr_PropVariantToStringVector = (__vartype(ptr_PropVariantToStringVector))GetProcAddress(hModule, "PropVariantToStringVector");
   ptr_PropVariantToStringVectorAlloc = (__vartype(ptr_PropVariantToStringVectorAlloc))GetProcAddress(hModule, "PropVariantToStringVectorAlloc");
   ptr_PropVariantToStringWithDefault = (__vartype(ptr_PropVariantToStringWithDefault))GetProcAddress(hModule, "PropVariantToStringWithDefault");
   ptr_PropVariantToUInt16 = (__vartype(ptr_PropVariantToUInt16))GetProcAddress(hModule, "PropVariantToUInt16");
   ptr_PropVariantToUInt16Vector = (__vartype(ptr_PropVariantToUInt16Vector))GetProcAddress(hModule, "PropVariantToUInt16Vector");
   ptr_PropVariantToUInt16VectorAlloc = (__vartype(ptr_PropVariantToUInt16VectorAlloc))GetProcAddress(hModule, "PropVariantToUInt16VectorAlloc");
   ptr_PropVariantToUInt16WithDefault = (__vartype(ptr_PropVariantToUInt16WithDefault))GetProcAddress(hModule, "PropVariantToUInt16WithDefault");
   ptr_PropVariantToUInt32 = (__vartype(ptr_PropVariantToUInt32))GetProcAddress(hModule, "PropVariantToUInt32");
   ptr_PropVariantToUInt32Vector = (__vartype(ptr_PropVariantToUInt32Vector))GetProcAddress(hModule, "PropVariantToUInt32Vector");
   ptr_PropVariantToUInt32VectorAlloc = (__vartype(ptr_PropVariantToUInt32VectorAlloc))GetProcAddress(hModule, "PropVariantToUInt32VectorAlloc");
   ptr_PropVariantToUInt32WithDefault = (__vartype(ptr_PropVariantToUInt32WithDefault))GetProcAddress(hModule, "PropVariantToUInt32WithDefault");
   ptr_PropVariantToUInt64 = (__vartype(ptr_PropVariantToUInt64))GetProcAddress(hModule, "PropVariantToUInt64");
   ptr_PropVariantToUInt64Vector = (__vartype(ptr_PropVariantToUInt64Vector))GetProcAddress(hModule, "PropVariantToUInt64Vector");
   ptr_PropVariantToUInt64VectorAlloc = (__vartype(ptr_PropVariantToUInt64VectorAlloc))GetProcAddress(hModule, "PropVariantToUInt64VectorAlloc");
   ptr_PropVariantToUInt64WithDefault = (__vartype(ptr_PropVariantToUInt64WithDefault))GetProcAddress(hModule, "PropVariantToUInt64WithDefault");
   ptr_PropVariantToVariant = (__vartype(ptr_PropVariantToVariant))GetProcAddress(hModule, "PropVariantToVariant");
   ptr_StgDeserializePropVariant = (__vartype(ptr_StgDeserializePropVariant))GetProcAddress(hModule, "StgDeserializePropVariant");
   ptr_StgSerializePropVariant = (__vartype(ptr_StgSerializePropVariant))GetProcAddress(hModule, "StgSerializePropVariant");
   ptr_VariantCompare = (__vartype(ptr_VariantCompare))GetProcAddress(hModule, "VariantCompare");
   ptr_VariantGetBooleanElem = (__vartype(ptr_VariantGetBooleanElem))GetProcAddress(hModule, "VariantGetBooleanElem");
   ptr_VariantGetDoubleElem = (__vartype(ptr_VariantGetDoubleElem))GetProcAddress(hModule, "VariantGetDoubleElem");
   ptr_VariantGetElementCount = (__vartype(ptr_VariantGetElementCount))GetProcAddress(hModule, "VariantGetElementCount");
   ptr_VariantGetInt16Elem = (__vartype(ptr_VariantGetInt16Elem))GetProcAddress(hModule, "VariantGetInt16Elem");
   ptr_VariantGetInt32Elem = (__vartype(ptr_VariantGetInt32Elem))GetProcAddress(hModule, "VariantGetInt32Elem");
   ptr_VariantGetInt64Elem = (__vartype(ptr_VariantGetInt64Elem))GetProcAddress(hModule, "VariantGetInt64Elem");
   ptr_VariantGetStringElem = (__vartype(ptr_VariantGetStringElem))GetProcAddress(hModule, "VariantGetStringElem");
   ptr_VariantGetUInt16Elem = (__vartype(ptr_VariantGetUInt16Elem))GetProcAddress(hModule, "VariantGetUInt16Elem");
   ptr_VariantGetUInt32Elem = (__vartype(ptr_VariantGetUInt32Elem))GetProcAddress(hModule, "VariantGetUInt32Elem");
   ptr_VariantGetUInt64Elem = (__vartype(ptr_VariantGetUInt64Elem))GetProcAddress(hModule, "VariantGetUInt64Elem");
   ptr_VariantToBoolean = (__vartype(ptr_VariantToBoolean))GetProcAddress(hModule, "VariantToBoolean");
   ptr_VariantToBooleanArray = (__vartype(ptr_VariantToBooleanArray))GetProcAddress(hModule, "VariantToBooleanArray");
   ptr_VariantToBooleanArrayAlloc = (__vartype(ptr_VariantToBooleanArrayAlloc))GetProcAddress(hModule, "VariantToBooleanArrayAlloc");
   ptr_VariantToBooleanWithDefault = (__vartype(ptr_VariantToBooleanWithDefault))GetProcAddress(hModule, "VariantToBooleanWithDefault");
   ptr_VariantToBuffer = (__vartype(ptr_VariantToBuffer))GetProcAddress(hModule, "VariantToBuffer");
   ptr_VariantToDosDateTime = (__vartype(ptr_VariantToDosDateTime))GetProcAddress(hModule, "VariantToDosDateTime");
   ptr_VariantToDouble = (__vartype(ptr_VariantToDouble))GetProcAddress(hModule, "VariantToDouble");
   ptr_VariantToDoubleArray = (__vartype(ptr_VariantToDoubleArray))GetProcAddress(hModule, "VariantToDoubleArray");
   ptr_VariantToDoubleArrayAlloc = (__vartype(ptr_VariantToDoubleArrayAlloc))GetProcAddress(hModule, "VariantToDoubleArrayAlloc");
   ptr_VariantToDoubleWithDefault = (__vartype(ptr_VariantToDoubleWithDefault))GetProcAddress(hModule, "VariantToDoubleWithDefault");
   ptr_VariantToFileTime = (__vartype(ptr_VariantToFileTime))GetProcAddress(hModule, "VariantToFileTime");
   ptr_VariantToGUID = (__vartype(ptr_VariantToGUID))GetProcAddress(hModule, "VariantToGUID");
   ptr_VariantToInt16 = (__vartype(ptr_VariantToInt16))GetProcAddress(hModule, "VariantToInt16");
   ptr_VariantToInt16Array = (__vartype(ptr_VariantToInt16Array))GetProcAddress(hModule, "VariantToInt16Array");
   ptr_VariantToInt16ArrayAlloc = (__vartype(ptr_VariantToInt16ArrayAlloc))GetProcAddress(hModule, "VariantToInt16ArrayAlloc");
   ptr_VariantToInt16WithDefault = (__vartype(ptr_VariantToInt16WithDefault))GetProcAddress(hModule, "VariantToInt16WithDefault");
   ptr_VariantToInt32 = (__vartype(ptr_VariantToInt32))GetProcAddress(hModule, "VariantToInt32");
   ptr_VariantToInt32Array = (__vartype(ptr_VariantToInt32Array))GetProcAddress(hModule, "VariantToInt32Array");
   ptr_VariantToInt32ArrayAlloc = (__vartype(ptr_VariantToInt32ArrayAlloc))GetProcAddress(hModule, "VariantToInt32ArrayAlloc");
   ptr_VariantToInt32WithDefault = (__vartype(ptr_VariantToInt32WithDefault))GetProcAddress(hModule, "VariantToInt32WithDefault");
   ptr_VariantToInt64 = (__vartype(ptr_VariantToInt64))GetProcAddress(hModule, "VariantToInt64");
   ptr_VariantToInt64Array = (__vartype(ptr_VariantToInt64Array))GetProcAddress(hModule, "VariantToInt64Array");
   ptr_VariantToInt64ArrayAlloc = (__vartype(ptr_VariantToInt64ArrayAlloc))GetProcAddress(hModule, "VariantToInt64ArrayAlloc");
   ptr_VariantToInt64WithDefault = (__vartype(ptr_VariantToInt64WithDefault))GetProcAddress(hModule, "VariantToInt64WithDefault");
   ptr_VariantToPropVariant = (__vartype(ptr_VariantToPropVariant))GetProcAddress(hModule, "VariantToPropVariant");
   ptr_VariantToStrRet = (__vartype(ptr_VariantToStrRet))GetProcAddress(hModule, "VariantToStrRet");
   ptr_VariantToString = (__vartype(ptr_VariantToString))GetProcAddress(hModule, "VariantToString");
   ptr_VariantToStringAlloc = (__vartype(ptr_VariantToStringAlloc))GetProcAddress(hModule, "VariantToStringAlloc");
   ptr_VariantToStringArray = (__vartype(ptr_VariantToStringArray))GetProcAddress(hModule, "VariantToStringArray");
   ptr_VariantToStringArrayAlloc = (__vartype(ptr_VariantToStringArrayAlloc))GetProcAddress(hModule, "VariantToStringArrayAlloc");
   ptr_VariantToStringWithDefault = (__vartype(ptr_VariantToStringWithDefault))GetProcAddress(hModule, "VariantToStringWithDefault");
   ptr_VariantToUInt16 = (__vartype(ptr_VariantToUInt16))GetProcAddress(hModule, "VariantToUInt16");
   ptr_VariantToUInt16Array = (__vartype(ptr_VariantToUInt16Array))GetProcAddress(hModule, "VariantToUInt16Array");
   ptr_VariantToUInt16ArrayAlloc = (__vartype(ptr_VariantToUInt16ArrayAlloc))GetProcAddress(hModule, "VariantToUInt16ArrayAlloc");
   ptr_VariantToUInt16WithDefault = (__vartype(ptr_VariantToUInt16WithDefault))GetProcAddress(hModule, "VariantToUInt16WithDefault");
   ptr_VariantToUInt32 = (__vartype(ptr_VariantToUInt32))GetProcAddress(hModule, "VariantToUInt32");
   ptr_VariantToUInt32Array = (__vartype(ptr_VariantToUInt32Array))GetProcAddress(hModule, "VariantToUInt32Array");
   ptr_VariantToUInt32ArrayAlloc = (__vartype(ptr_VariantToUInt32ArrayAlloc))GetProcAddress(hModule, "VariantToUInt32ArrayAlloc");
   ptr_VariantToUInt32WithDefault = (__vartype(ptr_VariantToUInt32WithDefault))GetProcAddress(hModule, "VariantToUInt32WithDefault");
   ptr_VariantToUInt64 = (__vartype(ptr_VariantToUInt64))GetProcAddress(hModule, "VariantToUInt64");
   ptr_VariantToUInt64Array = (__vartype(ptr_VariantToUInt64Array))GetProcAddress(hModule, "VariantToUInt64Array");
   ptr_VariantToUInt64ArrayAlloc = (__vartype(ptr_VariantToUInt64ArrayAlloc))GetProcAddress(hModule, "VariantToUInt64ArrayAlloc");
   ptr_VariantToUInt64WithDefault = (__vartype(ptr_VariantToUInt64WithDefault))GetProcAddress(hModule, "VariantToUInt64WithDefault");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

