#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_CreateProvHost;
void *ptr_CreateProvHost = NULL;
extern void *ptr_EnumServiceUserResources;
void *ptr_EnumServiceUserResources = NULL;
extern void *ptr_FwGetParsedDocument;
void *ptr_FwGetParsedDocument = NULL;
extern void *ptr_FwGetRootElement;
void *ptr_FwGetRootElement = NULL;
extern void *ptr_FwIsXmlEscapedProperly;
void *ptr_FwIsXmlEscapedProperly = NULL;
extern void *ptr_FwXmlCloseParser;
void *ptr_FwXmlCloseParser = NULL;
extern void *ptr_FwXmlCompareAttributeName;
void *ptr_FwXmlCompareAttributeName = NULL;
extern void *ptr_FwXmlCompareAttributeNameEx;
void *ptr_FwXmlCompareAttributeNameEx = NULL;
extern void *ptr_FwXmlCompareElementName;
void *ptr_FwXmlCompareElementName = NULL;
extern void *ptr_FwXmlCompareElementNameEx;
void *ptr_FwXmlCompareElementNameEx = NULL;
extern void *ptr_FwXmlCompareElementNameLen;
void *ptr_FwXmlCompareElementNameLen = NULL;
extern void *ptr_FwXmlCompareElementNameSpace;
void *ptr_FwXmlCompareElementNameSpace = NULL;
extern void *ptr_FwXmlCompareName;
void *ptr_FwXmlCompareName = NULL;
extern void *ptr_FwXmlCreateXmlFromElement;
void *ptr_FwXmlCreateXmlFromElement = NULL;
extern void *ptr_FwXmlDecodeXmlEscapes;
void *ptr_FwXmlDecodeXmlEscapes = NULL;
extern void *ptr_FwXmlEncodeXmlEscapes;
void *ptr_FwXmlEncodeXmlEscapes = NULL;
extern void *ptr_FwXmlFindAttribute;
void *ptr_FwXmlFindAttribute = NULL;
extern void *ptr_FwXmlFindAttributeEx;
void *ptr_FwXmlFindAttributeEx = NULL;
extern void *ptr_FwXmlFindChildElement;
void *ptr_FwXmlFindChildElement = NULL;
extern void *ptr_FwXmlFindChildElementEx;
void *ptr_FwXmlFindChildElementEx = NULL;
extern void *ptr_FwXmlGetAttribute;
void *ptr_FwXmlGetAttribute = NULL;
extern void *ptr_FwXmlGetAttributeNameEx;
void *ptr_FwXmlGetAttributeNameEx = NULL;
extern void *ptr_FwXmlGetAttributeNamespacePrefix;
void *ptr_FwXmlGetAttributeNamespacePrefix = NULL;
extern void *ptr_FwXmlGetAttributeValue;
void *ptr_FwXmlGetAttributeValue = NULL;
extern void *ptr_FwXmlGetAttributeValueDWord;
void *ptr_FwXmlGetAttributeValueDWord = NULL;
extern void *ptr_FwXmlGetBooleanValue;
void *ptr_FwXmlGetBooleanValue = NULL;
extern void *ptr_FwXmlGetBuffer;
void *ptr_FwXmlGetBuffer = NULL;
extern void *ptr_FwXmlGetChild;
void *ptr_FwXmlGetChild = NULL;
extern void *ptr_FwXmlGetElementName;
void *ptr_FwXmlGetElementName = NULL;
extern void *ptr_FwXmlGetElementNameEx;
void *ptr_FwXmlGetElementNameEx = NULL;
extern void *ptr_FwXmlGetElementNamespacePrefix;
void *ptr_FwXmlGetElementNamespacePrefix = NULL;
extern void *ptr_FwXmlGetElementNamespaceUrl;
void *ptr_FwXmlGetElementNamespaceUrl = NULL;
extern void *ptr_FwXmlGetEntryNameEx;
void *ptr_FwXmlGetEntryNameEx = NULL;
extern void *ptr_FwXmlGetNamespaceForPrefix;
void *ptr_FwXmlGetNamespaceForPrefix = NULL;
extern void *ptr_FwXmlGetNormalizedString;
void *ptr_FwXmlGetNormalizedString = NULL;
extern void *ptr_FwXmlGetReferenceXmlFromElement;
void *ptr_FwXmlGetReferenceXmlFromElement = NULL;
extern void *ptr_FwXmlGetSimpleContent;
void *ptr_FwXmlGetSimpleContent = NULL;
extern void *ptr_FwXmlGetSimpleContentEx;
void *ptr_FwXmlGetSimpleContentEx = NULL;
extern void *ptr_FwXmlGetSimpleContentEx2;
void *ptr_FwXmlGetSimpleContentEx2 = NULL;
extern void *ptr_FwXmlHasText;
void *ptr_FwXmlHasText = NULL;
extern void *ptr_FwXmlIsEmpty;
void *ptr_FwXmlIsEmpty = NULL;
extern void *ptr_FwXmlIsMustUnderstand;
void *ptr_FwXmlIsMustUnderstand = NULL;
extern void *ptr_FwXmlIsNull;
void *ptr_FwXmlIsNull = NULL;
extern void *ptr_FwXmlIsSimpleContent;
void *ptr_FwXmlIsSimpleContent = NULL;
extern void *ptr_FwXmlIsSimpleContentOrEmpty;
void *ptr_FwXmlIsSimpleContentOrEmpty = NULL;
extern void *ptr_FwXmlIsTrueValue;
void *ptr_FwXmlIsTrueValue = NULL;
extern void *ptr_FwXmlNumAttributes;
void *ptr_FwXmlNumAttributes = NULL;
extern void *ptr_FwXmlNumChildren;
void *ptr_FwXmlNumChildren = NULL;
extern void *ptr_FwXmlNumChildrenWithName;
void *ptr_FwXmlNumChildrenWithName = NULL;
extern void *ptr_FwXmlNumConsecutiveChildrenWithName;
void *ptr_FwXmlNumConsecutiveChildrenWithName = NULL;
extern void *ptr_FwXmlParsePrefixedXML;
void *ptr_FwXmlParsePrefixedXML = NULL;
extern void *ptr_FwXmlParseText;
void *ptr_FwXmlParseText = NULL;
extern void *ptr_FwXmlParserCreate;
void *ptr_FwXmlParserCreate = NULL;
extern void *ptr_FwXmlUpdatePrefixes;
void *ptr_FwXmlUpdatePrefixes = NULL;
extern void *ptr_GetServiceSecurity;
void *ptr_GetServiceSecurity = NULL;
extern void *ptr_RegisterModule;
void *ptr_RegisterModule = NULL;
extern void *ptr_ServiceMain;
void *ptr_ServiceMain = NULL;
extern void *ptr_SetServiceSecurity;
void *ptr_SetServiceSecurity = NULL;
extern void *ptr_StartSoapProcessor;
void *ptr_StartSoapProcessor = NULL;
extern void *ptr_StopSoapProcessor;
void *ptr_StopSoapProcessor = NULL;
extern void *ptr_SubscriptionsProvEndEnumerate;
void *ptr_SubscriptionsProvEndEnumerate = NULL;
extern void *ptr_SubscriptionsProvEnumerate;
void *ptr_SubscriptionsProvEnumerate = NULL;
extern void *ptr_SubscriptionsProvPullEnumerate;
void *ptr_SubscriptionsProvPullEnumerate = NULL;
extern void *ptr_SvchostPushServiceGlobals;
void *ptr_SvchostPushServiceGlobals = NULL;
extern void *ptr_WSManAckEvents;
void *ptr_WSManAckEvents = NULL;
extern void *ptr_WSManAddSubscriptionManagerInternal;
void *ptr_WSManAddSubscriptionManagerInternal = NULL;
extern void *ptr_WSManCloseCommand;
void *ptr_WSManCloseCommand = NULL;
extern void *ptr_WSManCloseEnumerationHandle;
void *ptr_WSManCloseEnumerationHandle = NULL;
extern void *ptr_WSManCloseEnumeratorHandle;
void *ptr_WSManCloseEnumeratorHandle = NULL;
extern void *ptr_WSManCloseObjectHandle;
void *ptr_WSManCloseObjectHandle = NULL;
extern void *ptr_WSManCloseOperation;
void *ptr_WSManCloseOperation = NULL;
extern void *ptr_WSManClosePublisherHandle;
void *ptr_WSManClosePublisherHandle = NULL;
extern void *ptr_WSManCloseSession;
void *ptr_WSManCloseSession = NULL;
extern void *ptr_WSManCloseSessionHandle;
void *ptr_WSManCloseSessionHandle = NULL;
extern void *ptr_WSManCloseShell;
void *ptr_WSManCloseShell = NULL;
extern void *ptr_WSManCloseSubscriptionHandle;
void *ptr_WSManCloseSubscriptionHandle = NULL;
extern void *ptr_WSManConstructError;
void *ptr_WSManConstructError = NULL;
extern void *ptr_WSManCreateEnumeratorInternal;
void *ptr_WSManCreateEnumeratorInternal = NULL;
extern void *ptr_WSManCreateInternal;
void *ptr_WSManCreateInternal = NULL;
extern void *ptr_WSManCreateInternalEx;
void *ptr_WSManCreateInternalEx = NULL;
extern void *ptr_WSManCreatePullSubscription;
void *ptr_WSManCreatePullSubscription = NULL;
extern void *ptr_WSManCreatePushSubscription;
void *ptr_WSManCreatePushSubscription = NULL;
extern void *ptr_WSManCreateSession;
void *ptr_WSManCreateSession = NULL;
extern void *ptr_WSManCreateSessionInternal;
void *ptr_WSManCreateSessionInternal = NULL;
extern void *ptr_WSManCreateShell;
void *ptr_WSManCreateShell = NULL;
extern void *ptr_WSManDecodeObject;
void *ptr_WSManDecodeObject = NULL;
extern void *ptr_WSManDeinitialize;
void *ptr_WSManDeinitialize = NULL;
extern void *ptr_WSManDeleteInternal;
void *ptr_WSManDeleteInternal = NULL;
extern void *ptr_WSManDeleteInternalEx;
void *ptr_WSManDeleteInternalEx = NULL;
extern void *ptr_WSManDeliverEndSubscriptionNotification;
void *ptr_WSManDeliverEndSubscriptionNotification = NULL;
extern void *ptr_WSManDeliverEvent;
void *ptr_WSManDeliverEvent = NULL;
extern void *ptr_WSManEncodeObject;
void *ptr_WSManEncodeObject = NULL;
extern void *ptr_WSManEncodeObjectEx;
void *ptr_WSManEncodeObjectEx = NULL;
extern void *ptr_WSManEncodeObjectInternal;
void *ptr_WSManEncodeObjectInternal = NULL;
extern void *ptr_WSManEnumerateInternal;
void *ptr_WSManEnumerateInternal = NULL;
extern void *ptr_WSManEnumerateInternalEx;
void *ptr_WSManEnumerateInternalEx = NULL;
extern void *ptr_WSManEnumeratorAddEvent;
void *ptr_WSManEnumeratorAddEvent = NULL;
extern void *ptr_WSManEnumeratorAddObject;
void *ptr_WSManEnumeratorAddObject = NULL;
extern void *ptr_WSManEnumeratorBatchPolicyViolated;
void *ptr_WSManEnumeratorBatchPolicyViolated = NULL;
extern void *ptr_WSManEnumeratorNextObject;
void *ptr_WSManEnumeratorNextObject = NULL;
extern void *ptr_WSManEnumeratorObjectCount;
void *ptr_WSManEnumeratorObjectCount = NULL;
extern void *ptr_WSManGetErrorMessage;
void *ptr_WSManGetErrorMessage = NULL;
extern void *ptr_WSManGetInternal;
void *ptr_WSManGetInternal = NULL;
extern void *ptr_WSManGetInternalEx;
void *ptr_WSManGetInternalEx = NULL;
extern void *ptr_WSManGetSessionOptionAsDword;
void *ptr_WSManGetSessionOptionAsDword = NULL;
extern void *ptr_WSManGetSessionOptionAsString;
void *ptr_WSManGetSessionOptionAsString = NULL;
extern void *ptr_WSManIdentifyInternal;
void *ptr_WSManIdentifyInternal = NULL;
extern void *ptr_WSManInitialize;
void *ptr_WSManInitialize = NULL;
extern void *ptr_WSManInvokeInternal;
void *ptr_WSManInvokeInternal = NULL;
extern void *ptr_WSManInvokeInternalEx;
void *ptr_WSManInvokeInternalEx = NULL;
extern void *ptr_WSManPluginAuthzOperationComplete;
void *ptr_WSManPluginAuthzOperationComplete = NULL;
extern void *ptr_WSManPluginAuthzQueryQuotaComplete;
void *ptr_WSManPluginAuthzQueryQuotaComplete = NULL;
extern void *ptr_WSManPluginAuthzUserComplete;
void *ptr_WSManPluginAuthzUserComplete = NULL;
extern void *ptr_WSManPluginFreeRequestDetails;
void *ptr_WSManPluginFreeRequestDetails = NULL;
extern void *ptr_WSManPluginGetOperationParameters;
void *ptr_WSManPluginGetOperationParameters = NULL;
extern void *ptr_WSManPluginObjectAndBookmarkResult;
void *ptr_WSManPluginObjectAndBookmarkResult = NULL;
extern void *ptr_WSManPluginObjectAndEprResult;
void *ptr_WSManPluginObjectAndEprResult = NULL;
extern void *ptr_WSManPluginObjectResult;
void *ptr_WSManPluginObjectResult = NULL;
extern void *ptr_WSManPluginOperationComplete;
void *ptr_WSManPluginOperationComplete = NULL;
extern void *ptr_WSManPluginReceiveResult;
void *ptr_WSManPluginReceiveResult = NULL;
extern void *ptr_WSManPluginReportContext;
void *ptr_WSManPluginReportContext = NULL;
extern void *ptr_WSManPluginShutdown;
void *ptr_WSManPluginShutdown = NULL;
extern void *ptr_WSManPluginStartup;
void *ptr_WSManPluginStartup = NULL;
extern void *ptr_WSManProvCreate;
void *ptr_WSManProvCreate = NULL;
extern void *ptr_WSManProvDelete;
void *ptr_WSManProvDelete = NULL;
extern void *ptr_WSManProvEndEnumerate;
void *ptr_WSManProvEndEnumerate = NULL;
extern void *ptr_WSManProvEnumerate;
void *ptr_WSManProvEnumerate = NULL;
extern void *ptr_WSManProvGet;
void *ptr_WSManProvGet = NULL;
extern void *ptr_WSManProvInvoke;
void *ptr_WSManProvInvoke = NULL;
extern void *ptr_WSManProvPullEnumerate;
void *ptr_WSManProvPullEnumerate = NULL;
extern void *ptr_WSManProvPut;
void *ptr_WSManProvPut = NULL;
extern void *ptr_WSManPull;
void *ptr_WSManPull = NULL;
extern void *ptr_WSManPullEvents;
void *ptr_WSManPullEvents = NULL;
extern void *ptr_WSManPutInternal;
void *ptr_WSManPutInternal = NULL;
extern void *ptr_WSManPutInternalEx;
void *ptr_WSManPutInternalEx = NULL;
extern void *ptr_WSManReceiveShellOutput;
void *ptr_WSManReceiveShellOutput = NULL;
extern void *ptr_WSManRemoveSubscriptionManagerInternal;
void *ptr_WSManRemoveSubscriptionManagerInternal = NULL;
extern void *ptr_WSManRunShellCommand;
void *ptr_WSManRunShellCommand = NULL;
extern void *ptr_WSManSendShellInput;
void *ptr_WSManSendShellInput = NULL;
extern void *ptr_WSManSetSessionOption;
void *ptr_WSManSetSessionOption = NULL;
extern void *ptr_WSManShellProvEndEnumerate;
void *ptr_WSManShellProvEndEnumerate = NULL;
extern void *ptr_WSManShellProvPullEnumerate;
void *ptr_WSManShellProvPullEnumerate = NULL;
extern void *ptr_WSManSignalShell;
void *ptr_WSManSignalShell = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\WsmSvc.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_CreateProvHost = (__vartype(ptr_CreateProvHost))GetProcAddress(hModule, "CreateProvHost");
   ptr_EnumServiceUserResources = (__vartype(ptr_EnumServiceUserResources))GetProcAddress(hModule, "EnumServiceUserResources");
   ptr_FwGetParsedDocument = (__vartype(ptr_FwGetParsedDocument))GetProcAddress(hModule, "FwGetParsedDocument");
   ptr_FwGetRootElement = (__vartype(ptr_FwGetRootElement))GetProcAddress(hModule, "FwGetRootElement");
   ptr_FwIsXmlEscapedProperly = (__vartype(ptr_FwIsXmlEscapedProperly))GetProcAddress(hModule, "FwIsXmlEscapedProperly");
   ptr_FwXmlCloseParser = (__vartype(ptr_FwXmlCloseParser))GetProcAddress(hModule, "FwXmlCloseParser");
   ptr_FwXmlCompareAttributeName = (__vartype(ptr_FwXmlCompareAttributeName))GetProcAddress(hModule, "FwXmlCompareAttributeName");
   ptr_FwXmlCompareAttributeNameEx = (__vartype(ptr_FwXmlCompareAttributeNameEx))GetProcAddress(hModule, "FwXmlCompareAttributeNameEx");
   ptr_FwXmlCompareElementName = (__vartype(ptr_FwXmlCompareElementName))GetProcAddress(hModule, "FwXmlCompareElementName");
   ptr_FwXmlCompareElementNameEx = (__vartype(ptr_FwXmlCompareElementNameEx))GetProcAddress(hModule, "FwXmlCompareElementNameEx");
   ptr_FwXmlCompareElementNameLen = (__vartype(ptr_FwXmlCompareElementNameLen))GetProcAddress(hModule, "FwXmlCompareElementNameLen");
   ptr_FwXmlCompareElementNameSpace = (__vartype(ptr_FwXmlCompareElementNameSpace))GetProcAddress(hModule, "FwXmlCompareElementNameSpace");
   ptr_FwXmlCompareName = (__vartype(ptr_FwXmlCompareName))GetProcAddress(hModule, "FwXmlCompareName");
   ptr_FwXmlCreateXmlFromElement = (__vartype(ptr_FwXmlCreateXmlFromElement))GetProcAddress(hModule, "FwXmlCreateXmlFromElement");
   ptr_FwXmlDecodeXmlEscapes = (__vartype(ptr_FwXmlDecodeXmlEscapes))GetProcAddress(hModule, "FwXmlDecodeXmlEscapes");
   ptr_FwXmlEncodeXmlEscapes = (__vartype(ptr_FwXmlEncodeXmlEscapes))GetProcAddress(hModule, "FwXmlEncodeXmlEscapes");
   ptr_FwXmlFindAttribute = (__vartype(ptr_FwXmlFindAttribute))GetProcAddress(hModule, "FwXmlFindAttribute");
   ptr_FwXmlFindAttributeEx = (__vartype(ptr_FwXmlFindAttributeEx))GetProcAddress(hModule, "FwXmlFindAttributeEx");
   ptr_FwXmlFindChildElement = (__vartype(ptr_FwXmlFindChildElement))GetProcAddress(hModule, "FwXmlFindChildElement");
   ptr_FwXmlFindChildElementEx = (__vartype(ptr_FwXmlFindChildElementEx))GetProcAddress(hModule, "FwXmlFindChildElementEx");
   ptr_FwXmlGetAttribute = (__vartype(ptr_FwXmlGetAttribute))GetProcAddress(hModule, "FwXmlGetAttribute");
   ptr_FwXmlGetAttributeNameEx = (__vartype(ptr_FwXmlGetAttributeNameEx))GetProcAddress(hModule, "FwXmlGetAttributeNameEx");
   ptr_FwXmlGetAttributeNamespacePrefix = (__vartype(ptr_FwXmlGetAttributeNamespacePrefix))GetProcAddress(hModule, "FwXmlGetAttributeNamespacePrefix");
   ptr_FwXmlGetAttributeValue = (__vartype(ptr_FwXmlGetAttributeValue))GetProcAddress(hModule, "FwXmlGetAttributeValue");
   ptr_FwXmlGetAttributeValueDWord = (__vartype(ptr_FwXmlGetAttributeValueDWord))GetProcAddress(hModule, "FwXmlGetAttributeValueDWord");
   ptr_FwXmlGetBooleanValue = (__vartype(ptr_FwXmlGetBooleanValue))GetProcAddress(hModule, "FwXmlGetBooleanValue");
   ptr_FwXmlGetBuffer = (__vartype(ptr_FwXmlGetBuffer))GetProcAddress(hModule, "FwXmlGetBuffer");
   ptr_FwXmlGetChild = (__vartype(ptr_FwXmlGetChild))GetProcAddress(hModule, "FwXmlGetChild");
   ptr_FwXmlGetElementName = (__vartype(ptr_FwXmlGetElementName))GetProcAddress(hModule, "FwXmlGetElementName");
   ptr_FwXmlGetElementNameEx = (__vartype(ptr_FwXmlGetElementNameEx))GetProcAddress(hModule, "FwXmlGetElementNameEx");
   ptr_FwXmlGetElementNamespacePrefix = (__vartype(ptr_FwXmlGetElementNamespacePrefix))GetProcAddress(hModule, "FwXmlGetElementNamespacePrefix");
   ptr_FwXmlGetElementNamespaceUrl = (__vartype(ptr_FwXmlGetElementNamespaceUrl))GetProcAddress(hModule, "FwXmlGetElementNamespaceUrl");
   ptr_FwXmlGetEntryNameEx = (__vartype(ptr_FwXmlGetEntryNameEx))GetProcAddress(hModule, "FwXmlGetEntryNameEx");
   ptr_FwXmlGetNamespaceForPrefix = (__vartype(ptr_FwXmlGetNamespaceForPrefix))GetProcAddress(hModule, "FwXmlGetNamespaceForPrefix");
   ptr_FwXmlGetNormalizedString = (__vartype(ptr_FwXmlGetNormalizedString))GetProcAddress(hModule, "FwXmlGetNormalizedString");
   ptr_FwXmlGetReferenceXmlFromElement = (__vartype(ptr_FwXmlGetReferenceXmlFromElement))GetProcAddress(hModule, "FwXmlGetReferenceXmlFromElement");
   ptr_FwXmlGetSimpleContent = (__vartype(ptr_FwXmlGetSimpleContent))GetProcAddress(hModule, "FwXmlGetSimpleContent");
   ptr_FwXmlGetSimpleContentEx = (__vartype(ptr_FwXmlGetSimpleContentEx))GetProcAddress(hModule, "FwXmlGetSimpleContentEx");
   ptr_FwXmlGetSimpleContentEx2 = (__vartype(ptr_FwXmlGetSimpleContentEx2))GetProcAddress(hModule, "FwXmlGetSimpleContentEx2");
   ptr_FwXmlHasText = (__vartype(ptr_FwXmlHasText))GetProcAddress(hModule, "FwXmlHasText");
   ptr_FwXmlIsEmpty = (__vartype(ptr_FwXmlIsEmpty))GetProcAddress(hModule, "FwXmlIsEmpty");
   ptr_FwXmlIsMustUnderstand = (__vartype(ptr_FwXmlIsMustUnderstand))GetProcAddress(hModule, "FwXmlIsMustUnderstand");
   ptr_FwXmlIsNull = (__vartype(ptr_FwXmlIsNull))GetProcAddress(hModule, "FwXmlIsNull");
   ptr_FwXmlIsSimpleContent = (__vartype(ptr_FwXmlIsSimpleContent))GetProcAddress(hModule, "FwXmlIsSimpleContent");
   ptr_FwXmlIsSimpleContentOrEmpty = (__vartype(ptr_FwXmlIsSimpleContentOrEmpty))GetProcAddress(hModule, "FwXmlIsSimpleContentOrEmpty");
   ptr_FwXmlIsTrueValue = (__vartype(ptr_FwXmlIsTrueValue))GetProcAddress(hModule, "FwXmlIsTrueValue");
   ptr_FwXmlNumAttributes = (__vartype(ptr_FwXmlNumAttributes))GetProcAddress(hModule, "FwXmlNumAttributes");
   ptr_FwXmlNumChildren = (__vartype(ptr_FwXmlNumChildren))GetProcAddress(hModule, "FwXmlNumChildren");
   ptr_FwXmlNumChildrenWithName = (__vartype(ptr_FwXmlNumChildrenWithName))GetProcAddress(hModule, "FwXmlNumChildrenWithName");
   ptr_FwXmlNumConsecutiveChildrenWithName = (__vartype(ptr_FwXmlNumConsecutiveChildrenWithName))GetProcAddress(hModule, "FwXmlNumConsecutiveChildrenWithName");
   ptr_FwXmlParsePrefixedXML = (__vartype(ptr_FwXmlParsePrefixedXML))GetProcAddress(hModule, "FwXmlParsePrefixedXML");
   ptr_FwXmlParseText = (__vartype(ptr_FwXmlParseText))GetProcAddress(hModule, "FwXmlParseText");
   ptr_FwXmlParserCreate = (__vartype(ptr_FwXmlParserCreate))GetProcAddress(hModule, "FwXmlParserCreate");
   ptr_FwXmlUpdatePrefixes = (__vartype(ptr_FwXmlUpdatePrefixes))GetProcAddress(hModule, "FwXmlUpdatePrefixes");
   ptr_GetServiceSecurity = (__vartype(ptr_GetServiceSecurity))GetProcAddress(hModule, "GetServiceSecurity");
   ptr_RegisterModule = (__vartype(ptr_RegisterModule))GetProcAddress(hModule, "RegisterModule");
   ptr_ServiceMain = (__vartype(ptr_ServiceMain))GetProcAddress(hModule, "ServiceMain");
   ptr_SetServiceSecurity = (__vartype(ptr_SetServiceSecurity))GetProcAddress(hModule, "SetServiceSecurity");
   ptr_StartSoapProcessor = (__vartype(ptr_StartSoapProcessor))GetProcAddress(hModule, "StartSoapProcessor");
   ptr_StopSoapProcessor = (__vartype(ptr_StopSoapProcessor))GetProcAddress(hModule, "StopSoapProcessor");
   ptr_SubscriptionsProvEndEnumerate = (__vartype(ptr_SubscriptionsProvEndEnumerate))GetProcAddress(hModule, "SubscriptionsProvEndEnumerate");
   ptr_SubscriptionsProvEnumerate = (__vartype(ptr_SubscriptionsProvEnumerate))GetProcAddress(hModule, "SubscriptionsProvEnumerate");
   ptr_SubscriptionsProvPullEnumerate = (__vartype(ptr_SubscriptionsProvPullEnumerate))GetProcAddress(hModule, "SubscriptionsProvPullEnumerate");
   ptr_SvchostPushServiceGlobals = (__vartype(ptr_SvchostPushServiceGlobals))GetProcAddress(hModule, "SvchostPushServiceGlobals");
   ptr_WSManAckEvents = (__vartype(ptr_WSManAckEvents))GetProcAddress(hModule, "WSManAckEvents");
   ptr_WSManAddSubscriptionManagerInternal = (__vartype(ptr_WSManAddSubscriptionManagerInternal))GetProcAddress(hModule, "WSManAddSubscriptionManagerInternal");
   ptr_WSManCloseCommand = (__vartype(ptr_WSManCloseCommand))GetProcAddress(hModule, "WSManCloseCommand");
   ptr_WSManCloseEnumerationHandle = (__vartype(ptr_WSManCloseEnumerationHandle))GetProcAddress(hModule, "WSManCloseEnumerationHandle");
   ptr_WSManCloseEnumeratorHandle = (__vartype(ptr_WSManCloseEnumeratorHandle))GetProcAddress(hModule, "WSManCloseEnumeratorHandle");
   ptr_WSManCloseObjectHandle = (__vartype(ptr_WSManCloseObjectHandle))GetProcAddress(hModule, "WSManCloseObjectHandle");
   ptr_WSManCloseOperation = (__vartype(ptr_WSManCloseOperation))GetProcAddress(hModule, "WSManCloseOperation");
   ptr_WSManClosePublisherHandle = (__vartype(ptr_WSManClosePublisherHandle))GetProcAddress(hModule, "WSManClosePublisherHandle");
   ptr_WSManCloseSession = (__vartype(ptr_WSManCloseSession))GetProcAddress(hModule, "WSManCloseSession");
   ptr_WSManCloseSessionHandle = (__vartype(ptr_WSManCloseSessionHandle))GetProcAddress(hModule, "WSManCloseSessionHandle");
   ptr_WSManCloseShell = (__vartype(ptr_WSManCloseShell))GetProcAddress(hModule, "WSManCloseShell");
   ptr_WSManCloseSubscriptionHandle = (__vartype(ptr_WSManCloseSubscriptionHandle))GetProcAddress(hModule, "WSManCloseSubscriptionHandle");
   ptr_WSManConstructError = (__vartype(ptr_WSManConstructError))GetProcAddress(hModule, "WSManConstructError");
   ptr_WSManCreateEnumeratorInternal = (__vartype(ptr_WSManCreateEnumeratorInternal))GetProcAddress(hModule, "WSManCreateEnumeratorInternal");
   ptr_WSManCreateInternal = (__vartype(ptr_WSManCreateInternal))GetProcAddress(hModule, "WSManCreateInternal");
   ptr_WSManCreateInternalEx = (__vartype(ptr_WSManCreateInternalEx))GetProcAddress(hModule, "WSManCreateInternalEx");
   ptr_WSManCreatePullSubscription = (__vartype(ptr_WSManCreatePullSubscription))GetProcAddress(hModule, "WSManCreatePullSubscription");
   ptr_WSManCreatePushSubscription = (__vartype(ptr_WSManCreatePushSubscription))GetProcAddress(hModule, "WSManCreatePushSubscription");
   ptr_WSManCreateSession = (__vartype(ptr_WSManCreateSession))GetProcAddress(hModule, "WSManCreateSession");
   ptr_WSManCreateSessionInternal = (__vartype(ptr_WSManCreateSessionInternal))GetProcAddress(hModule, "WSManCreateSessionInternal");
   ptr_WSManCreateShell = (__vartype(ptr_WSManCreateShell))GetProcAddress(hModule, "WSManCreateShell");
   ptr_WSManDecodeObject = (__vartype(ptr_WSManDecodeObject))GetProcAddress(hModule, "WSManDecodeObject");
   ptr_WSManDeinitialize = (__vartype(ptr_WSManDeinitialize))GetProcAddress(hModule, "WSManDeinitialize");
   ptr_WSManDeleteInternal = (__vartype(ptr_WSManDeleteInternal))GetProcAddress(hModule, "WSManDeleteInternal");
   ptr_WSManDeleteInternalEx = (__vartype(ptr_WSManDeleteInternalEx))GetProcAddress(hModule, "WSManDeleteInternalEx");
   ptr_WSManDeliverEndSubscriptionNotification = (__vartype(ptr_WSManDeliverEndSubscriptionNotification))GetProcAddress(hModule, "WSManDeliverEndSubscriptionNotification");
   ptr_WSManDeliverEvent = (__vartype(ptr_WSManDeliverEvent))GetProcAddress(hModule, "WSManDeliverEvent");
   ptr_WSManEncodeObject = (__vartype(ptr_WSManEncodeObject))GetProcAddress(hModule, "WSManEncodeObject");
   ptr_WSManEncodeObjectEx = (__vartype(ptr_WSManEncodeObjectEx))GetProcAddress(hModule, "WSManEncodeObjectEx");
   ptr_WSManEncodeObjectInternal = (__vartype(ptr_WSManEncodeObjectInternal))GetProcAddress(hModule, "WSManEncodeObjectInternal");
   ptr_WSManEnumerateInternal = (__vartype(ptr_WSManEnumerateInternal))GetProcAddress(hModule, "WSManEnumerateInternal");
   ptr_WSManEnumerateInternalEx = (__vartype(ptr_WSManEnumerateInternalEx))GetProcAddress(hModule, "WSManEnumerateInternalEx");
   ptr_WSManEnumeratorAddEvent = (__vartype(ptr_WSManEnumeratorAddEvent))GetProcAddress(hModule, "WSManEnumeratorAddEvent");
   ptr_WSManEnumeratorAddObject = (__vartype(ptr_WSManEnumeratorAddObject))GetProcAddress(hModule, "WSManEnumeratorAddObject");
   ptr_WSManEnumeratorBatchPolicyViolated = (__vartype(ptr_WSManEnumeratorBatchPolicyViolated))GetProcAddress(hModule, "WSManEnumeratorBatchPolicyViolated");
   ptr_WSManEnumeratorNextObject = (__vartype(ptr_WSManEnumeratorNextObject))GetProcAddress(hModule, "WSManEnumeratorNextObject");
   ptr_WSManEnumeratorObjectCount = (__vartype(ptr_WSManEnumeratorObjectCount))GetProcAddress(hModule, "WSManEnumeratorObjectCount");
   ptr_WSManGetErrorMessage = (__vartype(ptr_WSManGetErrorMessage))GetProcAddress(hModule, "WSManGetErrorMessage");
   ptr_WSManGetInternal = (__vartype(ptr_WSManGetInternal))GetProcAddress(hModule, "WSManGetInternal");
   ptr_WSManGetInternalEx = (__vartype(ptr_WSManGetInternalEx))GetProcAddress(hModule, "WSManGetInternalEx");
   ptr_WSManGetSessionOptionAsDword = (__vartype(ptr_WSManGetSessionOptionAsDword))GetProcAddress(hModule, "WSManGetSessionOptionAsDword");
   ptr_WSManGetSessionOptionAsString = (__vartype(ptr_WSManGetSessionOptionAsString))GetProcAddress(hModule, "WSManGetSessionOptionAsString");
   ptr_WSManIdentifyInternal = (__vartype(ptr_WSManIdentifyInternal))GetProcAddress(hModule, "WSManIdentifyInternal");
   ptr_WSManInitialize = (__vartype(ptr_WSManInitialize))GetProcAddress(hModule, "WSManInitialize");
   ptr_WSManInvokeInternal = (__vartype(ptr_WSManInvokeInternal))GetProcAddress(hModule, "WSManInvokeInternal");
   ptr_WSManInvokeInternalEx = (__vartype(ptr_WSManInvokeInternalEx))GetProcAddress(hModule, "WSManInvokeInternalEx");
   ptr_WSManPluginAuthzOperationComplete = (__vartype(ptr_WSManPluginAuthzOperationComplete))GetProcAddress(hModule, "WSManPluginAuthzOperationComplete");
   ptr_WSManPluginAuthzQueryQuotaComplete = (__vartype(ptr_WSManPluginAuthzQueryQuotaComplete))GetProcAddress(hModule, "WSManPluginAuthzQueryQuotaComplete");
   ptr_WSManPluginAuthzUserComplete = (__vartype(ptr_WSManPluginAuthzUserComplete))GetProcAddress(hModule, "WSManPluginAuthzUserComplete");
   ptr_WSManPluginFreeRequestDetails = (__vartype(ptr_WSManPluginFreeRequestDetails))GetProcAddress(hModule, "WSManPluginFreeRequestDetails");
   ptr_WSManPluginGetOperationParameters = (__vartype(ptr_WSManPluginGetOperationParameters))GetProcAddress(hModule, "WSManPluginGetOperationParameters");
   ptr_WSManPluginObjectAndBookmarkResult = (__vartype(ptr_WSManPluginObjectAndBookmarkResult))GetProcAddress(hModule, "WSManPluginObjectAndBookmarkResult");
   ptr_WSManPluginObjectAndEprResult = (__vartype(ptr_WSManPluginObjectAndEprResult))GetProcAddress(hModule, "WSManPluginObjectAndEprResult");
   ptr_WSManPluginObjectResult = (__vartype(ptr_WSManPluginObjectResult))GetProcAddress(hModule, "WSManPluginObjectResult");
   ptr_WSManPluginOperationComplete = (__vartype(ptr_WSManPluginOperationComplete))GetProcAddress(hModule, "WSManPluginOperationComplete");
   ptr_WSManPluginReceiveResult = (__vartype(ptr_WSManPluginReceiveResult))GetProcAddress(hModule, "WSManPluginReceiveResult");
   ptr_WSManPluginReportContext = (__vartype(ptr_WSManPluginReportContext))GetProcAddress(hModule, "WSManPluginReportContext");
   ptr_WSManPluginShutdown = (__vartype(ptr_WSManPluginShutdown))GetProcAddress(hModule, "WSManPluginShutdown");
   ptr_WSManPluginStartup = (__vartype(ptr_WSManPluginStartup))GetProcAddress(hModule, "WSManPluginStartup");
   ptr_WSManProvCreate = (__vartype(ptr_WSManProvCreate))GetProcAddress(hModule, "WSManProvCreate");
   ptr_WSManProvDelete = (__vartype(ptr_WSManProvDelete))GetProcAddress(hModule, "WSManProvDelete");
   ptr_WSManProvEndEnumerate = (__vartype(ptr_WSManProvEndEnumerate))GetProcAddress(hModule, "WSManProvEndEnumerate");
   ptr_WSManProvEnumerate = (__vartype(ptr_WSManProvEnumerate))GetProcAddress(hModule, "WSManProvEnumerate");
   ptr_WSManProvGet = (__vartype(ptr_WSManProvGet))GetProcAddress(hModule, "WSManProvGet");
   ptr_WSManProvInvoke = (__vartype(ptr_WSManProvInvoke))GetProcAddress(hModule, "WSManProvInvoke");
   ptr_WSManProvPullEnumerate = (__vartype(ptr_WSManProvPullEnumerate))GetProcAddress(hModule, "WSManProvPullEnumerate");
   ptr_WSManProvPut = (__vartype(ptr_WSManProvPut))GetProcAddress(hModule, "WSManProvPut");
   ptr_WSManPull = (__vartype(ptr_WSManPull))GetProcAddress(hModule, "WSManPull");
   ptr_WSManPullEvents = (__vartype(ptr_WSManPullEvents))GetProcAddress(hModule, "WSManPullEvents");
   ptr_WSManPutInternal = (__vartype(ptr_WSManPutInternal))GetProcAddress(hModule, "WSManPutInternal");
   ptr_WSManPutInternalEx = (__vartype(ptr_WSManPutInternalEx))GetProcAddress(hModule, "WSManPutInternalEx");
   ptr_WSManReceiveShellOutput = (__vartype(ptr_WSManReceiveShellOutput))GetProcAddress(hModule, "WSManReceiveShellOutput");
   ptr_WSManRemoveSubscriptionManagerInternal = (__vartype(ptr_WSManRemoveSubscriptionManagerInternal))GetProcAddress(hModule, "WSManRemoveSubscriptionManagerInternal");
   ptr_WSManRunShellCommand = (__vartype(ptr_WSManRunShellCommand))GetProcAddress(hModule, "WSManRunShellCommand");
   ptr_WSManSendShellInput = (__vartype(ptr_WSManSendShellInput))GetProcAddress(hModule, "WSManSendShellInput");
   ptr_WSManSetSessionOption = (__vartype(ptr_WSManSetSessionOption))GetProcAddress(hModule, "WSManSetSessionOption");
   ptr_WSManShellProvEndEnumerate = (__vartype(ptr_WSManShellProvEndEnumerate))GetProcAddress(hModule, "WSManShellProvEndEnumerate");
   ptr_WSManShellProvPullEnumerate = (__vartype(ptr_WSManShellProvPullEnumerate))GetProcAddress(hModule, "WSManShellProvPullEnumerate");
   ptr_WSManSignalShell = (__vartype(ptr_WSManSignalShell))GetProcAddress(hModule, "WSManSignalShell");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

