#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_FireVSDebugEvent;
void *ptr_FireVSDebugEvent = NULL;
extern void *ptr_TraceCloseLogFile;
void *ptr_TraceCloseLogFile = NULL;
extern void *ptr_TraceOpenLogFile;
void *ptr_TraceOpenLogFile = NULL;
extern void *ptr_TraceReturn;
void *ptr_TraceReturn = NULL;
extern void *ptr_TraceSQLAllocConnect;
void *ptr_TraceSQLAllocConnect = NULL;
extern void *ptr_TraceSQLAllocEnv;
void *ptr_TraceSQLAllocEnv = NULL;
extern void *ptr_TraceSQLAllocHandle;
void *ptr_TraceSQLAllocHandle = NULL;
extern void *ptr_TraceSQLAllocHandleStd;
void *ptr_TraceSQLAllocHandleStd = NULL;
extern void *ptr_TraceSQLAllocHandleStdW;
void *ptr_TraceSQLAllocHandleStdW = NULL;
extern void *ptr_TraceSQLAllocStmt;
void *ptr_TraceSQLAllocStmt = NULL;
extern void *ptr_TraceSQLBindCol;
void *ptr_TraceSQLBindCol = NULL;
extern void *ptr_TraceSQLBindParam;
void *ptr_TraceSQLBindParam = NULL;
extern void *ptr_TraceSQLBindParameter;
void *ptr_TraceSQLBindParameter = NULL;
extern void *ptr_TraceSQLBrowseConnect;
void *ptr_TraceSQLBrowseConnect = NULL;
extern void *ptr_TraceSQLBrowseConnectW;
void *ptr_TraceSQLBrowseConnectW = NULL;
extern void *ptr_TraceSQLBulkOperations;
void *ptr_TraceSQLBulkOperations = NULL;
extern void *ptr_TraceSQLCancel;
void *ptr_TraceSQLCancel = NULL;
extern void *ptr_TraceSQLCancelHandle;
void *ptr_TraceSQLCancelHandle = NULL;
extern void *ptr_TraceSQLCloseCursor;
void *ptr_TraceSQLCloseCursor = NULL;
extern void *ptr_TraceSQLColAttribute;
void *ptr_TraceSQLColAttribute = NULL;
extern void *ptr_TraceSQLColAttributeW;
void *ptr_TraceSQLColAttributeW = NULL;
extern void *ptr_TraceSQLColAttributes;
void *ptr_TraceSQLColAttributes = NULL;
extern void *ptr_TraceSQLColAttributesW;
void *ptr_TraceSQLColAttributesW = NULL;
extern void *ptr_TraceSQLColumnPrivileges;
void *ptr_TraceSQLColumnPrivileges = NULL;
extern void *ptr_TraceSQLColumnPrivilegesW;
void *ptr_TraceSQLColumnPrivilegesW = NULL;
extern void *ptr_TraceSQLColumns;
void *ptr_TraceSQLColumns = NULL;
extern void *ptr_TraceSQLColumnsW;
void *ptr_TraceSQLColumnsW = NULL;
extern void *ptr_TraceSQLConnect;
void *ptr_TraceSQLConnect = NULL;
extern void *ptr_TraceSQLConnectW;
void *ptr_TraceSQLConnectW = NULL;
extern void *ptr_TraceSQLCopyDesc;
void *ptr_TraceSQLCopyDesc = NULL;
extern void *ptr_TraceSQLDataSources;
void *ptr_TraceSQLDataSources = NULL;
extern void *ptr_TraceSQLDataSourcesW;
void *ptr_TraceSQLDataSourcesW = NULL;
extern void *ptr_TraceSQLDescribeCol;
void *ptr_TraceSQLDescribeCol = NULL;
extern void *ptr_TraceSQLDescribeColW;
void *ptr_TraceSQLDescribeColW = NULL;
extern void *ptr_TraceSQLDescribeParam;
void *ptr_TraceSQLDescribeParam = NULL;
extern void *ptr_TraceSQLDisconnect;
void *ptr_TraceSQLDisconnect = NULL;
extern void *ptr_TraceSQLDriverConnect;
void *ptr_TraceSQLDriverConnect = NULL;
extern void *ptr_TraceSQLDriverConnectW;
void *ptr_TraceSQLDriverConnectW = NULL;
extern void *ptr_TraceSQLDrivers;
void *ptr_TraceSQLDrivers = NULL;
extern void *ptr_TraceSQLDriversW;
void *ptr_TraceSQLDriversW = NULL;
extern void *ptr_TraceSQLEndTran;
void *ptr_TraceSQLEndTran = NULL;
extern void *ptr_TraceSQLError;
void *ptr_TraceSQLError = NULL;
extern void *ptr_TraceSQLErrorW;
void *ptr_TraceSQLErrorW = NULL;
extern void *ptr_TraceSQLExecDirect;
void *ptr_TraceSQLExecDirect = NULL;
extern void *ptr_TraceSQLExecDirectW;
void *ptr_TraceSQLExecDirectW = NULL;
extern void *ptr_TraceSQLExecute;
void *ptr_TraceSQLExecute = NULL;
extern void *ptr_TraceSQLExtendedFetch;
void *ptr_TraceSQLExtendedFetch = NULL;
extern void *ptr_TraceSQLFetch;
void *ptr_TraceSQLFetch = NULL;
extern void *ptr_TraceSQLFetchScroll;
void *ptr_TraceSQLFetchScroll = NULL;
extern void *ptr_TraceSQLForeignKeys;
void *ptr_TraceSQLForeignKeys = NULL;
extern void *ptr_TraceSQLForeignKeysW;
void *ptr_TraceSQLForeignKeysW = NULL;
extern void *ptr_TraceSQLFreeConnect;
void *ptr_TraceSQLFreeConnect = NULL;
extern void *ptr_TraceSQLFreeEnv;
void *ptr_TraceSQLFreeEnv = NULL;
extern void *ptr_TraceSQLFreeHandle;
void *ptr_TraceSQLFreeHandle = NULL;
extern void *ptr_TraceSQLFreeStmt;
void *ptr_TraceSQLFreeStmt = NULL;
extern void *ptr_TraceSQLGetConnectAttr;
void *ptr_TraceSQLGetConnectAttr = NULL;
extern void *ptr_TraceSQLGetConnectAttrW;
void *ptr_TraceSQLGetConnectAttrW = NULL;
extern void *ptr_TraceSQLGetConnectOption;
void *ptr_TraceSQLGetConnectOption = NULL;
extern void *ptr_TraceSQLGetConnectOptionW;
void *ptr_TraceSQLGetConnectOptionW = NULL;
extern void *ptr_TraceSQLGetCursorName;
void *ptr_TraceSQLGetCursorName = NULL;
extern void *ptr_TraceSQLGetCursorNameW;
void *ptr_TraceSQLGetCursorNameW = NULL;
extern void *ptr_TraceSQLGetData;
void *ptr_TraceSQLGetData = NULL;
extern void *ptr_TraceSQLGetDescField;
void *ptr_TraceSQLGetDescField = NULL;
extern void *ptr_TraceSQLGetDescFieldW;
void *ptr_TraceSQLGetDescFieldW = NULL;
extern void *ptr_TraceSQLGetDescRec;
void *ptr_TraceSQLGetDescRec = NULL;
extern void *ptr_TraceSQLGetDescRecW;
void *ptr_TraceSQLGetDescRecW = NULL;
extern void *ptr_TraceSQLGetDiagField;
void *ptr_TraceSQLGetDiagField = NULL;
extern void *ptr_TraceSQLGetDiagFieldW;
void *ptr_TraceSQLGetDiagFieldW = NULL;
extern void *ptr_TraceSQLGetDiagRec;
void *ptr_TraceSQLGetDiagRec = NULL;
extern void *ptr_TraceSQLGetDiagRecW;
void *ptr_TraceSQLGetDiagRecW = NULL;
extern void *ptr_TraceSQLGetEnvAttr;
void *ptr_TraceSQLGetEnvAttr = NULL;
extern void *ptr_TraceSQLGetFunctions;
void *ptr_TraceSQLGetFunctions = NULL;
extern void *ptr_TraceSQLGetInfo;
void *ptr_TraceSQLGetInfo = NULL;
extern void *ptr_TraceSQLGetInfoW;
void *ptr_TraceSQLGetInfoW = NULL;
extern void *ptr_TraceSQLGetStmtAttr;
void *ptr_TraceSQLGetStmtAttr = NULL;
extern void *ptr_TraceSQLGetStmtAttrW;
void *ptr_TraceSQLGetStmtAttrW = NULL;
extern void *ptr_TraceSQLGetStmtOption;
void *ptr_TraceSQLGetStmtOption = NULL;
extern void *ptr_TraceSQLGetTypeInfo;
void *ptr_TraceSQLGetTypeInfo = NULL;
extern void *ptr_TraceSQLGetTypeInfoW;
void *ptr_TraceSQLGetTypeInfoW = NULL;
extern void *ptr_TraceSQLMoreResults;
void *ptr_TraceSQLMoreResults = NULL;
extern void *ptr_TraceSQLNativeSql;
void *ptr_TraceSQLNativeSql = NULL;
extern void *ptr_TraceSQLNativeSqlW;
void *ptr_TraceSQLNativeSqlW = NULL;
extern void *ptr_TraceSQLNumParams;
void *ptr_TraceSQLNumParams = NULL;
extern void *ptr_TraceSQLNumResultCols;
void *ptr_TraceSQLNumResultCols = NULL;
extern void *ptr_TraceSQLParamData;
void *ptr_TraceSQLParamData = NULL;
extern void *ptr_TraceSQLParamOptions;
void *ptr_TraceSQLParamOptions = NULL;
extern void *ptr_TraceSQLPrepare;
void *ptr_TraceSQLPrepare = NULL;
extern void *ptr_TraceSQLPrepareW;
void *ptr_TraceSQLPrepareW = NULL;
extern void *ptr_TraceSQLPrimaryKeys;
void *ptr_TraceSQLPrimaryKeys = NULL;
extern void *ptr_TraceSQLPrimaryKeysW;
void *ptr_TraceSQLPrimaryKeysW = NULL;
extern void *ptr_TraceSQLProcedureColumns;
void *ptr_TraceSQLProcedureColumns = NULL;
extern void *ptr_TraceSQLProcedureColumnsW;
void *ptr_TraceSQLProcedureColumnsW = NULL;
extern void *ptr_TraceSQLProcedures;
void *ptr_TraceSQLProcedures = NULL;
extern void *ptr_TraceSQLProceduresW;
void *ptr_TraceSQLProceduresW = NULL;
extern void *ptr_TraceSQLPutData;
void *ptr_TraceSQLPutData = NULL;
extern void *ptr_TraceSQLRowCount;
void *ptr_TraceSQLRowCount = NULL;
extern void *ptr_TraceSQLSetConnectAttr;
void *ptr_TraceSQLSetConnectAttr = NULL;
extern void *ptr_TraceSQLSetConnectAttrW;
void *ptr_TraceSQLSetConnectAttrW = NULL;
extern void *ptr_TraceSQLSetConnectOption;
void *ptr_TraceSQLSetConnectOption = NULL;
extern void *ptr_TraceSQLSetConnectOptionW;
void *ptr_TraceSQLSetConnectOptionW = NULL;
extern void *ptr_TraceSQLSetCursorName;
void *ptr_TraceSQLSetCursorName = NULL;
extern void *ptr_TraceSQLSetCursorNameW;
void *ptr_TraceSQLSetCursorNameW = NULL;
extern void *ptr_TraceSQLSetDescField;
void *ptr_TraceSQLSetDescField = NULL;
extern void *ptr_TraceSQLSetDescFieldW;
void *ptr_TraceSQLSetDescFieldW = NULL;
extern void *ptr_TraceSQLSetDescRec;
void *ptr_TraceSQLSetDescRec = NULL;
extern void *ptr_TraceSQLSetEnvAttr;
void *ptr_TraceSQLSetEnvAttr = NULL;
extern void *ptr_TraceSQLSetParam;
void *ptr_TraceSQLSetParam = NULL;
extern void *ptr_TraceSQLSetPos;
void *ptr_TraceSQLSetPos = NULL;
extern void *ptr_TraceSQLSetScrollOptions;
void *ptr_TraceSQLSetScrollOptions = NULL;
extern void *ptr_TraceSQLSetStmtAttr;
void *ptr_TraceSQLSetStmtAttr = NULL;
extern void *ptr_TraceSQLSetStmtAttrW;
void *ptr_TraceSQLSetStmtAttrW = NULL;
extern void *ptr_TraceSQLSetStmtOption;
void *ptr_TraceSQLSetStmtOption = NULL;
extern void *ptr_TraceSQLSpecialColumns;
void *ptr_TraceSQLSpecialColumns = NULL;
extern void *ptr_TraceSQLSpecialColumnsW;
void *ptr_TraceSQLSpecialColumnsW = NULL;
extern void *ptr_TraceSQLStatistics;
void *ptr_TraceSQLStatistics = NULL;
extern void *ptr_TraceSQLStatisticsW;
void *ptr_TraceSQLStatisticsW = NULL;
extern void *ptr_TraceSQLTablePrivileges;
void *ptr_TraceSQLTablePrivileges = NULL;
extern void *ptr_TraceSQLTablePrivilegesW;
void *ptr_TraceSQLTablePrivilegesW = NULL;
extern void *ptr_TraceSQLTables;
void *ptr_TraceSQLTables = NULL;
extern void *ptr_TraceSQLTablesW;
void *ptr_TraceSQLTablesW = NULL;
extern void *ptr_TraceSQLTransact;
void *ptr_TraceSQLTransact = NULL;
extern void *ptr_TraceVSControl;
void *ptr_TraceVSControl = NULL;
extern void *ptr_TraceVersion;
void *ptr_TraceVersion = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\odbctrac.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_FireVSDebugEvent = (__vartype(ptr_FireVSDebugEvent))GetProcAddress(hModule, "FireVSDebugEvent");
   ptr_TraceCloseLogFile = (__vartype(ptr_TraceCloseLogFile))GetProcAddress(hModule, "TraceCloseLogFile");
   ptr_TraceOpenLogFile = (__vartype(ptr_TraceOpenLogFile))GetProcAddress(hModule, "TraceOpenLogFile");
   ptr_TraceReturn = (__vartype(ptr_TraceReturn))GetProcAddress(hModule, "TraceReturn");
   ptr_TraceSQLAllocConnect = (__vartype(ptr_TraceSQLAllocConnect))GetProcAddress(hModule, "TraceSQLAllocConnect");
   ptr_TraceSQLAllocEnv = (__vartype(ptr_TraceSQLAllocEnv))GetProcAddress(hModule, "TraceSQLAllocEnv");
   ptr_TraceSQLAllocHandle = (__vartype(ptr_TraceSQLAllocHandle))GetProcAddress(hModule, "TraceSQLAllocHandle");
   ptr_TraceSQLAllocHandleStd = (__vartype(ptr_TraceSQLAllocHandleStd))GetProcAddress(hModule, "TraceSQLAllocHandleStd");
   ptr_TraceSQLAllocHandleStdW = (__vartype(ptr_TraceSQLAllocHandleStdW))GetProcAddress(hModule, "TraceSQLAllocHandleStdW");
   ptr_TraceSQLAllocStmt = (__vartype(ptr_TraceSQLAllocStmt))GetProcAddress(hModule, "TraceSQLAllocStmt");
   ptr_TraceSQLBindCol = (__vartype(ptr_TraceSQLBindCol))GetProcAddress(hModule, "TraceSQLBindCol");
   ptr_TraceSQLBindParam = (__vartype(ptr_TraceSQLBindParam))GetProcAddress(hModule, "TraceSQLBindParam");
   ptr_TraceSQLBindParameter = (__vartype(ptr_TraceSQLBindParameter))GetProcAddress(hModule, "TraceSQLBindParameter");
   ptr_TraceSQLBrowseConnect = (__vartype(ptr_TraceSQLBrowseConnect))GetProcAddress(hModule, "TraceSQLBrowseConnect");
   ptr_TraceSQLBrowseConnectW = (__vartype(ptr_TraceSQLBrowseConnectW))GetProcAddress(hModule, "TraceSQLBrowseConnectW");
   ptr_TraceSQLBulkOperations = (__vartype(ptr_TraceSQLBulkOperations))GetProcAddress(hModule, "TraceSQLBulkOperations");
   ptr_TraceSQLCancel = (__vartype(ptr_TraceSQLCancel))GetProcAddress(hModule, "TraceSQLCancel");
   ptr_TraceSQLCancelHandle = (__vartype(ptr_TraceSQLCancelHandle))GetProcAddress(hModule, "TraceSQLCancelHandle");
   ptr_TraceSQLCloseCursor = (__vartype(ptr_TraceSQLCloseCursor))GetProcAddress(hModule, "TraceSQLCloseCursor");
   ptr_TraceSQLColAttribute = (__vartype(ptr_TraceSQLColAttribute))GetProcAddress(hModule, "TraceSQLColAttribute");
   ptr_TraceSQLColAttributeW = (__vartype(ptr_TraceSQLColAttributeW))GetProcAddress(hModule, "TraceSQLColAttributeW");
   ptr_TraceSQLColAttributes = (__vartype(ptr_TraceSQLColAttributes))GetProcAddress(hModule, "TraceSQLColAttributes");
   ptr_TraceSQLColAttributesW = (__vartype(ptr_TraceSQLColAttributesW))GetProcAddress(hModule, "TraceSQLColAttributesW");
   ptr_TraceSQLColumnPrivileges = (__vartype(ptr_TraceSQLColumnPrivileges))GetProcAddress(hModule, "TraceSQLColumnPrivileges");
   ptr_TraceSQLColumnPrivilegesW = (__vartype(ptr_TraceSQLColumnPrivilegesW))GetProcAddress(hModule, "TraceSQLColumnPrivilegesW");
   ptr_TraceSQLColumns = (__vartype(ptr_TraceSQLColumns))GetProcAddress(hModule, "TraceSQLColumns");
   ptr_TraceSQLColumnsW = (__vartype(ptr_TraceSQLColumnsW))GetProcAddress(hModule, "TraceSQLColumnsW");
   ptr_TraceSQLConnect = (__vartype(ptr_TraceSQLConnect))GetProcAddress(hModule, "TraceSQLConnect");
   ptr_TraceSQLConnectW = (__vartype(ptr_TraceSQLConnectW))GetProcAddress(hModule, "TraceSQLConnectW");
   ptr_TraceSQLCopyDesc = (__vartype(ptr_TraceSQLCopyDesc))GetProcAddress(hModule, "TraceSQLCopyDesc");
   ptr_TraceSQLDataSources = (__vartype(ptr_TraceSQLDataSources))GetProcAddress(hModule, "TraceSQLDataSources");
   ptr_TraceSQLDataSourcesW = (__vartype(ptr_TraceSQLDataSourcesW))GetProcAddress(hModule, "TraceSQLDataSourcesW");
   ptr_TraceSQLDescribeCol = (__vartype(ptr_TraceSQLDescribeCol))GetProcAddress(hModule, "TraceSQLDescribeCol");
   ptr_TraceSQLDescribeColW = (__vartype(ptr_TraceSQLDescribeColW))GetProcAddress(hModule, "TraceSQLDescribeColW");
   ptr_TraceSQLDescribeParam = (__vartype(ptr_TraceSQLDescribeParam))GetProcAddress(hModule, "TraceSQLDescribeParam");
   ptr_TraceSQLDisconnect = (__vartype(ptr_TraceSQLDisconnect))GetProcAddress(hModule, "TraceSQLDisconnect");
   ptr_TraceSQLDriverConnect = (__vartype(ptr_TraceSQLDriverConnect))GetProcAddress(hModule, "TraceSQLDriverConnect");
   ptr_TraceSQLDriverConnectW = (__vartype(ptr_TraceSQLDriverConnectW))GetProcAddress(hModule, "TraceSQLDriverConnectW");
   ptr_TraceSQLDrivers = (__vartype(ptr_TraceSQLDrivers))GetProcAddress(hModule, "TraceSQLDrivers");
   ptr_TraceSQLDriversW = (__vartype(ptr_TraceSQLDriversW))GetProcAddress(hModule, "TraceSQLDriversW");
   ptr_TraceSQLEndTran = (__vartype(ptr_TraceSQLEndTran))GetProcAddress(hModule, "TraceSQLEndTran");
   ptr_TraceSQLError = (__vartype(ptr_TraceSQLError))GetProcAddress(hModule, "TraceSQLError");
   ptr_TraceSQLErrorW = (__vartype(ptr_TraceSQLErrorW))GetProcAddress(hModule, "TraceSQLErrorW");
   ptr_TraceSQLExecDirect = (__vartype(ptr_TraceSQLExecDirect))GetProcAddress(hModule, "TraceSQLExecDirect");
   ptr_TraceSQLExecDirectW = (__vartype(ptr_TraceSQLExecDirectW))GetProcAddress(hModule, "TraceSQLExecDirectW");
   ptr_TraceSQLExecute = (__vartype(ptr_TraceSQLExecute))GetProcAddress(hModule, "TraceSQLExecute");
   ptr_TraceSQLExtendedFetch = (__vartype(ptr_TraceSQLExtendedFetch))GetProcAddress(hModule, "TraceSQLExtendedFetch");
   ptr_TraceSQLFetch = (__vartype(ptr_TraceSQLFetch))GetProcAddress(hModule, "TraceSQLFetch");
   ptr_TraceSQLFetchScroll = (__vartype(ptr_TraceSQLFetchScroll))GetProcAddress(hModule, "TraceSQLFetchScroll");
   ptr_TraceSQLForeignKeys = (__vartype(ptr_TraceSQLForeignKeys))GetProcAddress(hModule, "TraceSQLForeignKeys");
   ptr_TraceSQLForeignKeysW = (__vartype(ptr_TraceSQLForeignKeysW))GetProcAddress(hModule, "TraceSQLForeignKeysW");
   ptr_TraceSQLFreeConnect = (__vartype(ptr_TraceSQLFreeConnect))GetProcAddress(hModule, "TraceSQLFreeConnect");
   ptr_TraceSQLFreeEnv = (__vartype(ptr_TraceSQLFreeEnv))GetProcAddress(hModule, "TraceSQLFreeEnv");
   ptr_TraceSQLFreeHandle = (__vartype(ptr_TraceSQLFreeHandle))GetProcAddress(hModule, "TraceSQLFreeHandle");
   ptr_TraceSQLFreeStmt = (__vartype(ptr_TraceSQLFreeStmt))GetProcAddress(hModule, "TraceSQLFreeStmt");
   ptr_TraceSQLGetConnectAttr = (__vartype(ptr_TraceSQLGetConnectAttr))GetProcAddress(hModule, "TraceSQLGetConnectAttr");
   ptr_TraceSQLGetConnectAttrW = (__vartype(ptr_TraceSQLGetConnectAttrW))GetProcAddress(hModule, "TraceSQLGetConnectAttrW");
   ptr_TraceSQLGetConnectOption = (__vartype(ptr_TraceSQLGetConnectOption))GetProcAddress(hModule, "TraceSQLGetConnectOption");
   ptr_TraceSQLGetConnectOptionW = (__vartype(ptr_TraceSQLGetConnectOptionW))GetProcAddress(hModule, "TraceSQLGetConnectOptionW");
   ptr_TraceSQLGetCursorName = (__vartype(ptr_TraceSQLGetCursorName))GetProcAddress(hModule, "TraceSQLGetCursorName");
   ptr_TraceSQLGetCursorNameW = (__vartype(ptr_TraceSQLGetCursorNameW))GetProcAddress(hModule, "TraceSQLGetCursorNameW");
   ptr_TraceSQLGetData = (__vartype(ptr_TraceSQLGetData))GetProcAddress(hModule, "TraceSQLGetData");
   ptr_TraceSQLGetDescField = (__vartype(ptr_TraceSQLGetDescField))GetProcAddress(hModule, "TraceSQLGetDescField");
   ptr_TraceSQLGetDescFieldW = (__vartype(ptr_TraceSQLGetDescFieldW))GetProcAddress(hModule, "TraceSQLGetDescFieldW");
   ptr_TraceSQLGetDescRec = (__vartype(ptr_TraceSQLGetDescRec))GetProcAddress(hModule, "TraceSQLGetDescRec");
   ptr_TraceSQLGetDescRecW = (__vartype(ptr_TraceSQLGetDescRecW))GetProcAddress(hModule, "TraceSQLGetDescRecW");
   ptr_TraceSQLGetDiagField = (__vartype(ptr_TraceSQLGetDiagField))GetProcAddress(hModule, "TraceSQLGetDiagField");
   ptr_TraceSQLGetDiagFieldW = (__vartype(ptr_TraceSQLGetDiagFieldW))GetProcAddress(hModule, "TraceSQLGetDiagFieldW");
   ptr_TraceSQLGetDiagRec = (__vartype(ptr_TraceSQLGetDiagRec))GetProcAddress(hModule, "TraceSQLGetDiagRec");
   ptr_TraceSQLGetDiagRecW = (__vartype(ptr_TraceSQLGetDiagRecW))GetProcAddress(hModule, "TraceSQLGetDiagRecW");
   ptr_TraceSQLGetEnvAttr = (__vartype(ptr_TraceSQLGetEnvAttr))GetProcAddress(hModule, "TraceSQLGetEnvAttr");
   ptr_TraceSQLGetFunctions = (__vartype(ptr_TraceSQLGetFunctions))GetProcAddress(hModule, "TraceSQLGetFunctions");
   ptr_TraceSQLGetInfo = (__vartype(ptr_TraceSQLGetInfo))GetProcAddress(hModule, "TraceSQLGetInfo");
   ptr_TraceSQLGetInfoW = (__vartype(ptr_TraceSQLGetInfoW))GetProcAddress(hModule, "TraceSQLGetInfoW");
   ptr_TraceSQLGetStmtAttr = (__vartype(ptr_TraceSQLGetStmtAttr))GetProcAddress(hModule, "TraceSQLGetStmtAttr");
   ptr_TraceSQLGetStmtAttrW = (__vartype(ptr_TraceSQLGetStmtAttrW))GetProcAddress(hModule, "TraceSQLGetStmtAttrW");
   ptr_TraceSQLGetStmtOption = (__vartype(ptr_TraceSQLGetStmtOption))GetProcAddress(hModule, "TraceSQLGetStmtOption");
   ptr_TraceSQLGetTypeInfo = (__vartype(ptr_TraceSQLGetTypeInfo))GetProcAddress(hModule, "TraceSQLGetTypeInfo");
   ptr_TraceSQLGetTypeInfoW = (__vartype(ptr_TraceSQLGetTypeInfoW))GetProcAddress(hModule, "TraceSQLGetTypeInfoW");
   ptr_TraceSQLMoreResults = (__vartype(ptr_TraceSQLMoreResults))GetProcAddress(hModule, "TraceSQLMoreResults");
   ptr_TraceSQLNativeSql = (__vartype(ptr_TraceSQLNativeSql))GetProcAddress(hModule, "TraceSQLNativeSql");
   ptr_TraceSQLNativeSqlW = (__vartype(ptr_TraceSQLNativeSqlW))GetProcAddress(hModule, "TraceSQLNativeSqlW");
   ptr_TraceSQLNumParams = (__vartype(ptr_TraceSQLNumParams))GetProcAddress(hModule, "TraceSQLNumParams");
   ptr_TraceSQLNumResultCols = (__vartype(ptr_TraceSQLNumResultCols))GetProcAddress(hModule, "TraceSQLNumResultCols");
   ptr_TraceSQLParamData = (__vartype(ptr_TraceSQLParamData))GetProcAddress(hModule, "TraceSQLParamData");
   ptr_TraceSQLParamOptions = (__vartype(ptr_TraceSQLParamOptions))GetProcAddress(hModule, "TraceSQLParamOptions");
   ptr_TraceSQLPrepare = (__vartype(ptr_TraceSQLPrepare))GetProcAddress(hModule, "TraceSQLPrepare");
   ptr_TraceSQLPrepareW = (__vartype(ptr_TraceSQLPrepareW))GetProcAddress(hModule, "TraceSQLPrepareW");
   ptr_TraceSQLPrimaryKeys = (__vartype(ptr_TraceSQLPrimaryKeys))GetProcAddress(hModule, "TraceSQLPrimaryKeys");
   ptr_TraceSQLPrimaryKeysW = (__vartype(ptr_TraceSQLPrimaryKeysW))GetProcAddress(hModule, "TraceSQLPrimaryKeysW");
   ptr_TraceSQLProcedureColumns = (__vartype(ptr_TraceSQLProcedureColumns))GetProcAddress(hModule, "TraceSQLProcedureColumns");
   ptr_TraceSQLProcedureColumnsW = (__vartype(ptr_TraceSQLProcedureColumnsW))GetProcAddress(hModule, "TraceSQLProcedureColumnsW");
   ptr_TraceSQLProcedures = (__vartype(ptr_TraceSQLProcedures))GetProcAddress(hModule, "TraceSQLProcedures");
   ptr_TraceSQLProceduresW = (__vartype(ptr_TraceSQLProceduresW))GetProcAddress(hModule, "TraceSQLProceduresW");
   ptr_TraceSQLPutData = (__vartype(ptr_TraceSQLPutData))GetProcAddress(hModule, "TraceSQLPutData");
   ptr_TraceSQLRowCount = (__vartype(ptr_TraceSQLRowCount))GetProcAddress(hModule, "TraceSQLRowCount");
   ptr_TraceSQLSetConnectAttr = (__vartype(ptr_TraceSQLSetConnectAttr))GetProcAddress(hModule, "TraceSQLSetConnectAttr");
   ptr_TraceSQLSetConnectAttrW = (__vartype(ptr_TraceSQLSetConnectAttrW))GetProcAddress(hModule, "TraceSQLSetConnectAttrW");
   ptr_TraceSQLSetConnectOption = (__vartype(ptr_TraceSQLSetConnectOption))GetProcAddress(hModule, "TraceSQLSetConnectOption");
   ptr_TraceSQLSetConnectOptionW = (__vartype(ptr_TraceSQLSetConnectOptionW))GetProcAddress(hModule, "TraceSQLSetConnectOptionW");
   ptr_TraceSQLSetCursorName = (__vartype(ptr_TraceSQLSetCursorName))GetProcAddress(hModule, "TraceSQLSetCursorName");
   ptr_TraceSQLSetCursorNameW = (__vartype(ptr_TraceSQLSetCursorNameW))GetProcAddress(hModule, "TraceSQLSetCursorNameW");
   ptr_TraceSQLSetDescField = (__vartype(ptr_TraceSQLSetDescField))GetProcAddress(hModule, "TraceSQLSetDescField");
   ptr_TraceSQLSetDescFieldW = (__vartype(ptr_TraceSQLSetDescFieldW))GetProcAddress(hModule, "TraceSQLSetDescFieldW");
   ptr_TraceSQLSetDescRec = (__vartype(ptr_TraceSQLSetDescRec))GetProcAddress(hModule, "TraceSQLSetDescRec");
   ptr_TraceSQLSetEnvAttr = (__vartype(ptr_TraceSQLSetEnvAttr))GetProcAddress(hModule, "TraceSQLSetEnvAttr");
   ptr_TraceSQLSetParam = (__vartype(ptr_TraceSQLSetParam))GetProcAddress(hModule, "TraceSQLSetParam");
   ptr_TraceSQLSetPos = (__vartype(ptr_TraceSQLSetPos))GetProcAddress(hModule, "TraceSQLSetPos");
   ptr_TraceSQLSetScrollOptions = (__vartype(ptr_TraceSQLSetScrollOptions))GetProcAddress(hModule, "TraceSQLSetScrollOptions");
   ptr_TraceSQLSetStmtAttr = (__vartype(ptr_TraceSQLSetStmtAttr))GetProcAddress(hModule, "TraceSQLSetStmtAttr");
   ptr_TraceSQLSetStmtAttrW = (__vartype(ptr_TraceSQLSetStmtAttrW))GetProcAddress(hModule, "TraceSQLSetStmtAttrW");
   ptr_TraceSQLSetStmtOption = (__vartype(ptr_TraceSQLSetStmtOption))GetProcAddress(hModule, "TraceSQLSetStmtOption");
   ptr_TraceSQLSpecialColumns = (__vartype(ptr_TraceSQLSpecialColumns))GetProcAddress(hModule, "TraceSQLSpecialColumns");
   ptr_TraceSQLSpecialColumnsW = (__vartype(ptr_TraceSQLSpecialColumnsW))GetProcAddress(hModule, "TraceSQLSpecialColumnsW");
   ptr_TraceSQLStatistics = (__vartype(ptr_TraceSQLStatistics))GetProcAddress(hModule, "TraceSQLStatistics");
   ptr_TraceSQLStatisticsW = (__vartype(ptr_TraceSQLStatisticsW))GetProcAddress(hModule, "TraceSQLStatisticsW");
   ptr_TraceSQLTablePrivileges = (__vartype(ptr_TraceSQLTablePrivileges))GetProcAddress(hModule, "TraceSQLTablePrivileges");
   ptr_TraceSQLTablePrivilegesW = (__vartype(ptr_TraceSQLTablePrivilegesW))GetProcAddress(hModule, "TraceSQLTablePrivilegesW");
   ptr_TraceSQLTables = (__vartype(ptr_TraceSQLTables))GetProcAddress(hModule, "TraceSQLTables");
   ptr_TraceSQLTablesW = (__vartype(ptr_TraceSQLTablesW))GetProcAddress(hModule, "TraceSQLTablesW");
   ptr_TraceSQLTransact = (__vartype(ptr_TraceSQLTransact))GetProcAddress(hModule, "TraceSQLTransact");
   ptr_TraceVSControl = (__vartype(ptr_TraceVSControl))GetProcAddress(hModule, "TraceVSControl");
   ptr_TraceVersion = (__vartype(ptr_TraceVersion))GetProcAddress(hModule, "TraceVersion");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

