#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_DllGetClassObject;
void *ptr_DllGetClassObject = NULL;
extern void *ptr_IEnumString_Next_WIC_Proxy;
void *ptr_IEnumString_Next_WIC_Proxy = NULL;
extern void *ptr_IEnumString_Reset_WIC_Proxy;
void *ptr_IEnumString_Reset_WIC_Proxy = NULL;
extern void *ptr_IPropertyBag2_Write_Proxy;
void *ptr_IPropertyBag2_Write_Proxy = NULL;
extern void *ptr_IWICBitmapClipper_Initialize_Proxy;
void *ptr_IWICBitmapClipper_Initialize_Proxy = NULL;
extern void *ptr_IWICBitmapCodecInfo_DoesSupportAnimation_Proxy;
void *ptr_IWICBitmapCodecInfo_DoesSupportAnimation_Proxy = NULL;
extern void *ptr_IWICBitmapCodecInfo_DoesSupportLossless_Proxy;
void *ptr_IWICBitmapCodecInfo_DoesSupportLossless_Proxy = NULL;
extern void *ptr_IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy;
void *ptr_IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy = NULL;
extern void *ptr_IWICBitmapCodecInfo_GetContainerFormat_Proxy;
void *ptr_IWICBitmapCodecInfo_GetContainerFormat_Proxy = NULL;
extern void *ptr_IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy;
void *ptr_IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy = NULL;
extern void *ptr_IWICBitmapCodecInfo_GetDeviceModels_Proxy;
void *ptr_IWICBitmapCodecInfo_GetDeviceModels_Proxy = NULL;
extern void *ptr_IWICBitmapCodecInfo_GetFileExtensions_Proxy;
void *ptr_IWICBitmapCodecInfo_GetFileExtensions_Proxy = NULL;
extern void *ptr_IWICBitmapCodecInfo_GetMimeTypes_Proxy;
void *ptr_IWICBitmapCodecInfo_GetMimeTypes_Proxy = NULL;
extern void *ptr_IWICBitmapDecoder_CopyPalette_Proxy;
void *ptr_IWICBitmapDecoder_CopyPalette_Proxy = NULL;
extern void *ptr_IWICBitmapDecoder_GetColorContexts_Proxy;
void *ptr_IWICBitmapDecoder_GetColorContexts_Proxy = NULL;
extern void *ptr_IWICBitmapDecoder_GetDecoderInfo_Proxy;
void *ptr_IWICBitmapDecoder_GetDecoderInfo_Proxy = NULL;
extern void *ptr_IWICBitmapDecoder_GetFrameCount_Proxy;
void *ptr_IWICBitmapDecoder_GetFrameCount_Proxy = NULL;
extern void *ptr_IWICBitmapDecoder_GetFrame_Proxy;
void *ptr_IWICBitmapDecoder_GetFrame_Proxy = NULL;
extern void *ptr_IWICBitmapDecoder_GetMetadataQueryReader_Proxy;
void *ptr_IWICBitmapDecoder_GetMetadataQueryReader_Proxy = NULL;
extern void *ptr_IWICBitmapDecoder_GetPreview_Proxy;
void *ptr_IWICBitmapDecoder_GetPreview_Proxy = NULL;
extern void *ptr_IWICBitmapDecoder_GetThumbnail_Proxy;
void *ptr_IWICBitmapDecoder_GetThumbnail_Proxy = NULL;
extern void *ptr_IWICBitmapEncoder_Commit_Proxy;
void *ptr_IWICBitmapEncoder_Commit_Proxy = NULL;
extern void *ptr_IWICBitmapEncoder_CreateNewFrame_Proxy;
void *ptr_IWICBitmapEncoder_CreateNewFrame_Proxy = NULL;
extern void *ptr_IWICBitmapEncoder_GetEncoderInfo_Proxy;
void *ptr_IWICBitmapEncoder_GetEncoderInfo_Proxy = NULL;
extern void *ptr_IWICBitmapEncoder_GetMetadataQueryWriter_Proxy;
void *ptr_IWICBitmapEncoder_GetMetadataQueryWriter_Proxy = NULL;
extern void *ptr_IWICBitmapEncoder_Initialize_Proxy;
void *ptr_IWICBitmapEncoder_Initialize_Proxy = NULL;
extern void *ptr_IWICBitmapEncoder_SetPalette_Proxy;
void *ptr_IWICBitmapEncoder_SetPalette_Proxy = NULL;
extern void *ptr_IWICBitmapEncoder_SetThumbnail_Proxy;
void *ptr_IWICBitmapEncoder_SetThumbnail_Proxy = NULL;
extern void *ptr_IWICBitmapFlipRotator_Initialize_Proxy;
void *ptr_IWICBitmapFlipRotator_Initialize_Proxy = NULL;
extern void *ptr_IWICBitmapFrameDecode_GetColorContexts_Proxy;
void *ptr_IWICBitmapFrameDecode_GetColorContexts_Proxy = NULL;
extern void *ptr_IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy;
void *ptr_IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy = NULL;
extern void *ptr_IWICBitmapFrameDecode_GetThumbnail_Proxy;
void *ptr_IWICBitmapFrameDecode_GetThumbnail_Proxy = NULL;
extern void *ptr_IWICBitmapFrameEncode_Commit_Proxy;
void *ptr_IWICBitmapFrameEncode_Commit_Proxy = NULL;
extern void *ptr_IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy;
void *ptr_IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy = NULL;
extern void *ptr_IWICBitmapFrameEncode_Initialize_Proxy;
void *ptr_IWICBitmapFrameEncode_Initialize_Proxy = NULL;
extern void *ptr_IWICBitmapFrameEncode_SetColorContexts_Proxy;
void *ptr_IWICBitmapFrameEncode_SetColorContexts_Proxy = NULL;
extern void *ptr_IWICBitmapFrameEncode_SetResolution_Proxy;
void *ptr_IWICBitmapFrameEncode_SetResolution_Proxy = NULL;
extern void *ptr_IWICBitmapFrameEncode_SetSize_Proxy;
void *ptr_IWICBitmapFrameEncode_SetSize_Proxy = NULL;
extern void *ptr_IWICBitmapFrameEncode_SetThumbnail_Proxy;
void *ptr_IWICBitmapFrameEncode_SetThumbnail_Proxy = NULL;
extern void *ptr_IWICBitmapFrameEncode_WriteSource_Proxy;
void *ptr_IWICBitmapFrameEncode_WriteSource_Proxy = NULL;
extern void *ptr_IWICBitmapLock_GetDataPointer_STA_Proxy;
void *ptr_IWICBitmapLock_GetDataPointer_STA_Proxy = NULL;
extern void *ptr_IWICBitmapLock_GetStride_Proxy;
void *ptr_IWICBitmapLock_GetStride_Proxy = NULL;
extern void *ptr_IWICBitmapScaler_Initialize_Proxy;
void *ptr_IWICBitmapScaler_Initialize_Proxy = NULL;
extern void *ptr_IWICBitmapSource_CopyPalette_Proxy;
void *ptr_IWICBitmapSource_CopyPalette_Proxy = NULL;
extern void *ptr_IWICBitmapSource_CopyPixels_Proxy;
void *ptr_IWICBitmapSource_CopyPixels_Proxy = NULL;
extern void *ptr_IWICBitmapSource_GetPixelFormat_Proxy;
void *ptr_IWICBitmapSource_GetPixelFormat_Proxy = NULL;
extern void *ptr_IWICBitmapSource_GetResolution_Proxy;
void *ptr_IWICBitmapSource_GetResolution_Proxy = NULL;
extern void *ptr_IWICBitmapSource_GetSize_Proxy;
void *ptr_IWICBitmapSource_GetSize_Proxy = NULL;
extern void *ptr_IWICBitmap_Lock_Proxy;
void *ptr_IWICBitmap_Lock_Proxy = NULL;
extern void *ptr_IWICBitmap_SetPalette_Proxy;
void *ptr_IWICBitmap_SetPalette_Proxy = NULL;
extern void *ptr_IWICBitmap_SetResolution_Proxy;
void *ptr_IWICBitmap_SetResolution_Proxy = NULL;
extern void *ptr_IWICColorContext_InitializeFromMemory_Proxy;
void *ptr_IWICColorContext_InitializeFromMemory_Proxy = NULL;
extern void *ptr_IWICComponentFactory_CreateMetadataWriterFromReader_Proxy;
void *ptr_IWICComponentFactory_CreateMetadataWriterFromReader_Proxy = NULL;
extern void *ptr_IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy;
void *ptr_IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy = NULL;
extern void *ptr_IWICComponentInfo_GetAuthor_Proxy;
void *ptr_IWICComponentInfo_GetAuthor_Proxy = NULL;
extern void *ptr_IWICComponentInfo_GetCLSID_Proxy;
void *ptr_IWICComponentInfo_GetCLSID_Proxy = NULL;
extern void *ptr_IWICComponentInfo_GetFriendlyName_Proxy;
void *ptr_IWICComponentInfo_GetFriendlyName_Proxy = NULL;
extern void *ptr_IWICComponentInfo_GetSpecVersion_Proxy;
void *ptr_IWICComponentInfo_GetSpecVersion_Proxy = NULL;
extern void *ptr_IWICComponentInfo_GetVersion_Proxy;
void *ptr_IWICComponentInfo_GetVersion_Proxy = NULL;
extern void *ptr_IWICFastMetadataEncoder_Commit_Proxy;
void *ptr_IWICFastMetadataEncoder_Commit_Proxy = NULL;
extern void *ptr_IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy;
void *ptr_IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy = NULL;
extern void *ptr_IWICFormatConverter_Initialize_Proxy;
void *ptr_IWICFormatConverter_Initialize_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateBitmapClipper_Proxy;
void *ptr_IWICImagingFactory_CreateBitmapClipper_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateBitmapFlipRotator_Proxy;
void *ptr_IWICImagingFactory_CreateBitmapFlipRotator_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy;
void *ptr_IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateBitmapFromHICON_Proxy;
void *ptr_IWICImagingFactory_CreateBitmapFromHICON_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateBitmapFromMemory_Proxy;
void *ptr_IWICImagingFactory_CreateBitmapFromMemory_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateBitmapFromSource_Proxy;
void *ptr_IWICImagingFactory_CreateBitmapFromSource_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateBitmapScaler_Proxy;
void *ptr_IWICImagingFactory_CreateBitmapScaler_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateBitmap_Proxy;
void *ptr_IWICImagingFactory_CreateBitmap_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateComponentInfo_Proxy;
void *ptr_IWICImagingFactory_CreateComponentInfo_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateDecoderFromFileHandle_Proxy;
void *ptr_IWICImagingFactory_CreateDecoderFromFileHandle_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateDecoderFromFilename_Proxy;
void *ptr_IWICImagingFactory_CreateDecoderFromFilename_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateDecoderFromStream_Proxy;
void *ptr_IWICImagingFactory_CreateDecoderFromStream_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateEncoder_Proxy;
void *ptr_IWICImagingFactory_CreateEncoder_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy;
void *ptr_IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy;
void *ptr_IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateFormatConverter_Proxy;
void *ptr_IWICImagingFactory_CreateFormatConverter_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreatePalette_Proxy;
void *ptr_IWICImagingFactory_CreatePalette_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateQueryWriterFromReader_Proxy;
void *ptr_IWICImagingFactory_CreateQueryWriterFromReader_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateQueryWriter_Proxy;
void *ptr_IWICImagingFactory_CreateQueryWriter_Proxy = NULL;
extern void *ptr_IWICImagingFactory_CreateStream_Proxy;
void *ptr_IWICImagingFactory_CreateStream_Proxy = NULL;
extern void *ptr_IWICMetadataBlockReader_GetCount_Proxy;
void *ptr_IWICMetadataBlockReader_GetCount_Proxy = NULL;
extern void *ptr_IWICMetadataBlockReader_GetReaderByIndex_Proxy;
void *ptr_IWICMetadataBlockReader_GetReaderByIndex_Proxy = NULL;
extern void *ptr_IWICMetadataQueryReader_GetContainerFormat_Proxy;
void *ptr_IWICMetadataQueryReader_GetContainerFormat_Proxy = NULL;
extern void *ptr_IWICMetadataQueryReader_GetEnumerator_Proxy;
void *ptr_IWICMetadataQueryReader_GetEnumerator_Proxy = NULL;
extern void *ptr_IWICMetadataQueryReader_GetLocation_Proxy;
void *ptr_IWICMetadataQueryReader_GetLocation_Proxy = NULL;
extern void *ptr_IWICMetadataQueryReader_GetMetadataByName_Proxy;
void *ptr_IWICMetadataQueryReader_GetMetadataByName_Proxy = NULL;
extern void *ptr_IWICMetadataQueryWriter_RemoveMetadataByName_Proxy;
void *ptr_IWICMetadataQueryWriter_RemoveMetadataByName_Proxy = NULL;
extern void *ptr_IWICMetadataQueryWriter_SetMetadataByName_Proxy;
void *ptr_IWICMetadataQueryWriter_SetMetadataByName_Proxy = NULL;
extern void *ptr_IWICPalette_GetColorCount_Proxy;
void *ptr_IWICPalette_GetColorCount_Proxy = NULL;
extern void *ptr_IWICPalette_GetColors_Proxy;
void *ptr_IWICPalette_GetColors_Proxy = NULL;
extern void *ptr_IWICPalette_GetType_Proxy;
void *ptr_IWICPalette_GetType_Proxy = NULL;
extern void *ptr_IWICPalette_HasAlpha_Proxy;
void *ptr_IWICPalette_HasAlpha_Proxy = NULL;
extern void *ptr_IWICPalette_InitializeCustom_Proxy;
void *ptr_IWICPalette_InitializeCustom_Proxy = NULL;
extern void *ptr_IWICPalette_InitializeFromBitmap_Proxy;
void *ptr_IWICPalette_InitializeFromBitmap_Proxy = NULL;
extern void *ptr_IWICPalette_InitializeFromPalette_Proxy;
void *ptr_IWICPalette_InitializeFromPalette_Proxy = NULL;
extern void *ptr_IWICPalette_InitializePredefined_Proxy;
void *ptr_IWICPalette_InitializePredefined_Proxy = NULL;
extern void *ptr_IWICPixelFormatInfo_GetBitsPerPixel_Proxy;
void *ptr_IWICPixelFormatInfo_GetBitsPerPixel_Proxy = NULL;
extern void *ptr_IWICPixelFormatInfo_GetChannelCount_Proxy;
void *ptr_IWICPixelFormatInfo_GetChannelCount_Proxy = NULL;
extern void *ptr_IWICPixelFormatInfo_GetChannelMask_Proxy;
void *ptr_IWICPixelFormatInfo_GetChannelMask_Proxy = NULL;
extern void *ptr_IWICStream_InitializeFromIStream_Proxy;
void *ptr_IWICStream_InitializeFromIStream_Proxy = NULL;
extern void *ptr_IWICStream_InitializeFromMemory_Proxy;
void *ptr_IWICStream_InitializeFromMemory_Proxy = NULL;
extern void *ptr_WICConvertBitmapSource;
void *ptr_WICConvertBitmapSource = NULL;
extern void *ptr_WICCreateBitmapFromSection;
void *ptr_WICCreateBitmapFromSection = NULL;
extern void *ptr_WICCreateBitmapFromSectionEx;
void *ptr_WICCreateBitmapFromSectionEx = NULL;
extern void *ptr_WICCreateColorContext_Proxy;
void *ptr_WICCreateColorContext_Proxy = NULL;
extern void *ptr_WICCreateImagingFactory_Proxy;
void *ptr_WICCreateImagingFactory_Proxy = NULL;
extern void *ptr_WICGetMetadataContentSize;
void *ptr_WICGetMetadataContentSize = NULL;
extern void *ptr_WICMapGuidToShortName;
void *ptr_WICMapGuidToShortName = NULL;
extern void *ptr_WICMapSchemaToName;
void *ptr_WICMapSchemaToName = NULL;
extern void *ptr_WICMapShortNameToGuid;
void *ptr_WICMapShortNameToGuid = NULL;
extern void *ptr_WICMatchMetadataContent;
void *ptr_WICMatchMetadataContent = NULL;
extern void *ptr_WICSerializeMetadataContent;
void *ptr_WICSerializeMetadataContent = NULL;
extern void *ptr_WICSetEncoderFormat_Proxy;
void *ptr_WICSetEncoderFormat_Proxy = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\WindowsCodecs.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_DllGetClassObject = (__vartype(ptr_DllGetClassObject))GetProcAddress(hModule, "DllGetClassObject");
   ptr_IEnumString_Next_WIC_Proxy = (__vartype(ptr_IEnumString_Next_WIC_Proxy))GetProcAddress(hModule, "IEnumString_Next_WIC_Proxy");
   ptr_IEnumString_Reset_WIC_Proxy = (__vartype(ptr_IEnumString_Reset_WIC_Proxy))GetProcAddress(hModule, "IEnumString_Reset_WIC_Proxy");
   ptr_IPropertyBag2_Write_Proxy = (__vartype(ptr_IPropertyBag2_Write_Proxy))GetProcAddress(hModule, "IPropertyBag2_Write_Proxy");
   ptr_IWICBitmapClipper_Initialize_Proxy = (__vartype(ptr_IWICBitmapClipper_Initialize_Proxy))GetProcAddress(hModule, "IWICBitmapClipper_Initialize_Proxy");
   ptr_IWICBitmapCodecInfo_DoesSupportAnimation_Proxy = (__vartype(ptr_IWICBitmapCodecInfo_DoesSupportAnimation_Proxy))GetProcAddress(hModule, "IWICBitmapCodecInfo_DoesSupportAnimation_Proxy");
   ptr_IWICBitmapCodecInfo_DoesSupportLossless_Proxy = (__vartype(ptr_IWICBitmapCodecInfo_DoesSupportLossless_Proxy))GetProcAddress(hModule, "IWICBitmapCodecInfo_DoesSupportLossless_Proxy");
   ptr_IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy = (__vartype(ptr_IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy))GetProcAddress(hModule, "IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy");
   ptr_IWICBitmapCodecInfo_GetContainerFormat_Proxy = (__vartype(ptr_IWICBitmapCodecInfo_GetContainerFormat_Proxy))GetProcAddress(hModule, "IWICBitmapCodecInfo_GetContainerFormat_Proxy");
   ptr_IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy = (__vartype(ptr_IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy))GetProcAddress(hModule, "IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy");
   ptr_IWICBitmapCodecInfo_GetDeviceModels_Proxy = (__vartype(ptr_IWICBitmapCodecInfo_GetDeviceModels_Proxy))GetProcAddress(hModule, "IWICBitmapCodecInfo_GetDeviceModels_Proxy");
   ptr_IWICBitmapCodecInfo_GetFileExtensions_Proxy = (__vartype(ptr_IWICBitmapCodecInfo_GetFileExtensions_Proxy))GetProcAddress(hModule, "IWICBitmapCodecInfo_GetFileExtensions_Proxy");
   ptr_IWICBitmapCodecInfo_GetMimeTypes_Proxy = (__vartype(ptr_IWICBitmapCodecInfo_GetMimeTypes_Proxy))GetProcAddress(hModule, "IWICBitmapCodecInfo_GetMimeTypes_Proxy");
   ptr_IWICBitmapDecoder_CopyPalette_Proxy = (__vartype(ptr_IWICBitmapDecoder_CopyPalette_Proxy))GetProcAddress(hModule, "IWICBitmapDecoder_CopyPalette_Proxy");
   ptr_IWICBitmapDecoder_GetColorContexts_Proxy = (__vartype(ptr_IWICBitmapDecoder_GetColorContexts_Proxy))GetProcAddress(hModule, "IWICBitmapDecoder_GetColorContexts_Proxy");
   ptr_IWICBitmapDecoder_GetDecoderInfo_Proxy = (__vartype(ptr_IWICBitmapDecoder_GetDecoderInfo_Proxy))GetProcAddress(hModule, "IWICBitmapDecoder_GetDecoderInfo_Proxy");
   ptr_IWICBitmapDecoder_GetFrameCount_Proxy = (__vartype(ptr_IWICBitmapDecoder_GetFrameCount_Proxy))GetProcAddress(hModule, "IWICBitmapDecoder_GetFrameCount_Proxy");
   ptr_IWICBitmapDecoder_GetFrame_Proxy = (__vartype(ptr_IWICBitmapDecoder_GetFrame_Proxy))GetProcAddress(hModule, "IWICBitmapDecoder_GetFrame_Proxy");
   ptr_IWICBitmapDecoder_GetMetadataQueryReader_Proxy = (__vartype(ptr_IWICBitmapDecoder_GetMetadataQueryReader_Proxy))GetProcAddress(hModule, "IWICBitmapDecoder_GetMetadataQueryReader_Proxy");
   ptr_IWICBitmapDecoder_GetPreview_Proxy = (__vartype(ptr_IWICBitmapDecoder_GetPreview_Proxy))GetProcAddress(hModule, "IWICBitmapDecoder_GetPreview_Proxy");
   ptr_IWICBitmapDecoder_GetThumbnail_Proxy = (__vartype(ptr_IWICBitmapDecoder_GetThumbnail_Proxy))GetProcAddress(hModule, "IWICBitmapDecoder_GetThumbnail_Proxy");
   ptr_IWICBitmapEncoder_Commit_Proxy = (__vartype(ptr_IWICBitmapEncoder_Commit_Proxy))GetProcAddress(hModule, "IWICBitmapEncoder_Commit_Proxy");
   ptr_IWICBitmapEncoder_CreateNewFrame_Proxy = (__vartype(ptr_IWICBitmapEncoder_CreateNewFrame_Proxy))GetProcAddress(hModule, "IWICBitmapEncoder_CreateNewFrame_Proxy");
   ptr_IWICBitmapEncoder_GetEncoderInfo_Proxy = (__vartype(ptr_IWICBitmapEncoder_GetEncoderInfo_Proxy))GetProcAddress(hModule, "IWICBitmapEncoder_GetEncoderInfo_Proxy");
   ptr_IWICBitmapEncoder_GetMetadataQueryWriter_Proxy = (__vartype(ptr_IWICBitmapEncoder_GetMetadataQueryWriter_Proxy))GetProcAddress(hModule, "IWICBitmapEncoder_GetMetadataQueryWriter_Proxy");
   ptr_IWICBitmapEncoder_Initialize_Proxy = (__vartype(ptr_IWICBitmapEncoder_Initialize_Proxy))GetProcAddress(hModule, "IWICBitmapEncoder_Initialize_Proxy");
   ptr_IWICBitmapEncoder_SetPalette_Proxy = (__vartype(ptr_IWICBitmapEncoder_SetPalette_Proxy))GetProcAddress(hModule, "IWICBitmapEncoder_SetPalette_Proxy");
   ptr_IWICBitmapEncoder_SetThumbnail_Proxy = (__vartype(ptr_IWICBitmapEncoder_SetThumbnail_Proxy))GetProcAddress(hModule, "IWICBitmapEncoder_SetThumbnail_Proxy");
   ptr_IWICBitmapFlipRotator_Initialize_Proxy = (__vartype(ptr_IWICBitmapFlipRotator_Initialize_Proxy))GetProcAddress(hModule, "IWICBitmapFlipRotator_Initialize_Proxy");
   ptr_IWICBitmapFrameDecode_GetColorContexts_Proxy = (__vartype(ptr_IWICBitmapFrameDecode_GetColorContexts_Proxy))GetProcAddress(hModule, "IWICBitmapFrameDecode_GetColorContexts_Proxy");
   ptr_IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy = (__vartype(ptr_IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy))GetProcAddress(hModule, "IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy");
   ptr_IWICBitmapFrameDecode_GetThumbnail_Proxy = (__vartype(ptr_IWICBitmapFrameDecode_GetThumbnail_Proxy))GetProcAddress(hModule, "IWICBitmapFrameDecode_GetThumbnail_Proxy");
   ptr_IWICBitmapFrameEncode_Commit_Proxy = (__vartype(ptr_IWICBitmapFrameEncode_Commit_Proxy))GetProcAddress(hModule, "IWICBitmapFrameEncode_Commit_Proxy");
   ptr_IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy = (__vartype(ptr_IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy))GetProcAddress(hModule, "IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy");
   ptr_IWICBitmapFrameEncode_Initialize_Proxy = (__vartype(ptr_IWICBitmapFrameEncode_Initialize_Proxy))GetProcAddress(hModule, "IWICBitmapFrameEncode_Initialize_Proxy");
   ptr_IWICBitmapFrameEncode_SetColorContexts_Proxy = (__vartype(ptr_IWICBitmapFrameEncode_SetColorContexts_Proxy))GetProcAddress(hModule, "IWICBitmapFrameEncode_SetColorContexts_Proxy");
   ptr_IWICBitmapFrameEncode_SetResolution_Proxy = (__vartype(ptr_IWICBitmapFrameEncode_SetResolution_Proxy))GetProcAddress(hModule, "IWICBitmapFrameEncode_SetResolution_Proxy");
   ptr_IWICBitmapFrameEncode_SetSize_Proxy = (__vartype(ptr_IWICBitmapFrameEncode_SetSize_Proxy))GetProcAddress(hModule, "IWICBitmapFrameEncode_SetSize_Proxy");
   ptr_IWICBitmapFrameEncode_SetThumbnail_Proxy = (__vartype(ptr_IWICBitmapFrameEncode_SetThumbnail_Proxy))GetProcAddress(hModule, "IWICBitmapFrameEncode_SetThumbnail_Proxy");
   ptr_IWICBitmapFrameEncode_WriteSource_Proxy = (__vartype(ptr_IWICBitmapFrameEncode_WriteSource_Proxy))GetProcAddress(hModule, "IWICBitmapFrameEncode_WriteSource_Proxy");
   ptr_IWICBitmapLock_GetDataPointer_STA_Proxy = (__vartype(ptr_IWICBitmapLock_GetDataPointer_STA_Proxy))GetProcAddress(hModule, "IWICBitmapLock_GetDataPointer_STA_Proxy");
   ptr_IWICBitmapLock_GetStride_Proxy = (__vartype(ptr_IWICBitmapLock_GetStride_Proxy))GetProcAddress(hModule, "IWICBitmapLock_GetStride_Proxy");
   ptr_IWICBitmapScaler_Initialize_Proxy = (__vartype(ptr_IWICBitmapScaler_Initialize_Proxy))GetProcAddress(hModule, "IWICBitmapScaler_Initialize_Proxy");
   ptr_IWICBitmapSource_CopyPalette_Proxy = (__vartype(ptr_IWICBitmapSource_CopyPalette_Proxy))GetProcAddress(hModule, "IWICBitmapSource_CopyPalette_Proxy");
   ptr_IWICBitmapSource_CopyPixels_Proxy = (__vartype(ptr_IWICBitmapSource_CopyPixels_Proxy))GetProcAddress(hModule, "IWICBitmapSource_CopyPixels_Proxy");
   ptr_IWICBitmapSource_GetPixelFormat_Proxy = (__vartype(ptr_IWICBitmapSource_GetPixelFormat_Proxy))GetProcAddress(hModule, "IWICBitmapSource_GetPixelFormat_Proxy");
   ptr_IWICBitmapSource_GetResolution_Proxy = (__vartype(ptr_IWICBitmapSource_GetResolution_Proxy))GetProcAddress(hModule, "IWICBitmapSource_GetResolution_Proxy");
   ptr_IWICBitmapSource_GetSize_Proxy = (__vartype(ptr_IWICBitmapSource_GetSize_Proxy))GetProcAddress(hModule, "IWICBitmapSource_GetSize_Proxy");
   ptr_IWICBitmap_Lock_Proxy = (__vartype(ptr_IWICBitmap_Lock_Proxy))GetProcAddress(hModule, "IWICBitmap_Lock_Proxy");
   ptr_IWICBitmap_SetPalette_Proxy = (__vartype(ptr_IWICBitmap_SetPalette_Proxy))GetProcAddress(hModule, "IWICBitmap_SetPalette_Proxy");
   ptr_IWICBitmap_SetResolution_Proxy = (__vartype(ptr_IWICBitmap_SetResolution_Proxy))GetProcAddress(hModule, "IWICBitmap_SetResolution_Proxy");
   ptr_IWICColorContext_InitializeFromMemory_Proxy = (__vartype(ptr_IWICColorContext_InitializeFromMemory_Proxy))GetProcAddress(hModule, "IWICColorContext_InitializeFromMemory_Proxy");
   ptr_IWICComponentFactory_CreateMetadataWriterFromReader_Proxy = (__vartype(ptr_IWICComponentFactory_CreateMetadataWriterFromReader_Proxy))GetProcAddress(hModule, "IWICComponentFactory_CreateMetadataWriterFromReader_Proxy");
   ptr_IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy = (__vartype(ptr_IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy))GetProcAddress(hModule, "IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy");
   ptr_IWICComponentInfo_GetAuthor_Proxy = (__vartype(ptr_IWICComponentInfo_GetAuthor_Proxy))GetProcAddress(hModule, "IWICComponentInfo_GetAuthor_Proxy");
   ptr_IWICComponentInfo_GetCLSID_Proxy = (__vartype(ptr_IWICComponentInfo_GetCLSID_Proxy))GetProcAddress(hModule, "IWICComponentInfo_GetCLSID_Proxy");
   ptr_IWICComponentInfo_GetFriendlyName_Proxy = (__vartype(ptr_IWICComponentInfo_GetFriendlyName_Proxy))GetProcAddress(hModule, "IWICComponentInfo_GetFriendlyName_Proxy");
   ptr_IWICComponentInfo_GetSpecVersion_Proxy = (__vartype(ptr_IWICComponentInfo_GetSpecVersion_Proxy))GetProcAddress(hModule, "IWICComponentInfo_GetSpecVersion_Proxy");
   ptr_IWICComponentInfo_GetVersion_Proxy = (__vartype(ptr_IWICComponentInfo_GetVersion_Proxy))GetProcAddress(hModule, "IWICComponentInfo_GetVersion_Proxy");
   ptr_IWICFastMetadataEncoder_Commit_Proxy = (__vartype(ptr_IWICFastMetadataEncoder_Commit_Proxy))GetProcAddress(hModule, "IWICFastMetadataEncoder_Commit_Proxy");
   ptr_IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy = (__vartype(ptr_IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy))GetProcAddress(hModule, "IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy");
   ptr_IWICFormatConverter_Initialize_Proxy = (__vartype(ptr_IWICFormatConverter_Initialize_Proxy))GetProcAddress(hModule, "IWICFormatConverter_Initialize_Proxy");
   ptr_IWICImagingFactory_CreateBitmapClipper_Proxy = (__vartype(ptr_IWICImagingFactory_CreateBitmapClipper_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateBitmapClipper_Proxy");
   ptr_IWICImagingFactory_CreateBitmapFlipRotator_Proxy = (__vartype(ptr_IWICImagingFactory_CreateBitmapFlipRotator_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateBitmapFlipRotator_Proxy");
   ptr_IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy = (__vartype(ptr_IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy");
   ptr_IWICImagingFactory_CreateBitmapFromHICON_Proxy = (__vartype(ptr_IWICImagingFactory_CreateBitmapFromHICON_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateBitmapFromHICON_Proxy");
   ptr_IWICImagingFactory_CreateBitmapFromMemory_Proxy = (__vartype(ptr_IWICImagingFactory_CreateBitmapFromMemory_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateBitmapFromMemory_Proxy");
   ptr_IWICImagingFactory_CreateBitmapFromSource_Proxy = (__vartype(ptr_IWICImagingFactory_CreateBitmapFromSource_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateBitmapFromSource_Proxy");
   ptr_IWICImagingFactory_CreateBitmapScaler_Proxy = (__vartype(ptr_IWICImagingFactory_CreateBitmapScaler_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateBitmapScaler_Proxy");
   ptr_IWICImagingFactory_CreateBitmap_Proxy = (__vartype(ptr_IWICImagingFactory_CreateBitmap_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateBitmap_Proxy");
   ptr_IWICImagingFactory_CreateComponentInfo_Proxy = (__vartype(ptr_IWICImagingFactory_CreateComponentInfo_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateComponentInfo_Proxy");
   ptr_IWICImagingFactory_CreateDecoderFromFileHandle_Proxy = (__vartype(ptr_IWICImagingFactory_CreateDecoderFromFileHandle_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateDecoderFromFileHandle_Proxy");
   ptr_IWICImagingFactory_CreateDecoderFromFilename_Proxy = (__vartype(ptr_IWICImagingFactory_CreateDecoderFromFilename_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateDecoderFromFilename_Proxy");
   ptr_IWICImagingFactory_CreateDecoderFromStream_Proxy = (__vartype(ptr_IWICImagingFactory_CreateDecoderFromStream_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateDecoderFromStream_Proxy");
   ptr_IWICImagingFactory_CreateEncoder_Proxy = (__vartype(ptr_IWICImagingFactory_CreateEncoder_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateEncoder_Proxy");
   ptr_IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy = (__vartype(ptr_IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy");
   ptr_IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy = (__vartype(ptr_IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy");
   ptr_IWICImagingFactory_CreateFormatConverter_Proxy = (__vartype(ptr_IWICImagingFactory_CreateFormatConverter_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateFormatConverter_Proxy");
   ptr_IWICImagingFactory_CreatePalette_Proxy = (__vartype(ptr_IWICImagingFactory_CreatePalette_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreatePalette_Proxy");
   ptr_IWICImagingFactory_CreateQueryWriterFromReader_Proxy = (__vartype(ptr_IWICImagingFactory_CreateQueryWriterFromReader_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateQueryWriterFromReader_Proxy");
   ptr_IWICImagingFactory_CreateQueryWriter_Proxy = (__vartype(ptr_IWICImagingFactory_CreateQueryWriter_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateQueryWriter_Proxy");
   ptr_IWICImagingFactory_CreateStream_Proxy = (__vartype(ptr_IWICImagingFactory_CreateStream_Proxy))GetProcAddress(hModule, "IWICImagingFactory_CreateStream_Proxy");
   ptr_IWICMetadataBlockReader_GetCount_Proxy = (__vartype(ptr_IWICMetadataBlockReader_GetCount_Proxy))GetProcAddress(hModule, "IWICMetadataBlockReader_GetCount_Proxy");
   ptr_IWICMetadataBlockReader_GetReaderByIndex_Proxy = (__vartype(ptr_IWICMetadataBlockReader_GetReaderByIndex_Proxy))GetProcAddress(hModule, "IWICMetadataBlockReader_GetReaderByIndex_Proxy");
   ptr_IWICMetadataQueryReader_GetContainerFormat_Proxy = (__vartype(ptr_IWICMetadataQueryReader_GetContainerFormat_Proxy))GetProcAddress(hModule, "IWICMetadataQueryReader_GetContainerFormat_Proxy");
   ptr_IWICMetadataQueryReader_GetEnumerator_Proxy = (__vartype(ptr_IWICMetadataQueryReader_GetEnumerator_Proxy))GetProcAddress(hModule, "IWICMetadataQueryReader_GetEnumerator_Proxy");
   ptr_IWICMetadataQueryReader_GetLocation_Proxy = (__vartype(ptr_IWICMetadataQueryReader_GetLocation_Proxy))GetProcAddress(hModule, "IWICMetadataQueryReader_GetLocation_Proxy");
   ptr_IWICMetadataQueryReader_GetMetadataByName_Proxy = (__vartype(ptr_IWICMetadataQueryReader_GetMetadataByName_Proxy))GetProcAddress(hModule, "IWICMetadataQueryReader_GetMetadataByName_Proxy");
   ptr_IWICMetadataQueryWriter_RemoveMetadataByName_Proxy = (__vartype(ptr_IWICMetadataQueryWriter_RemoveMetadataByName_Proxy))GetProcAddress(hModule, "IWICMetadataQueryWriter_RemoveMetadataByName_Proxy");
   ptr_IWICMetadataQueryWriter_SetMetadataByName_Proxy = (__vartype(ptr_IWICMetadataQueryWriter_SetMetadataByName_Proxy))GetProcAddress(hModule, "IWICMetadataQueryWriter_SetMetadataByName_Proxy");
   ptr_IWICPalette_GetColorCount_Proxy = (__vartype(ptr_IWICPalette_GetColorCount_Proxy))GetProcAddress(hModule, "IWICPalette_GetColorCount_Proxy");
   ptr_IWICPalette_GetColors_Proxy = (__vartype(ptr_IWICPalette_GetColors_Proxy))GetProcAddress(hModule, "IWICPalette_GetColors_Proxy");
   ptr_IWICPalette_GetType_Proxy = (__vartype(ptr_IWICPalette_GetType_Proxy))GetProcAddress(hModule, "IWICPalette_GetType_Proxy");
   ptr_IWICPalette_HasAlpha_Proxy = (__vartype(ptr_IWICPalette_HasAlpha_Proxy))GetProcAddress(hModule, "IWICPalette_HasAlpha_Proxy");
   ptr_IWICPalette_InitializeCustom_Proxy = (__vartype(ptr_IWICPalette_InitializeCustom_Proxy))GetProcAddress(hModule, "IWICPalette_InitializeCustom_Proxy");
   ptr_IWICPalette_InitializeFromBitmap_Proxy = (__vartype(ptr_IWICPalette_InitializeFromBitmap_Proxy))GetProcAddress(hModule, "IWICPalette_InitializeFromBitmap_Proxy");
   ptr_IWICPalette_InitializeFromPalette_Proxy = (__vartype(ptr_IWICPalette_InitializeFromPalette_Proxy))GetProcAddress(hModule, "IWICPalette_InitializeFromPalette_Proxy");
   ptr_IWICPalette_InitializePredefined_Proxy = (__vartype(ptr_IWICPalette_InitializePredefined_Proxy))GetProcAddress(hModule, "IWICPalette_InitializePredefined_Proxy");
   ptr_IWICPixelFormatInfo_GetBitsPerPixel_Proxy = (__vartype(ptr_IWICPixelFormatInfo_GetBitsPerPixel_Proxy))GetProcAddress(hModule, "IWICPixelFormatInfo_GetBitsPerPixel_Proxy");
   ptr_IWICPixelFormatInfo_GetChannelCount_Proxy = (__vartype(ptr_IWICPixelFormatInfo_GetChannelCount_Proxy))GetProcAddress(hModule, "IWICPixelFormatInfo_GetChannelCount_Proxy");
   ptr_IWICPixelFormatInfo_GetChannelMask_Proxy = (__vartype(ptr_IWICPixelFormatInfo_GetChannelMask_Proxy))GetProcAddress(hModule, "IWICPixelFormatInfo_GetChannelMask_Proxy");
   ptr_IWICStream_InitializeFromIStream_Proxy = (__vartype(ptr_IWICStream_InitializeFromIStream_Proxy))GetProcAddress(hModule, "IWICStream_InitializeFromIStream_Proxy");
   ptr_IWICStream_InitializeFromMemory_Proxy = (__vartype(ptr_IWICStream_InitializeFromMemory_Proxy))GetProcAddress(hModule, "IWICStream_InitializeFromMemory_Proxy");
   ptr_WICConvertBitmapSource = (__vartype(ptr_WICConvertBitmapSource))GetProcAddress(hModule, "WICConvertBitmapSource");
   ptr_WICCreateBitmapFromSection = (__vartype(ptr_WICCreateBitmapFromSection))GetProcAddress(hModule, "WICCreateBitmapFromSection");
   ptr_WICCreateBitmapFromSectionEx = (__vartype(ptr_WICCreateBitmapFromSectionEx))GetProcAddress(hModule, "WICCreateBitmapFromSectionEx");
   ptr_WICCreateColorContext_Proxy = (__vartype(ptr_WICCreateColorContext_Proxy))GetProcAddress(hModule, "WICCreateColorContext_Proxy");
   ptr_WICCreateImagingFactory_Proxy = (__vartype(ptr_WICCreateImagingFactory_Proxy))GetProcAddress(hModule, "WICCreateImagingFactory_Proxy");
   ptr_WICGetMetadataContentSize = (__vartype(ptr_WICGetMetadataContentSize))GetProcAddress(hModule, "WICGetMetadataContentSize");
   ptr_WICMapGuidToShortName = (__vartype(ptr_WICMapGuidToShortName))GetProcAddress(hModule, "WICMapGuidToShortName");
   ptr_WICMapSchemaToName = (__vartype(ptr_WICMapSchemaToName))GetProcAddress(hModule, "WICMapSchemaToName");
   ptr_WICMapShortNameToGuid = (__vartype(ptr_WICMapShortNameToGuid))GetProcAddress(hModule, "WICMapShortNameToGuid");
   ptr_WICMatchMetadataContent = (__vartype(ptr_WICMatchMetadataContent))GetProcAddress(hModule, "WICMatchMetadataContent");
   ptr_WICSerializeMetadataContent = (__vartype(ptr_WICSerializeMetadataContent))GetProcAddress(hModule, "WICSerializeMetadataContent");
   ptr_WICSetEncoderFormat_Proxy = (__vartype(ptr_WICSetEncoderFormat_Proxy))GetProcAddress(hModule, "WICSetEncoderFormat_Proxy");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

