ifndef X64
.686p
.XMM
.safeseh SEH_handler
.model flat, C
option dotname
option casemap : none
endif

extern ptr_DllGetClassObject : PTR;
extern ptr_IEnumString_Next_WIC_Proxy : PTR;
extern ptr_IEnumString_Reset_WIC_Proxy : PTR;
extern ptr_IPropertyBag2_Write_Proxy : PTR;
extern ptr_IWICBitmapClipper_Initialize_Proxy : PTR;
extern ptr_IWICBitmapCodecInfo_DoesSupportAnimation_Proxy : PTR;
extern ptr_IWICBitmapCodecInfo_DoesSupportLossless_Proxy : PTR;
extern ptr_IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy : PTR;
extern ptr_IWICBitmapCodecInfo_GetContainerFormat_Proxy : PTR;
extern ptr_IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy : PTR;
extern ptr_IWICBitmapCodecInfo_GetDeviceModels_Proxy : PTR;
extern ptr_IWICBitmapCodecInfo_GetFileExtensions_Proxy : PTR;
extern ptr_IWICBitmapCodecInfo_GetMimeTypes_Proxy : PTR;
extern ptr_IWICBitmapDecoder_CopyPalette_Proxy : PTR;
extern ptr_IWICBitmapDecoder_GetColorContexts_Proxy : PTR;
extern ptr_IWICBitmapDecoder_GetDecoderInfo_Proxy : PTR;
extern ptr_IWICBitmapDecoder_GetFrameCount_Proxy : PTR;
extern ptr_IWICBitmapDecoder_GetFrame_Proxy : PTR;
extern ptr_IWICBitmapDecoder_GetMetadataQueryReader_Proxy : PTR;
extern ptr_IWICBitmapDecoder_GetPreview_Proxy : PTR;
extern ptr_IWICBitmapDecoder_GetThumbnail_Proxy : PTR;
extern ptr_IWICBitmapEncoder_Commit_Proxy : PTR;
extern ptr_IWICBitmapEncoder_CreateNewFrame_Proxy : PTR;
extern ptr_IWICBitmapEncoder_GetEncoderInfo_Proxy : PTR;
extern ptr_IWICBitmapEncoder_GetMetadataQueryWriter_Proxy : PTR;
extern ptr_IWICBitmapEncoder_Initialize_Proxy : PTR;
extern ptr_IWICBitmapEncoder_SetPalette_Proxy : PTR;
extern ptr_IWICBitmapEncoder_SetThumbnail_Proxy : PTR;
extern ptr_IWICBitmapFlipRotator_Initialize_Proxy : PTR;
extern ptr_IWICBitmapFrameDecode_GetColorContexts_Proxy : PTR;
extern ptr_IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy : PTR;
extern ptr_IWICBitmapFrameDecode_GetThumbnail_Proxy : PTR;
extern ptr_IWICBitmapFrameEncode_Commit_Proxy : PTR;
extern ptr_IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy : PTR;
extern ptr_IWICBitmapFrameEncode_Initialize_Proxy : PTR;
extern ptr_IWICBitmapFrameEncode_SetColorContexts_Proxy : PTR;
extern ptr_IWICBitmapFrameEncode_SetResolution_Proxy : PTR;
extern ptr_IWICBitmapFrameEncode_SetSize_Proxy : PTR;
extern ptr_IWICBitmapFrameEncode_SetThumbnail_Proxy : PTR;
extern ptr_IWICBitmapFrameEncode_WriteSource_Proxy : PTR;
extern ptr_IWICBitmapLock_GetDataPointer_STA_Proxy : PTR;
extern ptr_IWICBitmapLock_GetStride_Proxy : PTR;
extern ptr_IWICBitmapScaler_Initialize_Proxy : PTR;
extern ptr_IWICBitmapSource_CopyPalette_Proxy : PTR;
extern ptr_IWICBitmapSource_CopyPixels_Proxy : PTR;
extern ptr_IWICBitmapSource_GetPixelFormat_Proxy : PTR;
extern ptr_IWICBitmapSource_GetResolution_Proxy : PTR;
extern ptr_IWICBitmapSource_GetSize_Proxy : PTR;
extern ptr_IWICBitmap_Lock_Proxy : PTR;
extern ptr_IWICBitmap_SetPalette_Proxy : PTR;
extern ptr_IWICBitmap_SetResolution_Proxy : PTR;
extern ptr_IWICColorContext_InitializeFromMemory_Proxy : PTR;
extern ptr_IWICComponentFactory_CreateMetadataWriterFromReader_Proxy : PTR;
extern ptr_IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy : PTR;
extern ptr_IWICComponentInfo_GetAuthor_Proxy : PTR;
extern ptr_IWICComponentInfo_GetCLSID_Proxy : PTR;
extern ptr_IWICComponentInfo_GetFriendlyName_Proxy : PTR;
extern ptr_IWICComponentInfo_GetSpecVersion_Proxy : PTR;
extern ptr_IWICComponentInfo_GetVersion_Proxy : PTR;
extern ptr_IWICFastMetadataEncoder_Commit_Proxy : PTR;
extern ptr_IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy : PTR;
extern ptr_IWICFormatConverter_Initialize_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateBitmapClipper_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateBitmapFlipRotator_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateBitmapFromHICON_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateBitmapFromMemory_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateBitmapFromSource_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateBitmapScaler_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateBitmap_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateComponentInfo_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateDecoderFromFileHandle_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateDecoderFromFilename_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateDecoderFromStream_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateEncoder_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateFormatConverter_Proxy : PTR;
extern ptr_IWICImagingFactory_CreatePalette_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateQueryWriterFromReader_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateQueryWriter_Proxy : PTR;
extern ptr_IWICImagingFactory_CreateStream_Proxy : PTR;
extern ptr_IWICMetadataBlockReader_GetCount_Proxy : PTR;
extern ptr_IWICMetadataBlockReader_GetReaderByIndex_Proxy : PTR;
extern ptr_IWICMetadataQueryReader_GetContainerFormat_Proxy : PTR;
extern ptr_IWICMetadataQueryReader_GetEnumerator_Proxy : PTR;
extern ptr_IWICMetadataQueryReader_GetLocation_Proxy : PTR;
extern ptr_IWICMetadataQueryReader_GetMetadataByName_Proxy : PTR;
extern ptr_IWICMetadataQueryWriter_RemoveMetadataByName_Proxy : PTR;
extern ptr_IWICMetadataQueryWriter_SetMetadataByName_Proxy : PTR;
extern ptr_IWICPalette_GetColorCount_Proxy : PTR;
extern ptr_IWICPalette_GetColors_Proxy : PTR;
extern ptr_IWICPalette_GetType_Proxy : PTR;
extern ptr_IWICPalette_HasAlpha_Proxy : PTR;
extern ptr_IWICPalette_InitializeCustom_Proxy : PTR;
extern ptr_IWICPalette_InitializeFromBitmap_Proxy : PTR;
extern ptr_IWICPalette_InitializeFromPalette_Proxy : PTR;
extern ptr_IWICPalette_InitializePredefined_Proxy : PTR;
extern ptr_IWICPixelFormatInfo_GetBitsPerPixel_Proxy : PTR;
extern ptr_IWICPixelFormatInfo_GetChannelCount_Proxy : PTR;
extern ptr_IWICPixelFormatInfo_GetChannelMask_Proxy : PTR;
extern ptr_IWICStream_InitializeFromIStream_Proxy : PTR;
extern ptr_IWICStream_InitializeFromMemory_Proxy : PTR;
extern ptr_WICConvertBitmapSource : PTR;
extern ptr_WICCreateBitmapFromSection : PTR;
extern ptr_WICCreateBitmapFromSectionEx : PTR;
extern ptr_WICCreateColorContext_Proxy : PTR;
extern ptr_WICCreateImagingFactory_Proxy : PTR;
extern ptr_WICGetMetadataContentSize : PTR;
extern ptr_WICMapGuidToShortName : PTR;
extern ptr_WICMapSchemaToName : PTR;
extern ptr_WICMapShortNameToGuid : PTR;
extern ptr_WICMatchMetadataContent : PTR;
extern ptr_WICSerializeMetadataContent : PTR;
extern ptr_WICSetEncoderFormat_Proxy : PTR;


.code

align 16
SEH_handler   proc
; handler
ret
SEH_handler   endp

DllGetClassObject PROC
jmp ptr_DllGetClassObject
DllGetClassObject ENDP

IEnumString_Next_WIC_Proxy PROC
jmp ptr_IEnumString_Next_WIC_Proxy
IEnumString_Next_WIC_Proxy ENDP

IEnumString_Reset_WIC_Proxy PROC
jmp ptr_IEnumString_Reset_WIC_Proxy
IEnumString_Reset_WIC_Proxy ENDP

IPropertyBag2_Write_Proxy PROC
jmp ptr_IPropertyBag2_Write_Proxy
IPropertyBag2_Write_Proxy ENDP

IWICBitmapClipper_Initialize_Proxy PROC
jmp ptr_IWICBitmapClipper_Initialize_Proxy
IWICBitmapClipper_Initialize_Proxy ENDP

IWICBitmapCodecInfo_DoesSupportAnimation_Proxy PROC
jmp ptr_IWICBitmapCodecInfo_DoesSupportAnimation_Proxy
IWICBitmapCodecInfo_DoesSupportAnimation_Proxy ENDP

IWICBitmapCodecInfo_DoesSupportLossless_Proxy PROC
jmp ptr_IWICBitmapCodecInfo_DoesSupportLossless_Proxy
IWICBitmapCodecInfo_DoesSupportLossless_Proxy ENDP

IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy PROC
jmp ptr_IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy
IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy ENDP

IWICBitmapCodecInfo_GetContainerFormat_Proxy PROC
jmp ptr_IWICBitmapCodecInfo_GetContainerFormat_Proxy
IWICBitmapCodecInfo_GetContainerFormat_Proxy ENDP

IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy PROC
jmp ptr_IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy
IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy ENDP

IWICBitmapCodecInfo_GetDeviceModels_Proxy PROC
jmp ptr_IWICBitmapCodecInfo_GetDeviceModels_Proxy
IWICBitmapCodecInfo_GetDeviceModels_Proxy ENDP

IWICBitmapCodecInfo_GetFileExtensions_Proxy PROC
jmp ptr_IWICBitmapCodecInfo_GetFileExtensions_Proxy
IWICBitmapCodecInfo_GetFileExtensions_Proxy ENDP

IWICBitmapCodecInfo_GetMimeTypes_Proxy PROC
jmp ptr_IWICBitmapCodecInfo_GetMimeTypes_Proxy
IWICBitmapCodecInfo_GetMimeTypes_Proxy ENDP

IWICBitmapDecoder_CopyPalette_Proxy PROC
jmp ptr_IWICBitmapDecoder_CopyPalette_Proxy
IWICBitmapDecoder_CopyPalette_Proxy ENDP

IWICBitmapDecoder_GetColorContexts_Proxy PROC
jmp ptr_IWICBitmapDecoder_GetColorContexts_Proxy
IWICBitmapDecoder_GetColorContexts_Proxy ENDP

IWICBitmapDecoder_GetDecoderInfo_Proxy PROC
jmp ptr_IWICBitmapDecoder_GetDecoderInfo_Proxy
IWICBitmapDecoder_GetDecoderInfo_Proxy ENDP

IWICBitmapDecoder_GetFrameCount_Proxy PROC
jmp ptr_IWICBitmapDecoder_GetFrameCount_Proxy
IWICBitmapDecoder_GetFrameCount_Proxy ENDP

IWICBitmapDecoder_GetFrame_Proxy PROC
jmp ptr_IWICBitmapDecoder_GetFrame_Proxy
IWICBitmapDecoder_GetFrame_Proxy ENDP

IWICBitmapDecoder_GetMetadataQueryReader_Proxy PROC
jmp ptr_IWICBitmapDecoder_GetMetadataQueryReader_Proxy
IWICBitmapDecoder_GetMetadataQueryReader_Proxy ENDP

IWICBitmapDecoder_GetPreview_Proxy PROC
jmp ptr_IWICBitmapDecoder_GetPreview_Proxy
IWICBitmapDecoder_GetPreview_Proxy ENDP

IWICBitmapDecoder_GetThumbnail_Proxy PROC
jmp ptr_IWICBitmapDecoder_GetThumbnail_Proxy
IWICBitmapDecoder_GetThumbnail_Proxy ENDP

IWICBitmapEncoder_Commit_Proxy PROC
jmp ptr_IWICBitmapEncoder_Commit_Proxy
IWICBitmapEncoder_Commit_Proxy ENDP

IWICBitmapEncoder_CreateNewFrame_Proxy PROC
jmp ptr_IWICBitmapEncoder_CreateNewFrame_Proxy
IWICBitmapEncoder_CreateNewFrame_Proxy ENDP

IWICBitmapEncoder_GetEncoderInfo_Proxy PROC
jmp ptr_IWICBitmapEncoder_GetEncoderInfo_Proxy
IWICBitmapEncoder_GetEncoderInfo_Proxy ENDP

IWICBitmapEncoder_GetMetadataQueryWriter_Proxy PROC
jmp ptr_IWICBitmapEncoder_GetMetadataQueryWriter_Proxy
IWICBitmapEncoder_GetMetadataQueryWriter_Proxy ENDP

IWICBitmapEncoder_Initialize_Proxy PROC
jmp ptr_IWICBitmapEncoder_Initialize_Proxy
IWICBitmapEncoder_Initialize_Proxy ENDP

IWICBitmapEncoder_SetPalette_Proxy PROC
jmp ptr_IWICBitmapEncoder_SetPalette_Proxy
IWICBitmapEncoder_SetPalette_Proxy ENDP

IWICBitmapEncoder_SetThumbnail_Proxy PROC
jmp ptr_IWICBitmapEncoder_SetThumbnail_Proxy
IWICBitmapEncoder_SetThumbnail_Proxy ENDP

IWICBitmapFlipRotator_Initialize_Proxy PROC
jmp ptr_IWICBitmapFlipRotator_Initialize_Proxy
IWICBitmapFlipRotator_Initialize_Proxy ENDP

IWICBitmapFrameDecode_GetColorContexts_Proxy PROC
jmp ptr_IWICBitmapFrameDecode_GetColorContexts_Proxy
IWICBitmapFrameDecode_GetColorContexts_Proxy ENDP

IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy PROC
jmp ptr_IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy
IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy ENDP

IWICBitmapFrameDecode_GetThumbnail_Proxy PROC
jmp ptr_IWICBitmapFrameDecode_GetThumbnail_Proxy
IWICBitmapFrameDecode_GetThumbnail_Proxy ENDP

IWICBitmapFrameEncode_Commit_Proxy PROC
jmp ptr_IWICBitmapFrameEncode_Commit_Proxy
IWICBitmapFrameEncode_Commit_Proxy ENDP

IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy PROC
jmp ptr_IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy
IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy ENDP

IWICBitmapFrameEncode_Initialize_Proxy PROC
jmp ptr_IWICBitmapFrameEncode_Initialize_Proxy
IWICBitmapFrameEncode_Initialize_Proxy ENDP

IWICBitmapFrameEncode_SetColorContexts_Proxy PROC
jmp ptr_IWICBitmapFrameEncode_SetColorContexts_Proxy
IWICBitmapFrameEncode_SetColorContexts_Proxy ENDP

IWICBitmapFrameEncode_SetResolution_Proxy PROC
jmp ptr_IWICBitmapFrameEncode_SetResolution_Proxy
IWICBitmapFrameEncode_SetResolution_Proxy ENDP

IWICBitmapFrameEncode_SetSize_Proxy PROC
jmp ptr_IWICBitmapFrameEncode_SetSize_Proxy
IWICBitmapFrameEncode_SetSize_Proxy ENDP

IWICBitmapFrameEncode_SetThumbnail_Proxy PROC
jmp ptr_IWICBitmapFrameEncode_SetThumbnail_Proxy
IWICBitmapFrameEncode_SetThumbnail_Proxy ENDP

IWICBitmapFrameEncode_WriteSource_Proxy PROC
jmp ptr_IWICBitmapFrameEncode_WriteSource_Proxy
IWICBitmapFrameEncode_WriteSource_Proxy ENDP

IWICBitmapLock_GetDataPointer_STA_Proxy PROC
jmp ptr_IWICBitmapLock_GetDataPointer_STA_Proxy
IWICBitmapLock_GetDataPointer_STA_Proxy ENDP

IWICBitmapLock_GetStride_Proxy PROC
jmp ptr_IWICBitmapLock_GetStride_Proxy
IWICBitmapLock_GetStride_Proxy ENDP

IWICBitmapScaler_Initialize_Proxy PROC
jmp ptr_IWICBitmapScaler_Initialize_Proxy
IWICBitmapScaler_Initialize_Proxy ENDP

IWICBitmapSource_CopyPalette_Proxy PROC
jmp ptr_IWICBitmapSource_CopyPalette_Proxy
IWICBitmapSource_CopyPalette_Proxy ENDP

IWICBitmapSource_CopyPixels_Proxy PROC
jmp ptr_IWICBitmapSource_CopyPixels_Proxy
IWICBitmapSource_CopyPixels_Proxy ENDP

IWICBitmapSource_GetPixelFormat_Proxy PROC
jmp ptr_IWICBitmapSource_GetPixelFormat_Proxy
IWICBitmapSource_GetPixelFormat_Proxy ENDP

IWICBitmapSource_GetResolution_Proxy PROC
jmp ptr_IWICBitmapSource_GetResolution_Proxy
IWICBitmapSource_GetResolution_Proxy ENDP

IWICBitmapSource_GetSize_Proxy PROC
jmp ptr_IWICBitmapSource_GetSize_Proxy
IWICBitmapSource_GetSize_Proxy ENDP

IWICBitmap_Lock_Proxy PROC
jmp ptr_IWICBitmap_Lock_Proxy
IWICBitmap_Lock_Proxy ENDP

IWICBitmap_SetPalette_Proxy PROC
jmp ptr_IWICBitmap_SetPalette_Proxy
IWICBitmap_SetPalette_Proxy ENDP

IWICBitmap_SetResolution_Proxy PROC
jmp ptr_IWICBitmap_SetResolution_Proxy
IWICBitmap_SetResolution_Proxy ENDP

IWICColorContext_InitializeFromMemory_Proxy PROC
jmp ptr_IWICColorContext_InitializeFromMemory_Proxy
IWICColorContext_InitializeFromMemory_Proxy ENDP

IWICComponentFactory_CreateMetadataWriterFromReader_Proxy PROC
jmp ptr_IWICComponentFactory_CreateMetadataWriterFromReader_Proxy
IWICComponentFactory_CreateMetadataWriterFromReader_Proxy ENDP

IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy PROC
jmp ptr_IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy
IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy ENDP

IWICComponentInfo_GetAuthor_Proxy PROC
jmp ptr_IWICComponentInfo_GetAuthor_Proxy
IWICComponentInfo_GetAuthor_Proxy ENDP

IWICComponentInfo_GetCLSID_Proxy PROC
jmp ptr_IWICComponentInfo_GetCLSID_Proxy
IWICComponentInfo_GetCLSID_Proxy ENDP

IWICComponentInfo_GetFriendlyName_Proxy PROC
jmp ptr_IWICComponentInfo_GetFriendlyName_Proxy
IWICComponentInfo_GetFriendlyName_Proxy ENDP

IWICComponentInfo_GetSpecVersion_Proxy PROC
jmp ptr_IWICComponentInfo_GetSpecVersion_Proxy
IWICComponentInfo_GetSpecVersion_Proxy ENDP

IWICComponentInfo_GetVersion_Proxy PROC
jmp ptr_IWICComponentInfo_GetVersion_Proxy
IWICComponentInfo_GetVersion_Proxy ENDP

IWICFastMetadataEncoder_Commit_Proxy PROC
jmp ptr_IWICFastMetadataEncoder_Commit_Proxy
IWICFastMetadataEncoder_Commit_Proxy ENDP

IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy PROC
jmp ptr_IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy
IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy ENDP

IWICFormatConverter_Initialize_Proxy PROC
jmp ptr_IWICFormatConverter_Initialize_Proxy
IWICFormatConverter_Initialize_Proxy ENDP

IWICImagingFactory_CreateBitmapClipper_Proxy PROC
jmp ptr_IWICImagingFactory_CreateBitmapClipper_Proxy
IWICImagingFactory_CreateBitmapClipper_Proxy ENDP

IWICImagingFactory_CreateBitmapFlipRotator_Proxy PROC
jmp ptr_IWICImagingFactory_CreateBitmapFlipRotator_Proxy
IWICImagingFactory_CreateBitmapFlipRotator_Proxy ENDP

IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy PROC
jmp ptr_IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy
IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy ENDP

IWICImagingFactory_CreateBitmapFromHICON_Proxy PROC
jmp ptr_IWICImagingFactory_CreateBitmapFromHICON_Proxy
IWICImagingFactory_CreateBitmapFromHICON_Proxy ENDP

IWICImagingFactory_CreateBitmapFromMemory_Proxy PROC
jmp ptr_IWICImagingFactory_CreateBitmapFromMemory_Proxy
IWICImagingFactory_CreateBitmapFromMemory_Proxy ENDP

IWICImagingFactory_CreateBitmapFromSource_Proxy PROC
jmp ptr_IWICImagingFactory_CreateBitmapFromSource_Proxy
IWICImagingFactory_CreateBitmapFromSource_Proxy ENDP

IWICImagingFactory_CreateBitmapScaler_Proxy PROC
jmp ptr_IWICImagingFactory_CreateBitmapScaler_Proxy
IWICImagingFactory_CreateBitmapScaler_Proxy ENDP

IWICImagingFactory_CreateBitmap_Proxy PROC
jmp ptr_IWICImagingFactory_CreateBitmap_Proxy
IWICImagingFactory_CreateBitmap_Proxy ENDP

IWICImagingFactory_CreateComponentInfo_Proxy PROC
jmp ptr_IWICImagingFactory_CreateComponentInfo_Proxy
IWICImagingFactory_CreateComponentInfo_Proxy ENDP

IWICImagingFactory_CreateDecoderFromFileHandle_Proxy PROC
jmp ptr_IWICImagingFactory_CreateDecoderFromFileHandle_Proxy
IWICImagingFactory_CreateDecoderFromFileHandle_Proxy ENDP

IWICImagingFactory_CreateDecoderFromFilename_Proxy PROC
jmp ptr_IWICImagingFactory_CreateDecoderFromFilename_Proxy
IWICImagingFactory_CreateDecoderFromFilename_Proxy ENDP

IWICImagingFactory_CreateDecoderFromStream_Proxy PROC
jmp ptr_IWICImagingFactory_CreateDecoderFromStream_Proxy
IWICImagingFactory_CreateDecoderFromStream_Proxy ENDP

IWICImagingFactory_CreateEncoder_Proxy PROC
jmp ptr_IWICImagingFactory_CreateEncoder_Proxy
IWICImagingFactory_CreateEncoder_Proxy ENDP

IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy PROC
jmp ptr_IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy
IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy ENDP

IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy PROC
jmp ptr_IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy
IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy ENDP

IWICImagingFactory_CreateFormatConverter_Proxy PROC
jmp ptr_IWICImagingFactory_CreateFormatConverter_Proxy
IWICImagingFactory_CreateFormatConverter_Proxy ENDP

IWICImagingFactory_CreatePalette_Proxy PROC
jmp ptr_IWICImagingFactory_CreatePalette_Proxy
IWICImagingFactory_CreatePalette_Proxy ENDP

IWICImagingFactory_CreateQueryWriterFromReader_Proxy PROC
jmp ptr_IWICImagingFactory_CreateQueryWriterFromReader_Proxy
IWICImagingFactory_CreateQueryWriterFromReader_Proxy ENDP

IWICImagingFactory_CreateQueryWriter_Proxy PROC
jmp ptr_IWICImagingFactory_CreateQueryWriter_Proxy
IWICImagingFactory_CreateQueryWriter_Proxy ENDP

IWICImagingFactory_CreateStream_Proxy PROC
jmp ptr_IWICImagingFactory_CreateStream_Proxy
IWICImagingFactory_CreateStream_Proxy ENDP

IWICMetadataBlockReader_GetCount_Proxy PROC
jmp ptr_IWICMetadataBlockReader_GetCount_Proxy
IWICMetadataBlockReader_GetCount_Proxy ENDP

IWICMetadataBlockReader_GetReaderByIndex_Proxy PROC
jmp ptr_IWICMetadataBlockReader_GetReaderByIndex_Proxy
IWICMetadataBlockReader_GetReaderByIndex_Proxy ENDP

IWICMetadataQueryReader_GetContainerFormat_Proxy PROC
jmp ptr_IWICMetadataQueryReader_GetContainerFormat_Proxy
IWICMetadataQueryReader_GetContainerFormat_Proxy ENDP

IWICMetadataQueryReader_GetEnumerator_Proxy PROC
jmp ptr_IWICMetadataQueryReader_GetEnumerator_Proxy
IWICMetadataQueryReader_GetEnumerator_Proxy ENDP

IWICMetadataQueryReader_GetLocation_Proxy PROC
jmp ptr_IWICMetadataQueryReader_GetLocation_Proxy
IWICMetadataQueryReader_GetLocation_Proxy ENDP

IWICMetadataQueryReader_GetMetadataByName_Proxy PROC
jmp ptr_IWICMetadataQueryReader_GetMetadataByName_Proxy
IWICMetadataQueryReader_GetMetadataByName_Proxy ENDP

IWICMetadataQueryWriter_RemoveMetadataByName_Proxy PROC
jmp ptr_IWICMetadataQueryWriter_RemoveMetadataByName_Proxy
IWICMetadataQueryWriter_RemoveMetadataByName_Proxy ENDP

IWICMetadataQueryWriter_SetMetadataByName_Proxy PROC
jmp ptr_IWICMetadataQueryWriter_SetMetadataByName_Proxy
IWICMetadataQueryWriter_SetMetadataByName_Proxy ENDP

IWICPalette_GetColorCount_Proxy PROC
jmp ptr_IWICPalette_GetColorCount_Proxy
IWICPalette_GetColorCount_Proxy ENDP

IWICPalette_GetColors_Proxy PROC
jmp ptr_IWICPalette_GetColors_Proxy
IWICPalette_GetColors_Proxy ENDP

IWICPalette_GetType_Proxy PROC
jmp ptr_IWICPalette_GetType_Proxy
IWICPalette_GetType_Proxy ENDP

IWICPalette_HasAlpha_Proxy PROC
jmp ptr_IWICPalette_HasAlpha_Proxy
IWICPalette_HasAlpha_Proxy ENDP

IWICPalette_InitializeCustom_Proxy PROC
jmp ptr_IWICPalette_InitializeCustom_Proxy
IWICPalette_InitializeCustom_Proxy ENDP

IWICPalette_InitializeFromBitmap_Proxy PROC
jmp ptr_IWICPalette_InitializeFromBitmap_Proxy
IWICPalette_InitializeFromBitmap_Proxy ENDP

IWICPalette_InitializeFromPalette_Proxy PROC
jmp ptr_IWICPalette_InitializeFromPalette_Proxy
IWICPalette_InitializeFromPalette_Proxy ENDP

IWICPalette_InitializePredefined_Proxy PROC
jmp ptr_IWICPalette_InitializePredefined_Proxy
IWICPalette_InitializePredefined_Proxy ENDP

IWICPixelFormatInfo_GetBitsPerPixel_Proxy PROC
jmp ptr_IWICPixelFormatInfo_GetBitsPerPixel_Proxy
IWICPixelFormatInfo_GetBitsPerPixel_Proxy ENDP

IWICPixelFormatInfo_GetChannelCount_Proxy PROC
jmp ptr_IWICPixelFormatInfo_GetChannelCount_Proxy
IWICPixelFormatInfo_GetChannelCount_Proxy ENDP

IWICPixelFormatInfo_GetChannelMask_Proxy PROC
jmp ptr_IWICPixelFormatInfo_GetChannelMask_Proxy
IWICPixelFormatInfo_GetChannelMask_Proxy ENDP

IWICStream_InitializeFromIStream_Proxy PROC
jmp ptr_IWICStream_InitializeFromIStream_Proxy
IWICStream_InitializeFromIStream_Proxy ENDP

IWICStream_InitializeFromMemory_Proxy PROC
jmp ptr_IWICStream_InitializeFromMemory_Proxy
IWICStream_InitializeFromMemory_Proxy ENDP

WICConvertBitmapSource PROC
jmp ptr_WICConvertBitmapSource
WICConvertBitmapSource ENDP

WICCreateBitmapFromSection PROC
jmp ptr_WICCreateBitmapFromSection
WICCreateBitmapFromSection ENDP

WICCreateBitmapFromSectionEx PROC
jmp ptr_WICCreateBitmapFromSectionEx
WICCreateBitmapFromSectionEx ENDP

WICCreateColorContext_Proxy PROC
jmp ptr_WICCreateColorContext_Proxy
WICCreateColorContext_Proxy ENDP

WICCreateImagingFactory_Proxy PROC
jmp ptr_WICCreateImagingFactory_Proxy
WICCreateImagingFactory_Proxy ENDP

WICGetMetadataContentSize PROC
jmp ptr_WICGetMetadataContentSize
WICGetMetadataContentSize ENDP

WICMapGuidToShortName PROC
jmp ptr_WICMapGuidToShortName
WICMapGuidToShortName ENDP

WICMapSchemaToName PROC
jmp ptr_WICMapSchemaToName
WICMapSchemaToName ENDP

WICMapShortNameToGuid PROC
jmp ptr_WICMapShortNameToGuid
WICMapShortNameToGuid ENDP

WICMatchMetadataContent PROC
jmp ptr_WICMatchMetadataContent
WICMatchMetadataContent ENDP

WICSerializeMetadataContent PROC
jmp ptr_WICSerializeMetadataContent
WICSerializeMetadataContent ENDP

WICSetEncoderFormat_Proxy PROC
jmp ptr_WICSetEncoderFormat_Proxy
WICSetEncoderFormat_Proxy ENDP

end
