#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_AppCacheCheckManifest;
void *ptr_AppCacheCheckManifest = NULL;
extern void *ptr_AppCacheCloseHandle;
void *ptr_AppCacheCloseHandle = NULL;
extern void *ptr_AppCacheDeleteGroup;
void *ptr_AppCacheDeleteGroup = NULL;
extern void *ptr_AppCacheDeleteIEGroup;
void *ptr_AppCacheDeleteIEGroup = NULL;
extern void *ptr_AppCacheDuplicateHandle;
void *ptr_AppCacheDuplicateHandle = NULL;
extern void *ptr_AppCacheFinalize;
void *ptr_AppCacheFinalize = NULL;
extern void *ptr_AppCacheFreeDownloadList;
void *ptr_AppCacheFreeDownloadList = NULL;
extern void *ptr_AppCacheFreeGroupList;
void *ptr_AppCacheFreeGroupList = NULL;
extern void *ptr_AppCacheFreeIESpace;
void *ptr_AppCacheFreeIESpace = NULL;
extern void *ptr_AppCacheFreeSpace;
void *ptr_AppCacheFreeSpace = NULL;
extern void *ptr_AppCacheGetDownloadList;
void *ptr_AppCacheGetDownloadList = NULL;
extern void *ptr_AppCacheGetFallbackUrl;
void *ptr_AppCacheGetFallbackUrl = NULL;
extern void *ptr_AppCacheGetGroupList;
void *ptr_AppCacheGetGroupList = NULL;
extern void *ptr_AppCacheGetIEGroupList;
void *ptr_AppCacheGetIEGroupList = NULL;
extern void *ptr_AppCacheGetInfo;
void *ptr_AppCacheGetInfo = NULL;
extern void *ptr_AppCacheGetManifestUrl;
void *ptr_AppCacheGetManifestUrl = NULL;
extern void *ptr_AppCacheLookup;
void *ptr_AppCacheLookup = NULL;
extern void *ptr_CommitUrlCacheEntryA;
void *ptr_CommitUrlCacheEntryA = NULL;
extern void *ptr_CommitUrlCacheEntryBinaryBlob;
void *ptr_CommitUrlCacheEntryBinaryBlob = NULL;
extern void *ptr_CommitUrlCacheEntryW;
void *ptr_CommitUrlCacheEntryW = NULL;
extern void *ptr_CreateMD5SSOHash;
void *ptr_CreateMD5SSOHash = NULL;
extern void *ptr_CreateUrlCacheContainerA;
void *ptr_CreateUrlCacheContainerA = NULL;
extern void *ptr_CreateUrlCacheContainerW;
void *ptr_CreateUrlCacheContainerW = NULL;
extern void *ptr_CreateUrlCacheEntryA;
void *ptr_CreateUrlCacheEntryA = NULL;
extern void *ptr_CreateUrlCacheEntryExW;
void *ptr_CreateUrlCacheEntryExW = NULL;
extern void *ptr_CreateUrlCacheEntryW;
void *ptr_CreateUrlCacheEntryW = NULL;
extern void *ptr_CreateUrlCacheGroup;
void *ptr_CreateUrlCacheGroup = NULL;
extern void *ptr_DeleteIE3Cache;
void *ptr_DeleteIE3Cache = NULL;
extern void *ptr_DeleteUrlCacheContainerA;
void *ptr_DeleteUrlCacheContainerA = NULL;
extern void *ptr_DeleteUrlCacheContainerW;
void *ptr_DeleteUrlCacheContainerW = NULL;
extern void *ptr_DeleteUrlCacheEntry;
void *ptr_DeleteUrlCacheEntry = NULL;
extern void *ptr_DeleteUrlCacheEntryA;
void *ptr_DeleteUrlCacheEntryA = NULL;
extern void *ptr_DeleteUrlCacheEntryW;
void *ptr_DeleteUrlCacheEntryW = NULL;
extern void *ptr_DeleteUrlCacheGroup;
void *ptr_DeleteUrlCacheGroup = NULL;
extern void *ptr_DeleteWpadCacheForNetworks;
void *ptr_DeleteWpadCacheForNetworks = NULL;
extern void *ptr_DetectAutoProxyUrl;
void *ptr_DetectAutoProxyUrl = NULL;
extern void *ptr_DispatchAPICall;
void *ptr_DispatchAPICall = NULL;
extern void *ptr_DllCanUnloadNow;
void *ptr_DllCanUnloadNow = NULL;
extern void *ptr_DllGetClassObject;
void *ptr_DllGetClassObject = NULL;
extern void *ptr_DllInstall;
void *ptr_DllInstall = NULL;
extern void *ptr_DllRegisterServer;
void *ptr_DllRegisterServer = NULL;
extern void *ptr_DllUnregisterServer;
void *ptr_DllUnregisterServer = NULL;
extern void *ptr_FindCloseUrlCache;
void *ptr_FindCloseUrlCache = NULL;
extern void *ptr_FindFirstUrlCacheContainerA;
void *ptr_FindFirstUrlCacheContainerA = NULL;
extern void *ptr_FindFirstUrlCacheContainerW;
void *ptr_FindFirstUrlCacheContainerW = NULL;
extern void *ptr_FindFirstUrlCacheEntryA;
void *ptr_FindFirstUrlCacheEntryA = NULL;
extern void *ptr_FindFirstUrlCacheEntryExA;
void *ptr_FindFirstUrlCacheEntryExA = NULL;
extern void *ptr_FindFirstUrlCacheEntryExW;
void *ptr_FindFirstUrlCacheEntryExW = NULL;
extern void *ptr_FindFirstUrlCacheEntryW;
void *ptr_FindFirstUrlCacheEntryW = NULL;
extern void *ptr_FindFirstUrlCacheGroup;
void *ptr_FindFirstUrlCacheGroup = NULL;
extern void *ptr_FindNextUrlCacheContainerA;
void *ptr_FindNextUrlCacheContainerA = NULL;
extern void *ptr_FindNextUrlCacheContainerW;
void *ptr_FindNextUrlCacheContainerW = NULL;
extern void *ptr_FindNextUrlCacheEntryA;
void *ptr_FindNextUrlCacheEntryA = NULL;
extern void *ptr_FindNextUrlCacheEntryExA;
void *ptr_FindNextUrlCacheEntryExA = NULL;
extern void *ptr_FindNextUrlCacheEntryExW;
void *ptr_FindNextUrlCacheEntryExW = NULL;
extern void *ptr_FindNextUrlCacheEntryW;
void *ptr_FindNextUrlCacheEntryW = NULL;
extern void *ptr_FindNextUrlCacheGroup;
void *ptr_FindNextUrlCacheGroup = NULL;
extern void *ptr_ForceNexusLookup;
void *ptr_ForceNexusLookup = NULL;
extern void *ptr_ForceNexusLookupExW;
void *ptr_ForceNexusLookupExW = NULL;
extern void *ptr_FreeUrlCacheSpaceA;
void *ptr_FreeUrlCacheSpaceA = NULL;
extern void *ptr_FreeUrlCacheSpaceW;
void *ptr_FreeUrlCacheSpaceW = NULL;
extern void *ptr_FtpCommandA;
void *ptr_FtpCommandA = NULL;
extern void *ptr_FtpCommandW;
void *ptr_FtpCommandW = NULL;
extern void *ptr_FtpCreateDirectoryA;
void *ptr_FtpCreateDirectoryA = NULL;
extern void *ptr_FtpCreateDirectoryW;
void *ptr_FtpCreateDirectoryW = NULL;
extern void *ptr_FtpDeleteFileA;
void *ptr_FtpDeleteFileA = NULL;
extern void *ptr_FtpDeleteFileW;
void *ptr_FtpDeleteFileW = NULL;
extern void *ptr_FtpFindFirstFileA;
void *ptr_FtpFindFirstFileA = NULL;
extern void *ptr_FtpFindFirstFileW;
void *ptr_FtpFindFirstFileW = NULL;
extern void *ptr_FtpGetCurrentDirectoryA;
void *ptr_FtpGetCurrentDirectoryA = NULL;
extern void *ptr_FtpGetCurrentDirectoryW;
void *ptr_FtpGetCurrentDirectoryW = NULL;
extern void *ptr_FtpGetFileA;
void *ptr_FtpGetFileA = NULL;
extern void *ptr_FtpGetFileEx;
void *ptr_FtpGetFileEx = NULL;
extern void *ptr_FtpGetFileSize;
void *ptr_FtpGetFileSize = NULL;
extern void *ptr_FtpGetFileW;
void *ptr_FtpGetFileW = NULL;
extern void *ptr_FtpOpenFileA;
void *ptr_FtpOpenFileA = NULL;
extern void *ptr_FtpOpenFileW;
void *ptr_FtpOpenFileW = NULL;
extern void *ptr_FtpPutFileA;
void *ptr_FtpPutFileA = NULL;
extern void *ptr_FtpPutFileEx;
void *ptr_FtpPutFileEx = NULL;
extern void *ptr_FtpPutFileW;
void *ptr_FtpPutFileW = NULL;
extern void *ptr_FtpRemoveDirectoryA;
void *ptr_FtpRemoveDirectoryA = NULL;
extern void *ptr_FtpRemoveDirectoryW;
void *ptr_FtpRemoveDirectoryW = NULL;
extern void *ptr_FtpRenameFileA;
void *ptr_FtpRenameFileA = NULL;
extern void *ptr_FtpRenameFileW;
void *ptr_FtpRenameFileW = NULL;
extern void *ptr_FtpSetCurrentDirectoryA;
void *ptr_FtpSetCurrentDirectoryA = NULL;
extern void *ptr_FtpSetCurrentDirectoryW;
void *ptr_FtpSetCurrentDirectoryW = NULL;
extern void *ptr_GetProxyDllInfo;
void *ptr_GetProxyDllInfo = NULL;
extern void *ptr_GetUrlCacheConfigInfoA;
void *ptr_GetUrlCacheConfigInfoA = NULL;
extern void *ptr_GetUrlCacheConfigInfoW;
void *ptr_GetUrlCacheConfigInfoW = NULL;
extern void *ptr_GetUrlCacheEntryBinaryBlob;
void *ptr_GetUrlCacheEntryBinaryBlob = NULL;
extern void *ptr_GetUrlCacheEntryInfoA;
void *ptr_GetUrlCacheEntryInfoA = NULL;
extern void *ptr_GetUrlCacheEntryInfoExA;
void *ptr_GetUrlCacheEntryInfoExA = NULL;
extern void *ptr_GetUrlCacheEntryInfoExW;
void *ptr_GetUrlCacheEntryInfoExW = NULL;
extern void *ptr_GetUrlCacheEntryInfoW;
void *ptr_GetUrlCacheEntryInfoW = NULL;
extern void *ptr_GetUrlCacheGroupAttributeA;
void *ptr_GetUrlCacheGroupAttributeA = NULL;
extern void *ptr_GetUrlCacheGroupAttributeW;
void *ptr_GetUrlCacheGroupAttributeW = NULL;
extern void *ptr_GetUrlCacheHeaderData;
void *ptr_GetUrlCacheHeaderData = NULL;
extern void *ptr_GopherCreateLocatorA;
void *ptr_GopherCreateLocatorA = NULL;
extern void *ptr_GopherCreateLocatorW;
void *ptr_GopherCreateLocatorW = NULL;
extern void *ptr_GopherFindFirstFileA;
void *ptr_GopherFindFirstFileA = NULL;
extern void *ptr_GopherFindFirstFileW;
void *ptr_GopherFindFirstFileW = NULL;
extern void *ptr_GopherGetAttributeA;
void *ptr_GopherGetAttributeA = NULL;
extern void *ptr_GopherGetAttributeW;
void *ptr_GopherGetAttributeW = NULL;
extern void *ptr_GopherGetLocatorTypeA;
void *ptr_GopherGetLocatorTypeA = NULL;
extern void *ptr_GopherGetLocatorTypeW;
void *ptr_GopherGetLocatorTypeW = NULL;
extern void *ptr_GopherOpenFileA;
void *ptr_GopherOpenFileA = NULL;
extern void *ptr_GopherOpenFileW;
void *ptr_GopherOpenFileW = NULL;
extern void *ptr_HttpAddRequestHeadersA;
void *ptr_HttpAddRequestHeadersA = NULL;
extern void *ptr_HttpAddRequestHeadersW;
void *ptr_HttpAddRequestHeadersW = NULL;
extern void *ptr_HttpCheckDavCompliance;
void *ptr_HttpCheckDavCompliance = NULL;
extern void *ptr_HttpCloseDependencyHandle;
void *ptr_HttpCloseDependencyHandle = NULL;
extern void *ptr_HttpDuplicateDependencyHandle;
void *ptr_HttpDuplicateDependencyHandle = NULL;
extern void *ptr_HttpEndRequestA;
void *ptr_HttpEndRequestA = NULL;
extern void *ptr_HttpEndRequestW;
void *ptr_HttpEndRequestW = NULL;
extern void *ptr_HttpGetServerCredentials;
void *ptr_HttpGetServerCredentials = NULL;
extern void *ptr_HttpGetTunnelSocket;
void *ptr_HttpGetTunnelSocket = NULL;
extern void *ptr_HttpIsHostHstsEnabled;
void *ptr_HttpIsHostHstsEnabled = NULL;
extern void *ptr_HttpOpenDependencyHandle;
void *ptr_HttpOpenDependencyHandle = NULL;
extern void *ptr_HttpOpenRequestA;
void *ptr_HttpOpenRequestA = NULL;
extern void *ptr_HttpOpenRequestW;
void *ptr_HttpOpenRequestW = NULL;
extern void *ptr_HttpPushClose;
void *ptr_HttpPushClose = NULL;
extern void *ptr_HttpPushEnable;
void *ptr_HttpPushEnable = NULL;
extern void *ptr_HttpPushWait;
void *ptr_HttpPushWait = NULL;
extern void *ptr_HttpQueryInfoA;
void *ptr_HttpQueryInfoA = NULL;
extern void *ptr_HttpQueryInfoW;
void *ptr_HttpQueryInfoW = NULL;
extern void *ptr_HttpSendRequestA;
void *ptr_HttpSendRequestA = NULL;
extern void *ptr_HttpSendRequestExA;
void *ptr_HttpSendRequestExA = NULL;
extern void *ptr_HttpSendRequestExW;
void *ptr_HttpSendRequestExW = NULL;
extern void *ptr_HttpSendRequestW;
void *ptr_HttpSendRequestW = NULL;
extern void *ptr_HttpWebSocketClose;
void *ptr_HttpWebSocketClose = NULL;
extern void *ptr_HttpWebSocketCompleteUpgrade;
void *ptr_HttpWebSocketCompleteUpgrade = NULL;
extern void *ptr_HttpWebSocketQueryCloseStatus;
void *ptr_HttpWebSocketQueryCloseStatus = NULL;
extern void *ptr_HttpWebSocketReceive;
void *ptr_HttpWebSocketReceive = NULL;
extern void *ptr_HttpWebSocketSend;
void *ptr_HttpWebSocketSend = NULL;
extern void *ptr_HttpWebSocketShutdown;
void *ptr_HttpWebSocketShutdown = NULL;
extern void *ptr_IncrementUrlCacheHeaderData;
void *ptr_IncrementUrlCacheHeaderData = NULL;
extern void *ptr_InternetAlgIdToStringA;
void *ptr_InternetAlgIdToStringA = NULL;
extern void *ptr_InternetAlgIdToStringW;
void *ptr_InternetAlgIdToStringW = NULL;
extern void *ptr_InternetAttemptConnect;
void *ptr_InternetAttemptConnect = NULL;
extern void *ptr_InternetAutodial;
void *ptr_InternetAutodial = NULL;
extern void *ptr_InternetAutodialCallback;
void *ptr_InternetAutodialCallback = NULL;
extern void *ptr_InternetAutodialHangup;
void *ptr_InternetAutodialHangup = NULL;
extern void *ptr_InternetCanonicalizeUrlA;
void *ptr_InternetCanonicalizeUrlA = NULL;
extern void *ptr_InternetCanonicalizeUrlW;
void *ptr_InternetCanonicalizeUrlW = NULL;
extern void *ptr_InternetCheckConnectionA;
void *ptr_InternetCheckConnectionA = NULL;
extern void *ptr_InternetCheckConnectionW;
void *ptr_InternetCheckConnectionW = NULL;
extern void *ptr_InternetClearAllPerSiteCookieDecisions;
void *ptr_InternetClearAllPerSiteCookieDecisions = NULL;
extern void *ptr_InternetCloseHandle;
void *ptr_InternetCloseHandle = NULL;
extern void *ptr_InternetCombineUrlA;
void *ptr_InternetCombineUrlA = NULL;
extern void *ptr_InternetCombineUrlW;
void *ptr_InternetCombineUrlW = NULL;
extern void *ptr_InternetConfirmZoneCrossing;
void *ptr_InternetConfirmZoneCrossing = NULL;
extern void *ptr_InternetConfirmZoneCrossingA;
void *ptr_InternetConfirmZoneCrossingA = NULL;
extern void *ptr_InternetConfirmZoneCrossingW;
void *ptr_InternetConfirmZoneCrossingW = NULL;
extern void *ptr_InternetConnectA;
void *ptr_InternetConnectA = NULL;
extern void *ptr_InternetConnectW;
void *ptr_InternetConnectW = NULL;
extern void *ptr_InternetCrackUrlA;
void *ptr_InternetCrackUrlA = NULL;
extern void *ptr_InternetCrackUrlW;
void *ptr_InternetCrackUrlW = NULL;
extern void *ptr_InternetCreateUrlA;
void *ptr_InternetCreateUrlA = NULL;
extern void *ptr_InternetCreateUrlW;
void *ptr_InternetCreateUrlW = NULL;
extern void *ptr_InternetDial;
void *ptr_InternetDial = NULL;
extern void *ptr_InternetDialA;
void *ptr_InternetDialA = NULL;
extern void *ptr_InternetDialW;
void *ptr_InternetDialW = NULL;
extern void *ptr_InternetEnumPerSiteCookieDecisionA;
void *ptr_InternetEnumPerSiteCookieDecisionA = NULL;
extern void *ptr_InternetEnumPerSiteCookieDecisionW;
void *ptr_InternetEnumPerSiteCookieDecisionW = NULL;
extern void *ptr_InternetErrorDlg;
void *ptr_InternetErrorDlg = NULL;
extern void *ptr_InternetFindNextFileA;
void *ptr_InternetFindNextFileA = NULL;
extern void *ptr_InternetFindNextFileW;
void *ptr_InternetFindNextFileW = NULL;
extern void *ptr_InternetFortezzaCommand;
void *ptr_InternetFortezzaCommand = NULL;
extern void *ptr_InternetFreeCookies;
void *ptr_InternetFreeCookies = NULL;
extern void *ptr_InternetFreeProxyInfoList;
void *ptr_InternetFreeProxyInfoList = NULL;
extern void *ptr_InternetGetCertByURL;
void *ptr_InternetGetCertByURL = NULL;
extern void *ptr_InternetGetCertByURLA;
void *ptr_InternetGetCertByURLA = NULL;
extern void *ptr_InternetGetConnectedState;
void *ptr_InternetGetConnectedState = NULL;
extern void *ptr_InternetGetConnectedStateEx;
void *ptr_InternetGetConnectedStateEx = NULL;
extern void *ptr_InternetGetConnectedStateExA;
void *ptr_InternetGetConnectedStateExA = NULL;
extern void *ptr_InternetGetConnectedStateExW;
void *ptr_InternetGetConnectedStateExW = NULL;
extern void *ptr_InternetGetCookieA;
void *ptr_InternetGetCookieA = NULL;
extern void *ptr_InternetGetCookieEx2;
void *ptr_InternetGetCookieEx2 = NULL;
extern void *ptr_InternetGetCookieExA;
void *ptr_InternetGetCookieExA = NULL;
extern void *ptr_InternetGetCookieExW;
void *ptr_InternetGetCookieExW = NULL;
extern void *ptr_InternetGetCookieW;
void *ptr_InternetGetCookieW = NULL;
extern void *ptr_InternetGetLastResponseInfoA;
void *ptr_InternetGetLastResponseInfoA = NULL;
extern void *ptr_InternetGetLastResponseInfoW;
void *ptr_InternetGetLastResponseInfoW = NULL;
extern void *ptr_InternetGetPerSiteCookieDecisionA;
void *ptr_InternetGetPerSiteCookieDecisionA = NULL;
extern void *ptr_InternetGetPerSiteCookieDecisionW;
void *ptr_InternetGetPerSiteCookieDecisionW = NULL;
extern void *ptr_InternetGetProxyForUrl;
void *ptr_InternetGetProxyForUrl = NULL;
extern void *ptr_InternetGetSecurityInfoByURL;
void *ptr_InternetGetSecurityInfoByURL = NULL;
extern void *ptr_InternetGetSecurityInfoByURLA;
void *ptr_InternetGetSecurityInfoByURLA = NULL;
extern void *ptr_InternetGetSecurityInfoByURLW;
void *ptr_InternetGetSecurityInfoByURLW = NULL;
extern void *ptr_InternetGoOnline;
void *ptr_InternetGoOnline = NULL;
extern void *ptr_InternetGoOnlineA;
void *ptr_InternetGoOnlineA = NULL;
extern void *ptr_InternetGoOnlineW;
void *ptr_InternetGoOnlineW = NULL;
extern void *ptr_InternetHangUp;
void *ptr_InternetHangUp = NULL;
extern void *ptr_InternetInitializeAutoProxyDll;
void *ptr_InternetInitializeAutoProxyDll = NULL;
extern void *ptr_InternetLockRequestFile;
void *ptr_InternetLockRequestFile = NULL;
extern void *ptr_InternetOpenA;
void *ptr_InternetOpenA = NULL;
extern void *ptr_InternetOpenUrlA;
void *ptr_InternetOpenUrlA = NULL;
extern void *ptr_InternetOpenUrlW;
void *ptr_InternetOpenUrlW = NULL;
extern void *ptr_InternetOpenW;
void *ptr_InternetOpenW = NULL;
extern void *ptr_InternetQueryDataAvailable;
void *ptr_InternetQueryDataAvailable = NULL;
extern void *ptr_InternetQueryFortezzaStatus;
void *ptr_InternetQueryFortezzaStatus = NULL;
extern void *ptr_InternetQueryOptionA;
void *ptr_InternetQueryOptionA = NULL;
extern void *ptr_InternetQueryOptionW;
void *ptr_InternetQueryOptionW = NULL;
extern void *ptr_InternetReadFile;
void *ptr_InternetReadFile = NULL;
extern void *ptr_InternetReadFileExA;
void *ptr_InternetReadFileExA = NULL;
extern void *ptr_InternetReadFileExW;
void *ptr_InternetReadFileExW = NULL;
extern void *ptr_InternetSecurityProtocolToStringA;
void *ptr_InternetSecurityProtocolToStringA = NULL;
extern void *ptr_InternetSecurityProtocolToStringW;
void *ptr_InternetSecurityProtocolToStringW = NULL;
extern void *ptr_InternetSetCookieA;
void *ptr_InternetSetCookieA = NULL;
extern void *ptr_InternetSetCookieEx2;
void *ptr_InternetSetCookieEx2 = NULL;
extern void *ptr_InternetSetCookieExA;
void *ptr_InternetSetCookieExA = NULL;
extern void *ptr_InternetSetCookieExW;
void *ptr_InternetSetCookieExW = NULL;
extern void *ptr_InternetSetCookieW;
void *ptr_InternetSetCookieW = NULL;
extern void *ptr_InternetSetDialState;
void *ptr_InternetSetDialState = NULL;
extern void *ptr_InternetSetDialStateA;
void *ptr_InternetSetDialStateA = NULL;
extern void *ptr_InternetSetDialStateW;
void *ptr_InternetSetDialStateW = NULL;
extern void *ptr_InternetSetFilePointer;
void *ptr_InternetSetFilePointer = NULL;
extern void *ptr_InternetSetOptionA;
void *ptr_InternetSetOptionA = NULL;
extern void *ptr_InternetSetOptionExA;
void *ptr_InternetSetOptionExA = NULL;
extern void *ptr_InternetSetOptionExW;
void *ptr_InternetSetOptionExW = NULL;
extern void *ptr_InternetSetOptionW;
void *ptr_InternetSetOptionW = NULL;
extern void *ptr_InternetSetPerSiteCookieDecisionA;
void *ptr_InternetSetPerSiteCookieDecisionA = NULL;
extern void *ptr_InternetSetPerSiteCookieDecisionW;
void *ptr_InternetSetPerSiteCookieDecisionW = NULL;
extern void *ptr_InternetSetStatusCallback;
void *ptr_InternetSetStatusCallback = NULL;
extern void *ptr_InternetSetStatusCallbackA;
void *ptr_InternetSetStatusCallbackA = NULL;
extern void *ptr_InternetSetStatusCallbackW;
void *ptr_InternetSetStatusCallbackW = NULL;
extern void *ptr_InternetShowSecurityInfoByURL;
void *ptr_InternetShowSecurityInfoByURL = NULL;
extern void *ptr_InternetShowSecurityInfoByURLA;
void *ptr_InternetShowSecurityInfoByURLA = NULL;
extern void *ptr_InternetShowSecurityInfoByURLW;
void *ptr_InternetShowSecurityInfoByURLW = NULL;
extern void *ptr_InternetTimeFromSystemTime;
void *ptr_InternetTimeFromSystemTime = NULL;
extern void *ptr_InternetTimeFromSystemTimeA;
void *ptr_InternetTimeFromSystemTimeA = NULL;
extern void *ptr_InternetTimeFromSystemTimeW;
void *ptr_InternetTimeFromSystemTimeW = NULL;
extern void *ptr_InternetTimeToSystemTime;
void *ptr_InternetTimeToSystemTime = NULL;
extern void *ptr_InternetTimeToSystemTimeA;
void *ptr_InternetTimeToSystemTimeA = NULL;
extern void *ptr_InternetTimeToSystemTimeW;
void *ptr_InternetTimeToSystemTimeW = NULL;
extern void *ptr_InternetUnlockRequestFile;
void *ptr_InternetUnlockRequestFile = NULL;
extern void *ptr_InternetWriteFile;
void *ptr_InternetWriteFile = NULL;
extern void *ptr_InternetWriteFileExA;
void *ptr_InternetWriteFileExA = NULL;
extern void *ptr_InternetWriteFileExW;
void *ptr_InternetWriteFileExW = NULL;
extern void *ptr_IsHostInProxyBypassList;
void *ptr_IsHostInProxyBypassList = NULL;
extern void *ptr_IsUrlCacheEntryExpiredA;
void *ptr_IsUrlCacheEntryExpiredA = NULL;
extern void *ptr_IsUrlCacheEntryExpiredW;
void *ptr_IsUrlCacheEntryExpiredW = NULL;
extern void *ptr_LoadUrlCacheContent;
void *ptr_LoadUrlCacheContent = NULL;
extern void *ptr_ParseX509EncodedCertificateForListBoxEntry;
void *ptr_ParseX509EncodedCertificateForListBoxEntry = NULL;
extern void *ptr_PrivacyGetZonePreferenceW;
void *ptr_PrivacyGetZonePreferenceW = NULL;
extern void *ptr_PrivacySetZonePreferenceW;
void *ptr_PrivacySetZonePreferenceW = NULL;
extern void *ptr_ReadUrlCacheEntryStream;
void *ptr_ReadUrlCacheEntryStream = NULL;
extern void *ptr_ReadUrlCacheEntryStreamEx;
void *ptr_ReadUrlCacheEntryStreamEx = NULL;
extern void *ptr_RegisterUrlCacheNotification;
void *ptr_RegisterUrlCacheNotification = NULL;
extern void *ptr_ResumeSuspendedDownload;
void *ptr_ResumeSuspendedDownload = NULL;
extern void *ptr_RetrieveUrlCacheEntryFileA;
void *ptr_RetrieveUrlCacheEntryFileA = NULL;
extern void *ptr_RetrieveUrlCacheEntryFileW;
void *ptr_RetrieveUrlCacheEntryFileW = NULL;
extern void *ptr_RetrieveUrlCacheEntryStreamA;
void *ptr_RetrieveUrlCacheEntryStreamA = NULL;
extern void *ptr_RetrieveUrlCacheEntryStreamW;
void *ptr_RetrieveUrlCacheEntryStreamW = NULL;
extern void *ptr_RunOnceUrlCache;
void *ptr_RunOnceUrlCache = NULL;
extern void *ptr_SetUrlCacheConfigInfoA;
void *ptr_SetUrlCacheConfigInfoA = NULL;
extern void *ptr_SetUrlCacheConfigInfoW;
void *ptr_SetUrlCacheConfigInfoW = NULL;
extern void *ptr_SetUrlCacheEntryGroup;
void *ptr_SetUrlCacheEntryGroup = NULL;
extern void *ptr_SetUrlCacheEntryGroupA;
void *ptr_SetUrlCacheEntryGroupA = NULL;
extern void *ptr_SetUrlCacheEntryGroupW;
void *ptr_SetUrlCacheEntryGroupW = NULL;
extern void *ptr_SetUrlCacheEntryInfoA;
void *ptr_SetUrlCacheEntryInfoA = NULL;
extern void *ptr_SetUrlCacheEntryInfoW;
void *ptr_SetUrlCacheEntryInfoW = NULL;
extern void *ptr_SetUrlCacheGroupAttributeA;
void *ptr_SetUrlCacheGroupAttributeA = NULL;
extern void *ptr_SetUrlCacheGroupAttributeW;
void *ptr_SetUrlCacheGroupAttributeW = NULL;
extern void *ptr_SetUrlCacheHeaderData;
void *ptr_SetUrlCacheHeaderData = NULL;
extern void *ptr_ShowCertificate;
void *ptr_ShowCertificate = NULL;
extern void *ptr_ShowClientAuthCerts;
void *ptr_ShowClientAuthCerts = NULL;
extern void *ptr_ShowSecurityInfo;
void *ptr_ShowSecurityInfo = NULL;
extern void *ptr_ShowX509EncodedCertificate;
void *ptr_ShowX509EncodedCertificate = NULL;
extern void *ptr_UnlockUrlCacheEntryFile;
void *ptr_UnlockUrlCacheEntryFile = NULL;
extern void *ptr_UnlockUrlCacheEntryFileA;
void *ptr_UnlockUrlCacheEntryFileA = NULL;
extern void *ptr_UnlockUrlCacheEntryFileW;
void *ptr_UnlockUrlCacheEntryFileW = NULL;
extern void *ptr_UnlockUrlCacheEntryStream;
void *ptr_UnlockUrlCacheEntryStream = NULL;
extern void *ptr_UpdateUrlCacheContentPath;
void *ptr_UpdateUrlCacheContentPath = NULL;
extern void *ptr_UrlCacheCheckEntriesExist;
void *ptr_UrlCacheCheckEntriesExist = NULL;
extern void *ptr_UrlCacheCloseEntryHandle;
void *ptr_UrlCacheCloseEntryHandle = NULL;
extern void *ptr_UrlCacheContainerSetEntryMaximumAge;
void *ptr_UrlCacheContainerSetEntryMaximumAge = NULL;
extern void *ptr_UrlCacheCreateContainer;
void *ptr_UrlCacheCreateContainer = NULL;
extern void *ptr_UrlCacheFindFirstEntry;
void *ptr_UrlCacheFindFirstEntry = NULL;
extern void *ptr_UrlCacheFindNextEntry;
void *ptr_UrlCacheFindNextEntry = NULL;
extern void *ptr_UrlCacheFreeEntryInfo;
void *ptr_UrlCacheFreeEntryInfo = NULL;
extern void *ptr_UrlCacheGetContentPaths;
void *ptr_UrlCacheGetContentPaths = NULL;
extern void *ptr_UrlCacheGetEntryInfo;
void *ptr_UrlCacheGetEntryInfo = NULL;
extern void *ptr_UrlCacheGetGlobalLimit;
void *ptr_UrlCacheGetGlobalLimit = NULL;
extern void *ptr_UrlCacheReadEntryStream;
void *ptr_UrlCacheReadEntryStream = NULL;
extern void *ptr_UrlCacheReloadSettings;
void *ptr_UrlCacheReloadSettings = NULL;
extern void *ptr_UrlCacheRetrieveEntryFile;
void *ptr_UrlCacheRetrieveEntryFile = NULL;
extern void *ptr_UrlCacheRetrieveEntryStream;
void *ptr_UrlCacheRetrieveEntryStream = NULL;
extern void *ptr_UrlCacheSetGlobalLimit;
void *ptr_UrlCacheSetGlobalLimit = NULL;
extern void *ptr_UrlCacheUpdateEntryExtraData;
void *ptr_UrlCacheUpdateEntryExtraData = NULL;
extern void *ptr_UrlZonesDetach;
void *ptr_UrlZonesDetach = NULL;
extern void *ptr__GetFileExtensionFromUrl;
void *ptr__GetFileExtensionFromUrl = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\wininet.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_AppCacheCheckManifest = (__vartype(ptr_AppCacheCheckManifest))GetProcAddress(hModule, "AppCacheCheckManifest");
   ptr_AppCacheCloseHandle = (__vartype(ptr_AppCacheCloseHandle))GetProcAddress(hModule, "AppCacheCloseHandle");
   ptr_AppCacheDeleteGroup = (__vartype(ptr_AppCacheDeleteGroup))GetProcAddress(hModule, "AppCacheDeleteGroup");
   ptr_AppCacheDeleteIEGroup = (__vartype(ptr_AppCacheDeleteIEGroup))GetProcAddress(hModule, "AppCacheDeleteIEGroup");
   ptr_AppCacheDuplicateHandle = (__vartype(ptr_AppCacheDuplicateHandle))GetProcAddress(hModule, "AppCacheDuplicateHandle");
   ptr_AppCacheFinalize = (__vartype(ptr_AppCacheFinalize))GetProcAddress(hModule, "AppCacheFinalize");
   ptr_AppCacheFreeDownloadList = (__vartype(ptr_AppCacheFreeDownloadList))GetProcAddress(hModule, "AppCacheFreeDownloadList");
   ptr_AppCacheFreeGroupList = (__vartype(ptr_AppCacheFreeGroupList))GetProcAddress(hModule, "AppCacheFreeGroupList");
   ptr_AppCacheFreeIESpace = (__vartype(ptr_AppCacheFreeIESpace))GetProcAddress(hModule, "AppCacheFreeIESpace");
   ptr_AppCacheFreeSpace = (__vartype(ptr_AppCacheFreeSpace))GetProcAddress(hModule, "AppCacheFreeSpace");
   ptr_AppCacheGetDownloadList = (__vartype(ptr_AppCacheGetDownloadList))GetProcAddress(hModule, "AppCacheGetDownloadList");
   ptr_AppCacheGetFallbackUrl = (__vartype(ptr_AppCacheGetFallbackUrl))GetProcAddress(hModule, "AppCacheGetFallbackUrl");
   ptr_AppCacheGetGroupList = (__vartype(ptr_AppCacheGetGroupList))GetProcAddress(hModule, "AppCacheGetGroupList");
   ptr_AppCacheGetIEGroupList = (__vartype(ptr_AppCacheGetIEGroupList))GetProcAddress(hModule, "AppCacheGetIEGroupList");
   ptr_AppCacheGetInfo = (__vartype(ptr_AppCacheGetInfo))GetProcAddress(hModule, "AppCacheGetInfo");
   ptr_AppCacheGetManifestUrl = (__vartype(ptr_AppCacheGetManifestUrl))GetProcAddress(hModule, "AppCacheGetManifestUrl");
   ptr_AppCacheLookup = (__vartype(ptr_AppCacheLookup))GetProcAddress(hModule, "AppCacheLookup");
   ptr_CommitUrlCacheEntryA = (__vartype(ptr_CommitUrlCacheEntryA))GetProcAddress(hModule, "CommitUrlCacheEntryA");
   ptr_CommitUrlCacheEntryBinaryBlob = (__vartype(ptr_CommitUrlCacheEntryBinaryBlob))GetProcAddress(hModule, "CommitUrlCacheEntryBinaryBlob");
   ptr_CommitUrlCacheEntryW = (__vartype(ptr_CommitUrlCacheEntryW))GetProcAddress(hModule, "CommitUrlCacheEntryW");
   ptr_CreateMD5SSOHash = (__vartype(ptr_CreateMD5SSOHash))GetProcAddress(hModule, "CreateMD5SSOHash");
   ptr_CreateUrlCacheContainerA = (__vartype(ptr_CreateUrlCacheContainerA))GetProcAddress(hModule, "CreateUrlCacheContainerA");
   ptr_CreateUrlCacheContainerW = (__vartype(ptr_CreateUrlCacheContainerW))GetProcAddress(hModule, "CreateUrlCacheContainerW");
   ptr_CreateUrlCacheEntryA = (__vartype(ptr_CreateUrlCacheEntryA))GetProcAddress(hModule, "CreateUrlCacheEntryA");
   ptr_CreateUrlCacheEntryExW = (__vartype(ptr_CreateUrlCacheEntryExW))GetProcAddress(hModule, "CreateUrlCacheEntryExW");
   ptr_CreateUrlCacheEntryW = (__vartype(ptr_CreateUrlCacheEntryW))GetProcAddress(hModule, "CreateUrlCacheEntryW");
   ptr_CreateUrlCacheGroup = (__vartype(ptr_CreateUrlCacheGroup))GetProcAddress(hModule, "CreateUrlCacheGroup");
   ptr_DeleteIE3Cache = (__vartype(ptr_DeleteIE3Cache))GetProcAddress(hModule, "DeleteIE3Cache");
   ptr_DeleteUrlCacheContainerA = (__vartype(ptr_DeleteUrlCacheContainerA))GetProcAddress(hModule, "DeleteUrlCacheContainerA");
   ptr_DeleteUrlCacheContainerW = (__vartype(ptr_DeleteUrlCacheContainerW))GetProcAddress(hModule, "DeleteUrlCacheContainerW");
   ptr_DeleteUrlCacheEntry = (__vartype(ptr_DeleteUrlCacheEntry))GetProcAddress(hModule, "DeleteUrlCacheEntry");
   ptr_DeleteUrlCacheEntryA = (__vartype(ptr_DeleteUrlCacheEntryA))GetProcAddress(hModule, "DeleteUrlCacheEntryA");
   ptr_DeleteUrlCacheEntryW = (__vartype(ptr_DeleteUrlCacheEntryW))GetProcAddress(hModule, "DeleteUrlCacheEntryW");
   ptr_DeleteUrlCacheGroup = (__vartype(ptr_DeleteUrlCacheGroup))GetProcAddress(hModule, "DeleteUrlCacheGroup");
   ptr_DeleteWpadCacheForNetworks = (__vartype(ptr_DeleteWpadCacheForNetworks))GetProcAddress(hModule, "DeleteWpadCacheForNetworks");
   ptr_DetectAutoProxyUrl = (__vartype(ptr_DetectAutoProxyUrl))GetProcAddress(hModule, "DetectAutoProxyUrl");
   ptr_DispatchAPICall = (__vartype(ptr_DispatchAPICall))GetProcAddress(hModule, "DispatchAPICall");
   ptr_DllCanUnloadNow = (__vartype(ptr_DllCanUnloadNow))GetProcAddress(hModule, "DllCanUnloadNow");
   ptr_DllGetClassObject = (__vartype(ptr_DllGetClassObject))GetProcAddress(hModule, "DllGetClassObject");
   ptr_DllInstall = (__vartype(ptr_DllInstall))GetProcAddress(hModule, "DllInstall");
   ptr_DllRegisterServer = (__vartype(ptr_DllRegisterServer))GetProcAddress(hModule, "DllRegisterServer");
   ptr_DllUnregisterServer = (__vartype(ptr_DllUnregisterServer))GetProcAddress(hModule, "DllUnregisterServer");
   ptr_FindCloseUrlCache = (__vartype(ptr_FindCloseUrlCache))GetProcAddress(hModule, "FindCloseUrlCache");
   ptr_FindFirstUrlCacheContainerA = (__vartype(ptr_FindFirstUrlCacheContainerA))GetProcAddress(hModule, "FindFirstUrlCacheContainerA");
   ptr_FindFirstUrlCacheContainerW = (__vartype(ptr_FindFirstUrlCacheContainerW))GetProcAddress(hModule, "FindFirstUrlCacheContainerW");
   ptr_FindFirstUrlCacheEntryA = (__vartype(ptr_FindFirstUrlCacheEntryA))GetProcAddress(hModule, "FindFirstUrlCacheEntryA");
   ptr_FindFirstUrlCacheEntryExA = (__vartype(ptr_FindFirstUrlCacheEntryExA))GetProcAddress(hModule, "FindFirstUrlCacheEntryExA");
   ptr_FindFirstUrlCacheEntryExW = (__vartype(ptr_FindFirstUrlCacheEntryExW))GetProcAddress(hModule, "FindFirstUrlCacheEntryExW");
   ptr_FindFirstUrlCacheEntryW = (__vartype(ptr_FindFirstUrlCacheEntryW))GetProcAddress(hModule, "FindFirstUrlCacheEntryW");
   ptr_FindFirstUrlCacheGroup = (__vartype(ptr_FindFirstUrlCacheGroup))GetProcAddress(hModule, "FindFirstUrlCacheGroup");
   ptr_FindNextUrlCacheContainerA = (__vartype(ptr_FindNextUrlCacheContainerA))GetProcAddress(hModule, "FindNextUrlCacheContainerA");
   ptr_FindNextUrlCacheContainerW = (__vartype(ptr_FindNextUrlCacheContainerW))GetProcAddress(hModule, "FindNextUrlCacheContainerW");
   ptr_FindNextUrlCacheEntryA = (__vartype(ptr_FindNextUrlCacheEntryA))GetProcAddress(hModule, "FindNextUrlCacheEntryA");
   ptr_FindNextUrlCacheEntryExA = (__vartype(ptr_FindNextUrlCacheEntryExA))GetProcAddress(hModule, "FindNextUrlCacheEntryExA");
   ptr_FindNextUrlCacheEntryExW = (__vartype(ptr_FindNextUrlCacheEntryExW))GetProcAddress(hModule, "FindNextUrlCacheEntryExW");
   ptr_FindNextUrlCacheEntryW = (__vartype(ptr_FindNextUrlCacheEntryW))GetProcAddress(hModule, "FindNextUrlCacheEntryW");
   ptr_FindNextUrlCacheGroup = (__vartype(ptr_FindNextUrlCacheGroup))GetProcAddress(hModule, "FindNextUrlCacheGroup");
   ptr_ForceNexusLookup = (__vartype(ptr_ForceNexusLookup))GetProcAddress(hModule, "ForceNexusLookup");
   ptr_ForceNexusLookupExW = (__vartype(ptr_ForceNexusLookupExW))GetProcAddress(hModule, "ForceNexusLookupExW");
   ptr_FreeUrlCacheSpaceA = (__vartype(ptr_FreeUrlCacheSpaceA))GetProcAddress(hModule, "FreeUrlCacheSpaceA");
   ptr_FreeUrlCacheSpaceW = (__vartype(ptr_FreeUrlCacheSpaceW))GetProcAddress(hModule, "FreeUrlCacheSpaceW");
   ptr_FtpCommandA = (__vartype(ptr_FtpCommandA))GetProcAddress(hModule, "FtpCommandA");
   ptr_FtpCommandW = (__vartype(ptr_FtpCommandW))GetProcAddress(hModule, "FtpCommandW");
   ptr_FtpCreateDirectoryA = (__vartype(ptr_FtpCreateDirectoryA))GetProcAddress(hModule, "FtpCreateDirectoryA");
   ptr_FtpCreateDirectoryW = (__vartype(ptr_FtpCreateDirectoryW))GetProcAddress(hModule, "FtpCreateDirectoryW");
   ptr_FtpDeleteFileA = (__vartype(ptr_FtpDeleteFileA))GetProcAddress(hModule, "FtpDeleteFileA");
   ptr_FtpDeleteFileW = (__vartype(ptr_FtpDeleteFileW))GetProcAddress(hModule, "FtpDeleteFileW");
   ptr_FtpFindFirstFileA = (__vartype(ptr_FtpFindFirstFileA))GetProcAddress(hModule, "FtpFindFirstFileA");
   ptr_FtpFindFirstFileW = (__vartype(ptr_FtpFindFirstFileW))GetProcAddress(hModule, "FtpFindFirstFileW");
   ptr_FtpGetCurrentDirectoryA = (__vartype(ptr_FtpGetCurrentDirectoryA))GetProcAddress(hModule, "FtpGetCurrentDirectoryA");
   ptr_FtpGetCurrentDirectoryW = (__vartype(ptr_FtpGetCurrentDirectoryW))GetProcAddress(hModule, "FtpGetCurrentDirectoryW");
   ptr_FtpGetFileA = (__vartype(ptr_FtpGetFileA))GetProcAddress(hModule, "FtpGetFileA");
   ptr_FtpGetFileEx = (__vartype(ptr_FtpGetFileEx))GetProcAddress(hModule, "FtpGetFileEx");
   ptr_FtpGetFileSize = (__vartype(ptr_FtpGetFileSize))GetProcAddress(hModule, "FtpGetFileSize");
   ptr_FtpGetFileW = (__vartype(ptr_FtpGetFileW))GetProcAddress(hModule, "FtpGetFileW");
   ptr_FtpOpenFileA = (__vartype(ptr_FtpOpenFileA))GetProcAddress(hModule, "FtpOpenFileA");
   ptr_FtpOpenFileW = (__vartype(ptr_FtpOpenFileW))GetProcAddress(hModule, "FtpOpenFileW");
   ptr_FtpPutFileA = (__vartype(ptr_FtpPutFileA))GetProcAddress(hModule, "FtpPutFileA");
   ptr_FtpPutFileEx = (__vartype(ptr_FtpPutFileEx))GetProcAddress(hModule, "FtpPutFileEx");
   ptr_FtpPutFileW = (__vartype(ptr_FtpPutFileW))GetProcAddress(hModule, "FtpPutFileW");
   ptr_FtpRemoveDirectoryA = (__vartype(ptr_FtpRemoveDirectoryA))GetProcAddress(hModule, "FtpRemoveDirectoryA");
   ptr_FtpRemoveDirectoryW = (__vartype(ptr_FtpRemoveDirectoryW))GetProcAddress(hModule, "FtpRemoveDirectoryW");
   ptr_FtpRenameFileA = (__vartype(ptr_FtpRenameFileA))GetProcAddress(hModule, "FtpRenameFileA");
   ptr_FtpRenameFileW = (__vartype(ptr_FtpRenameFileW))GetProcAddress(hModule, "FtpRenameFileW");
   ptr_FtpSetCurrentDirectoryA = (__vartype(ptr_FtpSetCurrentDirectoryA))GetProcAddress(hModule, "FtpSetCurrentDirectoryA");
   ptr_FtpSetCurrentDirectoryW = (__vartype(ptr_FtpSetCurrentDirectoryW))GetProcAddress(hModule, "FtpSetCurrentDirectoryW");
   ptr_GetProxyDllInfo = (__vartype(ptr_GetProxyDllInfo))GetProcAddress(hModule, "GetProxyDllInfo");
   ptr_GetUrlCacheConfigInfoA = (__vartype(ptr_GetUrlCacheConfigInfoA))GetProcAddress(hModule, "GetUrlCacheConfigInfoA");
   ptr_GetUrlCacheConfigInfoW = (__vartype(ptr_GetUrlCacheConfigInfoW))GetProcAddress(hModule, "GetUrlCacheConfigInfoW");
   ptr_GetUrlCacheEntryBinaryBlob = (__vartype(ptr_GetUrlCacheEntryBinaryBlob))GetProcAddress(hModule, "GetUrlCacheEntryBinaryBlob");
   ptr_GetUrlCacheEntryInfoA = (__vartype(ptr_GetUrlCacheEntryInfoA))GetProcAddress(hModule, "GetUrlCacheEntryInfoA");
   ptr_GetUrlCacheEntryInfoExA = (__vartype(ptr_GetUrlCacheEntryInfoExA))GetProcAddress(hModule, "GetUrlCacheEntryInfoExA");
   ptr_GetUrlCacheEntryInfoExW = (__vartype(ptr_GetUrlCacheEntryInfoExW))GetProcAddress(hModule, "GetUrlCacheEntryInfoExW");
   ptr_GetUrlCacheEntryInfoW = (__vartype(ptr_GetUrlCacheEntryInfoW))GetProcAddress(hModule, "GetUrlCacheEntryInfoW");
   ptr_GetUrlCacheGroupAttributeA = (__vartype(ptr_GetUrlCacheGroupAttributeA))GetProcAddress(hModule, "GetUrlCacheGroupAttributeA");
   ptr_GetUrlCacheGroupAttributeW = (__vartype(ptr_GetUrlCacheGroupAttributeW))GetProcAddress(hModule, "GetUrlCacheGroupAttributeW");
   ptr_GetUrlCacheHeaderData = (__vartype(ptr_GetUrlCacheHeaderData))GetProcAddress(hModule, "GetUrlCacheHeaderData");
   ptr_GopherCreateLocatorA = (__vartype(ptr_GopherCreateLocatorA))GetProcAddress(hModule, "GopherCreateLocatorA");
   ptr_GopherCreateLocatorW = (__vartype(ptr_GopherCreateLocatorW))GetProcAddress(hModule, "GopherCreateLocatorW");
   ptr_GopherFindFirstFileA = (__vartype(ptr_GopherFindFirstFileA))GetProcAddress(hModule, "GopherFindFirstFileA");
   ptr_GopherFindFirstFileW = (__vartype(ptr_GopherFindFirstFileW))GetProcAddress(hModule, "GopherFindFirstFileW");
   ptr_GopherGetAttributeA = (__vartype(ptr_GopherGetAttributeA))GetProcAddress(hModule, "GopherGetAttributeA");
   ptr_GopherGetAttributeW = (__vartype(ptr_GopherGetAttributeW))GetProcAddress(hModule, "GopherGetAttributeW");
   ptr_GopherGetLocatorTypeA = (__vartype(ptr_GopherGetLocatorTypeA))GetProcAddress(hModule, "GopherGetLocatorTypeA");
   ptr_GopherGetLocatorTypeW = (__vartype(ptr_GopherGetLocatorTypeW))GetProcAddress(hModule, "GopherGetLocatorTypeW");
   ptr_GopherOpenFileA = (__vartype(ptr_GopherOpenFileA))GetProcAddress(hModule, "GopherOpenFileA");
   ptr_GopherOpenFileW = (__vartype(ptr_GopherOpenFileW))GetProcAddress(hModule, "GopherOpenFileW");
   ptr_HttpAddRequestHeadersA = (__vartype(ptr_HttpAddRequestHeadersA))GetProcAddress(hModule, "HttpAddRequestHeadersA");
   ptr_HttpAddRequestHeadersW = (__vartype(ptr_HttpAddRequestHeadersW))GetProcAddress(hModule, "HttpAddRequestHeadersW");
   ptr_HttpCheckDavCompliance = (__vartype(ptr_HttpCheckDavCompliance))GetProcAddress(hModule, "HttpCheckDavCompliance");
   ptr_HttpCloseDependencyHandle = (__vartype(ptr_HttpCloseDependencyHandle))GetProcAddress(hModule, "HttpCloseDependencyHandle");
   ptr_HttpDuplicateDependencyHandle = (__vartype(ptr_HttpDuplicateDependencyHandle))GetProcAddress(hModule, "HttpDuplicateDependencyHandle");
   ptr_HttpEndRequestA = (__vartype(ptr_HttpEndRequestA))GetProcAddress(hModule, "HttpEndRequestA");
   ptr_HttpEndRequestW = (__vartype(ptr_HttpEndRequestW))GetProcAddress(hModule, "HttpEndRequestW");
   ptr_HttpGetServerCredentials = (__vartype(ptr_HttpGetServerCredentials))GetProcAddress(hModule, "HttpGetServerCredentials");
   ptr_HttpGetTunnelSocket = (__vartype(ptr_HttpGetTunnelSocket))GetProcAddress(hModule, "HttpGetTunnelSocket");
   ptr_HttpIsHostHstsEnabled = (__vartype(ptr_HttpIsHostHstsEnabled))GetProcAddress(hModule, "HttpIsHostHstsEnabled");
   ptr_HttpOpenDependencyHandle = (__vartype(ptr_HttpOpenDependencyHandle))GetProcAddress(hModule, "HttpOpenDependencyHandle");
   ptr_HttpOpenRequestA = (__vartype(ptr_HttpOpenRequestA))GetProcAddress(hModule, "HttpOpenRequestA");
   ptr_HttpOpenRequestW = (__vartype(ptr_HttpOpenRequestW))GetProcAddress(hModule, "HttpOpenRequestW");
   ptr_HttpPushClose = (__vartype(ptr_HttpPushClose))GetProcAddress(hModule, "HttpPushClose");
   ptr_HttpPushEnable = (__vartype(ptr_HttpPushEnable))GetProcAddress(hModule, "HttpPushEnable");
   ptr_HttpPushWait = (__vartype(ptr_HttpPushWait))GetProcAddress(hModule, "HttpPushWait");
   ptr_HttpQueryInfoA = (__vartype(ptr_HttpQueryInfoA))GetProcAddress(hModule, "HttpQueryInfoA");
   ptr_HttpQueryInfoW = (__vartype(ptr_HttpQueryInfoW))GetProcAddress(hModule, "HttpQueryInfoW");
   ptr_HttpSendRequestA = (__vartype(ptr_HttpSendRequestA))GetProcAddress(hModule, "HttpSendRequestA");
   ptr_HttpSendRequestExA = (__vartype(ptr_HttpSendRequestExA))GetProcAddress(hModule, "HttpSendRequestExA");
   ptr_HttpSendRequestExW = (__vartype(ptr_HttpSendRequestExW))GetProcAddress(hModule, "HttpSendRequestExW");
   ptr_HttpSendRequestW = (__vartype(ptr_HttpSendRequestW))GetProcAddress(hModule, "HttpSendRequestW");
   ptr_HttpWebSocketClose = (__vartype(ptr_HttpWebSocketClose))GetProcAddress(hModule, "HttpWebSocketClose");
   ptr_HttpWebSocketCompleteUpgrade = (__vartype(ptr_HttpWebSocketCompleteUpgrade))GetProcAddress(hModule, "HttpWebSocketCompleteUpgrade");
   ptr_HttpWebSocketQueryCloseStatus = (__vartype(ptr_HttpWebSocketQueryCloseStatus))GetProcAddress(hModule, "HttpWebSocketQueryCloseStatus");
   ptr_HttpWebSocketReceive = (__vartype(ptr_HttpWebSocketReceive))GetProcAddress(hModule, "HttpWebSocketReceive");
   ptr_HttpWebSocketSend = (__vartype(ptr_HttpWebSocketSend))GetProcAddress(hModule, "HttpWebSocketSend");
   ptr_HttpWebSocketShutdown = (__vartype(ptr_HttpWebSocketShutdown))GetProcAddress(hModule, "HttpWebSocketShutdown");
   ptr_IncrementUrlCacheHeaderData = (__vartype(ptr_IncrementUrlCacheHeaderData))GetProcAddress(hModule, "IncrementUrlCacheHeaderData");
   ptr_InternetAlgIdToStringA = (__vartype(ptr_InternetAlgIdToStringA))GetProcAddress(hModule, "InternetAlgIdToStringA");
   ptr_InternetAlgIdToStringW = (__vartype(ptr_InternetAlgIdToStringW))GetProcAddress(hModule, "InternetAlgIdToStringW");
   ptr_InternetAttemptConnect = (__vartype(ptr_InternetAttemptConnect))GetProcAddress(hModule, "InternetAttemptConnect");
   ptr_InternetAutodial = (__vartype(ptr_InternetAutodial))GetProcAddress(hModule, "InternetAutodial");
   ptr_InternetAutodialCallback = (__vartype(ptr_InternetAutodialCallback))GetProcAddress(hModule, "InternetAutodialCallback");
   ptr_InternetAutodialHangup = (__vartype(ptr_InternetAutodialHangup))GetProcAddress(hModule, "InternetAutodialHangup");
   ptr_InternetCanonicalizeUrlA = (__vartype(ptr_InternetCanonicalizeUrlA))GetProcAddress(hModule, "InternetCanonicalizeUrlA");
   ptr_InternetCanonicalizeUrlW = (__vartype(ptr_InternetCanonicalizeUrlW))GetProcAddress(hModule, "InternetCanonicalizeUrlW");
   ptr_InternetCheckConnectionA = (__vartype(ptr_InternetCheckConnectionA))GetProcAddress(hModule, "InternetCheckConnectionA");
   ptr_InternetCheckConnectionW = (__vartype(ptr_InternetCheckConnectionW))GetProcAddress(hModule, "InternetCheckConnectionW");
   ptr_InternetClearAllPerSiteCookieDecisions = (__vartype(ptr_InternetClearAllPerSiteCookieDecisions))GetProcAddress(hModule, "InternetClearAllPerSiteCookieDecisions");
   ptr_InternetCloseHandle = (__vartype(ptr_InternetCloseHandle))GetProcAddress(hModule, "InternetCloseHandle");
   ptr_InternetCombineUrlA = (__vartype(ptr_InternetCombineUrlA))GetProcAddress(hModule, "InternetCombineUrlA");
   ptr_InternetCombineUrlW = (__vartype(ptr_InternetCombineUrlW))GetProcAddress(hModule, "InternetCombineUrlW");
   ptr_InternetConfirmZoneCrossing = (__vartype(ptr_InternetConfirmZoneCrossing))GetProcAddress(hModule, "InternetConfirmZoneCrossing");
   ptr_InternetConfirmZoneCrossingA = (__vartype(ptr_InternetConfirmZoneCrossingA))GetProcAddress(hModule, "InternetConfirmZoneCrossingA");
   ptr_InternetConfirmZoneCrossingW = (__vartype(ptr_InternetConfirmZoneCrossingW))GetProcAddress(hModule, "InternetConfirmZoneCrossingW");
   ptr_InternetConnectA = (__vartype(ptr_InternetConnectA))GetProcAddress(hModule, "InternetConnectA");
   ptr_InternetConnectW = (__vartype(ptr_InternetConnectW))GetProcAddress(hModule, "InternetConnectW");
   ptr_InternetCrackUrlA = (__vartype(ptr_InternetCrackUrlA))GetProcAddress(hModule, "InternetCrackUrlA");
   ptr_InternetCrackUrlW = (__vartype(ptr_InternetCrackUrlW))GetProcAddress(hModule, "InternetCrackUrlW");
   ptr_InternetCreateUrlA = (__vartype(ptr_InternetCreateUrlA))GetProcAddress(hModule, "InternetCreateUrlA");
   ptr_InternetCreateUrlW = (__vartype(ptr_InternetCreateUrlW))GetProcAddress(hModule, "InternetCreateUrlW");
   ptr_InternetDial = (__vartype(ptr_InternetDial))GetProcAddress(hModule, "InternetDial");
   ptr_InternetDialA = (__vartype(ptr_InternetDialA))GetProcAddress(hModule, "InternetDialA");
   ptr_InternetDialW = (__vartype(ptr_InternetDialW))GetProcAddress(hModule, "InternetDialW");
   ptr_InternetEnumPerSiteCookieDecisionA = (__vartype(ptr_InternetEnumPerSiteCookieDecisionA))GetProcAddress(hModule, "InternetEnumPerSiteCookieDecisionA");
   ptr_InternetEnumPerSiteCookieDecisionW = (__vartype(ptr_InternetEnumPerSiteCookieDecisionW))GetProcAddress(hModule, "InternetEnumPerSiteCookieDecisionW");
   ptr_InternetErrorDlg = (__vartype(ptr_InternetErrorDlg))GetProcAddress(hModule, "InternetErrorDlg");
   ptr_InternetFindNextFileA = (__vartype(ptr_InternetFindNextFileA))GetProcAddress(hModule, "InternetFindNextFileA");
   ptr_InternetFindNextFileW = (__vartype(ptr_InternetFindNextFileW))GetProcAddress(hModule, "InternetFindNextFileW");
   ptr_InternetFortezzaCommand = (__vartype(ptr_InternetFortezzaCommand))GetProcAddress(hModule, "InternetFortezzaCommand");
   ptr_InternetFreeCookies = (__vartype(ptr_InternetFreeCookies))GetProcAddress(hModule, "InternetFreeCookies");
   ptr_InternetFreeProxyInfoList = (__vartype(ptr_InternetFreeProxyInfoList))GetProcAddress(hModule, "InternetFreeProxyInfoList");
   ptr_InternetGetCertByURL = (__vartype(ptr_InternetGetCertByURL))GetProcAddress(hModule, "InternetGetCertByURL");
   ptr_InternetGetCertByURLA = (__vartype(ptr_InternetGetCertByURLA))GetProcAddress(hModule, "InternetGetCertByURLA");
   ptr_InternetGetConnectedState = (__vartype(ptr_InternetGetConnectedState))GetProcAddress(hModule, "InternetGetConnectedState");
   ptr_InternetGetConnectedStateEx = (__vartype(ptr_InternetGetConnectedStateEx))GetProcAddress(hModule, "InternetGetConnectedStateEx");
   ptr_InternetGetConnectedStateExA = (__vartype(ptr_InternetGetConnectedStateExA))GetProcAddress(hModule, "InternetGetConnectedStateExA");
   ptr_InternetGetConnectedStateExW = (__vartype(ptr_InternetGetConnectedStateExW))GetProcAddress(hModule, "InternetGetConnectedStateExW");
   ptr_InternetGetCookieA = (__vartype(ptr_InternetGetCookieA))GetProcAddress(hModule, "InternetGetCookieA");
   ptr_InternetGetCookieEx2 = (__vartype(ptr_InternetGetCookieEx2))GetProcAddress(hModule, "InternetGetCookieEx2");
   ptr_InternetGetCookieExA = (__vartype(ptr_InternetGetCookieExA))GetProcAddress(hModule, "InternetGetCookieExA");
   ptr_InternetGetCookieExW = (__vartype(ptr_InternetGetCookieExW))GetProcAddress(hModule, "InternetGetCookieExW");
   ptr_InternetGetCookieW = (__vartype(ptr_InternetGetCookieW))GetProcAddress(hModule, "InternetGetCookieW");
   ptr_InternetGetLastResponseInfoA = (__vartype(ptr_InternetGetLastResponseInfoA))GetProcAddress(hModule, "InternetGetLastResponseInfoA");
   ptr_InternetGetLastResponseInfoW = (__vartype(ptr_InternetGetLastResponseInfoW))GetProcAddress(hModule, "InternetGetLastResponseInfoW");
   ptr_InternetGetPerSiteCookieDecisionA = (__vartype(ptr_InternetGetPerSiteCookieDecisionA))GetProcAddress(hModule, "InternetGetPerSiteCookieDecisionA");
   ptr_InternetGetPerSiteCookieDecisionW = (__vartype(ptr_InternetGetPerSiteCookieDecisionW))GetProcAddress(hModule, "InternetGetPerSiteCookieDecisionW");
   ptr_InternetGetProxyForUrl = (__vartype(ptr_InternetGetProxyForUrl))GetProcAddress(hModule, "InternetGetProxyForUrl");
   ptr_InternetGetSecurityInfoByURL = (__vartype(ptr_InternetGetSecurityInfoByURL))GetProcAddress(hModule, "InternetGetSecurityInfoByURL");
   ptr_InternetGetSecurityInfoByURLA = (__vartype(ptr_InternetGetSecurityInfoByURLA))GetProcAddress(hModule, "InternetGetSecurityInfoByURLA");
   ptr_InternetGetSecurityInfoByURLW = (__vartype(ptr_InternetGetSecurityInfoByURLW))GetProcAddress(hModule, "InternetGetSecurityInfoByURLW");
   ptr_InternetGoOnline = (__vartype(ptr_InternetGoOnline))GetProcAddress(hModule, "InternetGoOnline");
   ptr_InternetGoOnlineA = (__vartype(ptr_InternetGoOnlineA))GetProcAddress(hModule, "InternetGoOnlineA");
   ptr_InternetGoOnlineW = (__vartype(ptr_InternetGoOnlineW))GetProcAddress(hModule, "InternetGoOnlineW");
   ptr_InternetHangUp = (__vartype(ptr_InternetHangUp))GetProcAddress(hModule, "InternetHangUp");
   ptr_InternetInitializeAutoProxyDll = (__vartype(ptr_InternetInitializeAutoProxyDll))GetProcAddress(hModule, "InternetInitializeAutoProxyDll");
   ptr_InternetLockRequestFile = (__vartype(ptr_InternetLockRequestFile))GetProcAddress(hModule, "InternetLockRequestFile");
   ptr_InternetOpenA = (__vartype(ptr_InternetOpenA))GetProcAddress(hModule, "InternetOpenA");
   ptr_InternetOpenUrlA = (__vartype(ptr_InternetOpenUrlA))GetProcAddress(hModule, "InternetOpenUrlA");
   ptr_InternetOpenUrlW = (__vartype(ptr_InternetOpenUrlW))GetProcAddress(hModule, "InternetOpenUrlW");
   ptr_InternetOpenW = (__vartype(ptr_InternetOpenW))GetProcAddress(hModule, "InternetOpenW");
   ptr_InternetQueryDataAvailable = (__vartype(ptr_InternetQueryDataAvailable))GetProcAddress(hModule, "InternetQueryDataAvailable");
   ptr_InternetQueryFortezzaStatus = (__vartype(ptr_InternetQueryFortezzaStatus))GetProcAddress(hModule, "InternetQueryFortezzaStatus");
   ptr_InternetQueryOptionA = (__vartype(ptr_InternetQueryOptionA))GetProcAddress(hModule, "InternetQueryOptionA");
   ptr_InternetQueryOptionW = (__vartype(ptr_InternetQueryOptionW))GetProcAddress(hModule, "InternetQueryOptionW");
   ptr_InternetReadFile = (__vartype(ptr_InternetReadFile))GetProcAddress(hModule, "InternetReadFile");
   ptr_InternetReadFileExA = (__vartype(ptr_InternetReadFileExA))GetProcAddress(hModule, "InternetReadFileExA");
   ptr_InternetReadFileExW = (__vartype(ptr_InternetReadFileExW))GetProcAddress(hModule, "InternetReadFileExW");
   ptr_InternetSecurityProtocolToStringA = (__vartype(ptr_InternetSecurityProtocolToStringA))GetProcAddress(hModule, "InternetSecurityProtocolToStringA");
   ptr_InternetSecurityProtocolToStringW = (__vartype(ptr_InternetSecurityProtocolToStringW))GetProcAddress(hModule, "InternetSecurityProtocolToStringW");
   ptr_InternetSetCookieA = (__vartype(ptr_InternetSetCookieA))GetProcAddress(hModule, "InternetSetCookieA");
   ptr_InternetSetCookieEx2 = (__vartype(ptr_InternetSetCookieEx2))GetProcAddress(hModule, "InternetSetCookieEx2");
   ptr_InternetSetCookieExA = (__vartype(ptr_InternetSetCookieExA))GetProcAddress(hModule, "InternetSetCookieExA");
   ptr_InternetSetCookieExW = (__vartype(ptr_InternetSetCookieExW))GetProcAddress(hModule, "InternetSetCookieExW");
   ptr_InternetSetCookieW = (__vartype(ptr_InternetSetCookieW))GetProcAddress(hModule, "InternetSetCookieW");
   ptr_InternetSetDialState = (__vartype(ptr_InternetSetDialState))GetProcAddress(hModule, "InternetSetDialState");
   ptr_InternetSetDialStateA = (__vartype(ptr_InternetSetDialStateA))GetProcAddress(hModule, "InternetSetDialStateA");
   ptr_InternetSetDialStateW = (__vartype(ptr_InternetSetDialStateW))GetProcAddress(hModule, "InternetSetDialStateW");
   ptr_InternetSetFilePointer = (__vartype(ptr_InternetSetFilePointer))GetProcAddress(hModule, "InternetSetFilePointer");
   ptr_InternetSetOptionA = (__vartype(ptr_InternetSetOptionA))GetProcAddress(hModule, "InternetSetOptionA");
   ptr_InternetSetOptionExA = (__vartype(ptr_InternetSetOptionExA))GetProcAddress(hModule, "InternetSetOptionExA");
   ptr_InternetSetOptionExW = (__vartype(ptr_InternetSetOptionExW))GetProcAddress(hModule, "InternetSetOptionExW");
   ptr_InternetSetOptionW = (__vartype(ptr_InternetSetOptionW))GetProcAddress(hModule, "InternetSetOptionW");
   ptr_InternetSetPerSiteCookieDecisionA = (__vartype(ptr_InternetSetPerSiteCookieDecisionA))GetProcAddress(hModule, "InternetSetPerSiteCookieDecisionA");
   ptr_InternetSetPerSiteCookieDecisionW = (__vartype(ptr_InternetSetPerSiteCookieDecisionW))GetProcAddress(hModule, "InternetSetPerSiteCookieDecisionW");
   ptr_InternetSetStatusCallback = (__vartype(ptr_InternetSetStatusCallback))GetProcAddress(hModule, "InternetSetStatusCallback");
   ptr_InternetSetStatusCallbackA = (__vartype(ptr_InternetSetStatusCallbackA))GetProcAddress(hModule, "InternetSetStatusCallbackA");
   ptr_InternetSetStatusCallbackW = (__vartype(ptr_InternetSetStatusCallbackW))GetProcAddress(hModule, "InternetSetStatusCallbackW");
   ptr_InternetShowSecurityInfoByURL = (__vartype(ptr_InternetShowSecurityInfoByURL))GetProcAddress(hModule, "InternetShowSecurityInfoByURL");
   ptr_InternetShowSecurityInfoByURLA = (__vartype(ptr_InternetShowSecurityInfoByURLA))GetProcAddress(hModule, "InternetShowSecurityInfoByURLA");
   ptr_InternetShowSecurityInfoByURLW = (__vartype(ptr_InternetShowSecurityInfoByURLW))GetProcAddress(hModule, "InternetShowSecurityInfoByURLW");
   ptr_InternetTimeFromSystemTime = (__vartype(ptr_InternetTimeFromSystemTime))GetProcAddress(hModule, "InternetTimeFromSystemTime");
   ptr_InternetTimeFromSystemTimeA = (__vartype(ptr_InternetTimeFromSystemTimeA))GetProcAddress(hModule, "InternetTimeFromSystemTimeA");
   ptr_InternetTimeFromSystemTimeW = (__vartype(ptr_InternetTimeFromSystemTimeW))GetProcAddress(hModule, "InternetTimeFromSystemTimeW");
   ptr_InternetTimeToSystemTime = (__vartype(ptr_InternetTimeToSystemTime))GetProcAddress(hModule, "InternetTimeToSystemTime");
   ptr_InternetTimeToSystemTimeA = (__vartype(ptr_InternetTimeToSystemTimeA))GetProcAddress(hModule, "InternetTimeToSystemTimeA");
   ptr_InternetTimeToSystemTimeW = (__vartype(ptr_InternetTimeToSystemTimeW))GetProcAddress(hModule, "InternetTimeToSystemTimeW");
   ptr_InternetUnlockRequestFile = (__vartype(ptr_InternetUnlockRequestFile))GetProcAddress(hModule, "InternetUnlockRequestFile");
   ptr_InternetWriteFile = (__vartype(ptr_InternetWriteFile))GetProcAddress(hModule, "InternetWriteFile");
   ptr_InternetWriteFileExA = (__vartype(ptr_InternetWriteFileExA))GetProcAddress(hModule, "InternetWriteFileExA");
   ptr_InternetWriteFileExW = (__vartype(ptr_InternetWriteFileExW))GetProcAddress(hModule, "InternetWriteFileExW");
   ptr_IsHostInProxyBypassList = (__vartype(ptr_IsHostInProxyBypassList))GetProcAddress(hModule, "IsHostInProxyBypassList");
   ptr_IsUrlCacheEntryExpiredA = (__vartype(ptr_IsUrlCacheEntryExpiredA))GetProcAddress(hModule, "IsUrlCacheEntryExpiredA");
   ptr_IsUrlCacheEntryExpiredW = (__vartype(ptr_IsUrlCacheEntryExpiredW))GetProcAddress(hModule, "IsUrlCacheEntryExpiredW");
   ptr_LoadUrlCacheContent = (__vartype(ptr_LoadUrlCacheContent))GetProcAddress(hModule, "LoadUrlCacheContent");
   ptr_ParseX509EncodedCertificateForListBoxEntry = (__vartype(ptr_ParseX509EncodedCertificateForListBoxEntry))GetProcAddress(hModule, "ParseX509EncodedCertificateForListBoxEntry");
   ptr_PrivacyGetZonePreferenceW = (__vartype(ptr_PrivacyGetZonePreferenceW))GetProcAddress(hModule, "PrivacyGetZonePreferenceW");
   ptr_PrivacySetZonePreferenceW = (__vartype(ptr_PrivacySetZonePreferenceW))GetProcAddress(hModule, "PrivacySetZonePreferenceW");
   ptr_ReadUrlCacheEntryStream = (__vartype(ptr_ReadUrlCacheEntryStream))GetProcAddress(hModule, "ReadUrlCacheEntryStream");
   ptr_ReadUrlCacheEntryStreamEx = (__vartype(ptr_ReadUrlCacheEntryStreamEx))GetProcAddress(hModule, "ReadUrlCacheEntryStreamEx");
   ptr_RegisterUrlCacheNotification = (__vartype(ptr_RegisterUrlCacheNotification))GetProcAddress(hModule, "RegisterUrlCacheNotification");
   ptr_ResumeSuspendedDownload = (__vartype(ptr_ResumeSuspendedDownload))GetProcAddress(hModule, "ResumeSuspendedDownload");
   ptr_RetrieveUrlCacheEntryFileA = (__vartype(ptr_RetrieveUrlCacheEntryFileA))GetProcAddress(hModule, "RetrieveUrlCacheEntryFileA");
   ptr_RetrieveUrlCacheEntryFileW = (__vartype(ptr_RetrieveUrlCacheEntryFileW))GetProcAddress(hModule, "RetrieveUrlCacheEntryFileW");
   ptr_RetrieveUrlCacheEntryStreamA = (__vartype(ptr_RetrieveUrlCacheEntryStreamA))GetProcAddress(hModule, "RetrieveUrlCacheEntryStreamA");
   ptr_RetrieveUrlCacheEntryStreamW = (__vartype(ptr_RetrieveUrlCacheEntryStreamW))GetProcAddress(hModule, "RetrieveUrlCacheEntryStreamW");
   ptr_RunOnceUrlCache = (__vartype(ptr_RunOnceUrlCache))GetProcAddress(hModule, "RunOnceUrlCache");
   ptr_SetUrlCacheConfigInfoA = (__vartype(ptr_SetUrlCacheConfigInfoA))GetProcAddress(hModule, "SetUrlCacheConfigInfoA");
   ptr_SetUrlCacheConfigInfoW = (__vartype(ptr_SetUrlCacheConfigInfoW))GetProcAddress(hModule, "SetUrlCacheConfigInfoW");
   ptr_SetUrlCacheEntryGroup = (__vartype(ptr_SetUrlCacheEntryGroup))GetProcAddress(hModule, "SetUrlCacheEntryGroup");
   ptr_SetUrlCacheEntryGroupA = (__vartype(ptr_SetUrlCacheEntryGroupA))GetProcAddress(hModule, "SetUrlCacheEntryGroupA");
   ptr_SetUrlCacheEntryGroupW = (__vartype(ptr_SetUrlCacheEntryGroupW))GetProcAddress(hModule, "SetUrlCacheEntryGroupW");
   ptr_SetUrlCacheEntryInfoA = (__vartype(ptr_SetUrlCacheEntryInfoA))GetProcAddress(hModule, "SetUrlCacheEntryInfoA");
   ptr_SetUrlCacheEntryInfoW = (__vartype(ptr_SetUrlCacheEntryInfoW))GetProcAddress(hModule, "SetUrlCacheEntryInfoW");
   ptr_SetUrlCacheGroupAttributeA = (__vartype(ptr_SetUrlCacheGroupAttributeA))GetProcAddress(hModule, "SetUrlCacheGroupAttributeA");
   ptr_SetUrlCacheGroupAttributeW = (__vartype(ptr_SetUrlCacheGroupAttributeW))GetProcAddress(hModule, "SetUrlCacheGroupAttributeW");
   ptr_SetUrlCacheHeaderData = (__vartype(ptr_SetUrlCacheHeaderData))GetProcAddress(hModule, "SetUrlCacheHeaderData");
   ptr_ShowCertificate = (__vartype(ptr_ShowCertificate))GetProcAddress(hModule, "ShowCertificate");
   ptr_ShowClientAuthCerts = (__vartype(ptr_ShowClientAuthCerts))GetProcAddress(hModule, "ShowClientAuthCerts");
   ptr_ShowSecurityInfo = (__vartype(ptr_ShowSecurityInfo))GetProcAddress(hModule, "ShowSecurityInfo");
   ptr_ShowX509EncodedCertificate = (__vartype(ptr_ShowX509EncodedCertificate))GetProcAddress(hModule, "ShowX509EncodedCertificate");
   ptr_UnlockUrlCacheEntryFile = (__vartype(ptr_UnlockUrlCacheEntryFile))GetProcAddress(hModule, "UnlockUrlCacheEntryFile");
   ptr_UnlockUrlCacheEntryFileA = (__vartype(ptr_UnlockUrlCacheEntryFileA))GetProcAddress(hModule, "UnlockUrlCacheEntryFileA");
   ptr_UnlockUrlCacheEntryFileW = (__vartype(ptr_UnlockUrlCacheEntryFileW))GetProcAddress(hModule, "UnlockUrlCacheEntryFileW");
   ptr_UnlockUrlCacheEntryStream = (__vartype(ptr_UnlockUrlCacheEntryStream))GetProcAddress(hModule, "UnlockUrlCacheEntryStream");
   ptr_UpdateUrlCacheContentPath = (__vartype(ptr_UpdateUrlCacheContentPath))GetProcAddress(hModule, "UpdateUrlCacheContentPath");
   ptr_UrlCacheCheckEntriesExist = (__vartype(ptr_UrlCacheCheckEntriesExist))GetProcAddress(hModule, "UrlCacheCheckEntriesExist");
   ptr_UrlCacheCloseEntryHandle = (__vartype(ptr_UrlCacheCloseEntryHandle))GetProcAddress(hModule, "UrlCacheCloseEntryHandle");
   ptr_UrlCacheContainerSetEntryMaximumAge = (__vartype(ptr_UrlCacheContainerSetEntryMaximumAge))GetProcAddress(hModule, "UrlCacheContainerSetEntryMaximumAge");
   ptr_UrlCacheCreateContainer = (__vartype(ptr_UrlCacheCreateContainer))GetProcAddress(hModule, "UrlCacheCreateContainer");
   ptr_UrlCacheFindFirstEntry = (__vartype(ptr_UrlCacheFindFirstEntry))GetProcAddress(hModule, "UrlCacheFindFirstEntry");
   ptr_UrlCacheFindNextEntry = (__vartype(ptr_UrlCacheFindNextEntry))GetProcAddress(hModule, "UrlCacheFindNextEntry");
   ptr_UrlCacheFreeEntryInfo = (__vartype(ptr_UrlCacheFreeEntryInfo))GetProcAddress(hModule, "UrlCacheFreeEntryInfo");
   ptr_UrlCacheGetContentPaths = (__vartype(ptr_UrlCacheGetContentPaths))GetProcAddress(hModule, "UrlCacheGetContentPaths");
   ptr_UrlCacheGetEntryInfo = (__vartype(ptr_UrlCacheGetEntryInfo))GetProcAddress(hModule, "UrlCacheGetEntryInfo");
   ptr_UrlCacheGetGlobalLimit = (__vartype(ptr_UrlCacheGetGlobalLimit))GetProcAddress(hModule, "UrlCacheGetGlobalLimit");
   ptr_UrlCacheReadEntryStream = (__vartype(ptr_UrlCacheReadEntryStream))GetProcAddress(hModule, "UrlCacheReadEntryStream");
   ptr_UrlCacheReloadSettings = (__vartype(ptr_UrlCacheReloadSettings))GetProcAddress(hModule, "UrlCacheReloadSettings");
   ptr_UrlCacheRetrieveEntryFile = (__vartype(ptr_UrlCacheRetrieveEntryFile))GetProcAddress(hModule, "UrlCacheRetrieveEntryFile");
   ptr_UrlCacheRetrieveEntryStream = (__vartype(ptr_UrlCacheRetrieveEntryStream))GetProcAddress(hModule, "UrlCacheRetrieveEntryStream");
   ptr_UrlCacheSetGlobalLimit = (__vartype(ptr_UrlCacheSetGlobalLimit))GetProcAddress(hModule, "UrlCacheSetGlobalLimit");
   ptr_UrlCacheUpdateEntryExtraData = (__vartype(ptr_UrlCacheUpdateEntryExtraData))GetProcAddress(hModule, "UrlCacheUpdateEntryExtraData");
   ptr_UrlZonesDetach = (__vartype(ptr_UrlZonesDetach))GetProcAddress(hModule, "UrlZonesDetach");
   ptr__GetFileExtensionFromUrl = (__vartype(ptr__GetFileExtensionFromUrl))GetProcAddress(hModule, "_GetFileExtensionFromUrl");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

