#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_CMP_GetBlockedDriverInfo;
void *ptr_CMP_GetBlockedDriverInfo = NULL;
extern void *ptr_CMP_GetServerSideDeviceInstallFlags;
void *ptr_CMP_GetServerSideDeviceInstallFlags = NULL;
extern void *ptr_CMP_Init_Detection;
void *ptr_CMP_Init_Detection = NULL;
extern void *ptr_CMP_RegisterNotification;
void *ptr_CMP_RegisterNotification = NULL;
extern void *ptr_CMP_Report_LogOn;
void *ptr_CMP_Report_LogOn = NULL;
extern void *ptr_CMP_UnregisterNotification;
void *ptr_CMP_UnregisterNotification = NULL;
extern void *ptr_CMP_WaitNoPendingInstallEvents;
void *ptr_CMP_WaitNoPendingInstallEvents = NULL;
extern void *ptr_CMP_WaitServicesAvailable;
void *ptr_CMP_WaitServicesAvailable = NULL;
extern void *ptr_CM_Add_Driver_PackageW;
void *ptr_CM_Add_Driver_PackageW = NULL;
extern void *ptr_CM_Add_Driver_Package_ExW;
void *ptr_CM_Add_Driver_Package_ExW = NULL;
extern void *ptr_CM_Add_Empty_Log_Conf;
void *ptr_CM_Add_Empty_Log_Conf = NULL;
extern void *ptr_CM_Add_Empty_Log_Conf_Ex;
void *ptr_CM_Add_Empty_Log_Conf_Ex = NULL;
extern void *ptr_CM_Add_IDA;
void *ptr_CM_Add_IDA = NULL;
extern void *ptr_CM_Add_IDW;
void *ptr_CM_Add_IDW = NULL;
extern void *ptr_CM_Add_ID_ExA;
void *ptr_CM_Add_ID_ExA = NULL;
extern void *ptr_CM_Add_ID_ExW;
void *ptr_CM_Add_ID_ExW = NULL;
extern void *ptr_CM_Add_Range;
void *ptr_CM_Add_Range = NULL;
extern void *ptr_CM_Add_Res_Des;
void *ptr_CM_Add_Res_Des = NULL;
extern void *ptr_CM_Add_Res_Des_Ex;
void *ptr_CM_Add_Res_Des_Ex = NULL;
extern void *ptr_CM_Apply_PowerScheme;
void *ptr_CM_Apply_PowerScheme = NULL;
extern void *ptr_CM_Connect_MachineA;
void *ptr_CM_Connect_MachineA = NULL;
extern void *ptr_CM_Connect_MachineW;
void *ptr_CM_Connect_MachineW = NULL;
extern void *ptr_CM_Create_DevNodeA;
void *ptr_CM_Create_DevNodeA = NULL;
extern void *ptr_CM_Create_DevNodeW;
void *ptr_CM_Create_DevNodeW = NULL;
extern void *ptr_CM_Create_DevNode_ExA;
void *ptr_CM_Create_DevNode_ExA = NULL;
extern void *ptr_CM_Create_DevNode_ExW;
void *ptr_CM_Create_DevNode_ExW = NULL;
extern void *ptr_CM_Create_Range_List;
void *ptr_CM_Create_Range_List = NULL;
extern void *ptr_CM_Delete_Class_Key;
void *ptr_CM_Delete_Class_Key = NULL;
extern void *ptr_CM_Delete_Class_Key_Ex;
void *ptr_CM_Delete_Class_Key_Ex = NULL;
extern void *ptr_CM_Delete_DevNode_Key;
void *ptr_CM_Delete_DevNode_Key = NULL;
extern void *ptr_CM_Delete_DevNode_Key_Ex;
void *ptr_CM_Delete_DevNode_Key_Ex = NULL;
extern void *ptr_CM_Delete_Device_Interface_KeyA;
void *ptr_CM_Delete_Device_Interface_KeyA = NULL;
extern void *ptr_CM_Delete_Device_Interface_KeyW;
void *ptr_CM_Delete_Device_Interface_KeyW = NULL;
extern void *ptr_CM_Delete_Device_Interface_Key_ExA;
void *ptr_CM_Delete_Device_Interface_Key_ExA = NULL;
extern void *ptr_CM_Delete_Device_Interface_Key_ExW;
void *ptr_CM_Delete_Device_Interface_Key_ExW = NULL;
extern void *ptr_CM_Delete_Driver_PackageW;
void *ptr_CM_Delete_Driver_PackageW = NULL;
extern void *ptr_CM_Delete_Driver_Package_ExW;
void *ptr_CM_Delete_Driver_Package_ExW = NULL;
extern void *ptr_CM_Delete_PowerScheme;
void *ptr_CM_Delete_PowerScheme = NULL;
extern void *ptr_CM_Delete_Range;
void *ptr_CM_Delete_Range = NULL;
extern void *ptr_CM_Detect_Resource_Conflict;
void *ptr_CM_Detect_Resource_Conflict = NULL;
extern void *ptr_CM_Detect_Resource_Conflict_Ex;
void *ptr_CM_Detect_Resource_Conflict_Ex = NULL;
extern void *ptr_CM_Disable_DevNode;
void *ptr_CM_Disable_DevNode = NULL;
extern void *ptr_CM_Disable_DevNode_Ex;
void *ptr_CM_Disable_DevNode_Ex = NULL;
extern void *ptr_CM_Disconnect_Machine;
void *ptr_CM_Disconnect_Machine = NULL;
extern void *ptr_CM_Dup_Range_List;
void *ptr_CM_Dup_Range_List = NULL;
extern void *ptr_CM_Duplicate_PowerScheme;
void *ptr_CM_Duplicate_PowerScheme = NULL;
extern void *ptr_CM_Enable_DevNode;
void *ptr_CM_Enable_DevNode = NULL;
extern void *ptr_CM_Enable_DevNode_Ex;
void *ptr_CM_Enable_DevNode_Ex = NULL;
extern void *ptr_CM_Enumerate_Classes;
void *ptr_CM_Enumerate_Classes = NULL;
extern void *ptr_CM_Enumerate_Classes_Ex;
void *ptr_CM_Enumerate_Classes_Ex = NULL;
extern void *ptr_CM_Enumerate_EnumeratorsA;
void *ptr_CM_Enumerate_EnumeratorsA = NULL;
extern void *ptr_CM_Enumerate_EnumeratorsW;
void *ptr_CM_Enumerate_EnumeratorsW = NULL;
extern void *ptr_CM_Enumerate_Enumerators_ExA;
void *ptr_CM_Enumerate_Enumerators_ExA = NULL;
extern void *ptr_CM_Enumerate_Enumerators_ExW;
void *ptr_CM_Enumerate_Enumerators_ExW = NULL;
extern void *ptr_CM_Find_Range;
void *ptr_CM_Find_Range = NULL;
extern void *ptr_CM_First_Range;
void *ptr_CM_First_Range = NULL;
extern void *ptr_CM_Free_Log_Conf;
void *ptr_CM_Free_Log_Conf = NULL;
extern void *ptr_CM_Free_Log_Conf_Ex;
void *ptr_CM_Free_Log_Conf_Ex = NULL;
extern void *ptr_CM_Free_Log_Conf_Handle;
void *ptr_CM_Free_Log_Conf_Handle = NULL;
extern void *ptr_CM_Free_Range_List;
void *ptr_CM_Free_Range_List = NULL;
extern void *ptr_CM_Free_Res_Des;
void *ptr_CM_Free_Res_Des = NULL;
extern void *ptr_CM_Free_Res_Des_Ex;
void *ptr_CM_Free_Res_Des_Ex = NULL;
extern void *ptr_CM_Free_Res_Des_Handle;
void *ptr_CM_Free_Res_Des_Handle = NULL;
extern void *ptr_CM_Free_Resource_Conflict_Handle;
void *ptr_CM_Free_Resource_Conflict_Handle = NULL;
extern void *ptr_CM_Get_Child;
void *ptr_CM_Get_Child = NULL;
extern void *ptr_CM_Get_Child_Ex;
void *ptr_CM_Get_Child_Ex = NULL;
extern void *ptr_CM_Get_Class_Key_NameA;
void *ptr_CM_Get_Class_Key_NameA = NULL;
extern void *ptr_CM_Get_Class_Key_NameW;
void *ptr_CM_Get_Class_Key_NameW = NULL;
extern void *ptr_CM_Get_Class_Key_Name_ExA;
void *ptr_CM_Get_Class_Key_Name_ExA = NULL;
extern void *ptr_CM_Get_Class_Key_Name_ExW;
void *ptr_CM_Get_Class_Key_Name_ExW = NULL;
extern void *ptr_CM_Get_Class_NameA;
void *ptr_CM_Get_Class_NameA = NULL;
extern void *ptr_CM_Get_Class_NameW;
void *ptr_CM_Get_Class_NameW = NULL;
extern void *ptr_CM_Get_Class_Name_ExA;
void *ptr_CM_Get_Class_Name_ExA = NULL;
extern void *ptr_CM_Get_Class_Name_ExW;
void *ptr_CM_Get_Class_Name_ExW = NULL;
extern void *ptr_CM_Get_Class_PropertyW;
void *ptr_CM_Get_Class_PropertyW = NULL;
extern void *ptr_CM_Get_Class_Property_ExW;
void *ptr_CM_Get_Class_Property_ExW = NULL;
extern void *ptr_CM_Get_Class_Property_Keys;
void *ptr_CM_Get_Class_Property_Keys = NULL;
extern void *ptr_CM_Get_Class_Property_Keys_Ex;
void *ptr_CM_Get_Class_Property_Keys_Ex = NULL;
extern void *ptr_CM_Get_Class_Registry_PropertyA;
void *ptr_CM_Get_Class_Registry_PropertyA = NULL;
extern void *ptr_CM_Get_Class_Registry_PropertyW;
void *ptr_CM_Get_Class_Registry_PropertyW = NULL;
extern void *ptr_CM_Get_Depth;
void *ptr_CM_Get_Depth = NULL;
extern void *ptr_CM_Get_Depth_Ex;
void *ptr_CM_Get_Depth_Ex = NULL;
extern void *ptr_CM_Get_DevNode_Custom_PropertyA;
void *ptr_CM_Get_DevNode_Custom_PropertyA = NULL;
extern void *ptr_CM_Get_DevNode_Custom_PropertyW;
void *ptr_CM_Get_DevNode_Custom_PropertyW = NULL;
extern void *ptr_CM_Get_DevNode_Custom_Property_ExA;
void *ptr_CM_Get_DevNode_Custom_Property_ExA = NULL;
extern void *ptr_CM_Get_DevNode_Custom_Property_ExW;
void *ptr_CM_Get_DevNode_Custom_Property_ExW = NULL;
extern void *ptr_CM_Get_DevNode_PropertyW;
void *ptr_CM_Get_DevNode_PropertyW = NULL;
extern void *ptr_CM_Get_DevNode_Property_ExW;
void *ptr_CM_Get_DevNode_Property_ExW = NULL;
extern void *ptr_CM_Get_DevNode_Property_Keys;
void *ptr_CM_Get_DevNode_Property_Keys = NULL;
extern void *ptr_CM_Get_DevNode_Property_Keys_Ex;
void *ptr_CM_Get_DevNode_Property_Keys_Ex = NULL;
extern void *ptr_CM_Get_DevNode_Registry_PropertyA;
void *ptr_CM_Get_DevNode_Registry_PropertyA = NULL;
extern void *ptr_CM_Get_DevNode_Registry_PropertyW;
void *ptr_CM_Get_DevNode_Registry_PropertyW = NULL;
extern void *ptr_CM_Get_DevNode_Registry_Property_ExA;
void *ptr_CM_Get_DevNode_Registry_Property_ExA = NULL;
extern void *ptr_CM_Get_DevNode_Registry_Property_ExW;
void *ptr_CM_Get_DevNode_Registry_Property_ExW = NULL;
extern void *ptr_CM_Get_DevNode_Status;
void *ptr_CM_Get_DevNode_Status = NULL;
extern void *ptr_CM_Get_DevNode_Status_Ex;
void *ptr_CM_Get_DevNode_Status_Ex = NULL;
extern void *ptr_CM_Get_Device_IDA;
void *ptr_CM_Get_Device_IDA = NULL;
extern void *ptr_CM_Get_Device_IDW;
void *ptr_CM_Get_Device_IDW = NULL;
extern void *ptr_CM_Get_Device_ID_ExA;
void *ptr_CM_Get_Device_ID_ExA = NULL;
extern void *ptr_CM_Get_Device_ID_ExW;
void *ptr_CM_Get_Device_ID_ExW = NULL;
extern void *ptr_CM_Get_Device_ID_ListA;
void *ptr_CM_Get_Device_ID_ListA = NULL;
extern void *ptr_CM_Get_Device_ID_ListW;
void *ptr_CM_Get_Device_ID_ListW = NULL;
extern void *ptr_CM_Get_Device_ID_List_ExA;
void *ptr_CM_Get_Device_ID_List_ExA = NULL;
extern void *ptr_CM_Get_Device_ID_List_ExW;
void *ptr_CM_Get_Device_ID_List_ExW = NULL;
extern void *ptr_CM_Get_Device_ID_List_SizeA;
void *ptr_CM_Get_Device_ID_List_SizeA = NULL;
extern void *ptr_CM_Get_Device_ID_List_SizeW;
void *ptr_CM_Get_Device_ID_List_SizeW = NULL;
extern void *ptr_CM_Get_Device_ID_List_Size_ExA;
void *ptr_CM_Get_Device_ID_List_Size_ExA = NULL;
extern void *ptr_CM_Get_Device_ID_List_Size_ExW;
void *ptr_CM_Get_Device_ID_List_Size_ExW = NULL;
extern void *ptr_CM_Get_Device_ID_Size;
void *ptr_CM_Get_Device_ID_Size = NULL;
extern void *ptr_CM_Get_Device_ID_Size_Ex;
void *ptr_CM_Get_Device_ID_Size_Ex = NULL;
extern void *ptr_CM_Get_Device_Interface_AliasA;
void *ptr_CM_Get_Device_Interface_AliasA = NULL;
extern void *ptr_CM_Get_Device_Interface_AliasW;
void *ptr_CM_Get_Device_Interface_AliasW = NULL;
extern void *ptr_CM_Get_Device_Interface_Alias_ExA;
void *ptr_CM_Get_Device_Interface_Alias_ExA = NULL;
extern void *ptr_CM_Get_Device_Interface_Alias_ExW;
void *ptr_CM_Get_Device_Interface_Alias_ExW = NULL;
extern void *ptr_CM_Get_Device_Interface_ListA;
void *ptr_CM_Get_Device_Interface_ListA = NULL;
extern void *ptr_CM_Get_Device_Interface_ListW;
void *ptr_CM_Get_Device_Interface_ListW = NULL;
extern void *ptr_CM_Get_Device_Interface_List_ExA;
void *ptr_CM_Get_Device_Interface_List_ExA = NULL;
extern void *ptr_CM_Get_Device_Interface_List_ExW;
void *ptr_CM_Get_Device_Interface_List_ExW = NULL;
extern void *ptr_CM_Get_Device_Interface_List_SizeA;
void *ptr_CM_Get_Device_Interface_List_SizeA = NULL;
extern void *ptr_CM_Get_Device_Interface_List_SizeW;
void *ptr_CM_Get_Device_Interface_List_SizeW = NULL;
extern void *ptr_CM_Get_Device_Interface_List_Size_ExA;
void *ptr_CM_Get_Device_Interface_List_Size_ExA = NULL;
extern void *ptr_CM_Get_Device_Interface_List_Size_ExW;
void *ptr_CM_Get_Device_Interface_List_Size_ExW = NULL;
extern void *ptr_CM_Get_Device_Interface_PropertyW;
void *ptr_CM_Get_Device_Interface_PropertyW = NULL;
extern void *ptr_CM_Get_Device_Interface_Property_ExW;
void *ptr_CM_Get_Device_Interface_Property_ExW = NULL;
extern void *ptr_CM_Get_Device_Interface_Property_KeysW;
void *ptr_CM_Get_Device_Interface_Property_KeysW = NULL;
extern void *ptr_CM_Get_Device_Interface_Property_Keys_ExW;
void *ptr_CM_Get_Device_Interface_Property_Keys_ExW = NULL;
extern void *ptr_CM_Get_First_Log_Conf;
void *ptr_CM_Get_First_Log_Conf = NULL;
extern void *ptr_CM_Get_First_Log_Conf_Ex;
void *ptr_CM_Get_First_Log_Conf_Ex = NULL;
extern void *ptr_CM_Get_Global_State;
void *ptr_CM_Get_Global_State = NULL;
extern void *ptr_CM_Get_Global_State_Ex;
void *ptr_CM_Get_Global_State_Ex = NULL;
extern void *ptr_CM_Get_HW_Prof_FlagsA;
void *ptr_CM_Get_HW_Prof_FlagsA = NULL;
extern void *ptr_CM_Get_HW_Prof_FlagsW;
void *ptr_CM_Get_HW_Prof_FlagsW = NULL;
extern void *ptr_CM_Get_HW_Prof_Flags_ExA;
void *ptr_CM_Get_HW_Prof_Flags_ExA = NULL;
extern void *ptr_CM_Get_HW_Prof_Flags_ExW;
void *ptr_CM_Get_HW_Prof_Flags_ExW = NULL;
extern void *ptr_CM_Get_Hardware_Profile_InfoA;
void *ptr_CM_Get_Hardware_Profile_InfoA = NULL;
extern void *ptr_CM_Get_Hardware_Profile_InfoW;
void *ptr_CM_Get_Hardware_Profile_InfoW = NULL;
extern void *ptr_CM_Get_Hardware_Profile_Info_ExA;
void *ptr_CM_Get_Hardware_Profile_Info_ExA = NULL;
extern void *ptr_CM_Get_Hardware_Profile_Info_ExW;
void *ptr_CM_Get_Hardware_Profile_Info_ExW = NULL;
extern void *ptr_CM_Get_Log_Conf_Priority;
void *ptr_CM_Get_Log_Conf_Priority = NULL;
extern void *ptr_CM_Get_Log_Conf_Priority_Ex;
void *ptr_CM_Get_Log_Conf_Priority_Ex = NULL;
extern void *ptr_CM_Get_Next_Log_Conf;
void *ptr_CM_Get_Next_Log_Conf = NULL;
extern void *ptr_CM_Get_Next_Log_Conf_Ex;
void *ptr_CM_Get_Next_Log_Conf_Ex = NULL;
extern void *ptr_CM_Get_Next_Res_Des;
void *ptr_CM_Get_Next_Res_Des = NULL;
extern void *ptr_CM_Get_Next_Res_Des_Ex;
void *ptr_CM_Get_Next_Res_Des_Ex = NULL;
extern void *ptr_CM_Get_Parent;
void *ptr_CM_Get_Parent = NULL;
extern void *ptr_CM_Get_Parent_Ex;
void *ptr_CM_Get_Parent_Ex = NULL;
extern void *ptr_CM_Get_Res_Des_Data;
void *ptr_CM_Get_Res_Des_Data = NULL;
extern void *ptr_CM_Get_Res_Des_Data_Ex;
void *ptr_CM_Get_Res_Des_Data_Ex = NULL;
extern void *ptr_CM_Get_Res_Des_Data_Size;
void *ptr_CM_Get_Res_Des_Data_Size = NULL;
extern void *ptr_CM_Get_Res_Des_Data_Size_Ex;
void *ptr_CM_Get_Res_Des_Data_Size_Ex = NULL;
extern void *ptr_CM_Get_Resource_Conflict_Count;
void *ptr_CM_Get_Resource_Conflict_Count = NULL;
extern void *ptr_CM_Get_Resource_Conflict_DetailsA;
void *ptr_CM_Get_Resource_Conflict_DetailsA = NULL;
extern void *ptr_CM_Get_Resource_Conflict_DetailsW;
void *ptr_CM_Get_Resource_Conflict_DetailsW = NULL;
extern void *ptr_CM_Get_Sibling;
void *ptr_CM_Get_Sibling = NULL;
extern void *ptr_CM_Get_Sibling_Ex;
void *ptr_CM_Get_Sibling_Ex = NULL;
extern void *ptr_CM_Get_Version;
void *ptr_CM_Get_Version = NULL;
extern void *ptr_CM_Get_Version_Ex;
void *ptr_CM_Get_Version_Ex = NULL;
extern void *ptr_CM_Import_PowerScheme;
void *ptr_CM_Import_PowerScheme = NULL;
extern void *ptr_CM_Install_DevNodeW;
void *ptr_CM_Install_DevNodeW = NULL;
extern void *ptr_CM_Install_DevNode_ExW;
void *ptr_CM_Install_DevNode_ExW = NULL;
extern void *ptr_CM_Intersect_Range_List;
void *ptr_CM_Intersect_Range_List = NULL;
extern void *ptr_CM_Invert_Range_List;
void *ptr_CM_Invert_Range_List = NULL;
extern void *ptr_CM_Is_Dock_Station_Present;
void *ptr_CM_Is_Dock_Station_Present = NULL;
extern void *ptr_CM_Is_Dock_Station_Present_Ex;
void *ptr_CM_Is_Dock_Station_Present_Ex = NULL;
extern void *ptr_CM_Is_Version_Available;
void *ptr_CM_Is_Version_Available = NULL;
extern void *ptr_CM_Is_Version_Available_Ex;
void *ptr_CM_Is_Version_Available_Ex = NULL;
extern void *ptr_CM_Locate_DevNodeA;
void *ptr_CM_Locate_DevNodeA = NULL;
extern void *ptr_CM_Locate_DevNodeW;
void *ptr_CM_Locate_DevNodeW = NULL;
extern void *ptr_CM_Locate_DevNode_ExA;
void *ptr_CM_Locate_DevNode_ExA = NULL;
extern void *ptr_CM_Locate_DevNode_ExW;
void *ptr_CM_Locate_DevNode_ExW = NULL;
extern void *ptr_CM_MapCrToSpErr;
void *ptr_CM_MapCrToSpErr = NULL;
extern void *ptr_CM_MapCrToWin32Err;
void *ptr_CM_MapCrToWin32Err = NULL;
extern void *ptr_CM_Merge_Range_List;
void *ptr_CM_Merge_Range_List = NULL;
extern void *ptr_CM_Modify_Res_Des;
void *ptr_CM_Modify_Res_Des = NULL;
extern void *ptr_CM_Modify_Res_Des_Ex;
void *ptr_CM_Modify_Res_Des_Ex = NULL;
extern void *ptr_CM_Move_DevNode;
void *ptr_CM_Move_DevNode = NULL;
extern void *ptr_CM_Move_DevNode_Ex;
void *ptr_CM_Move_DevNode_Ex = NULL;
extern void *ptr_CM_Next_Range;
void *ptr_CM_Next_Range = NULL;
extern void *ptr_CM_Open_Class_KeyA;
void *ptr_CM_Open_Class_KeyA = NULL;
extern void *ptr_CM_Open_Class_KeyW;
void *ptr_CM_Open_Class_KeyW = NULL;
extern void *ptr_CM_Open_Class_Key_ExA;
void *ptr_CM_Open_Class_Key_ExA = NULL;
extern void *ptr_CM_Open_Class_Key_ExW;
void *ptr_CM_Open_Class_Key_ExW = NULL;
extern void *ptr_CM_Open_DevNode_Key;
void *ptr_CM_Open_DevNode_Key = NULL;
extern void *ptr_CM_Open_DevNode_Key_Ex;
void *ptr_CM_Open_DevNode_Key_Ex = NULL;
extern void *ptr_CM_Open_Device_Interface_KeyA;
void *ptr_CM_Open_Device_Interface_KeyA = NULL;
extern void *ptr_CM_Open_Device_Interface_KeyW;
void *ptr_CM_Open_Device_Interface_KeyW = NULL;
extern void *ptr_CM_Open_Device_Interface_Key_ExA;
void *ptr_CM_Open_Device_Interface_Key_ExA = NULL;
extern void *ptr_CM_Open_Device_Interface_Key_ExW;
void *ptr_CM_Open_Device_Interface_Key_ExW = NULL;
extern void *ptr_CM_Query_And_Remove_SubTreeA;
void *ptr_CM_Query_And_Remove_SubTreeA = NULL;
extern void *ptr_CM_Query_And_Remove_SubTreeW;
void *ptr_CM_Query_And_Remove_SubTreeW = NULL;
extern void *ptr_CM_Query_And_Remove_SubTree_ExA;
void *ptr_CM_Query_And_Remove_SubTree_ExA = NULL;
extern void *ptr_CM_Query_And_Remove_SubTree_ExW;
void *ptr_CM_Query_And_Remove_SubTree_ExW = NULL;
extern void *ptr_CM_Query_Arbitrator_Free_Data;
void *ptr_CM_Query_Arbitrator_Free_Data = NULL;
extern void *ptr_CM_Query_Arbitrator_Free_Data_Ex;
void *ptr_CM_Query_Arbitrator_Free_Data_Ex = NULL;
extern void *ptr_CM_Query_Arbitrator_Free_Size;
void *ptr_CM_Query_Arbitrator_Free_Size = NULL;
extern void *ptr_CM_Query_Arbitrator_Free_Size_Ex;
void *ptr_CM_Query_Arbitrator_Free_Size_Ex = NULL;
extern void *ptr_CM_Query_Remove_SubTree;
void *ptr_CM_Query_Remove_SubTree = NULL;
extern void *ptr_CM_Query_Remove_SubTree_Ex;
void *ptr_CM_Query_Remove_SubTree_Ex = NULL;
extern void *ptr_CM_Query_Resource_Conflict_List;
void *ptr_CM_Query_Resource_Conflict_List = NULL;
extern void *ptr_CM_Reenumerate_DevNode;
void *ptr_CM_Reenumerate_DevNode = NULL;
extern void *ptr_CM_Reenumerate_DevNode_Ex;
void *ptr_CM_Reenumerate_DevNode_Ex = NULL;
extern void *ptr_CM_Register_Device_Driver;
void *ptr_CM_Register_Device_Driver = NULL;
extern void *ptr_CM_Register_Device_Driver_Ex;
void *ptr_CM_Register_Device_Driver_Ex = NULL;
extern void *ptr_CM_Register_Device_InterfaceA;
void *ptr_CM_Register_Device_InterfaceA = NULL;
extern void *ptr_CM_Register_Device_InterfaceW;
void *ptr_CM_Register_Device_InterfaceW = NULL;
extern void *ptr_CM_Register_Device_Interface_ExA;
void *ptr_CM_Register_Device_Interface_ExA = NULL;
extern void *ptr_CM_Register_Device_Interface_ExW;
void *ptr_CM_Register_Device_Interface_ExW = NULL;
extern void *ptr_CM_Remove_SubTree;
void *ptr_CM_Remove_SubTree = NULL;
extern void *ptr_CM_Remove_SubTree_Ex;
void *ptr_CM_Remove_SubTree_Ex = NULL;
extern void *ptr_CM_Request_Device_EjectA;
void *ptr_CM_Request_Device_EjectA = NULL;
extern void *ptr_CM_Request_Device_EjectW;
void *ptr_CM_Request_Device_EjectW = NULL;
extern void *ptr_CM_Request_Device_Eject_ExA;
void *ptr_CM_Request_Device_Eject_ExA = NULL;
extern void *ptr_CM_Request_Device_Eject_ExW;
void *ptr_CM_Request_Device_Eject_ExW = NULL;
extern void *ptr_CM_Request_Eject_PC;
void *ptr_CM_Request_Eject_PC = NULL;
extern void *ptr_CM_Request_Eject_PC_Ex;
void *ptr_CM_Request_Eject_PC_Ex = NULL;
extern void *ptr_CM_RestoreAll_DefaultPowerSchemes;
void *ptr_CM_RestoreAll_DefaultPowerSchemes = NULL;
extern void *ptr_CM_Restore_DefaultPowerScheme;
void *ptr_CM_Restore_DefaultPowerScheme = NULL;
extern void *ptr_CM_Run_Detection;
void *ptr_CM_Run_Detection = NULL;
extern void *ptr_CM_Run_Detection_Ex;
void *ptr_CM_Run_Detection_Ex = NULL;
extern void *ptr_CM_Set_ActiveScheme;
void *ptr_CM_Set_ActiveScheme = NULL;
extern void *ptr_CM_Set_Class_PropertyW;
void *ptr_CM_Set_Class_PropertyW = NULL;
extern void *ptr_CM_Set_Class_Property_ExW;
void *ptr_CM_Set_Class_Property_ExW = NULL;
extern void *ptr_CM_Set_Class_Registry_PropertyA;
void *ptr_CM_Set_Class_Registry_PropertyA = NULL;
extern void *ptr_CM_Set_Class_Registry_PropertyW;
void *ptr_CM_Set_Class_Registry_PropertyW = NULL;
extern void *ptr_CM_Set_DevNode_Problem;
void *ptr_CM_Set_DevNode_Problem = NULL;
extern void *ptr_CM_Set_DevNode_Problem_Ex;
void *ptr_CM_Set_DevNode_Problem_Ex = NULL;
extern void *ptr_CM_Set_DevNode_PropertyW;
void *ptr_CM_Set_DevNode_PropertyW = NULL;
extern void *ptr_CM_Set_DevNode_Property_ExW;
void *ptr_CM_Set_DevNode_Property_ExW = NULL;
extern void *ptr_CM_Set_DevNode_Registry_PropertyA;
void *ptr_CM_Set_DevNode_Registry_PropertyA = NULL;
extern void *ptr_CM_Set_DevNode_Registry_PropertyW;
void *ptr_CM_Set_DevNode_Registry_PropertyW = NULL;
extern void *ptr_CM_Set_DevNode_Registry_Property_ExA;
void *ptr_CM_Set_DevNode_Registry_Property_ExA = NULL;
extern void *ptr_CM_Set_DevNode_Registry_Property_ExW;
void *ptr_CM_Set_DevNode_Registry_Property_ExW = NULL;
extern void *ptr_CM_Set_Device_Interface_PropertyW;
void *ptr_CM_Set_Device_Interface_PropertyW = NULL;
extern void *ptr_CM_Set_Device_Interface_Property_ExW;
void *ptr_CM_Set_Device_Interface_Property_ExW = NULL;
extern void *ptr_CM_Set_HW_Prof;
void *ptr_CM_Set_HW_Prof = NULL;
extern void *ptr_CM_Set_HW_Prof_Ex;
void *ptr_CM_Set_HW_Prof_Ex = NULL;
extern void *ptr_CM_Set_HW_Prof_FlagsA;
void *ptr_CM_Set_HW_Prof_FlagsA = NULL;
extern void *ptr_CM_Set_HW_Prof_FlagsW;
void *ptr_CM_Set_HW_Prof_FlagsW = NULL;
extern void *ptr_CM_Set_HW_Prof_Flags_ExA;
void *ptr_CM_Set_HW_Prof_Flags_ExA = NULL;
extern void *ptr_CM_Set_HW_Prof_Flags_ExW;
void *ptr_CM_Set_HW_Prof_Flags_ExW = NULL;
extern void *ptr_CM_Setup_DevNode;
void *ptr_CM_Setup_DevNode = NULL;
extern void *ptr_CM_Setup_DevNode_Ex;
void *ptr_CM_Setup_DevNode_Ex = NULL;
extern void *ptr_CM_Test_Range_Available;
void *ptr_CM_Test_Range_Available = NULL;
extern void *ptr_CM_Uninstall_DevNode;
void *ptr_CM_Uninstall_DevNode = NULL;
extern void *ptr_CM_Uninstall_DevNode_Ex;
void *ptr_CM_Uninstall_DevNode_Ex = NULL;
extern void *ptr_CM_Unregister_Device_InterfaceA;
void *ptr_CM_Unregister_Device_InterfaceA = NULL;
extern void *ptr_CM_Unregister_Device_InterfaceW;
void *ptr_CM_Unregister_Device_InterfaceW = NULL;
extern void *ptr_CM_Unregister_Device_Interface_ExA;
void *ptr_CM_Unregister_Device_Interface_ExA = NULL;
extern void *ptr_CM_Unregister_Device_Interface_ExW;
void *ptr_CM_Unregister_Device_Interface_ExW = NULL;
extern void *ptr_CM_Write_UserPowerKey;
void *ptr_CM_Write_UserPowerKey = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\cfgmgr32.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_CMP_GetBlockedDriverInfo = (__vartype(ptr_CMP_GetBlockedDriverInfo))GetProcAddress(hModule, "CMP_GetBlockedDriverInfo");
   ptr_CMP_GetServerSideDeviceInstallFlags = (__vartype(ptr_CMP_GetServerSideDeviceInstallFlags))GetProcAddress(hModule, "CMP_GetServerSideDeviceInstallFlags");
   ptr_CMP_Init_Detection = (__vartype(ptr_CMP_Init_Detection))GetProcAddress(hModule, "CMP_Init_Detection");
   ptr_CMP_RegisterNotification = (__vartype(ptr_CMP_RegisterNotification))GetProcAddress(hModule, "CMP_RegisterNotification");
   ptr_CMP_Report_LogOn = (__vartype(ptr_CMP_Report_LogOn))GetProcAddress(hModule, "CMP_Report_LogOn");
   ptr_CMP_UnregisterNotification = (__vartype(ptr_CMP_UnregisterNotification))GetProcAddress(hModule, "CMP_UnregisterNotification");
   ptr_CMP_WaitNoPendingInstallEvents = (__vartype(ptr_CMP_WaitNoPendingInstallEvents))GetProcAddress(hModule, "CMP_WaitNoPendingInstallEvents");
   ptr_CMP_WaitServicesAvailable = (__vartype(ptr_CMP_WaitServicesAvailable))GetProcAddress(hModule, "CMP_WaitServicesAvailable");
   ptr_CM_Add_Driver_PackageW = (__vartype(ptr_CM_Add_Driver_PackageW))GetProcAddress(hModule, "CM_Add_Driver_PackageW");
   ptr_CM_Add_Driver_Package_ExW = (__vartype(ptr_CM_Add_Driver_Package_ExW))GetProcAddress(hModule, "CM_Add_Driver_Package_ExW");
   ptr_CM_Add_Empty_Log_Conf = (__vartype(ptr_CM_Add_Empty_Log_Conf))GetProcAddress(hModule, "CM_Add_Empty_Log_Conf");
   ptr_CM_Add_Empty_Log_Conf_Ex = (__vartype(ptr_CM_Add_Empty_Log_Conf_Ex))GetProcAddress(hModule, "CM_Add_Empty_Log_Conf_Ex");
   ptr_CM_Add_IDA = (__vartype(ptr_CM_Add_IDA))GetProcAddress(hModule, "CM_Add_IDA");
   ptr_CM_Add_IDW = (__vartype(ptr_CM_Add_IDW))GetProcAddress(hModule, "CM_Add_IDW");
   ptr_CM_Add_ID_ExA = (__vartype(ptr_CM_Add_ID_ExA))GetProcAddress(hModule, "CM_Add_ID_ExA");
   ptr_CM_Add_ID_ExW = (__vartype(ptr_CM_Add_ID_ExW))GetProcAddress(hModule, "CM_Add_ID_ExW");
   ptr_CM_Add_Range = (__vartype(ptr_CM_Add_Range))GetProcAddress(hModule, "CM_Add_Range");
   ptr_CM_Add_Res_Des = (__vartype(ptr_CM_Add_Res_Des))GetProcAddress(hModule, "CM_Add_Res_Des");
   ptr_CM_Add_Res_Des_Ex = (__vartype(ptr_CM_Add_Res_Des_Ex))GetProcAddress(hModule, "CM_Add_Res_Des_Ex");
   ptr_CM_Apply_PowerScheme = (__vartype(ptr_CM_Apply_PowerScheme))GetProcAddress(hModule, "CM_Apply_PowerScheme");
   ptr_CM_Connect_MachineA = (__vartype(ptr_CM_Connect_MachineA))GetProcAddress(hModule, "CM_Connect_MachineA");
   ptr_CM_Connect_MachineW = (__vartype(ptr_CM_Connect_MachineW))GetProcAddress(hModule, "CM_Connect_MachineW");
   ptr_CM_Create_DevNodeA = (__vartype(ptr_CM_Create_DevNodeA))GetProcAddress(hModule, "CM_Create_DevNodeA");
   ptr_CM_Create_DevNodeW = (__vartype(ptr_CM_Create_DevNodeW))GetProcAddress(hModule, "CM_Create_DevNodeW");
   ptr_CM_Create_DevNode_ExA = (__vartype(ptr_CM_Create_DevNode_ExA))GetProcAddress(hModule, "CM_Create_DevNode_ExA");
   ptr_CM_Create_DevNode_ExW = (__vartype(ptr_CM_Create_DevNode_ExW))GetProcAddress(hModule, "CM_Create_DevNode_ExW");
   ptr_CM_Create_Range_List = (__vartype(ptr_CM_Create_Range_List))GetProcAddress(hModule, "CM_Create_Range_List");
   ptr_CM_Delete_Class_Key = (__vartype(ptr_CM_Delete_Class_Key))GetProcAddress(hModule, "CM_Delete_Class_Key");
   ptr_CM_Delete_Class_Key_Ex = (__vartype(ptr_CM_Delete_Class_Key_Ex))GetProcAddress(hModule, "CM_Delete_Class_Key_Ex");
   ptr_CM_Delete_DevNode_Key = (__vartype(ptr_CM_Delete_DevNode_Key))GetProcAddress(hModule, "CM_Delete_DevNode_Key");
   ptr_CM_Delete_DevNode_Key_Ex = (__vartype(ptr_CM_Delete_DevNode_Key_Ex))GetProcAddress(hModule, "CM_Delete_DevNode_Key_Ex");
   ptr_CM_Delete_Device_Interface_KeyA = (__vartype(ptr_CM_Delete_Device_Interface_KeyA))GetProcAddress(hModule, "CM_Delete_Device_Interface_KeyA");
   ptr_CM_Delete_Device_Interface_KeyW = (__vartype(ptr_CM_Delete_Device_Interface_KeyW))GetProcAddress(hModule, "CM_Delete_Device_Interface_KeyW");
   ptr_CM_Delete_Device_Interface_Key_ExA = (__vartype(ptr_CM_Delete_Device_Interface_Key_ExA))GetProcAddress(hModule, "CM_Delete_Device_Interface_Key_ExA");
   ptr_CM_Delete_Device_Interface_Key_ExW = (__vartype(ptr_CM_Delete_Device_Interface_Key_ExW))GetProcAddress(hModule, "CM_Delete_Device_Interface_Key_ExW");
   ptr_CM_Delete_Driver_PackageW = (__vartype(ptr_CM_Delete_Driver_PackageW))GetProcAddress(hModule, "CM_Delete_Driver_PackageW");
   ptr_CM_Delete_Driver_Package_ExW = (__vartype(ptr_CM_Delete_Driver_Package_ExW))GetProcAddress(hModule, "CM_Delete_Driver_Package_ExW");
   ptr_CM_Delete_PowerScheme = (__vartype(ptr_CM_Delete_PowerScheme))GetProcAddress(hModule, "CM_Delete_PowerScheme");
   ptr_CM_Delete_Range = (__vartype(ptr_CM_Delete_Range))GetProcAddress(hModule, "CM_Delete_Range");
   ptr_CM_Detect_Resource_Conflict = (__vartype(ptr_CM_Detect_Resource_Conflict))GetProcAddress(hModule, "CM_Detect_Resource_Conflict");
   ptr_CM_Detect_Resource_Conflict_Ex = (__vartype(ptr_CM_Detect_Resource_Conflict_Ex))GetProcAddress(hModule, "CM_Detect_Resource_Conflict_Ex");
   ptr_CM_Disable_DevNode = (__vartype(ptr_CM_Disable_DevNode))GetProcAddress(hModule, "CM_Disable_DevNode");
   ptr_CM_Disable_DevNode_Ex = (__vartype(ptr_CM_Disable_DevNode_Ex))GetProcAddress(hModule, "CM_Disable_DevNode_Ex");
   ptr_CM_Disconnect_Machine = (__vartype(ptr_CM_Disconnect_Machine))GetProcAddress(hModule, "CM_Disconnect_Machine");
   ptr_CM_Dup_Range_List = (__vartype(ptr_CM_Dup_Range_List))GetProcAddress(hModule, "CM_Dup_Range_List");
   ptr_CM_Duplicate_PowerScheme = (__vartype(ptr_CM_Duplicate_PowerScheme))GetProcAddress(hModule, "CM_Duplicate_PowerScheme");
   ptr_CM_Enable_DevNode = (__vartype(ptr_CM_Enable_DevNode))GetProcAddress(hModule, "CM_Enable_DevNode");
   ptr_CM_Enable_DevNode_Ex = (__vartype(ptr_CM_Enable_DevNode_Ex))GetProcAddress(hModule, "CM_Enable_DevNode_Ex");
   ptr_CM_Enumerate_Classes = (__vartype(ptr_CM_Enumerate_Classes))GetProcAddress(hModule, "CM_Enumerate_Classes");
   ptr_CM_Enumerate_Classes_Ex = (__vartype(ptr_CM_Enumerate_Classes_Ex))GetProcAddress(hModule, "CM_Enumerate_Classes_Ex");
   ptr_CM_Enumerate_EnumeratorsA = (__vartype(ptr_CM_Enumerate_EnumeratorsA))GetProcAddress(hModule, "CM_Enumerate_EnumeratorsA");
   ptr_CM_Enumerate_EnumeratorsW = (__vartype(ptr_CM_Enumerate_EnumeratorsW))GetProcAddress(hModule, "CM_Enumerate_EnumeratorsW");
   ptr_CM_Enumerate_Enumerators_ExA = (__vartype(ptr_CM_Enumerate_Enumerators_ExA))GetProcAddress(hModule, "CM_Enumerate_Enumerators_ExA");
   ptr_CM_Enumerate_Enumerators_ExW = (__vartype(ptr_CM_Enumerate_Enumerators_ExW))GetProcAddress(hModule, "CM_Enumerate_Enumerators_ExW");
   ptr_CM_Find_Range = (__vartype(ptr_CM_Find_Range))GetProcAddress(hModule, "CM_Find_Range");
   ptr_CM_First_Range = (__vartype(ptr_CM_First_Range))GetProcAddress(hModule, "CM_First_Range");
   ptr_CM_Free_Log_Conf = (__vartype(ptr_CM_Free_Log_Conf))GetProcAddress(hModule, "CM_Free_Log_Conf");
   ptr_CM_Free_Log_Conf_Ex = (__vartype(ptr_CM_Free_Log_Conf_Ex))GetProcAddress(hModule, "CM_Free_Log_Conf_Ex");
   ptr_CM_Free_Log_Conf_Handle = (__vartype(ptr_CM_Free_Log_Conf_Handle))GetProcAddress(hModule, "CM_Free_Log_Conf_Handle");
   ptr_CM_Free_Range_List = (__vartype(ptr_CM_Free_Range_List))GetProcAddress(hModule, "CM_Free_Range_List");
   ptr_CM_Free_Res_Des = (__vartype(ptr_CM_Free_Res_Des))GetProcAddress(hModule, "CM_Free_Res_Des");
   ptr_CM_Free_Res_Des_Ex = (__vartype(ptr_CM_Free_Res_Des_Ex))GetProcAddress(hModule, "CM_Free_Res_Des_Ex");
   ptr_CM_Free_Res_Des_Handle = (__vartype(ptr_CM_Free_Res_Des_Handle))GetProcAddress(hModule, "CM_Free_Res_Des_Handle");
   ptr_CM_Free_Resource_Conflict_Handle = (__vartype(ptr_CM_Free_Resource_Conflict_Handle))GetProcAddress(hModule, "CM_Free_Resource_Conflict_Handle");
   ptr_CM_Get_Child = (__vartype(ptr_CM_Get_Child))GetProcAddress(hModule, "CM_Get_Child");
   ptr_CM_Get_Child_Ex = (__vartype(ptr_CM_Get_Child_Ex))GetProcAddress(hModule, "CM_Get_Child_Ex");
   ptr_CM_Get_Class_Key_NameA = (__vartype(ptr_CM_Get_Class_Key_NameA))GetProcAddress(hModule, "CM_Get_Class_Key_NameA");
   ptr_CM_Get_Class_Key_NameW = (__vartype(ptr_CM_Get_Class_Key_NameW))GetProcAddress(hModule, "CM_Get_Class_Key_NameW");
   ptr_CM_Get_Class_Key_Name_ExA = (__vartype(ptr_CM_Get_Class_Key_Name_ExA))GetProcAddress(hModule, "CM_Get_Class_Key_Name_ExA");
   ptr_CM_Get_Class_Key_Name_ExW = (__vartype(ptr_CM_Get_Class_Key_Name_ExW))GetProcAddress(hModule, "CM_Get_Class_Key_Name_ExW");
   ptr_CM_Get_Class_NameA = (__vartype(ptr_CM_Get_Class_NameA))GetProcAddress(hModule, "CM_Get_Class_NameA");
   ptr_CM_Get_Class_NameW = (__vartype(ptr_CM_Get_Class_NameW))GetProcAddress(hModule, "CM_Get_Class_NameW");
   ptr_CM_Get_Class_Name_ExA = (__vartype(ptr_CM_Get_Class_Name_ExA))GetProcAddress(hModule, "CM_Get_Class_Name_ExA");
   ptr_CM_Get_Class_Name_ExW = (__vartype(ptr_CM_Get_Class_Name_ExW))GetProcAddress(hModule, "CM_Get_Class_Name_ExW");
   ptr_CM_Get_Class_PropertyW = (__vartype(ptr_CM_Get_Class_PropertyW))GetProcAddress(hModule, "CM_Get_Class_PropertyW");
   ptr_CM_Get_Class_Property_ExW = (__vartype(ptr_CM_Get_Class_Property_ExW))GetProcAddress(hModule, "CM_Get_Class_Property_ExW");
   ptr_CM_Get_Class_Property_Keys = (__vartype(ptr_CM_Get_Class_Property_Keys))GetProcAddress(hModule, "CM_Get_Class_Property_Keys");
   ptr_CM_Get_Class_Property_Keys_Ex = (__vartype(ptr_CM_Get_Class_Property_Keys_Ex))GetProcAddress(hModule, "CM_Get_Class_Property_Keys_Ex");
   ptr_CM_Get_Class_Registry_PropertyA = (__vartype(ptr_CM_Get_Class_Registry_PropertyA))GetProcAddress(hModule, "CM_Get_Class_Registry_PropertyA");
   ptr_CM_Get_Class_Registry_PropertyW = (__vartype(ptr_CM_Get_Class_Registry_PropertyW))GetProcAddress(hModule, "CM_Get_Class_Registry_PropertyW");
   ptr_CM_Get_Depth = (__vartype(ptr_CM_Get_Depth))GetProcAddress(hModule, "CM_Get_Depth");
   ptr_CM_Get_Depth_Ex = (__vartype(ptr_CM_Get_Depth_Ex))GetProcAddress(hModule, "CM_Get_Depth_Ex");
   ptr_CM_Get_DevNode_Custom_PropertyA = (__vartype(ptr_CM_Get_DevNode_Custom_PropertyA))GetProcAddress(hModule, "CM_Get_DevNode_Custom_PropertyA");
   ptr_CM_Get_DevNode_Custom_PropertyW = (__vartype(ptr_CM_Get_DevNode_Custom_PropertyW))GetProcAddress(hModule, "CM_Get_DevNode_Custom_PropertyW");
   ptr_CM_Get_DevNode_Custom_Property_ExA = (__vartype(ptr_CM_Get_DevNode_Custom_Property_ExA))GetProcAddress(hModule, "CM_Get_DevNode_Custom_Property_ExA");
   ptr_CM_Get_DevNode_Custom_Property_ExW = (__vartype(ptr_CM_Get_DevNode_Custom_Property_ExW))GetProcAddress(hModule, "CM_Get_DevNode_Custom_Property_ExW");
   ptr_CM_Get_DevNode_PropertyW = (__vartype(ptr_CM_Get_DevNode_PropertyW))GetProcAddress(hModule, "CM_Get_DevNode_PropertyW");
   ptr_CM_Get_DevNode_Property_ExW = (__vartype(ptr_CM_Get_DevNode_Property_ExW))GetProcAddress(hModule, "CM_Get_DevNode_Property_ExW");
   ptr_CM_Get_DevNode_Property_Keys = (__vartype(ptr_CM_Get_DevNode_Property_Keys))GetProcAddress(hModule, "CM_Get_DevNode_Property_Keys");
   ptr_CM_Get_DevNode_Property_Keys_Ex = (__vartype(ptr_CM_Get_DevNode_Property_Keys_Ex))GetProcAddress(hModule, "CM_Get_DevNode_Property_Keys_Ex");
   ptr_CM_Get_DevNode_Registry_PropertyA = (__vartype(ptr_CM_Get_DevNode_Registry_PropertyA))GetProcAddress(hModule, "CM_Get_DevNode_Registry_PropertyA");
   ptr_CM_Get_DevNode_Registry_PropertyW = (__vartype(ptr_CM_Get_DevNode_Registry_PropertyW))GetProcAddress(hModule, "CM_Get_DevNode_Registry_PropertyW");
   ptr_CM_Get_DevNode_Registry_Property_ExA = (__vartype(ptr_CM_Get_DevNode_Registry_Property_ExA))GetProcAddress(hModule, "CM_Get_DevNode_Registry_Property_ExA");
   ptr_CM_Get_DevNode_Registry_Property_ExW = (__vartype(ptr_CM_Get_DevNode_Registry_Property_ExW))GetProcAddress(hModule, "CM_Get_DevNode_Registry_Property_ExW");
   ptr_CM_Get_DevNode_Status = (__vartype(ptr_CM_Get_DevNode_Status))GetProcAddress(hModule, "CM_Get_DevNode_Status");
   ptr_CM_Get_DevNode_Status_Ex = (__vartype(ptr_CM_Get_DevNode_Status_Ex))GetProcAddress(hModule, "CM_Get_DevNode_Status_Ex");
   ptr_CM_Get_Device_IDA = (__vartype(ptr_CM_Get_Device_IDA))GetProcAddress(hModule, "CM_Get_Device_IDA");
   ptr_CM_Get_Device_IDW = (__vartype(ptr_CM_Get_Device_IDW))GetProcAddress(hModule, "CM_Get_Device_IDW");
   ptr_CM_Get_Device_ID_ExA = (__vartype(ptr_CM_Get_Device_ID_ExA))GetProcAddress(hModule, "CM_Get_Device_ID_ExA");
   ptr_CM_Get_Device_ID_ExW = (__vartype(ptr_CM_Get_Device_ID_ExW))GetProcAddress(hModule, "CM_Get_Device_ID_ExW");
   ptr_CM_Get_Device_ID_ListA = (__vartype(ptr_CM_Get_Device_ID_ListA))GetProcAddress(hModule, "CM_Get_Device_ID_ListA");
   ptr_CM_Get_Device_ID_ListW = (__vartype(ptr_CM_Get_Device_ID_ListW))GetProcAddress(hModule, "CM_Get_Device_ID_ListW");
   ptr_CM_Get_Device_ID_List_ExA = (__vartype(ptr_CM_Get_Device_ID_List_ExA))GetProcAddress(hModule, "CM_Get_Device_ID_List_ExA");
   ptr_CM_Get_Device_ID_List_ExW = (__vartype(ptr_CM_Get_Device_ID_List_ExW))GetProcAddress(hModule, "CM_Get_Device_ID_List_ExW");
   ptr_CM_Get_Device_ID_List_SizeA = (__vartype(ptr_CM_Get_Device_ID_List_SizeA))GetProcAddress(hModule, "CM_Get_Device_ID_List_SizeA");
   ptr_CM_Get_Device_ID_List_SizeW = (__vartype(ptr_CM_Get_Device_ID_List_SizeW))GetProcAddress(hModule, "CM_Get_Device_ID_List_SizeW");
   ptr_CM_Get_Device_ID_List_Size_ExA = (__vartype(ptr_CM_Get_Device_ID_List_Size_ExA))GetProcAddress(hModule, "CM_Get_Device_ID_List_Size_ExA");
   ptr_CM_Get_Device_ID_List_Size_ExW = (__vartype(ptr_CM_Get_Device_ID_List_Size_ExW))GetProcAddress(hModule, "CM_Get_Device_ID_List_Size_ExW");
   ptr_CM_Get_Device_ID_Size = (__vartype(ptr_CM_Get_Device_ID_Size))GetProcAddress(hModule, "CM_Get_Device_ID_Size");
   ptr_CM_Get_Device_ID_Size_Ex = (__vartype(ptr_CM_Get_Device_ID_Size_Ex))GetProcAddress(hModule, "CM_Get_Device_ID_Size_Ex");
   ptr_CM_Get_Device_Interface_AliasA = (__vartype(ptr_CM_Get_Device_Interface_AliasA))GetProcAddress(hModule, "CM_Get_Device_Interface_AliasA");
   ptr_CM_Get_Device_Interface_AliasW = (__vartype(ptr_CM_Get_Device_Interface_AliasW))GetProcAddress(hModule, "CM_Get_Device_Interface_AliasW");
   ptr_CM_Get_Device_Interface_Alias_ExA = (__vartype(ptr_CM_Get_Device_Interface_Alias_ExA))GetProcAddress(hModule, "CM_Get_Device_Interface_Alias_ExA");
   ptr_CM_Get_Device_Interface_Alias_ExW = (__vartype(ptr_CM_Get_Device_Interface_Alias_ExW))GetProcAddress(hModule, "CM_Get_Device_Interface_Alias_ExW");
   ptr_CM_Get_Device_Interface_ListA = (__vartype(ptr_CM_Get_Device_Interface_ListA))GetProcAddress(hModule, "CM_Get_Device_Interface_ListA");
   ptr_CM_Get_Device_Interface_ListW = (__vartype(ptr_CM_Get_Device_Interface_ListW))GetProcAddress(hModule, "CM_Get_Device_Interface_ListW");
   ptr_CM_Get_Device_Interface_List_ExA = (__vartype(ptr_CM_Get_Device_Interface_List_ExA))GetProcAddress(hModule, "CM_Get_Device_Interface_List_ExA");
   ptr_CM_Get_Device_Interface_List_ExW = (__vartype(ptr_CM_Get_Device_Interface_List_ExW))GetProcAddress(hModule, "CM_Get_Device_Interface_List_ExW");
   ptr_CM_Get_Device_Interface_List_SizeA = (__vartype(ptr_CM_Get_Device_Interface_List_SizeA))GetProcAddress(hModule, "CM_Get_Device_Interface_List_SizeA");
   ptr_CM_Get_Device_Interface_List_SizeW = (__vartype(ptr_CM_Get_Device_Interface_List_SizeW))GetProcAddress(hModule, "CM_Get_Device_Interface_List_SizeW");
   ptr_CM_Get_Device_Interface_List_Size_ExA = (__vartype(ptr_CM_Get_Device_Interface_List_Size_ExA))GetProcAddress(hModule, "CM_Get_Device_Interface_List_Size_ExA");
   ptr_CM_Get_Device_Interface_List_Size_ExW = (__vartype(ptr_CM_Get_Device_Interface_List_Size_ExW))GetProcAddress(hModule, "CM_Get_Device_Interface_List_Size_ExW");
   ptr_CM_Get_Device_Interface_PropertyW = (__vartype(ptr_CM_Get_Device_Interface_PropertyW))GetProcAddress(hModule, "CM_Get_Device_Interface_PropertyW");
   ptr_CM_Get_Device_Interface_Property_ExW = (__vartype(ptr_CM_Get_Device_Interface_Property_ExW))GetProcAddress(hModule, "CM_Get_Device_Interface_Property_ExW");
   ptr_CM_Get_Device_Interface_Property_KeysW = (__vartype(ptr_CM_Get_Device_Interface_Property_KeysW))GetProcAddress(hModule, "CM_Get_Device_Interface_Property_KeysW");
   ptr_CM_Get_Device_Interface_Property_Keys_ExW = (__vartype(ptr_CM_Get_Device_Interface_Property_Keys_ExW))GetProcAddress(hModule, "CM_Get_Device_Interface_Property_Keys_ExW");
   ptr_CM_Get_First_Log_Conf = (__vartype(ptr_CM_Get_First_Log_Conf))GetProcAddress(hModule, "CM_Get_First_Log_Conf");
   ptr_CM_Get_First_Log_Conf_Ex = (__vartype(ptr_CM_Get_First_Log_Conf_Ex))GetProcAddress(hModule, "CM_Get_First_Log_Conf_Ex");
   ptr_CM_Get_Global_State = (__vartype(ptr_CM_Get_Global_State))GetProcAddress(hModule, "CM_Get_Global_State");
   ptr_CM_Get_Global_State_Ex = (__vartype(ptr_CM_Get_Global_State_Ex))GetProcAddress(hModule, "CM_Get_Global_State_Ex");
   ptr_CM_Get_HW_Prof_FlagsA = (__vartype(ptr_CM_Get_HW_Prof_FlagsA))GetProcAddress(hModule, "CM_Get_HW_Prof_FlagsA");
   ptr_CM_Get_HW_Prof_FlagsW = (__vartype(ptr_CM_Get_HW_Prof_FlagsW))GetProcAddress(hModule, "CM_Get_HW_Prof_FlagsW");
   ptr_CM_Get_HW_Prof_Flags_ExA = (__vartype(ptr_CM_Get_HW_Prof_Flags_ExA))GetProcAddress(hModule, "CM_Get_HW_Prof_Flags_ExA");
   ptr_CM_Get_HW_Prof_Flags_ExW = (__vartype(ptr_CM_Get_HW_Prof_Flags_ExW))GetProcAddress(hModule, "CM_Get_HW_Prof_Flags_ExW");
   ptr_CM_Get_Hardware_Profile_InfoA = (__vartype(ptr_CM_Get_Hardware_Profile_InfoA))GetProcAddress(hModule, "CM_Get_Hardware_Profile_InfoA");
   ptr_CM_Get_Hardware_Profile_InfoW = (__vartype(ptr_CM_Get_Hardware_Profile_InfoW))GetProcAddress(hModule, "CM_Get_Hardware_Profile_InfoW");
   ptr_CM_Get_Hardware_Profile_Info_ExA = (__vartype(ptr_CM_Get_Hardware_Profile_Info_ExA))GetProcAddress(hModule, "CM_Get_Hardware_Profile_Info_ExA");
   ptr_CM_Get_Hardware_Profile_Info_ExW = (__vartype(ptr_CM_Get_Hardware_Profile_Info_ExW))GetProcAddress(hModule, "CM_Get_Hardware_Profile_Info_ExW");
   ptr_CM_Get_Log_Conf_Priority = (__vartype(ptr_CM_Get_Log_Conf_Priority))GetProcAddress(hModule, "CM_Get_Log_Conf_Priority");
   ptr_CM_Get_Log_Conf_Priority_Ex = (__vartype(ptr_CM_Get_Log_Conf_Priority_Ex))GetProcAddress(hModule, "CM_Get_Log_Conf_Priority_Ex");
   ptr_CM_Get_Next_Log_Conf = (__vartype(ptr_CM_Get_Next_Log_Conf))GetProcAddress(hModule, "CM_Get_Next_Log_Conf");
   ptr_CM_Get_Next_Log_Conf_Ex = (__vartype(ptr_CM_Get_Next_Log_Conf_Ex))GetProcAddress(hModule, "CM_Get_Next_Log_Conf_Ex");
   ptr_CM_Get_Next_Res_Des = (__vartype(ptr_CM_Get_Next_Res_Des))GetProcAddress(hModule, "CM_Get_Next_Res_Des");
   ptr_CM_Get_Next_Res_Des_Ex = (__vartype(ptr_CM_Get_Next_Res_Des_Ex))GetProcAddress(hModule, "CM_Get_Next_Res_Des_Ex");
   ptr_CM_Get_Parent = (__vartype(ptr_CM_Get_Parent))GetProcAddress(hModule, "CM_Get_Parent");
   ptr_CM_Get_Parent_Ex = (__vartype(ptr_CM_Get_Parent_Ex))GetProcAddress(hModule, "CM_Get_Parent_Ex");
   ptr_CM_Get_Res_Des_Data = (__vartype(ptr_CM_Get_Res_Des_Data))GetProcAddress(hModule, "CM_Get_Res_Des_Data");
   ptr_CM_Get_Res_Des_Data_Ex = (__vartype(ptr_CM_Get_Res_Des_Data_Ex))GetProcAddress(hModule, "CM_Get_Res_Des_Data_Ex");
   ptr_CM_Get_Res_Des_Data_Size = (__vartype(ptr_CM_Get_Res_Des_Data_Size))GetProcAddress(hModule, "CM_Get_Res_Des_Data_Size");
   ptr_CM_Get_Res_Des_Data_Size_Ex = (__vartype(ptr_CM_Get_Res_Des_Data_Size_Ex))GetProcAddress(hModule, "CM_Get_Res_Des_Data_Size_Ex");
   ptr_CM_Get_Resource_Conflict_Count = (__vartype(ptr_CM_Get_Resource_Conflict_Count))GetProcAddress(hModule, "CM_Get_Resource_Conflict_Count");
   ptr_CM_Get_Resource_Conflict_DetailsA = (__vartype(ptr_CM_Get_Resource_Conflict_DetailsA))GetProcAddress(hModule, "CM_Get_Resource_Conflict_DetailsA");
   ptr_CM_Get_Resource_Conflict_DetailsW = (__vartype(ptr_CM_Get_Resource_Conflict_DetailsW))GetProcAddress(hModule, "CM_Get_Resource_Conflict_DetailsW");
   ptr_CM_Get_Sibling = (__vartype(ptr_CM_Get_Sibling))GetProcAddress(hModule, "CM_Get_Sibling");
   ptr_CM_Get_Sibling_Ex = (__vartype(ptr_CM_Get_Sibling_Ex))GetProcAddress(hModule, "CM_Get_Sibling_Ex");
   ptr_CM_Get_Version = (__vartype(ptr_CM_Get_Version))GetProcAddress(hModule, "CM_Get_Version");
   ptr_CM_Get_Version_Ex = (__vartype(ptr_CM_Get_Version_Ex))GetProcAddress(hModule, "CM_Get_Version_Ex");
   ptr_CM_Import_PowerScheme = (__vartype(ptr_CM_Import_PowerScheme))GetProcAddress(hModule, "CM_Import_PowerScheme");
   ptr_CM_Install_DevNodeW = (__vartype(ptr_CM_Install_DevNodeW))GetProcAddress(hModule, "CM_Install_DevNodeW");
   ptr_CM_Install_DevNode_ExW = (__vartype(ptr_CM_Install_DevNode_ExW))GetProcAddress(hModule, "CM_Install_DevNode_ExW");
   ptr_CM_Intersect_Range_List = (__vartype(ptr_CM_Intersect_Range_List))GetProcAddress(hModule, "CM_Intersect_Range_List");
   ptr_CM_Invert_Range_List = (__vartype(ptr_CM_Invert_Range_List))GetProcAddress(hModule, "CM_Invert_Range_List");
   ptr_CM_Is_Dock_Station_Present = (__vartype(ptr_CM_Is_Dock_Station_Present))GetProcAddress(hModule, "CM_Is_Dock_Station_Present");
   ptr_CM_Is_Dock_Station_Present_Ex = (__vartype(ptr_CM_Is_Dock_Station_Present_Ex))GetProcAddress(hModule, "CM_Is_Dock_Station_Present_Ex");
   ptr_CM_Is_Version_Available = (__vartype(ptr_CM_Is_Version_Available))GetProcAddress(hModule, "CM_Is_Version_Available");
   ptr_CM_Is_Version_Available_Ex = (__vartype(ptr_CM_Is_Version_Available_Ex))GetProcAddress(hModule, "CM_Is_Version_Available_Ex");
   ptr_CM_Locate_DevNodeA = (__vartype(ptr_CM_Locate_DevNodeA))GetProcAddress(hModule, "CM_Locate_DevNodeA");
   ptr_CM_Locate_DevNodeW = (__vartype(ptr_CM_Locate_DevNodeW))GetProcAddress(hModule, "CM_Locate_DevNodeW");
   ptr_CM_Locate_DevNode_ExA = (__vartype(ptr_CM_Locate_DevNode_ExA))GetProcAddress(hModule, "CM_Locate_DevNode_ExA");
   ptr_CM_Locate_DevNode_ExW = (__vartype(ptr_CM_Locate_DevNode_ExW))GetProcAddress(hModule, "CM_Locate_DevNode_ExW");
   ptr_CM_MapCrToSpErr = (__vartype(ptr_CM_MapCrToSpErr))GetProcAddress(hModule, "CM_MapCrToSpErr");
   ptr_CM_MapCrToWin32Err = (__vartype(ptr_CM_MapCrToWin32Err))GetProcAddress(hModule, "CM_MapCrToWin32Err");
   ptr_CM_Merge_Range_List = (__vartype(ptr_CM_Merge_Range_List))GetProcAddress(hModule, "CM_Merge_Range_List");
   ptr_CM_Modify_Res_Des = (__vartype(ptr_CM_Modify_Res_Des))GetProcAddress(hModule, "CM_Modify_Res_Des");
   ptr_CM_Modify_Res_Des_Ex = (__vartype(ptr_CM_Modify_Res_Des_Ex))GetProcAddress(hModule, "CM_Modify_Res_Des_Ex");
   ptr_CM_Move_DevNode = (__vartype(ptr_CM_Move_DevNode))GetProcAddress(hModule, "CM_Move_DevNode");
   ptr_CM_Move_DevNode_Ex = (__vartype(ptr_CM_Move_DevNode_Ex))GetProcAddress(hModule, "CM_Move_DevNode_Ex");
   ptr_CM_Next_Range = (__vartype(ptr_CM_Next_Range))GetProcAddress(hModule, "CM_Next_Range");
   ptr_CM_Open_Class_KeyA = (__vartype(ptr_CM_Open_Class_KeyA))GetProcAddress(hModule, "CM_Open_Class_KeyA");
   ptr_CM_Open_Class_KeyW = (__vartype(ptr_CM_Open_Class_KeyW))GetProcAddress(hModule, "CM_Open_Class_KeyW");
   ptr_CM_Open_Class_Key_ExA = (__vartype(ptr_CM_Open_Class_Key_ExA))GetProcAddress(hModule, "CM_Open_Class_Key_ExA");
   ptr_CM_Open_Class_Key_ExW = (__vartype(ptr_CM_Open_Class_Key_ExW))GetProcAddress(hModule, "CM_Open_Class_Key_ExW");
   ptr_CM_Open_DevNode_Key = (__vartype(ptr_CM_Open_DevNode_Key))GetProcAddress(hModule, "CM_Open_DevNode_Key");
   ptr_CM_Open_DevNode_Key_Ex = (__vartype(ptr_CM_Open_DevNode_Key_Ex))GetProcAddress(hModule, "CM_Open_DevNode_Key_Ex");
   ptr_CM_Open_Device_Interface_KeyA = (__vartype(ptr_CM_Open_Device_Interface_KeyA))GetProcAddress(hModule, "CM_Open_Device_Interface_KeyA");
   ptr_CM_Open_Device_Interface_KeyW = (__vartype(ptr_CM_Open_Device_Interface_KeyW))GetProcAddress(hModule, "CM_Open_Device_Interface_KeyW");
   ptr_CM_Open_Device_Interface_Key_ExA = (__vartype(ptr_CM_Open_Device_Interface_Key_ExA))GetProcAddress(hModule, "CM_Open_Device_Interface_Key_ExA");
   ptr_CM_Open_Device_Interface_Key_ExW = (__vartype(ptr_CM_Open_Device_Interface_Key_ExW))GetProcAddress(hModule, "CM_Open_Device_Interface_Key_ExW");
   ptr_CM_Query_And_Remove_SubTreeA = (__vartype(ptr_CM_Query_And_Remove_SubTreeA))GetProcAddress(hModule, "CM_Query_And_Remove_SubTreeA");
   ptr_CM_Query_And_Remove_SubTreeW = (__vartype(ptr_CM_Query_And_Remove_SubTreeW))GetProcAddress(hModule, "CM_Query_And_Remove_SubTreeW");
   ptr_CM_Query_And_Remove_SubTree_ExA = (__vartype(ptr_CM_Query_And_Remove_SubTree_ExA))GetProcAddress(hModule, "CM_Query_And_Remove_SubTree_ExA");
   ptr_CM_Query_And_Remove_SubTree_ExW = (__vartype(ptr_CM_Query_And_Remove_SubTree_ExW))GetProcAddress(hModule, "CM_Query_And_Remove_SubTree_ExW");
   ptr_CM_Query_Arbitrator_Free_Data = (__vartype(ptr_CM_Query_Arbitrator_Free_Data))GetProcAddress(hModule, "CM_Query_Arbitrator_Free_Data");
   ptr_CM_Query_Arbitrator_Free_Data_Ex = (__vartype(ptr_CM_Query_Arbitrator_Free_Data_Ex))GetProcAddress(hModule, "CM_Query_Arbitrator_Free_Data_Ex");
   ptr_CM_Query_Arbitrator_Free_Size = (__vartype(ptr_CM_Query_Arbitrator_Free_Size))GetProcAddress(hModule, "CM_Query_Arbitrator_Free_Size");
   ptr_CM_Query_Arbitrator_Free_Size_Ex = (__vartype(ptr_CM_Query_Arbitrator_Free_Size_Ex))GetProcAddress(hModule, "CM_Query_Arbitrator_Free_Size_Ex");
   ptr_CM_Query_Remove_SubTree = (__vartype(ptr_CM_Query_Remove_SubTree))GetProcAddress(hModule, "CM_Query_Remove_SubTree");
   ptr_CM_Query_Remove_SubTree_Ex = (__vartype(ptr_CM_Query_Remove_SubTree_Ex))GetProcAddress(hModule, "CM_Query_Remove_SubTree_Ex");
   ptr_CM_Query_Resource_Conflict_List = (__vartype(ptr_CM_Query_Resource_Conflict_List))GetProcAddress(hModule, "CM_Query_Resource_Conflict_List");
   ptr_CM_Reenumerate_DevNode = (__vartype(ptr_CM_Reenumerate_DevNode))GetProcAddress(hModule, "CM_Reenumerate_DevNode");
   ptr_CM_Reenumerate_DevNode_Ex = (__vartype(ptr_CM_Reenumerate_DevNode_Ex))GetProcAddress(hModule, "CM_Reenumerate_DevNode_Ex");
   ptr_CM_Register_Device_Driver = (__vartype(ptr_CM_Register_Device_Driver))GetProcAddress(hModule, "CM_Register_Device_Driver");
   ptr_CM_Register_Device_Driver_Ex = (__vartype(ptr_CM_Register_Device_Driver_Ex))GetProcAddress(hModule, "CM_Register_Device_Driver_Ex");
   ptr_CM_Register_Device_InterfaceA = (__vartype(ptr_CM_Register_Device_InterfaceA))GetProcAddress(hModule, "CM_Register_Device_InterfaceA");
   ptr_CM_Register_Device_InterfaceW = (__vartype(ptr_CM_Register_Device_InterfaceW))GetProcAddress(hModule, "CM_Register_Device_InterfaceW");
   ptr_CM_Register_Device_Interface_ExA = (__vartype(ptr_CM_Register_Device_Interface_ExA))GetProcAddress(hModule, "CM_Register_Device_Interface_ExA");
   ptr_CM_Register_Device_Interface_ExW = (__vartype(ptr_CM_Register_Device_Interface_ExW))GetProcAddress(hModule, "CM_Register_Device_Interface_ExW");
   ptr_CM_Remove_SubTree = (__vartype(ptr_CM_Remove_SubTree))GetProcAddress(hModule, "CM_Remove_SubTree");
   ptr_CM_Remove_SubTree_Ex = (__vartype(ptr_CM_Remove_SubTree_Ex))GetProcAddress(hModule, "CM_Remove_SubTree_Ex");
   ptr_CM_Request_Device_EjectA = (__vartype(ptr_CM_Request_Device_EjectA))GetProcAddress(hModule, "CM_Request_Device_EjectA");
   ptr_CM_Request_Device_EjectW = (__vartype(ptr_CM_Request_Device_EjectW))GetProcAddress(hModule, "CM_Request_Device_EjectW");
   ptr_CM_Request_Device_Eject_ExA = (__vartype(ptr_CM_Request_Device_Eject_ExA))GetProcAddress(hModule, "CM_Request_Device_Eject_ExA");
   ptr_CM_Request_Device_Eject_ExW = (__vartype(ptr_CM_Request_Device_Eject_ExW))GetProcAddress(hModule, "CM_Request_Device_Eject_ExW");
   ptr_CM_Request_Eject_PC = (__vartype(ptr_CM_Request_Eject_PC))GetProcAddress(hModule, "CM_Request_Eject_PC");
   ptr_CM_Request_Eject_PC_Ex = (__vartype(ptr_CM_Request_Eject_PC_Ex))GetProcAddress(hModule, "CM_Request_Eject_PC_Ex");
   ptr_CM_RestoreAll_DefaultPowerSchemes = (__vartype(ptr_CM_RestoreAll_DefaultPowerSchemes))GetProcAddress(hModule, "CM_RestoreAll_DefaultPowerSchemes");
   ptr_CM_Restore_DefaultPowerScheme = (__vartype(ptr_CM_Restore_DefaultPowerScheme))GetProcAddress(hModule, "CM_Restore_DefaultPowerScheme");
   ptr_CM_Run_Detection = (__vartype(ptr_CM_Run_Detection))GetProcAddress(hModule, "CM_Run_Detection");
   ptr_CM_Run_Detection_Ex = (__vartype(ptr_CM_Run_Detection_Ex))GetProcAddress(hModule, "CM_Run_Detection_Ex");
   ptr_CM_Set_ActiveScheme = (__vartype(ptr_CM_Set_ActiveScheme))GetProcAddress(hModule, "CM_Set_ActiveScheme");
   ptr_CM_Set_Class_PropertyW = (__vartype(ptr_CM_Set_Class_PropertyW))GetProcAddress(hModule, "CM_Set_Class_PropertyW");
   ptr_CM_Set_Class_Property_ExW = (__vartype(ptr_CM_Set_Class_Property_ExW))GetProcAddress(hModule, "CM_Set_Class_Property_ExW");
   ptr_CM_Set_Class_Registry_PropertyA = (__vartype(ptr_CM_Set_Class_Registry_PropertyA))GetProcAddress(hModule, "CM_Set_Class_Registry_PropertyA");
   ptr_CM_Set_Class_Registry_PropertyW = (__vartype(ptr_CM_Set_Class_Registry_PropertyW))GetProcAddress(hModule, "CM_Set_Class_Registry_PropertyW");
   ptr_CM_Set_DevNode_Problem = (__vartype(ptr_CM_Set_DevNode_Problem))GetProcAddress(hModule, "CM_Set_DevNode_Problem");
   ptr_CM_Set_DevNode_Problem_Ex = (__vartype(ptr_CM_Set_DevNode_Problem_Ex))GetProcAddress(hModule, "CM_Set_DevNode_Problem_Ex");
   ptr_CM_Set_DevNode_PropertyW = (__vartype(ptr_CM_Set_DevNode_PropertyW))GetProcAddress(hModule, "CM_Set_DevNode_PropertyW");
   ptr_CM_Set_DevNode_Property_ExW = (__vartype(ptr_CM_Set_DevNode_Property_ExW))GetProcAddress(hModule, "CM_Set_DevNode_Property_ExW");
   ptr_CM_Set_DevNode_Registry_PropertyA = (__vartype(ptr_CM_Set_DevNode_Registry_PropertyA))GetProcAddress(hModule, "CM_Set_DevNode_Registry_PropertyA");
   ptr_CM_Set_DevNode_Registry_PropertyW = (__vartype(ptr_CM_Set_DevNode_Registry_PropertyW))GetProcAddress(hModule, "CM_Set_DevNode_Registry_PropertyW");
   ptr_CM_Set_DevNode_Registry_Property_ExA = (__vartype(ptr_CM_Set_DevNode_Registry_Property_ExA))GetProcAddress(hModule, "CM_Set_DevNode_Registry_Property_ExA");
   ptr_CM_Set_DevNode_Registry_Property_ExW = (__vartype(ptr_CM_Set_DevNode_Registry_Property_ExW))GetProcAddress(hModule, "CM_Set_DevNode_Registry_Property_ExW");
   ptr_CM_Set_Device_Interface_PropertyW = (__vartype(ptr_CM_Set_Device_Interface_PropertyW))GetProcAddress(hModule, "CM_Set_Device_Interface_PropertyW");
   ptr_CM_Set_Device_Interface_Property_ExW = (__vartype(ptr_CM_Set_Device_Interface_Property_ExW))GetProcAddress(hModule, "CM_Set_Device_Interface_Property_ExW");
   ptr_CM_Set_HW_Prof = (__vartype(ptr_CM_Set_HW_Prof))GetProcAddress(hModule, "CM_Set_HW_Prof");
   ptr_CM_Set_HW_Prof_Ex = (__vartype(ptr_CM_Set_HW_Prof_Ex))GetProcAddress(hModule, "CM_Set_HW_Prof_Ex");
   ptr_CM_Set_HW_Prof_FlagsA = (__vartype(ptr_CM_Set_HW_Prof_FlagsA))GetProcAddress(hModule, "CM_Set_HW_Prof_FlagsA");
   ptr_CM_Set_HW_Prof_FlagsW = (__vartype(ptr_CM_Set_HW_Prof_FlagsW))GetProcAddress(hModule, "CM_Set_HW_Prof_FlagsW");
   ptr_CM_Set_HW_Prof_Flags_ExA = (__vartype(ptr_CM_Set_HW_Prof_Flags_ExA))GetProcAddress(hModule, "CM_Set_HW_Prof_Flags_ExA");
   ptr_CM_Set_HW_Prof_Flags_ExW = (__vartype(ptr_CM_Set_HW_Prof_Flags_ExW))GetProcAddress(hModule, "CM_Set_HW_Prof_Flags_ExW");
   ptr_CM_Setup_DevNode = (__vartype(ptr_CM_Setup_DevNode))GetProcAddress(hModule, "CM_Setup_DevNode");
   ptr_CM_Setup_DevNode_Ex = (__vartype(ptr_CM_Setup_DevNode_Ex))GetProcAddress(hModule, "CM_Setup_DevNode_Ex");
   ptr_CM_Test_Range_Available = (__vartype(ptr_CM_Test_Range_Available))GetProcAddress(hModule, "CM_Test_Range_Available");
   ptr_CM_Uninstall_DevNode = (__vartype(ptr_CM_Uninstall_DevNode))GetProcAddress(hModule, "CM_Uninstall_DevNode");
   ptr_CM_Uninstall_DevNode_Ex = (__vartype(ptr_CM_Uninstall_DevNode_Ex))GetProcAddress(hModule, "CM_Uninstall_DevNode_Ex");
   ptr_CM_Unregister_Device_InterfaceA = (__vartype(ptr_CM_Unregister_Device_InterfaceA))GetProcAddress(hModule, "CM_Unregister_Device_InterfaceA");
   ptr_CM_Unregister_Device_InterfaceW = (__vartype(ptr_CM_Unregister_Device_InterfaceW))GetProcAddress(hModule, "CM_Unregister_Device_InterfaceW");
   ptr_CM_Unregister_Device_Interface_ExA = (__vartype(ptr_CM_Unregister_Device_Interface_ExA))GetProcAddress(hModule, "CM_Unregister_Device_Interface_ExA");
   ptr_CM_Unregister_Device_Interface_ExW = (__vartype(ptr_CM_Unregister_Device_Interface_ExW))GetProcAddress(hModule, "CM_Unregister_Device_Interface_ExW");
   ptr_CM_Write_UserPowerKey = (__vartype(ptr_CM_Write_UserPowerKey))GetProcAddress(hModule, "CM_Write_UserPowerKey");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

