#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_AddGadgetMessageHandler;
void *ptr_AddGadgetMessageHandler = NULL;
extern void *ptr_AddLayeredRef;
void *ptr_AddLayeredRef = NULL;
extern void *ptr_AdjustClipInsideRef;
void *ptr_AdjustClipInsideRef = NULL;
extern void *ptr_AttachWndProcA;
void *ptr_AttachWndProcA = NULL;
extern void *ptr_AttachWndProcW;
void *ptr_AttachWndProcW = NULL;
extern void *ptr_AutoTrace;
void *ptr_AutoTrace = NULL;
extern void *ptr_BeginHideInputPaneAnimation;
void *ptr_BeginHideInputPaneAnimation = NULL;
extern void *ptr_BeginShowInputPaneAnimation;
void *ptr_BeginShowInputPaneAnimation = NULL;
extern void *ptr_BuildAnimation;
void *ptr_BuildAnimation = NULL;
extern void *ptr_BuildDropTarget;
void *ptr_BuildDropTarget = NULL;
extern void *ptr_BuildInterpolation;
void *ptr_BuildInterpolation = NULL;
extern void *ptr_CacheDWriteRenderTarget;
void *ptr_CacheDWriteRenderTarget = NULL;
extern void *ptr_ChangeCurrentAnimationScenario;
void *ptr_ChangeCurrentAnimationScenario = NULL;
extern void *ptr_ClearPushedOpacitiesFromGadgetTree;
void *ptr_ClearPushedOpacitiesFromGadgetTree = NULL;
extern void *ptr_ClearTopmostVisual;
void *ptr_ClearTopmostVisual = NULL;
extern void *ptr_CreateAction;
void *ptr_CreateAction = NULL;
extern void *ptr_CreateGadget;
void *ptr_CreateGadget = NULL;
extern void *ptr_CustomGadgetHitTestQuery;
void *ptr_CustomGadgetHitTestQuery = NULL;
extern void *ptr_DUserBuildGadget;
void *ptr_DUserBuildGadget = NULL;
extern void *ptr_DUserCastClass;
void *ptr_DUserCastClass = NULL;
extern void *ptr_DUserCastDirect;
void *ptr_DUserCastDirect = NULL;
extern void *ptr_DUserCastHandle;
void *ptr_DUserCastHandle = NULL;
extern void *ptr_DUserDeleteGadget;
void *ptr_DUserDeleteGadget = NULL;
extern void *ptr_DUserFindClass;
void *ptr_DUserFindClass = NULL;
extern void *ptr_DUserFlushDeferredMessages;
void *ptr_DUserFlushDeferredMessages = NULL;
extern void *ptr_DUserFlushMessages;
void *ptr_DUserFlushMessages = NULL;
extern void *ptr_DUserGetAlphaPRID;
void *ptr_DUserGetAlphaPRID = NULL;
extern void *ptr_DUserGetGutsData;
void *ptr_DUserGetGutsData = NULL;
extern void *ptr_DUserGetRectPRID;
void *ptr_DUserGetRectPRID = NULL;
extern void *ptr_DUserGetRotatePRID;
void *ptr_DUserGetRotatePRID = NULL;
extern void *ptr_DUserGetScalePRID;
void *ptr_DUserGetScalePRID = NULL;
extern void *ptr_DUserInstanceOf;
void *ptr_DUserInstanceOf = NULL;
extern void *ptr_DUserPostEvent;
void *ptr_DUserPostEvent = NULL;
extern void *ptr_DUserPostMethod;
void *ptr_DUserPostMethod = NULL;
extern void *ptr_DUserRegisterGuts;
void *ptr_DUserRegisterGuts = NULL;
extern void *ptr_DUserRegisterStub;
void *ptr_DUserRegisterStub = NULL;
extern void *ptr_DUserRegisterSuper;
void *ptr_DUserRegisterSuper = NULL;
extern void *ptr_DUserSendEvent;
void *ptr_DUserSendEvent = NULL;
extern void *ptr_DUserSendMethod;
void *ptr_DUserSendMethod = NULL;
extern void *ptr_DUserStopAnimation;
void *ptr_DUserStopAnimation = NULL;
extern void *ptr_DUserStopPVLAnimation;
void *ptr_DUserStopPVLAnimation = NULL;
extern void *ptr_DeleteHandle;
void *ptr_DeleteHandle = NULL;
extern void *ptr_DestroyPendingDCVisuals;
void *ptr_DestroyPendingDCVisuals = NULL;
extern void *ptr_DetachGadgetVisuals;
void *ptr_DetachGadgetVisuals = NULL;
extern void *ptr_DetachWndProc;
void *ptr_DetachWndProc = NULL;
extern void *ptr_DisableContainerHwnd;
void *ptr_DisableContainerHwnd = NULL;
extern void *ptr_DllMain;
void *ptr_DllMain = NULL;
extern void *ptr_DrawGadgetTree;
void *ptr_DrawGadgetTree = NULL;
extern void *ptr_EndInputPaneAnimation;
void *ptr_EndInputPaneAnimation = NULL;
extern void *ptr_EnsureAnimationsEnabled;
void *ptr_EnsureAnimationsEnabled = NULL;
extern void *ptr_EnsureGadgetTransInitialized;
void *ptr_EnsureGadgetTransInitialized = NULL;
extern void *ptr_EnumGadgets;
void *ptr_EnumGadgets = NULL;
extern void *ptr_FindGadgetFromPoint;
void *ptr_FindGadgetFromPoint = NULL;
extern void *ptr_FindGadgetMessages;
void *ptr_FindGadgetMessages = NULL;
extern void *ptr_FindGadgetTargetingInfo;
void *ptr_FindGadgetTargetingInfo = NULL;
extern void *ptr_FindStdColor;
void *ptr_FindStdColor = NULL;
extern void *ptr_FireGadgetMessages;
void *ptr_FireGadgetMessages = NULL;
extern void *ptr_ForwardGadgetMessage;
void *ptr_ForwardGadgetMessage = NULL;
extern void *ptr_GadgetTransCompositionChanged;
void *ptr_GadgetTransCompositionChanged = NULL;
extern void *ptr_GadgetTransSettingChanged;
void *ptr_GadgetTransSettingChanged = NULL;
extern void *ptr_GetActionTimeslice;
void *ptr_GetActionTimeslice = NULL;
extern void *ptr_GetCachedDWriteRenderTarget;
void *ptr_GetCachedDWriteRenderTarget = NULL;
extern void *ptr_GetDUserModule;
void *ptr_GetDUserModule = NULL;
extern void *ptr_GetDebug;
void *ptr_GetDebug = NULL;
extern void *ptr_GetFinalAnimatingPosition;
void *ptr_GetFinalAnimatingPosition = NULL;
extern void *ptr_GetGadget;
void *ptr_GetGadget = NULL;
extern void *ptr_GetGadgetAnimation;
void *ptr_GetGadgetAnimation = NULL;
extern void *ptr_GetGadgetBitmap;
void *ptr_GetGadgetBitmap = NULL;
extern void *ptr_GetGadgetBufferInfo;
void *ptr_GetGadgetBufferInfo = NULL;
extern void *ptr_GetGadgetCenterPoint;
void *ptr_GetGadgetCenterPoint = NULL;
extern void *ptr_GetGadgetFlags;
void *ptr_GetGadgetFlags = NULL;
extern void *ptr_GetGadgetFocus;
void *ptr_GetGadgetFocus = NULL;
extern void *ptr_GetGadgetLayerInfo;
void *ptr_GetGadgetLayerInfo = NULL;
extern void *ptr_GetGadgetMessageFilter;
void *ptr_GetGadgetMessageFilter = NULL;
extern void *ptr_GetGadgetProperty;
void *ptr_GetGadgetProperty = NULL;
extern void *ptr_GetGadgetRect;
void *ptr_GetGadgetRect = NULL;
extern void *ptr_GetGadgetRgn;
void *ptr_GetGadgetRgn = NULL;
extern void *ptr_GetGadgetRootInfo;
void *ptr_GetGadgetRootInfo = NULL;
extern void *ptr_GetGadgetRotation;
void *ptr_GetGadgetRotation = NULL;
extern void *ptr_GetGadgetScale;
void *ptr_GetGadgetScale = NULL;
extern void *ptr_GetGadgetSize;
void *ptr_GetGadgetSize = NULL;
extern void *ptr_GetGadgetStyle;
void *ptr_GetGadgetStyle = NULL;
extern void *ptr_GetGadgetTicket;
void *ptr_GetGadgetTicket = NULL;
extern void *ptr_GetGadgetVisual;
void *ptr_GetGadgetVisual = NULL;
extern void *ptr_GetMessageExA;
void *ptr_GetMessageExA = NULL;
extern void *ptr_GetMessageExW;
void *ptr_GetMessageExW = NULL;
extern void *ptr_GetStdColorBrushF;
void *ptr_GetStdColorBrushF = NULL;
extern void *ptr_GetStdColorBrushI;
void *ptr_GetStdColorBrushI = NULL;
extern void *ptr_GetStdColorF;
void *ptr_GetStdColorF = NULL;
extern void *ptr_GetStdColorI;
void *ptr_GetStdColorI = NULL;
extern void *ptr_GetStdColorName;
void *ptr_GetStdColorName = NULL;
extern void *ptr_GetStdColorPenF;
void *ptr_GetStdColorPenF = NULL;
extern void *ptr_GetStdColorPenI;
void *ptr_GetStdColorPenI = NULL;
extern void *ptr_GetStdPalette;
void *ptr_GetStdPalette = NULL;
extern void *ptr_InitGadgetComponent;
void *ptr_InitGadgetComponent = NULL;
extern void *ptr_InitGadgets;
void *ptr_InitGadgets = NULL;
extern void *ptr_InvalidateGadget;
void *ptr_InvalidateGadget = NULL;
extern void *ptr_InvalidateLayeredDescendants;
void *ptr_InvalidateLayeredDescendants = NULL;
extern void *ptr_IsGadgetParentChainStyle;
void *ptr_IsGadgetParentChainStyle = NULL;
extern void *ptr_IsInsideContext;
void *ptr_IsInsideContext = NULL;
extern void *ptr_IsStartDelete;
void *ptr_IsStartDelete = NULL;
extern void *ptr_LookupGadgetTicket;
void *ptr_LookupGadgetTicket = NULL;
extern void *ptr_MapGadgetPoints;
void *ptr_MapGadgetPoints = NULL;
extern void *ptr_PeekMessageExA;
void *ptr_PeekMessageExA = NULL;
extern void *ptr_PeekMessageExW;
void *ptr_PeekMessageExW = NULL;
extern void *ptr_RegisterGadgetMessage;
void *ptr_RegisterGadgetMessage = NULL;
extern void *ptr_RegisterGadgetMessageString;
void *ptr_RegisterGadgetMessageString = NULL;
extern void *ptr_RegisterGadgetProperty;
void *ptr_RegisterGadgetProperty = NULL;
extern void *ptr_ReleaseDetachedObjects;
void *ptr_ReleaseDetachedObjects = NULL;
extern void *ptr_ReleaseLayeredRef;
void *ptr_ReleaseLayeredRef = NULL;
extern void *ptr_ReleaseMouseCapture;
void *ptr_ReleaseMouseCapture = NULL;
extern void *ptr_RemoveClippingImmunityFromVisual;
void *ptr_RemoveClippingImmunityFromVisual = NULL;
extern void *ptr_RemoveGadgetMessageHandler;
void *ptr_RemoveGadgetMessageHandler = NULL;
extern void *ptr_RemoveGadgetProperty;
void *ptr_RemoveGadgetProperty = NULL;
extern void *ptr_ResetDUserDevice;
void *ptr_ResetDUserDevice = NULL;
extern void *ptr_ScheduleGadgetTransitions;
void *ptr_ScheduleGadgetTransitions = NULL;
extern void *ptr_SetActionTimeslice;
void *ptr_SetActionTimeslice = NULL;
extern void *ptr_SetAtlasingHints;
void *ptr_SetAtlasingHints = NULL;
extern void *ptr_SetGadgetBufferInfo;
void *ptr_SetGadgetBufferInfo = NULL;
extern void *ptr_SetGadgetCenterPoint;
void *ptr_SetGadgetCenterPoint = NULL;
extern void *ptr_SetGadgetFillF;
void *ptr_SetGadgetFillF = NULL;
extern void *ptr_SetGadgetFillI;
void *ptr_SetGadgetFillI = NULL;
extern void *ptr_SetGadgetFlags;
void *ptr_SetGadgetFlags = NULL;
extern void *ptr_SetGadgetFocus;
void *ptr_SetGadgetFocus = NULL;
extern void *ptr_SetGadgetFocusEx;
void *ptr_SetGadgetFocusEx = NULL;
extern void *ptr_SetGadgetLayerInfo;
void *ptr_SetGadgetLayerInfo = NULL;
extern void *ptr_SetGadgetMessageFilter;
void *ptr_SetGadgetMessageFilter = NULL;
extern void *ptr_SetGadgetOrder;
void *ptr_SetGadgetOrder = NULL;
extern void *ptr_SetGadgetParent;
void *ptr_SetGadgetParent = NULL;
extern void *ptr_SetGadgetProperty;
void *ptr_SetGadgetProperty = NULL;
extern void *ptr_SetGadgetRect;
void *ptr_SetGadgetRect = NULL;
extern void *ptr_SetGadgetRootInfo;
void *ptr_SetGadgetRootInfo = NULL;
extern void *ptr_SetGadgetRotation;
void *ptr_SetGadgetRotation = NULL;
extern void *ptr_SetGadgetScale;
void *ptr_SetGadgetScale = NULL;
extern void *ptr_SetGadgetStyle;
void *ptr_SetGadgetStyle = NULL;
extern void *ptr_SetHardwareDeviceUsage;
void *ptr_SetHardwareDeviceUsage = NULL;
extern void *ptr_SetMinimumDCompVersion;
void *ptr_SetMinimumDCompVersion = NULL;
extern void *ptr_SetRestoreCachedLayeredRefFlag;
void *ptr_SetRestoreCachedLayeredRefFlag = NULL;
extern void *ptr_SetTransitionVisualProperties;
void *ptr_SetTransitionVisualProperties = NULL;
extern void *ptr_SetWindowResizeFlag;
void *ptr_SetWindowResizeFlag = NULL;
extern void *ptr_UnregisterGadgetMessage;
void *ptr_UnregisterGadgetMessage = NULL;
extern void *ptr_UnregisterGadgetMessageString;
void *ptr_UnregisterGadgetMessageString = NULL;
extern void *ptr_UnregisterGadgetProperty;
void *ptr_UnregisterGadgetProperty = NULL;
extern void *ptr_UtilBuildFont;
void *ptr_UtilBuildFont = NULL;
extern void *ptr_UtilDrawBlendRect;
void *ptr_UtilDrawBlendRect = NULL;
extern void *ptr_UtilDrawOutlineRect;
void *ptr_UtilDrawOutlineRect = NULL;
extern void *ptr_UtilGetColor;
void *ptr_UtilGetColor = NULL;
extern void *ptr_UtilSetBackground;
void *ptr_UtilSetBackground = NULL;
extern void *ptr_WaitMessageEx;
void *ptr_WaitMessageEx = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\ieui.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_AddGadgetMessageHandler = (__vartype(ptr_AddGadgetMessageHandler))GetProcAddress(hModule, "AddGadgetMessageHandler");
   ptr_AddLayeredRef = (__vartype(ptr_AddLayeredRef))GetProcAddress(hModule, "AddLayeredRef");
   ptr_AdjustClipInsideRef = (__vartype(ptr_AdjustClipInsideRef))GetProcAddress(hModule, "AdjustClipInsideRef");
   ptr_AttachWndProcA = (__vartype(ptr_AttachWndProcA))GetProcAddress(hModule, "AttachWndProcA");
   ptr_AttachWndProcW = (__vartype(ptr_AttachWndProcW))GetProcAddress(hModule, "AttachWndProcW");
   ptr_AutoTrace = (__vartype(ptr_AutoTrace))GetProcAddress(hModule, "AutoTrace");
   ptr_BeginHideInputPaneAnimation = (__vartype(ptr_BeginHideInputPaneAnimation))GetProcAddress(hModule, "BeginHideInputPaneAnimation");
   ptr_BeginShowInputPaneAnimation = (__vartype(ptr_BeginShowInputPaneAnimation))GetProcAddress(hModule, "BeginShowInputPaneAnimation");
   ptr_BuildAnimation = (__vartype(ptr_BuildAnimation))GetProcAddress(hModule, "BuildAnimation");
   ptr_BuildDropTarget = (__vartype(ptr_BuildDropTarget))GetProcAddress(hModule, "BuildDropTarget");
   ptr_BuildInterpolation = (__vartype(ptr_BuildInterpolation))GetProcAddress(hModule, "BuildInterpolation");
   ptr_CacheDWriteRenderTarget = (__vartype(ptr_CacheDWriteRenderTarget))GetProcAddress(hModule, "CacheDWriteRenderTarget");
   ptr_ChangeCurrentAnimationScenario = (__vartype(ptr_ChangeCurrentAnimationScenario))GetProcAddress(hModule, "ChangeCurrentAnimationScenario");
   ptr_ClearPushedOpacitiesFromGadgetTree = (__vartype(ptr_ClearPushedOpacitiesFromGadgetTree))GetProcAddress(hModule, "ClearPushedOpacitiesFromGadgetTree");
   ptr_ClearTopmostVisual = (__vartype(ptr_ClearTopmostVisual))GetProcAddress(hModule, "ClearTopmostVisual");
   ptr_CreateAction = (__vartype(ptr_CreateAction))GetProcAddress(hModule, "CreateAction");
   ptr_CreateGadget = (__vartype(ptr_CreateGadget))GetProcAddress(hModule, "CreateGadget");
   ptr_CustomGadgetHitTestQuery = (__vartype(ptr_CustomGadgetHitTestQuery))GetProcAddress(hModule, "CustomGadgetHitTestQuery");
   ptr_DUserBuildGadget = (__vartype(ptr_DUserBuildGadget))GetProcAddress(hModule, "DUserBuildGadget");
   ptr_DUserCastClass = (__vartype(ptr_DUserCastClass))GetProcAddress(hModule, "DUserCastClass");
   ptr_DUserCastDirect = (__vartype(ptr_DUserCastDirect))GetProcAddress(hModule, "DUserCastDirect");
   ptr_DUserCastHandle = (__vartype(ptr_DUserCastHandle))GetProcAddress(hModule, "DUserCastHandle");
   ptr_DUserDeleteGadget = (__vartype(ptr_DUserDeleteGadget))GetProcAddress(hModule, "DUserDeleteGadget");
   ptr_DUserFindClass = (__vartype(ptr_DUserFindClass))GetProcAddress(hModule, "DUserFindClass");
   ptr_DUserFlushDeferredMessages = (__vartype(ptr_DUserFlushDeferredMessages))GetProcAddress(hModule, "DUserFlushDeferredMessages");
   ptr_DUserFlushMessages = (__vartype(ptr_DUserFlushMessages))GetProcAddress(hModule, "DUserFlushMessages");
   ptr_DUserGetAlphaPRID = (__vartype(ptr_DUserGetAlphaPRID))GetProcAddress(hModule, "DUserGetAlphaPRID");
   ptr_DUserGetGutsData = (__vartype(ptr_DUserGetGutsData))GetProcAddress(hModule, "DUserGetGutsData");
   ptr_DUserGetRectPRID = (__vartype(ptr_DUserGetRectPRID))GetProcAddress(hModule, "DUserGetRectPRID");
   ptr_DUserGetRotatePRID = (__vartype(ptr_DUserGetRotatePRID))GetProcAddress(hModule, "DUserGetRotatePRID");
   ptr_DUserGetScalePRID = (__vartype(ptr_DUserGetScalePRID))GetProcAddress(hModule, "DUserGetScalePRID");
   ptr_DUserInstanceOf = (__vartype(ptr_DUserInstanceOf))GetProcAddress(hModule, "DUserInstanceOf");
   ptr_DUserPostEvent = (__vartype(ptr_DUserPostEvent))GetProcAddress(hModule, "DUserPostEvent");
   ptr_DUserPostMethod = (__vartype(ptr_DUserPostMethod))GetProcAddress(hModule, "DUserPostMethod");
   ptr_DUserRegisterGuts = (__vartype(ptr_DUserRegisterGuts))GetProcAddress(hModule, "DUserRegisterGuts");
   ptr_DUserRegisterStub = (__vartype(ptr_DUserRegisterStub))GetProcAddress(hModule, "DUserRegisterStub");
   ptr_DUserRegisterSuper = (__vartype(ptr_DUserRegisterSuper))GetProcAddress(hModule, "DUserRegisterSuper");
   ptr_DUserSendEvent = (__vartype(ptr_DUserSendEvent))GetProcAddress(hModule, "DUserSendEvent");
   ptr_DUserSendMethod = (__vartype(ptr_DUserSendMethod))GetProcAddress(hModule, "DUserSendMethod");
   ptr_DUserStopAnimation = (__vartype(ptr_DUserStopAnimation))GetProcAddress(hModule, "DUserStopAnimation");
   ptr_DUserStopPVLAnimation = (__vartype(ptr_DUserStopPVLAnimation))GetProcAddress(hModule, "DUserStopPVLAnimation");
   ptr_DeleteHandle = (__vartype(ptr_DeleteHandle))GetProcAddress(hModule, "DeleteHandle");
   ptr_DestroyPendingDCVisuals = (__vartype(ptr_DestroyPendingDCVisuals))GetProcAddress(hModule, "DestroyPendingDCVisuals");
   ptr_DetachGadgetVisuals = (__vartype(ptr_DetachGadgetVisuals))GetProcAddress(hModule, "DetachGadgetVisuals");
   ptr_DetachWndProc = (__vartype(ptr_DetachWndProc))GetProcAddress(hModule, "DetachWndProc");
   ptr_DisableContainerHwnd = (__vartype(ptr_DisableContainerHwnd))GetProcAddress(hModule, "DisableContainerHwnd");
   ptr_DllMain = (__vartype(ptr_DllMain))GetProcAddress(hModule, "DllMain");
   ptr_DrawGadgetTree = (__vartype(ptr_DrawGadgetTree))GetProcAddress(hModule, "DrawGadgetTree");
   ptr_EndInputPaneAnimation = (__vartype(ptr_EndInputPaneAnimation))GetProcAddress(hModule, "EndInputPaneAnimation");
   ptr_EnsureAnimationsEnabled = (__vartype(ptr_EnsureAnimationsEnabled))GetProcAddress(hModule, "EnsureAnimationsEnabled");
   ptr_EnsureGadgetTransInitialized = (__vartype(ptr_EnsureGadgetTransInitialized))GetProcAddress(hModule, "EnsureGadgetTransInitialized");
   ptr_EnumGadgets = (__vartype(ptr_EnumGadgets))GetProcAddress(hModule, "EnumGadgets");
   ptr_FindGadgetFromPoint = (__vartype(ptr_FindGadgetFromPoint))GetProcAddress(hModule, "FindGadgetFromPoint");
   ptr_FindGadgetMessages = (__vartype(ptr_FindGadgetMessages))GetProcAddress(hModule, "FindGadgetMessages");
   ptr_FindGadgetTargetingInfo = (__vartype(ptr_FindGadgetTargetingInfo))GetProcAddress(hModule, "FindGadgetTargetingInfo");
   ptr_FindStdColor = (__vartype(ptr_FindStdColor))GetProcAddress(hModule, "FindStdColor");
   ptr_FireGadgetMessages = (__vartype(ptr_FireGadgetMessages))GetProcAddress(hModule, "FireGadgetMessages");
   ptr_ForwardGadgetMessage = (__vartype(ptr_ForwardGadgetMessage))GetProcAddress(hModule, "ForwardGadgetMessage");
   ptr_GadgetTransCompositionChanged = (__vartype(ptr_GadgetTransCompositionChanged))GetProcAddress(hModule, "GadgetTransCompositionChanged");
   ptr_GadgetTransSettingChanged = (__vartype(ptr_GadgetTransSettingChanged))GetProcAddress(hModule, "GadgetTransSettingChanged");
   ptr_GetActionTimeslice = (__vartype(ptr_GetActionTimeslice))GetProcAddress(hModule, "GetActionTimeslice");
   ptr_GetCachedDWriteRenderTarget = (__vartype(ptr_GetCachedDWriteRenderTarget))GetProcAddress(hModule, "GetCachedDWriteRenderTarget");
   ptr_GetDUserModule = (__vartype(ptr_GetDUserModule))GetProcAddress(hModule, "GetDUserModule");
   ptr_GetDebug = (__vartype(ptr_GetDebug))GetProcAddress(hModule, "GetDebug");
   ptr_GetFinalAnimatingPosition = (__vartype(ptr_GetFinalAnimatingPosition))GetProcAddress(hModule, "GetFinalAnimatingPosition");
   ptr_GetGadget = (__vartype(ptr_GetGadget))GetProcAddress(hModule, "GetGadget");
   ptr_GetGadgetAnimation = (__vartype(ptr_GetGadgetAnimation))GetProcAddress(hModule, "GetGadgetAnimation");
   ptr_GetGadgetBitmap = (__vartype(ptr_GetGadgetBitmap))GetProcAddress(hModule, "GetGadgetBitmap");
   ptr_GetGadgetBufferInfo = (__vartype(ptr_GetGadgetBufferInfo))GetProcAddress(hModule, "GetGadgetBufferInfo");
   ptr_GetGadgetCenterPoint = (__vartype(ptr_GetGadgetCenterPoint))GetProcAddress(hModule, "GetGadgetCenterPoint");
   ptr_GetGadgetFlags = (__vartype(ptr_GetGadgetFlags))GetProcAddress(hModule, "GetGadgetFlags");
   ptr_GetGadgetFocus = (__vartype(ptr_GetGadgetFocus))GetProcAddress(hModule, "GetGadgetFocus");
   ptr_GetGadgetLayerInfo = (__vartype(ptr_GetGadgetLayerInfo))GetProcAddress(hModule, "GetGadgetLayerInfo");
   ptr_GetGadgetMessageFilter = (__vartype(ptr_GetGadgetMessageFilter))GetProcAddress(hModule, "GetGadgetMessageFilter");
   ptr_GetGadgetProperty = (__vartype(ptr_GetGadgetProperty))GetProcAddress(hModule, "GetGadgetProperty");
   ptr_GetGadgetRect = (__vartype(ptr_GetGadgetRect))GetProcAddress(hModule, "GetGadgetRect");
   ptr_GetGadgetRgn = (__vartype(ptr_GetGadgetRgn))GetProcAddress(hModule, "GetGadgetRgn");
   ptr_GetGadgetRootInfo = (__vartype(ptr_GetGadgetRootInfo))GetProcAddress(hModule, "GetGadgetRootInfo");
   ptr_GetGadgetRotation = (__vartype(ptr_GetGadgetRotation))GetProcAddress(hModule, "GetGadgetRotation");
   ptr_GetGadgetScale = (__vartype(ptr_GetGadgetScale))GetProcAddress(hModule, "GetGadgetScale");
   ptr_GetGadgetSize = (__vartype(ptr_GetGadgetSize))GetProcAddress(hModule, "GetGadgetSize");
   ptr_GetGadgetStyle = (__vartype(ptr_GetGadgetStyle))GetProcAddress(hModule, "GetGadgetStyle");
   ptr_GetGadgetTicket = (__vartype(ptr_GetGadgetTicket))GetProcAddress(hModule, "GetGadgetTicket");
   ptr_GetGadgetVisual = (__vartype(ptr_GetGadgetVisual))GetProcAddress(hModule, "GetGadgetVisual");
   ptr_GetMessageExA = (__vartype(ptr_GetMessageExA))GetProcAddress(hModule, "GetMessageExA");
   ptr_GetMessageExW = (__vartype(ptr_GetMessageExW))GetProcAddress(hModule, "GetMessageExW");
   ptr_GetStdColorBrushF = (__vartype(ptr_GetStdColorBrushF))GetProcAddress(hModule, "GetStdColorBrushF");
   ptr_GetStdColorBrushI = (__vartype(ptr_GetStdColorBrushI))GetProcAddress(hModule, "GetStdColorBrushI");
   ptr_GetStdColorF = (__vartype(ptr_GetStdColorF))GetProcAddress(hModule, "GetStdColorF");
   ptr_GetStdColorI = (__vartype(ptr_GetStdColorI))GetProcAddress(hModule, "GetStdColorI");
   ptr_GetStdColorName = (__vartype(ptr_GetStdColorName))GetProcAddress(hModule, "GetStdColorName");
   ptr_GetStdColorPenF = (__vartype(ptr_GetStdColorPenF))GetProcAddress(hModule, "GetStdColorPenF");
   ptr_GetStdColorPenI = (__vartype(ptr_GetStdColorPenI))GetProcAddress(hModule, "GetStdColorPenI");
   ptr_GetStdPalette = (__vartype(ptr_GetStdPalette))GetProcAddress(hModule, "GetStdPalette");
   ptr_InitGadgetComponent = (__vartype(ptr_InitGadgetComponent))GetProcAddress(hModule, "InitGadgetComponent");
   ptr_InitGadgets = (__vartype(ptr_InitGadgets))GetProcAddress(hModule, "InitGadgets");
   ptr_InvalidateGadget = (__vartype(ptr_InvalidateGadget))GetProcAddress(hModule, "InvalidateGadget");
   ptr_InvalidateLayeredDescendants = (__vartype(ptr_InvalidateLayeredDescendants))GetProcAddress(hModule, "InvalidateLayeredDescendants");
   ptr_IsGadgetParentChainStyle = (__vartype(ptr_IsGadgetParentChainStyle))GetProcAddress(hModule, "IsGadgetParentChainStyle");
   ptr_IsInsideContext = (__vartype(ptr_IsInsideContext))GetProcAddress(hModule, "IsInsideContext");
   ptr_IsStartDelete = (__vartype(ptr_IsStartDelete))GetProcAddress(hModule, "IsStartDelete");
   ptr_LookupGadgetTicket = (__vartype(ptr_LookupGadgetTicket))GetProcAddress(hModule, "LookupGadgetTicket");
   ptr_MapGadgetPoints = (__vartype(ptr_MapGadgetPoints))GetProcAddress(hModule, "MapGadgetPoints");
   ptr_PeekMessageExA = (__vartype(ptr_PeekMessageExA))GetProcAddress(hModule, "PeekMessageExA");
   ptr_PeekMessageExW = (__vartype(ptr_PeekMessageExW))GetProcAddress(hModule, "PeekMessageExW");
   ptr_RegisterGadgetMessage = (__vartype(ptr_RegisterGadgetMessage))GetProcAddress(hModule, "RegisterGadgetMessage");
   ptr_RegisterGadgetMessageString = (__vartype(ptr_RegisterGadgetMessageString))GetProcAddress(hModule, "RegisterGadgetMessageString");
   ptr_RegisterGadgetProperty = (__vartype(ptr_RegisterGadgetProperty))GetProcAddress(hModule, "RegisterGadgetProperty");
   ptr_ReleaseDetachedObjects = (__vartype(ptr_ReleaseDetachedObjects))GetProcAddress(hModule, "ReleaseDetachedObjects");
   ptr_ReleaseLayeredRef = (__vartype(ptr_ReleaseLayeredRef))GetProcAddress(hModule, "ReleaseLayeredRef");
   ptr_ReleaseMouseCapture = (__vartype(ptr_ReleaseMouseCapture))GetProcAddress(hModule, "ReleaseMouseCapture");
   ptr_RemoveClippingImmunityFromVisual = (__vartype(ptr_RemoveClippingImmunityFromVisual))GetProcAddress(hModule, "RemoveClippingImmunityFromVisual");
   ptr_RemoveGadgetMessageHandler = (__vartype(ptr_RemoveGadgetMessageHandler))GetProcAddress(hModule, "RemoveGadgetMessageHandler");
   ptr_RemoveGadgetProperty = (__vartype(ptr_RemoveGadgetProperty))GetProcAddress(hModule, "RemoveGadgetProperty");
   ptr_ResetDUserDevice = (__vartype(ptr_ResetDUserDevice))GetProcAddress(hModule, "ResetDUserDevice");
   ptr_ScheduleGadgetTransitions = (__vartype(ptr_ScheduleGadgetTransitions))GetProcAddress(hModule, "ScheduleGadgetTransitions");
   ptr_SetActionTimeslice = (__vartype(ptr_SetActionTimeslice))GetProcAddress(hModule, "SetActionTimeslice");
   ptr_SetAtlasingHints = (__vartype(ptr_SetAtlasingHints))GetProcAddress(hModule, "SetAtlasingHints");
   ptr_SetGadgetBufferInfo = (__vartype(ptr_SetGadgetBufferInfo))GetProcAddress(hModule, "SetGadgetBufferInfo");
   ptr_SetGadgetCenterPoint = (__vartype(ptr_SetGadgetCenterPoint))GetProcAddress(hModule, "SetGadgetCenterPoint");
   ptr_SetGadgetFillF = (__vartype(ptr_SetGadgetFillF))GetProcAddress(hModule, "SetGadgetFillF");
   ptr_SetGadgetFillI = (__vartype(ptr_SetGadgetFillI))GetProcAddress(hModule, "SetGadgetFillI");
   ptr_SetGadgetFlags = (__vartype(ptr_SetGadgetFlags))GetProcAddress(hModule, "SetGadgetFlags");
   ptr_SetGadgetFocus = (__vartype(ptr_SetGadgetFocus))GetProcAddress(hModule, "SetGadgetFocus");
   ptr_SetGadgetFocusEx = (__vartype(ptr_SetGadgetFocusEx))GetProcAddress(hModule, "SetGadgetFocusEx");
   ptr_SetGadgetLayerInfo = (__vartype(ptr_SetGadgetLayerInfo))GetProcAddress(hModule, "SetGadgetLayerInfo");
   ptr_SetGadgetMessageFilter = (__vartype(ptr_SetGadgetMessageFilter))GetProcAddress(hModule, "SetGadgetMessageFilter");
   ptr_SetGadgetOrder = (__vartype(ptr_SetGadgetOrder))GetProcAddress(hModule, "SetGadgetOrder");
   ptr_SetGadgetParent = (__vartype(ptr_SetGadgetParent))GetProcAddress(hModule, "SetGadgetParent");
   ptr_SetGadgetProperty = (__vartype(ptr_SetGadgetProperty))GetProcAddress(hModule, "SetGadgetProperty");
   ptr_SetGadgetRect = (__vartype(ptr_SetGadgetRect))GetProcAddress(hModule, "SetGadgetRect");
   ptr_SetGadgetRootInfo = (__vartype(ptr_SetGadgetRootInfo))GetProcAddress(hModule, "SetGadgetRootInfo");
   ptr_SetGadgetRotation = (__vartype(ptr_SetGadgetRotation))GetProcAddress(hModule, "SetGadgetRotation");
   ptr_SetGadgetScale = (__vartype(ptr_SetGadgetScale))GetProcAddress(hModule, "SetGadgetScale");
   ptr_SetGadgetStyle = (__vartype(ptr_SetGadgetStyle))GetProcAddress(hModule, "SetGadgetStyle");
   ptr_SetHardwareDeviceUsage = (__vartype(ptr_SetHardwareDeviceUsage))GetProcAddress(hModule, "SetHardwareDeviceUsage");
   ptr_SetMinimumDCompVersion = (__vartype(ptr_SetMinimumDCompVersion))GetProcAddress(hModule, "SetMinimumDCompVersion");
   ptr_SetRestoreCachedLayeredRefFlag = (__vartype(ptr_SetRestoreCachedLayeredRefFlag))GetProcAddress(hModule, "SetRestoreCachedLayeredRefFlag");
   ptr_SetTransitionVisualProperties = (__vartype(ptr_SetTransitionVisualProperties))GetProcAddress(hModule, "SetTransitionVisualProperties");
   ptr_SetWindowResizeFlag = (__vartype(ptr_SetWindowResizeFlag))GetProcAddress(hModule, "SetWindowResizeFlag");
   ptr_UnregisterGadgetMessage = (__vartype(ptr_UnregisterGadgetMessage))GetProcAddress(hModule, "UnregisterGadgetMessage");
   ptr_UnregisterGadgetMessageString = (__vartype(ptr_UnregisterGadgetMessageString))GetProcAddress(hModule, "UnregisterGadgetMessageString");
   ptr_UnregisterGadgetProperty = (__vartype(ptr_UnregisterGadgetProperty))GetProcAddress(hModule, "UnregisterGadgetProperty");
   ptr_UtilBuildFont = (__vartype(ptr_UtilBuildFont))GetProcAddress(hModule, "UtilBuildFont");
   ptr_UtilDrawBlendRect = (__vartype(ptr_UtilDrawBlendRect))GetProcAddress(hModule, "UtilDrawBlendRect");
   ptr_UtilDrawOutlineRect = (__vartype(ptr_UtilDrawOutlineRect))GetProcAddress(hModule, "UtilDrawOutlineRect");
   ptr_UtilGetColor = (__vartype(ptr_UtilGetColor))GetProcAddress(hModule, "UtilGetColor");
   ptr_UtilSetBackground = (__vartype(ptr_UtilSetBackground))GetProcAddress(hModule, "UtilSetBackground");
   ptr_WaitMessageEx = (__vartype(ptr_WaitMessageEx))GetProcAddress(hModule, "WaitMessageEx");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

