#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_CalculateOpenPortOrAuthAppAddrStringSize;
void *ptr_CalculateOpenPortOrAuthAppAddrStringSize = NULL;
extern void *ptr_CreateDefaultPerInterfaceIcmpRule;
void *ptr_CreateDefaultPerInterfaceIcmpRule = NULL;
extern void *ptr_CreateDefaultPerInterfaceOpenPortRule;
void *ptr_CreateDefaultPerInterfaceOpenPortRule = NULL;
extern void *ptr_DllCanUnloadNow;
void *ptr_DllCanUnloadNow = NULL;
extern void *ptr_DllGetClassObject;
void *ptr_DllGetClassObject = NULL;
extern void *ptr_DllRegisterServer;
void *ptr_DllRegisterServer = NULL;
extern void *ptr_DllUnregisterServer;
void *ptr_DllUnregisterServer = NULL;
extern void *ptr_FWAddAuthenticationSet;
void *ptr_FWAddAuthenticationSet = NULL;
extern void *ptr_FWAddConnectionSecurityRule;
void *ptr_FWAddConnectionSecurityRule = NULL;
extern void *ptr_FWAddCryptoSet;
void *ptr_FWAddCryptoSet = NULL;
extern void *ptr_FWAddFirewallRule;
void *ptr_FWAddFirewallRule = NULL;
extern void *ptr_FWAddMainModeRule;
void *ptr_FWAddMainModeRule = NULL;
extern void *ptr_FWChangeNotificationCreate;
void *ptr_FWChangeNotificationCreate = NULL;
extern void *ptr_FWChangeNotificationDestroy;
void *ptr_FWChangeNotificationDestroy = NULL;
extern void *ptr_FWChangeTransactionalState;
void *ptr_FWChangeTransactionalState = NULL;
extern void *ptr_FWClosePolicyStore;
void *ptr_FWClosePolicyStore = NULL;
extern void *ptr_FWCopyAuthenticationSet;
void *ptr_FWCopyAuthenticationSet = NULL;
extern void *ptr_FWCopyConnectionSecurityRule;
void *ptr_FWCopyConnectionSecurityRule = NULL;
extern void *ptr_FWCopyCryptoSet;
void *ptr_FWCopyCryptoSet = NULL;
extern void *ptr_FWCopyFirewallRule;
void *ptr_FWCopyFirewallRule = NULL;
extern void *ptr_FWDeleteAllAuthenticationSets;
void *ptr_FWDeleteAllAuthenticationSets = NULL;
extern void *ptr_FWDeleteAllConnectionSecurityRules;
void *ptr_FWDeleteAllConnectionSecurityRules = NULL;
extern void *ptr_FWDeleteAllCryptoSets;
void *ptr_FWDeleteAllCryptoSets = NULL;
extern void *ptr_FWDeleteAllFirewallRules;
void *ptr_FWDeleteAllFirewallRules = NULL;
extern void *ptr_FWDeleteAllMainModeRules;
void *ptr_FWDeleteAllMainModeRules = NULL;
extern void *ptr_FWDeleteAuthenticationSet;
void *ptr_FWDeleteAuthenticationSet = NULL;
extern void *ptr_FWDeleteConnectionSecurityRule;
void *ptr_FWDeleteConnectionSecurityRule = NULL;
extern void *ptr_FWDeleteCryptoSet;
void *ptr_FWDeleteCryptoSet = NULL;
extern void *ptr_FWDeleteFirewallRule;
void *ptr_FWDeleteFirewallRule = NULL;
extern void *ptr_FWDeleteMainModeRule;
void *ptr_FWDeleteMainModeRule = NULL;
extern void *ptr_FWDeletePhase1SAs;
void *ptr_FWDeletePhase1SAs = NULL;
extern void *ptr_FWDeletePhase2SAs;
void *ptr_FWDeletePhase2SAs = NULL;
extern void *ptr_FWDiagGetAppList;
void *ptr_FWDiagGetAppList = NULL;
extern void *ptr_FWEnumAdapters;
void *ptr_FWEnumAdapters = NULL;
extern void *ptr_FWEnumAuthenticationSets;
void *ptr_FWEnumAuthenticationSets = NULL;
extern void *ptr_FWEnumConnectionSecurityRules;
void *ptr_FWEnumConnectionSecurityRules = NULL;
extern void *ptr_FWEnumCryptoSets;
void *ptr_FWEnumCryptoSets = NULL;
extern void *ptr_FWEnumFirewallRules;
void *ptr_FWEnumFirewallRules = NULL;
extern void *ptr_FWEnumMainModeRules;
void *ptr_FWEnumMainModeRules = NULL;
extern void *ptr_FWEnumNetworks;
void *ptr_FWEnumNetworks = NULL;
extern void *ptr_FWEnumPhase1SAs;
void *ptr_FWEnumPhase1SAs = NULL;
extern void *ptr_FWEnumPhase2SAs;
void *ptr_FWEnumPhase2SAs = NULL;
extern void *ptr_FWEnumProducts;
void *ptr_FWEnumProducts = NULL;
extern void *ptr_FWExportPolicy;
void *ptr_FWExportPolicy = NULL;
extern void *ptr_FWFreeAdapters;
void *ptr_FWFreeAdapters = NULL;
extern void *ptr_FWFreeAuthenticationSet;
void *ptr_FWFreeAuthenticationSet = NULL;
extern void *ptr_FWFreeAuthenticationSets;
void *ptr_FWFreeAuthenticationSets = NULL;
extern void *ptr_FWFreeConnectionSecurityRule;
void *ptr_FWFreeConnectionSecurityRule = NULL;
extern void *ptr_FWFreeConnectionSecurityRules;
void *ptr_FWFreeConnectionSecurityRules = NULL;
extern void *ptr_FWFreeCryptoSet;
void *ptr_FWFreeCryptoSet = NULL;
extern void *ptr_FWFreeCryptoSets;
void *ptr_FWFreeCryptoSets = NULL;
extern void *ptr_FWFreeDiagAppList;
void *ptr_FWFreeDiagAppList = NULL;
extern void *ptr_FWFreeFirewallRule;
void *ptr_FWFreeFirewallRule = NULL;
extern void *ptr_FWFreeFirewallRules;
void *ptr_FWFreeFirewallRules = NULL;
extern void *ptr_FWFreeFirewallRulesOld;
void *ptr_FWFreeFirewallRulesOld = NULL;
extern void *ptr_FWFreeMainModeRule;
void *ptr_FWFreeMainModeRule = NULL;
extern void *ptr_FWFreeMainModeRules;
void *ptr_FWFreeMainModeRules = NULL;
extern void *ptr_FWFreeNetworks;
void *ptr_FWFreeNetworks = NULL;
extern void *ptr_FWFreePhase1SAs;
void *ptr_FWFreePhase1SAs = NULL;
extern void *ptr_FWFreePhase2SAs;
void *ptr_FWFreePhase2SAs = NULL;
extern void *ptr_FWFreeProducts;
void *ptr_FWFreeProducts = NULL;
extern void *ptr_FWGPLock;
void *ptr_FWGPLock = NULL;
extern void *ptr_FWGPUnlock;
void *ptr_FWGPUnlock = NULL;
extern void *ptr_FWGetConfig;
void *ptr_FWGetConfig = NULL;
extern void *ptr_FWGetConfig2;
void *ptr_FWGetConfig2 = NULL;
extern void *ptr_FWGetGlobalConfig;
void *ptr_FWGetGlobalConfig = NULL;
extern void *ptr_FWGetGlobalConfig2;
void *ptr_FWGetGlobalConfig2 = NULL;
extern void *ptr_FWGetIndicatedPortInUse;
void *ptr_FWGetIndicatedPortInUse = NULL;
extern void *ptr_FWImportPolicy;
void *ptr_FWImportPolicy = NULL;
extern void *ptr_FWIndicatePortInUse;
void *ptr_FWIndicatePortInUse = NULL;
extern void *ptr_FWOpenPolicyStore;
void *ptr_FWOpenPolicyStore = NULL;
extern void *ptr_FWQueryAuthenticationSets;
void *ptr_FWQueryAuthenticationSets = NULL;
extern void *ptr_FWQueryConnectionSecurityRules;
void *ptr_FWQueryConnectionSecurityRules = NULL;
extern void *ptr_FWQueryCryptoSets;
void *ptr_FWQueryCryptoSets = NULL;
extern void *ptr_FWQueryFirewallRules;
void *ptr_FWQueryFirewallRules = NULL;
extern void *ptr_FWQueryMainModeRules;
void *ptr_FWQueryMainModeRules = NULL;
extern void *ptr_FWRegisterProduct;
void *ptr_FWRegisterProduct = NULL;
extern void *ptr_FWResetIndicatedPortInUse;
void *ptr_FWResetIndicatedPortInUse = NULL;
extern void *ptr_FWResolveGPONames;
void *ptr_FWResolveGPONames = NULL;
extern void *ptr_FWRestoreDefaults;
void *ptr_FWRestoreDefaults = NULL;
extern void *ptr_FWRestoreGPODefaults;
void *ptr_FWRestoreGPODefaults = NULL;
extern void *ptr_FWRevertTransaction;
void *ptr_FWRevertTransaction = NULL;
extern void *ptr_FWSetAuthenticationSet;
void *ptr_FWSetAuthenticationSet = NULL;
extern void *ptr_FWSetConfig;
void *ptr_FWSetConfig = NULL;
extern void *ptr_FWSetConnectionSecurityRule;
void *ptr_FWSetConnectionSecurityRule = NULL;
extern void *ptr_FWSetCryptoSet;
void *ptr_FWSetCryptoSet = NULL;
extern void *ptr_FWSetFirewallRule;
void *ptr_FWSetFirewallRule = NULL;
extern void *ptr_FWSetGPHelperFnPtrs;
void *ptr_FWSetGPHelperFnPtrs = NULL;
extern void *ptr_FWSetGlobalConfig;
void *ptr_FWSetGlobalConfig = NULL;
extern void *ptr_FWSetMainModeRule;
void *ptr_FWSetMainModeRule = NULL;
extern void *ptr_FWStatusMessageFromStatusCode;
void *ptr_FWStatusMessageFromStatusCode = NULL;
extern void *ptr_FWUnregisterProduct;
void *ptr_FWUnregisterProduct = NULL;
extern void *ptr_FWVerifyAuthenticationSet;
void *ptr_FWVerifyAuthenticationSet = NULL;
extern void *ptr_FWVerifyAuthenticationSetQuery;
void *ptr_FWVerifyAuthenticationSetQuery = NULL;
extern void *ptr_FWVerifyConnectionSecurityRule;
void *ptr_FWVerifyConnectionSecurityRule = NULL;
extern void *ptr_FWVerifyConnectionSecurityRuleQuery;
void *ptr_FWVerifyConnectionSecurityRuleQuery = NULL;
extern void *ptr_FWVerifyCryptoSet;
void *ptr_FWVerifyCryptoSet = NULL;
extern void *ptr_FWVerifyCryptoSetQuery;
void *ptr_FWVerifyCryptoSetQuery = NULL;
extern void *ptr_FWVerifyFirewallRule;
void *ptr_FWVerifyFirewallRule = NULL;
extern void *ptr_FWVerifyFirewallRuleQuery;
void *ptr_FWVerifyFirewallRuleQuery = NULL;
extern void *ptr_FWVerifyMainModeRule;
void *ptr_FWVerifyMainModeRule = NULL;
extern void *ptr_FWVerifyMainModeRuleQuery;
void *ptr_FWVerifyMainModeRuleQuery = NULL;
extern void *ptr_FreeAbsoluteInterfaces;
void *ptr_FreeAbsoluteInterfaces = NULL;
extern void *ptr_FwActivate;
void *ptr_FwActivate = NULL;
extern void *ptr_FwAddRule;
void *ptr_FwAddRule = NULL;
extern void *ptr_FwAddSet;
void *ptr_FwAddSet = NULL;
extern void *ptr_FwAddrChangeSourceInitialize;
void *ptr_FwAddrChangeSourceInitialize = NULL;
extern void *ptr_FwAddrChangeSourceShutdown;
void *ptr_FwAddrChangeSourceShutdown = NULL;
extern void *ptr_FwAddrChangeSourceSignal;
void *ptr_FwAddrChangeSourceSignal = NULL;
extern void *ptr_FwAdvPolicyDecodeFirewallRule;
void *ptr_FwAdvPolicyDecodeFirewallRule = NULL;
extern void *ptr_FwAdvPolicyEncodeRule;
void *ptr_FwAdvPolicyEncodeRule = NULL;
extern void *ptr_FwAlloc;
void *ptr_FwAlloc = NULL;
extern void *ptr_FwAllocCheckSize;
void *ptr_FwAllocCheckSize = NULL;
extern void *ptr_FwAnalyzeFirewallPolicy;
void *ptr_FwAnalyzeFirewallPolicy = NULL;
extern void *ptr_FwAnalyzeFirewallPolicyOnProfile;
void *ptr_FwAnalyzeFirewallPolicyOnProfile = NULL;
extern void *ptr_FwBstrToPorts;
void *ptr_FwBstrToPorts = NULL;
extern void *ptr_FwCSRuleEmpty;
void *ptr_FwCSRuleEmpty = NULL;
extern void *ptr_FwCSRuleVerify;
void *ptr_FwCSRuleVerify = NULL;
extern void *ptr_FwChangeSourceInitialize;
void *ptr_FwChangeSourceInitialize = NULL;
extern void *ptr_FwChangeSourceShutdown;
void *ptr_FwChangeSourceShutdown = NULL;
extern void *ptr_FwChangeSourceSignal;
void *ptr_FwChangeSourceSignal = NULL;
extern void *ptr_FwChangeSourceSignalStart;
void *ptr_FwChangeSourceSignalStart = NULL;
extern void *ptr_FwClosePolicyStore;
void *ptr_FwClosePolicyStore = NULL;
extern void *ptr_FwCopyAuthSet;
void *ptr_FwCopyAuthSet = NULL;
extern void *ptr_FwCopyCSRule;
void *ptr_FwCopyCSRule = NULL;
extern void *ptr_FwCopyCryptoSet;
void *ptr_FwCopyCryptoSet = NULL;
extern void *ptr_FwCopyICMPTypeCode;
void *ptr_FwCopyICMPTypeCode = NULL;
extern void *ptr_FwCopyLUID;
void *ptr_FwCopyLUID = NULL;
extern void *ptr_FwCopyMMRule;
void *ptr_FwCopyMMRule = NULL;
extern void *ptr_FwCopyMainModeRule;
void *ptr_FwCopyMainModeRule = NULL;
extern void *ptr_FwCopyPlatform;
void *ptr_FwCopyPlatform = NULL;
extern void *ptr_FwCopyPortRange;
void *ptr_FwCopyPortRange = NULL;
extern void *ptr_FwCopyPortsContents;
void *ptr_FwCopyPortsContents = NULL;
extern void *ptr_FwCopyRule;
void *ptr_FwCopyRule = NULL;
extern void *ptr_FwCopyWFAddressesContents;
void *ptr_FwCopyWFAddressesContents = NULL;
extern void *ptr_FwCreateLocalTempStore;
void *ptr_FwCreateLocalTempStore = NULL;
extern void *ptr_FwDeleteAllRules;
void *ptr_FwDeleteAllRules = NULL;
extern void *ptr_FwDeleteAllSets;
void *ptr_FwDeleteAllSets = NULL;
extern void *ptr_FwDeleteRule;
void *ptr_FwDeleteRule = NULL;
extern void *ptr_FwDeleteSet;
void *ptr_FwDeleteSet = NULL;
extern void *ptr_FwDestroyLocalTempStore;
void *ptr_FwDestroyLocalTempStore = NULL;
extern void *ptr_FwDoNothingOnObject;
void *ptr_FwDoNothingOnObject = NULL;
extern void *ptr_FwEmptyWFAddresses;
void *ptr_FwEmptyWFAddresses = NULL;
extern void *ptr_FwEmptyWFRule;
void *ptr_FwEmptyWFRule = NULL;
extern void *ptr_FwEnableMemTracing;
void *ptr_FwEnableMemTracing = NULL;
extern void *ptr_FwEnumRules;
void *ptr_FwEnumRules = NULL;
extern void *ptr_FwEnumSets;
void *ptr_FwEnumSets = NULL;
extern void *ptr_FwFree;
void *ptr_FwFree = NULL;
extern void *ptr_FwFreeAddresses;
void *ptr_FwFreeAddresses = NULL;
extern void *ptr_FwFreeRules;
void *ptr_FwFreeRules = NULL;
extern void *ptr_FwFreeSets;
void *ptr_FwFreeSets = NULL;
extern void *ptr_FwFreeWFRule;
void *ptr_FwFreeWFRule = NULL;
extern void *ptr_FwGetAddressesAsString;
void *ptr_FwGetAddressesAsString = NULL;
extern void *ptr_FwGetConfig;
void *ptr_FwGetConfig = NULL;
extern void *ptr_FwGetCurrentProfile;
void *ptr_FwGetCurrentProfile = NULL;
extern void *ptr_FwGetGlobalConfig;
void *ptr_FwGetGlobalConfig = NULL;
extern void *ptr_FwGetGlobalConfigFromLocalTempStore;
void *ptr_FwGetGlobalConfigFromLocalTempStore = NULL;
extern void *ptr_FwGetVersionField;
void *ptr_FwGetVersionField = NULL;
extern void *ptr_FwICFProfileToWfProfile;
void *ptr_FwICFProfileToWfProfile = NULL;
extern void *ptr_FwICFProtocolToWfProtocol;
void *ptr_FwICFProtocolToWfProtocol = NULL;
extern void *ptr_FwIPV4RangeContainsMulticast;
void *ptr_FwIPV4RangeContainsMulticast = NULL;
extern void *ptr_FwIPV6RangeContainsMulticast;
void *ptr_FwIPV6RangeContainsMulticast = NULL;
extern void *ptr_FwIsGroupPolicyEnforced;
void *ptr_FwIsGroupPolicyEnforced = NULL;
extern void *ptr_FwIsRemoteManagementEnabled;
void *ptr_FwIsRemoteManagementEnabled = NULL;
extern void *ptr_FwMMRuleVerify;
void *ptr_FwMMRuleVerify = NULL;
extern void *ptr_FwMigrateLegacyAuthenticatedBypassSddl;
void *ptr_FwMigrateLegacyAuthenticatedBypassSddl = NULL;
extern void *ptr_FwMigrateLegacySettings;
void *ptr_FwMigrateLegacySettings = NULL;
extern void *ptr_FwOpenPolicyStore;
void *ptr_FwOpenPolicyStore = NULL;
extern void *ptr_FwParseAddressToken;
void *ptr_FwParseAddressToken = NULL;
extern void *ptr_FwPortsToBstr;
void *ptr_FwPortsToBstr = NULL;
extern void *ptr_FwReduceObjectsToVersion;
void *ptr_FwReduceObjectsToVersion = NULL;
extern void *ptr_FwResolveIndirectString;
void *ptr_FwResolveIndirectString = NULL;
extern void *ptr_FwRuleResolveFlags;
void *ptr_FwRuleResolveFlags = NULL;
extern void *ptr_FwSddlStringVerify;
void *ptr_FwSddlStringVerify = NULL;
extern void *ptr_FwSetConfig;
void *ptr_FwSetConfig = NULL;
extern void *ptr_FwSetGlobalConfig;
void *ptr_FwSetGlobalConfig = NULL;
extern void *ptr_FwSetMemLeakPolicy;
void *ptr_FwSetMemLeakPolicy = NULL;
extern void *ptr_FwSetResolveFlags;
void *ptr_FwSetResolveFlags = NULL;
extern void *ptr_FwSetRule;
void *ptr_FwSetRule = NULL;
extern void *ptr_FwSetSet;
void *ptr_FwSetSet = NULL;
extern void *ptr_FwStringToAddresses;
void *ptr_FwStringToAddresses = NULL;
extern void *ptr_FwUniteWFAddressesContents;
void *ptr_FwUniteWFAddressesContents = NULL;
extern void *ptr_FwVerifyNoHeapLeaks;
void *ptr_FwVerifyNoHeapLeaks = NULL;
extern void *ptr_FwVerifyWFRuleSemantics;
void *ptr_FwVerifyWFRuleSemantics = NULL;
extern void *ptr_FwWfProtocolToICFProtocol;
void *ptr_FwWfProtocolToICFProtocol = NULL;
extern void *ptr_GetDisabledInterfaces;
void *ptr_GetDisabledInterfaces = NULL;
extern void *ptr_GetOpenPortOrAuthAppAddrScope;
void *ptr_GetOpenPortOrAuthAppAddrScope = NULL;
extern void *ptr_IcfAddrChangeNotificationCreate;
void *ptr_IcfAddrChangeNotificationCreate = NULL;
extern void *ptr_IcfChangeNotificationCreate;
void *ptr_IcfChangeNotificationCreate = NULL;
extern void *ptr_IcfChangeNotificationDestroy;
void *ptr_IcfChangeNotificationDestroy = NULL;
extern void *ptr_IcfConnect;
void *ptr_IcfConnect = NULL;
extern void *ptr_IcfDisconnect;
void *ptr_IcfDisconnect = NULL;
extern void *ptr_IcfFreeDynamicFwPorts;
void *ptr_IcfFreeDynamicFwPorts = NULL;
extern void *ptr_IcfFreeProfile;
void *ptr_IcfFreeProfile = NULL;
extern void *ptr_IcfFreeTickets;
void *ptr_IcfFreeTickets = NULL;
extern void *ptr_IcfGetCurrentProfileType;
void *ptr_IcfGetCurrentProfileType = NULL;
extern void *ptr_IcfGetDynamicFwPorts;
void *ptr_IcfGetDynamicFwPorts = NULL;
extern void *ptr_IcfGetOperationalMode;
void *ptr_IcfGetOperationalMode = NULL;
extern void *ptr_IcfGetProfile;
void *ptr_IcfGetProfile = NULL;
extern void *ptr_IcfGetTickets;
void *ptr_IcfGetTickets = NULL;
extern void *ptr_IcfIsPortAllowed;
void *ptr_IcfIsPortAllowed = NULL;
extern void *ptr_IcfOpenDynamicFwPortWithoutSocket;
void *ptr_IcfOpenDynamicFwPortWithoutSocket = NULL;
extern void *ptr_IcfSubNetsGetScope;
void *ptr_IcfSubNetsGetScope = NULL;
extern void *ptr_IsAddressesEmpty;
void *ptr_IsAddressesEmpty = NULL;
extern void *ptr_IsFirewallInCoExistanceMode;
void *ptr_IsFirewallInCoExistanceMode = NULL;
extern void *ptr_IsPortOrICMPAllowed;
void *ptr_IsPortOrICMPAllowed = NULL;
extern void *ptr_IsPortsEmpty;
void *ptr_IsPortsEmpty = NULL;
extern void *ptr_IsRuleOldAuthApp;
void *ptr_IsRuleOldAuthApp = NULL;
extern void *ptr_IsRuleOldGlobalOpenPort;
void *ptr_IsRuleOldGlobalOpenPort = NULL;
extern void *ptr_IsRuleOpenPortOrAuthApp;
void *ptr_IsRuleOpenPortOrAuthApp = NULL;
extern void *ptr_IsRulePerInterfaceIcmp;
void *ptr_IsRulePerInterfaceIcmp = NULL;
extern void *ptr_IsRulePerInterfaceOpenPort;
void *ptr_IsRulePerInterfaceOpenPort = NULL;
extern void *ptr_Isv4Orv6AddressesEmpty;
void *ptr_Isv4Orv6AddressesEmpty = NULL;
extern void *ptr_LoadGPExtensionDll;
void *ptr_LoadGPExtensionDll = NULL;
extern void *ptr_MakeAbsoluteInterfaces;
void *ptr_MakeAbsoluteInterfaces = NULL;
extern void *ptr_OpenPortOrAuthAppAddrToString;
void *ptr_OpenPortOrAuthAppAddrToString = NULL;
extern void *ptr_ValidatePortOrAppAddressString;
void *ptr_ValidatePortOrAppAddressString = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\FirewallAPI.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_CalculateOpenPortOrAuthAppAddrStringSize = (__vartype(ptr_CalculateOpenPortOrAuthAppAddrStringSize))GetProcAddress(hModule, "CalculateOpenPortOrAuthAppAddrStringSize");
   ptr_CreateDefaultPerInterfaceIcmpRule = (__vartype(ptr_CreateDefaultPerInterfaceIcmpRule))GetProcAddress(hModule, "CreateDefaultPerInterfaceIcmpRule");
   ptr_CreateDefaultPerInterfaceOpenPortRule = (__vartype(ptr_CreateDefaultPerInterfaceOpenPortRule))GetProcAddress(hModule, "CreateDefaultPerInterfaceOpenPortRule");
   ptr_DllCanUnloadNow = (__vartype(ptr_DllCanUnloadNow))GetProcAddress(hModule, "DllCanUnloadNow");
   ptr_DllGetClassObject = (__vartype(ptr_DllGetClassObject))GetProcAddress(hModule, "DllGetClassObject");
   ptr_DllRegisterServer = (__vartype(ptr_DllRegisterServer))GetProcAddress(hModule, "DllRegisterServer");
   ptr_DllUnregisterServer = (__vartype(ptr_DllUnregisterServer))GetProcAddress(hModule, "DllUnregisterServer");
   ptr_FWAddAuthenticationSet = (__vartype(ptr_FWAddAuthenticationSet))GetProcAddress(hModule, "FWAddAuthenticationSet");
   ptr_FWAddConnectionSecurityRule = (__vartype(ptr_FWAddConnectionSecurityRule))GetProcAddress(hModule, "FWAddConnectionSecurityRule");
   ptr_FWAddCryptoSet = (__vartype(ptr_FWAddCryptoSet))GetProcAddress(hModule, "FWAddCryptoSet");
   ptr_FWAddFirewallRule = (__vartype(ptr_FWAddFirewallRule))GetProcAddress(hModule, "FWAddFirewallRule");
   ptr_FWAddMainModeRule = (__vartype(ptr_FWAddMainModeRule))GetProcAddress(hModule, "FWAddMainModeRule");
   ptr_FWChangeNotificationCreate = (__vartype(ptr_FWChangeNotificationCreate))GetProcAddress(hModule, "FWChangeNotificationCreate");
   ptr_FWChangeNotificationDestroy = (__vartype(ptr_FWChangeNotificationDestroy))GetProcAddress(hModule, "FWChangeNotificationDestroy");
   ptr_FWChangeTransactionalState = (__vartype(ptr_FWChangeTransactionalState))GetProcAddress(hModule, "FWChangeTransactionalState");
   ptr_FWClosePolicyStore = (__vartype(ptr_FWClosePolicyStore))GetProcAddress(hModule, "FWClosePolicyStore");
   ptr_FWCopyAuthenticationSet = (__vartype(ptr_FWCopyAuthenticationSet))GetProcAddress(hModule, "FWCopyAuthenticationSet");
   ptr_FWCopyConnectionSecurityRule = (__vartype(ptr_FWCopyConnectionSecurityRule))GetProcAddress(hModule, "FWCopyConnectionSecurityRule");
   ptr_FWCopyCryptoSet = (__vartype(ptr_FWCopyCryptoSet))GetProcAddress(hModule, "FWCopyCryptoSet");
   ptr_FWCopyFirewallRule = (__vartype(ptr_FWCopyFirewallRule))GetProcAddress(hModule, "FWCopyFirewallRule");
   ptr_FWDeleteAllAuthenticationSets = (__vartype(ptr_FWDeleteAllAuthenticationSets))GetProcAddress(hModule, "FWDeleteAllAuthenticationSets");
   ptr_FWDeleteAllConnectionSecurityRules = (__vartype(ptr_FWDeleteAllConnectionSecurityRules))GetProcAddress(hModule, "FWDeleteAllConnectionSecurityRules");
   ptr_FWDeleteAllCryptoSets = (__vartype(ptr_FWDeleteAllCryptoSets))GetProcAddress(hModule, "FWDeleteAllCryptoSets");
   ptr_FWDeleteAllFirewallRules = (__vartype(ptr_FWDeleteAllFirewallRules))GetProcAddress(hModule, "FWDeleteAllFirewallRules");
   ptr_FWDeleteAllMainModeRules = (__vartype(ptr_FWDeleteAllMainModeRules))GetProcAddress(hModule, "FWDeleteAllMainModeRules");
   ptr_FWDeleteAuthenticationSet = (__vartype(ptr_FWDeleteAuthenticationSet))GetProcAddress(hModule, "FWDeleteAuthenticationSet");
   ptr_FWDeleteConnectionSecurityRule = (__vartype(ptr_FWDeleteConnectionSecurityRule))GetProcAddress(hModule, "FWDeleteConnectionSecurityRule");
   ptr_FWDeleteCryptoSet = (__vartype(ptr_FWDeleteCryptoSet))GetProcAddress(hModule, "FWDeleteCryptoSet");
   ptr_FWDeleteFirewallRule = (__vartype(ptr_FWDeleteFirewallRule))GetProcAddress(hModule, "FWDeleteFirewallRule");
   ptr_FWDeleteMainModeRule = (__vartype(ptr_FWDeleteMainModeRule))GetProcAddress(hModule, "FWDeleteMainModeRule");
   ptr_FWDeletePhase1SAs = (__vartype(ptr_FWDeletePhase1SAs))GetProcAddress(hModule, "FWDeletePhase1SAs");
   ptr_FWDeletePhase2SAs = (__vartype(ptr_FWDeletePhase2SAs))GetProcAddress(hModule, "FWDeletePhase2SAs");
   ptr_FWDiagGetAppList = (__vartype(ptr_FWDiagGetAppList))GetProcAddress(hModule, "FWDiagGetAppList");
   ptr_FWEnumAdapters = (__vartype(ptr_FWEnumAdapters))GetProcAddress(hModule, "FWEnumAdapters");
   ptr_FWEnumAuthenticationSets = (__vartype(ptr_FWEnumAuthenticationSets))GetProcAddress(hModule, "FWEnumAuthenticationSets");
   ptr_FWEnumConnectionSecurityRules = (__vartype(ptr_FWEnumConnectionSecurityRules))GetProcAddress(hModule, "FWEnumConnectionSecurityRules");
   ptr_FWEnumCryptoSets = (__vartype(ptr_FWEnumCryptoSets))GetProcAddress(hModule, "FWEnumCryptoSets");
   ptr_FWEnumFirewallRules = (__vartype(ptr_FWEnumFirewallRules))GetProcAddress(hModule, "FWEnumFirewallRules");
   ptr_FWEnumMainModeRules = (__vartype(ptr_FWEnumMainModeRules))GetProcAddress(hModule, "FWEnumMainModeRules");
   ptr_FWEnumNetworks = (__vartype(ptr_FWEnumNetworks))GetProcAddress(hModule, "FWEnumNetworks");
   ptr_FWEnumPhase1SAs = (__vartype(ptr_FWEnumPhase1SAs))GetProcAddress(hModule, "FWEnumPhase1SAs");
   ptr_FWEnumPhase2SAs = (__vartype(ptr_FWEnumPhase2SAs))GetProcAddress(hModule, "FWEnumPhase2SAs");
   ptr_FWEnumProducts = (__vartype(ptr_FWEnumProducts))GetProcAddress(hModule, "FWEnumProducts");
   ptr_FWExportPolicy = (__vartype(ptr_FWExportPolicy))GetProcAddress(hModule, "FWExportPolicy");
   ptr_FWFreeAdapters = (__vartype(ptr_FWFreeAdapters))GetProcAddress(hModule, "FWFreeAdapters");
   ptr_FWFreeAuthenticationSet = (__vartype(ptr_FWFreeAuthenticationSet))GetProcAddress(hModule, "FWFreeAuthenticationSet");
   ptr_FWFreeAuthenticationSets = (__vartype(ptr_FWFreeAuthenticationSets))GetProcAddress(hModule, "FWFreeAuthenticationSets");
   ptr_FWFreeConnectionSecurityRule = (__vartype(ptr_FWFreeConnectionSecurityRule))GetProcAddress(hModule, "FWFreeConnectionSecurityRule");
   ptr_FWFreeConnectionSecurityRules = (__vartype(ptr_FWFreeConnectionSecurityRules))GetProcAddress(hModule, "FWFreeConnectionSecurityRules");
   ptr_FWFreeCryptoSet = (__vartype(ptr_FWFreeCryptoSet))GetProcAddress(hModule, "FWFreeCryptoSet");
   ptr_FWFreeCryptoSets = (__vartype(ptr_FWFreeCryptoSets))GetProcAddress(hModule, "FWFreeCryptoSets");
   ptr_FWFreeDiagAppList = (__vartype(ptr_FWFreeDiagAppList))GetProcAddress(hModule, "FWFreeDiagAppList");
   ptr_FWFreeFirewallRule = (__vartype(ptr_FWFreeFirewallRule))GetProcAddress(hModule, "FWFreeFirewallRule");
   ptr_FWFreeFirewallRules = (__vartype(ptr_FWFreeFirewallRules))GetProcAddress(hModule, "FWFreeFirewallRules");
   ptr_FWFreeFirewallRulesOld = (__vartype(ptr_FWFreeFirewallRulesOld))GetProcAddress(hModule, "FWFreeFirewallRulesOld");
   ptr_FWFreeMainModeRule = (__vartype(ptr_FWFreeMainModeRule))GetProcAddress(hModule, "FWFreeMainModeRule");
   ptr_FWFreeMainModeRules = (__vartype(ptr_FWFreeMainModeRules))GetProcAddress(hModule, "FWFreeMainModeRules");
   ptr_FWFreeNetworks = (__vartype(ptr_FWFreeNetworks))GetProcAddress(hModule, "FWFreeNetworks");
   ptr_FWFreePhase1SAs = (__vartype(ptr_FWFreePhase1SAs))GetProcAddress(hModule, "FWFreePhase1SAs");
   ptr_FWFreePhase2SAs = (__vartype(ptr_FWFreePhase2SAs))GetProcAddress(hModule, "FWFreePhase2SAs");
   ptr_FWFreeProducts = (__vartype(ptr_FWFreeProducts))GetProcAddress(hModule, "FWFreeProducts");
   ptr_FWGPLock = (__vartype(ptr_FWGPLock))GetProcAddress(hModule, "FWGPLock");
   ptr_FWGPUnlock = (__vartype(ptr_FWGPUnlock))GetProcAddress(hModule, "FWGPUnlock");
   ptr_FWGetConfig = (__vartype(ptr_FWGetConfig))GetProcAddress(hModule, "FWGetConfig");
   ptr_FWGetConfig2 = (__vartype(ptr_FWGetConfig2))GetProcAddress(hModule, "FWGetConfig2");
   ptr_FWGetGlobalConfig = (__vartype(ptr_FWGetGlobalConfig))GetProcAddress(hModule, "FWGetGlobalConfig");
   ptr_FWGetGlobalConfig2 = (__vartype(ptr_FWGetGlobalConfig2))GetProcAddress(hModule, "FWGetGlobalConfig2");
   ptr_FWGetIndicatedPortInUse = (__vartype(ptr_FWGetIndicatedPortInUse))GetProcAddress(hModule, "FWGetIndicatedPortInUse");
   ptr_FWImportPolicy = (__vartype(ptr_FWImportPolicy))GetProcAddress(hModule, "FWImportPolicy");
   ptr_FWIndicatePortInUse = (__vartype(ptr_FWIndicatePortInUse))GetProcAddress(hModule, "FWIndicatePortInUse");
   ptr_FWOpenPolicyStore = (__vartype(ptr_FWOpenPolicyStore))GetProcAddress(hModule, "FWOpenPolicyStore");
   ptr_FWQueryAuthenticationSets = (__vartype(ptr_FWQueryAuthenticationSets))GetProcAddress(hModule, "FWQueryAuthenticationSets");
   ptr_FWQueryConnectionSecurityRules = (__vartype(ptr_FWQueryConnectionSecurityRules))GetProcAddress(hModule, "FWQueryConnectionSecurityRules");
   ptr_FWQueryCryptoSets = (__vartype(ptr_FWQueryCryptoSets))GetProcAddress(hModule, "FWQueryCryptoSets");
   ptr_FWQueryFirewallRules = (__vartype(ptr_FWQueryFirewallRules))GetProcAddress(hModule, "FWQueryFirewallRules");
   ptr_FWQueryMainModeRules = (__vartype(ptr_FWQueryMainModeRules))GetProcAddress(hModule, "FWQueryMainModeRules");
   ptr_FWRegisterProduct = (__vartype(ptr_FWRegisterProduct))GetProcAddress(hModule, "FWRegisterProduct");
   ptr_FWResetIndicatedPortInUse = (__vartype(ptr_FWResetIndicatedPortInUse))GetProcAddress(hModule, "FWResetIndicatedPortInUse");
   ptr_FWResolveGPONames = (__vartype(ptr_FWResolveGPONames))GetProcAddress(hModule, "FWResolveGPONames");
   ptr_FWRestoreDefaults = (__vartype(ptr_FWRestoreDefaults))GetProcAddress(hModule, "FWRestoreDefaults");
   ptr_FWRestoreGPODefaults = (__vartype(ptr_FWRestoreGPODefaults))GetProcAddress(hModule, "FWRestoreGPODefaults");
   ptr_FWRevertTransaction = (__vartype(ptr_FWRevertTransaction))GetProcAddress(hModule, "FWRevertTransaction");
   ptr_FWSetAuthenticationSet = (__vartype(ptr_FWSetAuthenticationSet))GetProcAddress(hModule, "FWSetAuthenticationSet");
   ptr_FWSetConfig = (__vartype(ptr_FWSetConfig))GetProcAddress(hModule, "FWSetConfig");
   ptr_FWSetConnectionSecurityRule = (__vartype(ptr_FWSetConnectionSecurityRule))GetProcAddress(hModule, "FWSetConnectionSecurityRule");
   ptr_FWSetCryptoSet = (__vartype(ptr_FWSetCryptoSet))GetProcAddress(hModule, "FWSetCryptoSet");
   ptr_FWSetFirewallRule = (__vartype(ptr_FWSetFirewallRule))GetProcAddress(hModule, "FWSetFirewallRule");
   ptr_FWSetGPHelperFnPtrs = (__vartype(ptr_FWSetGPHelperFnPtrs))GetProcAddress(hModule, "FWSetGPHelperFnPtrs");
   ptr_FWSetGlobalConfig = (__vartype(ptr_FWSetGlobalConfig))GetProcAddress(hModule, "FWSetGlobalConfig");
   ptr_FWSetMainModeRule = (__vartype(ptr_FWSetMainModeRule))GetProcAddress(hModule, "FWSetMainModeRule");
   ptr_FWStatusMessageFromStatusCode = (__vartype(ptr_FWStatusMessageFromStatusCode))GetProcAddress(hModule, "FWStatusMessageFromStatusCode");
   ptr_FWUnregisterProduct = (__vartype(ptr_FWUnregisterProduct))GetProcAddress(hModule, "FWUnregisterProduct");
   ptr_FWVerifyAuthenticationSet = (__vartype(ptr_FWVerifyAuthenticationSet))GetProcAddress(hModule, "FWVerifyAuthenticationSet");
   ptr_FWVerifyAuthenticationSetQuery = (__vartype(ptr_FWVerifyAuthenticationSetQuery))GetProcAddress(hModule, "FWVerifyAuthenticationSetQuery");
   ptr_FWVerifyConnectionSecurityRule = (__vartype(ptr_FWVerifyConnectionSecurityRule))GetProcAddress(hModule, "FWVerifyConnectionSecurityRule");
   ptr_FWVerifyConnectionSecurityRuleQuery = (__vartype(ptr_FWVerifyConnectionSecurityRuleQuery))GetProcAddress(hModule, "FWVerifyConnectionSecurityRuleQuery");
   ptr_FWVerifyCryptoSet = (__vartype(ptr_FWVerifyCryptoSet))GetProcAddress(hModule, "FWVerifyCryptoSet");
   ptr_FWVerifyCryptoSetQuery = (__vartype(ptr_FWVerifyCryptoSetQuery))GetProcAddress(hModule, "FWVerifyCryptoSetQuery");
   ptr_FWVerifyFirewallRule = (__vartype(ptr_FWVerifyFirewallRule))GetProcAddress(hModule, "FWVerifyFirewallRule");
   ptr_FWVerifyFirewallRuleQuery = (__vartype(ptr_FWVerifyFirewallRuleQuery))GetProcAddress(hModule, "FWVerifyFirewallRuleQuery");
   ptr_FWVerifyMainModeRule = (__vartype(ptr_FWVerifyMainModeRule))GetProcAddress(hModule, "FWVerifyMainModeRule");
   ptr_FWVerifyMainModeRuleQuery = (__vartype(ptr_FWVerifyMainModeRuleQuery))GetProcAddress(hModule, "FWVerifyMainModeRuleQuery");
   ptr_FreeAbsoluteInterfaces = (__vartype(ptr_FreeAbsoluteInterfaces))GetProcAddress(hModule, "FreeAbsoluteInterfaces");
   ptr_FwActivate = (__vartype(ptr_FwActivate))GetProcAddress(hModule, "FwActivate");
   ptr_FwAddRule = (__vartype(ptr_FwAddRule))GetProcAddress(hModule, "FwAddRule");
   ptr_FwAddSet = (__vartype(ptr_FwAddSet))GetProcAddress(hModule, "FwAddSet");
   ptr_FwAddrChangeSourceInitialize = (__vartype(ptr_FwAddrChangeSourceInitialize))GetProcAddress(hModule, "FwAddrChangeSourceInitialize");
   ptr_FwAddrChangeSourceShutdown = (__vartype(ptr_FwAddrChangeSourceShutdown))GetProcAddress(hModule, "FwAddrChangeSourceShutdown");
   ptr_FwAddrChangeSourceSignal = (__vartype(ptr_FwAddrChangeSourceSignal))GetProcAddress(hModule, "FwAddrChangeSourceSignal");
   ptr_FwAdvPolicyDecodeFirewallRule = (__vartype(ptr_FwAdvPolicyDecodeFirewallRule))GetProcAddress(hModule, "FwAdvPolicyDecodeFirewallRule");
   ptr_FwAdvPolicyEncodeRule = (__vartype(ptr_FwAdvPolicyEncodeRule))GetProcAddress(hModule, "FwAdvPolicyEncodeRule");
   ptr_FwAlloc = (__vartype(ptr_FwAlloc))GetProcAddress(hModule, "FwAlloc");
   ptr_FwAllocCheckSize = (__vartype(ptr_FwAllocCheckSize))GetProcAddress(hModule, "FwAllocCheckSize");
   ptr_FwAnalyzeFirewallPolicy = (__vartype(ptr_FwAnalyzeFirewallPolicy))GetProcAddress(hModule, "FwAnalyzeFirewallPolicy");
   ptr_FwAnalyzeFirewallPolicyOnProfile = (__vartype(ptr_FwAnalyzeFirewallPolicyOnProfile))GetProcAddress(hModule, "FwAnalyzeFirewallPolicyOnProfile");
   ptr_FwBstrToPorts = (__vartype(ptr_FwBstrToPorts))GetProcAddress(hModule, "FwBstrToPorts");
   ptr_FwCSRuleEmpty = (__vartype(ptr_FwCSRuleEmpty))GetProcAddress(hModule, "FwCSRuleEmpty");
   ptr_FwCSRuleVerify = (__vartype(ptr_FwCSRuleVerify))GetProcAddress(hModule, "FwCSRuleVerify");
   ptr_FwChangeSourceInitialize = (__vartype(ptr_FwChangeSourceInitialize))GetProcAddress(hModule, "FwChangeSourceInitialize");
   ptr_FwChangeSourceShutdown = (__vartype(ptr_FwChangeSourceShutdown))GetProcAddress(hModule, "FwChangeSourceShutdown");
   ptr_FwChangeSourceSignal = (__vartype(ptr_FwChangeSourceSignal))GetProcAddress(hModule, "FwChangeSourceSignal");
   ptr_FwChangeSourceSignalStart = (__vartype(ptr_FwChangeSourceSignalStart))GetProcAddress(hModule, "FwChangeSourceSignalStart");
   ptr_FwClosePolicyStore = (__vartype(ptr_FwClosePolicyStore))GetProcAddress(hModule, "FwClosePolicyStore");
   ptr_FwCopyAuthSet = (__vartype(ptr_FwCopyAuthSet))GetProcAddress(hModule, "FwCopyAuthSet");
   ptr_FwCopyCSRule = (__vartype(ptr_FwCopyCSRule))GetProcAddress(hModule, "FwCopyCSRule");
   ptr_FwCopyCryptoSet = (__vartype(ptr_FwCopyCryptoSet))GetProcAddress(hModule, "FwCopyCryptoSet");
   ptr_FwCopyICMPTypeCode = (__vartype(ptr_FwCopyICMPTypeCode))GetProcAddress(hModule, "FwCopyICMPTypeCode");
   ptr_FwCopyLUID = (__vartype(ptr_FwCopyLUID))GetProcAddress(hModule, "FwCopyLUID");
   ptr_FwCopyMMRule = (__vartype(ptr_FwCopyMMRule))GetProcAddress(hModule, "FwCopyMMRule");
   ptr_FwCopyMainModeRule = (__vartype(ptr_FwCopyMainModeRule))GetProcAddress(hModule, "FwCopyMainModeRule");
   ptr_FwCopyPlatform = (__vartype(ptr_FwCopyPlatform))GetProcAddress(hModule, "FwCopyPlatform");
   ptr_FwCopyPortRange = (__vartype(ptr_FwCopyPortRange))GetProcAddress(hModule, "FwCopyPortRange");
   ptr_FwCopyPortsContents = (__vartype(ptr_FwCopyPortsContents))GetProcAddress(hModule, "FwCopyPortsContents");
   ptr_FwCopyRule = (__vartype(ptr_FwCopyRule))GetProcAddress(hModule, "FwCopyRule");
   ptr_FwCopyWFAddressesContents = (__vartype(ptr_FwCopyWFAddressesContents))GetProcAddress(hModule, "FwCopyWFAddressesContents");
   ptr_FwCreateLocalTempStore = (__vartype(ptr_FwCreateLocalTempStore))GetProcAddress(hModule, "FwCreateLocalTempStore");
   ptr_FwDeleteAllRules = (__vartype(ptr_FwDeleteAllRules))GetProcAddress(hModule, "FwDeleteAllRules");
   ptr_FwDeleteAllSets = (__vartype(ptr_FwDeleteAllSets))GetProcAddress(hModule, "FwDeleteAllSets");
   ptr_FwDeleteRule = (__vartype(ptr_FwDeleteRule))GetProcAddress(hModule, "FwDeleteRule");
   ptr_FwDeleteSet = (__vartype(ptr_FwDeleteSet))GetProcAddress(hModule, "FwDeleteSet");
   ptr_FwDestroyLocalTempStore = (__vartype(ptr_FwDestroyLocalTempStore))GetProcAddress(hModule, "FwDestroyLocalTempStore");
   ptr_FwDoNothingOnObject = (__vartype(ptr_FwDoNothingOnObject))GetProcAddress(hModule, "FwDoNothingOnObject");
   ptr_FwEmptyWFAddresses = (__vartype(ptr_FwEmptyWFAddresses))GetProcAddress(hModule, "FwEmptyWFAddresses");
   ptr_FwEmptyWFRule = (__vartype(ptr_FwEmptyWFRule))GetProcAddress(hModule, "FwEmptyWFRule");
   ptr_FwEnableMemTracing = (__vartype(ptr_FwEnableMemTracing))GetProcAddress(hModule, "FwEnableMemTracing");
   ptr_FwEnumRules = (__vartype(ptr_FwEnumRules))GetProcAddress(hModule, "FwEnumRules");
   ptr_FwEnumSets = (__vartype(ptr_FwEnumSets))GetProcAddress(hModule, "FwEnumSets");
   ptr_FwFree = (__vartype(ptr_FwFree))GetProcAddress(hModule, "FwFree");
   ptr_FwFreeAddresses = (__vartype(ptr_FwFreeAddresses))GetProcAddress(hModule, "FwFreeAddresses");
   ptr_FwFreeRules = (__vartype(ptr_FwFreeRules))GetProcAddress(hModule, "FwFreeRules");
   ptr_FwFreeSets = (__vartype(ptr_FwFreeSets))GetProcAddress(hModule, "FwFreeSets");
   ptr_FwFreeWFRule = (__vartype(ptr_FwFreeWFRule))GetProcAddress(hModule, "FwFreeWFRule");
   ptr_FwGetAddressesAsString = (__vartype(ptr_FwGetAddressesAsString))GetProcAddress(hModule, "FwGetAddressesAsString");
   ptr_FwGetConfig = (__vartype(ptr_FwGetConfig))GetProcAddress(hModule, "FwGetConfig");
   ptr_FwGetCurrentProfile = (__vartype(ptr_FwGetCurrentProfile))GetProcAddress(hModule, "FwGetCurrentProfile");
   ptr_FwGetGlobalConfig = (__vartype(ptr_FwGetGlobalConfig))GetProcAddress(hModule, "FwGetGlobalConfig");
   ptr_FwGetGlobalConfigFromLocalTempStore = (__vartype(ptr_FwGetGlobalConfigFromLocalTempStore))GetProcAddress(hModule, "FwGetGlobalConfigFromLocalTempStore");
   ptr_FwGetVersionField = (__vartype(ptr_FwGetVersionField))GetProcAddress(hModule, "FwGetVersionField");
   ptr_FwICFProfileToWfProfile = (__vartype(ptr_FwICFProfileToWfProfile))GetProcAddress(hModule, "FwICFProfileToWfProfile");
   ptr_FwICFProtocolToWfProtocol = (__vartype(ptr_FwICFProtocolToWfProtocol))GetProcAddress(hModule, "FwICFProtocolToWfProtocol");
   ptr_FwIPV4RangeContainsMulticast = (__vartype(ptr_FwIPV4RangeContainsMulticast))GetProcAddress(hModule, "FwIPV4RangeContainsMulticast");
   ptr_FwIPV6RangeContainsMulticast = (__vartype(ptr_FwIPV6RangeContainsMulticast))GetProcAddress(hModule, "FwIPV6RangeContainsMulticast");
   ptr_FwIsGroupPolicyEnforced = (__vartype(ptr_FwIsGroupPolicyEnforced))GetProcAddress(hModule, "FwIsGroupPolicyEnforced");
   ptr_FwIsRemoteManagementEnabled = (__vartype(ptr_FwIsRemoteManagementEnabled))GetProcAddress(hModule, "FwIsRemoteManagementEnabled");
   ptr_FwMMRuleVerify = (__vartype(ptr_FwMMRuleVerify))GetProcAddress(hModule, "FwMMRuleVerify");
   ptr_FwMigrateLegacyAuthenticatedBypassSddl = (__vartype(ptr_FwMigrateLegacyAuthenticatedBypassSddl))GetProcAddress(hModule, "FwMigrateLegacyAuthenticatedBypassSddl");
   ptr_FwMigrateLegacySettings = (__vartype(ptr_FwMigrateLegacySettings))GetProcAddress(hModule, "FwMigrateLegacySettings");
   ptr_FwOpenPolicyStore = (__vartype(ptr_FwOpenPolicyStore))GetProcAddress(hModule, "FwOpenPolicyStore");
   ptr_FwParseAddressToken = (__vartype(ptr_FwParseAddressToken))GetProcAddress(hModule, "FwParseAddressToken");
   ptr_FwPortsToBstr = (__vartype(ptr_FwPortsToBstr))GetProcAddress(hModule, "FwPortsToBstr");
   ptr_FwReduceObjectsToVersion = (__vartype(ptr_FwReduceObjectsToVersion))GetProcAddress(hModule, "FwReduceObjectsToVersion");
   ptr_FwResolveIndirectString = (__vartype(ptr_FwResolveIndirectString))GetProcAddress(hModule, "FwResolveIndirectString");
   ptr_FwRuleResolveFlags = (__vartype(ptr_FwRuleResolveFlags))GetProcAddress(hModule, "FwRuleResolveFlags");
   ptr_FwSddlStringVerify = (__vartype(ptr_FwSddlStringVerify))GetProcAddress(hModule, "FwSddlStringVerify");
   ptr_FwSetConfig = (__vartype(ptr_FwSetConfig))GetProcAddress(hModule, "FwSetConfig");
   ptr_FwSetGlobalConfig = (__vartype(ptr_FwSetGlobalConfig))GetProcAddress(hModule, "FwSetGlobalConfig");
   ptr_FwSetMemLeakPolicy = (__vartype(ptr_FwSetMemLeakPolicy))GetProcAddress(hModule, "FwSetMemLeakPolicy");
   ptr_FwSetResolveFlags = (__vartype(ptr_FwSetResolveFlags))GetProcAddress(hModule, "FwSetResolveFlags");
   ptr_FwSetRule = (__vartype(ptr_FwSetRule))GetProcAddress(hModule, "FwSetRule");
   ptr_FwSetSet = (__vartype(ptr_FwSetSet))GetProcAddress(hModule, "FwSetSet");
   ptr_FwStringToAddresses = (__vartype(ptr_FwStringToAddresses))GetProcAddress(hModule, "FwStringToAddresses");
   ptr_FwUniteWFAddressesContents = (__vartype(ptr_FwUniteWFAddressesContents))GetProcAddress(hModule, "FwUniteWFAddressesContents");
   ptr_FwVerifyNoHeapLeaks = (__vartype(ptr_FwVerifyNoHeapLeaks))GetProcAddress(hModule, "FwVerifyNoHeapLeaks");
   ptr_FwVerifyWFRuleSemantics = (__vartype(ptr_FwVerifyWFRuleSemantics))GetProcAddress(hModule, "FwVerifyWFRuleSemantics");
   ptr_FwWfProtocolToICFProtocol = (__vartype(ptr_FwWfProtocolToICFProtocol))GetProcAddress(hModule, "FwWfProtocolToICFProtocol");
   ptr_GetDisabledInterfaces = (__vartype(ptr_GetDisabledInterfaces))GetProcAddress(hModule, "GetDisabledInterfaces");
   ptr_GetOpenPortOrAuthAppAddrScope = (__vartype(ptr_GetOpenPortOrAuthAppAddrScope))GetProcAddress(hModule, "GetOpenPortOrAuthAppAddrScope");
   ptr_IcfAddrChangeNotificationCreate = (__vartype(ptr_IcfAddrChangeNotificationCreate))GetProcAddress(hModule, "IcfAddrChangeNotificationCreate");
   ptr_IcfChangeNotificationCreate = (__vartype(ptr_IcfChangeNotificationCreate))GetProcAddress(hModule, "IcfChangeNotificationCreate");
   ptr_IcfChangeNotificationDestroy = (__vartype(ptr_IcfChangeNotificationDestroy))GetProcAddress(hModule, "IcfChangeNotificationDestroy");
   ptr_IcfConnect = (__vartype(ptr_IcfConnect))GetProcAddress(hModule, "IcfConnect");
   ptr_IcfDisconnect = (__vartype(ptr_IcfDisconnect))GetProcAddress(hModule, "IcfDisconnect");
   ptr_IcfFreeDynamicFwPorts = (__vartype(ptr_IcfFreeDynamicFwPorts))GetProcAddress(hModule, "IcfFreeDynamicFwPorts");
   ptr_IcfFreeProfile = (__vartype(ptr_IcfFreeProfile))GetProcAddress(hModule, "IcfFreeProfile");
   ptr_IcfFreeTickets = (__vartype(ptr_IcfFreeTickets))GetProcAddress(hModule, "IcfFreeTickets");
   ptr_IcfGetCurrentProfileType = (__vartype(ptr_IcfGetCurrentProfileType))GetProcAddress(hModule, "IcfGetCurrentProfileType");
   ptr_IcfGetDynamicFwPorts = (__vartype(ptr_IcfGetDynamicFwPorts))GetProcAddress(hModule, "IcfGetDynamicFwPorts");
   ptr_IcfGetOperationalMode = (__vartype(ptr_IcfGetOperationalMode))GetProcAddress(hModule, "IcfGetOperationalMode");
   ptr_IcfGetProfile = (__vartype(ptr_IcfGetProfile))GetProcAddress(hModule, "IcfGetProfile");
   ptr_IcfGetTickets = (__vartype(ptr_IcfGetTickets))GetProcAddress(hModule, "IcfGetTickets");
   ptr_IcfIsPortAllowed = (__vartype(ptr_IcfIsPortAllowed))GetProcAddress(hModule, "IcfIsPortAllowed");
   ptr_IcfOpenDynamicFwPortWithoutSocket = (__vartype(ptr_IcfOpenDynamicFwPortWithoutSocket))GetProcAddress(hModule, "IcfOpenDynamicFwPortWithoutSocket");
   ptr_IcfSubNetsGetScope = (__vartype(ptr_IcfSubNetsGetScope))GetProcAddress(hModule, "IcfSubNetsGetScope");
   ptr_IsAddressesEmpty = (__vartype(ptr_IsAddressesEmpty))GetProcAddress(hModule, "IsAddressesEmpty");
   ptr_IsFirewallInCoExistanceMode = (__vartype(ptr_IsFirewallInCoExistanceMode))GetProcAddress(hModule, "IsFirewallInCoExistanceMode");
   ptr_IsPortOrICMPAllowed = (__vartype(ptr_IsPortOrICMPAllowed))GetProcAddress(hModule, "IsPortOrICMPAllowed");
   ptr_IsPortsEmpty = (__vartype(ptr_IsPortsEmpty))GetProcAddress(hModule, "IsPortsEmpty");
   ptr_IsRuleOldAuthApp = (__vartype(ptr_IsRuleOldAuthApp))GetProcAddress(hModule, "IsRuleOldAuthApp");
   ptr_IsRuleOldGlobalOpenPort = (__vartype(ptr_IsRuleOldGlobalOpenPort))GetProcAddress(hModule, "IsRuleOldGlobalOpenPort");
   ptr_IsRuleOpenPortOrAuthApp = (__vartype(ptr_IsRuleOpenPortOrAuthApp))GetProcAddress(hModule, "IsRuleOpenPortOrAuthApp");
   ptr_IsRulePerInterfaceIcmp = (__vartype(ptr_IsRulePerInterfaceIcmp))GetProcAddress(hModule, "IsRulePerInterfaceIcmp");
   ptr_IsRulePerInterfaceOpenPort = (__vartype(ptr_IsRulePerInterfaceOpenPort))GetProcAddress(hModule, "IsRulePerInterfaceOpenPort");
   ptr_Isv4Orv6AddressesEmpty = (__vartype(ptr_Isv4Orv6AddressesEmpty))GetProcAddress(hModule, "Isv4Orv6AddressesEmpty");
   ptr_LoadGPExtensionDll = (__vartype(ptr_LoadGPExtensionDll))GetProcAddress(hModule, "LoadGPExtensionDll");
   ptr_MakeAbsoluteInterfaces = (__vartype(ptr_MakeAbsoluteInterfaces))GetProcAddress(hModule, "MakeAbsoluteInterfaces");
   ptr_OpenPortOrAuthAppAddrToString = (__vartype(ptr_OpenPortOrAuthAppAddrToString))GetProcAddress(hModule, "OpenPortOrAuthAppAddrToString");
   ptr_ValidatePortOrAppAddressString = (__vartype(ptr_ValidatePortOrAppAddressString))GetProcAddress(hModule, "ValidatePortOrAppAddressString");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

