#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_AccessCheck;
void *ptr_AccessCheck = NULL;
extern void *ptr_AccessCheckAndAuditAlarmW;
void *ptr_AccessCheckAndAuditAlarmW = NULL;
extern void *ptr_AccessCheckByType;
void *ptr_AccessCheckByType = NULL;
extern void *ptr_AccessCheckByTypeAndAuditAlarmW;
void *ptr_AccessCheckByTypeAndAuditAlarmW = NULL;
extern void *ptr_AccessCheckByTypeResultList;
void *ptr_AccessCheckByTypeResultList = NULL;
extern void *ptr_AccessCheckByTypeResultListAndAuditAlarmByHandleW;
void *ptr_AccessCheckByTypeResultListAndAuditAlarmByHandleW = NULL;
extern void *ptr_AccessCheckByTypeResultListAndAuditAlarmW;
void *ptr_AccessCheckByTypeResultListAndAuditAlarmW = NULL;
extern void *ptr_AddAccessAllowedAce;
void *ptr_AddAccessAllowedAce = NULL;
extern void *ptr_AddAccessAllowedAceEx;
void *ptr_AddAccessAllowedAceEx = NULL;
extern void *ptr_AddAccessAllowedObjectAce;
void *ptr_AddAccessAllowedObjectAce = NULL;
extern void *ptr_AddAccessDeniedAce;
void *ptr_AddAccessDeniedAce = NULL;
extern void *ptr_AddAccessDeniedAceEx;
void *ptr_AddAccessDeniedAceEx = NULL;
extern void *ptr_AddAccessDeniedObjectAce;
void *ptr_AddAccessDeniedObjectAce = NULL;
extern void *ptr_AddAce;
void *ptr_AddAce = NULL;
extern void *ptr_AddAuditAccessAce;
void *ptr_AddAuditAccessAce = NULL;
extern void *ptr_AddAuditAccessAceEx;
void *ptr_AddAuditAccessAceEx = NULL;
extern void *ptr_AddAuditAccessObjectAce;
void *ptr_AddAuditAccessObjectAce = NULL;
extern void *ptr_AddMandatoryAce;
void *ptr_AddMandatoryAce = NULL;
extern void *ptr_AdjustTokenGroups;
void *ptr_AdjustTokenGroups = NULL;
extern void *ptr_AdjustTokenPrivileges;
void *ptr_AdjustTokenPrivileges = NULL;
extern void *ptr_AllocateAndInitializeSid;
void *ptr_AllocateAndInitializeSid = NULL;
extern void *ptr_AllocateLocallyUniqueId;
void *ptr_AllocateLocallyUniqueId = NULL;
extern void *ptr_AreAllAccessesGranted;
void *ptr_AreAllAccessesGranted = NULL;
extern void *ptr_AreAnyAccessesGranted;
void *ptr_AreAnyAccessesGranted = NULL;
extern void *ptr_CheckTokenMembership;
void *ptr_CheckTokenMembership = NULL;
extern void *ptr_ConvertToAutoInheritPrivateObjectSecurity;
void *ptr_ConvertToAutoInheritPrivateObjectSecurity = NULL;
extern void *ptr_CopySid;
void *ptr_CopySid = NULL;
extern void *ptr_CreatePrivateObjectSecurity;
void *ptr_CreatePrivateObjectSecurity = NULL;
extern void *ptr_CreatePrivateObjectSecurityEx;
void *ptr_CreatePrivateObjectSecurityEx = NULL;
extern void *ptr_CreatePrivateObjectSecurityWithMultipleInheritance;
void *ptr_CreatePrivateObjectSecurityWithMultipleInheritance = NULL;
extern void *ptr_CreateRestrictedToken;
void *ptr_CreateRestrictedToken = NULL;
extern void *ptr_CreateWellKnownSid;
void *ptr_CreateWellKnownSid = NULL;
extern void *ptr_DeleteAce;
void *ptr_DeleteAce = NULL;
extern void *ptr_DestroyPrivateObjectSecurity;
void *ptr_DestroyPrivateObjectSecurity = NULL;
extern void *ptr_DuplicateToken;
void *ptr_DuplicateToken = NULL;
extern void *ptr_DuplicateTokenEx;
void *ptr_DuplicateTokenEx = NULL;
extern void *ptr_EqualDomainSid;
void *ptr_EqualDomainSid = NULL;
extern void *ptr_EqualPrefixSid;
void *ptr_EqualPrefixSid = NULL;
extern void *ptr_EqualSid;
void *ptr_EqualSid = NULL;
extern void *ptr_FindFirstFreeAce;
void *ptr_FindFirstFreeAce = NULL;
extern void *ptr_FreeSid;
void *ptr_FreeSid = NULL;
extern void *ptr_GetAce;
void *ptr_GetAce = NULL;
extern void *ptr_GetAclInformation;
void *ptr_GetAclInformation = NULL;
extern void *ptr_GetFileSecurityW;
void *ptr_GetFileSecurityW = NULL;
extern void *ptr_GetKernelObjectSecurity;
void *ptr_GetKernelObjectSecurity = NULL;
extern void *ptr_GetLengthSid;
void *ptr_GetLengthSid = NULL;
extern void *ptr_GetPrivateObjectSecurity;
void *ptr_GetPrivateObjectSecurity = NULL;
extern void *ptr_GetSecurityDescriptorControl;
void *ptr_GetSecurityDescriptorControl = NULL;
extern void *ptr_GetSecurityDescriptorDacl;
void *ptr_GetSecurityDescriptorDacl = NULL;
extern void *ptr_GetSecurityDescriptorGroup;
void *ptr_GetSecurityDescriptorGroup = NULL;
extern void *ptr_GetSecurityDescriptorLength;
void *ptr_GetSecurityDescriptorLength = NULL;
extern void *ptr_GetSecurityDescriptorOwner;
void *ptr_GetSecurityDescriptorOwner = NULL;
extern void *ptr_GetSecurityDescriptorRMControl;
void *ptr_GetSecurityDescriptorRMControl = NULL;
extern void *ptr_GetSecurityDescriptorSacl;
void *ptr_GetSecurityDescriptorSacl = NULL;
extern void *ptr_GetSidIdentifierAuthority;
void *ptr_GetSidIdentifierAuthority = NULL;
extern void *ptr_GetSidLengthRequired;
void *ptr_GetSidLengthRequired = NULL;
extern void *ptr_GetSidSubAuthority;
void *ptr_GetSidSubAuthority = NULL;
extern void *ptr_GetSidSubAuthorityCount;
void *ptr_GetSidSubAuthorityCount = NULL;
extern void *ptr_GetTokenInformation;
void *ptr_GetTokenInformation = NULL;
extern void *ptr_GetWindowsAccountDomainSid;
void *ptr_GetWindowsAccountDomainSid = NULL;
extern void *ptr_ImpersonateAnonymousToken;
void *ptr_ImpersonateAnonymousToken = NULL;
extern void *ptr_ImpersonateLoggedOnUser;
void *ptr_ImpersonateLoggedOnUser = NULL;
extern void *ptr_ImpersonateSelf;
void *ptr_ImpersonateSelf = NULL;
extern void *ptr_InitializeAcl;
void *ptr_InitializeAcl = NULL;
extern void *ptr_InitializeSecurityDescriptor;
void *ptr_InitializeSecurityDescriptor = NULL;
extern void *ptr_InitializeSid;
void *ptr_InitializeSid = NULL;
extern void *ptr_IsTokenRestricted;
void *ptr_IsTokenRestricted = NULL;
extern void *ptr_IsValidAcl;
void *ptr_IsValidAcl = NULL;
extern void *ptr_IsValidRelativeSecurityDescriptor;
void *ptr_IsValidRelativeSecurityDescriptor = NULL;
extern void *ptr_IsValidSecurityDescriptor;
void *ptr_IsValidSecurityDescriptor = NULL;
extern void *ptr_IsValidSid;
void *ptr_IsValidSid = NULL;
extern void *ptr_IsWellKnownSid;
void *ptr_IsWellKnownSid = NULL;
extern void *ptr_MakeAbsoluteSD;
void *ptr_MakeAbsoluteSD = NULL;
extern void *ptr_MakeAbsoluteSD2;
void *ptr_MakeAbsoluteSD2 = NULL;
extern void *ptr_MakeSelfRelativeSD;
void *ptr_MakeSelfRelativeSD = NULL;
extern void *ptr_MapGenericMask;
void *ptr_MapGenericMask = NULL;
extern void *ptr_ObjectCloseAuditAlarmW;
void *ptr_ObjectCloseAuditAlarmW = NULL;
extern void *ptr_ObjectDeleteAuditAlarmW;
void *ptr_ObjectDeleteAuditAlarmW = NULL;
extern void *ptr_ObjectOpenAuditAlarmW;
void *ptr_ObjectOpenAuditAlarmW = NULL;
extern void *ptr_ObjectPrivilegeAuditAlarmW;
void *ptr_ObjectPrivilegeAuditAlarmW = NULL;
extern void *ptr_PrivilegeCheck;
void *ptr_PrivilegeCheck = NULL;
extern void *ptr_PrivilegedServiceAuditAlarmW;
void *ptr_PrivilegedServiceAuditAlarmW = NULL;
extern void *ptr_QuerySecurityAccessMask;
void *ptr_QuerySecurityAccessMask = NULL;
extern void *ptr_RevertToSelf;
void *ptr_RevertToSelf = NULL;
extern void *ptr_SetAclInformation;
void *ptr_SetAclInformation = NULL;
extern void *ptr_SetFileSecurityW;
void *ptr_SetFileSecurityW = NULL;
extern void *ptr_SetKernelObjectSecurity;
void *ptr_SetKernelObjectSecurity = NULL;
extern void *ptr_SetPrivateObjectSecurity;
void *ptr_SetPrivateObjectSecurity = NULL;
extern void *ptr_SetPrivateObjectSecurityEx;
void *ptr_SetPrivateObjectSecurityEx = NULL;
extern void *ptr_SetSecurityAccessMask;
void *ptr_SetSecurityAccessMask = NULL;
extern void *ptr_SetSecurityDescriptorControl;
void *ptr_SetSecurityDescriptorControl = NULL;
extern void *ptr_SetSecurityDescriptorDacl;
void *ptr_SetSecurityDescriptorDacl = NULL;
extern void *ptr_SetSecurityDescriptorGroup;
void *ptr_SetSecurityDescriptorGroup = NULL;
extern void *ptr_SetSecurityDescriptorOwner;
void *ptr_SetSecurityDescriptorOwner = NULL;
extern void *ptr_SetSecurityDescriptorRMControl;
void *ptr_SetSecurityDescriptorRMControl = NULL;
extern void *ptr_SetSecurityDescriptorSacl;
void *ptr_SetSecurityDescriptorSacl = NULL;
extern void *ptr_SetTokenInformation;
void *ptr_SetTokenInformation = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\api-ms-win-security-base-l1-1-0.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_AccessCheck = (__vartype(ptr_AccessCheck))GetProcAddress(hModule, "AccessCheck");
   ptr_AccessCheckAndAuditAlarmW = (__vartype(ptr_AccessCheckAndAuditAlarmW))GetProcAddress(hModule, "AccessCheckAndAuditAlarmW");
   ptr_AccessCheckByType = (__vartype(ptr_AccessCheckByType))GetProcAddress(hModule, "AccessCheckByType");
   ptr_AccessCheckByTypeAndAuditAlarmW = (__vartype(ptr_AccessCheckByTypeAndAuditAlarmW))GetProcAddress(hModule, "AccessCheckByTypeAndAuditAlarmW");
   ptr_AccessCheckByTypeResultList = (__vartype(ptr_AccessCheckByTypeResultList))GetProcAddress(hModule, "AccessCheckByTypeResultList");
   ptr_AccessCheckByTypeResultListAndAuditAlarmByHandleW = (__vartype(ptr_AccessCheckByTypeResultListAndAuditAlarmByHandleW))GetProcAddress(hModule, "AccessCheckByTypeResultListAndAuditAlarmByHandleW");
   ptr_AccessCheckByTypeResultListAndAuditAlarmW = (__vartype(ptr_AccessCheckByTypeResultListAndAuditAlarmW))GetProcAddress(hModule, "AccessCheckByTypeResultListAndAuditAlarmW");
   ptr_AddAccessAllowedAce = (__vartype(ptr_AddAccessAllowedAce))GetProcAddress(hModule, "AddAccessAllowedAce");
   ptr_AddAccessAllowedAceEx = (__vartype(ptr_AddAccessAllowedAceEx))GetProcAddress(hModule, "AddAccessAllowedAceEx");
   ptr_AddAccessAllowedObjectAce = (__vartype(ptr_AddAccessAllowedObjectAce))GetProcAddress(hModule, "AddAccessAllowedObjectAce");
   ptr_AddAccessDeniedAce = (__vartype(ptr_AddAccessDeniedAce))GetProcAddress(hModule, "AddAccessDeniedAce");
   ptr_AddAccessDeniedAceEx = (__vartype(ptr_AddAccessDeniedAceEx))GetProcAddress(hModule, "AddAccessDeniedAceEx");
   ptr_AddAccessDeniedObjectAce = (__vartype(ptr_AddAccessDeniedObjectAce))GetProcAddress(hModule, "AddAccessDeniedObjectAce");
   ptr_AddAce = (__vartype(ptr_AddAce))GetProcAddress(hModule, "AddAce");
   ptr_AddAuditAccessAce = (__vartype(ptr_AddAuditAccessAce))GetProcAddress(hModule, "AddAuditAccessAce");
   ptr_AddAuditAccessAceEx = (__vartype(ptr_AddAuditAccessAceEx))GetProcAddress(hModule, "AddAuditAccessAceEx");
   ptr_AddAuditAccessObjectAce = (__vartype(ptr_AddAuditAccessObjectAce))GetProcAddress(hModule, "AddAuditAccessObjectAce");
   ptr_AddMandatoryAce = (__vartype(ptr_AddMandatoryAce))GetProcAddress(hModule, "AddMandatoryAce");
   ptr_AdjustTokenGroups = (__vartype(ptr_AdjustTokenGroups))GetProcAddress(hModule, "AdjustTokenGroups");
   ptr_AdjustTokenPrivileges = (__vartype(ptr_AdjustTokenPrivileges))GetProcAddress(hModule, "AdjustTokenPrivileges");
   ptr_AllocateAndInitializeSid = (__vartype(ptr_AllocateAndInitializeSid))GetProcAddress(hModule, "AllocateAndInitializeSid");
   ptr_AllocateLocallyUniqueId = (__vartype(ptr_AllocateLocallyUniqueId))GetProcAddress(hModule, "AllocateLocallyUniqueId");
   ptr_AreAllAccessesGranted = (__vartype(ptr_AreAllAccessesGranted))GetProcAddress(hModule, "AreAllAccessesGranted");
   ptr_AreAnyAccessesGranted = (__vartype(ptr_AreAnyAccessesGranted))GetProcAddress(hModule, "AreAnyAccessesGranted");
   ptr_CheckTokenMembership = (__vartype(ptr_CheckTokenMembership))GetProcAddress(hModule, "CheckTokenMembership");
   ptr_ConvertToAutoInheritPrivateObjectSecurity = (__vartype(ptr_ConvertToAutoInheritPrivateObjectSecurity))GetProcAddress(hModule, "ConvertToAutoInheritPrivateObjectSecurity");
   ptr_CopySid = (__vartype(ptr_CopySid))GetProcAddress(hModule, "CopySid");
   ptr_CreatePrivateObjectSecurity = (__vartype(ptr_CreatePrivateObjectSecurity))GetProcAddress(hModule, "CreatePrivateObjectSecurity");
   ptr_CreatePrivateObjectSecurityEx = (__vartype(ptr_CreatePrivateObjectSecurityEx))GetProcAddress(hModule, "CreatePrivateObjectSecurityEx");
   ptr_CreatePrivateObjectSecurityWithMultipleInheritance = (__vartype(ptr_CreatePrivateObjectSecurityWithMultipleInheritance))GetProcAddress(hModule, "CreatePrivateObjectSecurityWithMultipleInheritance");
   ptr_CreateRestrictedToken = (__vartype(ptr_CreateRestrictedToken))GetProcAddress(hModule, "CreateRestrictedToken");
   ptr_CreateWellKnownSid = (__vartype(ptr_CreateWellKnownSid))GetProcAddress(hModule, "CreateWellKnownSid");
   ptr_DeleteAce = (__vartype(ptr_DeleteAce))GetProcAddress(hModule, "DeleteAce");
   ptr_DestroyPrivateObjectSecurity = (__vartype(ptr_DestroyPrivateObjectSecurity))GetProcAddress(hModule, "DestroyPrivateObjectSecurity");
   ptr_DuplicateToken = (__vartype(ptr_DuplicateToken))GetProcAddress(hModule, "DuplicateToken");
   ptr_DuplicateTokenEx = (__vartype(ptr_DuplicateTokenEx))GetProcAddress(hModule, "DuplicateTokenEx");
   ptr_EqualDomainSid = (__vartype(ptr_EqualDomainSid))GetProcAddress(hModule, "EqualDomainSid");
   ptr_EqualPrefixSid = (__vartype(ptr_EqualPrefixSid))GetProcAddress(hModule, "EqualPrefixSid");
   ptr_EqualSid = (__vartype(ptr_EqualSid))GetProcAddress(hModule, "EqualSid");
   ptr_FindFirstFreeAce = (__vartype(ptr_FindFirstFreeAce))GetProcAddress(hModule, "FindFirstFreeAce");
   ptr_FreeSid = (__vartype(ptr_FreeSid))GetProcAddress(hModule, "FreeSid");
   ptr_GetAce = (__vartype(ptr_GetAce))GetProcAddress(hModule, "GetAce");
   ptr_GetAclInformation = (__vartype(ptr_GetAclInformation))GetProcAddress(hModule, "GetAclInformation");
   ptr_GetFileSecurityW = (__vartype(ptr_GetFileSecurityW))GetProcAddress(hModule, "GetFileSecurityW");
   ptr_GetKernelObjectSecurity = (__vartype(ptr_GetKernelObjectSecurity))GetProcAddress(hModule, "GetKernelObjectSecurity");
   ptr_GetLengthSid = (__vartype(ptr_GetLengthSid))GetProcAddress(hModule, "GetLengthSid");
   ptr_GetPrivateObjectSecurity = (__vartype(ptr_GetPrivateObjectSecurity))GetProcAddress(hModule, "GetPrivateObjectSecurity");
   ptr_GetSecurityDescriptorControl = (__vartype(ptr_GetSecurityDescriptorControl))GetProcAddress(hModule, "GetSecurityDescriptorControl");
   ptr_GetSecurityDescriptorDacl = (__vartype(ptr_GetSecurityDescriptorDacl))GetProcAddress(hModule, "GetSecurityDescriptorDacl");
   ptr_GetSecurityDescriptorGroup = (__vartype(ptr_GetSecurityDescriptorGroup))GetProcAddress(hModule, "GetSecurityDescriptorGroup");
   ptr_GetSecurityDescriptorLength = (__vartype(ptr_GetSecurityDescriptorLength))GetProcAddress(hModule, "GetSecurityDescriptorLength");
   ptr_GetSecurityDescriptorOwner = (__vartype(ptr_GetSecurityDescriptorOwner))GetProcAddress(hModule, "GetSecurityDescriptorOwner");
   ptr_GetSecurityDescriptorRMControl = (__vartype(ptr_GetSecurityDescriptorRMControl))GetProcAddress(hModule, "GetSecurityDescriptorRMControl");
   ptr_GetSecurityDescriptorSacl = (__vartype(ptr_GetSecurityDescriptorSacl))GetProcAddress(hModule, "GetSecurityDescriptorSacl");
   ptr_GetSidIdentifierAuthority = (__vartype(ptr_GetSidIdentifierAuthority))GetProcAddress(hModule, "GetSidIdentifierAuthority");
   ptr_GetSidLengthRequired = (__vartype(ptr_GetSidLengthRequired))GetProcAddress(hModule, "GetSidLengthRequired");
   ptr_GetSidSubAuthority = (__vartype(ptr_GetSidSubAuthority))GetProcAddress(hModule, "GetSidSubAuthority");
   ptr_GetSidSubAuthorityCount = (__vartype(ptr_GetSidSubAuthorityCount))GetProcAddress(hModule, "GetSidSubAuthorityCount");
   ptr_GetTokenInformation = (__vartype(ptr_GetTokenInformation))GetProcAddress(hModule, "GetTokenInformation");
   ptr_GetWindowsAccountDomainSid = (__vartype(ptr_GetWindowsAccountDomainSid))GetProcAddress(hModule, "GetWindowsAccountDomainSid");
   ptr_ImpersonateAnonymousToken = (__vartype(ptr_ImpersonateAnonymousToken))GetProcAddress(hModule, "ImpersonateAnonymousToken");
   ptr_ImpersonateLoggedOnUser = (__vartype(ptr_ImpersonateLoggedOnUser))GetProcAddress(hModule, "ImpersonateLoggedOnUser");
   ptr_ImpersonateSelf = (__vartype(ptr_ImpersonateSelf))GetProcAddress(hModule, "ImpersonateSelf");
   ptr_InitializeAcl = (__vartype(ptr_InitializeAcl))GetProcAddress(hModule, "InitializeAcl");
   ptr_InitializeSecurityDescriptor = (__vartype(ptr_InitializeSecurityDescriptor))GetProcAddress(hModule, "InitializeSecurityDescriptor");
   ptr_InitializeSid = (__vartype(ptr_InitializeSid))GetProcAddress(hModule, "InitializeSid");
   ptr_IsTokenRestricted = (__vartype(ptr_IsTokenRestricted))GetProcAddress(hModule, "IsTokenRestricted");
   ptr_IsValidAcl = (__vartype(ptr_IsValidAcl))GetProcAddress(hModule, "IsValidAcl");
   ptr_IsValidRelativeSecurityDescriptor = (__vartype(ptr_IsValidRelativeSecurityDescriptor))GetProcAddress(hModule, "IsValidRelativeSecurityDescriptor");
   ptr_IsValidSecurityDescriptor = (__vartype(ptr_IsValidSecurityDescriptor))GetProcAddress(hModule, "IsValidSecurityDescriptor");
   ptr_IsValidSid = (__vartype(ptr_IsValidSid))GetProcAddress(hModule, "IsValidSid");
   ptr_IsWellKnownSid = (__vartype(ptr_IsWellKnownSid))GetProcAddress(hModule, "IsWellKnownSid");
   ptr_MakeAbsoluteSD = (__vartype(ptr_MakeAbsoluteSD))GetProcAddress(hModule, "MakeAbsoluteSD");
   ptr_MakeAbsoluteSD2 = (__vartype(ptr_MakeAbsoluteSD2))GetProcAddress(hModule, "MakeAbsoluteSD2");
   ptr_MakeSelfRelativeSD = (__vartype(ptr_MakeSelfRelativeSD))GetProcAddress(hModule, "MakeSelfRelativeSD");
   ptr_MapGenericMask = (__vartype(ptr_MapGenericMask))GetProcAddress(hModule, "MapGenericMask");
   ptr_ObjectCloseAuditAlarmW = (__vartype(ptr_ObjectCloseAuditAlarmW))GetProcAddress(hModule, "ObjectCloseAuditAlarmW");
   ptr_ObjectDeleteAuditAlarmW = (__vartype(ptr_ObjectDeleteAuditAlarmW))GetProcAddress(hModule, "ObjectDeleteAuditAlarmW");
   ptr_ObjectOpenAuditAlarmW = (__vartype(ptr_ObjectOpenAuditAlarmW))GetProcAddress(hModule, "ObjectOpenAuditAlarmW");
   ptr_ObjectPrivilegeAuditAlarmW = (__vartype(ptr_ObjectPrivilegeAuditAlarmW))GetProcAddress(hModule, "ObjectPrivilegeAuditAlarmW");
   ptr_PrivilegeCheck = (__vartype(ptr_PrivilegeCheck))GetProcAddress(hModule, "PrivilegeCheck");
   ptr_PrivilegedServiceAuditAlarmW = (__vartype(ptr_PrivilegedServiceAuditAlarmW))GetProcAddress(hModule, "PrivilegedServiceAuditAlarmW");
   ptr_QuerySecurityAccessMask = (__vartype(ptr_QuerySecurityAccessMask))GetProcAddress(hModule, "QuerySecurityAccessMask");
   ptr_RevertToSelf = (__vartype(ptr_RevertToSelf))GetProcAddress(hModule, "RevertToSelf");
   ptr_SetAclInformation = (__vartype(ptr_SetAclInformation))GetProcAddress(hModule, "SetAclInformation");
   ptr_SetFileSecurityW = (__vartype(ptr_SetFileSecurityW))GetProcAddress(hModule, "SetFileSecurityW");
   ptr_SetKernelObjectSecurity = (__vartype(ptr_SetKernelObjectSecurity))GetProcAddress(hModule, "SetKernelObjectSecurity");
   ptr_SetPrivateObjectSecurity = (__vartype(ptr_SetPrivateObjectSecurity))GetProcAddress(hModule, "SetPrivateObjectSecurity");
   ptr_SetPrivateObjectSecurityEx = (__vartype(ptr_SetPrivateObjectSecurityEx))GetProcAddress(hModule, "SetPrivateObjectSecurityEx");
   ptr_SetSecurityAccessMask = (__vartype(ptr_SetSecurityAccessMask))GetProcAddress(hModule, "SetSecurityAccessMask");
   ptr_SetSecurityDescriptorControl = (__vartype(ptr_SetSecurityDescriptorControl))GetProcAddress(hModule, "SetSecurityDescriptorControl");
   ptr_SetSecurityDescriptorDacl = (__vartype(ptr_SetSecurityDescriptorDacl))GetProcAddress(hModule, "SetSecurityDescriptorDacl");
   ptr_SetSecurityDescriptorGroup = (__vartype(ptr_SetSecurityDescriptorGroup))GetProcAddress(hModule, "SetSecurityDescriptorGroup");
   ptr_SetSecurityDescriptorOwner = (__vartype(ptr_SetSecurityDescriptorOwner))GetProcAddress(hModule, "SetSecurityDescriptorOwner");
   ptr_SetSecurityDescriptorRMControl = (__vartype(ptr_SetSecurityDescriptorRMControl))GetProcAddress(hModule, "SetSecurityDescriptorRMControl");
   ptr_SetSecurityDescriptorSacl = (__vartype(ptr_SetSecurityDescriptorSacl))GetProcAddress(hModule, "SetSecurityDescriptorSacl");
   ptr_SetTokenInformation = (__vartype(ptr_SetTokenInformation))GetProcAddress(hModule, "SetTokenInformation");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

