#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_GetDomainName;
void *ptr_GetDomainName = NULL;
extern void *ptr_QueryUserProperty;
void *ptr_QueryUserProperty = NULL;
extern void *ptr_RegBuildNumberQuery;
void *ptr_RegBuildNumberQuery = NULL;
extern void *ptr_RegCdCreateA;
void *ptr_RegCdCreateA = NULL;
extern void *ptr_RegCdCreateW;
void *ptr_RegCdCreateW = NULL;
extern void *ptr_RegCdDeleteA;
void *ptr_RegCdDeleteA = NULL;
extern void *ptr_RegCdDeleteW;
void *ptr_RegCdDeleteW = NULL;
extern void *ptr_RegCdEnumerateA;
void *ptr_RegCdEnumerateA = NULL;
extern void *ptr_RegCdEnumerateW;
void *ptr_RegCdEnumerateW = NULL;
extern void *ptr_RegCdQueryA;
void *ptr_RegCdQueryA = NULL;
extern void *ptr_RegCdQueryW;
void *ptr_RegCdQueryW = NULL;
extern void *ptr_RegCloseServer;
void *ptr_RegCloseServer = NULL;
extern void *ptr_RegConsoleShadowQueryA;
void *ptr_RegConsoleShadowQueryA = NULL;
extern void *ptr_RegConsoleShadowQueryW;
void *ptr_RegConsoleShadowQueryW = NULL;
extern void *ptr_RegCreateMonitorConfigW;
void *ptr_RegCreateMonitorConfigW = NULL;
extern void *ptr_RegCreateUserConfigW;
void *ptr_RegCreateUserConfigW = NULL;
extern void *ptr_RegDefaultUserConfigQueryA;
void *ptr_RegDefaultUserConfigQueryA = NULL;
extern void *ptr_RegDefaultUserConfigQueryW;
void *ptr_RegDefaultUserConfigQueryW = NULL;
extern void *ptr_RegDenyTSConnectionsPolicy;
void *ptr_RegDenyTSConnectionsPolicy = NULL;
extern void *ptr_RegFreeUtilityCommandList;
void *ptr_RegFreeUtilityCommandList = NULL;
extern void *ptr_RegGetLicensePolicyID;
void *ptr_RegGetLicensePolicyID = NULL;
extern void *ptr_RegGetLicensingModePolicy;
void *ptr_RegGetLicensingModePolicy = NULL;
extern void *ptr_RegGetMachinePolicy;
void *ptr_RegGetMachinePolicy = NULL;
extern void *ptr_RegGetMachinePolicyEx;
void *ptr_RegGetMachinePolicyEx = NULL;
extern void *ptr_RegGetMachinePolicyNew;
void *ptr_RegGetMachinePolicyNew = NULL;
extern void *ptr_RegGetTServerVersion;
void *ptr_RegGetTServerVersion = NULL;
extern void *ptr_RegGetUserConfigFromUserParameters;
void *ptr_RegGetUserConfigFromUserParameters = NULL;
extern void *ptr_RegGetUserPolicy;
void *ptr_RegGetUserPolicy = NULL;
extern void *ptr_RegIsMachineInHelpMode;
void *ptr_RegIsMachineInHelpMode = NULL;
extern void *ptr_RegIsMachinePolicyAllowHelp;
void *ptr_RegIsMachinePolicyAllowHelp = NULL;
extern void *ptr_RegIsSrcAcceptingConnections;
void *ptr_RegIsSrcAcceptingConnections = NULL;
extern void *ptr_RegIsTServer;
void *ptr_RegIsTServer = NULL;
extern void *ptr_RegIsTimeZoneRedirectionEnabled;
void *ptr_RegIsTimeZoneRedirectionEnabled = NULL;
extern void *ptr_RegMergeUserConfigWithUserParameters;
void *ptr_RegMergeUserConfigWithUserParameters = NULL;
extern void *ptr_RegOpenServerA;
void *ptr_RegOpenServerA = NULL;
extern void *ptr_RegOpenServerW;
void *ptr_RegOpenServerW = NULL;
extern void *ptr_RegPdCreateA;
void *ptr_RegPdCreateA = NULL;
extern void *ptr_RegPdCreateW;
void *ptr_RegPdCreateW = NULL;
extern void *ptr_RegPdDeleteA;
void *ptr_RegPdDeleteA = NULL;
extern void *ptr_RegPdDeleteW;
void *ptr_RegPdDeleteW = NULL;
extern void *ptr_RegPdEnumerateA;
void *ptr_RegPdEnumerateA = NULL;
extern void *ptr_RegPdEnumerateW;
void *ptr_RegPdEnumerateW = NULL;
extern void *ptr_RegPdQueryA;
void *ptr_RegPdQueryA = NULL;
extern void *ptr_RegPdQueryW;
void *ptr_RegPdQueryW = NULL;
extern void *ptr_RegQueryAllowDWM;
void *ptr_RegQueryAllowDWM = NULL;
extern void *ptr_RegQueryConnectionSettings;
void *ptr_RegQueryConnectionSettings = NULL;
extern void *ptr_RegQueryListenerStart;
void *ptr_RegQueryListenerStart = NULL;
extern void *ptr_RegQueryMonitorSettings;
void *ptr_RegQueryMonitorSettings = NULL;
extern void *ptr_RegQueryOEMId;
void *ptr_RegQueryOEMId = NULL;
extern void *ptr_RegQuerySessionSettings;
void *ptr_RegQuerySessionSettings = NULL;
extern void *ptr_RegQueryUtilityCommandList;
void *ptr_RegQueryUtilityCommandList = NULL;
extern void *ptr_RegSAMUserConfig;
void *ptr_RegSAMUserConfig = NULL;
extern void *ptr_RegSetLicensePolicyID;
void *ptr_RegSetLicensePolicyID = NULL;
extern void *ptr_RegSetSrcAcceptConnections;
void *ptr_RegSetSrcAcceptConnections = NULL;
extern void *ptr_RegSetWinStationAllowDWM;
void *ptr_RegSetWinStationAllowDWM = NULL;
extern void *ptr_RegUserConfigDelete;
void *ptr_RegUserConfigDelete = NULL;
extern void *ptr_RegUserConfigQuery;
void *ptr_RegUserConfigQuery = NULL;
extern void *ptr_RegUserConfigRename;
void *ptr_RegUserConfigRename = NULL;
extern void *ptr_RegUserConfigSet;
void *ptr_RegUserConfigSet = NULL;
extern void *ptr_RegWdCreateA;
void *ptr_RegWdCreateA = NULL;
extern void *ptr_RegWdCreateW;
void *ptr_RegWdCreateW = NULL;
extern void *ptr_RegWdDeleteA;
void *ptr_RegWdDeleteA = NULL;
extern void *ptr_RegWdDeleteW;
void *ptr_RegWdDeleteW = NULL;
extern void *ptr_RegWdEnumerateA;
void *ptr_RegWdEnumerateA = NULL;
extern void *ptr_RegWdEnumerateW;
void *ptr_RegWdEnumerateW = NULL;
extern void *ptr_RegWdQueryA;
void *ptr_RegWdQueryA = NULL;
extern void *ptr_RegWdQueryW;
void *ptr_RegWdQueryW = NULL;
extern void *ptr_RegWinStationAccessCheck;
void *ptr_RegWinStationAccessCheck = NULL;
extern void *ptr_RegWinStationCreateA;
void *ptr_RegWinStationCreateA = NULL;
extern void *ptr_RegWinStationCreateW;
void *ptr_RegWinStationCreateW = NULL;
extern void *ptr_RegWinStationDeleteA;
void *ptr_RegWinStationDeleteA = NULL;
extern void *ptr_RegWinStationDeleteW;
void *ptr_RegWinStationDeleteW = NULL;
extern void *ptr_RegWinStationEnumerateA;
void *ptr_RegWinStationEnumerateA = NULL;
extern void *ptr_RegWinStationEnumerateW;
void *ptr_RegWinStationEnumerateW = NULL;
extern void *ptr_RegWinStationQueryA;
void *ptr_RegWinStationQueryA = NULL;
extern void *ptr_RegWinStationQueryDefaultSecurity;
void *ptr_RegWinStationQueryDefaultSecurity = NULL;
extern void *ptr_RegWinStationQueryEx;
void *ptr_RegWinStationQueryEx = NULL;
extern void *ptr_RegWinStationQueryExNew;
void *ptr_RegWinStationQueryExNew = NULL;
extern void *ptr_RegWinStationQueryExtendedSettingsW;
void *ptr_RegWinStationQueryExtendedSettingsW = NULL;
extern void *ptr_RegWinStationQueryNumValueW;
void *ptr_RegWinStationQueryNumValueW = NULL;
extern void *ptr_RegWinStationQuerySecurityA;
void *ptr_RegWinStationQuerySecurityA = NULL;
extern void *ptr_RegWinStationQuerySecurityW;
void *ptr_RegWinStationQuerySecurityW = NULL;
extern void *ptr_RegWinStationQueryValueW;
void *ptr_RegWinStationQueryValueW = NULL;
extern void *ptr_RegWinStationQueryW;
void *ptr_RegWinStationQueryW = NULL;
extern void *ptr_RegWinStationSetExtendedSettingsW;
void *ptr_RegWinStationSetExtendedSettingsW = NULL;
extern void *ptr_RegWinStationSetNumValueW;
void *ptr_RegWinStationSetNumValueW = NULL;
extern void *ptr_RegWinStationSetSecurityA;
void *ptr_RegWinStationSetSecurityA = NULL;
extern void *ptr_RegWinStationSetSecurityW;
void *ptr_RegWinStationSetSecurityW = NULL;
extern void *ptr_RegWinstationQuerySecurityConfig_Machine;
void *ptr_RegWinstationQuerySecurityConfig_Machine = NULL;
extern void *ptr_RegWinstationQuerySecurityConfig_Merged;
void *ptr_RegWinstationQuerySecurityConfig_Merged = NULL;
extern void *ptr_RegWinstationSetSecurityConfig;
void *ptr_RegWinstationSetSecurityConfig = NULL;
extern void *ptr_SetUserProperty;
void *ptr_SetUserProperty = NULL;
extern void *ptr_UsrPropGetString;
void *ptr_UsrPropGetString = NULL;
extern void *ptr_UsrPropGetValue;
void *ptr_UsrPropGetValue = NULL;
extern void *ptr_UsrPropSetString;
void *ptr_UsrPropSetString = NULL;
extern void *ptr_UsrPropSetValue;
void *ptr_UsrPropSetValue = NULL;
extern void *ptr_WaitForTSConnectionsPolicyChanges;
void *ptr_WaitForTSConnectionsPolicyChanges = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\regapi.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_GetDomainName = (__vartype(ptr_GetDomainName))GetProcAddress(hModule, "GetDomainName");
   ptr_QueryUserProperty = (__vartype(ptr_QueryUserProperty))GetProcAddress(hModule, "QueryUserProperty");
   ptr_RegBuildNumberQuery = (__vartype(ptr_RegBuildNumberQuery))GetProcAddress(hModule, "RegBuildNumberQuery");
   ptr_RegCdCreateA = (__vartype(ptr_RegCdCreateA))GetProcAddress(hModule, "RegCdCreateA");
   ptr_RegCdCreateW = (__vartype(ptr_RegCdCreateW))GetProcAddress(hModule, "RegCdCreateW");
   ptr_RegCdDeleteA = (__vartype(ptr_RegCdDeleteA))GetProcAddress(hModule, "RegCdDeleteA");
   ptr_RegCdDeleteW = (__vartype(ptr_RegCdDeleteW))GetProcAddress(hModule, "RegCdDeleteW");
   ptr_RegCdEnumerateA = (__vartype(ptr_RegCdEnumerateA))GetProcAddress(hModule, "RegCdEnumerateA");
   ptr_RegCdEnumerateW = (__vartype(ptr_RegCdEnumerateW))GetProcAddress(hModule, "RegCdEnumerateW");
   ptr_RegCdQueryA = (__vartype(ptr_RegCdQueryA))GetProcAddress(hModule, "RegCdQueryA");
   ptr_RegCdQueryW = (__vartype(ptr_RegCdQueryW))GetProcAddress(hModule, "RegCdQueryW");
   ptr_RegCloseServer = (__vartype(ptr_RegCloseServer))GetProcAddress(hModule, "RegCloseServer");
   ptr_RegConsoleShadowQueryA = (__vartype(ptr_RegConsoleShadowQueryA))GetProcAddress(hModule, "RegConsoleShadowQueryA");
   ptr_RegConsoleShadowQueryW = (__vartype(ptr_RegConsoleShadowQueryW))GetProcAddress(hModule, "RegConsoleShadowQueryW");
   ptr_RegCreateMonitorConfigW = (__vartype(ptr_RegCreateMonitorConfigW))GetProcAddress(hModule, "RegCreateMonitorConfigW");
   ptr_RegCreateUserConfigW = (__vartype(ptr_RegCreateUserConfigW))GetProcAddress(hModule, "RegCreateUserConfigW");
   ptr_RegDefaultUserConfigQueryA = (__vartype(ptr_RegDefaultUserConfigQueryA))GetProcAddress(hModule, "RegDefaultUserConfigQueryA");
   ptr_RegDefaultUserConfigQueryW = (__vartype(ptr_RegDefaultUserConfigQueryW))GetProcAddress(hModule, "RegDefaultUserConfigQueryW");
   ptr_RegDenyTSConnectionsPolicy = (__vartype(ptr_RegDenyTSConnectionsPolicy))GetProcAddress(hModule, "RegDenyTSConnectionsPolicy");
   ptr_RegFreeUtilityCommandList = (__vartype(ptr_RegFreeUtilityCommandList))GetProcAddress(hModule, "RegFreeUtilityCommandList");
   ptr_RegGetLicensePolicyID = (__vartype(ptr_RegGetLicensePolicyID))GetProcAddress(hModule, "RegGetLicensePolicyID");
   ptr_RegGetLicensingModePolicy = (__vartype(ptr_RegGetLicensingModePolicy))GetProcAddress(hModule, "RegGetLicensingModePolicy");
   ptr_RegGetMachinePolicy = (__vartype(ptr_RegGetMachinePolicy))GetProcAddress(hModule, "RegGetMachinePolicy");
   ptr_RegGetMachinePolicyEx = (__vartype(ptr_RegGetMachinePolicyEx))GetProcAddress(hModule, "RegGetMachinePolicyEx");
   ptr_RegGetMachinePolicyNew = (__vartype(ptr_RegGetMachinePolicyNew))GetProcAddress(hModule, "RegGetMachinePolicyNew");
   ptr_RegGetTServerVersion = (__vartype(ptr_RegGetTServerVersion))GetProcAddress(hModule, "RegGetTServerVersion");
   ptr_RegGetUserConfigFromUserParameters = (__vartype(ptr_RegGetUserConfigFromUserParameters))GetProcAddress(hModule, "RegGetUserConfigFromUserParameters");
   ptr_RegGetUserPolicy = (__vartype(ptr_RegGetUserPolicy))GetProcAddress(hModule, "RegGetUserPolicy");
   ptr_RegIsMachineInHelpMode = (__vartype(ptr_RegIsMachineInHelpMode))GetProcAddress(hModule, "RegIsMachineInHelpMode");
   ptr_RegIsMachinePolicyAllowHelp = (__vartype(ptr_RegIsMachinePolicyAllowHelp))GetProcAddress(hModule, "RegIsMachinePolicyAllowHelp");
   ptr_RegIsSrcAcceptingConnections = (__vartype(ptr_RegIsSrcAcceptingConnections))GetProcAddress(hModule, "RegIsSrcAcceptingConnections");
   ptr_RegIsTServer = (__vartype(ptr_RegIsTServer))GetProcAddress(hModule, "RegIsTServer");
   ptr_RegIsTimeZoneRedirectionEnabled = (__vartype(ptr_RegIsTimeZoneRedirectionEnabled))GetProcAddress(hModule, "RegIsTimeZoneRedirectionEnabled");
   ptr_RegMergeUserConfigWithUserParameters = (__vartype(ptr_RegMergeUserConfigWithUserParameters))GetProcAddress(hModule, "RegMergeUserConfigWithUserParameters");
   ptr_RegOpenServerA = (__vartype(ptr_RegOpenServerA))GetProcAddress(hModule, "RegOpenServerA");
   ptr_RegOpenServerW = (__vartype(ptr_RegOpenServerW))GetProcAddress(hModule, "RegOpenServerW");
   ptr_RegPdCreateA = (__vartype(ptr_RegPdCreateA))GetProcAddress(hModule, "RegPdCreateA");
   ptr_RegPdCreateW = (__vartype(ptr_RegPdCreateW))GetProcAddress(hModule, "RegPdCreateW");
   ptr_RegPdDeleteA = (__vartype(ptr_RegPdDeleteA))GetProcAddress(hModule, "RegPdDeleteA");
   ptr_RegPdDeleteW = (__vartype(ptr_RegPdDeleteW))GetProcAddress(hModule, "RegPdDeleteW");
   ptr_RegPdEnumerateA = (__vartype(ptr_RegPdEnumerateA))GetProcAddress(hModule, "RegPdEnumerateA");
   ptr_RegPdEnumerateW = (__vartype(ptr_RegPdEnumerateW))GetProcAddress(hModule, "RegPdEnumerateW");
   ptr_RegPdQueryA = (__vartype(ptr_RegPdQueryA))GetProcAddress(hModule, "RegPdQueryA");
   ptr_RegPdQueryW = (__vartype(ptr_RegPdQueryW))GetProcAddress(hModule, "RegPdQueryW");
   ptr_RegQueryAllowDWM = (__vartype(ptr_RegQueryAllowDWM))GetProcAddress(hModule, "RegQueryAllowDWM");
   ptr_RegQueryConnectionSettings = (__vartype(ptr_RegQueryConnectionSettings))GetProcAddress(hModule, "RegQueryConnectionSettings");
   ptr_RegQueryListenerStart = (__vartype(ptr_RegQueryListenerStart))GetProcAddress(hModule, "RegQueryListenerStart");
   ptr_RegQueryMonitorSettings = (__vartype(ptr_RegQueryMonitorSettings))GetProcAddress(hModule, "RegQueryMonitorSettings");
   ptr_RegQueryOEMId = (__vartype(ptr_RegQueryOEMId))GetProcAddress(hModule, "RegQueryOEMId");
   ptr_RegQuerySessionSettings = (__vartype(ptr_RegQuerySessionSettings))GetProcAddress(hModule, "RegQuerySessionSettings");
   ptr_RegQueryUtilityCommandList = (__vartype(ptr_RegQueryUtilityCommandList))GetProcAddress(hModule, "RegQueryUtilityCommandList");
   ptr_RegSAMUserConfig = (__vartype(ptr_RegSAMUserConfig))GetProcAddress(hModule, "RegSAMUserConfig");
   ptr_RegSetLicensePolicyID = (__vartype(ptr_RegSetLicensePolicyID))GetProcAddress(hModule, "RegSetLicensePolicyID");
   ptr_RegSetSrcAcceptConnections = (__vartype(ptr_RegSetSrcAcceptConnections))GetProcAddress(hModule, "RegSetSrcAcceptConnections");
   ptr_RegSetWinStationAllowDWM = (__vartype(ptr_RegSetWinStationAllowDWM))GetProcAddress(hModule, "RegSetWinStationAllowDWM");
   ptr_RegUserConfigDelete = (__vartype(ptr_RegUserConfigDelete))GetProcAddress(hModule, "RegUserConfigDelete");
   ptr_RegUserConfigQuery = (__vartype(ptr_RegUserConfigQuery))GetProcAddress(hModule, "RegUserConfigQuery");
   ptr_RegUserConfigRename = (__vartype(ptr_RegUserConfigRename))GetProcAddress(hModule, "RegUserConfigRename");
   ptr_RegUserConfigSet = (__vartype(ptr_RegUserConfigSet))GetProcAddress(hModule, "RegUserConfigSet");
   ptr_RegWdCreateA = (__vartype(ptr_RegWdCreateA))GetProcAddress(hModule, "RegWdCreateA");
   ptr_RegWdCreateW = (__vartype(ptr_RegWdCreateW))GetProcAddress(hModule, "RegWdCreateW");
   ptr_RegWdDeleteA = (__vartype(ptr_RegWdDeleteA))GetProcAddress(hModule, "RegWdDeleteA");
   ptr_RegWdDeleteW = (__vartype(ptr_RegWdDeleteW))GetProcAddress(hModule, "RegWdDeleteW");
   ptr_RegWdEnumerateA = (__vartype(ptr_RegWdEnumerateA))GetProcAddress(hModule, "RegWdEnumerateA");
   ptr_RegWdEnumerateW = (__vartype(ptr_RegWdEnumerateW))GetProcAddress(hModule, "RegWdEnumerateW");
   ptr_RegWdQueryA = (__vartype(ptr_RegWdQueryA))GetProcAddress(hModule, "RegWdQueryA");
   ptr_RegWdQueryW = (__vartype(ptr_RegWdQueryW))GetProcAddress(hModule, "RegWdQueryW");
   ptr_RegWinStationAccessCheck = (__vartype(ptr_RegWinStationAccessCheck))GetProcAddress(hModule, "RegWinStationAccessCheck");
   ptr_RegWinStationCreateA = (__vartype(ptr_RegWinStationCreateA))GetProcAddress(hModule, "RegWinStationCreateA");
   ptr_RegWinStationCreateW = (__vartype(ptr_RegWinStationCreateW))GetProcAddress(hModule, "RegWinStationCreateW");
   ptr_RegWinStationDeleteA = (__vartype(ptr_RegWinStationDeleteA))GetProcAddress(hModule, "RegWinStationDeleteA");
   ptr_RegWinStationDeleteW = (__vartype(ptr_RegWinStationDeleteW))GetProcAddress(hModule, "RegWinStationDeleteW");
   ptr_RegWinStationEnumerateA = (__vartype(ptr_RegWinStationEnumerateA))GetProcAddress(hModule, "RegWinStationEnumerateA");
   ptr_RegWinStationEnumerateW = (__vartype(ptr_RegWinStationEnumerateW))GetProcAddress(hModule, "RegWinStationEnumerateW");
   ptr_RegWinStationQueryA = (__vartype(ptr_RegWinStationQueryA))GetProcAddress(hModule, "RegWinStationQueryA");
   ptr_RegWinStationQueryDefaultSecurity = (__vartype(ptr_RegWinStationQueryDefaultSecurity))GetProcAddress(hModule, "RegWinStationQueryDefaultSecurity");
   ptr_RegWinStationQueryEx = (__vartype(ptr_RegWinStationQueryEx))GetProcAddress(hModule, "RegWinStationQueryEx");
   ptr_RegWinStationQueryExNew = (__vartype(ptr_RegWinStationQueryExNew))GetProcAddress(hModule, "RegWinStationQueryExNew");
   ptr_RegWinStationQueryExtendedSettingsW = (__vartype(ptr_RegWinStationQueryExtendedSettingsW))GetProcAddress(hModule, "RegWinStationQueryExtendedSettingsW");
   ptr_RegWinStationQueryNumValueW = (__vartype(ptr_RegWinStationQueryNumValueW))GetProcAddress(hModule, "RegWinStationQueryNumValueW");
   ptr_RegWinStationQuerySecurityA = (__vartype(ptr_RegWinStationQuerySecurityA))GetProcAddress(hModule, "RegWinStationQuerySecurityA");
   ptr_RegWinStationQuerySecurityW = (__vartype(ptr_RegWinStationQuerySecurityW))GetProcAddress(hModule, "RegWinStationQuerySecurityW");
   ptr_RegWinStationQueryValueW = (__vartype(ptr_RegWinStationQueryValueW))GetProcAddress(hModule, "RegWinStationQueryValueW");
   ptr_RegWinStationQueryW = (__vartype(ptr_RegWinStationQueryW))GetProcAddress(hModule, "RegWinStationQueryW");
   ptr_RegWinStationSetExtendedSettingsW = (__vartype(ptr_RegWinStationSetExtendedSettingsW))GetProcAddress(hModule, "RegWinStationSetExtendedSettingsW");
   ptr_RegWinStationSetNumValueW = (__vartype(ptr_RegWinStationSetNumValueW))GetProcAddress(hModule, "RegWinStationSetNumValueW");
   ptr_RegWinStationSetSecurityA = (__vartype(ptr_RegWinStationSetSecurityA))GetProcAddress(hModule, "RegWinStationSetSecurityA");
   ptr_RegWinStationSetSecurityW = (__vartype(ptr_RegWinStationSetSecurityW))GetProcAddress(hModule, "RegWinStationSetSecurityW");
   ptr_RegWinstationQuerySecurityConfig_Machine = (__vartype(ptr_RegWinstationQuerySecurityConfig_Machine))GetProcAddress(hModule, "RegWinstationQuerySecurityConfig_Machine");
   ptr_RegWinstationQuerySecurityConfig_Merged = (__vartype(ptr_RegWinstationQuerySecurityConfig_Merged))GetProcAddress(hModule, "RegWinstationQuerySecurityConfig_Merged");
   ptr_RegWinstationSetSecurityConfig = (__vartype(ptr_RegWinstationSetSecurityConfig))GetProcAddress(hModule, "RegWinstationSetSecurityConfig");
   ptr_SetUserProperty = (__vartype(ptr_SetUserProperty))GetProcAddress(hModule, "SetUserProperty");
   ptr_UsrPropGetString = (__vartype(ptr_UsrPropGetString))GetProcAddress(hModule, "UsrPropGetString");
   ptr_UsrPropGetValue = (__vartype(ptr_UsrPropGetValue))GetProcAddress(hModule, "UsrPropGetValue");
   ptr_UsrPropSetString = (__vartype(ptr_UsrPropSetString))GetProcAddress(hModule, "UsrPropSetString");
   ptr_UsrPropSetValue = (__vartype(ptr_UsrPropSetValue))GetProcAddress(hModule, "UsrPropSetValue");
   ptr_WaitForTSConnectionsPolicyChanges = (__vartype(ptr_WaitForTSConnectionsPolicyChanges))GetProcAddress(hModule, "WaitForTSConnectionsPolicyChanges");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

