#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_CopyPropVariant;
void *ptr_CopyPropVariant = NULL;
extern void *ptr_CreatePropVariant;
void *ptr_CreatePropVariant = NULL;
extern void *ptr_CreatePropertyStore;
void *ptr_CreatePropertyStore = NULL;
extern void *ptr_DestroyPropVariant;
void *ptr_DestroyPropVariant = NULL;
extern void *ptr_FormatTagFromWfx;
void *ptr_FormatTagFromWfx = NULL;
extern void *ptr_GetAMSubtypeFromD3DFormat;
void *ptr_GetAMSubtypeFromD3DFormat = NULL;
extern void *ptr_GetD3DFormatFromMFSubtype;
void *ptr_GetD3DFormatFromMFSubtype = NULL;
extern void *ptr_LFGetGlobalPool;
void *ptr_LFGetGlobalPool = NULL;
extern void *ptr_MFAddPeriodicCallback;
void *ptr_MFAddPeriodicCallback = NULL;
extern void *ptr_MFAllocateWorkQueue;
void *ptr_MFAllocateWorkQueue = NULL;
extern void *ptr_MFAllocateWorkQueueEx;
void *ptr_MFAllocateWorkQueueEx = NULL;
extern void *ptr_MFAppendCollection;
void *ptr_MFAppendCollection = NULL;
extern void *ptr_MFAverageTimePerFrameToFrameRate;
void *ptr_MFAverageTimePerFrameToFrameRate = NULL;
extern void *ptr_MFBeginCreateFile;
void *ptr_MFBeginCreateFile = NULL;
extern void *ptr_MFBeginGetHostByName;
void *ptr_MFBeginGetHostByName = NULL;
extern void *ptr_MFBeginRegisterWorkQueueWithMMCSS;
void *ptr_MFBeginRegisterWorkQueueWithMMCSS = NULL;
extern void *ptr_MFBeginUnregisterWorkQueueWithMMCSS;
void *ptr_MFBeginUnregisterWorkQueueWithMMCSS = NULL;
extern void *ptr_MFBlockThread;
void *ptr_MFBlockThread = NULL;
extern void *ptr_MFCalculateBitmapImageSize;
void *ptr_MFCalculateBitmapImageSize = NULL;
extern void *ptr_MFCalculateImageSize;
void *ptr_MFCalculateImageSize = NULL;
extern void *ptr_MFCancelCreateFile;
void *ptr_MFCancelCreateFile = NULL;
extern void *ptr_MFCancelWorkItem;
void *ptr_MFCancelWorkItem = NULL;
extern void *ptr_MFCompareFullToPartialMediaType;
void *ptr_MFCompareFullToPartialMediaType = NULL;
extern void *ptr_MFCompareSockaddrAddresses;
void *ptr_MFCompareSockaddrAddresses = NULL;
extern void *ptr_MFConvertColorInfoFromDXVA;
void *ptr_MFConvertColorInfoFromDXVA = NULL;
extern void *ptr_MFConvertColorInfoToDXVA;
void *ptr_MFConvertColorInfoToDXVA = NULL;
extern void *ptr_MFConvertFromFP16Array;
void *ptr_MFConvertFromFP16Array = NULL;
extern void *ptr_MFConvertToFP16Array;
void *ptr_MFConvertToFP16Array = NULL;
extern void *ptr_MFCopyImage;
void *ptr_MFCopyImage = NULL;
extern void *ptr_MFCreateAMMediaTypeFromMFMediaType;
void *ptr_MFCreateAMMediaTypeFromMFMediaType = NULL;
extern void *ptr_MFCreateAlignedMemoryBuffer;
void *ptr_MFCreateAlignedMemoryBuffer = NULL;
extern void *ptr_MFCreateAsyncResult;
void *ptr_MFCreateAsyncResult = NULL;
extern void *ptr_MFCreateAttributes;
void *ptr_MFCreateAttributes = NULL;
extern void *ptr_MFCreateAudioMediaType;
void *ptr_MFCreateAudioMediaType = NULL;
extern void *ptr_MFCreateCollection;
void *ptr_MFCreateCollection = NULL;
extern void *ptr_MFCreateEventQueue;
void *ptr_MFCreateEventQueue = NULL;
extern void *ptr_MFCreateFile;
void *ptr_MFCreateFile = NULL;
extern void *ptr_MFCreateGuid;
void *ptr_MFCreateGuid = NULL;
extern void *ptr_MFCreateLegacyMediaBufferOnMFMediaBuffer;
void *ptr_MFCreateLegacyMediaBufferOnMFMediaBuffer = NULL;
extern void *ptr_MFCreateMFByteStreamOnStream;
void *ptr_MFCreateMFByteStreamOnStream = NULL;
extern void *ptr_MFCreateMFVideoFormatFromMFMediaType;
void *ptr_MFCreateMFVideoFormatFromMFMediaType = NULL;
extern void *ptr_MFCreateMediaBufferWrapper;
void *ptr_MFCreateMediaBufferWrapper = NULL;
extern void *ptr_MFCreateMediaEvent;
void *ptr_MFCreateMediaEvent = NULL;
extern void *ptr_MFCreateMediaType;
void *ptr_MFCreateMediaType = NULL;
extern void *ptr_MFCreateMediaTypeFromRepresentation;
void *ptr_MFCreateMediaTypeFromRepresentation = NULL;
extern void *ptr_MFCreateMemoryBuffer;
void *ptr_MFCreateMemoryBuffer = NULL;
extern void *ptr_MFCreateMemoryStream;
void *ptr_MFCreateMemoryStream = NULL;
extern void *ptr_MFCreatePathFromURL;
void *ptr_MFCreatePathFromURL = NULL;
extern void *ptr_MFCreatePresentationDescriptor;
void *ptr_MFCreatePresentationDescriptor = NULL;
extern void *ptr_MFCreateSample;
void *ptr_MFCreateSample = NULL;
extern void *ptr_MFCreateSocket;
void *ptr_MFCreateSocket = NULL;
extern void *ptr_MFCreateSocketListener;
void *ptr_MFCreateSocketListener = NULL;
extern void *ptr_MFCreateSourceResolver;
void *ptr_MFCreateSourceResolver = NULL;
extern void *ptr_MFCreateStreamDescriptor;
void *ptr_MFCreateStreamDescriptor = NULL;
extern void *ptr_MFCreateSystemTimeSource;
void *ptr_MFCreateSystemTimeSource = NULL;
extern void *ptr_MFCreateSystemUnderlyingClock;
void *ptr_MFCreateSystemUnderlyingClock = NULL;
extern void *ptr_MFCreateTempFile;
void *ptr_MFCreateTempFile = NULL;
extern void *ptr_MFCreateTransformActivate;
void *ptr_MFCreateTransformActivate = NULL;
extern void *ptr_MFCreateURLFromPath;
void *ptr_MFCreateURLFromPath = NULL;
extern void *ptr_MFCreateUdpSockets;
void *ptr_MFCreateUdpSockets = NULL;
extern void *ptr_MFCreateVideoMediaType;
void *ptr_MFCreateVideoMediaType = NULL;
extern void *ptr_MFCreateVideoMediaTypeFromBitMapInfoHeader;
void *ptr_MFCreateVideoMediaTypeFromBitMapInfoHeader = NULL;
extern void *ptr_MFCreateVideoMediaTypeFromBitMapInfoHeaderEx;
void *ptr_MFCreateVideoMediaTypeFromBitMapInfoHeaderEx = NULL;
extern void *ptr_MFCreateVideoMediaTypeFromSubtype;
void *ptr_MFCreateVideoMediaTypeFromSubtype = NULL;
extern void *ptr_MFCreateVideoMediaTypeFromVideoInfoHeader;
void *ptr_MFCreateVideoMediaTypeFromVideoInfoHeader = NULL;
extern void *ptr_MFCreateVideoMediaTypeFromVideoInfoHeader2;
void *ptr_MFCreateVideoMediaTypeFromVideoInfoHeader2 = NULL;
extern void *ptr_MFCreateWaveFormatExFromMFMediaType;
void *ptr_MFCreateWaveFormatExFromMFMediaType = NULL;
extern void *ptr_MFDeserializeAttributesFromStream;
void *ptr_MFDeserializeAttributesFromStream = NULL;
extern void *ptr_MFDeserializeEvent;
void *ptr_MFDeserializeEvent = NULL;
extern void *ptr_MFDeserializeMediaTypeFromStream;
void *ptr_MFDeserializeMediaTypeFromStream = NULL;
extern void *ptr_MFDeserializePresentationDescriptor;
void *ptr_MFDeserializePresentationDescriptor = NULL;
extern void *ptr_MFEndCreateFile;
void *ptr_MFEndCreateFile = NULL;
extern void *ptr_MFEndGetHostByName;
void *ptr_MFEndGetHostByName = NULL;
extern void *ptr_MFEndRegisterWorkQueueWithMMCSS;
void *ptr_MFEndRegisterWorkQueueWithMMCSS = NULL;
extern void *ptr_MFEndUnregisterWorkQueueWithMMCSS;
void *ptr_MFEndUnregisterWorkQueueWithMMCSS = NULL;
extern void *ptr_MFFrameRateToAverageTimePerFrame;
void *ptr_MFFrameRateToAverageTimePerFrame = NULL;
extern void *ptr_MFFreeAdaptersAddresses;
void *ptr_MFFreeAdaptersAddresses = NULL;
extern void *ptr_MFGetAdaptersAddresses;
void *ptr_MFGetAdaptersAddresses = NULL;
extern void *ptr_MFGetAttributesAsBlob;
void *ptr_MFGetAttributesAsBlob = NULL;
extern void *ptr_MFGetAttributesAsBlobSize;
void *ptr_MFGetAttributesAsBlobSize = NULL;
extern void *ptr_MFGetConfigurationDWORD;
void *ptr_MFGetConfigurationDWORD = NULL;
extern void *ptr_MFGetConfigurationPolicy;
void *ptr_MFGetConfigurationPolicy = NULL;
extern void *ptr_MFGetConfigurationStore;
void *ptr_MFGetConfigurationStore = NULL;
extern void *ptr_MFGetConfigurationString;
void *ptr_MFGetConfigurationString = NULL;
extern void *ptr_MFGetIoPortHandle;
void *ptr_MFGetIoPortHandle = NULL;
extern void *ptr_MFGetMFTMerit;
void *ptr_MFGetMFTMerit = NULL;
extern void *ptr_MFGetNumericNameFromSockaddr;
void *ptr_MFGetNumericNameFromSockaddr = NULL;
extern void *ptr_MFGetPlaneSize;
void *ptr_MFGetPlaneSize = NULL;
extern void *ptr_MFGetPlatform;
void *ptr_MFGetPlatform = NULL;
extern void *ptr_MFGetPlatformVersion;
void *ptr_MFGetPlatformVersion = NULL;
extern void *ptr_MFGetPluginControl;
void *ptr_MFGetPluginControl = NULL;
extern void *ptr_MFGetPrivateWorkqueues;
void *ptr_MFGetPrivateWorkqueues = NULL;
extern void *ptr_MFGetRandomNumber;
void *ptr_MFGetRandomNumber = NULL;
extern void *ptr_MFGetSockaddrFromNumericName;
void *ptr_MFGetSockaddrFromNumericName = NULL;
extern void *ptr_MFGetStrideForBitmapInfoHeader;
void *ptr_MFGetStrideForBitmapInfoHeader = NULL;
extern void *ptr_MFGetSystemTime;
void *ptr_MFGetSystemTime = NULL;
extern void *ptr_MFGetTimerPeriodicity;
void *ptr_MFGetTimerPeriodicity = NULL;
extern void *ptr_MFGetUncompressedVideoFormat;
void *ptr_MFGetUncompressedVideoFormat = NULL;
extern void *ptr_MFGetWorkQueueMMCSSClass;
void *ptr_MFGetWorkQueueMMCSSClass = NULL;
extern void *ptr_MFGetWorkQueueMMCSSTaskId;
void *ptr_MFGetWorkQueueMMCSSTaskId = NULL;
extern void *ptr_MFHeapAlloc;
void *ptr_MFHeapAlloc = NULL;
extern void *ptr_MFHeapFree;
void *ptr_MFHeapFree = NULL;
extern void *ptr_MFInitAMMediaTypeFromMFMediaType;
void *ptr_MFInitAMMediaTypeFromMFMediaType = NULL;
extern void *ptr_MFInitAttributesFromBlob;
void *ptr_MFInitAttributesFromBlob = NULL;
extern void *ptr_MFInitMediaTypeFromAMMediaType;
void *ptr_MFInitMediaTypeFromAMMediaType = NULL;
extern void *ptr_MFInitMediaTypeFromMFVideoFormat;
void *ptr_MFInitMediaTypeFromMFVideoFormat = NULL;
extern void *ptr_MFInitMediaTypeFromMPEG1VideoInfo;
void *ptr_MFInitMediaTypeFromMPEG1VideoInfo = NULL;
extern void *ptr_MFInitMediaTypeFromMPEG2VideoInfo;
void *ptr_MFInitMediaTypeFromMPEG2VideoInfo = NULL;
extern void *ptr_MFInitMediaTypeFromVideoInfoHeader;
void *ptr_MFInitMediaTypeFromVideoInfoHeader = NULL;
extern void *ptr_MFInitMediaTypeFromVideoInfoHeader2;
void *ptr_MFInitMediaTypeFromVideoInfoHeader2 = NULL;
extern void *ptr_MFInitMediaTypeFromWaveFormatEx;
void *ptr_MFInitMediaTypeFromWaveFormatEx = NULL;
extern void *ptr_MFInitVideoFormat;
void *ptr_MFInitVideoFormat = NULL;
extern void *ptr_MFInitVideoFormat_RGB;
void *ptr_MFInitVideoFormat_RGB = NULL;
extern void *ptr_MFInvokeCallback;
void *ptr_MFInvokeCallback = NULL;
extern void *ptr_MFIsFeatureEnabled;
void *ptr_MFIsFeatureEnabled = NULL;
extern void *ptr_MFIsQueueThread;
void *ptr_MFIsQueueThread = NULL;
extern void *ptr_MFJoinIoPort;
void *ptr_MFJoinIoPort = NULL;
extern void *ptr_MFLockPlatform;
void *ptr_MFLockPlatform = NULL;
extern void *ptr_MFLockWorkQueue;
void *ptr_MFLockWorkQueue = NULL;
extern void *ptr_MFPlatformBigEndian;
void *ptr_MFPlatformBigEndian = NULL;
extern void *ptr_MFPlatformLittleEndian;
void *ptr_MFPlatformLittleEndian = NULL;
extern void *ptr_MFPutWorkItem;
void *ptr_MFPutWorkItem = NULL;
extern void *ptr_MFPutWorkItemEx;
void *ptr_MFPutWorkItemEx = NULL;
extern void *ptr_MFRecordError;
void *ptr_MFRecordError = NULL;
extern void *ptr_MFRemovePeriodicCallback;
void *ptr_MFRemovePeriodicCallback = NULL;
extern void *ptr_MFScheduleWorkItem;
void *ptr_MFScheduleWorkItem = NULL;
extern void *ptr_MFScheduleWorkItemEx;
void *ptr_MFScheduleWorkItemEx = NULL;
extern void *ptr_MFSerializeAttributesToStream;
void *ptr_MFSerializeAttributesToStream = NULL;
extern void *ptr_MFSerializeEvent;
void *ptr_MFSerializeEvent = NULL;
extern void *ptr_MFSerializeMediaTypeToStream;
void *ptr_MFSerializeMediaTypeToStream = NULL;
extern void *ptr_MFSerializePresentationDescriptor;
void *ptr_MFSerializePresentationDescriptor = NULL;
extern void *ptr_MFSetSockaddrAny;
void *ptr_MFSetSockaddrAny = NULL;
extern void *ptr_MFShutdown;
void *ptr_MFShutdown = NULL;
extern void *ptr_MFStartup;
void *ptr_MFStartup = NULL;
extern void *ptr_MFStreamDescriptorProtectMediaType;
void *ptr_MFStreamDescriptorProtectMediaType = NULL;
extern void *ptr_MFTEnum;
void *ptr_MFTEnum = NULL;
extern void *ptr_MFTEnumEx;
void *ptr_MFTEnumEx = NULL;
extern void *ptr_MFTGetInfo;
void *ptr_MFTGetInfo = NULL;
extern void *ptr_MFTRegister;
void *ptr_MFTRegister = NULL;
extern void *ptr_MFTRegisterLocal;
void *ptr_MFTRegisterLocal = NULL;
extern void *ptr_MFTRegisterLocalByCLSID;
void *ptr_MFTRegisterLocalByCLSID = NULL;
extern void *ptr_MFTUnregister;
void *ptr_MFTUnregister = NULL;
extern void *ptr_MFTUnregisterLocal;
void *ptr_MFTUnregisterLocal = NULL;
extern void *ptr_MFTUnregisterLocalByCLSID;
void *ptr_MFTUnregisterLocalByCLSID = NULL;
extern void *ptr_MFTraceError;
void *ptr_MFTraceError = NULL;
extern void *ptr_MFTraceFuncEnter;
void *ptr_MFTraceFuncEnter = NULL;
extern void *ptr_MFUnblockThread;
void *ptr_MFUnblockThread = NULL;
extern void *ptr_MFUnlockPlatform;
void *ptr_MFUnlockPlatform = NULL;
extern void *ptr_MFUnlockWorkQueue;
void *ptr_MFUnlockWorkQueue = NULL;
extern void *ptr_MFUnwrapMediaType;
void *ptr_MFUnwrapMediaType = NULL;
extern void *ptr_MFValidateMediaTypeSize;
void *ptr_MFValidateMediaTypeSize = NULL;
extern void *ptr_MFWrapMediaType;
void *ptr_MFWrapMediaType = NULL;
extern void *ptr_MFllMulDiv;
void *ptr_MFllMulDiv = NULL;
extern void *ptr_PropVariantFromStream;
void *ptr_PropVariantFromStream = NULL;
extern void *ptr_PropVariantToStream;
void *ptr_PropVariantToStream = NULL;
extern void *ptr_ValidateWaveFormat;
void *ptr_ValidateWaveFormat = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\mfplat.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_CopyPropVariant = (__vartype(ptr_CopyPropVariant))GetProcAddress(hModule, "CopyPropVariant");
   ptr_CreatePropVariant = (__vartype(ptr_CreatePropVariant))GetProcAddress(hModule, "CreatePropVariant");
   ptr_CreatePropertyStore = (__vartype(ptr_CreatePropertyStore))GetProcAddress(hModule, "CreatePropertyStore");
   ptr_DestroyPropVariant = (__vartype(ptr_DestroyPropVariant))GetProcAddress(hModule, "DestroyPropVariant");
   ptr_FormatTagFromWfx = (__vartype(ptr_FormatTagFromWfx))GetProcAddress(hModule, "FormatTagFromWfx");
   ptr_GetAMSubtypeFromD3DFormat = (__vartype(ptr_GetAMSubtypeFromD3DFormat))GetProcAddress(hModule, "GetAMSubtypeFromD3DFormat");
   ptr_GetD3DFormatFromMFSubtype = (__vartype(ptr_GetD3DFormatFromMFSubtype))GetProcAddress(hModule, "GetD3DFormatFromMFSubtype");
   ptr_LFGetGlobalPool = (__vartype(ptr_LFGetGlobalPool))GetProcAddress(hModule, "LFGetGlobalPool");
   ptr_MFAddPeriodicCallback = (__vartype(ptr_MFAddPeriodicCallback))GetProcAddress(hModule, "MFAddPeriodicCallback");
   ptr_MFAllocateWorkQueue = (__vartype(ptr_MFAllocateWorkQueue))GetProcAddress(hModule, "MFAllocateWorkQueue");
   ptr_MFAllocateWorkQueueEx = (__vartype(ptr_MFAllocateWorkQueueEx))GetProcAddress(hModule, "MFAllocateWorkQueueEx");
   ptr_MFAppendCollection = (__vartype(ptr_MFAppendCollection))GetProcAddress(hModule, "MFAppendCollection");
   ptr_MFAverageTimePerFrameToFrameRate = (__vartype(ptr_MFAverageTimePerFrameToFrameRate))GetProcAddress(hModule, "MFAverageTimePerFrameToFrameRate");
   ptr_MFBeginCreateFile = (__vartype(ptr_MFBeginCreateFile))GetProcAddress(hModule, "MFBeginCreateFile");
   ptr_MFBeginGetHostByName = (__vartype(ptr_MFBeginGetHostByName))GetProcAddress(hModule, "MFBeginGetHostByName");
   ptr_MFBeginRegisterWorkQueueWithMMCSS = (__vartype(ptr_MFBeginRegisterWorkQueueWithMMCSS))GetProcAddress(hModule, "MFBeginRegisterWorkQueueWithMMCSS");
   ptr_MFBeginUnregisterWorkQueueWithMMCSS = (__vartype(ptr_MFBeginUnregisterWorkQueueWithMMCSS))GetProcAddress(hModule, "MFBeginUnregisterWorkQueueWithMMCSS");
   ptr_MFBlockThread = (__vartype(ptr_MFBlockThread))GetProcAddress(hModule, "MFBlockThread");
   ptr_MFCalculateBitmapImageSize = (__vartype(ptr_MFCalculateBitmapImageSize))GetProcAddress(hModule, "MFCalculateBitmapImageSize");
   ptr_MFCalculateImageSize = (__vartype(ptr_MFCalculateImageSize))GetProcAddress(hModule, "MFCalculateImageSize");
   ptr_MFCancelCreateFile = (__vartype(ptr_MFCancelCreateFile))GetProcAddress(hModule, "MFCancelCreateFile");
   ptr_MFCancelWorkItem = (__vartype(ptr_MFCancelWorkItem))GetProcAddress(hModule, "MFCancelWorkItem");
   ptr_MFCompareFullToPartialMediaType = (__vartype(ptr_MFCompareFullToPartialMediaType))GetProcAddress(hModule, "MFCompareFullToPartialMediaType");
   ptr_MFCompareSockaddrAddresses = (__vartype(ptr_MFCompareSockaddrAddresses))GetProcAddress(hModule, "MFCompareSockaddrAddresses");
   ptr_MFConvertColorInfoFromDXVA = (__vartype(ptr_MFConvertColorInfoFromDXVA))GetProcAddress(hModule, "MFConvertColorInfoFromDXVA");
   ptr_MFConvertColorInfoToDXVA = (__vartype(ptr_MFConvertColorInfoToDXVA))GetProcAddress(hModule, "MFConvertColorInfoToDXVA");
   ptr_MFConvertFromFP16Array = (__vartype(ptr_MFConvertFromFP16Array))GetProcAddress(hModule, "MFConvertFromFP16Array");
   ptr_MFConvertToFP16Array = (__vartype(ptr_MFConvertToFP16Array))GetProcAddress(hModule, "MFConvertToFP16Array");
   ptr_MFCopyImage = (__vartype(ptr_MFCopyImage))GetProcAddress(hModule, "MFCopyImage");
   ptr_MFCreateAMMediaTypeFromMFMediaType = (__vartype(ptr_MFCreateAMMediaTypeFromMFMediaType))GetProcAddress(hModule, "MFCreateAMMediaTypeFromMFMediaType");
   ptr_MFCreateAlignedMemoryBuffer = (__vartype(ptr_MFCreateAlignedMemoryBuffer))GetProcAddress(hModule, "MFCreateAlignedMemoryBuffer");
   ptr_MFCreateAsyncResult = (__vartype(ptr_MFCreateAsyncResult))GetProcAddress(hModule, "MFCreateAsyncResult");
   ptr_MFCreateAttributes = (__vartype(ptr_MFCreateAttributes))GetProcAddress(hModule, "MFCreateAttributes");
   ptr_MFCreateAudioMediaType = (__vartype(ptr_MFCreateAudioMediaType))GetProcAddress(hModule, "MFCreateAudioMediaType");
   ptr_MFCreateCollection = (__vartype(ptr_MFCreateCollection))GetProcAddress(hModule, "MFCreateCollection");
   ptr_MFCreateEventQueue = (__vartype(ptr_MFCreateEventQueue))GetProcAddress(hModule, "MFCreateEventQueue");
   ptr_MFCreateFile = (__vartype(ptr_MFCreateFile))GetProcAddress(hModule, "MFCreateFile");
   ptr_MFCreateGuid = (__vartype(ptr_MFCreateGuid))GetProcAddress(hModule, "MFCreateGuid");
   ptr_MFCreateLegacyMediaBufferOnMFMediaBuffer = (__vartype(ptr_MFCreateLegacyMediaBufferOnMFMediaBuffer))GetProcAddress(hModule, "MFCreateLegacyMediaBufferOnMFMediaBuffer");
   ptr_MFCreateMFByteStreamOnStream = (__vartype(ptr_MFCreateMFByteStreamOnStream))GetProcAddress(hModule, "MFCreateMFByteStreamOnStream");
   ptr_MFCreateMFVideoFormatFromMFMediaType = (__vartype(ptr_MFCreateMFVideoFormatFromMFMediaType))GetProcAddress(hModule, "MFCreateMFVideoFormatFromMFMediaType");
   ptr_MFCreateMediaBufferWrapper = (__vartype(ptr_MFCreateMediaBufferWrapper))GetProcAddress(hModule, "MFCreateMediaBufferWrapper");
   ptr_MFCreateMediaEvent = (__vartype(ptr_MFCreateMediaEvent))GetProcAddress(hModule, "MFCreateMediaEvent");
   ptr_MFCreateMediaType = (__vartype(ptr_MFCreateMediaType))GetProcAddress(hModule, "MFCreateMediaType");
   ptr_MFCreateMediaTypeFromRepresentation = (__vartype(ptr_MFCreateMediaTypeFromRepresentation))GetProcAddress(hModule, "MFCreateMediaTypeFromRepresentation");
   ptr_MFCreateMemoryBuffer = (__vartype(ptr_MFCreateMemoryBuffer))GetProcAddress(hModule, "MFCreateMemoryBuffer");
   ptr_MFCreateMemoryStream = (__vartype(ptr_MFCreateMemoryStream))GetProcAddress(hModule, "MFCreateMemoryStream");
   ptr_MFCreatePathFromURL = (__vartype(ptr_MFCreatePathFromURL))GetProcAddress(hModule, "MFCreatePathFromURL");
   ptr_MFCreatePresentationDescriptor = (__vartype(ptr_MFCreatePresentationDescriptor))GetProcAddress(hModule, "MFCreatePresentationDescriptor");
   ptr_MFCreateSample = (__vartype(ptr_MFCreateSample))GetProcAddress(hModule, "MFCreateSample");
   ptr_MFCreateSocket = (__vartype(ptr_MFCreateSocket))GetProcAddress(hModule, "MFCreateSocket");
   ptr_MFCreateSocketListener = (__vartype(ptr_MFCreateSocketListener))GetProcAddress(hModule, "MFCreateSocketListener");
   ptr_MFCreateSourceResolver = (__vartype(ptr_MFCreateSourceResolver))GetProcAddress(hModule, "MFCreateSourceResolver");
   ptr_MFCreateStreamDescriptor = (__vartype(ptr_MFCreateStreamDescriptor))GetProcAddress(hModule, "MFCreateStreamDescriptor");
   ptr_MFCreateSystemTimeSource = (__vartype(ptr_MFCreateSystemTimeSource))GetProcAddress(hModule, "MFCreateSystemTimeSource");
   ptr_MFCreateSystemUnderlyingClock = (__vartype(ptr_MFCreateSystemUnderlyingClock))GetProcAddress(hModule, "MFCreateSystemUnderlyingClock");
   ptr_MFCreateTempFile = (__vartype(ptr_MFCreateTempFile))GetProcAddress(hModule, "MFCreateTempFile");
   ptr_MFCreateTransformActivate = (__vartype(ptr_MFCreateTransformActivate))GetProcAddress(hModule, "MFCreateTransformActivate");
   ptr_MFCreateURLFromPath = (__vartype(ptr_MFCreateURLFromPath))GetProcAddress(hModule, "MFCreateURLFromPath");
   ptr_MFCreateUdpSockets = (__vartype(ptr_MFCreateUdpSockets))GetProcAddress(hModule, "MFCreateUdpSockets");
   ptr_MFCreateVideoMediaType = (__vartype(ptr_MFCreateVideoMediaType))GetProcAddress(hModule, "MFCreateVideoMediaType");
   ptr_MFCreateVideoMediaTypeFromBitMapInfoHeader = (__vartype(ptr_MFCreateVideoMediaTypeFromBitMapInfoHeader))GetProcAddress(hModule, "MFCreateVideoMediaTypeFromBitMapInfoHeader");
   ptr_MFCreateVideoMediaTypeFromBitMapInfoHeaderEx = (__vartype(ptr_MFCreateVideoMediaTypeFromBitMapInfoHeaderEx))GetProcAddress(hModule, "MFCreateVideoMediaTypeFromBitMapInfoHeaderEx");
   ptr_MFCreateVideoMediaTypeFromSubtype = (__vartype(ptr_MFCreateVideoMediaTypeFromSubtype))GetProcAddress(hModule, "MFCreateVideoMediaTypeFromSubtype");
   ptr_MFCreateVideoMediaTypeFromVideoInfoHeader = (__vartype(ptr_MFCreateVideoMediaTypeFromVideoInfoHeader))GetProcAddress(hModule, "MFCreateVideoMediaTypeFromVideoInfoHeader");
   ptr_MFCreateVideoMediaTypeFromVideoInfoHeader2 = (__vartype(ptr_MFCreateVideoMediaTypeFromVideoInfoHeader2))GetProcAddress(hModule, "MFCreateVideoMediaTypeFromVideoInfoHeader2");
   ptr_MFCreateWaveFormatExFromMFMediaType = (__vartype(ptr_MFCreateWaveFormatExFromMFMediaType))GetProcAddress(hModule, "MFCreateWaveFormatExFromMFMediaType");
   ptr_MFDeserializeAttributesFromStream = (__vartype(ptr_MFDeserializeAttributesFromStream))GetProcAddress(hModule, "MFDeserializeAttributesFromStream");
   ptr_MFDeserializeEvent = (__vartype(ptr_MFDeserializeEvent))GetProcAddress(hModule, "MFDeserializeEvent");
   ptr_MFDeserializeMediaTypeFromStream = (__vartype(ptr_MFDeserializeMediaTypeFromStream))GetProcAddress(hModule, "MFDeserializeMediaTypeFromStream");
   ptr_MFDeserializePresentationDescriptor = (__vartype(ptr_MFDeserializePresentationDescriptor))GetProcAddress(hModule, "MFDeserializePresentationDescriptor");
   ptr_MFEndCreateFile = (__vartype(ptr_MFEndCreateFile))GetProcAddress(hModule, "MFEndCreateFile");
   ptr_MFEndGetHostByName = (__vartype(ptr_MFEndGetHostByName))GetProcAddress(hModule, "MFEndGetHostByName");
   ptr_MFEndRegisterWorkQueueWithMMCSS = (__vartype(ptr_MFEndRegisterWorkQueueWithMMCSS))GetProcAddress(hModule, "MFEndRegisterWorkQueueWithMMCSS");
   ptr_MFEndUnregisterWorkQueueWithMMCSS = (__vartype(ptr_MFEndUnregisterWorkQueueWithMMCSS))GetProcAddress(hModule, "MFEndUnregisterWorkQueueWithMMCSS");
   ptr_MFFrameRateToAverageTimePerFrame = (__vartype(ptr_MFFrameRateToAverageTimePerFrame))GetProcAddress(hModule, "MFFrameRateToAverageTimePerFrame");
   ptr_MFFreeAdaptersAddresses = (__vartype(ptr_MFFreeAdaptersAddresses))GetProcAddress(hModule, "MFFreeAdaptersAddresses");
   ptr_MFGetAdaptersAddresses = (__vartype(ptr_MFGetAdaptersAddresses))GetProcAddress(hModule, "MFGetAdaptersAddresses");
   ptr_MFGetAttributesAsBlob = (__vartype(ptr_MFGetAttributesAsBlob))GetProcAddress(hModule, "MFGetAttributesAsBlob");
   ptr_MFGetAttributesAsBlobSize = (__vartype(ptr_MFGetAttributesAsBlobSize))GetProcAddress(hModule, "MFGetAttributesAsBlobSize");
   ptr_MFGetConfigurationDWORD = (__vartype(ptr_MFGetConfigurationDWORD))GetProcAddress(hModule, "MFGetConfigurationDWORD");
   ptr_MFGetConfigurationPolicy = (__vartype(ptr_MFGetConfigurationPolicy))GetProcAddress(hModule, "MFGetConfigurationPolicy");
   ptr_MFGetConfigurationStore = (__vartype(ptr_MFGetConfigurationStore))GetProcAddress(hModule, "MFGetConfigurationStore");
   ptr_MFGetConfigurationString = (__vartype(ptr_MFGetConfigurationString))GetProcAddress(hModule, "MFGetConfigurationString");
   ptr_MFGetIoPortHandle = (__vartype(ptr_MFGetIoPortHandle))GetProcAddress(hModule, "MFGetIoPortHandle");
   ptr_MFGetMFTMerit = (__vartype(ptr_MFGetMFTMerit))GetProcAddress(hModule, "MFGetMFTMerit");
   ptr_MFGetNumericNameFromSockaddr = (__vartype(ptr_MFGetNumericNameFromSockaddr))GetProcAddress(hModule, "MFGetNumericNameFromSockaddr");
   ptr_MFGetPlaneSize = (__vartype(ptr_MFGetPlaneSize))GetProcAddress(hModule, "MFGetPlaneSize");
   ptr_MFGetPlatform = (__vartype(ptr_MFGetPlatform))GetProcAddress(hModule, "MFGetPlatform");
   ptr_MFGetPlatformVersion = (__vartype(ptr_MFGetPlatformVersion))GetProcAddress(hModule, "MFGetPlatformVersion");
   ptr_MFGetPluginControl = (__vartype(ptr_MFGetPluginControl))GetProcAddress(hModule, "MFGetPluginControl");
   ptr_MFGetPrivateWorkqueues = (__vartype(ptr_MFGetPrivateWorkqueues))GetProcAddress(hModule, "MFGetPrivateWorkqueues");
   ptr_MFGetRandomNumber = (__vartype(ptr_MFGetRandomNumber))GetProcAddress(hModule, "MFGetRandomNumber");
   ptr_MFGetSockaddrFromNumericName = (__vartype(ptr_MFGetSockaddrFromNumericName))GetProcAddress(hModule, "MFGetSockaddrFromNumericName");
   ptr_MFGetStrideForBitmapInfoHeader = (__vartype(ptr_MFGetStrideForBitmapInfoHeader))GetProcAddress(hModule, "MFGetStrideForBitmapInfoHeader");
   ptr_MFGetSystemTime = (__vartype(ptr_MFGetSystemTime))GetProcAddress(hModule, "MFGetSystemTime");
   ptr_MFGetTimerPeriodicity = (__vartype(ptr_MFGetTimerPeriodicity))GetProcAddress(hModule, "MFGetTimerPeriodicity");
   ptr_MFGetUncompressedVideoFormat = (__vartype(ptr_MFGetUncompressedVideoFormat))GetProcAddress(hModule, "MFGetUncompressedVideoFormat");
   ptr_MFGetWorkQueueMMCSSClass = (__vartype(ptr_MFGetWorkQueueMMCSSClass))GetProcAddress(hModule, "MFGetWorkQueueMMCSSClass");
   ptr_MFGetWorkQueueMMCSSTaskId = (__vartype(ptr_MFGetWorkQueueMMCSSTaskId))GetProcAddress(hModule, "MFGetWorkQueueMMCSSTaskId");
   ptr_MFHeapAlloc = (__vartype(ptr_MFHeapAlloc))GetProcAddress(hModule, "MFHeapAlloc");
   ptr_MFHeapFree = (__vartype(ptr_MFHeapFree))GetProcAddress(hModule, "MFHeapFree");
   ptr_MFInitAMMediaTypeFromMFMediaType = (__vartype(ptr_MFInitAMMediaTypeFromMFMediaType))GetProcAddress(hModule, "MFInitAMMediaTypeFromMFMediaType");
   ptr_MFInitAttributesFromBlob = (__vartype(ptr_MFInitAttributesFromBlob))GetProcAddress(hModule, "MFInitAttributesFromBlob");
   ptr_MFInitMediaTypeFromAMMediaType = (__vartype(ptr_MFInitMediaTypeFromAMMediaType))GetProcAddress(hModule, "MFInitMediaTypeFromAMMediaType");
   ptr_MFInitMediaTypeFromMFVideoFormat = (__vartype(ptr_MFInitMediaTypeFromMFVideoFormat))GetProcAddress(hModule, "MFInitMediaTypeFromMFVideoFormat");
   ptr_MFInitMediaTypeFromMPEG1VideoInfo = (__vartype(ptr_MFInitMediaTypeFromMPEG1VideoInfo))GetProcAddress(hModule, "MFInitMediaTypeFromMPEG1VideoInfo");
   ptr_MFInitMediaTypeFromMPEG2VideoInfo = (__vartype(ptr_MFInitMediaTypeFromMPEG2VideoInfo))GetProcAddress(hModule, "MFInitMediaTypeFromMPEG2VideoInfo");
   ptr_MFInitMediaTypeFromVideoInfoHeader = (__vartype(ptr_MFInitMediaTypeFromVideoInfoHeader))GetProcAddress(hModule, "MFInitMediaTypeFromVideoInfoHeader");
   ptr_MFInitMediaTypeFromVideoInfoHeader2 = (__vartype(ptr_MFInitMediaTypeFromVideoInfoHeader2))GetProcAddress(hModule, "MFInitMediaTypeFromVideoInfoHeader2");
   ptr_MFInitMediaTypeFromWaveFormatEx = (__vartype(ptr_MFInitMediaTypeFromWaveFormatEx))GetProcAddress(hModule, "MFInitMediaTypeFromWaveFormatEx");
   ptr_MFInitVideoFormat = (__vartype(ptr_MFInitVideoFormat))GetProcAddress(hModule, "MFInitVideoFormat");
   ptr_MFInitVideoFormat_RGB = (__vartype(ptr_MFInitVideoFormat_RGB))GetProcAddress(hModule, "MFInitVideoFormat_RGB");
   ptr_MFInvokeCallback = (__vartype(ptr_MFInvokeCallback))GetProcAddress(hModule, "MFInvokeCallback");
   ptr_MFIsFeatureEnabled = (__vartype(ptr_MFIsFeatureEnabled))GetProcAddress(hModule, "MFIsFeatureEnabled");
   ptr_MFIsQueueThread = (__vartype(ptr_MFIsQueueThread))GetProcAddress(hModule, "MFIsQueueThread");
   ptr_MFJoinIoPort = (__vartype(ptr_MFJoinIoPort))GetProcAddress(hModule, "MFJoinIoPort");
   ptr_MFLockPlatform = (__vartype(ptr_MFLockPlatform))GetProcAddress(hModule, "MFLockPlatform");
   ptr_MFLockWorkQueue = (__vartype(ptr_MFLockWorkQueue))GetProcAddress(hModule, "MFLockWorkQueue");
   ptr_MFPlatformBigEndian = (__vartype(ptr_MFPlatformBigEndian))GetProcAddress(hModule, "MFPlatformBigEndian");
   ptr_MFPlatformLittleEndian = (__vartype(ptr_MFPlatformLittleEndian))GetProcAddress(hModule, "MFPlatformLittleEndian");
   ptr_MFPutWorkItem = (__vartype(ptr_MFPutWorkItem))GetProcAddress(hModule, "MFPutWorkItem");
   ptr_MFPutWorkItemEx = (__vartype(ptr_MFPutWorkItemEx))GetProcAddress(hModule, "MFPutWorkItemEx");
   ptr_MFRecordError = (__vartype(ptr_MFRecordError))GetProcAddress(hModule, "MFRecordError");
   ptr_MFRemovePeriodicCallback = (__vartype(ptr_MFRemovePeriodicCallback))GetProcAddress(hModule, "MFRemovePeriodicCallback");
   ptr_MFScheduleWorkItem = (__vartype(ptr_MFScheduleWorkItem))GetProcAddress(hModule, "MFScheduleWorkItem");
   ptr_MFScheduleWorkItemEx = (__vartype(ptr_MFScheduleWorkItemEx))GetProcAddress(hModule, "MFScheduleWorkItemEx");
   ptr_MFSerializeAttributesToStream = (__vartype(ptr_MFSerializeAttributesToStream))GetProcAddress(hModule, "MFSerializeAttributesToStream");
   ptr_MFSerializeEvent = (__vartype(ptr_MFSerializeEvent))GetProcAddress(hModule, "MFSerializeEvent");
   ptr_MFSerializeMediaTypeToStream = (__vartype(ptr_MFSerializeMediaTypeToStream))GetProcAddress(hModule, "MFSerializeMediaTypeToStream");
   ptr_MFSerializePresentationDescriptor = (__vartype(ptr_MFSerializePresentationDescriptor))GetProcAddress(hModule, "MFSerializePresentationDescriptor");
   ptr_MFSetSockaddrAny = (__vartype(ptr_MFSetSockaddrAny))GetProcAddress(hModule, "MFSetSockaddrAny");
   ptr_MFShutdown = (__vartype(ptr_MFShutdown))GetProcAddress(hModule, "MFShutdown");
   ptr_MFStartup = (__vartype(ptr_MFStartup))GetProcAddress(hModule, "MFStartup");
   ptr_MFStreamDescriptorProtectMediaType = (__vartype(ptr_MFStreamDescriptorProtectMediaType))GetProcAddress(hModule, "MFStreamDescriptorProtectMediaType");
   ptr_MFTEnum = (__vartype(ptr_MFTEnum))GetProcAddress(hModule, "MFTEnum");
   ptr_MFTEnumEx = (__vartype(ptr_MFTEnumEx))GetProcAddress(hModule, "MFTEnumEx");
   ptr_MFTGetInfo = (__vartype(ptr_MFTGetInfo))GetProcAddress(hModule, "MFTGetInfo");
   ptr_MFTRegister = (__vartype(ptr_MFTRegister))GetProcAddress(hModule, "MFTRegister");
   ptr_MFTRegisterLocal = (__vartype(ptr_MFTRegisterLocal))GetProcAddress(hModule, "MFTRegisterLocal");
   ptr_MFTRegisterLocalByCLSID = (__vartype(ptr_MFTRegisterLocalByCLSID))GetProcAddress(hModule, "MFTRegisterLocalByCLSID");
   ptr_MFTUnregister = (__vartype(ptr_MFTUnregister))GetProcAddress(hModule, "MFTUnregister");
   ptr_MFTUnregisterLocal = (__vartype(ptr_MFTUnregisterLocal))GetProcAddress(hModule, "MFTUnregisterLocal");
   ptr_MFTUnregisterLocalByCLSID = (__vartype(ptr_MFTUnregisterLocalByCLSID))GetProcAddress(hModule, "MFTUnregisterLocalByCLSID");
   ptr_MFTraceError = (__vartype(ptr_MFTraceError))GetProcAddress(hModule, "MFTraceError");
   ptr_MFTraceFuncEnter = (__vartype(ptr_MFTraceFuncEnter))GetProcAddress(hModule, "MFTraceFuncEnter");
   ptr_MFUnblockThread = (__vartype(ptr_MFUnblockThread))GetProcAddress(hModule, "MFUnblockThread");
   ptr_MFUnlockPlatform = (__vartype(ptr_MFUnlockPlatform))GetProcAddress(hModule, "MFUnlockPlatform");
   ptr_MFUnlockWorkQueue = (__vartype(ptr_MFUnlockWorkQueue))GetProcAddress(hModule, "MFUnlockWorkQueue");
   ptr_MFUnwrapMediaType = (__vartype(ptr_MFUnwrapMediaType))GetProcAddress(hModule, "MFUnwrapMediaType");
   ptr_MFValidateMediaTypeSize = (__vartype(ptr_MFValidateMediaTypeSize))GetProcAddress(hModule, "MFValidateMediaTypeSize");
   ptr_MFWrapMediaType = (__vartype(ptr_MFWrapMediaType))GetProcAddress(hModule, "MFWrapMediaType");
   ptr_MFllMulDiv = (__vartype(ptr_MFllMulDiv))GetProcAddress(hModule, "MFllMulDiv");
   ptr_PropVariantFromStream = (__vartype(ptr_PropVariantFromStream))GetProcAddress(hModule, "PropVariantFromStream");
   ptr_PropVariantToStream = (__vartype(ptr_PropVariantToStream))GetProcAddress(hModule, "PropVariantToStream");
   ptr_ValidateWaveFormat = (__vartype(ptr_ValidateWaveFormat))GetProcAddress(hModule, "ValidateWaveFormat");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

