#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_HBA_CloseAdapter;
void *ptr_HBA_CloseAdapter = NULL;
extern void *ptr_HBA_FreeLibrary;
void *ptr_HBA_FreeLibrary = NULL;
extern void *ptr_HBA_GetAdapterAttributes;
void *ptr_HBA_GetAdapterAttributes = NULL;
extern void *ptr_HBA_GetAdapterName;
void *ptr_HBA_GetAdapterName = NULL;
extern void *ptr_HBA_GetAdapterPortAttributes;
void *ptr_HBA_GetAdapterPortAttributes = NULL;
extern void *ptr_HBA_GetBindingCapability;
void *ptr_HBA_GetBindingCapability = NULL;
extern void *ptr_HBA_GetBindingSupport;
void *ptr_HBA_GetBindingSupport = NULL;
extern void *ptr_HBA_GetDiscoveredPortAttributes;
void *ptr_HBA_GetDiscoveredPortAttributes = NULL;
extern void *ptr_HBA_GetEventBuffer;
void *ptr_HBA_GetEventBuffer = NULL;
extern void *ptr_HBA_GetFC4Statistics;
void *ptr_HBA_GetFC4Statistics = NULL;
extern void *ptr_HBA_GetFCPStatistics;
void *ptr_HBA_GetFCPStatistics = NULL;
extern void *ptr_HBA_GetFcpPersistentBinding;
void *ptr_HBA_GetFcpPersistentBinding = NULL;
extern void *ptr_HBA_GetFcpTargetMapping;
void *ptr_HBA_GetFcpTargetMapping = NULL;
extern void *ptr_HBA_GetFcpTargetMappingV2;
void *ptr_HBA_GetFcpTargetMappingV2 = NULL;
extern void *ptr_HBA_GetNumberOfAdapters;
void *ptr_HBA_GetNumberOfAdapters = NULL;
extern void *ptr_HBA_GetPersistentBindingV2;
void *ptr_HBA_GetPersistentBindingV2 = NULL;
extern void *ptr_HBA_GetPortAttributesByWWN;
void *ptr_HBA_GetPortAttributesByWWN = NULL;
extern void *ptr_HBA_GetPortStatistics;
void *ptr_HBA_GetPortStatistics = NULL;
extern void *ptr_HBA_GetRNIDMgmtInfo;
void *ptr_HBA_GetRNIDMgmtInfo = NULL;
extern void *ptr_HBA_GetVendorLibraryAttributes;
void *ptr_HBA_GetVendorLibraryAttributes = NULL;
extern void *ptr_HBA_GetVersion;
void *ptr_HBA_GetVersion = NULL;
extern void *ptr_HBA_GetWrapperLibraryAttributes;
void *ptr_HBA_GetWrapperLibraryAttributes = NULL;
extern void *ptr_HBA_LoadLibrary;
void *ptr_HBA_LoadLibrary = NULL;
extern void *ptr_HBA_OpenAdapter;
void *ptr_HBA_OpenAdapter = NULL;
extern void *ptr_HBA_OpenAdapterByWWN;
void *ptr_HBA_OpenAdapterByWWN = NULL;
extern void *ptr_HBA_RefreshAdapterConfiguration;
void *ptr_HBA_RefreshAdapterConfiguration = NULL;
extern void *ptr_HBA_RefreshInformation;
void *ptr_HBA_RefreshInformation = NULL;
extern void *ptr_HBA_RegisterForAdapterAddEvents;
void *ptr_HBA_RegisterForAdapterAddEvents = NULL;
extern void *ptr_HBA_RegisterForAdapterEvents;
void *ptr_HBA_RegisterForAdapterEvents = NULL;
extern void *ptr_HBA_RegisterForAdapterPortEvents;
void *ptr_HBA_RegisterForAdapterPortEvents = NULL;
extern void *ptr_HBA_RegisterForAdapterPortStatEvents;
void *ptr_HBA_RegisterForAdapterPortStatEvents = NULL;
extern void *ptr_HBA_RegisterForLinkEvents;
void *ptr_HBA_RegisterForLinkEvents = NULL;
extern void *ptr_HBA_RegisterForTargetEvents;
void *ptr_HBA_RegisterForTargetEvents = NULL;
extern void *ptr_HBA_RegisterLibrary;
void *ptr_HBA_RegisterLibrary = NULL;
extern void *ptr_HBA_RegisterLibraryV2;
void *ptr_HBA_RegisterLibraryV2 = NULL;
extern void *ptr_HBA_RemoveAllPersistentBindings;
void *ptr_HBA_RemoveAllPersistentBindings = NULL;
extern void *ptr_HBA_RemoveCallback;
void *ptr_HBA_RemoveCallback = NULL;
extern void *ptr_HBA_RemovePersistentBinding;
void *ptr_HBA_RemovePersistentBinding = NULL;
extern void *ptr_HBA_ResetStatistics;
void *ptr_HBA_ResetStatistics = NULL;
extern void *ptr_HBA_ScsiInquiryV2;
void *ptr_HBA_ScsiInquiryV2 = NULL;
extern void *ptr_HBA_ScsiReadCapacityV2;
void *ptr_HBA_ScsiReadCapacityV2 = NULL;
extern void *ptr_HBA_ScsiReportLUNsV2;
void *ptr_HBA_ScsiReportLUNsV2 = NULL;
extern void *ptr_HBA_SendCTPassThru;
void *ptr_HBA_SendCTPassThru = NULL;
extern void *ptr_HBA_SendCTPassThruV2;
void *ptr_HBA_SendCTPassThruV2 = NULL;
extern void *ptr_HBA_SendLIRR;
void *ptr_HBA_SendLIRR = NULL;
extern void *ptr_HBA_SendRLS;
void *ptr_HBA_SendRLS = NULL;
extern void *ptr_HBA_SendRNID;
void *ptr_HBA_SendRNID = NULL;
extern void *ptr_HBA_SendRNIDV2;
void *ptr_HBA_SendRNIDV2 = NULL;
extern void *ptr_HBA_SendRPL;
void *ptr_HBA_SendRPL = NULL;
extern void *ptr_HBA_SendRPS;
void *ptr_HBA_SendRPS = NULL;
extern void *ptr_HBA_SendReadCapacity;
void *ptr_HBA_SendReadCapacity = NULL;
extern void *ptr_HBA_SendReportLUNs;
void *ptr_HBA_SendReportLUNs = NULL;
extern void *ptr_HBA_SendSRL;
void *ptr_HBA_SendSRL = NULL;
extern void *ptr_HBA_SendScsiInquiry;
void *ptr_HBA_SendScsiInquiry = NULL;
extern void *ptr_HBA_SetBindingSupport;
void *ptr_HBA_SetBindingSupport = NULL;
extern void *ptr_HBA_SetPersistentBindingV2;
void *ptr_HBA_SetPersistentBindingV2 = NULL;
extern void *ptr_HBA_SetRNIDMgmtInfo;
void *ptr_HBA_SetRNIDMgmtInfo = NULL;
extern void *ptr_HbaGetAdapterNameByDeviceInstanceId;
void *ptr_HbaGetAdapterNameByDeviceInstanceId = NULL;
extern void *ptr_SMHBA_GetAdapterAttributes;
void *ptr_SMHBA_GetAdapterAttributes = NULL;
extern void *ptr_SMHBA_GetAdapterPortAttributes;
void *ptr_SMHBA_GetAdapterPortAttributes = NULL;
extern void *ptr_SMHBA_GetBindingCapability;
void *ptr_SMHBA_GetBindingCapability = NULL;
extern void *ptr_SMHBA_GetBindingSupport;
void *ptr_SMHBA_GetBindingSupport = NULL;
extern void *ptr_SMHBA_GetDiscoveredPortAttributes;
void *ptr_SMHBA_GetDiscoveredPortAttributes = NULL;
extern void *ptr_SMHBA_GetFCPhyAttributes;
void *ptr_SMHBA_GetFCPhyAttributes = NULL;
extern void *ptr_SMHBA_GetLUNStatistics;
void *ptr_SMHBA_GetLUNStatistics = NULL;
extern void *ptr_SMHBA_GetNumberOfPorts;
void *ptr_SMHBA_GetNumberOfPorts = NULL;
extern void *ptr_SMHBA_GetPersistentBinding;
void *ptr_SMHBA_GetPersistentBinding = NULL;
extern void *ptr_SMHBA_GetPhyStatistics;
void *ptr_SMHBA_GetPhyStatistics = NULL;
extern void *ptr_SMHBA_GetPortAttributesByWWN;
void *ptr_SMHBA_GetPortAttributesByWWN = NULL;
extern void *ptr_SMHBA_GetPortType;
void *ptr_SMHBA_GetPortType = NULL;
extern void *ptr_SMHBA_GetProtocolStatistics;
void *ptr_SMHBA_GetProtocolStatistics = NULL;
extern void *ptr_SMHBA_GetSASPhyAttributes;
void *ptr_SMHBA_GetSASPhyAttributes = NULL;
extern void *ptr_SMHBA_GetTargetMapping;
void *ptr_SMHBA_GetTargetMapping = NULL;
extern void *ptr_SMHBA_GetVendorLibraryAttributes;
void *ptr_SMHBA_GetVendorLibraryAttributes = NULL;
extern void *ptr_SMHBA_GetVersion;
void *ptr_SMHBA_GetVersion = NULL;
extern void *ptr_SMHBA_GetWrapperLibraryAttributes;
void *ptr_SMHBA_GetWrapperLibraryAttributes = NULL;
extern void *ptr_SMHBA_RegisterForAdapterAddEvents;
void *ptr_SMHBA_RegisterForAdapterAddEvents = NULL;
extern void *ptr_SMHBA_RegisterForAdapterEvents;
void *ptr_SMHBA_RegisterForAdapterEvents = NULL;
extern void *ptr_SMHBA_RegisterForAdapterPhyStatEvents;
void *ptr_SMHBA_RegisterForAdapterPhyStatEvents = NULL;
extern void *ptr_SMHBA_RegisterForAdapterPortEvents;
void *ptr_SMHBA_RegisterForAdapterPortEvents = NULL;
extern void *ptr_SMHBA_RegisterForAdapterPortStatEvents;
void *ptr_SMHBA_RegisterForAdapterPortStatEvents = NULL;
extern void *ptr_SMHBA_RegisterForTargetEvents;
void *ptr_SMHBA_RegisterForTargetEvents = NULL;
extern void *ptr_SMHBA_RegisterLibrary;
void *ptr_SMHBA_RegisterLibrary = NULL;
extern void *ptr_SMHBA_RemoveAllPersistentBindings;
void *ptr_SMHBA_RemoveAllPersistentBindings = NULL;
extern void *ptr_SMHBA_RemovePersistentBinding;
void *ptr_SMHBA_RemovePersistentBinding = NULL;
extern void *ptr_SMHBA_ScsiInquiry;
void *ptr_SMHBA_ScsiInquiry = NULL;
extern void *ptr_SMHBA_ScsiReadCapacity;
void *ptr_SMHBA_ScsiReadCapacity = NULL;
extern void *ptr_SMHBA_ScsiReportLuns;
void *ptr_SMHBA_ScsiReportLuns = NULL;
extern void *ptr_SMHBA_SendECHO;
void *ptr_SMHBA_SendECHO = NULL;
extern void *ptr_SMHBA_SendSMPPassThru;
void *ptr_SMHBA_SendSMPPassThru = NULL;
extern void *ptr_SMHBA_SendTEST;
void *ptr_SMHBA_SendTEST = NULL;
extern void *ptr_SMHBA_SetBindingSupport;
void *ptr_SMHBA_SetBindingSupport = NULL;
extern void *ptr_SMHBA_SetPersistentBinding;
void *ptr_SMHBA_SetPersistentBinding = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\hbaapi.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_HBA_CloseAdapter = (__vartype(ptr_HBA_CloseAdapter))GetProcAddress(hModule, "HBA_CloseAdapter");
   ptr_HBA_FreeLibrary = (__vartype(ptr_HBA_FreeLibrary))GetProcAddress(hModule, "HBA_FreeLibrary");
   ptr_HBA_GetAdapterAttributes = (__vartype(ptr_HBA_GetAdapterAttributes))GetProcAddress(hModule, "HBA_GetAdapterAttributes");
   ptr_HBA_GetAdapterName = (__vartype(ptr_HBA_GetAdapterName))GetProcAddress(hModule, "HBA_GetAdapterName");
   ptr_HBA_GetAdapterPortAttributes = (__vartype(ptr_HBA_GetAdapterPortAttributes))GetProcAddress(hModule, "HBA_GetAdapterPortAttributes");
   ptr_HBA_GetBindingCapability = (__vartype(ptr_HBA_GetBindingCapability))GetProcAddress(hModule, "HBA_GetBindingCapability");
   ptr_HBA_GetBindingSupport = (__vartype(ptr_HBA_GetBindingSupport))GetProcAddress(hModule, "HBA_GetBindingSupport");
   ptr_HBA_GetDiscoveredPortAttributes = (__vartype(ptr_HBA_GetDiscoveredPortAttributes))GetProcAddress(hModule, "HBA_GetDiscoveredPortAttributes");
   ptr_HBA_GetEventBuffer = (__vartype(ptr_HBA_GetEventBuffer))GetProcAddress(hModule, "HBA_GetEventBuffer");
   ptr_HBA_GetFC4Statistics = (__vartype(ptr_HBA_GetFC4Statistics))GetProcAddress(hModule, "HBA_GetFC4Statistics");
   ptr_HBA_GetFCPStatistics = (__vartype(ptr_HBA_GetFCPStatistics))GetProcAddress(hModule, "HBA_GetFCPStatistics");
   ptr_HBA_GetFcpPersistentBinding = (__vartype(ptr_HBA_GetFcpPersistentBinding))GetProcAddress(hModule, "HBA_GetFcpPersistentBinding");
   ptr_HBA_GetFcpTargetMapping = (__vartype(ptr_HBA_GetFcpTargetMapping))GetProcAddress(hModule, "HBA_GetFcpTargetMapping");
   ptr_HBA_GetFcpTargetMappingV2 = (__vartype(ptr_HBA_GetFcpTargetMappingV2))GetProcAddress(hModule, "HBA_GetFcpTargetMappingV2");
   ptr_HBA_GetNumberOfAdapters = (__vartype(ptr_HBA_GetNumberOfAdapters))GetProcAddress(hModule, "HBA_GetNumberOfAdapters");
   ptr_HBA_GetPersistentBindingV2 = (__vartype(ptr_HBA_GetPersistentBindingV2))GetProcAddress(hModule, "HBA_GetPersistentBindingV2");
   ptr_HBA_GetPortAttributesByWWN = (__vartype(ptr_HBA_GetPortAttributesByWWN))GetProcAddress(hModule, "HBA_GetPortAttributesByWWN");
   ptr_HBA_GetPortStatistics = (__vartype(ptr_HBA_GetPortStatistics))GetProcAddress(hModule, "HBA_GetPortStatistics");
   ptr_HBA_GetRNIDMgmtInfo = (__vartype(ptr_HBA_GetRNIDMgmtInfo))GetProcAddress(hModule, "HBA_GetRNIDMgmtInfo");
   ptr_HBA_GetVendorLibraryAttributes = (__vartype(ptr_HBA_GetVendorLibraryAttributes))GetProcAddress(hModule, "HBA_GetVendorLibraryAttributes");
   ptr_HBA_GetVersion = (__vartype(ptr_HBA_GetVersion))GetProcAddress(hModule, "HBA_GetVersion");
   ptr_HBA_GetWrapperLibraryAttributes = (__vartype(ptr_HBA_GetWrapperLibraryAttributes))GetProcAddress(hModule, "HBA_GetWrapperLibraryAttributes");
   ptr_HBA_LoadLibrary = (__vartype(ptr_HBA_LoadLibrary))GetProcAddress(hModule, "HBA_LoadLibrary");
   ptr_HBA_OpenAdapter = (__vartype(ptr_HBA_OpenAdapter))GetProcAddress(hModule, "HBA_OpenAdapter");
   ptr_HBA_OpenAdapterByWWN = (__vartype(ptr_HBA_OpenAdapterByWWN))GetProcAddress(hModule, "HBA_OpenAdapterByWWN");
   ptr_HBA_RefreshAdapterConfiguration = (__vartype(ptr_HBA_RefreshAdapterConfiguration))GetProcAddress(hModule, "HBA_RefreshAdapterConfiguration");
   ptr_HBA_RefreshInformation = (__vartype(ptr_HBA_RefreshInformation))GetProcAddress(hModule, "HBA_RefreshInformation");
   ptr_HBA_RegisterForAdapterAddEvents = (__vartype(ptr_HBA_RegisterForAdapterAddEvents))GetProcAddress(hModule, "HBA_RegisterForAdapterAddEvents");
   ptr_HBA_RegisterForAdapterEvents = (__vartype(ptr_HBA_RegisterForAdapterEvents))GetProcAddress(hModule, "HBA_RegisterForAdapterEvents");
   ptr_HBA_RegisterForAdapterPortEvents = (__vartype(ptr_HBA_RegisterForAdapterPortEvents))GetProcAddress(hModule, "HBA_RegisterForAdapterPortEvents");
   ptr_HBA_RegisterForAdapterPortStatEvents = (__vartype(ptr_HBA_RegisterForAdapterPortStatEvents))GetProcAddress(hModule, "HBA_RegisterForAdapterPortStatEvents");
   ptr_HBA_RegisterForLinkEvents = (__vartype(ptr_HBA_RegisterForLinkEvents))GetProcAddress(hModule, "HBA_RegisterForLinkEvents");
   ptr_HBA_RegisterForTargetEvents = (__vartype(ptr_HBA_RegisterForTargetEvents))GetProcAddress(hModule, "HBA_RegisterForTargetEvents");
   ptr_HBA_RegisterLibrary = (__vartype(ptr_HBA_RegisterLibrary))GetProcAddress(hModule, "HBA_RegisterLibrary");
   ptr_HBA_RegisterLibraryV2 = (__vartype(ptr_HBA_RegisterLibraryV2))GetProcAddress(hModule, "HBA_RegisterLibraryV2");
   ptr_HBA_RemoveAllPersistentBindings = (__vartype(ptr_HBA_RemoveAllPersistentBindings))GetProcAddress(hModule, "HBA_RemoveAllPersistentBindings");
   ptr_HBA_RemoveCallback = (__vartype(ptr_HBA_RemoveCallback))GetProcAddress(hModule, "HBA_RemoveCallback");
   ptr_HBA_RemovePersistentBinding = (__vartype(ptr_HBA_RemovePersistentBinding))GetProcAddress(hModule, "HBA_RemovePersistentBinding");
   ptr_HBA_ResetStatistics = (__vartype(ptr_HBA_ResetStatistics))GetProcAddress(hModule, "HBA_ResetStatistics");
   ptr_HBA_ScsiInquiryV2 = (__vartype(ptr_HBA_ScsiInquiryV2))GetProcAddress(hModule, "HBA_ScsiInquiryV2");
   ptr_HBA_ScsiReadCapacityV2 = (__vartype(ptr_HBA_ScsiReadCapacityV2))GetProcAddress(hModule, "HBA_ScsiReadCapacityV2");
   ptr_HBA_ScsiReportLUNsV2 = (__vartype(ptr_HBA_ScsiReportLUNsV2))GetProcAddress(hModule, "HBA_ScsiReportLUNsV2");
   ptr_HBA_SendCTPassThru = (__vartype(ptr_HBA_SendCTPassThru))GetProcAddress(hModule, "HBA_SendCTPassThru");
   ptr_HBA_SendCTPassThruV2 = (__vartype(ptr_HBA_SendCTPassThruV2))GetProcAddress(hModule, "HBA_SendCTPassThruV2");
   ptr_HBA_SendLIRR = (__vartype(ptr_HBA_SendLIRR))GetProcAddress(hModule, "HBA_SendLIRR");
   ptr_HBA_SendRLS = (__vartype(ptr_HBA_SendRLS))GetProcAddress(hModule, "HBA_SendRLS");
   ptr_HBA_SendRNID = (__vartype(ptr_HBA_SendRNID))GetProcAddress(hModule, "HBA_SendRNID");
   ptr_HBA_SendRNIDV2 = (__vartype(ptr_HBA_SendRNIDV2))GetProcAddress(hModule, "HBA_SendRNIDV2");
   ptr_HBA_SendRPL = (__vartype(ptr_HBA_SendRPL))GetProcAddress(hModule, "HBA_SendRPL");
   ptr_HBA_SendRPS = (__vartype(ptr_HBA_SendRPS))GetProcAddress(hModule, "HBA_SendRPS");
   ptr_HBA_SendReadCapacity = (__vartype(ptr_HBA_SendReadCapacity))GetProcAddress(hModule, "HBA_SendReadCapacity");
   ptr_HBA_SendReportLUNs = (__vartype(ptr_HBA_SendReportLUNs))GetProcAddress(hModule, "HBA_SendReportLUNs");
   ptr_HBA_SendSRL = (__vartype(ptr_HBA_SendSRL))GetProcAddress(hModule, "HBA_SendSRL");
   ptr_HBA_SendScsiInquiry = (__vartype(ptr_HBA_SendScsiInquiry))GetProcAddress(hModule, "HBA_SendScsiInquiry");
   ptr_HBA_SetBindingSupport = (__vartype(ptr_HBA_SetBindingSupport))GetProcAddress(hModule, "HBA_SetBindingSupport");
   ptr_HBA_SetPersistentBindingV2 = (__vartype(ptr_HBA_SetPersistentBindingV2))GetProcAddress(hModule, "HBA_SetPersistentBindingV2");
   ptr_HBA_SetRNIDMgmtInfo = (__vartype(ptr_HBA_SetRNIDMgmtInfo))GetProcAddress(hModule, "HBA_SetRNIDMgmtInfo");
   ptr_HbaGetAdapterNameByDeviceInstanceId = (__vartype(ptr_HbaGetAdapterNameByDeviceInstanceId))GetProcAddress(hModule, "HbaGetAdapterNameByDeviceInstanceId");
   ptr_SMHBA_GetAdapterAttributes = (__vartype(ptr_SMHBA_GetAdapterAttributes))GetProcAddress(hModule, "SMHBA_GetAdapterAttributes");
   ptr_SMHBA_GetAdapterPortAttributes = (__vartype(ptr_SMHBA_GetAdapterPortAttributes))GetProcAddress(hModule, "SMHBA_GetAdapterPortAttributes");
   ptr_SMHBA_GetBindingCapability = (__vartype(ptr_SMHBA_GetBindingCapability))GetProcAddress(hModule, "SMHBA_GetBindingCapability");
   ptr_SMHBA_GetBindingSupport = (__vartype(ptr_SMHBA_GetBindingSupport))GetProcAddress(hModule, "SMHBA_GetBindingSupport");
   ptr_SMHBA_GetDiscoveredPortAttributes = (__vartype(ptr_SMHBA_GetDiscoveredPortAttributes))GetProcAddress(hModule, "SMHBA_GetDiscoveredPortAttributes");
   ptr_SMHBA_GetFCPhyAttributes = (__vartype(ptr_SMHBA_GetFCPhyAttributes))GetProcAddress(hModule, "SMHBA_GetFCPhyAttributes");
   ptr_SMHBA_GetLUNStatistics = (__vartype(ptr_SMHBA_GetLUNStatistics))GetProcAddress(hModule, "SMHBA_GetLUNStatistics");
   ptr_SMHBA_GetNumberOfPorts = (__vartype(ptr_SMHBA_GetNumberOfPorts))GetProcAddress(hModule, "SMHBA_GetNumberOfPorts");
   ptr_SMHBA_GetPersistentBinding = (__vartype(ptr_SMHBA_GetPersistentBinding))GetProcAddress(hModule, "SMHBA_GetPersistentBinding");
   ptr_SMHBA_GetPhyStatistics = (__vartype(ptr_SMHBA_GetPhyStatistics))GetProcAddress(hModule, "SMHBA_GetPhyStatistics");
   ptr_SMHBA_GetPortAttributesByWWN = (__vartype(ptr_SMHBA_GetPortAttributesByWWN))GetProcAddress(hModule, "SMHBA_GetPortAttributesByWWN");
   ptr_SMHBA_GetPortType = (__vartype(ptr_SMHBA_GetPortType))GetProcAddress(hModule, "SMHBA_GetPortType");
   ptr_SMHBA_GetProtocolStatistics = (__vartype(ptr_SMHBA_GetProtocolStatistics))GetProcAddress(hModule, "SMHBA_GetProtocolStatistics");
   ptr_SMHBA_GetSASPhyAttributes = (__vartype(ptr_SMHBA_GetSASPhyAttributes))GetProcAddress(hModule, "SMHBA_GetSASPhyAttributes");
   ptr_SMHBA_GetTargetMapping = (__vartype(ptr_SMHBA_GetTargetMapping))GetProcAddress(hModule, "SMHBA_GetTargetMapping");
   ptr_SMHBA_GetVendorLibraryAttributes = (__vartype(ptr_SMHBA_GetVendorLibraryAttributes))GetProcAddress(hModule, "SMHBA_GetVendorLibraryAttributes");
   ptr_SMHBA_GetVersion = (__vartype(ptr_SMHBA_GetVersion))GetProcAddress(hModule, "SMHBA_GetVersion");
   ptr_SMHBA_GetWrapperLibraryAttributes = (__vartype(ptr_SMHBA_GetWrapperLibraryAttributes))GetProcAddress(hModule, "SMHBA_GetWrapperLibraryAttributes");
   ptr_SMHBA_RegisterForAdapterAddEvents = (__vartype(ptr_SMHBA_RegisterForAdapterAddEvents))GetProcAddress(hModule, "SMHBA_RegisterForAdapterAddEvents");
   ptr_SMHBA_RegisterForAdapterEvents = (__vartype(ptr_SMHBA_RegisterForAdapterEvents))GetProcAddress(hModule, "SMHBA_RegisterForAdapterEvents");
   ptr_SMHBA_RegisterForAdapterPhyStatEvents = (__vartype(ptr_SMHBA_RegisterForAdapterPhyStatEvents))GetProcAddress(hModule, "SMHBA_RegisterForAdapterPhyStatEvents");
   ptr_SMHBA_RegisterForAdapterPortEvents = (__vartype(ptr_SMHBA_RegisterForAdapterPortEvents))GetProcAddress(hModule, "SMHBA_RegisterForAdapterPortEvents");
   ptr_SMHBA_RegisterForAdapterPortStatEvents = (__vartype(ptr_SMHBA_RegisterForAdapterPortStatEvents))GetProcAddress(hModule, "SMHBA_RegisterForAdapterPortStatEvents");
   ptr_SMHBA_RegisterForTargetEvents = (__vartype(ptr_SMHBA_RegisterForTargetEvents))GetProcAddress(hModule, "SMHBA_RegisterForTargetEvents");
   ptr_SMHBA_RegisterLibrary = (__vartype(ptr_SMHBA_RegisterLibrary))GetProcAddress(hModule, "SMHBA_RegisterLibrary");
   ptr_SMHBA_RemoveAllPersistentBindings = (__vartype(ptr_SMHBA_RemoveAllPersistentBindings))GetProcAddress(hModule, "SMHBA_RemoveAllPersistentBindings");
   ptr_SMHBA_RemovePersistentBinding = (__vartype(ptr_SMHBA_RemovePersistentBinding))GetProcAddress(hModule, "SMHBA_RemovePersistentBinding");
   ptr_SMHBA_ScsiInquiry = (__vartype(ptr_SMHBA_ScsiInquiry))GetProcAddress(hModule, "SMHBA_ScsiInquiry");
   ptr_SMHBA_ScsiReadCapacity = (__vartype(ptr_SMHBA_ScsiReadCapacity))GetProcAddress(hModule, "SMHBA_ScsiReadCapacity");
   ptr_SMHBA_ScsiReportLuns = (__vartype(ptr_SMHBA_ScsiReportLuns))GetProcAddress(hModule, "SMHBA_ScsiReportLuns");
   ptr_SMHBA_SendECHO = (__vartype(ptr_SMHBA_SendECHO))GetProcAddress(hModule, "SMHBA_SendECHO");
   ptr_SMHBA_SendSMPPassThru = (__vartype(ptr_SMHBA_SendSMPPassThru))GetProcAddress(hModule, "SMHBA_SendSMPPassThru");
   ptr_SMHBA_SendTEST = (__vartype(ptr_SMHBA_SendTEST))GetProcAddress(hModule, "SMHBA_SendTEST");
   ptr_SMHBA_SetBindingSupport = (__vartype(ptr_SMHBA_SetBindingSupport))GetProcAddress(hModule, "SMHBA_SetBindingSupport");
   ptr_SMHBA_SetPersistentBinding = (__vartype(ptr_SMHBA_SetPersistentBinding))GetProcAddress(hModule, "SMHBA_SetPersistentBinding");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

