#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_AVIBuildFilter;
void *ptr_AVIBuildFilter = NULL;
extern void *ptr_AVIBuildFilterA;
void *ptr_AVIBuildFilterA = NULL;
extern void *ptr_AVIBuildFilterW;
void *ptr_AVIBuildFilterW = NULL;
extern void *ptr_AVIClearClipboard;
void *ptr_AVIClearClipboard = NULL;
extern void *ptr_AVIFileAddRef;
void *ptr_AVIFileAddRef = NULL;
extern void *ptr_AVIFileCreateStream;
void *ptr_AVIFileCreateStream = NULL;
extern void *ptr_AVIFileCreateStreamA;
void *ptr_AVIFileCreateStreamA = NULL;
extern void *ptr_AVIFileCreateStreamW;
void *ptr_AVIFileCreateStreamW = NULL;
extern void *ptr_AVIFileEndRecord;
void *ptr_AVIFileEndRecord = NULL;
extern void *ptr_AVIFileExit;
void *ptr_AVIFileExit = NULL;
extern void *ptr_AVIFileGetStream;
void *ptr_AVIFileGetStream = NULL;
extern void *ptr_AVIFileInfo;
void *ptr_AVIFileInfo = NULL;
extern void *ptr_AVIFileInfoA;
void *ptr_AVIFileInfoA = NULL;
extern void *ptr_AVIFileInfoW;
void *ptr_AVIFileInfoW = NULL;
extern void *ptr_AVIFileInit;
void *ptr_AVIFileInit = NULL;
extern void *ptr_AVIFileOpen;
void *ptr_AVIFileOpen = NULL;
extern void *ptr_AVIFileOpenA;
void *ptr_AVIFileOpenA = NULL;
extern void *ptr_AVIFileOpenW;
void *ptr_AVIFileOpenW = NULL;
extern void *ptr_AVIFileReadData;
void *ptr_AVIFileReadData = NULL;
extern void *ptr_AVIFileRelease;
void *ptr_AVIFileRelease = NULL;
extern void *ptr_AVIFileWriteData;
void *ptr_AVIFileWriteData = NULL;
extern void *ptr_AVIGetFromClipboard;
void *ptr_AVIGetFromClipboard = NULL;
extern void *ptr_AVIMakeCompressedStream;
void *ptr_AVIMakeCompressedStream = NULL;
extern void *ptr_AVIMakeFileFromStreams;
void *ptr_AVIMakeFileFromStreams = NULL;
extern void *ptr_AVIMakeStreamFromClipboard;
void *ptr_AVIMakeStreamFromClipboard = NULL;
extern void *ptr_AVIPutFileOnClipboard;
void *ptr_AVIPutFileOnClipboard = NULL;
extern void *ptr_AVISave;
void *ptr_AVISave = NULL;
extern void *ptr_AVISaveA;
void *ptr_AVISaveA = NULL;
extern void *ptr_AVISaveOptions;
void *ptr_AVISaveOptions = NULL;
extern void *ptr_AVISaveOptionsFree;
void *ptr_AVISaveOptionsFree = NULL;
extern void *ptr_AVISaveV;
void *ptr_AVISaveV = NULL;
extern void *ptr_AVISaveVA;
void *ptr_AVISaveVA = NULL;
extern void *ptr_AVISaveVW;
void *ptr_AVISaveVW = NULL;
extern void *ptr_AVISaveW;
void *ptr_AVISaveW = NULL;
extern void *ptr_AVIStreamAddRef;
void *ptr_AVIStreamAddRef = NULL;
extern void *ptr_AVIStreamBeginStreaming;
void *ptr_AVIStreamBeginStreaming = NULL;
extern void *ptr_AVIStreamCreate;
void *ptr_AVIStreamCreate = NULL;
extern void *ptr_AVIStreamEndStreaming;
void *ptr_AVIStreamEndStreaming = NULL;
extern void *ptr_AVIStreamFindSample;
void *ptr_AVIStreamFindSample = NULL;
extern void *ptr_AVIStreamGetFrame;
void *ptr_AVIStreamGetFrame = NULL;
extern void *ptr_AVIStreamGetFrameClose;
void *ptr_AVIStreamGetFrameClose = NULL;
extern void *ptr_AVIStreamGetFrameOpen;
void *ptr_AVIStreamGetFrameOpen = NULL;
extern void *ptr_AVIStreamInfo;
void *ptr_AVIStreamInfo = NULL;
extern void *ptr_AVIStreamInfoA;
void *ptr_AVIStreamInfoA = NULL;
extern void *ptr_AVIStreamInfoW;
void *ptr_AVIStreamInfoW = NULL;
extern void *ptr_AVIStreamLength;
void *ptr_AVIStreamLength = NULL;
extern void *ptr_AVIStreamOpenFromFile;
void *ptr_AVIStreamOpenFromFile = NULL;
extern void *ptr_AVIStreamOpenFromFileA;
void *ptr_AVIStreamOpenFromFileA = NULL;
extern void *ptr_AVIStreamOpenFromFileW;
void *ptr_AVIStreamOpenFromFileW = NULL;
extern void *ptr_AVIStreamRead;
void *ptr_AVIStreamRead = NULL;
extern void *ptr_AVIStreamReadData;
void *ptr_AVIStreamReadData = NULL;
extern void *ptr_AVIStreamReadFormat;
void *ptr_AVIStreamReadFormat = NULL;
extern void *ptr_AVIStreamRelease;
void *ptr_AVIStreamRelease = NULL;
extern void *ptr_AVIStreamSampleToTime;
void *ptr_AVIStreamSampleToTime = NULL;
extern void *ptr_AVIStreamSetFormat;
void *ptr_AVIStreamSetFormat = NULL;
extern void *ptr_AVIStreamStart;
void *ptr_AVIStreamStart = NULL;
extern void *ptr_AVIStreamTimeToSample;
void *ptr_AVIStreamTimeToSample = NULL;
extern void *ptr_AVIStreamWrite;
void *ptr_AVIStreamWrite = NULL;
extern void *ptr_AVIStreamWriteData;
void *ptr_AVIStreamWriteData = NULL;
extern void *ptr_CreateEditableStream;
void *ptr_CreateEditableStream = NULL;
extern void *ptr_DllCanUnloadNow;
void *ptr_DllCanUnloadNow = NULL;
extern void *ptr_DllGetClassObject;
void *ptr_DllGetClassObject = NULL;
extern void *ptr_EditStreamClone;
void *ptr_EditStreamClone = NULL;
extern void *ptr_EditStreamCopy;
void *ptr_EditStreamCopy = NULL;
extern void *ptr_EditStreamCut;
void *ptr_EditStreamCut = NULL;
extern void *ptr_EditStreamPaste;
void *ptr_EditStreamPaste = NULL;
extern void *ptr_EditStreamSetInfo;
void *ptr_EditStreamSetInfo = NULL;
extern void *ptr_EditStreamSetInfoA;
void *ptr_EditStreamSetInfoA = NULL;
extern void *ptr_EditStreamSetInfoW;
void *ptr_EditStreamSetInfoW = NULL;
extern void *ptr_EditStreamSetName;
void *ptr_EditStreamSetName = NULL;
extern void *ptr_EditStreamSetNameA;
void *ptr_EditStreamSetNameA = NULL;
extern void *ptr_EditStreamSetNameW;
void *ptr_EditStreamSetNameW = NULL;
extern void *ptr_IID_IAVIEditStream;
void *ptr_IID_IAVIEditStream = NULL;
extern void *ptr_IID_IAVIFile;
void *ptr_IID_IAVIFile = NULL;
extern void *ptr_IID_IAVIStream;
void *ptr_IID_IAVIStream = NULL;
extern void *ptr_IID_IGetFrame;
void *ptr_IID_IGetFrame = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\avifil32.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_AVIBuildFilter = (__vartype(ptr_AVIBuildFilter))GetProcAddress(hModule, "AVIBuildFilter");
   ptr_AVIBuildFilterA = (__vartype(ptr_AVIBuildFilterA))GetProcAddress(hModule, "AVIBuildFilterA");
   ptr_AVIBuildFilterW = (__vartype(ptr_AVIBuildFilterW))GetProcAddress(hModule, "AVIBuildFilterW");
   ptr_AVIClearClipboard = (__vartype(ptr_AVIClearClipboard))GetProcAddress(hModule, "AVIClearClipboard");
   ptr_AVIFileAddRef = (__vartype(ptr_AVIFileAddRef))GetProcAddress(hModule, "AVIFileAddRef");
   ptr_AVIFileCreateStream = (__vartype(ptr_AVIFileCreateStream))GetProcAddress(hModule, "AVIFileCreateStream");
   ptr_AVIFileCreateStreamA = (__vartype(ptr_AVIFileCreateStreamA))GetProcAddress(hModule, "AVIFileCreateStreamA");
   ptr_AVIFileCreateStreamW = (__vartype(ptr_AVIFileCreateStreamW))GetProcAddress(hModule, "AVIFileCreateStreamW");
   ptr_AVIFileEndRecord = (__vartype(ptr_AVIFileEndRecord))GetProcAddress(hModule, "AVIFileEndRecord");
   ptr_AVIFileExit = (__vartype(ptr_AVIFileExit))GetProcAddress(hModule, "AVIFileExit");
   ptr_AVIFileGetStream = (__vartype(ptr_AVIFileGetStream))GetProcAddress(hModule, "AVIFileGetStream");
   ptr_AVIFileInfo = (__vartype(ptr_AVIFileInfo))GetProcAddress(hModule, "AVIFileInfo");
   ptr_AVIFileInfoA = (__vartype(ptr_AVIFileInfoA))GetProcAddress(hModule, "AVIFileInfoA");
   ptr_AVIFileInfoW = (__vartype(ptr_AVIFileInfoW))GetProcAddress(hModule, "AVIFileInfoW");
   ptr_AVIFileInit = (__vartype(ptr_AVIFileInit))GetProcAddress(hModule, "AVIFileInit");
   ptr_AVIFileOpen = (__vartype(ptr_AVIFileOpen))GetProcAddress(hModule, "AVIFileOpen");
   ptr_AVIFileOpenA = (__vartype(ptr_AVIFileOpenA))GetProcAddress(hModule, "AVIFileOpenA");
   ptr_AVIFileOpenW = (__vartype(ptr_AVIFileOpenW))GetProcAddress(hModule, "AVIFileOpenW");
   ptr_AVIFileReadData = (__vartype(ptr_AVIFileReadData))GetProcAddress(hModule, "AVIFileReadData");
   ptr_AVIFileRelease = (__vartype(ptr_AVIFileRelease))GetProcAddress(hModule, "AVIFileRelease");
   ptr_AVIFileWriteData = (__vartype(ptr_AVIFileWriteData))GetProcAddress(hModule, "AVIFileWriteData");
   ptr_AVIGetFromClipboard = (__vartype(ptr_AVIGetFromClipboard))GetProcAddress(hModule, "AVIGetFromClipboard");
   ptr_AVIMakeCompressedStream = (__vartype(ptr_AVIMakeCompressedStream))GetProcAddress(hModule, "AVIMakeCompressedStream");
   ptr_AVIMakeFileFromStreams = (__vartype(ptr_AVIMakeFileFromStreams))GetProcAddress(hModule, "AVIMakeFileFromStreams");
   ptr_AVIMakeStreamFromClipboard = (__vartype(ptr_AVIMakeStreamFromClipboard))GetProcAddress(hModule, "AVIMakeStreamFromClipboard");
   ptr_AVIPutFileOnClipboard = (__vartype(ptr_AVIPutFileOnClipboard))GetProcAddress(hModule, "AVIPutFileOnClipboard");
   ptr_AVISave = (__vartype(ptr_AVISave))GetProcAddress(hModule, "AVISave");
   ptr_AVISaveA = (__vartype(ptr_AVISaveA))GetProcAddress(hModule, "AVISaveA");
   ptr_AVISaveOptions = (__vartype(ptr_AVISaveOptions))GetProcAddress(hModule, "AVISaveOptions");
   ptr_AVISaveOptionsFree = (__vartype(ptr_AVISaveOptionsFree))GetProcAddress(hModule, "AVISaveOptionsFree");
   ptr_AVISaveV = (__vartype(ptr_AVISaveV))GetProcAddress(hModule, "AVISaveV");
   ptr_AVISaveVA = (__vartype(ptr_AVISaveVA))GetProcAddress(hModule, "AVISaveVA");
   ptr_AVISaveVW = (__vartype(ptr_AVISaveVW))GetProcAddress(hModule, "AVISaveVW");
   ptr_AVISaveW = (__vartype(ptr_AVISaveW))GetProcAddress(hModule, "AVISaveW");
   ptr_AVIStreamAddRef = (__vartype(ptr_AVIStreamAddRef))GetProcAddress(hModule, "AVIStreamAddRef");
   ptr_AVIStreamBeginStreaming = (__vartype(ptr_AVIStreamBeginStreaming))GetProcAddress(hModule, "AVIStreamBeginStreaming");
   ptr_AVIStreamCreate = (__vartype(ptr_AVIStreamCreate))GetProcAddress(hModule, "AVIStreamCreate");
   ptr_AVIStreamEndStreaming = (__vartype(ptr_AVIStreamEndStreaming))GetProcAddress(hModule, "AVIStreamEndStreaming");
   ptr_AVIStreamFindSample = (__vartype(ptr_AVIStreamFindSample))GetProcAddress(hModule, "AVIStreamFindSample");
   ptr_AVIStreamGetFrame = (__vartype(ptr_AVIStreamGetFrame))GetProcAddress(hModule, "AVIStreamGetFrame");
   ptr_AVIStreamGetFrameClose = (__vartype(ptr_AVIStreamGetFrameClose))GetProcAddress(hModule, "AVIStreamGetFrameClose");
   ptr_AVIStreamGetFrameOpen = (__vartype(ptr_AVIStreamGetFrameOpen))GetProcAddress(hModule, "AVIStreamGetFrameOpen");
   ptr_AVIStreamInfo = (__vartype(ptr_AVIStreamInfo))GetProcAddress(hModule, "AVIStreamInfo");
   ptr_AVIStreamInfoA = (__vartype(ptr_AVIStreamInfoA))GetProcAddress(hModule, "AVIStreamInfoA");
   ptr_AVIStreamInfoW = (__vartype(ptr_AVIStreamInfoW))GetProcAddress(hModule, "AVIStreamInfoW");
   ptr_AVIStreamLength = (__vartype(ptr_AVIStreamLength))GetProcAddress(hModule, "AVIStreamLength");
   ptr_AVIStreamOpenFromFile = (__vartype(ptr_AVIStreamOpenFromFile))GetProcAddress(hModule, "AVIStreamOpenFromFile");
   ptr_AVIStreamOpenFromFileA = (__vartype(ptr_AVIStreamOpenFromFileA))GetProcAddress(hModule, "AVIStreamOpenFromFileA");
   ptr_AVIStreamOpenFromFileW = (__vartype(ptr_AVIStreamOpenFromFileW))GetProcAddress(hModule, "AVIStreamOpenFromFileW");
   ptr_AVIStreamRead = (__vartype(ptr_AVIStreamRead))GetProcAddress(hModule, "AVIStreamRead");
   ptr_AVIStreamReadData = (__vartype(ptr_AVIStreamReadData))GetProcAddress(hModule, "AVIStreamReadData");
   ptr_AVIStreamReadFormat = (__vartype(ptr_AVIStreamReadFormat))GetProcAddress(hModule, "AVIStreamReadFormat");
   ptr_AVIStreamRelease = (__vartype(ptr_AVIStreamRelease))GetProcAddress(hModule, "AVIStreamRelease");
   ptr_AVIStreamSampleToTime = (__vartype(ptr_AVIStreamSampleToTime))GetProcAddress(hModule, "AVIStreamSampleToTime");
   ptr_AVIStreamSetFormat = (__vartype(ptr_AVIStreamSetFormat))GetProcAddress(hModule, "AVIStreamSetFormat");
   ptr_AVIStreamStart = (__vartype(ptr_AVIStreamStart))GetProcAddress(hModule, "AVIStreamStart");
   ptr_AVIStreamTimeToSample = (__vartype(ptr_AVIStreamTimeToSample))GetProcAddress(hModule, "AVIStreamTimeToSample");
   ptr_AVIStreamWrite = (__vartype(ptr_AVIStreamWrite))GetProcAddress(hModule, "AVIStreamWrite");
   ptr_AVIStreamWriteData = (__vartype(ptr_AVIStreamWriteData))GetProcAddress(hModule, "AVIStreamWriteData");
   ptr_CreateEditableStream = (__vartype(ptr_CreateEditableStream))GetProcAddress(hModule, "CreateEditableStream");
   ptr_DllCanUnloadNow = (__vartype(ptr_DllCanUnloadNow))GetProcAddress(hModule, "DllCanUnloadNow");
   ptr_DllGetClassObject = (__vartype(ptr_DllGetClassObject))GetProcAddress(hModule, "DllGetClassObject");
   ptr_EditStreamClone = (__vartype(ptr_EditStreamClone))GetProcAddress(hModule, "EditStreamClone");
   ptr_EditStreamCopy = (__vartype(ptr_EditStreamCopy))GetProcAddress(hModule, "EditStreamCopy");
   ptr_EditStreamCut = (__vartype(ptr_EditStreamCut))GetProcAddress(hModule, "EditStreamCut");
   ptr_EditStreamPaste = (__vartype(ptr_EditStreamPaste))GetProcAddress(hModule, "EditStreamPaste");
   ptr_EditStreamSetInfo = (__vartype(ptr_EditStreamSetInfo))GetProcAddress(hModule, "EditStreamSetInfo");
   ptr_EditStreamSetInfoA = (__vartype(ptr_EditStreamSetInfoA))GetProcAddress(hModule, "EditStreamSetInfoA");
   ptr_EditStreamSetInfoW = (__vartype(ptr_EditStreamSetInfoW))GetProcAddress(hModule, "EditStreamSetInfoW");
   ptr_EditStreamSetName = (__vartype(ptr_EditStreamSetName))GetProcAddress(hModule, "EditStreamSetName");
   ptr_EditStreamSetNameA = (__vartype(ptr_EditStreamSetNameA))GetProcAddress(hModule, "EditStreamSetNameA");
   ptr_EditStreamSetNameW = (__vartype(ptr_EditStreamSetNameW))GetProcAddress(hModule, "EditStreamSetNameW");
   ptr_IID_IAVIEditStream = (__vartype(ptr_IID_IAVIEditStream))GetProcAddress(hModule, "IID_IAVIEditStream");
   ptr_IID_IAVIFile = (__vartype(ptr_IID_IAVIFile))GetProcAddress(hModule, "IID_IAVIFile");
   ptr_IID_IAVIStream = (__vartype(ptr_IID_IAVIStream))GetProcAddress(hModule, "IID_IAVIStream");
   ptr_IID_IGetFrame = (__vartype(ptr_IID_IGetFrame))GetProcAddress(hModule, "IID_IGetFrame");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

