#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_AcceptSecurityContext;
void *ptr_AcceptSecurityContext = NULL;
extern void *ptr_AcquireCredentialsHandleA;
void *ptr_AcquireCredentialsHandleA = NULL;
extern void *ptr_AcquireCredentialsHandleW;
void *ptr_AcquireCredentialsHandleW = NULL;
extern void *ptr_AddCredentialsA;
void *ptr_AddCredentialsA = NULL;
extern void *ptr_AddCredentialsW;
void *ptr_AddCredentialsW = NULL;
extern void *ptr_AddSecurityPackageA;
void *ptr_AddSecurityPackageA = NULL;
extern void *ptr_AddSecurityPackageW;
void *ptr_AddSecurityPackageW = NULL;
extern void *ptr_ApplyControlToken;
void *ptr_ApplyControlToken = NULL;
extern void *ptr_ChangeAccountPasswordA;
void *ptr_ChangeAccountPasswordA = NULL;
extern void *ptr_ChangeAccountPasswordW;
void *ptr_ChangeAccountPasswordW = NULL;
extern void *ptr_CompleteAuthToken;
void *ptr_CompleteAuthToken = NULL;
extern void *ptr_CredMarshalTargetInfo;
void *ptr_CredMarshalTargetInfo = NULL;
extern void *ptr_CredUnmarshalTargetInfo;
void *ptr_CredUnmarshalTargetInfo = NULL;
extern void *ptr_DecryptMessage;
void *ptr_DecryptMessage = NULL;
extern void *ptr_DeleteSecurityContext;
void *ptr_DeleteSecurityContext = NULL;
extern void *ptr_DeleteSecurityPackageA;
void *ptr_DeleteSecurityPackageA = NULL;
extern void *ptr_DeleteSecurityPackageW;
void *ptr_DeleteSecurityPackageW = NULL;
extern void *ptr_EncryptMessage;
void *ptr_EncryptMessage = NULL;
extern void *ptr_EnumerateSecurityPackagesA;
void *ptr_EnumerateSecurityPackagesA = NULL;
extern void *ptr_EnumerateSecurityPackagesW;
void *ptr_EnumerateSecurityPackagesW = NULL;
extern void *ptr_ExportSecurityContext;
void *ptr_ExportSecurityContext = NULL;
extern void *ptr_FreeContextBuffer;
void *ptr_FreeContextBuffer = NULL;
extern void *ptr_FreeCredentialsHandle;
void *ptr_FreeCredentialsHandle = NULL;
extern void *ptr_GetSecurityUserInfo;
void *ptr_GetSecurityUserInfo = NULL;
extern void *ptr_GetUserNameExA;
void *ptr_GetUserNameExA = NULL;
extern void *ptr_GetUserNameExW;
void *ptr_GetUserNameExW = NULL;
extern void *ptr_ImpersonateSecurityContext;
void *ptr_ImpersonateSecurityContext = NULL;
extern void *ptr_ImportSecurityContextA;
void *ptr_ImportSecurityContextA = NULL;
extern void *ptr_ImportSecurityContextW;
void *ptr_ImportSecurityContextW = NULL;
extern void *ptr_InitSecurityInterfaceA;
void *ptr_InitSecurityInterfaceA = NULL;
extern void *ptr_InitSecurityInterfaceW;
void *ptr_InitSecurityInterfaceW = NULL;
extern void *ptr_InitializeSecurityContextA;
void *ptr_InitializeSecurityContextA = NULL;
extern void *ptr_InitializeSecurityContextW;
void *ptr_InitializeSecurityContextW = NULL;
extern void *ptr_LogonUserExExW;
void *ptr_LogonUserExExW = NULL;
extern void *ptr_LsaCallAuthenticationPackage;
void *ptr_LsaCallAuthenticationPackage = NULL;
extern void *ptr_LsaConnectUntrusted;
void *ptr_LsaConnectUntrusted = NULL;
extern void *ptr_LsaDeregisterLogonProcess;
void *ptr_LsaDeregisterLogonProcess = NULL;
extern void *ptr_LsaEnumerateLogonSessions;
void *ptr_LsaEnumerateLogonSessions = NULL;
extern void *ptr_LsaFreeReturnBuffer;
void *ptr_LsaFreeReturnBuffer = NULL;
extern void *ptr_LsaGetLogonSessionData;
void *ptr_LsaGetLogonSessionData = NULL;
extern void *ptr_LsaLogonUser;
void *ptr_LsaLogonUser = NULL;
extern void *ptr_LsaLookupAuthenticationPackage;
void *ptr_LsaLookupAuthenticationPackage = NULL;
extern void *ptr_LsaRegisterLogonProcess;
void *ptr_LsaRegisterLogonProcess = NULL;
extern void *ptr_LsaRegisterPolicyChangeNotification;
void *ptr_LsaRegisterPolicyChangeNotification = NULL;
extern void *ptr_LsaUnregisterPolicyChangeNotification;
void *ptr_LsaUnregisterPolicyChangeNotification = NULL;
extern void *ptr_MakeSignature;
void *ptr_MakeSignature = NULL;
extern void *ptr_QueryContextAttributesA;
void *ptr_QueryContextAttributesA = NULL;
extern void *ptr_QueryContextAttributesW;
void *ptr_QueryContextAttributesW = NULL;
extern void *ptr_QueryCredentialsAttributesA;
void *ptr_QueryCredentialsAttributesA = NULL;
extern void *ptr_QueryCredentialsAttributesW;
void *ptr_QueryCredentialsAttributesW = NULL;
extern void *ptr_QuerySecurityContextToken;
void *ptr_QuerySecurityContextToken = NULL;
extern void *ptr_QuerySecurityPackageInfoA;
void *ptr_QuerySecurityPackageInfoA = NULL;
extern void *ptr_QuerySecurityPackageInfoW;
void *ptr_QuerySecurityPackageInfoW = NULL;
extern void *ptr_RevertSecurityContext;
void *ptr_RevertSecurityContext = NULL;
extern void *ptr_SaslAcceptSecurityContext;
void *ptr_SaslAcceptSecurityContext = NULL;
extern void *ptr_SaslEnumerateProfilesA;
void *ptr_SaslEnumerateProfilesA = NULL;
extern void *ptr_SaslEnumerateProfilesW;
void *ptr_SaslEnumerateProfilesW = NULL;
extern void *ptr_SaslGetContextOption;
void *ptr_SaslGetContextOption = NULL;
extern void *ptr_SaslGetProfilePackageA;
void *ptr_SaslGetProfilePackageA = NULL;
extern void *ptr_SaslGetProfilePackageW;
void *ptr_SaslGetProfilePackageW = NULL;
extern void *ptr_SaslIdentifyPackageA;
void *ptr_SaslIdentifyPackageA = NULL;
extern void *ptr_SaslIdentifyPackageW;
void *ptr_SaslIdentifyPackageW = NULL;
extern void *ptr_SaslInitializeSecurityContextA;
void *ptr_SaslInitializeSecurityContextA = NULL;
extern void *ptr_SaslInitializeSecurityContextW;
void *ptr_SaslInitializeSecurityContextW = NULL;
extern void *ptr_SaslSetContextOption;
void *ptr_SaslSetContextOption = NULL;
extern void *ptr_SealMessage;
void *ptr_SealMessage = NULL;
extern void *ptr_SecCacheSspiPackages;
void *ptr_SecCacheSspiPackages = NULL;
extern void *ptr_SecDeleteUserModeContext;
void *ptr_SecDeleteUserModeContext = NULL;
extern void *ptr_SecInitUserModeContext;
void *ptr_SecInitUserModeContext = NULL;
extern void *ptr_SeciAllocateAndSetCallFlags;
void *ptr_SeciAllocateAndSetCallFlags = NULL;
extern void *ptr_SeciAllocateAndSetIPAddress;
void *ptr_SeciAllocateAndSetIPAddress = NULL;
extern void *ptr_SeciFreeCallContext;
void *ptr_SeciFreeCallContext = NULL;
extern void *ptr_SetContextAttributesA;
void *ptr_SetContextAttributesA = NULL;
extern void *ptr_SetContextAttributesW;
void *ptr_SetContextAttributesW = NULL;
extern void *ptr_SetCredentialsAttributesA;
void *ptr_SetCredentialsAttributesA = NULL;
extern void *ptr_SetCredentialsAttributesW;
void *ptr_SetCredentialsAttributesW = NULL;
extern void *ptr_SspiCompareAuthIdentities;
void *ptr_SspiCompareAuthIdentities = NULL;
extern void *ptr_SspiCopyAuthIdentity;
void *ptr_SspiCopyAuthIdentity = NULL;
extern void *ptr_SspiDecryptAuthIdentity;
void *ptr_SspiDecryptAuthIdentity = NULL;
extern void *ptr_SspiEncodeAuthIdentityAsStrings;
void *ptr_SspiEncodeAuthIdentityAsStrings = NULL;
extern void *ptr_SspiEncodeStringsAsAuthIdentity;
void *ptr_SspiEncodeStringsAsAuthIdentity = NULL;
extern void *ptr_SspiEncryptAuthIdentity;
void *ptr_SspiEncryptAuthIdentity = NULL;
extern void *ptr_SspiExcludePackage;
void *ptr_SspiExcludePackage = NULL;
extern void *ptr_SspiFreeAuthIdentity;
void *ptr_SspiFreeAuthIdentity = NULL;
extern void *ptr_SspiGetComputerNameForSPN;
void *ptr_SspiGetComputerNameForSPN = NULL;
extern void *ptr_SspiGetTargetHostName;
void *ptr_SspiGetTargetHostName = NULL;
extern void *ptr_SspiIsAuthIdentityEncrypted;
void *ptr_SspiIsAuthIdentityEncrypted = NULL;
extern void *ptr_SspiLocalFree;
void *ptr_SspiLocalFree = NULL;
extern void *ptr_SspiMarshalAuthIdentity;
void *ptr_SspiMarshalAuthIdentity = NULL;
extern void *ptr_SspiPrepareForCredRead;
void *ptr_SspiPrepareForCredRead = NULL;
extern void *ptr_SspiPrepareForCredWrite;
void *ptr_SspiPrepareForCredWrite = NULL;
extern void *ptr_SspiUnmarshalAuthIdentity;
void *ptr_SspiUnmarshalAuthIdentity = NULL;
extern void *ptr_SspiUnmarshalAuthIdentityInternal;
void *ptr_SspiUnmarshalAuthIdentityInternal = NULL;
extern void *ptr_SspiValidateAuthIdentity;
void *ptr_SspiValidateAuthIdentity = NULL;
extern void *ptr_SspiZeroAuthIdentity;
void *ptr_SspiZeroAuthIdentity = NULL;
extern void *ptr_UnsealMessage;
void *ptr_UnsealMessage = NULL;
extern void *ptr_VerifySignature;
void *ptr_VerifySignature = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\sspicli.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_AcceptSecurityContext = (__vartype(ptr_AcceptSecurityContext))GetProcAddress(hModule, "AcceptSecurityContext");
   ptr_AcquireCredentialsHandleA = (__vartype(ptr_AcquireCredentialsHandleA))GetProcAddress(hModule, "AcquireCredentialsHandleA");
   ptr_AcquireCredentialsHandleW = (__vartype(ptr_AcquireCredentialsHandleW))GetProcAddress(hModule, "AcquireCredentialsHandleW");
   ptr_AddCredentialsA = (__vartype(ptr_AddCredentialsA))GetProcAddress(hModule, "AddCredentialsA");
   ptr_AddCredentialsW = (__vartype(ptr_AddCredentialsW))GetProcAddress(hModule, "AddCredentialsW");
   ptr_AddSecurityPackageA = (__vartype(ptr_AddSecurityPackageA))GetProcAddress(hModule, "AddSecurityPackageA");
   ptr_AddSecurityPackageW = (__vartype(ptr_AddSecurityPackageW))GetProcAddress(hModule, "AddSecurityPackageW");
   ptr_ApplyControlToken = (__vartype(ptr_ApplyControlToken))GetProcAddress(hModule, "ApplyControlToken");
   ptr_ChangeAccountPasswordA = (__vartype(ptr_ChangeAccountPasswordA))GetProcAddress(hModule, "ChangeAccountPasswordA");
   ptr_ChangeAccountPasswordW = (__vartype(ptr_ChangeAccountPasswordW))GetProcAddress(hModule, "ChangeAccountPasswordW");
   ptr_CompleteAuthToken = (__vartype(ptr_CompleteAuthToken))GetProcAddress(hModule, "CompleteAuthToken");
   ptr_CredMarshalTargetInfo = (__vartype(ptr_CredMarshalTargetInfo))GetProcAddress(hModule, "CredMarshalTargetInfo");
   ptr_CredUnmarshalTargetInfo = (__vartype(ptr_CredUnmarshalTargetInfo))GetProcAddress(hModule, "CredUnmarshalTargetInfo");
   ptr_DecryptMessage = (__vartype(ptr_DecryptMessage))GetProcAddress(hModule, "DecryptMessage");
   ptr_DeleteSecurityContext = (__vartype(ptr_DeleteSecurityContext))GetProcAddress(hModule, "DeleteSecurityContext");
   ptr_DeleteSecurityPackageA = (__vartype(ptr_DeleteSecurityPackageA))GetProcAddress(hModule, "DeleteSecurityPackageA");
   ptr_DeleteSecurityPackageW = (__vartype(ptr_DeleteSecurityPackageW))GetProcAddress(hModule, "DeleteSecurityPackageW");
   ptr_EncryptMessage = (__vartype(ptr_EncryptMessage))GetProcAddress(hModule, "EncryptMessage");
   ptr_EnumerateSecurityPackagesA = (__vartype(ptr_EnumerateSecurityPackagesA))GetProcAddress(hModule, "EnumerateSecurityPackagesA");
   ptr_EnumerateSecurityPackagesW = (__vartype(ptr_EnumerateSecurityPackagesW))GetProcAddress(hModule, "EnumerateSecurityPackagesW");
   ptr_ExportSecurityContext = (__vartype(ptr_ExportSecurityContext))GetProcAddress(hModule, "ExportSecurityContext");
   ptr_FreeContextBuffer = (__vartype(ptr_FreeContextBuffer))GetProcAddress(hModule, "FreeContextBuffer");
   ptr_FreeCredentialsHandle = (__vartype(ptr_FreeCredentialsHandle))GetProcAddress(hModule, "FreeCredentialsHandle");
   ptr_GetSecurityUserInfo = (__vartype(ptr_GetSecurityUserInfo))GetProcAddress(hModule, "GetSecurityUserInfo");
   ptr_GetUserNameExA = (__vartype(ptr_GetUserNameExA))GetProcAddress(hModule, "GetUserNameExA");
   ptr_GetUserNameExW = (__vartype(ptr_GetUserNameExW))GetProcAddress(hModule, "GetUserNameExW");
   ptr_ImpersonateSecurityContext = (__vartype(ptr_ImpersonateSecurityContext))GetProcAddress(hModule, "ImpersonateSecurityContext");
   ptr_ImportSecurityContextA = (__vartype(ptr_ImportSecurityContextA))GetProcAddress(hModule, "ImportSecurityContextA");
   ptr_ImportSecurityContextW = (__vartype(ptr_ImportSecurityContextW))GetProcAddress(hModule, "ImportSecurityContextW");
   ptr_InitSecurityInterfaceA = (__vartype(ptr_InitSecurityInterfaceA))GetProcAddress(hModule, "InitSecurityInterfaceA");
   ptr_InitSecurityInterfaceW = (__vartype(ptr_InitSecurityInterfaceW))GetProcAddress(hModule, "InitSecurityInterfaceW");
   ptr_InitializeSecurityContextA = (__vartype(ptr_InitializeSecurityContextA))GetProcAddress(hModule, "InitializeSecurityContextA");
   ptr_InitializeSecurityContextW = (__vartype(ptr_InitializeSecurityContextW))GetProcAddress(hModule, "InitializeSecurityContextW");
   ptr_LogonUserExExW = (__vartype(ptr_LogonUserExExW))GetProcAddress(hModule, "LogonUserExExW");
   ptr_LsaCallAuthenticationPackage = (__vartype(ptr_LsaCallAuthenticationPackage))GetProcAddress(hModule, "LsaCallAuthenticationPackage");
   ptr_LsaConnectUntrusted = (__vartype(ptr_LsaConnectUntrusted))GetProcAddress(hModule, "LsaConnectUntrusted");
   ptr_LsaDeregisterLogonProcess = (__vartype(ptr_LsaDeregisterLogonProcess))GetProcAddress(hModule, "LsaDeregisterLogonProcess");
   ptr_LsaEnumerateLogonSessions = (__vartype(ptr_LsaEnumerateLogonSessions))GetProcAddress(hModule, "LsaEnumerateLogonSessions");
   ptr_LsaFreeReturnBuffer = (__vartype(ptr_LsaFreeReturnBuffer))GetProcAddress(hModule, "LsaFreeReturnBuffer");
   ptr_LsaGetLogonSessionData = (__vartype(ptr_LsaGetLogonSessionData))GetProcAddress(hModule, "LsaGetLogonSessionData");
   ptr_LsaLogonUser = (__vartype(ptr_LsaLogonUser))GetProcAddress(hModule, "LsaLogonUser");
   ptr_LsaLookupAuthenticationPackage = (__vartype(ptr_LsaLookupAuthenticationPackage))GetProcAddress(hModule, "LsaLookupAuthenticationPackage");
   ptr_LsaRegisterLogonProcess = (__vartype(ptr_LsaRegisterLogonProcess))GetProcAddress(hModule, "LsaRegisterLogonProcess");
   ptr_LsaRegisterPolicyChangeNotification = (__vartype(ptr_LsaRegisterPolicyChangeNotification))GetProcAddress(hModule, "LsaRegisterPolicyChangeNotification");
   ptr_LsaUnregisterPolicyChangeNotification = (__vartype(ptr_LsaUnregisterPolicyChangeNotification))GetProcAddress(hModule, "LsaUnregisterPolicyChangeNotification");
   ptr_MakeSignature = (__vartype(ptr_MakeSignature))GetProcAddress(hModule, "MakeSignature");
   ptr_QueryContextAttributesA = (__vartype(ptr_QueryContextAttributesA))GetProcAddress(hModule, "QueryContextAttributesA");
   ptr_QueryContextAttributesW = (__vartype(ptr_QueryContextAttributesW))GetProcAddress(hModule, "QueryContextAttributesW");
   ptr_QueryCredentialsAttributesA = (__vartype(ptr_QueryCredentialsAttributesA))GetProcAddress(hModule, "QueryCredentialsAttributesA");
   ptr_QueryCredentialsAttributesW = (__vartype(ptr_QueryCredentialsAttributesW))GetProcAddress(hModule, "QueryCredentialsAttributesW");
   ptr_QuerySecurityContextToken = (__vartype(ptr_QuerySecurityContextToken))GetProcAddress(hModule, "QuerySecurityContextToken");
   ptr_QuerySecurityPackageInfoA = (__vartype(ptr_QuerySecurityPackageInfoA))GetProcAddress(hModule, "QuerySecurityPackageInfoA");
   ptr_QuerySecurityPackageInfoW = (__vartype(ptr_QuerySecurityPackageInfoW))GetProcAddress(hModule, "QuerySecurityPackageInfoW");
   ptr_RevertSecurityContext = (__vartype(ptr_RevertSecurityContext))GetProcAddress(hModule, "RevertSecurityContext");
   ptr_SaslAcceptSecurityContext = (__vartype(ptr_SaslAcceptSecurityContext))GetProcAddress(hModule, "SaslAcceptSecurityContext");
   ptr_SaslEnumerateProfilesA = (__vartype(ptr_SaslEnumerateProfilesA))GetProcAddress(hModule, "SaslEnumerateProfilesA");
   ptr_SaslEnumerateProfilesW = (__vartype(ptr_SaslEnumerateProfilesW))GetProcAddress(hModule, "SaslEnumerateProfilesW");
   ptr_SaslGetContextOption = (__vartype(ptr_SaslGetContextOption))GetProcAddress(hModule, "SaslGetContextOption");
   ptr_SaslGetProfilePackageA = (__vartype(ptr_SaslGetProfilePackageA))GetProcAddress(hModule, "SaslGetProfilePackageA");
   ptr_SaslGetProfilePackageW = (__vartype(ptr_SaslGetProfilePackageW))GetProcAddress(hModule, "SaslGetProfilePackageW");
   ptr_SaslIdentifyPackageA = (__vartype(ptr_SaslIdentifyPackageA))GetProcAddress(hModule, "SaslIdentifyPackageA");
   ptr_SaslIdentifyPackageW = (__vartype(ptr_SaslIdentifyPackageW))GetProcAddress(hModule, "SaslIdentifyPackageW");
   ptr_SaslInitializeSecurityContextA = (__vartype(ptr_SaslInitializeSecurityContextA))GetProcAddress(hModule, "SaslInitializeSecurityContextA");
   ptr_SaslInitializeSecurityContextW = (__vartype(ptr_SaslInitializeSecurityContextW))GetProcAddress(hModule, "SaslInitializeSecurityContextW");
   ptr_SaslSetContextOption = (__vartype(ptr_SaslSetContextOption))GetProcAddress(hModule, "SaslSetContextOption");
   ptr_SealMessage = (__vartype(ptr_SealMessage))GetProcAddress(hModule, "SealMessage");
   ptr_SecCacheSspiPackages = (__vartype(ptr_SecCacheSspiPackages))GetProcAddress(hModule, "SecCacheSspiPackages");
   ptr_SecDeleteUserModeContext = (__vartype(ptr_SecDeleteUserModeContext))GetProcAddress(hModule, "SecDeleteUserModeContext");
   ptr_SecInitUserModeContext = (__vartype(ptr_SecInitUserModeContext))GetProcAddress(hModule, "SecInitUserModeContext");
   ptr_SeciAllocateAndSetCallFlags = (__vartype(ptr_SeciAllocateAndSetCallFlags))GetProcAddress(hModule, "SeciAllocateAndSetCallFlags");
   ptr_SeciAllocateAndSetIPAddress = (__vartype(ptr_SeciAllocateAndSetIPAddress))GetProcAddress(hModule, "SeciAllocateAndSetIPAddress");
   ptr_SeciFreeCallContext = (__vartype(ptr_SeciFreeCallContext))GetProcAddress(hModule, "SeciFreeCallContext");
   ptr_SetContextAttributesA = (__vartype(ptr_SetContextAttributesA))GetProcAddress(hModule, "SetContextAttributesA");
   ptr_SetContextAttributesW = (__vartype(ptr_SetContextAttributesW))GetProcAddress(hModule, "SetContextAttributesW");
   ptr_SetCredentialsAttributesA = (__vartype(ptr_SetCredentialsAttributesA))GetProcAddress(hModule, "SetCredentialsAttributesA");
   ptr_SetCredentialsAttributesW = (__vartype(ptr_SetCredentialsAttributesW))GetProcAddress(hModule, "SetCredentialsAttributesW");
   ptr_SspiCompareAuthIdentities = (__vartype(ptr_SspiCompareAuthIdentities))GetProcAddress(hModule, "SspiCompareAuthIdentities");
   ptr_SspiCopyAuthIdentity = (__vartype(ptr_SspiCopyAuthIdentity))GetProcAddress(hModule, "SspiCopyAuthIdentity");
   ptr_SspiDecryptAuthIdentity = (__vartype(ptr_SspiDecryptAuthIdentity))GetProcAddress(hModule, "SspiDecryptAuthIdentity");
   ptr_SspiEncodeAuthIdentityAsStrings = (__vartype(ptr_SspiEncodeAuthIdentityAsStrings))GetProcAddress(hModule, "SspiEncodeAuthIdentityAsStrings");
   ptr_SspiEncodeStringsAsAuthIdentity = (__vartype(ptr_SspiEncodeStringsAsAuthIdentity))GetProcAddress(hModule, "SspiEncodeStringsAsAuthIdentity");
   ptr_SspiEncryptAuthIdentity = (__vartype(ptr_SspiEncryptAuthIdentity))GetProcAddress(hModule, "SspiEncryptAuthIdentity");
   ptr_SspiExcludePackage = (__vartype(ptr_SspiExcludePackage))GetProcAddress(hModule, "SspiExcludePackage");
   ptr_SspiFreeAuthIdentity = (__vartype(ptr_SspiFreeAuthIdentity))GetProcAddress(hModule, "SspiFreeAuthIdentity");
   ptr_SspiGetComputerNameForSPN = (__vartype(ptr_SspiGetComputerNameForSPN))GetProcAddress(hModule, "SspiGetComputerNameForSPN");
   ptr_SspiGetTargetHostName = (__vartype(ptr_SspiGetTargetHostName))GetProcAddress(hModule, "SspiGetTargetHostName");
   ptr_SspiIsAuthIdentityEncrypted = (__vartype(ptr_SspiIsAuthIdentityEncrypted))GetProcAddress(hModule, "SspiIsAuthIdentityEncrypted");
   ptr_SspiLocalFree = (__vartype(ptr_SspiLocalFree))GetProcAddress(hModule, "SspiLocalFree");
   ptr_SspiMarshalAuthIdentity = (__vartype(ptr_SspiMarshalAuthIdentity))GetProcAddress(hModule, "SspiMarshalAuthIdentity");
   ptr_SspiPrepareForCredRead = (__vartype(ptr_SspiPrepareForCredRead))GetProcAddress(hModule, "SspiPrepareForCredRead");
   ptr_SspiPrepareForCredWrite = (__vartype(ptr_SspiPrepareForCredWrite))GetProcAddress(hModule, "SspiPrepareForCredWrite");
   ptr_SspiUnmarshalAuthIdentity = (__vartype(ptr_SspiUnmarshalAuthIdentity))GetProcAddress(hModule, "SspiUnmarshalAuthIdentity");
   ptr_SspiUnmarshalAuthIdentityInternal = (__vartype(ptr_SspiUnmarshalAuthIdentityInternal))GetProcAddress(hModule, "SspiUnmarshalAuthIdentityInternal");
   ptr_SspiValidateAuthIdentity = (__vartype(ptr_SspiValidateAuthIdentity))GetProcAddress(hModule, "SspiValidateAuthIdentity");
   ptr_SspiZeroAuthIdentity = (__vartype(ptr_SspiZeroAuthIdentity))GetProcAddress(hModule, "SspiZeroAuthIdentity");
   ptr_UnsealMessage = (__vartype(ptr_UnsealMessage))GetProcAddress(hModule, "UnsealMessage");
   ptr_VerifySignature = (__vartype(ptr_VerifySignature))GetProcAddress(hModule, "VerifySignature");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

