#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_AddClusterNode;
void *ptr_AddClusterNode = NULL;
extern void *ptr_AddClusterResourceDependency;
void *ptr_AddClusterResourceDependency = NULL;
extern void *ptr_AddClusterResourceNode;
void *ptr_AddClusterResourceNode = NULL;
extern void *ptr_AddResourceToClusterSharedVolumes;
void *ptr_AddResourceToClusterSharedVolumes = NULL;
extern void *ptr_BackupClusterDatabase;
void *ptr_BackupClusterDatabase = NULL;
extern void *ptr_CanResourceBeDependent;
void *ptr_CanResourceBeDependent = NULL;
extern void *ptr_ChangeClusterResourceGroup;
void *ptr_ChangeClusterResourceGroup = NULL;
extern void *ptr_CloseCluster;
void *ptr_CloseCluster = NULL;
extern void *ptr_CloseClusterGroup;
void *ptr_CloseClusterGroup = NULL;
extern void *ptr_CloseClusterNetInterface;
void *ptr_CloseClusterNetInterface = NULL;
extern void *ptr_CloseClusterNetwork;
void *ptr_CloseClusterNetwork = NULL;
extern void *ptr_CloseClusterNode;
void *ptr_CloseClusterNode = NULL;
extern void *ptr_CloseClusterNotifyPort;
void *ptr_CloseClusterNotifyPort = NULL;
extern void *ptr_CloseClusterResource;
void *ptr_CloseClusterResource = NULL;
extern void *ptr_ClusterCloseEnum;
void *ptr_ClusterCloseEnum = NULL;
extern void *ptr_ClusterCloseEnumEx;
void *ptr_ClusterCloseEnumEx = NULL;
extern void *ptr_ClusterControl;
void *ptr_ClusterControl = NULL;
extern void *ptr_ClusterEnum;
void *ptr_ClusterEnum = NULL;
extern void *ptr_ClusterEnumEx;
void *ptr_ClusterEnumEx = NULL;
extern void *ptr_ClusterGetEnumCount;
void *ptr_ClusterGetEnumCount = NULL;
extern void *ptr_ClusterGetEnumCountEx;
void *ptr_ClusterGetEnumCountEx = NULL;
extern void *ptr_ClusterGroupCloseEnum;
void *ptr_ClusterGroupCloseEnum = NULL;
extern void *ptr_ClusterGroupControl;
void *ptr_ClusterGroupControl = NULL;
extern void *ptr_ClusterGroupEnum;
void *ptr_ClusterGroupEnum = NULL;
extern void *ptr_ClusterGroupGetEnumCount;
void *ptr_ClusterGroupGetEnumCount = NULL;
extern void *ptr_ClusterGroupOpenEnum;
void *ptr_ClusterGroupOpenEnum = NULL;
extern void *ptr_ClusterNetInterfaceControl;
void *ptr_ClusterNetInterfaceControl = NULL;
extern void *ptr_ClusterNetworkCloseEnum;
void *ptr_ClusterNetworkCloseEnum = NULL;
extern void *ptr_ClusterNetworkControl;
void *ptr_ClusterNetworkControl = NULL;
extern void *ptr_ClusterNetworkEnum;
void *ptr_ClusterNetworkEnum = NULL;
extern void *ptr_ClusterNetworkGetEnumCount;
void *ptr_ClusterNetworkGetEnumCount = NULL;
extern void *ptr_ClusterNetworkOpenEnum;
void *ptr_ClusterNetworkOpenEnum = NULL;
extern void *ptr_ClusterNodeCloseEnum;
void *ptr_ClusterNodeCloseEnum = NULL;
extern void *ptr_ClusterNodeCloseEnumEx;
void *ptr_ClusterNodeCloseEnumEx = NULL;
extern void *ptr_ClusterNodeControl;
void *ptr_ClusterNodeControl = NULL;
extern void *ptr_ClusterNodeEnum;
void *ptr_ClusterNodeEnum = NULL;
extern void *ptr_ClusterNodeEnumEx;
void *ptr_ClusterNodeEnumEx = NULL;
extern void *ptr_ClusterNodeGetEnumCount;
void *ptr_ClusterNodeGetEnumCount = NULL;
extern void *ptr_ClusterNodeGetEnumCountEx;
void *ptr_ClusterNodeGetEnumCountEx = NULL;
extern void *ptr_ClusterNodeOpenEnum;
void *ptr_ClusterNodeOpenEnum = NULL;
extern void *ptr_ClusterNodeOpenEnumEx;
void *ptr_ClusterNodeOpenEnumEx = NULL;
extern void *ptr_ClusterOpenEnum;
void *ptr_ClusterOpenEnum = NULL;
extern void *ptr_ClusterOpenEnumEx;
void *ptr_ClusterOpenEnumEx = NULL;
extern void *ptr_ClusterRegBatchAddCommand;
void *ptr_ClusterRegBatchAddCommand = NULL;
extern void *ptr_ClusterRegBatchCloseNotification;
void *ptr_ClusterRegBatchCloseNotification = NULL;
extern void *ptr_ClusterRegBatchReadCommand;
void *ptr_ClusterRegBatchReadCommand = NULL;
extern void *ptr_ClusterRegCloseBatch;
void *ptr_ClusterRegCloseBatch = NULL;
extern void *ptr_ClusterRegCloseBatchNotifyPort;
void *ptr_ClusterRegCloseBatchNotifyPort = NULL;
extern void *ptr_ClusterRegCloseKey;
void *ptr_ClusterRegCloseKey = NULL;
extern void *ptr_ClusterRegCreateBatch;
void *ptr_ClusterRegCreateBatch = NULL;
extern void *ptr_ClusterRegCreateBatchNotifyPort;
void *ptr_ClusterRegCreateBatchNotifyPort = NULL;
extern void *ptr_ClusterRegCreateKey;
void *ptr_ClusterRegCreateKey = NULL;
extern void *ptr_ClusterRegDeleteKey;
void *ptr_ClusterRegDeleteKey = NULL;
extern void *ptr_ClusterRegDeleteValue;
void *ptr_ClusterRegDeleteValue = NULL;
extern void *ptr_ClusterRegEnumKey;
void *ptr_ClusterRegEnumKey = NULL;
extern void *ptr_ClusterRegEnumValue;
void *ptr_ClusterRegEnumValue = NULL;
extern void *ptr_ClusterRegGetBatchNotification;
void *ptr_ClusterRegGetBatchNotification = NULL;
extern void *ptr_ClusterRegGetKeySecurity;
void *ptr_ClusterRegGetKeySecurity = NULL;
extern void *ptr_ClusterRegOpenKey;
void *ptr_ClusterRegOpenKey = NULL;
extern void *ptr_ClusterRegQueryInfoKey;
void *ptr_ClusterRegQueryInfoKey = NULL;
extern void *ptr_ClusterRegQueryValue;
void *ptr_ClusterRegQueryValue = NULL;
extern void *ptr_ClusterRegSetKeySecurity;
void *ptr_ClusterRegSetKeySecurity = NULL;
extern void *ptr_ClusterRegSetValue;
void *ptr_ClusterRegSetValue = NULL;
extern void *ptr_ClusterResourceCloseEnum;
void *ptr_ClusterResourceCloseEnum = NULL;
extern void *ptr_ClusterResourceControl;
void *ptr_ClusterResourceControl = NULL;
extern void *ptr_ClusterResourceEnum;
void *ptr_ClusterResourceEnum = NULL;
extern void *ptr_ClusterResourceGetEnumCount;
void *ptr_ClusterResourceGetEnumCount = NULL;
extern void *ptr_ClusterResourceOpenEnum;
void *ptr_ClusterResourceOpenEnum = NULL;
extern void *ptr_ClusterResourceTypeCloseEnum;
void *ptr_ClusterResourceTypeCloseEnum = NULL;
extern void *ptr_ClusterResourceTypeControl;
void *ptr_ClusterResourceTypeControl = NULL;
extern void *ptr_ClusterResourceTypeEnum;
void *ptr_ClusterResourceTypeEnum = NULL;
extern void *ptr_ClusterResourceTypeGetEnumCount;
void *ptr_ClusterResourceTypeGetEnumCount = NULL;
extern void *ptr_ClusterResourceTypeOpenEnum;
void *ptr_ClusterResourceTypeOpenEnum = NULL;
extern void *ptr_ClusterSharedVolumeClearBackupState;
void *ptr_ClusterSharedVolumeClearBackupState = NULL;
extern void *ptr_CreateCluster;
void *ptr_CreateCluster = NULL;
extern void *ptr_CreateClusterGroup;
void *ptr_CreateClusterGroup = NULL;
extern void *ptr_CreateClusterNotifyPort;
void *ptr_CreateClusterNotifyPort = NULL;
extern void *ptr_CreateClusterResource;
void *ptr_CreateClusterResource = NULL;
extern void *ptr_CreateClusterResourceType;
void *ptr_CreateClusterResourceType = NULL;
extern void *ptr_DeleteClusterGroup;
void *ptr_DeleteClusterGroup = NULL;
extern void *ptr_DeleteClusterResource;
void *ptr_DeleteClusterResource = NULL;
extern void *ptr_DeleteClusterResourceType;
void *ptr_DeleteClusterResourceType = NULL;
extern void *ptr_DestroyCluster;
void *ptr_DestroyCluster = NULL;
extern void *ptr_DestroyClusterGroup;
void *ptr_DestroyClusterGroup = NULL;
extern void *ptr_EvictClusterNode;
void *ptr_EvictClusterNode = NULL;
extern void *ptr_EvictClusterNodeEx;
void *ptr_EvictClusterNodeEx = NULL;
extern void *ptr_FailClusterResource;
void *ptr_FailClusterResource = NULL;
extern void *ptr_GetClusterFromGroup;
void *ptr_GetClusterFromGroup = NULL;
extern void *ptr_GetClusterFromNetInterface;
void *ptr_GetClusterFromNetInterface = NULL;
extern void *ptr_GetClusterFromNetwork;
void *ptr_GetClusterFromNetwork = NULL;
extern void *ptr_GetClusterFromNode;
void *ptr_GetClusterFromNode = NULL;
extern void *ptr_GetClusterFromResource;
void *ptr_GetClusterFromResource = NULL;
extern void *ptr_GetClusterGroupKey;
void *ptr_GetClusterGroupKey = NULL;
extern void *ptr_GetClusterGroupState;
void *ptr_GetClusterGroupState = NULL;
extern void *ptr_GetClusterInformation;
void *ptr_GetClusterInformation = NULL;
extern void *ptr_GetClusterKey;
void *ptr_GetClusterKey = NULL;
extern void *ptr_GetClusterNetInterface;
void *ptr_GetClusterNetInterface = NULL;
extern void *ptr_GetClusterNetInterfaceKey;
void *ptr_GetClusterNetInterfaceKey = NULL;
extern void *ptr_GetClusterNetInterfaceState;
void *ptr_GetClusterNetInterfaceState = NULL;
extern void *ptr_GetClusterNetworkId;
void *ptr_GetClusterNetworkId = NULL;
extern void *ptr_GetClusterNetworkKey;
void *ptr_GetClusterNetworkKey = NULL;
extern void *ptr_GetClusterNetworkState;
void *ptr_GetClusterNetworkState = NULL;
extern void *ptr_GetClusterNodeId;
void *ptr_GetClusterNodeId = NULL;
extern void *ptr_GetClusterNodeKey;
void *ptr_GetClusterNodeKey = NULL;
extern void *ptr_GetClusterNodeState;
void *ptr_GetClusterNodeState = NULL;
extern void *ptr_GetClusterNotify;
void *ptr_GetClusterNotify = NULL;
extern void *ptr_GetClusterQuorumResource;
void *ptr_GetClusterQuorumResource = NULL;
extern void *ptr_GetClusterResourceDependencyExpression;
void *ptr_GetClusterResourceDependencyExpression = NULL;
extern void *ptr_GetClusterResourceKey;
void *ptr_GetClusterResourceKey = NULL;
extern void *ptr_GetClusterResourceNetworkName;
void *ptr_GetClusterResourceNetworkName = NULL;
extern void *ptr_GetClusterResourceState;
void *ptr_GetClusterResourceState = NULL;
extern void *ptr_GetClusterResourceTypeKey;
void *ptr_GetClusterResourceTypeKey = NULL;
extern void *ptr_GetClusterSharedVolumeNameForFile;
void *ptr_GetClusterSharedVolumeNameForFile = NULL;
extern void *ptr_GetNodeClusterState;
void *ptr_GetNodeClusterState = NULL;
extern void *ptr_IsFileOnClusterSharedVolume;
void *ptr_IsFileOnClusterSharedVolume = NULL;
extern void *ptr_MoveClusterGroup;
void *ptr_MoveClusterGroup = NULL;
extern void *ptr_OfflineClusterGroup;
void *ptr_OfflineClusterGroup = NULL;
extern void *ptr_OfflineClusterResource;
void *ptr_OfflineClusterResource = NULL;
extern void *ptr_OnlineClusterGroup;
void *ptr_OnlineClusterGroup = NULL;
extern void *ptr_OnlineClusterResource;
void *ptr_OnlineClusterResource = NULL;
extern void *ptr_OpenCluster;
void *ptr_OpenCluster = NULL;
extern void *ptr_OpenClusterEx;
void *ptr_OpenClusterEx = NULL;
extern void *ptr_OpenClusterGroup;
void *ptr_OpenClusterGroup = NULL;
extern void *ptr_OpenClusterGroupEx;
void *ptr_OpenClusterGroupEx = NULL;
extern void *ptr_OpenClusterNetInterface;
void *ptr_OpenClusterNetInterface = NULL;
extern void *ptr_OpenClusterNetInterfaceEx;
void *ptr_OpenClusterNetInterfaceEx = NULL;
extern void *ptr_OpenClusterNetwork;
void *ptr_OpenClusterNetwork = NULL;
extern void *ptr_OpenClusterNetworkEx;
void *ptr_OpenClusterNetworkEx = NULL;
extern void *ptr_OpenClusterNode;
void *ptr_OpenClusterNode = NULL;
extern void *ptr_OpenClusterNodeEx;
void *ptr_OpenClusterNodeEx = NULL;
extern void *ptr_OpenClusterResource;
void *ptr_OpenClusterResource = NULL;
extern void *ptr_OpenClusterResourceEx;
void *ptr_OpenClusterResourceEx = NULL;
extern void *ptr_PauseClusterNode;
void *ptr_PauseClusterNode = NULL;
extern void *ptr_RegisterClusterNotify;
void *ptr_RegisterClusterNotify = NULL;
extern void *ptr_RemoveClusterResourceDependency;
void *ptr_RemoveClusterResourceDependency = NULL;
extern void *ptr_RemoveClusterResourceNode;
void *ptr_RemoveClusterResourceNode = NULL;
extern void *ptr_RemoveResourceFromClusterSharedVolumes;
void *ptr_RemoveResourceFromClusterSharedVolumes = NULL;
extern void *ptr_RestoreClusterDatabase;
void *ptr_RestoreClusterDatabase = NULL;
extern void *ptr_ResumeClusterNode;
void *ptr_ResumeClusterNode = NULL;
extern void *ptr_SetClusterGroupName;
void *ptr_SetClusterGroupName = NULL;
extern void *ptr_SetClusterGroupNodeList;
void *ptr_SetClusterGroupNodeList = NULL;
extern void *ptr_SetClusterName;
void *ptr_SetClusterName = NULL;
extern void *ptr_SetClusterNetworkName;
void *ptr_SetClusterNetworkName = NULL;
extern void *ptr_SetClusterNetworkPriorityOrder;
void *ptr_SetClusterNetworkPriorityOrder = NULL;
extern void *ptr_SetClusterQuorumResource;
void *ptr_SetClusterQuorumResource = NULL;
extern void *ptr_SetClusterResourceDependencyExpression;
void *ptr_SetClusterResourceDependencyExpression = NULL;
extern void *ptr_SetClusterResourceName;
void *ptr_SetClusterResourceName = NULL;
extern void *ptr_SetClusterServiceAccountPassword;
void *ptr_SetClusterServiceAccountPassword = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\clusapi.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_AddClusterNode = (__vartype(ptr_AddClusterNode))GetProcAddress(hModule, "AddClusterNode");
   ptr_AddClusterResourceDependency = (__vartype(ptr_AddClusterResourceDependency))GetProcAddress(hModule, "AddClusterResourceDependency");
   ptr_AddClusterResourceNode = (__vartype(ptr_AddClusterResourceNode))GetProcAddress(hModule, "AddClusterResourceNode");
   ptr_AddResourceToClusterSharedVolumes = (__vartype(ptr_AddResourceToClusterSharedVolumes))GetProcAddress(hModule, "AddResourceToClusterSharedVolumes");
   ptr_BackupClusterDatabase = (__vartype(ptr_BackupClusterDatabase))GetProcAddress(hModule, "BackupClusterDatabase");
   ptr_CanResourceBeDependent = (__vartype(ptr_CanResourceBeDependent))GetProcAddress(hModule, "CanResourceBeDependent");
   ptr_ChangeClusterResourceGroup = (__vartype(ptr_ChangeClusterResourceGroup))GetProcAddress(hModule, "ChangeClusterResourceGroup");
   ptr_CloseCluster = (__vartype(ptr_CloseCluster))GetProcAddress(hModule, "CloseCluster");
   ptr_CloseClusterGroup = (__vartype(ptr_CloseClusterGroup))GetProcAddress(hModule, "CloseClusterGroup");
   ptr_CloseClusterNetInterface = (__vartype(ptr_CloseClusterNetInterface))GetProcAddress(hModule, "CloseClusterNetInterface");
   ptr_CloseClusterNetwork = (__vartype(ptr_CloseClusterNetwork))GetProcAddress(hModule, "CloseClusterNetwork");
   ptr_CloseClusterNode = (__vartype(ptr_CloseClusterNode))GetProcAddress(hModule, "CloseClusterNode");
   ptr_CloseClusterNotifyPort = (__vartype(ptr_CloseClusterNotifyPort))GetProcAddress(hModule, "CloseClusterNotifyPort");
   ptr_CloseClusterResource = (__vartype(ptr_CloseClusterResource))GetProcAddress(hModule, "CloseClusterResource");
   ptr_ClusterCloseEnum = (__vartype(ptr_ClusterCloseEnum))GetProcAddress(hModule, "ClusterCloseEnum");
   ptr_ClusterCloseEnumEx = (__vartype(ptr_ClusterCloseEnumEx))GetProcAddress(hModule, "ClusterCloseEnumEx");
   ptr_ClusterControl = (__vartype(ptr_ClusterControl))GetProcAddress(hModule, "ClusterControl");
   ptr_ClusterEnum = (__vartype(ptr_ClusterEnum))GetProcAddress(hModule, "ClusterEnum");
   ptr_ClusterEnumEx = (__vartype(ptr_ClusterEnumEx))GetProcAddress(hModule, "ClusterEnumEx");
   ptr_ClusterGetEnumCount = (__vartype(ptr_ClusterGetEnumCount))GetProcAddress(hModule, "ClusterGetEnumCount");
   ptr_ClusterGetEnumCountEx = (__vartype(ptr_ClusterGetEnumCountEx))GetProcAddress(hModule, "ClusterGetEnumCountEx");
   ptr_ClusterGroupCloseEnum = (__vartype(ptr_ClusterGroupCloseEnum))GetProcAddress(hModule, "ClusterGroupCloseEnum");
   ptr_ClusterGroupControl = (__vartype(ptr_ClusterGroupControl))GetProcAddress(hModule, "ClusterGroupControl");
   ptr_ClusterGroupEnum = (__vartype(ptr_ClusterGroupEnum))GetProcAddress(hModule, "ClusterGroupEnum");
   ptr_ClusterGroupGetEnumCount = (__vartype(ptr_ClusterGroupGetEnumCount))GetProcAddress(hModule, "ClusterGroupGetEnumCount");
   ptr_ClusterGroupOpenEnum = (__vartype(ptr_ClusterGroupOpenEnum))GetProcAddress(hModule, "ClusterGroupOpenEnum");
   ptr_ClusterNetInterfaceControl = (__vartype(ptr_ClusterNetInterfaceControl))GetProcAddress(hModule, "ClusterNetInterfaceControl");
   ptr_ClusterNetworkCloseEnum = (__vartype(ptr_ClusterNetworkCloseEnum))GetProcAddress(hModule, "ClusterNetworkCloseEnum");
   ptr_ClusterNetworkControl = (__vartype(ptr_ClusterNetworkControl))GetProcAddress(hModule, "ClusterNetworkControl");
   ptr_ClusterNetworkEnum = (__vartype(ptr_ClusterNetworkEnum))GetProcAddress(hModule, "ClusterNetworkEnum");
   ptr_ClusterNetworkGetEnumCount = (__vartype(ptr_ClusterNetworkGetEnumCount))GetProcAddress(hModule, "ClusterNetworkGetEnumCount");
   ptr_ClusterNetworkOpenEnum = (__vartype(ptr_ClusterNetworkOpenEnum))GetProcAddress(hModule, "ClusterNetworkOpenEnum");
   ptr_ClusterNodeCloseEnum = (__vartype(ptr_ClusterNodeCloseEnum))GetProcAddress(hModule, "ClusterNodeCloseEnum");
   ptr_ClusterNodeCloseEnumEx = (__vartype(ptr_ClusterNodeCloseEnumEx))GetProcAddress(hModule, "ClusterNodeCloseEnumEx");
   ptr_ClusterNodeControl = (__vartype(ptr_ClusterNodeControl))GetProcAddress(hModule, "ClusterNodeControl");
   ptr_ClusterNodeEnum = (__vartype(ptr_ClusterNodeEnum))GetProcAddress(hModule, "ClusterNodeEnum");
   ptr_ClusterNodeEnumEx = (__vartype(ptr_ClusterNodeEnumEx))GetProcAddress(hModule, "ClusterNodeEnumEx");
   ptr_ClusterNodeGetEnumCount = (__vartype(ptr_ClusterNodeGetEnumCount))GetProcAddress(hModule, "ClusterNodeGetEnumCount");
   ptr_ClusterNodeGetEnumCountEx = (__vartype(ptr_ClusterNodeGetEnumCountEx))GetProcAddress(hModule, "ClusterNodeGetEnumCountEx");
   ptr_ClusterNodeOpenEnum = (__vartype(ptr_ClusterNodeOpenEnum))GetProcAddress(hModule, "ClusterNodeOpenEnum");
   ptr_ClusterNodeOpenEnumEx = (__vartype(ptr_ClusterNodeOpenEnumEx))GetProcAddress(hModule, "ClusterNodeOpenEnumEx");
   ptr_ClusterOpenEnum = (__vartype(ptr_ClusterOpenEnum))GetProcAddress(hModule, "ClusterOpenEnum");
   ptr_ClusterOpenEnumEx = (__vartype(ptr_ClusterOpenEnumEx))GetProcAddress(hModule, "ClusterOpenEnumEx");
   ptr_ClusterRegBatchAddCommand = (__vartype(ptr_ClusterRegBatchAddCommand))GetProcAddress(hModule, "ClusterRegBatchAddCommand");
   ptr_ClusterRegBatchCloseNotification = (__vartype(ptr_ClusterRegBatchCloseNotification))GetProcAddress(hModule, "ClusterRegBatchCloseNotification");
   ptr_ClusterRegBatchReadCommand = (__vartype(ptr_ClusterRegBatchReadCommand))GetProcAddress(hModule, "ClusterRegBatchReadCommand");
   ptr_ClusterRegCloseBatch = (__vartype(ptr_ClusterRegCloseBatch))GetProcAddress(hModule, "ClusterRegCloseBatch");
   ptr_ClusterRegCloseBatchNotifyPort = (__vartype(ptr_ClusterRegCloseBatchNotifyPort))GetProcAddress(hModule, "ClusterRegCloseBatchNotifyPort");
   ptr_ClusterRegCloseKey = (__vartype(ptr_ClusterRegCloseKey))GetProcAddress(hModule, "ClusterRegCloseKey");
   ptr_ClusterRegCreateBatch = (__vartype(ptr_ClusterRegCreateBatch))GetProcAddress(hModule, "ClusterRegCreateBatch");
   ptr_ClusterRegCreateBatchNotifyPort = (__vartype(ptr_ClusterRegCreateBatchNotifyPort))GetProcAddress(hModule, "ClusterRegCreateBatchNotifyPort");
   ptr_ClusterRegCreateKey = (__vartype(ptr_ClusterRegCreateKey))GetProcAddress(hModule, "ClusterRegCreateKey");
   ptr_ClusterRegDeleteKey = (__vartype(ptr_ClusterRegDeleteKey))GetProcAddress(hModule, "ClusterRegDeleteKey");
   ptr_ClusterRegDeleteValue = (__vartype(ptr_ClusterRegDeleteValue))GetProcAddress(hModule, "ClusterRegDeleteValue");
   ptr_ClusterRegEnumKey = (__vartype(ptr_ClusterRegEnumKey))GetProcAddress(hModule, "ClusterRegEnumKey");
   ptr_ClusterRegEnumValue = (__vartype(ptr_ClusterRegEnumValue))GetProcAddress(hModule, "ClusterRegEnumValue");
   ptr_ClusterRegGetBatchNotification = (__vartype(ptr_ClusterRegGetBatchNotification))GetProcAddress(hModule, "ClusterRegGetBatchNotification");
   ptr_ClusterRegGetKeySecurity = (__vartype(ptr_ClusterRegGetKeySecurity))GetProcAddress(hModule, "ClusterRegGetKeySecurity");
   ptr_ClusterRegOpenKey = (__vartype(ptr_ClusterRegOpenKey))GetProcAddress(hModule, "ClusterRegOpenKey");
   ptr_ClusterRegQueryInfoKey = (__vartype(ptr_ClusterRegQueryInfoKey))GetProcAddress(hModule, "ClusterRegQueryInfoKey");
   ptr_ClusterRegQueryValue = (__vartype(ptr_ClusterRegQueryValue))GetProcAddress(hModule, "ClusterRegQueryValue");
   ptr_ClusterRegSetKeySecurity = (__vartype(ptr_ClusterRegSetKeySecurity))GetProcAddress(hModule, "ClusterRegSetKeySecurity");
   ptr_ClusterRegSetValue = (__vartype(ptr_ClusterRegSetValue))GetProcAddress(hModule, "ClusterRegSetValue");
   ptr_ClusterResourceCloseEnum = (__vartype(ptr_ClusterResourceCloseEnum))GetProcAddress(hModule, "ClusterResourceCloseEnum");
   ptr_ClusterResourceControl = (__vartype(ptr_ClusterResourceControl))GetProcAddress(hModule, "ClusterResourceControl");
   ptr_ClusterResourceEnum = (__vartype(ptr_ClusterResourceEnum))GetProcAddress(hModule, "ClusterResourceEnum");
   ptr_ClusterResourceGetEnumCount = (__vartype(ptr_ClusterResourceGetEnumCount))GetProcAddress(hModule, "ClusterResourceGetEnumCount");
   ptr_ClusterResourceOpenEnum = (__vartype(ptr_ClusterResourceOpenEnum))GetProcAddress(hModule, "ClusterResourceOpenEnum");
   ptr_ClusterResourceTypeCloseEnum = (__vartype(ptr_ClusterResourceTypeCloseEnum))GetProcAddress(hModule, "ClusterResourceTypeCloseEnum");
   ptr_ClusterResourceTypeControl = (__vartype(ptr_ClusterResourceTypeControl))GetProcAddress(hModule, "ClusterResourceTypeControl");
   ptr_ClusterResourceTypeEnum = (__vartype(ptr_ClusterResourceTypeEnum))GetProcAddress(hModule, "ClusterResourceTypeEnum");
   ptr_ClusterResourceTypeGetEnumCount = (__vartype(ptr_ClusterResourceTypeGetEnumCount))GetProcAddress(hModule, "ClusterResourceTypeGetEnumCount");
   ptr_ClusterResourceTypeOpenEnum = (__vartype(ptr_ClusterResourceTypeOpenEnum))GetProcAddress(hModule, "ClusterResourceTypeOpenEnum");
   ptr_ClusterSharedVolumeClearBackupState = (__vartype(ptr_ClusterSharedVolumeClearBackupState))GetProcAddress(hModule, "ClusterSharedVolumeClearBackupState");
   ptr_CreateCluster = (__vartype(ptr_CreateCluster))GetProcAddress(hModule, "CreateCluster");
   ptr_CreateClusterGroup = (__vartype(ptr_CreateClusterGroup))GetProcAddress(hModule, "CreateClusterGroup");
   ptr_CreateClusterNotifyPort = (__vartype(ptr_CreateClusterNotifyPort))GetProcAddress(hModule, "CreateClusterNotifyPort");
   ptr_CreateClusterResource = (__vartype(ptr_CreateClusterResource))GetProcAddress(hModule, "CreateClusterResource");
   ptr_CreateClusterResourceType = (__vartype(ptr_CreateClusterResourceType))GetProcAddress(hModule, "CreateClusterResourceType");
   ptr_DeleteClusterGroup = (__vartype(ptr_DeleteClusterGroup))GetProcAddress(hModule, "DeleteClusterGroup");
   ptr_DeleteClusterResource = (__vartype(ptr_DeleteClusterResource))GetProcAddress(hModule, "DeleteClusterResource");
   ptr_DeleteClusterResourceType = (__vartype(ptr_DeleteClusterResourceType))GetProcAddress(hModule, "DeleteClusterResourceType");
   ptr_DestroyCluster = (__vartype(ptr_DestroyCluster))GetProcAddress(hModule, "DestroyCluster");
   ptr_DestroyClusterGroup = (__vartype(ptr_DestroyClusterGroup))GetProcAddress(hModule, "DestroyClusterGroup");
   ptr_EvictClusterNode = (__vartype(ptr_EvictClusterNode))GetProcAddress(hModule, "EvictClusterNode");
   ptr_EvictClusterNodeEx = (__vartype(ptr_EvictClusterNodeEx))GetProcAddress(hModule, "EvictClusterNodeEx");
   ptr_FailClusterResource = (__vartype(ptr_FailClusterResource))GetProcAddress(hModule, "FailClusterResource");
   ptr_GetClusterFromGroup = (__vartype(ptr_GetClusterFromGroup))GetProcAddress(hModule, "GetClusterFromGroup");
   ptr_GetClusterFromNetInterface = (__vartype(ptr_GetClusterFromNetInterface))GetProcAddress(hModule, "GetClusterFromNetInterface");
   ptr_GetClusterFromNetwork = (__vartype(ptr_GetClusterFromNetwork))GetProcAddress(hModule, "GetClusterFromNetwork");
   ptr_GetClusterFromNode = (__vartype(ptr_GetClusterFromNode))GetProcAddress(hModule, "GetClusterFromNode");
   ptr_GetClusterFromResource = (__vartype(ptr_GetClusterFromResource))GetProcAddress(hModule, "GetClusterFromResource");
   ptr_GetClusterGroupKey = (__vartype(ptr_GetClusterGroupKey))GetProcAddress(hModule, "GetClusterGroupKey");
   ptr_GetClusterGroupState = (__vartype(ptr_GetClusterGroupState))GetProcAddress(hModule, "GetClusterGroupState");
   ptr_GetClusterInformation = (__vartype(ptr_GetClusterInformation))GetProcAddress(hModule, "GetClusterInformation");
   ptr_GetClusterKey = (__vartype(ptr_GetClusterKey))GetProcAddress(hModule, "GetClusterKey");
   ptr_GetClusterNetInterface = (__vartype(ptr_GetClusterNetInterface))GetProcAddress(hModule, "GetClusterNetInterface");
   ptr_GetClusterNetInterfaceKey = (__vartype(ptr_GetClusterNetInterfaceKey))GetProcAddress(hModule, "GetClusterNetInterfaceKey");
   ptr_GetClusterNetInterfaceState = (__vartype(ptr_GetClusterNetInterfaceState))GetProcAddress(hModule, "GetClusterNetInterfaceState");
   ptr_GetClusterNetworkId = (__vartype(ptr_GetClusterNetworkId))GetProcAddress(hModule, "GetClusterNetworkId");
   ptr_GetClusterNetworkKey = (__vartype(ptr_GetClusterNetworkKey))GetProcAddress(hModule, "GetClusterNetworkKey");
   ptr_GetClusterNetworkState = (__vartype(ptr_GetClusterNetworkState))GetProcAddress(hModule, "GetClusterNetworkState");
   ptr_GetClusterNodeId = (__vartype(ptr_GetClusterNodeId))GetProcAddress(hModule, "GetClusterNodeId");
   ptr_GetClusterNodeKey = (__vartype(ptr_GetClusterNodeKey))GetProcAddress(hModule, "GetClusterNodeKey");
   ptr_GetClusterNodeState = (__vartype(ptr_GetClusterNodeState))GetProcAddress(hModule, "GetClusterNodeState");
   ptr_GetClusterNotify = (__vartype(ptr_GetClusterNotify))GetProcAddress(hModule, "GetClusterNotify");
   ptr_GetClusterQuorumResource = (__vartype(ptr_GetClusterQuorumResource))GetProcAddress(hModule, "GetClusterQuorumResource");
   ptr_GetClusterResourceDependencyExpression = (__vartype(ptr_GetClusterResourceDependencyExpression))GetProcAddress(hModule, "GetClusterResourceDependencyExpression");
   ptr_GetClusterResourceKey = (__vartype(ptr_GetClusterResourceKey))GetProcAddress(hModule, "GetClusterResourceKey");
   ptr_GetClusterResourceNetworkName = (__vartype(ptr_GetClusterResourceNetworkName))GetProcAddress(hModule, "GetClusterResourceNetworkName");
   ptr_GetClusterResourceState = (__vartype(ptr_GetClusterResourceState))GetProcAddress(hModule, "GetClusterResourceState");
   ptr_GetClusterResourceTypeKey = (__vartype(ptr_GetClusterResourceTypeKey))GetProcAddress(hModule, "GetClusterResourceTypeKey");
   ptr_GetClusterSharedVolumeNameForFile = (__vartype(ptr_GetClusterSharedVolumeNameForFile))GetProcAddress(hModule, "GetClusterSharedVolumeNameForFile");
   ptr_GetNodeClusterState = (__vartype(ptr_GetNodeClusterState))GetProcAddress(hModule, "GetNodeClusterState");
   ptr_IsFileOnClusterSharedVolume = (__vartype(ptr_IsFileOnClusterSharedVolume))GetProcAddress(hModule, "IsFileOnClusterSharedVolume");
   ptr_MoveClusterGroup = (__vartype(ptr_MoveClusterGroup))GetProcAddress(hModule, "MoveClusterGroup");
   ptr_OfflineClusterGroup = (__vartype(ptr_OfflineClusterGroup))GetProcAddress(hModule, "OfflineClusterGroup");
   ptr_OfflineClusterResource = (__vartype(ptr_OfflineClusterResource))GetProcAddress(hModule, "OfflineClusterResource");
   ptr_OnlineClusterGroup = (__vartype(ptr_OnlineClusterGroup))GetProcAddress(hModule, "OnlineClusterGroup");
   ptr_OnlineClusterResource = (__vartype(ptr_OnlineClusterResource))GetProcAddress(hModule, "OnlineClusterResource");
   ptr_OpenCluster = (__vartype(ptr_OpenCluster))GetProcAddress(hModule, "OpenCluster");
   ptr_OpenClusterEx = (__vartype(ptr_OpenClusterEx))GetProcAddress(hModule, "OpenClusterEx");
   ptr_OpenClusterGroup = (__vartype(ptr_OpenClusterGroup))GetProcAddress(hModule, "OpenClusterGroup");
   ptr_OpenClusterGroupEx = (__vartype(ptr_OpenClusterGroupEx))GetProcAddress(hModule, "OpenClusterGroupEx");
   ptr_OpenClusterNetInterface = (__vartype(ptr_OpenClusterNetInterface))GetProcAddress(hModule, "OpenClusterNetInterface");
   ptr_OpenClusterNetInterfaceEx = (__vartype(ptr_OpenClusterNetInterfaceEx))GetProcAddress(hModule, "OpenClusterNetInterfaceEx");
   ptr_OpenClusterNetwork = (__vartype(ptr_OpenClusterNetwork))GetProcAddress(hModule, "OpenClusterNetwork");
   ptr_OpenClusterNetworkEx = (__vartype(ptr_OpenClusterNetworkEx))GetProcAddress(hModule, "OpenClusterNetworkEx");
   ptr_OpenClusterNode = (__vartype(ptr_OpenClusterNode))GetProcAddress(hModule, "OpenClusterNode");
   ptr_OpenClusterNodeEx = (__vartype(ptr_OpenClusterNodeEx))GetProcAddress(hModule, "OpenClusterNodeEx");
   ptr_OpenClusterResource = (__vartype(ptr_OpenClusterResource))GetProcAddress(hModule, "OpenClusterResource");
   ptr_OpenClusterResourceEx = (__vartype(ptr_OpenClusterResourceEx))GetProcAddress(hModule, "OpenClusterResourceEx");
   ptr_PauseClusterNode = (__vartype(ptr_PauseClusterNode))GetProcAddress(hModule, "PauseClusterNode");
   ptr_RegisterClusterNotify = (__vartype(ptr_RegisterClusterNotify))GetProcAddress(hModule, "RegisterClusterNotify");
   ptr_RemoveClusterResourceDependency = (__vartype(ptr_RemoveClusterResourceDependency))GetProcAddress(hModule, "RemoveClusterResourceDependency");
   ptr_RemoveClusterResourceNode = (__vartype(ptr_RemoveClusterResourceNode))GetProcAddress(hModule, "RemoveClusterResourceNode");
   ptr_RemoveResourceFromClusterSharedVolumes = (__vartype(ptr_RemoveResourceFromClusterSharedVolumes))GetProcAddress(hModule, "RemoveResourceFromClusterSharedVolumes");
   ptr_RestoreClusterDatabase = (__vartype(ptr_RestoreClusterDatabase))GetProcAddress(hModule, "RestoreClusterDatabase");
   ptr_ResumeClusterNode = (__vartype(ptr_ResumeClusterNode))GetProcAddress(hModule, "ResumeClusterNode");
   ptr_SetClusterGroupName = (__vartype(ptr_SetClusterGroupName))GetProcAddress(hModule, "SetClusterGroupName");
   ptr_SetClusterGroupNodeList = (__vartype(ptr_SetClusterGroupNodeList))GetProcAddress(hModule, "SetClusterGroupNodeList");
   ptr_SetClusterName = (__vartype(ptr_SetClusterName))GetProcAddress(hModule, "SetClusterName");
   ptr_SetClusterNetworkName = (__vartype(ptr_SetClusterNetworkName))GetProcAddress(hModule, "SetClusterNetworkName");
   ptr_SetClusterNetworkPriorityOrder = (__vartype(ptr_SetClusterNetworkPriorityOrder))GetProcAddress(hModule, "SetClusterNetworkPriorityOrder");
   ptr_SetClusterQuorumResource = (__vartype(ptr_SetClusterQuorumResource))GetProcAddress(hModule, "SetClusterQuorumResource");
   ptr_SetClusterResourceDependencyExpression = (__vartype(ptr_SetClusterResourceDependencyExpression))GetProcAddress(hModule, "SetClusterResourceDependencyExpression");
   ptr_SetClusterResourceName = (__vartype(ptr_SetClusterResourceName))GetProcAddress(hModule, "SetClusterResourceName");
   ptr_SetClusterServiceAccountPassword = (__vartype(ptr_SetClusterServiceAccountPassword))GetProcAddress(hModule, "SetClusterServiceAccountPassword");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

