#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_FXSAPIFree;
void *ptr_FXSAPIFree = NULL;
extern void *ptr_FXSAPIInitialize;
void *ptr_FXSAPIInitialize = NULL;
extern void *ptr_FaxAbort;
void *ptr_FaxAbort = NULL;
extern void *ptr_FaxAccessCheck;
void *ptr_FaxAccessCheck = NULL;
extern void *ptr_FaxAccessCheckEx;
void *ptr_FaxAccessCheckEx = NULL;
extern void *ptr_FaxAccessCheckEx2;
void *ptr_FaxAccessCheckEx2 = NULL;
extern void *ptr_FaxAddOutboundGroupA;
void *ptr_FaxAddOutboundGroupA = NULL;
extern void *ptr_FaxAddOutboundGroupW;
void *ptr_FaxAddOutboundGroupW = NULL;
extern void *ptr_FaxAddOutboundRuleA;
void *ptr_FaxAddOutboundRuleA = NULL;
extern void *ptr_FaxAddOutboundRuleW;
void *ptr_FaxAddOutboundRuleW = NULL;
extern void *ptr_FaxAnswerCall;
void *ptr_FaxAnswerCall = NULL;
extern void *ptr_FaxCheckValidFaxFolder;
void *ptr_FaxCheckValidFaxFolder = NULL;
extern void *ptr_FaxClose;
void *ptr_FaxClose = NULL;
extern void *ptr_FaxCompleteJobParamsA;
void *ptr_FaxCompleteJobParamsA = NULL;
extern void *ptr_FaxCompleteJobParamsW;
void *ptr_FaxCompleteJobParamsW = NULL;
extern void *ptr_FaxConnectFaxServerA;
void *ptr_FaxConnectFaxServerA = NULL;
extern void *ptr_FaxConnectFaxServerW;
void *ptr_FaxConnectFaxServerW = NULL;
extern void *ptr_FaxCreateAccount;
void *ptr_FaxCreateAccount = NULL;
extern void *ptr_FaxDeleteAccount;
void *ptr_FaxDeleteAccount = NULL;
extern void *ptr_FaxEnableRoutingMethodA;
void *ptr_FaxEnableRoutingMethodA = NULL;
extern void *ptr_FaxEnableRoutingMethodW;
void *ptr_FaxEnableRoutingMethodW = NULL;
extern void *ptr_FaxEndMessagesEnum;
void *ptr_FaxEndMessagesEnum = NULL;
extern void *ptr_FaxEnumAccounts;
void *ptr_FaxEnumAccounts = NULL;
extern void *ptr_FaxEnumGlobalRoutingInfoA;
void *ptr_FaxEnumGlobalRoutingInfoA = NULL;
extern void *ptr_FaxEnumGlobalRoutingInfoW;
void *ptr_FaxEnumGlobalRoutingInfoW = NULL;
extern void *ptr_FaxEnumJobsA;
void *ptr_FaxEnumJobsA = NULL;
extern void *ptr_FaxEnumJobsEx2;
void *ptr_FaxEnumJobsEx2 = NULL;
extern void *ptr_FaxEnumJobsExA;
void *ptr_FaxEnumJobsExA = NULL;
extern void *ptr_FaxEnumJobsExW;
void *ptr_FaxEnumJobsExW = NULL;
extern void *ptr_FaxEnumJobsW;
void *ptr_FaxEnumJobsW = NULL;
extern void *ptr_FaxEnumMessagesA;
void *ptr_FaxEnumMessagesA = NULL;
extern void *ptr_FaxEnumMessagesEx;
void *ptr_FaxEnumMessagesEx = NULL;
extern void *ptr_FaxEnumMessagesW;
void *ptr_FaxEnumMessagesW = NULL;
extern void *ptr_FaxEnumOutboundGroupsA;
void *ptr_FaxEnumOutboundGroupsA = NULL;
extern void *ptr_FaxEnumOutboundGroupsW;
void *ptr_FaxEnumOutboundGroupsW = NULL;
extern void *ptr_FaxEnumOutboundRulesA;
void *ptr_FaxEnumOutboundRulesA = NULL;
extern void *ptr_FaxEnumOutboundRulesW;
void *ptr_FaxEnumOutboundRulesW = NULL;
extern void *ptr_FaxEnumPortsA;
void *ptr_FaxEnumPortsA = NULL;
extern void *ptr_FaxEnumPortsExA;
void *ptr_FaxEnumPortsExA = NULL;
extern void *ptr_FaxEnumPortsExW;
void *ptr_FaxEnumPortsExW = NULL;
extern void *ptr_FaxEnumPortsW;
void *ptr_FaxEnumPortsW = NULL;
extern void *ptr_FaxEnumRoutingExtensionsA;
void *ptr_FaxEnumRoutingExtensionsA = NULL;
extern void *ptr_FaxEnumRoutingExtensionsW;
void *ptr_FaxEnumRoutingExtensionsW = NULL;
extern void *ptr_FaxEnumRoutingMethodsA;
void *ptr_FaxEnumRoutingMethodsA = NULL;
extern void *ptr_FaxEnumRoutingMethodsW;
void *ptr_FaxEnumRoutingMethodsW = NULL;
extern void *ptr_FaxEnumerateProvidersA;
void *ptr_FaxEnumerateProvidersA = NULL;
extern void *ptr_FaxEnumerateProvidersW;
void *ptr_FaxEnumerateProvidersW = NULL;
extern void *ptr_FaxFreeBuffer;
void *ptr_FaxFreeBuffer = NULL;
extern void *ptr_FaxFreeSenderInformation;
void *ptr_FaxFreeSenderInformation = NULL;
extern void *ptr_FaxGetAccountInfo;
void *ptr_FaxGetAccountInfo = NULL;
extern void *ptr_FaxGetActivityLoggingConfigurationA;
void *ptr_FaxGetActivityLoggingConfigurationA = NULL;
extern void *ptr_FaxGetActivityLoggingConfigurationW;
void *ptr_FaxGetActivityLoggingConfigurationW = NULL;
extern void *ptr_FaxGetArchiveConfigurationA;
void *ptr_FaxGetArchiveConfigurationA = NULL;
extern void *ptr_FaxGetArchiveConfigurationW;
void *ptr_FaxGetArchiveConfigurationW = NULL;
extern void *ptr_FaxGetConfigOption;
void *ptr_FaxGetConfigOption = NULL;
extern void *ptr_FaxGetConfigWizardUsed;
void *ptr_FaxGetConfigWizardUsed = NULL;
extern void *ptr_FaxGetConfigurationA;
void *ptr_FaxGetConfigurationA = NULL;
extern void *ptr_FaxGetConfigurationW;
void *ptr_FaxGetConfigurationW = NULL;
extern void *ptr_FaxGetCountryListA;
void *ptr_FaxGetCountryListA = NULL;
extern void *ptr_FaxGetCountryListW;
void *ptr_FaxGetCountryListW = NULL;
extern void *ptr_FaxGetDeviceStatusA;
void *ptr_FaxGetDeviceStatusA = NULL;
extern void *ptr_FaxGetDeviceStatusW;
void *ptr_FaxGetDeviceStatusW = NULL;
extern void *ptr_FaxGetExtensionDataA;
void *ptr_FaxGetExtensionDataA = NULL;
extern void *ptr_FaxGetExtensionDataW;
void *ptr_FaxGetExtensionDataW = NULL;
extern void *ptr_FaxGetGeneralConfiguration;
void *ptr_FaxGetGeneralConfiguration = NULL;
extern void *ptr_FaxGetJobA;
void *ptr_FaxGetJobA = NULL;
extern void *ptr_FaxGetJobEx2;
void *ptr_FaxGetJobEx2 = NULL;
extern void *ptr_FaxGetJobExA;
void *ptr_FaxGetJobExA = NULL;
extern void *ptr_FaxGetJobExW;
void *ptr_FaxGetJobExW = NULL;
extern void *ptr_FaxGetJobW;
void *ptr_FaxGetJobW = NULL;
extern void *ptr_FaxGetLoggingCategoriesA;
void *ptr_FaxGetLoggingCategoriesA = NULL;
extern void *ptr_FaxGetLoggingCategoriesW;
void *ptr_FaxGetLoggingCategoriesW = NULL;
extern void *ptr_FaxGetMessageA;
void *ptr_FaxGetMessageA = NULL;
extern void *ptr_FaxGetMessageEx;
void *ptr_FaxGetMessageEx = NULL;
extern void *ptr_FaxGetMessageTiffA;
void *ptr_FaxGetMessageTiffA = NULL;
extern void *ptr_FaxGetMessageTiffW;
void *ptr_FaxGetMessageTiffW = NULL;
extern void *ptr_FaxGetMessageW;
void *ptr_FaxGetMessageW = NULL;
extern void *ptr_FaxGetOutboxConfiguration;
void *ptr_FaxGetOutboxConfiguration = NULL;
extern void *ptr_FaxGetPageData;
void *ptr_FaxGetPageData = NULL;
extern void *ptr_FaxGetPersonalCoverPagesOption;
void *ptr_FaxGetPersonalCoverPagesOption = NULL;
extern void *ptr_FaxGetPortA;
void *ptr_FaxGetPortA = NULL;
extern void *ptr_FaxGetPortExA;
void *ptr_FaxGetPortExA = NULL;
extern void *ptr_FaxGetPortExW;
void *ptr_FaxGetPortExW = NULL;
extern void *ptr_FaxGetPortW;
void *ptr_FaxGetPortW = NULL;
extern void *ptr_FaxGetQueueStates;
void *ptr_FaxGetQueueStates = NULL;
extern void *ptr_FaxGetReceiptsConfigurationA;
void *ptr_FaxGetReceiptsConfigurationA = NULL;
extern void *ptr_FaxGetReceiptsConfigurationW;
void *ptr_FaxGetReceiptsConfigurationW = NULL;
extern void *ptr_FaxGetReceiptsOptions;
void *ptr_FaxGetReceiptsOptions = NULL;
extern void *ptr_FaxGetRecipientInfoA;
void *ptr_FaxGetRecipientInfoA = NULL;
extern void *ptr_FaxGetRecipientInfoW;
void *ptr_FaxGetRecipientInfoW = NULL;
extern void *ptr_FaxGetRecipientsLimit;
void *ptr_FaxGetRecipientsLimit = NULL;
extern void *ptr_FaxGetReportedServerAPIVersion;
void *ptr_FaxGetReportedServerAPIVersion = NULL;
extern void *ptr_FaxGetRoutingInfoA;
void *ptr_FaxGetRoutingInfoA = NULL;
extern void *ptr_FaxGetRoutingInfoW;
void *ptr_FaxGetRoutingInfoW = NULL;
extern void *ptr_FaxGetSecurity;
void *ptr_FaxGetSecurity = NULL;
extern void *ptr_FaxGetSecurityEx;
void *ptr_FaxGetSecurityEx = NULL;
extern void *ptr_FaxGetSecurityEx2;
void *ptr_FaxGetSecurityEx2 = NULL;
extern void *ptr_FaxGetSenderInfoA;
void *ptr_FaxGetSenderInfoA = NULL;
extern void *ptr_FaxGetSenderInfoW;
void *ptr_FaxGetSenderInfoW = NULL;
extern void *ptr_FaxGetSenderInformation;
void *ptr_FaxGetSenderInformation = NULL;
extern void *ptr_FaxGetServerActivity;
void *ptr_FaxGetServerActivity = NULL;
extern void *ptr_FaxGetServerSKU;
void *ptr_FaxGetServerSKU = NULL;
extern void *ptr_FaxGetServicePrintersA;
void *ptr_FaxGetServicePrintersA = NULL;
extern void *ptr_FaxGetServicePrintersW;
void *ptr_FaxGetServicePrintersW = NULL;
extern void *ptr_FaxGetVersion;
void *ptr_FaxGetVersion = NULL;
extern void *ptr_FaxInitializeEventQueue;
void *ptr_FaxInitializeEventQueue = NULL;
extern void *ptr_FaxOpenPort;
void *ptr_FaxOpenPort = NULL;
extern void *ptr_FaxPrintCoverPageA;
void *ptr_FaxPrintCoverPageA = NULL;
extern void *ptr_FaxPrintCoverPageW;
void *ptr_FaxPrintCoverPageW = NULL;
extern void *ptr_FaxReAssignMessage;
void *ptr_FaxReAssignMessage = NULL;
extern void *ptr_FaxRefreshArchive;
void *ptr_FaxRefreshArchive = NULL;
extern void *ptr_FaxRegisterForServerEvents;
void *ptr_FaxRegisterForServerEvents = NULL;
extern void *ptr_FaxRegisterForServerEventsEx;
void *ptr_FaxRegisterForServerEventsEx = NULL;
extern void *ptr_FaxRegisterRoutingExtensionW;
void *ptr_FaxRegisterRoutingExtensionW = NULL;
extern void *ptr_FaxRegisterServiceProviderExA;
void *ptr_FaxRegisterServiceProviderExA = NULL;
extern void *ptr_FaxRegisterServiceProviderExW;
void *ptr_FaxRegisterServiceProviderExW = NULL;
extern void *ptr_FaxRelease;
void *ptr_FaxRelease = NULL;
extern void *ptr_FaxRemoveMessage;
void *ptr_FaxRemoveMessage = NULL;
extern void *ptr_FaxRemoveOutboundGroupA;
void *ptr_FaxRemoveOutboundGroupA = NULL;
extern void *ptr_FaxRemoveOutboundGroupW;
void *ptr_FaxRemoveOutboundGroupW = NULL;
extern void *ptr_FaxRemoveOutboundRule;
void *ptr_FaxRemoveOutboundRule = NULL;
extern void *ptr_FaxSendDocumentA;
void *ptr_FaxSendDocumentA = NULL;
extern void *ptr_FaxSendDocumentEx2;
void *ptr_FaxSendDocumentEx2 = NULL;
extern void *ptr_FaxSendDocumentExA;
void *ptr_FaxSendDocumentExA = NULL;
extern void *ptr_FaxSendDocumentExW;
void *ptr_FaxSendDocumentExW = NULL;
extern void *ptr_FaxSendDocumentForBroadcastA;
void *ptr_FaxSendDocumentForBroadcastA = NULL;
extern void *ptr_FaxSendDocumentForBroadcastW;
void *ptr_FaxSendDocumentForBroadcastW = NULL;
extern void *ptr_FaxSendDocumentW;
void *ptr_FaxSendDocumentW = NULL;
extern void *ptr_FaxSetActivityLoggingConfigurationA;
void *ptr_FaxSetActivityLoggingConfigurationA = NULL;
extern void *ptr_FaxSetActivityLoggingConfigurationW;
void *ptr_FaxSetActivityLoggingConfigurationW = NULL;
extern void *ptr_FaxSetArchiveConfigurationA;
void *ptr_FaxSetArchiveConfigurationA = NULL;
extern void *ptr_FaxSetArchiveConfigurationW;
void *ptr_FaxSetArchiveConfigurationW = NULL;
extern void *ptr_FaxSetConfigWizardUsed;
void *ptr_FaxSetConfigWizardUsed = NULL;
extern void *ptr_FaxSetConfigurationA;
void *ptr_FaxSetConfigurationA = NULL;
extern void *ptr_FaxSetConfigurationW;
void *ptr_FaxSetConfigurationW = NULL;
extern void *ptr_FaxSetDeviceOrderInGroupA;
void *ptr_FaxSetDeviceOrderInGroupA = NULL;
extern void *ptr_FaxSetDeviceOrderInGroupW;
void *ptr_FaxSetDeviceOrderInGroupW = NULL;
extern void *ptr_FaxSetExtensionDataA;
void *ptr_FaxSetExtensionDataA = NULL;
extern void *ptr_FaxSetExtensionDataW;
void *ptr_FaxSetExtensionDataW = NULL;
extern void *ptr_FaxSetGeneralConfiguration;
void *ptr_FaxSetGeneralConfiguration = NULL;
extern void *ptr_FaxSetGlobalRoutingInfoA;
void *ptr_FaxSetGlobalRoutingInfoA = NULL;
extern void *ptr_FaxSetGlobalRoutingInfoW;
void *ptr_FaxSetGlobalRoutingInfoW = NULL;
extern void *ptr_FaxSetJobA;
void *ptr_FaxSetJobA = NULL;
extern void *ptr_FaxSetJobW;
void *ptr_FaxSetJobW = NULL;
extern void *ptr_FaxSetLoggingCategoriesA;
void *ptr_FaxSetLoggingCategoriesA = NULL;
extern void *ptr_FaxSetLoggingCategoriesW;
void *ptr_FaxSetLoggingCategoriesW = NULL;
extern void *ptr_FaxSetMessage;
void *ptr_FaxSetMessage = NULL;
extern void *ptr_FaxSetOutboundGroupA;
void *ptr_FaxSetOutboundGroupA = NULL;
extern void *ptr_FaxSetOutboundGroupW;
void *ptr_FaxSetOutboundGroupW = NULL;
extern void *ptr_FaxSetOutboundRuleA;
void *ptr_FaxSetOutboundRuleA = NULL;
extern void *ptr_FaxSetOutboundRuleW;
void *ptr_FaxSetOutboundRuleW = NULL;
extern void *ptr_FaxSetOutboxConfiguration;
void *ptr_FaxSetOutboxConfiguration = NULL;
extern void *ptr_FaxSetPortA;
void *ptr_FaxSetPortA = NULL;
extern void *ptr_FaxSetPortExA;
void *ptr_FaxSetPortExA = NULL;
extern void *ptr_FaxSetPortExW;
void *ptr_FaxSetPortExW = NULL;
extern void *ptr_FaxSetPortW;
void *ptr_FaxSetPortW = NULL;
extern void *ptr_FaxSetQueue;
void *ptr_FaxSetQueue = NULL;
extern void *ptr_FaxSetReceiptsConfigurationA;
void *ptr_FaxSetReceiptsConfigurationA = NULL;
extern void *ptr_FaxSetReceiptsConfigurationW;
void *ptr_FaxSetReceiptsConfigurationW = NULL;
extern void *ptr_FaxSetRoutingInfoA;
void *ptr_FaxSetRoutingInfoA = NULL;
extern void *ptr_FaxSetRoutingInfoW;
void *ptr_FaxSetRoutingInfoW = NULL;
extern void *ptr_FaxSetSecurity;
void *ptr_FaxSetSecurity = NULL;
extern void *ptr_FaxSetSecurityEx2;
void *ptr_FaxSetSecurityEx2 = NULL;
extern void *ptr_FaxSetSenderInformation;
void *ptr_FaxSetSenderInformation = NULL;
extern void *ptr_FaxStartMessagesEnum;
void *ptr_FaxStartMessagesEnum = NULL;
extern void *ptr_FaxStartMessagesEnumEx;
void *ptr_FaxStartMessagesEnumEx = NULL;
extern void *ptr_FaxStartPrintJob2W;
void *ptr_FaxStartPrintJob2W = NULL;
extern void *ptr_FaxStartPrintJobA;
void *ptr_FaxStartPrintJobA = NULL;
extern void *ptr_FaxStartPrintJobW;
void *ptr_FaxStartPrintJobW = NULL;
extern void *ptr_FaxUnregisterForServerEvents;
void *ptr_FaxUnregisterForServerEvents = NULL;
extern void *ptr_FaxUnregisterRoutingExtensionA;
void *ptr_FaxUnregisterRoutingExtensionA = NULL;
extern void *ptr_FaxUnregisterRoutingExtensionW;
void *ptr_FaxUnregisterRoutingExtensionW = NULL;
extern void *ptr_FaxUnregisterServiceProviderExA;
void *ptr_FaxUnregisterServiceProviderExA = NULL;
extern void *ptr_FaxUnregisterServiceProviderExW;
void *ptr_FaxUnregisterServiceProviderExW = NULL;
extern void *ptr_IsDeviceVirtual;
void *ptr_IsDeviceVirtual = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\FXSAPI.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_FXSAPIFree = (__vartype(ptr_FXSAPIFree))GetProcAddress(hModule, "FXSAPIFree");
   ptr_FXSAPIInitialize = (__vartype(ptr_FXSAPIInitialize))GetProcAddress(hModule, "FXSAPIInitialize");
   ptr_FaxAbort = (__vartype(ptr_FaxAbort))GetProcAddress(hModule, "FaxAbort");
   ptr_FaxAccessCheck = (__vartype(ptr_FaxAccessCheck))GetProcAddress(hModule, "FaxAccessCheck");
   ptr_FaxAccessCheckEx = (__vartype(ptr_FaxAccessCheckEx))GetProcAddress(hModule, "FaxAccessCheckEx");
   ptr_FaxAccessCheckEx2 = (__vartype(ptr_FaxAccessCheckEx2))GetProcAddress(hModule, "FaxAccessCheckEx2");
   ptr_FaxAddOutboundGroupA = (__vartype(ptr_FaxAddOutboundGroupA))GetProcAddress(hModule, "FaxAddOutboundGroupA");
   ptr_FaxAddOutboundGroupW = (__vartype(ptr_FaxAddOutboundGroupW))GetProcAddress(hModule, "FaxAddOutboundGroupW");
   ptr_FaxAddOutboundRuleA = (__vartype(ptr_FaxAddOutboundRuleA))GetProcAddress(hModule, "FaxAddOutboundRuleA");
   ptr_FaxAddOutboundRuleW = (__vartype(ptr_FaxAddOutboundRuleW))GetProcAddress(hModule, "FaxAddOutboundRuleW");
   ptr_FaxAnswerCall = (__vartype(ptr_FaxAnswerCall))GetProcAddress(hModule, "FaxAnswerCall");
   ptr_FaxCheckValidFaxFolder = (__vartype(ptr_FaxCheckValidFaxFolder))GetProcAddress(hModule, "FaxCheckValidFaxFolder");
   ptr_FaxClose = (__vartype(ptr_FaxClose))GetProcAddress(hModule, "FaxClose");
   ptr_FaxCompleteJobParamsA = (__vartype(ptr_FaxCompleteJobParamsA))GetProcAddress(hModule, "FaxCompleteJobParamsA");
   ptr_FaxCompleteJobParamsW = (__vartype(ptr_FaxCompleteJobParamsW))GetProcAddress(hModule, "FaxCompleteJobParamsW");
   ptr_FaxConnectFaxServerA = (__vartype(ptr_FaxConnectFaxServerA))GetProcAddress(hModule, "FaxConnectFaxServerA");
   ptr_FaxConnectFaxServerW = (__vartype(ptr_FaxConnectFaxServerW))GetProcAddress(hModule, "FaxConnectFaxServerW");
   ptr_FaxCreateAccount = (__vartype(ptr_FaxCreateAccount))GetProcAddress(hModule, "FaxCreateAccount");
   ptr_FaxDeleteAccount = (__vartype(ptr_FaxDeleteAccount))GetProcAddress(hModule, "FaxDeleteAccount");
   ptr_FaxEnableRoutingMethodA = (__vartype(ptr_FaxEnableRoutingMethodA))GetProcAddress(hModule, "FaxEnableRoutingMethodA");
   ptr_FaxEnableRoutingMethodW = (__vartype(ptr_FaxEnableRoutingMethodW))GetProcAddress(hModule, "FaxEnableRoutingMethodW");
   ptr_FaxEndMessagesEnum = (__vartype(ptr_FaxEndMessagesEnum))GetProcAddress(hModule, "FaxEndMessagesEnum");
   ptr_FaxEnumAccounts = (__vartype(ptr_FaxEnumAccounts))GetProcAddress(hModule, "FaxEnumAccounts");
   ptr_FaxEnumGlobalRoutingInfoA = (__vartype(ptr_FaxEnumGlobalRoutingInfoA))GetProcAddress(hModule, "FaxEnumGlobalRoutingInfoA");
   ptr_FaxEnumGlobalRoutingInfoW = (__vartype(ptr_FaxEnumGlobalRoutingInfoW))GetProcAddress(hModule, "FaxEnumGlobalRoutingInfoW");
   ptr_FaxEnumJobsA = (__vartype(ptr_FaxEnumJobsA))GetProcAddress(hModule, "FaxEnumJobsA");
   ptr_FaxEnumJobsEx2 = (__vartype(ptr_FaxEnumJobsEx2))GetProcAddress(hModule, "FaxEnumJobsEx2");
   ptr_FaxEnumJobsExA = (__vartype(ptr_FaxEnumJobsExA))GetProcAddress(hModule, "FaxEnumJobsExA");
   ptr_FaxEnumJobsExW = (__vartype(ptr_FaxEnumJobsExW))GetProcAddress(hModule, "FaxEnumJobsExW");
   ptr_FaxEnumJobsW = (__vartype(ptr_FaxEnumJobsW))GetProcAddress(hModule, "FaxEnumJobsW");
   ptr_FaxEnumMessagesA = (__vartype(ptr_FaxEnumMessagesA))GetProcAddress(hModule, "FaxEnumMessagesA");
   ptr_FaxEnumMessagesEx = (__vartype(ptr_FaxEnumMessagesEx))GetProcAddress(hModule, "FaxEnumMessagesEx");
   ptr_FaxEnumMessagesW = (__vartype(ptr_FaxEnumMessagesW))GetProcAddress(hModule, "FaxEnumMessagesW");
   ptr_FaxEnumOutboundGroupsA = (__vartype(ptr_FaxEnumOutboundGroupsA))GetProcAddress(hModule, "FaxEnumOutboundGroupsA");
   ptr_FaxEnumOutboundGroupsW = (__vartype(ptr_FaxEnumOutboundGroupsW))GetProcAddress(hModule, "FaxEnumOutboundGroupsW");
   ptr_FaxEnumOutboundRulesA = (__vartype(ptr_FaxEnumOutboundRulesA))GetProcAddress(hModule, "FaxEnumOutboundRulesA");
   ptr_FaxEnumOutboundRulesW = (__vartype(ptr_FaxEnumOutboundRulesW))GetProcAddress(hModule, "FaxEnumOutboundRulesW");
   ptr_FaxEnumPortsA = (__vartype(ptr_FaxEnumPortsA))GetProcAddress(hModule, "FaxEnumPortsA");
   ptr_FaxEnumPortsExA = (__vartype(ptr_FaxEnumPortsExA))GetProcAddress(hModule, "FaxEnumPortsExA");
   ptr_FaxEnumPortsExW = (__vartype(ptr_FaxEnumPortsExW))GetProcAddress(hModule, "FaxEnumPortsExW");
   ptr_FaxEnumPortsW = (__vartype(ptr_FaxEnumPortsW))GetProcAddress(hModule, "FaxEnumPortsW");
   ptr_FaxEnumRoutingExtensionsA = (__vartype(ptr_FaxEnumRoutingExtensionsA))GetProcAddress(hModule, "FaxEnumRoutingExtensionsA");
   ptr_FaxEnumRoutingExtensionsW = (__vartype(ptr_FaxEnumRoutingExtensionsW))GetProcAddress(hModule, "FaxEnumRoutingExtensionsW");
   ptr_FaxEnumRoutingMethodsA = (__vartype(ptr_FaxEnumRoutingMethodsA))GetProcAddress(hModule, "FaxEnumRoutingMethodsA");
   ptr_FaxEnumRoutingMethodsW = (__vartype(ptr_FaxEnumRoutingMethodsW))GetProcAddress(hModule, "FaxEnumRoutingMethodsW");
   ptr_FaxEnumerateProvidersA = (__vartype(ptr_FaxEnumerateProvidersA))GetProcAddress(hModule, "FaxEnumerateProvidersA");
   ptr_FaxEnumerateProvidersW = (__vartype(ptr_FaxEnumerateProvidersW))GetProcAddress(hModule, "FaxEnumerateProvidersW");
   ptr_FaxFreeBuffer = (__vartype(ptr_FaxFreeBuffer))GetProcAddress(hModule, "FaxFreeBuffer");
   ptr_FaxFreeSenderInformation = (__vartype(ptr_FaxFreeSenderInformation))GetProcAddress(hModule, "FaxFreeSenderInformation");
   ptr_FaxGetAccountInfo = (__vartype(ptr_FaxGetAccountInfo))GetProcAddress(hModule, "FaxGetAccountInfo");
   ptr_FaxGetActivityLoggingConfigurationA = (__vartype(ptr_FaxGetActivityLoggingConfigurationA))GetProcAddress(hModule, "FaxGetActivityLoggingConfigurationA");
   ptr_FaxGetActivityLoggingConfigurationW = (__vartype(ptr_FaxGetActivityLoggingConfigurationW))GetProcAddress(hModule, "FaxGetActivityLoggingConfigurationW");
   ptr_FaxGetArchiveConfigurationA = (__vartype(ptr_FaxGetArchiveConfigurationA))GetProcAddress(hModule, "FaxGetArchiveConfigurationA");
   ptr_FaxGetArchiveConfigurationW = (__vartype(ptr_FaxGetArchiveConfigurationW))GetProcAddress(hModule, "FaxGetArchiveConfigurationW");
   ptr_FaxGetConfigOption = (__vartype(ptr_FaxGetConfigOption))GetProcAddress(hModule, "FaxGetConfigOption");
   ptr_FaxGetConfigWizardUsed = (__vartype(ptr_FaxGetConfigWizardUsed))GetProcAddress(hModule, "FaxGetConfigWizardUsed");
   ptr_FaxGetConfigurationA = (__vartype(ptr_FaxGetConfigurationA))GetProcAddress(hModule, "FaxGetConfigurationA");
   ptr_FaxGetConfigurationW = (__vartype(ptr_FaxGetConfigurationW))GetProcAddress(hModule, "FaxGetConfigurationW");
   ptr_FaxGetCountryListA = (__vartype(ptr_FaxGetCountryListA))GetProcAddress(hModule, "FaxGetCountryListA");
   ptr_FaxGetCountryListW = (__vartype(ptr_FaxGetCountryListW))GetProcAddress(hModule, "FaxGetCountryListW");
   ptr_FaxGetDeviceStatusA = (__vartype(ptr_FaxGetDeviceStatusA))GetProcAddress(hModule, "FaxGetDeviceStatusA");
   ptr_FaxGetDeviceStatusW = (__vartype(ptr_FaxGetDeviceStatusW))GetProcAddress(hModule, "FaxGetDeviceStatusW");
   ptr_FaxGetExtensionDataA = (__vartype(ptr_FaxGetExtensionDataA))GetProcAddress(hModule, "FaxGetExtensionDataA");
   ptr_FaxGetExtensionDataW = (__vartype(ptr_FaxGetExtensionDataW))GetProcAddress(hModule, "FaxGetExtensionDataW");
   ptr_FaxGetGeneralConfiguration = (__vartype(ptr_FaxGetGeneralConfiguration))GetProcAddress(hModule, "FaxGetGeneralConfiguration");
   ptr_FaxGetJobA = (__vartype(ptr_FaxGetJobA))GetProcAddress(hModule, "FaxGetJobA");
   ptr_FaxGetJobEx2 = (__vartype(ptr_FaxGetJobEx2))GetProcAddress(hModule, "FaxGetJobEx2");
   ptr_FaxGetJobExA = (__vartype(ptr_FaxGetJobExA))GetProcAddress(hModule, "FaxGetJobExA");
   ptr_FaxGetJobExW = (__vartype(ptr_FaxGetJobExW))GetProcAddress(hModule, "FaxGetJobExW");
   ptr_FaxGetJobW = (__vartype(ptr_FaxGetJobW))GetProcAddress(hModule, "FaxGetJobW");
   ptr_FaxGetLoggingCategoriesA = (__vartype(ptr_FaxGetLoggingCategoriesA))GetProcAddress(hModule, "FaxGetLoggingCategoriesA");
   ptr_FaxGetLoggingCategoriesW = (__vartype(ptr_FaxGetLoggingCategoriesW))GetProcAddress(hModule, "FaxGetLoggingCategoriesW");
   ptr_FaxGetMessageA = (__vartype(ptr_FaxGetMessageA))GetProcAddress(hModule, "FaxGetMessageA");
   ptr_FaxGetMessageEx = (__vartype(ptr_FaxGetMessageEx))GetProcAddress(hModule, "FaxGetMessageEx");
   ptr_FaxGetMessageTiffA = (__vartype(ptr_FaxGetMessageTiffA))GetProcAddress(hModule, "FaxGetMessageTiffA");
   ptr_FaxGetMessageTiffW = (__vartype(ptr_FaxGetMessageTiffW))GetProcAddress(hModule, "FaxGetMessageTiffW");
   ptr_FaxGetMessageW = (__vartype(ptr_FaxGetMessageW))GetProcAddress(hModule, "FaxGetMessageW");
   ptr_FaxGetOutboxConfiguration = (__vartype(ptr_FaxGetOutboxConfiguration))GetProcAddress(hModule, "FaxGetOutboxConfiguration");
   ptr_FaxGetPageData = (__vartype(ptr_FaxGetPageData))GetProcAddress(hModule, "FaxGetPageData");
   ptr_FaxGetPersonalCoverPagesOption = (__vartype(ptr_FaxGetPersonalCoverPagesOption))GetProcAddress(hModule, "FaxGetPersonalCoverPagesOption");
   ptr_FaxGetPortA = (__vartype(ptr_FaxGetPortA))GetProcAddress(hModule, "FaxGetPortA");
   ptr_FaxGetPortExA = (__vartype(ptr_FaxGetPortExA))GetProcAddress(hModule, "FaxGetPortExA");
   ptr_FaxGetPortExW = (__vartype(ptr_FaxGetPortExW))GetProcAddress(hModule, "FaxGetPortExW");
   ptr_FaxGetPortW = (__vartype(ptr_FaxGetPortW))GetProcAddress(hModule, "FaxGetPortW");
   ptr_FaxGetQueueStates = (__vartype(ptr_FaxGetQueueStates))GetProcAddress(hModule, "FaxGetQueueStates");
   ptr_FaxGetReceiptsConfigurationA = (__vartype(ptr_FaxGetReceiptsConfigurationA))GetProcAddress(hModule, "FaxGetReceiptsConfigurationA");
   ptr_FaxGetReceiptsConfigurationW = (__vartype(ptr_FaxGetReceiptsConfigurationW))GetProcAddress(hModule, "FaxGetReceiptsConfigurationW");
   ptr_FaxGetReceiptsOptions = (__vartype(ptr_FaxGetReceiptsOptions))GetProcAddress(hModule, "FaxGetReceiptsOptions");
   ptr_FaxGetRecipientInfoA = (__vartype(ptr_FaxGetRecipientInfoA))GetProcAddress(hModule, "FaxGetRecipientInfoA");
   ptr_FaxGetRecipientInfoW = (__vartype(ptr_FaxGetRecipientInfoW))GetProcAddress(hModule, "FaxGetRecipientInfoW");
   ptr_FaxGetRecipientsLimit = (__vartype(ptr_FaxGetRecipientsLimit))GetProcAddress(hModule, "FaxGetRecipientsLimit");
   ptr_FaxGetReportedServerAPIVersion = (__vartype(ptr_FaxGetReportedServerAPIVersion))GetProcAddress(hModule, "FaxGetReportedServerAPIVersion");
   ptr_FaxGetRoutingInfoA = (__vartype(ptr_FaxGetRoutingInfoA))GetProcAddress(hModule, "FaxGetRoutingInfoA");
   ptr_FaxGetRoutingInfoW = (__vartype(ptr_FaxGetRoutingInfoW))GetProcAddress(hModule, "FaxGetRoutingInfoW");
   ptr_FaxGetSecurity = (__vartype(ptr_FaxGetSecurity))GetProcAddress(hModule, "FaxGetSecurity");
   ptr_FaxGetSecurityEx = (__vartype(ptr_FaxGetSecurityEx))GetProcAddress(hModule, "FaxGetSecurityEx");
   ptr_FaxGetSecurityEx2 = (__vartype(ptr_FaxGetSecurityEx2))GetProcAddress(hModule, "FaxGetSecurityEx2");
   ptr_FaxGetSenderInfoA = (__vartype(ptr_FaxGetSenderInfoA))GetProcAddress(hModule, "FaxGetSenderInfoA");
   ptr_FaxGetSenderInfoW = (__vartype(ptr_FaxGetSenderInfoW))GetProcAddress(hModule, "FaxGetSenderInfoW");
   ptr_FaxGetSenderInformation = (__vartype(ptr_FaxGetSenderInformation))GetProcAddress(hModule, "FaxGetSenderInformation");
   ptr_FaxGetServerActivity = (__vartype(ptr_FaxGetServerActivity))GetProcAddress(hModule, "FaxGetServerActivity");
   ptr_FaxGetServerSKU = (__vartype(ptr_FaxGetServerSKU))GetProcAddress(hModule, "FaxGetServerSKU");
   ptr_FaxGetServicePrintersA = (__vartype(ptr_FaxGetServicePrintersA))GetProcAddress(hModule, "FaxGetServicePrintersA");
   ptr_FaxGetServicePrintersW = (__vartype(ptr_FaxGetServicePrintersW))GetProcAddress(hModule, "FaxGetServicePrintersW");
   ptr_FaxGetVersion = (__vartype(ptr_FaxGetVersion))GetProcAddress(hModule, "FaxGetVersion");
   ptr_FaxInitializeEventQueue = (__vartype(ptr_FaxInitializeEventQueue))GetProcAddress(hModule, "FaxInitializeEventQueue");
   ptr_FaxOpenPort = (__vartype(ptr_FaxOpenPort))GetProcAddress(hModule, "FaxOpenPort");
   ptr_FaxPrintCoverPageA = (__vartype(ptr_FaxPrintCoverPageA))GetProcAddress(hModule, "FaxPrintCoverPageA");
   ptr_FaxPrintCoverPageW = (__vartype(ptr_FaxPrintCoverPageW))GetProcAddress(hModule, "FaxPrintCoverPageW");
   ptr_FaxReAssignMessage = (__vartype(ptr_FaxReAssignMessage))GetProcAddress(hModule, "FaxReAssignMessage");
   ptr_FaxRefreshArchive = (__vartype(ptr_FaxRefreshArchive))GetProcAddress(hModule, "FaxRefreshArchive");
   ptr_FaxRegisterForServerEvents = (__vartype(ptr_FaxRegisterForServerEvents))GetProcAddress(hModule, "FaxRegisterForServerEvents");
   ptr_FaxRegisterForServerEventsEx = (__vartype(ptr_FaxRegisterForServerEventsEx))GetProcAddress(hModule, "FaxRegisterForServerEventsEx");
   ptr_FaxRegisterRoutingExtensionW = (__vartype(ptr_FaxRegisterRoutingExtensionW))GetProcAddress(hModule, "FaxRegisterRoutingExtensionW");
   ptr_FaxRegisterServiceProviderExA = (__vartype(ptr_FaxRegisterServiceProviderExA))GetProcAddress(hModule, "FaxRegisterServiceProviderExA");
   ptr_FaxRegisterServiceProviderExW = (__vartype(ptr_FaxRegisterServiceProviderExW))GetProcAddress(hModule, "FaxRegisterServiceProviderExW");
   ptr_FaxRelease = (__vartype(ptr_FaxRelease))GetProcAddress(hModule, "FaxRelease");
   ptr_FaxRemoveMessage = (__vartype(ptr_FaxRemoveMessage))GetProcAddress(hModule, "FaxRemoveMessage");
   ptr_FaxRemoveOutboundGroupA = (__vartype(ptr_FaxRemoveOutboundGroupA))GetProcAddress(hModule, "FaxRemoveOutboundGroupA");
   ptr_FaxRemoveOutboundGroupW = (__vartype(ptr_FaxRemoveOutboundGroupW))GetProcAddress(hModule, "FaxRemoveOutboundGroupW");
   ptr_FaxRemoveOutboundRule = (__vartype(ptr_FaxRemoveOutboundRule))GetProcAddress(hModule, "FaxRemoveOutboundRule");
   ptr_FaxSendDocumentA = (__vartype(ptr_FaxSendDocumentA))GetProcAddress(hModule, "FaxSendDocumentA");
   ptr_FaxSendDocumentEx2 = (__vartype(ptr_FaxSendDocumentEx2))GetProcAddress(hModule, "FaxSendDocumentEx2");
   ptr_FaxSendDocumentExA = (__vartype(ptr_FaxSendDocumentExA))GetProcAddress(hModule, "FaxSendDocumentExA");
   ptr_FaxSendDocumentExW = (__vartype(ptr_FaxSendDocumentExW))GetProcAddress(hModule, "FaxSendDocumentExW");
   ptr_FaxSendDocumentForBroadcastA = (__vartype(ptr_FaxSendDocumentForBroadcastA))GetProcAddress(hModule, "FaxSendDocumentForBroadcastA");
   ptr_FaxSendDocumentForBroadcastW = (__vartype(ptr_FaxSendDocumentForBroadcastW))GetProcAddress(hModule, "FaxSendDocumentForBroadcastW");
   ptr_FaxSendDocumentW = (__vartype(ptr_FaxSendDocumentW))GetProcAddress(hModule, "FaxSendDocumentW");
   ptr_FaxSetActivityLoggingConfigurationA = (__vartype(ptr_FaxSetActivityLoggingConfigurationA))GetProcAddress(hModule, "FaxSetActivityLoggingConfigurationA");
   ptr_FaxSetActivityLoggingConfigurationW = (__vartype(ptr_FaxSetActivityLoggingConfigurationW))GetProcAddress(hModule, "FaxSetActivityLoggingConfigurationW");
   ptr_FaxSetArchiveConfigurationA = (__vartype(ptr_FaxSetArchiveConfigurationA))GetProcAddress(hModule, "FaxSetArchiveConfigurationA");
   ptr_FaxSetArchiveConfigurationW = (__vartype(ptr_FaxSetArchiveConfigurationW))GetProcAddress(hModule, "FaxSetArchiveConfigurationW");
   ptr_FaxSetConfigWizardUsed = (__vartype(ptr_FaxSetConfigWizardUsed))GetProcAddress(hModule, "FaxSetConfigWizardUsed");
   ptr_FaxSetConfigurationA = (__vartype(ptr_FaxSetConfigurationA))GetProcAddress(hModule, "FaxSetConfigurationA");
   ptr_FaxSetConfigurationW = (__vartype(ptr_FaxSetConfigurationW))GetProcAddress(hModule, "FaxSetConfigurationW");
   ptr_FaxSetDeviceOrderInGroupA = (__vartype(ptr_FaxSetDeviceOrderInGroupA))GetProcAddress(hModule, "FaxSetDeviceOrderInGroupA");
   ptr_FaxSetDeviceOrderInGroupW = (__vartype(ptr_FaxSetDeviceOrderInGroupW))GetProcAddress(hModule, "FaxSetDeviceOrderInGroupW");
   ptr_FaxSetExtensionDataA = (__vartype(ptr_FaxSetExtensionDataA))GetProcAddress(hModule, "FaxSetExtensionDataA");
   ptr_FaxSetExtensionDataW = (__vartype(ptr_FaxSetExtensionDataW))GetProcAddress(hModule, "FaxSetExtensionDataW");
   ptr_FaxSetGeneralConfiguration = (__vartype(ptr_FaxSetGeneralConfiguration))GetProcAddress(hModule, "FaxSetGeneralConfiguration");
   ptr_FaxSetGlobalRoutingInfoA = (__vartype(ptr_FaxSetGlobalRoutingInfoA))GetProcAddress(hModule, "FaxSetGlobalRoutingInfoA");
   ptr_FaxSetGlobalRoutingInfoW = (__vartype(ptr_FaxSetGlobalRoutingInfoW))GetProcAddress(hModule, "FaxSetGlobalRoutingInfoW");
   ptr_FaxSetJobA = (__vartype(ptr_FaxSetJobA))GetProcAddress(hModule, "FaxSetJobA");
   ptr_FaxSetJobW = (__vartype(ptr_FaxSetJobW))GetProcAddress(hModule, "FaxSetJobW");
   ptr_FaxSetLoggingCategoriesA = (__vartype(ptr_FaxSetLoggingCategoriesA))GetProcAddress(hModule, "FaxSetLoggingCategoriesA");
   ptr_FaxSetLoggingCategoriesW = (__vartype(ptr_FaxSetLoggingCategoriesW))GetProcAddress(hModule, "FaxSetLoggingCategoriesW");
   ptr_FaxSetMessage = (__vartype(ptr_FaxSetMessage))GetProcAddress(hModule, "FaxSetMessage");
   ptr_FaxSetOutboundGroupA = (__vartype(ptr_FaxSetOutboundGroupA))GetProcAddress(hModule, "FaxSetOutboundGroupA");
   ptr_FaxSetOutboundGroupW = (__vartype(ptr_FaxSetOutboundGroupW))GetProcAddress(hModule, "FaxSetOutboundGroupW");
   ptr_FaxSetOutboundRuleA = (__vartype(ptr_FaxSetOutboundRuleA))GetProcAddress(hModule, "FaxSetOutboundRuleA");
   ptr_FaxSetOutboundRuleW = (__vartype(ptr_FaxSetOutboundRuleW))GetProcAddress(hModule, "FaxSetOutboundRuleW");
   ptr_FaxSetOutboxConfiguration = (__vartype(ptr_FaxSetOutboxConfiguration))GetProcAddress(hModule, "FaxSetOutboxConfiguration");
   ptr_FaxSetPortA = (__vartype(ptr_FaxSetPortA))GetProcAddress(hModule, "FaxSetPortA");
   ptr_FaxSetPortExA = (__vartype(ptr_FaxSetPortExA))GetProcAddress(hModule, "FaxSetPortExA");
   ptr_FaxSetPortExW = (__vartype(ptr_FaxSetPortExW))GetProcAddress(hModule, "FaxSetPortExW");
   ptr_FaxSetPortW = (__vartype(ptr_FaxSetPortW))GetProcAddress(hModule, "FaxSetPortW");
   ptr_FaxSetQueue = (__vartype(ptr_FaxSetQueue))GetProcAddress(hModule, "FaxSetQueue");
   ptr_FaxSetReceiptsConfigurationA = (__vartype(ptr_FaxSetReceiptsConfigurationA))GetProcAddress(hModule, "FaxSetReceiptsConfigurationA");
   ptr_FaxSetReceiptsConfigurationW = (__vartype(ptr_FaxSetReceiptsConfigurationW))GetProcAddress(hModule, "FaxSetReceiptsConfigurationW");
   ptr_FaxSetRoutingInfoA = (__vartype(ptr_FaxSetRoutingInfoA))GetProcAddress(hModule, "FaxSetRoutingInfoA");
   ptr_FaxSetRoutingInfoW = (__vartype(ptr_FaxSetRoutingInfoW))GetProcAddress(hModule, "FaxSetRoutingInfoW");
   ptr_FaxSetSecurity = (__vartype(ptr_FaxSetSecurity))GetProcAddress(hModule, "FaxSetSecurity");
   ptr_FaxSetSecurityEx2 = (__vartype(ptr_FaxSetSecurityEx2))GetProcAddress(hModule, "FaxSetSecurityEx2");
   ptr_FaxSetSenderInformation = (__vartype(ptr_FaxSetSenderInformation))GetProcAddress(hModule, "FaxSetSenderInformation");
   ptr_FaxStartMessagesEnum = (__vartype(ptr_FaxStartMessagesEnum))GetProcAddress(hModule, "FaxStartMessagesEnum");
   ptr_FaxStartMessagesEnumEx = (__vartype(ptr_FaxStartMessagesEnumEx))GetProcAddress(hModule, "FaxStartMessagesEnumEx");
   ptr_FaxStartPrintJob2W = (__vartype(ptr_FaxStartPrintJob2W))GetProcAddress(hModule, "FaxStartPrintJob2W");
   ptr_FaxStartPrintJobA = (__vartype(ptr_FaxStartPrintJobA))GetProcAddress(hModule, "FaxStartPrintJobA");
   ptr_FaxStartPrintJobW = (__vartype(ptr_FaxStartPrintJobW))GetProcAddress(hModule, "FaxStartPrintJobW");
   ptr_FaxUnregisterForServerEvents = (__vartype(ptr_FaxUnregisterForServerEvents))GetProcAddress(hModule, "FaxUnregisterForServerEvents");
   ptr_FaxUnregisterRoutingExtensionA = (__vartype(ptr_FaxUnregisterRoutingExtensionA))GetProcAddress(hModule, "FaxUnregisterRoutingExtensionA");
   ptr_FaxUnregisterRoutingExtensionW = (__vartype(ptr_FaxUnregisterRoutingExtensionW))GetProcAddress(hModule, "FaxUnregisterRoutingExtensionW");
   ptr_FaxUnregisterServiceProviderExA = (__vartype(ptr_FaxUnregisterServiceProviderExA))GetProcAddress(hModule, "FaxUnregisterServiceProviderExA");
   ptr_FaxUnregisterServiceProviderExW = (__vartype(ptr_FaxUnregisterServiceProviderExW))GetProcAddress(hModule, "FaxUnregisterServiceProviderExW");
   ptr_IsDeviceVirtual = (__vartype(ptr_IsDeviceVirtual))GetProcAddress(hModule, "IsDeviceVirtual");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

