#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_LdapGetLastError;
void *ptr_LdapGetLastError = NULL;
extern void *ptr_LdapMapErrorToWin32;
void *ptr_LdapMapErrorToWin32 = NULL;
extern void *ptr_LdapUTF8ToUnicode;
void *ptr_LdapUTF8ToUnicode = NULL;
extern void *ptr_LdapUnicodeToUTF8;
void *ptr_LdapUnicodeToUTF8 = NULL;
extern void *ptr_ber_alloc_t;
void *ptr_ber_alloc_t = NULL;
extern void *ptr_ber_bvdup;
void *ptr_ber_bvdup = NULL;
extern void *ptr_ber_bvecfree;
void *ptr_ber_bvecfree = NULL;
extern void *ptr_ber_bvfree;
void *ptr_ber_bvfree = NULL;
extern void *ptr_ber_first_element;
void *ptr_ber_first_element = NULL;
extern void *ptr_ber_flatten;
void *ptr_ber_flatten = NULL;
extern void *ptr_ber_free;
void *ptr_ber_free = NULL;
extern void *ptr_ber_init;
void *ptr_ber_init = NULL;
extern void *ptr_ber_next_element;
void *ptr_ber_next_element = NULL;
extern void *ptr_ber_peek_tag;
void *ptr_ber_peek_tag = NULL;
extern void *ptr_ber_printf;
void *ptr_ber_printf = NULL;
extern void *ptr_ber_scanf;
void *ptr_ber_scanf = NULL;
extern void *ptr_ber_skip_tag;
void *ptr_ber_skip_tag = NULL;
extern void *ptr_cldap_open;
void *ptr_cldap_open = NULL;
extern void *ptr_cldap_openA;
void *ptr_cldap_openA = NULL;
extern void *ptr_cldap_openW;
void *ptr_cldap_openW = NULL;
extern void *ptr_ldap_abandon;
void *ptr_ldap_abandon = NULL;
extern void *ptr_ldap_add;
void *ptr_ldap_add = NULL;
extern void *ptr_ldap_addA;
void *ptr_ldap_addA = NULL;
extern void *ptr_ldap_addW;
void *ptr_ldap_addW = NULL;
extern void *ptr_ldap_add_ext;
void *ptr_ldap_add_ext = NULL;
extern void *ptr_ldap_add_extA;
void *ptr_ldap_add_extA = NULL;
extern void *ptr_ldap_add_extW;
void *ptr_ldap_add_extW = NULL;
extern void *ptr_ldap_add_ext_s;
void *ptr_ldap_add_ext_s = NULL;
extern void *ptr_ldap_add_ext_sA;
void *ptr_ldap_add_ext_sA = NULL;
extern void *ptr_ldap_add_ext_sW;
void *ptr_ldap_add_ext_sW = NULL;
extern void *ptr_ldap_add_s;
void *ptr_ldap_add_s = NULL;
extern void *ptr_ldap_add_sA;
void *ptr_ldap_add_sA = NULL;
extern void *ptr_ldap_add_sW;
void *ptr_ldap_add_sW = NULL;
extern void *ptr_ldap_bind;
void *ptr_ldap_bind = NULL;
extern void *ptr_ldap_bindA;
void *ptr_ldap_bindA = NULL;
extern void *ptr_ldap_bindW;
void *ptr_ldap_bindW = NULL;
extern void *ptr_ldap_bind_s;
void *ptr_ldap_bind_s = NULL;
extern void *ptr_ldap_bind_sA;
void *ptr_ldap_bind_sA = NULL;
extern void *ptr_ldap_bind_sW;
void *ptr_ldap_bind_sW = NULL;
extern void *ptr_ldap_check_filterA;
void *ptr_ldap_check_filterA = NULL;
extern void *ptr_ldap_check_filterW;
void *ptr_ldap_check_filterW = NULL;
extern void *ptr_ldap_cleanup;
void *ptr_ldap_cleanup = NULL;
extern void *ptr_ldap_close_extended_op;
void *ptr_ldap_close_extended_op = NULL;
extern void *ptr_ldap_compare;
void *ptr_ldap_compare = NULL;
extern void *ptr_ldap_compareA;
void *ptr_ldap_compareA = NULL;
extern void *ptr_ldap_compareW;
void *ptr_ldap_compareW = NULL;
extern void *ptr_ldap_compare_ext;
void *ptr_ldap_compare_ext = NULL;
extern void *ptr_ldap_compare_extA;
void *ptr_ldap_compare_extA = NULL;
extern void *ptr_ldap_compare_extW;
void *ptr_ldap_compare_extW = NULL;
extern void *ptr_ldap_compare_ext_s;
void *ptr_ldap_compare_ext_s = NULL;
extern void *ptr_ldap_compare_ext_sA;
void *ptr_ldap_compare_ext_sA = NULL;
extern void *ptr_ldap_compare_ext_sW;
void *ptr_ldap_compare_ext_sW = NULL;
extern void *ptr_ldap_compare_s;
void *ptr_ldap_compare_s = NULL;
extern void *ptr_ldap_compare_sA;
void *ptr_ldap_compare_sA = NULL;
extern void *ptr_ldap_compare_sW;
void *ptr_ldap_compare_sW = NULL;
extern void *ptr_ldap_conn_from_msg;
void *ptr_ldap_conn_from_msg = NULL;
extern void *ptr_ldap_connect;
void *ptr_ldap_connect = NULL;
extern void *ptr_ldap_control_free;
void *ptr_ldap_control_free = NULL;
extern void *ptr_ldap_control_freeA;
void *ptr_ldap_control_freeA = NULL;
extern void *ptr_ldap_control_freeW;
void *ptr_ldap_control_freeW = NULL;
extern void *ptr_ldap_controls_free;
void *ptr_ldap_controls_free = NULL;
extern void *ptr_ldap_controls_freeA;
void *ptr_ldap_controls_freeA = NULL;
extern void *ptr_ldap_controls_freeW;
void *ptr_ldap_controls_freeW = NULL;
extern void *ptr_ldap_count_entries;
void *ptr_ldap_count_entries = NULL;
extern void *ptr_ldap_count_references;
void *ptr_ldap_count_references = NULL;
extern void *ptr_ldap_count_values;
void *ptr_ldap_count_values = NULL;
extern void *ptr_ldap_count_valuesA;
void *ptr_ldap_count_valuesA = NULL;
extern void *ptr_ldap_count_valuesW;
void *ptr_ldap_count_valuesW = NULL;
extern void *ptr_ldap_count_values_len;
void *ptr_ldap_count_values_len = NULL;
extern void *ptr_ldap_create_page_control;
void *ptr_ldap_create_page_control = NULL;
extern void *ptr_ldap_create_page_controlA;
void *ptr_ldap_create_page_controlA = NULL;
extern void *ptr_ldap_create_page_controlW;
void *ptr_ldap_create_page_controlW = NULL;
extern void *ptr_ldap_create_sort_control;
void *ptr_ldap_create_sort_control = NULL;
extern void *ptr_ldap_create_sort_controlA;
void *ptr_ldap_create_sort_controlA = NULL;
extern void *ptr_ldap_create_sort_controlW;
void *ptr_ldap_create_sort_controlW = NULL;
extern void *ptr_ldap_create_vlv_controlA;
void *ptr_ldap_create_vlv_controlA = NULL;
extern void *ptr_ldap_create_vlv_controlW;
void *ptr_ldap_create_vlv_controlW = NULL;
extern void *ptr_ldap_delete;
void *ptr_ldap_delete = NULL;
extern void *ptr_ldap_deleteA;
void *ptr_ldap_deleteA = NULL;
extern void *ptr_ldap_deleteW;
void *ptr_ldap_deleteW = NULL;
extern void *ptr_ldap_delete_ext;
void *ptr_ldap_delete_ext = NULL;
extern void *ptr_ldap_delete_extA;
void *ptr_ldap_delete_extA = NULL;
extern void *ptr_ldap_delete_extW;
void *ptr_ldap_delete_extW = NULL;
extern void *ptr_ldap_delete_ext_s;
void *ptr_ldap_delete_ext_s = NULL;
extern void *ptr_ldap_delete_ext_sA;
void *ptr_ldap_delete_ext_sA = NULL;
extern void *ptr_ldap_delete_ext_sW;
void *ptr_ldap_delete_ext_sW = NULL;
extern void *ptr_ldap_delete_s;
void *ptr_ldap_delete_s = NULL;
extern void *ptr_ldap_delete_sA;
void *ptr_ldap_delete_sA = NULL;
extern void *ptr_ldap_delete_sW;
void *ptr_ldap_delete_sW = NULL;
extern void *ptr_ldap_dn2ufn;
void *ptr_ldap_dn2ufn = NULL;
extern void *ptr_ldap_dn2ufnA;
void *ptr_ldap_dn2ufnA = NULL;
extern void *ptr_ldap_dn2ufnW;
void *ptr_ldap_dn2ufnW = NULL;
extern void *ptr_ldap_encode_sort_controlA;
void *ptr_ldap_encode_sort_controlA = NULL;
extern void *ptr_ldap_encode_sort_controlW;
void *ptr_ldap_encode_sort_controlW = NULL;
extern void *ptr_ldap_err2string;
void *ptr_ldap_err2string = NULL;
extern void *ptr_ldap_err2stringA;
void *ptr_ldap_err2stringA = NULL;
extern void *ptr_ldap_err2stringW;
void *ptr_ldap_err2stringW = NULL;
extern void *ptr_ldap_escape_filter_element;
void *ptr_ldap_escape_filter_element = NULL;
extern void *ptr_ldap_escape_filter_elementA;
void *ptr_ldap_escape_filter_elementA = NULL;
extern void *ptr_ldap_escape_filter_elementW;
void *ptr_ldap_escape_filter_elementW = NULL;
extern void *ptr_ldap_explode_dn;
void *ptr_ldap_explode_dn = NULL;
extern void *ptr_ldap_explode_dnA;
void *ptr_ldap_explode_dnA = NULL;
extern void *ptr_ldap_explode_dnW;
void *ptr_ldap_explode_dnW = NULL;
extern void *ptr_ldap_extended_operation;
void *ptr_ldap_extended_operation = NULL;
extern void *ptr_ldap_extended_operationA;
void *ptr_ldap_extended_operationA = NULL;
extern void *ptr_ldap_extended_operationW;
void *ptr_ldap_extended_operationW = NULL;
extern void *ptr_ldap_extended_operation_sA;
void *ptr_ldap_extended_operation_sA = NULL;
extern void *ptr_ldap_extended_operation_sW;
void *ptr_ldap_extended_operation_sW = NULL;
extern void *ptr_ldap_first_attribute;
void *ptr_ldap_first_attribute = NULL;
extern void *ptr_ldap_first_attributeA;
void *ptr_ldap_first_attributeA = NULL;
extern void *ptr_ldap_first_attributeW;
void *ptr_ldap_first_attributeW = NULL;
extern void *ptr_ldap_first_entry;
void *ptr_ldap_first_entry = NULL;
extern void *ptr_ldap_first_reference;
void *ptr_ldap_first_reference = NULL;
extern void *ptr_ldap_free_controls;
void *ptr_ldap_free_controls = NULL;
extern void *ptr_ldap_free_controlsA;
void *ptr_ldap_free_controlsA = NULL;
extern void *ptr_ldap_free_controlsW;
void *ptr_ldap_free_controlsW = NULL;
extern void *ptr_ldap_get_dn;
void *ptr_ldap_get_dn = NULL;
extern void *ptr_ldap_get_dnA;
void *ptr_ldap_get_dnA = NULL;
extern void *ptr_ldap_get_dnW;
void *ptr_ldap_get_dnW = NULL;
extern void *ptr_ldap_get_next_page;
void *ptr_ldap_get_next_page = NULL;
extern void *ptr_ldap_get_next_page_s;
void *ptr_ldap_get_next_page_s = NULL;
extern void *ptr_ldap_get_option;
void *ptr_ldap_get_option = NULL;
extern void *ptr_ldap_get_optionA;
void *ptr_ldap_get_optionA = NULL;
extern void *ptr_ldap_get_optionW;
void *ptr_ldap_get_optionW = NULL;
extern void *ptr_ldap_get_paged_count;
void *ptr_ldap_get_paged_count = NULL;
extern void *ptr_ldap_get_values;
void *ptr_ldap_get_values = NULL;
extern void *ptr_ldap_get_valuesA;
void *ptr_ldap_get_valuesA = NULL;
extern void *ptr_ldap_get_valuesW;
void *ptr_ldap_get_valuesW = NULL;
extern void *ptr_ldap_get_values_len;
void *ptr_ldap_get_values_len = NULL;
extern void *ptr_ldap_get_values_lenA;
void *ptr_ldap_get_values_lenA = NULL;
extern void *ptr_ldap_get_values_lenW;
void *ptr_ldap_get_values_lenW = NULL;
extern void *ptr_ldap_init;
void *ptr_ldap_init = NULL;
extern void *ptr_ldap_initA;
void *ptr_ldap_initA = NULL;
extern void *ptr_ldap_initW;
void *ptr_ldap_initW = NULL;
extern void *ptr_ldap_memfree;
void *ptr_ldap_memfree = NULL;
extern void *ptr_ldap_memfreeA;
void *ptr_ldap_memfreeA = NULL;
extern void *ptr_ldap_memfreeW;
void *ptr_ldap_memfreeW = NULL;
extern void *ptr_ldap_modify;
void *ptr_ldap_modify = NULL;
extern void *ptr_ldap_modifyA;
void *ptr_ldap_modifyA = NULL;
extern void *ptr_ldap_modifyW;
void *ptr_ldap_modifyW = NULL;
extern void *ptr_ldap_modify_ext;
void *ptr_ldap_modify_ext = NULL;
extern void *ptr_ldap_modify_extA;
void *ptr_ldap_modify_extA = NULL;
extern void *ptr_ldap_modify_extW;
void *ptr_ldap_modify_extW = NULL;
extern void *ptr_ldap_modify_ext_s;
void *ptr_ldap_modify_ext_s = NULL;
extern void *ptr_ldap_modify_ext_sA;
void *ptr_ldap_modify_ext_sA = NULL;
extern void *ptr_ldap_modify_ext_sW;
void *ptr_ldap_modify_ext_sW = NULL;
extern void *ptr_ldap_modify_s;
void *ptr_ldap_modify_s = NULL;
extern void *ptr_ldap_modify_sA;
void *ptr_ldap_modify_sA = NULL;
extern void *ptr_ldap_modify_sW;
void *ptr_ldap_modify_sW = NULL;
extern void *ptr_ldap_modrdn;
void *ptr_ldap_modrdn = NULL;
extern void *ptr_ldap_modrdn2;
void *ptr_ldap_modrdn2 = NULL;
extern void *ptr_ldap_modrdn2A;
void *ptr_ldap_modrdn2A = NULL;
extern void *ptr_ldap_modrdn2W;
void *ptr_ldap_modrdn2W = NULL;
extern void *ptr_ldap_modrdn2_s;
void *ptr_ldap_modrdn2_s = NULL;
extern void *ptr_ldap_modrdn2_sA;
void *ptr_ldap_modrdn2_sA = NULL;
extern void *ptr_ldap_modrdn2_sW;
void *ptr_ldap_modrdn2_sW = NULL;
extern void *ptr_ldap_modrdnA;
void *ptr_ldap_modrdnA = NULL;
extern void *ptr_ldap_modrdnW;
void *ptr_ldap_modrdnW = NULL;
extern void *ptr_ldap_modrdn_s;
void *ptr_ldap_modrdn_s = NULL;
extern void *ptr_ldap_modrdn_sA;
void *ptr_ldap_modrdn_sA = NULL;
extern void *ptr_ldap_modrdn_sW;
void *ptr_ldap_modrdn_sW = NULL;
extern void *ptr_ldap_msgfree;
void *ptr_ldap_msgfree = NULL;
extern void *ptr_ldap_next_attribute;
void *ptr_ldap_next_attribute = NULL;
extern void *ptr_ldap_next_attributeA;
void *ptr_ldap_next_attributeA = NULL;
extern void *ptr_ldap_next_attributeW;
void *ptr_ldap_next_attributeW = NULL;
extern void *ptr_ldap_next_entry;
void *ptr_ldap_next_entry = NULL;
extern void *ptr_ldap_next_reference;
void *ptr_ldap_next_reference = NULL;
extern void *ptr_ldap_open;
void *ptr_ldap_open = NULL;
extern void *ptr_ldap_openA;
void *ptr_ldap_openA = NULL;
extern void *ptr_ldap_openW;
void *ptr_ldap_openW = NULL;
extern void *ptr_ldap_parse_extended_resultA;
void *ptr_ldap_parse_extended_resultA = NULL;
extern void *ptr_ldap_parse_extended_resultW;
void *ptr_ldap_parse_extended_resultW = NULL;
extern void *ptr_ldap_parse_page_control;
void *ptr_ldap_parse_page_control = NULL;
extern void *ptr_ldap_parse_page_controlA;
void *ptr_ldap_parse_page_controlA = NULL;
extern void *ptr_ldap_parse_page_controlW;
void *ptr_ldap_parse_page_controlW = NULL;
extern void *ptr_ldap_parse_reference;
void *ptr_ldap_parse_reference = NULL;
extern void *ptr_ldap_parse_referenceA;
void *ptr_ldap_parse_referenceA = NULL;
extern void *ptr_ldap_parse_referenceW;
void *ptr_ldap_parse_referenceW = NULL;
extern void *ptr_ldap_parse_result;
void *ptr_ldap_parse_result = NULL;
extern void *ptr_ldap_parse_resultA;
void *ptr_ldap_parse_resultA = NULL;
extern void *ptr_ldap_parse_resultW;
void *ptr_ldap_parse_resultW = NULL;
extern void *ptr_ldap_parse_sort_control;
void *ptr_ldap_parse_sort_control = NULL;
extern void *ptr_ldap_parse_sort_controlA;
void *ptr_ldap_parse_sort_controlA = NULL;
extern void *ptr_ldap_parse_sort_controlW;
void *ptr_ldap_parse_sort_controlW = NULL;
extern void *ptr_ldap_parse_vlv_controlA;
void *ptr_ldap_parse_vlv_controlA = NULL;
extern void *ptr_ldap_parse_vlv_controlW;
void *ptr_ldap_parse_vlv_controlW = NULL;
extern void *ptr_ldap_perror;
void *ptr_ldap_perror = NULL;
extern void *ptr_ldap_rename_ext;
void *ptr_ldap_rename_ext = NULL;
extern void *ptr_ldap_rename_extA;
void *ptr_ldap_rename_extA = NULL;
extern void *ptr_ldap_rename_extW;
void *ptr_ldap_rename_extW = NULL;
extern void *ptr_ldap_rename_ext_s;
void *ptr_ldap_rename_ext_s = NULL;
extern void *ptr_ldap_rename_ext_sA;
void *ptr_ldap_rename_ext_sA = NULL;
extern void *ptr_ldap_rename_ext_sW;
void *ptr_ldap_rename_ext_sW = NULL;
extern void *ptr_ldap_result;
void *ptr_ldap_result = NULL;
extern void *ptr_ldap_result2error;
void *ptr_ldap_result2error = NULL;
extern void *ptr_ldap_sasl_bindA;
void *ptr_ldap_sasl_bindA = NULL;
extern void *ptr_ldap_sasl_bindW;
void *ptr_ldap_sasl_bindW = NULL;
extern void *ptr_ldap_sasl_bind_sA;
void *ptr_ldap_sasl_bind_sA = NULL;
extern void *ptr_ldap_sasl_bind_sW;
void *ptr_ldap_sasl_bind_sW = NULL;
extern void *ptr_ldap_search;
void *ptr_ldap_search = NULL;
extern void *ptr_ldap_searchA;
void *ptr_ldap_searchA = NULL;
extern void *ptr_ldap_searchW;
void *ptr_ldap_searchW = NULL;
extern void *ptr_ldap_search_abandon_page;
void *ptr_ldap_search_abandon_page = NULL;
extern void *ptr_ldap_search_ext;
void *ptr_ldap_search_ext = NULL;
extern void *ptr_ldap_search_extA;
void *ptr_ldap_search_extA = NULL;
extern void *ptr_ldap_search_extW;
void *ptr_ldap_search_extW = NULL;
extern void *ptr_ldap_search_ext_s;
void *ptr_ldap_search_ext_s = NULL;
extern void *ptr_ldap_search_ext_sA;
void *ptr_ldap_search_ext_sA = NULL;
extern void *ptr_ldap_search_ext_sW;
void *ptr_ldap_search_ext_sW = NULL;
extern void *ptr_ldap_search_init_page;
void *ptr_ldap_search_init_page = NULL;
extern void *ptr_ldap_search_init_pageA;
void *ptr_ldap_search_init_pageA = NULL;
extern void *ptr_ldap_search_init_pageW;
void *ptr_ldap_search_init_pageW = NULL;
extern void *ptr_ldap_search_s;
void *ptr_ldap_search_s = NULL;
extern void *ptr_ldap_search_sA;
void *ptr_ldap_search_sA = NULL;
extern void *ptr_ldap_search_sW;
void *ptr_ldap_search_sW = NULL;
extern void *ptr_ldap_search_st;
void *ptr_ldap_search_st = NULL;
extern void *ptr_ldap_search_stA;
void *ptr_ldap_search_stA = NULL;
extern void *ptr_ldap_search_stW;
void *ptr_ldap_search_stW = NULL;
extern void *ptr_ldap_set_dbg_flags;
void *ptr_ldap_set_dbg_flags = NULL;
extern void *ptr_ldap_set_dbg_routine;
void *ptr_ldap_set_dbg_routine = NULL;
extern void *ptr_ldap_set_option;
void *ptr_ldap_set_option = NULL;
extern void *ptr_ldap_set_optionA;
void *ptr_ldap_set_optionA = NULL;
extern void *ptr_ldap_set_optionW;
void *ptr_ldap_set_optionW = NULL;
extern void *ptr_ldap_simple_bind;
void *ptr_ldap_simple_bind = NULL;
extern void *ptr_ldap_simple_bindA;
void *ptr_ldap_simple_bindA = NULL;
extern void *ptr_ldap_simple_bindW;
void *ptr_ldap_simple_bindW = NULL;
extern void *ptr_ldap_simple_bind_s;
void *ptr_ldap_simple_bind_s = NULL;
extern void *ptr_ldap_simple_bind_sA;
void *ptr_ldap_simple_bind_sA = NULL;
extern void *ptr_ldap_simple_bind_sW;
void *ptr_ldap_simple_bind_sW = NULL;
extern void *ptr_ldap_sslinit;
void *ptr_ldap_sslinit = NULL;
extern void *ptr_ldap_sslinitA;
void *ptr_ldap_sslinitA = NULL;
extern void *ptr_ldap_sslinitW;
void *ptr_ldap_sslinitW = NULL;
extern void *ptr_ldap_start_tls_sA;
void *ptr_ldap_start_tls_sA = NULL;
extern void *ptr_ldap_start_tls_sW;
void *ptr_ldap_start_tls_sW = NULL;
extern void *ptr_ldap_startup;
void *ptr_ldap_startup = NULL;
extern void *ptr_ldap_stop_tls_s;
void *ptr_ldap_stop_tls_s = NULL;
extern void *ptr_ldap_ufn2dn;
void *ptr_ldap_ufn2dn = NULL;
extern void *ptr_ldap_ufn2dnA;
void *ptr_ldap_ufn2dnA = NULL;
extern void *ptr_ldap_ufn2dnW;
void *ptr_ldap_ufn2dnW = NULL;
extern void *ptr_ldap_unbind;
void *ptr_ldap_unbind = NULL;
extern void *ptr_ldap_unbind_s;
void *ptr_ldap_unbind_s = NULL;
extern void *ptr_ldap_value_free;
void *ptr_ldap_value_free = NULL;
extern void *ptr_ldap_value_freeA;
void *ptr_ldap_value_freeA = NULL;
extern void *ptr_ldap_value_freeW;
void *ptr_ldap_value_freeW = NULL;
extern void *ptr_ldap_value_free_len;
void *ptr_ldap_value_free_len = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\Wldap32.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_LdapGetLastError = (__vartype(ptr_LdapGetLastError))GetProcAddress(hModule, "LdapGetLastError");
   ptr_LdapMapErrorToWin32 = (__vartype(ptr_LdapMapErrorToWin32))GetProcAddress(hModule, "LdapMapErrorToWin32");
   ptr_LdapUTF8ToUnicode = (__vartype(ptr_LdapUTF8ToUnicode))GetProcAddress(hModule, "LdapUTF8ToUnicode");
   ptr_LdapUnicodeToUTF8 = (__vartype(ptr_LdapUnicodeToUTF8))GetProcAddress(hModule, "LdapUnicodeToUTF8");
   ptr_ber_alloc_t = (__vartype(ptr_ber_alloc_t))GetProcAddress(hModule, "ber_alloc_t");
   ptr_ber_bvdup = (__vartype(ptr_ber_bvdup))GetProcAddress(hModule, "ber_bvdup");
   ptr_ber_bvecfree = (__vartype(ptr_ber_bvecfree))GetProcAddress(hModule, "ber_bvecfree");
   ptr_ber_bvfree = (__vartype(ptr_ber_bvfree))GetProcAddress(hModule, "ber_bvfree");
   ptr_ber_first_element = (__vartype(ptr_ber_first_element))GetProcAddress(hModule, "ber_first_element");
   ptr_ber_flatten = (__vartype(ptr_ber_flatten))GetProcAddress(hModule, "ber_flatten");
   ptr_ber_free = (__vartype(ptr_ber_free))GetProcAddress(hModule, "ber_free");
   ptr_ber_init = (__vartype(ptr_ber_init))GetProcAddress(hModule, "ber_init");
   ptr_ber_next_element = (__vartype(ptr_ber_next_element))GetProcAddress(hModule, "ber_next_element");
   ptr_ber_peek_tag = (__vartype(ptr_ber_peek_tag))GetProcAddress(hModule, "ber_peek_tag");
   ptr_ber_printf = (__vartype(ptr_ber_printf))GetProcAddress(hModule, "ber_printf");
   ptr_ber_scanf = (__vartype(ptr_ber_scanf))GetProcAddress(hModule, "ber_scanf");
   ptr_ber_skip_tag = (__vartype(ptr_ber_skip_tag))GetProcAddress(hModule, "ber_skip_tag");
   ptr_cldap_open = (__vartype(ptr_cldap_open))GetProcAddress(hModule, "cldap_open");
   ptr_cldap_openA = (__vartype(ptr_cldap_openA))GetProcAddress(hModule, "cldap_openA");
   ptr_cldap_openW = (__vartype(ptr_cldap_openW))GetProcAddress(hModule, "cldap_openW");
   ptr_ldap_abandon = (__vartype(ptr_ldap_abandon))GetProcAddress(hModule, "ldap_abandon");
   ptr_ldap_add = (__vartype(ptr_ldap_add))GetProcAddress(hModule, "ldap_add");
   ptr_ldap_addA = (__vartype(ptr_ldap_addA))GetProcAddress(hModule, "ldap_addA");
   ptr_ldap_addW = (__vartype(ptr_ldap_addW))GetProcAddress(hModule, "ldap_addW");
   ptr_ldap_add_ext = (__vartype(ptr_ldap_add_ext))GetProcAddress(hModule, "ldap_add_ext");
   ptr_ldap_add_extA = (__vartype(ptr_ldap_add_extA))GetProcAddress(hModule, "ldap_add_extA");
   ptr_ldap_add_extW = (__vartype(ptr_ldap_add_extW))GetProcAddress(hModule, "ldap_add_extW");
   ptr_ldap_add_ext_s = (__vartype(ptr_ldap_add_ext_s))GetProcAddress(hModule, "ldap_add_ext_s");
   ptr_ldap_add_ext_sA = (__vartype(ptr_ldap_add_ext_sA))GetProcAddress(hModule, "ldap_add_ext_sA");
   ptr_ldap_add_ext_sW = (__vartype(ptr_ldap_add_ext_sW))GetProcAddress(hModule, "ldap_add_ext_sW");
   ptr_ldap_add_s = (__vartype(ptr_ldap_add_s))GetProcAddress(hModule, "ldap_add_s");
   ptr_ldap_add_sA = (__vartype(ptr_ldap_add_sA))GetProcAddress(hModule, "ldap_add_sA");
   ptr_ldap_add_sW = (__vartype(ptr_ldap_add_sW))GetProcAddress(hModule, "ldap_add_sW");
   ptr_ldap_bind = (__vartype(ptr_ldap_bind))GetProcAddress(hModule, "ldap_bind");
   ptr_ldap_bindA = (__vartype(ptr_ldap_bindA))GetProcAddress(hModule, "ldap_bindA");
   ptr_ldap_bindW = (__vartype(ptr_ldap_bindW))GetProcAddress(hModule, "ldap_bindW");
   ptr_ldap_bind_s = (__vartype(ptr_ldap_bind_s))GetProcAddress(hModule, "ldap_bind_s");
   ptr_ldap_bind_sA = (__vartype(ptr_ldap_bind_sA))GetProcAddress(hModule, "ldap_bind_sA");
   ptr_ldap_bind_sW = (__vartype(ptr_ldap_bind_sW))GetProcAddress(hModule, "ldap_bind_sW");
   ptr_ldap_check_filterA = (__vartype(ptr_ldap_check_filterA))GetProcAddress(hModule, "ldap_check_filterA");
   ptr_ldap_check_filterW = (__vartype(ptr_ldap_check_filterW))GetProcAddress(hModule, "ldap_check_filterW");
   ptr_ldap_cleanup = (__vartype(ptr_ldap_cleanup))GetProcAddress(hModule, "ldap_cleanup");
   ptr_ldap_close_extended_op = (__vartype(ptr_ldap_close_extended_op))GetProcAddress(hModule, "ldap_close_extended_op");
   ptr_ldap_compare = (__vartype(ptr_ldap_compare))GetProcAddress(hModule, "ldap_compare");
   ptr_ldap_compareA = (__vartype(ptr_ldap_compareA))GetProcAddress(hModule, "ldap_compareA");
   ptr_ldap_compareW = (__vartype(ptr_ldap_compareW))GetProcAddress(hModule, "ldap_compareW");
   ptr_ldap_compare_ext = (__vartype(ptr_ldap_compare_ext))GetProcAddress(hModule, "ldap_compare_ext");
   ptr_ldap_compare_extA = (__vartype(ptr_ldap_compare_extA))GetProcAddress(hModule, "ldap_compare_extA");
   ptr_ldap_compare_extW = (__vartype(ptr_ldap_compare_extW))GetProcAddress(hModule, "ldap_compare_extW");
   ptr_ldap_compare_ext_s = (__vartype(ptr_ldap_compare_ext_s))GetProcAddress(hModule, "ldap_compare_ext_s");
   ptr_ldap_compare_ext_sA = (__vartype(ptr_ldap_compare_ext_sA))GetProcAddress(hModule, "ldap_compare_ext_sA");
   ptr_ldap_compare_ext_sW = (__vartype(ptr_ldap_compare_ext_sW))GetProcAddress(hModule, "ldap_compare_ext_sW");
   ptr_ldap_compare_s = (__vartype(ptr_ldap_compare_s))GetProcAddress(hModule, "ldap_compare_s");
   ptr_ldap_compare_sA = (__vartype(ptr_ldap_compare_sA))GetProcAddress(hModule, "ldap_compare_sA");
   ptr_ldap_compare_sW = (__vartype(ptr_ldap_compare_sW))GetProcAddress(hModule, "ldap_compare_sW");
   ptr_ldap_conn_from_msg = (__vartype(ptr_ldap_conn_from_msg))GetProcAddress(hModule, "ldap_conn_from_msg");
   ptr_ldap_connect = (__vartype(ptr_ldap_connect))GetProcAddress(hModule, "ldap_connect");
   ptr_ldap_control_free = (__vartype(ptr_ldap_control_free))GetProcAddress(hModule, "ldap_control_free");
   ptr_ldap_control_freeA = (__vartype(ptr_ldap_control_freeA))GetProcAddress(hModule, "ldap_control_freeA");
   ptr_ldap_control_freeW = (__vartype(ptr_ldap_control_freeW))GetProcAddress(hModule, "ldap_control_freeW");
   ptr_ldap_controls_free = (__vartype(ptr_ldap_controls_free))GetProcAddress(hModule, "ldap_controls_free");
   ptr_ldap_controls_freeA = (__vartype(ptr_ldap_controls_freeA))GetProcAddress(hModule, "ldap_controls_freeA");
   ptr_ldap_controls_freeW = (__vartype(ptr_ldap_controls_freeW))GetProcAddress(hModule, "ldap_controls_freeW");
   ptr_ldap_count_entries = (__vartype(ptr_ldap_count_entries))GetProcAddress(hModule, "ldap_count_entries");
   ptr_ldap_count_references = (__vartype(ptr_ldap_count_references))GetProcAddress(hModule, "ldap_count_references");
   ptr_ldap_count_values = (__vartype(ptr_ldap_count_values))GetProcAddress(hModule, "ldap_count_values");
   ptr_ldap_count_valuesA = (__vartype(ptr_ldap_count_valuesA))GetProcAddress(hModule, "ldap_count_valuesA");
   ptr_ldap_count_valuesW = (__vartype(ptr_ldap_count_valuesW))GetProcAddress(hModule, "ldap_count_valuesW");
   ptr_ldap_count_values_len = (__vartype(ptr_ldap_count_values_len))GetProcAddress(hModule, "ldap_count_values_len");
   ptr_ldap_create_page_control = (__vartype(ptr_ldap_create_page_control))GetProcAddress(hModule, "ldap_create_page_control");
   ptr_ldap_create_page_controlA = (__vartype(ptr_ldap_create_page_controlA))GetProcAddress(hModule, "ldap_create_page_controlA");
   ptr_ldap_create_page_controlW = (__vartype(ptr_ldap_create_page_controlW))GetProcAddress(hModule, "ldap_create_page_controlW");
   ptr_ldap_create_sort_control = (__vartype(ptr_ldap_create_sort_control))GetProcAddress(hModule, "ldap_create_sort_control");
   ptr_ldap_create_sort_controlA = (__vartype(ptr_ldap_create_sort_controlA))GetProcAddress(hModule, "ldap_create_sort_controlA");
   ptr_ldap_create_sort_controlW = (__vartype(ptr_ldap_create_sort_controlW))GetProcAddress(hModule, "ldap_create_sort_controlW");
   ptr_ldap_create_vlv_controlA = (__vartype(ptr_ldap_create_vlv_controlA))GetProcAddress(hModule, "ldap_create_vlv_controlA");
   ptr_ldap_create_vlv_controlW = (__vartype(ptr_ldap_create_vlv_controlW))GetProcAddress(hModule, "ldap_create_vlv_controlW");
   ptr_ldap_delete = (__vartype(ptr_ldap_delete))GetProcAddress(hModule, "ldap_delete");
   ptr_ldap_deleteA = (__vartype(ptr_ldap_deleteA))GetProcAddress(hModule, "ldap_deleteA");
   ptr_ldap_deleteW = (__vartype(ptr_ldap_deleteW))GetProcAddress(hModule, "ldap_deleteW");
   ptr_ldap_delete_ext = (__vartype(ptr_ldap_delete_ext))GetProcAddress(hModule, "ldap_delete_ext");
   ptr_ldap_delete_extA = (__vartype(ptr_ldap_delete_extA))GetProcAddress(hModule, "ldap_delete_extA");
   ptr_ldap_delete_extW = (__vartype(ptr_ldap_delete_extW))GetProcAddress(hModule, "ldap_delete_extW");
   ptr_ldap_delete_ext_s = (__vartype(ptr_ldap_delete_ext_s))GetProcAddress(hModule, "ldap_delete_ext_s");
   ptr_ldap_delete_ext_sA = (__vartype(ptr_ldap_delete_ext_sA))GetProcAddress(hModule, "ldap_delete_ext_sA");
   ptr_ldap_delete_ext_sW = (__vartype(ptr_ldap_delete_ext_sW))GetProcAddress(hModule, "ldap_delete_ext_sW");
   ptr_ldap_delete_s = (__vartype(ptr_ldap_delete_s))GetProcAddress(hModule, "ldap_delete_s");
   ptr_ldap_delete_sA = (__vartype(ptr_ldap_delete_sA))GetProcAddress(hModule, "ldap_delete_sA");
   ptr_ldap_delete_sW = (__vartype(ptr_ldap_delete_sW))GetProcAddress(hModule, "ldap_delete_sW");
   ptr_ldap_dn2ufn = (__vartype(ptr_ldap_dn2ufn))GetProcAddress(hModule, "ldap_dn2ufn");
   ptr_ldap_dn2ufnA = (__vartype(ptr_ldap_dn2ufnA))GetProcAddress(hModule, "ldap_dn2ufnA");
   ptr_ldap_dn2ufnW = (__vartype(ptr_ldap_dn2ufnW))GetProcAddress(hModule, "ldap_dn2ufnW");
   ptr_ldap_encode_sort_controlA = (__vartype(ptr_ldap_encode_sort_controlA))GetProcAddress(hModule, "ldap_encode_sort_controlA");
   ptr_ldap_encode_sort_controlW = (__vartype(ptr_ldap_encode_sort_controlW))GetProcAddress(hModule, "ldap_encode_sort_controlW");
   ptr_ldap_err2string = (__vartype(ptr_ldap_err2string))GetProcAddress(hModule, "ldap_err2string");
   ptr_ldap_err2stringA = (__vartype(ptr_ldap_err2stringA))GetProcAddress(hModule, "ldap_err2stringA");
   ptr_ldap_err2stringW = (__vartype(ptr_ldap_err2stringW))GetProcAddress(hModule, "ldap_err2stringW");
   ptr_ldap_escape_filter_element = (__vartype(ptr_ldap_escape_filter_element))GetProcAddress(hModule, "ldap_escape_filter_element");
   ptr_ldap_escape_filter_elementA = (__vartype(ptr_ldap_escape_filter_elementA))GetProcAddress(hModule, "ldap_escape_filter_elementA");
   ptr_ldap_escape_filter_elementW = (__vartype(ptr_ldap_escape_filter_elementW))GetProcAddress(hModule, "ldap_escape_filter_elementW");
   ptr_ldap_explode_dn = (__vartype(ptr_ldap_explode_dn))GetProcAddress(hModule, "ldap_explode_dn");
   ptr_ldap_explode_dnA = (__vartype(ptr_ldap_explode_dnA))GetProcAddress(hModule, "ldap_explode_dnA");
   ptr_ldap_explode_dnW = (__vartype(ptr_ldap_explode_dnW))GetProcAddress(hModule, "ldap_explode_dnW");
   ptr_ldap_extended_operation = (__vartype(ptr_ldap_extended_operation))GetProcAddress(hModule, "ldap_extended_operation");
   ptr_ldap_extended_operationA = (__vartype(ptr_ldap_extended_operationA))GetProcAddress(hModule, "ldap_extended_operationA");
   ptr_ldap_extended_operationW = (__vartype(ptr_ldap_extended_operationW))GetProcAddress(hModule, "ldap_extended_operationW");
   ptr_ldap_extended_operation_sA = (__vartype(ptr_ldap_extended_operation_sA))GetProcAddress(hModule, "ldap_extended_operation_sA");
   ptr_ldap_extended_operation_sW = (__vartype(ptr_ldap_extended_operation_sW))GetProcAddress(hModule, "ldap_extended_operation_sW");
   ptr_ldap_first_attribute = (__vartype(ptr_ldap_first_attribute))GetProcAddress(hModule, "ldap_first_attribute");
   ptr_ldap_first_attributeA = (__vartype(ptr_ldap_first_attributeA))GetProcAddress(hModule, "ldap_first_attributeA");
   ptr_ldap_first_attributeW = (__vartype(ptr_ldap_first_attributeW))GetProcAddress(hModule, "ldap_first_attributeW");
   ptr_ldap_first_entry = (__vartype(ptr_ldap_first_entry))GetProcAddress(hModule, "ldap_first_entry");
   ptr_ldap_first_reference = (__vartype(ptr_ldap_first_reference))GetProcAddress(hModule, "ldap_first_reference");
   ptr_ldap_free_controls = (__vartype(ptr_ldap_free_controls))GetProcAddress(hModule, "ldap_free_controls");
   ptr_ldap_free_controlsA = (__vartype(ptr_ldap_free_controlsA))GetProcAddress(hModule, "ldap_free_controlsA");
   ptr_ldap_free_controlsW = (__vartype(ptr_ldap_free_controlsW))GetProcAddress(hModule, "ldap_free_controlsW");
   ptr_ldap_get_dn = (__vartype(ptr_ldap_get_dn))GetProcAddress(hModule, "ldap_get_dn");
   ptr_ldap_get_dnA = (__vartype(ptr_ldap_get_dnA))GetProcAddress(hModule, "ldap_get_dnA");
   ptr_ldap_get_dnW = (__vartype(ptr_ldap_get_dnW))GetProcAddress(hModule, "ldap_get_dnW");
   ptr_ldap_get_next_page = (__vartype(ptr_ldap_get_next_page))GetProcAddress(hModule, "ldap_get_next_page");
   ptr_ldap_get_next_page_s = (__vartype(ptr_ldap_get_next_page_s))GetProcAddress(hModule, "ldap_get_next_page_s");
   ptr_ldap_get_option = (__vartype(ptr_ldap_get_option))GetProcAddress(hModule, "ldap_get_option");
   ptr_ldap_get_optionA = (__vartype(ptr_ldap_get_optionA))GetProcAddress(hModule, "ldap_get_optionA");
   ptr_ldap_get_optionW = (__vartype(ptr_ldap_get_optionW))GetProcAddress(hModule, "ldap_get_optionW");
   ptr_ldap_get_paged_count = (__vartype(ptr_ldap_get_paged_count))GetProcAddress(hModule, "ldap_get_paged_count");
   ptr_ldap_get_values = (__vartype(ptr_ldap_get_values))GetProcAddress(hModule, "ldap_get_values");
   ptr_ldap_get_valuesA = (__vartype(ptr_ldap_get_valuesA))GetProcAddress(hModule, "ldap_get_valuesA");
   ptr_ldap_get_valuesW = (__vartype(ptr_ldap_get_valuesW))GetProcAddress(hModule, "ldap_get_valuesW");
   ptr_ldap_get_values_len = (__vartype(ptr_ldap_get_values_len))GetProcAddress(hModule, "ldap_get_values_len");
   ptr_ldap_get_values_lenA = (__vartype(ptr_ldap_get_values_lenA))GetProcAddress(hModule, "ldap_get_values_lenA");
   ptr_ldap_get_values_lenW = (__vartype(ptr_ldap_get_values_lenW))GetProcAddress(hModule, "ldap_get_values_lenW");
   ptr_ldap_init = (__vartype(ptr_ldap_init))GetProcAddress(hModule, "ldap_init");
   ptr_ldap_initA = (__vartype(ptr_ldap_initA))GetProcAddress(hModule, "ldap_initA");
   ptr_ldap_initW = (__vartype(ptr_ldap_initW))GetProcAddress(hModule, "ldap_initW");
   ptr_ldap_memfree = (__vartype(ptr_ldap_memfree))GetProcAddress(hModule, "ldap_memfree");
   ptr_ldap_memfreeA = (__vartype(ptr_ldap_memfreeA))GetProcAddress(hModule, "ldap_memfreeA");
   ptr_ldap_memfreeW = (__vartype(ptr_ldap_memfreeW))GetProcAddress(hModule, "ldap_memfreeW");
   ptr_ldap_modify = (__vartype(ptr_ldap_modify))GetProcAddress(hModule, "ldap_modify");
   ptr_ldap_modifyA = (__vartype(ptr_ldap_modifyA))GetProcAddress(hModule, "ldap_modifyA");
   ptr_ldap_modifyW = (__vartype(ptr_ldap_modifyW))GetProcAddress(hModule, "ldap_modifyW");
   ptr_ldap_modify_ext = (__vartype(ptr_ldap_modify_ext))GetProcAddress(hModule, "ldap_modify_ext");
   ptr_ldap_modify_extA = (__vartype(ptr_ldap_modify_extA))GetProcAddress(hModule, "ldap_modify_extA");
   ptr_ldap_modify_extW = (__vartype(ptr_ldap_modify_extW))GetProcAddress(hModule, "ldap_modify_extW");
   ptr_ldap_modify_ext_s = (__vartype(ptr_ldap_modify_ext_s))GetProcAddress(hModule, "ldap_modify_ext_s");
   ptr_ldap_modify_ext_sA = (__vartype(ptr_ldap_modify_ext_sA))GetProcAddress(hModule, "ldap_modify_ext_sA");
   ptr_ldap_modify_ext_sW = (__vartype(ptr_ldap_modify_ext_sW))GetProcAddress(hModule, "ldap_modify_ext_sW");
   ptr_ldap_modify_s = (__vartype(ptr_ldap_modify_s))GetProcAddress(hModule, "ldap_modify_s");
   ptr_ldap_modify_sA = (__vartype(ptr_ldap_modify_sA))GetProcAddress(hModule, "ldap_modify_sA");
   ptr_ldap_modify_sW = (__vartype(ptr_ldap_modify_sW))GetProcAddress(hModule, "ldap_modify_sW");
   ptr_ldap_modrdn = (__vartype(ptr_ldap_modrdn))GetProcAddress(hModule, "ldap_modrdn");
   ptr_ldap_modrdn2 = (__vartype(ptr_ldap_modrdn2))GetProcAddress(hModule, "ldap_modrdn2");
   ptr_ldap_modrdn2A = (__vartype(ptr_ldap_modrdn2A))GetProcAddress(hModule, "ldap_modrdn2A");
   ptr_ldap_modrdn2W = (__vartype(ptr_ldap_modrdn2W))GetProcAddress(hModule, "ldap_modrdn2W");
   ptr_ldap_modrdn2_s = (__vartype(ptr_ldap_modrdn2_s))GetProcAddress(hModule, "ldap_modrdn2_s");
   ptr_ldap_modrdn2_sA = (__vartype(ptr_ldap_modrdn2_sA))GetProcAddress(hModule, "ldap_modrdn2_sA");
   ptr_ldap_modrdn2_sW = (__vartype(ptr_ldap_modrdn2_sW))GetProcAddress(hModule, "ldap_modrdn2_sW");
   ptr_ldap_modrdnA = (__vartype(ptr_ldap_modrdnA))GetProcAddress(hModule, "ldap_modrdnA");
   ptr_ldap_modrdnW = (__vartype(ptr_ldap_modrdnW))GetProcAddress(hModule, "ldap_modrdnW");
   ptr_ldap_modrdn_s = (__vartype(ptr_ldap_modrdn_s))GetProcAddress(hModule, "ldap_modrdn_s");
   ptr_ldap_modrdn_sA = (__vartype(ptr_ldap_modrdn_sA))GetProcAddress(hModule, "ldap_modrdn_sA");
   ptr_ldap_modrdn_sW = (__vartype(ptr_ldap_modrdn_sW))GetProcAddress(hModule, "ldap_modrdn_sW");
   ptr_ldap_msgfree = (__vartype(ptr_ldap_msgfree))GetProcAddress(hModule, "ldap_msgfree");
   ptr_ldap_next_attribute = (__vartype(ptr_ldap_next_attribute))GetProcAddress(hModule, "ldap_next_attribute");
   ptr_ldap_next_attributeA = (__vartype(ptr_ldap_next_attributeA))GetProcAddress(hModule, "ldap_next_attributeA");
   ptr_ldap_next_attributeW = (__vartype(ptr_ldap_next_attributeW))GetProcAddress(hModule, "ldap_next_attributeW");
   ptr_ldap_next_entry = (__vartype(ptr_ldap_next_entry))GetProcAddress(hModule, "ldap_next_entry");
   ptr_ldap_next_reference = (__vartype(ptr_ldap_next_reference))GetProcAddress(hModule, "ldap_next_reference");
   ptr_ldap_open = (__vartype(ptr_ldap_open))GetProcAddress(hModule, "ldap_open");
   ptr_ldap_openA = (__vartype(ptr_ldap_openA))GetProcAddress(hModule, "ldap_openA");
   ptr_ldap_openW = (__vartype(ptr_ldap_openW))GetProcAddress(hModule, "ldap_openW");
   ptr_ldap_parse_extended_resultA = (__vartype(ptr_ldap_parse_extended_resultA))GetProcAddress(hModule, "ldap_parse_extended_resultA");
   ptr_ldap_parse_extended_resultW = (__vartype(ptr_ldap_parse_extended_resultW))GetProcAddress(hModule, "ldap_parse_extended_resultW");
   ptr_ldap_parse_page_control = (__vartype(ptr_ldap_parse_page_control))GetProcAddress(hModule, "ldap_parse_page_control");
   ptr_ldap_parse_page_controlA = (__vartype(ptr_ldap_parse_page_controlA))GetProcAddress(hModule, "ldap_parse_page_controlA");
   ptr_ldap_parse_page_controlW = (__vartype(ptr_ldap_parse_page_controlW))GetProcAddress(hModule, "ldap_parse_page_controlW");
   ptr_ldap_parse_reference = (__vartype(ptr_ldap_parse_reference))GetProcAddress(hModule, "ldap_parse_reference");
   ptr_ldap_parse_referenceA = (__vartype(ptr_ldap_parse_referenceA))GetProcAddress(hModule, "ldap_parse_referenceA");
   ptr_ldap_parse_referenceW = (__vartype(ptr_ldap_parse_referenceW))GetProcAddress(hModule, "ldap_parse_referenceW");
   ptr_ldap_parse_result = (__vartype(ptr_ldap_parse_result))GetProcAddress(hModule, "ldap_parse_result");
   ptr_ldap_parse_resultA = (__vartype(ptr_ldap_parse_resultA))GetProcAddress(hModule, "ldap_parse_resultA");
   ptr_ldap_parse_resultW = (__vartype(ptr_ldap_parse_resultW))GetProcAddress(hModule, "ldap_parse_resultW");
   ptr_ldap_parse_sort_control = (__vartype(ptr_ldap_parse_sort_control))GetProcAddress(hModule, "ldap_parse_sort_control");
   ptr_ldap_parse_sort_controlA = (__vartype(ptr_ldap_parse_sort_controlA))GetProcAddress(hModule, "ldap_parse_sort_controlA");
   ptr_ldap_parse_sort_controlW = (__vartype(ptr_ldap_parse_sort_controlW))GetProcAddress(hModule, "ldap_parse_sort_controlW");
   ptr_ldap_parse_vlv_controlA = (__vartype(ptr_ldap_parse_vlv_controlA))GetProcAddress(hModule, "ldap_parse_vlv_controlA");
   ptr_ldap_parse_vlv_controlW = (__vartype(ptr_ldap_parse_vlv_controlW))GetProcAddress(hModule, "ldap_parse_vlv_controlW");
   ptr_ldap_perror = (__vartype(ptr_ldap_perror))GetProcAddress(hModule, "ldap_perror");
   ptr_ldap_rename_ext = (__vartype(ptr_ldap_rename_ext))GetProcAddress(hModule, "ldap_rename_ext");
   ptr_ldap_rename_extA = (__vartype(ptr_ldap_rename_extA))GetProcAddress(hModule, "ldap_rename_extA");
   ptr_ldap_rename_extW = (__vartype(ptr_ldap_rename_extW))GetProcAddress(hModule, "ldap_rename_extW");
   ptr_ldap_rename_ext_s = (__vartype(ptr_ldap_rename_ext_s))GetProcAddress(hModule, "ldap_rename_ext_s");
   ptr_ldap_rename_ext_sA = (__vartype(ptr_ldap_rename_ext_sA))GetProcAddress(hModule, "ldap_rename_ext_sA");
   ptr_ldap_rename_ext_sW = (__vartype(ptr_ldap_rename_ext_sW))GetProcAddress(hModule, "ldap_rename_ext_sW");
   ptr_ldap_result = (__vartype(ptr_ldap_result))GetProcAddress(hModule, "ldap_result");
   ptr_ldap_result2error = (__vartype(ptr_ldap_result2error))GetProcAddress(hModule, "ldap_result2error");
   ptr_ldap_sasl_bindA = (__vartype(ptr_ldap_sasl_bindA))GetProcAddress(hModule, "ldap_sasl_bindA");
   ptr_ldap_sasl_bindW = (__vartype(ptr_ldap_sasl_bindW))GetProcAddress(hModule, "ldap_sasl_bindW");
   ptr_ldap_sasl_bind_sA = (__vartype(ptr_ldap_sasl_bind_sA))GetProcAddress(hModule, "ldap_sasl_bind_sA");
   ptr_ldap_sasl_bind_sW = (__vartype(ptr_ldap_sasl_bind_sW))GetProcAddress(hModule, "ldap_sasl_bind_sW");
   ptr_ldap_search = (__vartype(ptr_ldap_search))GetProcAddress(hModule, "ldap_search");
   ptr_ldap_searchA = (__vartype(ptr_ldap_searchA))GetProcAddress(hModule, "ldap_searchA");
   ptr_ldap_searchW = (__vartype(ptr_ldap_searchW))GetProcAddress(hModule, "ldap_searchW");
   ptr_ldap_search_abandon_page = (__vartype(ptr_ldap_search_abandon_page))GetProcAddress(hModule, "ldap_search_abandon_page");
   ptr_ldap_search_ext = (__vartype(ptr_ldap_search_ext))GetProcAddress(hModule, "ldap_search_ext");
   ptr_ldap_search_extA = (__vartype(ptr_ldap_search_extA))GetProcAddress(hModule, "ldap_search_extA");
   ptr_ldap_search_extW = (__vartype(ptr_ldap_search_extW))GetProcAddress(hModule, "ldap_search_extW");
   ptr_ldap_search_ext_s = (__vartype(ptr_ldap_search_ext_s))GetProcAddress(hModule, "ldap_search_ext_s");
   ptr_ldap_search_ext_sA = (__vartype(ptr_ldap_search_ext_sA))GetProcAddress(hModule, "ldap_search_ext_sA");
   ptr_ldap_search_ext_sW = (__vartype(ptr_ldap_search_ext_sW))GetProcAddress(hModule, "ldap_search_ext_sW");
   ptr_ldap_search_init_page = (__vartype(ptr_ldap_search_init_page))GetProcAddress(hModule, "ldap_search_init_page");
   ptr_ldap_search_init_pageA = (__vartype(ptr_ldap_search_init_pageA))GetProcAddress(hModule, "ldap_search_init_pageA");
   ptr_ldap_search_init_pageW = (__vartype(ptr_ldap_search_init_pageW))GetProcAddress(hModule, "ldap_search_init_pageW");
   ptr_ldap_search_s = (__vartype(ptr_ldap_search_s))GetProcAddress(hModule, "ldap_search_s");
   ptr_ldap_search_sA = (__vartype(ptr_ldap_search_sA))GetProcAddress(hModule, "ldap_search_sA");
   ptr_ldap_search_sW = (__vartype(ptr_ldap_search_sW))GetProcAddress(hModule, "ldap_search_sW");
   ptr_ldap_search_st = (__vartype(ptr_ldap_search_st))GetProcAddress(hModule, "ldap_search_st");
   ptr_ldap_search_stA = (__vartype(ptr_ldap_search_stA))GetProcAddress(hModule, "ldap_search_stA");
   ptr_ldap_search_stW = (__vartype(ptr_ldap_search_stW))GetProcAddress(hModule, "ldap_search_stW");
   ptr_ldap_set_dbg_flags = (__vartype(ptr_ldap_set_dbg_flags))GetProcAddress(hModule, "ldap_set_dbg_flags");
   ptr_ldap_set_dbg_routine = (__vartype(ptr_ldap_set_dbg_routine))GetProcAddress(hModule, "ldap_set_dbg_routine");
   ptr_ldap_set_option = (__vartype(ptr_ldap_set_option))GetProcAddress(hModule, "ldap_set_option");
   ptr_ldap_set_optionA = (__vartype(ptr_ldap_set_optionA))GetProcAddress(hModule, "ldap_set_optionA");
   ptr_ldap_set_optionW = (__vartype(ptr_ldap_set_optionW))GetProcAddress(hModule, "ldap_set_optionW");
   ptr_ldap_simple_bind = (__vartype(ptr_ldap_simple_bind))GetProcAddress(hModule, "ldap_simple_bind");
   ptr_ldap_simple_bindA = (__vartype(ptr_ldap_simple_bindA))GetProcAddress(hModule, "ldap_simple_bindA");
   ptr_ldap_simple_bindW = (__vartype(ptr_ldap_simple_bindW))GetProcAddress(hModule, "ldap_simple_bindW");
   ptr_ldap_simple_bind_s = (__vartype(ptr_ldap_simple_bind_s))GetProcAddress(hModule, "ldap_simple_bind_s");
   ptr_ldap_simple_bind_sA = (__vartype(ptr_ldap_simple_bind_sA))GetProcAddress(hModule, "ldap_simple_bind_sA");
   ptr_ldap_simple_bind_sW = (__vartype(ptr_ldap_simple_bind_sW))GetProcAddress(hModule, "ldap_simple_bind_sW");
   ptr_ldap_sslinit = (__vartype(ptr_ldap_sslinit))GetProcAddress(hModule, "ldap_sslinit");
   ptr_ldap_sslinitA = (__vartype(ptr_ldap_sslinitA))GetProcAddress(hModule, "ldap_sslinitA");
   ptr_ldap_sslinitW = (__vartype(ptr_ldap_sslinitW))GetProcAddress(hModule, "ldap_sslinitW");
   ptr_ldap_start_tls_sA = (__vartype(ptr_ldap_start_tls_sA))GetProcAddress(hModule, "ldap_start_tls_sA");
   ptr_ldap_start_tls_sW = (__vartype(ptr_ldap_start_tls_sW))GetProcAddress(hModule, "ldap_start_tls_sW");
   ptr_ldap_startup = (__vartype(ptr_ldap_startup))GetProcAddress(hModule, "ldap_startup");
   ptr_ldap_stop_tls_s = (__vartype(ptr_ldap_stop_tls_s))GetProcAddress(hModule, "ldap_stop_tls_s");
   ptr_ldap_ufn2dn = (__vartype(ptr_ldap_ufn2dn))GetProcAddress(hModule, "ldap_ufn2dn");
   ptr_ldap_ufn2dnA = (__vartype(ptr_ldap_ufn2dnA))GetProcAddress(hModule, "ldap_ufn2dnA");
   ptr_ldap_ufn2dnW = (__vartype(ptr_ldap_ufn2dnW))GetProcAddress(hModule, "ldap_ufn2dnW");
   ptr_ldap_unbind = (__vartype(ptr_ldap_unbind))GetProcAddress(hModule, "ldap_unbind");
   ptr_ldap_unbind_s = (__vartype(ptr_ldap_unbind_s))GetProcAddress(hModule, "ldap_unbind_s");
   ptr_ldap_value_free = (__vartype(ptr_ldap_value_free))GetProcAddress(hModule, "ldap_value_free");
   ptr_ldap_value_freeA = (__vartype(ptr_ldap_value_freeA))GetProcAddress(hModule, "ldap_value_freeA");
   ptr_ldap_value_freeW = (__vartype(ptr_ldap_value_freeW))GetProcAddress(hModule, "ldap_value_freeW");
   ptr_ldap_value_free_len = (__vartype(ptr_ldap_value_free_len))GetProcAddress(hModule, "ldap_value_free_len");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

