ifndef X64
.686p
.XMM
.safeseh SEH_handler
.model flat, C
option dotname
option casemap : none
endif

extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGUESTLIB_1ERROR_1SUCCESS_1get : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1CloseHandle : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuLimitMHz : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuReservationMHz : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuShares : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuStolenMs : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuUsedMs : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetElapsedMs : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetErrorText : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostCpuUsedMs : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemKernOvhdMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemMappedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysFreeMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSharedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSwappedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUnmappedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUsedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostNumCpuCores : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostProcessorSpeed : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemActiveMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemBalloonedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemLimitMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemMappedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemOverheadMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemReservationMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedSavedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemShares : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSwappedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemTargetSizeMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemUsedMB : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetResourcePoolPath : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetSessionId : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1OpenHandle : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatFree : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatGet : PTR;
extern ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1UpdateInfo : PTR;


.code

align 16
SEH_handler   proc
; handler
ret
SEH_handler   endp

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGUESTLIB_1ERROR_1SUCCESS_1get PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGUESTLIB_1ERROR_1SUCCESS_1get
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGUESTLIB_1ERROR_1SUCCESS_1get ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1CloseHandle PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1CloseHandle
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1CloseHandle ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuLimitMHz PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuLimitMHz
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuLimitMHz ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuReservationMHz PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuReservationMHz
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuReservationMHz ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuShares PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuShares
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuShares ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuStolenMs PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuStolenMs
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuStolenMs ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuUsedMs PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuUsedMs
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuUsedMs ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetElapsedMs PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetElapsedMs
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetElapsedMs ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetErrorText PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetErrorText
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetErrorText ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostCpuUsedMs PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostCpuUsedMs
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostCpuUsedMs ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemKernOvhdMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemKernOvhdMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemKernOvhdMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemMappedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemMappedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemMappedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysFreeMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysFreeMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysFreeMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSharedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSharedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSharedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSwappedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSwappedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSwappedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUnmappedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUnmappedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUnmappedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUsedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUsedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUsedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostNumCpuCores PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostNumCpuCores
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostNumCpuCores ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostProcessorSpeed PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostProcessorSpeed
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostProcessorSpeed ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemActiveMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemActiveMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemActiveMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemBalloonedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemBalloonedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemBalloonedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemLimitMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemLimitMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemLimitMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemMappedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemMappedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemMappedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemOverheadMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemOverheadMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemOverheadMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemReservationMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemReservationMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemReservationMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedSavedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedSavedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedSavedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemShares PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemShares
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemShares ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSwappedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSwappedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSwappedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemTargetSizeMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemTargetSizeMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemTargetSizeMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemUsedMB PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemUsedMB
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemUsedMB ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetResourcePoolPath PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetResourcePoolPath
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetResourcePoolPath ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetSessionId PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetSessionId
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetSessionId ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1OpenHandle PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1OpenHandle
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1OpenHandle ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatFree PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatFree
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatFree ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatGet PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatGet
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatGet ENDP

Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1UpdateInfo PROC
jmp ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1UpdateInfo
Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1UpdateInfo ENDP

end
