#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGUESTLIB_1ERROR_1SUCCESS_1get;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGUESTLIB_1ERROR_1SUCCESS_1get = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1CloseHandle;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1CloseHandle = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuLimitMHz;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuLimitMHz = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuReservationMHz;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuReservationMHz = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuShares;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuShares = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuStolenMs;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuStolenMs = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuUsedMs;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuUsedMs = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetElapsedMs;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetElapsedMs = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetErrorText;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetErrorText = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostCpuUsedMs;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostCpuUsedMs = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemKernOvhdMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemKernOvhdMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemMappedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemMappedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysFreeMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysFreeMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSharedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSharedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSwappedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSwappedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUnmappedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUnmappedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUsedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUsedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostNumCpuCores;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostNumCpuCores = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostProcessorSpeed;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostProcessorSpeed = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemActiveMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemActiveMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemBalloonedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemBalloonedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemLimitMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemLimitMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemMappedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemMappedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemOverheadMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemOverheadMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemReservationMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemReservationMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedSavedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedSavedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemShares;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemShares = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSwappedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSwappedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemTargetSizeMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemTargetSizeMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemUsedMB;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemUsedMB = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetResourcePoolPath;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetResourcePoolPath = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetSessionId;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetSessionId = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1OpenHandle;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1OpenHandle = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatFree;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatFree = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatGet;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatGet = NULL;
extern void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1UpdateInfo;
void *ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1UpdateInfo = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\vmGuestLibJava.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGUESTLIB_1ERROR_1SUCCESS_1get = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGUESTLIB_1ERROR_1SUCCESS_1get))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGUESTLIB_1ERROR_1SUCCESS_1get");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1CloseHandle = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1CloseHandle))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1CloseHandle");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuLimitMHz = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuLimitMHz))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuLimitMHz");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuReservationMHz = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuReservationMHz))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuReservationMHz");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuShares = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuShares))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuShares");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuStolenMs = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuStolenMs))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuStolenMs");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuUsedMs = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuUsedMs))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetCpuUsedMs");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetElapsedMs = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetElapsedMs))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetElapsedMs");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetErrorText = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetErrorText))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetErrorText");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostCpuUsedMs = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostCpuUsedMs))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostCpuUsedMs");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemKernOvhdMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemKernOvhdMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemKernOvhdMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemMappedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemMappedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemMappedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysFreeMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysFreeMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysFreeMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemPhysMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSharedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSharedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSharedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSwappedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSwappedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemSwappedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUnmappedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUnmappedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUnmappedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUsedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUsedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostMemUsedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostNumCpuCores = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostNumCpuCores))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostNumCpuCores");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostProcessorSpeed = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostProcessorSpeed))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetHostProcessorSpeed");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemActiveMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemActiveMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemActiveMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemBalloonedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemBalloonedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemBalloonedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemLimitMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemLimitMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemLimitMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemMappedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemMappedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemMappedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemOverheadMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemOverheadMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemOverheadMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemReservationMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemReservationMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemReservationMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedSavedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedSavedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSharedSavedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemShares = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemShares))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemShares");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSwappedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSwappedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemSwappedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemTargetSizeMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemTargetSizeMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemTargetSizeMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemUsedMB = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemUsedMB))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetMemUsedMB");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetResourcePoolPath = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetResourcePoolPath))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetResourcePoolPath");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetSessionId = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetSessionId))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1GetSessionId");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1OpenHandle = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1OpenHandle))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1OpenHandle");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatFree = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatFree))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatFree");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatGet = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatGet))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1StatGet");
   ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1UpdateInfo = (__vartype(ptr_Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1UpdateInfo))GetProcAddress(hModule, "Java_com_vmware_vmguestlib_VMGuestLibInternalJNI_VMGuestLib_1UpdateInfo");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

