#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_GetTapi16CallbackMsg;
void *ptr_GetTapi16CallbackMsg = NULL;
extern void *ptr_LAddrParamsInited;
void *ptr_LAddrParamsInited = NULL;
extern void *ptr_LOpenDialAsst;
void *ptr_LOpenDialAsst = NULL;
extern void *ptr_LocWizardDlgProc;
void *ptr_LocWizardDlgProc = NULL;
extern void *ptr_MMCAddProvider;
void *ptr_MMCAddProvider = NULL;
extern void *ptr_MMCConfigProvider;
void *ptr_MMCConfigProvider = NULL;
extern void *ptr_MMCGetAvailableProviders;
void *ptr_MMCGetAvailableProviders = NULL;
extern void *ptr_MMCGetDeviceFlags;
void *ptr_MMCGetDeviceFlags = NULL;
extern void *ptr_MMCGetLineInfo;
void *ptr_MMCGetLineInfo = NULL;
extern void *ptr_MMCGetLineStatus;
void *ptr_MMCGetLineStatus = NULL;
extern void *ptr_MMCGetPhoneInfo;
void *ptr_MMCGetPhoneInfo = NULL;
extern void *ptr_MMCGetPhoneStatus;
void *ptr_MMCGetPhoneStatus = NULL;
extern void *ptr_MMCGetProviderList;
void *ptr_MMCGetProviderList = NULL;
extern void *ptr_MMCGetServerConfig;
void *ptr_MMCGetServerConfig = NULL;
extern void *ptr_MMCInitialize;
void *ptr_MMCInitialize = NULL;
extern void *ptr_MMCRemoveProvider;
void *ptr_MMCRemoveProvider = NULL;
extern void *ptr_MMCSetLineInfo;
void *ptr_MMCSetLineInfo = NULL;
extern void *ptr_MMCSetPhoneInfo;
void *ptr_MMCSetPhoneInfo = NULL;
extern void *ptr_MMCSetServerConfig;
void *ptr_MMCSetServerConfig = NULL;
extern void *ptr_MMCShutdown;
void *ptr_MMCShutdown = NULL;
extern void *ptr_NonAsyncEventThread;
void *ptr_NonAsyncEventThread = NULL;
extern void *ptr_TAPIWndProc;
void *ptr_TAPIWndProc = NULL;
extern void *ptr_TUISPIDLLCallback;
void *ptr_TUISPIDLLCallback = NULL;
extern void *ptr_internalConfig;
void *ptr_internalConfig = NULL;
extern void *ptr_internalCreateDefLocation;
void *ptr_internalCreateDefLocation = NULL;
extern void *ptr_internalNewLocationW;
void *ptr_internalNewLocationW = NULL;
extern void *ptr_internalPerformance;
void *ptr_internalPerformance = NULL;
extern void *ptr_internalRemoveLocation;
void *ptr_internalRemoveLocation = NULL;
extern void *ptr_internalRenameLocationW;
void *ptr_internalRenameLocationW = NULL;
extern void *ptr_lineAccept;
void *ptr_lineAccept = NULL;
extern void *ptr_lineAddProvider;
void *ptr_lineAddProvider = NULL;
extern void *ptr_lineAddProviderA;
void *ptr_lineAddProviderA = NULL;
extern void *ptr_lineAddProviderW;
void *ptr_lineAddProviderW = NULL;
extern void *ptr_lineAddToConference;
void *ptr_lineAddToConference = NULL;
extern void *ptr_lineAgentSpecific;
void *ptr_lineAgentSpecific = NULL;
extern void *ptr_lineAnswer;
void *ptr_lineAnswer = NULL;
extern void *ptr_lineBlindTransfer;
void *ptr_lineBlindTransfer = NULL;
extern void *ptr_lineBlindTransferA;
void *ptr_lineBlindTransferA = NULL;
extern void *ptr_lineBlindTransferW;
void *ptr_lineBlindTransferW = NULL;
extern void *ptr_lineClose;
void *ptr_lineClose = NULL;
extern void *ptr_lineCompleteCall;
void *ptr_lineCompleteCall = NULL;
extern void *ptr_lineCompleteTransfer;
void *ptr_lineCompleteTransfer = NULL;
extern void *ptr_lineConfigDialog;
void *ptr_lineConfigDialog = NULL;
extern void *ptr_lineConfigDialogA;
void *ptr_lineConfigDialogA = NULL;
extern void *ptr_lineConfigDialogEdit;
void *ptr_lineConfigDialogEdit = NULL;
extern void *ptr_lineConfigDialogEditA;
void *ptr_lineConfigDialogEditA = NULL;
extern void *ptr_lineConfigDialogEditW;
void *ptr_lineConfigDialogEditW = NULL;
extern void *ptr_lineConfigDialogW;
void *ptr_lineConfigDialogW = NULL;
extern void *ptr_lineConfigProvider;
void *ptr_lineConfigProvider = NULL;
extern void *ptr_lineCreateAgentA;
void *ptr_lineCreateAgentA = NULL;
extern void *ptr_lineCreateAgentSessionA;
void *ptr_lineCreateAgentSessionA = NULL;
extern void *ptr_lineCreateAgentSessionW;
void *ptr_lineCreateAgentSessionW = NULL;
extern void *ptr_lineCreateAgentW;
void *ptr_lineCreateAgentW = NULL;
extern void *ptr_lineDeallocateCall;
void *ptr_lineDeallocateCall = NULL;
extern void *ptr_lineDevSpecific;
void *ptr_lineDevSpecific = NULL;
extern void *ptr_lineDevSpecificFeature;
void *ptr_lineDevSpecificFeature = NULL;
extern void *ptr_lineDial;
void *ptr_lineDial = NULL;
extern void *ptr_lineDialA;
void *ptr_lineDialA = NULL;
extern void *ptr_lineDialW;
void *ptr_lineDialW = NULL;
extern void *ptr_lineDrop;
void *ptr_lineDrop = NULL;
extern void *ptr_lineForward;
void *ptr_lineForward = NULL;
extern void *ptr_lineForwardA;
void *ptr_lineForwardA = NULL;
extern void *ptr_lineForwardW;
void *ptr_lineForwardW = NULL;
extern void *ptr_lineGatherDigits;
void *ptr_lineGatherDigits = NULL;
extern void *ptr_lineGatherDigitsA;
void *ptr_lineGatherDigitsA = NULL;
extern void *ptr_lineGatherDigitsW;
void *ptr_lineGatherDigitsW = NULL;
extern void *ptr_lineGenerateDigits;
void *ptr_lineGenerateDigits = NULL;
extern void *ptr_lineGenerateDigitsA;
void *ptr_lineGenerateDigitsA = NULL;
extern void *ptr_lineGenerateDigitsW;
void *ptr_lineGenerateDigitsW = NULL;
extern void *ptr_lineGenerateTone;
void *ptr_lineGenerateTone = NULL;
extern void *ptr_lineGetAddressCaps;
void *ptr_lineGetAddressCaps = NULL;
extern void *ptr_lineGetAddressCapsA;
void *ptr_lineGetAddressCapsA = NULL;
extern void *ptr_lineGetAddressCapsW;
void *ptr_lineGetAddressCapsW = NULL;
extern void *ptr_lineGetAddressID;
void *ptr_lineGetAddressID = NULL;
extern void *ptr_lineGetAddressIDA;
void *ptr_lineGetAddressIDA = NULL;
extern void *ptr_lineGetAddressIDW;
void *ptr_lineGetAddressIDW = NULL;
extern void *ptr_lineGetAddressStatus;
void *ptr_lineGetAddressStatus = NULL;
extern void *ptr_lineGetAddressStatusA;
void *ptr_lineGetAddressStatusA = NULL;
extern void *ptr_lineGetAddressStatusW;
void *ptr_lineGetAddressStatusW = NULL;
extern void *ptr_lineGetAgentActivityListA;
void *ptr_lineGetAgentActivityListA = NULL;
extern void *ptr_lineGetAgentActivityListW;
void *ptr_lineGetAgentActivityListW = NULL;
extern void *ptr_lineGetAgentCapsA;
void *ptr_lineGetAgentCapsA = NULL;
extern void *ptr_lineGetAgentCapsW;
void *ptr_lineGetAgentCapsW = NULL;
extern void *ptr_lineGetAgentGroupListA;
void *ptr_lineGetAgentGroupListA = NULL;
extern void *ptr_lineGetAgentGroupListW;
void *ptr_lineGetAgentGroupListW = NULL;
extern void *ptr_lineGetAgentInfo;
void *ptr_lineGetAgentInfo = NULL;
extern void *ptr_lineGetAgentSessionInfo;
void *ptr_lineGetAgentSessionInfo = NULL;
extern void *ptr_lineGetAgentSessionList;
void *ptr_lineGetAgentSessionList = NULL;
extern void *ptr_lineGetAgentStatusA;
void *ptr_lineGetAgentStatusA = NULL;
extern void *ptr_lineGetAgentStatusW;
void *ptr_lineGetAgentStatusW = NULL;
extern void *ptr_lineGetAppPriority;
void *ptr_lineGetAppPriority = NULL;
extern void *ptr_lineGetAppPriorityA;
void *ptr_lineGetAppPriorityA = NULL;
extern void *ptr_lineGetAppPriorityW;
void *ptr_lineGetAppPriorityW = NULL;
extern void *ptr_lineGetCallInfo;
void *ptr_lineGetCallInfo = NULL;
extern void *ptr_lineGetCallInfoA;
void *ptr_lineGetCallInfoA = NULL;
extern void *ptr_lineGetCallInfoW;
void *ptr_lineGetCallInfoW = NULL;
extern void *ptr_lineGetCallStatus;
void *ptr_lineGetCallStatus = NULL;
extern void *ptr_lineGetConfRelatedCalls;
void *ptr_lineGetConfRelatedCalls = NULL;
extern void *ptr_lineGetCountry;
void *ptr_lineGetCountry = NULL;
extern void *ptr_lineGetCountryA;
void *ptr_lineGetCountryA = NULL;
extern void *ptr_lineGetCountryW;
void *ptr_lineGetCountryW = NULL;
extern void *ptr_lineGetDevCaps;
void *ptr_lineGetDevCaps = NULL;
extern void *ptr_lineGetDevCapsA;
void *ptr_lineGetDevCapsA = NULL;
extern void *ptr_lineGetDevCapsW;
void *ptr_lineGetDevCapsW = NULL;
extern void *ptr_lineGetDevConfig;
void *ptr_lineGetDevConfig = NULL;
extern void *ptr_lineGetDevConfigA;
void *ptr_lineGetDevConfigA = NULL;
extern void *ptr_lineGetDevConfigW;
void *ptr_lineGetDevConfigW = NULL;
extern void *ptr_lineGetGroupListA;
void *ptr_lineGetGroupListA = NULL;
extern void *ptr_lineGetGroupListW;
void *ptr_lineGetGroupListW = NULL;
extern void *ptr_lineGetID;
void *ptr_lineGetID = NULL;
extern void *ptr_lineGetIDA;
void *ptr_lineGetIDA = NULL;
extern void *ptr_lineGetIDW;
void *ptr_lineGetIDW = NULL;
extern void *ptr_lineGetIcon;
void *ptr_lineGetIcon = NULL;
extern void *ptr_lineGetIconA;
void *ptr_lineGetIconA = NULL;
extern void *ptr_lineGetIconW;
void *ptr_lineGetIconW = NULL;
extern void *ptr_lineGetLineDevStatus;
void *ptr_lineGetLineDevStatus = NULL;
extern void *ptr_lineGetLineDevStatusA;
void *ptr_lineGetLineDevStatusA = NULL;
extern void *ptr_lineGetLineDevStatusW;
void *ptr_lineGetLineDevStatusW = NULL;
extern void *ptr_lineGetMessage;
void *ptr_lineGetMessage = NULL;
extern void *ptr_lineGetNewCalls;
void *ptr_lineGetNewCalls = NULL;
extern void *ptr_lineGetNumRings;
void *ptr_lineGetNumRings = NULL;
extern void *ptr_lineGetProviderList;
void *ptr_lineGetProviderList = NULL;
extern void *ptr_lineGetProviderListA;
void *ptr_lineGetProviderListA = NULL;
extern void *ptr_lineGetProviderListW;
void *ptr_lineGetProviderListW = NULL;
extern void *ptr_lineGetProxyStatus;
void *ptr_lineGetProxyStatus = NULL;
extern void *ptr_lineGetQueueInfo;
void *ptr_lineGetQueueInfo = NULL;
extern void *ptr_lineGetQueueListA;
void *ptr_lineGetQueueListA = NULL;
extern void *ptr_lineGetQueueListW;
void *ptr_lineGetQueueListW = NULL;
extern void *ptr_lineGetRequest;
void *ptr_lineGetRequest = NULL;
extern void *ptr_lineGetRequestA;
void *ptr_lineGetRequestA = NULL;
extern void *ptr_lineGetRequestW;
void *ptr_lineGetRequestW = NULL;
extern void *ptr_lineGetStatusMessages;
void *ptr_lineGetStatusMessages = NULL;
extern void *ptr_lineGetTranslateCaps;
void *ptr_lineGetTranslateCaps = NULL;
extern void *ptr_lineGetTranslateCapsA;
void *ptr_lineGetTranslateCapsA = NULL;
extern void *ptr_lineGetTranslateCapsW;
void *ptr_lineGetTranslateCapsW = NULL;
extern void *ptr_lineHandoff;
void *ptr_lineHandoff = NULL;
extern void *ptr_lineHandoffA;
void *ptr_lineHandoffA = NULL;
extern void *ptr_lineHandoffW;
void *ptr_lineHandoffW = NULL;
extern void *ptr_lineHold;
void *ptr_lineHold = NULL;
extern void *ptr_lineInitialize;
void *ptr_lineInitialize = NULL;
extern void *ptr_lineInitializeExA;
void *ptr_lineInitializeExA = NULL;
extern void *ptr_lineInitializeExW;
void *ptr_lineInitializeExW = NULL;
extern void *ptr_lineMakeCall;
void *ptr_lineMakeCall = NULL;
extern void *ptr_lineMakeCallA;
void *ptr_lineMakeCallA = NULL;
extern void *ptr_lineMakeCallW;
void *ptr_lineMakeCallW = NULL;
extern void *ptr_lineMonitorDigits;
void *ptr_lineMonitorDigits = NULL;
extern void *ptr_lineMonitorMedia;
void *ptr_lineMonitorMedia = NULL;
extern void *ptr_lineMonitorTones;
void *ptr_lineMonitorTones = NULL;
extern void *ptr_lineNegotiateAPIVersion;
void *ptr_lineNegotiateAPIVersion = NULL;
extern void *ptr_lineNegotiateExtVersion;
void *ptr_lineNegotiateExtVersion = NULL;
extern void *ptr_lineOpen;
void *ptr_lineOpen = NULL;
extern void *ptr_lineOpenA;
void *ptr_lineOpenA = NULL;
extern void *ptr_lineOpenW;
void *ptr_lineOpenW = NULL;
extern void *ptr_linePark;
void *ptr_linePark = NULL;
extern void *ptr_lineParkA;
void *ptr_lineParkA = NULL;
extern void *ptr_lineParkW;
void *ptr_lineParkW = NULL;
extern void *ptr_linePickup;
void *ptr_linePickup = NULL;
extern void *ptr_linePickupA;
void *ptr_linePickupA = NULL;
extern void *ptr_linePickupW;
void *ptr_linePickupW = NULL;
extern void *ptr_linePrepareAddToConference;
void *ptr_linePrepareAddToConference = NULL;
extern void *ptr_linePrepareAddToConferenceA;
void *ptr_linePrepareAddToConferenceA = NULL;
extern void *ptr_linePrepareAddToConferenceW;
void *ptr_linePrepareAddToConferenceW = NULL;
extern void *ptr_lineProxyMessage;
void *ptr_lineProxyMessage = NULL;
extern void *ptr_lineProxyResponse;
void *ptr_lineProxyResponse = NULL;
extern void *ptr_lineRedirect;
void *ptr_lineRedirect = NULL;
extern void *ptr_lineRedirectA;
void *ptr_lineRedirectA = NULL;
extern void *ptr_lineRedirectW;
void *ptr_lineRedirectW = NULL;
extern void *ptr_lineRegisterRequestRecipient;
void *ptr_lineRegisterRequestRecipient = NULL;
extern void *ptr_lineReleaseUserUserInfo;
void *ptr_lineReleaseUserUserInfo = NULL;
extern void *ptr_lineRemoveFromConference;
void *ptr_lineRemoveFromConference = NULL;
extern void *ptr_lineRemoveProvider;
void *ptr_lineRemoveProvider = NULL;
extern void *ptr_lineSecureCall;
void *ptr_lineSecureCall = NULL;
extern void *ptr_lineSendUserUserInfo;
void *ptr_lineSendUserUserInfo = NULL;
extern void *ptr_lineSetAgentActivity;
void *ptr_lineSetAgentActivity = NULL;
extern void *ptr_lineSetAgentGroup;
void *ptr_lineSetAgentGroup = NULL;
extern void *ptr_lineSetAgentMeasurementPeriod;
void *ptr_lineSetAgentMeasurementPeriod = NULL;
extern void *ptr_lineSetAgentSessionState;
void *ptr_lineSetAgentSessionState = NULL;
extern void *ptr_lineSetAgentState;
void *ptr_lineSetAgentState = NULL;
extern void *ptr_lineSetAgentStateEx;
void *ptr_lineSetAgentStateEx = NULL;
extern void *ptr_lineSetAppPriority;
void *ptr_lineSetAppPriority = NULL;
extern void *ptr_lineSetAppPriorityA;
void *ptr_lineSetAppPriorityA = NULL;
extern void *ptr_lineSetAppPriorityW;
void *ptr_lineSetAppPriorityW = NULL;
extern void *ptr_lineSetAppSpecific;
void *ptr_lineSetAppSpecific = NULL;
extern void *ptr_lineSetCallData;
void *ptr_lineSetCallData = NULL;
extern void *ptr_lineSetCallParams;
void *ptr_lineSetCallParams = NULL;
extern void *ptr_lineSetCallPrivilege;
void *ptr_lineSetCallPrivilege = NULL;
extern void *ptr_lineSetCallQualityOfService;
void *ptr_lineSetCallQualityOfService = NULL;
extern void *ptr_lineSetCallTreatment;
void *ptr_lineSetCallTreatment = NULL;
extern void *ptr_lineSetCurrentLocation;
void *ptr_lineSetCurrentLocation = NULL;
extern void *ptr_lineSetDevConfig;
void *ptr_lineSetDevConfig = NULL;
extern void *ptr_lineSetDevConfigA;
void *ptr_lineSetDevConfigA = NULL;
extern void *ptr_lineSetDevConfigW;
void *ptr_lineSetDevConfigW = NULL;
extern void *ptr_lineSetLineDevStatus;
void *ptr_lineSetLineDevStatus = NULL;
extern void *ptr_lineSetMediaControl;
void *ptr_lineSetMediaControl = NULL;
extern void *ptr_lineSetMediaMode;
void *ptr_lineSetMediaMode = NULL;
extern void *ptr_lineSetNumRings;
void *ptr_lineSetNumRings = NULL;
extern void *ptr_lineSetQueueMeasurementPeriod;
void *ptr_lineSetQueueMeasurementPeriod = NULL;
extern void *ptr_lineSetStatusMessages;
void *ptr_lineSetStatusMessages = NULL;
extern void *ptr_lineSetTerminal;
void *ptr_lineSetTerminal = NULL;
extern void *ptr_lineSetTollList;
void *ptr_lineSetTollList = NULL;
extern void *ptr_lineSetTollListA;
void *ptr_lineSetTollListA = NULL;
extern void *ptr_lineSetTollListW;
void *ptr_lineSetTollListW = NULL;
extern void *ptr_lineSetupConference;
void *ptr_lineSetupConference = NULL;
extern void *ptr_lineSetupConferenceA;
void *ptr_lineSetupConferenceA = NULL;
extern void *ptr_lineSetupConferenceW;
void *ptr_lineSetupConferenceW = NULL;
extern void *ptr_lineSetupTransfer;
void *ptr_lineSetupTransfer = NULL;
extern void *ptr_lineSetupTransferA;
void *ptr_lineSetupTransferA = NULL;
extern void *ptr_lineSetupTransferW;
void *ptr_lineSetupTransferW = NULL;
extern void *ptr_lineShutdown;
void *ptr_lineShutdown = NULL;
extern void *ptr_lineSwapHold;
void *ptr_lineSwapHold = NULL;
extern void *ptr_lineTranslateAddress;
void *ptr_lineTranslateAddress = NULL;
extern void *ptr_lineTranslateAddressA;
void *ptr_lineTranslateAddressA = NULL;
extern void *ptr_lineTranslateAddressW;
void *ptr_lineTranslateAddressW = NULL;
extern void *ptr_lineTranslateDialog;
void *ptr_lineTranslateDialog = NULL;
extern void *ptr_lineTranslateDialogA;
void *ptr_lineTranslateDialogA = NULL;
extern void *ptr_lineTranslateDialogW;
void *ptr_lineTranslateDialogW = NULL;
extern void *ptr_lineUncompleteCall;
void *ptr_lineUncompleteCall = NULL;
extern void *ptr_lineUnhold;
void *ptr_lineUnhold = NULL;
extern void *ptr_lineUnpark;
void *ptr_lineUnpark = NULL;
extern void *ptr_lineUnparkA;
void *ptr_lineUnparkA = NULL;
extern void *ptr_lineUnparkW;
void *ptr_lineUnparkW = NULL;
extern void *ptr_phoneClose;
void *ptr_phoneClose = NULL;
extern void *ptr_phoneConfigDialog;
void *ptr_phoneConfigDialog = NULL;
extern void *ptr_phoneConfigDialogA;
void *ptr_phoneConfigDialogA = NULL;
extern void *ptr_phoneConfigDialogW;
void *ptr_phoneConfigDialogW = NULL;
extern void *ptr_phoneDevSpecific;
void *ptr_phoneDevSpecific = NULL;
extern void *ptr_phoneGetButtonInfo;
void *ptr_phoneGetButtonInfo = NULL;
extern void *ptr_phoneGetButtonInfoA;
void *ptr_phoneGetButtonInfoA = NULL;
extern void *ptr_phoneGetButtonInfoW;
void *ptr_phoneGetButtonInfoW = NULL;
extern void *ptr_phoneGetData;
void *ptr_phoneGetData = NULL;
extern void *ptr_phoneGetDevCaps;
void *ptr_phoneGetDevCaps = NULL;
extern void *ptr_phoneGetDevCapsA;
void *ptr_phoneGetDevCapsA = NULL;
extern void *ptr_phoneGetDevCapsW;
void *ptr_phoneGetDevCapsW = NULL;
extern void *ptr_phoneGetDisplay;
void *ptr_phoneGetDisplay = NULL;
extern void *ptr_phoneGetGain;
void *ptr_phoneGetGain = NULL;
extern void *ptr_phoneGetHookSwitch;
void *ptr_phoneGetHookSwitch = NULL;
extern void *ptr_phoneGetID;
void *ptr_phoneGetID = NULL;
extern void *ptr_phoneGetIDA;
void *ptr_phoneGetIDA = NULL;
extern void *ptr_phoneGetIDW;
void *ptr_phoneGetIDW = NULL;
extern void *ptr_phoneGetIcon;
void *ptr_phoneGetIcon = NULL;
extern void *ptr_phoneGetIconA;
void *ptr_phoneGetIconA = NULL;
extern void *ptr_phoneGetIconW;
void *ptr_phoneGetIconW = NULL;
extern void *ptr_phoneGetLamp;
void *ptr_phoneGetLamp = NULL;
extern void *ptr_phoneGetMessage;
void *ptr_phoneGetMessage = NULL;
extern void *ptr_phoneGetRing;
void *ptr_phoneGetRing = NULL;
extern void *ptr_phoneGetStatus;
void *ptr_phoneGetStatus = NULL;
extern void *ptr_phoneGetStatusA;
void *ptr_phoneGetStatusA = NULL;
extern void *ptr_phoneGetStatusMessages;
void *ptr_phoneGetStatusMessages = NULL;
extern void *ptr_phoneGetStatusW;
void *ptr_phoneGetStatusW = NULL;
extern void *ptr_phoneGetVolume;
void *ptr_phoneGetVolume = NULL;
extern void *ptr_phoneInitialize;
void *ptr_phoneInitialize = NULL;
extern void *ptr_phoneInitializeExA;
void *ptr_phoneInitializeExA = NULL;
extern void *ptr_phoneInitializeExW;
void *ptr_phoneInitializeExW = NULL;
extern void *ptr_phoneNegotiateAPIVersion;
void *ptr_phoneNegotiateAPIVersion = NULL;
extern void *ptr_phoneNegotiateExtVersion;
void *ptr_phoneNegotiateExtVersion = NULL;
extern void *ptr_phoneOpen;
void *ptr_phoneOpen = NULL;
extern void *ptr_phoneSetButtonInfo;
void *ptr_phoneSetButtonInfo = NULL;
extern void *ptr_phoneSetButtonInfoA;
void *ptr_phoneSetButtonInfoA = NULL;
extern void *ptr_phoneSetButtonInfoW;
void *ptr_phoneSetButtonInfoW = NULL;
extern void *ptr_phoneSetData;
void *ptr_phoneSetData = NULL;
extern void *ptr_phoneSetDisplay;
void *ptr_phoneSetDisplay = NULL;
extern void *ptr_phoneSetGain;
void *ptr_phoneSetGain = NULL;
extern void *ptr_phoneSetHookSwitch;
void *ptr_phoneSetHookSwitch = NULL;
extern void *ptr_phoneSetLamp;
void *ptr_phoneSetLamp = NULL;
extern void *ptr_phoneSetRing;
void *ptr_phoneSetRing = NULL;
extern void *ptr_phoneSetStatusMessages;
void *ptr_phoneSetStatusMessages = NULL;
extern void *ptr_phoneSetVolume;
void *ptr_phoneSetVolume = NULL;
extern void *ptr_phoneShutdown;
void *ptr_phoneShutdown = NULL;
extern void *ptr_tapiGetLocationInfo;
void *ptr_tapiGetLocationInfo = NULL;
extern void *ptr_tapiGetLocationInfoA;
void *ptr_tapiGetLocationInfoA = NULL;
extern void *ptr_tapiGetLocationInfoW;
void *ptr_tapiGetLocationInfoW = NULL;
extern void *ptr_tapiRequestDrop;
void *ptr_tapiRequestDrop = NULL;
extern void *ptr_tapiRequestMakeCall;
void *ptr_tapiRequestMakeCall = NULL;
extern void *ptr_tapiRequestMakeCallA;
void *ptr_tapiRequestMakeCallA = NULL;
extern void *ptr_tapiRequestMakeCallW;
void *ptr_tapiRequestMakeCallW = NULL;
extern void *ptr_tapiRequestMediaCall;
void *ptr_tapiRequestMediaCall = NULL;
extern void *ptr_tapiRequestMediaCallA;
void *ptr_tapiRequestMediaCallA = NULL;
extern void *ptr_tapiRequestMediaCallW;
void *ptr_tapiRequestMediaCallW = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\tapi32.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_GetTapi16CallbackMsg = (__vartype(ptr_GetTapi16CallbackMsg))GetProcAddress(hModule, "GetTapi16CallbackMsg");
   ptr_LAddrParamsInited = (__vartype(ptr_LAddrParamsInited))GetProcAddress(hModule, "LAddrParamsInited");
   ptr_LOpenDialAsst = (__vartype(ptr_LOpenDialAsst))GetProcAddress(hModule, "LOpenDialAsst");
   ptr_LocWizardDlgProc = (__vartype(ptr_LocWizardDlgProc))GetProcAddress(hModule, "LocWizardDlgProc");
   ptr_MMCAddProvider = (__vartype(ptr_MMCAddProvider))GetProcAddress(hModule, "MMCAddProvider");
   ptr_MMCConfigProvider = (__vartype(ptr_MMCConfigProvider))GetProcAddress(hModule, "MMCConfigProvider");
   ptr_MMCGetAvailableProviders = (__vartype(ptr_MMCGetAvailableProviders))GetProcAddress(hModule, "MMCGetAvailableProviders");
   ptr_MMCGetDeviceFlags = (__vartype(ptr_MMCGetDeviceFlags))GetProcAddress(hModule, "MMCGetDeviceFlags");
   ptr_MMCGetLineInfo = (__vartype(ptr_MMCGetLineInfo))GetProcAddress(hModule, "MMCGetLineInfo");
   ptr_MMCGetLineStatus = (__vartype(ptr_MMCGetLineStatus))GetProcAddress(hModule, "MMCGetLineStatus");
   ptr_MMCGetPhoneInfo = (__vartype(ptr_MMCGetPhoneInfo))GetProcAddress(hModule, "MMCGetPhoneInfo");
   ptr_MMCGetPhoneStatus = (__vartype(ptr_MMCGetPhoneStatus))GetProcAddress(hModule, "MMCGetPhoneStatus");
   ptr_MMCGetProviderList = (__vartype(ptr_MMCGetProviderList))GetProcAddress(hModule, "MMCGetProviderList");
   ptr_MMCGetServerConfig = (__vartype(ptr_MMCGetServerConfig))GetProcAddress(hModule, "MMCGetServerConfig");
   ptr_MMCInitialize = (__vartype(ptr_MMCInitialize))GetProcAddress(hModule, "MMCInitialize");
   ptr_MMCRemoveProvider = (__vartype(ptr_MMCRemoveProvider))GetProcAddress(hModule, "MMCRemoveProvider");
   ptr_MMCSetLineInfo = (__vartype(ptr_MMCSetLineInfo))GetProcAddress(hModule, "MMCSetLineInfo");
   ptr_MMCSetPhoneInfo = (__vartype(ptr_MMCSetPhoneInfo))GetProcAddress(hModule, "MMCSetPhoneInfo");
   ptr_MMCSetServerConfig = (__vartype(ptr_MMCSetServerConfig))GetProcAddress(hModule, "MMCSetServerConfig");
   ptr_MMCShutdown = (__vartype(ptr_MMCShutdown))GetProcAddress(hModule, "MMCShutdown");
   ptr_NonAsyncEventThread = (__vartype(ptr_NonAsyncEventThread))GetProcAddress(hModule, "NonAsyncEventThread");
   ptr_TAPIWndProc = (__vartype(ptr_TAPIWndProc))GetProcAddress(hModule, "TAPIWndProc");
   ptr_TUISPIDLLCallback = (__vartype(ptr_TUISPIDLLCallback))GetProcAddress(hModule, "TUISPIDLLCallback");
   ptr_internalConfig = (__vartype(ptr_internalConfig))GetProcAddress(hModule, "internalConfig");
   ptr_internalCreateDefLocation = (__vartype(ptr_internalCreateDefLocation))GetProcAddress(hModule, "internalCreateDefLocation");
   ptr_internalNewLocationW = (__vartype(ptr_internalNewLocationW))GetProcAddress(hModule, "internalNewLocationW");
   ptr_internalPerformance = (__vartype(ptr_internalPerformance))GetProcAddress(hModule, "internalPerformance");
   ptr_internalRemoveLocation = (__vartype(ptr_internalRemoveLocation))GetProcAddress(hModule, "internalRemoveLocation");
   ptr_internalRenameLocationW = (__vartype(ptr_internalRenameLocationW))GetProcAddress(hModule, "internalRenameLocationW");
   ptr_lineAccept = (__vartype(ptr_lineAccept))GetProcAddress(hModule, "lineAccept");
   ptr_lineAddProvider = (__vartype(ptr_lineAddProvider))GetProcAddress(hModule, "lineAddProvider");
   ptr_lineAddProviderA = (__vartype(ptr_lineAddProviderA))GetProcAddress(hModule, "lineAddProviderA");
   ptr_lineAddProviderW = (__vartype(ptr_lineAddProviderW))GetProcAddress(hModule, "lineAddProviderW");
   ptr_lineAddToConference = (__vartype(ptr_lineAddToConference))GetProcAddress(hModule, "lineAddToConference");
   ptr_lineAgentSpecific = (__vartype(ptr_lineAgentSpecific))GetProcAddress(hModule, "lineAgentSpecific");
   ptr_lineAnswer = (__vartype(ptr_lineAnswer))GetProcAddress(hModule, "lineAnswer");
   ptr_lineBlindTransfer = (__vartype(ptr_lineBlindTransfer))GetProcAddress(hModule, "lineBlindTransfer");
   ptr_lineBlindTransferA = (__vartype(ptr_lineBlindTransferA))GetProcAddress(hModule, "lineBlindTransferA");
   ptr_lineBlindTransferW = (__vartype(ptr_lineBlindTransferW))GetProcAddress(hModule, "lineBlindTransferW");
   ptr_lineClose = (__vartype(ptr_lineClose))GetProcAddress(hModule, "lineClose");
   ptr_lineCompleteCall = (__vartype(ptr_lineCompleteCall))GetProcAddress(hModule, "lineCompleteCall");
   ptr_lineCompleteTransfer = (__vartype(ptr_lineCompleteTransfer))GetProcAddress(hModule, "lineCompleteTransfer");
   ptr_lineConfigDialog = (__vartype(ptr_lineConfigDialog))GetProcAddress(hModule, "lineConfigDialog");
   ptr_lineConfigDialogA = (__vartype(ptr_lineConfigDialogA))GetProcAddress(hModule, "lineConfigDialogA");
   ptr_lineConfigDialogEdit = (__vartype(ptr_lineConfigDialogEdit))GetProcAddress(hModule, "lineConfigDialogEdit");
   ptr_lineConfigDialogEditA = (__vartype(ptr_lineConfigDialogEditA))GetProcAddress(hModule, "lineConfigDialogEditA");
   ptr_lineConfigDialogEditW = (__vartype(ptr_lineConfigDialogEditW))GetProcAddress(hModule, "lineConfigDialogEditW");
   ptr_lineConfigDialogW = (__vartype(ptr_lineConfigDialogW))GetProcAddress(hModule, "lineConfigDialogW");
   ptr_lineConfigProvider = (__vartype(ptr_lineConfigProvider))GetProcAddress(hModule, "lineConfigProvider");
   ptr_lineCreateAgentA = (__vartype(ptr_lineCreateAgentA))GetProcAddress(hModule, "lineCreateAgentA");
   ptr_lineCreateAgentSessionA = (__vartype(ptr_lineCreateAgentSessionA))GetProcAddress(hModule, "lineCreateAgentSessionA");
   ptr_lineCreateAgentSessionW = (__vartype(ptr_lineCreateAgentSessionW))GetProcAddress(hModule, "lineCreateAgentSessionW");
   ptr_lineCreateAgentW = (__vartype(ptr_lineCreateAgentW))GetProcAddress(hModule, "lineCreateAgentW");
   ptr_lineDeallocateCall = (__vartype(ptr_lineDeallocateCall))GetProcAddress(hModule, "lineDeallocateCall");
   ptr_lineDevSpecific = (__vartype(ptr_lineDevSpecific))GetProcAddress(hModule, "lineDevSpecific");
   ptr_lineDevSpecificFeature = (__vartype(ptr_lineDevSpecificFeature))GetProcAddress(hModule, "lineDevSpecificFeature");
   ptr_lineDial = (__vartype(ptr_lineDial))GetProcAddress(hModule, "lineDial");
   ptr_lineDialA = (__vartype(ptr_lineDialA))GetProcAddress(hModule, "lineDialA");
   ptr_lineDialW = (__vartype(ptr_lineDialW))GetProcAddress(hModule, "lineDialW");
   ptr_lineDrop = (__vartype(ptr_lineDrop))GetProcAddress(hModule, "lineDrop");
   ptr_lineForward = (__vartype(ptr_lineForward))GetProcAddress(hModule, "lineForward");
   ptr_lineForwardA = (__vartype(ptr_lineForwardA))GetProcAddress(hModule, "lineForwardA");
   ptr_lineForwardW = (__vartype(ptr_lineForwardW))GetProcAddress(hModule, "lineForwardW");
   ptr_lineGatherDigits = (__vartype(ptr_lineGatherDigits))GetProcAddress(hModule, "lineGatherDigits");
   ptr_lineGatherDigitsA = (__vartype(ptr_lineGatherDigitsA))GetProcAddress(hModule, "lineGatherDigitsA");
   ptr_lineGatherDigitsW = (__vartype(ptr_lineGatherDigitsW))GetProcAddress(hModule, "lineGatherDigitsW");
   ptr_lineGenerateDigits = (__vartype(ptr_lineGenerateDigits))GetProcAddress(hModule, "lineGenerateDigits");
   ptr_lineGenerateDigitsA = (__vartype(ptr_lineGenerateDigitsA))GetProcAddress(hModule, "lineGenerateDigitsA");
   ptr_lineGenerateDigitsW = (__vartype(ptr_lineGenerateDigitsW))GetProcAddress(hModule, "lineGenerateDigitsW");
   ptr_lineGenerateTone = (__vartype(ptr_lineGenerateTone))GetProcAddress(hModule, "lineGenerateTone");
   ptr_lineGetAddressCaps = (__vartype(ptr_lineGetAddressCaps))GetProcAddress(hModule, "lineGetAddressCaps");
   ptr_lineGetAddressCapsA = (__vartype(ptr_lineGetAddressCapsA))GetProcAddress(hModule, "lineGetAddressCapsA");
   ptr_lineGetAddressCapsW = (__vartype(ptr_lineGetAddressCapsW))GetProcAddress(hModule, "lineGetAddressCapsW");
   ptr_lineGetAddressID = (__vartype(ptr_lineGetAddressID))GetProcAddress(hModule, "lineGetAddressID");
   ptr_lineGetAddressIDA = (__vartype(ptr_lineGetAddressIDA))GetProcAddress(hModule, "lineGetAddressIDA");
   ptr_lineGetAddressIDW = (__vartype(ptr_lineGetAddressIDW))GetProcAddress(hModule, "lineGetAddressIDW");
   ptr_lineGetAddressStatus = (__vartype(ptr_lineGetAddressStatus))GetProcAddress(hModule, "lineGetAddressStatus");
   ptr_lineGetAddressStatusA = (__vartype(ptr_lineGetAddressStatusA))GetProcAddress(hModule, "lineGetAddressStatusA");
   ptr_lineGetAddressStatusW = (__vartype(ptr_lineGetAddressStatusW))GetProcAddress(hModule, "lineGetAddressStatusW");
   ptr_lineGetAgentActivityListA = (__vartype(ptr_lineGetAgentActivityListA))GetProcAddress(hModule, "lineGetAgentActivityListA");
   ptr_lineGetAgentActivityListW = (__vartype(ptr_lineGetAgentActivityListW))GetProcAddress(hModule, "lineGetAgentActivityListW");
   ptr_lineGetAgentCapsA = (__vartype(ptr_lineGetAgentCapsA))GetProcAddress(hModule, "lineGetAgentCapsA");
   ptr_lineGetAgentCapsW = (__vartype(ptr_lineGetAgentCapsW))GetProcAddress(hModule, "lineGetAgentCapsW");
   ptr_lineGetAgentGroupListA = (__vartype(ptr_lineGetAgentGroupListA))GetProcAddress(hModule, "lineGetAgentGroupListA");
   ptr_lineGetAgentGroupListW = (__vartype(ptr_lineGetAgentGroupListW))GetProcAddress(hModule, "lineGetAgentGroupListW");
   ptr_lineGetAgentInfo = (__vartype(ptr_lineGetAgentInfo))GetProcAddress(hModule, "lineGetAgentInfo");
   ptr_lineGetAgentSessionInfo = (__vartype(ptr_lineGetAgentSessionInfo))GetProcAddress(hModule, "lineGetAgentSessionInfo");
   ptr_lineGetAgentSessionList = (__vartype(ptr_lineGetAgentSessionList))GetProcAddress(hModule, "lineGetAgentSessionList");
   ptr_lineGetAgentStatusA = (__vartype(ptr_lineGetAgentStatusA))GetProcAddress(hModule, "lineGetAgentStatusA");
   ptr_lineGetAgentStatusW = (__vartype(ptr_lineGetAgentStatusW))GetProcAddress(hModule, "lineGetAgentStatusW");
   ptr_lineGetAppPriority = (__vartype(ptr_lineGetAppPriority))GetProcAddress(hModule, "lineGetAppPriority");
   ptr_lineGetAppPriorityA = (__vartype(ptr_lineGetAppPriorityA))GetProcAddress(hModule, "lineGetAppPriorityA");
   ptr_lineGetAppPriorityW = (__vartype(ptr_lineGetAppPriorityW))GetProcAddress(hModule, "lineGetAppPriorityW");
   ptr_lineGetCallInfo = (__vartype(ptr_lineGetCallInfo))GetProcAddress(hModule, "lineGetCallInfo");
   ptr_lineGetCallInfoA = (__vartype(ptr_lineGetCallInfoA))GetProcAddress(hModule, "lineGetCallInfoA");
   ptr_lineGetCallInfoW = (__vartype(ptr_lineGetCallInfoW))GetProcAddress(hModule, "lineGetCallInfoW");
   ptr_lineGetCallStatus = (__vartype(ptr_lineGetCallStatus))GetProcAddress(hModule, "lineGetCallStatus");
   ptr_lineGetConfRelatedCalls = (__vartype(ptr_lineGetConfRelatedCalls))GetProcAddress(hModule, "lineGetConfRelatedCalls");
   ptr_lineGetCountry = (__vartype(ptr_lineGetCountry))GetProcAddress(hModule, "lineGetCountry");
   ptr_lineGetCountryA = (__vartype(ptr_lineGetCountryA))GetProcAddress(hModule, "lineGetCountryA");
   ptr_lineGetCountryW = (__vartype(ptr_lineGetCountryW))GetProcAddress(hModule, "lineGetCountryW");
   ptr_lineGetDevCaps = (__vartype(ptr_lineGetDevCaps))GetProcAddress(hModule, "lineGetDevCaps");
   ptr_lineGetDevCapsA = (__vartype(ptr_lineGetDevCapsA))GetProcAddress(hModule, "lineGetDevCapsA");
   ptr_lineGetDevCapsW = (__vartype(ptr_lineGetDevCapsW))GetProcAddress(hModule, "lineGetDevCapsW");
   ptr_lineGetDevConfig = (__vartype(ptr_lineGetDevConfig))GetProcAddress(hModule, "lineGetDevConfig");
   ptr_lineGetDevConfigA = (__vartype(ptr_lineGetDevConfigA))GetProcAddress(hModule, "lineGetDevConfigA");
   ptr_lineGetDevConfigW = (__vartype(ptr_lineGetDevConfigW))GetProcAddress(hModule, "lineGetDevConfigW");
   ptr_lineGetGroupListA = (__vartype(ptr_lineGetGroupListA))GetProcAddress(hModule, "lineGetGroupListA");
   ptr_lineGetGroupListW = (__vartype(ptr_lineGetGroupListW))GetProcAddress(hModule, "lineGetGroupListW");
   ptr_lineGetID = (__vartype(ptr_lineGetID))GetProcAddress(hModule, "lineGetID");
   ptr_lineGetIDA = (__vartype(ptr_lineGetIDA))GetProcAddress(hModule, "lineGetIDA");
   ptr_lineGetIDW = (__vartype(ptr_lineGetIDW))GetProcAddress(hModule, "lineGetIDW");
   ptr_lineGetIcon = (__vartype(ptr_lineGetIcon))GetProcAddress(hModule, "lineGetIcon");
   ptr_lineGetIconA = (__vartype(ptr_lineGetIconA))GetProcAddress(hModule, "lineGetIconA");
   ptr_lineGetIconW = (__vartype(ptr_lineGetIconW))GetProcAddress(hModule, "lineGetIconW");
   ptr_lineGetLineDevStatus = (__vartype(ptr_lineGetLineDevStatus))GetProcAddress(hModule, "lineGetLineDevStatus");
   ptr_lineGetLineDevStatusA = (__vartype(ptr_lineGetLineDevStatusA))GetProcAddress(hModule, "lineGetLineDevStatusA");
   ptr_lineGetLineDevStatusW = (__vartype(ptr_lineGetLineDevStatusW))GetProcAddress(hModule, "lineGetLineDevStatusW");
   ptr_lineGetMessage = (__vartype(ptr_lineGetMessage))GetProcAddress(hModule, "lineGetMessage");
   ptr_lineGetNewCalls = (__vartype(ptr_lineGetNewCalls))GetProcAddress(hModule, "lineGetNewCalls");
   ptr_lineGetNumRings = (__vartype(ptr_lineGetNumRings))GetProcAddress(hModule, "lineGetNumRings");
   ptr_lineGetProviderList = (__vartype(ptr_lineGetProviderList))GetProcAddress(hModule, "lineGetProviderList");
   ptr_lineGetProviderListA = (__vartype(ptr_lineGetProviderListA))GetProcAddress(hModule, "lineGetProviderListA");
   ptr_lineGetProviderListW = (__vartype(ptr_lineGetProviderListW))GetProcAddress(hModule, "lineGetProviderListW");
   ptr_lineGetProxyStatus = (__vartype(ptr_lineGetProxyStatus))GetProcAddress(hModule, "lineGetProxyStatus");
   ptr_lineGetQueueInfo = (__vartype(ptr_lineGetQueueInfo))GetProcAddress(hModule, "lineGetQueueInfo");
   ptr_lineGetQueueListA = (__vartype(ptr_lineGetQueueListA))GetProcAddress(hModule, "lineGetQueueListA");
   ptr_lineGetQueueListW = (__vartype(ptr_lineGetQueueListW))GetProcAddress(hModule, "lineGetQueueListW");
   ptr_lineGetRequest = (__vartype(ptr_lineGetRequest))GetProcAddress(hModule, "lineGetRequest");
   ptr_lineGetRequestA = (__vartype(ptr_lineGetRequestA))GetProcAddress(hModule, "lineGetRequestA");
   ptr_lineGetRequestW = (__vartype(ptr_lineGetRequestW))GetProcAddress(hModule, "lineGetRequestW");
   ptr_lineGetStatusMessages = (__vartype(ptr_lineGetStatusMessages))GetProcAddress(hModule, "lineGetStatusMessages");
   ptr_lineGetTranslateCaps = (__vartype(ptr_lineGetTranslateCaps))GetProcAddress(hModule, "lineGetTranslateCaps");
   ptr_lineGetTranslateCapsA = (__vartype(ptr_lineGetTranslateCapsA))GetProcAddress(hModule, "lineGetTranslateCapsA");
   ptr_lineGetTranslateCapsW = (__vartype(ptr_lineGetTranslateCapsW))GetProcAddress(hModule, "lineGetTranslateCapsW");
   ptr_lineHandoff = (__vartype(ptr_lineHandoff))GetProcAddress(hModule, "lineHandoff");
   ptr_lineHandoffA = (__vartype(ptr_lineHandoffA))GetProcAddress(hModule, "lineHandoffA");
   ptr_lineHandoffW = (__vartype(ptr_lineHandoffW))GetProcAddress(hModule, "lineHandoffW");
   ptr_lineHold = (__vartype(ptr_lineHold))GetProcAddress(hModule, "lineHold");
   ptr_lineInitialize = (__vartype(ptr_lineInitialize))GetProcAddress(hModule, "lineInitialize");
   ptr_lineInitializeExA = (__vartype(ptr_lineInitializeExA))GetProcAddress(hModule, "lineInitializeExA");
   ptr_lineInitializeExW = (__vartype(ptr_lineInitializeExW))GetProcAddress(hModule, "lineInitializeExW");
   ptr_lineMakeCall = (__vartype(ptr_lineMakeCall))GetProcAddress(hModule, "lineMakeCall");
   ptr_lineMakeCallA = (__vartype(ptr_lineMakeCallA))GetProcAddress(hModule, "lineMakeCallA");
   ptr_lineMakeCallW = (__vartype(ptr_lineMakeCallW))GetProcAddress(hModule, "lineMakeCallW");
   ptr_lineMonitorDigits = (__vartype(ptr_lineMonitorDigits))GetProcAddress(hModule, "lineMonitorDigits");
   ptr_lineMonitorMedia = (__vartype(ptr_lineMonitorMedia))GetProcAddress(hModule, "lineMonitorMedia");
   ptr_lineMonitorTones = (__vartype(ptr_lineMonitorTones))GetProcAddress(hModule, "lineMonitorTones");
   ptr_lineNegotiateAPIVersion = (__vartype(ptr_lineNegotiateAPIVersion))GetProcAddress(hModule, "lineNegotiateAPIVersion");
   ptr_lineNegotiateExtVersion = (__vartype(ptr_lineNegotiateExtVersion))GetProcAddress(hModule, "lineNegotiateExtVersion");
   ptr_lineOpen = (__vartype(ptr_lineOpen))GetProcAddress(hModule, "lineOpen");
   ptr_lineOpenA = (__vartype(ptr_lineOpenA))GetProcAddress(hModule, "lineOpenA");
   ptr_lineOpenW = (__vartype(ptr_lineOpenW))GetProcAddress(hModule, "lineOpenW");
   ptr_linePark = (__vartype(ptr_linePark))GetProcAddress(hModule, "linePark");
   ptr_lineParkA = (__vartype(ptr_lineParkA))GetProcAddress(hModule, "lineParkA");
   ptr_lineParkW = (__vartype(ptr_lineParkW))GetProcAddress(hModule, "lineParkW");
   ptr_linePickup = (__vartype(ptr_linePickup))GetProcAddress(hModule, "linePickup");
   ptr_linePickupA = (__vartype(ptr_linePickupA))GetProcAddress(hModule, "linePickupA");
   ptr_linePickupW = (__vartype(ptr_linePickupW))GetProcAddress(hModule, "linePickupW");
   ptr_linePrepareAddToConference = (__vartype(ptr_linePrepareAddToConference))GetProcAddress(hModule, "linePrepareAddToConference");
   ptr_linePrepareAddToConferenceA = (__vartype(ptr_linePrepareAddToConferenceA))GetProcAddress(hModule, "linePrepareAddToConferenceA");
   ptr_linePrepareAddToConferenceW = (__vartype(ptr_linePrepareAddToConferenceW))GetProcAddress(hModule, "linePrepareAddToConferenceW");
   ptr_lineProxyMessage = (__vartype(ptr_lineProxyMessage))GetProcAddress(hModule, "lineProxyMessage");
   ptr_lineProxyResponse = (__vartype(ptr_lineProxyResponse))GetProcAddress(hModule, "lineProxyResponse");
   ptr_lineRedirect = (__vartype(ptr_lineRedirect))GetProcAddress(hModule, "lineRedirect");
   ptr_lineRedirectA = (__vartype(ptr_lineRedirectA))GetProcAddress(hModule, "lineRedirectA");
   ptr_lineRedirectW = (__vartype(ptr_lineRedirectW))GetProcAddress(hModule, "lineRedirectW");
   ptr_lineRegisterRequestRecipient = (__vartype(ptr_lineRegisterRequestRecipient))GetProcAddress(hModule, "lineRegisterRequestRecipient");
   ptr_lineReleaseUserUserInfo = (__vartype(ptr_lineReleaseUserUserInfo))GetProcAddress(hModule, "lineReleaseUserUserInfo");
   ptr_lineRemoveFromConference = (__vartype(ptr_lineRemoveFromConference))GetProcAddress(hModule, "lineRemoveFromConference");
   ptr_lineRemoveProvider = (__vartype(ptr_lineRemoveProvider))GetProcAddress(hModule, "lineRemoveProvider");
   ptr_lineSecureCall = (__vartype(ptr_lineSecureCall))GetProcAddress(hModule, "lineSecureCall");
   ptr_lineSendUserUserInfo = (__vartype(ptr_lineSendUserUserInfo))GetProcAddress(hModule, "lineSendUserUserInfo");
   ptr_lineSetAgentActivity = (__vartype(ptr_lineSetAgentActivity))GetProcAddress(hModule, "lineSetAgentActivity");
   ptr_lineSetAgentGroup = (__vartype(ptr_lineSetAgentGroup))GetProcAddress(hModule, "lineSetAgentGroup");
   ptr_lineSetAgentMeasurementPeriod = (__vartype(ptr_lineSetAgentMeasurementPeriod))GetProcAddress(hModule, "lineSetAgentMeasurementPeriod");
   ptr_lineSetAgentSessionState = (__vartype(ptr_lineSetAgentSessionState))GetProcAddress(hModule, "lineSetAgentSessionState");
   ptr_lineSetAgentState = (__vartype(ptr_lineSetAgentState))GetProcAddress(hModule, "lineSetAgentState");
   ptr_lineSetAgentStateEx = (__vartype(ptr_lineSetAgentStateEx))GetProcAddress(hModule, "lineSetAgentStateEx");
   ptr_lineSetAppPriority = (__vartype(ptr_lineSetAppPriority))GetProcAddress(hModule, "lineSetAppPriority");
   ptr_lineSetAppPriorityA = (__vartype(ptr_lineSetAppPriorityA))GetProcAddress(hModule, "lineSetAppPriorityA");
   ptr_lineSetAppPriorityW = (__vartype(ptr_lineSetAppPriorityW))GetProcAddress(hModule, "lineSetAppPriorityW");
   ptr_lineSetAppSpecific = (__vartype(ptr_lineSetAppSpecific))GetProcAddress(hModule, "lineSetAppSpecific");
   ptr_lineSetCallData = (__vartype(ptr_lineSetCallData))GetProcAddress(hModule, "lineSetCallData");
   ptr_lineSetCallParams = (__vartype(ptr_lineSetCallParams))GetProcAddress(hModule, "lineSetCallParams");
   ptr_lineSetCallPrivilege = (__vartype(ptr_lineSetCallPrivilege))GetProcAddress(hModule, "lineSetCallPrivilege");
   ptr_lineSetCallQualityOfService = (__vartype(ptr_lineSetCallQualityOfService))GetProcAddress(hModule, "lineSetCallQualityOfService");
   ptr_lineSetCallTreatment = (__vartype(ptr_lineSetCallTreatment))GetProcAddress(hModule, "lineSetCallTreatment");
   ptr_lineSetCurrentLocation = (__vartype(ptr_lineSetCurrentLocation))GetProcAddress(hModule, "lineSetCurrentLocation");
   ptr_lineSetDevConfig = (__vartype(ptr_lineSetDevConfig))GetProcAddress(hModule, "lineSetDevConfig");
   ptr_lineSetDevConfigA = (__vartype(ptr_lineSetDevConfigA))GetProcAddress(hModule, "lineSetDevConfigA");
   ptr_lineSetDevConfigW = (__vartype(ptr_lineSetDevConfigW))GetProcAddress(hModule, "lineSetDevConfigW");
   ptr_lineSetLineDevStatus = (__vartype(ptr_lineSetLineDevStatus))GetProcAddress(hModule, "lineSetLineDevStatus");
   ptr_lineSetMediaControl = (__vartype(ptr_lineSetMediaControl))GetProcAddress(hModule, "lineSetMediaControl");
   ptr_lineSetMediaMode = (__vartype(ptr_lineSetMediaMode))GetProcAddress(hModule, "lineSetMediaMode");
   ptr_lineSetNumRings = (__vartype(ptr_lineSetNumRings))GetProcAddress(hModule, "lineSetNumRings");
   ptr_lineSetQueueMeasurementPeriod = (__vartype(ptr_lineSetQueueMeasurementPeriod))GetProcAddress(hModule, "lineSetQueueMeasurementPeriod");
   ptr_lineSetStatusMessages = (__vartype(ptr_lineSetStatusMessages))GetProcAddress(hModule, "lineSetStatusMessages");
   ptr_lineSetTerminal = (__vartype(ptr_lineSetTerminal))GetProcAddress(hModule, "lineSetTerminal");
   ptr_lineSetTollList = (__vartype(ptr_lineSetTollList))GetProcAddress(hModule, "lineSetTollList");
   ptr_lineSetTollListA = (__vartype(ptr_lineSetTollListA))GetProcAddress(hModule, "lineSetTollListA");
   ptr_lineSetTollListW = (__vartype(ptr_lineSetTollListW))GetProcAddress(hModule, "lineSetTollListW");
   ptr_lineSetupConference = (__vartype(ptr_lineSetupConference))GetProcAddress(hModule, "lineSetupConference");
   ptr_lineSetupConferenceA = (__vartype(ptr_lineSetupConferenceA))GetProcAddress(hModule, "lineSetupConferenceA");
   ptr_lineSetupConferenceW = (__vartype(ptr_lineSetupConferenceW))GetProcAddress(hModule, "lineSetupConferenceW");
   ptr_lineSetupTransfer = (__vartype(ptr_lineSetupTransfer))GetProcAddress(hModule, "lineSetupTransfer");
   ptr_lineSetupTransferA = (__vartype(ptr_lineSetupTransferA))GetProcAddress(hModule, "lineSetupTransferA");
   ptr_lineSetupTransferW = (__vartype(ptr_lineSetupTransferW))GetProcAddress(hModule, "lineSetupTransferW");
   ptr_lineShutdown = (__vartype(ptr_lineShutdown))GetProcAddress(hModule, "lineShutdown");
   ptr_lineSwapHold = (__vartype(ptr_lineSwapHold))GetProcAddress(hModule, "lineSwapHold");
   ptr_lineTranslateAddress = (__vartype(ptr_lineTranslateAddress))GetProcAddress(hModule, "lineTranslateAddress");
   ptr_lineTranslateAddressA = (__vartype(ptr_lineTranslateAddressA))GetProcAddress(hModule, "lineTranslateAddressA");
   ptr_lineTranslateAddressW = (__vartype(ptr_lineTranslateAddressW))GetProcAddress(hModule, "lineTranslateAddressW");
   ptr_lineTranslateDialog = (__vartype(ptr_lineTranslateDialog))GetProcAddress(hModule, "lineTranslateDialog");
   ptr_lineTranslateDialogA = (__vartype(ptr_lineTranslateDialogA))GetProcAddress(hModule, "lineTranslateDialogA");
   ptr_lineTranslateDialogW = (__vartype(ptr_lineTranslateDialogW))GetProcAddress(hModule, "lineTranslateDialogW");
   ptr_lineUncompleteCall = (__vartype(ptr_lineUncompleteCall))GetProcAddress(hModule, "lineUncompleteCall");
   ptr_lineUnhold = (__vartype(ptr_lineUnhold))GetProcAddress(hModule, "lineUnhold");
   ptr_lineUnpark = (__vartype(ptr_lineUnpark))GetProcAddress(hModule, "lineUnpark");
   ptr_lineUnparkA = (__vartype(ptr_lineUnparkA))GetProcAddress(hModule, "lineUnparkA");
   ptr_lineUnparkW = (__vartype(ptr_lineUnparkW))GetProcAddress(hModule, "lineUnparkW");
   ptr_phoneClose = (__vartype(ptr_phoneClose))GetProcAddress(hModule, "phoneClose");
   ptr_phoneConfigDialog = (__vartype(ptr_phoneConfigDialog))GetProcAddress(hModule, "phoneConfigDialog");
   ptr_phoneConfigDialogA = (__vartype(ptr_phoneConfigDialogA))GetProcAddress(hModule, "phoneConfigDialogA");
   ptr_phoneConfigDialogW = (__vartype(ptr_phoneConfigDialogW))GetProcAddress(hModule, "phoneConfigDialogW");
   ptr_phoneDevSpecific = (__vartype(ptr_phoneDevSpecific))GetProcAddress(hModule, "phoneDevSpecific");
   ptr_phoneGetButtonInfo = (__vartype(ptr_phoneGetButtonInfo))GetProcAddress(hModule, "phoneGetButtonInfo");
   ptr_phoneGetButtonInfoA = (__vartype(ptr_phoneGetButtonInfoA))GetProcAddress(hModule, "phoneGetButtonInfoA");
   ptr_phoneGetButtonInfoW = (__vartype(ptr_phoneGetButtonInfoW))GetProcAddress(hModule, "phoneGetButtonInfoW");
   ptr_phoneGetData = (__vartype(ptr_phoneGetData))GetProcAddress(hModule, "phoneGetData");
   ptr_phoneGetDevCaps = (__vartype(ptr_phoneGetDevCaps))GetProcAddress(hModule, "phoneGetDevCaps");
   ptr_phoneGetDevCapsA = (__vartype(ptr_phoneGetDevCapsA))GetProcAddress(hModule, "phoneGetDevCapsA");
   ptr_phoneGetDevCapsW = (__vartype(ptr_phoneGetDevCapsW))GetProcAddress(hModule, "phoneGetDevCapsW");
   ptr_phoneGetDisplay = (__vartype(ptr_phoneGetDisplay))GetProcAddress(hModule, "phoneGetDisplay");
   ptr_phoneGetGain = (__vartype(ptr_phoneGetGain))GetProcAddress(hModule, "phoneGetGain");
   ptr_phoneGetHookSwitch = (__vartype(ptr_phoneGetHookSwitch))GetProcAddress(hModule, "phoneGetHookSwitch");
   ptr_phoneGetID = (__vartype(ptr_phoneGetID))GetProcAddress(hModule, "phoneGetID");
   ptr_phoneGetIDA = (__vartype(ptr_phoneGetIDA))GetProcAddress(hModule, "phoneGetIDA");
   ptr_phoneGetIDW = (__vartype(ptr_phoneGetIDW))GetProcAddress(hModule, "phoneGetIDW");
   ptr_phoneGetIcon = (__vartype(ptr_phoneGetIcon))GetProcAddress(hModule, "phoneGetIcon");
   ptr_phoneGetIconA = (__vartype(ptr_phoneGetIconA))GetProcAddress(hModule, "phoneGetIconA");
   ptr_phoneGetIconW = (__vartype(ptr_phoneGetIconW))GetProcAddress(hModule, "phoneGetIconW");
   ptr_phoneGetLamp = (__vartype(ptr_phoneGetLamp))GetProcAddress(hModule, "phoneGetLamp");
   ptr_phoneGetMessage = (__vartype(ptr_phoneGetMessage))GetProcAddress(hModule, "phoneGetMessage");
   ptr_phoneGetRing = (__vartype(ptr_phoneGetRing))GetProcAddress(hModule, "phoneGetRing");
   ptr_phoneGetStatus = (__vartype(ptr_phoneGetStatus))GetProcAddress(hModule, "phoneGetStatus");
   ptr_phoneGetStatusA = (__vartype(ptr_phoneGetStatusA))GetProcAddress(hModule, "phoneGetStatusA");
   ptr_phoneGetStatusMessages = (__vartype(ptr_phoneGetStatusMessages))GetProcAddress(hModule, "phoneGetStatusMessages");
   ptr_phoneGetStatusW = (__vartype(ptr_phoneGetStatusW))GetProcAddress(hModule, "phoneGetStatusW");
   ptr_phoneGetVolume = (__vartype(ptr_phoneGetVolume))GetProcAddress(hModule, "phoneGetVolume");
   ptr_phoneInitialize = (__vartype(ptr_phoneInitialize))GetProcAddress(hModule, "phoneInitialize");
   ptr_phoneInitializeExA = (__vartype(ptr_phoneInitializeExA))GetProcAddress(hModule, "phoneInitializeExA");
   ptr_phoneInitializeExW = (__vartype(ptr_phoneInitializeExW))GetProcAddress(hModule, "phoneInitializeExW");
   ptr_phoneNegotiateAPIVersion = (__vartype(ptr_phoneNegotiateAPIVersion))GetProcAddress(hModule, "phoneNegotiateAPIVersion");
   ptr_phoneNegotiateExtVersion = (__vartype(ptr_phoneNegotiateExtVersion))GetProcAddress(hModule, "phoneNegotiateExtVersion");
   ptr_phoneOpen = (__vartype(ptr_phoneOpen))GetProcAddress(hModule, "phoneOpen");
   ptr_phoneSetButtonInfo = (__vartype(ptr_phoneSetButtonInfo))GetProcAddress(hModule, "phoneSetButtonInfo");
   ptr_phoneSetButtonInfoA = (__vartype(ptr_phoneSetButtonInfoA))GetProcAddress(hModule, "phoneSetButtonInfoA");
   ptr_phoneSetButtonInfoW = (__vartype(ptr_phoneSetButtonInfoW))GetProcAddress(hModule, "phoneSetButtonInfoW");
   ptr_phoneSetData = (__vartype(ptr_phoneSetData))GetProcAddress(hModule, "phoneSetData");
   ptr_phoneSetDisplay = (__vartype(ptr_phoneSetDisplay))GetProcAddress(hModule, "phoneSetDisplay");
   ptr_phoneSetGain = (__vartype(ptr_phoneSetGain))GetProcAddress(hModule, "phoneSetGain");
   ptr_phoneSetHookSwitch = (__vartype(ptr_phoneSetHookSwitch))GetProcAddress(hModule, "phoneSetHookSwitch");
   ptr_phoneSetLamp = (__vartype(ptr_phoneSetLamp))GetProcAddress(hModule, "phoneSetLamp");
   ptr_phoneSetRing = (__vartype(ptr_phoneSetRing))GetProcAddress(hModule, "phoneSetRing");
   ptr_phoneSetStatusMessages = (__vartype(ptr_phoneSetStatusMessages))GetProcAddress(hModule, "phoneSetStatusMessages");
   ptr_phoneSetVolume = (__vartype(ptr_phoneSetVolume))GetProcAddress(hModule, "phoneSetVolume");
   ptr_phoneShutdown = (__vartype(ptr_phoneShutdown))GetProcAddress(hModule, "phoneShutdown");
   ptr_tapiGetLocationInfo = (__vartype(ptr_tapiGetLocationInfo))GetProcAddress(hModule, "tapiGetLocationInfo");
   ptr_tapiGetLocationInfoA = (__vartype(ptr_tapiGetLocationInfoA))GetProcAddress(hModule, "tapiGetLocationInfoA");
   ptr_tapiGetLocationInfoW = (__vartype(ptr_tapiGetLocationInfoW))GetProcAddress(hModule, "tapiGetLocationInfoW");
   ptr_tapiRequestDrop = (__vartype(ptr_tapiRequestDrop))GetProcAddress(hModule, "tapiRequestDrop");
   ptr_tapiRequestMakeCall = (__vartype(ptr_tapiRequestMakeCall))GetProcAddress(hModule, "tapiRequestMakeCall");
   ptr_tapiRequestMakeCallA = (__vartype(ptr_tapiRequestMakeCallA))GetProcAddress(hModule, "tapiRequestMakeCallA");
   ptr_tapiRequestMakeCallW = (__vartype(ptr_tapiRequestMakeCallW))GetProcAddress(hModule, "tapiRequestMakeCallW");
   ptr_tapiRequestMediaCall = (__vartype(ptr_tapiRequestMediaCall))GetProcAddress(hModule, "tapiRequestMediaCall");
   ptr_tapiRequestMediaCallA = (__vartype(ptr_tapiRequestMediaCallA))GetProcAddress(hModule, "tapiRequestMediaCallA");
   ptr_tapiRequestMediaCallW = (__vartype(ptr_tapiRequestMediaCallW))GetProcAddress(hModule, "tapiRequestMediaCallW");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

