#include <windows.h>
#include <shlwapi.h>

extern "C" {
extern void *ptr_BreakRecordsIntoBlob;
void *ptr_BreakRecordsIntoBlob = NULL;
extern void *ptr_CombineRecordsInBlob;
void *ptr_CombineRecordsInBlob = NULL;
extern void *ptr_DnsAcquireContextHandle_A;
void *ptr_DnsAcquireContextHandle_A = NULL;
extern void *ptr_DnsAcquireContextHandle_W;
void *ptr_DnsAcquireContextHandle_W = NULL;
extern void *ptr_DnsAllocateRecord;
void *ptr_DnsAllocateRecord = NULL;
extern void *ptr_DnsApiAlloc;
void *ptr_DnsApiAlloc = NULL;
extern void *ptr_DnsApiAllocZero;
void *ptr_DnsApiAllocZero = NULL;
extern void *ptr_DnsApiFree;
void *ptr_DnsApiFree = NULL;
extern void *ptr_DnsApiHeapReset;
void *ptr_DnsApiHeapReset = NULL;
extern void *ptr_DnsApiRealloc;
void *ptr_DnsApiRealloc = NULL;
extern void *ptr_DnsApiSetDebugGlobals;
void *ptr_DnsApiSetDebugGlobals = NULL;
extern void *ptr_DnsAsyncRegisterHostAddrs;
void *ptr_DnsAsyncRegisterHostAddrs = NULL;
extern void *ptr_DnsAsyncRegisterInit;
void *ptr_DnsAsyncRegisterInit = NULL;
extern void *ptr_DnsAsyncRegisterTerm;
void *ptr_DnsAsyncRegisterTerm = NULL;
extern void *ptr_DnsCopyStringEx;
void *ptr_DnsCopyStringEx = NULL;
extern void *ptr_DnsCreateReverseNameStringForIpAddress;
void *ptr_DnsCreateReverseNameStringForIpAddress = NULL;
extern void *ptr_DnsCreateStandardDnsNameCopy;
void *ptr_DnsCreateStandardDnsNameCopy = NULL;
extern void *ptr_DnsCreateStringCopy;
void *ptr_DnsCreateStringCopy = NULL;
extern void *ptr_DnsDhcpRegisterAddrs;
void *ptr_DnsDhcpRegisterAddrs = NULL;
extern void *ptr_DnsDhcpRegisterHostAddrs;
void *ptr_DnsDhcpRegisterHostAddrs = NULL;
extern void *ptr_DnsDhcpRegisterInit;
void *ptr_DnsDhcpRegisterInit = NULL;
extern void *ptr_DnsDhcpRegisterTerm;
void *ptr_DnsDhcpRegisterTerm = NULL;
extern void *ptr_DnsDhcpRemoveRegistrations;
void *ptr_DnsDhcpRemoveRegistrations = NULL;
extern void *ptr_DnsDhcpSrvRegisterHostAddr;
void *ptr_DnsDhcpSrvRegisterHostAddr = NULL;
extern void *ptr_DnsDhcpSrvRegisterHostAddrEx;
void *ptr_DnsDhcpSrvRegisterHostAddrEx = NULL;
extern void *ptr_DnsDhcpSrvRegisterHostName;
void *ptr_DnsDhcpSrvRegisterHostName = NULL;
extern void *ptr_DnsDhcpSrvRegisterHostNameEx;
void *ptr_DnsDhcpSrvRegisterHostNameEx = NULL;
extern void *ptr_DnsDhcpSrvRegisterInit;
void *ptr_DnsDhcpSrvRegisterInit = NULL;
extern void *ptr_DnsDhcpSrvRegisterInitialize;
void *ptr_DnsDhcpSrvRegisterInitialize = NULL;
extern void *ptr_DnsDhcpSrvRegisterTerm;
void *ptr_DnsDhcpSrvRegisterTerm = NULL;
extern void *ptr_DnsDowncaseDnsNameLabel;
void *ptr_DnsDowncaseDnsNameLabel = NULL;
extern void *ptr_DnsExtractRecordsFromMessage_UTF8;
void *ptr_DnsExtractRecordsFromMessage_UTF8 = NULL;
extern void *ptr_DnsExtractRecordsFromMessage_W;
void *ptr_DnsExtractRecordsFromMessage_W = NULL;
extern void *ptr_DnsFindAuthoritativeZone;
void *ptr_DnsFindAuthoritativeZone = NULL;
extern void *ptr_DnsFlushResolverCache;
void *ptr_DnsFlushResolverCache = NULL;
extern void *ptr_DnsFlushResolverCacheEntry_A;
void *ptr_DnsFlushResolverCacheEntry_A = NULL;
extern void *ptr_DnsFlushResolverCacheEntry_UTF8;
void *ptr_DnsFlushResolverCacheEntry_UTF8 = NULL;
extern void *ptr_DnsFlushResolverCacheEntry_W;
void *ptr_DnsFlushResolverCacheEntry_W = NULL;
extern void *ptr_DnsFree;
void *ptr_DnsFree = NULL;
extern void *ptr_DnsFreeConfigStructure;
void *ptr_DnsFreeConfigStructure = NULL;
extern void *ptr_DnsFreePolicyConfig;
void *ptr_DnsFreePolicyConfig = NULL;
extern void *ptr_DnsFreeProxyName;
void *ptr_DnsFreeProxyName = NULL;
extern void *ptr_DnsGetBufferLengthForStringCopy;
void *ptr_DnsGetBufferLengthForStringCopy = NULL;
extern void *ptr_DnsGetCacheDataTable;
void *ptr_DnsGetCacheDataTable = NULL;
extern void *ptr_DnsGetDnsServerList;
void *ptr_DnsGetDnsServerList = NULL;
extern void *ptr_DnsGetDomainName;
void *ptr_DnsGetDomainName = NULL;
extern void *ptr_DnsGetLastFailedUpdateInfo;
void *ptr_DnsGetLastFailedUpdateInfo = NULL;
extern void *ptr_DnsGetPolicyTableInfo;
void *ptr_DnsGetPolicyTableInfo = NULL;
extern void *ptr_DnsGetPolicyTableInfoPrivate;
void *ptr_DnsGetPolicyTableInfoPrivate = NULL;
extern void *ptr_DnsGetPrimaryDomainName_A;
void *ptr_DnsGetPrimaryDomainName_A = NULL;
extern void *ptr_DnsGetProxyInfoPrivate;
void *ptr_DnsGetProxyInfoPrivate = NULL;
extern void *ptr_DnsGetProxyInformation;
void *ptr_DnsGetProxyInformation = NULL;
extern void *ptr_DnsGlobals;
void *ptr_DnsGlobals = NULL;
extern void *ptr_DnsIpv6AddressToString;
void *ptr_DnsIpv6AddressToString = NULL;
extern void *ptr_DnsIpv6StringToAddress;
void *ptr_DnsIpv6StringToAddress = NULL;
extern void *ptr_DnsIsAMailboxType;
void *ptr_DnsIsAMailboxType = NULL;
extern void *ptr_DnsIsStatusRcode;
void *ptr_DnsIsStatusRcode = NULL;
extern void *ptr_DnsIsStringCountValidForTextType;
void *ptr_DnsIsStringCountValidForTextType = NULL;
extern void *ptr_DnsLogEvent;
void *ptr_DnsLogEvent = NULL;
extern void *ptr_DnsLogIn;
void *ptr_DnsLogIn = NULL;
extern void *ptr_DnsLogInit;
void *ptr_DnsLogInit = NULL;
extern void *ptr_DnsLogIt;
void *ptr_DnsLogIt = NULL;
extern void *ptr_DnsLogOut;
void *ptr_DnsLogOut = NULL;
extern void *ptr_DnsLogTime;
void *ptr_DnsLogTime = NULL;
extern void *ptr_DnsMapRcodeToStatus;
void *ptr_DnsMapRcodeToStatus = NULL;
extern void *ptr_DnsModifyRecordsInSet_A;
void *ptr_DnsModifyRecordsInSet_A = NULL;
extern void *ptr_DnsModifyRecordsInSet_UTF8;
void *ptr_DnsModifyRecordsInSet_UTF8 = NULL;
extern void *ptr_DnsModifyRecordsInSet_W;
void *ptr_DnsModifyRecordsInSet_W = NULL;
extern void *ptr_DnsNameCompareEx_A;
void *ptr_DnsNameCompareEx_A = NULL;
extern void *ptr_DnsNameCompareEx_UTF8;
void *ptr_DnsNameCompareEx_UTF8 = NULL;
extern void *ptr_DnsNameCompareEx_W;
void *ptr_DnsNameCompareEx_W = NULL;
extern void *ptr_DnsNameCompare_A;
void *ptr_DnsNameCompare_A = NULL;
extern void *ptr_DnsNameCompare_UTF8;
void *ptr_DnsNameCompare_UTF8 = NULL;
extern void *ptr_DnsNameCompare_W;
void *ptr_DnsNameCompare_W = NULL;
extern void *ptr_DnsNameCopy;
void *ptr_DnsNameCopy = NULL;
extern void *ptr_DnsNameCopyAllocate;
void *ptr_DnsNameCopyAllocate = NULL;
extern void *ptr_DnsNetworkInfo_CreateFromFAZ;
void *ptr_DnsNetworkInfo_CreateFromFAZ = NULL;
extern void *ptr_DnsNetworkInformation_CreateFromFAZ;
void *ptr_DnsNetworkInformation_CreateFromFAZ = NULL;
extern void *ptr_DnsNotifyResolver;
void *ptr_DnsNotifyResolver = NULL;
extern void *ptr_DnsNotifyResolverClusterIp;
void *ptr_DnsNotifyResolverClusterIp = NULL;
extern void *ptr_DnsNotifyResolverEx;
void *ptr_DnsNotifyResolverEx = NULL;
extern void *ptr_DnsQueryConfig;
void *ptr_DnsQueryConfig = NULL;
extern void *ptr_DnsQueryConfigAllocEx;
void *ptr_DnsQueryConfigAllocEx = NULL;
extern void *ptr_DnsQueryConfigDword;
void *ptr_DnsQueryConfigDword = NULL;
extern void *ptr_DnsQueryExA;
void *ptr_DnsQueryExA = NULL;
extern void *ptr_DnsQueryExUTF8;
void *ptr_DnsQueryExUTF8 = NULL;
extern void *ptr_DnsQueryExW;
void *ptr_DnsQueryExW = NULL;
extern void *ptr_DnsQuery_A;
void *ptr_DnsQuery_A = NULL;
extern void *ptr_DnsQuery_UTF8;
void *ptr_DnsQuery_UTF8 = NULL;
extern void *ptr_DnsQuery_W;
void *ptr_DnsQuery_W = NULL;
extern void *ptr_DnsRecordBuild_UTF8;
void *ptr_DnsRecordBuild_UTF8 = NULL;
extern void *ptr_DnsRecordBuild_W;
void *ptr_DnsRecordBuild_W = NULL;
extern void *ptr_DnsRecordCompare;
void *ptr_DnsRecordCompare = NULL;
extern void *ptr_DnsRecordCopyEx;
void *ptr_DnsRecordCopyEx = NULL;
extern void *ptr_DnsRecordListFree;
void *ptr_DnsRecordListFree = NULL;
extern void *ptr_DnsRecordSetCompare;
void *ptr_DnsRecordSetCompare = NULL;
extern void *ptr_DnsRecordSetCopyEx;
void *ptr_DnsRecordSetCopyEx = NULL;
extern void *ptr_DnsRecordSetDetach;
void *ptr_DnsRecordSetDetach = NULL;
extern void *ptr_DnsRecordStringForType;
void *ptr_DnsRecordStringForType = NULL;
extern void *ptr_DnsRecordStringForWritableType;
void *ptr_DnsRecordStringForWritableType = NULL;
extern void *ptr_DnsRecordTypeForName;
void *ptr_DnsRecordTypeForName = NULL;
extern void *ptr_DnsRegisterClusterAddress;
void *ptr_DnsRegisterClusterAddress = NULL;
extern void *ptr_DnsReleaseContextHandle;
void *ptr_DnsReleaseContextHandle = NULL;
extern void *ptr_DnsRemoveRegistrations;
void *ptr_DnsRemoveRegistrations = NULL;
extern void *ptr_DnsReplaceRecordSetA;
void *ptr_DnsReplaceRecordSetA = NULL;
extern void *ptr_DnsReplaceRecordSetUTF8;
void *ptr_DnsReplaceRecordSetUTF8 = NULL;
extern void *ptr_DnsReplaceRecordSetW;
void *ptr_DnsReplaceRecordSetW = NULL;
extern void *ptr_DnsResolverOp;
void *ptr_DnsResolverOp = NULL;
extern void *ptr_DnsScreenLocalAddrsForRegistration;
void *ptr_DnsScreenLocalAddrsForRegistration = NULL;
extern void *ptr_DnsSetConfigDword;
void *ptr_DnsSetConfigDword = NULL;
extern void *ptr_DnsStatusString;
void *ptr_DnsStatusString = NULL;
extern void *ptr_DnsStringCopyAllocateEx;
void *ptr_DnsStringCopyAllocateEx = NULL;
extern void *ptr_DnsTraceServerConfig;
void *ptr_DnsTraceServerConfig = NULL;
extern void *ptr_DnsUnicodeToUtf8;
void *ptr_DnsUnicodeToUtf8 = NULL;
extern void *ptr_DnsUpdate;
void *ptr_DnsUpdate = NULL;
extern void *ptr_DnsUpdateMachinePresence;
void *ptr_DnsUpdateMachinePresence = NULL;
extern void *ptr_DnsUpdateTest_A;
void *ptr_DnsUpdateTest_A = NULL;
extern void *ptr_DnsUpdateTest_UTF8;
void *ptr_DnsUpdateTest_UTF8 = NULL;
extern void *ptr_DnsUpdateTest_W;
void *ptr_DnsUpdateTest_W = NULL;
extern void *ptr_DnsUtf8ToUnicode;
void *ptr_DnsUtf8ToUnicode = NULL;
extern void *ptr_DnsValidateNameOrIp_TempW;
void *ptr_DnsValidateNameOrIp_TempW = NULL;
extern void *ptr_DnsValidateName_A;
void *ptr_DnsValidateName_A = NULL;
extern void *ptr_DnsValidateName_UTF8;
void *ptr_DnsValidateName_UTF8 = NULL;
extern void *ptr_DnsValidateName_W;
void *ptr_DnsValidateName_W = NULL;
extern void *ptr_DnsValidateServerArray_A;
void *ptr_DnsValidateServerArray_A = NULL;
extern void *ptr_DnsValidateServerArray_W;
void *ptr_DnsValidateServerArray_W = NULL;
extern void *ptr_DnsValidateServerStatus;
void *ptr_DnsValidateServerStatus = NULL;
extern void *ptr_DnsValidateServer_A;
void *ptr_DnsValidateServer_A = NULL;
extern void *ptr_DnsValidateServer_W;
void *ptr_DnsValidateServer_W = NULL;
extern void *ptr_DnsValidateUtf8Byte;
void *ptr_DnsValidateUtf8Byte = NULL;
extern void *ptr_DnsWriteQuestionToBuffer_UTF8;
void *ptr_DnsWriteQuestionToBuffer_UTF8 = NULL;
extern void *ptr_DnsWriteQuestionToBuffer_W;
void *ptr_DnsWriteQuestionToBuffer_W = NULL;
extern void *ptr_DnsWriteReverseNameStringForIpAddress;
void *ptr_DnsWriteReverseNameStringForIpAddress = NULL;
extern void *ptr_Dns_AddRecordsToMessage;
void *ptr_Dns_AddRecordsToMessage = NULL;
extern void *ptr_Dns_AllocateMsgBuf;
void *ptr_Dns_AllocateMsgBuf = NULL;
extern void *ptr_Dns_BuildPacket;
void *ptr_Dns_BuildPacket = NULL;
extern void *ptr_Dns_CleanupWinsock;
void *ptr_Dns_CleanupWinsock = NULL;
extern void *ptr_Dns_CloseConnection;
void *ptr_Dns_CloseConnection = NULL;
extern void *ptr_Dns_CloseSocket;
void *ptr_Dns_CloseSocket = NULL;
extern void *ptr_Dns_CreateMulticastSocket;
void *ptr_Dns_CreateMulticastSocket = NULL;
extern void *ptr_Dns_CreateSocket;
void *ptr_Dns_CreateSocket = NULL;
extern void *ptr_Dns_CreateSocketEx;
void *ptr_Dns_CreateSocketEx = NULL;
extern void *ptr_Dns_ExtractRecordsFromMessage;
void *ptr_Dns_ExtractRecordsFromMessage = NULL;
extern void *ptr_Dns_FindAuthoritativeZoneLib;
void *ptr_Dns_FindAuthoritativeZoneLib = NULL;
extern void *ptr_Dns_FreeMsgBuf;
void *ptr_Dns_FreeMsgBuf = NULL;
extern void *ptr_Dns_GetRandomXid;
void *ptr_Dns_GetRandomXid = NULL;
extern void *ptr_Dns_InitializeMsgBuf;
void *ptr_Dns_InitializeMsgBuf = NULL;
extern void *ptr_Dns_InitializeMsgRemoteSockaddr;
void *ptr_Dns_InitializeMsgRemoteSockaddr = NULL;
extern void *ptr_Dns_InitializeWinsock;
void *ptr_Dns_InitializeWinsock = NULL;
extern void *ptr_Dns_OpenTcpConnectionAndSend;
void *ptr_Dns_OpenTcpConnectionAndSend = NULL;
extern void *ptr_Dns_ParseMessage;
void *ptr_Dns_ParseMessage = NULL;
extern void *ptr_Dns_ParsePacketRecord;
void *ptr_Dns_ParsePacketRecord = NULL;
extern void *ptr_Dns_PingAdapterServers;
void *ptr_Dns_PingAdapterServers = NULL;
extern void *ptr_Dns_ReadPacketName;
void *ptr_Dns_ReadPacketName = NULL;
extern void *ptr_Dns_ReadPacketNameAllocate;
void *ptr_Dns_ReadPacketNameAllocate = NULL;
extern void *ptr_Dns_ReadRecordStructureFromPacket;
void *ptr_Dns_ReadRecordStructureFromPacket = NULL;
extern void *ptr_Dns_RecvTcp;
void *ptr_Dns_RecvTcp = NULL;
extern void *ptr_Dns_ResetNetworkInfo;
void *ptr_Dns_ResetNetworkInfo = NULL;
extern void *ptr_Dns_SendAndRecvUdp;
void *ptr_Dns_SendAndRecvUdp = NULL;
extern void *ptr_Dns_SendEx;
void *ptr_Dns_SendEx = NULL;
extern void *ptr_Dns_SetRecordDatalength;
void *ptr_Dns_SetRecordDatalength = NULL;
extern void *ptr_Dns_SetRecordsSection;
void *ptr_Dns_SetRecordsSection = NULL;
extern void *ptr_Dns_SetRecordsTtl;
void *ptr_Dns_SetRecordsTtl = NULL;
extern void *ptr_Dns_SkipPacketName;
void *ptr_Dns_SkipPacketName = NULL;
extern void *ptr_Dns_SkipToRecord;
void *ptr_Dns_SkipToRecord = NULL;
extern void *ptr_Dns_UpdateLib;
void *ptr_Dns_UpdateLib = NULL;
extern void *ptr_Dns_UpdateLibEx;
void *ptr_Dns_UpdateLibEx = NULL;
extern void *ptr_Dns_WriteDottedNameToPacket;
void *ptr_Dns_WriteDottedNameToPacket = NULL;
extern void *ptr_Dns_WriteQuestionToMessage;
void *ptr_Dns_WriteQuestionToMessage = NULL;
extern void *ptr_Dns_WriteRecordStructureToPacketEx;
void *ptr_Dns_WriteRecordStructureToPacketEx = NULL;
extern void *ptr_ExtraInfo_Init;
void *ptr_ExtraInfo_Init = NULL;
extern void *ptr_Faz_AreServerListsInSameNameSpace;
void *ptr_Faz_AreServerListsInSameNameSpace = NULL;
extern void *ptr_FlushDnsPolicyUnreachableStatus;
void *ptr_FlushDnsPolicyUnreachableStatus = NULL;
extern void *ptr_GetCurrentTimeInSeconds;
void *ptr_GetCurrentTimeInSeconds = NULL;
extern void *ptr_HostsFile_Close;
void *ptr_HostsFile_Close = NULL;
extern void *ptr_HostsFile_Open;
void *ptr_HostsFile_Open = NULL;
extern void *ptr_HostsFile_ReadLine;
void *ptr_HostsFile_ReadLine = NULL;
extern void *ptr_IpHelp_IsAddrOnLink;
void *ptr_IpHelp_IsAddrOnLink = NULL;
extern void *ptr_Local_GetRecordsForLocalName;
void *ptr_Local_GetRecordsForLocalName = NULL;
extern void *ptr_Local_GetRecordsForLocalNameEx;
void *ptr_Local_GetRecordsForLocalNameEx = NULL;
extern void *ptr_NetInfo_Build;
void *ptr_NetInfo_Build = NULL;
extern void *ptr_NetInfo_Clean;
void *ptr_NetInfo_Clean = NULL;
extern void *ptr_NetInfo_Copy;
void *ptr_NetInfo_Copy = NULL;
extern void *ptr_NetInfo_Free;
void *ptr_NetInfo_Free = NULL;
extern void *ptr_NetInfo_GetAdapterByAddress;
void *ptr_NetInfo_GetAdapterByAddress = NULL;
extern void *ptr_NetInfo_GetAdapterByInterfaceIndex;
void *ptr_NetInfo_GetAdapterByInterfaceIndex = NULL;
extern void *ptr_NetInfo_GetAdapterByName;
void *ptr_NetInfo_GetAdapterByName = NULL;
extern void *ptr_NetInfo_IsAddrConfig;
void *ptr_NetInfo_IsAddrConfig = NULL;
extern void *ptr_NetInfo_IsForUpdate;
void *ptr_NetInfo_IsForUpdate = NULL;
extern void *ptr_NetInfo_ResetServerPriorities;
void *ptr_NetInfo_ResetServerPriorities = NULL;
extern void *ptr_NetInfo_UpdateServerReachability;
void *ptr_NetInfo_UpdateServerReachability = NULL;
extern void *ptr_QueryDirectEx;
void *ptr_QueryDirectEx = NULL;
extern void *ptr_Query_Main;
void *ptr_Query_Main = NULL;
extern void *ptr_Reg_FreeUpdateInfo;
void *ptr_Reg_FreeUpdateInfo = NULL;
extern void *ptr_Reg_GetValueEx;
void *ptr_Reg_GetValueEx = NULL;
extern void *ptr_Reg_ReadGlobalsEx;
void *ptr_Reg_ReadGlobalsEx = NULL;
extern void *ptr_Reg_ReadUpdateInfo;
void *ptr_Reg_ReadUpdateInfo = NULL;
extern void *ptr_Security_ContextListTimeout;
void *ptr_Security_ContextListTimeout = NULL;
extern void *ptr_Send_AndRecvUdpWithParam;
void *ptr_Send_AndRecvUdpWithParam = NULL;
extern void *ptr_Send_MessagePrivate;
void *ptr_Send_MessagePrivate = NULL;
extern void *ptr_Send_OpenTcpConnectionAndSend;
void *ptr_Send_OpenTcpConnectionAndSend = NULL;
extern void *ptr_Socket_CacheCleanup;
void *ptr_Socket_CacheCleanup = NULL;
extern void *ptr_Socket_CacheInit;
void *ptr_Socket_CacheInit = NULL;
extern void *ptr_Socket_CleanupWinsock;
void *ptr_Socket_CleanupWinsock = NULL;
extern void *ptr_Socket_ClearMessageSockets;
void *ptr_Socket_ClearMessageSockets = NULL;
extern void *ptr_Socket_CloseEx;
void *ptr_Socket_CloseEx = NULL;
extern void *ptr_Socket_CloseMessageSockets;
void *ptr_Socket_CloseMessageSockets = NULL;
extern void *ptr_Socket_Create;
void *ptr_Socket_Create = NULL;
extern void *ptr_Socket_CreateMulticast;
void *ptr_Socket_CreateMulticast = NULL;
extern void *ptr_Socket_InitWinsock;
void *ptr_Socket_InitWinsock = NULL;
extern void *ptr_Socket_JoinMulticast;
void *ptr_Socket_JoinMulticast = NULL;
extern void *ptr_Socket_RecvFrom;
void *ptr_Socket_RecvFrom = NULL;
extern void *ptr_Socket_SetMulticastInterface;
void *ptr_Socket_SetMulticastInterface = NULL;
extern void *ptr_Socket_SetMulticastLoopBack;
void *ptr_Socket_SetMulticastLoopBack = NULL;
extern void *ptr_Socket_SetTtl;
void *ptr_Socket_SetTtl = NULL;
extern void *ptr_Socket_TcpListen;
void *ptr_Socket_TcpListen = NULL;
extern void *ptr_Trace_Reset;
void *ptr_Trace_Reset = NULL;
extern void *ptr_Update_ReplaceAddressRecordsW;
void *ptr_Update_ReplaceAddressRecordsW = NULL;
extern void *ptr_Util_IsIp6Running;
void *ptr_Util_IsIp6Running = NULL;
}


static HMODULE hModule = NULL;
static void module_init()
{    
   if (hModule) return;
   wchar_t sz_module_file[MAX_PATH];
   GetSystemDirectoryW(sz_module_file, MAX_PATH);
   wcscat_s(sz_module_file, L"\\dnsapi.dll");
   hModule = LoadLibraryW(sz_module_file);
   if (!hModule) return;

   #define __vartype(x) decltype(x)
   ptr_BreakRecordsIntoBlob = (__vartype(ptr_BreakRecordsIntoBlob))GetProcAddress(hModule, "BreakRecordsIntoBlob");
   ptr_CombineRecordsInBlob = (__vartype(ptr_CombineRecordsInBlob))GetProcAddress(hModule, "CombineRecordsInBlob");
   ptr_DnsAcquireContextHandle_A = (__vartype(ptr_DnsAcquireContextHandle_A))GetProcAddress(hModule, "DnsAcquireContextHandle_A");
   ptr_DnsAcquireContextHandle_W = (__vartype(ptr_DnsAcquireContextHandle_W))GetProcAddress(hModule, "DnsAcquireContextHandle_W");
   ptr_DnsAllocateRecord = (__vartype(ptr_DnsAllocateRecord))GetProcAddress(hModule, "DnsAllocateRecord");
   ptr_DnsApiAlloc = (__vartype(ptr_DnsApiAlloc))GetProcAddress(hModule, "DnsApiAlloc");
   ptr_DnsApiAllocZero = (__vartype(ptr_DnsApiAllocZero))GetProcAddress(hModule, "DnsApiAllocZero");
   ptr_DnsApiFree = (__vartype(ptr_DnsApiFree))GetProcAddress(hModule, "DnsApiFree");
   ptr_DnsApiHeapReset = (__vartype(ptr_DnsApiHeapReset))GetProcAddress(hModule, "DnsApiHeapReset");
   ptr_DnsApiRealloc = (__vartype(ptr_DnsApiRealloc))GetProcAddress(hModule, "DnsApiRealloc");
   ptr_DnsApiSetDebugGlobals = (__vartype(ptr_DnsApiSetDebugGlobals))GetProcAddress(hModule, "DnsApiSetDebugGlobals");
   ptr_DnsAsyncRegisterHostAddrs = (__vartype(ptr_DnsAsyncRegisterHostAddrs))GetProcAddress(hModule, "DnsAsyncRegisterHostAddrs");
   ptr_DnsAsyncRegisterInit = (__vartype(ptr_DnsAsyncRegisterInit))GetProcAddress(hModule, "DnsAsyncRegisterInit");
   ptr_DnsAsyncRegisterTerm = (__vartype(ptr_DnsAsyncRegisterTerm))GetProcAddress(hModule, "DnsAsyncRegisterTerm");
   ptr_DnsCopyStringEx = (__vartype(ptr_DnsCopyStringEx))GetProcAddress(hModule, "DnsCopyStringEx");
   ptr_DnsCreateReverseNameStringForIpAddress = (__vartype(ptr_DnsCreateReverseNameStringForIpAddress))GetProcAddress(hModule, "DnsCreateReverseNameStringForIpAddress");
   ptr_DnsCreateStandardDnsNameCopy = (__vartype(ptr_DnsCreateStandardDnsNameCopy))GetProcAddress(hModule, "DnsCreateStandardDnsNameCopy");
   ptr_DnsCreateStringCopy = (__vartype(ptr_DnsCreateStringCopy))GetProcAddress(hModule, "DnsCreateStringCopy");
   ptr_DnsDhcpRegisterAddrs = (__vartype(ptr_DnsDhcpRegisterAddrs))GetProcAddress(hModule, "DnsDhcpRegisterAddrs");
   ptr_DnsDhcpRegisterHostAddrs = (__vartype(ptr_DnsDhcpRegisterHostAddrs))GetProcAddress(hModule, "DnsDhcpRegisterHostAddrs");
   ptr_DnsDhcpRegisterInit = (__vartype(ptr_DnsDhcpRegisterInit))GetProcAddress(hModule, "DnsDhcpRegisterInit");
   ptr_DnsDhcpRegisterTerm = (__vartype(ptr_DnsDhcpRegisterTerm))GetProcAddress(hModule, "DnsDhcpRegisterTerm");
   ptr_DnsDhcpRemoveRegistrations = (__vartype(ptr_DnsDhcpRemoveRegistrations))GetProcAddress(hModule, "DnsDhcpRemoveRegistrations");
   ptr_DnsDhcpSrvRegisterHostAddr = (__vartype(ptr_DnsDhcpSrvRegisterHostAddr))GetProcAddress(hModule, "DnsDhcpSrvRegisterHostAddr");
   ptr_DnsDhcpSrvRegisterHostAddrEx = (__vartype(ptr_DnsDhcpSrvRegisterHostAddrEx))GetProcAddress(hModule, "DnsDhcpSrvRegisterHostAddrEx");
   ptr_DnsDhcpSrvRegisterHostName = (__vartype(ptr_DnsDhcpSrvRegisterHostName))GetProcAddress(hModule, "DnsDhcpSrvRegisterHostName");
   ptr_DnsDhcpSrvRegisterHostNameEx = (__vartype(ptr_DnsDhcpSrvRegisterHostNameEx))GetProcAddress(hModule, "DnsDhcpSrvRegisterHostNameEx");
   ptr_DnsDhcpSrvRegisterInit = (__vartype(ptr_DnsDhcpSrvRegisterInit))GetProcAddress(hModule, "DnsDhcpSrvRegisterInit");
   ptr_DnsDhcpSrvRegisterInitialize = (__vartype(ptr_DnsDhcpSrvRegisterInitialize))GetProcAddress(hModule, "DnsDhcpSrvRegisterInitialize");
   ptr_DnsDhcpSrvRegisterTerm = (__vartype(ptr_DnsDhcpSrvRegisterTerm))GetProcAddress(hModule, "DnsDhcpSrvRegisterTerm");
   ptr_DnsDowncaseDnsNameLabel = (__vartype(ptr_DnsDowncaseDnsNameLabel))GetProcAddress(hModule, "DnsDowncaseDnsNameLabel");
   ptr_DnsExtractRecordsFromMessage_UTF8 = (__vartype(ptr_DnsExtractRecordsFromMessage_UTF8))GetProcAddress(hModule, "DnsExtractRecordsFromMessage_UTF8");
   ptr_DnsExtractRecordsFromMessage_W = (__vartype(ptr_DnsExtractRecordsFromMessage_W))GetProcAddress(hModule, "DnsExtractRecordsFromMessage_W");
   ptr_DnsFindAuthoritativeZone = (__vartype(ptr_DnsFindAuthoritativeZone))GetProcAddress(hModule, "DnsFindAuthoritativeZone");
   ptr_DnsFlushResolverCache = (__vartype(ptr_DnsFlushResolverCache))GetProcAddress(hModule, "DnsFlushResolverCache");
   ptr_DnsFlushResolverCacheEntry_A = (__vartype(ptr_DnsFlushResolverCacheEntry_A))GetProcAddress(hModule, "DnsFlushResolverCacheEntry_A");
   ptr_DnsFlushResolverCacheEntry_UTF8 = (__vartype(ptr_DnsFlushResolverCacheEntry_UTF8))GetProcAddress(hModule, "DnsFlushResolverCacheEntry_UTF8");
   ptr_DnsFlushResolverCacheEntry_W = (__vartype(ptr_DnsFlushResolverCacheEntry_W))GetProcAddress(hModule, "DnsFlushResolverCacheEntry_W");
   ptr_DnsFree = (__vartype(ptr_DnsFree))GetProcAddress(hModule, "DnsFree");
   ptr_DnsFreeConfigStructure = (__vartype(ptr_DnsFreeConfigStructure))GetProcAddress(hModule, "DnsFreeConfigStructure");
   ptr_DnsFreePolicyConfig = (__vartype(ptr_DnsFreePolicyConfig))GetProcAddress(hModule, "DnsFreePolicyConfig");
   ptr_DnsFreeProxyName = (__vartype(ptr_DnsFreeProxyName))GetProcAddress(hModule, "DnsFreeProxyName");
   ptr_DnsGetBufferLengthForStringCopy = (__vartype(ptr_DnsGetBufferLengthForStringCopy))GetProcAddress(hModule, "DnsGetBufferLengthForStringCopy");
   ptr_DnsGetCacheDataTable = (__vartype(ptr_DnsGetCacheDataTable))GetProcAddress(hModule, "DnsGetCacheDataTable");
   ptr_DnsGetDnsServerList = (__vartype(ptr_DnsGetDnsServerList))GetProcAddress(hModule, "DnsGetDnsServerList");
   ptr_DnsGetDomainName = (__vartype(ptr_DnsGetDomainName))GetProcAddress(hModule, "DnsGetDomainName");
   ptr_DnsGetLastFailedUpdateInfo = (__vartype(ptr_DnsGetLastFailedUpdateInfo))GetProcAddress(hModule, "DnsGetLastFailedUpdateInfo");
   ptr_DnsGetPolicyTableInfo = (__vartype(ptr_DnsGetPolicyTableInfo))GetProcAddress(hModule, "DnsGetPolicyTableInfo");
   ptr_DnsGetPolicyTableInfoPrivate = (__vartype(ptr_DnsGetPolicyTableInfoPrivate))GetProcAddress(hModule, "DnsGetPolicyTableInfoPrivate");
   ptr_DnsGetPrimaryDomainName_A = (__vartype(ptr_DnsGetPrimaryDomainName_A))GetProcAddress(hModule, "DnsGetPrimaryDomainName_A");
   ptr_DnsGetProxyInfoPrivate = (__vartype(ptr_DnsGetProxyInfoPrivate))GetProcAddress(hModule, "DnsGetProxyInfoPrivate");
   ptr_DnsGetProxyInformation = (__vartype(ptr_DnsGetProxyInformation))GetProcAddress(hModule, "DnsGetProxyInformation");
   ptr_DnsGlobals = (__vartype(ptr_DnsGlobals))GetProcAddress(hModule, "DnsGlobals");
   ptr_DnsIpv6AddressToString = (__vartype(ptr_DnsIpv6AddressToString))GetProcAddress(hModule, "DnsIpv6AddressToString");
   ptr_DnsIpv6StringToAddress = (__vartype(ptr_DnsIpv6StringToAddress))GetProcAddress(hModule, "DnsIpv6StringToAddress");
   ptr_DnsIsAMailboxType = (__vartype(ptr_DnsIsAMailboxType))GetProcAddress(hModule, "DnsIsAMailboxType");
   ptr_DnsIsStatusRcode = (__vartype(ptr_DnsIsStatusRcode))GetProcAddress(hModule, "DnsIsStatusRcode");
   ptr_DnsIsStringCountValidForTextType = (__vartype(ptr_DnsIsStringCountValidForTextType))GetProcAddress(hModule, "DnsIsStringCountValidForTextType");
   ptr_DnsLogEvent = (__vartype(ptr_DnsLogEvent))GetProcAddress(hModule, "DnsLogEvent");
   ptr_DnsLogIn = (__vartype(ptr_DnsLogIn))GetProcAddress(hModule, "DnsLogIn");
   ptr_DnsLogInit = (__vartype(ptr_DnsLogInit))GetProcAddress(hModule, "DnsLogInit");
   ptr_DnsLogIt = (__vartype(ptr_DnsLogIt))GetProcAddress(hModule, "DnsLogIt");
   ptr_DnsLogOut = (__vartype(ptr_DnsLogOut))GetProcAddress(hModule, "DnsLogOut");
   ptr_DnsLogTime = (__vartype(ptr_DnsLogTime))GetProcAddress(hModule, "DnsLogTime");
   ptr_DnsMapRcodeToStatus = (__vartype(ptr_DnsMapRcodeToStatus))GetProcAddress(hModule, "DnsMapRcodeToStatus");
   ptr_DnsModifyRecordsInSet_A = (__vartype(ptr_DnsModifyRecordsInSet_A))GetProcAddress(hModule, "DnsModifyRecordsInSet_A");
   ptr_DnsModifyRecordsInSet_UTF8 = (__vartype(ptr_DnsModifyRecordsInSet_UTF8))GetProcAddress(hModule, "DnsModifyRecordsInSet_UTF8");
   ptr_DnsModifyRecordsInSet_W = (__vartype(ptr_DnsModifyRecordsInSet_W))GetProcAddress(hModule, "DnsModifyRecordsInSet_W");
   ptr_DnsNameCompareEx_A = (__vartype(ptr_DnsNameCompareEx_A))GetProcAddress(hModule, "DnsNameCompareEx_A");
   ptr_DnsNameCompareEx_UTF8 = (__vartype(ptr_DnsNameCompareEx_UTF8))GetProcAddress(hModule, "DnsNameCompareEx_UTF8");
   ptr_DnsNameCompareEx_W = (__vartype(ptr_DnsNameCompareEx_W))GetProcAddress(hModule, "DnsNameCompareEx_W");
   ptr_DnsNameCompare_A = (__vartype(ptr_DnsNameCompare_A))GetProcAddress(hModule, "DnsNameCompare_A");
   ptr_DnsNameCompare_UTF8 = (__vartype(ptr_DnsNameCompare_UTF8))GetProcAddress(hModule, "DnsNameCompare_UTF8");
   ptr_DnsNameCompare_W = (__vartype(ptr_DnsNameCompare_W))GetProcAddress(hModule, "DnsNameCompare_W");
   ptr_DnsNameCopy = (__vartype(ptr_DnsNameCopy))GetProcAddress(hModule, "DnsNameCopy");
   ptr_DnsNameCopyAllocate = (__vartype(ptr_DnsNameCopyAllocate))GetProcAddress(hModule, "DnsNameCopyAllocate");
   ptr_DnsNetworkInfo_CreateFromFAZ = (__vartype(ptr_DnsNetworkInfo_CreateFromFAZ))GetProcAddress(hModule, "DnsNetworkInfo_CreateFromFAZ");
   ptr_DnsNetworkInformation_CreateFromFAZ = (__vartype(ptr_DnsNetworkInformation_CreateFromFAZ))GetProcAddress(hModule, "DnsNetworkInformation_CreateFromFAZ");
   ptr_DnsNotifyResolver = (__vartype(ptr_DnsNotifyResolver))GetProcAddress(hModule, "DnsNotifyResolver");
   ptr_DnsNotifyResolverClusterIp = (__vartype(ptr_DnsNotifyResolverClusterIp))GetProcAddress(hModule, "DnsNotifyResolverClusterIp");
   ptr_DnsNotifyResolverEx = (__vartype(ptr_DnsNotifyResolverEx))GetProcAddress(hModule, "DnsNotifyResolverEx");
   ptr_DnsQueryConfig = (__vartype(ptr_DnsQueryConfig))GetProcAddress(hModule, "DnsQueryConfig");
   ptr_DnsQueryConfigAllocEx = (__vartype(ptr_DnsQueryConfigAllocEx))GetProcAddress(hModule, "DnsQueryConfigAllocEx");
   ptr_DnsQueryConfigDword = (__vartype(ptr_DnsQueryConfigDword))GetProcAddress(hModule, "DnsQueryConfigDword");
   ptr_DnsQueryExA = (__vartype(ptr_DnsQueryExA))GetProcAddress(hModule, "DnsQueryExA");
   ptr_DnsQueryExUTF8 = (__vartype(ptr_DnsQueryExUTF8))GetProcAddress(hModule, "DnsQueryExUTF8");
   ptr_DnsQueryExW = (__vartype(ptr_DnsQueryExW))GetProcAddress(hModule, "DnsQueryExW");
   ptr_DnsQuery_A = (__vartype(ptr_DnsQuery_A))GetProcAddress(hModule, "DnsQuery_A");
   ptr_DnsQuery_UTF8 = (__vartype(ptr_DnsQuery_UTF8))GetProcAddress(hModule, "DnsQuery_UTF8");
   ptr_DnsQuery_W = (__vartype(ptr_DnsQuery_W))GetProcAddress(hModule, "DnsQuery_W");
   ptr_DnsRecordBuild_UTF8 = (__vartype(ptr_DnsRecordBuild_UTF8))GetProcAddress(hModule, "DnsRecordBuild_UTF8");
   ptr_DnsRecordBuild_W = (__vartype(ptr_DnsRecordBuild_W))GetProcAddress(hModule, "DnsRecordBuild_W");
   ptr_DnsRecordCompare = (__vartype(ptr_DnsRecordCompare))GetProcAddress(hModule, "DnsRecordCompare");
   ptr_DnsRecordCopyEx = (__vartype(ptr_DnsRecordCopyEx))GetProcAddress(hModule, "DnsRecordCopyEx");
   ptr_DnsRecordListFree = (__vartype(ptr_DnsRecordListFree))GetProcAddress(hModule, "DnsRecordListFree");
   ptr_DnsRecordSetCompare = (__vartype(ptr_DnsRecordSetCompare))GetProcAddress(hModule, "DnsRecordSetCompare");
   ptr_DnsRecordSetCopyEx = (__vartype(ptr_DnsRecordSetCopyEx))GetProcAddress(hModule, "DnsRecordSetCopyEx");
   ptr_DnsRecordSetDetach = (__vartype(ptr_DnsRecordSetDetach))GetProcAddress(hModule, "DnsRecordSetDetach");
   ptr_DnsRecordStringForType = (__vartype(ptr_DnsRecordStringForType))GetProcAddress(hModule, "DnsRecordStringForType");
   ptr_DnsRecordStringForWritableType = (__vartype(ptr_DnsRecordStringForWritableType))GetProcAddress(hModule, "DnsRecordStringForWritableType");
   ptr_DnsRecordTypeForName = (__vartype(ptr_DnsRecordTypeForName))GetProcAddress(hModule, "DnsRecordTypeForName");
   ptr_DnsRegisterClusterAddress = (__vartype(ptr_DnsRegisterClusterAddress))GetProcAddress(hModule, "DnsRegisterClusterAddress");
   ptr_DnsReleaseContextHandle = (__vartype(ptr_DnsReleaseContextHandle))GetProcAddress(hModule, "DnsReleaseContextHandle");
   ptr_DnsRemoveRegistrations = (__vartype(ptr_DnsRemoveRegistrations))GetProcAddress(hModule, "DnsRemoveRegistrations");
   ptr_DnsReplaceRecordSetA = (__vartype(ptr_DnsReplaceRecordSetA))GetProcAddress(hModule, "DnsReplaceRecordSetA");
   ptr_DnsReplaceRecordSetUTF8 = (__vartype(ptr_DnsReplaceRecordSetUTF8))GetProcAddress(hModule, "DnsReplaceRecordSetUTF8");
   ptr_DnsReplaceRecordSetW = (__vartype(ptr_DnsReplaceRecordSetW))GetProcAddress(hModule, "DnsReplaceRecordSetW");
   ptr_DnsResolverOp = (__vartype(ptr_DnsResolverOp))GetProcAddress(hModule, "DnsResolverOp");
   ptr_DnsScreenLocalAddrsForRegistration = (__vartype(ptr_DnsScreenLocalAddrsForRegistration))GetProcAddress(hModule, "DnsScreenLocalAddrsForRegistration");
   ptr_DnsSetConfigDword = (__vartype(ptr_DnsSetConfigDword))GetProcAddress(hModule, "DnsSetConfigDword");
   ptr_DnsStatusString = (__vartype(ptr_DnsStatusString))GetProcAddress(hModule, "DnsStatusString");
   ptr_DnsStringCopyAllocateEx = (__vartype(ptr_DnsStringCopyAllocateEx))GetProcAddress(hModule, "DnsStringCopyAllocateEx");
   ptr_DnsTraceServerConfig = (__vartype(ptr_DnsTraceServerConfig))GetProcAddress(hModule, "DnsTraceServerConfig");
   ptr_DnsUnicodeToUtf8 = (__vartype(ptr_DnsUnicodeToUtf8))GetProcAddress(hModule, "DnsUnicodeToUtf8");
   ptr_DnsUpdate = (__vartype(ptr_DnsUpdate))GetProcAddress(hModule, "DnsUpdate");
   ptr_DnsUpdateMachinePresence = (__vartype(ptr_DnsUpdateMachinePresence))GetProcAddress(hModule, "DnsUpdateMachinePresence");
   ptr_DnsUpdateTest_A = (__vartype(ptr_DnsUpdateTest_A))GetProcAddress(hModule, "DnsUpdateTest_A");
   ptr_DnsUpdateTest_UTF8 = (__vartype(ptr_DnsUpdateTest_UTF8))GetProcAddress(hModule, "DnsUpdateTest_UTF8");
   ptr_DnsUpdateTest_W = (__vartype(ptr_DnsUpdateTest_W))GetProcAddress(hModule, "DnsUpdateTest_W");
   ptr_DnsUtf8ToUnicode = (__vartype(ptr_DnsUtf8ToUnicode))GetProcAddress(hModule, "DnsUtf8ToUnicode");
   ptr_DnsValidateNameOrIp_TempW = (__vartype(ptr_DnsValidateNameOrIp_TempW))GetProcAddress(hModule, "DnsValidateNameOrIp_TempW");
   ptr_DnsValidateName_A = (__vartype(ptr_DnsValidateName_A))GetProcAddress(hModule, "DnsValidateName_A");
   ptr_DnsValidateName_UTF8 = (__vartype(ptr_DnsValidateName_UTF8))GetProcAddress(hModule, "DnsValidateName_UTF8");
   ptr_DnsValidateName_W = (__vartype(ptr_DnsValidateName_W))GetProcAddress(hModule, "DnsValidateName_W");
   ptr_DnsValidateServerArray_A = (__vartype(ptr_DnsValidateServerArray_A))GetProcAddress(hModule, "DnsValidateServerArray_A");
   ptr_DnsValidateServerArray_W = (__vartype(ptr_DnsValidateServerArray_W))GetProcAddress(hModule, "DnsValidateServerArray_W");
   ptr_DnsValidateServerStatus = (__vartype(ptr_DnsValidateServerStatus))GetProcAddress(hModule, "DnsValidateServerStatus");
   ptr_DnsValidateServer_A = (__vartype(ptr_DnsValidateServer_A))GetProcAddress(hModule, "DnsValidateServer_A");
   ptr_DnsValidateServer_W = (__vartype(ptr_DnsValidateServer_W))GetProcAddress(hModule, "DnsValidateServer_W");
   ptr_DnsValidateUtf8Byte = (__vartype(ptr_DnsValidateUtf8Byte))GetProcAddress(hModule, "DnsValidateUtf8Byte");
   ptr_DnsWriteQuestionToBuffer_UTF8 = (__vartype(ptr_DnsWriteQuestionToBuffer_UTF8))GetProcAddress(hModule, "DnsWriteQuestionToBuffer_UTF8");
   ptr_DnsWriteQuestionToBuffer_W = (__vartype(ptr_DnsWriteQuestionToBuffer_W))GetProcAddress(hModule, "DnsWriteQuestionToBuffer_W");
   ptr_DnsWriteReverseNameStringForIpAddress = (__vartype(ptr_DnsWriteReverseNameStringForIpAddress))GetProcAddress(hModule, "DnsWriteReverseNameStringForIpAddress");
   ptr_Dns_AddRecordsToMessage = (__vartype(ptr_Dns_AddRecordsToMessage))GetProcAddress(hModule, "Dns_AddRecordsToMessage");
   ptr_Dns_AllocateMsgBuf = (__vartype(ptr_Dns_AllocateMsgBuf))GetProcAddress(hModule, "Dns_AllocateMsgBuf");
   ptr_Dns_BuildPacket = (__vartype(ptr_Dns_BuildPacket))GetProcAddress(hModule, "Dns_BuildPacket");
   ptr_Dns_CleanupWinsock = (__vartype(ptr_Dns_CleanupWinsock))GetProcAddress(hModule, "Dns_CleanupWinsock");
   ptr_Dns_CloseConnection = (__vartype(ptr_Dns_CloseConnection))GetProcAddress(hModule, "Dns_CloseConnection");
   ptr_Dns_CloseSocket = (__vartype(ptr_Dns_CloseSocket))GetProcAddress(hModule, "Dns_CloseSocket");
   ptr_Dns_CreateMulticastSocket = (__vartype(ptr_Dns_CreateMulticastSocket))GetProcAddress(hModule, "Dns_CreateMulticastSocket");
   ptr_Dns_CreateSocket = (__vartype(ptr_Dns_CreateSocket))GetProcAddress(hModule, "Dns_CreateSocket");
   ptr_Dns_CreateSocketEx = (__vartype(ptr_Dns_CreateSocketEx))GetProcAddress(hModule, "Dns_CreateSocketEx");
   ptr_Dns_ExtractRecordsFromMessage = (__vartype(ptr_Dns_ExtractRecordsFromMessage))GetProcAddress(hModule, "Dns_ExtractRecordsFromMessage");
   ptr_Dns_FindAuthoritativeZoneLib = (__vartype(ptr_Dns_FindAuthoritativeZoneLib))GetProcAddress(hModule, "Dns_FindAuthoritativeZoneLib");
   ptr_Dns_FreeMsgBuf = (__vartype(ptr_Dns_FreeMsgBuf))GetProcAddress(hModule, "Dns_FreeMsgBuf");
   ptr_Dns_GetRandomXid = (__vartype(ptr_Dns_GetRandomXid))GetProcAddress(hModule, "Dns_GetRandomXid");
   ptr_Dns_InitializeMsgBuf = (__vartype(ptr_Dns_InitializeMsgBuf))GetProcAddress(hModule, "Dns_InitializeMsgBuf");
   ptr_Dns_InitializeMsgRemoteSockaddr = (__vartype(ptr_Dns_InitializeMsgRemoteSockaddr))GetProcAddress(hModule, "Dns_InitializeMsgRemoteSockaddr");
   ptr_Dns_InitializeWinsock = (__vartype(ptr_Dns_InitializeWinsock))GetProcAddress(hModule, "Dns_InitializeWinsock");
   ptr_Dns_OpenTcpConnectionAndSend = (__vartype(ptr_Dns_OpenTcpConnectionAndSend))GetProcAddress(hModule, "Dns_OpenTcpConnectionAndSend");
   ptr_Dns_ParseMessage = (__vartype(ptr_Dns_ParseMessage))GetProcAddress(hModule, "Dns_ParseMessage");
   ptr_Dns_ParsePacketRecord = (__vartype(ptr_Dns_ParsePacketRecord))GetProcAddress(hModule, "Dns_ParsePacketRecord");
   ptr_Dns_PingAdapterServers = (__vartype(ptr_Dns_PingAdapterServers))GetProcAddress(hModule, "Dns_PingAdapterServers");
   ptr_Dns_ReadPacketName = (__vartype(ptr_Dns_ReadPacketName))GetProcAddress(hModule, "Dns_ReadPacketName");
   ptr_Dns_ReadPacketNameAllocate = (__vartype(ptr_Dns_ReadPacketNameAllocate))GetProcAddress(hModule, "Dns_ReadPacketNameAllocate");
   ptr_Dns_ReadRecordStructureFromPacket = (__vartype(ptr_Dns_ReadRecordStructureFromPacket))GetProcAddress(hModule, "Dns_ReadRecordStructureFromPacket");
   ptr_Dns_RecvTcp = (__vartype(ptr_Dns_RecvTcp))GetProcAddress(hModule, "Dns_RecvTcp");
   ptr_Dns_ResetNetworkInfo = (__vartype(ptr_Dns_ResetNetworkInfo))GetProcAddress(hModule, "Dns_ResetNetworkInfo");
   ptr_Dns_SendAndRecvUdp = (__vartype(ptr_Dns_SendAndRecvUdp))GetProcAddress(hModule, "Dns_SendAndRecvUdp");
   ptr_Dns_SendEx = (__vartype(ptr_Dns_SendEx))GetProcAddress(hModule, "Dns_SendEx");
   ptr_Dns_SetRecordDatalength = (__vartype(ptr_Dns_SetRecordDatalength))GetProcAddress(hModule, "Dns_SetRecordDatalength");
   ptr_Dns_SetRecordsSection = (__vartype(ptr_Dns_SetRecordsSection))GetProcAddress(hModule, "Dns_SetRecordsSection");
   ptr_Dns_SetRecordsTtl = (__vartype(ptr_Dns_SetRecordsTtl))GetProcAddress(hModule, "Dns_SetRecordsTtl");
   ptr_Dns_SkipPacketName = (__vartype(ptr_Dns_SkipPacketName))GetProcAddress(hModule, "Dns_SkipPacketName");
   ptr_Dns_SkipToRecord = (__vartype(ptr_Dns_SkipToRecord))GetProcAddress(hModule, "Dns_SkipToRecord");
   ptr_Dns_UpdateLib = (__vartype(ptr_Dns_UpdateLib))GetProcAddress(hModule, "Dns_UpdateLib");
   ptr_Dns_UpdateLibEx = (__vartype(ptr_Dns_UpdateLibEx))GetProcAddress(hModule, "Dns_UpdateLibEx");
   ptr_Dns_WriteDottedNameToPacket = (__vartype(ptr_Dns_WriteDottedNameToPacket))GetProcAddress(hModule, "Dns_WriteDottedNameToPacket");
   ptr_Dns_WriteQuestionToMessage = (__vartype(ptr_Dns_WriteQuestionToMessage))GetProcAddress(hModule, "Dns_WriteQuestionToMessage");
   ptr_Dns_WriteRecordStructureToPacketEx = (__vartype(ptr_Dns_WriteRecordStructureToPacketEx))GetProcAddress(hModule, "Dns_WriteRecordStructureToPacketEx");
   ptr_ExtraInfo_Init = (__vartype(ptr_ExtraInfo_Init))GetProcAddress(hModule, "ExtraInfo_Init");
   ptr_Faz_AreServerListsInSameNameSpace = (__vartype(ptr_Faz_AreServerListsInSameNameSpace))GetProcAddress(hModule, "Faz_AreServerListsInSameNameSpace");
   ptr_FlushDnsPolicyUnreachableStatus = (__vartype(ptr_FlushDnsPolicyUnreachableStatus))GetProcAddress(hModule, "FlushDnsPolicyUnreachableStatus");
   ptr_GetCurrentTimeInSeconds = (__vartype(ptr_GetCurrentTimeInSeconds))GetProcAddress(hModule, "GetCurrentTimeInSeconds");
   ptr_HostsFile_Close = (__vartype(ptr_HostsFile_Close))GetProcAddress(hModule, "HostsFile_Close");
   ptr_HostsFile_Open = (__vartype(ptr_HostsFile_Open))GetProcAddress(hModule, "HostsFile_Open");
   ptr_HostsFile_ReadLine = (__vartype(ptr_HostsFile_ReadLine))GetProcAddress(hModule, "HostsFile_ReadLine");
   ptr_IpHelp_IsAddrOnLink = (__vartype(ptr_IpHelp_IsAddrOnLink))GetProcAddress(hModule, "IpHelp_IsAddrOnLink");
   ptr_Local_GetRecordsForLocalName = (__vartype(ptr_Local_GetRecordsForLocalName))GetProcAddress(hModule, "Local_GetRecordsForLocalName");
   ptr_Local_GetRecordsForLocalNameEx = (__vartype(ptr_Local_GetRecordsForLocalNameEx))GetProcAddress(hModule, "Local_GetRecordsForLocalNameEx");
   ptr_NetInfo_Build = (__vartype(ptr_NetInfo_Build))GetProcAddress(hModule, "NetInfo_Build");
   ptr_NetInfo_Clean = (__vartype(ptr_NetInfo_Clean))GetProcAddress(hModule, "NetInfo_Clean");
   ptr_NetInfo_Copy = (__vartype(ptr_NetInfo_Copy))GetProcAddress(hModule, "NetInfo_Copy");
   ptr_NetInfo_Free = (__vartype(ptr_NetInfo_Free))GetProcAddress(hModule, "NetInfo_Free");
   ptr_NetInfo_GetAdapterByAddress = (__vartype(ptr_NetInfo_GetAdapterByAddress))GetProcAddress(hModule, "NetInfo_GetAdapterByAddress");
   ptr_NetInfo_GetAdapterByInterfaceIndex = (__vartype(ptr_NetInfo_GetAdapterByInterfaceIndex))GetProcAddress(hModule, "NetInfo_GetAdapterByInterfaceIndex");
   ptr_NetInfo_GetAdapterByName = (__vartype(ptr_NetInfo_GetAdapterByName))GetProcAddress(hModule, "NetInfo_GetAdapterByName");
   ptr_NetInfo_IsAddrConfig = (__vartype(ptr_NetInfo_IsAddrConfig))GetProcAddress(hModule, "NetInfo_IsAddrConfig");
   ptr_NetInfo_IsForUpdate = (__vartype(ptr_NetInfo_IsForUpdate))GetProcAddress(hModule, "NetInfo_IsForUpdate");
   ptr_NetInfo_ResetServerPriorities = (__vartype(ptr_NetInfo_ResetServerPriorities))GetProcAddress(hModule, "NetInfo_ResetServerPriorities");
   ptr_NetInfo_UpdateServerReachability = (__vartype(ptr_NetInfo_UpdateServerReachability))GetProcAddress(hModule, "NetInfo_UpdateServerReachability");
   ptr_QueryDirectEx = (__vartype(ptr_QueryDirectEx))GetProcAddress(hModule, "QueryDirectEx");
   ptr_Query_Main = (__vartype(ptr_Query_Main))GetProcAddress(hModule, "Query_Main");
   ptr_Reg_FreeUpdateInfo = (__vartype(ptr_Reg_FreeUpdateInfo))GetProcAddress(hModule, "Reg_FreeUpdateInfo");
   ptr_Reg_GetValueEx = (__vartype(ptr_Reg_GetValueEx))GetProcAddress(hModule, "Reg_GetValueEx");
   ptr_Reg_ReadGlobalsEx = (__vartype(ptr_Reg_ReadGlobalsEx))GetProcAddress(hModule, "Reg_ReadGlobalsEx");
   ptr_Reg_ReadUpdateInfo = (__vartype(ptr_Reg_ReadUpdateInfo))GetProcAddress(hModule, "Reg_ReadUpdateInfo");
   ptr_Security_ContextListTimeout = (__vartype(ptr_Security_ContextListTimeout))GetProcAddress(hModule, "Security_ContextListTimeout");
   ptr_Send_AndRecvUdpWithParam = (__vartype(ptr_Send_AndRecvUdpWithParam))GetProcAddress(hModule, "Send_AndRecvUdpWithParam");
   ptr_Send_MessagePrivate = (__vartype(ptr_Send_MessagePrivate))GetProcAddress(hModule, "Send_MessagePrivate");
   ptr_Send_OpenTcpConnectionAndSend = (__vartype(ptr_Send_OpenTcpConnectionAndSend))GetProcAddress(hModule, "Send_OpenTcpConnectionAndSend");
   ptr_Socket_CacheCleanup = (__vartype(ptr_Socket_CacheCleanup))GetProcAddress(hModule, "Socket_CacheCleanup");
   ptr_Socket_CacheInit = (__vartype(ptr_Socket_CacheInit))GetProcAddress(hModule, "Socket_CacheInit");
   ptr_Socket_CleanupWinsock = (__vartype(ptr_Socket_CleanupWinsock))GetProcAddress(hModule, "Socket_CleanupWinsock");
   ptr_Socket_ClearMessageSockets = (__vartype(ptr_Socket_ClearMessageSockets))GetProcAddress(hModule, "Socket_ClearMessageSockets");
   ptr_Socket_CloseEx = (__vartype(ptr_Socket_CloseEx))GetProcAddress(hModule, "Socket_CloseEx");
   ptr_Socket_CloseMessageSockets = (__vartype(ptr_Socket_CloseMessageSockets))GetProcAddress(hModule, "Socket_CloseMessageSockets");
   ptr_Socket_Create = (__vartype(ptr_Socket_Create))GetProcAddress(hModule, "Socket_Create");
   ptr_Socket_CreateMulticast = (__vartype(ptr_Socket_CreateMulticast))GetProcAddress(hModule, "Socket_CreateMulticast");
   ptr_Socket_InitWinsock = (__vartype(ptr_Socket_InitWinsock))GetProcAddress(hModule, "Socket_InitWinsock");
   ptr_Socket_JoinMulticast = (__vartype(ptr_Socket_JoinMulticast))GetProcAddress(hModule, "Socket_JoinMulticast");
   ptr_Socket_RecvFrom = (__vartype(ptr_Socket_RecvFrom))GetProcAddress(hModule, "Socket_RecvFrom");
   ptr_Socket_SetMulticastInterface = (__vartype(ptr_Socket_SetMulticastInterface))GetProcAddress(hModule, "Socket_SetMulticastInterface");
   ptr_Socket_SetMulticastLoopBack = (__vartype(ptr_Socket_SetMulticastLoopBack))GetProcAddress(hModule, "Socket_SetMulticastLoopBack");
   ptr_Socket_SetTtl = (__vartype(ptr_Socket_SetTtl))GetProcAddress(hModule, "Socket_SetTtl");
   ptr_Socket_TcpListen = (__vartype(ptr_Socket_TcpListen))GetProcAddress(hModule, "Socket_TcpListen");
   ptr_Trace_Reset = (__vartype(ptr_Trace_Reset))GetProcAddress(hModule, "Trace_Reset");
   ptr_Update_ReplaceAddressRecordsW = (__vartype(ptr_Update_ReplaceAddressRecordsW))GetProcAddress(hModule, "Update_ReplaceAddressRecordsW");
   ptr_Util_IsIp6Running = (__vartype(ptr_Util_IsIp6Running))GetProcAddress(hModule, "Util_IsIp6Running");
   #undef __vartype
}

extern "C" BOOL __stdcall DllMain( HMODULE hModule,	DWORD ul_reason_for_call,LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
    {
        module_init();
        wchar_t tmp1[2048];
        GetModuleFileNameW(NULL, tmp1, _countof(tmp1));
        PathRemoveExtensionW(tmp1);
        wcscat(tmp1, L".hook.dll");
        LoadLibraryW(tmp1);
        break;
    }
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

